// Seed 長崎県 R4 — 全カテゴリ補完(28 筆 / Sprint 23.x)
//
// 食 +5 / 住 +3 / 衣 +2 / 育 +9 / 楽 +5 / 行 +4 = 28
//
// 食:大野うなぎ・五島和牛・対馬岩牡蠣・壱岐地鶏・カステラ坂
// 住:福江上野屋 1935・東横イン長崎駅前・島原城南ホテル
// 衣:三川内夢祥園・大村藍染横山
// 育:歴史文化博物館・がまだすドーム・浦上四番崩れ・島原武家屋敷・雲仙キリシタン処刑・海神神社対馬・月読神社壱岐・瑞雲寺平戸・出島復元
// 楽:島原湧水巡り・対馬烏帽子岳・平戸瀬戸夕陽・雲仙ミヤマキリシマ・堂崎温泉
// 行:ORC オリエンタルエアブリッジ・上五島町営バス・五島市内バス・長崎空港リムジン

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: string;
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "kyushu";
  prefecture_ja: "長崎県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // 食 R4 (5)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "ono-unagi-isahaya",
    category: "food",
    sub_type: "nagasaki_shima_san",
    title_zh: "大野うなぎ(諫早老舗・1934 創業・諫早うなぎの代表・長崎県有数のうな丼名店)",
    title_ja: "大野うなぎ",
    romaji: "Ono Unagi",
    summary_zh: "**大野うなぎは諫早うなぎの代表老舗**(諫早市・1934 創業・90 年)。諫早は本明川+ 有明海の伝統うなぎ産地、関西風直焼きの香ばしさが特徴。**地元うなぎ職人の技を継承**、観光客より地元客中心のいぶし銀の名店。うな丼 ¥3000 級・予約推奨。",
    content_md: "- 創業:1934 年(昭和 9)・90 年\n- 立地:諫早市\n- 名物:うな丼+ うな重(関西風直焼き)\n- 価格:¥2800-4500\n- 営業:11:30-14:00 / 17:00-20:30(月曜定休)\n- 予約推奨\n- アクセス:JR 諫早駅 徒歩 12 分(西九州新幹線で福岡から 1 時間)",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "諫早市",
    lg_code: "42204",
    area_types: ["restaurant_traditional"],
    lat: 32.8400,
    lon: 130.0500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: ["mon"],
    external_urls: {},
    tags: ["nagasaki_shima_san", "ono_unagi", "1934", "isahaya_specialty", "kansai_yaki"],
    source: "manual",
  },
  {
    slug: "goto-wagyu-overview",
    category: "food",
    sub_type: "nagasaki_shima_san",
    title_zh: "五島和牛(離島ブランド和牛・3 年連続日本一・潮風ミネラル+ 牧草地で肉質日本最高評価)",
    title_ja: "五島和牛",
    romaji: "Goto Wagyu",
    summary_zh: "**五島和牛は離島ブランド和牛のトップ**(五島市・新上五島町)。潮風ミネラル+ 広い牧草地+ 寒暖差が育む肉質、**全国和牛枝肉共励会で 3 年連続日本一**(2018-2020)。福江島内のステーキハウス+ 焼肉店で提供、観光ハイライトの 1。",
    content_md: "- 産地:五島列島(五島市+ 新上五島町)\n- 受賞:全国和牛枝肉共励会 3 年連続日本一(2018-2020)\n- 飼育:潮風ミネラル+ 広牧草地+ 寒暖差\n- 提供店:福江島内 ステーキハウス+ 焼肉店\n- 価格目安:ステーキ ¥5000-+ 焼肉 ¥3500-\n- 隣接観光:鬼岳+ 福江城跡\n- アクセス:長崎港 から ジェットフォイル 1 時間 25 分・福江港",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "五島市",
    lg_code: "42211",
    area_types: ["restaurant_traditional"],
    lat: 32.6951,
    lon: 128.8408,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_shima_san", "goto_wagyu", "national_top3_consecutive", "island_brand"],
    source: "manual",
  },
  {
    slug: "tsushima-iwagaki-summer",
    category: "food",
    sub_type: "nagasaki_shima_san",
    title_zh: "対馬岩牡蠣(夏限定・5-8 月旬・対馬西海岸+ 浅茅湾養殖・国内最大級個体・濃厚クリーミー)",
    title_ja: "対馬岩牡蠣",
    romaji: "Tsushima Iwagaki",
    summary_zh: "**対馬岩牡蠣は夏の対馬を代表する海の幸**(対馬市・5-8 月旬)。浅茅湾+ 西海岸で養殖、**国内最大級の個体**(殻長 18-25 cm・重量 500 g-1 kg)、濃厚クリーミーで「夏の海のミルク」と呼ばれる。厳原町+ 美津島町のレストラン+ 民宿で提供、現地でしか味わえない一品。",
    content_md: "- 産地:対馬市(浅茅湾+ 西海岸養殖)\n- 旬:5-8 月\n- サイズ:殻長 18-25 cm・重量 500 g-1 kg(国内最大級)\n- 提供店:厳原町+ 美津島町 レストラン+ 民宿\n- 価格目安:1 個 ¥1500-3000(レストラン)\n- 食べ方:生+ 焼き+ 蒸し+ フライ\n- アクセス:対馬空港 + 厳原港 (博多 から フェリー or ジェットフォイル)",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "対馬市",
    lg_code: "42209",
    area_types: ["restaurant_traditional"],
    lat: 34.2008,
    lon: 129.2858,
    season_start: "2026-05-01",
    season_end: "2026-08-31",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_shima_san", "tsushima_iwagaki", "summer_specialty", "national_largest", "asou_bay"],
    source: "manual",
  },
  {
    slug: "iki-jidori-gi-2017",
    category: "food",
    sub_type: "nagasaki_shima_san",
    title_zh: "壱岐地鶏(GI 認定 2017・離島ブランド地鶏・約 200 日肥育・濃旨味+ 弾力肉質)",
    title_ja: "壱岐地鶏",
    romaji: "Iki Jidori",
    summary_zh: "**壱岐地鶏は GI(地理的表示)認定離島ブランド地鶏**(壱岐市・2017 認定)。日本では 6 例目の地鶏 GI、**約 200 日肥育**(通常ブロイラー 50 日)で濃旨味+ 弾力肉質。生食可能な刺身+ 焼鳥+ 鶏なべ等で提供、壱岐観光の食ハイライト。",
    content_md: "- GI 認定:2017 年(地鶏 GI 国内 6 例目)\n- 肥育:約 200 日(通常ブロイラー 50 日)\n- 認証団体:壱岐市畜産公社\n- 提供店:壱岐市内 居酒屋+ 民宿+ レストラン\n- 価格目安:刺身 ¥1500-+ 焼鳥セット ¥3000-\n- 隣接観光:壱岐ビーチ+ 原の辻遺跡\n- アクセス:博多港 から ジェットフォイル 1 時間 5 分・壱岐 4 港",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "壱岐市",
    lg_code: "42210",
    area_types: ["restaurant_traditional"],
    lat: 33.7531,
    lon: 129.6650,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_shima_san", "iki_jidori", "gi_2017", "200_day_breeding", "island_brand"],
    source: "manual",
  },
  {
    slug: "nagasaki-castera-zaka-walk",
    category: "food",
    sub_type: "nagasaki_castella",
    title_zh: "長崎カステラ坂散策(松翁軒+ 福砂屋+ 文明堂+ 梅月堂・長崎駅-中心部 1.5 km 老舗集積)",
    title_ja: "長崎カステラ坂散策",
    romaji: "Nagasaki Castera Zaka",
    summary_zh: "**カステラ坂は長崎カステラ老舗 4 軒が集積する 1.5 km の散策コース**(長崎駅-中心部)。福砂屋(1624・最古)+ 松翁軒(1681)+ 文明堂(1900)+ 梅月堂(1894)が徒歩 15 分圏内、各店で試食+ 1 切れ買い+ 食べ比べが可能。観光客は 4 店巡りでカステラの違いを味わう、長崎観光の食事散策ハイライト。",
    content_md: "- ルート:長崎駅 → 万屋町(福砂屋本店)→ 観光通り(松翁軒)→ 浜の町(文明堂)→ 浜の町(梅月堂)\n- 全長:1.5 km\n- 老舗 4 軒:福砂屋 1624(最古 400 年)+ 松翁軒 1681(345 年)+ 文明堂 1900(125 年)+ 梅月堂 1894(130 年)\n- 試食:多くの店舗で 1 切れ試食可\n- 価格目安:1 切れ ¥150-300・1 本 ¥1200-2500\n- 所要:30 分-1 時間\n- アクセス:JR 長崎駅 出発・観光通り経由",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["restaurant_traditional", "shopping_district_urban"],
    lat: 32.7444,
    lon: 129.8767,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_castella", "castera_zaka", "4_old_shops", "1_5km_walk", "tasting_compare"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 住 R4 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "ueno-ryokan-fukue-1935",
    category: "lodging",
    sub_type: "nagasaki_island_lodging",
    title_zh: "上野屋旅館(五島福江市内・1935 創業・90 年老舗・福江城下町・五島和牛料理)",
    title_ja: "上野屋旅館",
    romaji: "Ueno Ryokan",
    summary_zh: "**上野屋旅館は五島福江市内の老舗旅館**(五島市・1935 創業・90 年)。福江城下町に立地、五島和牛+ 五島産魚介の郷土料理が看板。**福江港+ 福江城跡+ 鬼岳まで車 5-15 分**、五島観光のハブとして利便性高。中規模 18 室の家族経営、ホスピタリティで評価高。",
    content_md: "- 創業:1935 年(昭和 10)・90 年\n- 立地:五島市福江市内(福江城下町)\n- 室数:18 室(中規模・家族経営)\n- 料理:五島和牛+ 五島産魚介の郷土料理\n- 料金目安:¥12000-20000/泊(2 食付)\n- 隣接:福江港(車 5 分)+ 福江城跡(徒歩 5 分)+ 鬼岳(車 15 分)\n- アクセス:長崎港 から ジェットフォイル 1 時間 25 分・福江港 徒歩 / 車",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "五島市",
    lg_code: "42211",
    area_types: ["onsen_field"],
    lat: 32.6943,
    lon: 128.8425,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_island_lodging", "ueno_ryokan", "1935", "fukue_castle_town", "goto_wagyu"],
    source: "manual",
  },
  {
    slug: "toyoko-inn-nagasaki-eki",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "東横イン長崎駅前(2003 開業・JR 長崎駅 徒歩 5 分・全国チェーン・コスパ良 270 室)",
    title_ja: "東横イン長崎駅前",
    romaji: "Toyoko Inn Nagasaki",
    summary_zh: "**東横イン長崎駅前は駅徒歩 5 分の全国チェーンビジネスホテル**(長崎市大黒町・2003 開業・270 室)。コスパ重視の旅行者+ ビジネス客向け、無料朝食(おにぎり+ 味噌汁)+ コインランドリー+ 大浴場無し。長崎駅前にホテル多数あるが、東横は最も安価帯で 1 泊 ¥6500-9000。",
    content_md: "- 開業:2003 年(平成 15)\n- 立地:JR 長崎駅 徒歩 5 分(大黒町)\n- 室数:270 室(全国チェーン最大級)\n- 系列:東横イン\n- 朝食:無料(おにぎり+ 味噌汁・簡易)\n- 料金目安:¥6500-9000/泊\n- 大浴場:なし(各室バス・温泉なし)\n- アクセス:JR 長崎駅 徒歩 5 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["urban_central"],
    lat: 32.7556,
    lon: 129.8722,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://www.toyoko-inn.com/" },
    tags: ["budget_hotel_chain", "toyoko_inn", "2003", "270_rooms", "lowest_price"],
    source: "manual",
  },
  {
    slug: "shimabara-jonan-hotel-1952",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "島原城南ホテル(1952 創業・島原温泉中堅老舗・70 年・島原城+ 武家屋敷徒歩・郷土料理)",
    title_ja: "島原城南ホテル",
    romaji: "Shimabara Jonan Hotel",
    summary_zh: "**島原城南ホテルは 1952 創業の中堅温泉ホテル**(島原市・70 年)。**島原温泉(海岸温泉系)** + 郷土料理(具雑煮+ 寒晒し)。島原城+ 武家屋敷+ 鯉の泳ぐまち徒歩圏、島原観光のベース宿として中規模 50 室。料金 ¥15000-25000(2 食付)、日帰り入浴も対応。",
    content_md: "- 創業:1952 年(昭和 27)・70 年\n- 立地:島原市萩原(島原温泉)\n- 室数:50 室\n- 温泉:島原温泉(海岸温泉系)\n- 料理:島原郷土料理(具雑煮+ 寒晒し+ 地魚)\n- 料金目安:¥15000-25000/泊(2 食付)\n- 日帰り入浴:¥800\n- 隣接:島原城(徒歩 10 分)+ 武家屋敷(徒歩 8 分)\n- アクセス:島原鉄道 島原駅 徒歩 10 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "島原市",
    lg_code: "42203",
    area_types: ["onsen_field"],
    lat: 32.7833,
    lon: 130.3700,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["onsen_ryokan", "shimabara_jonan", "1952", "70_years", "shimabara_onsen"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 衣 R4 (2)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "mikawachi-yumesyouen-kiln",
    category: "fashion",
    sub_type: "nagasaki_hasami_mikawachi",
    title_zh: "三川内焼 夢祥園窯(平戸藩窯系統・透かし彫り+ 瓜型抹茶碗・現代の若手継承窯元)",
    title_ja: "夢祥園窯",
    romaji: "Yumesyouen Kiln",
    summary_zh: "**夢祥園窯は三川内焼の若手継承窯元**(佐世保市三川内町・平戸藩窯系統)。透かし彫り技法+ 細密染付の伝統を維持しつつ、瓜型抹茶碗+ 葡萄文等の現代モチーフを開発。三川内焼陶器市(GW + 10 月)+ 直販店で出品、若年層+ ギフト需要に応える。",
    content_md: "- 立地:佐世保市三川内町\n- 系統:平戸藩窯(国指定伝統工芸品 1978)\n- 技法:透かし彫り+ 細密染付+ 唐子絵\n- 現代開発:瓜型抹茶碗+ 葡萄文\n- 製品:茶碗+ 抹茶碗+ 花瓶\n- 価格帯:小皿 ¥2500-+ 抹茶碗 ¥15000-\n- 営業:9:00-17:00(日曜定休)\n- アクセス:JR 三河内駅 徒歩 12 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "佐世保市",
    lg_code: "42202",
    area_types: ["historic_district"],
    lat: 33.2014,
    lon: 129.7392,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: ["sun"],
    external_urls: {},
    tags: ["nagasaki_hasami_mikawachi", "yumesyouen_kiln", "young_kiln", "uri_chawan"],
    source: "manual",
  },
  {
    slug: "omura-aizome-yokoyama",
    category: "fashion",
    sub_type: "nagasaki_omura_aizome",
    title_zh: "横山藍染工房(大村市・大村藍染め伝統工芸・天然藍 100%・体験型工房)",
    title_ja: "横山藍染工房",
    romaji: "Yokoyama Aizome",
    summary_zh: "**横山藍染工房は大村藍染め唯一の現役工房**(大村市・天然藍 100% 染色)。大村藍染めは江戸期から続く長崎県唯一の藍染め伝統、化学染料を使わず藍の生葉から染液を発酵させる技法。**藍染め体験 ¥3500-6500**(ハンカチ・トートバッグ・Tシャツ等)で観光客に人気。",
    content_md: "- 立地:大村市\n- 染料:天然藍 100%(化学染料未使用)\n- 由来:江戸期からの大村藍染め伝統\n- 体験:¥3500-6500(ハンカチ+ トートバッグ+ Tシャツ)\n- 体験時間:1.5-3 時間(要予約)\n- 価格帯:ハンカチ ¥2500-+ Tシャツ ¥8000-\n- 営業:10:00-17:00(月曜定休)\n- アクセス:JR 大村駅 徒歩 15 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "大村市",
    lg_code: "42205",
    area_types: ["historic_district"],
    lat: 32.8950,
    lon: 129.9667,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: ["mon"],
    external_urls: {},
    tags: ["nagasaki_omura_aizome", "yokoyama_aizome", "natural_indigo", "omura_dyeing", "experience"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 育 R4 (9)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nagasaki-museum-history-culture-2005",
    category: "culture",
    sub_type: "museum_art",
    title_zh: "長崎歴史文化博物館(2005 開館・旧長崎奉行所跡地+ 立山役所復元・出島貿易史総合)",
    title_ja: "長崎歴史文化博物館",
    romaji: "Nagasaki History Culture Museum",
    summary_zh: "**長崎歴史文化博物館は出島貿易+ 海外交流史の総合博物館**(長崎市立山町・2005 開館)。**旧長崎奉行所立山役所跡地** に建設、奉行所の一部を復元保存。出島オランダ貿易+ 唐人屋敷+ 唐寺+ シーボルト+ 開国期の長崎に関する 7 万点+ 史料。常設+ 特別展で長崎史を体系的に学べる必訪施設。",
    content_md: "- 開館:2005 年(平成 17)\n- 立地:長崎市立山町(旧長崎奉行所立山役所跡地)\n- 史的価値:江戸期長崎奉行所の一部を復元保存\n- 主要展示:出島オランダ貿易+ 唐人屋敷+ 唐寺+ シーボルト+ 開国期(7 万点+ 史料)\n- 入館料:¥630\n- 営業:8:30-19:00(第 1・第 3 月曜休館)\n- 隣接:諏訪神社(徒歩 8 分)+ 浦上駅(徒歩 15 分)\n- アクセス:長崎電軌「桜町」電停 徒歩 8 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["museum_art"],
    lat: 32.7544,
    lon: 129.8783,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["mon"],
    external_urls: { official: "https://www.nmhc.jp/" },
    tags: ["museum_art", "history_culture", "2005", "bugyousho_restoration", "70k_artifacts"],
    source: "manual",
  },
  {
    slug: "gamadasu-dome-1995-eruption",
    category: "culture",
    sub_type: "museum_art",
    title_zh: "雲仙岳災害記念館 がまだすドーム(島原市・2002 開館・1990-95 雲仙噴火体験館・大型シアター)",
    title_ja: "がまだすドーム",
    romaji: "Gamadasu Dome",
    summary_zh: "**がまだすドームは 1990-95 雲仙普賢岳噴火を記録する災害記念館**(島原市平成町・2002 開館)。**44 名の犠牲者を出した近代日本最大級の火山災害** を体系的に学べる施設、大型シアター+ 火砕流体験コーナー+ 当時の被災家屋遺構展示。「がまだす」は島原方言「頑張ろう」の意。",
    content_md: "- 開館:2002 年(平成 14)\n- 立地:島原市平成町(平成新山隣接)\n- 名前由来:島原方言「がまだす」(頑張ろう)\n- 主要展示:雲仙普賢岳噴火 1990-95 全記録+ 火砕流体験+ 被災家屋遺構\n- 犠牲:44 名(報道関係者+ 火山学者+ 消防士・1991-06-03 大火砕流)\n- 入館料:¥1050\n- 営業:9:00-17:00(年中無休)\n- 隣接:平成新山(車 10 分)+ 道の駅 みずなし本陣(徒歩 5 分)\n- アクセス:島原鉄道 島原駅 から 車 10 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "島原市",
    lg_code: "42203",
    area_types: ["museum_art"],
    lat: 32.7811,
    lon: 130.3897,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.udmh.or.jp/" },
    tags: ["museum_art", "gamadasu_dome", "2002", "1991_eruption", "44_casualties"],
    source: "manual",
  },
  {
    slug: "urakami-yobankuzure-1867",
    category: "culture",
    sub_type: "nagasaki_christian_history",
    title_zh: "浦上四番崩れ史跡(1867 慶応 3・潜伏キリシタン 3000 名検挙+ 全国流配・解禁の契機)",
    title_ja: "浦上四番崩れ史跡",
    romaji: "Urakami Yobankuzure",
    summary_zh: "**浦上四番崩れは長崎潜伏キリシタンの大迫害事件**(1867 年・浦上)。3000 名以上の信徒が検挙+ 全国 21 藩へ流配、配流先で 600 名死亡(殉教扱い)。1873 解禁(明治 6 政府がキリシタン禁制廃止)の直接的契機となった事件、現在の浦上天主堂建立の背景。**史跡碑+ 関連施設(浦上街道+ 西坂教会記念館)** が散在する歴史散策コース。",
    content_md: "- 発生:1867 年(慶応 3)6 月\n- 検挙数:3000 名以上\n- 流配先:全国 21 藩(津和野+ 萩+ 鹿児島+ 福山等)\n- 死亡:600 名(配流先で・殉教扱い)\n- 解禁:1873 年(明治 6)・キリシタン禁制廃止の直接的契機\n- 史跡:浦上天主堂周辺+ 浦上街道+ 西坂教会記念館\n- 入場:無料(常時)\n- 隣接:浦上天主堂(R1 既出)+ 西坂教会記念館\n- アクセス:長崎電軌「平和公園」電停 徒歩 8 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["history_site_castle"],
    lat: 32.7763,
    lon: 129.8678,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_christian_history", "urakami_yobankuzure", "1867", "3000_arrested", "1873_release"],
    source: "manual",
  },
  {
    slug: "shimabara-bukei-yashiki",
    category: "culture",
    sub_type: "history_site_castle",
    title_zh: "島原武家屋敷+ 鯉の泳ぐまち(島原市・武家屋敷 3 軒保存+ 用水路に泳ぐ鯉・島原観光散策定番)",
    title_ja: "島原武家屋敷・鯉の泳ぐまち",
    romaji: "Shimabara Bukei Yashiki",
    summary_zh: "**島原武家屋敷+ 鯉の泳ぐまちは島原市内の歴史散策スポット**(島原市新町・無料公開)。**篠塚邸+ 山本邸+ 鳥田邸の 3 軒の武家屋敷** が当時の姿で保存、用水路には数百匹の錦鯉。島原は名水の街(R3 楽 で島原水まつり登場)、湧水利用の用水路文化を体感できる。城下町の雰囲気+ 銀水具雑煮(R3 食)も近接。",
    content_md: "- 立地:島原市新町(島原城 徒歩 5 分)\n- 武家屋敷:篠塚邸+ 山本邸+ 鳥田邸の 3 軒(無料公開)\n- 鯉の泳ぐまち:用水路 200 m に 数百匹の錦鯉\n- 由来:島原藩士の住居町・湧水利用の用水路文化\n- 入場料:無料(常時)\n- 営業:9:00-17:00(屋敷内)\n- 隣接:島原城(徒歩 5 分)+ 銀水(徒歩 3 分)+ 島原港(徒歩 15 分)\n- アクセス:島原鉄道 島原駅 徒歩 8 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "島原市",
    lg_code: "42203",
    area_types: ["history_site_castle", "historic_district"],
    lat: 32.7833,
    lon: 130.3650,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["history_site_castle", "shimabara_bukei_yashiki", "carp_streets", "samurai_residence", "free"],
    source: "manual",
  },
  {
    slug: "unzen-jigoku-kirishitan-junkyo",
    category: "culture",
    sub_type: "nagasaki_christian_history",
    title_zh: "雲仙地獄キリシタン処刑地(1627-1632・松倉氏により 33 名処刑・湯処刑伝承碑)",
    title_ja: "雲仙地獄キリシタン処刑地",
    romaji: "Unzen Jigoku Kirishitan Junkyo",
    summary_zh: "**雲仙地獄は江戸初期キリシタン処刑の地**(雲仙温泉・1627-1632)。松倉重政・勝家の島原藩キリシタン弾圧で 33 名のキリシタンが **熱湯地獄に投げ込まれて処刑**(湯処刑)、長崎地区最も残虐な迫害事件。雲仙地獄(R1 楽既出)に **キリシタン殉教碑** が建立、観光地獄の負の歴史を今に伝える。",
    content_md: "- 期間:1627-1632 年(寛永 4-9)\n- 処刑者:33 名(島原藩松倉重政+勝家による)\n- 処刑方法:湯処刑(熱湯地獄に投げ込む・他に石抱+ 板挟み)\n- 殉教碑:雲仙地獄遊歩道沿い\n- 史的意義:雲仙地獄観光地の負の歴史・島原の乱(1637)の遠因\n- 入場:無料(雲仙地獄遊歩道内)\n- 営業:常時(雲仙地獄に準じる)\n- 隣接:雲仙地獄+ 雲仙お山の情報館(R3)\n- アクセス:諫早駅 から バス 80 分・雲仙下車",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "雲仙市",
    lg_code: "42213",
    area_types: ["history_site_castle"],
    lat: 32.7458,
    lon: 130.2592,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_christian_history", "unzen_kirishitan", "1627_1632", "33_martyrs", "yu_punishment"],
    source: "manual",
  },
  {
    slug: "watazumi-jinja-tsushima",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "海神神社(対馬・対馬国一宮・延喜式内社・神功皇后伝承・国宝高麗仏 2 体)",
    title_ja: "海神神社",
    romaji: "Watazumi Jinja",
    summary_zh: "**海神神社は対馬国一宮**(対馬市峰町・延喜式内社)。神功皇后(伝・3 世紀)の対馬遠征時に建立伝、海神(綿津見神)を祀る対馬最高格式の神社。**国宝指定の高麗仏 2 体**(青銅菩薩立像)を所蔵、対馬と朝鮮半島の文化交流を象徴する寺宝。山中の静謐な立地、対馬観光のハイライト。",
    content_md: "- 創建:伝 3 世紀(神功皇后伝承)\n- 社格:対馬国一宮+ 延喜式内社(平安期 9C)\n- 主祭神:豊玉姫命(綿津見神)\n- 国宝:高麗仏 2 体(青銅菩薩立像・11C)\n- 立地:対馬市峰町木坂\n- 入場料:無料(宝物殿は要予約)\n- 営業:24 時間(社務所 9:00-17:00)\n- 隣接観光:浅茅湾(車 30 分)+ 万松院(車 30 分)\n- アクセス:対馬空港 から 車 50 分・厳原港 から 車 1 時間",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "対馬市",
    lg_code: "42209",
    area_types: ["shrine_temple"],
    lat: 34.3886,
    lon: 129.2944,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "watazumi_jinja", "tsushima_ichinomiya", "korean_buddha", "national_treasure"],
    source: "manual",
  },
  {
    slug: "tsukiyomi-jinja-iki",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "月読神社(壱岐・国生み神話 八神の 1・京都松尾大社月読神社の本宮・延喜式内社)",
    title_ja: "月読神社",
    romaji: "Tsukiyomi Jinja",
    summary_zh: "**月読神社は壱岐の古社**(壱岐市芦辺町・延喜式内社)。**京都松尾大社月読神社の本宮**(伝・3 世紀末月読命を京都へ勧請)、月読命(イザナギ・イザナミ国生み 八神の 1)を祀る。壱岐は天皇家祖神に連なる神話の島、原の辻遺跡(R1 育)+ 一支国 + 神話の島の三位一体観光。",
    content_md: "- 社格:延喜式内社(平安期 9C)\n- 主祭神:月読命(国生み神話 八神の 1)\n- 史的意義:京都松尾大社月読神社の本宮(壱岐 → 京都勧請伝)\n- 立地:壱岐市芦辺町国分東触\n- 入場料:無料\n- 営業:24 時間\n- 隣接観光:原の辻遺跡(車 10 分)+ 壱岐ビーチ(車 15 分)\n- アクセス:芦辺港 から 車 10 分(壱岐空港 から 車 20 分)",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "壱岐市",
    lg_code: "42210",
    area_types: ["shrine_temple"],
    lat: 33.7547,
    lon: 129.7397,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "tsukiyomi_jinja", "ikinokuni", "matsuo_taisha_origin", "kuninokami"],
    source: "manual",
  },
  {
    slug: "zuiun-ji-hirado",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "瑞雲寺(平戸松浦家菩提寺・1554 創建・松浦法印重信ゆかり・寺院教会併立眺望の中心)",
    title_ja: "瑞雲寺",
    romaji: "Zuiunji",
    summary_zh: "**瑞雲寺は平戸松浦家の菩提寺**(平戸市鏡川町・1554 創建)。松浦法印重信(平戸藩の精神的祖)が建立、松浦氏歴代墓所。**平戸ザビエル記念教会と並ぶ立地で「寺院と教会の見える風景」** の中心被写体、平戸観光の SNS 映えスポット。",
    content_md: "- 創建:1554 年(天文 23)・松浦法印重信\n- 宗派:臨済宗\n- 役割:松浦家菩提寺・歴代墓所\n- 史的意義:松浦氏精神的祖の創建寺\n- 立地:平戸市鏡川町(平戸ザビエル教会隣接)\n- 観光価値:寺院と教会の見える風景の構成要素\n- 入場料:無料(墓所拝観は要連絡)\n- 営業:9:00-17:00\n- 隣接:平戸ザビエル記念教会(徒歩 1 分)+ 光明寺+ 平戸城(徒歩 8 分)\n- アクセス:松浦鉄道 たびら平戸口駅 から バス 30 分・平戸桟橋 徒歩 10 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "平戸市",
    lg_code: "42207",
    area_types: ["shrine_temple"],
    lat: 33.3672,
    lon: 129.5489,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "zuiunji", "1554", "matsuura_clan_bodaiji", "temple_church_view"],
    source: "manual",
  },
  {
    slug: "dejima-restoration-1996",
    category: "culture",
    sub_type: "nagasaki_dutch_china_trade",
    title_zh: "出島復元事業(1996 開始・16 棟復元完成・カピタン部屋+ ヘトル部屋+ 一番蔵+ 二番蔵)",
    title_ja: "出島復元事業",
    romaji: "Dejima Restoration",
    summary_zh: "**出島復元事業は 1996 年開始の長期再現プロジェクト**(長崎市出島町)。1922 国指定史跡指定後、1996 第 1 期スタート、現在 **16 棟の復元完成**(カピタン部屋・ヘトル部屋・一番蔵・二番蔵・乙名部屋・通詞部屋・水門 等)。江戸期の出島の姿を再現、復元手法の精度+ 史実考証で評価高、出島観光の展示中核。",
    content_md: "- 開始:1996 年(平成 8)・第 1 期\n- 復元棟数:16 棟(2026 年現在)\n- 主要復元:カピタン部屋(オランダ商館長居所)+ ヘトル部屋+ 一番蔵+ 二番蔵+ 乙名部屋+ 通詞部屋+ 水門\n- 評価:精緻な史実考証で全国の史跡復元事例の手本\n- 入場料:出島入場 ¥520 込\n- 営業:8:00-21:00(年中無休)\n- 隣接:出島(R1 育既出)+ 出島ワーフ\n- アクセス:長崎電軌「出島」電停 徒歩 1 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["history_site_castle"],
    lat: 32.7437,
    lon: 129.8731,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://nagasakidejima.jp/" },
    tags: ["nagasaki_dutch_china_trade", "dejima_restoration", "1996_start", "16_buildings", "kapitan_room"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 楽 R4 (5)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shimabara-yusui-meguri-7sites",
    category: "entertainment",
    sub_type: "nagasaki_unzen_jigoku",
    title_zh: "島原 7 大湧水巡り(名水百選 1985・湧水庭園+ 浜の川湧水+ 鯉の泳ぐまち+ 散策)",
    title_ja: "島原湧水巡り",
    romaji: "Shimabara Yusui Meguri",
    summary_zh: "**島原は「水の都」で名水百選 1985 認定**(島原市)。**7 大湧水**(浜の川湧水・速魚川湧水・四明荘湧水 等)が街中に点在、徒歩 1 時間で巡れる散策コース。**湧水庭園「四明荘」**(国登録有形文化財・1908 邸宅)+ 浜の川湧水観光交流館(2014 整備)+ 鯉の泳ぐまち で水の街を体感。",
    content_md: "- 認定:名水百選(1985 環境省)\n- 7 大湧水:浜の川+ 速魚川+ 四明荘+ 白土湖+ 銀水+ 大手川+ 弁財天\n- 散策時間:徒歩 1 時間 30 分\n- 湧水庭園 四明荘:国登録有形文化財(1908 邸宅・¥310)\n- 浜の川湧水観光交流館:2014 整備・無料\n- 入場:多くは無料\n- アクセス:島原鉄道 島原駅 徒歩 5-15 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "島原市",
    lg_code: "42203",
    area_types: ["historic_district", "scenic_spot"],
    lat: 32.7833,
    lon: 130.3650,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_unzen_jigoku", "shimabara_yusui", "meisui_100", "7_sites", "free"],
    source: "manual",
  },
  {
    slug: "tsushima-eboshidake-tenboudai",
    category: "entertainment",
    sub_type: "nagasaki_kujukushima_marine",
    title_zh: "対馬烏帽子岳展望台(176m・浅茅湾全景+ 200+ 入江+ 多島海・国境離島最高絶景)",
    title_ja: "烏帽子岳展望台",
    romaji: "Eboshidake Tenboudai",
    summary_zh: "**烏帽子岳展望台は浅茅湾全景の最良スポット**(対馬市美津島町・標高 176 m)。山頂展望デッキから **浅茅湾 200+ 入江+ 多島海+ リアス式海岸** の絶景が一望、「日本のフィヨルド」の全景眺望。車道+ 徒歩 5 分でアクセス可、無料 24 時間開放、サンセット時刻が最美。",
    content_md: "- 標高:176 m\n- 立地:対馬市美津島町(浅茅湾畔)\n- 眺望:浅茅湾 200+ 入江+ 多島海+ リアス式海岸\n- 入場:無料(24 時間開放)\n- アクセス手段:展望台駐車場 から 徒歩 5 分(車道整備)\n- ベスト:サンセット時刻\n- 駐車場:無料 30 台\n- 隣接:浅茅湾(車 10 分)+ 万松院(車 30 分)\n- アクセス:対馬空港 から 車 25 分・厳原港 から 車 35 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "対馬市",
    lg_code: "42209",
    area_types: ["scenic_spot", "mountain_village"],
    lat: 34.3500,
    lon: 129.3000,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_kujukushima_marine", "eboshidake", "176m", "asou_bay_panorama", "free_24h"],
    source: "manual",
  },
  {
    slug: "hirado-tabira-sunset",
    category: "entertainment",
    sub_type: "nagasaki_night_view",
    title_zh: "平戸瀬戸夕陽(田平公園・平戸大橋+ 平戸島シルエット+ サンセット・全国級夕陽スポット)",
    title_ja: "平戸瀬戸夕陽",
    romaji: "Hirado Seto Sunset",
    summary_zh: "**平戸瀬戸夕陽は全国級サンセットスポット**(平戸市田平町・田平公園)。平戸大橋(R1 行)+ 平戸島シルエット+ 平戸瀬戸の急流の組み合わせで、夕陽が橋の真下に沈む絶景。**春-秋の夕方 18:00-19:30** が最ベスト、写真愛好家+ 観光客で賑わう。田平公園(R2 楽は別 entry tabira-cherry-hirado-1500・桜が主目的)とは別 angle。",
    content_md: "- 立地:平戸市田平町(田平公園)\n- 眺望:平戸大橋+ 平戸島+ 平戸瀬戸\n- ベスト時間:春-秋 18:00-19:30(夕陽が橋下に沈む)\n- 入場:無料(常時)\n- 駐車場:無料 200 台\n- 隣接:田平天主堂(国重文 R2 育)+ 田平公園桜 (R2 楽)+ 平戸大橋(徒歩 5 分)\n- アクセス:松浦鉄道 たびら平戸口駅 徒歩 10 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "平戸市",
    lg_code: "42207",
    area_types: ["scenic_spot"],
    lat: 33.3781,
    lon: 129.5803,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_night_view", "hirado_sunset", "tabira_park", "national_top_sunset", "free"],
    source: "manual",
  },
  {
    slug: "unzen-miyamakirishima-may",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "雲仙仁田峠ミヤマキリシマ(5 月中旬-6 月上旬・10 万本ピンクの絨毯・国指定天然記念物)",
    title_ja: "雲仙ミヤマキリシマ",
    romaji: "Unzen Miyamakirishima",
    summary_zh: "**雲仙のミヤマキリシマは国内屈指の山岳ツツジ群落**(雲仙市仁田峠・5 月中旬-6 月上旬)。**10 万本のミヤマキリシマがピンクの絨毯**、雲仙ロープウェイ(R2 楽既出)で妙見岳まで上がると 360 度ピンクの世界。**国指定天然記念物**(1956 指定)、大型連休後の春の絶景イベント。",
    content_md: "- 時期:5 月中旬-6 月上旬\n- 規模:10 万本(国内屈指の山岳ツツジ群落)\n- 認定:国指定天然記念物(1956)\n- 立地:雲仙市仁田峠(標高 1080 m)\n- アクセス手段:雲仙ロープウェイ(往復 ¥1290・3 分)で妙見岳駅(1330 m)\n- 入場:無料(仁田峠循環道路通行料 ¥520)\n- ベスト時間:午前中 (撮影光量+ 混雑回避)\n- 駐車場:無料 600 台\n- アクセス:雲仙温泉 から 車 15 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "雲仙市",
    lg_code: "42213",
    area_types: ["national_park", "flower_field"],
    lat: 32.7600,
    lon: 130.2611,
    season_start: "2026-05-15",
    season_end: "2026-06-05",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://unzen-ropeway.com/" },
    tags: ["flower_field", "miyamakirishima", "may_june", "100k_flowers", "national_natural_monument"],
    source: "manual",
  },
  {
    slug: "fukue-doroibata-onsen",
    category: "entertainment",
    sub_type: "nagasaki_kujukushima_marine",
    title_zh: "堂崎温泉(五島福江島・離島温泉体験・夕陽眺望+ 露天風呂+ ¥500・地元客中心の隠れ家)",
    title_ja: "堂崎温泉",
    romaji: "Doroibata Onsen",
    summary_zh: "**堂崎温泉は五島福江島の離島温泉**(五島市浜町・¥500)。福江島西側の海岸沿いに立地、**夕陽眺望可能な露天風呂** で観光客より地元客中心の隠れ家温泉。レンタカーでの五島観光時に立寄り、観光帰りの汗+ 疲れ流し+ サンセット鑑賞の三拍子。",
    content_md: "- 立地:五島市福江島西部(浜町)\n- 入浴料:¥500(大人・子供 ¥300)\n- 営業:11:00-22:00(火曜定休)\n- 設備:大浴場+ 露天風呂(夕陽眺望)+ サウナ\n- 泉質:単純温泉\n- 雰囲気:地元客中心の隠れ家\n- 隣接:鬼岳(車 25 分)+ 堂崎天主堂(車 5 分)\n- アクセス:福江港 から 車 30 分(レンタカー必須)",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "五島市",
    lg_code: "42211",
    area_types: ["onsen_field"],
    lat: 32.7300,
    lon: 128.8100,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["tue"],
    external_urls: {},
    tags: ["nagasaki_kujukushima_marine", "doroibata_onsen", "fukue_west", "sunset_rotenburo", "500yen"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 行 R4 (4)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "orc-air-1961-overview",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "オリエンタルエアブリッジ ORC(1961 創業・国内最小級航空会社・本社大村・離島 5 空港運航)",
    title_ja: "オリエンタルエアブリッジ",
    romaji: "Oriental Air Bridge",
    summary_zh: "**ORC(オリエンタルエアブリッジ)は国内最小級の航空会社**(本社:大村市・1961 創業)。長崎空港 hub に **長崎-福江・対馬・壱岐+ 福岡-五島・対馬・壱岐 等の離島路線専門運航**。機材は ボンバルディア DHC-8(40-50 席)、JAL コードシェアで全国予約可。離島観光+ ビジネス利用の生命線。",
    content_md: "- 創業:1961 年(昭和 36)・60+ 年\n- 本社:大村市(長崎空港隣)\n- 機材:ボンバルディア DHC-8(40-50 席)\n- 主要路線:長崎-福江・対馬・壱岐+ 福岡-五島・対馬・壱岐+ 福岡-宮崎\n- コードシェア:JAL(全国予約可)\n- 1 日便数:30+ 便/日\n- 規模:従業員 200+ 名(国内最小級航空会社)\n- 予約:JAL ネット予約+ ORC 公式(www.orc-air.co.jp)\n- アクセス:長崎空港 hub",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "大村市",
    lg_code: "42205",
    area_types: ["airport"],
    lat: 32.9167,
    lon: 129.9136,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.orc-air.co.jp/" },
    tags: ["airport_access", "orc", "1961", "smallest_japan_airline", "island_routes"],
    source: "manual",
  },
  {
    slug: "shin-kamigoto-municipal-bus",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "新上五島町営バス(中通島内 全 6 路線・主要観光地+ 教会群+ 港アクセス・¥190-1100)",
    title_ja: "新上五島町営バス",
    romaji: "Shin Kamigoto Municipal Bus",
    summary_zh: "**新上五島町営バスは中通島内の路線バス**(新上五島町・6 路線)。有川港+ 奈良尾港+ 鯛ノ浦港+ 頭ヶ島港+ 各地集落+ 教会群を結ぶ、**頭ヶ島天主堂(R1 育・国重文)**+ **江上天主堂(R1 育)** ほか教会群アクセスに必須。レンタカーがない観光客の生命線、1 日数本-10 本程度で要事前確認。",
    content_md: "- 運営:新上五島町交通(町営)\n- 路線数:6 路線\n- 主要 hub:有川港バスセンター+ 奈良尾港+ 鯛ノ浦港\n- 観光連絡:頭ヶ島天主堂(R1 育)+ 江上天主堂(R1 育・船便)+ 矢堅目+ 龍観山展望台\n- 運賃:¥190-1100(区間制)\n- 1 日本数:1 路線あたり 4-10 便/日\n- 備考:離島で本数少ない・要事前時刻表確認\n- アクセス:佐世保 から フェリー 1.5 時間・有川港 / 鯛ノ浦港",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: "南松浦郡",
    municipality_ja: "新上五島町",
    lg_code: "42411",
    area_types: ["transit_hub"],
    lat: 33.0578,
    lon: 129.1414,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["area_access_guide", "shin_kamigoto_bus", "6_routes", "church_access", "island_essential"],
    source: "manual",
  },
  {
    slug: "goto-municipal-bus-fukue",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "五島自動車(福江島内・五島市町民バス併設・主要観光地+ 福江港+ 福江空港+ 教会群)",
    title_ja: "五島自動車",
    romaji: "Goto Bus",
    summary_zh: "**五島自動車は福江島内の路線バス**(五島市・五島市町民バス併設)。福江港+ 福江空港+ 鬼岳+ 大瀬崎灯台+ 三井楽+ 玉之浦等を結ぶ、福江島観光の主要交通。**江上天主堂(R1 育・奈留島) は別途船便**+ 五島市内バスは中継のみ。1 日 5-15 便程度、レンタカー併用が現実的。",
    content_md: "- 運営:五島自動車(株)+ 五島市町民バス\n- 路線数:10+ 路線\n- 主要 hub:福江港バスターミナル+ 福江空港\n- 観光連絡:鬼岳(R1 楽)+ 大瀬崎灯台+ 三井楽+ 玉之浦+ 福江城跡\n- 運賃:¥160-2000(区間制)\n- 1 日本数:1 路線あたり 5-15 便/日\n- 備考:離島で本数少ない・レンタカー併用推奨\n- アクセス:長崎港 から ジェットフォイル 1 時間 25 分・福江港",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "五島市",
    lg_code: "42211",
    area_types: ["transit_hub"],
    lat: 32.6951,
    lon: 128.8408,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["area_access_guide", "goto_jidousha", "fukue_bus", "10_routes", "rental_combine"],
    source: "manual",
  },
  {
    slug: "nagasaki-airport-limousine",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "長崎空港リムジンバス(空港-市内 50 分・¥1200・1 日 30+ 便・新大村駅+ 諫早駅経由)",
    title_ja: "長崎空港リムジンバス",
    romaji: "Nagasaki Airport Limousine",
    summary_zh: "**長崎空港リムジンバスは空港-長崎市内の主要アクセス**(50 分・¥1200・1 日 30+ 便)。長崎自動車+ 県営バス共同運行、**新大村駅(西九州新幹線・徒歩 10 分)+ 諫早駅(西九州新幹線・徒歩 5 分)経由** で長崎駅前バスターミナル。新幹線併用も便利、空港アクセスの定番。",
    content_md: "- 運営:長崎自動車+ 県営バス共同運行\n- 所要:50 分(長崎空港-長崎駅前)\n- 料金:¥1200(片道)+ 往復 ¥2200\n- 1 日本数:30+ 便/日(便数最多級)\n- 主要停留所:長崎空港 → 大村 IC → 諫早駅 → 浦上駅 → 長崎駅前\n- 西九州新幹線併用:諫早駅 + 新大村駅で乗換可\n- 予約:不要(自由乗車・支払 IC カード可)\n- 営業:5:30-23:00\n- アクセス:長崎空港 1F 到着ロビー前",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "大村市",
    lg_code: "42205",
    area_types: ["airport", "transit_hub"],
    lat: 32.9167,
    lon: 129.9136,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.nagasaki-bus.co.jp/" },
    tags: ["airport_access", "limousine_bus", "50min", "1200yen", "30_routes_per_day"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[nagasaki-r4] 尚無條目");
    return;
  }
  console.log(`[nagasaki-r4] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const byCat = new Map<string, number>();
    for (const r of rows) byCat.set(r.category, (byCat.get(r.category) ?? 0) + 1);
    for (const [k, v] of [...byCat.entries()].sort()) {
      console.log(`  ${k.padEnd(15)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[nagasaki-r4] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[nagasaki-r4] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[nagasaki-r4] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
