// Seed 埼玉県 育 R1(21 筆 / Sprint 1.4 / 第十一卷)
//
// 軸:川越文化 6 + 秩父文化 6 + 行田さきたま 3 + さいたま市 2 + その他 4 = 21
//   川越:蔵造り街+時の鐘+喜多院+本丸御殿+菓子屋横丁+川越まつり
//   秩父:秩父神社+夜祭+三峯神社+芝桜の丘+まつり会館+龍勢
//   行田:さきたま古墳群+稲荷山鉄剣+忍城
//   さいたま市:大宮氷川+浦和調
//   その他:鉢形城+鷲宮+遠山記念館+飯能能仁寺

import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // ─── 川越文化 6 ───
  {
    slug: "kawagoe-kurazukuri-street",
    category: "culture",
    sub_type: "saitama_kawagoe_culture",
    title_zh: "川越蔵造り街(川越市仲町・1893 川越大火後再建蔵造り建築群+ 国選定 1999 重要伝統的建造物群保存地区+ 約 30 棟現存・「小江戸川越」象徴・年間 700 万人観光地+ R1 衣 川越唐桟+R1 食 川越芋スイーツ+R1 住 川越プリンス・町家旅館 観光中核)",
    title_ja: "川越蔵造り街",
    romaji: "Kawagoe Kurazukuri Street",
    summary_zh: "**川越蔵造り街は 1893 大火後再建蔵造り建築群・国選定 1999 重要伝統的建造物群保存地区**(川越市仲町・**約 30 棟現存・年間 700 万人観光地**)。R1 衣+食+住 観光中核、「小江戸川越」象徴。",
    content_md:
      "- 立地:**川越市仲町**\n- 起源:**1893 川越大火後再建**\n- 認定:**国選定 1999 重要伝統的建造物群保存地区**\n- 規模:**約 30 棟現存 + 年間 700 万人観光**\n- 別名:**「小江戸川越」**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "川越市",
    lg_code: "11201",
    area_types: ["history_site_castle", "shopping_district"],
    lat: 35.9251,
    lon: 139.4858,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia_ja: "https://ja.wikipedia.org/wiki/川越市",
    },
    tags: ["kurazukuri", "1893_fire", "1999_dento", "30_buildings", "small_edo"],
    source: "manual",
  },
  {
    slug: "kawagoe-tokinokane-1894",
    category: "culture",
    sub_type: "saitama_kawagoe_culture",
    title_zh: "川越時の鐘(川越市幸町・1894 川越大火後 4 代目再建 131 年+ 高さ 16m 木造櫓+ 1 日 4 回 6/12/15/18 時自動鐘・川越のシンボル+ 環境省「残したい日本の音風景 100 選」1996+ R1 衣 川越唐桟+R1 食 川越時の鐘銘菓 観光連動)",
    title_ja: "川越時の鐘",
    romaji: "Kawagoe Toki no Kane",
    summary_zh: "**川越時の鐘は 1894 大火後 4 代目再建 131 年・高さ 16m 木造櫓**(川越市幸町・**1996 残したい日本の音風景 100 選**)。1 日 4 回自動鐘、R1 衣+食 連動、川越のシンボル。",
    content_md:
      "- 立地:**川越市幸町**\n- 起源:**1894 大火後 4 代目再建 131 年**\n- 認定:**1996 残したい日本の音風景 100 選**\n- 規模:**高さ 16m 木造櫓**\n- 鐘:**1 日 4 回 6/12/15/18 時自動**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "川越市",
    lg_code: "11201",
    area_types: ["history_site_castle"],
    lat: 35.9258,
    lon: 139.4858,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia_ja: "https://ja.wikipedia.org/wiki/時の鐘_(川越市)",
    },
    tags: ["tokinokane", "1894", "131_years", "1996_oto100"],
    source: "manual",
  },
  {
    slug: "kawagoe-kitain-temple-830",
    category: "culture",
    sub_type: "saitama_kawagoe_culture",
    title_zh: "喜多院(川越市小仙波町・830 慈覚大師円仁開基 1195 年+ 天台宗関東三十六不動尊 28 番+ 徳川家光誕生の間 + 春日局化粧の間 江戸城紅葉山御殿移築・五百羅漢 538 体・初詣 30 万人 関東屈指)",
    title_ja: "喜多院",
    romaji: "Kitain",
    summary_zh: "**喜多院は 830 慈覚大師円仁開基 1195 年・天台宗関東三十六不動尊 28 番**(川越市小仙波町・**徳川家光誕生の間 + 春日局化粧の間 江戸城紅葉山御殿移築**)。五百羅漢 538 体、初詣 30 万人。",
    content_md:
      "- 立地:**川越市小仙波町**\n- 起源:**830 慈覚大師円仁開基 1195 年**\n- 宗派:**天台宗関東三十六不動尊 28 番**\n- 看板:**徳川家光誕生の間 + 春日局化粧の間(江戸城紅葉山御殿移築)**\n- 五百羅漢:**538 体**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "川越市",
    lg_code: "11201",
    area_types: ["temple_shrine"],
    lat: 35.9156,
    lon: 139.4928,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.kawagoe.com/kitain/",
    },
    tags: ["kitain", "830", "1195_years", "iemitsu", "538_rakan"],
    source: "manual",
  },
  {
    slug: "kawagoe-jou-honmaru-goten",
    category: "culture",
    sub_type: "saitama_kawagoe_culture",
    title_zh: "川越城本丸御殿(川越市郭町・1848 嘉永元年再建 177 年+ 全国 4 例現存本丸御殿の 1+ 太田道灌 1457 築城・川越藩松平家 17 万石・国指定史跡 2008・現存御殿 16 室+ 入館 ¥100 大人)",
    title_ja: "川越城本丸御殿",
    romaji: "Kawagoe Jō Honmaru Goten",
    summary_zh: "**川越城本丸御殿は 1848 嘉永元年再建 177 年・全国 4 例現存本丸御殿の 1**(川越市郭町・**太田道灌 1457 築城・国指定史跡 2008**)。現存 16 室、入館 ¥100 大人。",
    content_md:
      "- 立地:**川越市郭町**\n- 築城:**太田道灌 1457**\n- 再建:**1848 嘉永元年・177 年**\n- 認定:**全国 4 例現存本丸御殿 + 国指定史跡 2008**\n- 入館:**¥100 大人**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "川越市",
    lg_code: "11201",
    area_types: ["history_site_castle"],
    lat: 35.9272,
    lon: 139.4878,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["monday"],
    external_urls: {
      wikipedia_ja: "https://ja.wikipedia.org/wiki/川越城",
    },
    tags: ["kawagoe_jou", "honmaru_goten", "1848", "177_years", "1457_dokan"],
    source: "manual",
  },
  {
    slug: "kawagoe-kashiya-yokocho",
    category: "culture",
    sub_type: "saitama_kawagoe_culture",
    title_zh: "菓子屋横丁(川越市元町・明治初期 1796 創業説 + 昭和初期 70+ 軒最盛・現存 20+ 軒駄菓子屋・国登録有形文化財地区+ 環境省「残したい日本の音風景 100 選」1996+ R1 食 川越芋スイーツ 観光中核+ 1 軒平均 ¥150-800 駄菓子)",
    title_ja: "菓子屋横丁",
    romaji: "Kashiya Yokochō",
    summary_zh: "**菓子屋横丁は明治初期創業 + 昭和初期 70+ 軒最盛・現存 20+ 軒駄菓子屋**(川越市元町・**国登録有形文化財地区 + 1996 残したい日本の音風景 100 選**)。R1 食 川越芋連動、¥150-800/駄菓子。",
    content_md:
      "- 立地:**川越市元町**\n- 起源:**明治初期 + 昭和初期 70+ 軒最盛**\n- 規模:**現存 20+ 軒駄菓子屋**\n- 認定:**国登録有形文化財地区 + 1996 音風景 100 選**\n- 関連:**R1 食 川越芋スイーツ**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "川越市",
    lg_code: "11201",
    area_types: ["shopping_district", "history_site_castle"],
    lat: 35.9268,
    lon: 139.4847,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kashiya_yokocho", "20_shops", "登録有形"],
    source: "manual",
  },
  {
    slug: "kawagoe-matsuri-unesco-2016",
    category: "culture",
    sub_type: "saitama_kawagoe_culture",
    title_zh: "川越まつり(川越市・10 月第 3 土日・氷川神社例祭・1648 慶安元年起源 377 年+ 山車 29 台+ 関東三大祭+ 2005 国指定重要無形民俗文化財+ UNESCO 無形文化遺産 2016「山・鉾・屋台行事」33 件構成・観客 100 万人 / 2 日)",
    title_ja: "川越まつり",
    romaji: "Kawagoe Matsuri",
    summary_zh: "**川越まつりは 10 月第 3 土日・氷川神社例祭・1648 慶安元年起源 377 年**(川越・**山車 29 台 + 2005 国指定重要無形民俗 + UNESCO 無形 2016 構成**)。観客 100 万人/2 日、関東三大祭。",
    content_md:
      "- 立地:**川越市**\n- 起源:**1648 慶安元年・377 年**\n- 開催:**10 月第 3 土日(氷川神社例祭)**\n- 規模:**山車 29 台 + 観客 100 万人/2 日**\n- 認定:**2005 国指定重要無形民俗 + UNESCO 無形 2016「山・鉾・屋台行事」33 件構成**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "川越市",
    lg_code: "11201",
    area_types: ["festival_grounds"],
    lat: 35.9251,
    lon: 139.4858,
    season_start: "2026-10-15",
    season_end: "2026-10-19",
    event_start: "2026-10-17T13:00:00+09:00",
    event_end: "2026-10-18T22:00:00+09:00",
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia_ja: "https://ja.wikipedia.org/wiki/川越まつり",
    },
    tags: [
      "kawagoe_matsuri",
      "1648",
      "377_years",
      "2005_national",
      "unesco_2016",
    ],
    source: "manual",
  },

  // ─── 秩父文化 6 ───
  {
    slug: "chichibu-jinja",
    category: "culture",
    sub_type: "saitama_chichibu_culture",
    title_zh: "秩父神社(秩父市番場町・崇神天皇代 BC97-BC30 創建説 2000 年+ 武蔵國三大社の 1+ 秩父三社(秩父+三峯+宝登山)中核+ 1592 徳川家康再建本殿+ 国指定重要文化財・つなぎの龍 + 子宝育子の虎+ 秩父夜祭母社)",
    title_ja: "秩父神社",
    romaji: "Chichibu Jinja",
    summary_zh: "**秩父神社は崇神天皇代 BC97-BC30 創建説 2000 年・武蔵國三大社の 1**(秩父市番場町・**1592 徳川家康再建本殿 + 国指定重要文化財**)。秩父三社中核、つなぎの龍、夜祭母社。",
    content_md:
      "- 立地:**秩父市番場町**\n- 起源:**崇神天皇代 BC97-BC30 創建説 2000 年**\n- 認定:**国指定重要文化財(本殿)**\n- 本殿:**1592 徳川家康再建**\n- 並列:**武蔵國三大社 + 秩父三社(秩父 + 三峯 + 宝登山)中核**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "秩父市",
    lg_code: "11207",
    area_types: ["temple_shrine"],
    lat: 35.9978,
    lon: 139.0894,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.chichibu-jinja.or.jp/",
    },
    tags: ["chichibu_jinja", "musashi_three", "1592_ieyasu"],
    source: "manual",
  },
  {
    slug: "chichibu-yomatsuri-unesco-2016",
    category: "culture",
    sub_type: "saitama_chichibu_culture",
    title_zh: "秩父夜祭(秩父市番場町・12/2-3 秩父神社例祭・約 300 年伝統 1600 年代起源・2 大笠鉾 + 4 大屋台計 6 基+ 1962 国指定重要無形民俗+ UNESCO 無形文化遺産 2016「山・鉾・屋台行事」33 件構成・京都祇園 + 飛騨高山と並ぶ日本三大曳山祭・観客 30 万人 / 12/3 大祭日)",
    title_ja: "秩父夜祭",
    romaji: "Chichibu Yomatsuri",
    summary_zh: "**秩父夜祭は 12/2-3 秩父神社例祭・約 300 年伝統・2 大笠鉾 + 4 大屋台計 6 基**(秩父・**1962 国指定重要無形民俗 + UNESCO 無形 2016 構成**)。京都祇園+飛騨高山と並ぶ**日本三大曳山祭**、観客 30 万人/12/3。",
    content_md:
      "- 立地:**秩父市番場町(秩父神社例祭)**\n- 起源:**1600 年代・約 300 年伝統**\n- 開催:**12/2-3(12/3 が大祭)**\n- 規模:**2 大笠鉾 + 4 大屋台計 6 基 + 観客 30 万人/12/3**\n- 認定:**1962 国指定重要無形民俗 + UNESCO 無形 2016**\n- 並列:**日本三大曳山祭(京都祇園 + 飛騨高山 + 秩父)**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "秩父市",
    lg_code: "11207",
    area_types: ["festival_grounds"],
    lat: 35.9978,
    lon: 139.0894,
    season_start: "2026-11-25",
    season_end: "2026-12-04",
    event_start: "2026-12-03T18:00:00+09:00",
    event_end: "2026-12-03T23:00:00+09:00",
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia_ja: "https://ja.wikipedia.org/wiki/秩父夜祭",
    },
    tags: [
      "chichibu_yomatsuri",
      "1962_national",
      "unesco_2016",
      "japan_three_hikiyama",
    ],
    source: "manual",
  },
  {
    slug: "mitsumine-jinja-paws",
    category: "culture",
    sub_type: "saitama_chichibu_culture",
    title_zh: "三峯神社(秩父市三峰・景行天皇代日本武尊創建説・標高 1,100m 妙法ヶ岳麓+ 神犬眷属の三峯狼信仰+ 関東屈指のパワースポット+ 秩父三社の 1+ 国指定重要文化財拝殿+ R1 住 興雲閣宿坊・西武秩父駅 → バス 75 分)",
    title_ja: "三峯神社",
    romaji: "Mitsumine Jinja",
    summary_zh: "**三峯神社は景行天皇代日本武尊創建説・標高 1,100m 妙法ヶ岳麓・神犬眷属の三峯狼信仰**(秩父市三峰・**関東屈指のパワースポット + 秩父三社の 1**)。R1 住 興雲閣宿坊、西武秩父 → バス 75 分。",
    content_md:
      "- 立地:**埼玉県秩父市三峰 298-1**\n- 標高:**1,100m**\n- 起源:**景行天皇代日本武尊創建説**\n- 看板:**神犬眷属の三峯狼信仰 + 関東屈指のパワースポット**\n- 並列:**秩父三社(秩父神社 + 三峯神社 + 宝登山神社)**\n- 関連:**R1 住 興雲閣宿坊**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "秩父市",
    lg_code: "11207",
    area_types: ["temple_shrine", "mountain"],
    lat: 35.9239,
    lon: 138.9322,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.mitsuminejinja.or.jp/",
    },
    tags: ["mitsumine_jinja", "1100m", "powerspot", "ookami"],
    source: "manual",
  },
  {
    slug: "shibazakura-no-oka-hitsujiyama",
    category: "culture",
    sub_type: "saitama_chichibu_culture",
    title_zh: "芝桜の丘(秩父市羊山公園・1996 開園 29 年+ 9 種約 40 万株芝桜+ 4-5 月開花 GW 全盛・武甲山(1,304m)背景・秩父観光中核+ 入園 ¥300 + 開花期間限定 ¥500・観客 25 万人/シーズン)",
    title_ja: "芝桜の丘",
    romaji: "Shibazakura no Oka",
    summary_zh: "**芝桜の丘は 1996 開園 29 年・9 種約 40 万株芝桜**(秩父市羊山公園・**4-5 月開花 GW 全盛 + 武甲山背景**)。入園 ¥300(開花期 ¥500)、観客 25 万人/シーズン。",
    content_md:
      "- 立地:**秩父市羊山公園**\n- 起源:**1996 開園 29 年**\n- 規模:**9 種約 40 万株芝桜**\n- 開花:**4-5 月(GW 全盛)**\n- 入園:**¥300(開花期間 ¥500)**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "秩父市",
    lg_code: "11207",
    area_types: ["scenic_spot"],
    lat: 35.9914,
    lon: 139.0839,
    season_start: "2026-04-10",
    season_end: "2026-05-10",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shibazakura", "hitsujiyama", "1996", "400k_株"],
    source: "manual",
  },
  {
    slug: "chichibu-matsuri-kaikan",
    category: "culture",
    sub_type: "saitama_chichibu_culture",
    title_zh: "秩父まつり会館(秩父市番場町・1934 開館 91 年+ 秩父夜祭の 2 大笠鉾 + 4 大屋台展示・3D シアター夜祭再現+ 入館 ¥500 大人+ R1 育 秩父神社隣接・夜祭出演前後の屋台保管庫)",
    title_ja: "秩父まつり会館",
    romaji: "Chichibu Matsuri Kaikan",
    summary_zh: "**秩父まつり会館は 1934 開館 91 年・秩父夜祭の 2 大笠鉾 + 4 大屋台展示**(秩父市番場町・**3D シアター夜祭再現**)。入館 ¥500、R1 育 秩父神社隣接。",
    content_md:
      "- 立地:**秩父市番場町**\n- 開館:**1934・91 年**\n- 看板:**夜祭 6 基(2 大笠鉾 + 4 大屋台)展示 + 3D シアター**\n- 入館:**¥500 大人**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "秩父市",
    lg_code: "11207",
    area_types: ["museum_art"],
    lat: 35.9981,
    lon: 139.0867,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["tuesday"],
    external_urls: {},
    tags: ["matsuri_kaikan", "1934", "91_years"],
    source: "manual",
  },

  // ─── 行田・さきたま 3 ───
  {
    slug: "sakitama-kofun-gun",
    category: "culture",
    sub_type: "saitama_north_culture",
    title_zh: "さきたま古墳群(行田市埼玉・5-7 世紀 古墳時代 9 基大型古墳+ 1938 国指定史跡 + 2020 国特別史跡昇格・稲荷山古墳(120m 前方後円墳)・丸墓山古墳(直径 105m 円墳・全国最大級)・国宝鉄剣出土地+ 関東屈指の古墳群 + 「埼玉」県名発祥地)",
    title_ja: "さきたま古墳群",
    romaji: "Sakitama Kofun Gun",
    summary_zh: "**さきたま古墳群は 5-7 世紀古墳時代 9 基大型古墳・1938 国指定史跡 + 2020 国特別史跡昇格**(行田市埼玉・**稲荷山 120m + 丸墓山 105m 全国最大級**)。**「埼玉」県名発祥地** + 国宝鉄剣出土地、関東屈指。",
    content_md:
      "- 立地:**行田市埼玉**\n- 時代:**5-7 世紀古墳時代**\n- 規模:**9 基大型古墳(稲荷山 120m 前方後円墳 + 丸墓山 直径 105m 円墳全国最大級)**\n- 認定:**1938 国指定史跡 + 2020 国特別史跡昇格**\n- 由来:**「埼玉」県名発祥地**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "行田市",
    lg_code: "11206",
    area_types: ["history_site_castle"],
    lat: 36.1267,
    lon: 139.4789,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia_ja: "https://ja.wikipedia.org/wiki/埼玉古墳群",
    },
    tags: [
      "sakitama_kofun",
      "1938_national",
      "2020_special",
      "9_kofun",
      "saitama_origin",
    ],
    source: "manual",
  },
  {
    slug: "inariyama-kofun-tekken-kokuho",
    category: "culture",
    sub_type: "saitama_north_culture",
    title_zh: "稲荷山古墳出土鉄剣(行田市・5 世紀後半雄略天皇代金錯銘鉄剣+ 1968 出土・1983 国宝指定・全長 73.5cm 表裏 115 文字漢字象嵌・古事記日本書紀以前 漢字記紀発祥資料・「獲加多支鹵大王」記載+ 県立さきたま史跡の博物館展示)",
    title_ja: "稲荷山古墳出土鉄剣",
    romaji: "Inariyama Tekken",
    summary_zh: "**稲荷山古墳出土鉄剣は 5 世紀後半・1968 出土・1983 国宝指定**(行田・**全長 73.5cm 表裏 115 文字漢字象嵌**)。**「獲加多支鹵大王」雄略天皇記載 + 古事記以前漢字記紀発祥資料**、さきたま史跡博物館展示。",
    content_md:
      "- 立地:**行田市・県立さきたま史跡の博物館展示**\n- 時代:**5 世紀後半雄略天皇代**\n- 出土:**1968(稲荷山古墳礫槨)**\n- 認定:**1983 国宝**\n- 規模:**全長 73.5cm + 表裏 115 文字漢字象嵌**\n- 史的価値:**「獲加多支鹵大王」雄略天皇記載 + 漢字記紀発祥資料**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "行田市",
    lg_code: "11206",
    area_types: ["museum_art", "history_site_castle"],
    lat: 36.1267,
    lon: 139.4789,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["monday"],
    external_urls: {
      wikipedia_ja: "https://ja.wikipedia.org/wiki/稲荷山古墳出土鉄剣",
    },
    tags: ["inariyama_tekken", "1968", "1983_kokuho", "wakatakeru_okimi"],
    source: "manual",
  },
  {
    slug: "gyoda-oshijou",
    category: "culture",
    sub_type: "saitama_north_culture",
    title_zh: "忍城(行田市本丸・1478 文明 10 年成田顕泰築城 547 年+ 関東七名城 + 浮き城・1590 石田三成水攻も落ちず・「のぼうの城」モデル・1973 模擬御三階櫓再建・郷土博物館入館 ¥200・R1 衣 行田足袋+ R1 育 さきたま古墳群 観光連動)",
    title_ja: "忍城",
    romaji: "Oshi Jō",
    summary_zh: "**忍城は 1478 文明 10 年成田顕泰築城 547 年・関東七名城 + 浮き城**(行田・**1590 石田水攻も落ちず・「のぼうの城」モデル**)。1973 模擬御三階櫓再建、入館 ¥200、R1 衣+育 連動。",
    content_md:
      "- 立地:**行田市本丸**\n- 築城:**1478 文明 10 年成田顕泰・547 年**\n- 別名:**関東七名城 + 浮き城**\n- 看板:**1590 石田三成水攻も落ちず・「のぼうの城」モデル**\n- 再建:**1973 模擬御三階櫓**\n- 入館:**¥200(郷土博物館)**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "行田市",
    lg_code: "11206",
    area_types: ["history_site_castle"],
    lat: 36.1397,
    lon: 139.4544,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["monday"],
    external_urls: {
      wikipedia_ja: "https://ja.wikipedia.org/wiki/忍城",
    },
    tags: ["oshi_jou", "1478", "547_years", "ukijiro", "ishida_mizuzeme_1590"],
    source: "manual",
  },

  // ─── さいたま市 2 ───
  {
    slug: "omiya-hikawa-jinja",
    category: "culture",
    sub_type: "saitama_central_culture",
    title_zh: "武蔵一宮 氷川神社(さいたま市大宮区・第 5 代孝昭天皇代 約 BC473 創建説 約 2500 年+ 武蔵國一宮 + 全国 280+ 氷川神社の総本社+ 大宮の地名由来・国指定重要文化財楼門 1940・初詣 200 万人 関東屈指)",
    title_ja: "武蔵一宮 氷川神社",
    romaji: "Hikawa Jinja",
    summary_zh: "**武蔵一宮 氷川神社は約 BC473 創建説 約 2500 年・武蔵國一宮 + 全国 280+ 氷川神社の総本社**(さいたま市大宮区・**大宮の地名由来**)。1940 国指定重要文化財楼門、初詣 200 万人。",
    content_md:
      "- 立地:**さいたま市大宮区**\n- 起源:**約 BC473 第 5 代孝昭天皇代・約 2500 年**\n- 認定:**武蔵國一宮 + 全国 280+ 氷川神社総本社 + 1940 国指定重要文化財楼門**\n- 由来:**「大宮」の地名由来**\n- 初詣:**200 万人 関東屈指**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "さいたま市大宮区",
    lg_code: "11100",
    area_types: ["temple_shrine"],
    lat: 35.9173,
    lon: 139.6298,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://musashiichinomiya-hikawa.or.jp/",
    },
    tags: ["hikawa", "musashi_ichinomiya", "280_total_shrine", "omiya_origin"],
    source: "manual",
  },
  {
    slug: "urawa-tsuki-jinja",
    category: "culture",
    sub_type: "saitama_central_culture",
    title_zh: "調神社・つきのみや(さいたま市浦和区・崇神天皇代 BC97-BC30 創建説 + 1900 年代以降「ウサギ神社」観光化・調神社七不思議+ 鳥居なし・松なし・狛兎+ 浦和うさぎ観光中核+ R1 食 浦和うなぎ 観光連動・初詣 30 万人)",
    title_ja: "調神社",
    romaji: "Tsuki Jinja",
    summary_zh: "**調神社は崇神天皇代 BC97-BC30 創建説・1900 年代以降「ウサギ神社」観光化**(さいたま市浦和区・**七不思議:鳥居なし + 松なし + 狛兎**)。R1 食 浦和うなぎ連動、初詣 30 万人。",
    content_md:
      "- 立地:**さいたま市浦和区**\n- 起源:**崇神天皇代 BC97-BC30 創建説**\n- 別名:**ウサギ神社**\n- 七不思議:**鳥居なし + 松なし + 狛兎(犬ではなく)**\n- 関連:**R1 食 浦和うなぎ**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "さいたま市浦和区",
    lg_code: "11100",
    area_types: ["temple_shrine"],
    lat: 35.853,
    lon: 139.6481,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["tsuki_jinja", "rabbit_shrine", "seven_mysteries"],
    source: "manual",
  },

  // ─── その他 4 ───
  {
    slug: "hachigata-jou-yorii",
    category: "culture",
    sub_type: "saitama_north_culture",
    title_zh: "鉢形城(大里郡寄居町・1476 文明 8 年長尾景春築城 549 年+ 北条氏邦 1564 入城・荒川 + 深沢川天険利用の典型山城・1932 国指定史跡 + 続日本 100 名城 18 番・鉢形城歴史館 入館 ¥200)",
    title_ja: "鉢形城",
    romaji: "Hachigata Jō",
    summary_zh: "**鉢形城は 1476 長尾景春築城 549 年・北条氏邦 1564 入城**(寄居町・**荒川+深沢川天険利用 + 1932 国指定史跡 + 続日本 100 名城 18 番**)。歴史館 ¥200。",
    content_md:
      "- 立地:**大里郡寄居町**\n- 築城:**1476 文明 8 年長尾景春・549 年**\n- 入城:**北条氏邦 1564**\n- 認定:**1932 国指定史跡 + 続日本 100 名城 18 番**\n- 入館:**¥200(歴史館)**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: "大里郡",
    municipality_ja: "寄居町",
    lg_code: "11408",
    area_types: ["history_site_castle"],
    lat: 36.1108,
    lon: 139.1939,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["monday"],
    external_urls: {
      wikipedia_ja: "https://ja.wikipedia.org/wiki/鉢形城",
    },
    tags: ["hachigata_jou", "1476", "549_years", "1932_national", "100castle_18"],
    source: "manual",
  },
  {
    slug: "washinomiya-jinja-kuki",
    category: "culture",
    sub_type: "saitama_east_culture",
    title_zh: "鷲宮神社(久喜市鷲宮・神武天皇代 BC660-BC585 創建説 関東最古+ 武蔵國二之宮 + 出雲族関東開拓神拠点・2007 アニメ「らき☆すた」舞台聖地巡礼発祥地+ 初詣 47 万人 県内 3 位・国登録有形文化財拝殿)",
    title_ja: "鷲宮神社",
    romaji: "Washinomiya Jinja",
    summary_zh: "**鷲宮神社は神武天皇代 BC660-BC585 創建説・関東最古・武蔵國二之宮**(久喜市鷲宮・**2007 アニメ「らき☆すた」舞台 = 聖地巡礼発祥地**)。初詣 47 万人県内 3 位。",
    content_md:
      "- 立地:**久喜市鷲宮**\n- 起源:**神武天皇代 BC660-BC585 創建説 関東最古**\n- 看板:**武蔵國二之宮 + 出雲族関東開拓神拠点**\n- 文化現象:**2007 アニメ「らき☆すた」舞台 = 聖地巡礼発祥地**\n- 認定:**国登録有形文化財拝殿**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "久喜市",
    lg_code: "11232",
    area_types: ["temple_shrine"],
    lat: 36.1158,
    lon: 139.6711,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia_ja: "https://ja.wikipedia.org/wiki/鷲宮神社",
    },
    tags: ["washinomiya", "kanto_oldest", "lucky_star_2007"],
    source: "manual",
  },
  {
    slug: "toyama-kinenkan-kawajima",
    category: "culture",
    sub_type: "saitama_central_culture",
    title_zh: "遠山記念館(比企郡川島町・1936 完成 89 年+ 日興證券創業者遠山元一邸宅+ 国登録有形文化財建造物 9 棟・3 棟形式の数寄屋造大邸宅・東洋古美術品 4500 点コレクション・国宝 + 国指定重要文化財含・入館 ¥1,000)",
    title_ja: "遠山記念館",
    romaji: "Tōyama Kinenkan",
    summary_zh: "**遠山記念館は 1936 完成 89 年・日興證券創業者遠山元一邸宅**(川島町・**国登録有形文化財建造物 9 棟 + 3 棟形式数寄屋造**)。東洋古美術品 4500 点(国宝含)、入館 ¥1,000。",
    content_md:
      "- 立地:**比企郡川島町**\n- 起源:**1936 完成 89 年**\n- 由来:**日興證券創業者遠山元一邸宅**\n- 認定:**国登録有形文化財建造物 9 棟 + 3 棟形式数寄屋造大邸宅**\n- 蔵品:**東洋古美術品 4500 点 + 国宝 + 国指定重要文化財含**\n- 入館:**¥1,000**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: "比企郡",
    municipality_ja: "川島町",
    lg_code: "11346",
    area_types: ["museum_art", "history_site_castle"],
    lat: 35.9772,
    lon: 139.4717,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: ["monday"],
    external_urls: {
      official: "https://www.e-kinenkan.com/",
    },
    tags: ["toyama_kinenkan", "1936", "nikko_securities", "4500_collection"],
    source: "manual",
  },
  {
    slug: "hanno-noninji",
    category: "culture",
    sub_type: "saitama_west_culture",
    title_zh: "能仁寺(飯能市飯能・1501 文亀元年中山家範開基 524 年+ 曹洞宗+ 飯能市指定文化財池泉回遊式庭園・1868 戊辰戦争「飯能戦争」振武軍激戦地+ 池泉庭園入園 ¥300+ 天覧山(195m)登山口隣接)",
    title_ja: "能仁寺",
    romaji: "Nōninji",
    summary_zh: "**能仁寺は 1501 文亀元年中山家範開基 524 年・曹洞宗・池泉回遊式庭園**(飯能市・**1868 戊辰戦争「飯能戦争」振武軍激戦地**)。庭園入園 ¥300、天覧山登山口隣接。",
    content_md:
      "- 立地:**飯能市飯能**\n- 起源:**1501 文亀元年中山家範開基 524 年**\n- 宗派:**曹洞宗**\n- 看板:**池泉回遊式庭園(飯能市指定文化財)**\n- 史跡:**1868 戊辰戦争「飯能戦争」振武軍激戦地**\n- 入園:**¥300**",
    region: "kanto",
    prefecture_ja: "埼玉県",
    gun_ja: null,
    municipality_ja: "飯能市",
    lg_code: "11209",
    area_types: ["temple_shrine"],
    lat: 35.8533,
    lon: 139.3253,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nooninji", "1501", "524_years", "hanno_war_1868"],
    source: "manual",
  },
];

seedMain(rows, "saitama-culture-r1");
