// Seed 徳島県 R3 補完(20 筆 / Sprint 3.x / 第十六卷)
// 食 5 / 衣 3 / 住 3 / 育 3 / 楽 4 / 行 2 = 20 累積 142 + 20 = 162
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  {
    slug: "awa-mikan-kanten",
    category: "food", sub_type: "tokushima_fruit",
    title_zh: "阿波みかん+柚子+はっさく(阿南市+ 那賀+ 牟岐・1900 年代以降柑橘産地化 100+ 年+ R1 食 すだち並ぶ徳島柑橘・「阿波みかん」+「阿南はっさく」・¥800-2,500/kg)",
    title_ja: "阿波みかん", romaji: "Awa Mikan",
    summary_zh: "**阿波みかん+柚子+はっさくは 1900 年代以降 100+ 年・R1 食 すだち並ぶ徳島柑橘・「阿波みかん」+「阿南はっさく」**(阿南+那賀+牟岐)。¥800-2,500/kg。",
    content_md: "- 立地:**阿南市 + 那賀町 + 牟岐町**\n- 起源:**1900 年代以降柑橘産地化 100+ 年**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "阿南市", lg_code: "36204",
    area_types: ["farm_field"], lat: 33.9217, lon: 134.6594,
    season_start: "2026-11-01", season_end: "2027-02-28", event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["awa_mikan"], source: "manual",
  },
  {
    slug: "naruto-tai-meshi",
    category: "food", sub_type: "tokushima_seafood",
    title_zh: "鳴門鯛飯+ 鯛茶漬け(鳴門市+ 全県・R1 食 鳴門鯛派生・「鳴門鯛飯」郷土料理+ 鳴門海峡桜鯛+寒鯛・1 食 ¥2,500-5,500・国際 SNS 海外旅行者代表)",
    title_ja: "鳴門鯛飯", romaji: "Naruto Tai Meshi",
    summary_zh: "**鳴門鯛飯+鯛茶漬けは R1 食 派生・「鳴門鯛飯」郷土料理・鳴門海峡桜鯛+寒鯛**(鳴門+全県)。¥2,500-5,500、海外代表。",
    content_md: "- 立地:**鳴門市 + 全県**\n- 関連:**R1 食 鳴門鯛派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202",
    area_types: ["restaurant_traditional"], lat: 34.1722, lon: 134.6086,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["naruto_tai_meshi"], source: "manual",
  },
  {
    slug: "iya-bussinkin",
    category: "food", sub_type: "tokushima_seibu_food",
    title_zh: "祖谷物産+ 大歩危祖谷弁当(三好市祖谷+ 大歩危・R1 食 祖谷そば+山菜岩魚派生・「祖谷弁当」+「大歩危ボックス」+ 山菜+鹿肉+岩魚詰め合わせ・¥1,500-3,500・JR 大歩危駅売店+道の駅大歩危)",
    title_ja: "祖谷弁当", romaji: "Iya Bento",
    summary_zh: "**祖谷物産+大歩危祖谷弁当は R1 食 そば+山菜派生・「祖谷弁当」+「大歩危ボックス」・山菜+鹿肉+岩魚詰合わせ**(三好祖谷+大歩危)。¥1,500-3,500。",
    content_md: "- 立地:**三好市祖谷 + 大歩危**\n- 関連:**R1 食 祖谷そば + 山菜岩魚派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 33.8728, lon: 133.8019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["iya_bento"], source: "manual",
  },
  {
    slug: "udatsu-machi-wagashi",
    category: "food", sub_type: "tokushima_seibu_food",
    title_zh: "美馬うだつ町並み和菓子(美馬市脇町+ つるぎ・R2 育 うだつ町並み 1988 派生・「うだつ饅頭」+「藍染最中」+ 江戸期豪商屋敷併設老舗 6+ 軒・¥350-1,500・国際 SNS 海外伝統菓子代表)",
    title_ja: "うだつ町和菓子", romaji: "Udatsu Wagashi",
    summary_zh: "**美馬うだつ町並み和菓子は R2 育 1988 派生・「うだつ饅頭」+「藍染最中」+江戸期豪商老舗 6+ 軒**(美馬脇町+つるぎ)。¥350-1,500、海外代表。",
    content_md: "- 立地:**美馬市脇町 + つるぎ町**\n- 関連:**R2 育 うだつの町並み 1988 派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "美馬市", lg_code: "36207",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 34.0500, lon: 134.0167,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["udatsu_wagashi"], source: "manual",
  },
  {
    slug: "kaiyo-moika-products",
    category: "food", sub_type: "tokushima_nanbu_food",
    title_zh: "海陽町モイカ加工品+ 干物(海部郡海陽町+ 牟岐+ 美波・R1 楽 海陽モイカ祭派生・「モイカ」(アオリイカ)干物+ 一夜干し+ アヒージョ・¥800-3,500/袋・道の駅+JR 牟岐駅売店)",
    title_ja: "海陽モイカ加工", romaji: "Kaiyo Moika Products",
    summary_zh: "**海陽町モイカ加工品+干物は R1 楽 派生・「モイカ」干物+一夜干し+アヒージョ**(海陽+牟岐+美波)。¥800-3,500/袋、道の駅+JR 牟岐。",
    content_md: "- 立地:**海部郡海陽町 + 牟岐町 + 美波町**\n- 関連:**R1 楽 海陽モイカ祭派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "海部郡", municipality_ja: "海陽町", lg_code: "36388",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 33.5333, lon: 134.3000,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["moika_products"], source: "manual",
  },
  {
    slug: "awa-odori-ren-aparel",
    category: "fashion", sub_type: "tokushima_dento",
    title_zh: "阿波踊り連別装束+ 有名連揃え(全県・R1 衣 阿波踊り装束 1981 派生・連 1000+ 軒+ 「阿呆連」「娯茶平」「うずき連」 30+ 有名連各別オリジナル装束+ 連入会記念装束・¥9,500-65,000)",
    title_ja: "阿波踊り連別", romaji: "Awa Ren Aparel",
    summary_zh: "**阿波踊り連別装束+有名連揃えは R1 衣 1981 派生・連 1000+ 軒・「阿呆連」+「娯茶平」+「うずき連」 30+ 有名連オリジナル装束**(全県)。¥9,500-65,000。",
    content_md: "- 立地:**全県**\n- 関連:**R1 衣 阿波踊り装束 1981 派生**\n- 規模:**連 1000+ 軒 + 30+ 有名連各別オリジナル装束**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["industrial_heritage", "shopping_district"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["awa_ren_aparel"], source: "manual",
  },
  {
    slug: "naka-washi",
    category: "fashion", sub_type: "tokushima_nanbu_clothing",
    title_zh: "那賀町和紙+ 阿波和紙(那賀郡那賀町+ 上勝・1990 年代以降阿波和紙復興 35+ 年+ R1 衣 阿波太布 1973 並ぶ伝統工芸+ 楮和紙+ 阿波青藍染和紙・¥1,500-9,500/枚)",
    title_ja: "那賀和紙", romaji: "Naka Washi",
    summary_zh: "**那賀町和紙+阿波和紙は 1990 年代以降復興 35+ 年・R1 衣 太布並ぶ伝統工芸・楮和紙+阿波青藍染和紙**(那賀+上勝)。¥1,500-9,500/枚。",
    content_md: "- 立地:**那賀郡那賀町 + 上勝町**\n- 関連:**R1 衣 阿波太布 1973 並ぶ伝統工芸**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "那賀郡", municipality_ja: "那賀町", lg_code: "36368",
    area_types: ["industrial_heritage"], lat: 33.9000, lon: 134.3000,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["naka_washi"], source: "manual",
  },
  {
    slug: "iya-heike-armor",
    category: "fashion", sub_type: "tokushima_seibu_clothing",
    title_zh: "祖谷平家屋敷+ 鎧兜模型展示(三好市祖谷+ 大歩危・R1 衣 祖谷平家落人観光着 R1 派生・「東祖谷平家屋敷民俗資料館」 1985+ 平家落人 12 名鎧兜+ 武具+ 衣装複製展示・¥510)",
    title_ja: "平家屋敷", romaji: "Heike Yashiki",
    summary_zh: "**祖谷平家屋敷+鎧兜模型展示は R1 衣 派生・「東祖谷平家屋敷民俗資料館」 1985・平家落人 12 名鎧兜+武具+衣装複製**(三好祖谷+大歩危)。¥510。",
    content_md: "- 立地:**三好市祖谷 + 大歩危**\n- 関連:**R1 衣 祖谷平家落人観光着派生**\n- 起源:**「東祖谷平家屋敷民俗資料館」 1985**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208",
    area_types: ["museum_art", "history_site_castle"], lat: 33.8728, lon: 133.8019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["heike_yashiki_1985"], source: "manual",
  },
  {
    slug: "udatsu-machi-bnb",
    category: "lodging", sub_type: "tokushima_seibu_lodging",
    title_zh: "美馬うだつの町並み古民家ステイ+ 「あい染の宿」(美馬市脇町+ つるぎ町貞光・R2 住 うだつ古民家民泊+R2 育 うだつ 1988 派生・1900 年代以降豪商屋敷ステイ+ 藍染体験+ ¥18,000-45,000/泊)",
    title_ja: "うだつ町ステイ", romaji: "Udatsu Stay",
    summary_zh: "**美馬うだつ町並み古民家ステイ+「あい染の宿」は R2 住+R2 育 派生・1900 年代以降豪商屋敷ステイ+藍染体験**(美馬脇町+つるぎ貞光)。¥18,000-45,000/泊。",
    content_md: "- 立地:**美馬市脇町 + つるぎ町貞光**\n- 関連:**R2 住 うだつ古民家 + R2 育 うだつ町並み 1988 派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "美馬市", lg_code: "36207",
    area_types: ["accommodation_ryokan", "history_site_castle"], lat: 34.0500, lon: 134.0167,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["udatsu_stay"], source: "manual",
  },
  {
    slug: "kaiyo-pension",
    category: "lodging", sub_type: "tokushima_nanbu_lodging",
    title_zh: "海陽町ペンション+ サーフ宿(海部郡海陽町大里+ 美波・R1 楽 阿南海陽サーフ+R2 住 海陽うみがめテラス派生・1980 年代以降サーファー向ペンション 45+ 年+ 民泊 8+ 軒・¥7,500-15,000/泊)",
    title_ja: "海陽サーフペンション", romaji: "Kaiyo Surf",
    summary_zh: "**海陽町ペンション+サーフ宿は R1 楽+R2 住 派生・1980 年代以降サーファー向 45+ 年・民泊 8+ 軒**(海陽大里+美波)。¥7,500-15,000/泊。",
    content_md: "- 立地:**海部郡海陽町大里 + 美波町**\n- 関連:**R1 楽 阿南海陽サーフ + R2 住 海陽うみがめテラス派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "海部郡", municipality_ja: "海陽町", lg_code: "36388",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 33.5333, lon: 134.3000,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kaiyo_pension"], source: "manual",
  },
  {
    slug: "kamiyama-eyenokawa",
    category: "lodging", sub_type: "tokushima_tobu_lodging",
    title_zh: "神山町「えんがわオフィス」+ アーティスト民泊(名西郡神山町・R1 楽 神山クリエイティブツアー派生・1999 神山 AIR 創設 26+ 年+ サテライトオフィス民泊+ 古民家リノベ 8+ 軒・¥9,500-22,000/泊+ 国際 SNS 海外クリエイター代表)",
    title_ja: "神山えんがわ", romaji: "Kamiyama Engawa",
    summary_zh: "**神山町「えんがわオフィス」+アーティスト民泊は R1 楽 派生・1999 神山 AIR 26+ 年・サテライト民泊+古民家リノベ 8+ 軒**(神山)。¥9,500-22,000/泊、海外クリエイター代表。",
    content_md: "- 立地:**名西郡神山町**\n- 関連:**R1 楽 神山クリエイティブツアー派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "名西郡", municipality_ja: "神山町", lg_code: "36341",
    area_types: ["accommodation_ryokan"], lat: 33.9486, lon: 134.3608,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kamiyama_engawa"], source: "manual",
  },
  {
    slug: "anan-led-museum",
    category: "culture", sub_type: "tokushima_nanbu_culture",
    title_zh: "阿南日亜化学+ 中村修二青色 LED 記念館(阿南市羽ノ浦+ 那賀川・R1 衣 阿南 LED 1959 派生・1959 日亜化学工業創業 66+ 年+ 中村修二 2014 ノーベル物理学賞・「阿南 LED 記念館」 2015+ 産業観光ツアー・観覧無料)",
    title_ja: "阿南 LED 記念館", romaji: "Anan LED Memorial",
    summary_zh: "**阿南日亜化学+中村修二青色 LED 記念館は R1 衣 1959 派生・1959 日亜創業 66+ 年・中村修二 2014 ノーベル・「阿南 LED 記念館」 2015**(阿南羽ノ浦)。観覧無料。",
    content_md: "- 立地:**阿南市羽ノ浦 + 那賀川**\n- 関連:**R1 衣 阿南 LED 1959 派生**\n- 起源:**「阿南 LED 記念館」 2015 + 中村修二 2014 ノーベル物理学賞**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "阿南市", lg_code: "36204",
    area_types: ["museum_art", "industrial_heritage"], lat: 33.9217, lon: 134.6594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: 30, closed_days: ["sunday"],
    external_urls: {}, tags: ["anan_led_memorial_2015"], source: "manual",
  },
  {
    slug: "iwaya-jinja-shrine",
    category: "culture", sub_type: "tokushima_shrine_temple",
    title_zh: "岩屋寺+ 阿波七霊峰(三好市東祖谷+ 阿波・四国八十八札所外+ 「阿波七霊峰」 古代山岳信仰 1500+ 年・剣山+焼山+雲辺寺山並ぶ阿波山岳霊場・参拝無料)",
    title_ja: "岩屋寺+七霊峰", romaji: "Iwaya 7 Ryōhō",
    summary_zh: "**岩屋寺+阿波七霊峰は四国 88 札所外・「阿波七霊峰」古代山岳信仰 1500+ 年・剣山+焼山+雲辺寺山並ぶ阿波山岳霊場**(三好東祖谷+阿波)。参拝無料。",
    content_md: "- 立地:**三好市東祖谷 + 阿波市**\n- 起源:**古代山岳信仰 1500+ 年**\n- 認定:**「阿波七霊峰」 + 剣山 + 焼山 + 雲辺寺山並ぶ阿波山岳霊場**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208",
    area_types: ["history_site_castle", "nature_park"], lat: 33.8728, lon: 133.8019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["awa_7_ryōhō"], source: "manual",
  },
  {
    slug: "anan-uminohi-museum",
    category: "culture", sub_type: "tokushima_nanbu_culture",
    title_zh: "阿南橘湾漁業文化記念館+ 海と灯台(阿南市椿+ 牟岐・1900 年代以降阿南漁業 100+ 年+ R1 食 阿南橘湾朝市派生・椿泊漁業協同組合資料+ 椿崎灯台 1893+ 海軍航空隊跡地・観覧 ¥200)",
    title_ja: "阿南漁業記念館", romaji: "Anan Fishing",
    summary_zh: "**阿南橘湾漁業文化記念館+海と灯台は 1900 年代以降漁業 100+ 年・R1 食派生・椿泊漁協資料+椿崎灯台 1893+海軍航空隊跡地**(阿南椿+牟岐)。¥200。",
    content_md: "- 立地:**阿南市椿 + 牟岐町**\n- 関連:**R1 食 阿南橘湾朝市派生**\n- 認定:**椿崎灯台 1893 + 海軍航空隊跡地**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "阿南市", lg_code: "36204",
    area_types: ["museum_art", "history_site_castle"], lat: 33.9217, lon: 134.6594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["anan_fishing_museum"], source: "manual",
  },
  {
    slug: "naruto-german-fest",
    category: "entertainment", sub_type: "tokushima_tobu_entertainment",
    title_zh: "鳴門ドイツ館「第九」演奏会+ ベートーヴェン記念(鳴門市大麻町・R1 育 鳴門ドイツ館 1972 派生・1918 第九日本初演記念・毎年 6 月「ベートーヴェン第九」演奏会+ 12 月年末第九演奏・¥1,500-3,500・国際 SNS 海外音楽ファン代表)",
    title_ja: "ドイツ館第九", romaji: "German Daiku",
    summary_zh: "**鳴門ドイツ館「第九」演奏会+ベートーヴェン記念は R1 育 1972 派生・1918 第九日本初演記念・毎年 6 月+12 月年末「第九」**(鳴門大麻)。¥1,500-3,500、海外音楽代表。",
    content_md: "- 立地:**鳴門市大麻町**\n- 関連:**R1 育 鳴門ドイツ館 1972 派生**\n- 起源:**1918 「ベートーヴェン第九」全国初日本初演**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202",
    area_types: ["theme_park", "history_site_castle"], lat: 34.1722, lon: 134.6086,
    season_start: null, season_end: null, event_start: "2026-06-04T19:00:00+09:00", event_end: "2026-06-04T21:30:00+09:00",
    price_tier: 3, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["german_daiku"], source: "manual",
  },
  {
    slug: "kamiyama-art-village-fest",
    category: "entertainment", sub_type: "tokushima_tobu_entertainment",
    title_zh: "神山アート祭+ 里山アートビレッジ(名西郡神山町・R1 楽 神山クリエイティブツアー+R1 衣 神山 2010 派生・「神山アーティストインレジデンス」 1999+ アート祭+ 里山アートインスタレーション・参加無料)",
    title_ja: "神山アート祭", romaji: "Kamiyama Art Fest",
    summary_zh: "**神山アート祭+里山アートビレッジは R1 楽+R1 衣 派生・「神山 AIR」 1999+アート祭+里山アートインスタレーション**(神山)。参加無料。",
    content_md: "- 立地:**名西郡神山町**\n- 関連:**R1 楽 神山クリエイティブツアー + R1 衣 神山 2010 派生**\n- 起源:**「神山アーティストインレジデンス」 1999**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "名西郡", municipality_ja: "神山町", lg_code: "36341",
    area_types: ["museum_art"], lat: 33.9486, lon: 134.3608,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kamiyama_art_fest"], source: "manual",
  },
  {
    slug: "minami-umigame-night",
    category: "entertainment", sub_type: "tokushima_nanbu_entertainment",
    title_zh: "美波町大浜海岸+ ウミガメ夜間観察会(海部郡美波町日和佐・R1 楽 うみがめ博物館 1985+R1 楽 美波町うみがめプロジェクト派生・5-8 月夜間ウミガメ産卵観察会+ 大浜海岸国天記 1972・¥800/人・国際 SNS 海外自然愛好者代表)",
    title_ja: "うみがめ夜間観察", romaji: "Umigame Night",
    summary_zh: "**美波町大浜海岸+ウミガメ夜間観察会は R1 楽 派生・5-8 月夜間ウミガメ産卵観察+大浜海岸国天記 1972**(美波日和佐)。¥800、海外自然代表。",
    content_md: "- 立地:**海部郡美波町日和佐**\n- 関連:**R1 楽 うみがめ博物館 1985 + 大浜海岸国天記 1972 派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "海部郡", municipality_ja: "美波町", lg_code: "36383",
    area_types: ["beach_coast", "nature_park"], lat: 33.7311, lon: 134.5306,
    season_start: "2026-05-01", season_end: "2026-08-31", event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["umigame_night"], source: "manual",
  },
  {
    slug: "iya-hotaru-river",
    category: "entertainment", sub_type: "tokushima_seibu_entertainment",
    title_zh: "三好祖谷+ 大歩危ホタル観賞(三好市東祖谷+ 大歩危・R1 育 祖谷渓 1964 派生・6 月源氏ホタル+平家ホタル乱舞・祖谷川+ 大歩危川辺観賞会・参加無料・国際 SNS 海外自然代表)",
    title_ja: "祖谷ホタル", romaji: "Iya Hotaru",
    summary_zh: "**三好祖谷+大歩危ホタル観賞は R1 育 派生・6 月源氏+平家ホタル乱舞・祖谷川+大歩危川辺**(三好東祖谷+大歩危)。参加無料、海外代表。",
    content_md: "- 立地:**三好市東祖谷 + 大歩危**\n- 関連:**R1 育 祖谷渓 1964 派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208",
    area_types: ["nature_park"], lat: 33.8728, lon: 133.8019,
    season_start: "2026-06-01", season_end: "2026-06-30", event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["iya_hotaru"], source: "manual",
  },
  {
    slug: "anan-coast-bus",
    category: "transport", sub_type: "tokushima_nanbu_transport",
    title_zh: "阿南市バス+ 沿岸シャトル(阿南市・R1 行 JR 牟岐線+ 海陽コミュニティ派生・1965 阿南市バス開業 60+ 年+ 4 路線+ R1 食 阿南橘湾朝市+R1 楽 阿南光フェスタアクセス・¥220-510/片道)",
    title_ja: "阿南市バス", romaji: "Anan Bus",
    summary_zh: "**阿南市バス+沿岸シャトルは R1 行+R3 行 派生・1965 開業 60+ 年・4 路線・R1 食 朝市+R1 楽 光フェスタアクセス**(阿南)。¥220-510/片道。",
    content_md: "- 立地:**阿南市**\n- 関連:**R1 行 JR 牟岐線 + 海陽コミュニティ派生**\n- 起源:**1965 阿南市バス開業 60+ 年**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "阿南市", lg_code: "36204",
    area_types: ["transport_hub"], lat: 33.9217, lon: 134.6594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["anan_bus_1965"], source: "manual",
  },
  {
    slug: "naka-katsuura-shuttle",
    category: "transport", sub_type: "tokushima_nanbu_transport",
    title_zh: "那賀川沿岸シャトル+ 山中バス(那賀郡那賀町+ 勝浦町+ 上勝・R1 行 那賀コミュニティ派生・那賀川流域山中シャトル+ R1 楽 那賀ラフティング+R1 楽 上勝ゼロウェイスト見学+ 山中宿泊者送迎・¥190-650/片道)",
    title_ja: "那賀山中シャトル", romaji: "Naka Mountain Shuttle",
    summary_zh: "**那賀川沿岸シャトル+山中バスは R1 行 派生・那賀川流域山中シャトル+R1 楽 ラフティング+ゼロウェイスト見学+山中宿泊送迎**(那賀+勝浦+上勝)。¥190-650/片道。",
    content_md: "- 立地:**那賀郡那賀町 + 勝浦町 + 上勝町**\n- 関連:**R1 行 那賀コミュニティ + R1 楽 那賀ラフティング + R1 楽 上勝ゼロウェイスト派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "那賀郡", municipality_ja: "那賀町", lg_code: "36368",
    area_types: ["transport_hub"], lat: 33.9000, lon: 134.3000,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["naka_katsuura_shuttle"], source: "manual",
  },
];

seedMain(rows, "tokushima-r3");
