// Seed 茨城県 食 R1(25 筆 / Sprint 1.1 / 第〇八卷 開卷)
//
// 茨城 3 大名物 5(水戸納豆+鮟鱇+メロン+干し芋+蓮根) /
// 郷土食 4 / 海産+霞ヶ浦 3 / 果実 3 / 銘菓 5 / 酒 3 / 米果 2 = 25

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "茨城県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 茨城 3 大名物 (5)
  { slug: "mito-natto-no1-japan", category: "food", sub_type: "ibaraki_3_meibutsu", title_zh: "水戸納豆(水戸市・全国納豆生産量 No.1 県・40% シェア+ 江戸期 1700 年代水戸藩献上+ 「水戸天狗納豆」「だるま食品」老舗 5+ 軒+ R1 育 偕楽園 1842 観光客向け定番土産+ 水戸駅売店+全国百貨店流通+ 1 パック ¥150-400)", title_ja: "水戸納豆", romaji: "Mito Nattō", summary_zh: "**水戸納豆は全国納豆生産量 No.1 県・40% シェア**(水戸市・**江戸期 1700 年代水戸藩献上**)。「水戸天狗納豆」+「だるま食品」、R1 育 偕楽園観光土産、水戸駅+百貨店、¥150-400。", content_md: "- 立地:**水戸市**\n- 認定:**全国納豆生産量 No.1 県・40% シェア**\n- 起源:**江戸期 1700 年代 水戸藩献上**\n- 老舗:**水戸天狗納豆 + だるま食品 等 5+ 軒**\n- 並列観光:**R1 育 偕楽園 1842**\n- 価格:**1 パック ¥150-400**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["industrial_heritage", "shopping_district"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mito_natto", "no1_japan", "40_percent", "tengu_natto"], source: "manual" },
  { slug: "ankoh-nabe-ooarai-kitaibaraki", category: "food", sub_type: "ibaraki_3_meibutsu", title_zh: "鮟鱇鍋(大洗町+北茨城市・常磐沿岸冬代表+ 江戸期 水戸藩献上+ 「鮟鱇 7 つ道具」+ 大洗+平潟+大津港 ブランド+ 11-3 月旬+ 老舗料亭 8+ 軒+ 1 人前 ¥3,500-8,500+ 観光客向け常磐高級鍋代表)", title_ja: "鮟鱇鍋", romaji: "Ankō Nabe", summary_zh: "**鮟鱇鍋は常磐沿岸冬代表**(大洗+北茨城・**江戸期水戸藩献上+「鮟鱇 7 つ道具」**)。大洗+平潟+大津港ブランド、11-3 月旬、老舗 8+ 軒、¥3,500-8,500。", content_md: "- 立地:**大洗町 + 北茨城市平潟・大津港**\n- 起源:**江戸期 水戸藩献上**\n- 看板:**「鮟鱇 7 つ道具」**\n- ブランド:**大洗 + 平潟 + 大津港**\n- 期:**11-3 月旬**\n- 老舗:**料亭 8+ 軒**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "大洗町", lg_code: "08309", area_types: ["restaurant_traditional"], lat: 36.3094, lon: 140.5750, season_start: "2026-11-01", season_end: "2027-03-31", event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ankoh_nabe", "edo_mito", "7_tools", "joban_coast"], source: "manual" },
  { slug: "ibaraki-melon-hokota-no1", category: "food", sub_type: "ibaraki_3_meibutsu", title_zh: "茨城メロン(鉾田市+茨城町+鹿島・全国メロン生産量 No.1 県・35% シェア+ 1980 年代開発+ アンデス+クインシー+イバラキング+ 5-7 月旬+ 観光メロン狩り 30+ 園+ 1 玉 ¥2,500-7,500+ 全国百貨店流通)", title_ja: "茨城メロン", romaji: "Ibaraki Melon", summary_zh: "**茨城メロンは全国メロン生産量 No.1 県・35% シェア**(鉾田+茨城町+鹿島・**1980 年代開発**)。アンデス+クインシー+イバラキング、5-7 月、狩り 30+ 園、¥2,500-7,500。", content_md: "- 立地:**鉾田市 + 茨城町 + 鹿島市**\n- 認定:**全国メロン生産量 No.1 県・35% シェア**\n- 起源:**1980 年代開発**\n- 種:**アンデス + クインシー + イバラキング**\n- 期:**5-7 月旬**\n- 規模:**メロン狩り 30+ 園**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "鉾田市", lg_code: "08234", area_types: ["farm_field"], lat: 36.1581, lon: 140.5128, season_start: "2026-05-01", season_end: "2026-07-31", event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ibaraki_melon", "no1_japan", "35_percent", "ibaraki_king"], source: "manual" },
  { slug: "hoshiimo-hitachinaka-90", category: "food", sub_type: "ibaraki_3_meibutsu", title_zh: "干し芋(ひたちなか市+東海村+那珂市・全国干し芋生産量 No.1 県・90% シェア+ 1908 大正期発祥+ 紅はるか+いずみ品種+ 12-3 月旬+ 道の駅+全国百貨店流通+ 1 袋 ¥800-1,800+ 観光土産代表)", title_ja: "干し芋", romaji: "Hoshiimo", summary_zh: "**干し芋は全国生産量 No.1 県・90% シェア**(ひたちなか+東海+那珂・**1908 大正期発祥**)。紅はるか+いずみ、12-3 月、道の駅+百貨店、¥800-1,800。", content_md: "- 立地:**ひたちなか市 + 東海村 + 那珂市**\n- 認定:**全国干し芋生産量 No.1 県・90% シェア**\n- 起源:**1908 大正期発祥 117 年**\n- 種:**紅はるか + いずみ**\n- 期:**12-3 月旬**\n- 価格:**1 袋 ¥800-1,800**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "ひたちなか市", lg_code: "08221", area_types: ["industrial_heritage", "farm_field"], lat: 36.3961, lon: 140.5350, season_start: "2026-12-01", season_end: "2027-03-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["hoshiimo", "1908", "90_percent", "no1_japan"], source: "manual" },
  { slug: "ibaraki-renkon-no1", category: "food", sub_type: "ibaraki_3_meibutsu", title_zh: "茨城蓮根(土浦市+かすみがうら市+稲敷市・全国蓮根生産量 No.1 県・50% シェア+ 江戸期 霞ヶ浦周辺栽培+ 蓮根料理+天ぷら+煮物+きんぴら+ 1kg ¥800-1,800+ 通年流通+ 全国百貨店ヒット)", title_ja: "茨城蓮根", romaji: "Ibaraki Renkon", summary_zh: "**茨城蓮根は全国生産量 No.1 県・50% シェア**(土浦+かすみがうら+稲敷・**江戸期霞ヶ浦周辺栽培**)。蓮根料理+天ぷら+煮物+きんぴら、¥800-1,800/kg、全国百貨店。", content_md: "- 立地:**土浦市 + かすみがうら市 + 稲敷市**(霞ヶ浦周辺)\n- 認定:**全国蓮根生産量 No.1 県・50% シェア**\n- 起源:**江戸期 霞ヶ浦周辺栽培**\n- 用途:**蓮根料理 + 天ぷら + 煮物 + きんぴら**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "土浦市", lg_code: "08203", area_types: ["farm_field"], lat: 36.0786, lon: 140.2042, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ibaraki_renkon", "no1_japan", "50_percent", "kasumigaura"], source: "manual" },

  // 郷土食 (4)
  { slug: "hitachi-gyu-1976", category: "food", sub_type: "ibaraki_meat", title_zh: "常陸牛(常陸太田市+常陸大宮市+日立・1976 認定 ブランド和牛 49 年+ 県内 約 200 戸生産・A4 以上限定+ R1 食 米沢牛(山形)+秋田比内地鶏 系統 と並ぶ東北甲信越 ブランド和牛+ 老舗料亭 5+ 軒+ ¥6,500-15,000)", title_ja: "常陸牛", romaji: "Hitachi Gyū", summary_zh: "**常陸牛は 1976 認定ブランド和牛 49 年**(常陸太田+常陸大宮+日立・**県内 200 戸生産・A4 以上限定**)。R1 食 米沢牛+比内地鶏 系統並ぶ、老舗 5+ 軒、¥6,500-15,000。", content_md: "- 立地:**常陸太田市 + 常陸大宮市 + 日立市**\n- 起源:**1976 認定 ブランド和牛 49 年**\n- 認定:**県内 約 200 戸生産・A4 以上限定**\n- 並列:**山形米沢牛 + 秋田比内地鶏 + 茨城常陸牛 = 関東甲信越ブランド和牛系統**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "常陸太田市", lg_code: "08212", area_types: ["farm_field", "restaurant_traditional"], lat: 36.5358, lon: 140.5286, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["hitachi_gyu", "1976", "49_years", "wagyu_a4"], source: "manual" },
  { slug: "joban-aki-soba", category: "food", sub_type: "ibaraki_kyodo", title_zh: "常陸秋そば(常陸太田+常陸大宮+大子町・1985 茨城県農試開発+ 全国食味ランキング上位そば+ 9-10 月新そば旬+ R1 食 山形板そば+福島山都そば と並ぶ東日本そば文化+ 茨城そば店 50+ 軒+ 1 杯 ¥1,000-2,200)", title_ja: "常陸秋そば", romaji: "Jōban Aki Soba", summary_zh: "**常陸秋そばは 1985 茨城県農試開発・全国食味ランキング上位**(常陸太田+常陸大宮+大子・**9-10 月新そば旬**)。R1 食 山形板そば+福島山都そばと並ぶ、50+ 軒、¥1,000-2,200。", content_md: "- 立地:**常陸太田市 + 常陸大宮市 + 久慈郡大子町**\n- 起源:**1985 茨城県農試開発 40 年**\n- 認定:**全国食味ランキング上位そば**\n- 期:**9-10 月新そば旬**\n- 並列:**山形板そば(R1 食) + 福島山都そば(R3 食) + 茨城常陸秋そば = 東日本そば文化**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "常陸太田市", lg_code: "08212", area_types: ["restaurant_traditional", "farm_field"], lat: 36.5358, lon: 140.5286, season_start: "2026-09-15", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["joban_aki_soba", "1985", "40_years"], source: "manual" },
  { slug: "mito-natto-shoyu-ramen", category: "food", sub_type: "ibaraki_kyodo", title_zh: "水戸スタミナラーメン(水戸市・1970 年代発祥 50+ 年+ R1 食 水戸納豆派生・納豆+醤油+太麺+ 「ホットラーメン」+「冷やしスタミナ」2 系統+ 市内 30+ 軒+ 1 杯 ¥800-1,200+ 観光客向け B 級代表)", title_ja: "水戸スタミナラーメン", romaji: "Mito Stamina Ramen", summary_zh: "**水戸スタミナラーメンは 1970 年代発祥 50+ 年**(水戸・**R1 食 水戸納豆派生・納豆+醤油+太麺**)。「ホット」+「冷やしスタミナ」2 系統、市内 30+ 軒、¥800-1,200。", content_md: "- 立地:**水戸市**\n- 起源:**1970 年代発祥 50+ 年**\n- 関係:**R1 食 水戸納豆派生**\n- 構成:**納豆 + 醤油 + 太麺**\n- 規模:**市内 30+ 軒**\n- 並列:**「ホットラーメン」+「冷やしスタミナ」2 系統**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["restaurant_traditional"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mito_stamina_ramen", "1970s"], source: "manual" },
  { slug: "kashima-tako", category: "food", sub_type: "ibaraki_seafood", title_zh: "鹿島タコ(鹿嶋市+神栖市・常磐沿岸+ 鹿島港+波崎港 水揚げ+ 江戸期から漁業伝承+ タコ刺身+タコ飯+タコ唐揚げ+ R1 育 鹿島神宮(常陸国一之宮)観光客向け+ 1 人前 ¥1,500-3,500)", title_ja: "鹿島タコ", romaji: "Kashima Tako", summary_zh: "**鹿島タコは常磐沿岸鹿島港+波崎港**(鹿嶋+神栖・**江戸期から漁業伝承**)。タコ刺身+タコ飯+唐揚げ、R1 育 鹿島神宮観光、¥1,500-3,500。", content_md: "- 立地:**鹿嶋市 + 神栖市**\n- 起源:**江戸期から漁業伝承**\n- 用途:**タコ刺身 + タコ飯 + タコ唐揚げ**\n- 並列:**R1 育 鹿島神宮(常陸国一之宮)観光客向け**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "鹿嶋市", lg_code: "08222", area_types: ["restaurant_traditional"], lat: 35.9656, lon: 140.6447, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kashima_tako", "edo_origin"], source: "manual" },

  // 海産+霞ヶ浦 (3)
  { slug: "ooarai-anki-fukurin", category: "food", sub_type: "ibaraki_seafood", title_zh: "大洗鮟鱇吊し切り(大洗町・R1 食 鮟鱇鍋派生・伝統的吊し切り(あんこうの吊るし切り)実演+ 大洗まいわい市場+大洗水族館 R1 楽 観光客向け+ 県無形民俗・茨城名物+ 1 月-2 月実演観覧無料・購入別)", title_ja: "大洗鮟鱇吊し切り", romaji: "Ōarai Ankō Tsurushi", summary_zh: "**大洗鮟鱇吊し切りは R1 食 鮟鱇鍋派生・伝統吊し切り実演**(大洗・**県無形民俗・茨城名物**)。R1 楽 大洗水族館観光、1-2 月実演観覧無料・購入別。", content_md: "- 立地:**大洗町**(R1 食 鮟鱇鍋関連)\n- 関係:**R1 食 鮟鱇鍋派生**\n- 構成:**伝統的吊し切り(あんこうの吊るし切り)実演**\n- 認定:**県無形民俗・茨城名物**\n- 並列観光:**R1 楽 大洗水族館**\n- 期:**1-2 月実演**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "大洗町", lg_code: "08309", area_types: ["restaurant_traditional", "festival_event"], lat: 36.3094, lon: 140.5750, season_start: "2026-01-01", season_end: "2027-02-28", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ankoh_tsurushi", "kashima"], source: "manual" },
  { slug: "namegata-namazu-kasumigaura", category: "food", sub_type: "ibaraki_seafood", title_zh: "行方ナマズ+霞ヶ浦淡水魚料理(行方市+土浦市+石岡・霞ヶ浦+北浦水域 ナマズ・コイ・フナ・ワカサギ伝承料理+ 江戸期 漁業伝承+ 蒲焼+刺身+天ぷら+ R1 食 茨城蓮根 沿岸 と組合せ+ 1 人前 ¥1,800-3,500)", title_ja: "行方ナマズ+霞ヶ浦淡水魚", romaji: "Namegata Namazu", summary_zh: "**行方ナマズ+霞ヶ浦淡水魚料理は霞ヶ浦+北浦水域伝承**(行方+土浦+石岡・**ナマズ・コイ・フナ・ワカサギ**)。江戸期漁業、蒲焼+刺身+天ぷら、R1 食 蓮根沿岸組合せ、¥1,800-3,500。", content_md: "- 立地:**行方市 + 土浦市 + 石岡市**(霞ヶ浦 + 北浦水域)\n- 起源:**江戸期 漁業伝承**\n- 構成:**ナマズ + コイ + フナ + ワカサギ**\n- 用途:**蒲焼 + 刺身 + 天ぷら**\n- 並列:**R1 食 茨城蓮根 沿岸 と組合せ**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "行方市", lg_code: "08233", area_types: ["restaurant_traditional"], lat: 35.9961, lon: 140.4806, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["namegata_namazu", "kasumigaura", "edo_origin"], source: "manual" },
  { slug: "hitachinaka-mehikari", category: "food", sub_type: "ibaraki_seafood", title_zh: "常磐メヒカリ(ひたちなか市+日立市+北茨城・常磐沿岸特産深海魚+ R1 食 福島いわきメヒカリ系統 共有+ 11-3 月旬+ 唐揚げ+干物+寿司+ 那珂湊おさかな市場+全国百貨店流通+ 1 人前 ¥800-1,500)", title_ja: "常磐メヒカリ", romaji: "Jōban Mehikari", summary_zh: "**常磐メヒカリは常磐沿岸特産深海魚**(ひたちなか+日立+北茨城・**R1 食 福島いわきメヒカリ系統共有**)。11-3 月、那珂湊おさかな市場+百貨店、¥800-1,500。", content_md: "- 立地:**ひたちなか市 + 日立市 + 北茨城市**\n- 期:**11-3 月旬**\n- 系統:**R1 食 福島いわきメヒカリ系統共有(常磐沿岸 共通深海魚)**\n- 用途:**唐揚げ + 干物 + 寿司**\n- 並列:**那珂湊おさかな市場**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "ひたちなか市", lg_code: "08221", area_types: ["restaurant_traditional"], lat: 36.3961, lon: 140.5350, season_start: "2026-11-01", season_end: "2027-03-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["joban_mehikari", "deep_sea"], source: "manual" },

  // 果実 (3)
  { slug: "tsukuba-strawberry", category: "food", sub_type: "ibaraki_fruit", title_zh: "つくばいちご(つくば市+つくばみらい市・関東いちご産地代表・1980 年代開発+ もういっこ・とちおとめ・ベリーツ品種+ 12-5 月旬+ いちご狩り 30+ 観光園+ R1 育 つくば学園都市観光と組合せ+ 1kg ¥3,500-7,500)", title_ja: "つくばいちご", romaji: "Tsukuba Ichigo", summary_zh: "**つくばいちごは関東いちご産地代表**(つくば+つくばみらい・**1980 年代開発+もういっこ・とちおとめ・ベリーツ**)。12-5 月、狩り 30+ 園、R1 育 学園都市組合せ、¥3,500-7,500/kg。", content_md: "- 立地:**つくば市 + つくばみらい市**\n- 起源:**1980 年代開発**\n- 種:**もういっこ + とちおとめ + ベリーツ**\n- 期:**12-5 月旬**\n- 規模:**いちご狩り 30+ 観光園**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "つくば市", lg_code: "08220", area_types: ["farm_field"], lat: 36.0833, lon: 140.0764, season_start: "2026-12-01", season_end: "2027-05-31", event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsukuba_ichigo", "1980s"], source: "manual" },
  { slug: "daigo-ringo", category: "food", sub_type: "ibaraki_fruit", title_zh: "大子りんご(久慈郡大子町・関東りんご産地代表・標高 300-500m 山地気候+ 1900 年代開発+ ふじ+つがる+ジョナゴールド+ 9-11 月旬+ 観光りんご狩り 25+ 園+ R1 楽 袋田の滝(R1 育)観光と組合せ+ 1kg ¥1,500-3,000)", title_ja: "大子りんご", romaji: "Daigo Ringo", summary_zh: "**大子りんごは関東りんご産地代表・標高 300-500m 山地気候**(大子・**1900 年代開発+ふじ+つがる+ジョナゴールド**)。9-11 月、狩り 25+ 園、R1 楽 袋田の滝組合せ、¥1,500-3,000/kg。", content_md: "- 立地:**久慈郡大子町**\n- 規模:**標高 300-500m 山地気候**\n- 起源:**1900 年代開発**\n- 種:**ふじ + つがる + ジョナゴールド**\n- 期:**9-11 月旬**\n- 並列観光:**R1 育 袋田の滝**", region: "kanto", prefecture_ja: "茨城県", gun_ja: "久慈郡", municipality_ja: "大子町", lg_code: "08364", area_types: ["farm_field"], lat: 36.7681, lon: 140.3556, season_start: "2026-09-15", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["daigo_ringo", "300_500m"], source: "manual" },
  { slug: "mito-no-ume", category: "food", sub_type: "ibaraki_fruit", title_zh: "水戸の梅(水戸市・R1 育 偕楽園 1842 徳川斉昭 3000 本梅 派生・梅干し+梅酒+梅菓子+ 2 月下-3 月梅まつり期+ 道の駅+全国百貨店流通+ 1 個 ¥250-500+ 観光土産代表)", title_ja: "水戸の梅", romaji: "Mito no Ume", summary_zh: "**水戸の梅は R1 育 偕楽園 1842 徳川斉昭 3000 本梅派生**(水戸・**梅干し+梅酒+梅菓子**)。2 月下-3 月梅まつり、道の駅+百貨店、¥250-500、観光土産代表。", content_md: "- 立地:**水戸市**(R1 育 偕楽園 1842)\n- 関係:**R1 育 偕楽園 3000 本梅派生**\n- 構成:**梅干し + 梅酒 + 梅菓子**\n- 期:**2 月下-3 月梅まつり期**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["industrial_heritage", "shopping_district"], lat: 36.3658, lon: 140.4711, season_start: "2026-02-15", season_end: "2026-03-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mito_no_ume", "kairakuen"], source: "manual" },

  // 銘菓 (5)
  { slug: "mito-baikou-1844", category: "food", sub_type: "ibaraki_meika", title_zh: "水戸の梅(銘菓・1844 創業 181 年+ R1 育 偕楽園 1842 徳川斉昭 関連・3000 本梅 由来+ 求肥+紫蘇+梅 練菓子+ JR 水戸駅売店+全国百貨店流通+ 1 箱 ¥1,200-1,800+ 県銘菓代表)", title_ja: "水戸の梅(銘菓)", romaji: "Mito no Ume (Meika)", summary_zh: "**水戸の梅銘菓は 1844 創業 181 年・R1 育 偕楽園関連**(水戸・**求肥+紫蘇+梅練菓子**)。JR 水戸駅+全国百貨店、¥1,200-1,800/箱、県銘菓代表。", content_md: "- 立地:**水戸市**\n- 起源:**1844 創業 181 年**\n- 関係:**R1 育 偕楽園 1842 徳川斉昭・3000 本梅 由来**\n- 構成:**求肥 + 紫蘇 + 梅 練菓子**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["restaurant_traditional", "shopping_district"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mito_baikou", "1844", "181_years"], source: "manual" },
  { slug: "tsuchiura-kashidori-1869", category: "food", sub_type: "ibaraki_meika", title_zh: "雪村あんこう+土浦菓子司 1869 銘菓(土浦市・1869 明治期創業 156 年+ 県内最古菓子店+ 干菓子+落雁+どらやき+ R1 食 茨城蓮根 観光客向け+ JR 土浦駅売店+全国百貨店流通+ 1 箱 ¥1,200-2,200)", title_ja: "土浦菓子司 1869 銘菓", romaji: "Tsuchiura Kashitsukasa", summary_zh: "**雪村あんこう+土浦菓子司は 1869 明治期創業 156 年・県内最古菓子店**(土浦・**干菓子+落雁+どらやき**)。R1 食 蓮根観光、JR 土浦駅+百貨店、¥1,200-2,200/箱。", content_md: "- 立地:**土浦市**\n- 起源:**1869 明治期創業 156 年**\n- 認定:**県内最古菓子店**\n- 構成:**干菓子 + 落雁 + どらやき**\n- 並列観光:**R1 食 茨城蓮根**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "土浦市", lg_code: "08203", area_types: ["restaurant_traditional", "shopping_district"], lat: 36.0786, lon: 140.2042, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsuchiura_kashitsukasa", "1869", "156_years"], source: "manual" },
  { slug: "mito-natto-monaka", category: "food", sub_type: "ibaraki_meika", title_zh: "水戸納豆もなか+納豆スイーツ(水戸市・R1 食 水戸納豆派生・現代化銘菓+ 納豆求肥+納豆あんこ+納豆チョコ+ JR 水戸駅売店+全国百貨店ヒット+ ¥350-1,200+ 観光客 SNS 拡散+ R1 衣 水戸納豆グッズ と並ぶ)", title_ja: "水戸納豆もなか+スイーツ", romaji: "Mito Nattō Monaka", summary_zh: "**水戸納豆もなか+納豆スイーツは R1 食 水戸納豆派生現代化銘菓**(納豆求肥+あんこ+チョコ)。水戸駅+全国百貨店、¥350-1,200、SNS 拡散。", content_md: "- 関係:**R1 食 水戸納豆 No.1 派生**\n- 構成:**納豆求肥 + 納豆あんこ + 納豆チョコ**\n- 価格:**¥350-1,200**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["restaurant_traditional", "shopping_district"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mito_natto_monaka", "modern"], source: "manual" },
  { slug: "kasama-meika-yaki", category: "food", sub_type: "ibaraki_meika", title_zh: "笠間焼+ そばまんじゅう(笠間市・R1 衣 笠間焼 1772 国指定 1992 派生・銘菓・笠間焼器+そばまんじゅう+栗まんじゅう+ JR 水戸線 笠間駅売店+ 全国百貨店流通+ 1 箱 ¥1,200-1,800)", title_ja: "笠間そばまんじゅう", romaji: "Kasama Soba Manjū", summary_zh: "**笠間焼+そばまんじゅうは R1 衣 笠間焼 1772 派生**(笠間・**笠間焼器+そばまんじゅう+栗まんじゅう**)。JR 水戸線笠間駅売店+百貨店、¥1,200-1,800/箱。", content_md: "- 立地:**笠間市**\n- 関係:**R1 衣 笠間焼 1772 国指定 1992 派生**\n- 構成:**笠間焼器 + そばまんじゅう + 栗まんじゅう**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "笠間市", lg_code: "08216", area_types: ["restaurant_traditional", "shopping_district"], lat: 36.3858, lon: 140.2614, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kasama_soba_manju"], source: "manual" },
  { slug: "ibaraki-melon-cake-modern", category: "food", sub_type: "ibaraki_meika", title_zh: "茨城メロンスイーツ(R1 食 茨城メロン全国 No.1 派生・現代洋菓子+ メロンタルト+ジェラート+パイ+ プリン+ JR 水戸駅+土浦駅+つくば駅売店+全国百貨店ヒット+ ¥350-1,500+ 観光客 SNS 拡散代表)", title_ja: "茨城メロンスイーツ", romaji: "Ibaraki Melon Sweets", summary_zh: "**茨城メロンスイーツは R1 食 メロン No.1 派生現代洋菓子**(タルト+ジェラート+パイ+プリン)。水戸+土浦+つくば駅+全国百貨店、¥350-1,500、SNS 拡散代表。", content_md: "- 関係:**R1 食 茨城メロン全国 No.1 派生**\n- 構成:**メロンタルト + ジェラート + パイ + プリン**\n- 流通:**JR 水戸駅 + 土浦駅 + つくば駅売店 + 全国百貨店**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "鉾田市", lg_code: "08234", area_types: ["restaurant_traditional", "shopping_district"], lat: 36.1581, lon: 140.5128, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ibaraki_melon_sweets"], source: "manual" },

  // 酒 (3)
  { slug: "tsukinoi-shuzo-1865-ooarai", category: "food", sub_type: "ibaraki_sake", title_zh: "月の井酒造(大洗町・1865 創業 160 年+ R1 食 鮟鱇鍋(大洗)観光客向け+ 「月の井」純米吟醸+大吟醸+ 全国新酒鑑評会金賞常連+ 720ml ¥1,800-4,500+ R1 楽 大洗水族館観光と組合せ)", title_ja: "月の井酒造", romaji: "Tsukinoi Shuzō", summary_zh: "**月の井酒造は 1865 創業 160 年**(大洗・**R1 食 鮟鱇鍋観光客向け**)。「月の井」純米吟醸+大吟醸、全国新酒鑑評会金賞常連、¥1,800-4,500/720ml。", content_md: "- 立地:**大洗町**\n- 起源:**1865 創業 160 年**\n- 看板:**「月の井」純米吟醸 + 大吟醸**\n- 認定:**全国新酒鑑評会金賞常連**\n- 並列観光:**R1 食 鮟鱇鍋 + R1 楽 大洗水族館**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "大洗町", lg_code: "08309", area_types: ["industrial_heritage"], lat: 36.3094, lon: 140.5750, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsukinoi", "1865", "160_years"], source: "manual" },
  { slug: "raifuku-shuzo-1716", category: "food", sub_type: "ibaraki_sake", title_zh: "来福酒造(筑西市・1716 創業 309 年+ 茨城最古酒蔵候補+ 「来福」純米吟醸+大吟醸+ 全国新酒鑑評会金賞最多受賞蔵元の一+ 720ml ¥2,500-7,500+ 全国百貨店流通+ R1 食 月の井 1865 と並ぶ茨城地酒老舗)", title_ja: "来福酒造", romaji: "Raifuku Shuzō", summary_zh: "**来福酒造は 1716 創業 309 年・茨城最古酒蔵候補**(筑西・**全国新酒鑑評会金賞最多受賞蔵元の一**)。「来福」純米+大吟醸、¥2,500-7,500/720ml、R1 食 月の井 1865 と並ぶ。", content_md: "- 立地:**筑西市**\n- 起源:**1716 創業 309 年**\n- 認定:**茨城最古酒蔵候補 + 全国新酒鑑評会金賞最多受賞蔵元の一**\n- 並列:**月の井 1865 + 来福 1716 + 牛久シャトーカミヤ 1903 = 茨城地酒 3 大老舗**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "筑西市", lg_code: "08227", area_types: ["industrial_heritage"], lat: 36.3092, lon: 139.9842, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: { official: "https://www.raifuku.co.jp/" }, tags: ["raifuku", "1716", "309_years"], source: "manual" },
  { slug: "ushiku-chateau-kamiya-1903", category: "food", sub_type: "ibaraki_sake", title_zh: "牛久シャトーカミヤ(牛久市・1903 創業 122 年+ 日本最古ワイナリー+ 国登録有形文化財・神谷伝兵衛創設+ 赤+白ワイン+ ブランデー+ シャトー見学 ¥500+ R1 育 牛久大仏(120m 世界最大級青銅仏)観光と組合せ)", title_ja: "牛久シャトーカミヤ", romaji: "Ushiku Chateau Kamiya", summary_zh: "**牛久シャトーカミヤは日本最古ワイナリー・1903 創業 122 年**(牛久・**国登録有形文化財・神谷伝兵衛創設**)。シャトー見学 ¥500、R1 育 牛久大仏組合せ。", content_md: "- 立地:**牛久市**\n- 起源:**1903 創業 122 年**\n- 認定:**日本最古ワイナリー + 国登録有形文化財・神谷伝兵衛創設**\n- 構成:**赤 + 白ワイン + ブランデー**\n- 並列観光:**R1 育 牛久大仏(120m 世界最大級青銅仏)**\n- 見学:**¥500**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "牛久市", lg_code: "08219", area_types: ["industrial_heritage", "history_site_castle"], lat: 35.9806, lon: 140.1408, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: { official: "https://www.ushikuchateau.co.jp/" }, tags: ["ushiku_chateau", "1903", "122_years", "japan_oldest_winery"], source: "manual" },

  // 米果 (2)
  { slug: "ibaraki-koshihikari-tsukuba", category: "food", sub_type: "ibaraki_kyodo", title_zh: "茨城コシヒカリ(つくば市+下妻+常総+守谷・全国コシヒカリ生産量 No.4 県+ 1956 開発+ R1 育 つくば学園都市農業試験場連動+ 全国食味ランキング A+ 1kg ¥1,200-2,000+ JR 茨城駅+全国百貨店流通)", title_ja: "茨城コシヒカリ", romaji: "Ibaraki Koshihikari", summary_zh: "**茨城コシヒカリは全国生産量 No.4 県**(つくば+下妻+常総+守谷・**1956 開発+R1 育 つくば学園都市農業試験場連動**)。全国食味 A、¥1,200-2,000/kg。", content_md: "- 立地:**つくば市 + 下妻市 + 常総市 + 守谷市**\n- 認定:**全国コシヒカリ生産量 No.4 県**\n- 起源:**1956 開発**\n- 並列:**R1 育 つくば学園都市農業試験場連動**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "つくば市", lg_code: "08220", area_types: ["farm_field"], lat: 36.0833, lon: 140.0764, season_start: "2026-09-15", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ibaraki_koshihikari", "1956", "no4_japan"], source: "manual" },
  { slug: "ibaraki-natto-snack-modern", category: "food", sub_type: "ibaraki_meika", title_zh: "水戸納豆スナック+納豆チップス現代化(R1 食 水戸納豆全国 No.1 派生・現代化加工食品+ 納豆チップス+納豆煎餅+納豆ふりかけ+ JR 水戸駅+全国百貨店ヒット+ ¥350-1,200+ 海外輸出 観光客 SNS 拡散代表)", title_ja: "水戸納豆スナック", romaji: "Mito Nattō Snack Modern", summary_zh: "**水戸納豆スナック+納豆チップス現代化は R1 食 派生加工食品**(納豆チップス+煎餅+ふりかけ)。JR 水戸駅+全国百貨店、¥350-1,200、海外輸出+SNS 拡散。", content_md: "- 関係:**R1 食 水戸納豆全国 No.1 派生**\n- 構成:**納豆チップス + 納豆煎餅 + 納豆ふりかけ**\n- 流通:**JR 水戸駅 + 全国百貨店ヒット + 海外輸出**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["industrial_heritage", "shopping_district"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mito_natto_snack_modern"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[ibaraki-food-r1] 尚無條目"); return; }
  console.log(`[ibaraki-food-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[ibaraki-food-r1] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[ibaraki-food-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[ibaraki-food-r1] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
