// Seed 神奈川県 R4 補完(20 筆 / Sprint 4.x / 第十四卷)
// 食 5 / 衣 3 / 住 3 / 育 4 / 楽 3 / 行 2 = 20 累積 163 + 20 = 183
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 食 5
  {
    slug: "yokohama-cafe-bashamichi",
    category: "food", sub_type: "kanagawa_yokohama_food",
    title_zh: "横浜カフェ文化+ 馬車道珈琲(横浜市中区馬車道+ 関内・1859 開港時西洋珈琲伝来 166+ 年+ 全国カフェ文化発祥地候補・喜久屋本店 1869+ 馬車道十番館 1967・「馬車道」全国カフェストリート発祥候補・1 杯 ¥800-1,500・国際 SNS 海外旅行者代表)",
    title_ja: "横浜カフェ", romaji: "Yokohama Café",
    summary_zh: "**横浜カフェ文化+馬車道珈琲は 1859 開港時西洋珈琲伝来 166+ 年・全国カフェ文化発祥地候補・喜久屋 1869+馬車道十番館 1967**(中区馬車道+関内)。¥800-1,500、海外代表。",
    content_md: "- 立地:**横浜市中区馬車道 + 関内**\n- 起源:**1859 開港時西洋珈琲伝来 166+ 年**\n- 認定:**全国カフェ文化発祥地候補 + 喜久屋本店 1869 + 馬車道十番館 1967**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["restaurant_traditional", "history_site_castle"], lat: 35.4444, lon: 139.6403,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokohama_cafe", "1859"], source: "manual",
  },
  {
    slug: "kamaboko-experience-suzuhiro",
    category: "food", sub_type: "kanagawa_ashigara_food",
    title_zh: "鈴廣かまぼこ博物館+ 製造体験(小田原市風祭・1865 鈴廣創業 160+ 年(R1 食派生)+ 1985 鈴廣かまぼこ博物館開館 40+ 年+ 製造体験(蒲鉾+ ちくわ手作り体験)+ 試食販売・¥1,650/体験・国際 SNS 海外旅行者代表)",
    title_ja: "鈴廣かまぼこ博物館", romaji: "Suzuhiro Kamaboko",
    summary_zh: "**鈴廣かまぼこ博物館+製造体験は 1865 鈴廣 160+ 年+1985 博物館 40+ 年・蒲鉾+ちくわ手作り体験**(小田原風祭)。¥1,650/体験、海外代表。",
    content_md: "- 立地:**小田原市風祭**\n- 関連:**R1 食 鈴廣 1865 派生**\n- 起源:**1985 鈴廣かまぼこ博物館開館 40+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "小田原市", lg_code: "14206",
    area_types: ["industrial_heritage", "restaurant_traditional"], lat: 35.2381, lon: 139.1306,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["suzuhiro_museum_1985"], source: "manual",
  },
  {
    slug: "yokohama-chuka-takagi",
    category: "food", sub_type: "kanagawa_yokohama_food",
    title_zh: "横浜中華街高級レストラン「萬珍樓本店」+「華正樓」(横浜市中区山下町・R1 食 派生・萬珍樓本店 1892 創業 133+ 年(R3 食派生)+ 華正樓 1939 創業 86+ 年+ 聘珍樓 1884 創業 141+ 年(2022 廃業まで全国最古中華レストラン)・¥9,500-32,000)",
    title_ja: "中華街高級レストラン", romaji: "Chinatown Luxury",
    summary_zh: "**横浜中華街高級レストランは萬珍樓本店 1892 133+ 年+華正樓 1939 86+ 年+聘珍樓 1884 141+ 年(2022 廃業)**(中区山下町)。¥9,500-32,000、R3 食派生。",
    content_md: "- 立地:**横浜市中区山下町**\n- 関連:**R1 食 横浜中華街 + R3 食 老舗派生**\n- 老舗:**萬珍樓本店 1892 133+ 年 + 華正樓 1939 86+ 年 + 聘珍樓 1884 141+ 年(2022 廃業)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["restaurant_traditional"], lat: 35.4428, lon: 139.6450,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["chinatown_takagi", "manchinrou"], source: "manual",
  },
  {
    slug: "miura-ama-fishing",
    category: "food", sub_type: "kanagawa_miura_food",
    title_zh: "三浦海女漁+ 三崎海女文化(三浦市三崎+ 城ヶ島・三浦半島海女漁業 江戸期から 300+ 年+ 鮑+ 栄螺+ 海苔+ ウニ・三崎海女文化展(三浦市民会館)+ 7-8 月旬+ 三崎港朝市販売・¥3,500-12,000)",
    title_ja: "三浦海女", romaji: "Miura Ama",
    summary_zh: "**三浦海女漁+三崎海女文化は三浦半島海女漁業江戸期から 300+ 年・鮑+栄螺+海苔+ウニ・7-8 月旬・三崎港朝市販売**(三浦三崎+城ヶ島)。¥3,500-12,000。",
    content_md: "- 立地:**三浦市三崎 + 城ヶ島**\n- 起源:**三浦半島海女漁業 江戸期から 300+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "三浦市", lg_code: "14210",
    area_types: ["restaurant_traditional", "industrial_heritage"], lat: 35.1378, lon: 139.6178,
    season_start: "2026-07-01", season_end: "2026-08-31", event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["miura_ama"], source: "manual",
  },
  {
    slug: "kawasaki-hormone",
    category: "food", sub_type: "kanagawa_kawasaki_food",
    title_zh: "川崎ホルモン+ B 級グルメ(川崎市川崎区+ JR 川崎駅周辺・R1 食 川崎ニュータンタン派生・1950 年代以降工業地帯労働者向ホルモン文化 70+ 年+ 川崎駅前ホルモン老舗 25+ 軒+ ¥1,500-3,500)",
    title_ja: "川崎ホルモン", romaji: "Kawasaki Hormone",
    summary_zh: "**川崎ホルモン+B 級は R1 食 川崎ニュータンタン派生・1950 年代以降工業地帯労働者向 70+ 年・駅前ホルモン老舗 25+ 軒**(川崎区+JR 川崎)。¥1,500-3,500。",
    content_md: "- 立地:**川崎市川崎区 + JR 川崎駅周辺**\n- 関連:**R1 食 川崎ニュータンタン派生**\n- 起源:**1950 年代以降工業地帯労働者向ホルモン文化 70+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "川崎市", lg_code: "14130",
    area_types: ["restaurant_traditional"], lat: 35.5308, lon: 139.7028,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kawasaki_hormone"], source: "manual",
  },

  // 衣 3
  {
    slug: "yokohama-vintage-furugi",
    category: "fashion", sub_type: "kanagawa_yokohama_clothing",
    title_zh: "横浜古着+ ヴィンテージ街(横浜市中区伊勢佐木町+元町+関内・1900 年代以降米軍払下げ古着街発祥 100+ 年+ 「ヴィンテージモール」+「シカゴ」+ 100+ 古着店+ 米軍ジャケット+ ジーンズ・¥3,500-25,000・国内古着ファン代表)",
    title_ja: "横浜古着街", romaji: "Yokohama Vintage",
    summary_zh: "**横浜古着+ヴィンテージ街は 1900 年代以降米軍払下げ古着街発祥 100+ 年・「ヴィンテージモール」+「シカゴ」+100+ 古着店・米軍ジャケット+ジーンズ**(中区伊勢佐木町+元町+関内)。¥3,500-25,000。",
    content_md: "- 立地:**横浜市中区伊勢佐木町 + 元町 + 関内**\n- 起源:**1900 年代以降米軍払下げ古着街発祥 100+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["shopping_district"], lat: 35.4444, lon: 139.6403,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokohama_vintage"], source: "manual",
  },
  {
    slug: "miura-outdoor-camp",
    category: "fashion", sub_type: "kanagawa_miura_clothing",
    title_zh: "三浦+三崎キャンプ・アウトドアウェア(三浦市+ 横須賀・三浦半島キャンプ場 30+ 軒+ 1990 年代以降アウトドアブーム派生 35+ 年+ 油壷キャンプ場・スノーピーク+モンベル+コロンビア・¥9,500-65,000・国内 SNS アウトドアファン代表)",
    title_ja: "三浦アウトドア", romaji: "Miura Outdoor",
    summary_zh: "**三浦+三崎キャンプ・アウトドアウェアは三浦半島キャンプ場 30+ 軒・1990 年代以降ブーム派生 35+ 年・油壷キャンプ場・スノーピーク+モンベル**(三浦+横須賀)。¥9,500-65,000。",
    content_md: "- 立地:**三浦市 + 横須賀市**\n- 起源:**1990 年代以降アウトドアブーム派生 35+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "三浦市", lg_code: "14210",
    area_types: ["shopping_district", "nature_park"], lat: 35.1378, lon: 139.6178,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["miura_outdoor"], source: "manual",
  },
  {
    slug: "kamakura-nabeshima-yaki",
    category: "fashion", sub_type: "kanagawa_dento",
    title_zh: "鎌倉鍋島焼+ 鎌倉陶磁器(鎌倉市・1900 年代以降鎌倉陶芸家集積 100+ 年+ 「鎌倉笹焼」+ 「鎌倉小山陶房」 工房 12+ 軒+ 茶碗+酒盃+大皿+ 鎌倉陶芸協会・¥3,500-45,000・R5 食 鎌倉精進料理連動)",
    title_ja: "鎌倉陶磁器", romaji: "Kamakura Tōjiki",
    summary_zh: "**鎌倉鍋島焼+鎌倉陶磁器は 1900 年代以降陶芸家集積 100+ 年・「鎌倉笹焼」+「鎌倉小山陶房」工房 12+ 軒**(鎌倉)。¥3,500-45,000、R5 食 鎌倉精進料理連動。",
    content_md: "- 立地:**鎌倉市**\n- 起源:**1900 年代以降鎌倉陶芸家集積 100+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["industrial_heritage", "shopping_district"], lat: 35.3197, lon: 139.5519,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kamakura_tojiki"], source: "manual",
  },

  // 住 3
  {
    slug: "enoshima-bnb-villa",
    category: "lodging", sub_type: "kanagawa_shonan_lodging",
    title_zh: "江ノ島+ 片瀬海岸民泊+ ヴィラ(藤沢市江の島+ 片瀬海岸+ 鎌倉七里ガ浜・R1 楽 江ノ島派生・1990 年代以降ヴィラ+民泊 80+ 軒+ オーシャンビュー+ サーフィン直結・小田急片瀬江ノ島駅徒歩 5 分・¥18,000-65,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "江ノ島ヴィラ", romaji: "Enoshima Villa",
    summary_zh: "**江ノ島+片瀬海岸民泊+ヴィラは R1 楽 江ノ島派生・1990 年代以降 80+ 軒・オーシャンビュー+サーフィン直結**(藤沢江の島+片瀬+鎌倉七里ガ浜)。¥18,000-65,000/泊。",
    content_md: "- 立地:**藤沢市江の島 + 片瀬海岸 + 鎌倉七里ガ浜**\n- 関連:**R1 楽 江ノ島派生**\n- 規模:**ヴィラ + 民泊 80+ 軒**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "藤沢市", lg_code: "14205",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 35.2997, lon: 139.4806,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["enoshima_villa"], source: "manual",
  },
  {
    slug: "kennō-farm-stay",
    category: "lodging", sub_type: "kanagawa_kennō_lodging",
    title_zh: "県央ファームステイ+ 大磯ホテルヴィラ(伊勢原市+ 厚木+ 秦野+ 大磯・R1 食 海老名いちご派生農家民泊+ 1990 年代以降ファーミングステイ 35+ 年+ いちご摘取り+ 大磯町ヴィラリゾート・¥9,500-32,000/泊+ 国際観光客向け体験あり)",
    title_ja: "県央ファームステイ", romaji: "Kennō Farm Stay",
    summary_zh: "**県央ファームステイ+大磯ヴィラは R1 食 いちご派生農家民泊+1990 年代以降 35+ 年・いちご摘取り+大磯ヴィラリゾート**(伊勢原+厚木+秦野+大磯)。¥9,500-32,000/泊、国際向け体験。",
    content_md: "- 立地:**伊勢原市 + 厚木市 + 秦野市 + 大磯町**\n- 関連:**R1 食 海老名いちご派生農家民泊 + 1990 年代以降 35+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "厚木市", lg_code: "14212",
    area_types: ["accommodation_ryokan", "farm_field"], lat: 35.4467, lon: 139.3650,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kennō_farm_stay"], source: "manual",
  },
  {
    slug: "shin-yokohama-business-hotels",
    category: "lodging", sub_type: "kanagawa_yokohama_lodging",
    title_zh: "新横浜駅前ビジネスホテル+ 川崎駅前ビジネス(横浜市港北区新横浜+ 川崎市・R1 行 新横浜+JR 川崎派生・新横浜プリンス 1992+ オークラフロンティア新横浜 1989+ 中堅ホテル 35+ 軒・¥9,500-22,000/泊・出張+観光客向け代表)",
    title_ja: "新横浜+川崎ホテル", romaji: "Shin-Yokohama Hotel",
    summary_zh: "**新横浜+川崎駅前ビジネスは R1 行 派生・新横浜プリンス 1992+オークラ 1989+中堅 35+ 軒**(港北新横浜+川崎)。¥9,500-22,000/泊、出張+観光代表。",
    content_md: "- 立地:**横浜市港北区新横浜 + 川崎市**\n- 関連:**R1 行 新横浜 + JR 川崎派生**\n- 規模:**中堅ホテル 35+ 軒**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["accommodation_hotel"], lat: 35.5103, lon: 139.6164,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["shin_yokohama_business"], source: "manual",
  },

  // 育 4
  {
    slug: "shomyoji-1258",
    category: "culture", sub_type: "kanagawa_shrine_temple",
    title_zh: "称名寺(横浜市金沢区金沢町・1258 正嘉 2 年北条実時建立 767+ 年+ 真言律宗別格本山+ 国指定重要文化財 仁王門 1771+ 国宝 「金沢文庫絵」「弥勒来迎図」(R1 育 金沢文庫 R1 派生)・参拝無料・京急金沢文庫駅徒歩 12 分)",
    title_ja: "称名寺", romaji: "Shōmyō-ji",
    summary_zh: "**称名寺は 1258 正嘉 2 年北条実時建立 767+ 年・真言律宗別格本山・国重文 仁王門 1771・国宝 R1 育 金沢文庫派生**(横浜金沢)。京急金沢文庫徒歩 12 分、参拝無料。",
    content_md: "- 立地:**横浜市金沢区金沢町**\n- 起源:**1258 正嘉 2 年北条実時建立 767+ 年**\n- 認定:**真言律宗別格本山 + 国指定重要文化財 仁王門 1771 + 国宝(R1 育 金沢文庫派生)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["history_site_castle"], lat: 35.3486, lon: 139.6250,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shomyoji_1258"], source: "manual",
  },
  {
    slug: "kawasaki-minkaen-1967",
    category: "culture", sub_type: "kanagawa_museum",
    title_zh: "川崎日本民家園(川崎市多摩区枡形・1967 開園 58+ 年+ 全国最大級野外古民家博物館候補+ 7ha 大規模野外博物館+ 国指定重要文化財 民家 6 棟+ 25 棟江戸期古民家移築・¥500・小田急向ヶ丘遊園駅徒歩 13 分)",
    title_ja: "川崎日本民家園", romaji: "Kawasaki Minkaen",
    summary_zh: "**川崎日本民家園は 1967 開園 58+ 年・全国最大級野外古民家博物館候補・7ha・国重文民家 6 棟+25 棟江戸期古民家移築**(川崎多摩枡形)。¥500、小田急向ヶ丘徒歩 13 分。",
    content_md: "- 立地:**川崎市多摩区枡形**\n- 起源:**1967 開園 58+ 年**\n- 認定:**全国最大級野外古民家博物館候補 + 7ha + 国指定重要文化財 民家 6 棟 + 25 棟江戸期古民家移築**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "川崎市", lg_code: "14130",
    area_types: ["museum_art", "history_site_castle"], lat: 35.6133, lon: 139.5453,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["kawasaki_minkaen_1967"], source: "manual",
  },
  {
    slug: "yokohama-museum-art-1989",
    category: "culture", sub_type: "kanagawa_museum",
    title_zh: "横浜美術館(横浜市西区みなとみらい・1989 開館 36+ 年+ 丹下健三設計+ 横浜博覧会記念建設・幕末-現代日本西洋現代美術所蔵 12,000+ 点・常設観覧 ¥500・国際 SNS 海外現代アート代表)",
    title_ja: "横浜美術館", romaji: "Yokohama Museum of Art",
    summary_zh: "**横浜美術館は 1989 開館 36+ 年・丹下健三設計・横浜博覧会記念建設・幕末-現代日本西洋現代美術所蔵 12,000+ 点**(西区みなとみらい)。常設 ¥500、海外現代アート代表。",
    content_md: "- 立地:**横浜市西区みなとみらい**\n- 起源:**1989 開館 36+ 年 + 横浜博覧会記念建設**\n- 認定:**丹下健三設計 + 幕末-現代日本西洋現代美術所蔵 12,000+ 点**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["museum_art"], lat: 35.4569, lon: 139.6308,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["thursday"],
    external_urls: {}, tags: ["yokohama_museum_art_1989"], source: "manual",
  },
  {
    slug: "kanazawa-zoo-1982",
    category: "culture", sub_type: "kanagawa_museum",
    title_zh: "横浜市立金沢動物園(横浜市金沢区釜利谷東・1982 開園 43+ 年+ 横浜市立 2 大動物園(野毛山+金沢)+ 56ha 山地動物園+ コアラ+ ゾウ+ オカピ+ R1 育 金沢文庫+ R4 育 称名寺隣接・¥600)",
    title_ja: "金沢動物園", romaji: "Kanazawa Zoo",
    summary_zh: "**横浜市立金沢動物園は 1982 開園 43+ 年・横浜市立 2 大動物園(野毛山+金沢)・56ha 山地・コアラ+ゾウ+オカピ**(横浜金沢)。R1 育 金沢文庫+R4 育 称名寺隣接、¥600。",
    content_md: "- 立地:**横浜市金沢区釜利谷東**\n- 起源:**1982 開園 43+ 年**\n- 認定:**横浜市立 2 大動物園(野毛山 + 金沢) + 56ha 山地動物園**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["aquarium_zoo"], lat: 35.3486, lon: 139.6250,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["kanazawa_zoo_1982"], source: "manual",
  },

  // 楽 3
  {
    slug: "yokosuka-shobu-en",
    category: "entertainment", sub_type: "kanagawa_miura_entertainment",
    title_zh: "横須賀しょうぶ園(横須賀市阿部倉・1986 開園 39+ 年+ 全国最大級花菖蒲園+ 7ha 大規模庭園+ 200 種 14 万株花菖蒲(6 月旬)+ 4000 株あじさい・¥310・京急横須賀中央駅+バス・国内花季観光客代表)",
    title_ja: "横須賀しょうぶ園", romaji: "Yokosuka Shōbu-en",
    summary_zh: "**横須賀しょうぶ園は 1986 開園 39+ 年・全国最大級花菖蒲園・7ha・200 種 14 万株花菖蒲(6 月)+4000 株あじさい**(横須賀阿部倉)。¥310、花季観光客代表。",
    content_md: "- 立地:**横須賀市阿部倉**\n- 起源:**1986 開園 39+ 年**\n- 認定:**全国最大級花菖蒲園 + 7ha + 200 種 14 万株花菖蒲(6 月旬)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横須賀市", lg_code: "14201",
    area_types: ["nature_park"], lat: 35.2806, lon: 139.6711,
    season_start: "2026-06-01", season_end: "2026-06-30", event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokosuka_shobu"], source: "manual",
  },
  {
    slug: "noge-yama-zoo-1951",
    category: "entertainment", sub_type: "kanagawa_yokohama_entertainment",
    title_zh: "横浜野毛山動物園+ 動物園通り(横浜市中区西戸部町・1951 開園 74+ 年+ 全国最古市立動物園候補(R5 育 上野動物園 1882 後)+ 入園無料(全国唯一の入園無料市立動物園)+ レッサーパンダ+キリン+ライオン・JR 桜木町徒歩 15 分)",
    title_ja: "野毛山動物園", romaji: "Nogeyama Zoo",
    summary_zh: "**横浜野毛山動物園は 1951 開園 74+ 年・全国最古市立動物園候補・入園無料(全国唯一の入園無料市立動物園)・レッサーパンダ+キリン+ライオン**(中区西戸部)。JR 桜木町徒歩 15 分。",
    content_md: "- 立地:**横浜市中区西戸部町**\n- 起源:**1951 開園 74+ 年**\n- 認定:**入園無料(全国唯一の入園無料市立動物園) + レッサーパンダ + キリン + ライオン**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["aquarium_zoo"], lat: 35.4456, lon: 139.6217,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["noge_yama_1951"], source: "manual",
  },
  {
    slug: "oiso-station-walk",
    category: "entertainment", sub_type: "kanagawa_shonan_entertainment",
    title_zh: "大磯町散策+ 旧伊藤博文邸+ 大磯駅周辺(中郡大磯町・1885 大磯駅開業 140+ 年+ 1894 旧伊藤博文邸「滄浪閣」(国登録 1996)+ R1 育 旧吉田茂邸+ 大磯ロングビーチ+ 大磯町文学館・無料散策・国際 SNS 政治史代表)",
    title_ja: "大磯町散策", romaji: "Ōiso Walk",
    summary_zh: "**大磯町散策+旧伊藤博文邸+大磯駅は 1885 駅開業 140+ 年+1894 旧伊藤邸「滄浪閣」国登録 1996・R1 育 吉田茂邸+R2 楽 ロングビーチ+文学館**(大磯)。無料、政治史代表。",
    content_md: "- 立地:**中郡大磯町**\n- 起源:**1885 大磯駅開業 140+ 年 + 1894 旧伊藤博文邸「滄浪閣」国登録 1996**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "中郡", municipality_ja: "大磯町", lg_code: "14341",
    area_types: ["history_site_castle"], lat: 35.3056, lon: 139.3211,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["oiso_walk"], source: "manual",
  },

  // 行 2
  {
    slug: "kawasaki-bus-1939",
    category: "transport", sub_type: "kanagawa_subway",
    title_zh: "川崎市営バス(川崎市・1939 開業 86+ 年+ 全国大手都市バス網候補+ 川崎駅+ 川崎大師+ 京浜工業地帯主要路線・1 日 30 万人乗降+ 民営+市営合計 100+ 路線・¥220 均一)",
    title_ja: "川崎市営バス", romaji: "Kawasaki Bus",
    summary_zh: "**川崎市営バスは 1939 開業 86+ 年・全国大手都市バス網候補・川崎駅+川崎大師+京浜工業地帯・1 日 30 万人乗降・100+ 路線**(川崎)。¥220 均一。",
    content_md: "- 立地:**川崎市**\n- 起源:**1939 開業 86+ 年**\n- 規模:**川崎駅 + 川崎大師 + 京浜工業地帯主要路線 + 1 日 30 万人乗降**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "川崎市", lg_code: "14130",
    area_types: ["transport_hub"], lat: 35.5308, lon: 139.7028,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kawasaki_bus_1939"], source: "manual",
  },
  {
    slug: "izu-hakone-railway",
    category: "transport", sub_type: "kanagawa_private_railway",
    title_zh: "伊豆箱根鉄道大雄山線(小田原市+南足柄市・1925 大雄山鉄道として開業 100+ 年+ 小田原-大雄山駅 9.6km・12 駅+ 大雄山最乗寺(1394 開山)アクセス・¥280/片道+ R1 行 小田原駅 R1 派生)",
    title_ja: "伊豆箱根鉄道大雄山線", romaji: "Izu-Hakone Daiyūzan",
    summary_zh: "**伊豆箱根鉄道大雄山線は 1925 大雄山鉄道として開業 100+ 年・小田原-大雄山 9.6km+12 駅・大雄山最乗寺 1394 アクセス**(小田原+南足柄)。¥280/片道、R1 行 小田原派生。",
    content_md: "- 立地:**小田原市 + 南足柄市**\n- 起源:**1925 大雄山鉄道として開業 100+ 年**\n- 認定:**大雄山最乗寺(1394 開山)アクセス**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "小田原市", lg_code: "14206",
    area_types: ["transport_hub"], lat: 35.2581, lon: 139.1556,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["izu_hakone_daiyuzan_1925"], source: "manual",
  },
];

seedMain(rows, "kanagawa-r4");
