// Seed 大阪府 · 住類 條目 → public.japan_entries(Sprint 17.8 住 R1)
//
// 大阪の住類軸:
//   - ラグジュアリー:Ritz-Carlton(1997 関西初) + Conrad(2017) + St. Regis(2010) + W(2021) + Four Seasons(2024) + Imperial(1996) + Hilton(1986)
//   - アッパーミドル:Swissotel + Granvia + Hyatt Regency + New Otani + Marriott Miyako + Rihga Royal + ANA Crowne
//   - ビジネスチェーン:アパ + 東横イン + 三井ガーデン + リッチモンド + ドーミーイン + スーパーホテル
//   - USJ オフィシャル 4:ユニバーサルポート + 京阪 + パークフロント + JR
//   - カプセル + ホステル:ナインアワーズ + ファーストキャビン + Khaosan + Drop Inn
//   - 関空:日航関空(1994) + ハイアット関西空港 + スターゲートホテル(りんくう)
//
// 嚴格定義:具体ホテル・実在ステイ施設のみ。エリア概論なし(SKIP_SUB_TYPES の lodging_area_guide が既存)。
//
// 43 筆構成
//
// Usage:
//   npm run seed:japan-osaka-lodging:dry
//   npm run seed:japan-osaka-lodging

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "luxury_hotel"
  | "international_luxury"
  | "budget_hotel_chain"
  | "capsule_hostel"
  | "osaka_usj_official"
  | "osaka_kix_airport";

interface SeedRow {
  slug: string;
  category: "lodging";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "kansai";
  prefecture_ja: "大阪府";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ══════════════════════════════════════════════════════════════════
  // A. ラグジュアリー 国際系(7 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "ritz-carlton-osaka",
    category: "lodging",
    sub_type: "international_luxury",
    title_zh: "ザ・リッツ・カールトン大阪(1997・関西初リッツ・梅田)",
    title_ja: "ザ・リッツ・カールトン大阪",
    romaji: "The Ritz-Carlton Ōsaka",
    summary_zh:
      "1997 ハービスエント(梅田西)に開業の関西初リッツ・カールトン。地下 1 階 + 地上 37 階・292 室。英国王侯貴族邸宅をモチーフのインテリア。10F 香港レストラン花筐 + ロビーの 18C 英国アンティーク家具。大阪駅徒歩 7 分,関西旅行の格付け基準として 1 泊 ¥80000-200000。",
    content_md:
      "- 開業:1997(関西初リッツ)\n- 立地:ハービスエント(梅田西)\n- 客室:292 室・37F\n- 1 泊:¥80000-200000\n- アクセス:大阪駅徒歩 7 分\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.700,
    lon: 135.495,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["luxury", "ritz_carlton", "umeda", "since_1997"],
    source: "manual",
  },
  {
    slug: "conrad-osaka",
    category: "lodging",
    sub_type: "international_luxury",
    title_zh: "コンラッド大阪(2017・中之島フェスティバルタワー W・40F 天空ホテル)",
    title_ja: "コンラッド大阪",
    romaji: "Conrad Ōsaka",
    summary_zh:
      "2017 中之島フェスティバルタワー West(高 200 m)33-40F に開業の Hilton 系ラグジュアリー Conrad ブランド。164 室・全室 38F 以上の高層ビュー(大阪湾 + 大阪城 + 都市夜景一望)。隣接の朝日新聞 + フェスティバルホール + 中之島香雪美術館との文化集積地。京阪中之島線『渡辺橋駅』直結。",
    content_md:
      "- 開業:2017\n- 立地:中之島フェスティバルタワー West 33-40F\n- 客室:164 室\n- 全室 38F 以上\n- 京阪渡辺橋駅直結\n- 1 泊:¥60000-150000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.692,
    lon: 135.493,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.hilton.com/ja/hotels/osakaci-conrad-osaka/" },
    tags: ["luxury", "conrad", "nakanoshima", "since_2017", "skyhotel"],
    source: "manual",
  },
  {
    slug: "st-regis-osaka",
    category: "lodging",
    sub_type: "international_luxury",
    title_zh: "セントレジスホテル大阪(2010・関西初・本町・全室バトラーサービス)",
    title_ja: "セントレジスホテル大阪",
    romaji: "St. Regis Ōsaka",
    summary_zh:
      "2010 中央区本町に開業の関西初セントレジス(マリオット系最高級ブランド)。全 160 室・27F・1 室 60 ㎡以上の広さ。全室バトラーサービス(専属バトラー 1 室 1 人配備)+ コンシェルジュ。御堂筋沿で大丸心斎橋本店 + 高級ブランド街徒歩 5 分。",
    content_md:
      "- 開業:2010(関西初セントレジス)\n- 立地:本町(御堂筋沿)\n- 客室:160 室・27F・1 室 60 ㎡+\n- 全室バトラーサービス\n- 1 泊:¥80000-180000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.marriott.co.jp/hotels/travel/osaxr-the-st-regis-osaka/" },
    tags: ["luxury", "st_regis", "honmachi", "since_2010", "butler"],
    source: "manual",
  },
  {
    slug: "w-osaka",
    category: "lodging",
    sub_type: "international_luxury",
    title_zh: "W 大阪(2021・関西初 W・心斎橋・安藤忠雄設計)",
    title_ja: "W 大阪",
    romaji: "W Ōsaka",
    summary_zh:
      "2021 御堂筋心斎橋に開業の関西初 W ホテル(マリオット系ライフスタイルラグジュアリー)。安藤忠雄設計のコンクリ + ガラスファサード,27F・337 室。Bar『MIXup』+ ロビー巨大水盤 + 屋上プール『WET DECK』。心斎橋筋徒歩 3 分・道頓堀徒歩 7 分。",
    content_md:
      "- 開業:2021(関西初 W)\n- 設計:安藤忠雄\n- 客室:337 室・27F\n- 名物:屋上プール WET DECK\n- 心斎橋筋徒歩 3 分\n- 1 泊:¥45000-150000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.674,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.marriott.co.jp/hotels/travel/osaow-w-osaka/" },
    tags: ["luxury", "w_hotel", "shinsaibashi", "since_2021", "ando_tadao"],
    source: "manual",
  },
  {
    slug: "imperial-hotel-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "帝国ホテル大阪(1996・北区天満・大川沿・桜之宮ビュー)",
    title_ja: "帝国ホテル大阪",
    romaji: "Imperial Hotel Ōsaka",
    summary_zh:
      "1996 帝国ホテル(東京 1923 創業)が北区天満橋大川沿に開業の関西本店。22F・381 室。大川 + 桜之宮公園 + 大阪城のビュー。和食『嘉門』+ フランス料理『レ・セゾン』+ 中華『ジャスミン・ガーデン』の格式高いレストラン。JR 桜ノ宮駅徒歩 5 分。",
    content_md:
      "- 開業:1996\n- 立地:北区天満橋(大川沿)\n- 客室:381 室・22F\n- 大川 + 桜之宮 + 大阪城ビュー\n- JR 桜ノ宮駅徒歩 5 分\n- 1 泊:¥35000-120000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.701,
    lon: 135.524,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.imperialhotel.co.jp/osaka/" },
    tags: ["luxury", "imperial", "okawa", "since_1996", "sakuranomiya_view"],
    source: "manual",
  },
  {
    slug: "four-seasons-osaka",
    category: "lodging",
    sub_type: "international_luxury",
    title_zh: "フォーシーズンズホテル大阪(2024 開業・関西初 FS・大手前 OBP 北・最新最高級)",
    title_ja: "フォーシーズンズホテル大阪",
    romaji: "Four Seasons Hotel Ōsaka",
    summary_zh:
      "2024/8 中央区大手前(大阪城公園北・OBP 北側)に開業の関西初フォーシーズンズ。地下 1 階 + 地上 39 階・175 室。大阪城 + 大川 + 都市夜景の絶景。Modern Japanese + Italian + Lounge の 3 レストラン。安田秀一設計の和モダン建築。",
    content_md:
      "- 開業:2024/8(関西初 FS)\n- 立地:中央区大手前(大阪城公園北)\n- 客室:175 室・39F\n- 設計:安田秀一(和モダン)\n- 大阪城 + 大川絶景\n- 1 泊:¥100000-300000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.689,
    lon: 135.524,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.fourseasons.com/jp/osaka/" },
    tags: ["luxury", "four_seasons", "ote_mae", "since_2024", "newest"],
    source: "manual",
  },
  {
    slug: "hilton-osaka",
    category: "lodging",
    sub_type: "international_luxury",
    title_zh: "ヒルトン大阪(1986・関西初ヒルトン・梅田・大阪駅前ビル)",
    title_ja: "ヒルトン大阪",
    romaji: "Hilton Ōsaka",
    summary_zh:
      "1986 大阪駅前西側に開業の関西初ヒルトン。35F・525 室。日本初の高層ヒルトンで,1990s 関西経済バブル期の象徴的高級ホテル。フランス料理『ロカンダ』+ 中華『黄龍 2』+ 鉄板『元気』。JR 大阪駅徒歩 3 分。",
    content_md:
      "- 開業:1986(関西初ヒルトン)\n- 客室:525 室・35F\n- JR 大阪駅徒歩 3 分\n- 1 泊:¥30000-80000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.701,
    lon: 135.494,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.hiltonhotels.jp/hotel/kansai/hilton-osaka" },
    tags: ["luxury", "hilton", "umeda", "since_1986"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // B. アッパーミドル(8 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "swissotel-nankai-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "スイスホテル南海大阪(1990・なんば駅直結・36F・国際カンファレンス)",
    title_ja: "スイスホテル南海大阪",
    romaji: "Swissôtel Nankai Ōsaka",
    summary_zh:
      "1990 南海なんば駅併設に開業の国際クラス Swissôtel(現・アコーグループ)。36F・546 室。なんば駅直結で関空特急ラピート始発駅 → なんば → ホテルが直結アクセス。なんばパークス + 高島屋なんば本店徒歩 1 分。",
    content_md:
      "- 開業:1990\n- 立地:南海なんば駅併設\n- 客室:546 室・36F\n- 関空ラピート始発直結\n- 1 泊:¥18000-50000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.501,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.swissotel.com/hotels/nankai-osaka/" },
    tags: ["luxury", "swissotel", "namba", "since_1990", "rapid_direct"],
    source: "manual",
  },
  {
    slug: "hotel-granvia-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテルグランヴィア大阪(1983・JR 大阪駅直結・26F・JR 西日本旗艦)",
    title_ja: "ホテルグランヴィア大阪",
    romaji: "Hotel Granvia Ōsaka",
    summary_zh:
      "1983 JR 大阪駅(アクティ大阪)併設に開業の JR 西日本系ホテル。26F・714 室の関西最大級客室数。JR 大阪駅直結で,関西国際空港特急 はるか + 新幹線 + 在来線アクセス最強。1995 阪神大震災の災害本部としても機能。",
    content_md:
      "- 開業:1983\n- 立地:JR 大阪駅直結\n- 客室:714 室・26F(関西最大級)\n- 1 泊:¥18000-45000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.703,
    lon: 135.495,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.granvia-osaka.jp/" },
    tags: ["luxury", "granvia", "jr_osaka", "since_1983", "max_rooms"],
    source: "manual",
  },
  {
    slug: "hyatt-regency-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ハイアットリージェンシー大阪(1994・港区咲洲・ベイエリア・大阪 WTC 隣)",
    title_ja: "ハイアットリージェンシー大阪",
    romaji: "Hyatt Regency Ōsaka",
    summary_zh:
      "1994 港区南港咲洲(ATC・大阪 WTC 隣接)に開業のハイアット。28F・474 室。ベイエリア立地で大阪湾 + USJ 連絡船 + 関空特急ラピート(駅直結)へのアクセス容易。大阪市内中心部からは大阪メトロ南港ポートタウン線で 25 分。",
    content_md:
      "- 開業:1994\n- 立地:港区咲洲(ATC 隣接)\n- 客室:474 室・28F\n- ベイエリア + 関空ラピート直結\n- 1 泊:¥20000-60000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.629,
    lon: 135.420,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.hyatt.com/ja-JP/hotel/japan/hyatt-regency-osaka/osakr" },
    tags: ["luxury", "hyatt_regency", "sakishima", "bay", "since_1994"],
    source: "manual",
  },
  {
    slug: "hotel-new-otani-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテルニューオータニ大阪(1986・大阪城公園隣接・37F・大阪城ビュー)",
    title_ja: "ホテルニューオータニ大阪",
    romaji: "Hotel New Ōtani Ōsaka",
    summary_zh:
      "1986 中央区大阪城公園隣接(OBP・大阪ビジネスパーク内)に開業のニューオータニ系。37F・525 室。大阪城天守閣ビューが最大特色で,京橋駅徒歩 7 分。大手企業 OBP との連動でビジネス + 観光両用。",
    content_md:
      "- 開業:1986\n- 立地:OBP(大阪城公園隣接)\n- 客室:525 室・37F\n- 大阪城天守閣ビュー\n- 京橋駅徒歩 7 分\n- 1 泊:¥25000-70000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.694,
    lon: 135.532,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.newotani.co.jp/osaka/" },
    tags: ["luxury", "new_otani", "obp", "since_1986", "castle_view"],
    source: "manual",
  },
  {
    slug: "osaka-marriott-miyako",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "大阪マリオット都ホテル(2014・あべのハルカス内・38-55F・関西最高層ホテル)",
    title_ja: "大阪マリオット都ホテル",
    romaji: "Ōsaka Marriott Miyako Hotel",
    summary_zh:
      "2014 あべのハルカス(高 300 m)38-55F に開業の関西最高層ホテル。360 室の全室高層ビュー(大阪市内 + 大阪湾 + 京都方面)。マリオット国際 + 都ホテル(近鉄系)の合資ブランド。隣接ハルカス百貨店 + 美術館 + 展望台連結。",
    content_md:
      "- 開業:2014\n- 立地:あべのハルカス 38-55F\n- 客室:360 室\n- 関西最高層ホテル\n- 全室高層ビュー\n- 1 泊:¥30000-100000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.646,
    lon: 135.514,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["luxury", "marriott", "miyako", "harukas", "since_2014", "tallest"],
    source: "manual",
  },
  {
    slug: "rihga-royal-hotel-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "リーガロイヤルホテル(1965・中之島・大阪老舗最高級・JR 西日本系)",
    title_ja: "リーガロイヤルホテル",
    romaji: "Rihga Royal Hotel",
    summary_zh:
      "1965 中之島(土佐堀川沿)に開業の大阪老舗最高級ホテル(リーガロイヤルホテルズ本店)。30F・963 室の関西最大級客室数。1970 万博開催時の海外賓客接待主舞台。皇室 + 海外要人の常宿として知られる。隣接の朝日新聞 + 中之島香雪美術館 + 大阪国際会議場との文化集積地。",
    content_md:
      "- 開業:1965\n- 立地:中之島(土佐堀川沿)\n- 客室:963 室・30F(関西最大級)\n- 皇室 + 海外要人常宿\n- 1970 万博海外賓客主舞台\n- 1 泊:¥18000-50000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.694,
    lon: 135.488,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.rihga.co.jp/osaka" },
    tags: ["luxury", "rihga_royal", "nakanoshima", "since_1965", "imperial_guest"],
    source: "manual",
  },
  {
    slug: "ana-crowne-plaza-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ANA クラウンプラザホテル大阪(1986・大阪駅徒歩 5 分・21F)",
    title_ja: "ANA クラウンプラザホテル大阪",
    romaji: "ANA Crowne Plaza Ōsaka",
    summary_zh:
      "1986 大阪駅徒歩 5 分の北区堂島浜に開業の ANA 系国際クラス。21F・475 室。1986 開業時は ANA ホテル,2010 IHG クラウンプラザブランド統合。中之島 + 堂島浜の中間立地。淀屋橋駅徒歩 5 分。",
    content_md:
      "- 開業:1986(2010 クラウンプラザ統合)\n- 客室:475 室・21F\n- 大阪駅徒歩 5 分\n- 1 泊:¥18000-45000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.694,
    lon: 135.495,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.anacrowneplaza-osaka.jp/" },
    tags: ["luxury", "ana_crowne_plaza", "umeda", "since_1986"],
    source: "manual",
  },
  {
    slug: "hotel-monterey-grasmere",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテルモントレ グラスミア大阪(1991・なんば・英国コッツウォルズ風)",
    title_ja: "ホテルモントレ グラスミア大阪",
    romaji: "Hotel Monterey La Sœur Ōsaka",
    summary_zh:
      "1991 なんば駅(なんばCITY 隣接)に開業のホテルモントレ系。英国コッツウォルズ風建築 + インテリアで,21F・341 室。なんば駅徒歩 3 分でアクセス最強の中堅ラグジュアリー。大阪 5 大ラグジュアリーの一角。",
    content_md:
      "- 開業:1991\n- 立地:なんば駅徒歩 3 分\n- 様式:英国コッツウォルズ風\n- 客室:341 室・21F\n- 1 泊:¥15000-35000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.501,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.hotelmonterey.co.jp/grasmere/" },
    tags: ["luxury", "monterey", "grasmere", "namba", "since_1991", "british"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // C. ミドル + ブティック(7 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "cross-hotel-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "クロスホテル大阪(2008・心斎橋・モダンデザイン・京阪系)",
    title_ja: "クロスホテル大阪",
    romaji: "Cross Hotel Ōsaka",
    summary_zh:
      "2008 心斎橋筋商店街隣接に開業の京阪電鉄系デザインホテル。15F・226 室。アジアン + モダン融合のインテリア。心斎橋駅徒歩 3 分・道頓堀徒歩 5 分でファッション + 観光客中心。1 泊 ¥15000-30000 のミドル価格帯。",
    content_md:
      "- 開業:2008\n- 立地:心斎橋筋商店街隣接\n- 客室:226 室・15F\n- 心斎橋駅徒歩 3 分\n- 1 泊:¥15000-30000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.674,
    lon: 135.501,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.crosshotel.com/osaka/" },
    tags: ["boutique", "cross", "shinsaibashi", "since_2008"],
    source: "manual",
  },
  {
    slug: "moxy-osaka-honmachi",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "モクシー大阪本町(2019・若年向 Marriott・SNS スポット)",
    title_ja: "モクシー大阪本町",
    romaji: "Moxy Ōsaka Honmachi",
    summary_zh:
      "2019 中央区本町に開業の Marriott 系若年向ライフスタイルブランド Moxy。13F・220 室。アジア初の Moxy 旗艦の一つ。エントランス『Bar 兼 ロビー兼 チェックイン』のオープン構造で SNS スポット。本町駅徒歩 2 分。1 泊 ¥12000-25000 のミドル価格帯。",
    content_md:
      "- 開業:2019\n- 立地:本町駅徒歩 2 分\n- 客室:220 室・13F\n- アジア初 Moxy 旗艦\n- 1 泊:¥12000-25000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.501,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.marriott.com/ja/hotels/osamx-moxy-osaka-honmachi/" },
    tags: ["boutique", "moxy", "honmachi", "since_2019", "young"],
    source: "manual",
  },
  {
    slug: "mitsui-garden-osaka-premier",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "三井ガーデンホテル大阪プレミア(2014・中之島フェスティバルタワー West・展望)",
    title_ja: "三井ガーデンホテル大阪プレミア",
    romaji: "Mitsui Garden Hotel Ōsaka Premier",
    summary_zh:
      "2014 中之島フェスティバルタワー West 17-32F に開業の三井ガーデンプレミアブランド。273 室の高層ビュー(全室 17F 以上)。1F-3F は同タワーの中之島香雪美術館 + フェスティバルホール。京阪渡辺橋駅直結。",
    content_md:
      "- 開業:2014\n- 立地:中之島フェスティバルタワー West 17-32F\n- 客室:273 室\n- 全室 17F 以上\n- 京阪渡辺橋駅直結\n- 1 泊:¥15000-35000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.692,
    lon: 135.493,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.gardenhotels.co.jp/osaka-premier/" },
    tags: ["mid_class", "mitsui_garden", "nakanoshima", "since_2014"],
    source: "manual",
  },
  {
    slug: "hotel-monterey-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテルモントレ大阪(1996・梅田・ベルギー風建築)",
    title_ja: "ホテルモントレ大阪",
    romaji: "Hotel Monterey Ōsaka",
    summary_zh:
      "1996 北区曽根崎(梅田南)に開業のホテルモントレ系。ベルギー風アール・デコ建築 + インテリアで,15F・360 室。大阪駅徒歩 5 分。1 泊 ¥10000-25000 のミドルエントリー価格帯。",
    content_md:
      "- 開業:1996\n- 立地:北区曽根崎(梅田南)\n- 様式:ベルギー風アール・デコ\n- 客室:360 室・15F\n- 大阪駅徒歩 5 分\n- 1 泊:¥10000-25000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.701,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.hotelmonterey.co.jp/osaka/" },
    tags: ["mid_class", "monterey", "umeda", "since_1996", "belgium"],
    source: "manual",
  },
  {
    slug: "hotel-monterey-la-soeur-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテルモントレ ラ・スールおおさか(1995・西天満・大川沿)",
    title_ja: "ホテルモントレ ラ・スールおおさか",
    romaji: "Hotel Monterey La Sœur Ōsaka",
    summary_zh:
      "1995 北区西天満(大川沿)に開業のホテルモントレ系姉妹ホテル。フランス風建築で,15F・244 室。大川 + 大阪市中央公会堂(中之島)+ 桜之宮ビュー。京阪天満橋駅徒歩 5 分。1 泊 ¥10000-22000。",
    content_md:
      "- 開業:1995\n- 立地:北区西天満(大川沿)\n- 様式:フランス風建築\n- 客室:244 室・15F\n- 京阪天満橋駅徒歩 5 分\n- 1 泊:¥10000-22000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.696,
    lon: 135.510,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.hotelmonterey.co.jp/lasoeur_osaka/" },
    tags: ["mid_class", "monterey", "la_soeur", "tenma", "since_1995"],
    source: "manual",
  },
  {
    slug: "mitsui-garden-yodoyabashi",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "三井ガーデンホテル大阪淀屋橋(2003・船場・ビジネス + 観光両用)",
    title_ja: "三井ガーデンホテル大阪淀屋橋",
    romaji: "Mitsui Garden Hotel Ōsaka Yodoyabashi",
    summary_zh:
      "2003 中央区今橋(淀屋橋・船場)に開業の三井ガーデン系ミドルクラス。15F・410 室。日比野克彦アート装飾。淀屋橋駅 + 北浜駅徒歩 5 分でビジネス + 観光両用。1 泊 ¥10000-25000。",
    content_md:
      "- 開業:2003\n- 立地:今橋(淀屋橋・船場)\n- 客室:410 室・15F\n- 日比野克彦アート\n- 1 泊:¥10000-25000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.692,
    lon: 135.503,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["mid_class", "mitsui_garden", "yodoyabashi", "since_2003"],
    source: "manual",
  },
  {
    slug: "hotel-the-flag-shinsaibashi",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテル ザ フラッグ心斎橋(2018・心斎橋・モダンデザイン)",
    title_ja: "ホテル ザ フラッグ心斎橋",
    romaji: "Hotel The Flag Shinsaibashi",
    summary_zh:
      "2018 心斎橋筋商店街徒歩 3 分に開業のモダンデザインホテル。10F・180 室。香港 + 台湾アジアテイスト + 木材インテリアの混合。1F カフェ『MOI』が朝食 + ロビー機能。心斎橋駅 + 道頓堀徒歩 5 分。1 泊 ¥9000-20000。",
    content_md:
      "- 開業:2018\n- 立地:心斎橋筋商店街徒歩 3 分\n- 客室:180 室・10F\n- アジアテイスト + 木材\n- 1 泊:¥9000-20000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.674,
    lon: 135.502,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["boutique", "the_flag", "shinsaibashi", "since_2018"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // D. ビジネスチェーン(7 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "apa-namba-shinsaibashi",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "アパホテル難波心斎橋駅東(なんば駅東・観光客 No.1 アパ・温泉大浴場)",
    title_ja: "アパホテル難波心斎橋駅東",
    romaji: "APA Hotel Namba Shinsaibashi-Eki Higashi",
    summary_zh:
      "なんば駅東口徒歩 2 分の大型アパホテル。20F・600 室余の関西最大級アパで,屋上に温泉大浴場併設。心斎橋筋 + 道頓堀 + 黒門市場徒歩 10 分圏で観光客 No.1。1 泊 ¥8000-15000 のビジネス価格帯。",
    content_md:
      "- 立地:なんば駅東口徒歩 2 分\n- 客室:600 室余・20F\n- 屋上温泉大浴場\n- 観光客 No.1 アパ\n- 1 泊:¥8000-15000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.503,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["budget", "apa", "namba", "onsen_bath"],
    source: "manual",
  },
  {
    slug: "apa-osaka-umeda",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "アパホテル新大阪駅前(新大阪駅前・新幹線ビジネス No.1)",
    title_ja: "アパホテル新大阪駅前",
    romaji: "APA Hotel Shin-Osaka-Eki-Mae",
    summary_zh:
      "新大阪駅西口徒歩 3 分の大型アパホテル。15F・500 室余。新幹線『のぞみ』+ 関空特急『はるか』直結で,東京 + 関空からのビジネス出張客 No.1。1 泊 ¥7000-13000。",
    content_md:
      "- 立地:新大阪駅西口徒歩 3 分\n- 客室:500 室余・15F\n- 新幹線 + 関空特急直結\n- 1 泊:¥7000-13000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.733,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["budget", "apa", "shin_osaka", "shinkansen"],
    source: "manual",
  },
  {
    slug: "toyoko-inn-osaka-namba",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "東横イン大阪なんば(なんば駅前・全国チェーン関西旗艦)",
    title_ja: "東横イン大阪なんば",
    romaji: "Toyoko Inn Ōsaka Namba",
    summary_zh:
      "なんば駅西口徒歩 5 分の東横イン(全国 300 店舗超のビジネスチェーン)関西旗艦。10F・250 室。全室 Wi-Fi + 朝食バイキング無料。1 泊 ¥6000-10000。会員は ¥500-1000 割引。",
    content_md:
      "- 立地:なんば駅西口徒歩 5 分\n- 客室:250 室・10F\n- 朝食バイキング無料\n- 会員割引\n- 1 泊:¥6000-10000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.toyoko-inn.com/" },
    tags: ["budget", "toyoko_inn", "namba", "free_breakfast"],
    source: "manual",
  },
  {
    slug: "richmond-osaka-namba",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "リッチモンドホテル難波大国町(なんば南・ロイヤルパインズ系)",
    title_ja: "リッチモンドホテル難波大国町",
    romaji: "Richmond Hotel Namba Daikokuchō",
    summary_zh:
      "なんば駅南徒歩 7 分(大国町駅徒歩 3 分)のリッチモンドホテル(ロイヤルパインズ系の中堅ビジネスチェーン)。13F・182 室。なんば + でんでんタウン + 通天閣徒歩 10 分圏。1 泊 ¥8000-14000。",
    content_md:
      "- 立地:大国町駅徒歩 3 分(なんば南)\n- 客室:182 室・13F\n- 1 泊:¥8000-14000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.658,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["budget", "richmond", "namba", "daikokucho"],
    source: "manual",
  },
  {
    slug: "dormy-inn-namba-osaka",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "ドーミーイン難波(なんば駅・天然温泉付ビジネス・夜鳴きそば無料)",
    title_ja: "ドーミーイン難波",
    romaji: "Dormy Inn Namba",
    summary_zh:
      "なんば駅徒歩 7 分のドーミーイン(共立メンテナンス系)。13F・220 室。天然温泉大浴場(地下 1500 m 掘削)+ 夜鳴きそば無料サービスが名物。ビジネス + 観光両用。1 泊 ¥10000-17000。",
    content_md:
      "- 立地:なんば駅徒歩 7 分\n- 客室:220 室・13F\n- 天然温泉大浴場(地下 1500 m)\n- 夜鳴きそば無料\n- 1 泊:¥10000-17000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.502,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["budget", "dormy_inn", "namba", "natural_onsen", "yonaki_soba"],
    source: "manual",
  },
  {
    slug: "super-hotel-tennouji",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "スーパーホテル天王寺(天王寺・大阪中堅チェーン創業地)",
    title_ja: "スーパーホテル天王寺",
    romaji: "Super Hotel Tennōji",
    summary_zh:
      "1989 大阪市西成創業のスーパーホテル(全国 150 店舗超のビジネスチェーン)の天王寺店。10F・110 室。あべのハルカス徒歩 7 分。価格安(1 泊 ¥5500-9500)で関西出張客に人気。",
    content_md:
      "- 立地:天王寺(あべのハルカス徒歩 7 分)\n- 客室:110 室・10F\n- 1 泊:¥5500-9500\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.643,
    lon: 135.516,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.superhotel.co.jp/s_hotels/tennouji/" },
    tags: ["budget", "super_hotel", "tennoji", "since_1989"],
    source: "manual",
  },
  {
    slug: "hotel-keihan-kyobashi",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "ホテル京阪 京橋 グランデ(京橋駅前・京阪沿線アクセス)",
    title_ja: "ホテル京阪 京橋 グランデ",
    romaji: "Hotel Keihan Kyōbashi Grande",
    summary_zh:
      "京阪電鉄系のホテル京阪 京橋本店。京橋駅徒歩 5 分の 13F・217 室。京阪沿線(枚方 + 寝屋川 + 京都)からのビジネス出張 + 観光客に便利。1 泊 ¥8000-15000。",
    content_md:
      "- 立地:京橋駅徒歩 5 分\n- 客室:217 室・13F\n- 京阪沿線アクセス\n- 1 泊:¥8000-15000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.696,
    lon: 135.534,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["budget", "keihan", "kyobashi"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // E. USJ オフィシャル 4 ホテル(4 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "hotel-universal-port",
    category: "lodging",
    sub_type: "osaka_usj_official",
    title_zh: "ホテル ユニバーサル ポート(2001・USJ 開業同時・USJ オフィシャル第 1 号)",
    title_ja: "ホテル ユニバーサル ポート",
    romaji: "Hotel Universal Port",
    summary_zh:
      "2001 USJ 開業と同時に開業した USJ オフィシャル第 1 号ホテル。28F・600 室の大型。USJ ゲート徒歩 5 分で USJ 限定アーリーパークインアクセス権付。家族向 + キャラクタールーム充実。",
    content_md:
      "- 開業:2001(USJ 同時)\n- 立地:USJ ゲート徒歩 5 分\n- 客室:600 室・28F\n- USJ 早期入園権付\n- 1 泊:¥18000-50000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.667,
    lon: 135.430,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.hoteluniversalport.jp/" },
    tags: ["usj_official", "universal_port", "since_2001", "first"],
    source: "manual",
  },
  {
    slug: "hotel-keihan-universal-tower",
    category: "lodging",
    sub_type: "osaka_usj_official",
    title_zh: "ホテル京阪ユニバーサル・タワー(2008・USJ 隣接・36F 関西最高層 USJ ホテル)",
    title_ja: "ホテル京阪ユニバーサル・タワー",
    romaji: "Hotel Keihan Universal Tower",
    summary_zh:
      "2008 USJ 隣接のユニバーサル・シティウォーク横に開業の USJ オフィシャル。36F・631 室で関西最高層 USJ ホテル。USJ ゲート徒歩 1 分。USJ 早期入園権付。1 泊 ¥17000-50000。",
    content_md:
      "- 開業:2008\n- 立地:USJ ゲート徒歩 1 分\n- 客室:631 室・36F(関西最高層 USJ)\n- USJ 早期入園権付\n- 1 泊:¥17000-50000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.667,
    lon: 135.432,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["usj_official", "keihan_tower", "since_2008", "tallest"],
    source: "manual",
  },
  {
    slug: "park-front-hotel-usj",
    category: "lodging",
    sub_type: "osaka_usj_official",
    title_zh: "ザ パークフロントホテル at ユニバーサル・スタジオ・ジャパン(2014・USJ 正面)",
    title_ja: "ザ パークフロントホテル at ユニバーサル・スタジオ・ジャパン",
    romaji: "The Park Front Hotel at USJ",
    summary_zh:
      "2014 USJ 正面ゲートの真正面に開業の USJ オフィシャル。30F・600 室。USJ ゲート徒歩 1 分の最短アクセス + USJ ロゴ正面ビュー。USJ 早期入園権付。1 泊 ¥18000-55000。",
    content_md:
      "- 開業:2014\n- 立地:USJ 正面ゲート徒歩 1 分\n- 客室:600 室・30F\n- USJ 早期入園権付\n- 1 泊:¥18000-55000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.667,
    lon: 135.433,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.parkfronthotel.com/" },
    tags: ["usj_official", "park_front", "since_2014"],
    source: "manual",
  },
  {
    slug: "jr-hotel-universal-city",
    category: "lodging",
    sub_type: "osaka_usj_official",
    title_zh: "ホテル近鉄ユニバーサル・シティ(2008・USJ 西端・JR 西日本系)",
    title_ja: "ホテル近鉄ユニバーサル・シティ",
    romaji: "Hotel Kintetsu Universal City",
    summary_zh:
      "2008 USJ 隣接のユニバーサル・シティウォーク西端に開業の近鉄系 USJ オフィシャル。15F・440 室。USJ ゲート徒歩 5 分。USJ 早期入園権付。1 泊 ¥15000-45000。家族向け価格帯。",
    content_md:
      "- 開業:2008\n- 立地:USJ ゲート徒歩 5 分\n- 客室:440 室・15F\n- USJ 早期入園権付\n- 1 泊:¥15000-45000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.667,
    lon: 135.435,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["usj_official", "kintetsu", "since_2008"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // F. カプセル + ホステル(5 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "nine-hours-namba",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "ナインアワーズなんば駅(2013・SF 系カプセル・1.5 万円/月割安)",
    title_ja: "ナインアワーズなんば駅",
    romaji: "Nine Hours Namba",
    summary_zh:
      "2013 ナインアワーズ(2009 京都創業のデザインカプセル)のなんば駅前店。男女別フロアの SF 系カプセル 124 室。シャワー + ロッカー付。なんば駅徒歩 1 分。1 泊 ¥3500-5500 のリーズナブル。",
    content_md:
      "- 開業:2013\n- 立地:なんば駅徒歩 1 分\n- 客室:124 室・男女別\n- 1 泊:¥3500-5500\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.501,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["capsule", "nine_hours", "namba", "since_2013"],
    source: "manual",
  },
  {
    slug: "first-cabin-umeda",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "ファーストキャビン関西空港(2011・梅田・飛行機ファーストクラス風カプセル)",
    title_ja: "ファーストキャビン梅田",
    romaji: "First Cabin Umeda",
    summary_zh:
      "2011 創業のファーストキャビン(飛行機ファーストクラス風カプセル)の梅田店。150 室・女性専用フロア有。各カプセルに 32 inch TV + 鍵付ロッカー。梅田駅徒歩 7 分。1 泊 ¥4500-7500。",
    content_md:
      "- 開業:2011\n- 立地:梅田駅徒歩 7 分\n- 客室:150 室\n- ファーストクラス風\n- 1 泊:¥4500-7500\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.701,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://first-cabin.jp/" },
    tags: ["capsule", "first_cabin", "umeda", "since_2011"],
    source: "manual",
  },
  {
    slug: "khaosan-world-namba",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "Khaosan World 難波(2012・難波・国際バックパッカーズ向)",
    title_ja: "Khaosan World 難波",
    romaji: "Khaosan World Namba",
    summary_zh:
      "2012 なんば駅徒歩 5 分に開業の国際バックパッカーズ向ホステル。ドミトリー(8 床) + プライベートルーム複合。共同キッチン + ラウンジで国際旅人交流。1 泊 ¥2500-6000。外国人観光客向け。",
    content_md:
      "- 開業:2012\n- 立地:なんば駅徒歩 5 分\n- ドミトリー + プライベート\n- 共同キッチン + ラウンジ\n- 1 泊:¥2500-6000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.666,
    lon: 135.502,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://khaosan-tokyo.com/world-namba/" },
    tags: ["hostel", "khaosan", "namba", "backpacker"],
    source: "manual",
  },
  {
    slug: "drop-inn-osaka",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "DROP INN OSAKA(2010s・難波・カプセル + ホステル混合)",
    title_ja: "DROP INN OSAKA",
    romaji: "DROP INN OSAKA",
    summary_zh:
      "2010s 後期難波エリアに開業のカプセル + ホステル混合型。男女別カプセル + 個室 + ドミトリー混合提供。共同シャワー + 共同ラウンジ + Wi-Fi。なんば駅徒歩 5 分。1 泊 ¥2500-5500。",
    content_md:
      "- 立地:なんば駅徒歩 5 分\n- 形式:カプセル + 個室 + ドミトリー\n- 1 泊:¥2500-5500\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.502,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["hostel", "drop_inn", "namba", "mixed_format"],
    source: "manual",
  },
  {
    slug: "hostel-q-osaka",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "Hostel Q Osaka(2014・心斎橋・若年女性向)",
    title_ja: "Hostel Q Osaka",
    romaji: "Hostel Q Ōsaka",
    summary_zh:
      "2014 心斎橋筋商店街徒歩 5 分に開業の若年女性向ホステル。女性専用フロアが特色で,ドミトリー + 個室混合 80 室。共同キッチン + ラウンジ + フリードリンク。1 泊 ¥3500-6500。",
    content_md:
      "- 開業:2014\n- 立地:心斎橋筋徒歩 5 分\n- 女性専用フロアあり\n- 客室:80 室\n- 1 泊:¥3500-6500\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.674,
    lon: 135.502,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["hostel", "q", "shinsaibashi", "female_friendly"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // G. 関空エリア(3 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "nikko-kansai-airport",
    category: "lodging",
    sub_type: "osaka_kix_airport",
    title_zh: "ホテル日航関西空港(1994・関空島内・JR/南海駅直結・関空ターミナル直結)",
    title_ja: "ホテル日航関西空港",
    romaji: "Hotel Nikko Kansai Airport",
    summary_zh:
      "1994 関空開港同時開業の関空島内唯一のホテル。9F・575 室。JR + 南海関西空港駅 + 第 1 ターミナルから屋根付通路で直結アクセス。早朝 + 深夜便の搭乗客 No.1 選択。1 泊 ¥18000-40000。",
    content_md:
      "- 開業:1994(関空同時)\n- 立地:関空島内・ターミナル直結\n- 客室:575 室・9F\n- 早朝深夜便対応\n- 1 泊:¥18000-40000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "泉佐野市",
    lg_code: "27213",
    area_types: ["coastal", "airport"],
    lat: 34.434,
    lon: 135.244,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.nikkokix.com/" },
    tags: ["airport_hotel", "nikko", "kix", "since_1994", "terminal_direct"],
    source: "manual",
  },
  {
    slug: "hyatt-regency-kix",
    category: "lodging",
    sub_type: "osaka_kix_airport",
    title_zh: "ハイアットリージェンシー関西空港(2003・りんくう連絡橋根元・国際クラス)",
    title_ja: "ハイアットリージェンシー関西空港",
    romaji: "Hyatt Regency Kansai Airport",
    summary_zh:
      "2003 関空連絡橋根元(りんくうタウン側)に開業の国際クラス。10F・230 室。関空島から無料シャトルバス 7 分。1F-9F の渦巻ガラスファサード + 1990s 関西アヴァンギャルド建築。長期滞在 + 国際カンファレンス向け。1 泊 ¥15000-35000。",
    content_md:
      "- 開業:2003\n- 立地:関空連絡橋根元(りんくう側)\n- 客室:230 室・10F\n- 関空シャトル無料 7 分\n- 1 泊:¥15000-35000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "泉佐野市",
    lg_code: "27213",
    area_types: ["urban", "coastal"],
    lat: 34.412,
    lon: 135.302,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.hyatt.com/ja-JP/hotel/japan/hyatt-regency-osaka/osakix" },
    tags: ["airport_hotel", "hyatt_regency", "kix", "rinku", "since_2003"],
    source: "manual",
  },
  {
    slug: "stargate-hotel-kansai-airport",
    category: "lodging",
    sub_type: "osaka_kix_airport",
    title_zh: "スターゲートホテル関西エアポート(1996・りんくう・56F 関空 No.1 高層)",
    title_ja: "スターゲートホテル関西エアポート",
    romaji: "Star Gate Hotel Kansai Airport",
    summary_zh:
      "1996 関空連絡橋根元(りんくうタウン)に開業の 56F・680 室の関空エリア最大かつ最高層ホテル。高層階から関空島 + 大阪湾 + 神戸方面ビュー。1F-2F 関空連絡橋見え + りんくうプレミアムアウトレット徒歩 5 分。1 泊 ¥10000-25000。",
    content_md:
      "- 開業:1996\n- 客室:680 室・56F(関空 No.1 高層)\n- りんくうアウトレット徒歩 5 分\n- 1 泊:¥10000-25000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "泉佐野市",
    lg_code: "27213",
    area_types: ["urban", "coastal"],
    lat: 34.412,
    lon: 135.298,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["airport_hotel", "stargate", "rinku", "since_1996", "tallest_kix"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // H. 千里・北摂(2 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "hotel-hankyu-international",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテル阪急インターナショナル(1992・千里中央・阪急系国際クラス)",
    title_ja: "ホテル阪急インターナショナル",
    romaji: "Hotel Hankyū International",
    summary_zh:
      "1992 北区茶屋町(梅田北・阪急梅田駅徒歩 7 分)に開業の阪急系国際クラスホテル。22F・168 室。1F『マルメゾン』(老舗フランス料理)+ 21F『ピアノ・バー』。阪急梅田 + JR 大阪駅徒歩 7 分。1 泊 ¥25000-60000。",
    content_md:
      "- 開業:1992\n- 立地:北区茶屋町\n- 客室:168 室・22F\n- 阪急梅田徒歩 7 分\n- 1 泊:¥25000-60000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.708,
    lon: 135.499,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["luxury", "hankyu_international", "umeda", "since_1992"],
    source: "manual",
  },
  {
    slug: "remm-hotel-shin-osaka",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "remm 新大阪(2013・新大阪駅直結・阪急系デザインビジネス)",
    title_ja: "remm 新大阪",
    romaji: "remm Shin-Ōsaka",
    summary_zh:
      "2013 新大阪駅(JR 西日本系)に開業の阪急 remm ブランド(デザインビジネス系)。10F・287 室。各室マッサージチェア装備が特色。新幹線直結。1 泊 ¥10000-22000。",
    content_md:
      "- 開業:2013\n- 立地:新大阪駅直結\n- 客室:287 室・10F\n- 各室マッサージチェア\n- 1 泊:¥10000-22000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.733,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["budget", "remm", "shin_osaka", "since_2013", "massage_chair"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // R2 expansion(2026-04-29・43 → ~67)
  // ══════════════════════════════════════════════════════════════════

  // ── R2-A. ラグジュアリー追加(3 筆) ──────────────────
  {
    slug: "intercontinental-osaka",
    category: "lodging",
    sub_type: "international_luxury",
    title_zh: "インターコンチネンタルホテル大阪(2013・関西初・グランフロント北館 19-30F)",
    title_ja: "インターコンチネンタルホテル大阪",
    romaji: "InterContinental Hotel Ōsaka",
    summary_zh:
      "2013 グランフロント大阪北館 19-30F に開業の関西初インターコンチネンタル(IHG 系最高級)。272 室。地上 200 m 超の高層ビュー(JR 大阪駅 + 梅田スカイビル + 大阪城方面一望)。隣接のグランフロント大阪 + JR 大阪駅徒歩 5 分でアクセス最強。",
    content_md:
      "- 開業:2013(関西初インターコンチ)\n- 立地:グランフロント大阪北館 19-30F\n- 客室:272 室\n- JR 大阪駅徒歩 5 分\n- 1 泊:¥40000-120000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.703,
    lon: 135.495,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["luxury", "intercontinental", "grandfront", "since_2013"],
    source: "manual",
  },
  {
    slug: "sheraton-miyako-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "シェラトン都ホテル大阪(1973・上本町・近鉄系・関西最古シェラトン)",
    title_ja: "シェラトン都ホテル大阪",
    romaji: "Sheraton Miyako Hotel Ōsaka",
    summary_zh:
      "1973 近鉄上本町駅併設に開業の都ホテル系(近鉄)+ 1985 シェラトン提携。21F・564 室。近鉄沿線(奈良 + 三重)からのアクセス + 大阪城公園徒歩 15 分。日本国産ホテル + 国際チェーン融合の代表例。1 泊 ¥18000-45000。",
    content_md:
      "- 開業:1973(1985 シェラトン提携)\n- 立地:近鉄上本町駅直結\n- 客室:564 室・21F\n- 1 泊:¥18000-45000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.667,
    lon: 135.521,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["luxury", "sheraton_miyako", "uehonmachi", "since_1973", "kintetsu"],
    source: "manual",
  },
  {
    slug: "art-hotel-osaka-bay-tower",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "アートホテル大阪ベイタワー(1991・港区・21F・大阪湾ビュー)",
    title_ja: "アートホテル大阪ベイタワー",
    romaji: "Art Hotel Ōsaka Bay Tower",
    summary_zh:
      "1991 港区大阪湾沿に開業のアートホテルブランド(ロイヤルパインズ系)。21F・322 室。USJ + 海遊館アクセス + 大阪湾 + 神戸方面ビュー。大阪市営地下鉄中央線『弁天町駅』徒歩 1 分。1 泊 ¥10000-25000。",
    content_md:
      "- 開業:1991\n- 立地:港区大阪湾沿\n- 客室:322 室・21F\n- 弁天町駅徒歩 1 分\n- 1 泊:¥10000-25000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.668,
    lon: 135.460,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["mid_class", "art_hotel", "bay_tower", "since_1991", "bentencho"],
    source: "manual",
  },

  // ── R2-B. 新世代デザイン(4 筆) ──────────────────
  {
    slug: "aloft-osaka-dojima",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "アロフト大阪堂島(2020・Marriott 系若年向ライフスタイル・北区堂島)",
    title_ja: "アロフト大阪堂島",
    romaji: "Aloft Ōsaka Dōjima",
    summary_zh:
      "2020 北区堂島に開業の Marriott 系若年向ライフスタイルブランド アロフト。30F・250 室。屋上プール + バーで SNS 系。大阪駅 + 北新地徒歩 7 分。Moxy 本町と並ぶ Marriott の関西若年戦略の中核。1 泊 ¥15000-35000。",
    content_md:
      "- 開業:2020\n- 立地:北区堂島(大阪駅徒歩 7 分)\n- 客室:250 室・30F\n- 屋上プール + バー\n- 1 泊:¥15000-35000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.696,
    lon: 135.498,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.marriott.co.jp/hotels/travel/osaal-aloft-osaka-dojima/" },
    tags: ["boutique", "aloft", "dojima", "since_2020", "rooftop_pool"],
    source: "manual",
  },
  {
    slug: "voco-osaka-central",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "voco 大阪セントラル(2020・本町・IHG 新世代ライフスタイル)",
    title_ja: "voco 大阪セントラル",
    romaji: "voco Ōsaka Central",
    summary_zh:
      "2020 中央区本町に開業の IHG 系新世代ライフスタイルブランド voco の関西初。20F・200 室。本町駅徒歩 3 分。1 泊 ¥12000-30000。",
    content_md:
      "- 開業:2020\n- 立地:本町駅徒歩 3 分\n- 客室:200 室・20F\n- IHG 系新世代\n- 1 泊:¥12000-30000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.ihg.com/voco/hotels/jp/ja/osaka/osavn/hoteldetail" },
    tags: ["boutique", "voco", "honmachi", "since_2020", "ihg"],
    source: "manual",
  },
  {
    slug: "candeo-hotels-osaka-namba",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "カンデオホテルズ大阪なんば(2017・なんば駅前・最上階スカイスパ)",
    title_ja: "カンデオホテルズ大阪なんば",
    romaji: "Candeo Hotels Ōsaka Namba",
    summary_zh:
      "2017 なんば駅前に開業のカンデオホテルズ(ミドルクラスブランド)。15F・308 室。最上階に天空スカイスパ(露天風呂 + サウナ + 城西ビュー)が特色。なんば駅徒歩 3 分。1 泊 ¥10000-25000。",
    content_md:
      "- 開業:2017\n- 立地:なんば駅徒歩 3 分\n- 客室:308 室・15F\n- 最上階スカイスパ(露天 + サウナ)\n- 1 泊:¥10000-25000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.664,
    lon: 135.502,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.candeohotels.com/ja/osaka-namba/" },
    tags: ["mid_class", "candeo", "namba", "since_2017", "sky_spa"],
    source: "manual",
  },
  {
    slug: "royal-park-canvas-osaka-kitahama",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ザ・ロイヤルパークキャンバス大阪北浜(2020・三井不動産系・北浜)",
    title_ja: "ザ・ロイヤルパークキャンバス大阪北浜",
    romaji: "The Royal Park Canvas Ōsaka Kitahama",
    summary_zh:
      "2020 中央区北浜に開業の三井不動産系若年向ライフスタイルブランド。15F・148 室。北浜駅徒歩 1 分・船場 + 大丸心斎橋徒歩 10 分圏。1F カフェ + 屋上ロビー。1 泊 ¥12000-28000。",
    content_md:
      "- 開業:2020\n- 立地:北浜駅徒歩 1 分\n- 客室:148 室・15F\n- 1 泊:¥12000-28000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.690,
    lon: 135.508,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.royalparkhotels.co.jp/canvas/osakakitahama/" },
    tags: ["boutique", "royal_park_canvas", "kitahama", "since_2020"],
    source: "manual",
  },

  // ── R2-C. 中堅ホテル(4 筆) ──────────────────
  {
    slug: "hotel-nikko-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテル日航大阪(1989・心斎橋・JAL 系・26F・関西 JAL 旗艦)",
    title_ja: "ホテル日航大阪",
    romaji: "Hotel Nikko Ōsaka",
    summary_zh:
      "1989 心斎橋筋商店街隣接(御堂筋沿)に開業の JAL 系。26F・634 室。御堂筋 + 大丸心斎橋本店 + 心斎橋駅徒歩 1 分でアクセス最強。1 泊 ¥20000-50000。",
    content_md:
      "- 開業:1989\n- 立地:心斎橋駅徒歩 1 分(御堂筋沿)\n- 客室:634 室・26F\n- 1 泊:¥20000-50000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.674,
    lon: 135.501,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.hno.co.jp/" },
    tags: ["luxury", "nikko", "shinsaibashi", "since_1989", "jal"],
    source: "manual",
  },
  {
    slug: "mitsui-garden-osaka-honmachi",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "三井ガーデンホテル大阪本町(2017・本町・大型 415 室)",
    title_ja: "三井ガーデンホテル大阪本町",
    romaji: "Mitsui Garden Hotel Ōsaka Honmachi",
    summary_zh:
      "2017 中央区本町に開業の三井ガーデン系。15F・415 室の大型。本町駅徒歩 1 分・船場 + 大丸心斎橋本店 + 大阪城徒歩 15 分圏。最上階大浴場あり。1 泊 ¥12000-28000。",
    content_md:
      "- 開業:2017\n- 立地:本町駅徒歩 1 分\n- 客室:415 室・15F\n- 最上階大浴場\n- 1 泊:¥12000-28000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.683,
    lon: 135.502,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["mid_class", "mitsui_garden", "honmachi", "since_2017"],
    source: "manual",
  },
  {
    slug: "exel-tokyu-shinsaibashi",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "大阪エクセルホテル東急(2008・心斎橋・東急系・新阪急ビル)",
    title_ja: "大阪エクセルホテル東急",
    romaji: "Ōsaka Excel Hotel Tōkyū",
    summary_zh:
      "2008 心斎橋(新阪急ビル併設)に開業の東急ホテルズ系。13F・346 室。心斎橋駅徒歩 5 分・大丸心斎橋本店徒歩 3 分。東急沿線(東京)からのビジネス客 + 関西観光客両用。1 泊 ¥12000-30000。",
    content_md:
      "- 開業:2008\n- 立地:心斎橋(新阪急ビル併設)\n- 客室:346 室・13F\n- 1 泊:¥12000-30000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.674,
    lon: 135.502,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.tokyuhotels.co.jp/osaka-e/" },
    tags: ["mid_class", "tokyu", "shinsaibashi", "since_2008"],
    source: "manual",
  },
  {
    slug: "hotel-royal-classic-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテル ロイヤルクラシック大阪(2019・なんば旧歌舞伎座跡・隈研吾デザイン)",
    title_ja: "ホテル ロイヤルクラシック大阪",
    romaji: "Hotel Royal Classic Ōsaka",
    summary_zh:
      "2019 なんば旧歌舞伎座跡(1932-2009 の大阪歌舞伎座跡地)に開業のロイヤルパインズ系。21F・138 室。隈研吾設計の和モダン。歌舞伎座建物の意匠継承(屋根 + 一部エントランス)。なんば駅徒歩 3 分。1 泊 ¥18000-50000。",
    content_md:
      "- 開業:2019\n- 立地:なんば旧大阪歌舞伎座跡\n- 設計:隈研吾(和モダン + 歌舞伎座意匠継承)\n- 客室:138 室・21F\n- 1 泊:¥18000-50000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.501,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["luxury", "royal_classic", "kabukiza_site", "kuma_kengo", "since_2019"],
    source: "manual",
  },

  // ── R2-D. USJ オフィシャル追加(2 筆) ──────────────────
  {
    slug: "hotel-universal-port-vita",
    category: "lodging",
    sub_type: "osaka_usj_official",
    title_zh: "ホテル ユニバーサル ポート ヴィータ(2018・USJ オフィシャル第 5 弾)",
    title_ja: "ホテル ユニバーサル ポート ヴィータ",
    romaji: "Hotel Universal Port Vita",
    summary_zh:
      "2018 USJ 隣接(ホテル ユニバーサル ポート姉妹館)に開業の USJ オフィシャル第 5 弾。28F・428 室。家族 + ファミリー向で,キャラクタールーム充実。USJ ゲート徒歩 7 分。USJ 早期入園権付。1 泊 ¥15000-45000。",
    content_md:
      "- 開業:2018\n- USJ オフィシャル第 5 弾\n- 客室:428 室・28F\n- USJ ゲート徒歩 7 分\n- 1 泊:¥15000-45000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.667,
    lon: 135.430,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["usj_official", "vita", "since_2018"],
    source: "manual",
  },
  {
    slug: "liber-hotel-usj",
    category: "lodging",
    sub_type: "osaka_usj_official",
    title_zh: "リーベル ホテル at ユニバーサル・スタジオ・ジャパン(2022・USJ オフィシャル第 6 弾)",
    title_ja: "リーベル ホテル at ユニバーサル・スタジオ・ジャパン",
    romaji: "Liber Hotel at USJ",
    summary_zh:
      "2022 USJ 隣接に開業の USJ オフィシャル最新(第 6 弾)。28F・410 室。最新ホテルらしくモダンインテリア + 全室高層ビュー。USJ ゲート徒歩 5 分。USJ 早期入園権付。1 泊 ¥18000-50000。",
    content_md:
      "- 開業:2022(USJ オフィシャル第 6 弾)\n- 客室:410 室・28F\n- USJ ゲート徒歩 5 分\n- 1 泊:¥18000-50000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.668,
    lon: 135.434,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["usj_official", "liber", "since_2022"],
    source: "manual",
  },

  // ── R2-E. 関空エリア追加(1 筆) ──────────────────
  {
    slug: "hotel-hewitt-rinku",
    category: "lodging",
    sub_type: "osaka_kix_airport",
    title_zh: "ホテル ヒューイットりんくう(2002・りんくうタワー・関空アクセス)",
    title_ja: "ホテル ヒューイットりんくう",
    romaji: "Hotel Hewitt Rinkū",
    summary_zh:
      "2002 りんくうタウン(りんくうゲートタワービル併設)に開業の関空アクセスホテル。15F・232 室。関空島から無料シャトル 7 分・りんくうプレミアムアウトレット徒歩 7 分。1 泊 ¥9000-22000。",
    content_md:
      "- 開業:2002\n- 立地:りんくうタウン(りんくうゲートタワー)\n- 客室:232 室・15F\n- 関空シャトル 7 分\n- 1 泊:¥9000-22000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "泉佐野市",
    lg_code: "27213",
    area_types: ["urban", "coastal"],
    lat: 34.412,
    lon: 135.299,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["airport_hotel", "hewitt", "rinku", "since_2002"],
    source: "manual",
  },

  // ── R2-F. ビジネスチェーン追加(5 筆) ──────────────────
  {
    slug: "apa-tenmabashi",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "アパホテル天満橋駅前(京阪沿線・大阪城公園徒歩 7 分)",
    title_ja: "アパホテル天満橋駅前",
    romaji: "APA Hotel Tenmabashi-Eki-Mae",
    summary_zh:
      "京阪天満橋駅前(大阪城公園徒歩 7 分)のアパホテル。13F・230 室。京阪沿線(京都・枚方)からのビジネス + 大阪城観光客両用。1 泊 ¥7000-13000。",
    content_md:
      "- 立地:京阪天満橋駅前(大阪城徒歩 7 分)\n- 客室:230 室・13F\n- 1 泊:¥7000-13000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.694,
    lon: 135.516,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.apahotel.com/" },
    tags: ["budget", "apa", "tenmabashi"],
    source: "manual",
  },
  {
    slug: "daiwa-roynet-yodoyabashi",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "ダイワロイネットホテル大阪淀屋橋(2008・船場・大和ハウス系)",
    title_ja: "ダイワロイネットホテル大阪淀屋橋",
    romaji: "Daiwa Roynet Hotel Ōsaka Yodoyabashi",
    summary_zh:
      "2008 中央区船場(淀屋橋駅前)に開業の大和ハウス系ビジネスチェーン。15F・280 室。1 泊 ¥9000-16000。淀屋橋駅徒歩 1 分。",
    content_md:
      "- 開業:2008\n- 立地:淀屋橋駅徒歩 1 分\n- 客室:280 室・15F\n- 1 泊:¥9000-16000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.692,
    lon: 135.504,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.daiwaroynet.jp/yodoyabashi/" },
    tags: ["budget", "daiwa_roynet", "yodoyabashi", "since_2008"],
    source: "manual",
  },
  {
    slug: "henn-na-hotel-osaka-namba",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "変なホテル大阪 なんば(2019・ロボット受付・H.I.S. 系)",
    title_ja: "変なホテル大阪 なんば",
    romaji: "Henn na Hotel Ōsaka Namba",
    summary_zh:
      "2019 なんば駅徒歩 5 分に開業の H.I.S. 系『世界初のロボットホテル』(ハウステンボス変なホテル系列)。13F・225 室。受付ロボット + 顔認証チェックイン + 自動ドア + 部屋音声制御。1 泊 ¥7000-15000。",
    content_md:
      "- 開業:2019\n- 立地:なんば駅徒歩 5 分\n- 客室:225 室・13F\n- 受付ロボット + 顔認証\n- 1 泊:¥7000-15000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.503,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["budget", "henn_na", "namba", "since_2019", "robot"],
    source: "manual",
  },
  {
    slug: "shin-osaka-station-hotel",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "新大阪ステーションホテル(1976・新大阪駅前老舗・JR 西日本系)",
    title_ja: "新大阪ステーションホテル",
    romaji: "Shin-Ōsaka Station Hotel",
    summary_zh:
      "1976 新大阪駅前に開業の JR 西日本系老舗ビジネスホテル(本館 + 新館)。新幹線アクセス + 駅徒歩 3 分。出張ビジネス No.1 選択肢。1 泊 ¥8000-15000。",
    content_md:
      "- 開業:1976\n- 立地:新大阪駅徒歩 3 分\n- 構成:本館 + 新館\n- 1 泊:¥8000-15000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.733,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["budget", "station_hotel", "shin_osaka", "since_1976"],
    source: "manual",
  },
  {
    slug: "courtyard-marriott-shin-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "コートヤード・バイ・マリオット 新大阪ステーション(2020・新大阪駅徒歩 1 分)",
    title_ja: "コートヤード・バイ・マリオット 新大阪ステーション",
    romaji: "Courtyard by Marriott Shin-Ōsaka Station",
    summary_zh:
      "2020 新大阪駅徒歩 1 分に開業の Marriott コートヤードブランド。15F・360 室。新幹線 + 関空特急直結で東京 + 関空からのビジネス + 観光客に最適。1 泊 ¥12000-30000。",
    content_md:
      "- 開業:2020\n- 立地:新大阪駅徒歩 1 分\n- 客室:360 室・15F\n- 1 泊:¥12000-30000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.733,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.marriott.co.jp/hotels/travel/osaco-courtyard-osaka-station/" },
    tags: ["mid_class", "courtyard_marriott", "shin_osaka", "since_2020"],
    source: "manual",
  },

  // ── R2-G. 北浜・本町追加(2 筆) ──────────────────
  {
    slug: "royal-park-iconic-osaka-midosuji",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ザ・ロイヤルパーク・アイコニック大阪御堂筋(2020・本町・三井不動産系・最上級)",
    title_ja: "ザ・ロイヤルパーク・アイコニック大阪御堂筋",
    romaji: "The Royal Park Iconic Ōsaka Midōsuji",
    summary_zh:
      "2020 本町(御堂筋沿)に開業の三井不動産系最上級ブランド アイコニック。28F・333 室。御堂筋 + 大丸心斎橋本店徒歩 7 分。最上階レストラン + ラウンジ。1 泊 ¥25000-60000。",
    content_md:
      "- 開業:2020\n- 立地:本町(御堂筋沿)\n- 客室:333 室・28F\n- 1 泊:¥25000-60000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.royalparkhotels.co.jp/iconic/osaka/" },
    tags: ["luxury", "royal_park_iconic", "midosuji", "since_2020"],
    source: "manual",
  },
  {
    slug: "holiday-inn-osaka-namba",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "ホリデイ・イン大阪なんば(1995・なんば駅徒歩 5 分・IHG 系老舗)",
    title_ja: "ホリデイ・イン大阪なんば",
    romaji: "Holiday Inn Ōsaka Namba",
    summary_zh:
      "1995 なんば駅徒歩 5 分に開業の IHG 系ホリデイ・イン。15F・314 室。1 泊 ¥10000-20000。",
    content_md:
      "- 開業:1995\n- 立地:なんば駅徒歩 5 分\n- 客室:314 室・15F\n- 1 泊:¥10000-20000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.502,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.ihg.com/holidayinn/hotels/jp/ja/osaka/osaka/hoteldetail" },
    tags: ["mid_class", "holiday_inn", "namba", "since_1995"],
    source: "manual",
  },

  // ── R2-H. 阪急梅田追加(1 筆) ──────────────────
  {
    slug: "hotel-hankyu-respire-osaka",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテル阪急レスパイア大阪(2019・梅田・阪急系新ブランド)",
    title_ja: "ホテル阪急レスパイア大阪",
    romaji: "Hotel Hankyū Respire Ōsaka",
    summary_zh:
      "2019 阪急梅田駅前に開業の阪急ホテルズ新ブランド『レスパイア(REIT 系)』。15F・1030 室の関西最大級客室数。阪急梅田駅徒歩 5 分。1 泊 ¥10000-22000。",
    content_md:
      "- 開業:2019\n- 立地:阪急梅田駅徒歩 5 分\n- 客室:1030 室・15F(関西最大級)\n- 1 泊:¥10000-22000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.706,
    lon: 135.498,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.hankyu-hotel.com/hotel/respire/" },
    tags: ["mid_class", "hankyu_respire", "umeda", "since_2019", "max_rooms"],
    source: "manual",
  },

  // ── R2-I. 新大阪 + その他追加(1 筆) ──────────────────
  {
    slug: "hotel-vischio-shin-osaka",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "ホテル ヴィスキオ新大阪(2018・新大阪駅前・JR 西日本系新ブランド)",
    title_ja: "ホテル ヴィスキオ新大阪",
    romaji: "Hotel Vischio Shin-Ōsaka",
    summary_zh:
      "2018 新大阪駅徒歩 3 分に開業の JR 西日本系新ブランド ヴィスキオ。13F・180 室。1 泊 ¥9000-18000。",
    content_md:
      "- 開業:2018\n- 立地:新大阪駅徒歩 3 分\n- 客室:180 室・13F\n- 1 泊:¥9000-18000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.733,
    lon: 135.500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["budget", "vischio", "shin_osaka", "since_2018"],
    source: "manual",
  },
];

async function main() {
  console.log(`[seed] ${rows.length} rows to seed`);
  const byKind: Record<string, number> = {};
  for (const r of rows) byKind[r.sub_type] = (byKind[r.sub_type] ?? 0) + 1;
  console.log(`[seed] by sub_type: ${JSON.stringify(byKind, null, 2)}`);

  if (DRY) {
    for (const r of rows) {
      console.log(
        `  [${r.sub_type.padEnd(28)}] ${r.title_zh} (${r.municipality_ja ?? "-"}/${r.lg_code ?? "-"})`,
      );
    }
    return;
  }

  const sb = createAdminClient();
  const { data, error } = await sb
    .from("japan_entries")
    .upsert(rows, { onConflict: "slug" })
    .select("id, slug");
  if (error) {
    console.error("[seed] upsert failed", error);
    process.exit(1);
  }
  console.log(`[seed] upserted ${data?.length ?? 0} rows`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
