// Seed 千葉県 R3 補完(20 筆 / Sprint 3.x / 第十二卷)
// 食 5 / 衣 3 / 住 3 / 育 4 / 楽 3 / 行 2 = 20 累積 143 + 20 = 163
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 食 5
  {
    slug: "chiba-sake-2-roho",
    category: "food", sub_type: "chiba_sake",
    title_zh: "千葉地酒 2 大老舗(東薫酒造 1825+寒菊銘醸 1883)+ 香取市佐原・山武市・東薫酒造 1825 文政 8 年創業 200 年+「東薫」「叶」純米吟醸+ 寒菊銘醸 1883 明治 16 年創業 142 年+「寒菊」「OCEAN 99」純米吟醸+ 全国新酒鑑評会金賞常連+ R1 食 飯沼本家 1673 と並ぶ千葉地酒 3 大・720ml ¥2,500-7,500)",
    title_ja: "千葉地酒 2 大老舗", romaji: "Chiba Sake Roho",
    summary_zh: "**千葉地酒 2 大老舗(東薫酒造 1825 200 年+寒菊銘醸 1883 142 年)・全国新酒鑑評会金賞常連**(佐原+山武)。R1 食 飯沼本家 1673 と並ぶ 3 大、¥2,500-7,500/720ml。",
    content_md: "- 立地:**香取市佐原 + 山武市**\n- 起源:**東薫 1825 文政 8 年 200 年 + 寒菊 1883 明治 16 年 142 年**\n- 並列:**飯沼本家 1673 + 東薫 1825 + 寒菊 1883 = 千葉地酒 3 大老舗**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "香取市", lg_code: "12236",
    area_types: ["industrial_heritage"], lat: 35.8983, lon: 140.5028,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["chiba_sake_roho", "tokun_1825", "kankiku_1883"], source: "manual",
  },
  {
    slug: "choshi-sanma",
    category: "food", sub_type: "chiba_seafood",
    title_zh: "銚子サンマ+秋鮭(銚子市・R1 食 銚子港派生・全国サンマ水揚げ量上位+ 黒潮親潮交差点+ 9-11 月旬秋サンマ・銚子寿司店+魚屋直販+ ウオッセ 21 観光市場販売・1 尾 ¥350-1,200・道の駅銚子)",
    title_ja: "銚子サンマ", romaji: "Chōshi Sanma",
    summary_zh: "**銚子サンマ+秋鮭は R1 食 銚子港派生・全国サンマ水揚げ量上位・黒潮親潮交差点**(銚子・**9-11 月旬秋サンマ**)。寿司店+魚屋+ウオッセ 21、¥350-1,200/尾。",
    content_md: "- 立地:**銚子市**\n- 関連:**R1 食 銚子港派生**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "銚子市", lg_code: "12202",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 35.7344, lon: 140.8264,
    season_start: "2026-09-01", season_end: "2026-11-30", event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["choshi_sanma"], source: "manual",
  },
  {
    slug: "chiba-seasonal-meika",
    category: "food", sub_type: "chiba_meika",
    title_zh: "千葉雛菓子+端午菓子(全県・房総中央雛菓子伝統 200+ 年・3 月雛祭り+5 月端午節句菓子+ 米屋本店+亀屋 老舗 8+ 軒+ R1 食 太巻き祭り寿司並ぶ農村祭事菓子・季節限定 ¥800-3,500/箱)",
    title_ja: "千葉季節銘菓", romaji: "Chiba Seasonal Meika",
    summary_zh: "**千葉雛菓子+端午菓子は房総中央伝統 200+ 年・3 月雛祭り+5 月端午節句**(全県・**米屋+亀屋 老舗 8+ 軒**)。R1 食 太巻き祭り寿司並ぶ、季節 ¥800-3,500/箱。",
    content_md: "- 全域:**千葉県全域**\n- 起源:**房総中央雛菓子伝統 200+ 年**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 35.6047, lon: 140.1233,
    season_start: "2026-02-15", season_end: "2026-05-15", event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["chiba_seasonal_meika"], source: "manual",
  },
  {
    slug: "urayasu-asari-tsukudani",
    category: "food", sub_type: "chiba_meika",
    title_zh: "浦安あさり佃煮+ 海産加工品(浦安市+船橋・R1 食 東京湾あさり派生・1900 年代浦安漁師町から伝統佃煮+ あさり+ハマグリ+ アサリしぐれ煮+ あさりつくだに・道の駅+JR 浦安駅売店・¥800-3,500/箱)",
    title_ja: "浦安あさり佃煮", romaji: "Urayasu Asari Tsukudani",
    summary_zh: "**浦安あさり佃煮+海産加工品は R1 食 東京湾あさり派生・1900 年代浦安漁師町から伝統佃煮**(浦安+船橋・**あさり+ハマグリ+しぐれ煮**)。¥800-3,500/箱。",
    content_md: "- 立地:**浦安市 + 船橋市**\n- 関連:**R1 食 東京湾あさり派生**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "浦安市", lg_code: "12227",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 35.6533, lon: 139.9019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["urayasu_asari_tsukudani"], source: "manual",
  },
  {
    slug: "yachimata-peanut-butter",
    category: "food", sub_type: "chiba_meika",
    title_zh: "八街+富里ピーナッツバター(八街市+富里+成田・R1 食 八街落花生派生・1990 年代以降開発・千葉県オリジナル「Q ナッツ」品種ピーナッツバター・道の駅+JR 駅売店+成田空港+全国百貨店流通・1 瓶 ¥800-2,500・国際旅行者代表土産)",
    title_ja: "八街ピーナッツバター", romaji: "Yachimata Peanut Butter",
    summary_zh: "**八街+富里ピーナッツバターは R1 食 八街落花生派生・1990 年代以降開発・千葉オリジナル「Q ナッツ」品種**(八街+富里+成田)。¥800-2,500/瓶、国際代表土産。",
    content_md: "- 立地:**八街市 + 富里市 + 成田市**\n- 関連:**R1 食 八街落花生派生 + 「Q ナッツ」県オリジナル品種**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "八街市", lg_code: "12230",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 35.6614, lon: 140.3194,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yachimata_peanut_butter"], source: "manual",
  },

  // 衣 3
  {
    slug: "boso-kaigara-accessory",
    category: "fashion", sub_type: "chiba_resort",
    title_zh: "房総貝殻+海岸ハンドメイドアクセサリー(館山市+南房総+鴨川+銚子・房総海岸 50+ 種貝殻・1980 年代以降ハンドメイド工房+ シェルピアス+ ネックレス+ ブレスレット・道の駅+海岸土産店+ R1 楽 沖ノ島+九十九里浜連動・¥800-4,500)",
    title_ja: "房総貝殻アクセ", romaji: "Bōsō Shell Accessory",
    summary_zh: "**房総貝殻+海岸ハンドメイドアクセサリーは房総海岸 50+ 種貝殻・1980 年代以降工房・シェルピアス+ネックレス+ブレスレット**(館山+南房総+鴨川+銚子)。R1 楽 沖ノ島連動、¥800-4,500。",
    content_md: "- 立地:**館山市 + 南房総市 + 鴨川市 + 銚子市**\n- 起源:**1980 年代以降ハンドメイド工房**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "館山市", lg_code: "12205",
    area_types: ["shopping_district"], lat: 34.9961, lon: 139.8694,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["boso_shell_accessory"], source: "manual",
  },
  {
    slug: "disney-kids-aparel",
    category: "fashion", sub_type: "chiba_disney",
    title_zh: "東京ディズニーキッズアパレル+ぬいぐるみ(浦安市舞浜・R1 衣 disney マーチャンダイズ派生・赤ちゃん+幼児+小学生向専用ライン+ ベビー服+幼児帽子+キャラクターぬいぐるみ・¥1,800-12,000・国内ファミリー観光客代表・国際 SNS 海外旅行者ファミリー代表)",
    title_ja: "ディズニーキッズアパレル", romaji: "Disney Kids Aparel",
    summary_zh: "**東京ディズニーキッズアパレル+ぬいぐるみは R1 衣 マーチャンダイズ派生・赤ちゃん+幼児+小学生向ベビー服+帽子+ぬいぐるみ**(浦安舞浜)。¥1,800-12,000、国内ファミリー代表。",
    content_md: "- 立地:**浦安市舞浜**\n- 関連:**R1 衣 disney マーチャンダイズ派生**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "浦安市", lg_code: "12227",
    area_types: ["shopping_district"], lat: 35.6329, lon: 139.8804,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["disney_kids"], source: "manual",
  },
  {
    slug: "lotte-marines-aparel",
    category: "fashion", sub_type: "chiba_chiibakun",
    title_zh: "千葉ロッテマリーンズ公式アパレル(千葉市美浜区・1992 ロッテオリオンズから千葉移転 33+ 年+ ZOZO マリン本拠地 R1 楽 派生+ チームユニフォーム+ T シャツ+ 帽子+ メガホン・¥1,500-9,500+ 国内野球ファン代表+ 海外 MLB 系列ファン代表)",
    title_ja: "ロッテマリーンズ", romaji: "Lotte Marines",
    summary_zh: "**千葉ロッテマリーンズ公式アパレルは 1992 千葉移転 33+ 年・ZOZO マリン本拠地 R1 楽派生・ユニフォーム+T+帽子**(千葉美浜)。¥1,500-9,500、国内野球ファン代表。",
    content_md: "- 立地:**千葉市美浜区**\n- 起源:**1992 ロッテオリオンズから千葉移転 33+ 年**\n- 関連:**R1 楽 ZOZO マリン派生**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["shopping_district"], lat: 35.6453, lon: 140.0297,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["lotte_marines", "1992"], source: "manual",
  },

  // 住 3
  {
    slug: "urayasu-mid-hotels-ikspiari",
    category: "lodging", sub_type: "chiba_disney_hotel",
    title_zh: "浦安舞浜中堅ホテル+ イクスピアリ周辺(浦安市舞浜・1983 ディズニーリゾート開園 42+ 年・公式オフィシャルホテル 6+ 軒(ヒルトン+シェラトン+オークラ+サンルート他)+ R1 楽 イクスピアリショッピング徒歩 5 分+ R1 行 JR 舞浜駅徒歩 10 分・¥18,000-45,000/泊)",
    title_ja: "舞浜中堅ホテル", romaji: "Maihama Mid-Hotels",
    summary_zh: "**浦安舞浜中堅ホテル+イクスピアリ周辺は 1983 ディズニーリゾート 42+ 年・公式オフィシャル 6+ 軒(シェラトン+オークラ+サンルート他)**(浦安舞浜)。¥18,000-45,000/泊。",
    content_md: "- 立地:**浦安市舞浜**\n- 規模:**公式オフィシャルホテル 6+ 軒(ヒルトン + シェラトン + オークラ + サンルート他)**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "浦安市", lg_code: "12227",
    area_types: ["accommodation_hotel"], lat: 35.6342, lon: 139.8819,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["maihama_mid_hotels"], source: "manual",
  },
  {
    slug: "inubo-saki-ryokan",
    category: "lodging", sub_type: "chiba_choshi_inubo",
    title_zh: "犬吠埼+ 銚子海岸沿旅館群(銚子市・R1 育 犬吠埼灯台 1874+ 地球の丸く見える丘隣接・太平洋直面オーシャンビュー・1 月初日の出スポット 2 万人参拝・老舗+ 中堅旅館 8+ 軒+ R1 食 銚子港+つりきんめ連動・¥12,000-32,000/泊)",
    title_ja: "犬吠埼旅館", romaji: "Inubō Ryokan",
    summary_zh: "**犬吠埼+銚子海岸沿旅館群は R1 育 犬吠埼灯台 1874・地球の丸く見える丘隣接・1 月初日の出 2 万人**(銚子・**老舗+中堅旅館 8+ 軒**)。R1 食 銚子港+つりきんめ連動、¥12,000-32,000/泊。",
    content_md: "- 立地:**銚子市犬吠埼**\n- 規模:**旅館 8+ 軒 + 太平洋直面**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "銚子市", lg_code: "12202",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 35.7081, lon: 140.8678,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["inubo_ryokan"], source: "manual",
  },
  {
    slug: "kamogawa-coast-ryokan",
    category: "lodging", sub_type: "chiba_kamogawa_onsen",
    title_zh: "鴨川太海+和田浦沿岸旅館群(鴨川市太海+和田浦・R1 食 鴨川くじら+ なめろう派生・太平洋直面オーシャンビュー旅館 12+ 軒+ R1 楽 鴨川シーワールド+ R1 育 誕生寺観光連動・¥12,000-28,000/泊)",
    title_ja: "鴨川沿岸旅館", romaji: "Kamogawa Coast Ryokan",
    summary_zh: "**鴨川太海+和田浦沿岸旅館群は R1 食 鴨川くじら+なめろう派生・太平洋直面 12+ 軒**(鴨川太海+和田浦)。R1 楽 シーワールド+R1 育 誕生寺連動、¥12,000-28,000/泊。",
    content_md: "- 立地:**鴨川市太海 + 和田浦**\n- 規模:**太平洋直面旅館 12+ 軒**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "鴨川市", lg_code: "12223",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 35.0875, lon: 140.0908,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kamogawa_coast"], source: "manual",
  },

  // 育 4
  {
    slug: "chiba-jinja-tsukihoshi",
    category: "culture", sub_type: "chiba_boso_shrine",
    title_zh: "千葉神社(千葉市中央区・1180 治承 4 年 千葉常胤建立 845+ 年+ 千葉氏祖神祀る・千葉氏家紋月星紋発祥+ 妙見信仰本社+ 国登録有形文化財 千葉神社尊星殿(2002)+ R1 育 香取神宮+安房神社並ぶ千葉古社・参拝無料)",
    title_ja: "千葉神社", romaji: "Chiba Jinja",
    summary_zh: "**千葉神社は 1180 千葉常胤建立 845+ 年・千葉氏祖神祀る・月星紋発祥・妙見信仰本社・尊星殿国登録 2002**(千葉中央)。R1 育 三国一宮並ぶ古社、参拝無料。",
    content_md: "- 立地:**千葉市中央区**\n- 起源:**1180 治承 4 年 千葉常胤建立 845+ 年**\n- 認定:**千葉氏祖神祀る + 月星紋発祥 + 千葉神社尊星殿 国登録有形文化財 2002**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["history_site_castle"], lat: 35.6131, lon: 140.1233,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["chiba_jinja", "1180", "tsukihoshi_origin"], source: "manual",
  },
  {
    slug: "kazusa-kokubunji-1929",
    category: "culture", sub_type: "chiba_boso_shrine",
    title_zh: "上総国分寺跡(市原市・741 聖武天皇命建立 1284+ 年+ 国指定史跡 1929+ 七重塔復元基壇+ 国分寺跡公園+ 上総国府所在地 R1 行 小湊鉄道五井駅徒歩 30 分・無料散策)",
    title_ja: "上総国分寺跡", romaji: "Kazusa Kokubunji",
    summary_zh: "**上総国分寺跡は 741 聖武天皇命建立 1284+ 年・国指定史跡 1929・七重塔復元基壇+国分寺跡公園・上総国府所在地**(市原)。R1 行 小湊鉄道徒歩 30 分、無料。",
    content_md: "- 立地:**市原市**\n- 起源:**741 聖武天皇命建立 1284+ 年**\n- 認定:**国指定史跡 1929 + 上総国府所在地**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "市原市", lg_code: "12219",
    area_types: ["history_site_castle"], lat: 35.4981, lon: 140.1158,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kazusa_kokubunji", "741", "1929_designation"], source: "manual",
  },
  {
    slug: "kasori-kaizuka-2017",
    category: "culture", sub_type: "chiba_boso_shrine",
    title_zh: "加曽利貝塚(千葉市若葉区・縄文時代中期-後期 約 5000-3000 年前+ 国指定特別史跡 2017+ 全国 165 史跡中の特別史跡 8 件のうち 全国唯一の貝塚特別史跡+ 13.4ha 縄文最大級貝塚遺跡+ 加曽利貝塚博物館 1966 開館・観覧 ¥800)",
    title_ja: "加曽利貝塚", romaji: "Kasori Kaizuka",
    summary_zh: "**加曽利貝塚は縄文中期-後期 5000-3000 年前・国指定特別史跡 2017・全国唯一の貝塚特別史跡・13.4ha 縄文最大級・博物館 1966**(千葉若葉)。観覧 ¥800。",
    content_md: "- 立地:**千葉市若葉区**\n- 起源:**縄文時代中期-後期 約 5000-3000 年前**\n- 認定:**国指定特別史跡 2017 + 全国唯一の貝塚特別史跡 + 13.4ha 縄文最大級**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["history_site_castle", "museum_art"], lat: 35.6394, lon: 140.1819,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["kasori_kaizuka", "2017_special_designation", "national_only_kaizuka"], source: "manual",
  },
  {
    slug: "chuo-museum-otone-bunkan",
    category: "culture", sub_type: "chiba_museum",
    title_zh: "千葉県立中央博物館大利根分館(香取市佐原・1991 開館 34+ 年+ R1 育 千葉県立中央博物館 R1 育 派生・利根川流域+水郷+漁業文化展示+ R1 育 佐原伝建+伊能忠敬隣接観光連動・観覧 ¥300)",
    title_ja: "中央博物館大利根分館", romaji: "Otone Bunkan",
    summary_zh: "**千葉県立中央博物館大利根分館は 1991 開館 34+ 年・利根川流域+水郷+漁業文化展示**(佐原・**R1 育 中央博物館派生**)。R1 育 佐原伝建+伊能忠敬連動、¥300。",
    content_md: "- 立地:**香取市佐原**\n- 起源:**1991 開館 34+ 年**\n- 関連:**R1 育 千葉県立中央博物館派生**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "香取市", lg_code: "12236",
    area_types: ["museum_art"], lat: 35.8983, lon: 140.5028,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["otone_bunkan", "1991"], source: "manual",
  },

  // 楽 3
  {
    slug: "makuhari-kaihin-park",
    category: "entertainment", sub_type: "chiba_park",
    title_zh: "千葉県立幕張海浜公園(千葉市美浜区・1989 県立公園指定 36+ 年+ 76ha 大規模海浜公園+ 海浜大芝生+ 日本庭園 見浜園 1990 開園+ R1 楽 ZOZO マリン+幕張メッセ+三井 OL 幕張一括観光・無料散策)",
    title_ja: "幕張海浜公園", romaji: "Makuhari Kaihin Park",
    summary_zh: "**千葉県立幕張海浜公園は 1989 県立指定 36+ 年・76ha 大規模海浜公園・日本庭園見浜園 1990**(千葉美浜)。R1 楽 ZOZO+幕張+三井 OL 連動、無料。",
    content_md: "- 立地:**千葉市美浜区**\n- 起源:**1989 県立公園指定 36+ 年**\n- 規模:**76ha + 日本庭園見浜園 1990**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["nature_park"], lat: 35.6481, lon: 140.0356,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["makuhari_kaihin"], source: "manual",
  },
  {
    slug: "chiba-port-park",
    category: "entertainment", sub_type: "chiba_park",
    title_zh: "千葉ポートパーク+千葉中央港(千葉市中央区・1986 開園 39+ 年+ 28ha 海浜公園+ 千葉ポートタワー(R1 楽)隣接+ 人工ビーチ+ JR 千葉港駅徒歩 5 分・無料散策・夕日名所候補)",
    title_ja: "千葉ポートパーク", romaji: "Chiba Port Park",
    summary_zh: "**千葉ポートパーク+千葉中央港は 1986 開園 39+ 年・28ha 海浜公園・千葉ポートタワー(R1 楽)隣接・人工ビーチ**(千葉中央)。JR 千葉港駅徒歩 5 分、無料。",
    content_md: "- 立地:**千葉市中央区**\n- 起源:**1986 開園 39+ 年**\n- 規模:**28ha 海浜公園**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["nature_park", "beach_coast"], lat: 35.5994, lon: 140.1064,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["chiba_port_park"], source: "manual",
  },
  {
    slug: "urayasu-sakaigawa-park",
    category: "entertainment", sub_type: "chiba_park",
    title_zh: "浦安境川親水公園+ 浦安魚市場跡(浦安市・浦安漁師町歴史 江戸期から+ 1971 浦安漁業権放棄(東京 disney 派生)+ 境川沿親水公園+ 浦安市郷土博物館 1995 開館・観覧 ¥0-300)",
    title_ja: "浦安境川親水公園", romaji: "Urayasu Sakaigawa",
    summary_zh: "**浦安境川親水公園+浦安魚市場跡は浦安漁師町歴史 江戸期から・1971 漁業権放棄(disney 派生)・境川沿親水公園・郷土博物館 1995**(浦安)。¥0-300。",
    content_md: "- 立地:**浦安市**\n- 認定:**1971 浦安漁業権放棄(東京 disney 派生) + 浦安市郷土博物館 1995 開館**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "浦安市", lg_code: "12227",
    area_types: ["nature_park", "museum_art"], lat: 35.6533, lon: 139.9019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["urayasu_sakaigawa", "1971_gyogyō_houki"], source: "manual",
  },

  // 行 2
  {
    slug: "jr-kururi-line-1936",
    category: "transport", sub_type: "chiba_jr_boso",
    title_zh: "JR 久留里線(木更津市+君津・1936 全通 89+ 年+ 木更津駅-上総亀山駅 32.2km・千葉県内唯一の非電化 JR 線+ 全国 JR 路線収益最下位常連+ R1 育 久留里城+ R1 楽 亀山湖連動・¥860/片道)",
    title_ja: "JR 久留里線", romaji: "JR Kururi",
    summary_zh: "**JR 久留里線は 1936 全通 89+ 年・木更津-上総亀山 32.2km・千葉県内唯一の非電化 JR 線・全国 JR 収益最下位常連**(木更津+君津)。R1 育 久留里城+R1 楽 亀山湖連動、¥860/片道。",
    content_md: "- 立地:**木更津市 + 君津市**\n- 起源:**1936 全通 89+ 年**\n- 認定:**千葉県内唯一の非電化 JR 線 + 全国 JR 路線収益最下位常連**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "木更津市", lg_code: "12206",
    area_types: ["transport_hub", "nature_park"], lat: 35.3781, lon: 139.9156,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_kururi", "1936"], source: "manual",
  },
  {
    slug: "jr-narita-station-1897",
    category: "transport", sub_type: "chiba_terminal",
    title_zh: "JR 成田駅(成田市・1897 明治 30 年開業 128+ 年+ JR 成田線(我孫子-成田-銚子)+ JR 成田線分岐(成田-成田空港+成田-成田湯川経由空港 第 2 ターミナル)+ 京成成田駅徒歩 5 分+ 1 日 5 万人乗降+ R1 育 成田山新勝寺参道徒歩 10 分・¥0)",
    title_ja: "JR 成田駅", romaji: "JR Narita Station",
    summary_zh: "**JR 成田駅は 1897 明治 30 年開業 128+ 年・JR 成田線+成田線分岐(成田-成田空港)・京成成田駅徒歩 5 分・1 日 5 万人乗降**(成田)。R1 育 新勝寺徒歩 10 分。",
    content_md: "- 立地:**成田市**\n- 起源:**1897 明治 30 年開業 128+ 年**\n- 規模:**3 路線 + 1 日 5 万人乗降**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "成田市", lg_code: "12211",
    area_types: ["transport_hub"], lat: 35.7775, lon: 140.3175,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_narita_station", "1897"], source: "manual",
  },
];

seedMain(rows, "chiba-r3");
