// Seed 広島県 · 樂類 條目 → public.japan_entries(Sprint 31.5 楽 R1)
//
// 25 筆構成:
//   Phase A しまなみ海道 4(概論+ サイクリング+ 生口島+ 大三島大山祇神社)
//   Phase B 宮島楽 4(水中花火 8 月+ 紅葉谷+ 夜歩き+ 鹿)
//   Phase C 渓谷+ スキー 3(三段峡渓流舟下り+ 帝釈峡カヌー+ 芸北みずほスキー)
//   Phase D 水族+ 動物+ マツダ 3(宮島水族館 1959+ 安佐動物 1971+ マツダミュージアム)
//   Phase E 祭礼+ フラワー 4(広島フラワー GW+ とうかさん 6 月+ 三原やっさ 8 月+ 福山ばら 5 月)
//   Phase F 観戦+ 夜景 3(マツダスタジアム 2009+ うり姫山+ 三次花田植 5 月)
//   Phase G 温泉+ 海水浴 4(湯来温泉+ 宮浜温泉+ 江ノ浦海水浴+ 瀬戸田サンセット)

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: "entertainment";
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "chugoku";
  prefecture_ja: "広島県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // Phase A — しまなみ海道(4)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shimanami-kaido-overview",
    category: "entertainment",
    sub_type: "hiroshima_shimanami",
    title_zh: "しまなみ海道(尾道-今治 全長 60km・1999 開通・世界で唯一の自転車対応高速道・6 つの島+ 7 つの橋)",
    title_ja: "しまなみ海道",
    romaji: "Shimanami Kaido",
    summary_zh: "**しまなみ海道は世界唯一の自転車対応高速道**(尾道市-今治市・1999 全通・60 km)。**6 島(向島+ 因島+ 生口島+ 大三島+ 伯方島+ 大島)+ 7 橋** を結ぶ瀬戸内海横断、サイクリングの世界的聖地。レンタル自転車で 1 日完走+ 多島海絶景+ レモン+ 海産物食事 等 観光ハイライト。",
    content_md: "- 全通:1999 年(平成 11)・西瀬戸自動車道\n- 起点:尾道市-終点:愛媛県今治市\n- 全長:60 km(自転車道)+ 73 km(自動車道)\n- 6 島:向島+ 因島+ 生口島+ 大三島+ 伯方島+ 大島\n- 7 橋:新尾道大橋+ 因島大橋+ 生口橋+ 多々羅大橋+ 大三島橋+ 伯方・大島大橋+ 来島海峡大橋\n- 自転車道:世界唯一の高速道路+ 自転車道並列\n- アクセス:JR 尾道駅 起点(尾道港 + 千光寺公園経由)",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["scenic_spot", "road_route"],
    lat: 34.4089,
    lon: 133.1956,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_shimanami", "shimanami_kaido", "60km", "1999_opening", "6_islands_7_bridges"],
    source: "manual",
  },
  {
    slug: "shimanami-cycling-1day",
    category: "entertainment",
    sub_type: "hiroshima_shimanami",
    title_zh: "しまなみ海道 1 日サイクリング(レンタサイクル ¥1500-3000・5-8 時間・尾道-今治完走)",
    title_ja: "しまなみ海道 1 日サイクリング",
    romaji: "Shimanami 1 Day Cycling",
    summary_zh: "**しまなみ海道 1 日サイクリングは観光体験のメイン**(60 km・5-8 時間)。**尾道港+ 主要島で乗捨可能なレンタサイクル ¥1500-3000**、尾道発+ 今治着が定番ルート。中級者向け、初心者は部分コース(因島大橋まで等)+ レンタル電動アシストも選択可。",
    content_md: "- 全長:60 km(完走)\n- 所要:5-8 時間(平均速度 10-12 km/h)\n- レンタル:¥1500-3000(乗捨対応・尾道+ 今治+ 主要島ターミナル)\n- レンタル業者:しまなみレンタサイクル+ ジャイアント尾道店+ ONOMICHI U2\n- 装備:ヘルメット+ パンク補修キット+ 地図\n- 部分コース:因島大橋まで(20 km・往復)+ 生口島まで(35 km)+ 全完走\n- ベスト時期:春(3-5 月)+ 秋(10-11 月)\n- 注意:夏は暑+ 水分補給・冬は風強い\n- アクセス:JR 尾道駅 から 港まで 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["activity_water", "scenic_spot"],
    lat: 34.4089,
    lon: 133.1956,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_shimanami", "1day_cycling", "5_8_hours", "1500_3000_yen", "lean_drop"],
    source: "manual",
  },
  {
    slug: "ikuchi-island-attractions",
    category: "entertainment",
    sub_type: "hiroshima_shimanami",
    title_zh: "生口島(尾道市瀬戸田町・しまなみ中継地・平山郁夫美術館 1997+ 耕三寺+ 瀬戸田レモン)",
    title_ja: "生口島",
    romaji: "Ikuchi Island",
    summary_zh: "**生口島はしまなみ海道の中核観光地**(尾道市瀬戸田町)。**平山郁夫美術館 1997**(画家 平山郁夫生誕地)+ **耕三寺**(西の日光・国登録)+ R1 食既出 setoda-lemon(全国 1 位)+ サンセットビーチ。サイクリングルート上の必訪、半日-1 日滞在可能。",
    content_md: "- 立地:尾道市瀬戸田町(しまなみ海道中継)\n- 主要観光:平山郁夫美術館 1997+ 耕三寺(西の日光)+ サンセットビーチ\n- R1 食既出:setoda-lemon-overview(全国 1 位)\n- 入場:平山郁夫美術館 ¥920+ 耕三寺 ¥1400\n- 営業:9:00-17:00(年中無休)\n- アクセス:しまなみ海道 サイクリング + 路線バス + 尾道港 から 高速船",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["scenic_spot", "museum_art"],
    lat: 34.3050,
    lon: 133.0833,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_shimanami", "ikuchi_island", "hirayama_museum_1997", "kosanji", "lemon_island"],
    source: "manual",
  },
  {
    slug: "omishima-mishimataisha",
    category: "entertainment",
    sub_type: "hiroshima_shimanami",
    title_zh: "大山祇神社(愛媛県・大三島・伊予国一宮・1500 年・武具 8 割収蔵+ 国宝 鎧・刀剣多数)",
    title_ja: "大山祇神社",
    romaji: "Oyamazumi Jinja",
    summary_zh: "**大山祇神社は伊予国一宮+ 全国武具 8 割収蔵**(愛媛県今治市大三島町・1500 年)。しまなみ海道大三島に位置、源義経+ 源頼朝+ 戦国大名の **武具奉納が全国 8 割以上を占める**、国宝鎧 8 領+ 国宝刀剣 多数。広島県外だがしまなみ海道観光の主要 spot。",
    content_md: "- 創建:伝 神武天皇東征時(1500 年伝)\n- 立地:愛媛県今治市大三島町(しまなみ海道大三島)\n- 社格:伊予国一宮+ 元国幣大社\n- 武具収蔵:全国の 8 割(国宝鎧 8 領+ 国宝刀剣多数)\n- 紫陽花群:6 月\n- 入場:無料(参拝)+ 紫陽花苑 ¥300\n- 営業:24 時間(社務所 8:30-17:00)\n- アクセス:しまなみ海道 大三島 IC 徒歩 25 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["scenic_spot", "shrine_temple"],
    lat: 34.2519,
    lon: 132.9831,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_shimanami", "oyamazumi_jinja", "iyo_ichinomiya", "national_80_armor", "1500_years"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase B — 宮島楽(4)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "miyajima-mizu-hanabi-aug",
    category: "entertainment",
    sub_type: "hiroshima_miyajima_play",
    title_zh: "宮島水中花火大会(8 月初・厳島神社海上花火 5000 発・年 1 回最大花火大会・廃止 2020 後 復活運動)",
    title_ja: "宮島水中花火大会",
    romaji: "Miyajima Mizu Hanabi",
    summary_zh: "**宮島水中花火大会は厳島神社海上花火**(廿日市市宮島町・8 月初)。**厳島神社大鳥居+ 海面花火の組合わせで世界的に有名**、毎年 30 万人来場の広島最大花火。COVID-19+ 安全問題で 2020 廃止、2024 復活運動進行中。海面打上+ 大鳥居眺望が観光ハイライト。",
    content_md: "- 開催:8 月第 1 週末(2026 年 8 月 1 日予定)\n- 規模:海上花火 5000 発+ 60 分\n- 来場:30 万人(全国級)\n- 立地:廿日市市宮島町(厳島神社海上)\n- 観覧:宮島島内+ 対岸宮島口+ 観覧船\n- 注意:COVID-19+ 安全問題で 2020 廃止・復活運動進行中(2024 復活予定)\n- 入場:無料(対岸)・観覧船 ¥3500-8000\n- アクセス:宮島フェリー 宮島桟橋 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "廿日市市",
    lg_code: "34213",
    area_types: ["festival_event"],
    lat: 34.2956,
    lon: 132.3197,
    season_start: null,
    season_end: null,
    event_start: "2026-08-01",
    event_end: "2026-08-01",
    price_tier: 1,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_miyajima_play", "mizu_hanabi", "5000_shells", "300k_visitors", "world_famous"],
    source: "manual",
  },
  {
    slug: "miyajima-koyo-dani",
    category: "entertainment",
    sub_type: "hiroshima_miyajima_play",
    title_zh: "宮島紅葉谷公園(廿日市市宮島・紅葉時期 11 月・厳島神社徒歩 10 分・千本もみじ・絶景)",
    title_ja: "宮島紅葉谷公園",
    romaji: "Miyajima Momiji Dani",
    summary_zh: "**宮島紅葉谷公園は宮島の紅葉名所**(廿日市市宮島町・11 月中旬-12 月初)。**1000+ 本のもみじ**+ 厳島神社+ 弥山(R1 育)+ ロープウェイ起点の好立地、岩惣(R1 住)隣接の散策コース。紅葉時期は人出多いが宮島観光のハイライトの 1。",
    content_md: "- 立地:廿日市市宮島町(厳島神社徒歩 10 分)\n- 紅葉時期:11 月中旬-12 月初\n- 主要樹種:もみじ 1000+ 本(特にカエデ)\n- 周辺:岩惣(R1 住)+ 弥山ロープウェイ起点+ 紅葉茶屋\n- 入場:無料(常時)\n- 営業:24 時間\n- アクセス:宮島フェリー 宮島桟橋 徒歩 12 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "廿日市市",
    lg_code: "34213",
    area_types: ["scenic_spot", "park_garden"],
    lat: 34.2961,
    lon: 132.3197,
    season_start: "2026-11-15",
    season_end: "2026-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_miyajima_play", "momiji_dani", "1000_momiji", "november", "iwaso_adjacent"],
    source: "manual",
  },
  {
    slug: "miyajima-overnight-walk",
    category: "entertainment",
    sub_type: "hiroshima_miyajima_play",
    title_zh: "宮島夜散策(日帰り客退散後の島内・厳島神社夜間ライト+ 灯篭+ 鹿夜遊び・宮島宿泊客の特権)",
    title_ja: "宮島夜散策",
    romaji: "Miyajima Yoru Sansaku",
    summary_zh: "**宮島夜散策は宮島宿泊客の特権**(廿日市市宮島町)。**日帰り客は最終フェリー 22:14 で退散** → 残った宿泊客のみが体験できる **静寂の島内+ 厳島神社夜間ライトアップ+ 灯篭+ 自由に歩く野生鹿** の独特な夜景。R1 住既出の岩惣+ 錦水館等宿泊客向け。",
    content_md: "- 立地:廿日市市宮島町(全島)\n- ベスト時間:21:00-23:00\n- 厳島神社ライトアップ:18:00-23:00\n- 大鳥居ライト:日没-23:00\n- 鹿:野生 600+ 頭・夜は自由活動\n- 入場:無料(常時)\n- アクセス:宮島内宿泊客限定・最終フェリー 22:14 後の散策",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "廿日市市",
    lg_code: "34213",
    area_types: ["scenic_spot"],
    lat: 34.2956,
    lon: 132.3197,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_miyajima_play", "miyajima_yoru", "overnight_only", "shrine_lightup", "wild_deer_600"],
    source: "manual",
  },
  {
    slug: "miyajima-sika-deer",
    category: "entertainment",
    sub_type: "hiroshima_miyajima_play",
    title_zh: "宮島野生鹿(廿日市市宮島・600+ 頭・神聖島の使い・自由放浪・観光客と共生)",
    title_ja: "宮島野生鹿",
    romaji: "Miyajima Sika",
    summary_zh: "**宮島野生鹿は厳島神社神使**(廿日市市宮島町・600+ 頭)。R1 既出 奈良鹿(春日大社神使)とは別系統、宮島では **「神聖島の使い」として古来から自由放浪**。観光客と共生、餌やり禁止(島内徹底)、SNS 映え・観光ハイライト。R1 育既出 itsukushima と一体。",
    content_md: "- 立地:廿日市市宮島町(全島)\n- 数:600+ 頭(2024 年現在)\n- 由来:厳島神社神使(神聖島伝統)\n- 比較:奈良鹿(春日大社使)+ 宮島鹿(厳島使)\n- 餌やり:禁止(2008 年から島内徹底)\n- 観光価値:神社+ 鹿の組合わせで SNS 映え\n- 入場:無料(常時)\n- アクセス:宮島フェリー 宮島桟橋 上陸即\n- 注意:噛む+ 突進する個体あり・近づきすぎない",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "廿日市市",
    lg_code: "34213",
    area_types: ["scenic_spot"],
    lat: 34.2961,
    lon: 132.3194,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_miyajima_play", "miyajima_sika", "600_head", "shrine_messenger", "no_feeding"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase C — 渓谷+ スキー(3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "sandankyo-rafting",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "三段峡渓流舟下り(安芸太田町・国指定特別名勝・新緑+ 紅葉・黒淵+ 猿飛区間 渓流舟)",
    title_ja: "三段峡渓流舟下り",
    romaji: "Sandankyo Rafting",
    summary_zh: "**三段峡渓流舟下りは国指定特別名勝の渓谷体験**(R1 育既出 sandankyo-1925 の楽 angle)。**黒淵+ 猿飛 区間** の渓流を木舟で下る、5-11 月限定。新緑(5 月)+ 紅葉(11 月)が絶景、舟下り ¥1300・所要 30 分。三段峡観光のハイライト。",
    content_md: "- 立地:山県郡安芸太田町(R1 育 sandankyo)\n- 期間:5-11 月\n- 区間:黒淵+ 猿飛(渓流舟下り 最人気区間)\n- 所要:30 分\n- 料金:¥1300(大人)\n- ベスト時期:新緑 5 月+ 紅葉 11 月\n- アクセス:JR 横川駅 から バス 1 時間 30 分・三段峡口下車",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: "山県郡",
    municipality_ja: "安芸太田町",
    lg_code: "34368",
    area_types: ["activity_water", "scenic_spot"],
    lat: 34.5547,
    lon: 132.1819,
    season_start: "2026-05-01",
    season_end: "2026-11-30",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["momiji", "sandankyo_rafting", "national_special_scenic", "30min", "kurobuchi_sarutobi"],
    source: "manual",
  },
  {
    slug: "taishakukyo-canoe",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "帝釈峡神龍湖カヌー(庄原市+ 神石高原町・国指定名勝・全長 8km 湖+ カヌー体験 ¥4500・季節)",
    title_ja: "帝釈峡神龍湖カヌー",
    romaji: "Taishakukyo Canoe",
    summary_zh: "**帝釈峡神龍湖カヌーは渓谷体験**(R1 育 taishakukyo-1923 の楽 angle・庄原市東城町)。**全長 8 km の神龍湖でカヌー** + 紅葉時期(11 月)が絶景、初心者+ 家族 OK。R1 育の三段峡渓流舟と並ぶ広島渓谷 2 大体験。",
    content_md: "- 立地:庄原市東城町+ 神石高原町(R1 育 taishakukyo)\n- 全長:神龍湖 8 km\n- カヌー体験:¥4500(2 時間・初心者 OK)\n- 紅葉時期:11 月\n- 営業:4-11 月(冬季休業)\n- 隣接:雄橋(国天然記念物)+ 鬼の唐門\n- アクセス:JR 福塩線 東城駅 から 車 15 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "庄原市",
    lg_code: "34210",
    area_types: ["activity_water", "scenic_spot"],
    lat: 34.8717,
    lon: 133.2750,
    season_start: "2026-04-01",
    season_end: "2026-11-30",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["momiji", "taishakukyo_canoe", "8km_lake", "4500yen", "national_scenic"],
    source: "manual",
  },
  {
    slug: "mizuho-ski-resort",
    category: "entertainment",
    sub_type: "ski_season",
    title_zh: "芸北みずほハイランドスキー場(山県郡北広島町・標高 950m・西日本屈指雪量・12-3 月)",
    title_ja: "芸北みずほハイランドスキー場",
    romaji: "Mizuho Highland Ski",
    summary_zh: "**芸北みずほハイランドは西日本屈指のスキー場**(山県郡北広島町・標高 950 m)。**標高 950 m+ 西日本屈指の雪量**(年間 8 m+)、12-3 月運営。R1 既出 ニセコ系列の北海道は別格として、西日本では最大級。広島市内 から 車 1 時間 30 分の利便性。",
    content_md: "- 立地:山県郡北広島町(芸北高原)\n- 標高:950 m\n- 雪量:年間 8 m+(西日本屈指)\n- 営業期間:12 月-3 月\n- 主要コース:8 コース(初級+ 中級+ 上級)\n- リフト料金:1 日 ¥4500\n- レンタル:¥3500/1 日\n- アクセス:広島市内 から 車 1 時間 30 分(中国自動車道)",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: "山県郡",
    municipality_ja: "北広島町",
    lg_code: "34369",
    area_types: ["activity_snow", "mountain_village"],
    lat: 34.6889,
    lon: 132.3194,
    season_start: "2026-12-15",
    season_end: "2027-03-31",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["ski_season", "mizuho_highland", "950m", "west_japan_top", "8m_snow"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase D — 水族+ 動物+ マツダ(3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "miyajima-aquarium-1959",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "宮島水族館(廿日市市宮島・1959 開館・2011 全面リニューアル・スナメリ瀬戸内固有種・350 種)",
    title_ja: "宮島水族館",
    romaji: "Miyajima Aquarium",
    summary_zh: "**宮島水族館は瀬戸内海生物特化水族館**(廿日市市宮島町・1959 開館・2011 リニューアル)。**スナメリ(瀬戸内海固有のイルカ科)を全国唯一展示**、瀬戸内海+ 厳島周辺生物 350 種。宮島観光の家族向けスポット、入館料 ¥1420。",
    content_md: "- 開館:1959 年(昭和 34)・2011 年全面リニューアル\n- 立地:廿日市市宮島町\n- 主要展示:スナメリ(瀬戸内海固有・全国唯一)+ 牡蠣養殖+ 瀬戸内海生物 350 種\n- 入館料:¥1420\n- 営業:9:00-17:00(年中無休)\n- 隣接:厳島神社(徒歩 10 分)+ 大聖院\n- アクセス:宮島フェリー 宮島桟橋 徒歩 25 分(島内バスあり)",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "廿日市市",
    lg_code: "34213",
    area_types: ["aquarium_zoo"],
    lat: 34.2856,
    lon: 132.3197,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.miyajima-aqua.jp/" },
    tags: ["aquarium_zoo", "miyajima_aquarium", "1959", "2011_renewal", "sunameri_unique"],
    source: "manual",
  },
  {
    slug: "asa-zoo-1971",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "広島市安佐動物公園(1971 開園・全国 2 位飼育数 170 種・国内最大級丘陵動物園・年 70 万人)",
    title_ja: "広島市安佐動物公園",
    romaji: "Asa Zoo",
    summary_zh: "**広島市安佐動物公園は全国 2 位飼育数の丘陵動物園**(広島市安佐北区・1971 開園・170 種)。**東京上野動物園に次ぐ規模**、サファリ風放し飼いコーナー+ 子供向け体験+ 夜の動物園イベント。年 70 万人来場、家族連れの広島観光定番。",
    content_md: "- 開園:1971 年(昭和 46)\n- 立地:広島市安佐北区(丘陵地)\n- 飼育数:170 種(全国 2 位・上野動物園に次ぐ)\n- 来場:約 70 万人/年\n- 入園料:¥510\n- 営業:9:00-16:30(木曜定休)\n- 主要展示:サファリ風放し飼いコーナー+ アジア小動物+ 夜の動物園(夏)\n- アクセス:広島市内 から バス 50 分・安佐動物公園下車",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "広島市",
    lg_code: "34100",
    area_types: ["aquarium_zoo"],
    lat: 34.5419,
    lon: 132.4914,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["thu"],
    external_urls: { official: "https://www.asazoo.jp/" },
    tags: ["aquarium_zoo", "asa_zoo", "1971", "national_2nd", "170_species"],
    source: "manual",
  },
  {
    slug: "mazda-museum",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "マツダミュージアム(広島市府中町・マツダ本社内・無料見学・MX-5+ ロータリーエンジン+ 工場ライン)",
    title_ja: "マツダミュージアム",
    romaji: "Mazda Museum",
    summary_zh: "**マツダミュージアムはマツダ本社内の自動車博物館**(広島市府中町・無料・要事前予約)。**MX-5+ コスモスポーツ+ RX-7+ ロータリーエンジン展示+ 実工場ライン見学** が組合わせ、自動車ファン+ 工業史愛好家の必訪。広島が **マツダ本社+ サンフレッチェ広島+ カープ** の本拠地である象徴。",
    content_md: "- 立地:広島市府中町(マツダ本社内)\n- 入場:無料(要事前予約)\n- 主要展示:MX-5+ コスモスポーツ+ RX-7+ ロータリーエンジン+ 実工場ライン\n- 営業:9:00-15:00(土日祝休)\n- 予約:電話 + ネット(www.mazda.com・1 ヶ月前推奨)\n- 所要:1.5 時間(ガイド付ツアー)\n- アクセス:JR 山陽本線 向洋駅 徒歩 20 分(マツダ送迎バスあり)",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: "安芸郡",
    municipality_ja: "府中町",
    lg_code: "34302",
    area_types: ["museum_art"],
    lat: 34.3725,
    lon: 132.5031,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 30,
    closed_days: ["sat", "sun"],
    external_urls: { official: "https://www.mazda.com/ja/about/museum/" },
    tags: ["aquarium_zoo", "mazda_museum", "free_admission", "rotary_engine", "factory_tour"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase E — 祭礼+ フラワー(4)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "hiroshima-flower-festival-may",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "広島フラワーフェスティバル(GW 5/3-5・1977 起源・80 万人来場・平和大通り+ 平和公園)",
    title_ja: "ひろしまフラワーフェスティバル",
    romaji: "Hiroshima Flower Festival",
    summary_zh: "**広島フラワーフェスティバルは GW の広島最大祭**(5 月 3-5 日・1977 起源)。**平和大通り+ 平和記念公園を会場**、原爆復興+ 平和を象徴する祭。**3 日間 80 万人来場**(全国級)、パレード+ ステージ+ 屋台+ 花展示等多彩。広島市民の最大イベント。",
    content_md: "- 開催:5 月 3-5 日(GW)・1977 起源\n- 主会場:平和大通り+ 平和記念公園(R1 育)\n- 来場:80 万人(3 日間・全国級)\n- 内容:パレード+ ステージ+ 屋台+ 花展示+ ピースメッセージ\n- 入場:無料\n- アクセス:広島電鉄「原爆ドーム前」電停 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "広島市",
    lg_code: "34100",
    area_types: ["festival_event"],
    lat: 34.3917,
    lon: 132.4528,
    season_start: null,
    season_end: null,
    event_start: "2026-05-03",
    event_end: "2026-05-05",
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.hiroshima-ff.com/" },
    tags: ["flower_field", "flower_festival", "1977_origin", "800k_visitors", "gw_3day"],
    source: "manual",
  },
  {
    slug: "tokasan-orifuren-fes-jun",
    category: "entertainment",
    sub_type: "ancient_festival",
    title_zh: "とうかさん大祭(6 月第 1 週末・広島市内・浴衣の日始まり・60 万人来場・1620 起源)",
    title_ja: "とうかさん大祭",
    romaji: "Toukasan Taisai",
    summary_zh: "**とうかさん大祭は浴衣の日始まりの広島祭**(広島市中区・6 月第 1 週末・1620 起源)。**1620 年浅野家入封後始まった圓隆寺の祭事**、現代は「浴衣の日」始まりとして 60 万人来場の広島最大夏祭の 1。R1 既出広島フラワーフェスと並ぶ都心 2 大祭。",
    content_md: "- 開催:6 月第 1 週末(土+ 日 + 月)\n- 起源:1620 年(元和 6)・浅野家入封\n- 主会場:広島市中区(中央通り+ とうかさん圓隆寺)\n- 来場:60 万人\n- 文化:浴衣の日始まり(全国の浴衣シーズン開幕)\n- 入場:無料\n- アクセス:広島電鉄「八丁堀」電停 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "広島市",
    lg_code: "34100",
    area_types: ["festival_event"],
    lat: 34.3925,
    lon: 132.4711,
    season_start: null,
    season_end: null,
    event_start: "2026-06-05",
    event_end: "2026-06-07",
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["ancient_festival", "toukasan", "1620_origin", "yukata_kickoff", "600k_visitors"],
    source: "manual",
  },
  {
    slug: "mihara-yatsui-aug",
    category: "entertainment",
    sub_type: "ancient_festival",
    title_zh: "三原やっさ祭り(8 月第 1 週末・三原市・1567 小早川隆景築城祝起源・3 日間 35 万人)",
    title_ja: "三原やっさ祭り",
    romaji: "Mihara Yatsui",
    summary_zh: "**三原やっさ祭りは 1567 年起源の備後最大祭**(三原市・8 月第 1 週末・3 日間)。**小早川隆景三原城築城祝が起源**、現在は **やっさ踊り+ タコ料理(R1 食 mihara-tako)+ 花火** で 35 万人来場。備後地方最大の夏祭、三原観光のハイライト。",
    content_md: "- 開催:8 月第 1 週末(3 日間)\n- 起源:1567 年(永禄 10)小早川隆景三原城築城祝\n- 主会場:三原市内(駅前+ 港+ 商店街)\n- 来場:35 万人(3 日間)\n- 内容:やっさ踊り+ タコ料理(R1 食)+ 花火大会\n- 入場:無料\n- アクセス:JR 三原駅 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "三原市",
    lg_code: "34204",
    area_types: ["festival_event"],
    lat: 34.4031,
    lon: 133.0786,
    season_start: null,
    season_end: null,
    event_start: "2026-08-08",
    event_end: "2026-08-10",
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["ancient_festival", "mihara_yatsui", "1567_origin", "350k_visitors", "kobayakawa_takakage"],
    source: "manual",
  },
  {
    slug: "fukuyama-bara-matsuri-may",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "福山ばら祭(5 月第 3 週末・福山市・1956 起源・市花ばら・80 万人来場・福山ばら公園)",
    title_ja: "福山ばら祭",
    romaji: "Fukuyama Bara Matsuri",
    summary_zh: "**福山ばら祭は 1956 起源の備後最大花祭**(福山市・5 月第 3 週末・80 万人来場)。**福山駅前+ ばら公園で市花ばら満開時期**、ばらのアーチ+ ばら品種展示+ ローズパレード+ ばら和菓子(R1 食 fukuyama-bara-wagashi)。R1 既出ばら関連の集大成。",
    content_md: "- 開催:5 月第 3 週末\n- 起源:1956 年(昭和 31)・市花ばら指定\n- 主会場:福山駅前+ ばら公園\n- 来場:80 万人(2 日間)\n- 内容:ばらアーチ+ 品種展示+ ローズパレード+ ばら和菓子(R1 食)+ ばら土産(R1 衣)\n- 入場:無料\n- アクセス:JR 福山駅 徒歩 1-15 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "福山市",
    lg_code: "34207",
    area_types: ["festival_event", "flower_field"],
    lat: 34.4889,
    lon: 133.3633,
    season_start: null,
    season_end: null,
    event_start: "2026-05-16",
    event_end: "2026-05-17",
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["flower_field", "fukuyama_bara_fes", "1956_origin", "800k_visitors", "city_flower"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase F — 観戦+ 夜景(3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "mazda-stadium-2009",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "MAZDA Zoom-Zoom スタジアム広島(2009 開業・広島東洋カープ本拠地・3 万人収容・全国屈指人気球場)",
    title_ja: "MAZDA Zoom-Zoom スタジアム広島",
    romaji: "Mazda Stadium Hiroshima",
    summary_zh: "**MAZDA Zoom-Zoom スタジアム広島はカープ本拠地**(広島市南区・2009 開業・3 万人収容)。**広島東洋カープ(プロ野球パ・リーグ)+ サンフレッチェ広島(J リーグ)** の本拠地、全国屈指の人気球場として満員必至。試合観戦+ 球場見学が広島観光のスポーツ angle。",
    content_md: "- 開業:2009 年(平成 21)\n- 立地:広島市南区(JR 広島駅 徒歩 10 分)\n- 収容:約 3 万 3 千人\n- ホームチーム:広島東洋カープ(プロ野球)\n- チケット:¥2500-12000(プレミアム高額)\n- 営業:野球シーズン 4-10 月+ 試合日のみ開場\n- アクセス:JR 広島駅 徒歩 10 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "広島市",
    lg_code: "34100",
    area_types: ["sports"],
    lat: 34.3917,
    lon: 132.4847,
    season_start: "2026-04-01",
    season_end: "2026-10-31",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.mazdastadium.jp/" },
    tags: ["sports_spectate", "mazda_stadium", "2009", "carp_home", "33k_capacity"],
    source: "manual",
  },
  {
    slug: "urihime-yama-yakei",
    category: "entertainment",
    sub_type: "scenic_spot",
    title_zh: "うり姫山公園(広島市南区・標高 137m・広島湾全景夜景・「日本夜景遺産」+ 2 階級夜景認定)",
    title_ja: "うり姫山公園",
    romaji: "Urihime Yama Koen",
    summary_zh: "**うり姫山公園は広島市内の代表夜景スポット**(広島市南区・標高 137 m)。**広島湾+ 広島市街+ 平和大通り+ 原爆ドーム** が一望、日本夜景遺産+ 2 階級夜景認定。R1 既出 鍋冠山(R1 楽 nabekanmuriyama)の長崎版的位置づけ、無料 24 時間+ 駐車場。",
    content_md: "- 標高:137 m\n- 立地:広島市南区比治山公園隣\n- 認定:日本夜景遺産+ 2 階級夜景\n- 眺望:広島湾+ 市街+ 平和大通り+ 原爆ドーム\n- 入場:無料(常時)\n- 駐車場:無料 30 台\n- ベスト時間:日没後 1 時間\n- アクセス:広島電鉄「比治山下」電停 徒歩 20 分(車 5 分)",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "広島市",
    lg_code: "34100",
    area_types: ["scenic_spot"],
    lat: 34.3833,
    lon: 132.4806,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["scenic_spot", "urihime_yama", "137m", "japan_night_view_heritage", "free"],
    source: "manual",
  },
  {
    slug: "miyoshi-hanada-ue-may",
    category: "entertainment",
    sub_type: "ancient_festival",
    title_zh: "三次花田植(三次市+ 安芸高田市・国指定重要無形民俗文化財 1976・5 月最終週末・牛使い+ 田植唄)",
    title_ja: "壬生の花田植",
    romaji: "Mibu Hanada Ue",
    summary_zh: "**壬生の花田植は国指定重要無形民俗文化財**(三次市+ 安芸高田市・5 月最終週末)。**牛使いが飾った牛 で田を耕し、田植女が田植唄を歌いながら稲を植える伝統田植儀式**。1976 年国指定、2011 年ユネスコ無形文化遺産に登録された貴重な祭礼、観光客の必訪。",
    content_md: "- 開催:5 月最終週末\n- 認定:国指定重要無形民俗文化財(1976)+ ユネスコ無形文化遺産(2011)\n- 主会場:安芸高田市美土里町(壬生)\n- 内容:牛使い+ 田植女+ 田植唄+ 飾り牛 30 頭+\n- 来場:数万人\n- 入場:無料\n- アクセス:JR 芸備線 三次駅 から 車 30 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "安芸高田市",
    lg_code: "34214",
    area_types: ["festival_event"],
    lat: 34.6717,
    lon: 132.7344,
    season_start: null,
    season_end: null,
    event_start: "2026-05-31",
    event_end: "2026-05-31",
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["ancient_festival", "mibu_hanada_ue", "national_intangible_1976", "unesco_2011", "may_last_weekend"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase G — 温泉+ 海水浴(4)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "yuki-onsen-overview",
    category: "entertainment",
    sub_type: "hiroshima_setouchi_onsen",
    title_zh: "湯来温泉(広島市佐伯区・1300 年起源・広島最古温泉・湯来高原+ 旅館 5 軒・広島市内 から 1 時間)",
    title_ja: "湯来温泉",
    romaji: "Yuki Onsen",
    summary_zh: "**湯来温泉は広島最古の温泉地**(広島市佐伯区・1300 年起源)。**奈良期の発見伝**、湯来高原の山間温泉地で 5+ 軒の旅館が散在。広島市内 から 車 1 時間の利便性、地元客中心の素朴な温泉。日帰り入浴 ¥600-1500、宿泊 ¥10000-18000(2 食付)。",
    content_md: "- 立地:広島市佐伯区湯来町(山間温泉地)\n- 起源:1300 年(奈良期発見伝)\n- 旅館数:5+ 軒\n- 泉質:単純温泉(美肌の湯)\n- 日帰り入浴:¥600-1500\n- 宿泊:¥10000-18000/泊(2 食付)\n- アクセス:広島市内 から 車 1 時間",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "広島市",
    lg_code: "34100",
    area_types: ["onsen_field"],
    lat: 34.4583,
    lon: 132.2583,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_setouchi_onsen", "yuki_onsen", "1300_years", "hiroshima_oldest_onsen", "5_inns"],
    source: "manual",
  },
  {
    slug: "miyahama-onsen-overview",
    category: "entertainment",
    sub_type: "hiroshima_setouchi_onsen",
    title_zh: "宮浜温泉(廿日市市・宮島眺望温泉・1964 開湯・10+ 軒旅館・宮島フェリー徒歩 15 分)",
    title_ja: "宮浜温泉",
    romaji: "Miyahama Onsen",
    summary_zh: "**宮浜温泉は宮島眺望の海岸温泉**(廿日市市宮浜・1964 開湯)。**宮島大鳥居が眺望できる温泉**、10+ 軒の旅館・ホテルが集まる。R1 既出 宮島内の岩惣等高級宿の代替として、本土側でアクセス便利+ 宿泊費控えめの選択肢。",
    content_md: "- 開湯:1964 年(昭和 39)\n- 立地:廿日市市宮浜(宮島対岸)\n- 旅館数:10+ 軒\n- 眺望:宮島大鳥居+ 厳島神社\n- 泉質:塩化物泉\n- 日帰り入浴:¥800-1500\n- 宿泊:¥12000-25000/泊(2 食付)\n- アクセス:宮島フェリー 宮島口 から 車 5 分(徒歩 15 分)",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "廿日市市",
    lg_code: "34213",
    area_types: ["onsen_field"],
    lat: 34.3097,
    lon: 132.3036,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_setouchi_onsen", "miyahama_onsen", "1964", "miyajima_view", "10_inns"],
    source: "manual",
  },
  {
    slug: "egashira-beach-onomichi",
    category: "entertainment",
    sub_type: "hiroshima_setouchi_onsen",
    title_zh: "瀬戸田サンセットビーチ(尾道市瀬戸田町・しまなみ海道+ 多島海+ サンセット・夏海水浴 7-8 月)",
    title_ja: "瀬戸田サンセットビーチ",
    romaji: "Setoda Sunset Beach",
    summary_zh: "**瀬戸田サンセットビーチはしまなみ海道のリゾートビーチ**(尾道市瀬戸田町)。**多島海+ しまなみ海道+ サンセット** の絶景、7-8 月海水浴+ 周辺レモン畑(R1 食既出)+ 平山郁夫美術館(R1 楽既出)とセット。",
    content_md: "- 立地:尾道市瀬戸田町(生口島)\n- 海水浴期間:7-8 月\n- 砂質:白砂(瀬戸内系)\n- 設備:無料駐車場+ シャワー+ トイレ\n- 周辺:レモン畑(R1 食 setoda-lemon)+ 平山郁夫美術館(R1 楽)\n- アクセス:しまなみ海道 生口島南 IC 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["coast_seaside"],
    lat: 34.2917,
    lon: 133.0833,
    season_start: "2026-07-15",
    season_end: "2026-08-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_setouchi_onsen", "setoda_sunset_beach", "shimanami_resort", "july_august", "lemon_island"],
    source: "manual",
  },
  {
    slug: "etajima-tsuboi-beach",
    category: "entertainment",
    sub_type: "hiroshima_setouchi_onsen",
    title_zh: "江田島ツボイ海水浴場(江田島市・透明度高+ 砂浜+ 旧海軍兵学校徒歩・夏 7-8 月家族向け)",
    title_ja: "江田島ツボイ海水浴場",
    romaji: "Etajima Tsuboi Beach",
    summary_zh: "**江田島ツボイ海水浴場は瀬戸内海離島ビーチ**(江田島市・透明度高い砂浜)。R1 育既出 旧海軍兵学校(R1 etajima-naval-academy)観光と一体、夏 7-8 月の家族向け海水浴+ 江田島和牡蠣(R1 食 hiroshima-kaki)も食事可。広島市内 から フェリー 30 分の利便性。",
    content_md: "- 立地:江田島市(瀬戸内海離島)\n- 海水浴期間:7-8 月\n- 砂浜:透明度高+ 白砂\n- 周辺:旧海軍兵学校(R1 育・徒歩 15 分)+ 江田島和牡蠣養殖場\n- 入場:無料\n- アクセス:広島港 から フェリー 30 分・小用港 から バス",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "江田島市",
    lg_code: "34215",
    area_types: ["coast_seaside"],
    lat: 34.2375,
    lon: 132.4719,
    season_start: "2026-07-15",
    season_end: "2026-08-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_setouchi_onsen", "etajima_tsuboi", "ferry_30min", "high_transparency", "naval_academy_walk"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[hiroshima-entertainment] 尚無條目");
    return;
  }
  console.log(`[hiroshima-entertainment] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(32)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[hiroshima-entertainment] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[hiroshima-entertainment] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[hiroshima-entertainment] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
