// Seed 神奈川県 R5 補完(20 筆 / Sprint 5.x / 第十四卷)
// 食 5 / 衣 3 / 住 3 / 育 4 / 楽 3 / 行 2 = 20 累積 183 + 20 = 203
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 食 5
  {
    slug: "shumai-specialty-tribute",
    category: "food", sub_type: "kanagawa_yokohama_food",
    title_zh: "横浜シウマイ専門店+ 派生品(横浜市中区+ 西区横浜駅・R1 食 崎陽軒シウマイ 1908 派生・「シウマイ娘」販売店全国 100+ 軒+ シウマイ弁当(全国駅弁売上首位常連)+ シウマイ饅頭+派生菓子・¥850-2,500・国際 SNS 海外旅行者代表)",
    title_ja: "シウマイ専門", romaji: "Shumai Specialty",
    summary_zh: "**横浜シウマイ専門店+派生品は R1 食 崎陽軒 1908 派生・「シウマイ娘」販売店 100+ 軒・シウマイ弁当(全国駅弁売上首位常連)・シウマイ饅頭**(中区+横浜駅)。¥850-2,500、海外代表。",
    content_md: "- 立地:**横浜市中区 + 西区横浜駅**\n- 関連:**R1 食 崎陽軒シウマイ 1908 派生**\n- 認定:**シウマイ弁当(全国駅弁売上首位常連)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shumai_specialty"], source: "manual",
  },
  {
    slug: "yokosuka-naval-port-pasta",
    category: "food", sub_type: "kanagawa_miura_food",
    title_zh: "横須賀港湾パスタ+ ナポリタン(横須賀市本町+ どぶ板通+ JR 横須賀駅・1945 戦後米軍兵食起源 80+ 年+ 「よこすかネイビーバーガー」R2 食派生+ 「ヨコスカチェリーチーズケーキ」+ ナポリタン・¥1,500-3,500)",
    title_ja: "横須賀パスタ", romaji: "Yokosuka Pasta",
    summary_zh: "**横須賀港湾パスタ+ナポリタンは 1945 戦後米軍兵食起源 80+ 年・R2 食 ネイビーバーガー派生・「ヨコスカチェリーチーズ」+ナポリタン**(横須賀本町+どぶ板+JR)。¥1,500-3,500。",
    content_md: "- 立地:**横須賀市本町 + どぶ板通 + JR 横須賀駅**\n- 起源:**1945 戦後米軍兵食起源 80+ 年**\n- 関連:**R2 食 ネイビーバーガー派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横須賀市", lg_code: "14201",
    area_types: ["restaurant_traditional"], lat: 35.2806, lon: 139.6711,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokosuka_pasta"], source: "manual",
  },
  {
    slug: "kamakura-matcha-sweets",
    category: "food", sub_type: "kanagawa_shonan_food",
    title_zh: "鎌倉抹茶スイーツ+ 抹茶アイス(鎌倉市小町+ 山ノ内+ 長谷・R1 食 鎌倉精進料理派生・1990 年代以降抹茶スイーツブーム・「茶寮 風花」+「ドルチェ・ファル・ニエンテ」+ 抹茶パフェ+ ロールケーキ・¥800-3,500・国際 SNS 海外抹茶ファン代表)",
    title_ja: "鎌倉抹茶スイーツ", romaji: "Kamakura Matcha",
    summary_zh: "**鎌倉抹茶スイーツ+抹茶アイスは R1 食 精進料理派生・1990 年代以降ブーム・「茶寮 風花」+「ドルチェ・ファル・ニエンテ」+抹茶パフェ+ロールケーキ**(小町+山ノ内+長谷)。¥800-3,500。",
    content_md: "- 立地:**鎌倉市小町 + 山ノ内 + 長谷**\n- 関連:**R1 食 鎌倉精進料理派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["restaurant_traditional"], lat: 35.3197, lon: 139.5519,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kamakura_matcha"], source: "manual",
  },
  {
    slug: "kanagawa-rice-harumi",
    category: "food", sub_type: "kanagawa_kennō_food",
    title_zh: "神奈川県オリジナル米はるみ+ さがみのほし(全県+海老名+ 厚木+ 平塚・1991 神奈川県オリジナル「はるみ」品種開発 34+ 年+ 「さがみのほし」 2013 開発・全国食味 A・1kg ¥1,500-3,500・JR 駅+全国百貨店流通)",
    title_ja: "神奈川オリジナル米", romaji: "Kanagawa Rice",
    summary_zh: "**神奈川県オリジナル米はるみ+さがみのほしは 1991 「はるみ」 34+ 年+2013 「さがみのほし」・全国食味 A**(全県+海老名+厚木+平塚)。¥1,500-3,500/kg、JR+百貨店。",
    content_md: "- 立地:**全県 + 海老名市 + 厚木市 + 平塚市**\n- 起源:**1991 神奈川県オリジナル「はるみ」品種開発 34+ 年 + 「さがみのほし」 2013 開発**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "海老名市", lg_code: "14215",
    area_types: ["farm_field"], lat: 35.4583, lon: 139.3914,
    season_start: "2026-09-15", season_end: "2026-10-31", event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kanagawa_rice_harumi"], source: "manual",
  },
  {
    slug: "hayama-yacht-french",
    category: "food", sub_type: "kanagawa_miura_food",
    title_zh: "葉山ヨットハーバー+ フレンチレストラン(三浦郡葉山町堀内+森戸海岸・1964 葉山港ヨットハーバー開業 61+ 年(1964 東京五輪ヨット会場)+ 葉山フレンチ「シャトーレストランジョエル」 1991+ 「日影茶屋」 1690 江戸期創業 335+ 年(全国最古料亭候補)・¥9,500-32,000)",
    title_ja: "葉山ヨット+フレンチ", romaji: "Hayama Yacht French",
    summary_zh: "**葉山ヨットハーバー+フレンチレストランは 1964 ヨットハーバー 61+ 年(1964 東京五輪会場)・「日影茶屋」 1690 江戸期 335+ 年(全国最古料亭候補)**(葉山堀内+森戸)。¥9,500-32,000。",
    content_md: "- 立地:**三浦郡葉山町堀内 + 森戸海岸**\n- 起源:**1964 葉山港ヨットハーバー開業 61+ 年(1964 東京五輪ヨット会場) + 「日影茶屋」 1690 江戸期創業 335+ 年**\n- 認定:**全国最古料亭候補**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "三浦郡", municipality_ja: "葉山町", lg_code: "14301",
    area_types: ["restaurant_traditional", "beach_coast"], lat: 35.2733, lon: 139.5808,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["hayama_yacht_1964", "hikage_chaya_1690"], source: "manual",
  },

  // 衣 3
  {
    slug: "yokohama-kamome-scarf",
    category: "fashion", sub_type: "kanagawa_yokohama_clothing",
    title_zh: "横浜カモメ柄スカーフ+ 横浜マスコット派生(横浜市中区+元町・R1 衣 シルクスカーフ 1859 派生・横浜市の鳥カモメ柄スカーフ+ 横浜開港マスコット「ハマ虎」+横浜赤レンガロゴ・¥3,500-12,000・国際 SNS 海外旅行者代表土産)",
    title_ja: "横浜カモメスカーフ", romaji: "Yokohama Kamome Scarf",
    summary_zh: "**横浜カモメ柄スカーフ+マスコット派生は R1 衣 シルクスカーフ 1859 派生・横浜市の鳥カモメ柄+「ハマ虎」+赤レンガロゴ**(中区+元町)。¥3,500-12,000、海外代表土産。",
    content_md: "- 立地:**横浜市中区 + 元町**\n- 関連:**R1 衣 シルクスカーフ 1859 派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["shopping_district"], lat: 35.4400, lon: 139.6500,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokohama_kamome"], source: "manual",
  },
  {
    slug: "kamakura-komachi-goshuin",
    category: "fashion", sub_type: "kanagawa_kannushi",
    title_zh: "鎌倉小町通御朱印帳+ 鎌倉武家紋アパレル(鎌倉市小町・R1 食 鎌倉小町通商店街派生・R1 育 鶴岡八幡宮+大仏+建長寺御朱印帳 50+ 種+ 鎌倉武家「笹竜胆」家紋アパレル(源頼朝家紋)・¥1,500-3,500・国際 SNS 海外御朱印巡礼者代表)",
    title_ja: "鎌倉御朱印", romaji: "Kamakura Goshuin",
    summary_zh: "**鎌倉小町通御朱印帳+武家紋アパレルは R1 食 派生・R1 育 鶴岡八幡宮+大仏+建長寺御朱印帳 50+ 種+「笹竜胆」家紋(源頼朝)**(鎌倉小町)。¥1,500-3,500、海外代表。",
    content_md: "- 立地:**鎌倉市小町**\n- 関連:**R1 食 小町通 + R1 育 鶴岡八幡宮 + 大仏 + 建長寺派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["shopping_district"], lat: 35.3197, lon: 139.5519,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kamakura_goshuin"], source: "manual",
  },
  {
    slug: "tanzawa-hiking-wear",
    category: "fashion", sub_type: "kanagawa_kennō_clothing",
    title_zh: "丹沢大山ハイキングウェア+ 大山詣り装束派生(伊勢原市+ 秦野+ 山北町+ 清川村・R1 楽 丹沢大山国定公園 1965 派生+ R1 衣 大山詣り装束派生・モンベル+ コロンビア+ ノースフェイス・登山靴+ レインウェア+ ザック・¥9,500-65,000)",
    title_ja: "丹沢大山ハイキング", romaji: "Tanzawa Hiking",
    summary_zh: "**丹沢大山ハイキングウェア+大山詣派生は R1 楽 丹沢大山 1965+R1 衣 大山詣派生・モンベル+コロンビア+ノースフェイス**(伊勢原+秦野+山北+清川)。¥9,500-65,000。",
    content_md: "- 立地:**伊勢原市 + 秦野市 + 山北町 + 清川村**\n- 関連:**R1 楽 丹沢大山国定公園 1965 + R1 衣 大山詣り装束派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "秦野市", lg_code: "14211",
    area_types: ["shopping_district"], lat: 35.3744, lon: 139.2206,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tanzawa_hiking_wear"], source: "manual",
  },

  // 住 3
  {
    slug: "oiso-villa-resort",
    category: "lodging", sub_type: "kanagawa_shonan_lodging",
    title_zh: "大磯ヴィラリゾート+ 海岸沿コテージ(中郡大磯町・R1 住 大磯プリンス 1986+R2 楽 大磯ロングビーチ 1957 派生・1900 年代以降「湘南別荘」貸切ヴィラ 30+ 軒+ オーシャンビュー+ R4 楽 大磯町散策連動・¥22,000-85,000/泊・国内+海外旅行者代表)",
    title_ja: "大磯ヴィラ", romaji: "Ōiso Villa",
    summary_zh: "**大磯ヴィラリゾート+海岸沿コテージは R1 住 大磯プリンス 1986+R2 楽 ロングビーチ 1957 派生・1900 年代以降「湘南別荘」30+ 軒・オーシャンビュー**(大磯)。¥22,000-85,000/泊。",
    content_md: "- 立地:**中郡大磯町**\n- 関連:**R1 住 大磯プリンス 1986 + R2 楽 大磯ロングビーチ 1957 派生**\n- 規模:**「湘南別荘」貸切ヴィラ 30+ 軒**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "中郡", municipality_ja: "大磯町", lg_code: "14341",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 35.3056, lon: 139.3211,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["oiso_villa"], source: "manual",
  },
  {
    slug: "kamakura-station-hotels",
    category: "lodging", sub_type: "kanagawa_shonan_lodging",
    title_zh: "鎌倉駅前ビジネスホテル+ 中堅ホテル(鎌倉市・JR 鎌倉駅+ 江ノ電鎌倉駅前・カトレヤホテル鎌倉 1969+ 中堅ホテル 12+ 軒+ R3 住 鎌倉禅寺宿坊+R3 住 鎌倉古民家連動・¥9,500-22,000/泊)",
    title_ja: "鎌倉駅前ホテル", romaji: "Kamakura Station Hotel",
    summary_zh: "**鎌倉駅前ビジネスホテル+中堅は JR 鎌倉+江ノ電鎌倉駅前・カトレヤ 1969+中堅 12+ 軒**(鎌倉)。R3 住 禅寺宿坊+古民家連動、¥9,500-22,000/泊。",
    content_md: "- 立地:**鎌倉市**\n- 規模:**カトレヤホテル鎌倉 1969 + 中堅ホテル 12+ 軒**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["accommodation_hotel"], lat: 35.3197, lon: 139.5519,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kamakura_station_hotel"], source: "manual",
  },
  {
    slug: "yokohama-chinatown-stay",
    category: "lodging", sub_type: "kanagawa_yokohama_lodging",
    title_zh: "横浜中華街民泊+ 中華風ホテル(横浜市中区山下町・R1 食 横浜中華街 1859 派生・1990 年代以降民泊+中華風ホテル 35+ 軒+ R4 食 中華街高級店併設+ ローズホテル横浜 1979+ ¥12,000-35,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "中華街民泊", romaji: "Chinatown Stay",
    summary_zh: "**横浜中華街民泊+中華風ホテルは R1 食 1859 派生・1990 年代以降民泊+中華風 35+ 軒・ローズホテル 1979**(中区山下町)。¥12,000-35,000/泊、海外代表。",
    content_md: "- 立地:**横浜市中区山下町**\n- 関連:**R1 食 横浜中華街 1859 派生**\n- 規模:**民泊 + 中華風ホテル 35+ 軒**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["accommodation_hotel"], lat: 35.4428, lon: 139.6450,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["chinatown_stay"], source: "manual",
  },

  // 育 4
  {
    slug: "kawasaki-municipal-museum-1988",
    category: "culture", sub_type: "kanagawa_museum",
    title_zh: "川崎市市民ミュージアム+ 等々力プラザ(川崎市中原区等々力・1988 開館 37+ 年+ 川崎市総合博物館・川崎の自然史+古代-現代+漫画美術+映像・観覧 ¥500・JR 武蔵小杉駅+バス・現在改装中(2019 台風損壊で休館中・再開予定 2025 後)",
    title_ja: "川崎市民ミュージアム", romaji: "Kawasaki Municipal Museum",
    summary_zh: "**川崎市市民ミュージアム+等々力プラザは 1988 開館 37+ 年・川崎総合博物館・自然史+古代-現代+漫画+映像**(川崎中原等々力)。¥500、現在改装中(2019 台風損壊)。",
    content_md: "- 立地:**川崎市中原区等々力**\n- 起源:**1988 開館 37+ 年**\n- 認定:**川崎市総合博物館 + 川崎自然史 + 古代-現代 + 漫画美術 + 映像**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "川崎市", lg_code: "14130",
    area_types: ["museum_art"], lat: 35.5736, lon: 139.6464,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["kawasaki_museum_1988"], source: "manual",
  },
  {
    slug: "komyoji-1243",
    category: "culture", sub_type: "kanagawa_shrine_temple",
    title_zh: "光明寺(鎌倉市材木座・1243 寛元元年北条経時建立 782+ 年+ 浄土宗大本山+ 国指定重要文化財 山門 1847(関東最大級山門)+ 海岸沿+ 紅葉名所・参拝無料・JR 鎌倉駅+江ノ電バス・国際 SNS 海外旅行者代表)",
    title_ja: "光明寺", romaji: "Kōmyō-ji",
    summary_zh: "**光明寺は 1243 寛元元年北条経時建立 782+ 年・浄土宗大本山・国重文 山門 1847(関東最大級山門)・海岸沿+紅葉名所**(鎌倉材木座)。参拝無料、海外代表。",
    content_md: "- 立地:**鎌倉市材木座**\n- 起源:**1243 寛元元年北条経時建立 782+ 年**\n- 認定:**浄土宗大本山 + 国指定重要文化財 山門 1847(関東最大級山門) + 紅葉名所**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["history_site_castle"], lat: 35.3083, lon: 139.5519,
    season_start: "2026-11-15", season_end: "2026-12-05", event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["komyoji_1243"], source: "manual",
  },
  {
    slug: "yokohama-hachiman-bashi",
    category: "culture", sub_type: "kanagawa_shrine_temple",
    title_zh: "横浜八幡橋八幡神社+ 横浜開港総鎮守(横浜市中区八幡橋・神社 1641 創建 384+ 年(伝承)+ 横浜港の前身 神奈川宿の総鎮守・横浜開港 1859 派生・徒歩アクセス・参拝無料)",
    title_ja: "八幡橋八幡神社", romaji: "Hachimanbashi",
    summary_zh: "**横浜八幡橋八幡神社+横浜開港総鎮守は神社 1641 創建 384+ 年伝承・横浜港の前身神奈川宿総鎮守・横浜開港 1859 派生**(中区八幡橋)。参拝無料。",
    content_md: "- 立地:**横浜市中区八幡橋**\n- 起源:**1641 創建 384+ 年(伝承) + 横浜開港 1859 派生**\n- 認定:**神奈川宿総鎮守**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["history_site_castle"], lat: 35.4344, lon: 139.6431,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["hachimanbashi_1641"], source: "manual",
  },
  {
    slug: "saijōji-1394",
    category: "culture", sub_type: "kanagawa_shrine_temple",
    title_zh: "大雄山最乗寺(南足柄市大雄町・1394 応永元年 了庵慧明禅師開山 631+ 年+ 曹洞宗関東屈指大寺院+ 国指定重要文化財 鐘楼+ 道了尊伝説・3000 株あじさい(7 月)+ 紅葉(11 月)・参拝無料+ R4 行 伊豆箱根大雄山線終点)",
    title_ja: "大雄山最乗寺", romaji: "Saijōji",
    summary_zh: "**大雄山最乗寺は 1394 応永元年 了庵慧明禅師開山 631+ 年・曹洞宗関東屈指大寺院・国重文 鐘楼・道了尊伝説**(南足柄大雄町)。R4 行 伊豆箱根大雄山線終点、参拝無料。",
    content_md: "- 立地:**南足柄市大雄町**\n- 起源:**1394 応永元年 了庵慧明禅師開山 631+ 年**\n- 認定:**曹洞宗関東屈指大寺院 + 国指定重要文化財 鐘楼 + 道了尊伝説**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "南足柄市", lg_code: "14216",
    area_types: ["history_site_castle", "nature_park"], lat: 35.3389, lon: 139.0833,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["saijoji_1394"], source: "manual",
  },

  // 楽 3
  {
    slug: "yokohama-bay-cruise",
    category: "entertainment", sub_type: "kanagawa_yokohama_entertainment",
    title_zh: "横浜港クルーズ船+ ロイヤルウィング(横浜市中区大さん橋+ 山下公園・1991 ロイヤルウィング就航 34+ 年+ ベイブリッジ 1989 周遊+ 山下公園+赤レンガ+みなとみらい+ベイブリッジ 90 分クルーズ+ ¥3,500-12,000/食事付・国際 SNS 海外旅行者代表)",
    title_ja: "横浜港クルーズ", romaji: "Yokohama Bay Cruise",
    summary_zh: "**横浜港クルーズ船+ロイヤルウィングは 1991 就航 34+ 年・ベイブリッジ 1989 周遊+山下公園+赤レンガ+みなとみらい 90 分**(中区大さん橋)。¥3,500-12,000、海外代表。",
    content_md: "- 立地:**横浜市中区大さん橋 + 山下公園**\n- 起源:**1991 ロイヤルウィング就航 34+ 年**\n- 認定:**ベイブリッジ 1989 周遊 + 90 分クルーズ**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["theme_park", "transport_hub"], lat: 35.4533, lon: 139.6428,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["yokohama_cruise_1991"], source: "manual",
  },
  {
    slug: "kamakura-festivals",
    category: "entertainment", sub_type: "kanagawa_seasonal",
    title_zh: "鎌倉まつり+ 鶴岡八幡宮例大祭(鎌倉市・R1 育 鶴岡八幡宮 1063 派生・鎌倉まつり 4 月第 2 日曜+ 鶴岡八幡宮例大祭 9 月 14-16 日(国指定無形民俗候補)+ 流鏑馬+ 武家行列・100 神輿+ 50 万人観衆・参加無料・国際 SNS 海外伝統文化代表)",
    title_ja: "鎌倉まつり", romaji: "Kamakura Festivals",
    summary_zh: "**鎌倉まつり+鶴岡八幡宮例大祭は R1 育 1063 派生・4 月第 2 日曜+9 月 14-16 日例大祭・流鏑馬+武家行列・100 神輿+50 万人**(鎌倉)。参加無料、海外代表。",
    content_md: "- 立地:**鎌倉市**\n- 関連:**R1 育 鶴岡八幡宮 1063 派生**\n- 規模:**鎌倉まつり 4 月第 2 日曜 + 鶴岡八幡宮例大祭 9 月 14-16 日 + 流鏑馬 + 武家行列**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["history_site_castle"], lat: 35.3258, lon: 139.5564,
    season_start: null, season_end: null, event_start: "2026-09-14T09:00:00+09:00", event_end: "2026-09-16T20:00:00+09:00",
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kamakura_festivals"], source: "manual",
  },
  {
    slug: "kawasaki-daishi-hatsumode",
    category: "entertainment", sub_type: "kanagawa_seasonal",
    title_zh: "川崎大師元日初詣+ 厄除大祭(川崎市川崎区大師町・R1 育 川崎大師 1128 派生・1 月 1-3 日初詣 300 万人(全国第 3 位)+ 厄除大祭+ 護摩供・京急大師線増発+ 24 時間参拝・参拝無料・国際 SNS 海外旅行者代表)",
    title_ja: "川崎大師初詣", romaji: "Kawasaki Hatsumode",
    summary_zh: "**川崎大師元日初詣+厄除大祭は R1 育 1128 派生・1 月 1-3 日初詣 300 万人(全国第 3 位)・京急大師線増発+24 時間参拝**(川崎大師町)。参拝無料、海外代表。",
    content_md: "- 立地:**川崎市川崎区大師町**\n- 関連:**R1 育 川崎大師平間寺 1128 派生**\n- 認定:**1 月 1-3 日初詣 300 万人(全国第 3 位)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "川崎市", lg_code: "14130",
    area_types: ["history_site_castle"], lat: 35.5350, lon: 139.7300,
    season_start: null, season_end: null, event_start: "2026-12-31T22:00:00+09:00", event_end: "2027-01-03T20:00:00+09:00",
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kawasaki_daishi_hatsumode"], source: "manual",
  },

  // 行 2
  {
    slug: "yokohama-bay-bridge-1989",
    category: "transport", sub_type: "kanagawa_kosoku",
    title_zh: "横浜ベイブリッジ+ 横浜横須賀道路 1979(横浜市中区+鶴見+横須賀・横浜ベイブリッジ 1989 開通 36+ 年(全長 860m 海上斜張橋)+ 横浜横須賀道路 1979 開通 46+ 年+ 首都高湾岸線+ R5 楽 横浜港クルーズ連動・通行料 ¥520-1,520)",
    title_ja: "ベイブリッジ+横横道路", romaji: "Bay Bridge",
    summary_zh: "**横浜ベイブリッジ+横須賀道路は 1989 開通 36+ 年(海上斜張橋 860m)+横須賀道路 1979 開通 46+ 年・R5 楽 港クルーズ連動**(中区+鶴見+横須賀)。¥520-1,520。",
    content_md: "- 起源:**横浜ベイブリッジ 1989 開通 36+ 年 + 横浜横須賀道路 1979 開通 46+ 年**\n- 規模:**全長 860m 海上斜張橋 + 首都高湾岸線**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.4567, lon: 139.6678,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["bay_bridge_1989"], source: "manual",
  },
  {
    slug: "yokohama-kanjō-southern-line",
    category: "transport", sub_type: "kanagawa_kosoku",
    title_zh: "横浜環状南線+ 国道 16 号線(横浜市+ 鎌倉+ 藤沢+ 横須賀・国道 16 号線 1885 横須賀軍道起源 140+ 年+ 横浜環状南線 2017 部分開通+ 県内主要道路網+ 第三京浜+横浜横須賀+横羽線連結・通行料 ¥0-520)",
    title_ja: "国道 16+環状南", romaji: "Kanjō Southern",
    summary_zh: "**横浜環状南線+国道 16 号線は 1885 横須賀軍道起源 140+ 年+横浜環状南 2017 部分開通・県内主要網・第三京浜+横須賀+横羽連結**(横浜+鎌倉+藤沢+横須賀)。¥0-520。",
    content_md: "- 起源:**国道 16 号線 1885 横須賀軍道起源 140+ 年 + 横浜環状南線 2017 部分開通**\n- 規模:**県内主要道路網 + 第三京浜 + 横浜横須賀 + 横羽線連結**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["route16_kanjō"], source: "manual",
  },
];

seedMain(rows, "kanagawa-r5");
