// Seed 静岡県 · 楽類 條目 → public.japan_entries(Sprint 19.5 楽 R1)
//
// 静岡 = 富士山眺望 + 河津桜 + テーマパーク + 観光列車 + 海:
//   - 富士山眺望:日本平・薩埵峠(広重画題)・大瀬崎・三島スカイウォーク(2015 日本最長吊橋 400m)
//   - 河津桜(2-3 月)— 全国級早咲き桜・河津町河津川沿い 8000 本
//   - 大井川鐡道 SL(現役 SL「かわね路」号・国内最大級 SL 観光列車)
//   - 伊豆シャボテン動物公園(1959・カピバラ温泉発祥地)
//   - 沼津港深海水族館(駿河湾深海・国内唯一)
//   - 熱海海上花火大会(年 12+ 回・春夏秋・冬)
//   - 時之栖イルミネーション(全国 5 大級・冬季)
//   - 御前崎サーフィン・白浜大浜(下田)
//   - 寸又峡夢の吊橋(秘境吊橋・コバルトブルー渓谷)
//
// 嚴格定義:全部具体観光スポット・テーマパーク・自然名所・実在物件のみ。
//
// 28 筆構成:
//   Phase A 富士山眺望 4(日本平・薩埵峠・大瀬崎・三島スカイウォーク)
//   Phase B 河津桜 1(河津桜まつり 2-3 月)
//   Phase C テーマパーク 4(シャボテン公園・パルパル・ぐらんぱる・ぐりんぱ)
//   Phase D 水族館・動物園 3(沼津深海・下田海中・日本平動物園)
//   Phase E 観光列車 3(大井川 SL・天竜浜名湖鉄道・伊豆急リゾート 21)
//   Phase F 花火 2(熱海海上花火・清水みなと祭り)
//   Phase G イルミ 1(時之栖)
//   Phase H 海・サーフ 2(御前崎・白浜大浜)
//   Phase I 修善寺虹の郷 1
//   Phase J 寸又峡夢の吊橋 1
//   Phase K その他名所 6(エコパ・初島・伊東マリン・沼津御用邸・河津七滝・井川五郎ダム + 浄蓮の滝)
//
// Usage:
//   npm run seed:japan-shizuoka-entertainment:dry
//   npm run seed:japan-shizuoka-entertainment

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "shizuoka_fujisan_view"
  | "shizuoka_kawazu_sakura"
  | "shizuoka_observation_train"
  | "shizuoka_nature_spot"
  | "theme_park"
  | "aquarium_zoo"
  | "sakura"
  | "firework_festival"
  | "illumination"
  | "flower_field"
  | "sports_spectate";

interface SeedRow {
  slug: string;
  category: "entertainment";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "chubu";
  prefecture_ja: "静岡県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // Phase A — 富士山眺望(4 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nihondaira-ropeway-yakei",
    category: "entertainment",
    sub_type: "shizuoka_fujisan_view",
    title_zh: "日本平 + 久能山ロープウェイ(夜景 100 選・富士山絶景)",
    title_ja: "日本平 + 日本平夢テラス",
    romaji: "Nihondaira",
    summary_zh: "**日本平は静岡市駿河区の山頂展望台**(海抜 307 m・国指定名勝)。富士山+駿河湾+南アルプス三方の絶景、夜景 100 選。山頂に「日本平夢テラス」(2018 開業・隈研吾設計)+ 日本平ホテル + 久能山東照宮ロープウェイ起点。観光・夜景デート・写真愛好家の定番。",
    content_md: "- 立地:静岡市駿河区(海抜 307 m 山頂)\n- 認定:国指定名勝(2018)・日本夜景遺産・夜景 100 選\n- 山頂施設:日本平夢テラス(2018 開業・隈研吾設計・無料)・日本平ホテル(老舗)・久能山東照宮ロープウェイ起点(山上駅)\n- 絶景:富士山(北方 50 km)+ 駿河湾(東方)+ 南アルプス(西北)+ 静岡市(南方)\n- 夢テラス:無料展望回廊・夜景時(11 月-2 月日没後 21:00 まで開放)\n- 久能山ロープウェイ:山頂駅 → 久能山東照宮(所要 5 分・往復 ¥1500)\n- アクセス:JR 静岡駅 から しずてつバス 40 分・日本平山頂下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["nature_view", "luxury_resort"],
    lat: 34.974,
    lon: 138.476,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shizuoka_fujisan_view", "nihondaira", "yakei_100", "kuma_kengo_2018"],
    source: "manual",
  },
  {
    slug: "satta-toge-hiroshige-view",
    category: "entertainment",
    sub_type: "shizuoka_fujisan_view",
    title_zh: "薩埵峠展望台(歌川広重「東海道五十三次・由比」原画地・富士+駿河湾絶景)",
    title_ja: "薩埵峠(さったとうげ)展望台",
    romaji: "Satta Toge",
    summary_zh: "**薩埵峠は歌川広重「東海道五十三次・由比」の原画地**(静岡市清水区由比~興津)。江戸期東海道の難所、富士山と駿河湾と松林を一望できる絶景ポイント。広重浮世絵と寸分違わぬ景観が現存、150+ 年経っても変わらぬ富士山眺望スポットとして写真愛好家の聖地。",
    content_md: "- 立地:静岡市清水区由比~興津(東海道旧道沿い)\n- 標高:約 100 m(駿河湾を見下ろす)\n- 文化:歌川広重「東海道五十三次・由比」(1833)の原画地\n- 絶景構成:富士山 + 駿河湾 + 松林 + 国道 1 号 + 東名高速 + 東海道本線(現代要素も同視野)\n- アクセス:JR 由比駅 から徒歩 25 分(山道)・JR 興津駅 徒歩 25 分(逆方向)\n- 駐車場:興津側に小規模駐車場\n- 撮影ベストタイム:夜明け~午前(順光)・夕暮れ(逆光シルエット)\n- 周辺:広重美術館(由比・徒歩 25 分)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["nature_view", "rural_townscape"],
    lat: 35.094,
    lon: 138.560,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shizuoka_fujisan_view", "satta_toge", "hiroshige", "tokaido_53"],
    source: "manual",
  },
  {
    slug: "osezaki-jinike-suruga",
    category: "entertainment",
    sub_type: "shizuoka_fujisan_view",
    title_zh: "大瀬崎(西伊豆・神池の不思議・富士山絶景・ダイビング聖地)",
    title_ja: "大瀬崎",
    romaji: "Osezaki",
    summary_zh: "**大瀬崎は西伊豆・沼津市の岬**(駿河湾突き出し)。富士山眺望地として絶景、岬突端の「神池」は海に囲まれているのに淡水という不思議で天然記念物。岬全体は「大瀬神社」(海の神)の神域、樹齢千年超の楠群(国指定天然記念物)あり。ダイビング聖地としても有名(駿河湾深海性魚類が浅場で観察可能)。",
    content_md: "- 立地:沼津市西浦(西伊豆・駿河湾突端)\n- 富士山眺望:駿河湾越しに直近で見える絶景(距離 30 km)\n- 神池:岬先端・海に囲まれた淡水池(原因不明・国指定天然記念物)\n- 樹叢:樹齢 1000 年超の楠 130 本(国指定天然記念物)\n- 大瀬神社:岬全体が神域・海の神を祀る\n- ダイビング:全国 200+ ダイビングポイントの 1 つ・浅場で深海性魚観察可能\n- 入場料:無料(神池見学 ¥100)\n- アクセス:JR 沼津駅 から バス 60 分・大瀬岬下車・終バス注意",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "沼津市",
    lg_code: "22203",
    area_types: ["nature_view", "fishing_port"],
    lat: 35.040,
    lon: 138.789,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shizuoka_fujisan_view", "osezaki", "jinike", "diving_spot"],
    source: "manual",
  },
  {
    slug: "mishima-skywalk-2015",
    category: "entertainment",
    sub_type: "shizuoka_fujisan_view",
    title_zh: "三島スカイウォーク(2015 開業・日本最長歩行者専用吊橋 400m・富士山絶景)",
    title_ja: "三島スカイウォーク",
    romaji: "Mishima Skywalk",
    summary_zh: "**三島スカイウォークは 2015 年開業の日本最長歩行者専用吊橋**(全長 400m)。三島市笹原・箱根西麓に建つ、富士山+駿河湾+伊豆山稜を 3 方一望の絶景。橋本体 ¥1100 + 隣接施設(ジップライン・フォレストアドベンチャー・バンジー・展望ドーム・グランピング)の総合エンタメ施設。",
    content_md: "- 開業:2015 年(平成27)三島\n- 仕様:全長 400 m(歩行者専用吊橋として日本最長)・高さ 70 m\n- 絶景:富士山 + 駿河湾 + 伊豆山稜 三方一望\n- 隣接アクティビティ:ジップライン(560m+ 250m 2 種)・フォレストアドベンチャー・バンジー・展望ドーム\n- 入場料:吊橋通行 ¥1100・各アクティビティ別\n- 営業:9:00-17:00\n- 定休:無休\n- アクセス:JR 三島駅 から バス 25 分・スカイウォーク下車・東名 沼津 IC 車 25 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "三島市",
    lg_code: "22206",
    area_types: ["nature_view", "luxury_resort"],
    lat: 35.092,
    lon: 138.876,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://mishima-skywalk.jp/" },
    tags: ["shizuoka_fujisan_view", "mishima_skywalk", "2015", "japan_longest_pedestrian_bridge"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase B — 河津桜(1 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kawazu-zakura-matsuri",
    category: "entertainment",
    sub_type: "shizuoka_kawazu_sakura",
    title_zh: "河津桜まつり(2-3 月・全国級早咲き桜・河津川沿い 8000 本)",
    title_ja: "河津桜まつり",
    romaji: "Kawazu-zakura Matsuri",
    summary_zh: "**河津桜は全国で最も早咲きの桜**(河津町・賀茂郡)。1955 年河津川河岸で発見された自然交配種(オオシマザクラ × ヒカンザクラ系)、開花期 1 月下旬~3 月初旬で「春一番の桜」として全国観光客が殺到。河津川沿い 4 km に 8000 本、まつり期間中夜のライトアップも実施。",
    content_md: "- 場所:賀茂郡河津町河津川沿い 約 4 km\n- 規模:約 8000 本の河津桜\n- 開花期:1 月下旬~3 月初旬(年により変動)\n- まつり期間:2 月 1 日~3 月 10 日(年に応じて調整)\n- 由来:1955 年河津町飯田勝美氏が河津川で発見・1974 年「河津桜」と命名\n- 品種:オオシマザクラ × ヒカンザクラ系(自然交配)\n- ライトアップ:まつり期間中 18:00-21:00\n- 来場者:年間 100 万人超\n- 屋台:約 100 軒(河津駅前~川沿い)\n- アクセス:伊豆急 河津駅 徒歩 0 分(駅前から始まる)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: "賀茂郡",
    municipality_ja: "河津町",
    lg_code: "22302",
    area_types: ["nature_view", "rural_townscape"],
    lat: 34.745,
    lon: 138.953,
    season_start: "2026-02-01",
    season_end: "2026-03-10",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://kawazuzakura.jp/" },
    tags: ["shizuoka_kawazu_sakura", "kawazu", "early_sakura", "8000_trees"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase C — テーマパーク(4 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "izu-shaboten-1959",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "伊豆シャボテン動物公園(1959 開園・カピバラ温泉発祥地)",
    title_ja: "伊豆シャボテン動物公園",
    romaji: "Izu Shaboten Zoo",
    summary_zh: "**伊豆シャボテン動物公園はカピバラ温泉発祥地**(伊東市・1959 開園)。世界各国のサボテン 1500 種 + 動物 140 種を展示する複合テーマパーク、特に冬期(11-3 月)のカピバラ温泉(湯気でほっこりするカピバラ達)は SNS で全国級話題。大室山ロープウェイ隣接、家族向け定番。",
    content_md: "- 開園:1959 年(昭和34)伊東\n- 立地:伊東市富戸(大室山麓)\n- カピバラ温泉:1982 開始(カピバラの故郷再現として湯船発案)・冬期(11 月下旬-4 月上旬)\n- 動物展示:140 種(カピバラ・カンガルー・リスザル・クジャク等の放し飼い)\n- 植物展示:サボテン 1500 種(温室)\n- 入場料:¥2700(子供 ¥1300)\n- 営業:9:30-17:00(冬季 16:00)\n- 定休:無休\n- 隣接:大室山(登山リフト 6 分・360°富士山眺望)\n- アクセス:伊豆急 伊豆高原駅 から バス 20 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 34.910,
    lon: 139.085,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://izushaboten.com/" },
    tags: ["theme_park", "izu_shaboten", "1959", "capybara_onsen_origin"],
    source: "manual",
  },
  {
    slug: "hamanako-pal-pal",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "浜名湖パルパル(舘山寺・大型遊園地・浜名湖畔・1959 開園)",
    title_ja: "浜名湖パルパル",
    romaji: "Hamanako Pal Pal",
    summary_zh: "**浜名湖パルパルは浜名湖畔の大型遊園地**(浜松市西区舘山寺・1959 開園)。30+ アトラクション(観覧車・ジェットコースター・ゴーカート 等)+ 浜名湖一望の立地、家族向けの定番テーマパーク。隣接の舘山寺ロープウェイで大草山(標高 113 m)へ、浜名湖一望の絶景。",
    content_md: "- 開園:1959 年(昭和34)浜松\n- 立地:浜松市西区舘山寺町(浜名湖畔)\n- アトラクション:30+(観覧車「コクー」45m・ジェットコースター・ゴーカート・メリーゴーランド 等)\n- 隣接:舘山寺ロープウェイ → 大草山(標高 113m・浜名湖一望)\n- 入園料:¥1300 + 乗物別 or フリーパス ¥4900\n- 営業:9:30-17:00\n- 定休:不定休(月数日)\n- アクセス:JR 浜松駅 から路線バス 50 分・舘山寺温泉下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 34.751,
    lon: 137.622,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://pal2.co.jp/" },
    tags: ["theme_park", "hamanako", "pal_pal", "1959"],
    source: "manual",
  },
  {
    slug: "izu-grandparis",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "伊豆ぐらんぱる公園(伊豆高原・大型レジャーランド・夜のイルミネーション)",
    title_ja: "伊豆ぐらんぱる公園",
    romaji: "Izu Grandparis",
    summary_zh: "**伊豆ぐらんぱる公園は伊豆高原の大型レジャーランド**(伊東市)。70+ アトラクション(ジップライン・ボートアドベンチャー・恐竜公園・カート 等)+ 冬期「グランイルミ」(全国 5 大級イルミネーション)。家族・カップル両用、伊豆高原観光の中心 1 つ。",
    content_md: "- 立地:伊東市富戸(伊豆高原)\n- アトラクション:70+(ジップライン・ボートアドベンチャー・恐竜公園・カート・パターゴルフ・水上アスレチック)\n- グランイルミ:11 月-8 月通年・夜のイルミネーション(全国 5 大級・¥1500)\n- 入園料:¥1500(夜の部 ¥1500)・乗物別\n- 営業:9:00-17:00 + 夜の部 16:00-21:30\n- 定休:無休\n- アクセス:伊豆急 伊豆高原駅 から バス 12 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["luxury_resort"],
    lat: 34.901,
    lon: 139.097,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://granpal.com/" },
    tags: ["theme_park", "izu_kogen", "grandparis", "gran_illumi"],
    source: "manual",
  },
  {
    slug: "fujikyu-grinpa-yamabe",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ぐりんぱ(裾野市・富士山麓家族遊園地・1965 開園)",
    title_ja: "ぐりんぱ",
    romaji: "Grinpa",
    summary_zh: "**ぐりんぱは富士山麓の家族向け遊園地**(裾野市・1965 開園)。富士サファリパーク隣接、富士山絶景立地。シルバニアファミリーや忍たま乱太郎のテーマエリアで子供連れに人気、夏は屋外プール・冬は雪遊びパーク。",
    content_md: "- 開園:1965 年(昭和40)裾野\n- 立地:裾野市須山(富士山南麓・標高 1100 m)\n- 富士山絶景:園内各所から富士山一望\n- テーマエリア:シルバニアパーク + ピカソのタマゴ + 忍たま乱太郎\n- 季節アトラクション:夏 屋外プール・冬 雪遊びパーク\n- 入園料:¥1300・フリーパス ¥3700(子供 ¥2900)\n- 営業:9:30-17:00\n- 定休:水曜(夏休み無休)\n- アクセス:JR 御殿場駅 から バス 50 分・東名 御殿場 IC 車 30 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "裾野市",
    lg_code: "22220",
    area_types: ["luxury_resort", "mountain_village"],
    lat: 35.293,
    lon: 138.815,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["wed"],
    external_urls: { official: "https://www.grinpa.com/" },
    tags: ["theme_park", "grinpa", "susono", "1965", "fuji_view"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase D — 水族館・動物園(3 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "numazu-shinkai-aquarium",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "沼津港深海水族館(駿河湾深海・国内唯一・2011 開業)",
    title_ja: "沼津港深海水族館",
    romaji: "Numazu Shinkai Aquarium",
    summary_zh: "**沼津港深海水族館は駿河湾深海生物専門水族館**(沼津市・2011 開業)。駿河湾(日本最深 2500 m・深海生物 1000+ 種)直近の立地を活かした、国内唯一の深海専門。シーラカンス展示(冷凍標本 + 剥製 5 体)・メガマウス・グソクムシ・トロボッチ等の深海魚を生体展示。",
    content_md: "- 開業:2011 年(平成23)沼津港\n- 規模:延床面積 約 1500 m²\n- 専門:駿河湾深海生物(水深 200-2500 m)\n- 看板展示:シーラカンス(冷凍標本 + 剥製 5 体・世界最大級コレクション)\n- 深海生体展示:タカアシガニ・グソクムシ・トロボッチ・メガマウス(剥製)・ダイオウイカ標本\n- 入場料:¥1800\n- 営業:10:00-18:00\n- 定休:無休\n- 立地:沼津港・港八十三番地内\n- アクセス:JR 沼津駅 から バス 15 分・沼津港下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "沼津市",
    lg_code: "22203",
    area_types: ["fishing_port", "urban_central"],
    lat: 35.087,
    lon: 138.851,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.numazu-deepsea.com/" },
    tags: ["aquarium_zoo", "numazu", "shinkai", "2011", "japan_only_deepsea"],
    source: "manual",
  },
  {
    slug: "shimoda-aquarium",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "下田海中水族館(1967 開業・湾内浮遊水族館・イルカショー)",
    title_ja: "下田海中水族館",
    romaji: "Shimoda Aquarium",
    summary_zh: "**下田海中水族館は湾内浮遊型水族館**(下田市・1967 開業)。下田湾の天然海域を網で囲ったフロート水族館で、海域そのものが展示水槽。イルカショー(¥1500 含)・ペンギン・アザラシ・サメ等。湾内浮遊型は国内 5 例しかなく、伊豆観光の定番。",
    content_md: "- 開業:1967 年(昭和42)下田\n- 立地:下田市三丁目(下田湾内浮遊型)\n- 構造:湾内を網で囲ったフロート水族館・海域そのものが展示\n- 看板:イルカショー(1 日 4 回・¥1500 入場料込)・タッチプール\n- 入場料:¥2200\n- 営業:9:00-16:30\n- 定休:無休\n- アクセス:伊豆急 下田駅 徒歩 12 分 or バス 5 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "下田市",
    lg_code: "22219",
    area_types: ["urban_central", "fishing_port"],
    lat: 34.674,
    lon: 138.936,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://shimoda-aquarium.com/" },
    tags: ["aquarium_zoo", "shimoda", "1967", "floating_aquarium"],
    source: "manual",
  },
  {
    slug: "nihondaira-zoo-shizuoka",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "靜岡市立日本平動物園(1969 開業・市民動物園・コアラ・ホッキョクグマ)",
    title_ja: "静岡市立日本平動物園",
    romaji: "Nihondaira Zoo",
    summary_zh: "**静岡市立日本平動物園は静岡市民の動物園**(1969 開業)。日本平の麓、150 種 700 頭の動物を展示。コアラ(2009 から飼育)・ホッキョクグマ(全国動物園で 30 頭程度のうち 2 頭が常駐)・レッサーパンダ等の人気者。家族向け定番、入場料リーズナブル(¥620)。",
    content_md: "- 開業:1969 年(昭和44)静岡\n- 規模:約 6 万 m²\n- 動物:150 種 700 頭\n- 看板:コアラ(2009-)・ホッキョクグマ(2 頭)・レッサーパンダ・キリン・ゾウ\n- 入場料:¥620(子供 ¥150)\n- 営業:9:00-16:30\n- 定休:月曜・年末年始\n- 立地:静岡市駿河区池田(JR 静岡駅 から バス 25 分・動物園入口下車)\n- アクセス:JR 静岡駅 から しずてつバス 25 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["urban_central", "rural_townscape"],
    lat: 34.974,
    lon: 138.443,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["mon"],
    external_urls: { official: "https://www.nhdzoo.jp/" },
    tags: ["aquarium_zoo", "nihondaira_zoo", "shizuoka", "1969", "koala"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase E — 観光列車(3 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "oigawa-tetsudo-sl",
    category: "entertainment",
    sub_type: "shizuoka_observation_train",
    title_zh: "大井川鐵道 SL「かわね路」(現役 SL 観光列車・国内最大級・大井川渓谷)",
    title_ja: "大井川鐵道 SL かわね路",
    romaji: "Oigawa Tetsudo SL Kawanej",
    summary_zh: "**大井川鐵道 SL は国内最大級の現役 SL 観光列車**。新金谷~千頭(38 km)を 90 分で走る、C11 形 + C56 形 + C108 形の本物 SL 牽引車両。大井川沿いの渓谷美 + 茶畑 + 蒸気機関車の郷愁感の三位一体で、「ぽっぽや」「千と千尋の神隠し」のような映画気分を実体験。",
    content_md: "- 区間:新金谷駅(島田市)~千頭駅(川根本町)・38 km\n- 所要:90 分\n- SL:C11形(2 両)+ C56 形 + C108 形(現役 SL の中で国内最大級)\n- 客車:旧型客車(国鉄昭和期車両改装)\n- 運行:春~秋 1 日 2-3 往復(冬季は週末のみ)\n- 料金:¥4500(乗車券 + SL 急行料金)\n- 連絡:千頭駅から井川線(アプト式・寸又峡・接岨峡)へ乗換可\n- 沿線:茶畑 + 大井川 + 鉄橋(蓬莱橋世界最長木造橋付近)\n- アクセス:JR 金谷駅 で大井川鐵道に乗換",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "島田市",
    lg_code: "22209",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 34.823,
    lon: 138.139,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://oigawa-railway.co.jp/" },
    tags: ["shizuoka_observation_train", "oigawa", "sl_kawane", "japan_oldest_sl_operating"],
    source: "manual",
  },
  {
    slug: "tenryu-hamanako-rail",
    category: "entertainment",
    sub_type: "shizuoka_observation_train",
    title_zh: "天竜浜名湖鉄道(国登録文化財駅舎多数・浜名湖周遊・1935 開業)",
    title_ja: "天竜浜名湖鉄道",
    romaji: "Tenryu Hamanako Tetsudo",
    summary_zh: "**天竜浜名湖鉄道は浜名湖を北側周遊する第三セクター鉄道**(浜松市~掛川市・67 km)。1935 年開業の国鉄二俣線が前身、駅舎の半数(36 駅中 17 駅)が国登録有形文化財という鉄道遺産。観光列車「TH9200 形(ナディア号)」で浜名湖+ 天竜川の景観を楽しめる。",
    content_md: "- 区間:浜松市東区(新所原)~掛川市(掛川駅)・67 km\n- 開業:1935 年(昭和10)国鉄二俣線として\n- 第三セクター化:1987(JR 民営化時)\n- 国登録有形文化財:36 駅中 17 駅(駅舎・プラットホーム・上家)\n- 観光列車:TH9200 形「ナディア号」(浜名湖周遊)・TH3000 形(通勤通学)\n- 沿線:浜名湖北岸 + 天竜川 + 天浜線温泉(西気賀・三ヶ日・浜松フルーツパーク・遠州森町)\n- 1 日乗車券:¥1750(全線フリー)\n- アクセス:JR 浜松駅 (新所原駅で接続)・掛川駅",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["rural_townscape", "industrial_heritage"],
    lat: 34.722,
    lon: 137.620,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.tenhama.co.jp/" },
    tags: ["shizuoka_observation_train", "tenhama", "1935", "registered_heritage_stations"],
    source: "manual",
  },
  {
    slug: "izukyu-resort-21",
    category: "entertainment",
    sub_type: "shizuoka_observation_train",
    title_zh: "伊豆急行リゾート 21(海眺座席+黒船仕様・伊豆東海岸観光列車)",
    title_ja: "伊豆急行リゾート 21",
    romaji: "Izukyu Resort 21",
    summary_zh: "**リゾート 21 は伊豆急行の観光特急車両**(1985 デビュー)。先頭車両「展望席」(運転席後ろから前方視界)+ 海側座席(全席海向き)で、伊豆東海岸の絶景(相模湾+伊豆諸島)を堪能。「黒船電車」「キンメ電車」等のラッピング車両でテーマ性も。",
    content_md: "- デビュー:1985 年(昭和60)伊豆急行\n- 区間:伊東駅~伊豆急下田駅(45 km)\n- 特徴:先頭展望席 + 全席海向き(東海岸右側座席・特に左側)\n- ラッピング車両:「黒船電車」(下田開国モチーフ)・「キンメ電車」(下田名物金目鯛)\n- 料金:乗車券のみ(特別料金不要)・1 日乗車券 ¥1900\n- 運行:伊豆急線各駅停車として 1 日 8 往復\n- アクセス:JR 伊東駅 で伊豆急に乗換",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["luxury_resort", "urban_central"],
    lat: 34.965,
    lon: 139.099,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.izukyu.co.jp/resort21/" },
    tags: ["shizuoka_observation_train", "izukyu", "resort_21", "1985"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase F — 花火大会(2 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "atami-kaijo-fireworks",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "熱海海上花火大会(年 12+ 回開催・春夏秋冬・サンビーチ前)",
    title_ja: "熱海海上花火大会",
    romaji: "Atami Kaijo Fireworks",
    summary_zh: "**熱海海上花火大会は年間 12+ 回開催される全国唯一級の花火大会**(熱海港・サンビーチ前)。1952 年開始、毎年 4-12 月にかけて月 1-3 回(夏は週 1 回)、約 5000 発の花火を 25 分間打上げる。熱海湾の三面山岳に囲まれた擂鉢地形で音響効果が高く、「鳴り花火」が湾全体に響き渡る。",
    content_md: "- 開始:1952 年(昭和27)熱海\n- 開催数:年 12-15 回(4-12 月)\n- 季節:春(5 月 GW)・夏(7-8 月)・秋(10-11 月)・冬(12 月)\n- 規模:約 5000 発・25 分間\n- 会場:熱海港 + サンビーチ前\n- 観賞:無料(海岸沿い・ホテル屋上)\n- アクセス:JR 熱海駅 徒歩 15 分(花火当日臨時バスあり)\n- 注意:夏 7-8 月は宿予約必須\n- 公式情報:熱海市観光協会",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "熱海市",
    lg_code: "22205",
    area_types: ["urban_central", "luxury_resort"],
    lat: 35.094,
    lon: 139.080,
    season_start: "2026-04-01",
    season_end: "2026-12-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.ataminews.gr.jp/event/22/" },
    tags: ["firework_festival", "atami", "kaijo_hanabi", "1952", "year_round"],
    source: "manual",
  },
  {
    slug: "shimizu-minato-fireworks",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "清水みなと祭り花火(7 月最終週末・約 1 万発・清水港)",
    title_ja: "清水みなと祭り花火大会",
    romaji: "Shimizu Minato Fireworks",
    summary_zh: "**清水みなと祭り花火は静岡市最大の花火大会**(7 月最終週末・清水港)。1947 年開始、戦災復興祭から発展、約 1 万発の花火 + 海上スターマインで全国 30 位以内の規模。清水港(エスパルスドリームプラザ前)から打上げ、富士山+海+花火の三位一体絶景。",
    content_md: "- 開始:1947 年(昭和22)清水\n- 開催:7 月最終週末(土日 2 日連続)\n- 規模:約 1 万発・90 分間\n- 会場:清水港(エスパルスドリームプラザ前 + 折戸湾)\n- 観賞:無料(海岸沿い)・有料席 ¥3000-5000\n- 同期祭:清水みなと祭り(踊りパレード・祭り屋台)\n- アクセス:JR 清水駅 から無料シャトル + 徒歩 15 分\n- 注意:夜空の混雑・帰路は 21 時以降",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["urban_central", "fishing_port"],
    lat: 35.013,
    lon: 138.499,
    season_start: "2026-07-31",
    season_end: "2026-08-02",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["firework_festival", "shimizu", "minato_matsuri", "1947"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase G — イルミネーション(1 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "tokinosumika-illumination",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "時之栖イルミネーション(御殿場・全国 5 大級・11-3 月・無料入場)",
    title_ja: "時之栖イルミネーション",
    romaji: "Toki no Sumika Illumination",
    summary_zh: "**時之栖イルミネーションは全国 5 大級の冬季イルミネーション**(御殿場時之栖内・1996 開始)。30 万 m² の敷地全体に 600 万球の LED、巨大ウォーターイルミネーション「光のトンネル」「ナイアガラの滝」等の大規模構造物。期間 11 月-3 月、入場無料(別途有料エリアあり)。",
    content_md: "- 開始:1996 年(平成8)御殿場時之栖\n- 規模:600 万球の LED・敷地 30 万 m² 全域\n- 主要構造物:光のトンネル(全長 100 m)・ナイアガラの滝・ウォーターイルミネーション\n- 期間:11 月初~3 月中旬\n- 入場料:無料(時之栖入園無料)\n- 営業時間:16:30-22:00(イルミ点灯)\n- 駐車場:無料(2000 台)\n- 隣接:時之栖ホテル群 + ベルナール温泉 + 御殿場高原ビール\n- アクセス:JR 御殿場駅 から無料シャトル 20 分・東名 御殿場 IC 車 8 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "御殿場市",
    lg_code: "22215",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 35.302,
    lon: 138.917,
    season_start: "2026-11-01",
    season_end: "2026-03-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.tokinosumika.com/illumi/" },
    tags: ["illumination", "tokinosumika", "gotemba", "1996", "national_5_largest"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase H — 海・サーフ(2 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "omaezaki-surfing",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "御前崎サーフィン(全国級ポイント・遠州灘・年間波あり)",
    title_ja: "御前崎サーフポイント",
    romaji: "Omaezaki Surfing",
    summary_zh: "**御前崎は遠州灘の全国級サーフポイント**(御前崎市)。遠州灘の南東風 + 太平洋からの大波で、年間通じて波あり。地元プロサーファー育成地として知られ、毎年プロ大会開催。御前崎灯台(1874 年完成・国登録文化財)と海蝕崖の絶景もセット。",
    content_md: "- 立地:御前崎市御前崎(遠州灘最東端)\n- 波質:全国級・年間波あり(遠州灘の卓越風)\n- レベル:中級~上級向け(初心者は近隣の白羽 or 浜岡)\n- プロ大会:JPSA(日本プロサーフィン連盟)主催大会開催地\n- 隣接:御前崎灯台(1874 完成・国登録文化財・海絶景)・なぶら市場(海鮮市場)\n- アクセス:JR 菊川駅 から バス 50 分・御前崎下車\n- 駐車場:無料(海岸沿い)\n- ベストシーズン:9-11 月(秋)・3-5 月(春)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "御前崎市",
    lg_code: "22223",
    area_types: ["rural_townscape", "fishing_port"],
    lat: 34.601,
    lon: 138.226,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["model_course", "omaezaki", "surfing", "enshu_nada"],
    source: "manual",
  },
  {
    slug: "shirahama-beach-shimoda",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "白浜大浜海水浴場(下田・伊豆 No.1 ビーチ・透明度 + 白砂)",
    title_ja: "白浜大浜海水浴場",
    romaji: "Shirahama Ohama Beach",
    summary_zh: "**白浜大浜は伊豆 No.1 のビーチ**(下田市・伊豆半島南東岸)。約 700 m の白砂海岸、透明度日本トップクラス、夏(7-8 月)は 30 万人の海水浴客で賑わう。白浜神社隣接、サーフィン+海水浴+ダイビング+岩礁探検の多目的活用。日本の渚 100 選。",
    content_md: "- 立地:下田市白浜(伊豆半島南東岸)\n- 規模:約 700 m の白砂海岸・水深浅\n- 透明度:伊豆半島 1 位(夏でも 5-10 m 視界)\n- 認定:日本の渚 100 選\n- アクティビティ:海水浴・サーフィン(波の質中級)・ダイビング・岩礁探検\n- 海水浴期間:7 月初~8 月末\n- 隣接:白浜神社(伊豆最古神社)\n- 駐車場:有料(¥1500/日・夏季)\n- アクセス:伊豆急 下田駅 から バス 13 分・白浜海岸下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "下田市",
    lg_code: "22219",
    area_types: ["fishing_port", "rural_townscape"],
    lat: 34.694,
    lon: 138.972,
    season_start: "2026-07-01",
    season_end: "2026-08-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["model_course", "shirahama", "shimoda", "izu_no1_beach", "100_beaches"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase I — 修善寺虹の郷(1 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shuzenji-niji-no-sato",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "修善寺虹の郷(花の郷+ミニチュア英国村+ローカル鉄道・1990 開園)",
    title_ja: "修善寺虹の郷",
    romaji: "Shuzenji Niji no Sato",
    summary_zh: "**修善寺虹の郷は花の郷+テーマパーク**(伊豆市・1990 開園)。約 50 万 m² に英国村・カナダ村(原寸大ミニチュア街並)+ ローカル鉄道(1/3 規模 SL)+ 桜・あじさい・バラ・もみじの四季の花の郷を併設。家族向け定番、修善寺温泉と組合せ 1 日コース。",
    content_md: "- 開園:1990 年(平成2)伊豆市修善寺\n- 規模:約 50 万 m²\n- 構成:英国村・カナダ村(原寸大ミニチュア街並)+ 日本庭園 + 花の郷\n- 季節花:桜(4 月)・あじさい(6 月)・バラ(5,10 月)・もみじ(11 月)\n- ローカル鉄道:1/3 スケール SL「ロムニー鉄道」(全長 700 m)\n- 入園料:¥1300\n- 営業:9:00-17:00(冬季 16:00)\n- 定休:火曜\n- アクセス:伊豆箱根 修善寺駅 から バス 20 分・虹の郷下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊豆市",
    lg_code: "22222",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 34.992,
    lon: 138.916,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["tue"],
    external_urls: { official: "https://www.nijinosato.com/" },
    tags: ["flower_field", "shuzenji", "niji_no_sato", "1990"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase J — 寸又峡(1 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "yumeno-tsuribashi-sumatakyo",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "夢の吊橋(寸又峡・コバルトブルー渓谷湖・恋愛のパワースポット)",
    title_ja: "夢の吊橋",
    romaji: "Yume no Tsuribashi",
    summary_zh: "**夢の吊橋は寸又峡のコバルトブルー渓谷湖を渡る吊橋**(川根本町・南アルプス麓)。長さ 90 m・水面 8 m の歩行者専用、湖の独特な青色は鉱物含有水の屈折で生まれる現象。「橋の真ん中で恋人の名前を呼ぶと結ばれる」という伝説で恋愛のパワースポット。寸又峡温泉から徒歩 30 分。",
    content_md: "- 立地:川根本町寸又峡(南アルプス麓・大井川上流)\n- 寸法:長さ 90 m・水面 8 m\n- コバルトブルー湖:鉱物含有水の屈折で青色\n- 由来:「橋の真ん中で恋人の名前を呼ぶと結ばれる」恋愛伝説\n- 入場料:無料\n- アクセス:寸又峡温泉から徒歩 30 分(山道)・大井川鐡道 千頭駅 から バス 40 分\n- 注意:渋滞時間に橋上人数制限あり(片側通行)・GW + 夏 + 紅葉時 60 分以上待ち\n- ベストシーズン:新緑(5 月)・紅葉(11 月中旬-下旬)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: "榛原郡",
    municipality_ja: "川根本町",
    lg_code: "22429",
    area_types: ["mountain_village", "rural_townscape"],
    lat: 35.155,
    lon: 138.122,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["model_course", "yume_no_tsuribashi", "sumatakyo", "cobalt_blue"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase K — その他名所(6 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "ekopa-stadium-iwata",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "エコパスタジアム(磐田・W 杯ラグビー 2019 会場・5 万人収容)",
    title_ja: "エコパスタジアム",
    romaji: "Ecopa Stadium",
    summary_zh: "**エコパスタジアムは静岡県最大級スタジアム**(磐田市・2001 完成・5 万人収容)。FIFA W 杯 2002・W 杯ラグビー 2019 会場、ジュビロ磐田ホームスタジアム。サッカー J 1 + ラグビー + 大型コンサート(嵐・ミスチル等)で年間多数のイベント開催、地元静岡の sports + entertainment hub。",
    content_md: "- 完成:2001 年(平成13)磐田\n- 収容:50889 人\n- 主催:静岡県\n- 国際大会:FIFA W 杯 2002(4 試合)・W 杯ラグビー 2019(4 試合)\n- ホーム:ジュビロ磐田(J リーグ)・ヤマハ発動機ジュビロ(ラグビー)\n- コンサート:大型アーティスト(嵐 2017・ミスチル 2018 等)\n- 入場料:イベント別\n- アクセス:JR 愛野駅 徒歩 15 分(イベント時臨時バス・新幹線 掛川駅 + 浜松駅 から無料シャトル)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "袋井市",
    lg_code: "22216",
    area_types: ["urban_central", "luxury_resort"],
    lat: 34.731,
    lon: 137.923,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.ecopa.jp/" },
    tags: ["sports_spectate", "ecopa", "iwata", "2001", "w_cup"],
    source: "manual",
  },
  {
    slug: "hatsushima-atami-pica",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "初島(熱海離島・PICA リゾート・所要 30 分高速船)",
    title_ja: "初島(はつしま)",
    romaji: "Hatsushima",
    summary_zh: "**初島は熱海港から高速船 30 分の離島**(伊豆諸島最北端・面積 0.4 km²)。PICA(株)が運営するリゾート施設「PICA 初島」(コテージ + アスレチック + ヤシの木のシエスタ)があり、本土近接でリゾート気分を 1 日体験。海水浴 + 釣り + アジアンガーデン R-Asia + 海鮮居酒屋。",
    content_md: "- 立地:熱海市初島(熱海港から南東 10 km)\n- 面積:0.4 km²(住人 200 名)\n- アクセス:熱海港から高速船 30 分(往復 ¥2800)\n- リゾート:PICA 初島(コテージ・アスレチック・シエスタ)\n- 主要施設:アジアンガーデン R-Asia + 海泉浴 SPA + 海鮮居酒屋\n- 海水浴:7-8 月初島海水浴場\n- 営業:通年(冬季は便数減)\n- アクセス:JR 熱海駅 → 熱海港 徒歩 15 分 → 高速船 30 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "熱海市",
    lg_code: "22205",
    area_types: ["luxury_resort", "fishing_port"],
    lat: 35.030,
    lon: 139.171,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.hatsushima.jp/" },
    tags: ["model_course", "hatsushima", "atami", "pica_resort"],
    source: "manual",
  },
  {
    slug: "ito-marina-town",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "伊東マリンタウン(2003 開業・港湾型ショッピング+海鮮+遊覧船)",
    title_ja: "伊東マリンタウン",
    romaji: "Ito Marine Town",
    summary_zh: "**伊東マリンタウンは伊東港の道の駅型観光施設**(2003 開業・道の駅伊東マリンタウン)。海鮮市場 + 海鮮レストラン + 土産物 + 遊覧船「リゾート 21」発着 + 足湯 + 観覧車を複合、伊東観光の 1 日 hub。富士山絶景の天然温泉「シーサイドスパ」も併設。",
    content_md: "- 開業:2003 年(平成15)伊東港\n- 構成:道の駅 + 海鮮市場 + レストラン + 土産物 + 観覧車 + 足湯 + 遊覧船発着\n- 観覧車:¥600(高さ 35 m・湾内一望)\n- 遊覧船「はるひら丸」:伊東湾遊覧 ¥1500(40 分)\n- 天然温泉:シーサイドスパ ¥1000(¥1500 タオル付)\n- 海鮮:伊豆名物の金目鯛・伊勢海老・サザエの食堂\n- 入場料:無料(各施設別途)\n- 営業:9:00-18:00\n- アクセス:JR 伊東駅 から路線バス 8 分・マリンタウン下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["urban_central", "fishing_port"],
    lat: 34.957,
    lon: 139.106,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://ito-marinetown.co.jp/" },
    tags: ["model_course", "ito_marine_town", "2003", "michinoeki"],
    source: "manual",
  },
  {
    slug: "numazu-goyotei-park",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "沼津御用邸記念公園(明治皇族別荘・1893 完成・国指定名勝)",
    title_ja: "沼津御用邸記念公園",
    romaji: "Numazu Goyotei Park",
    summary_zh: "**沼津御用邸記念公園は明治期皇族別荘**(沼津市・1893 完成・国指定名勝)。明治天皇 + 大正天皇 + 昭和天皇が静養に使用した皇室別荘、駿河湾沿い千本松原の中の数寄屋造り建築。1969 年皇室から県に下賜され公園化、当時の生活を保存展示。",
    content_md: "- 完成:1893 年(明治26)沼津\n- 利用:明治天皇(1893-1912)+ 大正天皇(1912-1926)+ 昭和天皇(1926-1969)の静養所\n- 公園化:1969 年(昭和44)県に下賜\n- 認定:国指定名勝(2010)\n- 立地:沼津市下香貫(駿河湾沿い千本松原内)\n- 主要建築:御用邸本館 + 別館 + 馬車道(数寄屋造り)\n- 入場料:¥410\n- 営業:9:00-16:30\n- 定休:火曜\n- 周辺:千本松原(松原 100 選)\n- アクセス:JR 沼津駅 から バス 15 分・御用邸前下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "沼津市",
    lg_code: "22203",
    area_types: ["luxury_resort", "historic_district"],
    lat: 35.080,
    lon: 138.852,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["tue"],
    external_urls: { official: "https://www.numazu-goyotei.com/" },
    tags: ["model_course", "numazu", "goyotei", "1893", "imperial_villa"],
    source: "manual",
  },
  {
    slug: "kawazu-nanadaru-7falls",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "河津七滝(伊豆天城・7 つの滝群・伊豆の踊子作中地)",
    title_ja: "河津七滝(かわづななだる)",
    romaji: "Kawazu Nanadaru",
    summary_zh: "**河津七滝は伊豆天城の 7 つの滝群**(賀茂郡河津町)。釜滝・エビ滝・蛇滝・初景滝・カニ滝・出合滝・大滝の 7 つが約 1 km の渓谷に連なる。川端康成『伊豆の踊子』中で主人公一行が天城越え時に通った道、初景滝そばに「踊子像」設置。遊歩道整備済、所要 40 分。",
    content_md: "- 立地:賀茂郡河津町梨本(天城峠南麓・河津川源流)\n- 滝群:7 滝(釜滝・エビ滝・蛇滝・初景滝・カニ滝・出合滝・大滝)\n- 全長:遊歩道 約 1 km・所要 40 分\n- 文学:川端康成『伊豆の踊子』作中の道(主人公が踊子と歩いた天城)\n- モニュメント:初景滝そばに「踊子像」(主人公 + 踊子の青銅像)\n- 入場料:無料\n- アクセス:伊豆急 河津駅 から バス 40 分・水生地下下車\n- ベストシーズン:新緑 5 月・紅葉 11 月",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: "賀茂郡",
    municipality_ja: "河津町",
    lg_code: "22302",
    area_types: ["nature_view", "mountain_village"],
    lat: 34.808,
    lon: 138.940,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["model_course", "kawazu", "nanadaru", "izu_no_odoriko"],
    source: "manual",
  },
  {
    slug: "joren-no-taki-amagi",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "浄蓮の滝(伊豆天城・落差 25 m・名瀑 100 選・天然わさび田併設)",
    title_ja: "浄蓮の滝",
    romaji: "Joren no Taki",
    summary_zh: "**浄蓮の滝は伊豆天城を代表する名瀑**(伊豆市湯ヶ島)。落差 25 m・幅 7 m、玄武岩の柱状節理を流れ落ちる青く澄んだ滝水。日本の滝百選、石川さゆり『天城越え』歌詞「あの淨蓮の滝」の浄蓮の滝。隣接の天然わさび田(伊豆 No.1 規模)もあり、わさびソフトクリーム名物。",
    content_md: "- 立地:伊豆市湯ヶ島(天城峠北麓)\n- 規模:落差 25 m・幅 7 m\n- 認定:日本の滝百選\n- 構造:玄武岩柱状節理を流下\n- 隣接:天然わさび田(伊豆最大規模・道路沿い)\n- 名物:わさびソフトクリーム(¥400)・わさび漬\n- 文化:石川さゆり『天城越え』歌詞「あの淨蓮の滝」\n- 入場料:無料(駐車場 ¥500)\n- アクセス:伊豆箱根 修善寺駅 から バス 30 分・浄蓮の滝下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊豆市",
    lg_code: "22222",
    area_types: ["nature_view", "mountain_village"],
    lat: 34.866,
    lon: 138.917,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["model_course", "joren_taki", "amagi", "100_falls"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R2 補完(2026-04-29)— 富士サファリ + 熱海梅園 +2
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "fuji-safari-park-susono-1980",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "富士サファリパーク(裾野市・1980 開園・国内最大級サファリ動物園)",
    title_ja: "富士サファリパーク",
    romaji: "Fuji Safari Park",
    summary_zh: "**富士サファリパークは国内最大級のサファリパーク**(裾野市・1980 開園)。富士山南麓 74 万 m² の広大な敷地に 70 種 1000 頭の野生動物(ライオン・キリン・ゾウ・チーター・ホワイトタイガー等)を放し飼い、自家用車 + サファリバス + ナイトサファリ + ジャングルバスで観察可能。富士山絶景立地。",
    content_md: "- 開園:1980 年(昭和55)裾野\n- 立地:裾野市須山(富士山南麓・標高 850m)\n- 規模:74 万 m²\n- 動物:70 種・1000 頭\n- 観察方法:\n  - 自家用車(マイカー)入場\n  - ジャングルバス(¥1500-・餌やり可)\n  - スーパージャングルバス(¥3500・特別ガイド)\n  - ナイトサファリ(夏季のみ)\n- ふれあいゾーン:カピバラ・羊・モルモット\n- 入園料:¥3200・小人 ¥2000・60+ 1900\n- 営業:9:00-15:30(最終入園)\n- 定休:無休\n- アクセス:JR 御殿場駅 から バス 35 分・東名 御殿場 IC 車 35 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "裾野市",
    lg_code: "22220",
    area_types: ["luxury_resort", "mountain_village"],
    lat: 35.279,
    lon: 138.840,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.fujisafari.co.jp/" },
    tags: ["theme_park", "fuji_safari", "susono", "1980", "japan_largest_safari"],
    source: "manual",
  },
  {
    slug: "atami-baien-1886",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "熱海梅園(1886 開園・「日本一早咲き」+「日本一遅紅葉」のダブル名所)",
    title_ja: "熱海梅園",
    romaji: "Atami Baien",
    summary_zh: "**熱海梅園は明治 19 年/1886 開園の梅の名所**。「日本一早咲き梅」(11 月下旬から早咲き)+「日本一遅紅葉」(12 月初旬まで紅葉)で年間 2 シーズン来客が殺到する珍しい園。59 品種 469 本の梅 + 446 本のもみじ + 60 本の桜。冬の梅まつり(1-3 月)+ 紅葉まつり(11-12 月)の 2 大イベント。",
    content_md: "- 開園:1886 年(明治19)\n- 規模:約 4 万 m²\n- 梅:59 品種・469 本(日本一早咲き 11 月下旬-3 月初旬・日本一遅咲きでも開花期の長さで知られる)\n- もみじ:446 本(日本一遅紅葉・12 月初-中旬)\n- 桜:60 本(2-3 月)\n- 梅まつり:1 月中-3 月初・期間中 ¥300\n- 紅葉まつり:11 月中-12 月中・期間中 ¥300\n- 通常期:無料\n- 営業:8:30-16:00\n- 立地:熱海市梅園町\n- アクセス:JR 来宮駅 徒歩 5 分・JR 熱海駅 から バス 10 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "熱海市",
    lg_code: "22205",
    area_types: ["urban_central", "luxury_resort"],
    lat: 35.107,
    lon: 139.073,
    season_start: "2026-01-15",
    season_end: "2026-03-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.ataminews.gr.jp/spot/108/" },
    tags: ["flower_field", "atami_baien", "1886", "earliest_plum_japan", "latest_momiji_japan"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R3 補完(2026-04-29)— 浜松フラワーパーク + 掛川大祭 +2
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "hamamatsu-flower-park-1970",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "浜松フラワーパーク(1970 開園・浜名湖畔・約 30 万 m²・四季の花)",
    title_ja: "浜松フラワーパーク",
    romaji: "Hamamatsu Flower Park",
    summary_zh: "**浜松フラワーパークは浜名湖畔の大型花植物公園**(浜松市西区・1970 開園・約 30 万 m²)。世界の植物 3000 種・60 種 30 万本の花木を擁する、関西/中部最大級の花テーマパーク。桜(3-4 月・1300 本)・チューリップ(4 月・43 万球)・バラ(5,10 月)・ハナショウブ(6 月)・睡蓮(夏)・モミジ(11 月)の四季演出。",
    content_md: "- 開園:1970 年(昭和45)浜松\n- 規模:約 30 万 m²\n- 植物:3000 種・60 種 30 万本\n- 季節花:\n  - 桜(3 月下-4 月上・1300 本)\n  - チューリップ(4 月・43 万球・国内最大級)\n  - バラ(5 月・10 月・1300 株)\n  - ハナショウブ(6 月)\n  - 睡蓮(7-8 月)\n  - モミジ(11 月)\n- 入園料:期間別 ¥600-1000(春 + 秋ピーク高い)\n- 営業:9:00-17:00(冬季 16:30)\n- 定休:無休\n- 隣接:浜名湖パルパル(舘山寺温泉)\n- アクセス:JR 浜松駅 から路線バス 50 分・フラワーパーク下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 34.748,
    lon: 137.624,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["flower_field", "hamamatsu_flower_park", "1970", "300000sqm", "tulip_japan_largest"],
    source: "manual",
  },
  {
    slug: "kakegawa-sai-festival-3year",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "掛川大祭(3 年に 1 度・遠州三大祭・1814 創始・10 月初旬・40 余町合同祭)",
    title_ja: "掛川大祭",
    romaji: "Kakegawa Sai Festival",
    summary_zh: "**掛川大祭は遠州地方最大級の祭礼**(3 年に 1 度・10 月初旬・1814 文化11 創始)。掛川市内 40+ 町が大屋台(三層構造・各町独自の彫刻)を引き回し、市内中心部を巡行。普段使われる「小祭(毎年)」と「大祭(3 年に 1 度・大屋台が出る)」の 2 段階、観光客は大祭年(2026 開催年)を狙うべき。",
    content_md: "- 開催:3 年に 1 度(2026・2029・2032 ...)10 月第 1 週末\n- 創始:1814 年(文化11)\n- 系譜:遠州三大祭(掛川 + 浜松まつり + 三熊野神社大祭)\n- 主体:掛川市内 40+ 町(各町が大屋台を所有・伝統継承)\n- 大屋台:三層構造・各町独自の精緻な彫刻・年代物\n- 巡行ルート:掛川駅周辺~掛川城下~祭礼会場 約 5 km\n- 動員:3 日間で 30 万人超\n- 入場料:無料\n- アクセス:JR 掛川駅 徒歩 5-15 分(各祭礼会場)\n- 注意:2026 大祭年は宿泊予約必須(3 ヶ月前)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "掛川市",
    lg_code: "22213",
    area_types: ["urban_central", "historic_district"],
    lat: 34.778,
    lon: 137.998,
    season_start: "2026-10-02",
    season_end: "2026-10-04",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["firework_festival", "kakegawa_sai", "enshu_3_festivals", "1814", "triennial"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R4 補完(2026-04-29)— 富士川楽座 + 浜名湖ガーデンパーク +2
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "fujikawa-rakuza-1996",
    category: "entertainment",
    sub_type: "shizuoka_fujisan_view",
    title_zh: "富士川楽座(1996 開業・道の駅+科学館+富士山絶景・東名 富士川 SA 連結)",
    title_ja: "富士川楽座",
    romaji: "Fujikawa Rakuza",
    summary_zh: "**富士川楽座は東名 富士川 SA 連結の複合観光施設**(富士市・1996 開業)。道の駅+ 科学館「ディスカバリーパーク」+ プラネタリウム+ 大観覧車「Fujisky View」(高さ 60 m・無料)+ 富士山土産・レストラン。富士山絶景の東名サービスエリアとしても国内 5 大の人気で、夜の観覧車から富士山シルエットが圧巻。",
    content_md: "- 開業:1996 年(平成8)富士市\n- 構成:道の駅 + ディスカバリーパーク(科学館)+ プラネタリウム + 大観覧車「Fujisky View」+ 富士山土産\n- 大観覧車:高さ 60 m・無料(¥600 で乗れる場合も時期で変動)\n- 富士山ビュー:絶景・写真愛好家集合\n- 東名連結:富士川 SA(下り線)+ 富士川楽座 で同一施設化\n- 一般道アクセス:可能(国道 1 号・富士市)\n- 営業:9:00-21:00\n- 定休:無休\n- 入場料:無料(科学館 ¥630・プラネタリウム ¥630・¥1100 セット)\n- アクセス:JR 富士川駅 徒歩 15 分・東名 富士川 SA 直結",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "富士市",
    lg_code: "22210",
    area_types: ["luxury_resort", "urban_central"],
    lat: 35.158,
    lon: 138.642,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.fujikawarakuza.co.jp/" },
    tags: ["shizuoka_fujisan_view", "fujikawa_rakuza", "1996", "michinoeki_sa_combo"],
    source: "manual",
  },
  {
    slug: "hamanako-garden-park-2004",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "浜名湖ガーデンパーク(2004 浜名湖花博跡地・56 ha 無料公園・四季の花)",
    title_ja: "浜名湖ガーデンパーク",
    romaji: "Hamanako Garden Park",
    summary_zh: "**浜名湖ガーデンパークは 2004 年浜名湖花博跡地の大規模庭園公園**(浜松市西区・56 ha)。花博終了後 2005 年から無料一般開放、現在も四季の花(チューリップ・バラ・コスモス・キンモクセイ)+ 浜名湖一望の展望デッキ+ 国際庭園(各国の名園再現)を擁する、入場無料で楽しめる大型公園の代表。",
    content_md: "- 開園:2005 年(平成17)花博跡地から一般公開\n- 前史:2004 浜名湖花博(124 日間で 545 万人来場)\n- 規模:56 ha(東京ドーム 12 個分)\n- 構成:国際庭園(各国の名園再現)+ 花の美術館 + 体験学習花広場 + 浜名湖展望デッキ\n- 季節花:チューリップ(4 月)・バラ(5,10 月)・ヒマワリ(8 月)・コスモス(10 月)\n- 入場料:**無料**\n- 営業:8:30-17:00(冬季 16:30)\n- 定休:無休\n- 駐車場:無料 約 1500 台\n- 隣接:浜松フラワーパーク(車 10 分)・浜名湖パルパル(車 15 分)\n- アクセス:JR 浜松駅 から路線バス 50 分・舘山寺方面・ガーデンパーク下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 34.745,
    lon: 137.605,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.hamanako-gardenpark.jp/" },
    tags: ["flower_field", "hamanako_garden", "2005", "free_entry", "56ha"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R5 補完(2026-04-29)— 修善寺竹林夜 + ゆるキャン朝霧 + 浜松動物園 + 三島スカイウォークジップ +4
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shuzenji-takebayashi-night",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "修善寺 竹林の小径(夜ライトアップ・修善寺温泉中心地・写真スポット)",
    title_ja: "修善寺 竹林の小径",
    romaji: "Shuzenji Takebayashi",
    summary_zh: "**竹林の小径は修善寺温泉のシンボル散策路**(伊豆市修善寺・桂川沿い)。約 270 m の竹林トンネル、夜にライトアップ(年中無料)で幻想的な竹影の小径に。隣接の独鈷の湯(伊豆最古の湯・1163 弘法大師伝説)+ 修禅寺と組合せ、修善寺温泉観光の必見スポット。",
    content_md: "- 立地:伊豆市修善寺(桂川沿い・修禅寺近く)\n- 規模:約 270 m の竹林散策路\n- 夜ライトアップ:年中・日没-22:00(無料)\n- 隣接観光地:独鈷の湯(伊豆最古湯・1163 弘法大師伝承)・修禅寺・とっこ大師像・指月殿\n- ベストシーズン:年中(竹は常緑)・特に新緑(5 月)・紅葉(11 月)\n- 撮影スポット:小径の中央 + 桂川越しの竹林\n- アクセス:伊豆箱根 修善寺駅 から バス 8 分・修善寺温泉口下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊豆市",
    lg_code: "22222",
    area_types: ["onsen_town", "historic_district"],
    lat: 34.971,
    lon: 138.926,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shizuoka_nature_spot", "shuzenji_takebayashi", "night_light_up"],
    source: "manual",
  },
  {
    slug: "yurucan-asagiri-fujinomiya",
    category: "entertainment",
    sub_type: "shizuoka_fujisan_view",
    title_zh: "ゆるキャン△ 聖地巡禮(朝霧高原・富士宮・あfろ漫画原作・キャンプ場群)",
    title_ja: "ゆるキャン△ 朝霧高原 聖地",
    romaji: "Yuru Camp Asagiri",
    summary_zh: "**ゆるキャン△聖地は朝霧高原・富士宮市の各キャンプ場**。あfろ作の漫画(2015-)+ アニメ(2018-)で全国級の人気を博した、女子高生キャンプ漫画の主要舞台。富士山絶景の朝霧高原 + ふもとっぱらキャンプ場 + 田貫湖 + 白糸の滝周辺の聖地スポットが点在、若年層キャンパーの巡礼地に。",
    content_md: "- 原作:あfろ『ゆるキャン△』(2015-・芳文社)\n- アニメ:第 1 期 2018・第 2 期 2021・第 3 期 2024\n- 主要聖地スポット:\n  - 朝霧高原(富士宮市・原作主舞台・富士山絶景キャンプ場群)\n  - ふもとっぱらキャンプ場(富士宮市朝霧・原作頻出)\n  - 田貫湖キャンプ場(富士宮市・湖畔)\n  - 白糸の滝(原作 4 巻)\n  - 富士川楽座(原作 5 巻)\n- 富士宮市側の関連スポット:富士宮市役所 + 道の駅朝霧高原 + 富士本宮浅間大社\n- 連動商品:富士宮市内のコラボ土産・うなぎパイ等\n- アクセス:JR 富士宮駅 から路線バス + 車・キャンプ場アクセスは車推奨",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "富士宮市",
    lg_code: "22207",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 35.349,
    lon: 138.575,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["shizuoka_fujisan_view", "yurucan", "asagiri", "anime_pilgrimage"],
    source: "manual",
  },
  {
    slug: "hamamatsu-zoological-park-1950",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "浜松市動物園(舘山寺・1950 開園・浜名湖畔・約 100 種・浜松フラワーパーク隣接)",
    title_ja: "浜松市動物園",
    romaji: "Hamamatsu Zoological Park",
    summary_zh: "**浜松市動物園は舘山寺地区の動物園**(浜松市西区舘山寺町・1950 開園)。浜名湖畔の高台に約 100 種 400 頭の動物を展示、ゴールデンライオンタマリン(国内 4 頭中 2 頭・絶滅危惧種)等の珍獣で全国動物園マニアにも知られる。隣接の浜松フラワーパーク + 浜名湖パルパル と合わせて 1 日コース。",
    content_md: "- 開園:1950 年(昭和25)浜松\n- 立地:浜松市西区舘山寺町(浜名湖畔・大草山中腹)\n- 規模:13 ha\n- 動物:約 100 種 400 頭\n- 看板:ゴールデンライオンタマリン(絶滅危惧種・全国 4 頭中 2 頭・絶滅回避飼育プログラム参加)・ジャイアントパンダ過去飼育(1986-1990)・ホッキョクグマ\n- 入園料:¥600(子供 ¥150)\n- 営業:9:00-16:30\n- 定休:12 月 29-31 日\n- 隣接:浜松フラワーパーク(徒歩 5 分)・舘山寺ロープウェイ(徒歩 8 分)\n- アクセス:JR 浜松駅 から路線バス 50 分・舘山寺温泉下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 34.751,
    lon: 137.625,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.hamazoo.net/" },
    tags: ["aquarium_zoo", "hamamatsu_zoo", "1950", "kanzanji"],
    source: "manual",
  },
  {
    slug: "mishima-skywalk-zip-line-2017",
    category: "entertainment",
    sub_type: "shizuoka_fujisan_view",
    title_zh: "三島スカイウォーク ジップライン(2017 開業・560m + 250m 2 種・全国級空中アスレチック)",
    title_ja: "三島スカイウォーク ジップライン",
    romaji: "Mishima Skywalk Zipline",
    summary_zh: "**三島スカイウォーク ジップラインは全国級の空中アスレチック**(三島市笹原・2017 開業)。日本最長歩行者専用吊橋(400 m)に隣接して、ロングジップ「フォレストアドベンチャー三島」(560 m + 250 m の 2 種)を併設。富士山+駿河湾を空中から望む絶景体験で、家族・カップル・若年層に人気。",
    content_md: "- 開業:2017 年(平成29)三島\n- 立地:三島スカイウォーク隣接(三島市笹原)\n- ジップライン:\n  - ロング(560 m・最長)・¥1700\n  - ショート(250 m)・¥1100\n  - セット(両方)¥2500\n- 富士山絶景:空中から望む(晴天時)\n- 体重制限:25-130 kg\n- 営業:9:00-17:00\n- 注意:強風時運休\n- 三島スカイウォーク 入場料 別途 ¥1100\n- アクセス:JR 三島駅 から バス 25 分・スカイウォーク下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "三島市",
    lg_code: "22206",
    area_types: ["luxury_resort", "nature_view"],
    lat: 35.092,
    lon: 138.876,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://mishima-skywalk.jp/zipline/" },
    tags: ["shizuoka_fujisan_view", "skywalk_zipline", "2017", "560m"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R6 補完(2026-04-29)— 大井川川下り + 御前崎海浜公園 +2
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "oigawa-river-rapids-shimada",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "大井川川下り(島田・大井川渓谷ラフティング・SL観光列車と組合せ)",
    title_ja: "大井川川下り",
    romaji: "Oigawa River Rapids",
    summary_zh: "**大井川川下りは大井川渓谷のラフティング体験**(島田市~川根本町)。大井川鐡道 SL「かわね路」と組合せて、SL+ ラフティング+ 寸又峡夢の吊橋 の三点セット 1 日コースが定番。コースは初心者向け(2 時間 ¥6500)~ 上級者向け(3 時間 ¥9500)、3-11 月の温暖期営業。",
    content_md: "- 区間:島田市~川根本町(大井川中流~上流)\n- 営業期間:3 月-11 月(冬季水温低くて休業)\n- 主要業者:大井川川下りビックスマイル + 大井川ラフティング\n- コース:\n  - ファミリーコース(2 時間・¥6500・小学生 OK)\n  - スタンダードコース(3 時間・¥9500・中学生 OK)\n  - エキスパートコース(4 時間・¥12000・経験者向)\n- 装備:ライフジャケット + ヘルメット + ウェットスーツ レンタル料込\n- 組合せ推奨:朝 SL かわね路 → 昼 ラフティング → 夕 寸又峡夢の吊橋\n- アクセス:大井川鐡道 千頭駅 + 川根温泉笹間渡駅 から各業者送迎",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "島田市",
    lg_code: "22209",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 35.000,
    lon: 138.155,
    season_start: "2026-03-15",
    season_end: "2026-11-15",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["shizuoka_nature_spot", "oigawa_rapids", "rafting", "sl_combo"],
    source: "manual",
  },
  {
    slug: "omaezaki-marine-park",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "御前崎海浜公園(御前崎灯台麓・遠州灘景観・サーフポイント+海水浴+キャンプ)",
    title_ja: "御前崎海浜公園",
    romaji: "Omaezaki Marine Park",
    summary_zh: "**御前崎海浜公園は遠州灘最東端の総合海浜公園**(御前崎市)。御前崎灯台(1874・国登録文化財)の麓に位置、サーフポイント(全国級)+ 海水浴場(夏)+ キャンプ場+ なぶら市場(海鮮食堂)+ 御前崎ロングビーチ を擁する複合公園。日の出+夕陽+ 灯台 の絶景写真スポット。",
    content_md: "- 立地:御前崎市御前崎(遠州灘最東端の岬)\n- 構成:サーフポイント + 海水浴場(7-8 月)+ キャンプ場 + なぶら市場 + 御前崎ロングビーチ\n- 隣接:御前崎灯台(国登録文化財・徒歩 5 分)\n- 海水浴期間:7 月初~8 月末\n- サーフィン:全国級・年間波あり(JPSA 大会開催地)\n- なぶら市場:海鮮食堂 + 土産物・地元魚種(キンメダイ・カツオ等)\n- 入場料:無料(駐車場 ¥500)\n- アクセス:JR 菊川駅 から バス 50 分・御前崎下車",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "御前崎市",
    lg_code: "22223",
    area_types: ["fishing_port", "rural_townscape"],
    lat: 34.601,
    lon: 138.226,
    season_start: "2026-07-01",
    season_end: "2026-08-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shizuoka_nature_spot", "omaezaki", "marine_park", "lighthouse_combo"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[shizuoka-entertainment] 尚無條目");
    return;
  }
  console.log(`[shizuoka-entertainment] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(28)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch, { onConflict: "slug" });
    if (error) {
      console.error("[shizuoka-entertainment] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[shizuoka-entertainment] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[shizuoka-entertainment] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
