// Seed 広島県 R2 補完(20 筆 / Sprint 32.x)
//
// 食 +3 / 住 +3 / 衣 +2 / 育 +5 / 楽 +4 / 行 +3 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: string;
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "chugoku";
  prefecture_ja: "広島県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // 食 R2 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kure-kaigun-curry",
    category: "food",
    sub_type: "local_specialty",
    title_zh: "呉海軍カレー(呉市・1908 海軍カレー由来・市内 30+ 軒・大和ミュージアム R1 育隣・観光名物)",
    title_ja: "呉海軍カレー",
    romaji: "Kure Kaigun Curry",
    summary_zh: "**呉海軍カレーは旧海軍由来の郷土カレー**(呉市・1908 海軍料理として確立)。**呉鎮守府(海軍工廠)の艦船食料に毎週金曜カレー** が定着、戦後も呉市民食として継続。**市内 30+ 軒の認定店** がオリジナルレシピ提供、R1 育既出 大和ミュージアム+ 旧海軍兵学校 観光と組合わせ。",
    content_md: "- 由来:1908 年(明治 41)・旧海軍料理として確立\n- 立地:呉市内 30+ 軒の認定店\n- 主要店:呉海軍カレーフェスタ参加店+ 共楽館+ ハイカラ食堂\n- 価格目安:¥1000-2000\n- 営業:店舗による(11:00-21:00 が標準)\n- 隣接観光:R1 育 大和ミュージアム+ 旧海軍兵学校\n- アクセス:JR 呉駅 徒歩 5-15 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "呉市",
    lg_code: "34202",
    area_types: ["restaurant_traditional"],
    lat: 34.2453,
    lon: 132.5664,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["local_specialty", "kure_kaigun_curry", "1908_origin", "30_certified", "yamato_museum_neighbor"],
    source: "manual",
  },
  {
    slug: "setoda-lemon-cake",
    category: "food",
    sub_type: "hiroshima_meika",
    title_zh: "瀬戸田レモンケーキ(尾道市瀬戸田町・しまなみ海道銘菓・島の駅瀬戸田+ 平山郁夫美術館 隣)",
    title_ja: "瀬戸田レモンケーキ",
    romaji: "Setoda Lemon Cake",
    summary_zh: "**瀬戸田レモンケーキはしまなみ海道銘菓**(尾道市瀬戸田町)。R1 食既出 setoda-lemon-overview(全国 1 位レモン)を加工した洋菓子、**レモン皮+ レモン果汁+ レモンチョコレート コーティング**。島の駅瀬戸田+ 平山郁夫美術館(R1 楽 ikuchi)隣で販売、しまなみ サイクリスト+ 観光客のお土産代表。",
    content_md: "- 産地:尾道市瀬戸田町(R1 食 setoda-lemon-overview の加工品)\n- 主要販売:島の駅瀬戸田+ 平山郁夫美術館(R1 楽)隣+ 尾道市内土産店\n- 価格目安:1 個 ¥250-350・10 個入箱 ¥2200\n- 主要メーカー:島ごころ+ 瀬戸田町農業協同組合\n- 営業:店舗による(9:00-18:00)\n- アクセス:しまなみ海道 生口島 + 尾道市内",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["restaurant_traditional"],
    lat: 34.3050,
    lon: 133.0833,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_meika", "setoda_lemon_cake", "shimanami", "ikuchi_island", "lemon_chocolate"],
    source: "manual",
  },
  {
    slug: "miyajima-kakimeshi-cuisine",
    category: "food",
    sub_type: "hiroshima_kaki",
    title_zh: "宮島牡蠣めし(廿日市市宮島・牡蠣炊き込みご飯郷土料理・R1 食既出 牡蠣屋+ かなわ等で提供)",
    title_ja: "宮島牡蠣めし",
    romaji: "Miyajima Kakimeshi",
    summary_zh: "**宮島牡蠣めしは郷土料理炊き込みご飯**(廿日市市宮島町)。R1 食既出 hiroshima-kaki-overview の関連料理、**生牡蠣+ ご飯+ 牡蠣スープで炊き込む** 宮島伝統食。R1 食既出 牡蠣屋(R1 miyajima-kakiya-1948)+ かなわ(R1 kanawa-1959)等で提供、観光客の食事 angle。",
    content_md: "- 立地:廿日市市宮島町(R1 食 hiroshima-kaki 関連)\n- 提供店:R1 食 牡蠣屋(1948)+ かなわ(1959)+ 表参道商店街(R1 衣)各店\n- 食べ方:炊き込みご飯+ 牡蠣スープ+ 海苔+ 三つ葉\n- 価格目安:¥1200-2500(セット ¥2500-4500)\n- 旬:11-3 月(R1 食 hiroshima-kaki と同じ)\n- アクセス:宮島フェリー 宮島桟橋 徒歩 5-10 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "廿日市市",
    lg_code: "34213",
    area_types: ["restaurant_traditional"],
    lat: 34.2961,
    lon: 132.3194,
    season_start: "2026-11-01",
    season_end: "2027-03-31",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_kaki", "miyajima_kakimeshi", "rice_bowl", "winter_specialty", "kakiya_kanawa"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 住 R2 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "onomichi-u2-2014",
    category: "lodging",
    sub_type: "hiroshima_setouchi_classical",
    title_zh: "ONOMICHI U2(尾道市・2014 開業・廃倉庫リノベ・サイクリスト特化宿+ レストラン・しまなみ起点)",
    title_ja: "ONOMICHI U2",
    romaji: "Onomichi U2",
    summary_zh: "**ONOMICHI U2 はサイクリスト特化型ホテル**(尾道市・2014 開業)。**1943 年建造の海運倉庫を世界初の「サイクリスト向けホテル」にリノベ**、客室内に自転車持ち込み可+ 24 時間メンテ工房+ レストラン+ ベーカリー+ 直営ジャイアントストア併設。R1 楽 しまなみ サイクリングの起点宿として有名、料金 ¥18000-30000。",
    content_md: "- 開業:2014 年(平成 26)\n- 立地:尾道市西御所町(尾道港畔)\n- 由来:1943 年海運倉庫を世界初サイクリストホテルにリノベ\n- 室数:28 室(客室内に自転車持ち込み可)\n- 設備:24 時間メンテ工房+ ジャイアントストア+ レストラン+ ベーカリー\n- 料金目安:¥18000-30000/泊\n- 隣接:R1 楽 shimanami-cycling 起点+ JR 尾道駅(徒歩 8 分)\n- アクセス:JR 尾道駅 徒歩 8 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["urban_central"],
    lat: 34.4078,
    lon: 133.1958,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.onomichi-u2.com/" },
    tags: ["hiroshima_setouchi_classical", "onomichi_u2", "2014", "world_first_cyclist", "1943_warehouse_reno"],
    source: "manual",
  },
  {
    slug: "tomonoura-iroha-2008",
    category: "lodging",
    sub_type: "hiroshima_setouchi_classical",
    title_zh: "御舟宿いろは(福山市鞆町・2008 開業・古民家リノベ・宮崎駿監修・崖の上のポニョ関連)",
    title_ja: "御舟宿いろは",
    romaji: "Mifuna Yado Iroha",
    summary_zh: "**御舟宿いろはは古民家リノベ宿**(福山市鞆町・2008 開業)。**江戸期商家を宮崎駿(崖の上のポニョ監督)が直接監修してリノベ**、6 室のみの隠れ家宿。R1 楽既出 鞆の浦観光と一体、ジブリファン+ 文学愛好家に人気、料金 ¥30000-60000。",
    content_md: "- 開業:2008 年(平成 20)\n- 立地:福山市鞆町(R1 鞆の浦伝統建造物群保存地区内)\n- 監修:宮崎駿(崖の上のポニョ監督)\n- 由来:江戸期商家を古民家リノベ\n- 室数:6 室(隠れ家)\n- 料金目安:¥30000-60000/泊\n- 隣接:R1 育 鞆常夜灯 1859+ R1 食 保命酒 1659+ R1 衣 鞆商店街\n- アクセス:JR 福山駅 から バス 30 分・鞆の浦下車",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "福山市",
    lg_code: "34207",
    area_types: ["historic_district"],
    lat: 34.3811,
    lon: 133.3839,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_setouchi_classical", "mifuna_iroha", "2008", "miyazaki_supervised", "ponyo_related"],
    source: "manual",
  },
  {
    slug: "saijo-station-classical-stay",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "西条酒蔵通り 古民家泊(東広島市西条・酒蔵通りの古民家リノベ宿・酒祭り 10 月最寄)",
    title_ja: "西条酒蔵通り古民家泊",
    romaji: "Saijo Sakegura Stay",
    summary_zh: "**西条酒蔵通り古民家泊は近年整備された古民家リノベ宿群**(東広島市西条・R1 食 saijo-shuzo-michi-7 沿い)。**酒蔵通りの江戸-明治期商家** をリノベ、地酒+ 西条料理+ 酒蔵見学のセット体験。**酒祭り(10 月)時は最寄宿** として満員必至、料金 ¥20000-35000(2 食付・地酒コース)。",
    content_md: "- 立地:東広島市西条本町(R1 食 saijo-shuzo-michi 沿い)\n- 由来:江戸-明治期商家を古民家リノベ\n- 主要宿:酒蔵通り古民家+ 西条オリエンタル等\n- 料金目安:¥20000-35000/泊(2 食付・地酒コース)\n- 酒祭り(10/10-11):3 ヶ月前予約必須\n- 隣接:R1 食 西条 7 蔵+ R1 食 賀茂鶴 1873+ R1 衣 saijo-sake-souvenir\n- アクセス:JR 山陽本線 西条駅 徒歩 5-10 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "東広島市",
    lg_code: "34212",
    area_types: ["onsen_field", "historic_district"],
    lat: 34.4267,
    lon: 132.7456,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["onsen_ryokan", "saijo_classical_stay", "kominka_reno", "october_full", "sake_brewery_neighbor"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 衣 R2 (2)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kumano-fude-takemoto-1746",
    category: "fashion",
    sub_type: "hiroshima_kumanofude",
    title_zh: "竹本義方堂(熊野町・1746 創業・279 年・熊野最古級筆店・書道筆+ 化粧筆・国宝級老舗)",
    title_ja: "竹本義方堂",
    romaji: "Takemoto Gihoudou",
    summary_zh: "**竹本義方堂は熊野筆最古級の老舗**(安芸郡熊野町・1746 創業・279 年)。R1 衣既出 hakuhodo-fude-1959(化粧筆世界 OEM)とは別系統、**江戸期からの伝統書道筆+ 仏画筆+ 化粧筆** を継承する文化財級老舗。地元客+ 書道家中心、観光客向けの体験+ 直販あり。",
    content_md: "- 創業:1746 年(延享 3)・279 年\n- 立地:安芸郡熊野町(R1 衣 kumano-fude 産地)\n- 主要商品:書道筆+ 仏画筆+ 化粧筆+ 工芸筆\n- 価格帯:¥3000-200000+(高級書道筆)\n- 比較:hakuhodo-fude(R1・化粧筆世界 OEM)+ takemoto(R2・書道筆伝統)\n- 営業:9:00-17:00(日曜定休)\n- アクセス:JR 海田市駅 から バス 25 分・熊野下車",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: "安芸郡",
    municipality_ja: "熊野町",
    lg_code: "34307",
    area_types: ["historic_district"],
    lat: 34.3361,
    lon: 132.5689,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: null,
    closed_days: ["sun"],
    external_urls: {},
    tags: ["hiroshima_kumanofude", "takemoto_gihoudou", "1746", "279_years", "shodo_specialty"],
    source: "manual",
  },
  {
    slug: "takehara-machinami-souvenir",
    category: "fashion",
    sub_type: "shopping_district_local",
    title_zh: "竹原町並み保存地区 土産(竹原市・国指定重要伝統的建造物群 1982・安芸の小京都・竹細工)",
    title_ja: "竹原町並み保存地区",
    romaji: "Takehara Machinami",
    summary_zh: "**竹原町並み保存地区は「安芸の小京都」**(竹原市本町・国指定重要伝統的建造物群保存地区 1982)。**江戸-明治期町家 100+ 軒+ 竹細工+ たけはら塩+ 地酒(竹鶴)** が集積、観光客の食散歩+ 土産購入 hub。R1 育 既出 hiroshima-jou(広島城)+ R1 食 西条酒蔵通りの先の中継観光地。",
    content_md: "- 認定:国指定重要伝統的建造物群保存地区(1982 年)\n- 立地:竹原市本町(JR 竹原駅 徒歩 15 分)\n- 規模:江戸-明治期町家 100+ 軒\n- 主要商品:竹細工+ たけはら塩+ 地酒(竹鶴)+ 和菓子\n- 営業:店舗による(9:00-17:00)\n- アクセス:JR 呉線 竹原駅 徒歩 15 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "竹原市",
    lg_code: "34203",
    area_types: ["shopping_district_local", "historic_district"],
    lat: 34.3411,
    lon: 132.9089,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shopping_district_local", "takehara_machinami", "1982_designation", "aki_kyoto", "100_machiya"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 育 R2 (5)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "mouri-motonari-haka-akitakata",
    category: "culture",
    sub_type: "history_site_castle",
    title_zh: "毛利元就墓所(安芸高田市・国指定史跡・1571 没・三本の矢伝説の毛利氏始祖・吉田郡山城跡 隣接)",
    title_ja: "毛利元就墓所",
    romaji: "Mouri Motonari Haka",
    summary_zh: "**毛利元就墓所は戦国大名毛利氏の始祖墓**(安芸高田市・国指定史跡)。**1571 年没の毛利元就(1497-1571)** は安芸の小領主から中国地方の大国へ拡張、R1 育既出 広島城築城の毛利輝元の祖父。**「三本の矢」伝説**(息子 3 人の結束)で知られる、安芸高田が毛利氏の本拠地。**吉田郡山城跡**(国史跡)隣接で歴史散策コース。",
    content_md: "- 立地:安芸高田市吉田町(吉田郡山城跡内)\n- 国指定史跡\n- 没年:1571 年(元亀 2)\n- 史的価値:三本の矢伝説の毛利氏始祖+ R1 育 広島城 毛利輝元の祖父\n- 隣接:吉田郡山城跡(国史跡)+ 元就資料館\n- 入場:無料(常時)\n- アクセス:JR 芸備線 吉田口駅 から バス 30 分・吉田下車",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "安芸高田市",
    lg_code: "34214",
    area_types: ["history_site_castle"],
    lat: 34.6717,
    lon: 132.7344,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["history_site_castle", "mouri_motonari", "1571", "three_arrows", "yoshida_koriyama"],
    source: "manual",
  },
  {
    slug: "kakurinji-kasai-650",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "鶴林寺(尾道市御調町・650 創建・国指定史跡・1370 年・備後最古寺の 1・古代仏教遺産)",
    title_ja: "鶴林寺",
    romaji: "Kakurinji",
    summary_zh: "**鶴林寺は備後最古寺の 1**(尾道市御調町・650 創建・1370 年)。**飛鳥期創建の古代寺院**、備後地方の仏教文化発祥地。R1 既出のメジャー寺(R1 千光寺 806・厳島神社 593)に並ぶ広島県内最古級寺院、観光客は少ないが歴史的価値高。",
    content_md: "- 創建:650 年(白雉 1)・1370 年\n- 立地:尾道市御調町\n- 史的価値:備後最古寺の 1・飛鳥期\n- 国指定史跡\n- 入場:無料(常時)\n- 営業:9:00-17:00\n- アクセス:JR 尾道駅 から 車 30 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["shrine_temple"],
    lat: 34.4769,
    lon: 133.1556,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "kakurinji", "650_origin", "1370_years", "bingo_oldest"],
    source: "manual",
  },
  {
    slug: "tomonoura-fukuzenji-tairo-1697",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "福禅寺対潮楼(福山市鞆町・国指定史跡 1697・朝鮮通信使迎接・「日東第一形勝」絶景)",
    title_ja: "福禅寺対潮楼",
    romaji: "Fukuzenji Tairou",
    summary_zh: "**福禅寺対潮楼は鞆の浦の歴史的迎賓楼**(福山市鞆町・1697 完成・国指定史跡)。**朝鮮通信使(江戸期 12 回)が宿泊+ 迎接した楼閣**、対馬+ 鞆の浦+ 大坂+ 江戸の中継地。**朝鮮通信使が「日東第一形勝(東海第一の絶景)」と命名** した瀬戸内多島海眺望、観光客の必訪。",
    content_md: "- 完成:1697 年(元禄 10)\n- 国指定史跡\n- 立地:福山市鞆町(鞆の浦)\n- 史的価値:朝鮮通信使(江戸期 12 回)迎接の楼閣\n- 朝鮮通信使命名:「日東第一形勝(東海第一の絶景)」\n- 入場料:¥200\n- 営業:8:00-17:00\n- 隣接:R1 育 鞆常夜灯 1859+ R1 食 保命酒 1659+ R1 住 御舟宿いろは\n- アクセス:JR 福山駅 から バス 30 分・鞆の浦下車",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "福山市",
    lg_code: "34207",
    area_types: ["shrine_temple", "history_site_castle"],
    lat: 34.3811,
    lon: 133.3839,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "fukuzenji_tairou", "1697", "korean_envoy", "japan_top_view"],
    source: "manual",
  },
  {
    slug: "hijiyama-park-rikugun-bochi",
    category: "culture",
    sub_type: "history_site_castle",
    title_zh: "比治山公園陸軍墓地(広島市南区・1872 整備・原爆生残り墓地・桜+ 紅葉名所+ 戦争関連史跡)",
    title_ja: "比治山公園陸軍墓地",
    romaji: "Hijiyama Rikugun Bochi",
    summary_zh: "**比治山公園陸軍墓地は明治期軍関連史跡**(広島市南区・1872 整備)。**広島は明治-戦時に大本営所在地+ 軍都化**、比治山公園の陸軍墓地に多数の戦没者墓+ R1 育既出の被爆+ 平和テーマと連動。**現在は桜+ 紅葉名所**、市民+ 観光客の散策スポット、広島市現代美術館 1989 併設。",
    content_md: "- 整備:1872 年(明治 5)\n- 立地:広島市南区(比治山公園内)\n- 史的価値:明治-戦時の広島大本営+ 軍都の象徴墓地\n- 1945 原爆:墓地は爆心地 から 2.5 km+ 部分被害\n- 桜:3 月下旬-4 月初\n- 隣接:広島市現代美術館 1989(¥370)\n- 入場:無料(墓地+ 公園)\n- アクセス:広島電鉄「比治山下」電停 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "広島市",
    lg_code: "34100",
    area_types: ["history_site_castle", "park_garden"],
    lat: 34.3833,
    lon: 132.4806,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["history_site_castle", "hijiyama_rikugun_bochi", "1872", "military_capital", "post_atomic_survivor"],
    source: "manual",
  },
  {
    slug: "miyoshi-jinja-akitakata",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "三吉神社(三次市+ 安芸高田市・備北古社・延喜式内社・1300 年・三吉氏ゆかり戦国地域守護)",
    title_ja: "三吉神社",
    romaji: "Miyoshi Jinja",
    summary_zh: "**三吉神社は備北の古社**(三次市・延喜式内社・1300 年)。**三吉氏(備後三次の戦国大名)ゆかり**、地域守護の中心。R1 食 既出 三次ワイナリー+ R1 育既出 三段峡(芸備線アクセス)+ R1 楽 三次霧の海観光と一体の備北文化拠点。",
    content_md: "- 社格:延喜式内社(平安期 9C)\n- 立地:三次市(備北中心)\n- 創建:伝 1300 年(平安期)\n- 史的価値:三吉氏(戦国大名)ゆかり地域守護神\n- 隣接観光:R1 食 三次ワイナリー+ R1 楽 霧の海+ R1 行 芸備線\n- 入場:無料\n- 営業:24 時間(社務所 9:00-17:00)\n- アクセス:JR 芸備線 三次駅 徒歩 / 車 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "三次市",
    lg_code: "34209",
    area_types: ["shrine_temple"],
    lat: 34.8047,
    lon: 132.8508,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "miyoshi_jinja", "1300_years", "engi_shiki", "miyoshi_clan"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 楽 R2 (4)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "miyoshi-night-mist-river",
    category: "entertainment",
    sub_type: "scenic_spot",
    title_zh: "三次霧の海(三次市・11-2 月明け方・盆地霧現象・高谷山展望台・全国屈指雲海絶景)",
    title_ja: "三次霧の海",
    romaji: "Miyoshi Kiri no Umi",
    summary_zh: "**三次霧の海は備北盆地の雲海現象**(三次市・11-2 月明け方)。三次盆地+ 高谷山展望台 から **盆地一面が雲海に覆われ、向こうの山々が島のように浮かぶ絶景**。年 50+ 日発生、全国屈指雲海スポット。早朝 5-7 時がベスト、写真愛好家+ 観光客に人気。",
    content_md: "- 立地:三次市高谷山展望台\n- 期間:11 月-2 月明け方(5:00-8:00)\n- 発生:年 50+ 日(早朝の盆地霧)\n- ベスト時間:日の出前後 1 時間\n- 入場:無料(常時)\n- 駐車場:無料 30 台\n- 隣接:三次ワイナリー(R1 食)+ 三吉神社(R2 育)\n- アクセス:JR 芸備線 三次駅 から 車 15 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "三次市",
    lg_code: "34209",
    area_types: ["scenic_spot"],
    lat: 34.8047,
    lon: 132.8508,
    season_start: "2026-11-01",
    season_end: "2027-02-28",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["scenic_spot", "miyoshi_kiri", "11_to_2_month", "kotani_yama", "fog_sea_top"],
    source: "manual",
  },
  {
    slug: "saijo-sake-festival-october",
    category: "entertainment",
    sub_type: "ancient_festival",
    title_zh: "西条酒まつり(東広島市西条・10 月第 2 週末・25 万人来場・全国 250 銘柄試飲・全国最大酒祭)",
    title_ja: "西条酒まつり",
    romaji: "Saijo Sake Festival",
    summary_zh: "**西条酒まつりは全国最大の酒祭**(東広島市西条・10 月第 2 週末・25 万人来場)。R1 食既出 saijo-shuzo-michi-7(全国 3 大銘醸地)の年中行事、**全国 250 銘柄+ 試飲チケット ¥2200**、酒蔵巡り+ ステージ+ 屋台。広島観光の秋ハイライト、3 ヶ月前ホテル予約必須。",
    content_md: "- 開催:10 月第 2 週末(土+ 日 2 日間)\n- 立地:東広島市西条本町(R1 食 saijo-shuzo-michi)\n- 来場:25 万人\n- 試飲:全国 250 銘柄+ ¥2200(試飲チケット)\n- 内容:酒蔵巡り+ ステージ+ 屋台 200+ 軒\n- 全国最大級酒祭\n- 入場:無料(試飲別)\n- 隣接:R1 食 saijo-shuzo-michi 7 蔵+ R2 住 西条古民家泊\n- アクセス:JR 山陽本線 西条駅 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "東広島市",
    lg_code: "34212",
    area_types: ["festival_event"],
    lat: 34.4267,
    lon: 132.7456,
    season_start: null,
    season_end: null,
    event_start: "2026-10-10",
    event_end: "2026-10-11",
    price_tier: 2,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://sakematsuri.com/" },
    tags: ["ancient_festival", "saijo_sake_fes", "october", "250k_visitors", "250_brands"],
    source: "manual",
  },
  {
    slug: "shimanami-cycling-marathon-oct",
    category: "entertainment",
    sub_type: "hiroshima_shimanami",
    title_zh: "しまなみ海道サイクリング大会(10 月・年 1 回・3 種コース 70/110/140km・8000 人参加)",
    title_ja: "しまなみ海道サイクリング大会",
    romaji: "Shimanami Cycling",
    summary_zh: "**しまなみ海道サイクリング大会は年 1 回の国際自転車イベント**(10 月・8000 人参加)。**3 種コース(70 km+ 110 km+ 140 km)**、世界中のサイクリスト+ 一般参加者が集う。R1 楽既出 shimanami-cycling-1day(個人体験)とは別、競技+ 完走証イベント。事前予約必須(¥10000-15000)。",
    content_md: "- 開催:10 月年 1 回\n- 立地:尾道市-愛媛県今治市(しまなみ海道全域)\n- コース:3 種(70 km+ 110 km+ 140 km)\n- 参加者:約 8000 人(国内+ 国外)\n- 料金:¥10000-15000(コース別)\n- 完走証+ 賞品付\n- 予約:電話 + ネット・3 ヶ月前推奨\n- アクセス:JR 尾道駅 + 各島 起点",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["activity_water", "scenic_spot"],
    lat: 34.4089,
    lon: 133.1956,
    season_start: null,
    season_end: null,
    event_start: "2026-10-25",
    event_end: "2026-10-25",
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_shimanami", "cycling_marathon", "october", "8000_participants", "3_courses"],
    source: "manual",
  },
  {
    slug: "mihara-kobayakawa-takakage-fes",
    category: "entertainment",
    sub_type: "ancient_festival",
    title_zh: "三原浮城まつり(三原市・小早川隆景築城祭・5 月+ 11 月+ 8 月やっさ)",
    title_ja: "三原浮城まつり",
    romaji: "Mihara Ukijiro",
    summary_zh: "**三原浮城まつりは小早川隆景三原城築城を祝う祭**(三原市・5 月+ 11 月)。**1567 年小早川隆景三原城築城**(海に浮かぶ「浮城」)起源、現代は春+ 秋の市民祭+ R1 楽既出 三原やっさ祭り(8 月)と並ぶ三原 3 大祭。三原駅前+ 港エリアで開催。",
    content_md: "- 開催:春 5 月+ 秋 11 月(年 2 回)\n- 立地:三原市(三原駅前+ 港エリア)\n- 由来:1567 年(永禄 10)小早川隆景三原城築城祝\n- 三原 3 大祭:R1 楽 やっさ(8 月)+ R2 楽 浮城(春秋)\n- 内容:武者行列+ ステージ+ 屋台\n- 入場:無料\n- 隣接:R1 食 mihara-tako+ R1 衣 mihara-daruma\n- アクセス:JR 三原駅 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "三原市",
    lg_code: "34204",
    area_types: ["festival_event"],
    lat: 34.4031,
    lon: 133.0786,
    season_start: null,
    season_end: null,
    event_start: "2026-05-09",
    event_end: "2026-05-10",
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["ancient_festival", "mihara_ukijiro", "1567_origin", "kobayakawa_takakage", "spring_autumn"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 行 R2 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shimanami-ferry-routes",
    category: "transport",
    sub_type: "hiroshima_island_routes",
    title_zh: "しまなみ高速船(尾道港-生口島+ 大三島-今治・サイクリスト+ 観光客向けショートカット)",
    title_ja: "しまなみ高速船",
    romaji: "Shimanami Kosen",
    summary_zh: "**しまなみ高速船はサイクリスト+ 観光客向けショートカット**(尾道港-各島・複数業者運行)。R1 楽 既出 shimanami-cycling 全長 60 km を **部分的にショートカット**(尾道-生口島・尾道-大三島・今治-生口島 等)、自転車輪行可能。1 日券 ¥3000+ 個別 ¥1000-2000。",
    content_md: "- 運営:複数業者(尾道港 から 各島)\n- 主要航路:尾道-生口島+ 尾道-大三島+ 今治-生口島\n- 自転車輪行:可能\n- 料金:個別 ¥1000-2000・1 日券 ¥3000\n- 利点:R1 楽 shimanami 60km 全完走 必要なし・部分ショートカット\n- 隣接:R1 行 onomichi-port + R1 楽 shimanami-cycling\n- アクセス:尾道港(JR 尾道駅 徒歩 5 分)",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["ferry_terminal"],
    lat: 34.4089,
    lon: 133.1956,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_island_routes", "shimanami_ferry", "shortcuts", "bike_carry", "multi_route"],
    source: "manual",
  },
  {
    slug: "kure-station-jr",
    category: "transport",
    sub_type: "hiroshima_jr_local",
    title_zh: "JR 呉駅(呉市・1903 開業・呉軍港+ 大和ミュージアム R1 育徒歩・呉観光起点・JR 呉線+ 路線バス hub)",
    title_ja: "JR 呉駅",
    romaji: "JR Kure Eki",
    summary_zh: "**JR 呉駅は呉観光の起点**(呉市・1903 開業)。R1 育既出 大和ミュージアム+ 旧海軍兵学校(江田島フェリー乗換)+ R2 食 呉海軍カレー観光のメイン hub、JR 呉線+ 路線バス+ 江田島フェリー連絡。広島駅 から JR 呉線 30 分の利便性。",
    content_md: "- 開業:1903 年(明治 36)\n- 立地:呉市中央(呉港隣)\n- JR 接続:呉線\n- 隣接:R1 育 大和ミュージアム(徒歩 5 分)+ 旧海軍兵学校(江田島・連絡フェリー)+ R2 食 呉海軍カレー店\n- 1 日乗車人員:約 1.5 万人\n- アクセス:広島駅 から JR 呉線 30 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "呉市",
    lg_code: "34202",
    area_types: ["transit_hub"],
    lat: 34.2422,
    lon: 132.5550,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_jr_local", "kure_eki", "1903", "yamato_museum_walk", "kure_naval_hub"],
    source: "manual",
  },
  {
    slug: "innoshima-bridge-walk",
    category: "transport",
    sub_type: "hiroshima_shimanami",
    title_zh: "因島大橋(尾道市因島・1983 完成・しまなみ海道 第 1 橋・全長 1270m・歩道+ サイクリング)",
    title_ja: "因島大橋",
    romaji: "Innoshima Ohashi",
    summary_zh: "**因島大橋はしまなみ海道の第 1 橋**(尾道市因島・1983 完成・全長 1270 m)。**しまなみ海道の歴史的第 1 橋**(7 橋中最古)、向島-因島を結ぶ吊橋+ 歩道+ サイクリング道。R1 楽 shimanami-cycling 起点近く、徒歩+ 自転車で渡れる絶景吊橋。",
    content_md: "- 完成:1983 年(昭和 58)・しまなみ第 1 橋\n- 全長:1270 m\n- 構造:吊橋(主塔 145 m)\n- 連絡:向島(尾道市)↔ 因島(尾道市)\n- 通行:車道+ 歩道+ サイクリング道\n- 通行料:無料\n- アクセス:JR 尾道駅 から 渡し船で向島・尾道港 から 高速船で因島",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["scenic_spot", "road_route"],
    lat: 34.3669,
    lon: 133.1581,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_shimanami", "innoshima_ohashi", "1983", "1270m", "shimanami_first_bridge"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[hiroshima-r2] 尚無條目");
    return;
  }
  console.log(`[hiroshima-r2] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const byCat = new Map<string, number>();
    for (const r of rows) byCat.set(r.category, (byCat.get(r.category) ?? 0) + 1);
    for (const [k, v] of [...byCat.entries()].sort()) {
      console.log(`  ${k.padEnd(15)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[hiroshima-r2] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[hiroshima-r2] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[hiroshima-r2] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
