// Seed 神奈川県 楽 R1(20 筆 / Sprint 1.5 / 第十四卷)
// 横浜 5 / 湘南 4 / 箱根 5 / 三浦 2 / 県央 2 / 川崎 2 = 20
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 横浜 5
  {
    slug: "minatomirai-21-1989",
    category: "entertainment", sub_type: "kanagawa_yokohama_entertainment",
    title_zh: "みなとみらい 21(横浜市西区みなとみらい・1989 横浜博覧会開催を契機に開発開始 36+ 年+ 国内最大級ウォーターフロント再開発+ R1 育 横浜赤レンガ倉庫+ R1 住 ロイヤルパーク+インターコンチ+ R1 楽 コスモワールド・ランドマーク 集積・無料散策)",
    title_ja: "みなとみらい 21", romaji: "Minato Mirai 21",
    summary_zh: "**みなとみらい 21 は 1989 横浜博覧会開発 36+ 年・国内最大級ウォーターフロント・R1 育 赤レンガ+R1 住 ロイヤルパーク+R1 楽 コスモワールド集積**(西区)。無料。",
    content_md: "- 立地:**横浜市西区みなとみらい**\n- 起源:**1989 横浜博覧会開催契機に開発開始 36+ 年**\n- 認定:**国内最大級ウォーターフロント再開発**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["theme_park", "shopping_district"], lat: 35.4569, lon: 139.6386,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["minatomirai_1989"], source: "manual",
  },
  {
    slug: "yokohama-cosmo-world-1989",
    category: "entertainment", sub_type: "kanagawa_yokohama_entertainment",
    title_zh: "横浜コスモワールド+ コスモクロック 21(横浜市中区新港・1989 開園 36+ 年+ 「コスモクロック 21」高さ 112.5m 大観覧車(全国最大級+時計付世界初)+ R1 楽 みなとみらい+赤レンガ徒歩 5 分・¥0(入園無料・観覧車 ¥900))",
    title_ja: "コスモワールド", romaji: "Cosmo World",
    summary_zh: "**横浜コスモワールド+コスモクロック 21 は 1989 開園 36+ 年・112.5m 大観覧車(全国最大級+時計付世界初)・R1 楽 みなとみらい+赤レンガ徒歩 5 分**(中区新港)。観覧車 ¥900。",
    content_md: "- 立地:**横浜市中区新港**\n- 起源:**1989 開園 36+ 年**\n- 認定:**「コスモクロック 21」高さ 112.5m 大観覧車(全国最大級 + 時計付世界初)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["theme_park"], lat: 35.4569, lon: 139.6361,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["cosmo_world_1989"], source: "manual",
  },
  {
    slug: "hakkeijima-seaparadise-1993",
    category: "entertainment", sub_type: "kanagawa_yokohama_entertainment",
    title_zh: "横浜八景島シーパラダイス(横浜市金沢区八景島・1993 開園 32+ 年+ 国内最大級水族館+ 4 大水族館(アクアミュージアム+ふれあいラグーン+ドルフィンファンタジー+うみファーム)+ ジェットコースター+ホテル併設・¥3,300・国内ファミリー観光客代表)",
    title_ja: "八景島シーパラ", romaji: "Hakkeijima Sea Paradise",
    summary_zh: "**横浜八景島シーパラダイスは 1993 開園 32+ 年・国内最大級水族館・4 大水族館+ジェットコースター+ホテル併設**(横浜金沢八景島)。¥3,300、ファミリー代表。",
    content_md: "- 立地:**横浜市金沢区八景島**\n- 起源:**1993 開園 32+ 年**\n- 認定:**国内最大級水族館 + 4 大水族館 + ジェットコースター + ホテル併設**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["aquarium_zoo", "theme_park"], lat: 35.3372, lon: 139.6328,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["hakkeijima_1993"], source: "manual",
  },
  {
    slug: "yokohama-marine-tower-1961",
    category: "entertainment", sub_type: "kanagawa_yokohama_entertainment",
    title_zh: "横浜マリンタワー(横浜市中区山下町・1961 開業 64+ 年+ 1959 横浜開港 100 周年記念建設+ 高さ 106m 灯台型展望タワー(2008-2009 改修)+ 山下公園 1930 隣接+ 観覧 ¥1,000)",
    title_ja: "横浜マリンタワー", romaji: "Yokohama Marine Tower",
    summary_zh: "**横浜マリンタワーは 1961 開業 64+ 年・1959 横浜開港 100 周年記念建設・高さ 106m 灯台型展望タワー・山下公園 1930 隣接**(中区山下町)。¥1,000。",
    content_md: "- 立地:**横浜市中区山下町**\n- 起源:**1961 開業 64+ 年 + 1959 横浜開港 100 周年記念建設**\n- 認定:**高さ 106m 灯台型展望タワー**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["theme_park", "history_site_castle"], lat: 35.4428, lon: 139.6489,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["marine_tower_1961"], source: "manual",
  },
  {
    slug: "yokohama-stadium-1929",
    category: "entertainment", sub_type: "kanagawa_yokohama_entertainment",
    title_zh: "横浜スタジアム+ 横浜公園(横浜市中区横浜公園・横浜公園 1876 開園 149+ 年(全国最古洋式公園候補)+ 横浜スタジアム 1978 開業 47+ 年+ 横浜 DeNA ベイスターズ R1 衣 派生本拠地+ 3 万 4046 人収容+ 1929 第 1 代横浜公園球場・¥3,500-12,000)",
    title_ja: "横浜スタジアム", romaji: "Yokohama Stadium",
    summary_zh: "**横浜スタジアム+横浜公園は 1876 公園 149+ 年(全国最古洋式公園候補)+1978 スタジアム 47+ 年・横浜 DeNA 本拠地・3 万 4046 人収容**(中区)。¥3,500-12,000。",
    content_md: "- 立地:**横浜市中区横浜公園**\n- 起源:**横浜公園 1876 開園 149+ 年(全国最古洋式公園候補) + 横浜スタジアム 1978 開業 47+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["theme_park", "nature_park"], lat: 35.4439, lon: 139.6403,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["yokohama_stadium_1978", "yokohama_park_1876"], source: "manual",
  },

  // 湘南 4
  {
    slug: "shin-enoshima-aquarium-2004",
    category: "entertainment", sub_type: "kanagawa_shonan_entertainment",
    title_zh: "新江ノ島水族館(藤沢市片瀬海岸・2004 開館 21+ 年(旧 江ノ島水族館 1954 から 2003 閉館後再建)+ クラゲファンタジーホール+ イルカパフォーマンス+ ペンギン+ アザラシ・¥2,500・小田急片瀬江ノ島駅徒歩 3 分・国内ファミリー観光客代表)",
    title_ja: "新江ノ島水族館", romaji: "Shin Enoshima Aquarium",
    summary_zh: "**新江ノ島水族館は 2004 開館 21+ 年(旧 1954-2003 閉館後再建)・クラゲファンタジーホール+イルカ+ペンギン+アザラシ**(藤沢片瀬)。¥2,500、小田急片瀬江ノ島徒歩 3 分。",
    content_md: "- 立地:**藤沢市片瀬海岸**\n- 起源:**2004 開館 21+ 年(旧 江ノ島水族館 1954 から 2003 閉館後再建)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "藤沢市", lg_code: "14205",
    area_types: ["aquarium_zoo"], lat: 35.3056, lon: 139.4844,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shin_enoshima_2004"], source: "manual",
  },
  {
    slug: "enoshima-cocking-1882",
    category: "entertainment", sub_type: "kanagawa_shonan_entertainment",
    title_zh: "江ノ島サムエル・コッキング苑+ 江の島シーキャンドル(藤沢市江の島・1882 英国貿易商コッキング造園 143+ 年+ 江の島展望灯台「シーキャンドル」2003 高さ 59.8m+ 富士山+鎌倉+三浦半島眺望+ 12 月-2 月チューリップ+ 9-10 月コスモス・¥500・国際 SNS 海外旅行者代表)",
    title_ja: "江の島サムエル", romaji: "Enoshima Samuel Cocking",
    summary_zh: "**江ノ島サムエル・コッキング苑+シーキャンドルは 1882 コッキング造園 143+ 年+シーキャンドル 2003 59.8m・富士山+鎌倉+三浦眺望**(藤沢江の島)。¥500、海外代表。",
    content_md: "- 立地:**藤沢市江の島**\n- 起源:**1882 英国貿易商コッキング造園 143+ 年 + シーキャンドル 2003 開業 22+ 年**\n- 認定:**江の島展望灯台「シーキャンドル」高さ 59.8m + 富士山 + 鎌倉 + 三浦半島眺望**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "藤沢市", lg_code: "14205",
    area_types: ["nature_park", "theme_park"], lat: 35.2997, lon: 139.4806,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["enoshima_cocking_1882", "shokudai_2003"], source: "manual",
  },
  {
    slug: "shichirigahama-surf",
    category: "entertainment", sub_type: "kanagawa_shonan_entertainment",
    title_zh: "七里ヶ浜+ 由比ヶ浜サーフィン+海水浴(鎌倉市七里ガ浜+由比ガ浜・由比ガ浜 1884 開設 141+ 年(全国最古海水浴場候補)+ 七里ヶ浜湘南サーフメッカ+ 江ノ電七里ヶ浜駅+由比ガ浜駅・無料)",
    title_ja: "七里ヶ浜+由比ヶ浜", romaji: "Shichirigahama Yuigahama",
    summary_zh: "**七里ヶ浜+由比ガ浜は由比ガ浜 1884 開設 141+ 年(全国最古海水浴場候補)・七里ヶ浜湘南サーフメッカ**(鎌倉)。江ノ電七里ヶ浜+由比ガ浜駅、無料。",
    content_md: "- 立地:**鎌倉市七里ガ浜 + 由比ガ浜**\n- 起源:**由比ガ浜 1884 開設 141+ 年(全国最古海水浴場候補)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["beach_coast"], lat: 35.3056, lon: 139.5167,
    season_start: "2026-07-01", season_end: "2026-08-31", event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shichirigahama", "yuigahama_1884"], source: "manual",
  },
  {
    slug: "chigasaki-southern-beach",
    category: "entertainment", sub_type: "kanagawa_shonan_entertainment",
    title_zh: "茅ヶ崎サザンビーチ+ サザンオールスターズ聖地(茅ヶ崎市・1978 サザンオールスターズ「勝手にシンドバッド」茅ヶ崎発祥 47+ 年+ サザンビーチちがさき(全国海水浴場 100 選 1996)+ えぼし岩・無料散策・国内 SNS 音楽ファン代表)",
    title_ja: "茅ヶ崎サザン", romaji: "Chigasaki Southern",
    summary_zh: "**茅ヶ崎サザンビーチ+サザンオールスターズ聖地は 1978 「勝手にシンドバッド」茅ヶ崎発祥 47+ 年・全国海水浴場 100 選 1996・えぼし岩**(茅ヶ崎)。無料、音楽ファン代表。",
    content_md: "- 立地:**茅ヶ崎市**\n- 起源:**1978 サザンオールスターズ「勝手にシンドバッド」茅ヶ崎発祥 47+ 年**\n- 認定:**サザンビーチちがさき 全国海水浴場 100 選 1996 + えぼし岩**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "茅ヶ崎市", lg_code: "14207",
    area_types: ["beach_coast"], lat: 35.3331, lon: 139.4067,
    season_start: "2026-07-01", season_end: "2026-08-31", event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["chigasaki_southern", "1978"], source: "manual",
  },

  // 箱根 5
  {
    slug: "ashinoko-pirate-ship",
    category: "entertainment", sub_type: "kanagawa_hakone_entertainment",
    title_zh: "芦ノ湖海賊船+ 箱根登山船(足柄下郡箱根町元箱根+桃源台・芦ノ湖 4400 万年前カルデラ湖+ 1963 海賊船型遊覧船運航 62+ 年+ 富士山箱根伊豆国立公園 1936+ R1 育 箱根神社隣接+ R1 住 芦ノ湖プリンス連動・¥1,200/片道)",
    title_ja: "芦ノ湖海賊船", romaji: "Ashinoko Pirate",
    summary_zh: "**芦ノ湖海賊船+登山船は 4400 万年前カルデラ湖・1963 海賊船型運航 62+ 年・富士箱根伊豆国立公園 1936**(箱根元箱根+桃源台)。R1 育 箱根神社隣接、¥1,200/片道。",
    content_md: "- 立地:**足柄下郡箱根町元箱根 + 桃源台**\n- 起源:**1963 海賊船型遊覧船運航 62+ 年**\n- 認定:**4400 万年前カルデラ湖 + 富士箱根伊豆国立公園 1936**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "足柄下郡", municipality_ja: "箱根町", lg_code: "14382",
    area_types: ["theme_park", "nature_park"], lat: 35.2031, lon: 139.0250,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["ashinoko_pirate_1963"], source: "manual",
  },
  {
    slug: "owakudani-1959",
    category: "entertainment", sub_type: "kanagawa_hakone_entertainment",
    title_zh: "大涌谷+ 黒たまご(足柄下郡箱根町仙石原・3000 年前火山活動・噴煙活動継続中+ 1900 年代以降観光開発・1959 箱根ロープウェイ開通 66+ 年+ 「黒たまご」温泉卵 1 個食べると寿命 7 年延長伝承・¥500・標高 1044m)",
    title_ja: "大涌谷", romaji: "Ōwakudani",
    summary_zh: "**大涌谷+黒たまごは 3000 年前火山活動・噴煙継続・1959 ロープウェイ開通 66+ 年・「黒たまご」温泉卵 1 個食べると寿命 7 年延長伝承**(箱根仙石原)。¥500、標高 1044m。",
    content_md: "- 立地:**足柄下郡箱根町仙石原**\n- 起源:**1959 箱根ロープウェイ開通 66+ 年**\n- 認定:**3000 年前火山活動 + 「黒たまご」温泉卵伝承 + 標高 1044m**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "足柄下郡", municipality_ja: "箱根町", lg_code: "14382",
    area_types: ["nature_park"], lat: 35.2444, lon: 139.0211,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["owakudani"], source: "manual",
  },
  {
    slug: "hakone-open-air-museum-1969",
    category: "entertainment", sub_type: "kanagawa_hakone_entertainment",
    title_zh: "彫刻の森美術館(足柄下郡箱根町二ノ平・1969 開館 56+ 年+ 全国最古野外彫刻美術館・7 万 m² 大規模庭園+ ヘンリー・ムーア+ ロダン+ ピカソ展示館+ 屋外彫刻 120+ 体・¥2,000・国際 SNS 海外旅行者代表)",
    title_ja: "彫刻の森美術館", romaji: "Open Air Museum",
    summary_zh: "**彫刻の森美術館は 1969 開館 56+ 年・全国最古野外彫刻美術館・7 万 m² 庭園・ムーア+ロダン+ピカソ館+屋外彫刻 120+ 体**(箱根二ノ平)。¥2,000、海外代表。",
    content_md: "- 立地:**足柄下郡箱根町二ノ平**\n- 起源:**1969 開館 56+ 年**\n- 認定:**全国最古野外彫刻美術館 + 7 万 m² 大規模庭園 + 屋外彫刻 120+ 体**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "足柄下郡", municipality_ja: "箱根町", lg_code: "14382",
    area_types: ["museum_art", "nature_park"], lat: 35.2486, lon: 139.0589,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["chokoku_no_mori_1969"], source: "manual",
  },
  {
    slug: "gora-park-1914",
    category: "entertainment", sub_type: "kanagawa_hakone_entertainment",
    title_zh: "箱根強羅公園(足柄下郡箱根町強羅・1914 開園 111+ 年+ 全国最古フランス式庭園・国登録記念物 2014・噴水+大温室+クラフトハウス+ R1 食 箱根温泉饅頭隣接・¥550)",
    title_ja: "箱根強羅公園", romaji: "Gōra Park",
    summary_zh: "**箱根強羅公園は 1914 開園 111+ 年・全国最古フランス式庭園・国登録記念物 2014・噴水+大温室+クラフトハウス**(箱根強羅)。¥550、R1 食 箱根温泉饅頭隣接。",
    content_md: "- 立地:**足柄下郡箱根町強羅**\n- 起源:**1914 開園 111+ 年**\n- 認定:**全国最古フランス式庭園 + 国登録記念物 2014**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "足柄下郡", municipality_ja: "箱根町", lg_code: "14382",
    area_types: ["nature_park"], lat: 35.2531, lon: 139.0314,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["gora_park_1914"], source: "manual",
  },
  {
    slug: "sengoku-pampas-grass",
    category: "entertainment", sub_type: "kanagawa_hakone_entertainment",
    title_zh: "仙石原ススキ草原(足柄下郡箱根町仙石原・100ha 全国 3 大ススキ名所候補(蘇陽峡+曽爾高原並ぶ)+ 9 月中旬-11 月中旬黄金色ススキ+ 富士箱根伊豆国立公園内・無料散策・国内 SNS 秋季観光名所代表)",
    title_ja: "仙石原ススキ", romaji: "Sengoku Susuki",
    summary_zh: "**仙石原ススキ草原は 100ha 全国 3 大ススキ名所候補(蘇陽峡+曽爾高原並ぶ)・9 月中旬-11 月中旬黄金色ススキ・富士箱根伊豆国立公園内**(箱根仙石原)。無料。",
    content_md: "- 立地:**足柄下郡箱根町仙石原**\n- 認定:**100ha 全国 3 大ススキ名所候補(蘇陽峡 + 曽爾高原並ぶ) + 富士箱根伊豆国立公園内**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "足柄下郡", municipality_ja: "箱根町", lg_code: "14382",
    area_types: ["nature_park"], lat: 35.2647, lon: 139.0211,
    season_start: "2026-09-15", season_end: "2026-11-15", event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["sengoku_susuki"], source: "manual",
  },

  // 三浦 2
  {
    slug: "jogashima-island",
    category: "entertainment", sub_type: "kanagawa_miura_entertainment",
    title_zh: "城ヶ島+ 城ヶ島灯台(三浦市三崎・三浦半島最南端・面積 0.99km²+ 城ヶ島灯台 1870 点灯 155+ 年(国内 5 番目洋式灯台)・馬の背洞門・天然記念物・北原白秋詩碑・¥0(灯台公園無料)・京急三崎口駅+バス)",
    title_ja: "城ヶ島", romaji: "Jōgashima",
    summary_zh: "**城ヶ島+城ヶ島灯台は三浦半島最南端・0.99km²・灯台 1870 点灯 155+ 年(国内 5 番目洋式)・馬の背洞門・北原白秋詩碑**(三浦三崎)。京急三崎口+バス、無料。",
    content_md: "- 立地:**三浦市三崎**\n- 起源:**城ヶ島灯台 1870 点灯 155+ 年(国内 5 番目洋式灯台)**\n- 認定:**三浦半島最南端 + 馬の背洞門 + 北原白秋詩碑**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "三浦市", lg_code: "14210",
    area_types: ["nature_park", "beach_coast"], lat: 35.1278, lon: 139.6206,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jogashima", "lighthouse_1870"], source: "manual",
  },
  {
    slug: "yokosuka-verny-dobuita",
    category: "entertainment", sub_type: "kanagawa_miura_entertainment",
    title_zh: "横須賀ヴェルニー公園+ どぶ板通商店街(横須賀市汐入町+ 本町・1865 横須賀製鉄所創設フランス人ヴェルニー記念公園 1947+ R1 衣 どぶ板通スカジャン発祥・米軍横須賀基地隣接・米海軍カレー+ ネイビーバーガー・無料)",
    title_ja: "ヴェルニー+どぶ板", romaji: "Verny Dobuita",
    summary_zh: "**横須賀ヴェルニー公園+どぶ板通商店街は 1865 製鉄所フランス人ヴェルニー記念 1947+R1 衣 どぶ板スカジャン発祥・米軍基地隣接・海軍カレー+ネイビーバーガー**(横須賀)。無料。",
    content_md: "- 立地:**横須賀市汐入町 + 本町**\n- 起源:**1865 横須賀製鉄所創設フランス人ヴェルニー記念公園 1947**\n- 関連:**R1 衣 どぶ板通商店街スカジャン派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横須賀市", lg_code: "14201",
    area_types: ["nature_park", "history_site_castle"], lat: 35.2806, lon: 139.6711,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["verny_park", "dobuita"], source: "manual",
  },

  // 県央 2
  {
    slug: "sagamiko-pleasure-forest",
    category: "entertainment", sub_type: "kanagawa_kennō_entertainment",
    title_zh: "さがみ湖プレジャーフォレスト+ 相模湖(相模原市緑区・1965 さがみ湖ピクニックランド開園 60+ 年+ 2007 富士急行買収「プレジャーフォレスト」改称・全国最大級イルミネーション 600 万球(11 月-4 月)+ 遊園地+温泉+キャンプ場・¥2,000)",
    title_ja: "さがみ湖プレジャーフォレスト", romaji: "Sagamiko",
    summary_zh: "**さがみ湖プレジャーフォレスト+相模湖は 1965 開園 60+ 年・2007 富士急行改称・全国最大級イルミネーション 600 万球(11-4 月)・遊園地+温泉+キャンプ**(相模原緑)。¥2,000。",
    content_md: "- 立地:**相模原市緑区**\n- 起源:**1965 さがみ湖ピクニックランド開園 60+ 年 + 2007 富士急行買収「プレジャーフォレスト」改称**\n- 認定:**全国最大級イルミネーション 600 万球(11 月-4 月)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "相模原市", lg_code: "14150",
    area_types: ["theme_park", "nature_park"], lat: 35.6017, lon: 139.2089,
    season_start: "2026-11-01", season_end: "2027-04-30", event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["sagamiko_1965", "pleasure_forest_2007"], source: "manual",
  },
  {
    slug: "tanzawa-oyama-1965",
    category: "entertainment", sub_type: "kanagawa_kennō_entertainment",
    title_zh: "丹沢大山国定公園(伊勢原市+ 秦野市+清川村+愛川+ 山北町・1965 国定公園指定 60+ 年+ 401 km² 大規模国定公園+ 標高 1252m 大山+1567m 塔ノ岳+1672m 蛭ヶ岳・登山+紅葉+R1 育 大山阿夫利連動・無料散策)",
    title_ja: "丹沢大山", romaji: "Tanzawa Ōyama",
    summary_zh: "**丹沢大山国定公園は 1965 国定公園指定 60+ 年・401km² 大規模・大山 1252m+塔ノ岳 1567m+蛭ヶ岳 1672m**(伊勢原+秦野+清川+愛川+山北)。R1 育 大山連動、無料。",
    content_md: "- 立地:**伊勢原市 + 秦野市 + 清川村 + 愛川町 + 山北町**\n- 起源:**1965 国定公園指定 60+ 年**\n- 規模:**401 km² + 標高 1252m 大山 + 1567m 塔ノ岳 + 1672m 蛭ヶ岳**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "伊勢原市", lg_code: "14214",
    area_types: ["nature_park"], lat: 35.4250, lon: 139.2367,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tanzawa_oyama_1965"], source: "manual",
  },

  // 川崎 2
  {
    slug: "kawasaki-factory-night-view",
    category: "entertainment", sub_type: "kanagawa_kawasaki_entertainment",
    title_zh: "川崎工場夜景観光(川崎市川崎区・京浜工業地帯+ 2008 「工場夜景クルーズ」発祥+ 全国 4 大工場夜景候補(室蘭+四日市+周南並ぶ)+ JFE スチール・東亜石油・夜景クルーズ船 ¥3,000-5,500・国際 SNS 海外旅行者代表)",
    title_ja: "川崎工場夜景", romaji: "Kawasaki Factory Night",
    summary_zh: "**川崎工場夜景観光は京浜工業地帯・2008 工場夜景クルーズ発祥・全国 4 大工場夜景候補(室蘭+四日市+周南並ぶ)・JFE+東亜石油**(川崎区)。¥3,000-5,500、海外代表。",
    content_md: "- 立地:**川崎市川崎区**\n- 起源:**2008 「工場夜景クルーズ」発祥**\n- 認定:**全国 4 大工場夜景候補(室蘭 + 四日市 + 周南並ぶ) + JFE スチール + 東亜石油**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "川崎市", lg_code: "14130",
    area_types: ["industrial_heritage", "theme_park"], lat: 35.5308, lon: 139.7028,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kawasaki_factory_night_2008"], source: "manual",
  },
  {
    slug: "kawasaki-daishi-omotesando",
    category: "entertainment", sub_type: "kanagawa_kawasaki_entertainment",
    title_zh: "川崎大師仲見世+ 厄除参道商店街(川崎市川崎区大師町・R1 育 川崎大師平間寺 1128 派生・京急大師線川崎大師駅-本堂 350m 商店街 100+ 軒+ くずもち+ 飴+ 招福だるま+ 護摩参拝・無料散策・国際 SNS 海外旅行者代表)",
    title_ja: "川崎大師参道", romaji: "Kawasaki Daishi Sandō",
    summary_zh: "**川崎大師仲見世+厄除参道商店街は R1 育 川崎大師 1128 派生・川崎大師駅-本堂 350m 商店街 100+ 軒・くずもち+飴+招福だるま+護摩**(川崎大師町)。無料、海外代表。",
    content_md: "- 立地:**川崎市川崎区大師町**\n- 関連:**R1 育 川崎大師平間寺 1128 派生**\n- 規模:**京急大師線川崎大師駅-本堂 350m 商店街 100+ 軒**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "川崎市", lg_code: "14130",
    area_types: ["shopping_district", "history_site_castle"], lat: 35.5350, lon: 139.7300,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kawasaki_daishi_sandō"], source: "manual",
  },
];

seedMain(rows, "kanagawa-entertainment-r1");
