// Seed 愛媛県 食 R1(25 筆 / Sprint 17.1 — 第十七卷愛媛県開卷)
// 鯛めし系 5 / 海産 5 / 蜜柑+郷土 5 / 麺+ 鶏 4 / 道後+和菓子 4 / 山地 + 補完 2 = 25
// 累積 +25 = 25 entries 達成
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  {
    slug: "matsuyama-tai-meshi",
    category: "food", sub_type: "ehime_meibutsu",
    title_zh: "松山鯛めし+ 五色鯛めし(松山市・宇和島系と違う「炊き込み式」+ 鯛と香味野菜の蒸し焚き+ 江戸期松山藩 1600 年代より家庭料理 400+ 年・¥1,800-3,500)",
    title_ja: "松山鯛めし", romaji: "Matsuyama Tai Meshi",
    summary_zh: "**松山鯛めしは「炊き込み式」+ 鯛と香味野菜蒸し焚き+ 江戸期松山藩 1600 年代より家庭料理 400+ 年**(松山)。¥1,800-3,500、宇和島鯛めし(生卵タレ式)と二大別。",
    content_md: "- 立地:**松山市道後温泉・大街道・松山中央**\n- 起源:**江戸期松山藩 1600 年代より家庭料理 400+ 年**\n- 派生:**宇和島鯛めし(生卵タレ式)= 宇和島系・松山鯛めし = 炊き込み系・二大スタイル**\n- 観光客向け店舗:**「すし丸」「鯛や」道後 30+ 店舗**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["restaurant_traditional"],
    lat: 33.8392, lon: 132.7655,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["matsuyama_tai_meshi"], source: "manual",
  },
  {
    slug: "uwajima-tai-meshi",
    category: "food", sub_type: "ehime_meibutsu",
    title_zh: "宇和島鯛めし+ 卵掛け式(宇和島市・伊予水軍 1500 年代より海上料理伝承 500+ 年+ 漁師飯系・刺身鯛+ 生卵+ 醤油タレで丼飯+ 全国食楽郎テレビ放映+ 観光客代表料理・¥1,800-4,200)",
    title_ja: "宇和島鯛めし", romaji: "Uwajima Tai Meshi",
    summary_zh: "**宇和島鯛めしは伊予水軍 1500 年代より 500+ 年・刺身鯛+生卵+醤油タレで丼飯**(宇和島)。¥1,800-4,200、観光客代表料理。",
    content_md: "- 立地:**宇和島市中央町・きさいや広場・道の駅**\n- 起源:**伊予水軍 1500 年代より海上料理伝承 500+ 年**\n- 派生:**漁師飯系 → 刺身鯛+生卵+醤油タレで丼飯**\n- 名店:**「ほづみ亭」「鯛や」「丸水」 30+ 店舗・全国食楽郎テレビ放映**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "宇和島市", lg_code: "38203",
    area_types: ["restaurant_traditional"],
    lat: 33.2235, lon: 132.5611,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["uwajima_tai_meshi"], source: "manual",
  },
  {
    slug: "imabari-yakitori",
    category: "food", sub_type: "ehime_meat",
    title_zh: "今治焼鳥+ 鉄板焼鳥(今治市・1960 年代造船所労働者向けに鉄板焼鳥誕生 65+ 年+ 串無しで鉄板に押し付けて短時間で焼く独自スタイル+ 鶏皮+ 鶏もも+ 全国焼鳥地ランク上位+「世界の中心で愛をさけぶ」舞台ロケ・¥800-2,800)",
    title_ja: "今治焼鳥", romaji: "Imabari Yakitori",
    summary_zh: "**今治焼鳥+ 鉄板焼鳥は 1960 年代造船所労働者向け 65+ 年・串無しで鉄板押し付け短時間焼**(今治)。¥800-2,800。",
    content_md: "- 立地:**今治市本町・大手町・港町**\n- 起源:**1960 年代造船所労働者向けに鉄板焼鳥誕生 65+ 年**\n- 派生:**串無しで鉄板に押し付けて短時間で焼く独自スタイル → 鶏皮+鶏もも**\n- 名店:**「五味鳥」「鳥林」「鳥番長」 50+ 店舗・全国焼鳥地ランク上位**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "今治市", lg_code: "38202",
    area_types: ["restaurant_traditional"],
    lat: 34.0660, lon: 132.9988,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["imabari_yakitori"], source: "manual",
  },
  {
    slug: "yawatahama-jakoten",
    category: "food", sub_type: "ehime_seafood",
    title_zh: "八幡浜じゃこ天+ 揚げ蒲鉾(八幡浜市・宇和海漁港 1700 年代より漁師飯誕生 320+ 年+ 小魚すり身を揚げた郷土蒲鉾+ 県内全市町に普及+ 駅弁+ 朝ご飯定番+ 全国食楽郎テレビ放映・¥250-1,800)",
    title_ja: "八幡浜じゃこ天", romaji: "Yawatahama Jakoten",
    summary_zh: "**八幡浜じゃこ天+揚げ蒲鉾は 1700 年代より 320+ 年・小魚すり身を揚げた郷土蒲鉾**(八幡浜)。¥250-1,800、駅弁+朝ご飯定番。",
    content_md: "- 立地:**八幡浜市本町・港町・どーや市場**\n- 起源:**宇和海漁港 1700 年代より漁師飯誕生 320+ 年**\n- 派生:**小魚すり身を揚げた郷土蒲鉾 → 県内全市町に普及**\n- 名店:**「谷本蒲鉾」「向井蒲鉾」 1900 年代創業老舗 100+ 年**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "八幡浜市", lg_code: "38204",
    area_types: ["restaurant_traditional", "shopping_district"],
    lat: 33.4659, lon: 132.4226,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yawatahama_jakoten"], source: "manual",
  },
  {
    slug: "uwajima-fukumen",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "宇和島ふくめん+ こんにゃくと魚すり身(宇和島市・伊予水軍時代 1500 年代より宴会料理伝承 500+ 年+ こんにゃく+ 魚すり身+ 椎茸+ 紅生姜+ 椀盛り+ 結婚祝い席に必出・「四国八十八食」 認定・¥1,200-2,800)",
    title_ja: "宇和島ふくめん", romaji: "Uwajima Fukumen",
    summary_zh: "**宇和島ふくめん+こんにゃくと魚すり身は伊予水軍時代 1500 年代より 500+ 年・こんにゃく+魚すり身+椎茸+紅生姜+椀盛り+結婚祝い席必出**(宇和島)。¥1,200-2,800、四国八十八食認定。",
    content_md: "- 立地:**宇和島市中央町・きさいや広場**\n- 起源:**伊予水軍時代 1500 年代より宴会料理伝承 500+ 年**\n- 派生:**こんにゃく+魚すり身+椎茸+紅生姜+椀盛り → 結婚祝い席に必出**\n- 認定:**「四国八十八食」 認定**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "宇和島市", lg_code: "38203",
    area_types: ["restaurant_traditional"],
    lat: 33.2235, lon: 132.5611,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["uwajima_fukumen"], source: "manual",
  },
  {
    slug: "iyokan-citrus-products",
    category: "food", sub_type: "ehime_mikan",
    title_zh: "伊予柑+ 温州蜜柑加工品(松山+ 八幡浜+ 大洲+ 西予・愛媛蜜柑全国 2 位+ 1885 年伊予柑栽培開始 140+ 年+ 紅まどんな新品種 2005+ ジュース+ ジャム+ ジェラート派生・¥800-4,500)",
    title_ja: "伊予柑+温州蜜柑加工", romaji: "Iyokan Mikan",
    summary_zh: "**伊予柑+温州蜜柑加工品は愛媛全国 2 位+1885 年伊予柑栽培 140+ 年+紅まどんな新品種 2005+ジュース+ジャム+ジェラート**(松山+八幡浜+大洲+西予)。¥800-4,500。",
    content_md: "- 立地:**松山市 + 八幡浜市 + 大洲市 + 西予市**\n- 起源:**1885 年伊予柑栽培開始 140+ 年 + 紅まどんな新品種 2005**\n- 派生:**ジュース+ジャム+ジェラート → 全国百貨店流通**\n- 名店:**「えひめみかん協同組合」「JAえひめ南」「伊予八幡浜柑橘」 30+ 加工所**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["shopping_district"],
    lat: 33.8392, lon: 132.7655,
    season_start: "11-01", season_end: "02-28", event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["iyokan_citrus"], source: "manual",
  },
  {
    slug: "matsuyama-imotaki",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "松山いも炊き+ 秋祭り宴会料理(松山市・松山藩江戸期 1700 年代より秋祭り宴会料理 320+ 年+ さといも+ 鶏肉+ 干鱈+ 醤油味+ 河原で大鍋を囲む「いも炊き会」 → 松山秋祭り 10 月初旬最盛期+ 一族集まる季節料理・¥1,500-3,800)",
    title_ja: "松山いも炊き", romaji: "Matsuyama Imotaki",
    summary_zh: "**松山いも炊き+秋祭り宴会料理は江戸期 1700 年代より 320+ 年・さといも+鶏肉+干鱈+醤油味・河原大鍋「いも炊き会」秋祭り**(松山)。¥1,500-3,800。",
    content_md: "- 立地:**松山市重信川河原+ 道後温泉旅館**\n- 起源:**松山藩江戸期 1700 年代より秋祭り宴会料理 320+ 年**\n- 派生:**さといも+鶏肉+干鱈+醤油味 → 河原で大鍋を囲む「いも炊き会」 → 松山秋祭り 10 月初旬最盛期**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["restaurant_traditional"],
    lat: 33.8392, lon: 132.7655,
    season_start: "09-15", season_end: "11-15", event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["matsuyama_imotaki"], source: "manual",
  },
  {
    slug: "saijo-uchinuki-tofu",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "西条うちぬき水豆腐+ 名水豆腐料理(西条市・西条「うちぬき」 自噴湧水 環境省名水 100 選 1985+ 1300+ 年湧水伝承+ 大豆と名水で作る濃厚豆腐+ 湯豆腐+ 冷奴+ 豆腐田楽+ 西条祭り供物 1670+・¥800-2,500)",
    title_ja: "西条うちぬき豆腐", romaji: "Saijō Uchinuki Tofu",
    summary_zh: "**西条うちぬき水豆腐は環境省名水 100 選 1985+1300+ 年湧水伝承+大豆と名水で濃厚豆腐+湯豆腐+冷奴+豆腐田楽+西条祭り供物 1670+**(西条)。¥800-2,500。",
    content_md: "- 立地:**西条市本町・うちぬき広場**\n- 起源:**1300+ 年湧水伝承 + 環境省名水 100 選 1985**\n- 派生:**大豆と名水で作る濃厚豆腐 → 湯豆腐+冷奴+豆腐田楽 → 西条祭り供物 1670+**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "西条市", lg_code: "38206",
    area_types: ["restaurant_traditional"],
    lat: 33.9192, lon: 133.1809,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["saijo_uchinuki_tofu"], source: "manual",
  },
  {
    slug: "uwajima-satsuma-jiru",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "宇和島さつま汁+ 焼魚と麦味噌(宇和島市・宇和島藩江戸期 1700 年代より漁師家庭料理 320+ 年+ 焼魚すり身+ 麦味噌+ 出汁+ 麦飯にかけて食べる名物・四国八十八食認定+ 観光客向けに「ほづみ亭」 等で復刻提供・¥800-2,200)",
    title_ja: "宇和島さつま汁", romaji: "Uwajima Satsuma Jiru",
    summary_zh: "**宇和島さつま汁+焼魚と麦味噌は江戸期 1700 年代より 320+ 年・焼魚すり身+麦味噌+出汁+麦飯にかけ・四国八十八食認定**(宇和島)。¥800-2,200。",
    content_md: "- 立地:**宇和島市中央町・きさいや広場**\n- 起源:**宇和島藩江戸期 1700 年代より漁師家庭料理 320+ 年**\n- 派生:**焼魚すり身+麦味噌+出汁+麦飯にかけて食べる名物 → 観光客向けに「ほづみ亭」等で復刻提供**\n- 認定:**四国八十八食認定**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "宇和島市", lg_code: "38203",
    area_types: ["restaurant_traditional"],
    lat: 33.2235, lon: 132.5611,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["uwajima_satsuma_jiru"], source: "manual",
  },
  {
    slug: "matsuyama-tarte",
    category: "food", sub_type: "ehime_wagashi",
    title_zh: "松山一六タルト+ 柚子餡ロールカステラ(松山市+ 全県・1635 年松山藩主蒲生忠知ポルトガル系製法導入 390+ 年+ 一六本舗 1883 年創業 142+ 年+ ロールカステラ+ 柚子餡+ 駅弁+ 全国百貨店流通・¥800-3,200)",
    title_ja: "松山一六タルト", romaji: "Matsuyama Ichiroku Taruto",
    summary_zh: "**松山一六タルト+柚子餡ロールカステラは 1635 年ポルトガル系製法導入 390+ 年+一六本舗 1883 創業 142+ 年・柚子餡+駅弁+全国百貨店流通**(松山+全県)。¥800-3,200。",
    content_md: "- 立地:**松山市大街道・道後・松山駅+ 全県土産店**\n- 起源:**1635 年松山藩主蒲生忠知ポルトガル系製法導入 390+ 年 + 一六本舗 1883 年創業 142+ 年**\n- 派生:**ロールカステラ+柚子餡 → 駅弁+全国百貨店流通**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["shopping_district"],
    lat: 33.8392, lon: 132.7655,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["matsuyama_tarte_1635"], source: "manual",
  },
  {
    slug: "matsuyama-bocchan-dango",
    category: "food", sub_type: "ehime_wagashi",
    title_zh: "松山坊っちゃん団子+ 三色串団子(松山市道後・1895 夏目漱石「坊っちゃん」 連載小説に登場 130+ 年+ 抹茶+ 卵黄+ 小豆三色三段+ 道後温泉本館前+ 全国観光客代表土産+ 全県土産店流通・¥600-1,800)",
    title_ja: "松山坊っちゃん団子", romaji: "Matsuyama Bocchan Dango",
    summary_zh: "**松山坊っちゃん団子+三色串団子は 1895 漱石「坊っちゃん」 130+ 年・抹茶+卵黄+小豆三色三段+道後本館前**(松山道後)。¥600-1,800、全国観光客代表土産。",
    content_md: "- 立地:**松山市道後温泉本館前+ 大街道**\n- 起源:**1895 夏目漱石「坊っちゃん」連載小説に登場 130+ 年**\n- 派生:**抹茶+卵黄+小豆三色三段 → 道後温泉本館前+全国観光客代表土産**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["shopping_district"],
    lat: 33.8417, lon: 132.7864,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["matsuyama_bocchan_dango"], source: "manual",
  },
  {
    slug: "matsuyama-ronken-mantou",
    category: "food", sub_type: "ehime_wagashi",
    title_zh: "松山労研饅頭+ 蒸饅頭酒種(松山市・1931 年松山労働科学研究所考案 94+ 年+ 酒種発酵生地+ 大正期労働者の栄養食起源+ 国登録有形民俗候補・¥150-800)",
    title_ja: "松山労研饅頭", romaji: "Matsuyama Rōken Mantou",
    summary_zh: "**松山労研饅頭+蒸饅頭酒種は 1931 労働科学研究所 94+ 年・酒種発酵生地+大正期労働者の栄養食**(松山)。¥150-800、国登録有形民俗候補。",
    content_md: "- 立地:**松山市大街道・労研饅頭本舗**\n- 起源:**1931 年松山労働科学研究所考案 94+ 年**\n- 派生:**酒種発酵生地 → 大正期労働者の栄養食起源**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["shopping_district"],
    lat: 33.8392, lon: 132.7655,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["matsuyama_roken_mantou_1931"], source: "manual",
  },
  {
    slug: "uwajima-tai-somen",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "宇和島鯛そうめん+ 蒸し鯛素麺盛り(宇和島市・伊予水軍時代 1500 年代より宴会料理 500+ 年+ 蒸し鯛丸ごとに素麺盛り+ 椀盛り+ 結婚祝い席+ 観光客代表料理・四国八十八食認定・¥3,800-12,000)",
    title_ja: "宇和島鯛そうめん", romaji: "Uwajima Tai Sōmen",
    summary_zh: "**宇和島鯛そうめん+蒸し鯛素麺盛りは伊予水軍 1500 年代より 500+ 年・蒸し鯛丸ごとに素麺+結婚祝い席・四国八十八食認定**(宇和島)。¥3,800-12,000。",
    content_md: "- 立地:**宇和島市中央町・「ほづみ亭」「鯛や」**\n- 起源:**伊予水軍時代 1500 年代より宴会料理 500+ 年**\n- 派生:**蒸し鯛丸ごとに素麺盛り+椀盛り → 結婚祝い席+観光客代表料理**\n- 認定:**四国八十八食認定**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "宇和島市", lg_code: "38203",
    area_types: ["restaurant_traditional"],
    lat: 33.2235, lon: 132.5611,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["uwajima_tai_somen"], source: "manual",
  },
  {
    slug: "kamijima-lemon",
    category: "food", sub_type: "ehime_mikan",
    title_zh: "上島町レモン+ 国産レモン日本一(越智郡上島町・1985 年国産レモン栽培開始 40+ 年+ 全国生産首位+ 国産レモンジュース+ レモンケーキ+ レモン塩+ 上島町ふるさと納税代表+ JA瀬戸内+ しまなみ海道流通・¥800-3,500)",
    title_ja: "上島町レモン", romaji: "Kamijima Remon",
    summary_zh: "**上島町レモンは 1985 年栽培 40+ 年+全国生産首位・レモンジュース+ケーキ+塩+ふるさと納税代表+JA瀬戸内+しまなみ流通**(越智郡上島)。¥800-3,500。",
    content_md: "- 立地:**越智郡上島町岩城+ 弓削+ 生名+ 魚島**\n- 起源:**1985 年国産レモン栽培開始 40+ 年 + 全国生産首位**\n- 派生:**国産レモンジュース+レモンケーキ+レモン塩 → 上島町ふるさと納税代表 + JA瀬戸内+しまなみ海道流通**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "越智郡", municipality_ja: "上島町", lg_code: "38356",
    area_types: ["shopping_district"],
    lat: 34.2631, lon: 133.2017,
    season_start: "10-01", season_end: "01-31", event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kamijima_remon_1985"], source: "manual",
  },
  {
    slug: "imabari-yaki-buta-tama",
    category: "food", sub_type: "ehime_meat",
    title_zh: "今治焼豚玉子飯+ 焼豚と半熟卵丼(今治市・1950 年代造船所労働者向けに誕生 75+ 年+ 焼豚+ 半熟玉子+ 醤油味タレ+ 丼飯+ 「焼豚玉子飯の会」 認定店 30+ 軒・全国 B 級グルメ大会上位入賞・¥850-1,800)",
    title_ja: "今治焼豚玉子飯", romaji: "Imabari Yakibuta Tamago Meshi",
    summary_zh: "**今治焼豚玉子飯+焼豚と半熟卵丼は 1950 年代造船所労働者向け 75+ 年・焼豚+半熟玉子+醤油タレ+丼飯**(今治)。¥850-1,800、認定店 30+ 軒。",
    content_md: "- 立地:**今治市本町・大手町・港町**\n- 起源:**1950 年代造船所労働者向けに誕生 75+ 年**\n- 派生:**焼豚+半熟玉子+醤油味タレ+丼飯 → 「焼豚玉子飯の会」認定店 30+ 軒**\n- 大会:**全国 B 級グルメ大会上位入賞**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "今治市", lg_code: "38202",
    area_types: ["restaurant_traditional"],
    lat: 34.0660, lon: 132.9988,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["imabari_yakibuta_tamago"], source: "manual",
  },
  {
    slug: "matsuyama-gomoku-zushi",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "松山ずし+ 五目酢飯(松山市・松山藩江戸期 1700 年代より家庭料理伝承 320+ 年+ 五目具材酢飯+ 椎茸+ 干瓢+ 高野豆腐+ 紅生姜+ 祝い席+ 山岳寺院供物・¥1,200-2,800)",
    title_ja: "松山ずし", romaji: "Matsuyama Zushi",
    summary_zh: "**松山ずし+五目酢飯は江戸期 1700 年代より 320+ 年・五目具材+椎茸+干瓢+高野+紅生姜+祝い席+山岳寺院供物**(松山)。¥1,200-2,800。",
    content_md: "- 立地:**松山市本町+ 道後温泉旅館**\n- 起源:**松山藩江戸期 1700 年代より家庭料理伝承 320+ 年**\n- 派生:**五目具材酢飯+椎茸+干瓢+高野豆腐+紅生姜 → 祝い席+山岳寺院供物**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["restaurant_traditional"],
    lat: 33.8392, lon: 132.7655,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["matsuyama_gomoku_zushi"], source: "manual",
  },
  {
    slug: "uwajima-jakoten-noodle",
    category: "food", sub_type: "ehime_seafood",
    title_zh: "宇和島ちゃんぽん+ じゃこ天派生(宇和島+ 八幡浜・1950 年代漁師飯系誕生 75+ 年+ じゃこ天+ 中華麺+ 醤油豚骨スープ+ 八幡浜ちゃんぽんブランド+ 全国 B 級グルメ大会上位入賞・¥850-1,800)",
    title_ja: "宇和島ちゃんぽん", romaji: "Uwajima Chanpon",
    summary_zh: "**宇和島ちゃんぽん+じゃこ天派生は 1950 年代漁師飯系 75+ 年・じゃこ天+中華麺+醤油豚骨スープ+八幡浜ブランド・B 級大会上位**(宇和島+八幡浜)。¥850-1,800。",
    content_md: "- 立地:**宇和島市 + 八幡浜市**\n- 起源:**1950 年代漁師飯系誕生 75+ 年**\n- 派生:**じゃこ天+中華麺+醤油豚骨スープ → 八幡浜ちゃんぽんブランド**\n- 大会:**全国 B 級グルメ大会上位入賞**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "宇和島市", lg_code: "38203",
    area_types: ["restaurant_traditional"],
    lat: 33.2235, lon: 132.5611,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["uwajima_chanpon"], source: "manual",
  },
  {
    slug: "ozu-kawamatsuri-cuisine",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "大洲鵜飼料理+ 肱川川魚(大洲市・大洲藩江戸期 1635 年加藤貞泰公鵜飼観光 390+ 年+ 鵜飼漁の鮎料理+ 鮎塩焼+ 鵜飼観覧船料理+ 国登録有形民俗候補+ 7-9 月期限定+ 国指定鵜飼地・¥4,500-12,000)",
    title_ja: "大洲鵜飼料理", romaji: "Ōzu Ukai Cuisine",
    summary_zh: "**大洲鵜飼料理+肱川川魚は江戸期 1635 加藤貞泰公観光 390+ 年・鮎塩焼+鵜飼観覧船料理・7-9 月限定・国登録有形民俗候補+国指定鵜飼地**(大洲)。¥4,500-12,000。",
    content_md: "- 立地:**大洲市肱川+ 鵜飼観覧船**\n- 起源:**大洲藩江戸期 1635 年加藤貞泰公鵜飼観光 390+ 年**\n- 派生:**鵜飼漁の鮎料理+鮎塩焼+鵜飼観覧船料理 → 7-9 月期限定**\n- 認定:**国登録有形民俗候補 + 国指定鵜飼地**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "大洲市", lg_code: "38207",
    area_types: ["restaurant_traditional"],
    lat: 33.5061, lon: 132.5461,
    season_start: "07-01", season_end: "09-20", event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 7, closed_days: [],
    external_urls: {}, tags: ["ozu_ukai"], source: "manual",
  },
  {
    slug: "kuma-kogen-yamaimo",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "久万高原じゃがいも+ 山地野菜(上浮穴郡久万高原町・標高 800m 寒暖差栽培+ 1950 年代以降高原野菜栽培 70+ 年+ じゃがいも+ 山ぶどう+ 山菜・道の駅天空農園+ 県内地産地消代表・¥600-2,500)",
    title_ja: "久万高原じゃがいも", romaji: "Kuma Kōgen Jagaimo",
    summary_zh: "**久万高原じゃがいも+山地野菜は標高 800m 寒暖差+1950 年代以降 70+ 年・じゃがいも+山ぶどう+山菜・道の駅天空農園**(上浮穴郡久万高原)。¥600-2,500。",
    content_md: "- 立地:**上浮穴郡久万高原町・道の駅天空農園**\n- 起源:**標高 800m 寒暖差栽培 + 1950 年代以降高原野菜栽培 70+ 年**\n- 派生:**じゃがいも+山ぶどう+山菜 → 県内地産地消代表**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "上浮穴郡", municipality_ja: "久万高原町", lg_code: "38386",
    area_types: ["shopping_district"],
    lat: 33.6562, lon: 132.9011,
    season_start: "06-15", season_end: "10-31", event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kuma_kogen_jagaimo"], source: "manual",
  },
  {
    slug: "ainan-katsuo-tataki",
    category: "food", sub_type: "ehime_seafood",
    title_zh: "愛南鰹のたたき+ 宇和海鰹(南宇和郡愛南町・宇和海漁港 1700 年代より漁師飯系 320+ 年+ 鰹を藁で炙り+ にんにく+ ねぎ+ ポン酢+ 高知県境界共通文化+ 国産鰹消費首位地域・¥1,500-3,800)",
    title_ja: "愛南鰹のたたき", romaji: "Ainan Katsuo Tataki",
    summary_zh: "**愛南鰹のたたき+宇和海鰹は 1700 年代より 320+ 年・藁炙り+にんにく+ねぎ+ポン酢+高知県境界共通+国産鰹消費首位**(南宇和郡愛南)。¥1,500-3,800。",
    content_md: "- 立地:**南宇和郡愛南町深浦+ 御荘**\n- 起源:**宇和海漁港 1700 年代より漁師飯系 320+ 年**\n- 派生:**鰹を藁で炙り+にんにく+ねぎ+ポン酢 → 高知県境界共通文化+国産鰹消費首位地域**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "南宇和郡", municipality_ja: "愛南町", lg_code: "38506",
    area_types: ["restaurant_traditional"],
    lat: 32.9617, lon: 132.5814,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["ainan_katsuo_tataki"], source: "manual",
  },
  {
    slug: "iyo-ikegaiyaki",
    category: "food", sub_type: "ehime_seafood",
    title_zh: "伊予いけ貝焼き+ 宇和海特産(伊予市+ 西予市・宇和海特産いけ貝(平貝)漁業 1700 年代より 320+ 年+ いけ貝塩焼+ いけ貝刺身+ 伊予水軍時代より宴会料理+ 西予市三瓶港地産・¥1,500-4,500)",
    title_ja: "伊予いけ貝焼き", romaji: "Iyo Ikegai Yaki",
    summary_zh: "**伊予いけ貝焼きは宇和海特産+1700 年代より 320+ 年・塩焼+刺身+伊予水軍宴会料理+西予三瓶港地産**(伊予+西予)。¥1,500-4,500。",
    content_md: "- 立地:**伊予市港町+ 西予市三瓶**\n- 起源:**宇和海特産いけ貝(平貝)漁業 1700 年代より 320+ 年**\n- 派生:**いけ貝塩焼+いけ貝刺身 → 伊予水軍時代より宴会料理 + 西予市三瓶港地産**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "伊予市", lg_code: "38210",
    area_types: ["restaurant_traditional"],
    lat: 33.7531, lon: 132.7050,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["iyo_ikegai"], source: "manual",
  },
  {
    slug: "shikokuchuo-paper-tea",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "四国中央市紙の郷茶+ 川之江+ 伊予三島茶(四国中央市・川之江紙業 1700 年代より茶栽培 320+ 年+ 伊予三島地産茶+ 紙工業地と茶産地共生+ 「紙のまち」博物館併設・¥600-2,200)",
    title_ja: "四国中央市茶", romaji: "Shikokuchūō Cha",
    summary_zh: "**四国中央市紙の郷茶+川之江+伊予三島茶は 1700 年代より 320+ 年・紙工業地と茶産地共生+「紙のまち」博物館併設**(四国中央)。¥600-2,200。",
    content_md: "- 立地:**四国中央市川之江+ 伊予三島**\n- 起源:**川之江紙業 1700 年代より茶栽培 320+ 年**\n- 派生:**伊予三島地産茶 → 紙工業地と茶産地共生 + 「紙のまち」博物館併設**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "四国中央市", lg_code: "38213",
    area_types: ["shopping_district"],
    lat: 33.9786, lon: 133.5494,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shikokuchuo_cha"], source: "manual",
  },
  {
    slug: "uchiko-wax-cuisine",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "内子和ろうそく料理+ 木蝋鶏鍋(喜多郡内子町・1804 年木蝋業興隆 220+ 年+ 国指定重要伝統的建造物群保存地区 1982 + 内子座 1916 復元 109+ 年+ 鶏鍋+ 麦味噌+ 季節野菜+ 観光客向け復刻提供・¥1,500-3,500)",
    title_ja: "内子和ろうそく料理", romaji: "Uchiko Wagosoku",
    summary_zh: "**内子和ろうそく料理+木蝋鶏鍋は 1804 木蝋業 220+ 年・国指定伝建群 1982+内子座 1916 復元 109+ 年・鶏鍋+麦味噌+季節野菜**(喜多郡内子)。¥1,500-3,500。",
    content_md: "- 立地:**喜多郡内子町本町・八日市護国地区**\n- 起源:**1804 年木蝋業興隆 220+ 年 + 国指定重要伝統的建造物群保存地区 1982 + 内子座 1916 復元 109+ 年**\n- 派生:**鶏鍋+麦味噌+季節野菜 → 観光客向け復刻提供**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "喜多郡", municipality_ja: "内子町", lg_code: "38422",
    area_types: ["restaurant_traditional"],
    lat: 33.5400, lon: 132.6586,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["uchiko_wagosoku"], source: "manual",
  },
  {
    slug: "tobe-yaki-utsuwa-cuisine",
    category: "food", sub_type: "ehime_kyodo",
    title_zh: "砥部焼器懐石+ 砥部焼料理店(伊予郡砥部町・1777 年砥部焼開窯 248+ 年+ 国指定伝統的工芸品 1976+ 砥部焼器で楽しむ懐石+ 砥部焼陶芸の里+ 国登録有形民俗候補・¥4,500-12,000)",
    title_ja: "砥部焼器懐石", romaji: "Tobe Yaki Kaiseki",
    summary_zh: "**砥部焼器懐石+砥部焼料理店は 1777 年開窯 248+ 年・国指定伝統工芸 1976+砥部焼器懐石+陶芸の里**(伊予郡砥部)。¥4,500-12,000、国登録候補。",
    content_md: "- 立地:**伊予郡砥部町・砥部焼陶芸の里**\n- 起源:**1777 年砥部焼開窯 248+ 年 + 国指定伝統的工芸品 1976**\n- 派生:**砥部焼器で楽しむ懐石 → 砥部焼陶芸の里 + 国登録有形民俗候補**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "伊予郡", municipality_ja: "砥部町", lg_code: "38402",
    area_types: ["restaurant_traditional"],
    lat: 33.7344, lon: 132.7872,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 7, closed_days: [],
    external_urls: {}, tags: ["tobe_yaki_kaiseki_1777"], source: "manual",
  },
  {
    slug: "saijo-isoshigi-fish",
    category: "food", sub_type: "ehime_seafood",
    title_zh: "西条いかなご+ 春いかなご漁(西条市・瀬戸内海春いかなご漁 1700 年代より 320+ 年+ 釜揚げいかなご+ 醤油佃煮+ 春先 3-4 月期限定+ 県内地産地消代表+ JAえひめ流通・¥800-2,500)",
    title_ja: "西条いかなご", romaji: "Saijō Ikanago",
    summary_zh: "**西条いかなご+春いかなご漁は 1700 年代より 320+ 年・釜揚げ+醤油佃煮+3-4 月期限定+JAえひめ流通**(西条)。¥800-2,500。",
    content_md: "- 立地:**西条市港町+ 道の駅**\n- 起源:**瀬戸内海春いかなご漁 1700 年代より 320+ 年**\n- 派生:**釜揚げいかなご+醤油佃煮 → 春先 3-4 月期限定 + 県内地産地消代表**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "西条市", lg_code: "38206",
    area_types: ["shopping_district"],
    lat: 33.9192, lon: 133.1809,
    season_start: "03-01", season_end: "04-30", event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["saijo_ikanago"], source: "manual",
  },
];

seedMain(rows, "ehime-food-r1");
