// Seed 福島県 衣 R1(18 筆 / Sprint 1.2)
// 会津漆器+本郷焼 4 / 大堀相馬焼+陶器 2 / 三春駒+赤べこ 3 / こけし+提灯 2 / 商店街+百貨店 5 / ご当地キャラ 2 = 18

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "tohoku"; prefecture_ja: "福島県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 会津漆器+本郷焼 (4)
  { slug: "aizu-lacquer-1590", category: "fashion", sub_type: "fukushima_aizu_lacquer", title_zh: "会津漆器(会津若松市・1590 蒲生氏郷 入封 産業奨励起源 435 年+ 国指定伝統的工芸品 1975+ 会津塗代表+ 椀+盆+小箱+茶道具+ R1 食 こづゆ 漆椀提供連動+ 老舗 5+ 軒+ ¥8,500-180,000)", title_ja: "会津漆器", romaji: "Aizu Shikki", summary_zh: "**会津漆器は 1590 蒲生氏郷入封産業奨励起源 435 年**(会津若松・**国指定伝統的工芸品 1975**)。会津塗代表、R1 食 こづゆ漆椀連動、老舗 5+ 軒、¥8,500-180,000。", content_md: "- 立地:**会津若松市**\n- 起源:**1590 蒲生氏郷入封産業奨励起源 435 年**\n- 認定:**国指定伝統的工芸品 1975**\n- 構成:**椀 + 盆 + 小箱 + 茶道具**\n- 関連:**R1 食 こづゆ漆椀提供連動**\n- 価格:**¥8,500-180,000**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["craft_workshop", "industrial_heritage"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aizu_shikki", "1590_gamou_ujisato", "1975_dento", "435_years"], source: "manual" },
  { slug: "aizu-hongo-yaki-1593", category: "fashion", sub_type: "fukushima_aizu_lacquer", title_zh: "会津本郷焼(会津美里町・1593 蒲生氏郷期発祥 432 年+ 国指定伝統的工芸品 1993+ 東北最古陶器産地+ 「ニシン鉢」代表+ R1 食 ニシン山椒漬け関連+ ¥3,500-35,000+ 老舗 8+ 窯)", title_ja: "会津本郷焼", romaji: "Aizu Hongō Yaki", summary_zh: "**会津本郷焼は 1593 蒲生氏郷期 432 年・東北最古陶器産地**(会津美里・**国指定伝統的工芸品 1993**)。「ニシン鉢」代表、R1 食 ニシン山椒漬け関連、¥3,500-35,000。", content_md: "- 立地:**大沼郡会津美里町**\n- 起源:**1593 蒲生氏郷期発祥 432 年**\n- 認定:**国指定伝統的工芸品 1993 + 東北最古陶器産地**\n- 看板:**「ニシン鉢」代表(R1 食 ニシン山椒漬け関連)**\n- 価格:**¥3,500-35,000**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "大沼郡", municipality_ja: "会津美里町", lg_code: "07447", area_types: ["craft_workshop"], lat: 37.5219, lon: 139.8164, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aizu_hongo_yaki", "1593", "1993_dento", "tohoku_oldest_pottery"], source: "manual" },
  { slug: "aizu-momen", category: "fashion", sub_type: "fukushima_aizu_lacquer", title_zh: "会津木綿(会津若松市・江戸期 1600 年代発祥+ 県重要無形文化財+ 自然藍染+紅花染 縞模様+ 着物+反物+小物+ R1 衣 米沢織(山形・共有東北織物文化)+ 老舗 工房 3+ 軒+ ¥15,000-150,000)", title_ja: "会津木綿", romaji: "Aizu Momen", summary_zh: "**会津木綿は江戸期 1600 年代発祥**(会津若松・**県重要無形文化財**)。自然藍染+紅花染縞模様、R1 衣 米沢織と並ぶ東北織物、¥15,000-150,000。", content_md: "- 立地:**会津若松市**\n- 起源:**江戸期 1600 年代発祥**\n- 認定:**県重要無形文化財**\n- 構成:**自然藍染 + 紅花染 縞模様**\n- 並列:**R1 衣 米沢織(山形)と並ぶ東北織物文化**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["craft_workshop"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aizu_momen", "edo_origin"], source: "manual" },
  { slug: "aizu-kiri-tansu", category: "fashion", sub_type: "fukushima_aizu_lacquer", title_zh: "会津桐箪笥(会津若松市・1611 蒲生秀行期発祥+ 県伝統工芸品+ 桐木地+漆塗+ R1 衣 仙台箪笥(宮城)・米沢織と並ぶ東北家具老舗+ 老舗工房 3+ 軒+ 1 棹 ¥250,000-1,200,000)", title_ja: "会津桐箪笥", romaji: "Aizu Kiri Tansu", summary_zh: "**会津桐箪笥は 1611 蒲生秀行期発祥**(会津若松・**県伝統工芸品**)。桐木地+漆塗、R1 衣 仙台箪笥+米沢織と並ぶ東北家具老舗、¥250,000-1,200,000。", content_md: "- 立地:**会津若松市**\n- 起源:**1611 蒲生秀行期発祥**\n- 認定:**県伝統工芸品**\n- 構成:**桐木地 + 漆塗**\n- 並列:**R1 衣 仙台箪笥(宮城) + 会津桐箪笥 = 東北家具老舗**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["craft_workshop"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aizu_kiri_tansu", "1611_gamou_hideyuki"], source: "manual" },

  // 大堀相馬焼+陶器 (2)
  { slug: "ohori-soma-yaki-1690", category: "fashion", sub_type: "fukushima_imono", title_zh: "大堀相馬焼(浪江町大堀・1690 江戸期発祥 335 年+ 国指定伝統的工芸品 1978+ 「青ひび」貫入+「走り駒」絵代表+ 2011 震災後双葉郡西郷村等避難復興+ 「相馬焼陶芸の杜」復興拠点+ ¥3,500-50,000)", title_ja: "大堀相馬焼", romaji: "Ōbori Sōma Yaki", summary_zh: "**大堀相馬焼は 1690 江戸期 335 年・国指定伝統的工芸品 1978**(浪江町大堀・**「青ひび」貫入+「走り駒」絵**)。2011 震災後復興拠点、¥3,500-50,000。", content_md: "- 立地:**双葉郡浪江町大堀**\n- 起源:**1690 江戸期発祥 335 年**\n- 認定:**国指定伝統的工芸品 1978**\n- 看板:**「青ひび」貫入 + 「走り駒」絵代表**\n- 縁:**2011 震災後双葉郡西郷村等避難復興・「相馬焼陶芸の杜」復興拠点**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "双葉郡", municipality_ja: "浪江町", lg_code: "07547", area_types: ["craft_workshop", "industrial_heritage"], lat: 37.4861, lon: 140.9986, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ohori_soma", "1690", "335_years", "1978_dento", "post_disaster"], source: "manual" },
  { slug: "miharu-uma-doll-1600", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "三春駒+三春人形(田村郡三春町・江戸期 1600 年代 三春藩献上民芸+ 県重要無形民俗+ 木彫り馬玩具+紙張子人形+ R1 食 ままどおる三万石(三春)地場+ 道の駅+全国百貨店流通+ ¥1,500-8,000)", title_ja: "三春駒+三春人形", romaji: "Miharu Koma / Miharu Ningyō", summary_zh: "**三春駒+三春人形は江戸期 1600 年代三春藩献上民芸**(三春町・**県重要無形民俗**)。木彫り馬+紙張子、R1 食 ままどおる地場、¥1,500-8,000。", content_md: "- 立地:**田村郡三春町**\n- 起源:**江戸期 1600 年代 三春藩献上民芸**\n- 認定:**県重要無形民俗**\n- 構成:**木彫り馬玩具 + 紙張子人形**\n- 並列:**R1 食 ままどおる三万石(三春)地場**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "田村郡", municipality_ja: "三春町", lg_code: "07521", area_types: ["craft_workshop"], lat: 37.4444, lon: 140.4842, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["miharu_koma", "edo_1600s", "miharu_ningyo"], source: "manual" },

  // 赤べこ (3)
  { slug: "akabeko-aizu-1611", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "赤べこ(会津若松市+柳津町・807 平安期発祥伝説 1218 年+ 1611 会津地震復興時 民間信仰由来+ 紙張子赤牛人形+ 県重要無形民俗+ 「魔除け」+「子供守り」全国知名度高+ 道の駅+全国百貨店+ ¥800-3,500)", title_ja: "赤べこ", romaji: "Akabeko", summary_zh: "**赤べこは 807 平安期発祥伝説 1218 年・1611 会津地震復興民間信仰**(会津+柳津・**県重要無形民俗**)。「魔除け」+「子供守り」全国知名度、道の駅+百貨店、¥800-3,500。", content_md: "- 立地:**会津若松市 + 河沼郡柳津町**\n- 起源:**807 平安期発祥伝説 + 1611 会津地震復興時 民間信仰**\n- 認定:**県重要無形民俗**\n- 構成:**紙張子赤牛人形**\n- 信仰:**「魔除け」 + 「子供守り」全国知名度高**\n- 価格:**¥800-3,500**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["craft_workshop"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["akabeko", "807_heian", "1611_aizu_eqk", "yakuyoke"], source: "manual" },
  { slug: "okiagari-koboshi", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "起き上がり小法師(会津若松市・江戸期 1600 年代 会津藩献上正月縁起物+ 県重要無形民俗+ 紙張子人形・「七転八起」縁起物+ R1 衣 赤べこ と並ぶ会津 2 大民芸+ 道の駅+全国百貨店流通+ ¥600-2,500)", title_ja: "起き上がり小法師", romaji: "Okiagari Kobōshi", summary_zh: "**起き上がり小法師は江戸期 1600 年代会津藩献上正月縁起**(会津若松・**県重要無形民俗・「七転八起」**)。R1 衣 赤べこと並ぶ会津 2 大民芸、¥600-2,500。", content_md: "- 立地:**会津若松市**\n- 起源:**江戸期 1600 年代 会津藩献上正月縁起物**\n- 認定:**県重要無形民俗**\n- 構成:**紙張子人形・「七転八起」縁起物**\n- 並列:**R1 衣 赤べこ + 起き上がり小法師 = 会津 2 大民芸**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["craft_workshop"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["okiagari_koboshi", "edo_aizu", "shichi_ten_hakki"], source: "manual" },
  { slug: "aizu-rose-no-fude", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "会津絵ろうそく(会津若松市・1590 蒲生氏郷期 産業奨励 起源 435 年+ 県重要無形文化財+ 木蝋ろうそく + 手描花絵+ R1 食 こづゆ漆椀観光と組合せ+ 老舗 工房 5+ 軒+ ¥800-3,500/本)", title_ja: "会津絵ろうそく", romaji: "Aizu E-rōsoku", summary_zh: "**会津絵ろうそくは 1590 蒲生氏郷期 産業奨励起源 435 年**(会津若松・**県重要無形文化財**)。木蝋ろうそく+手描花絵、老舗工房 5+ 軒、¥800-3,500/本。", content_md: "- 立地:**会津若松市**\n- 起源:**1590 蒲生氏郷期 産業奨励起源 435 年**\n- 認定:**県重要無形文化財**\n- 構成:**木蝋ろうそく + 手描花絵**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["craft_workshop"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aizu_e_rosoku", "1590", "435_years"], source: "manual" },

  // こけし+提灯 (2)
  { slug: "tsuchiyu-kokeshi-fukushima", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "土湯系こけし(福島市土湯+二本松市岳・全国 11 系統こけしの一・福島側起源+ R1 衣 鳴子+遠刈田+作並系統(宮城・山形)と並ぶ+ 江戸期 1700 年代発祥+ 国指定伝統的工芸品 1981+ 1 体 ¥1,500-6,000)", title_ja: "土湯系こけし", romaji: "Tsuchiyu Kokeshi", summary_zh: "**土湯系こけしは全国 11 系統・福島側起源**(福島市土湯+二本松岳・**江戸期 1700 年代+国指定伝統的工芸品 1981**)。R1 衣 鳴子+遠刈田+作並系統と並ぶ。", content_md: "- 立地:**福島市土湯 + 二本松市岳**\n- 起源:**江戸期 1700 年代発祥**\n- 認定:**国指定伝統的工芸品 1981**\n- 並列:**全国 11 系統(山形 R1 衣 土湯系・福島側起源)**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["craft_workshop"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsuchiyu_kokeshi", "1700s", "1981_dento", "fukushima_origin"], source: "manual" },
  { slug: "nihonmatsu-chouchin", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "二本松提灯(二本松市・江戸期 二本松藩献上+ R1 楽 二本松提灯祭り 国指定 1968 由来+ 紙提灯+和紙+竹+ 道の駅+物産店流通+ ¥800-15,000+ 観光土産代表)", title_ja: "二本松提灯", romaji: "Nihonmatsu Chōchin", summary_zh: "**二本松提灯は江戸期二本松藩献上**(二本松市・**R1 楽 二本松提灯祭り 国指定 1968 由来**)。紙提灯+和紙+竹、道の駅+物産店、¥800-15,000。", content_md: "- 立地:**二本松市**\n- 起源:**江戸期 二本松藩献上**\n- 関連:**R1 楽 二本松提灯祭り 国指定 1968 由来**\n- 構成:**紙提灯 + 和紙 + 竹**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "二本松市", lg_code: "07210", area_types: ["craft_workshop"], lat: 37.5847, lon: 140.4314, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["nihonmatsu_chouchin", "edo_origin"], source: "manual" },

  // 商店街+百貨店 (5)
  { slug: "fukushima-station-spal-1981", category: "fashion", sub_type: "fukushima_dept_store", title_zh: "JR 福島駅 S-PAL+エスパル(JR 福島駅構内・1981 開業+ 全 80+ 店舗+ R1 食 桃あかつき+喜多方ラーメン+ままどおる+薄皮饅頭 集約販売+ 観光土産集中拠点+ JR 福島駅 1982 東北新幹線連動)", title_ja: "JR 福島駅 S-PAL", romaji: "JR Fukushima S-PAL", summary_zh: "**JR 福島駅 S-PAL は 1981 開業**(構内・**全 80+ 店舗**)。R1 食 桃+喜多方ラーメン+ままどおる+薄皮饅頭集約、観光土産集中、東北新幹線連動。", content_md: "- 立地:**JR 福島駅構内**\n- 起源:**1981 開業 44 年**\n- 規模:**全 80+ 店舗**\n- 並列:**R1 食 桃あかつき + 喜多方ラーメン + ままどおる + 薄皮饅頭 集約販売**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["shopping_district", "transit_hub"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["fukushima_spal", "1981", "80_stores"], source: "manual" },
  { slug: "koriyama-eki-shopping-pivot", category: "fashion", sub_type: "fukushima_dept_store", title_zh: "JR 郡山駅+エスパル郡山(JR 郡山駅構内・1996 開業+ 全 60+ 店舗+ R1 食 薄皮饅頭(柏屋 1852 県内最古菓子)+ ままどおる(三万石 三春)+ 銘菓集約+ 観光土産集中拠点+ R1 行 東北新幹線郡山駅連動)", title_ja: "JR 郡山駅+エスパル郡山", romaji: "JR Kōriyama Espal", summary_zh: "**JR 郡山駅+エスパル郡山は 1996 開業**(全 60+ 店舗・**R1 食 薄皮饅頭+ままどおる+銘菓集約**)。観光土産集中、東北新幹線郡山駅連動。", content_md: "- 立地:**JR 郡山駅構内**\n- 起源:**1996 開業**\n- 規模:**全 60+ 店舗**\n- 並列:**R1 食 薄皮饅頭(柏屋 1852)+ ままどおる(三万石 三春)+ 銘菓集約**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "郡山市", lg_code: "07203", area_types: ["shopping_district", "transit_hub"], lat: 37.4006, lon: 140.3597, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["koriyama_espal", "1996", "60_stores"], source: "manual" },
  { slug: "aizu-nanokamachi-dori", category: "fashion", sub_type: "fukushima_dept_store", title_zh: "会津若松七日町通り(会津若松市・1590 蒲生氏郷 城下町形成 435 年+ 全長 600m アーケード商店街+ 大正レトロ建築群+ R1 衣 会津漆器+赤べこ+起き上がり小法師 老舗 30+ 軒+ R1 食 馬刺し+ソースカツ丼観光客必訪)", title_ja: "会津若松七日町通り", romaji: "Aizu Nanokamachi Dōri", summary_zh: "**会津若松七日町通りは 1590 蒲生氏郷城下町 435 年**(全長 600m+大正レトロ)。R1 衣 漆器+赤べこ+小法師老舗 30+ 軒、R1 食 馬刺し+ソースカツ丼観光必訪。", content_md: "- 立地:**会津若松市**\n- 起源:**1590 蒲生氏郷 城下町形成 435 年**\n- 規模:**全長 600m アーケード + 大正レトロ建築群**\n- 並列:**R1 衣 会津漆器 + 赤べこ + 起き上がり小法師 老舗 30+ 軒**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["shopping_district", "history_site_castle"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["nanokamachi", "1590", "600m", "30_stores"], source: "manual" },
  { slug: "kitakata-zo-shopping", category: "fashion", sub_type: "fukushima_dept_store", title_zh: "喜多方蔵造り街並み商店街(喜多方市・江戸-明治期 蔵造り建築 4,000+ 棟・全国蔵建築密度 No.1+ 重伝建候補+ R1 食 喜多方ラーメン 120+ 軒沿道+ 観光客 SNS 拡散代表+ 全長 1.5km 街区)", title_ja: "喜多方蔵造り街並み", romaji: "Kitakata Kura-zukuri", summary_zh: "**喜多方蔵造り街並みは江戸-明治期 4,000+ 棟・全国蔵建築密度 No.1**(喜多方・**重伝建候補**)。R1 食 ラーメン 120+ 軒沿道、SNS 拡散、1.5km。", content_md: "- 立地:**喜多方市**\n- 起源:**江戸-明治期 蔵造り建築 4,000+ 棟**\n- 認定:**全国蔵建築密度 No.1 + 重伝建候補**\n- 規模:**全長 1.5km 街区**\n- 並列:**R1 食 喜多方ラーメン 120+ 軒沿道**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "喜多方市", lg_code: "07208", area_types: ["shopping_district", "history_site_castle"], lat: 37.6500, lon: 139.8742, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kitakata_kura", "4000_buildings", "no1_density"], source: "manual" },
  { slug: "uchijuku-souvenir-edo", category: "fashion", sub_type: "fukushima_dept_store", title_zh: "大内宿土産物店街(南会津郡下郷町・R1 育 大内宿 1640 江戸宿場町 重伝建 1981 派生・全 30+ 軒土産店+ そば+焼き餅+地酒+郷土民芸品+ 江戸期茅葺街並み・全国 SNS 拡散観光客必訪+ ¥350-3,500)", title_ja: "大内宿土産物店街", romaji: "Ōuchijuku Souvenir", summary_zh: "**大内宿土産物店街は R1 育 1640 江戸宿場 重伝建 1981 派生**(下郷町・**全 30+ 軒+江戸期茅葺街並み**)。そば+焼き餅+地酒+郷土民芸、SNS 拡散、¥350-3,500。", content_md: "- 立地:**南会津郡下郷町大内宿**(R1 育 大内宿)\n- 関係:**R1 育 大内宿 1640 江戸宿場町 重伝建 1981 派生**\n- 規模:**全 30+ 軒土産店**\n- 構成:**そば + 焼き餅 + 地酒 + 郷土民芸品**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "南会津郡", municipality_ja: "下郷町", lg_code: "07362", area_types: ["shopping_district", "history_site_castle"], lat: 37.3258, lon: 139.8606, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ouchijuku_souvenir", "30_stores"], source: "manual" },

  // ご当地キャラ (2)
  { slug: "fukushima-kibitan-mascot", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "キビタン(福島県観光物産協会マスコット・1995 開発+ 県鳥キビタキモチーフ+ ぬいぐるみ+T シャツ+文具+ JR 福島駅+郡山駅売店 + 県物産店全域+ ¥500-3,500+ 観光客向け県土産代表)", title_ja: "キビタン", romaji: "Kibitan", summary_zh: "**キビタンは福島県観光物産協会マスコット**(1995 開発・**県鳥キビタキモチーフ**)。ぬいぐるみ+T シャツ+文具、福島駅+郡山駅売店、¥500-3,500、県土産代表。", content_md: "- 全域:**福島県全域**\n- 起源:**1995 開発**\n- 縁:**県鳥キビタキモチーフ**\n- 構成:**ぬいぐるみ + T シャツ + 文具**\n- 価格:**¥500-3,500**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["shopping_district"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kibitan", "1995", "kibitaki"], source: "manual" },
  { slug: "fukushima-byakkotai-goods", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "白虎隊グッズ・武者キャラクター(会津若松市・R1 育 飯盛山白虎隊 1868 戊辰戦争派生・武者ぬいぐるみ+鎧フィギュア+ T シャツ+文具+ 白虎隊記念館 物販+ ¥800-5,500+ 観光武将ファン+歴史ファン代表)", title_ja: "白虎隊グッズ", romaji: "Byakkotai Goods", summary_zh: "**白虎隊グッズは R1 育 飯盛山白虎隊 1868 戊辰戦争派生**(会津・**武者ぬいぐるみ+鎧フィギュア+T シャツ**)。白虎隊記念館物販、¥800-5,500、武将+歴史ファン代表。", content_md: "- 立地:**会津若松市**(R1 育 飯盛山白虎隊)\n- 関係:**R1 育 飯盛山白虎隊 1868 戊辰戦争派生**\n- 構成:**武者ぬいぐるみ + 鎧フィギュア + T シャツ + 文具**\n- 価格:**¥800-5,500**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["shopping_district"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["byakkotai_goods", "1868_boshin"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[fukushima-fashion-r1] 尚無條目"); return; }
  console.log(`[fukushima-fashion-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[fukushima-fashion-r1] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[fukushima-fashion-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[fukushima-fashion-r1] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
