// Seed 群馬県 育 R1(21 筆 / Sprint 1.4)
// 富岡製糸 UNESCO+谷川岳+草津湯畑+伊香保石段+榛名+赤城+妙義 三山+ etc

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "群馬県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  { slug: "tomioka-silk-mill-1872", category: "culture", sub_type: "gunma_shrine_temple", title_zh: "富岡製糸場(富岡市・明治 5 年 1872 創業 153 年+ 日本初官営製糸場・国宝 3 棟+重要文化財・2014 UNESCO 世界遺産「富岡製糸場と絹産業遺産群」・近代化産業遺産+ 入場 ¥1,000+ 国際観光客代表)", title_ja: "富岡製糸場", romaji: "Tomioka Silk Mill", summary_zh: "**富岡製糸場は明治 5 年 1872 創業 153 年・日本初官営製糸場・国宝 3 棟・2014 UNESCO 世界遺産**(富岡・**近代化産業遺産**)。¥1,000、国際観光客代表。", content_md: "- 立地:**富岡市**\n- 起源:**明治 5 年 1872 創業 153 年**\n- 認定:**日本初官営製糸場 + 国宝 3 棟 + 重要文化財 + 2014 UNESCO 世界遺産**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "富岡市", lg_code: "10210", area_types: ["industrial_heritage", "history_site_castle"], lat: 36.2575, lon: 138.8939, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tomioka_silk_mill", "1872", "153_years", "unesco_2014"], source: "manual" },
  { slug: "tanigawa-dake-1977m", category: "culture", sub_type: "gunma_outdoor", title_zh: "谷川岳(利根郡みなかみ町・標高 1977m+ 日本百名山+ 「魔の山」世界登山遭難最多記録・国指定天然記念物+ R1 行 谷川岳ロープウェイ標高 1319m まで+ 5-10 月登山+ R1 住 水上温泉郷観光連動・入場無料)", title_ja: "谷川岳", romaji: "Tanigawa-dake", summary_zh: "**谷川岳は標高 1977m・日本百名山・「魔の山」世界登山遭難最多記録**(みなかみ・**国指定天然記念物**)。R1 行 ロープウェイ 1319m、5-10 月登山、R1 住 水上連動、無料。", content_md: "- 立地:**利根郡みなかみ町**\n- 規模:**標高 1977m**\n- 認定:**日本百名山 + 「魔の山」世界登山遭難最多記録 + 国指定天然記念物**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["scenic_spot"], lat: 36.8364, lon: 139.0125, season_start: "2026-05-01", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tanigawa_dake", "1977m", "japan_100"], source: "manual" },
  { slug: "kusatsu-yubatake-source", category: "culture", sub_type: "gunma_outdoor", title_zh: "草津湯畑(吾妻郡草津町・推定 1500+ 年湯治場+ 自然湧出量 No.1 毎分 4 万 L 源泉中核+ 草津温泉観光中核・夜間ライトアップ+ 入場無料・「日本一の湯」称号+ 海外観光客 SNS 拡散代表+ R1 住 草津温泉観光中核)", title_ja: "草津湯畑", romaji: "Kusatsu Yubatake", summary_zh: "**草津湯畑は推定 1500+ 年湯治場・自然湧出量 No.1 毎分 4 万 L 源泉中核**(草津・**「日本一の湯」称号**)。夜間ライトアップ、無料、海外 SNS 拡散代表、R1 住 草津温泉観光中核。", content_md: "- 立地:**吾妻郡草津町**\n- 起源:**推定 1500+ 年湯治場**\n- 認定:**自然湧出量 No.1 毎分 4 万 L 源泉中核 + 「日本一の湯」称号**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["scenic_spot", "onsen_field"], lat: 36.6228, lon: 138.5969, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kusatsu_yubatake", "no1_volume"], source: "manual" },
  { slug: "ikaho-ishidan-365", category: "culture", sub_type: "gunma_outdoor", title_zh: "伊香保 365 段石段街(渋川市伊香保・1903 大正期改修・全長 300m+ 365 段石段+ R1 住 伊香保温泉派生中核・上から伊香保神社+ 月の輪+ 県重要文化財群+ R1 衣 石段街土産通り連動・入場無料)", title_ja: "伊香保 365 段石段街", romaji: "Ikaho Ishidan", summary_zh: "**伊香保 365 段石段街は 1903 大正期改修・全長 300m+365 段**(渋川・**R1 住 伊香保温泉派生中核+上に伊香保神社**)。県重要文化財群、R1 衣 石段街土産通り、無料。", content_md: "- 立地:**渋川市伊香保**\n- 起源:**1903 大正期改修**\n- 規模:**全長 300m + 365 段**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["scenic_spot", "shopping_district"], lat: 36.4886, lon: 138.9242, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ikaho_ishidan_culture", "365_steps"], source: "manual" },
  { slug: "haruna-jinja-586", category: "culture", sub_type: "gunma_shrine_temple", title_zh: "榛名神社(高崎市榛名・586 創建 1439 年+ 群馬屈指山岳信仰拠点・上野国式内社・国指定重要文化財 7 棟+ 「九折岩」奇岩群+ パワースポット代表・R1 食 榛名梅+R1 育 榛名山連動・入場無料)", title_ja: "榛名神社", romaji: "Haruna Jinja", summary_zh: "**榛名神社は 586 創建 1439 年・群馬屈指山岳信仰拠点・上野国式内社・国指定重要文化財 7 棟**(高崎榛名・**「九折岩」奇岩群+パワースポット代表**)。R1 食 梅+R1 育 榛名山連動、無料。", content_md: "- 立地:**高崎市榛名**\n- 起源:**586 創建 1439 年**\n- 認定:**上野国式内社 + 国指定重要文化財 7 棟**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["shrine_temple", "scenic_spot"], lat: 36.4842, lon: 138.8328, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["haruna_jinja", "586", "1439_years"], source: "manual" },
  { slug: "haruna-yama-1449m", category: "culture", sub_type: "gunma_outdoor", title_zh: "榛名山+榛名湖(高崎+東吾妻+渋川・標高 1449m 榛名富士+榛名湖+ R1 育 榛名神社派生・上毛三山一+ 4 月桜+5-6 月新緑+10-11 月紅葉・観賞無料・R1 住 伊香保温泉観光連動)", title_ja: "榛名山+榛名湖", romaji: "Haruna-san", summary_zh: "**榛名山+榛名湖は標高 1449m 榛名富士+榛名湖・上毛三山一**(高崎+東吾妻+渋川・**R1 育 榛名神社派生・桜+新緑+紅葉**)。R1 住 伊香保連動、無料。", content_md: "- 立地:**高崎市 + 吾妻郡東吾妻町 + 渋川市**\n- 規模:**標高 1449m 榛名富士 + 榛名湖**\n- 認定:**上毛三山(榛名 + 赤城 + 妙義) 一**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["scenic_spot"], lat: 36.4733, lon: 138.8606, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["haruna_san", "1449m", "joumou_3"], source: "manual" },
  { slug: "akagi-yama-1828m", category: "culture", sub_type: "gunma_outdoor", title_zh: "赤城山(前橋+桐生+渋川+沼田・標高 1828m 黒檜山+大沼+小沼+ 日本百名山+ 上毛三山一+ R1 育 赤城神社・1300+ 年伝承+ 4-11 月登山+ 6 月レンゲツツジ群生+ 関東屈指山岳代表・観賞無料)", title_ja: "赤城山", romaji: "Akagi-yama", summary_zh: "**赤城山は標高 1828m 黒檜山+大沼+小沼・日本百名山・上毛三山一**(前橋+桐生+渋川+沼田・**R1 育 赤城神社 1300+ 年**)。4-11 月登山+6 月レンゲツツジ、無料。", content_md: "- 立地:**前橋市 + 桐生市 + 渋川市 + 沼田市**\n- 規模:**標高 1828m**\n- 認定:**日本百名山 + 上毛三山(赤城 + 榛名 + 妙義) 一**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["scenic_spot", "shrine_temple"], lat: 36.5536, lon: 139.1747, season_start: "2026-04-01", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["akagi_san", "1828m", "japan_100"], source: "manual" },
  { slug: "myogi-san-3-strange", category: "culture", sub_type: "gunma_outdoor", title_zh: "妙義山(富岡+下仁田+安中・標高 1104m 白雲山+金洞山+ 日本三大奇勝+ 関東 7 名山+ 上毛三山一+ 国指定名勝 1923+ 4-11 月登山+ 紅葉+桜・観賞無料・関東屈指奇岩観光代表)", title_ja: "妙義山", romaji: "Myōgi-san", summary_zh: "**妙義山は標高 1104m 白雲山+金洞山・日本三大奇勝+関東 7 名山+上毛三山一・国指定名勝 1923**(富岡+下仁田+安中・**4-11 月登山**)。関東屈指奇岩観光代表、無料。", content_md: "- 立地:**富岡市 + 甘楽郡下仁田町 + 安中市**\n- 規模:**標高 1104m 白雲山 + 金洞山**\n- 認定:**日本三大奇勝 + 関東 7 名山 + 上毛三山一 + 国指定名勝 1923**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "富岡市", lg_code: "10210", area_types: ["scenic_spot"], lat: 36.3225, lon: 138.7361, season_start: "2026-04-01", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["myogi_san", "japan_3_kishou", "1923"], source: "manual" },
  { slug: "takasaki-byakue-kannon", category: "culture", sub_type: "gunma_shrine_temple", title_zh: "高崎白衣大観音(高崎市・1936 完成 89 年+ 高さ 41.8m コンクリート観音像・全国最大級コンクリート仏像+ 県重要文化財・R1 衣 高崎達磨+R1 食 高崎ハム観光連動+ 入場 ¥300+ 関東屈指観音像代表)", title_ja: "高崎白衣大観音", romaji: "Takasaki Byakue Kannon", summary_zh: "**高崎白衣大観音は 1936 完成 89 年・高さ 41.8m・全国最大級コンクリート仏像**(高崎・**県重要文化財**)。R1 衣 高崎達磨+R1 食 高崎ハム連動、¥300、関東屈指観音像代表。", content_md: "- 立地:**高崎市**\n- 起源:**1936 完成 89 年**\n- 規模:**高さ 41.8m コンクリート観音像**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["shrine_temple", "scenic_spot"], lat: 36.3225, lon: 138.9994, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["takasaki_kannon", "1936", "41_8m"], source: "manual" },
  { slug: "kusatsu-saigawara-park", category: "culture", sub_type: "gunma_outdoor", title_zh: "草津 西の河原公園+大露天風呂(吾妻郡草津町・R1 住 草津温泉派生・温泉川+岩風呂+大露天風呂(全国最大級 500 ㎡)・公園散策無料・大露天 ¥700+ 海外観光客 SNS 拡散代表)", title_ja: "草津 西の河原公園", romaji: "Saigawara Park", summary_zh: "**草津 西の河原公園+大露天風呂は R1 住派生・温泉川+岩風呂+大露天(全国最大級 500 ㎡)**(草津)。散策無料、大露天 ¥700、海外 SNS 拡散代表。", content_md: "- 立地:**吾妻郡草津町**\n- 関係:**R1 住 草津温泉派生**\n- 規模:**温泉川 + 岩風呂 + 大露天風呂(全国最大級 500 ㎡)**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["scenic_spot", "onsen_field"], lat: 36.6228, lon: 138.5969, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["saigawara"], source: "manual" },
  { slug: "kusatsu-shirane-2160m", category: "culture", sub_type: "gunma_outdoor", title_zh: "草津白根山(吾妻郡草津町・標高 2160m+ 日本百名山+ 国立公園上信越高原+ 火山(湯釜) 美しい青色火口湖+ 5-11 月登山可+ R1 住 草津温泉+R1 育 西の河原公園観光連動+ 入場無料)", title_ja: "草津白根山", romaji: "Kusatsu Shirane", summary_zh: "**草津白根山は標高 2160m・日本百名山・湯釜美しい青色火口湖**(草津・**国立公園上信越高原**)。5-11 月登山、R1 住 草津温泉+R1 育 西の河原連動、無料。", content_md: "- 立地:**吾妻郡草津町**\n- 規模:**標高 2160m**\n- 認定:**日本百名山 + 国立公園上信越高原**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["scenic_spot"], lat: 36.6431, lon: 138.5267, season_start: "2026-05-01", season_end: "2026-11-15", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["shirane_san", "2160m", "japan_100"], source: "manual" },
  { slug: "moroin-bunpuku-1426", category: "culture", sub_type: "gunma_shrine_temple", title_zh: "茂林寺(館林市・応永 33 年 1426 創建 599 年+ 「分福茶釜」狸寺伝説起源+ 国指定重要文化財 茶釜+ 21 体狸像+ 国内+海外子供観光客代表・入場無料・R1 食 龍神酒造観光連動)", title_ja: "茂林寺", romaji: "Morinji", summary_zh: "**茂林寺は応永 33 年 1426 創建 599 年・「分福茶釜」狸寺伝説起源**(館林・**国指定重要文化財茶釜+21 体狸像**)。R1 食 龍神酒造連動、無料、子供観光客代表。", content_md: "- 立地:**館林市**\n- 起源:**応永 33 年 1426 創建 599 年**\n- 認定:**「分福茶釜」狸寺伝説起源 + 国指定重要文化財茶釜**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "館林市", lg_code: "10207", area_types: ["shrine_temple"], lat: 36.2089, lon: 139.5358, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["morinji", "1426", "599_years", "bunpuku"], source: "manual" },
  { slug: "tomihiro-museum-1991", category: "culture", sub_type: "gunma_modern_art", title_zh: "富弘美術館(みどり市東町・1991 開館 34 年+ 詩画家星野富弘 個人美術館・2005 改装妹島和世+西沢立衛建築・国際建築賞受賞・四季折々絶景庭園・入館 ¥520+ R1 楽 草木湖観光連動)", title_ja: "富弘美術館", romaji: "Tomihiro Museum", summary_zh: "**富弘美術館は 1991 開館 34 年・詩画家星野富弘個人美術館**(みどり東町・**2005 改装妹島和世+西沢立衛建築・国際建築賞受賞**)。¥520、R1 楽 草木湖連動。", content_md: "- 立地:**みどり市東町**\n- 起源:**1991 開館 34 年**\n- 関連:**2005 改装妹島和世 + 西沢立衛建築・国際建築賞受賞**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "みどり市", lg_code: "10212", area_types: ["museum_art"], lat: 36.5847, lon: 139.4322, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["tomihiro_museum", "1991"], source: "manual" },
  { slug: "tatebayashi-bijutsu-museum", category: "culture", sub_type: "gunma_modern_art", title_zh: "群馬県立館林美術館(館林市・2001 開館 24 年+ 高松伸建築・現代美術+彫刻+ 4 万 ㎡ 多々良沼公園内+ 国際的彫刻コレクション+ 入館 ¥620+ R1 育 茂林寺観光連動)", title_ja: "館林美術館", romaji: "Tatebayashi Museum", summary_zh: "**群馬県立館林美術館は 2001 開館 24 年・高松伸建築**(館林・**4 万 ㎡ 多々良沼公園内+国際彫刻コレクション**)。¥620、R1 育 茂林寺連動。", content_md: "- 立地:**館林市**\n- 起源:**2001 開館 24 年**\n- 関連:**高松伸建築 + 4 万 ㎡ 多々良沼公園内**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "館林市", lg_code: "10207", area_types: ["museum_art"], lat: 36.2453, lon: 139.5419, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["tatebayashi_museum", "2001"], source: "manual" },
  { slug: "harahira-arc-museum", category: "culture", sub_type: "gunma_modern_art", title_zh: "ハラ ミュージアム アーク 原美術館 ARC(渋川市・1988 開園 37 年+ 磯崎新建築・現代美術館分館+ 4.5 万 ㎡ 庭園+ 国際現代美術 1000+ 点+ 入館 ¥1,500+ R1 住 伊香保温泉観光連動)", title_ja: "原美術館 ARC", romaji: "Hara Museum ARC", summary_zh: "**ハラ ミュージアム アーク 原美術館 ARC は 1988 開園 37 年・磯崎新建築**(渋川・**4.5 万 ㎡ 庭園+国際現代美術 1000+ 点**)。¥1,500、R1 住 伊香保連動。", content_md: "- 立地:**渋川市**\n- 起源:**1988 開園 37 年**\n- 関連:**磯崎新建築 + 4.5 万 ㎡ 庭園**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["museum_art"], lat: 36.4647, lon: 138.9519, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: ["木"], external_urls: {}, tags: ["hara_arc", "1988"], source: "manual" },
  { slug: "kiryu-tenmangu-1196", category: "culture", sub_type: "gunma_shrine_temple", title_zh: "桐生天満宮(桐生市・建久 7 年 1196 創建 829 年+ R1 衣 桐生織 1300 年伝統 守護神社・桐生新町重伝建中核・国登録有形文化財群+ 11 月酉の市+R1 楽 桐生八木節祭観光連動・入場無料)", title_ja: "桐生天満宮", romaji: "Kiryū Tenmangū", summary_zh: "**桐生天満宮は建久 7 年 1196 創建 829 年・R1 衣 桐生織守護神社・桐生新町重伝建中核**(桐生・**国登録有形文化財群**)。R1 楽 桐生八木節祭、無料。", content_md: "- 立地:**桐生市**\n- 起源:**建久 7 年 1196 創建 829 年**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "桐生市", lg_code: "10203", area_types: ["shrine_temple"], lat: 36.4044, lon: 139.3306, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kiryu_tenmangu", "1196"], source: "manual" },
  { slug: "numata-castle-ruins", category: "culture", sub_type: "gunma_history_museum", title_zh: "沼田城跡+真田氏ゆかり地(沼田市・天文元年 1532 築城 493 年+ 真田信之 1590 入城・関東屈指山城・国指定史跡候補+ R1 食 沼田りんご+R1 住 老神温泉観光連動・入場無料・歴史散策代表)", title_ja: "沼田城跡", romaji: "Numata Castle", summary_zh: "**沼田城跡+真田氏ゆかり地は天文元年 1532 築城 493 年・真田信之 1590 入城**(沼田・**関東屈指山城+国指定史跡候補**)。R1 食 りんご+R1 住 老神温泉、無料。", content_md: "- 立地:**沼田市**\n- 起源:**天文元年 1532 築城 493 年**\n- 関連:**真田信之 1590 入城**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "沼田市", lg_code: "10206", area_types: ["history_site_castle"], lat: 36.6453, lon: 139.0444, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["numata_castle", "1532", "sanada"], source: "manual" },
  { slug: "onioshidashi-1783", category: "culture", sub_type: "gunma_outdoor", title_zh: "鬼押出し溶岩園(吾妻郡嬬恋村・1783 浅間山天明大噴火+ 全長 5km 溶岩台地・国指定特別天然記念物 1934+ 国際火山地形学者代表現地+ R1 食 嬬恋キャベツ+R1 住 万座温泉観光連動・入場 ¥700)", title_ja: "鬼押出し溶岩園", romaji: "Onioshidashi", summary_zh: "**鬼押出し溶岩園は 1783 浅間山天明大噴火・全長 5km 溶岩台地・国指定特別天然記念物 1934**(嬬恋・**国際火山地形学者代表現地**)。R1 食 キャベツ+R1 住 万座、¥700。", content_md: "- 立地:**吾妻郡嬬恋村**\n- 起源:**1783 浅間山天明大噴火**\n- 規模:**全長 5km 溶岩台地**\n- 認定:**国指定特別天然記念物 1934**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "嬬恋村", lg_code: "10425", area_types: ["scenic_spot"], lat: 36.4636, lon: 138.5181, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["onioshidashi", "1783", "1934"], source: "manual" },
  { slug: "shoumon-darumadera", category: "culture", sub_type: "gunma_shrine_temple", title_zh: "少林山達磨寺(高崎市・1697 創建 328 年+ R1 衣 高崎達磨 80% 派生地・「達磨寺」全国達磨発祥+ 達磨絵付け体験+ 1 月 6-7 日七草大祭(全国 5 万人動員)+ 入場無料・R1 衣 達磨絵付け体験連動)", title_ja: "少林山達磨寺", romaji: "Shōrinzan Daruma-ji", summary_zh: "**少林山達磨寺は 1697 創建 328 年・R1 衣 高崎達磨 80% 派生地・「達磨寺」全国達磨発祥**(高崎・**1 月七草大祭 5 万人動員**)。R1 衣 達磨絵付け、無料。", content_md: "- 立地:**高崎市**\n- 起源:**1697 創建 328 年**\n- 認定:**全国達磨発祥地**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["shrine_temple"], lat: 36.3500, lon: 138.9744, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["shorinzan_daruma", "1697"], source: "manual" },
  { slug: "haruna-kuruma-jinja", category: "culture", sub_type: "gunma_history_museum", title_zh: "群馬県立歴史博物館+群馬県立近代美術館(高崎市・1979 県歴博開館 46 年+ 1974 県近美開館 51 年+ 県歴史民俗+自然科学+群馬出身画家+現代美術+ 高崎観音山周辺+ 入館 ¥300+ R1 育 高崎白衣観音観光連動)", title_ja: "群馬県立歴博+近美", romaji: "Gunma Pref Historical", summary_zh: "**群馬県立歴史博物館+県立近代美術館は 1979 県歴博 46 年・1974 県近美 51 年**(高崎・**歴史民俗+自然+群馬画家+現代美術**)。¥300、R1 育 高崎白衣観音連動。", content_md: "- 立地:**高崎市**\n- 起源:**1979 県歴博 + 1974 県近美**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["museum_art"], lat: 36.3225, lon: 138.9994, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["gunma_pref_museum"], source: "manual" },
  { slug: "shima-blue-lake", category: "culture", sub_type: "gunma_outdoor", title_zh: "四万ブルー(吾妻郡中之条町・R1 住 四万温泉 1563 派生・四万川ダム湖+四万湖+奥四万湖・国際 SNS 拡散「四万ブルー」+ 神秘的青色湖水+ 5-7 月+9-11 月眺望ピーク+ 入場無料+ 海外観光客代表)", title_ja: "四万ブルー", romaji: "Shima Blue", summary_zh: "**四万ブルーは R1 住 四万温泉 1563 派生・四万川ダム湖+四万湖+奥四万湖**(中之条・**国際 SNS 拡散「四万ブルー」+神秘青色湖水**)。5-7+9-11 月、無料、海外観光客代表。", content_md: "- 立地:**吾妻郡中之条町**\n- 関係:**R1 住 四万温泉 1563 派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "中之条町", lg_code: "10421", area_types: ["scenic_spot"], lat: 36.6628, lon: 138.7708, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["shima_blue"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[gunma-culture-r1] 尚無條目"); return; }
  console.log(`[gunma-culture-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) return;
  const sb = createAdminClient();
  const { error } = await sb.from("japan_entries").upsert(rows as any, { onConflict: "slug" });
  if (error) { console.error("[gunma-culture-r1] upsert failed:", error); process.exit(1); }
  console.log(`[gunma-culture-r1] Done — ${rows.length} rows.`);
}
main().catch((err) => { console.error(err); process.exit(1); });
