// Seed 神奈川県 R2 補完(20 筆 / Sprint 2.x / 第十四卷)
// 食 5 / 衣 3 / 住 3 / 育 3 / 楽 4 / 行 2 = 20 累積 123 + 20 = 143
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 食 5
  {
    slug: "kamakura-shojin-ryori",
    category: "food", sub_type: "kanagawa_shonan_food",
    title_zh: "鎌倉精進料理(鎌倉市建長寺+円覚寺+寿福寺・R1 食 建長寺けんちん 1253 派生・鎌倉武家+禅宗精進料理 800+ 年伝統+ 季節野菜+ 山菜+ ごま豆腐+ 五目飯・建長寺(¥3,000-7,500)+一茶庵(¥2,500-5,500)・国際 SNS 海外旅行者代表)",
    title_ja: "鎌倉精進料理", romaji: "Kamakura Shōjin",
    summary_zh: "**鎌倉精進料理は R1 食 けんちん 1253 派生・鎌倉武家+禅宗精進料理 800+ 年伝統・季節野菜+山菜+ごま豆腐+五目飯**(建長寺+円覚寺+寿福寺)。¥3,000-7,500、海外代表。",
    content_md: "- 立地:**鎌倉市建長寺 + 円覚寺 + 寿福寺**\n- 関連:**R1 食 建長寺けんちん 1253 派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["restaurant_traditional", "history_site_castle"], lat: 35.3389, lon: 139.5497,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kamakura_shojin"], source: "manual",
  },
  {
    slug: "yokohama-craft-beer",
    category: "food", sub_type: "kanagawa_yokohama_food",
    title_zh: "横浜クラフトビール+ 横浜ベイブルーイング(横浜市中区+ 西区・1869 横浜キリンビール創業 156+ 年(全国最古ビール工場候補)+ 横浜ベイブルーイング 1999+ 横浜開港クラフトビール+ 中華街+赤レンガ周辺ブルワリーバー 25+ 軒・¥800-1,500)",
    title_ja: "横浜クラフト", romaji: "Yokohama Craft Beer",
    summary_zh: "**横浜クラフトビール+ベイブルーイングは 1869 キリンビール 156+ 年(全国最古ビール工場候補)+横浜ベイブルーイング 1999・ブルワリーバー 25+ 軒**(横浜中+西区)。¥800-1,500。",
    content_md: "- 立地:**横浜市中区 + 西区**\n- 起源:**1869 横浜キリンビール創業 156+ 年(全国最古ビール工場候補)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["restaurant_traditional", "industrial_heritage"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokohama_craft_beer", "kirin_1869"], source: "manual",
  },
  {
    slug: "miura-yasai-ja",
    category: "food", sub_type: "kanagawa_miura_food",
    title_zh: "三浦野菜+ JA 横須賀(三浦市+ 横須賀+葉山・R1 食 三浦キャベツ大根 派生・全国野菜産地候補・JA 横須賀運営直売所 8+ 軒+ ブロッコリー+ にんじん+ ねぎ+ えぼだい・1kg ¥350-1,500・国内 SNS 産地直販代表)",
    title_ja: "三浦野菜 JA", romaji: "Miura Yasai JA",
    summary_zh: "**三浦野菜+JA 横須賀は R1 食 三浦キャベツ大根派生・全国野菜産地候補・JA 横須賀運営直売所 8+ 軒・ブロッコリー+にんじん+ねぎ**(三浦+横須賀+葉山)。¥350-1,500/kg、産地直販代表。",
    content_md: "- 立地:**三浦市 + 横須賀市 + 葉山町**\n- 関連:**R1 食 三浦キャベツ + 大根派生**\n- 規模:**JA 横須賀運営直売所 8+ 軒**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "三浦市", lg_code: "14210",
    area_types: ["farm_field", "shopping_district"], lat: 35.1378, lon: 139.6178,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["miura_yasai_ja"], source: "manual",
  },
  {
    slug: "hayama-gyu-burger",
    category: "food", sub_type: "kanagawa_miura_food",
    title_zh: "葉山牛ハンバーガー+ 高級ハンバーグ専門店(葉山町+ 横須賀+ 鎌倉・R1 食 葉山牛 1989 派生・葉山牛使用バーガー専門店 「アバランチ葉山」+ 鎌倉「ハンバーガー&ステーキシマショウ」+ 高級店 1 個 ¥2,500-5,500)",
    title_ja: "葉山牛バーガー", romaji: "Hayama Gyu Burger",
    summary_zh: "**葉山牛ハンバーガー+高級ハンバーグは R1 食 葉山牛 1989 派生・「アバランチ葉山」+「シマショウ」鎌倉**(葉山+横須賀+鎌倉)。¥2,500-5,500/個。",
    content_md: "- 立地:**三浦郡葉山町 + 横須賀市 + 鎌倉市**\n- 関連:**R1 食 葉山牛 1989 派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "三浦郡", municipality_ja: "葉山町", lg_code: "14301",
    area_types: ["restaurant_traditional"], lat: 35.2733, lon: 139.5808,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["hayama_gyu_burger"], source: "manual",
  },
  {
    slug: "yokosuka-navy-burger-2008",
    category: "food", sub_type: "kanagawa_miura_food",
    title_zh: "横須賀ネイビーバーガー(横須賀市本町+ どぶ板通+ JR 横須賀駅・2008 横須賀市公認「ヨコスカネイビーバーガー」発祥 17+ 年+ 米軍横須賀基地レシピ伝承+ 国内最古ハンバーガー店「TSUNAMI」+ R1 衣 どぶ板通+R1 食 海軍カレー連動・¥1,500-3,500)",
    title_ja: "ネイビーバーガー", romaji: "Navy Burger",
    summary_zh: "**横須賀ネイビーバーガーは 2008 公認発祥 17+ 年・米軍基地レシピ伝承・国内最古バーガー店「TSUNAMI」**(本町+どぶ板+JR 横須賀)。R1 衣 どぶ板+R1 食 カレー連動、¥1,500-3,500。",
    content_md: "- 立地:**横須賀市本町 + どぶ板通 + JR 横須賀駅**\n- 起源:**2008 横須賀市公認「ヨコスカネイビーバーガー」発祥 17+ 年**\n- 認定:**米軍横須賀基地レシピ伝承 + 国内最古ハンバーガー店「TSUNAMI」**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横須賀市", lg_code: "14201",
    area_types: ["restaurant_traditional"], lat: 35.2806, lon: 139.6711,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["navy_burger_2008"], source: "manual",
  },

  // 衣 3
  {
    slug: "yokohama-akarenga-marche",
    category: "fashion", sub_type: "kanagawa_yokohama_clothing",
    title_zh: "横浜赤レンガ倉庫マルシェ+ 季節市(横浜市中区新港・R1 育 赤レンガ倉庫 1911 派生・春クラフトマルシェ+ 夏 オクトーバーフェスト 9-10 月+ 冬クリスマスマーケット 11-12 月+ 国際 SNS 海外旅行者代表+ 無料入場)",
    title_ja: "赤レンガマルシェ", romaji: "Akarenga Marche",
    summary_zh: "**横浜赤レンガ倉庫マルシェ+季節市は R1 育 1911 派生・春クラフト+夏オクトーバーフェスト 9-10 月+冬クリスマス 11-12 月**(中区新港)。海外代表、無料入場。",
    content_md: "- 立地:**横浜市中区新港**\n- 関連:**R1 育 赤レンガ倉庫 1911 派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["shopping_district"], lat: 35.4533, lon: 139.6428,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["akarenga_marche"], source: "manual",
  },
  {
    slug: "kamakura-shikki",
    category: "fashion", sub_type: "kanagawa_dento",
    title_zh: "鎌倉漆器+ 朱塗椀(鎌倉市・R1 衣 鎌倉彫 1979 派生・鎌倉時代以降漆芸 800+ 年・朱塗椀+漆塗箸+漆塗茶碗・「漆 一貫」「香林文化」工房・¥3,500-45,000・R1 食 鎌倉精進料理連動)",
    title_ja: "鎌倉漆器", romaji: "Kamakura Shikki",
    summary_zh: "**鎌倉漆器+朱塗椀は R1 衣 鎌倉彫 1979 派生・鎌倉時代以降漆芸 800+ 年・朱塗椀+漆塗箸+漆塗茶碗・「漆一貫」+「香林文化」工房**(鎌倉)。¥3,500-45,000、R1 食 精進料理連動。",
    content_md: "- 立地:**鎌倉市**\n- 関連:**R1 衣 鎌倉彫 1979 派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["industrial_heritage", "shopping_district"], lat: 35.3197, lon: 139.5519,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kamakura_shikki"], source: "manual",
  },
  {
    slug: "oyama-mokuchou",
    category: "fashion", sub_type: "kanagawa_kennō_clothing",
    title_zh: "大山木彫+ 大山こま(伊勢原市大山+ 秦野・R1 育 大山阿夫利神社派生・江戸期から「大山こま」(独楽)+ 大山木彫 200+ 年+ 大山参道老舗 8+ 軒+ 木彫椀+独楽+ お土産・¥1,200-12,000・大山先導師宿坊連動)",
    title_ja: "大山木彫+独楽", romaji: "Ōyama Mokuchou",
    summary_zh: "**大山木彫+大山こまは R1 育 大山阿夫利派生・江戸期から「大山こま」+木彫 200+ 年・参道老舗 8+ 軒・木彫椀+独楽**(伊勢原大山+秦野)。¥1,200-12,000、先導師宿坊連動。",
    content_md: "- 立地:**伊勢原市大山 + 秦野市**\n- 関連:**R1 育 大山阿夫利神社派生 + R1 住 大山先導師宿坊連動**\n- 起源:**江戸期から「大山こま」(独楽) + 大山木彫 200+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "伊勢原市", lg_code: "14214",
    area_types: ["industrial_heritage", "shopping_district"], lat: 35.4250, lon: 139.2367,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["oyama_mokuchou"], source: "manual",
  },

  // 住 3
  {
    slug: "kamakura-kominka-ryokan",
    category: "lodging", sub_type: "kanagawa_shonan_lodging",
    title_zh: "鎌倉古民家旅館+ 一棟貸切宿(鎌倉市山ノ内+雪ノ下+ 七里ガ浜・1900 年代以降鎌倉武家屋敷リノベ古民家ホテル 25+ 軒+ 「亀の井別荘」「IZA 鎌倉」古民家+ 庭付一棟貸切+ R1 育 円覚寺+建長寺周辺・¥22,000-65,000/泊+ 国際 SNS 海外旅行者代表)",
    title_ja: "鎌倉古民家", romaji: "Kamakura Kominka",
    summary_zh: "**鎌倉古民家旅館+一棟貸切は 1900 年代以降武家屋敷リノベ 25+ 軒・「亀の井別荘」+「IZA 鎌倉」古民家+庭付一棟貸切**(鎌倉山ノ内+雪ノ下+七里ガ浜)。¥22,000-65,000/泊。",
    content_md: "- 立地:**鎌倉市山ノ内 + 雪ノ下 + 七里ガ浜**\n- 起源:**1900 年代以降鎌倉武家屋敷リノベ古民家ホテル 25+ 軒**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["accommodation_ryokan", "history_site_castle"], lat: 35.3375, lon: 139.5478,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["kamakura_kominka"], source: "manual",
  },
  {
    slug: "miura-minshuku",
    category: "lodging", sub_type: "kanagawa_miura_lodging",
    title_zh: "三浦民宿+ 三崎漁師宿(三浦市三崎+ 三戸+ 横須賀・R1 食 三崎マグロ派生・1900 年代以降漁師民宿 100+ 年+ マグロ三昧+ 朝獲れ刺身・民宿 25+ 軒・1 泊 2 食付・¥9,500-18,000/泊・国内グルメ観光客代表)",
    title_ja: "三浦民宿", romaji: "Miura Minshuku",
    summary_zh: "**三浦民宿+三崎漁師宿は R1 食 三崎マグロ派生・1900 年代以降民宿 100+ 年・マグロ三昧+朝獲れ刺身・民宿 25+ 軒**(三浦三崎+三戸+横須賀)。¥9,500-18,000/泊。",
    content_md: "- 立地:**三浦市三崎 + 三戸 + 横須賀市**\n- 関連:**R1 食 三崎マグロ派生**\n- 規模:**民宿 25+ 軒 + 1 泊 2 食付**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "三浦市", lg_code: "14210",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 35.1378, lon: 139.6178,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["miura_minshuku"], source: "manual",
  },
  {
    slug: "nanasawa-onsen-atsugi",
    category: "lodging", sub_type: "kanagawa_kennō_lodging",
    title_zh: "七沢温泉+ 厚木 七沢自然郷(厚木市七沢・古来から開湯 800+ 年伝承+ 大山阿夫利神社東麓・「玉川旅館」「福元館」老舗 8+ 軒・R1 育 大山阿夫利連動+R1 食 厚木シロコロ連動・¥12,000-32,000/泊・JR 本厚木駅+バス)",
    title_ja: "七沢温泉", romaji: "Nanasawa Onsen",
    summary_zh: "**七沢温泉+厚木七沢自然郷は古来から開湯 800+ 年伝承・大山阿夫利東麓・「玉川旅館」「福元館」老舗 8+ 軒**(厚木七沢)。R1 育 大山+R1 食 シロコロ連動、¥12,000-32,000/泊。",
    content_md: "- 立地:**厚木市七沢**\n- 起源:**古来から開湯 800+ 年伝承**\n- 認定:**大山阿夫利神社東麓 + 「玉川旅館」+「福元館」老舗 8+ 軒**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "厚木市", lg_code: "14212",
    area_types: ["onsen_natural", "accommodation_ryokan"], lat: 35.4133, lon: 139.2769,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["nanasawa_onsen"], source: "manual",
  },

  // 育 3
  {
    slug: "yokohama-history-museum-1995",
    category: "culture", sub_type: "kanagawa_museum",
    title_zh: "横浜歴史博物館+ 大塚・歳勝土遺跡公園(横浜市都筑区中川・1995 開館 30+ 年+ 大塚・歳勝土遺跡(国指定史跡 1986 縄文-弥生環濠集落)+ 横浜古代-現代 2 万年通史展示・観覧 ¥400・横浜市営地下鉄センター北駅徒歩 5 分)",
    title_ja: "横浜歴史博物館", romaji: "Yokohama History Museum",
    summary_zh: "**横浜歴史博物館+大塚・歳勝土遺跡公園は 1995 開館 30+ 年・大塚・歳勝土遺跡国史跡 1986(縄文-弥生環濠集落)・横浜古代-現代 2 万年通史**(都筑区中川)。¥400。",
    content_md: "- 立地:**横浜市都筑区中川**\n- 起源:**1995 開館 30+ 年**\n- 認定:**大塚・歳勝土遺跡 国指定史跡 1986 縄文-弥生環濠集落**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["museum_art", "history_site_castle"], lat: 35.5497, lon: 139.5694,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["yokohama_history_1995"], source: "manual",
  },
  {
    slug: "kamakura-kokuhokan-1928",
    category: "culture", sub_type: "kanagawa_museum",
    title_zh: "鎌倉国宝館(鎌倉市雪ノ下・1928 開館 97+ 年+ R1 育 鶴岡八幡宮境内・鎌倉時代の国宝+国指定重要文化財 2000+ 件所蔵+ 運慶+快慶 仏像+ 鎌倉時代古文書・¥600・国際 SNS 海外旅行者代表)",
    title_ja: "鎌倉国宝館", romaji: "Kamakura Kokuhōkan",
    summary_zh: "**鎌倉国宝館は 1928 開館 97+ 年・R1 育 鶴岡八幡宮境内・国宝+国重文 2000+ 件・運慶+快慶 仏像**(鎌倉雪ノ下)。¥600、海外代表。",
    content_md: "- 立地:**鎌倉市雪ノ下**\n- 起源:**1928 開館 97+ 年**\n- 認定:**R1 育 鶴岡八幡宮境内 + 国宝 + 国指定重要文化財 2000+ 件所蔵 + 運慶 + 快慶 仏像**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["museum_art", "history_site_castle"], lat: 35.3258, lon: 139.5564,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["kamakura_kokuhokan_1928"], source: "manual",
  },
  {
    slug: "kanagawa-pref-history-1967",
    category: "culture", sub_type: "kanagawa_museum",
    title_zh: "神奈川県立歴史博物館(横浜市中区南仲通・1967 開館 58+ 年+ 旧横浜正金銀行本店 1904 国指定重要文化財建築 1995・神奈川 6 万年通史展示+ 鎌倉幕府+ 横浜開港 1859 史料・観覧 ¥300)",
    title_ja: "神奈川県立歴史博物館", romaji: "Kanagawa Pref History",
    summary_zh: "**神奈川県立歴史博物館は 1967 開館 58+ 年・旧横浜正金銀行本店 1904 国重文建築 1995・神奈川 6 万年通史+鎌倉幕府+横浜開港 1859 史料**(中区南仲通)。¥300。",
    content_md: "- 立地:**横浜市中区南仲通**\n- 起源:**1967 開館 58+ 年**\n- 認定:**旧横浜正金銀行本店 1904 国指定重要文化財建築 1995**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["museum_art", "history_site_castle"], lat: 35.4444, lon: 139.6403,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["kanagawa_pref_history_1967"], source: "manual",
  },

  // 楽 4
  {
    slug: "yamashita-park-1930",
    category: "entertainment", sub_type: "kanagawa_yokohama_entertainment",
    title_zh: "山下公園+ 氷川丸(横浜市中区山下町・1930 開園 95+ 年+ 関東大震災復興公園・全国有数臨海公園+ 氷川丸 1930 大型客船 国指定重要文化財 2016+ R1 楽 マリンタワー隣接・無料散策・国際 SNS 海外旅行者代表)",
    title_ja: "山下公園+氷川丸", romaji: "Yamashita Park",
    summary_zh: "**山下公園+氷川丸は 1930 開園 95+ 年・関東大震災復興公園・全国有数臨海公園・氷川丸 1930 大型客船 国重文 2016**(中区山下町)。R1 楽 マリンタワー隣接、無料、海外代表。",
    content_md: "- 立地:**横浜市中区山下町**\n- 起源:**1930 開園 95+ 年**\n- 認定:**関東大震災復興公園 + 氷川丸 1930 大型客船 国指定重要文化財 2016**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["nature_park", "history_site_castle"], lat: 35.4428, lon: 139.6489,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yamashita_park_1930", "hikawa_maru_2016"], source: "manual",
  },
  {
    slug: "yokohama-dockyard-1885",
    category: "entertainment", sub_type: "kanagawa_yokohama_entertainment",
    title_zh: "ドックヤードガーデン+ 旧横浜船渠 2 号ドック(横浜市西区みなとみらい・1885 旧横浜船渠 2 号ドック建設 140+ 年+ 国指定重要文化財 1997+ 1989 ランドマークタワー敷地内庭園化 36+ 年+ R1 楽 みなとみらい+ランドマーク連動・無料)",
    title_ja: "ドックヤードガーデン", romaji: "Dockyard Garden",
    summary_zh: "**ドックヤードガーデン+旧横浜船渠 2 号ドックは 1885 建設 140+ 年・国重文 1997・1989 ランドマーク敷地内庭園化 36+ 年**(西区みなとみらい)。R1 楽 みなとみらい+ランドマーク連動、無料。",
    content_md: "- 立地:**横浜市西区みなとみらい**\n- 起源:**1885 旧横浜船渠 2 号ドック建設 140+ 年 + 1989 ランドマークタワー敷地内庭園化 36+ 年**\n- 認定:**国指定重要文化財 1997**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["history_site_castle", "shopping_district"], lat: 35.4549, lon: 139.6311,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokohama_dockyard_1885", "1997_designation"], source: "manual",
  },
  {
    slug: "chinatown-spring-mid-festival",
    category: "entertainment", sub_type: "kanagawa_yokohama_entertainment",
    title_zh: "横浜中華街春節+ 中秋節+関帝誕(横浜市中区山下町・R1 食 横浜中華街 1859 派生・春節(旧正月 1-2 月)+ 中秋節(9-10 月)+ 関帝誕(7 月)+ 春節獅子舞・龍舞 50+ 団体・60 万人観衆・国際 SNS 海外旅行者代表+ 無料観覧)",
    title_ja: "中華街春節中秋", romaji: "Chinatown Festivals",
    summary_zh: "**横浜中華街春節+中秋節+関帝誕は R1 食 1859 派生・春節 1-2 月+中秋 9-10 月+関帝誕 7 月・獅子舞+龍舞 50+ 団体・60 万人観衆**(中区山下町)。海外代表、無料。",
    content_md: "- 立地:**横浜市中区山下町**\n- 関連:**R1 食 横浜中華街 1859 派生**\n- 規模:**春節(旧正月 1-2 月) + 中秋節(9-10 月) + 関帝誕(7 月) + 60 万人観衆**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["history_site_castle", "shopping_district"], lat: 35.4428, lon: 139.6450,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["chinatown_festivals"], source: "manual",
  },
  {
    slug: "oiso-long-beach-1957",
    category: "entertainment", sub_type: "kanagawa_shonan_entertainment",
    title_zh: "大磯ロングビーチ(中郡大磯町国府本郷・1957 開業 68+ 年+ 全国最古プール候補(屋外プール)+ 130m 流れるプール+ 8 種プール・大磯プリンスホテル 1986 R1 住併設・夏限定 7-9 月・¥3,800-7,000・国内ファミリー観光客代表)",
    title_ja: "大磯ロングビーチ", romaji: "Ōiso Long Beach",
    summary_zh: "**大磯ロングビーチは 1957 開業 68+ 年・全国最古プール候補・130m 流れるプール+8 種プール・大磯プリンス 1986 併設**(大磯国府本郷)。夏限定 7-9 月、¥3,800-7,000、ファミリー代表。",
    content_md: "- 立地:**中郡大磯町国府本郷**\n- 起源:**1957 開業 68+ 年**\n- 認定:**全国最古プール候補(屋外プール) + 130m 流れるプール + 8 種プール**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "中郡", municipality_ja: "大磯町", lg_code: "14341",
    area_types: ["theme_park", "beach_coast"], lat: 35.3056, lon: 139.3211,
    season_start: "2026-07-01", season_end: "2026-09-15", event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["oiso_long_beach_1957"], source: "manual",
  },

  // 行 2
  {
    slug: "sotetsu-1917",
    category: "transport", sub_type: "kanagawa_private_railway",
    title_zh: "相模鉄道(相鉄)(横浜市+ 海老名・1917 神中鉄道として開業 108+ 年+ 横浜-海老名+湘南台 35.9km・27 駅+ 1 日 70 万人乗降+ 2019 相鉄・JR 直通+ 2023 相鉄・東急直通+ ¥150-460/片道)",
    title_ja: "相模鉄道", romaji: "Sōtetsu",
    summary_zh: "**相模鉄道(相鉄)は 1917 神中鉄道開業 108+ 年・横浜-海老名+湘南台 35.9km+27 駅・1 日 70 万人・2019 JR 直通+2023 東急直通**(横浜+海老名)。¥150-460/片道。",
    content_md: "- 立地:**横浜市 + 海老名市**\n- 起源:**1917 神中鉄道として開業 108+ 年**\n- 規模:**横浜-海老名 + 湘南台 35.9km + 27 駅 + 1 日 70 万人乗降**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["sotetsu_1917"], source: "manual",
  },
  {
    slug: "jr-sagami-line-1921",
    category: "transport", sub_type: "kanagawa_jr",
    title_zh: "JR 相模線(茅ヶ崎-橋本・1921 相模鉄道相模線として開業 104+ 年+ 1944 国有化・茅ヶ崎-海老名-厚木-相模原-橋本 33.3km・18 駅+ 県央通勤線+ R1 食 海老名いちご+R1 育 寒川神社連動・¥150-510/片道)",
    title_ja: "JR 相模線", romaji: "JR Sagami",
    summary_zh: "**JR 相模線は 1921 相模鉄道相模線開業 104+ 年・1944 国有化・茅ヶ崎-海老名-厚木-相模原-橋本 33.3km・18 駅・県央通勤線**(茅ヶ崎-橋本)。¥150-510/片道。",
    content_md: "- 立地:**茅ヶ崎市 - 海老名市 - 厚木市 - 相模原市**\n- 起源:**1921 相模鉄道相模線として開業 104+ 年 + 1944 国有化**\n- 規模:**33.3km + 18 駅**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "茅ヶ崎市", lg_code: "14207",
    area_types: ["transport_hub"], lat: 35.3331, lon: 139.4067,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_sagami_1921"], source: "manual",
  },
];

seedMain(rows, "kanagawa-r2");
