// Seed 埼玉県 食 R1(25 筆 / Sprint 1.1 / 第十一卷 開卷)
//
// 埼玉 5 大名物 5(草加せんべい+深谷ねぎ+武蔵野うどん+川越サツマイモ+行田フライ) /
// 郷土食 4 / 川魚 3 / 果実 3 / 銘菓 5 / 酒 3 / 米肉 2 = 25

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "埼玉県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 5 大名物 (5)
  { slug: "soka-senbei-1850", category: "food", sub_type: "saitama_3_meibutsu", title_zh: "草加せんべい(草加市・江戸期 1850 年代発祥 175 年+ 日光街道宿場由来+ 国 GI 地理的表示保護登録 2017+ 醤油焼き煎餅・全国煎餅代表+ 草加せんべい振興協議会 老舗 30+ 軒+ 1 袋 ¥350-1,200+ 観光客代表土産)", title_ja: "草加せんべい", romaji: "Sōka Senbei", summary_zh: "**草加せんべいは江戸期 1850 年代発祥 175 年・国 GI 地理的表示保護登録 2017**(草加・**日光街道宿場由来・全国煎餅代表**)。老舗 30+ 軒、¥350-1,200/袋、観光客代表土産。", content_md: "- 立地:**草加市**\n- 起源:**江戸期 1850 年代発祥 175 年**\n- 認定:**国 GI 地理的表示保護登録 2017 + 全国煎餅代表 + 日光街道宿場由来**\n- 規模:**老舗 30+ 軒**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "草加市", lg_code: "11221", area_types: ["restaurant_traditional", "shopping_district"], lat: 35.8252, lon: 139.8056, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["soka_senbei", "1850s", "175_years", "gi_2017"], source: "manual" },
  { slug: "fukaya-negi-no1", category: "food", sub_type: "saitama_3_meibutsu", title_zh: "深谷ねぎ(深谷市+本庄+熊谷・全国白ねぎ生産量上位県・1900 年代以降産地化+ 「深谷の白ねぎ」全国ブランド+ 12-3 月旬+ 道の駅+全国百貨店流通+ 1 束 ¥800-1,800+ R1 楽 深谷ねぎ祭観光連動)", title_ja: "深谷ねぎ", romaji: "Fukaya Negi", summary_zh: "**深谷ねぎは全国白ねぎ生産量上位県・「深谷の白ねぎ」全国ブランド**(深谷+本庄+熊谷・**1900 年代以降産地化**)。12-3 月、道の駅+百貨店、¥800-1,800/束、R1 楽 ねぎ祭連動。", content_md: "- 立地:**深谷市 + 本庄市 + 熊谷市**\n- 認定:**全国白ねぎ生産量上位県 + 「深谷の白ねぎ」全国ブランド**\n- 起源:**1900 年代以降産地化**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "深谷市", lg_code: "11218", area_types: ["farm_field"], lat: 36.1969, lon: 139.2811, season_start: "2026-12-01", season_end: "2027-03-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["fukaya_negi"], source: "manual" },
  { slug: "musashino-udon", category: "food", sub_type: "saitama_3_meibutsu", title_zh: "武蔵野うどん(所沢市+狭山+入間+三芳・江戸期発祥 300+ 年+ 関東関口手打ち代表麺・地粉手打ち+太麺コシ強+肉汁つけ麺・市内 50+ 軒+ R1 食 川越鰻並ぶ埼玉麺文化代表・1 杯 ¥800-1,500)", title_ja: "武蔵野うどん", romaji: "Musashino Udon", summary_zh: "**武蔵野うどんは江戸期発祥 300+ 年・関東関口手打ち代表麺**(所沢+狭山+入間+三芳・**地粉手打ち+太麺コシ強+肉汁つけ麺**)。市内 50+ 軒、¥800-1,500、R1 食 川越鰻並ぶ。", content_md: "- 立地:**所沢市 + 狭山市 + 入間市 + 入間郡三芳町**\n- 起源:**江戸期発祥 300+ 年**\n- 構成:**地粉手打ち + 太麺コシ強 + 肉汁つけ麺**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "所沢市", lg_code: "11208", area_types: ["restaurant_traditional"], lat: 35.7989, lon: 139.4689, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["musashino_udon", "edo_origin"], source: "manual" },
  { slug: "kawagoe-satsumaimo", category: "food", sub_type: "saitama_3_meibutsu", title_zh: "川越サツマイモ(川越市+三芳・江戸期 1700 年代後期栽培開始 250+ 年+ 「川越いも」全国ブランド・「九里四里(栗より)うまい十三里」+ 9-12 月旬+ R1 育 川越蔵造り街観光連動・道の駅+市内菓子店流通+ 1kg ¥800-2,500)", title_ja: "川越サツマイモ", romaji: "Kawagoe Satsumaimo", summary_zh: "**川越サツマイモは江戸期 1700 年代後期栽培開始 250+ 年・「川越いも」全国ブランド**(川越・**「九里四里うまい十三里」**)。9-12 月、R1 育 蔵造り街連動、¥800-2,500/kg。", content_md: "- 立地:**川越市 + 入間郡三芳町**\n- 起源:**江戸期 1700 年代後期栽培開始 250+ 年**\n- 認定:**「川越いも」全国ブランド + 「九里四里(栗より)うまい十三里」**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "川越市", lg_code: "11201", area_types: ["farm_field", "shopping_district"], lat: 35.9251, lon: 139.4858, season_start: "2026-09-01", season_end: "2026-12-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kawagoe_imo", "1700s", "edo_origin"], source: "manual" },
  { slug: "gyoda-fry", category: "food", sub_type: "saitama_3_meibutsu", title_zh: "行田フライ+ゼリーフライ(行田市・大正期 1910 年代発祥 110+ 年+ 戦時 B 級グルメ普及・行田市内 30+ 軒+ 小麦粉+ねぎ+卵+ソース・「フライ」「ゼリーフライ」2 系統+ 1 個 ¥350-700+ R1 育 行田古墳群観光連動)", title_ja: "行田フライ", romaji: "Gyōda Fry", summary_zh: "**行田フライ+ゼリーフライは大正期 1910 年代発祥 110+ 年・戦時 B 級グルメ普及**(行田・**市内 30+ 軒・「フライ」+「ゼリーフライ」2 系統**)。¥350-700、R1 育 行田古墳群連動。", content_md: "- 立地:**行田市**\n- 起源:**大正期 1910 年代発祥 110+ 年**\n- 構成:**フライ + ゼリーフライ 2 系統**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "行田市", lg_code: "11206", area_types: ["restaurant_traditional"], lat: 36.1389, lon: 139.4556, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["gyoda_fry", "1910s"], source: "manual" },

  // 郷土食 (4)
  { slug: "kawagoe-unagi-iseya", category: "food", sub_type: "saitama_kyodo", title_zh: "川越鰻+小江戸鰻料理(川越市・伊勢屋 1843 創業 182 年・小川菊 1832 創業 193 年 2 大老舗+ 江戸期 鰻 蒲焼伝統+ R1 育 川越蔵造り街観光客向け+ 1 重 ¥3,500-7,500+ 観光客代表)", title_ja: "川越鰻", romaji: "Kawagoe Unagi", summary_zh: "**川越鰻+小江戸鰻料理は 1832-1843 創業 182-193 年 2 大老舗**(川越・**伊勢屋+小川菊**)。江戸期蒲焼伝統、R1 育 蔵造り街連動、¥3,500-7,500/重。", content_md: "- 立地:**川越市**\n- 起源:**伊勢屋 1843 + 小川菊 1832 創業**\n- 構成:**江戸期鰻蒲焼伝統**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "川越市", lg_code: "11201", area_types: ["restaurant_traditional"], lat: 35.9251, lon: 139.4858, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["kawagoe_unagi", "1832", "1843"], source: "manual" },
  { slug: "soka-karinto-edo", category: "food", sub_type: "saitama_kyodo", title_zh: "草加かりんとう(草加市・R1 食 草加せんべい派生・江戸期から派生菓子・小麦粉+黒糖+揚げ・草加駅周辺老舗 5+ 軒+ R1 楽 草加宿場まつり観光連動・1 袋 ¥350-1,200+ 観光客代表土産)", title_ja: "草加かりんとう", romaji: "Sōka Karintō", summary_zh: "**草加かりんとうは R1 食 草加せんべい派生・江戸期から派生菓子**(草加・**老舗 5+ 軒**)。R1 楽 草加宿場まつり連動、¥350-1,200/袋、観光客代表土産。", content_md: "- 立地:**草加市**\n- 関係:**R1 食 草加せんべい派生**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "草加市", lg_code: "11221", area_types: ["restaurant_traditional", "shopping_district"], lat: 35.8252, lon: 139.8056, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["soka_karinto"], source: "manual" },
  { slug: "chichibu-soba", category: "food", sub_type: "saitama_kyodo", title_zh: "秩父そば(秩父市+小鹿野・荒川源流清流水+ 自家粉手打ち・江戸期から伝統・市内 25+ 軒・R1 育 三峯神社+秩父神社観光連動・「秩父太そば」品種・1 杯 ¥1,000-2,200)", title_ja: "秩父そば", romaji: "Chichibu Soba", summary_zh: "**秩父そばは荒川源流清流水+自家粉手打ち・江戸期から伝統**(秩父+小鹿野・**市内 25+ 軒・「秩父太そば」品種**)。R1 育 三峯+秩父神社連動、¥1,000-2,200。", content_md: "- 立地:**秩父市 + 秩父郡小鹿野町**\n- 起源:**江戸期から伝統**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "秩父市", lg_code: "11207", area_types: ["restaurant_traditional"], lat: 35.9914, lon: 139.0833, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["chichibu_soba"], source: "manual" },
  { slug: "kazo-udon-edo", category: "food", sub_type: "saitama_kyodo", title_zh: "加須うどん(加須市・江戸期 1700 年代発祥 300+ 年+ 利根川流域手打ちうどん・関東屈指麺文化+ R1 食 武蔵野うどん並ぶ埼玉 2 大うどん・市内 25+ 軒・1 杯 ¥800-1,500+ R1 楽 加須うどんまつり)", title_ja: "加須うどん", romaji: "Kazo Udon", summary_zh: "**加須うどんは江戸期 1700 年代発祥 300+ 年・利根川流域手打ちうどん**(加須・**市内 25+ 軒**)。R1 食 武蔵野うどん並ぶ 2 大うどん、¥800-1,500、R1 楽 加須うどんまつり。", content_md: "- 立地:**加須市**\n- 起源:**江戸期 1700 年代発祥 300+ 年**\n- 並列:**R1 食 武蔵野うどん + 加須うどん = 埼玉 2 大うどん**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "加須市", lg_code: "11210", area_types: ["restaurant_traditional"], lat: 36.1297, lon: 139.6011, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kazo_udon"], source: "manual" },

  // 川魚 (3)
  { slug: "urawa-unagi-1900", category: "food", sub_type: "saitama_seafood", title_zh: "浦和ウナギ(さいたま市浦和区・1900 年代以降「浦和の蒲焼」鰻文化発祥+ 浦和うなぎ取扱店組合 老舗 8+ 軒+ JR 浦和駅周辺+ R1 育 別所沼公園+調神社観光連動・1 重 ¥3,500-7,500)", title_ja: "浦和ウナギ", romaji: "Urawa Unagi", summary_zh: "**浦和ウナギは 1900 年代以降「浦和の蒲焼」鰻文化発祥**(浦和・**老舗 8+ 軒・JR 浦和駅周辺**)。R1 育 別所沼+調神社連動、¥3,500-7,500/重。", content_md: "- 立地:**さいたま市浦和区**\n- 起源:**1900 年代以降鰻文化発祥**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "さいたま市", lg_code: "11108", area_types: ["restaurant_traditional"], lat: 35.8617, lon: 139.6453, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["urawa_unagi"], source: "manual" },
  { slug: "chichibu-ayu", category: "food", sub_type: "saitama_seafood", title_zh: "秩父+荒川あゆ(秩父市+長瀞町+寄居・荒川+赤平川源流清流+ 友釣りあゆ伝承+ 6-9 月旬+ あゆ塩焼+刺身+南蛮漬+ R1 楽 長瀞ライン下り+R1 育 三峯神社観光連動+ 1 尾 ¥800-1,800)", title_ja: "秩父+荒川あゆ", romaji: "Chichibu Ayu", summary_zh: "**秩父+荒川あゆは荒川+赤平川源流清流・友釣り伝承・6-9 月旬**(秩父+長瀞+寄居)。塩焼+刺身+南蛮漬、R1 楽 長瀞ライン下り+R1 育 三峯連動、¥800-1,800/尾。", content_md: "- 立地:**秩父市 + 秩父郡長瀞町 + 大里郡寄居町**\n- 河川:**荒川 + 赤平川源流**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "秩父市", lg_code: "11207", area_types: ["restaurant_traditional"], lat: 35.9914, lon: 139.0833, season_start: "2026-06-01", season_end: "2026-09-30", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["chichibu_ayu"], source: "manual" },
  { slug: "haniyu-tonegawa-fish", category: "food", sub_type: "saitama_seafood", title_zh: "羽生+利根川川魚(羽生市+加須市+久喜・利根川+渡良瀬川流域+ コイ・フナ・ナマズ・ウナギ伝承料理+ 江戸期から伝統・川魚料理店 8+ 軒+ R1 食 加須うどん観光連動+ 1 人前 ¥1,800-3,500)", title_ja: "羽生+利根川川魚", romaji: "Haniyu Tonegawa Fish", summary_zh: "**羽生+利根川川魚は利根川+渡良瀬川流域・コイ+フナ+ナマズ+ウナギ伝承料理**(羽生+加須+久喜・**川魚料理店 8+ 軒**)。R1 食 加須うどん連動、¥1,800-3,500。", content_md: "- 立地:**羽生市 + 加須市 + 久喜市**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "羽生市", lg_code: "11216", area_types: ["restaurant_traditional"], lat: 36.1722, lon: 139.5478, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["haniyu_kawazakana"], source: "manual" },

  // 果実 (3)
  { slug: "chichibu-shine-muscat", category: "food", sub_type: "saitama_fruit", title_zh: "秩父シャインマスカット+ぶどう(秩父市+横瀬+小鹿野・標高 300-500m 高原気候+ 1980 年代以降開発・全国ぶどう産地上位+ 8-10 月旬+ ぶどう狩り 25+ 観光園+ R1 育 三峯神社+秩父観光連動+ 1 房 ¥2,500-5,500)", title_ja: "秩父シャインマスカット", romaji: "Chichibu Shine Muscat", summary_zh: "**秩父シャインマスカット+ぶどうは標高 300-500m 高原気候・1980 年代以降開発**(秩父+横瀬+小鹿野・**全国産地上位**)。8-10 月、狩り 25+ 園、¥2,500-5,500/房。", content_md: "- 立地:**秩父市 + 秩父郡横瀬町 + 小鹿野町**\n- 起源:**1980 年代以降開発**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "秩父市", lg_code: "11207", area_types: ["farm_field"], lat: 35.9914, lon: 139.0833, season_start: "2026-08-01", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["chichibu_shine_muscat"], source: "manual" },
  { slug: "yorii-mikan", category: "food", sub_type: "saitama_fruit", title_zh: "寄居+小川みかん(大里郡寄居町+比企郡小川町・関東屈指北限みかん産地・1700 年代から栽培+ 11-1 月旬+ みかん狩り 12+ 観光園+ 1kg ¥600-1,500+ R1 育 寄居北条石風呂観光連動+ 国内観光客冬代表)", title_ja: "寄居+小川みかん", romaji: "Yorii Mikan", summary_zh: "**寄居+小川みかんは関東屈指北限みかん産地・1700 年代から栽培**(寄居+小川・**11-1 月旬・狩り 12+ 観光園**)。¥600-1,500/kg、R1 育 寄居連動、国内観光客冬代表。", content_md: "- 立地:**大里郡寄居町 + 比企郡小川町**\n- 起源:**1700 年代から栽培**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: "大里郡", municipality_ja: "寄居町", lg_code: "11408", area_types: ["farm_field"], lat: 36.1108, lon: 139.1939, season_start: "2026-11-01", season_end: "2027-01-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yorii_mikan", "kanto_north_limit"], source: "manual" },
  { slug: "kazo-pear-no2", category: "food", sub_type: "saitama_fruit", title_zh: "加須+白岡なし(加須市+白岡市+久喜・全国なし生産量上位県+ 1900 年代以降産地化+ 「彩玉」県オリジナル品種・8-10 月旬+ なし狩り 20+ 観光園+ R1 食 加須うどん観光連動+ 1kg ¥800-1,800)", title_ja: "加須+白岡なし", romaji: "Kazo Shiraoka Pear", summary_zh: "**加須+白岡なしは全国生産量上位県・1900 年代以降産地化**(加須+白岡+久喜・**「彩玉」県オリジナル品種**)。8-10 月、狩り 20+ 園、R1 食 加須うどん連動、¥800-1,800/kg。", content_md: "- 立地:**加須市 + 白岡市 + 久喜市**\n- 認定:**全国なし生産量上位県 + 「彩玉」県オリジナル品種**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "加須市", lg_code: "11210", area_types: ["farm_field"], lat: 36.1297, lon: 139.6011, season_start: "2026-08-01", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kazo_pear", "saigyoku"], source: "manual" },

  // 銘菓 (5)
  { slug: "kawagoe-imo-sweets", category: "food", sub_type: "saitama_meika", title_zh: "川越芋スイーツ+菓子屋横丁(川越市・R1 食 川越サツマイモ派生・菓子屋横丁(国の登録有形文化財)・芋ようかん+芋餅+芋けんぴ+芋アイス・老舗 30+ 軒+ R1 育 川越蔵造り街観光中核+ ¥350-1,800)", title_ja: "川越芋スイーツ", romaji: "Kawagoe Imo Sweets", summary_zh: "**川越芋スイーツ+菓子屋横丁は R1 食 川越サツマイモ派生・菓子屋横丁(国の登録有形文化財)**(川越・**老舗 30+ 軒**)。R1 育 蔵造り街観光中核、¥350-1,800。", content_md: "- 立地:**川越市**\n- 関係:**R1 食 川越サツマイモ派生**\n- 認定:**菓子屋横丁(国の登録有形文化財)**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "川越市", lg_code: "11201", area_types: ["restaurant_traditional", "shopping_district"], lat: 35.9251, lon: 139.4858, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kawagoe_imo_sweets"], source: "manual" },
  { slug: "kawagoe-tokinokane-meika", category: "food", sub_type: "saitama_meika", title_zh: "川越時の鐘銘菓(川越市・R1 育 時の鐘 1894 派生・1900 年代開発・時の鐘最中+蔵の街サブレ+小江戸クッキー+ JR 川越駅+小江戸蔵里売店+全国百貨店流通+ ¥350-1,800+ R1 育 蔵造り街観光客代表土産)", title_ja: "川越時の鐘銘菓", romaji: "Kawagoe Tokinokane Meika", summary_zh: "**川越時の鐘銘菓は R1 育 時の鐘 1894 派生・1900 年代開発**(時の鐘最中+蔵の街サブレ+小江戸クッキー)。JR 川越駅+全国百貨店、¥350-1,800、R1 育 蔵造り街代表土産。", content_md: "- 立地:**川越市**\n- 関係:**R1 育 時の鐘 1894 派生**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "川越市", lg_code: "11201", area_types: ["restaurant_traditional", "shopping_district"], lat: 35.9251, lon: 139.4858, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kawagoe_tokinokane_meika"], source: "manual" },
  { slug: "chichibu-yokan", category: "food", sub_type: "saitama_meika", title_zh: "秩父羊羹+秩父銘菓(秩父市・1900 年代以降地元菓子店+ 秩父音楽羊羹+秩父七草もち・八幡屋本店 1879 創業 146 年+ JR 秩父駅売店+全国百貨店+ ¥1,200-2,500/箱+ R1 育 秩父神社観光連動)", title_ja: "秩父羊羹", romaji: "Chichibu Yōkan", summary_zh: "**秩父羊羹+秩父銘菓は 1900 年代以降地元菓子店・八幡屋本店 1879 創業 146 年**(秩父・**音楽羊羹+七草もち**)。JR 秩父駅+百貨店、¥1,200-2,500/箱、R1 育 秩父神社連動。", content_md: "- 立地:**秩父市**\n- 起源:**八幡屋本店 1879 創業 146 年**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "秩父市", lg_code: "11207", area_types: ["restaurant_traditional"], lat: 35.9914, lon: 139.0833, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["chichibu_yokan", "1879"], source: "manual" },
  { slug: "kawagoe-monaka-meika", category: "food", sub_type: "saitama_meika", title_zh: "亀屋川越本店 1783 銘菓(川越市・天明 3 年 1783 創業 242 年+ 県内最古和菓子老舗候補+ R1 食 川越サツマイモ派生最中・亀の最中+小江戸サブレ+ 国登録有形文化財店舗+ JR 川越駅売店+全国百貨店+ ¥350-2,500)", title_ja: "亀屋川越本店", romaji: "Kameya Kawagoe", summary_zh: "**亀屋川越本店は天明 3 年 1783 創業 242 年・県内最古和菓子老舗候補**(川越・**国登録有形文化財店舗**)。R1 食 サツマイモ派生最中、JR 川越駅+全国百貨店、¥350-2,500。", content_md: "- 立地:**川越市**\n- 起源:**天明 3 年 1783 創業 242 年**\n- 認定:**県内最古和菓子老舗候補 + 国登録有形文化財店舗**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "川越市", lg_code: "11201", area_types: ["restaurant_traditional", "history_site_castle"], lat: 35.9251, lon: 139.4858, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kameya_kawagoe", "1783", "242_years"], source: "manual" },
  { slug: "saitama-kobaton-meika", category: "food", sub_type: "saitama_meika", title_zh: "コバトン+さいたまっち県マスコット銘菓(全県・2005 県マスコット コバトン 20 年+ 2014 さいたまっち追加・公式マスコット銘菓・コバトン最中+どら焼き+クッキー+ JR 駅売店+全国百貨店流通+ ¥350-1,500)", title_ja: "コバトン銘菓", romaji: "Kobaton Meika", summary_zh: "**コバトン+さいたまっち県マスコット銘菓は 2005 県マスコット 20 年・2014 さいたまっち追加**(全県・**公式銘菓最中+どら焼き+クッキー**)。JR 駅+百貨店、¥350-1,500。", content_md: "- 全域:**埼玉県全域**\n- 起源:**2005 県マスコット 20 年**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "さいたま市", lg_code: "11100", area_types: ["shopping_district"], lat: 35.9059, lon: 139.6238, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kobaton_meika", "2005"], source: "manual" },

  // 酒 (3)
  { slug: "shinkame-1848-hasuda", category: "food", sub_type: "saitama_sake", title_zh: "神亀酒造(蓮田市・嘉永元年 1848 創業 177 年+ 「神亀」純米酒のみで現代日本酒復活運動の代表蔵+ 1987 全国初純米蔵宣言+ 全国新酒鑑評会金賞常連+ 720ml ¥3,500-12,000+ 国際 SNS 海外輸出代表)", title_ja: "神亀酒造", romaji: "Shinkame", summary_zh: "**神亀酒造は嘉永元年 1848 創業 177 年・1987 全国初純米蔵宣言・現代日本酒復活運動代表**(蓮田・**全国新酒鑑評会金賞常連**)。¥3,500-12,000/720ml、国際 SNS 海外輸出代表。", content_md: "- 立地:**蓮田市**\n- 起源:**嘉永元年 1848 創業 177 年**\n- 認定:**1987 全国初純米蔵宣言 + 現代日本酒復活運動代表**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "蓮田市", lg_code: "11238", area_types: ["industrial_heritage"], lat: 35.9994, lon: 139.6531, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["shinkame", "1848", "177_years", "junmai_pioneer"], source: "manual" },
  { slug: "yokota-shuzo-1805", category: "food", sub_type: "saitama_sake", title_zh: "横田酒造(羽生市・文化 2 年 1805 創業 220 年+ 「日本橋」純米吟醸+大吟醸+ 全国新酒鑑評会金賞常連+ R1 食 羽生川魚観光連動+ 720ml ¥2,500-7,500+ 全国百貨店流通+ R1 食 神亀 1848 と並ぶ埼玉地酒老舗 2 大)", title_ja: "横田酒造", romaji: "Yokota Shuzō", summary_zh: "**横田酒造は文化 2 年 1805 創業 220 年・「日本橋」純米吟醸+大吟醸**(羽生・**全国新酒鑑評会金賞常連**)。R1 食 羽生川魚連動、¥2,500-7,500/720ml、神亀 1848 と並ぶ。", content_md: "- 立地:**羽生市**\n- 起源:**文化 2 年 1805 創業 220 年**\n- 看板:**「日本橋」純米吟醸 + 大吟醸**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "羽生市", lg_code: "11216", area_types: ["industrial_heritage"], lat: 36.1722, lon: 139.5478, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yokota", "1805", "220_years"], source: "manual" },
  { slug: "kamaya-shuzo-1748", category: "food", sub_type: "saitama_sake", title_zh: "釜屋酒造(加須市騎西・寛延元年 1748 創業 277 年+ 埼玉最古酒蔵候補+ 「釜屋」純米吟醸+大吟醸+ 全国新酒鑑評会金賞常連+ R1 食 加須うどん観光連動・720ml ¥2,500-7,500+ 神亀 1848+横田 1805+釜屋 1748 = 埼玉地酒 3 大老舗)", title_ja: "釜屋酒造", romaji: "Kamaya Shuzō", summary_zh: "**釜屋酒造は寛延元年 1748 創業 277 年・埼玉最古酒蔵候補**(加須騎西・**全国新酒鑑評会金賞常連**)。R1 食 加須うどん連動、¥2,500-7,500/720ml、神亀+横田+釜屋 = 地酒 3 大老舗。", content_md: "- 立地:**加須市騎西**\n- 起源:**寛延元年 1748 創業 277 年**\n- 認定:**埼玉最古酒蔵候補**\n- 並列:**神亀 1848 + 横田 1805 + 釜屋 1748 = 埼玉地酒 3 大老舗**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "加須市", lg_code: "11210", area_types: ["industrial_heritage"], lat: 36.1297, lon: 139.6011, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kamaya", "1748", "277_years", "saitama_oldest"], source: "manual" },

  // 米肉 (2)
  { slug: "saitama-bushu-gyu", category: "food", sub_type: "saitama_meat", title_zh: "武州和牛+秩父牛(秩父市+小鹿野+横瀬・1990 年代ブランド化 35 年+ 県内 約 100 戸生産・A4 以上限定+ R1 食 上州牛(群馬)+常陸牛(茨城)系統 関東甲信越ブランド和牛+ ¥6,500-12,500/100g+ R1 育 秩父観光連動)", title_ja: "武州和牛+秩父牛", romaji: "Bushū Gyū", summary_zh: "**武州和牛+秩父牛は 1990 年代ブランド化 35 年・県内 100 戸生産・A4 以上限定**(秩父+小鹿野+横瀬)。R1 食 上州+常陸牛系統、¥6,500-12,500/100g、R1 育 秩父連動。", content_md: "- 立地:**秩父市 + 秩父郡小鹿野町 + 横瀬町**\n- 起源:**1990 年代ブランド化 35 年**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "秩父市", lg_code: "11207", area_types: ["farm_field", "restaurant_traditional"], lat: 35.9914, lon: 139.0833, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["bushu_gyu"], source: "manual" },
  { slug: "saitama-koshihikari", category: "food", sub_type: "saitama_kyodo", title_zh: "埼玉コシヒカリ+ 彩のかがやき+彩のきずな(全県・全国コシヒカリ生産量上位県+ 県オリジナル「彩のかがやき」「彩のきずな」品種・全国食味ランキング A+ 1kg ¥1,200-2,500+ JR 駅+全国百貨店流通+ R1 育 川越蔵造り街観光連動)", title_ja: "埼玉コシヒカリ", romaji: "Saitama Koshihikari", summary_zh: "**埼玉コシヒカリ+彩のかがやき+彩のきずなは全国上位県・県オリジナル 2 品種**(全県・**全国食味 A**)。¥1,200-2,500/kg、R1 育 川越蔵造り街連動。", content_md: "- 全域:**埼玉県全域**\n- 認定:**全国コシヒカリ生産量上位県 + 「彩のかがやき」「彩のきずな」県オリジナル品種**", region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "さいたま市", lg_code: "11100", area_types: ["farm_field"], lat: 35.9059, lon: 139.6238, season_start: "2026-09-15", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["saitama_koshihikari", "sai_no_kagayaki"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[saitama-food-r1] 尚無條目"); return; }
  console.log(`[saitama-food-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[saitama-food-r1] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[saitama-food-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[saitama-food-r1] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
