// Seed 大阪府 · 楽類 條目 → public.japan_entries(Sprint 17.6 樂 R1)
//
// 大阪の樂類軸:
//   - USJ(2001 開業)+ Super Nintendo World(2021)+ ハリポタ(2014)+ ミニオン(2017)
//   - 海遊館(1990 世界最大級水族館・ジンベエザメ)+ 天王寺動物園(1915 国内最古級)
//   - 桜:大阪城 3000 本 + 造幣局桜の通り抜け 340 品種 + 毛馬桜之宮 4500 本
//   - 紅葉:箕面公園(滝百選)+ 観心寺(楠木菩提寺)+ 牛滝山
//   - 花火:天神祭奉納 5000 発 + 淀川 15000 発 + PL 15000 発(関西最大)
//   - イルミ:大阪光の饗宴(御堂筋イルミ + OSAKA 光のルネサンス)11-1 月
//   - 万博 2025 (4/13-10/13) → EXPO CITY 跡地 + ニフレル + OSAKA WHEEL
//   - スポーツ:京セラドーム(オリックス本拠)+ ヤンマー(セレッソ)
//   - 夜景:あべのハルカス 300 + 通天閣 + 道頓堀グリコ + 梅田スカイ
//   - 温泉:スパワールド(8 国の風呂)+ 箕面温泉スパガーデン
//
// 嚴格定義:具体テーマパーク・実在花火大会・実在桜名所・季節食材体験のみ。概論なし。
//
// 45 筆構成
//
// Usage:
//   npm run seed:japan-osaka-entertainment:dry
//   npm run seed:japan-osaka-entertainment

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "theme_park"
  | "sakura"
  | "momiji"
  | "firework_festival"
  | "illumination"
  | "flower_field"
  | "aquarium_zoo"
  | "music_festival"
  | "sports_spectate"
  | "seasonal_food"
  | "osaka_night_view"
  | "osaka_onsen_spa";

interface SeedRow {
  slug: string;
  category: "entertainment";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "kansai";
  prefecture_ja: "大阪府";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ══════════════════════════════════════════════════════════════════
  // A. テーマパーク(8 筆) — USJ 5 + ひらかたパーク + ニフレル + EXPO CITY
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "usj-universal-studios-japan",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ユニバーサル・スタジオ・ジャパン(USJ・2001 開業・年 1500 万人)",
    title_ja: "ユニバーサル・スタジオ・ジャパン",
    romaji: "Universal Studios Japan",
    summary_zh:
      "2001 大阪市此花区桜島(大阪湾埋立地)に開業のユニバーサル映画スタジオ系テーマパーク。アジア初の USJ。総面積 54 ha・10 のエリア(ハリーポッター + ミニオンパーク + Super Nintendo World 等)。年間入場 1500 万人余で東京ディズニーランドに次ぐ日本第 2 位テーマパーク。",
    content_md:
      "- 開業:2001\n- 立地:大阪市此花区桜島(大阪湾)\n- 面積:54 ha\n- 入場:年 1500 万人余\n- 主要エリア:Super Nintendo World + ハリポタ + ミニオン + ジュラシック\n- パス:1 デイ ¥8400-(変動制)\n- アクセス:JR ゆめ咲線 ユニバーサルシティ駅\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.665,
    lon: 135.432,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.usj.co.jp/" },
    tags: ["theme_park", "usj", "universal", "konohanaku", "yumesaki"],
    source: "manual",
  },
  {
    slug: "usj-super-nintendo-world",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "Super Nintendo World(2021 開園・USJ 世界初の任天堂エリア)",
    title_ja: "スーパー・ニンテンドー・ワールド",
    romaji: "Super Nintendo World",
    summary_zh:
      "2021/3/18 USJ 内に開園した世界初のニンテンドー公式テーマエリア。マリオの世界を原寸再現,『マリオカート ~ クッパの挑戦状 ~』(ライド)+『ヨッシー・アドベンチャー』(ファミリーライド)+ パワーアップバンド連動アクティビティ。2024 ドンキーコングカントリー拡張。USJ 入場者の半数以上が利用。整理券 + アプリで時間予約必須。",
    content_md:
      "- 開園:2021/3/18\n- 世界初の任天堂公式テーマエリア\n- 主要ライド:マリオカート + ヨッシー\n- 2024 ドンキーコングカントリー拡張\n- パワーアップバンド:アクティビティ連動装置\n- 整理券・アプリ予約必須\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.665,
    lon: 135.432,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.usj.co.jp/web/ja/jp/area/usj-super-nintendo-world" },
    tags: ["theme_park", "usj", "nintendo", "mario", "since_2021"],
    source: "manual",
  },
  {
    slug: "usj-harry-potter-area",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ウィザーディング・ワールド・オブ・ハリー・ポッター(USJ・2014 開園)",
    title_ja: "ウィザーディング・ワールド・オブ・ハリー・ポッター",
    romaji: "Wizarding World of Harry Potter",
    summary_zh:
      "2014/7/15 USJ 内に開園した世界 2 番目のハリーポッターエリア(初は米オーランド USJ・2010)。ホグワーツ城原寸再現 + ホグズミード村再現 + 『ハリー・ポッター・アンド・ザ・フォービドゥン・ジャーニー』(4D ライド)+ ホグワーツ・エクスプレス。バタービール販売。USJ の象徴的エリア,2014 開園以来集客牽引。",
    content_md:
      "- 開園:2014/7/15\n- 世界 2 番目(初は米オーランド 2010)\n- 主要ライド:フォービドゥン・ジャーニー(4D)\n- 再現:ホグワーツ城 + ホグズミード村\n- 名物:バタービール ¥600-1100\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.665,
    lon: 135.432,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.usj.co.jp/web/ja/jp/area/wizarding-world-of-harry-potter" },
    tags: ["theme_park", "usj", "harry_potter", "since_2014", "hogwarts"],
    source: "manual",
  },
  {
    slug: "usj-minion-park",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ミニオン・パーク(USJ・2017 開園・世界最大ミニオンエリア)",
    title_ja: "ミニオン・パーク",
    romaji: "Minion Park",
    summary_zh:
      "2017/4/21 USJ 内に開園した世界最大のミニオン公式テーマエリア。『ディスピカブル・ミー・ミニオン・メイヘム』(モーションシミュレーターライド)+ ミニオン・ハチャメチャ・ライド。ミニオングッズ + フォト撮影が中心,USJ ファミリー客の人気 No.1 エリア。",
    content_md:
      "- 開園:2017/4/21\n- 世界最大のミニオン公式エリア\n- 主要ライド:ミニオン・メイヘム(シミュレーター)\n- ファミリー客 No.1 人気\n- グッズ + フォト撮影中心\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.665,
    lon: 135.432,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.usj.co.jp/web/ja/jp/area/minion-park" },
    tags: ["theme_park", "usj", "minion", "since_2017", "family"],
    source: "manual",
  },
  {
    slug: "usj-jurassic-park",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ジュラシック・パーク・エリア(USJ・2001 開園・The Ride + The Flying Dinosaur)",
    title_ja: "ジュラシック・パーク・エリア",
    romaji: "Jurassic Park Area",
    summary_zh:
      "2001 USJ 開業時からの基幹エリア。『ジュラシック・パーク・ザ・ライド』(ボートシューティング)+ 2016 開園『ザ・フライング・ダイナソー』(世界最長フライングコースター・1124 m)。フライングは仰向け吊り下げ式で『恐竜に掴まれた』体験。USJ スリル系の代表。",
    content_md:
      "- 開園:2001(基幹エリア)\n- 主要ライド 1:ジュラシック・パーク・ザ・ライド\n- 主要ライド 2:ザ・フライング・ダイナソー(2016・世界最長フライング 1124 m)\n- フライング:仰向け吊り下げ式\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.665,
    lon: 135.432,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.usj.co.jp/web/ja/jp/area/jurassic-park" },
    tags: ["theme_park", "usj", "jurassic", "thrill"],
    source: "manual",
  },
  {
    slug: "hirakata-park",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ひらかたパーク(1912 開園・関西最古遊園地・ローカルランドマーク)",
    title_ja: "ひらかたパーク",
    romaji: "Hirakata Park",
    summary_zh:
      "1912 京阪電気鉄道(枚方公園駅前)が開園した日本現存最古級遊園地・関西最古遊園地。木製コースター『エルフ』(1976 開業現役)+ 観覧車『スカイウォーカー』(高 80 m)等 30 機種以上。冬期スケート場 + 夏期プール『ザ・ブーン』。地元 V6 岡田准一の応援大使でも知られる。",
    content_md:
      "- 開園:1912(関西最古・日本現存最古級)\n- 運営:京阪電鉄\n- 主要ライド:30 機種余\n- 冬期:スケート場\n- 夏期:プール『ザ・ブーン』\n- 入園:¥1800-(キャラクターパス含む ¥4900)\n- アクセス:京阪枚方公園駅徒歩 3 分\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "枚方市",
    lg_code: "27210",
    area_types: ["urban"],
    lat: 34.815,
    lon: 135.654,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.hirakatapark.co.jp/" },
    tags: ["theme_park", "hirapa", "since_1912", "keihan"],
    source: "manual",
  },
  {
    slug: "nifrel-suita",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ニフレル(NIFREL・2015 開園・万博公園・生体感じる新型水族館)",
    title_ja: "ニフレル",
    romaji: "Nifrel",
    summary_zh:
      "2015 万博記念公園 EXPO CITY 内に開園の海遊館プロデュース新型水族館。『感性にふれる』をコンセプトに,動物と植物の境界 + 色彩 + わざ + すがた + みず 等 8 ゾーンで生体展示。ホワイトタイガー + ミニカバ + ペンギン + ワオキツネザル等の哺乳類 + 鳥類 + 魚類混合展示。",
    content_md:
      "- 開園:2015\n- 立地:EXPO CITY 内\n- 運営:海遊館プロデュース\n- 8 ゾーン:色 + わざ + すがた + 水中 + みず + WONDER MOMENTS + うごき + 触れる\n- 主要動物:ホワイトタイガー + ミニカバ\n- 入館:9:30-19:00 ¥2200\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "吹田市",
    lg_code: "27205",
    area_types: ["urban", "suburban"],
    lat: 34.806,
    lon: 135.535,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.nifrel.jp/" },
    tags: ["aquarium", "nifrel", "expo_city", "kaiyukan_brand"],
    source: "manual",
  },
  {
    slug: "expo-city-osaka-wheel",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "OSAKA WHEEL(2016 EXPO CITY・高 123 m 日本最大級観覧車)",
    title_ja: "OSAKA WHEEL",
    romaji: "Osaka Wheel",
    summary_zh:
      "2016 EXPO CITY 開業時に設置の高 123 m・直径 100 m 観覧車。日本最大の観覧車(東京の大観覧車パレットタウン 115 m + リバーサイドパーク 100 m を超える)。全 72 ゴンドラ全シースルー床採用 + Wi-Fi 完備。1 周 18 分。万博公園 + 太陽の塔 + 大阪市内一望。",
    content_md:
      "- 開業:2016\n- 高さ:123 m(日本最大)\n- 直径:100 m\n- ゴンドラ:72 機(全シースルー床 + Wi-Fi)\n- 1 周:18 分\n- 営業:10:00-22:00 ¥1000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "吹田市",
    lg_code: "27205",
    area_types: ["urban", "suburban"],
    lat: 34.808,
    lon: 135.536,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://osaka-wheel.com/" },
    tags: ["ferris_wheel", "expo_city", "japan_largest", "since_2016"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // B. 水族館・動物園(2 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "osaka-kaiyukan",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "海遊館(1990 開館・世界最大級水族館・ジンベエザメ)",
    title_ja: "海遊館",
    romaji: "Kaiyūkan",
    summary_zh:
      "1990 港区天保山に開館した世界最大級水族館。ピーター・チャマイヤー設計の 8 階建て構造で,中央巨大水槽『太平洋』(深 9 m × 幅 34 m × 容積 5400 t)を上から下まで螺旋状に巡る独自の動線。ジンベエザメ 2 頭 + マンタ + イルカ + ペンギン等 620 種・3 万点。年間 250 万人来館。",
    content_md:
      "- 開館:1990\n- 立地:港区天保山\n- 設計:ピーター・チャマイヤー\n- 中央水槽:太平洋(5400 t・深 9 m)\n- 主要展示:ジンベエザメ 2 頭 + マンタ + イルカ\n- 種数:620 種 3 万点\n- 入館:10:00-20:00 ¥2700\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.654,
    lon: 135.428,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.kaiyukan.com/" },
    tags: ["aquarium", "kaiyukan", "whaleshark", "tempozan"],
    source: "manual",
  },
  {
    slug: "tennoji-zoo",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "天王寺動物園(1915 開園・国内最古級・関西最大都市型動物園)",
    title_ja: "天王寺動物園",
    romaji: "Tennōji Dōbutsuen",
    summary_zh:
      "1915 開園の国内 3 番目古い動物園(上野 1882・京都 1903 に次ぐ)。天王寺公園内 11 ha・関西最大都市型動物園。コアラ 4 頭(日本最古飼育園)+ ライオン + キリン + ホッキョクグマ等 180 種・1000 点。あべのハルカスから一望できる立地。",
    content_md:
      "- 開園:1915(国内 3 番目古い)\n- 立地:天王寺公園内\n- 面積:11 ha\n- 種数:180 種 1000 点\n- 主要動物:コアラ + ライオン + ホッキョクグマ\n- 入園:9:30-17:00 月曜休 ¥500\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.653,
    lon: 135.508,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["mon"],
    external_urls: { official: "https://www.tennojizoo.jp/" },
    tags: ["zoo", "tennoji", "since_1915", "koala"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // C. 桜(5 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "osaka-castle-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "大阪城公園 桜(西の丸庭園 300 本 + 公園 3000 本・夜桜)",
    title_ja: "大阪城公園 桜",
    romaji: "Ōsaka-jō Kōen Sakura",
    summary_zh:
      "大阪城公園内 3000 本の桜(ソメイヨシノ 中心)。最人気は西の丸庭園(300 本・有料区域・夜桜ライトアップ 18:00-21:00)。3 月末 - 4 月初開花。重要文化財の千貫櫓 + 大手門 + 大阪城天守閣のバックドロップで夜桜撮影定番。",
    content_md:
      "- 規模:公園内 3000 本\n- 西の丸庭園:300 本(有料 ¥350)\n- 開花:3 月末 - 4 月初\n- 夜桜ライトアップ:18:00-21:00(西の丸)\n- バック:天守閣 + 千貫櫓\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.687,
    lon: 135.526,
    season_start: "2026-03-25",
    season_end: "2026-04-10",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "osaka_castle", "yozakura", "spring"],
    source: "manual",
  },
  {
    slug: "zoheikyoku-sakura-toshikenukei",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "造幣局 桜の通り抜け(340 品種 600 本・年 1 回 1 週間限定)",
    title_ja: "造幣局 桜の通り抜け",
    romaji: "Zōheikyoku Sakura no Tōrinukei",
    summary_zh:
      "1883 造幣局構内に植えられた桜が,1883 当時局長遠藤謹助の発案で年 1 回 1 週間市民開放。340 品種 600 本(ソメイヨシノ + 八重桜 + 普賢象 等)で,日本の里桜の博物館。4 月中旬の 7 日間のみ事前予約制(2025 から)。560 m の通り抜け道で約 100 万人来訪。",
    content_md:
      "- 創始:1883 遠藤謹助局長\n- 規模:340 品種 600 本(里桜博物館)\n- 開催:4 月中旬・7 日間\n- 距離:560 m 通り抜け\n- 動員:約 100 万人/年\n- 2025- 事前予約制\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.696,
    lon: 135.528,
    season_start: "2026-04-10",
    season_end: "2026-04-16",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "zoheikyoku", "satozakura", "annual_event"],
    source: "manual",
  },
  {
    slug: "kema-sakuranomiya-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "毛馬桜之宮公園 桜(大川沿 4500 本・4 km 桜並木・関西桜百選)",
    title_ja: "毛馬桜之宮公園",
    romaji: "Kema Sakuranomiya Kōen",
    summary_zh:
      "毛馬閘門 → 大川沿 → 桜宮橋 → 天神橋の 4 km 河川敷公園。4500 本のソメイヨシノが連なる関西桜百選。3 月末 - 4 月初開花。隣接の大阪市中央公会堂(中之島)+ 中之島公園と合わせ大阪市内最大花見スポット。屋台多数 + 川沿散歩 + ランニング向き。",
    content_md:
      "- 規模:4500 本\n- 距離:4 km(毛馬閘門 - 天神橋)\n- 開花:3 月末 - 4 月初\n- 関西桜百選\n- 屋台多数\n- 中之島公園隣接\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.704,
    lon: 135.523,
    season_start: "2026-03-25",
    season_end: "2026-04-10",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "okawa", "sakuranomiya", "kansai_100", "yatai"],
    source: "manual",
  },
  {
    slug: "expo-koen-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "万博記念公園 桜(5500 本・関西桜百選・ライトアップ)",
    title_ja: "万博記念公園 桜",
    romaji: "Banpaku Kinen Kōen Sakura",
    summary_zh:
      "万博記念公園 260 ha 内の 5500 本桜(ソメイヨシノ + シダレザクラ + 八重桜 等 9 種)。関西桜百選。3 月下旬 - 4 月中旬開花。日本庭園(枯山水 + シダレザクラ)+ 自然文化園 + 太陽の塔バックドロップ。3 月末 - 4 月初の桜まつり期間夜間ライトアップ。",
    content_md:
      "- 規模:5500 本(9 種)\n- 関西桜百選\n- 開花:3 月下旬 - 4 月中旬\n- 桜まつり期間:夜間ライトアップ\n- バック:太陽の塔\n- 入園:¥260\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "吹田市",
    lg_code: "27205",
    area_types: ["urban", "suburban"],
    lat: 34.808,
    lon: 135.535,
    season_start: "2026-03-25",
    season_end: "2026-04-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["wed"],
    external_urls: { official: "https://www.expo70-park.jp/" },
    tags: ["sakura", "expo_park", "kansai_100", "yozakura"],
    source: "manual",
  },
  {
    slug: "takatsuki-shiroyama-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "高槻城跡公園 桜(200 本・西国街道沿の落穏花見)",
    title_ja: "高槻城跡公園 桜",
    romaji: "Takatsuki Shiroyama Sakura",
    summary_zh:
      "高槻城跡公園内 200 本の桜。高山右近時代の石垣 + 内堀復元と桜を組合わせた歴史的景観。3 月末 - 4 月初開花。大阪都心の混雑を避ける落穏花見スポットで地元客中心。",
    content_md:
      "- 規模:200 本\n- 開花:3 月末 - 4 月初\n- 高山右近石垣 + 内堀\n- 落穏花見・地元客中心\n- 入園:24h 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "高槻市",
    lg_code: "27207",
    area_types: ["urban"],
    lat: 34.846,
    lon: 135.616,
    season_start: "2026-03-25",
    season_end: "2026-04-10",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "takatsuki", "shiroyama", "quiet_hanami"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // D. 紅葉(3 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "minoo-koen-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "箕面公園 紅葉(箕面の滝・滝百選・モミジの天ぷら)",
    title_ja: "箕面公園",
    romaji: "Minō Kōen",
    summary_zh:
      "箕面市の箕面公園内 5000 本余のモミジが紅葉する関西紅葉名所。中心は箕面の滝(高 33 m・日本の滝百選 + 名水百選)。11 月中旬 - 12 月初開葉,11 月下旬最盛期。阪急電車の終点箕面駅から 2.7 km の滝道を徒歩 40 分散策が定番。名物『もみじの天ぷら』(モミジの葉天ぷら・1300 年前から)。",
    content_md:
      "- 規模:5000 本余モミジ\n- 中心:箕面の滝(高 33 m・滝百選 + 名水百選)\n- 開葉:11 月中旬 - 12 月初\n- 最盛期:11 月下旬\n- 滝道:2.7 km(阪急箕面 → 滝)\n- 名物:もみじの天ぷら\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "箕面市",
    lg_code: "27220",
    area_types: ["mountain", "rural"],
    lat: 34.842,
    lon: 135.469,
    season_start: "2026-11-15",
    season_end: "2026-12-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["momiji", "minoo", "waterfall_100", "meisui_100"],
    source: "manual",
  },
  {
    slug: "kanshin-ji-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "観心寺 紅葉(楠木正成菩提寺・国宝金堂と紅葉)",
    title_ja: "観心寺 紅葉",
    romaji: "Kanshin-ji Momiji",
    summary_zh:
      "河内長野山中の観心寺(楠木正成菩提寺・国宝金堂)境内 1000 本余のモミジ。11 月中旬 - 12 月初紅葉,11 月下旬最盛期。国宝金堂(室町期)+ 国宝建掛塔と紅葉のコラボが奥河内の代表的紅葉景観。京都の混雑を避ける穴場で関西紅葉通の人気。",
    content_md:
      "- 規模:1000 本余モミジ\n- 開葉:11 月中旬 - 12 月初\n- 最盛期:11 月下旬\n- バック:国宝金堂 + 建掛塔\n- 楠木正成菩提寺\n- 京都穴場として人気\n- 拝観:9:00-17:00 ¥400\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "河内長野市",
    lg_code: "27216",
    area_types: ["mountain", "rural"],
    lat: 34.404,
    lon: 135.567,
    season_start: "2026-11-15",
    season_end: "2026-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["momiji", "kanshin_ji", "kusunoki", "国宝"],
    source: "manual",
  },
  {
    slug: "ushiotaki-momiji-kishiwada",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "牛滝山大威徳寺 紅葉(岸和田・大阪 紅葉の名所)",
    title_ja: "牛滝山大威徳寺",
    romaji: "Ushiotaki-san Daiitoku-ji",
    summary_zh:
      "岸和田市山中の大威徳寺境内 + 牛滝(三段瀑)+ モミジ 3000 本余の紅葉名所。11 月中旬 - 12 月初紅葉。多宝塔(室町期・国指定重文)+ 紅葉が大阪 No.1 の構図。3 段の滝(一の滝 + 二の滝 + 錦流の滝)沿いの紅葉散策路。",
    content_md:
      "- 規模:3000 本余モミジ\n- 滝:三段瀑(一の滝 + 二の滝 + 錦流の滝)\n- 開葉:11 月中旬 - 12 月初\n- 重文:多宝塔(室町期)\n- 大阪 No.1 紅葉構図\n- 拝観:9:00-16:00 ¥300\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "岸和田市",
    lg_code: "27202",
    area_types: ["mountain", "rural"],
    lat: 34.444,
    lon: 135.434,
    season_start: "2026-11-15",
    season_end: "2026-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["momiji", "ushiotaki", "kishiwada", "重要文化財"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // E. 花火(4 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "tenjin-matsuri-hanabi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "天神祭奉納花火(7/25・5000 発・船渡御と同時開催)",
    title_ja: "天神祭奉納花火",
    romaji: "Tenjin Matsuri Hōnō Hanabi",
    summary_zh:
      "天神祭(日本三大祭)本宮の 7/25 夜 19:30-21:00 に大川河川敷で打上げる奉納花火 5000 発。船渡御の御鳳輦船 100 隻 + 篝火と同時演出で,大川を背景に花火 + 篝火 + 船 + 都市夜景の四重奏。観覧場所:桜之宮公園 + 川崎橋 + 国分寺橋 + 帝国ホテル前。動員 130 万人(2 日間)。",
    content_md:
      "- 開催:7/25 19:30-21:00\n- 規模:5000 発\n- 場所:大川(桜之宮公園周辺)\n- 同時:船渡御 + 篝火\n- 動員:130 万人(2 日間)\n- 観覧無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.696,
    lon: 135.516,
    season_start: null,
    season_end: null,
    event_start: "2026-07-25",
    event_end: "2026-07-25",
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://osakatemmangu.or.jp/" },
    tags: ["fireworks", "tenjin_matsuri", "july", "okawa"],
    source: "manual",
  },
  {
    slug: "naniwa-yodogawa-hanabi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "なにわ淀川花火大会(1989 創始・8 月・15000 発・関西最大級)",
    title_ja: "なにわ淀川花火大会",
    romaji: "Naniwa Yodogawa Hanabi Taikai",
    summary_zh:
      "1989 創始の関西最大級花火大会。8 月第 1 土曜の 19:50-20:40 新淀川河川敷(十三大橋 - 阪神高速の間)で打上げる 15000 発。動員 50 万人。観覧場所:十三河川敷 + 海老江南公園 + リバーサイド地区。屋台 200 軒余・有料席 ¥3000-7000。",
    content_md:
      "- 創始:1989\n- 開催:8 月第 1 土曜 19:50-20:40\n- 規模:15000 発\n- 関西最大級\n- 動員:50 万人\n- 場所:新淀川河川敷(十三大橋 - 阪神高速)\n- 有料席:¥3000-7000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban"],
    lat: 34.715,
    lon: 135.495,
    season_start: null,
    season_end: null,
    event_start: "2026-08-01",
    event_end: "2026-08-01",
    price_tier: 0,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.yodohanabi.com/" },
    tags: ["fireworks", "yodogawa", "august", "kansai_largest"],
    source: "manual",
  },
  {
    slug: "pl-hanabi-tondabayashi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "PL 花火芸術(1953 創始・8/1・15000 発・宗教法人主催・大阪最大)",
    title_ja: "PL 花火芸術",
    romaji: "PL Hanabi Geijutsu",
    summary_zh:
      "1953 PL 教団(パーフェクト リバティー教団・富田林本部)が教祖祭として始めた花火大会。毎年 8/1 19:50-20:40 富田林市の PL 教団本部敷地内で 15000 発打上げ。日本最大級の花火大会で,『PL 花火』として全国知名。富田林駅から徒歩 1 km の大阪平野一望の高台が観覧場所。",
    content_md:
      "- 創始:1953(PL 教団教祖祭)\n- 開催:8/1 19:50-20:40\n- 規模:15000 発\n- 主催:PL 教団(宗教法人)\n- 場所:PL 教団本部(富田林)\n- 動員:30 万人\n- 観覧無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "富田林市",
    lg_code: "27214",
    area_types: ["urban", "suburban"],
    lat: 34.503,
    lon: 135.591,
    season_start: null,
    season_end: null,
    event_start: "2026-08-01",
    event_end: "2026-08-01",
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["fireworks", "pl", "tondabayashi", "august_1"],
    source: "manual",
  },
  {
    slug: "izumiotsu-rinkukoen-hanabi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "りんくう花火(2010 創始・関空対岸・8 月下旬・5000 発)",
    title_ja: "りんくう花火",
    romaji: "Rinkū Hanabi",
    summary_zh:
      "2010 創始,泉佐野市りんくう公園(関空連絡橋根元)で開催の花火大会。8 月下旬土曜 20:00-20:45 打上 5000 発。海上花火 + 関空島背景の独特の景観。動員 5 万人。りんくう公園の砂浜から関空連絡橋越しに花火を見る構図が SNS 人気。",
    content_md:
      "- 創始:2010\n- 開催:8 月下旬土曜 20:00-20:45\n- 規模:5000 発\n- 場所:りんくう公園(関空対岸)\n- 動員:5 万人\n- バック:関空連絡橋\n- 観覧無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "泉佐野市",
    lg_code: "27213",
    area_types: ["urban", "coastal"],
    lat: 34.430,
    lon: 135.298,
    season_start: null,
    season_end: null,
    event_start: "2026-08-22",
    event_end: "2026-08-22",
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["fireworks", "rinku", "kix_view", "august"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // F. イルミネーション(4 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "osaka-hikari-no-kyoen",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "大阪・光の饗宴(2013 創始・11-1 月・大阪府連動イルミ大祭)",
    title_ja: "大阪・光の饗宴",
    romaji: "Ōsaka Hikari no Kyōen",
    summary_zh:
      "2013 大阪府主催で始めた大阪市内連動イルミネーション大祭。11 月初 - 1 月中旬の 2 ヶ月余で,御堂筋イルミ(キタ - ミナミ 4 km・銀杏並木 760 本ライトアップ)+ OSAKA 光のルネサンス(中之島・12 月 - 1 月)+ 各駅・施設連動装飾。動員 1500 万人余。日本最大規模都市型イルミ。",
    content_md:
      "- 創始:2013\n- 開催:11 月初 - 1 月中旬\n- 範囲:大阪市全域連動\n- 主軸:御堂筋イルミ + OSAKA 光のルネサンス\n- 動員:1500 万人余/年\n- 日本最大都市型イルミ\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.500,
    season_start: "2026-11-03",
    season_end: "2027-01-15",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.hikari-kyoen.com/" },
    tags: ["illumination", "midosuji", "winter", "city_wide"],
    source: "manual",
  },
  {
    slug: "midosuji-illumination",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "御堂筋イルミ(2009 創始・銀杏並木 760 本ライトアップ・4 km)",
    title_ja: "御堂筋イルミネーション",
    romaji: "Midōsuji Illumination",
    summary_zh:
      "2009 創始の御堂筋(梅田 → なんば 4 km)イルミネーション。銀杏並木 760 本に LED 約 100 万球を装着,11 月初 - 1 月中旬 17:00-23:00 ライトアップ。世界最長級イルミネーション(2015 ギネス記録)。色は毎年テーマ変更(青 + 白 + 黄 + ピンク 等)。動員 700 万人。",
    content_md:
      "- 創始:2009\n- 開催:11 月初 - 1 月中旬 17:00-23:00\n- 規模:銀杏並木 760 本・LED 100 万球\n- 距離:4 km(梅田 - なんば)\n- 2015 ギネス記録(世界最長級)\n- 動員:700 万人/年\n- 観覧無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.500,
    season_start: "2026-11-03",
    season_end: "2027-01-15",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["illumination", "midosuji", "ginkgo", "guinness"],
    source: "manual",
  },
  {
    slug: "namba-parks-canyon-illumination",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "なんばパークス キャニオンイルミ(11-2 月・8 階段段イルミ)",
    title_ja: "なんばパークス キャニオンイルミ",
    romaji: "Namba Parks Canyon Illumination",
    summary_zh:
      "なんばパークス(2007 開業の階段状商業施設)の 8 階屋上庭園 + 階段空間にイルミ装着。11 月初 - 2 月中旬 17:00-23:00。階段段毎にテーマ変更 + 動的演出。なんば駅徒歩 3 分・観覧無料・カップル定番。",
    content_md:
      "- 開催:11 月初 - 2 月中旬 17:00-23:00\n- 規模:8 階屋上庭園 + 階段\n- 観覧無料\n- なんば駅徒歩 3 分\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.661,
    lon: 135.502,
    season_start: "2026-11-03",
    season_end: "2027-02-14",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.nambaparks.com/" },
    tags: ["illumination", "namba_parks", "winter", "couple"],
    source: "manual",
  },
  {
    slug: "expo-city-illumination",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "EXPO CITY イルミ(11-2 月・OSAKA WHEEL ライトアップ + 万博公園)",
    title_ja: "EXPO CITY イルミネーション",
    romaji: "EXPO CITY Illumination",
    summary_zh:
      "EXPO CITY(2015 開業)+ 隣接万博記念公園のイルミネーション。OSAKA WHEEL(高 123 m)の LED ライトアップ + 太陽の塔ライトアップ + 自然文化園イルミの三重奏。11 月初 - 2 月中旬 17:00-22:00。家族向け。",
    content_md:
      "- 開催:11 月初 - 2 月中旬 17:00-22:00\n- 三重奏:OSAKA WHEEL + 太陽の塔 + 自然文化園\n- 家族向け\n- 万博公園入園:¥260\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "吹田市",
    lg_code: "27205",
    area_types: ["urban", "suburban"],
    lat: 34.808,
    lon: 135.535,
    season_start: "2026-11-03",
    season_end: "2027-02-14",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["wed"],
    external_urls: {},
    tags: ["illumination", "expo_city", "osaka_wheel", "winter", "family"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // G. 花畑・植物園(3 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "nagai-shokubutsu-en",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "長居植物園(1974 開園・900 種・四季花暦)",
    title_ja: "長居植物園",
    romaji: "Nagai Shokubutsu-en",
    summary_zh:
      "1974 長居公園内に開園,大阪市立自然史博物館と一体運営。24 ha・900 種約 6 万本の植物。春バラ(5 月・600 種 + 1700 株)+ 夏ハス + 秋コスモス(15 万本)+ 紅葉モミジ + 冬牡丹。3-12 月夜間ライトアップ + プロジェクションマッピング『チームラボ ボタニカルガーデン』(通年・¥1800)。",
    content_md:
      "- 開園:1974\n- 立地:長居公園(東住吉区)\n- 面積:24 ha\n- 種数:900 種 6 万本\n- 春バラ:5 月(600 種 1700 株)\n- 秋コスモス:15 万本\n- チームラボ:通年夜間 ¥1800\n- 入園:9:30-17:00 月曜休 ¥200\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban"],
    lat: 34.610,
    lon: 135.522,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["mon"],
    external_urls: { official: "https://botanical-garden.nagai-park.jp/" },
    tags: ["botanical_garden", "nagai", "rose", "cosmos", "teamlab"],
    source: "manual",
  },
  {
    slug: "expo-rose-garden",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "万博公園 平和のバラ園(5800 株・春バラ 5 月・秋バラ 10 月)",
    title_ja: "万博公園 平和のバラ園",
    romaji: "Banpaku Heiwa no Bara-en",
    summary_zh:
      "万博記念公園内 8000 ㎡の大規模バラ園。260 品種 5800 株のバラを植栽。春バラ(5 月中旬 - 6 月初・最盛期 5 月下旬)+ 秋バラ(10 月中旬 - 11 月初)。1970 万博跡地の象徴の一つ『平和のバラ園』。",
    content_md:
      "- 規模:8000 ㎡(260 品種 5800 株)\n- 春バラ:5 月中旬 - 6 月初\n- 秋バラ:10 月中旬 - 11 月初\n- 万博公園内\n- 入園:¥260\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "吹田市",
    lg_code: "27205",
    area_types: ["urban", "suburban"],
    lat: 34.806,
    lon: 135.534,
    season_start: "2026-05-15",
    season_end: "2026-06-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["wed"],
    external_urls: {},
    tags: ["rose_garden", "expo_park", "spring", "autumn"],
    source: "manual",
  },
  {
    slug: "hattori-ryokuchi-park",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "服部緑地(1941 開園・大阪府最大都市公園・日本民家集落博物館)",
    title_ja: "服部緑地",
    romaji: "Hattori Ryokuchi",
    summary_zh:
      "1941 開園の大阪府最大都市公園(126 ha・東京日比谷公園 16 ha の 8 倍)。豊中市内の広大な緑地で,日本民家集落博物館(全国 12 棟の民家移築・1956 開設)+ 都市緑化植物園 + 乗馬センター + テニスコート + 円形花壇 + プール 等多目的施設。豊中市民の憩いの場。",
    content_md:
      "- 開園:1941\n- 面積:126 ha(大阪府最大都市公園)\n- 主要施設:日本民家集落博物館 + 都市緑化植物園 + 乗馬\n- 民家集落博物館:全国 12 棟移築\n- 入園:24h 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "豊中市",
    lg_code: "27203",
    area_types: ["urban", "suburban"],
    lat: 34.778,
    lon: 135.487,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["park", "hattori", "toyonaka", "minka_museum"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // H. プロスポーツ(2 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "kyocera-dome-osaka",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "京セラドーム大阪(1997・オリックスバファローズ本拠地・38000 席)",
    title_ja: "京セラドーム大阪",
    romaji: "Kyocera Dome Ōsaka",
    summary_zh:
      "1997 大阪市西区千代崎に開業の全天候型ドーム球場。プロ野球オリックス・バファローズ(2004 統合・パ・リーグ)本拠地。収容 38000 席。コンサート会場でも頻用(嵐 + EXILE + 米津玄師等)。隣接の京セラドームスポット施設(回転寿司くら寿司本店 等)。",
    content_md:
      "- 開業:1997\n- ホーム:オリックスバファローズ(パ・リーグ)\n- 収容:38000 席\n- 立地:大阪市西区千代崎\n- 主要利用:プロ野球 + コンサート\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.670,
    lon: 135.476,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.kyoceradome-osaka.jp/" },
    tags: ["baseball", "kyocera_dome", "orix_buffaloes", "concert_venue"],
    source: "manual",
  },
  {
    slug: "yanmar-stadium-nagai",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "ヤンマースタジアム長居(1996・セレッソ大阪本拠・47000 席)",
    title_ja: "ヤンマースタジアム長居",
    romaji: "Yanmar Stadium Nagai",
    summary_zh:
      "1996 開業の長居陸上競技場。J リーグ セレッソ大阪本拠地。収容 47000 席で日本最大級陸上競技場。2002 FIFA ワールドカップ会場。隣接のヨドコウ桜スタジアム(2015 改装・25000 席)もセレッソ大阪小規模試合用。長居公園内で植物園 + 自然史博物館も同地区。",
    content_md:
      "- 開業:1996\n- ホーム:セレッソ大阪(J リーグ)\n- 収容:47000 席(日本最大級陸上競技場)\n- 2002 FIFA ワールドカップ会場\n- 隣接:ヨドコウ桜スタジアム(25000 席)\n- 長居公園内\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban"],
    lat: 34.610,
    lon: 135.521,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["soccer", "cerezo_osaka", "j_league", "nagai", "fifa_2002"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // I. 音楽祭(1 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "summer-sonic-osaka",
    category: "entertainment",
    sub_type: "music_festival",
    title_zh: "サマーソニック大阪(2000 創始・8 月舞洲・東京と同時開催)",
    title_ja: "サマーソニック大阪",
    romaji: "Summer Sonic Osaka",
    summary_zh:
      "2000 創始のクリエイティブマン主催の都市型ロックフェス。東京(QVC マリンフィールド)+ 大阪(舞洲)で 8 月中旬土日同時開催し出演者交換構造。大阪会場は舞洲スポーツアイランドで,海上風景 + ライブステージ。動員 6 万人/日。出演:海外メジャー(Foo Fighters / Coldplay / 等) + 国内メジャー。",
    content_md:
      "- 創始:2000\n- 開催:8 月中旬土日(東京・大阪同時)\n- 大阪会場:舞洲スポーツアイランド\n- 動員:6 万人/日\n- 主催:クリエイティブマン\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.667,
    lon: 135.395,
    season_start: null,
    season_end: null,
    event_start: "2026-08-15",
    event_end: "2026-08-16",
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.summersonic.com/" },
    tags: ["music_festival", "summer_sonic", "maishima", "rock"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // J. 大阪夜景(5 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "abeno-harukas-300",
    category: "entertainment",
    sub_type: "osaka_night_view",
    title_zh: "あべのハルカス展望台 300(2014・日本最高層 300 m・360 度大阪一望)",
    title_ja: "あべのハルカス 300",
    romaji: "Abeno Harukas 300",
    summary_zh:
      "2014 開業の高さ 300 m あべのハルカス(日本最高層ビル)の 16-60F 展望スペース。58F-60F の天上回廊 + 屋上ヘリポートが定番。360 度大阪一望で,昼は明石海峡大橋 + 京都方面まで,夜は大阪夜景日本三大級。1 日 4-5 回回数制で混雑少ない。",
    content_md:
      "- 開業:2014\n- 高さ:300 m(日本最高層)\n- 展望:58-60F + 屋上ヘリポート\n- 360 度大阪一望\n- 営業:9:00-22:00 ¥1500\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.646,
    lon: 135.514,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.abenoharukas-300.jp/" },
    tags: ["night_view", "abeno_harukas", "japan_tallest", "tennoji"],
    source: "manual",
  },
  {
    slug: "umeda-sky-building-floating-garden",
    category: "entertainment",
    sub_type: "osaka_night_view",
    title_zh: "梅田スカイビル空中庭園展望台(1993 原広司・173 m・大阪三大夜景)",
    title_ja: "梅田スカイビル 空中庭園展望台",
    romaji: "Umeda Sky Building Kūchū Teien",
    summary_zh:
      "1993 大阪駅西側に開業の梅田スカイビル(設計原広司)40F 空中庭園展望台。2 棟のタワーを上部で連結する独特の空中構造で,40F の屋外展望デッキから 360 度梅田・大阪夜景を一望。大阪三大夜景(ハルカス + 通天閣 + 梅田スカイ)。1990 年代日本の前衛建築の代表。",
    content_md:
      "- 開業:1993\n- 設計:原広司\n- 高さ:173 m(40F 展望)\n- 構造:2 棟連結の空中庭園\n- 大阪三大夜景\n- 営業:9:30-22:30 ¥2000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.706,
    lon: 135.490,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.skybldg.co.jp/" },
    tags: ["night_view", "umeda_sky", "hara_hiroshi", "1993"],
    source: "manual",
  },
  {
    slug: "tsutenkaku-night-view",
    category: "entertainment",
    sub_type: "osaka_night_view",
    title_zh: "通天閣 展望台 + ライトアップ(夜の新世界・ビリケン + 大阪庶民派夜景)",
    title_ja: "通天閣 夜景",
    romaji: "Tsūtenkaku Yakei",
    summary_zh:
      "通天閣展望台(高 91 m)から夜の新世界 + 道頓堀 + ハルカスを見る大阪庶民派夜景の代表。通天閣自体も 1956 二代目開業以来の独特なライトアップで,色変り照明(明日の天気予報 + 季節カラー)が大阪の夜のシンボル。タワー直下の新世界レトロネオン群も合わせ独特の昭和ノスタルジー夜景。",
    content_md:
      "- 高さ:91 m(展望台)\n- 営業:10:00-20:00 ¥1000-1200\n- ライトアップ:色変り(天気 + 季節)\n- 周辺:新世界レトロネオン群\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.652,
    lon: 135.506,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.tsutenkaku.co.jp/" },
    tags: ["night_view", "tsutenkaku", "shinsekai", "showa_neon"],
    source: "manual",
  },
  {
    slug: "dotonbori-glico-night",
    category: "entertainment",
    sub_type: "osaka_night_view",
    title_zh: "道頓堀グリコサイン(1935 初代・現 6 代目 LED・大阪 No.1 SNS スポット)",
    title_ja: "道頓堀グリコサイン",
    romaji: "Dōtonbori Glico Sign",
    summary_zh:
      "1935 江崎グリコ社が道頓堀戎橋に設置した『ランナー』広告ネオン。現在は 6 代目(2014 設置の LED 巨大ディスプレイ・横 33 m × 縦 25 m)で世界最大級ネオン広告。2014 リニューアル後,動画 + 季節装飾で SNS 投稿率 No.1 の大阪夜景代表。戎橋から見上げる構図が定番。",
    content_md:
      "- 初代:1935 江崎グリコ\n- 現 6 代目:2014 LED\n- 規模:横 33 m × 縦 25 m\n- 立地:道頓堀戎橋\n- SNS 投稿率 No.1\n- 観覧無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.668,
    lon: 135.501,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["night_view", "glico", "dotonbori", "instagram_no1"],
    source: "manual",
  },
  {
    slug: "osaka-castle-illumination",
    category: "entertainment",
    sub_type: "osaka_night_view",
    title_zh: "大阪城天守閣 ライトアップ(終夜・四季色変り・天守閣の夜)",
    title_ja: "大阪城 ライトアップ",
    romaji: "Ōsaka-jō Light-up",
    summary_zh:
      "大阪城天守閣(1931 再建)の終夜ライトアップ。日没から 23:00 まで(夏は 24:00 まで)金色 + 白色基調 + 季節色(春桜 + 夏緑 + 秋紅葉 + 冬青)で天守を照射。大阪城公園 24h 開放で,公園内ジョギング + 散歩中に天守閣ライトアップを背景に撮影できる。",
    content_md:
      "- ライトアップ:日没 - 23:00(夏 - 24:00)\n- 色:金白基調 + 季節色\n- 公園:24h 開放\n- 観覧無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.687,
    lon: 135.526,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["night_view", "osaka_castle", "lightup", "free"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // K. 温泉・スパ(2 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "spa-world-shinsekai",
    category: "entertainment",
    sub_type: "osaka_onsen_spa",
    title_zh: "スパワールド(1997・新世界・8 国の風呂 + プール)",
    title_ja: "スパワールド",
    romaji: "Spa World",
    summary_zh:
      "1997 新世界に開業の 8 階建て温泉複合施設。男湯 + 女湯各々 4 国(欧州館 + アジア館)風呂テーマで月毎入替(イタリア・スペイン・トルコ・古代ローマ・日本・中国・バリ・ペルシャ等)。屋上プール『プールゾーン』(夏期)+ 韓国式アカスリ岩盤浴。24 時間営業。新世界アクセス徒歩 5 分。",
    content_md:
      "- 開業:1997\n- 構成:8 階複合施設\n- 8 国の風呂(月入替)\n- 屋上プール:夏期\n- 営業:24 時間\n- 入館:¥1500-2400(時間帯別)\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.652,
    lon: 135.506,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.spaworld.co.jp/" },
    tags: ["spa", "shinsekai", "8_countries", "24h"],
    source: "manual",
  },
  {
    slug: "minoo-onsen-spa-garden",
    category: "entertainment",
    sub_type: "osaka_onsen_spa",
    title_zh: "箕面温泉スパガーデン(1965・天然温泉 + 6 種風呂)",
    title_ja: "箕面温泉スパガーデン",
    romaji: "Minō Onsen Spa Garden",
    summary_zh:
      "1965 阪急阪神ホテルズが箕面公園入口に開業の天然温泉施設。pH 8.5 のアルカリ性単純泉(美肌の湯)+ 6 種風呂(露天 + 内湯 + サウナ等)+ 箕面の山景観。温泉 + ホテル泊 + レストランの一体型。箕面駅から無料送迎バス(15 分間隔)。日帰り入浴 + 1 泊宿泊両対応。",
    content_md:
      "- 開業:1965\n- 泉質:アルカリ性単純泉(pH 8.5)\n- 6 種風呂(露天 + 内湯 + サウナ)\n- ホテル併設\n- 阪急箕面駅から無料送迎\n- 日帰り:¥1500-2500\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "箕面市",
    lg_code: "27220",
    area_types: ["mountain", "rural"],
    lat: 34.831,
    lon: 135.470,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["onsen", "minoo", "alkaline", "hankyu"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // L. 季節食材体験(5 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "kawachi-grape-picking-summer",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "河内ぶどう狩り(8-10 月・柏原 - 羽曳野・関西最大ぶどう産地)",
    title_ja: "河内ぶどう狩り",
    romaji: "Kawachi Budō-gari",
    summary_zh:
      "大阪府は実は全国 5 位のぶどう生産地で,柏原市 + 羽曳野市の 河内地域 が中心。デラウェア + ピオーネ + 巨峰 + シャインマスカット 等。8 月中旬 - 10 月中旬の 2 ヶ月余,30 軒余のぶどう園で食べ放題 ¥1500-3500。柏原デラ (デラウェア・1875 渡来初地)が日本のデラウェア発祥地。",
    content_md:
      "- 期間:8 月中旬 - 10 月中旬\n- 立地:柏原 + 羽曳野(河内地域)\n- 大阪府全国 5 位生産\n- 品種:デラウェア + ピオーネ + 巨峰 + シャイン\n- 食べ放題:¥1500-3500\n- 柏原デラ:1875 日本初\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "柏原市",
    lg_code: "27221",
    area_types: ["rural"],
    lat: 34.583,
    lon: 135.628,
    season_start: "2026-08-15",
    season_end: "2026-10-15",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["fruit_picking", "grape", "kawachi", "kashiwara", "delaware"],
    source: "manual",
  },
  {
    slug: "kishiwada-strawberry-picking-spring",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "南河内 いちご狩り(1-5 月・羽曳野 - 富田林・あまおう + 章姫)",
    title_ja: "南河内 いちご狩り",
    romaji: "Minami-Kawachi Ichigo-gari",
    summary_zh:
      "南河内地域(羽曳野 + 富田林 + 河内長野 + 太子町)のいちご狩り。1 月中旬 - 5 月初の 4 ヶ月。あまおう + 章姫 + 紅ほっぺ 等。20 軒余のいちご園で 30 分食べ放題 ¥1500-2500。土壌改良のハウス栽培 + 高設栽培で立ったまま摘める作業性。家族 + カップル人気。",
    content_md:
      "- 期間:1 月中旬 - 5 月初\n- 立地:南河内(羽曳野 + 富田林 + 河内長野 + 太子)\n- 品種:あまおう + 章姫 + 紅ほっぺ\n- 食べ放題:¥1500-2500(30 分)\n- 高設栽培で立ち作業\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "羽曳野市",
    lg_code: "27222",
    area_types: ["rural"],
    lat: 34.554,
    lon: 135.605,
    season_start: "2026-01-15",
    season_end: "2026-05-05",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["fruit_picking", "strawberry", "minami_kawachi", "habikino"],
    source: "manual",
  },
  {
    slug: "fugu-winter-osaka-experience",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "冬のふぐ料理体験(11-3 月・大阪は全国第一消費地・てっさてっちり)",
    title_ja: "ふぐ料理シーズン",
    romaji: "Fugu Ryōri Season",
    summary_zh:
      "大阪は全国ふぐ消費量第一(全国 60% 超)で,11 月初 - 3 月末がシーズン。てっさ(刺身)+ てっちり(鍋)+ 唐揚 + 雑炊の 4 品コースが定番,コース ¥6000-25000。新世界『づぼらや』(2020 閉店)+ 道頓堀『づぼらや道頓堀』伝統。専門店 100 軒余。冬限定の旅行体験。",
    content_md:
      "- 期間:11 月初 - 3 月末\n- 大阪府:全国ふぐ消費 60%+\n- 4 品コース:てっさ + てっちり + 唐揚 + 雑炊\n- 価格:¥6000-25000\n- 専門店:100 軒余\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.668,
    lon: 135.501,
    season_start: "2026-11-01",
    season_end: "2027-03-31",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_food", "fugu", "winter", "tessa", "tetchiri"],
    source: "manual",
  },
  {
    slug: "izumi-mizunashi-takenoko-spring",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "和泉 水なす + たけのこ(4-5 月・泉州春の代表食材)",
    title_ja: "和泉 水なす + たけのこ",
    romaji: "Izumi Mizunasu + Takenoko",
    summary_zh:
      "和泉市 + 泉佐野 + 貝塚 等泉州地域の春食材体験。水なす(なすの一種・生食可・甘み強い・大阪府指定品)+ 春たけのこ。4-5 月限定で漬物 + 田舎料理として地元道の駅 + 直売所で購入。水なす漬は泉州土産定番。",
    content_md:
      "- 期間:4-5 月\n- 立地:泉州地域(和泉 + 泉佐野 + 貝塚)\n- 水なす:生食可・甘み強(大阪府指定)\n- 春たけのこ\n- 道の駅 + 直売所購入\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "和泉市",
    lg_code: "27219",
    area_types: ["rural"],
    lat: 34.488,
    lon: 135.443,
    season_start: "2026-04-01",
    season_end: "2026-05-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_food", "mizunasu", "takenoko", "izumi", "spring"],
    source: "manual",
  },
  {
    slug: "kishiwada-orange-picking-winter",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "和泉・岸和田 みかん狩り(11-12 月・温州みかん・大阪府最大産地)",
    title_ja: "みかん狩り",
    romaji: "Mikan-gari",
    summary_zh:
      "和泉市・岸和田市の山間部(温州みかん主要栽培地)で 11 月初 - 12 月末のみかん狩り。20 軒余のみかん園で 食べ放題 ¥1000-1500 + 持帰り ¥500/kg 程度。家族 + カップル向けの秋冬体験。",
    content_md:
      "- 期間:11 月初 - 12 月末\n- 立地:和泉市・岸和田市山間部\n- 品種:温州みかん\n- 食べ放題:¥1000-1500\n- 持帰り:¥500/kg\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "岸和田市",
    lg_code: "27202",
    area_types: ["rural"],
    lat: 34.444,
    lon: 135.434,
    season_start: "2026-11-01",
    season_end: "2026-12-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["fruit_picking", "mikan", "kishiwada", "izumi", "autumn"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // R2 expansion(2026-04-29・49 → ~74)
  // ══════════════════════════════════════════════════════════════════

  // ── R2-A. USJ 季節イベント(3 筆) ──────────────────
  {
    slug: "usj-halloween-horror-night",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "USJ ハロウィン・ホラー・ナイト(2002 創始・9-11 月・ゾンビ街)",
    title_ja: "ユニバーサル・サプライズ・ハロウィーン",
    romaji: "USJ Halloween Horror Night",
    summary_zh:
      "2002 USJ 開業 2 年目から始まったハロウィン期間限定イベント。9 月初 - 11 月初の 2 ヶ月余開催で,日没後 18:00-22:00 にパーク内をゾンビ + 殺人鬼が徘徊する『ストリート・ゾンビ』+ 各種ホラーアトラクション。日本のテーマパークで最古かつ最大規模のハロウィンイベント。期間中の入場者は通常期の 1.5 倍。",
    content_md:
      "- 創始:2002\n- 期間:9 月初 - 11 月初\n- 夜間:18:00-22:00 ゾンビ徘徊\n- 名物:ストリート・ゾンビ + ホラーアトラクション\n- 期間中入場:通常 1.5 倍\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.665,
    lon: 135.432,
    season_start: "2026-09-01",
    season_end: "2026-11-04",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.usj.co.jp/web/ja/jp/halloween" },
    tags: ["theme_park", "usj", "halloween", "zombie", "since_2002"],
    source: "manual",
  },
  {
    slug: "usj-christmas-season",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "USJ クリスマス(11-1 月・世界一の天使ツリー・スノーパレード)",
    title_ja: "ユニバーサル・ワンダー・クリスマス",
    romaji: "USJ Wonder Christmas",
    summary_zh:
      "11 月中旬 - 1 月中旬の 2 ヶ月余開催される USJ クリスマスイベント。中央セントラル広場の高 36 m の世界最大級ツリー(2018-19 ギネス世界記録『最も電飾の多い人工クリスマスツリー』58 万球以上)+ ツリー前の天使コーラスショー + クリスマスパレード。家族 + カップル定番。",
    content_md:
      "- 期間:11 月中旬 - 1 月中旬\n- 中央ツリー:高 36 m・LED 58 万球(2018-19 ギネス記録)\n- イベント:天使コーラス + パレード\n- 家族 + カップル定番\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.665,
    lon: 135.432,
    season_start: "2026-11-15",
    season_end: "2027-01-15",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.usj.co.jp/web/ja/jp/christmas" },
    tags: ["theme_park", "usj", "christmas", "winter", "guinness_tree"],
    source: "manual",
  },
  {
    slug: "usj-cool-japan-season",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "USJ クールジャパン(2015 創始・1-7 月・コラボ期間限定アトラクション)",
    title_ja: "ユニバーサル・クールジャパン",
    romaji: "USJ Cool Japan",
    summary_zh:
      "2015 年から始まった USJ の春-夏期間限定 IP コラボイベント。鬼滅の刃 + チェンソーマン + 呪術廻戦 + モンスターハンター + 名探偵コナン 等の人気アニメ・ゲーム系 IP と USJ がコラボした XR ライド + フォトスポット + コラボフード等を 1-7 月期間限定で展開。日本コンテンツファンの巡礼地。",
    content_md:
      "- 創始:2015\n- 期間:1 月中旬 - 7 月初\n- 主要 IP:鬼滅 + 呪術廻戦 + チェンソーマン + モンハン + コナン\n- 形式:XR ライド + フォト + コラボフード\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.665,
    lon: 135.432,
    season_start: "2026-01-15",
    season_end: "2026-07-04",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.usj.co.jp/web/ja/jp/cool-japan" },
    tags: ["theme_park", "usj", "cool_japan", "anime_collab", "since_2015"],
    source: "manual",
  },

  // ── R2-B. ユニバーサルシティウォーク(1 筆) ──────────────────
  {
    slug: "universal-citywalk-osaka",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ユニバーサル・シティウォーク大阪(2001・USJ 隣接モール)",
    title_ja: "ユニバーサル・シティウォーク大阪",
    romaji: "Universal CityWalk Osaka",
    summary_zh:
      "2001 USJ 開業時に同時開業した USJ 隣接の屋外型商業モール。USJ 入場前後の食事 + 買物 + ホテルチェックインのハブで,ハードロックカフェ + たこ焼ミュージアム + 人形劇場 + キャラクターグッズ専門店 + USJ オフィシャルホテル群連結。USJ チケット不要で利用可能・観光客の食事スポットとして人気。",
    content_md:
      "- 開業:2001(USJ 同時)\n- 立地:USJ 入場ゲート前\n- 主要店舗:ハードロック + たこ焼ミュージアム + USJ グッズ\n- 入場:無料(USJ チケット不要)\n- 営業:11:00-22:00(店舗別)\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.667,
    lon: 135.434,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["mall", "usj", "citywalk", "free_entry"],
    source: "manual",
  },

  // ── R2-C. 桜・紅葉補完(4 筆) ──────────────────
  {
    slug: "daisen-koen-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "大仙公園 桜(堺・仁徳天皇陵隣接・1000 本)",
    title_ja: "大仙公園 桜",
    romaji: "Daisen Kōen Sakura",
    summary_zh:
      "1989 開園の堺市最大都市公園(38 ha・仁徳天皇陵に隣接)。1000 本のソメイヨシノが 3 月末 - 4 月初開花。日本庭園 + 堺市博物館 + 中央図書館を内包する文化軸。世界遺産仁徳天皇陵を背景にした桜風景が観光客 No.1 構図。屋台少なめで落ち着き花見。",
    content_md:
      "- 開園:1989\n- 規模:1000 本\n- 開花:3 月末 - 4 月初\n- 仁徳天皇陵隣接(世界遺産)\n- 日本庭園 + 博物館併設\n- 入園:24h 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "堺市",
    lg_code: "27140",
    area_types: ["urban"],
    lat: 34.564,
    lon: 135.488,
    season_start: "2026-03-25",
    season_end: "2026-04-10",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "daisen", "sakai", "world_heritage_view"],
    source: "manual",
  },
  {
    slug: "ibaraki-motoibaraki-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "元茨木川緑地 桜(2.5 km 桜並木・茨木市民の聖地)",
    title_ja: "元茨木川緑地 桜",
    romaji: "Moto-Ibarakigawa Ryokuchi Sakura",
    summary_zh:
      "1968 旧茨木川廃川後に整備された 2.5 km の細長い緑地公園。500 本のソメイヨシノが川跡に沿って咲く茨木市民の桜聖地。3 月末 - 4 月初開花。地元向けの落ち着き花見スポットで観光客少なめ・ローカル感濃厚。",
    content_md:
      "- 整備:1968(旧茨木川廃川後)\n- 規模:500 本\n- 距離:2.5 km(川跡沿)\n- 開花:3 月末 - 4 月初\n- 地元向け落ち着き花見\n- 入園:24h 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "茨木市",
    lg_code: "27211",
    area_types: ["urban"],
    lat: 34.815,
    lon: 135.566,
    season_start: "2026-03-25",
    season_end: "2026-04-10",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "ibaraki", "river_side", "local"],
    source: "manual",
  },
  {
    slug: "ikeda-jo-koen-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "池田城跡公園 桜(室町期山城跡・150 本)",
    title_ja: "池田城跡公園 桜",
    romaji: "Ikeda-jō Kōen Sakura",
    summary_zh:
      "室町期池田氏居城跡(現城跡公園)の桜 150 本。3 月末 - 4 月初開花。模擬櫓 + 茶室 + 復元枯山水 + 桜のコラボが歴史と春の融合。阪急池田駅徒歩 15 分のアクセス。地元客中心の落ち着き花見。",
    content_md:
      "- 規模:150 本\n- 開花:3 月末 - 4 月初\n- 室町期池田氏居城跡\n- 模擬櫓 + 茶室\n- アクセス:阪急池田駅徒歩 15 分\n- 入園:9:00-19:00 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "池田市",
    lg_code: "27204",
    area_types: ["urban"],
    lat: 34.823,
    lon: 135.430,
    season_start: "2026-03-25",
    season_end: "2026-04-10",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: ["tue"],
    external_urls: {},
    tags: ["sakura", "ikeda", "castle_ruins", "local"],
    source: "manual",
  },
  {
    slug: "expo-koen-koyo",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "万博公園 紅葉(自然文化園 1 万本余・11 月下旬)",
    title_ja: "万博公園 紅葉",
    romaji: "Banpaku Kōen Kōyō",
    summary_zh:
      "万博記念公園内 自然文化園エリアの紅葉。モミジ + イチョウ + ポプラ等 1 万本余が 11 月中旬 - 12 月初紅葉。最盛期は 11 月下旬。日本庭園(枯山水 + 紅葉)+ 太陽の塔バックドロップ + 大芝生広場の構図。京都 嵐山の混雑を避ける関西紅葉穴場。",
    content_md:
      "- 規模:1 万本余(モミジ + イチョウ + ポプラ)\n- 開葉:11 月中旬 - 12 月初\n- 最盛期:11 月下旬\n- 日本庭園 + 太陽の塔背景\n- 京都嵐山の混雑回避穴場\n- 入園:¥260\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "吹田市",
    lg_code: "27205",
    area_types: ["urban", "suburban"],
    lat: 34.808,
    lon: 135.535,
    season_start: "2026-11-15",
    season_end: "2026-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["wed"],
    external_urls: {},
    tags: ["momiji", "expo_park", "japanese_garden", "kyoto_alternative"],
    source: "manual",
  },

  // ── R2-D. 花畑追加(3 筆) ──────────────────
  {
    slug: "maishima-seaside-park-nemophila",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "大阪まいしまシーサイドパーク(ネモフィラ 100 万本 + ひまわり 50 万本)",
    title_ja: "大阪まいしまシーサイドパーク",
    romaji: "Ōsaka Maishima Seaside Park",
    summary_zh:
      "2019 開園の此花区舞洲(大阪湾埋立地)花畑公園。春(4-5 月)ネモフィラ 100 万本(青空と海と花の三重奏)+ 夏(7-8 月)ひまわり 50 万本(関西最大級)が見頃。海風と海景観の中での花畑が SNS で大人気。USJ 隣接舞洲で,USJ + シーサイドパークの 1 日コース可。",
    content_md:
      "- 開園:2019\n- 立地:此花区舞洲(大阪湾)\n- 春:ネモフィラ 100 万本(4-5 月)\n- 夏:ひまわり 50 万本(7-8 月)\n- 海風 + 海景観の三重奏\n- 入園:¥1300\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.665,
    lon: 135.402,
    season_start: "2026-04-01",
    season_end: "2026-05-15",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://seasidepark.maishima.com/" },
    tags: ["flower_field", "nemophila", "sunflower", "maishima", "instagram"],
    source: "manual",
  },
  {
    slug: "eiraku-dam-ajisai",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "永楽ダム アジサイ(茨木 北部・2 万株・6 月)",
    title_ja: "永楽ダム アジサイ",
    romaji: "Eiraku Dam Ajisai",
    summary_zh:
      "茨木市北部山中の永楽ダム湖畔遊歩道沿に植栽された 2 万株のアジサイ。6 月中旬 - 7 月初開花,梅雨時期の関西アジサイ名所。湖畔 + アジサイ + 山林の三重奏で京都三室戸寺の混雑を避ける穴場。アクセス困難(車推奨・JR 茨木駅からバス 30 分)。",
    content_md:
      "- 規模:2 万株\n- 開花:6 月中旬 - 7 月初\n- 立地:永楽ダム湖畔\n- 茨木市北部山中\n- アクセス:車推奨(駅からバス 30 分)\n- 入園:24h 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "茨木市",
    lg_code: "27211",
    area_types: ["mountain", "rural"],
    lat: 34.873,
    lon: 135.612,
    season_start: "2026-06-15",
    season_end: "2026-07-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["flower_field", "ajisai", "rainy_season", "ibaraki", "rural"],
    source: "manual",
  },
  {
    slug: "tsurumi-ryokuchi-flower",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "鶴見緑地(1990 国際花博跡地・風車前花壇 + 咲くやこの花館)",
    title_ja: "鶴見緑地",
    romaji: "Tsurumi Ryokuchi",
    summary_zh:
      "1990 国際花と緑の博覧会(EXPO'90)跡地の都市公園(126 ha)。象徴オランダ風車前の花壇は四季花替り(春チューリップ + 夏ひまわり + 秋コスモス + 冬パンジー)で SNS フォトスポット。咲くやこの花館(温室・植物園・1990 開館)+ プール + ジョギングコース併設。",
    content_md:
      "- 開園:1972 / 国際花博 1990\n- 面積:126 ha\n- 象徴:オランダ風車 + 季節花壇\n- 咲くやこの花館(温室)\n- 入園:24h 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban"],
    lat: 34.713,
    lon: 135.555,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.tsurumi-ryokuchi.jp/" },
    tags: ["park", "tsurumi", "expo_1990", "windmill", "flower_garden"],
    source: "manual",
  },

  // ── R2-E. 夜景・展望追加(2 筆) ──────────────────
  {
    slug: "cosmo-tower-saka",
    category: "entertainment",
    sub_type: "osaka_night_view",
    title_zh: "大阪府咲洲庁舎展望台(COSMO TOWER・1995・55F・252 m)",
    title_ja: "大阪府咲洲庁舎展望台",
    romaji: "Ōsaka-fu Sakishima Chōsha Tenbōdai",
    summary_zh:
      "1995 大阪市住之江区咲洲(大阪湾埋立地)に開業の 55 階建超高層ビル(高 256 m)。1995-2014 大阪府庁舎,2010 移転後展望台施設化。55F 展望ロビー(高 252 m)が屋外 200 度ガラス張で大阪湾 + USJ + 夢洲 + 神戸方面一望。価格安(¥1000)で穴場の夜景スポット。",
    content_md:
      "- 開業:1995(大阪府庁舎)\n- 高さ:256 m(55F 展望 252 m)\n- 展望:屋外 200 度ガラス張\n- 一望:大阪湾 + USJ + 夢洲 + 神戸\n- 営業:11:00-22:00 ¥1000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.629,
    lon: 135.418,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["mon"],
    external_urls: { official: "https://sakishima-observatory.com/" },
    tags: ["night_view", "cosmo_tower", "sakishima", "bay_view", "since_1995"],
    source: "manual",
  },
  {
    slug: "tempozan-ferris-wheel",
    category: "entertainment",
    sub_type: "osaka_night_view",
    title_zh: "天保山大観覧車(1997・高 112.5 m・海遊館隣接・カラー LED)",
    title_ja: "天保山大観覧車",
    romaji: "Tempōzan Daikanransha",
    summary_zh:
      "1997 天保山ハーバービレッジ(海遊館隣接)に設置された大型観覧車。高 112.5 m・直径 100 m で開業当時世界最大,現在も日本最大級。60 ゴンドラ・1 周 15 分。LED フルカラー照明で夜は色変り装飾(明日の天気予報 + 季節カラー)。海遊館 + 天保山 + 大阪湾の景観を一望。",
    content_md:
      "- 開業:1997\n- 高さ:112.5 m(直径 100 m)\n- 開業時世界最大\n- ゴンドラ:60 機(1 周 15 分)\n- LED 色変り(天気 + 季節)\n- 営業:10:00-22:00 ¥900\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.654,
    lon: 135.428,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://tempozan-kanransya.com/" },
    tags: ["ferris_wheel", "tempozan", "since_1997", "kaiyukan_adj", "led"],
    source: "manual",
  },

  // ── R2-F. 温泉・スパ追加(2 筆) ──────────────────
  {
    slug: "naniwa-kenkou-land",
    category: "entertainment",
    sub_type: "osaka_onsen_spa",
    title_zh: "なにわ健康ランド(1990・東大阪・大阪型健康ランド・24 時間)",
    title_ja: "なにわ健康ランド",
    romaji: "Naniwa Kenkō Land",
    summary_zh:
      "1990 東大阪市菱屋西に開業の関西型健康ランド施設。天然温泉 + 漢方湯 + 露天 + サウナ + 岩盤浴 + リラクゼーション + 仮眠室 + レストランの 24 時間総合施設。地元 + 出張サラリーマンに人気で,『なにわ健康ランド』の関西弁テレビ CM(1990s)で知名。",
    content_md:
      "- 開業:1990\n- 立地:東大阪市菱屋西\n- 構成:天然温泉 + 漢方湯 + 露天 + サウナ + 岩盤浴\n- 営業:24 時間\n- 入館:¥1700-2900(時間帯別)\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "東大阪市",
    lg_code: "27227",
    area_types: ["urban"],
    lat: 34.673,
    lon: 135.563,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["onsen", "kenkou_land", "24h", "higashi_osaka"],
    source: "manual",
  },
  {
    slug: "amano-yu-onsen-kawachinagano",
    category: "entertainment",
    sub_type: "osaka_onsen_spa",
    title_zh: "上方温泉一休(2002・河内長野・天然温泉・露天 17 種)",
    title_ja: "上方温泉一休",
    romaji: "Kamigata Onsen Ikkyū",
    summary_zh:
      "2002 河内長野市天野山の天然温泉施設。源泉 30°C・pH 7.5 のナトリウム泉。露天 17 種(打たせ湯 + ジェット + 源泉風呂 等)+ 内湯 5 種 + サウナ 3 種。観心寺 + 金剛寺の山中ロケーションで京都嵐山の混雑を避ける穴場温泉。日帰りのみ。",
    content_md:
      "- 開業:2002\n- 立地:河内長野市天野山\n- 泉質:ナトリウム泉(pH 7.5)\n- 露天 17 種 + 内湯 5 種 + サウナ 3 種\n- 観心寺 + 金剛寺アクセス\n- 入館:¥800-1500\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "河内長野市",
    lg_code: "27216",
    area_types: ["mountain", "rural"],
    lat: 34.398,
    lon: 135.575,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["onsen", "kawachinagano", "amanosan", "rural"],
    source: "manual",
  },

  // ── R2-G. プロサッカー(1 筆) ──────────────────
  {
    slug: "panasonic-stadium-suita",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "パナソニックスタジアム吹田(2015・ガンバ大阪本拠・40000 席)",
    title_ja: "パナソニックスタジアム吹田",
    romaji: "Panasonic Stadium Suita",
    summary_zh:
      "2015 万博記念公園内に開業の J リーグ専用スタジアム。ガンバ大阪本拠地で 40000 席。パナソニック創業者松下幸之助とゆかりの地(パナソニックは大阪府門真市拠点)で命名権。世界最高水準のサッカー専用スタジアムとされ,屋根 + ピッチ間距離が短く臨場感最高。",
    content_md:
      "- 開業:2015\n- 立地:万博記念公園内\n- ホーム:ガンバ大阪(J1)\n- 収容:40000 席\n- サッカー専用設計\n- 屋根 + 短距離ピッチ\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "吹田市",
    lg_code: "27205",
    area_types: ["urban", "suburban"],
    lat: 34.804,
    lon: 135.539,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["soccer", "gamba_osaka", "j_league", "suita", "since_2015"],
    source: "manual",
  },

  // ── R2-H. キッズ・体験施設(1 筆) ──────────────────
  {
    slug: "kids-plaza-osaka",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "キッズプラザ大阪(1997・扇町・日本初の体験型こども博物館)",
    title_ja: "キッズプラザ大阪",
    romaji: "Kids Plaza Ōsaka",
    summary_zh:
      "1997 北区扇町に開業した日本初の本格的体験型こども博物館。大阪市が NHK 大阪放送局と共同建設した 5 階建て体験施設で,科学 + 文化 + 国際 + 創作 + メディアの体験ゾーン。子供向け 0-12 歳メイン。NHK 大阪放送局 BK プラザ + キッズプラザ + 扇町公園の 1 日コース。",
    content_md:
      "- 開業:1997\n- 立地:北区扇町\n- 日本初の体験型こども博物館\n- 5 階建・全 6 ゾーン体験施設\n- 対象:0-12 歳\n- 営業:9:30-17:00 月曜休 ¥1400\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.704,
    lon: 135.514,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["mon"],
    external_urls: { official: "https://www.kidsplaza.or.jp/" },
    tags: ["kids", "interactive", "ogimachi", "since_1997", "japan_first"],
    source: "manual",
  },

  // ── R2-I. イルミ追加(2 筆) ──────────────────
  {
    slug: "hirakata-park-illumination",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "ひらかたパーク・ヒラパー光の遊園地(11-2 月・遊園地全体イルミ)",
    title_ja: "ヒラパー光の遊園地",
    romaji: "Hirapa Hikari no Yūenchi",
    summary_zh:
      "ひらかたパーク(関西最古遊園地・1912)の冬期イルミイベント『光の遊園地』。11 月初 - 2 月末の 4 ヶ月間,遊園地全体に LED 装着 + 観覧車スカイウォーカー(高 80 m)カラーライトアップ + アトラクション夜間運行。家族 + カップル定番,平日空き気味で穴場。",
    content_md:
      "- 期間:11 月初 - 2 月末\n- 観覧車:スカイウォーカー(80 m)カラー LED\n- 営業:17:00-21:00\n- 入園:¥1800\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "枚方市",
    lg_code: "27210",
    area_types: ["urban"],
    lat: 34.815,
    lon: 135.654,
    season_start: "2026-11-03",
    season_end: "2027-02-28",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.hirakatapark.co.jp/" },
    tags: ["illumination", "hirapa", "winter", "ferris_wheel"],
    source: "manual",
  },
  {
    slug: "kishiwada-castle-illumi",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "岸和田城ライトアップ(8 月だんじり期間・LED 演色)",
    title_ja: "岸和田城ライトアップ",
    romaji: "Kishiwada-jō Light-up",
    summary_zh:
      "岸和田城(1334 楠木・1597 小出秀政)の通年夜間ライトアップ + 8 月だんじり試験曳期間中の LED 演色。城 + 八陣の庭(重森三玲・名勝)+ 桜並木のコラボがインスタ人気。8 月だんじり期間中は赤系 + 9 月本祭は青系 + 紅葉期はオレンジ系で色変り。岸和田駅徒歩 7 分。",
    content_md:
      "- ライトアップ:通年 17:00-22:00\n- 8 月だんじり期間 + 9 月本祭で LED 色変り\n- 八陣の庭(重森三玲・名勝)\n- 観覧無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "岸和田市",
    lg_code: "27202",
    area_types: ["urban"],
    lat: 34.461,
    lon: 135.371,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["illumination", "kishiwada_castle", "danjiri_season", "led"],
    source: "manual",
  },

  // ── R2-J. 季節食材追加(3 筆) ──────────────────
  {
    slug: "senshu-tamanegi-spring",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "泉州玉ねぎ(4-6 月・大阪府特産・甘み No.1 早生玉ねぎ)",
    title_ja: "泉州玉ねぎ",
    romaji: "Senshū Tamanegi",
    summary_zh:
      "泉州地域(泉佐野 + 貝塚 + 岸和田 + 阪南 等)の早生玉ねぎ。江戸期 1600s 頃から栽培,1885 関西最初の輸出玉ねぎ産地として全国に。生食可の甘み + 軟らかさで全国ブランド化。4 月中旬 - 6 月中旬収穫期に直売所 + 道の駅で販売。塩茹で + サラダ生食 + 玉ねぎチップス 等。",
    content_md:
      "- 期間:4 月中旬 - 6 月中旬\n- 立地:泉州地域(泉佐野 + 貝塚 + 岸和田 + 阪南)\n- 起源:江戸期 1600s\n- 1885 関西初の輸出玉ねぎ\n- 特徴:生食可の甘み + 軟らかさ\n- 道の駅・直売所\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "泉佐野市",
    lg_code: "27213",
    area_types: ["rural"],
    lat: 34.405,
    lon: 135.319,
    season_start: "2026-04-15",
    season_end: "2026-06-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_food", "tamanegi", "senshu", "spring", "specialty"],
    source: "manual",
  },
  {
    slug: "kawachi-momo-summer",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "河内桃(7-8 月・羽曳野 + 太子町・関西高級桃産地)",
    title_ja: "河内桃",
    romaji: "Kawachi Momo",
    summary_zh:
      "羽曳野市 + 太子町(南河内地域)の桃。古市古墳群(世界遺産)の表土が桃栽培に最適とされ,江戸後期から栽培。白桃 + 黄桃 + 千疋桃 等。7 月初 - 8 月末収穫期に直売所 + 桃狩り。岡山桃に匹敵する関西高級桃ブランド。羽曳野道の駅 + 太子町道の駅で販売。",
    content_md:
      "- 期間:7 月初 - 8 月末\n- 立地:南河内(羽曳野 + 太子町)\n- 起源:江戸後期\n- 品種:白桃 + 黄桃 + 千疋桃\n- 道の駅 + 直売所 + 桃狩り\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "羽曳野市",
    lg_code: "27222",
    area_types: ["rural"],
    lat: 34.554,
    lon: 135.605,
    season_start: "2026-07-01",
    season_end: "2026-08-31",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_food", "momo", "kawachi", "summer", "specialty"],
    source: "manual",
  },
  {
    slug: "tondabayashi-eggplant-summer",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "富田林 海老芋 + なす(7-10 月・南河内伝統野菜・大阪府指定)",
    title_ja: "富田林 海老芋・なす",
    romaji: "Tondabayashi Ebi-imo + Nasu",
    summary_zh:
      "富田林市 + 河内長野市の南河内伝統野菜。海老芋(エビ型に湾曲する里芋・通称タロイモ)+ なす(伝統品種『田辺大根』)が大阪府『なにわの伝統野菜』指定。7 月 - 10 月収穫期に道の駅 + 直売所で販売。煮物 + 田楽 + 漬物 等の郷土料理に使用。",
    content_md:
      "- 期間:7 月 - 10 月\n- 立地:南河内(富田林 + 河内長野)\n- 大阪府『なにわの伝統野菜』指定\n- 海老芋:エビ型湾曲里芋\n- 田辺大根伝統品種\n- 道の駅 + 直売所\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "富田林市",
    lg_code: "27214",
    area_types: ["rural"],
    lat: 34.503,
    lon: 135.591,
    season_start: "2026-07-01",
    season_end: "2026-10-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_food", "ebi_imo", "nasu", "tondabayashi", "naniwa_traditional"],
    source: "manual",
  },

  // ── R2-K. 阪堺電車レトロ(1 筆) ──────────────────
  {
    slug: "hankai-trolley-retro-tour",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "阪堺電車レトロ車両(1928 製チンチン電車・住吉 → 浜寺)",
    title_ja: "阪堺電車レトロ車両",
    romaji: "Hankai Densha Retro Sharyō",
    summary_zh:
      "阪堺電車(大阪市内 → 堺の路面電車)に保存運行されるレトロ車両『161 形』(1928 製)+『166 形』。チンチン電車の異名で大阪 → 堺の旧街道沿に古風な街並を抜ける体験。1 日乗車券 ¥600 で全線乗放題,住吉大社 → 浜寺公園 9 km 60 分。SNS で外国人観光客人気。",
    content_md:
      "- レトロ車両:161 形(1928 製)+ 166 形\n- 区間:住吉 → 堺 → 浜寺(全線 14 km)\n- 1 日乗車券:¥600\n- 観覧:住吉大社 + 浜寺公園\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban"],
    lat: 34.612,
    lon: 135.493,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.hankai.co.jp/" },
    tags: ["tram", "retro", "hankai", "sumiyoshi", "since_1928"],
    source: "manual",
  },

  // ── R2-L. 万博 2025 跡地(1 筆) ──────────────────
  {
    slug: "expo2025-yumeshima-legacy",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "夢洲 EXPO 2025 跡地(2025/4-10 開催・大阪・関西万博・将来 IR 化)",
    title_ja: "夢洲 EXPO 2025 跡地",
    romaji: "Yumeshima EXPO 2025 Ato",
    summary_zh:
      "2025/4/13-10/13 開催の大阪・関西万博(EXPO 2025・160 ヶ国参加・動員 2820 万人)跡地。此花区夢洲の人工島 155 ha・象徴の大屋根リング(直径 615 m × 高 12 m・世界最大級木造建築)。万博終了後の現在(2026)は段階的解体 + 一部保存中。2030 IR(統合型リゾート・カジノ含)開業予定。期間限定で跡地ガイドツアー実施(要予約)。",
    content_md:
      "- 万博開催:2025/4/13-10/13\n- 動員:2820 万人(160 ヶ国参加)\n- 立地:此花区夢洲(155 ha)\n- 大屋根リング:直径 615 m × 高 12 m(世界最大級木造)\n- 現状(2026):段階的解体 + 一部保存\n- 将来:2030 IR 開業予定\n- 跡地ツアー:要予約\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.640,
    lon: 135.388,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["expo_2025", "yumeshima", "wood_ring", "IR_future"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // R3 expansion(2026-04-29・73 → ~92)
  // ══════════════════════════════════════════════════════════════════

  // ── R3-A. テーマパーク + キッズ(3 筆) ──────────────────
  {
    slug: "lego-discovery-center-osaka",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "レゴランド・ディスカバリー・センター大阪(2015・天保山・屋内型 LEGO)",
    title_ja: "レゴランド・ディスカバリー・センター大阪",
    romaji: "Legoland Discovery Center Ōsaka",
    summary_zh:
      "2015 天保山ハーバービレッジ内に開業の屋内型 LEGO テーマパーク。3-10 歳家族向けで,LEGO 造型展示 + ライド + 4D シアター + プレイゾーン。海遊館 + 天保山観覧車徒歩圏で,ベイエリア家族 1 日コースの一部。",
    content_md:
      "- 開業:2015\n- 立地:天保山ハーバービレッジ内\n- 対象:3-10 歳家族向け\n- 入場:¥2800-3500\n- 営業:10:00-18:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.654,
    lon: 135.428,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://www.legolanddiscoverycenter.jp/osaka/" },
    tags: ["theme_park", "lego", "tempozan", "since_2015", "kids"],
    source: "manual",
  },
  {
    slug: "bornelund-asobi-tsurumi",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "ボーネルンドあそびのせかい(鶴見緑地・北欧玩具体験施設)",
    title_ja: "ボーネルンドあそびのせかい 鶴見緑地店",
    romaji: "Bornelund Asobi no Sekai",
    summary_zh:
      "鶴見緑地内の北欧系玩具体験施設『ボーネルンド』。1-12 歳家族向けで,北欧の知育玩具 + ボールプール + 砂遊び + 木製玩具体験。週末 + 雨天時の家族 indoor 遊び場として人気。1 日 ¥1500/家族。",
    content_md:
      "- 立地:鶴見緑地内\n- 対象:1-12 歳家族向け\n- 北欧系知育玩具\n- 1 日:¥1500/家族\n- 営業:10:00-19:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban"],
    lat: 34.713,
    lon: 135.555,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kids", "bornelund", "tsurumi", "scandinavian_toys"],
    source: "manual",
  },
  {
    slug: "nhk-osaka-bk-plaza",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "NHK 大阪 BK プラザ(大阪歴博 1F・無料体験 + 番組制作見学)",
    title_ja: "NHK 大阪 BK プラザ",
    romaji: "NHK Ōsaka BK Plaza",
    summary_zh:
      "NHK 大阪放送局(2001 開局)1 F の無料体験スタジオ。番組制作見学 + クロマキー合成体験 + キャスター体験 + ニュースキャスター席座り体験 等。大阪歴史博物館 1F に併設,難波宮跡 + 大阪城公園アクセスと組合せ可能。家族 + 学校団体定番。",
    content_md:
      "- 立地:NHK 大阪放送局 1F(大阪歴博併設)\n- 体験:番組制作 + クロマキー + キャスター席\n- 入場:無料\n- 営業:10:00-18:00 火曜休\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.521,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: ["tue"],
    external_urls: { official: "https://www.nhk.or.jp/osaka/bkplaza/" },
    tags: ["kids", "nhk", "bk_plaza", "free", "tv_studio"],
    source: "manual",
  },

  // ── R3-B. USJ 新エリア(1 筆) ──────────────────
  {
    slug: "usj-donkey-kong-country",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "USJ ドンキーコング・カントリー(2024/12 開業・SNW 拡張・任天堂第 2 弾)",
    title_ja: "ドンキーコング・カントリー",
    romaji: "Donkey Kong Country",
    summary_zh:
      "2024/12 USJ Super Nintendo World 拡張で開業した任天堂第 2 弾エリア。ドンキーコングのジャングル世界を再現,主要ライド『ドンキーコング・カントリー・マイン・カート・マッドネス』(動的トロッコシミュレーター)。1.7 ha・SNW 全体面積の 70% 拡張。",
    content_md:
      "- 開業:2024/12\n- 立地:USJ SNW 拡張\n- 主要ライド:マイン・カート・マッドネス\n- 1.7 ha\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.665,
    lon: 135.432,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.usj.co.jp/web/ja/jp/area/donkey-kong-country" },
    tags: ["theme_park", "usj", "donkey_kong", "since_2024", "snw_expansion"],
    source: "manual",
  },

  // ── R3-C. 桜・紅葉追加(4 筆) ──────────────────
  {
    slug: "hattori-ryokuchi-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "服部緑地 桜(豊中・1500 本・大阪府最大都市公園春景)",
    title_ja: "服部緑地 桜",
    romaji: "Hattori Ryokuchi Sakura",
    summary_zh:
      "大阪府最大都市公園(126 ha・1941 開園)の春桜 1500 本(ソメイヨシノ + ヤマザクラ)。3 月末 - 4 月初開花。日本民家集落博物館 + 円形花壇 + ピクニック広場の組合せで家族花見スポット。豊中市阪急曽根駅徒歩 10 分。",
    content_md:
      "- 規模:1500 本\n- 開花:3 月末 - 4 月初\n- 大阪府最大都市公園\n- 阪急曽根駅徒歩 10 分\n- 入園:24h 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "豊中市",
    lg_code: "27203",
    area_types: ["urban", "suburban"],
    lat: 34.778,
    lon: 135.487,
    season_start: "2026-03-25",
    season_end: "2026-04-10",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "hattori_ryokuchi", "toyonaka", "family"],
    source: "manual",
  },
  {
    slug: "daisen-koen-koyo",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "大仙公園 紅葉(堺・古墳隣接・1000 本・11 月下旬)",
    title_ja: "大仙公園 紅葉",
    romaji: "Daisen Kōen Kōyō",
    summary_zh:
      "堺市大仙公園(38 ha・仁徳天皇陵隣接)内 1000 本余のモミジ + イチョウが秋紅葉。11 月中旬 - 12 月初開葉。世界遺産 仁徳陵を背景にした紅葉景観 + 日本庭園(枯山水 + 紅葉)+ 堺市博物館徒歩 5 分。",
    content_md:
      "- 規模:1000 本余\n- 開葉:11 月中旬 - 12 月初\n- 仁徳陵隣接\n- 日本庭園 + 博物館徒歩 5 分\n- 入園:24h 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "堺市",
    lg_code: "27140",
    area_types: ["urban"],
    lat: 34.564,
    lon: 135.488,
    season_start: "2026-11-15",
    season_end: "2026-12-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["momiji", "daisen", "sakai", "world_heritage_view"],
    source: "manual",
  },
  {
    slug: "ikeda-jo-koen-koyo",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "池田城跡公園 紅葉(室町期山城跡 + モミジ・11 月下旬)",
    title_ja: "池田城跡公園 紅葉",
    romaji: "Ikeda-jō Kōen Kōyō",
    summary_zh:
      "室町期池田氏居城跡(現城跡公園)の秋紅葉 200 本余。11 月中旬 - 12 月初開葉。模擬櫓 + 茶室 + 復元枯山水 + 紅葉のコラボが歴史と秋の融合。阪急池田駅徒歩 15 分。",
    content_md:
      "- 規模:200 本余\n- 開葉:11 月中旬 - 12 月初\n- 室町期池田氏居城跡\n- 模擬櫓 + 茶室\n- 入園:9:00-19:00 火曜休 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "池田市",
    lg_code: "27204",
    area_types: ["urban"],
    lat: 34.823,
    lon: 135.430,
    season_start: "2026-11-15",
    season_end: "2026-12-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: ["tue"],
    external_urls: {},
    tags: ["momiji", "ikeda", "castle_ruins"],
    source: "manual",
  },
  {
    slug: "takatsuki-shiroyama-koyo",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "高槻城跡公園 紅葉(高山右近城跡 + モミジ・11 月下旬)",
    title_ja: "高槻城跡公園 紅葉",
    romaji: "Takatsuki Shiroyama Kōyō",
    summary_zh:
      "高山右近時代(1573)の高槻城跡公園内 300 本余の紅葉。11 月中旬 - 12 月初開葉。石垣 + 内堀復元 + 紅葉のコラボが歴史と秋の融合。高山右近記念聖堂(1962)隣接。",
    content_md:
      "- 規模:300 本余\n- 開葉:11 月中旬 - 12 月初\n- 高山右近(1573)石垣 + 内堀\n- 高山右近記念聖堂隣接\n- 入園:24h 無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "高槻市",
    lg_code: "27207",
    area_types: ["urban"],
    lat: 34.846,
    lon: 135.616,
    season_start: "2026-11-15",
    season_end: "2026-12-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["momiji", "takatsuki", "shiroyama", "takayama_ukon"],
    source: "manual",
  },

  // ── R3-D. 花畑追加(4 筆) ──────────────────
  {
    slug: "nakanoshima-park-bara-spring",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "中之島公園バラ園(春バラ・310 品種 3700 株・5 月中旬)",
    title_ja: "中之島公園バラ園",
    romaji: "Nakanoshima Park Bara-en",
    summary_zh:
      "中之島公園内 13000 ㎡のバラ園。310 品種 3700 株のバラが 5 月中旬 - 6 月初に春バラ最盛期。大阪市中央公会堂(1918)+ 中之島中央図書館(1904)+ 朝日新聞ビルの近代建築群と組合せた『大阪のバラ』撮影スポット。観覧無料。",
    content_md:
      "- 規模:310 品種 3700 株(13000 ㎡)\n- 春バラ:5 月中旬 - 6 月初\n- 中央公会堂背景\n- 観覧無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.694,
    lon: 135.504,
    season_start: "2026-05-15",
    season_end: "2026-06-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["flower_field", "bara", "nakanoshima", "spring", "kindai_kenchiku"],
    source: "manual",
  },
  {
    slug: "nakanoshima-park-bara-autumn",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "中之島公園バラ園 秋バラ(10 月中旬・色濃いめ + 香り強)",
    title_ja: "中之島公園 秋バラ",
    romaji: "Nakanoshima Park Bara Autumn",
    summary_zh:
      "中之島公園バラ園の秋バラ(10 月中旬 - 11 月初)。気温下がり昼夜寒暖差で色が春バラより濃く + 香りも強い。春に比べ観光客少なめで穴場。中央公会堂 + 中之島近代建築群と組合せ撮影定番。",
    content_md:
      "- 期間:10 月中旬 - 11 月初\n- 色:春バラより濃い\n- 香り:強\n- 春より観光客少なめ\n- 観覧無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.694,
    lon: 135.504,
    season_start: "2026-10-15",
    season_end: "2026-11-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["flower_field", "bara", "nakanoshima", "autumn"],
    source: "manual",
  },
  {
    slug: "expo-park-cosmos-october",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "万博記念公園 コスモス(10-11 月・15 万本・自然文化園)",
    title_ja: "万博記念公園 コスモス",
    romaji: "Banpaku Kōen Cosmos",
    summary_zh:
      "万博記念公園自然文化園 コスモスの丘 5000 ㎡に 15 万本のコスモス。10 月中旬 - 11 月初開花。太陽の塔背景にコスモス畑の構図が SNS 大人気。大阪 No.1 コスモス名所。",
    content_md:
      "- 規模:15 万本(5000 ㎡)\n- 開花:10 月中旬 - 11 月初\n- 太陽の塔背景\n- 大阪 No.1 コスモス\n- 入園:¥260\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "吹田市",
    lg_code: "27205",
    area_types: ["urban", "suburban"],
    lat: 34.808,
    lon: 135.535,
    season_start: "2026-10-15",
    season_end: "2026-11-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["wed"],
    external_urls: {},
    tags: ["flower_field", "cosmos", "expo_park", "autumn", "150000"],
    source: "manual",
  },
  {
    slug: "expo-park-azalea-spring",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "万博記念公園 ツツジ(4-5 月・3000 本・春の花暦)",
    title_ja: "万博記念公園 ツツジ",
    romaji: "Banpaku Kōen Tsutsuji",
    summary_zh:
      "万博記念公園自然文化園内 3000 本のツツジ(キリシマツツジ + ヒラドツツジ等)。4 月中旬 - 5 月中旬開花。コスモス + バラ + 桜と並ぶ万博 4 大花暦。大阪 No.1 ツツジ名所。",
    content_md:
      "- 規模:3000 本\n- 開花:4 月中旬 - 5 月中旬\n- 大阪 No.1 ツツジ\n- 入園:¥260\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "吹田市",
    lg_code: "27205",
    area_types: ["urban", "suburban"],
    lat: 34.808,
    lon: 135.535,
    season_start: "2026-04-15",
    season_end: "2026-05-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["wed"],
    external_urls: {},
    tags: ["flower_field", "tsutsuji", "expo_park", "spring"],
    source: "manual",
  },

  // ── R3-E. スポーツ・年中行事(2 筆) ──────────────────
  {
    slug: "osaka-marathon-march",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "大阪マラソン(2011 創始・3 月開催・関西最大シティマラソン)",
    title_ja: "大阪マラソン",
    romaji: "Ōsaka Marathon",
    summary_zh:
      "2011 創始の大阪市内シティマラソン(フルマラソン 42.195 km)。毎年 2 月末 - 3 月開催。大阪城公園 → 御堂筋 → 大阪城公園の周回コースで,3 万人余ランナー参加。日本三大マラソン(東京 + 大阪 + 京都)の一つ。観戦無料。",
    content_md:
      "- 創始:2011\n- 開催:2 月末 - 3 月初\n- フルマラソン:42.195 km\n- 参加:3 万人余\n- コース:大阪城 → 御堂筋\n- 観戦無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.687,
    lon: 135.526,
    season_start: null,
    season_end: null,
    event_start: "2026-02-22",
    event_end: "2026-02-22",
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.osaka-marathon.com/" },
    tags: ["marathon", "osaka_city", "since_2011", "japan_3_great"],
    source: "manual",
  },
  {
    slug: "osaka-grand-sumo-haru-basho",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "大相撲 三月場所(春場所・大阪府立体育会館・1953 開設・年 1 回 15 日)",
    title_ja: "大相撲 三月場所",
    romaji: "Ōzumō Sangatsu Basho",
    summary_zh:
      "大相撲六場所のうち春場所(大阪場所)。毎年 3 月の第 2 日曜から 15 日間,難波の大阪府立体育会館(1953 開設)で開催。年間 1 回の関西大相撲開催で,大阪・関西相撲ファン + 海外観客の聖地。チケット ¥3500-15000(マス席)。",
    content_md:
      "- 開催:3 月第 2 日曜から 15 日間\n- 会場:大阪府立体育会館(1953)\n- 場所:難波\n- チケット:¥3500-15000\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.665,
    lon: 135.502,
    season_start: null,
    season_end: null,
    event_start: "2026-03-08",
    event_end: "2026-03-22",
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.sumo.or.jp/" },
    tags: ["sumo", "haru_basho", "namba", "since_1953"],
    source: "manual",
  },

  // ── R3-F. 銭湯・スパ追加(2 筆) ──────────────────
  {
    slug: "spa-suminoe",
    category: "entertainment",
    sub_type: "osaka_onsen_spa",
    title_zh: "スパスミノエ(1986・住之江・関西最古級スパ・天然温泉付)",
    title_ja: "スパスミノエ",
    romaji: "Spa Suminoe",
    summary_zh:
      "1986 住之江区(住之江競艇隣接)に開業の関西最古級スパ施設。天然温泉(地下 1500 m)+ 露天 + 内湯 + サウナ + 食事処。住之江競艇場 + 大阪南港アクセス便利。1 泊 + 入浴の宿泊プランも有。日帰り ¥1500-2500。",
    content_md:
      "- 開業:1986(関西最古級スパ)\n- 立地:住之江区(住之江競艇隣接)\n- 天然温泉(地下 1500 m)\n- 入館:¥1500-2500(日帰り)\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban", "coastal"],
    lat: 34.612,
    lon: 135.467,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://spasuminoe.jp/" },
    tags: ["onsen", "spa_suminoe", "since_1986", "natural_onsen"],
    source: "manual",
  },
  {
    slug: "naniwanoyu-tenma",
    category: "entertainment",
    sub_type: "osaka_onsen_spa",
    title_zh: "なにわの湯(1999 天満・天然温泉・大阪市内最古級銭湯型スパ)",
    title_ja: "なにわの湯",
    romaji: "Naniwa-no-Yu",
    summary_zh:
      "1999 北区天満(天神橋筋商店街徒歩 5 分)に開業の天然温泉付銭湯型スパ。地下 850 m から汲上の天然温泉(ナトリウム炭酸水素塩泉)+ 露天 + 内湯 + サウナ + 漢方薬湯。大阪市内最古級銭湯型スパ。日帰り ¥850-1500。",
    content_md:
      "- 開業:1999\n- 立地:天満(天神橋筋徒歩 5 分)\n- 天然温泉:地下 850 m(ナトリウム炭酸水素塩泉)\n- 入館:¥850-1500\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "大阪市",
    lg_code: "27100",
    area_types: ["urban_central"],
    lat: 34.700,
    lon: 135.510,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://naniwanoyu.com/" },
    tags: ["onsen", "naniwanoyu", "tenma", "since_1999"],
    source: "manual",
  },

  // ── R3-G. 季節食材追加(2 筆) ──────────────────
  {
    slug: "kawachi-fig-autumn",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "河内イチジク(8-10 月・羽曳野 + 富田林・大阪府全国生産 No.1)",
    title_ja: "河内イチジク",
    romaji: "Kawachi Ichijiku",
    summary_zh:
      "大阪府は全国 No.1 のイチジク生産県(2024 統計)。河内地域(羽曳野 + 富田林 + 太子町)の山麓土壌で大粒甘味の濃いイチジクが採れる。8 月中旬 - 10 月中旬収穫期に直売所 + 道の駅で販売。生食 + ジャム + ワイン用が定番。",
    content_md:
      "- 期間:8 月中旬 - 10 月中旬\n- 立地:河内地域(羽曳野 + 富田林 + 太子町)\n- 大阪府全国 No.1 生産\n- 用途:生食 + ジャム + ワイン用\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "羽曳野市",
    lg_code: "27222",
    area_types: ["rural"],
    lat: 34.554,
    lon: 135.605,
    season_start: "2026-08-15",
    season_end: "2026-10-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_food", "ichijiku", "kawachi", "autumn", "no1_japan"],
    source: "manual",
  },
  {
    slug: "osaka-strawberry-greenhouse-winter",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "大阪温室いちご(12-2 月・羽曳野 + 富田林・冬期高設栽培観光いちご狩り)",
    title_ja: "大阪温室いちご",
    romaji: "Ōsaka Onshitsu Ichigo",
    summary_zh:
      "大阪府の温室いちご栽培。羽曳野 + 富田林 + 河内長野等の南河内 + 北摂地域で,12 月初 - 2 月末の冬期(早期は 11 月)に高設栽培ハウスで観光いちご狩り。1 月クリスマス・年末年始は予約必須。あまおう + 章姫 + 紅ほっぺ等。30 分食べ放題 ¥2200-3500。R1 春いちご(1-5 月)の冬期早期 version。",
    content_md:
      "- 期間:12 月初 - 2 月末(早期 11 月)\n- 立地:南河内 + 北摂\n- 温室高設栽培\n- 食べ放題:¥2200-3500(冬期は春より高)\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "大阪府",
    gun_ja: null,
    municipality_ja: "羽曳野市",
    lg_code: "27222",
    area_types: ["rural"],
    lat: 34.554,
    lon: 135.605,
    season_start: "2026-12-01",
    season_end: "2027-02-28",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_food", "strawberry", "winter", "greenhouse"],
    source: "manual",
  },
];

async function main() {
  console.log(`[seed] ${rows.length} rows to seed`);
  const byKind: Record<string, number> = {};
  for (const r of rows) byKind[r.sub_type] = (byKind[r.sub_type] ?? 0) + 1;
  console.log(`[seed] by sub_type: ${JSON.stringify(byKind, null, 2)}`);

  if (DRY) {
    for (const r of rows) {
      console.log(
        `  [${r.sub_type.padEnd(28)}] ${r.title_zh} (${r.municipality_ja ?? "-"}/${r.lg_code ?? "-"})`,
      );
    }
    return;
  }

  const sb = createAdminClient();
  const { data, error } = await sb
    .from("japan_entries")
    .upsert(rows, { onConflict: "slug" })
    .select("id, slug");
  if (error) {
    console.error("[seed] upsert failed", error);
    process.exit(1);
  }
  console.log(`[seed] upserted ${data?.length ?? 0} rows`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
