// Seed 神奈川県 衣 R1(18 筆 / Sprint 1.2 / 第十四卷)
// 国指定伝統工芸 2 / 横浜港町 4 / 鎌倉湘南 3 / 軍港 2 / 装束 2 / スポーツ 3 / マスコット 1 / その他 1 = 18
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 国指定伝統工芸 2
  {
    slug: "kamakura-bori-1979",
    category: "fashion", sub_type: "kanagawa_dento",
    title_zh: "鎌倉彫(鎌倉市・1979 経済産業大臣指定伝統工芸品+ 鎌倉時代 1185 仏師運慶+ 円覚寺 1282 派生 800+ 年・桂・銀杏木彫漆塗椀+盆+ 工房 25+ 軒・「鎌倉彫会館」博物館・¥3,500-150,000・国際 SNS 海外伝統工芸代表)",
    title_ja: "鎌倉彫", romaji: "Kamakura Bori",
    summary_zh: "**鎌倉彫は 1979 経産大臣指定伝統工芸品・鎌倉時代 1185 仏師運慶+円覚寺 1282 派生 800+ 年・桂・銀杏木彫漆塗椀+盆**(鎌倉)。工房 25+ 軒、¥3,500-150,000、海外代表。",
    content_md: "- 立地:**鎌倉市**\n- 起源:**鎌倉時代 1185 仏師運慶 + 円覚寺 1282 派生 800+ 年**\n- 認定:**1979 経産大臣指定伝統工芸品**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["industrial_heritage"], lat: 35.3197, lon: 139.5519,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kamakura_bori", "1979_designation", "800_years"], source: "manual",
  },
  {
    slug: "hakone-yosegi-1984",
    category: "fashion", sub_type: "kanagawa_dento",
    title_zh: "箱根寄木細工(足柄下郡箱根町畑宿+小田原・1984 経済産業大臣指定伝統工芸品+ 江戸期 1830 年代石川仁兵衛発祥 195+ 年+ 70+ 種木材幾何学模様+ 寄木箱+秘密箱+コースター・畑宿 25+ 軒・¥1,500-25,000・国際 SNS 海外伝統工芸代表)",
    title_ja: "箱根寄木細工", romaji: "Hakone Yosegi",
    summary_zh: "**箱根寄木細工は 1984 経産大臣指定伝統工芸品・江戸期 1830 年代石川仁兵衛発祥 195+ 年・70+ 種木材幾何学模様・寄木箱+秘密箱**(箱根畑宿+小田原)。¥1,500-25,000。",
    content_md: "- 立地:**足柄下郡箱根町畑宿 + 小田原市**\n- 起源:**江戸期 1830 年代石川仁兵衛発祥 195+ 年**\n- 認定:**1984 経産大臣指定伝統工芸品**\n- 構成:**70+ 種木材幾何学模様**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "足柄下郡", municipality_ja: "箱根町", lg_code: "14382",
    area_types: ["industrial_heritage", "shopping_district"], lat: 35.2331, lon: 139.1064,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["hakone_yosegi", "1984_designation", "195_years"], source: "manual",
  },

  // 横浜港町 4
  {
    slug: "yokohama-silk-scarf",
    category: "fashion", sub_type: "kanagawa_yokohama_clothing",
    title_zh: "横浜シルクスカーフ+ シルク博物館 1959(横浜市中区山下町+元町・1859 横浜開港時シルク輸出発祥 166+ 年+ 1900 年代以降全国シルクスカーフ生産 90% シェア+ シルク博物館 1959+ 開港記念会館・¥3,500-25,000・国際 SNS 海外旅行者代表)",
    title_ja: "横浜シルクスカーフ", romaji: "Yokohama Silk Scarf",
    summary_zh: "**横浜シルクスカーフ+シルク博物館 1959 は 1859 開港時シルク輸出発祥 166+ 年・全国スカーフ生産 90% シェア・シルク博物館 1959**(中区山下町+元町)。¥3,500-25,000、海外代表。",
    content_md: "- 立地:**横浜市中区山下町 + 元町**\n- 起源:**1859 横浜開港時シルク輸出発祥 166+ 年**\n- 認定:**全国シルクスカーフ生産 90% シェア + シルク博物館 1959**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["industrial_heritage", "shopping_district"], lat: 35.4428, lon: 139.6450,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokohama_silk_1859", "silk_museum_1959"], source: "manual",
  },
  {
    slug: "yokohama-motomachi-fashion",
    category: "fashion", sub_type: "kanagawa_yokohama_clothing",
    title_zh: "横浜元町ファッションブランド(横浜市中区元町・R1 食 元町商店街 1859 派生・Mihama 1923 102+ 年(全国フォーマルバッグ老舗候補)+ Kitamura+ Star Jewelry 老舗+ Fukuzo 1955・¥18,000-150,000・国際 SNS 海外旅行者代表)",
    title_ja: "横浜元町ブランド", romaji: "Motomachi Brands",
    summary_zh: "**横浜元町ファッションブランドは R1 食 元町 1859 派生・Mihama 1923 102+ 年(全国フォーマルバッグ老舗)+Kitamura+Star Jewelry+Fukuzo 1955**(中区元町)。¥18,000-150,000、海外代表。",
    content_md: "- 立地:**横浜市中区元町**\n- 関連:**R1 食 元町商店街 1859 派生**\n- 老舗:**Mihama 1923 102+ 年 + Kitamura + Star Jewelry + Fukuzo 1955**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["shopping_district"], lat: 35.4400, lon: 139.6500,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["motomachi_brands", "mihama_1923"], source: "manual",
  },
  {
    slug: "yokohama-chinatown-aparel",
    category: "fashion", sub_type: "kanagawa_yokohama_clothing",
    title_zh: "横浜中華街土産アパレル(横浜市中区山下町・R1 食 横浜中華街 1859 派生・チャイナドレス+ パンダぬいぐるみ+ 関帝廟 1873 ロゴグッズ・国際 SNS 海外旅行者代表土産・¥1,200-12,000)",
    title_ja: "中華街アパレル", romaji: "Chinatown Aparel",
    summary_zh: "**横浜中華街土産アパレルは R1 食 横浜中華街 1859 派生・チャイナドレス+パンダぬいぐるみ+関帝廟 1873 ロゴグッズ**(中区山下町)。¥1,200-12,000、海外代表土産。",
    content_md: "- 立地:**横浜市中区山下町**\n- 関連:**R1 食 横浜中華街 1859 派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["shopping_district"], lat: 35.4428, lon: 139.6450,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["chinatown_aparel"], source: "manual",
  },
  {
    slug: "yokohama-akarenga-aparel",
    category: "fashion", sub_type: "kanagawa_yokohama_clothing",
    title_zh: "横浜赤レンガ倉庫アパレル+ クリスマスマーケット(横浜市中区新港・赤レンガ倉庫 1911 国指定有形文化財 2007 派生・横浜限定アパレル+ 雑貨+ クリスマスマーケット(11 月-12 月)・¥1,500-12,000・国際 SNS 海外旅行者代表)",
    title_ja: "赤レンガ倉庫アパレル", romaji: "Akarenga Aparel",
    summary_zh: "**横浜赤レンガ倉庫アパレル+クリスマスマーケットは赤レンガ 1911 国指定 2007 派生・限定アパレル+雑貨+クリスマスマーケット 11-12 月**(中区新港)。¥1,500-12,000。",
    content_md: "- 立地:**横浜市中区新港**\n- 関連:**赤レンガ倉庫 1911 国指定有形文化財 2007 派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["shopping_district", "history_site_castle"], lat: 35.4533, lon: 139.6428,
    season_start: "2026-11-01", season_end: "2026-12-25", event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["akarenga_aparel"], source: "manual",
  },

  // 鎌倉湘南 3
  {
    slug: "kamakura-omiyage-aparel",
    category: "fashion", sub_type: "kanagawa_shonan_clothing",
    title_zh: "鎌倉土産アパレル+ 鳩 T シャツ+ 大仏グッズ(鎌倉市・R1 食 鳩サブレー豊島屋 1894+R1 育 鎌倉大仏 1252 派生・鳩 T シャツ+ 大仏ぬいぐるみ+ 江ノ電ロゴグッズ・小町通 商店街・¥800-3,500・国際 SNS 海外旅行者代表)",
    title_ja: "鎌倉土産アパレル", romaji: "Kamakura Omiyage",
    summary_zh: "**鎌倉土産アパレル+鳩 T+大仏グッズは R1 食 鳩サブレー 1894+R1 育 大仏 1252 派生・鳩 T+大仏ぬいぐるみ+江ノ電ロゴ**(鎌倉)。¥800-3,500、海外代表。",
    content_md: "- 立地:**鎌倉市**\n- 関連:**R1 食 鳩サブレー豊島屋 1894 + R1 育 鎌倉大仏 1252 派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["shopping_district"], lat: 35.3197, lon: 139.5519,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kamakura_omiyage"], source: "manual",
  },
  {
    slug: "shonan-surf-aloha",
    category: "fashion", sub_type: "kanagawa_shonan_clothing",
    title_zh: "湘南サーフ+アロハ+ ハンテンウェア(鎌倉+藤沢+ 茅ヶ崎+ 江ノ島・1960 年代以降湘南サーフ文化発祥 65+ 年+ サザンオールスターズ茅ヶ崎発祥 1978 派生・サーフブランド+ アロハシャツ+ ボードショーツ+ 「TUBE」JIN ROH 老舗・¥3,500-25,000)",
    title_ja: "湘南サーフ", romaji: "Shōnan Surf",
    summary_zh: "**湘南サーフ+アロハは 1960 年代以降サーフ文化 65+ 年・サザンオールスターズ茅ヶ崎発祥 1978 派生・サーフ+アロハ+ボードショーツ**(鎌倉+藤沢+茅ヶ崎+江ノ島)。¥3,500-25,000。",
    content_md: "- 立地:**鎌倉市 + 藤沢市 + 茅ヶ崎市 + 江の島**\n- 起源:**1960 年代以降湘南サーフ文化発祥 65+ 年**\n- 認定:**サザンオールスターズ茅ヶ崎発祥 1978 派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "茅ヶ崎市", lg_code: "14207",
    area_types: ["shopping_district"], lat: 35.3331, lon: 139.4067,
    season_start: "2026-06-01", season_end: "2026-09-30", event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shonan_surf", "1960s"], source: "manual",
  },
  {
    slug: "enoshima-omiyage",
    category: "fashion", sub_type: "kanagawa_shonan_clothing",
    title_zh: "江ノ島土産アパレル+ 江ノ電グッズ(藤沢市江の島・R1 食 江ノ島たこせんべい 1985 派生・江ノ電ロゴ T シャツ+帽子+タオル+ 江ノ島水族館グッズ+ 江ノ島タワー観光土産・¥800-3,500・国際 SNS 海外旅行者代表)",
    title_ja: "江ノ島土産", romaji: "Enoshima Omiyage",
    summary_zh: "**江ノ島土産アパレル+江ノ電グッズは R1 食 たこせんべい 1985 派生・江ノ電ロゴ T+帽子+タオル+江ノ島水族館グッズ**(藤沢江の島)。¥800-3,500、海外代表。",
    content_md: "- 立地:**藤沢市江の島**\n- 関連:**R1 食 江ノ島たこせんべい 1985 派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "藤沢市", lg_code: "14205",
    area_types: ["shopping_district"], lat: 35.2997, lon: 139.4806,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["enoshima_omiyage"], source: "manual",
  },

  // 軍港 2
  {
    slug: "yokosuka-sukajan",
    category: "fashion", sub_type: "kanagawa_miura_clothing",
    title_zh: "横須賀スカジャン+ ネイビーグッズ(横須賀市本町+ どぶ板通商店街・1945 戦後米軍兵向けスカジャン発祥 80+ 年+ 全国「スカジャン」発祥地・刺繍ジャケット+ 龍+鷲+富士山+富士山+ どぶ板通り商店街・¥18,000-65,000)",
    title_ja: "横須賀スカジャン", romaji: "Yokosuka Sukajan",
    summary_zh: "**横須賀スカジャン+ネイビーグッズは 1945 戦後米軍兵向け発祥 80+ 年・全国「スカジャン」発祥地・刺繍ジャケット+龍+鷲+富士山**(横須賀本町+どぶ板通)。¥18,000-65,000。",
    content_md: "- 立地:**横須賀市本町 + どぶ板通商店街**\n- 起源:**1945 戦後米軍兵向けスカジャン発祥 80+ 年**\n- 認定:**全国「スカジャン」発祥地**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横須賀市", lg_code: "14201",
    area_types: ["shopping_district", "industrial_heritage"], lat: 35.2806, lon: 139.6711,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokosuka_sukajan", "1945", "national_origin"], source: "manual",
  },
  {
    slug: "misaki-gyoshi-hanten",
    category: "fashion", sub_type: "kanagawa_miura_clothing",
    title_zh: "三崎漁師袢纏+ 腹掛け(三浦市三崎+ 横須賀・R1 食 三崎マグロ派生・1900 年代以降三崎漁師伝統作業着 100+ 年+ 紺地白染抜+ 漁協屋号入袢纏+ 腹掛け+ 帆前掛け・¥4,500-15,000)",
    title_ja: "三崎漁師袢纏", romaji: "Misaki Gyoshi",
    summary_zh: "**三崎漁師袢纏+腹掛けは R1 食 三崎マグロ派生・1900 年代以降漁師伝統作業着 100+ 年・紺地白染抜+漁協屋号+腹掛け+帆前掛け**(三浦三崎+横須賀)。¥4,500-15,000。",
    content_md: "- 立地:**三浦市三崎 + 横須賀市**\n- 関連:**R1 食 三崎マグロ派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "三浦市", lg_code: "14210",
    area_types: ["industrial_heritage", "shopping_district"], lat: 35.1378, lon: 139.6178,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["misaki_gyoshi"], source: "manual",
  },

  // 装束 2
  {
    slug: "oyama-mode-pilgrimage-clothing",
    category: "fashion", sub_type: "kanagawa_kennō_clothing",
    title_zh: "大山詣り装束+ 大山阿夫利神社白装束(伊勢原市大山+ 平塚+ 秦野・大山阿夫利神社 紀元前 97 年伝承 2122+ 年(R1 育)派生・江戸期から「大山詣り」修験道装束+ 白装束+ 菅笠+ 金剛杖・年間 25 万人参拝・¥3,500-12,000)",
    title_ja: "大山詣り装束", romaji: "Ōyama Pilgrim",
    summary_zh: "**大山詣り装束+大山阿夫利白装束は紀元前 97 年伝承 2122+ 年(R1 育)派生・江戸期から「大山詣り」修験道装束+白装束+菅笠+金剛杖・年間 25 万人**(伊勢原大山+平塚+秦野)。¥3,500-12,000。",
    content_md: "- 立地:**伊勢原市大山 + 平塚市 + 秦野市**\n- 関連:**R1 育 大山阿夫利神社派生**\n- 起源:**江戸期から「大山詣り」修験道装束**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "伊勢原市", lg_code: "14214",
    area_types: ["industrial_heritage", "history_site_castle"], lat: 35.4250, lon: 139.2367,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["oyama_pilgrim"], source: "manual",
  },
  {
    slug: "kawasaki-daishi-omamori",
    category: "fashion", sub_type: "kanagawa_kawasaki_clothing",
    title_zh: "川崎大師参詣御朱印帳+お守り+巾着(川崎市川崎区大師町・川崎大師平間寺 1128 開基 897+ 年(R1 育)派生・全国第 3 位年間参拝者(成田山+明治神宮並ぶ)初詣 300 万人+ 御朱印帳+ 厄除お守り+ ダルマ・¥800-3,500・国際 SNS 海外旅行者代表)",
    title_ja: "川崎大師お守り", romaji: "Kawasaki Daishi Omamori",
    summary_zh: "**川崎大師参詣御朱印帳+お守り+巾着は 1128 開基 897+ 年・全国第 3 位年間参拝者(成田山+明治並ぶ)初詣 300 万人**(川崎大師町)。¥800-3,500、海外代表。",
    content_md: "- 立地:**川崎市川崎区大師町**\n- 関連:**R1 育 川崎大師平間寺 1128 派生**\n- 認定:**全国第 3 位年間参拝者(成田山 + 明治神宮並ぶ)初詣 300 万人**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "川崎市", lg_code: "14130",
    area_types: ["history_site_castle", "shopping_district"], lat: 35.5350, lon: 139.7300,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kawasaki_daishi_omamori"], source: "manual",
  },

  // スポーツ 3
  {
    slug: "yokohama-baystars-aparel",
    category: "fashion", sub_type: "kanagawa_sports",
    title_zh: "横浜 DeNA ベイスターズアパレル(横浜市中区+ JR 横浜駅+ 横浜スタジアム・1949 大洋ホエールズ創立 76+ 年+ 1992 横浜大洋→2011 横浜 DeNA・横浜スタジアム本拠地・¥1,500-9,500・国内野球ファン代表)",
    title_ja: "ベイスターズアパレル", romaji: "Baystars Aparel",
    summary_zh: "**横浜 DeNA ベイスターズアパレルは 1949 大洋ホエールズ創立 76+ 年+1992 横浜大洋→2011 横浜 DeNA・横浜スタジアム本拠地**(中区+横浜駅)。¥1,500-9,500、国内野球ファン代表。",
    content_md: "- 立地:**横浜市中区 + JR 横浜駅 + 横浜スタジアム**\n- 起源:**1949 大洋ホエールズ創立 76+ 年 + 1992 横浜大洋 → 2011 横浜 DeNA**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["shopping_district"], lat: 35.4439, lon: 139.6403,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["baystars_1949"], source: "manual",
  },
  {
    slug: "kawasaki-frontale-aparel",
    category: "fashion", sub_type: "kanagawa_sports",
    title_zh: "川崎フロンターレアパレル+ 等々力陸上競技場(川崎市中原区等々力・1955 富士通サッカー部 70+ 年+ 1996 J リーグ加盟 29+ 年+ 等々力陸上競技場本拠地・¥1,500-9,500・J リーグファン代表)",
    title_ja: "フロンターレアパレル", romaji: "Frontale Aparel",
    summary_zh: "**川崎フロンターレアパレル+等々力は 1955 富士通サッカー部 70+ 年+1996 J リーグ 29+ 年・等々力陸上本拠地**(川崎中原)。¥1,500-9,500、J リーグファン代表。",
    content_md: "- 立地:**川崎市中原区等々力**\n- 起源:**1955 富士通サッカー部 70+ 年 + 1996 J リーグ加盟 29+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "川崎市", lg_code: "14130",
    area_types: ["shopping_district"], lat: 35.5736, lon: 139.6464,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["frontale_1955"], source: "manual",
  },
  {
    slug: "yokohama-fmarinos-aparel",
    category: "fashion", sub_type: "kanagawa_sports",
    title_zh: "横浜 F・マリノスアパレル(横浜市中区+ 日産スタジアム・1972 日産自動車サッカー部創立 53+ 年+ 1992 横浜マリノス J リーグ加盟+ 日産スタジアム本拠地+ 川崎フロンターレ並ぶ神奈川 J リーグ 2 大・¥1,500-9,500)",
    title_ja: "F・マリノス", romaji: "F.Marinos Aparel",
    summary_zh: "**横浜 F・マリノスアパレルは 1972 日産自動車サッカー部 53+ 年+1992 J リーグ・日産スタジアム本拠地・川崎フロンターレ並ぶ神奈川 J リーグ 2 大**(横浜中区)。¥1,500-9,500。",
    content_md: "- 立地:**横浜市中区 + 日産スタジアム(港北区)**\n- 起源:**1972 日産自動車サッカー部創立 53+ 年 + 1992 横浜マリノス J リーグ加盟**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["shopping_district"], lat: 35.5103, lon: 139.6064,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["f_marinos_1972"], source: "manual",
  },

  // マスコット 1
  {
    slug: "kanagawa-kintaro-mascot",
    category: "fashion", sub_type: "kanagawa_mascot",
    title_zh: "かながわキンタロウ+ 県マスコットアパレル(全県・2011 神奈川県観光大使「かながわキンタロウ」採用 14+ 年+ 県の花ヤマユリ+ 県の鳥カモメ+ 県の木イチョウ・T シャツ+帽子+タオル+ ぬいぐるみ・¥800-2,500・JR 駅+羽田空港+全国百貨店流通)",
    title_ja: "かながわキンタロウ", romaji: "Kanagawa Kintarō",
    summary_zh: "**かながわキンタロウ+県マスコットアパレルは 2011 県観光大使採用 14+ 年・県花ヤマユリ+県鳥カモメ+県木イチョウ**(全県)。JR 駅+羽田+百貨店、¥800-2,500。",
    content_md: "- 全域:**神奈川県全域**\n- 起源:**2011 神奈川県観光大使「かながわキンタロウ」採用 14+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["shopping_district"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kanagawa_kintaro_2011"], source: "manual",
  },

  // その他 1
  {
    slug: "odawara-chochin",
    category: "fashion", sub_type: "kanagawa_ashigara_clothing",
    title_zh: "小田原ちょうちん+ 提灯祭(小田原市本町+ 大稲荷神社・江戸期 1700 年代発祥 300+ 年+ 折畳式携帯ちょうちん・小田原宿名物・小田原ちょうちん祭り 7 月+ 道の駅+小田原城観光土産・¥1,200-4,500・R1 食 小田原蒲鉾連動)",
    title_ja: "小田原ちょうちん", romaji: "Odawara Chōchin",
    summary_zh: "**小田原ちょうちん+提灯祭は江戸期 1700 年代発祥 300+ 年・折畳式携帯・小田原宿名物・ちょうちん祭り 7 月**(小田原本町+大稲荷)。¥1,200-4,500、R1 食 蒲鉾連動。",
    content_md: "- 立地:**小田原市本町 + 大稲荷神社**\n- 起源:**江戸期 1700 年代発祥 300+ 年**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "小田原市", lg_code: "14206",
    area_types: ["industrial_heritage", "shopping_district"], lat: 35.2581, lon: 139.1556,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["odawara_chochin"], source: "manual",
  },
];

seedMain(rows, "kanagawa-clothing-r1");
