// Seed 福島県 R6 收卷(20 筆 / Sprint 6.x — 第〇七卷完結・東北 6 県全卷完結)
// 食 4 / 住 3 / 衣 3 / 育 4 / 楽 4 / 行 2 = 20
//
// 223 entries 達成:R1 123 + R2 20 + R3 20 + R4 20 + R5 20 + R6 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "tohoku"; prefecture_ja: "福島県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 食 (4)
  { slug: "fukushima-aizu-anko-mochi-modern", category: "food", sub_type: "fukushima_meika", title_zh: "会津銘菓モダン+ あんこ和菓子(R1 食 会津みなとや+太郎庵+R3 食 ゆべし派生・現代化・ロールケーキ+大福+モンブラン+ JR 会津若松駅売店+全国百貨店ヒット+ ¥350-1,200+ 観光客 SNS 拡散)", title_ja: "会津銘菓モダン", romaji: "Aizu Meika Modern", summary_zh: "**会津銘菓モダン+あんこ和菓子は R1+R3 食 派生現代化**(ロールケーキ+大福+モンブラン)。会津若松駅+全国百貨店、¥350-1,200、SNS 拡散。", content_md: "- 関係:**R1 食 会津みなとや+太郎庵 + R3 食 ゆべし派生**\n- 構成:**ロールケーキ + 大福 + モンブラン**\n- 流通:**JR 会津若松駅売店 + 全国百貨店**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["restaurant_traditional", "shopping_district"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aizu_meika_modern"], source: "manual" },
  { slug: "fukushima-fish-sashimi-iwaki", category: "food", sub_type: "fukushima_seafood", title_zh: "いわき+常磐沿岸刺身盛り合わせ(R1 食 メヒカリ+サンマ+R1 食 相馬うに+ホッキ派生・常磐沿岸高級寿司刺身+ R1 楽 アクアマリン観光客向け+ いわき+相馬料亭 5+ 軒+ 1 人前 ¥3,500-8,500)", title_ja: "いわき常磐刺身盛り合わせ", romaji: "Iwaki Jōban Sashimi", summary_zh: "**いわき+常磐沿岸刺身盛り合わせは R1 食 メヒカリ+サンマ+うに+ホッキ派生**(常磐高級寿司刺身)。R1 楽 アクアマリン観光、料亭 5+ 軒、¥3,500-8,500。", content_md: "- 立地:**いわき市 + 相馬市 + 南相馬市**\n- 関係:**R1 食 メヒカリ + サンマ + 相馬うに + ホッキ 派生**\n- 構成:**常磐沿岸高級寿司刺身**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "いわき市", lg_code: "07204", area_types: ["restaurant_traditional"], lat: 37.0539, lon: 140.8869, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["iwaki_jaban_sashimi"], source: "manual" },
  { slug: "fukushima-jingisukan-azuma", category: "food", sub_type: "fukushima_meat", title_zh: "あづまジンギスカン+R5 楽 グランデコ系(福島市+猪苗代+北塩原・1980 年代開発+ ラム肉+りんごつけだれ+ R5 楽 あづま+グランデコスキー場 拠点+ 1 人前 ¥2,500-4,500+ R1 食 蔵王ジンギスカン(山形)系統と並ぶ東北ジンギスカン)", title_ja: "あづまジンギスカン", romaji: "Azuma Jingisukan", summary_zh: "**あづまジンギスカンは 1980 年代開発**(福島+猪苗代+北塩原・**ラム肉+りんごつけだれ**)。R5 楽 あづま+グランデコ拠点、¥2,500-4,500、R1 食 蔵王ジンギスカン(山形)系統。", content_md: "- 立地:**福島市 + 猪苗代町 + 北塩原村**\n- 起源:**1980 年代開発**\n- 構成:**ラム肉 + りんごつけだれ**\n- 並列:**R1 食 蔵王ジンギスカン(山形)+ あづまジンギスカン = 東北ジンギスカン 2 大**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["restaurant_traditional", "mountain_village"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["azuma_jingisukan"], source: "manual" },
  { slug: "fukushima-meibutsu-sake-cocktail", category: "food", sub_type: "fukushima_sake", title_zh: "福島地酒モダンカクテル+ ハイボール(R1 食 大七 1752+末廣 1850+飛露喜+R3 食 会津醤油使用 派生・現代和食店モダン日本酒コクテル+ 福島市内+郡山+会津 5+ バー+ ¥800-2,500/杯+ R1 衣 七日町通り観光客向け新代表)", title_ja: "福島地酒モダンカクテル", romaji: "Fukushima Sake Cocktail Modern", summary_zh: "**福島地酒モダンカクテルは R1 食+R3 食 派生現代和食モダン日本酒**(福島+郡山+会津・**5+ バー**)。¥800-2,500、R1 衣 七日町観光客向け新代表。", content_md: "- 関係:**R1 食 大七 1752 + 末廣 1850 + 飛露喜 + R3 食 会津醤油 派生**\n- 構成:**現代和食店モダン日本酒コクテル**\n- 規模:**福島 + 郡山 + 会津 5+ バー**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["restaurant_traditional"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["fukushima_sake_cocktail"], source: "manual" },

  // 住 (3)
  { slug: "fukushima-aizu-modern-luxury", category: "lodging", sub_type: "fukushima_aizu_castle", title_zh: "会津若松モダンラグジュアリー旅館 R6・無限堂+会津若松ガーデン(会津若松市・2010-2015 開業 高級旅館+ 全 30-50 室+ R1 育 鶴ヶ城眺望露天+ R1 食 馬刺し+R1 食 会津地鶏会席+ 1 泊 2 食 ¥38,500-65,000+ 海外観光客向け代表)", title_ja: "無限堂+会津若松ガーデン", romaji: "Mugendō / Aizu Garden", summary_zh: "**無限堂+会津若松ガーデンは 2010-2015 開業高級旅館**(会津若松・**全 30-50 室+R1 育 鶴ヶ城眺望露天**)。R1 食 馬刺し+地鶏会席、¥38,500-65,000、海外観光客代表。", content_md: "- 立地:**会津若松市**\n- 起源:**2010-2015 開業**\n- 規模:**全 30-50 室・高級旅館**\n- 看板:**R1 育 鶴ヶ城眺望露天**\n- 食事:**R1 食 馬刺し + 会津地鶏会席**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["onsen_field"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["mugendo_aizu_garden", "2010_2015_luxury"], source: "manual" },
  { slug: "fukushima-mountain-lodge-bandai", category: "lodging", sub_type: "fukushima_other_onsen", title_zh: "磐梯山麓ロッジ+裏磐梯ペンション拡張(耶麻郡北塩原村+猪苗代+磐梯町・R1 住 裏磐梯リゾート派生・小規模ロッジ+ペンション 全 20+ 軒+ R1 育 磐梯山+R1 楽 五色沼+R1 楽 諸橋ダリ 拠点+ 1 泊 2 食 ¥10,500-15,500)", title_ja: "磐梯山麓ロッジ", romaji: "Bandai Lodge", summary_zh: "**磐梯山麓ロッジ+裏磐梯ペンション拡張は R1 住 派生**(北塩原+猪苗代+磐梯・**全 20+ 軒小規模**)。R1 育 磐梯山+R1 楽 五色沼+諸橋ダリ拠点、¥10,500-15,500。", content_md: "- 立地:**耶麻郡北塩原村 + 猪苗代町 + 磐梯町**\n- 関係:**R1 住 裏磐梯リゾート派生**\n- 規模:**全 20+ 軒小規模ロッジ + ペンション**\n- 並列観光:**R1 育 磐梯山 + R1 楽 五色沼 + 諸橋ダリ**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "耶麻郡", municipality_ja: "北塩原村", lg_code: "07402", area_types: ["scenic_spot", "mountain_village"], lat: 37.6453, lon: 140.0853, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["bandai_lodge", "20_inns"], source: "manual" },
  { slug: "fukushima-3-11-recovery-hotel", category: "lodging", sub_type: "fukushima_other_onsen", title_zh: "浪江+大熊復興ホテル(双葉郡浪江町+大熊町・2018-2022 復興期開業+ 全 50-100 室+ R1 育 双葉 3.11 伝承館+R2 楽 浪江・大熊復興ツアー観光客向け+ 1 泊朝食付 ¥7,500-11,500+ 全国 学習向け復興ホテル代表)", title_ja: "浪江+大熊復興ホテル", romaji: "Namie / Ōkuma Recovery Hotel", summary_zh: "**浪江+大熊復興ホテルは 2018-2022 復興期開業**(双葉・**全 50-100 室**)。R1 育 3.11 伝承館+R2 楽 復興ツアー観光、¥7,500-11,500、全国学習復興ホテル代表。", content_md: "- 立地:**双葉郡浪江町 + 大熊町**\n- 起源:**2018-2022 復興期開業**\n- 規模:**全 50-100 室**\n- 並列観光:**R1 育 双葉 3.11 伝承館 + R2 楽 浪江・大熊復興ツアー**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "双葉郡", municipality_ja: "浪江町", lg_code: "07547", area_types: ["shopping_district"], lat: 37.4861, lon: 140.9986, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["namie_okuma_recovery_hotel"], source: "manual" },

  // 衣 (3)
  { slug: "fukushima-3-11-recovery-goods", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "ふくしま 3.11 復興グッズ(R1 育 双葉 3.11 伝承館+R2 楽 浪江・大熊復興ツアー派生・「がんばろうふくしま」+復興メッセージ T シャツ+缶バッジ+ ピンバッジ+ 道の駅+全国百貨店+ ¥500-2,500+ 全国 SNS 拡散学習土産代表)", title_ja: "ふくしま 3.11 復興グッズ", romaji: "Fukushima 3.11 Recovery", summary_zh: "**ふくしま 3.11 復興グッズは R1 育+R2 楽 派生**(「がんばろうふくしま」+復興メッセージ T シャツ+缶バッジ+ピンバッジ)。道の駅+全国百貨店、¥500-2,500、SNS 拡散学習土産代表。", content_md: "- 関係:**R1 育 双葉 3.11 伝承館 + R2 楽 浪江・大熊復興ツアー 派生**\n- 構成:**「がんばろうふくしま」+ 復興メッセージ T シャツ + 缶バッジ + ピンバッジ**\n- 流通:**道の駅 + 全国百貨店**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["shopping_district"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["fukushima_3_11_recovery_goods"], source: "manual" },
  { slug: "fukushima-tsuchiyu-kokeshi-master", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "土湯系こけし名工作品(R1 衣 土湯系こけし 1700 派生・伝統工芸士作 名工作品+ 100 万円超 高級こけし+ R1 住 土湯温泉拠点・福島こけし発祥地+ 全国こけしファン+海外観光客 SNS 拡散+ R1 育 県立美術館展示)", title_ja: "土湯系こけし名工作品", romaji: "Tsuchiyu Kokeshi Master", summary_zh: "**土湯系こけし名工作品は R1 衣 1700 派生・伝統工芸士作**(100 万円超高級こけし)。R1 住 土湯温泉拠点・福島こけし発祥地、全国+海外 SNS 拡散、R1 育 県立美術館展示。", content_md: "- 立地:**福島市土湯 + 二本松市岳**(R1 住 土湯温泉)\n- 関係:**R1 衣 土湯系こけし 1700 派生**\n- 認定:**伝統工芸士作 名工作品**\n- 価格:**100 万円超 高級品**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["craft_workshop"], lat: 37.7000, lon: 140.3500, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsuchiyu_master", "1m_yen"], source: "manual" },
  { slug: "fukushima-airport-souvenir", category: "fashion", sub_type: "fukushima_dept_store", title_zh: "福島空港+JR 駅売店(R1 行 福島空港 1993+R1 衣 福島駅 S-PAL+郡山エスパル派生・全 30+ 軒土産店集約+ R1 食 ままどおる+薄皮饅頭+R1 衣 赤べこ+R1 育 野口英世+全福島土産集約販売+ 観光客集中拠点)", title_ja: "福島空港+JR 駅売店", romaji: "Fukushima Airport / JR Souvenir", summary_zh: "**福島空港+JR 駅売店は R1 行+R1 衣 派生**(全 30+ 軒土産集約・**ままどおる+薄皮饅頭+赤べこ+野口英世**)。観光客集中拠点。", content_md: "- 立地:**福島空港 + JR 福島駅 + 郡山駅**\n- 関係:**R1 行 福島空港 1993 + R1 衣 福島 S-PAL + 郡山エスパル派生**\n- 規模:**全 30+ 軒土産店集約**\n- 並列:**R1 食 ままどおる + 薄皮饅頭 + R1 衣 赤べこ + R1 育 野口英世**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["shopping_district", "transit_hub"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["fukushima_airport_souvenir"], source: "manual" },

  // 育 (4)
  { slug: "fukushima-aizu-bukeyashiki-village", category: "culture", sub_type: "fukushima_aizu_castle", title_zh: "東山温泉武家屋敷詳細(R1 育 会津武家屋敷派生・R1 住 東山温泉郷隣接・38 棟 江戸期会津藩家老西郷頼母邸 詳細+ 茶室+蔵+門 全構造復元+ 入館 ¥850(R1 育 込み)+ R1 食 馬刺し+こづゆ茶屋併設)", title_ja: "東山温泉武家屋敷", romaji: "Higashiyama Bukeyashiki", summary_zh: "**東山温泉武家屋敷は R1 育 派生詳細・R1 住 東山温泉郷隣接**(38 棟会津藩家老西郷頼母邸+茶室+蔵+門全構造復元)。¥850 込み、R1 食 馬刺し茶屋併設。", content_md: "- 立地:**会津若松市東山温泉**(R1 住 東山温泉郷隣接)\n- 関係:**R1 育 会津武家屋敷派生**\n- 構成:**38 棟 江戸期会津藩家老西郷頼母邸 詳細・茶室+蔵+門 全構造復元**\n- 入館:**¥850**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["history_site_castle", "onsen_field"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["higashiyama_bukeyashiki"], source: "manual" },
  { slug: "fukushima-soma-noma-museum", category: "culture", sub_type: "fukushima_history_museum", title_zh: "相馬野馬追資料館(相馬市+南相馬市・1989 開館+ R1 楽 相馬野馬追 1300 年国指定 1978 派生資料館+ 武具+鎧+古文書 多数+ 1300 年伝承資料豊富+ 入館 ¥300+ R3 育 中村城跡(相馬利胤 1611)観光と組合せ)", title_ja: "相馬野馬追資料館", romaji: "Sōma Nomaoi Shiryōkan", summary_zh: "**相馬野馬追資料館は 1989 開館**(相馬+南相馬・**R1 楽 1300 年国指定 1978 派生**)。武具+鎧+古文書 1300 年資料、¥300、R3 育 中村城跡組合せ。", content_md: "- 立地:**相馬市 + 南相馬市**\n- 起源:**1989 開館 36 年**\n- 関係:**R1 楽 相馬野馬追 1300 年 派生資料館**\n- 内容:**武具 + 鎧 + 古文書 多数**\n- 入館:**¥300**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "相馬市", lg_code: "07209", area_types: ["museum_art"], lat: 37.7967, lon: 140.9189, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["soma_nomaoi_shiryo", "1989"], source: "manual" },
  { slug: "fukushima-azuma-shrine-temples", category: "culture", sub_type: "fukushima_shrine_temple", title_zh: "福島市稲荷神社+寺院群(福島市・福島稲荷神社 1592 創建+ 福島市内 古社 5+ 軒+ R3 育 福島市文化センター旧舎隣接+ 4 月稲荷祭礼+ 入場無料+ R1 楽 花見山公園観光と組合せ)", title_ja: "福島市稲荷神社", romaji: "Fukushima Inari Jinja", summary_zh: "**福島市稲荷神社+寺院群は 1592 創建+市内古社 5+ 軒**(福島・**4 月稲荷祭礼**)。R3 育 文化センター旧舎隣接、無料、R1 楽 花見山組合せ。", content_md: "- 立地:**福島市**\n- 起源:**1592 創建**\n- 規模:**福島市内 古社 5+ 軒**\n- 並列:**R3 育 福島市文化センター旧舎隣接 + R1 楽 花見山公園**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["shrine_temple"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: "2026-04-15", event_end: "2026-04-15", price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["fukushima_inari", "1592"], source: "manual" },
  { slug: "fukushima-tohoku-region-tour-history", category: "culture", sub_type: "fukushima_history_museum", title_zh: "東北 6 県観光連絡施設(福島市+郡山+会津若松・1980 年代開設+ R1 行 東北新幹線福島駅+郡山駅連動+ 東北 6 県(青森+岩手+宮城+秋田+山形+福島)観光案内集約+ 国際観光客向け+ 入場無料+ JR 駅徒歩 5 分)", title_ja: "東北 6 県観光連絡施設", romaji: "Tōhoku 6 Pref Tour Liaison", summary_zh: "**東北 6 県観光連絡施設は 1980 年代開設**(福島+郡山+会津若松・**R1 行 新幹線連動+6 県観光案内集約**)。国際観光客向け、無料、JR 駅徒歩 5 分。", content_md: "- 立地:**福島市 + 郡山市 + 会津若松市**\n- 起源:**1980 年代開設**\n- 構成:**東北 6 県(青森 + 岩手 + 宮城 + 秋田 + 山形 + 福島)観光案内集約**\n- 並列:**R1 行 東北新幹線福島駅 + 郡山駅連動**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["transit_hub", "shopping_district"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tohoku_6_liaison"], source: "manual" },

  // 楽 (4)
  { slug: "fukushima-aizu-tour-pass-3day", category: "entertainment", sub_type: "fukushima_outdoor", title_zh: "会津まるごとパス・3 日券+ 会津周遊観光(R1 行 会津バス 1 日+R4 行 会津エリアパス 2 日派生・3 日 ¥5,500+ R1 育 鶴ヶ城+大内宿+塔のへつり+R1 楽 五色沼+R1 食 喜多方ラーメン全会津周遊・SNS 拡散代表)", title_ja: "会津まるごとパス 3 日券", romaji: "Aizu Marugoto Pass 3-Day", summary_zh: "**会津まるごとパス 3 日券は ¥5,500**(R1+R4 派生・**R1 育 鶴ヶ城+大内宿+R1 楽 五色沼+R1 食 喜多方ラーメン**)。全会津周遊・SNS 拡散代表。", content_md: "- 関係:**R1 行 会津バス 1 日 + R4 行 会津エリアパス 2 日 派生**\n- 期:**3 日連続使用**\n- 料金:**¥5,500**\n- 並列観光:**R1 育 鶴ヶ城 + 大内宿 + 塔のへつり + R1 楽 五色沼 + R1 食 喜多方ラーメン**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["festival_event"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aizu_marugoto_3day"], source: "manual" },
  { slug: "fukushima-tadami-momiji-train", category: "entertainment", sub_type: "fukushima_outdoor", title_zh: "JR 只見線紅葉列車(R1 楽 只見線+R3 行 只見線派生・10-11 月紅葉期特別便+ 第一只見川橋梁・第三只見川橋梁 紅葉名所+ 全国紅葉鉄道 No.1 候補+ 海外観光客 SNS 拡散・1 日 5-6 便+ ¥1,500-3,500)", title_ja: "JR 只見線紅葉列車", romaji: "Tadami Momiji Train", summary_zh: "**JR 只見線紅葉列車は R1 楽+R3 行 派生・10-11 月特別便**(第一+第三只見川橋梁紅葉名所)。全国紅葉鉄道 No.1 候補、海外 SNS 拡散、1 日 5-6 便、¥1,500-3,500。", content_md: "- 関係:**R1 楽 只見線 1971 + R3 行 只見線詳細 派生**\n- 期:**10-11 月紅葉期特別便**\n- 看板:**第一只見川橋梁 + 第三只見川橋梁 紅葉名所**\n- 認定:**全国紅葉鉄道 No.1 候補**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "只見町", lg_code: "07367", area_types: ["transit_hub", "scenic_spot"], lat: 37.3506, lon: 139.3147, season_start: "2026-10-15", season_end: "2026-11-15", event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["tadami_momiji_train"], source: "manual" },
  { slug: "fukushima-iizaka-momiji", category: "entertainment", sub_type: "fukushima_outdoor", title_zh: "飯坂温泉紅葉観光(R1 住 飯坂温泉郷+R3 楽 飯坂花火+R5 楽 飯坂冬の物語派生・10-11 月紅葉期+ 摺上川渓谷紅葉名所+ 浴衣ライトアップ・観覧無料+ R1 食 円盤餃子(福島市)観光と組合せ)", title_ja: "飯坂温泉紅葉観光", romaji: "Iizaka Onsen Momiji", summary_zh: "**飯坂温泉紅葉観光は R1 住+R3+R5 楽 派生・10-11 月紅葉期**(福島飯坂・**摺上川渓谷紅葉**)。浴衣ライトアップ無料、R1 食 円盤餃子組合せ。", content_md: "- 立地:**福島市飯坂**(R1 住 飯坂温泉郷)\n- 関係:**R3 楽 飯坂花火 + R5 楽 飯坂冬の物語 派生**\n- 期:**10-11 月紅葉期**\n- 看板:**摺上川渓谷紅葉名所 + 浴衣ライトアップ**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["scenic_spot"], lat: 37.8244, lon: 140.4633, season_start: "2026-10-15", season_end: "2026-11-15", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["iizaka_momiji"], source: "manual" },
  { slug: "fukushima-tohoku-6-pref-tour", category: "entertainment", sub_type: "fukushima_outdoor", title_zh: "東北 6 県観光ハイライト周遊(JR 福島駅+郡山駅起点・R1 行 東北新幹線+山形新幹線分岐 連動・R6 育 東北 6 県観光連絡派生・福島→山形→秋田→青森→岩手→宮城 1 週間周遊コース+ JR EAST PASS Tohoku 5 日 ¥30,000)", title_ja: "東北 6 県観光ハイライト周遊", romaji: "Tōhoku 6 Pref Highlight", summary_zh: "**東北 6 県観光ハイライト周遊は R1 行 新幹線+R6 育 派生**(福島起点・**福島→山形→秋田→青森→岩手→宮城 1 週間**)。JR EAST PASS Tohoku 5 日 ¥30,000、海外 SNS 拡散。", content_md: "- 起点:**JR 福島駅 + 郡山駅**\n- 関係:**R1 行 東北新幹線 + 山形新幹線分岐 + R6 育 東北 6 県観光連絡施設派生**\n- 構成:**福島 → 山形 → 秋田 → 青森 → 岩手 → 宮城 1 週間周遊**\n- 料金:**JR EAST PASS Tohoku 5 日 ¥30,000(宮城 R4 行 派生)**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["transit_hub", "scenic_spot"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["tohoku_6_pref_tour", "1_week_loop"], source: "manual" },

  // 行 (2)
  { slug: "fukushima-shirakawa-tour-pass", category: "transport", sub_type: "fukushima_pass_ticket", title_zh: "白河+県南観光パス(白河市+西郷村+棚倉町・JR 東北本線+水郡線+市内バス共通券・1 日 ¥1,500+ R1 楽 白河小峰城 1340+R3 育 白河関跡 8 世紀+R3 楽 白河だるま市 観光客向け代表)", title_ja: "白河+県南観光パス", romaji: "Shirakawa Kennan Tour Pass", summary_zh: "**白河+県南観光パスは ¥1,500**(白河+西郷+棚倉・**JR 東北本線+水郡線+市内バス共通**)。R1 楽 白河小峰城+R3 育 白河関跡+R3 楽 だるま市観光向け。", content_md: "- 対象:**JR 東北本線 + 水郡線 + 白河市内バス**\n- 期:**1 日連続使用**\n- 料金:**¥1,500**\n- 並列観光:**R1 楽 白河小峰城 1340 + R3 育 白河関跡 8 世紀 + R3 楽 白河だるま市**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "白河市", lg_code: "07205", area_types: ["transit_hub"], lat: 37.1264, lon: 140.2117, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["shirakawa_kennan_pass"], source: "manual" },
  { slug: "fukushima-tour-taxi", category: "transport", sub_type: "fukushima_road", title_zh: "福島観光タクシー(福島市+郡山+会津若松+いわき・JR 駅前タクシー+ 半日 ¥18,500-25,000 + 1 日 ¥35,000-55,000+ R1 育 鶴ヶ城+大内宿+R1 楽 五色沼+磐梯+ハワイアンズ+R1 食 喜多方+米沢牛 効率周遊+ レンタカー無し旅行向け)", title_ja: "福島観光タクシー", romaji: "Fukushima Tour Taxi", summary_zh: "**福島観光タクシーは JR 福島+郡山+会津+いわき駅前**(半日 ¥18,500-25,000・1 日 ¥35,000-55,000)。R1 育 鶴ヶ城+大内宿+磐梯+ハワイアンズ+R1 食 喜多方周遊、レンタカー無し向け。", content_md: "- 立地:**JR 福島駅 + 郡山駅 + 会津若松駅 + いわき駅**\n- 価格:**半日 ¥18,500-25,000 + 1 日 ¥35,000-55,000**\n- 並列観光:**R1 育 鶴ヶ城 + 大内宿 + R1 楽 五色沼 + 磐梯 + ハワイアンズ + R1 食 喜多方ラーメン + 米沢牛(山形)効率周遊**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["transit_hub"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 7, closed_days: [], external_urls: {}, tags: ["fukushima_tour_taxi"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[fukushima-r6] 尚無條目"); return; }
  console.log(`[fukushima-r6] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[fukushima-r6] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[fukushima-r6] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[fukushima-r6] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
