// Seed 神奈川県 行 R1(19 筆 / Sprint 1.6 / 第十四卷)
// JR 4 / 私鉄 4 / 新幹線 1 / 地下鉄 1 / ターミナル 2 / 箱根登山 3 / 道路 2 / 港 1 / 江ノ電 1 = 19
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // JR 4
  {
    slug: "yokohama-station-1872",
    category: "transport", sub_type: "kanagawa_terminal",
    title_zh: "JR 横浜駅(横浜市西区高島・1872 明治 5 年新橋-横浜開通 153+ 年(国内最古鉄道駅候補)+ JR 6 路線+京急+東急東横+相鉄+横浜市営地下鉄+ 11 路線結節+ 1 日 230 万人乗降全国 4 位+ 横浜駅 5 代目 1980 改築)",
    title_ja: "JR 横浜駅", romaji: "JR Yokohama Station",
    summary_zh: "**JR 横浜駅は 1872 明治 5 年新橋-横浜開通 153+ 年(国内最古鉄道駅候補)・11 路線結節・1 日 230 万人乗降全国 4 位**(西区高島)。",
    content_md: "- 立地:**横浜市西区高島**\n- 起源:**1872 明治 5 年新橋-横浜開通 153+ 年(国内最古鉄道駅候補)**\n- 規模:**JR 6 路線 + 京急 + 東急東横 + 相鉄 + 横浜市営地下鉄 11 路線結節 + 1 日 230 万人乗降全国 4 位**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub", "history_site_castle"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokohama_station_1872", "national_oldest_rail_station"], source: "manual",
  },
  {
    slug: "jr-tokaido-honsen-1872",
    category: "transport", sub_type: "kanagawa_jr",
    title_zh: "JR 東海道本線(東京-神戸・1872 明治 5 年 新橋-横浜部分開通 153+ 年(国内最古鉄道路線)+ 国内最重要幹線・東京 R1 行 山手線並ぶ+ 横浜+川崎+大船+小田原+熱海・¥150-1,520/片道+ JR Pass 全外国人 free)",
    title_ja: "JR 東海道本線", romaji: "JR Tōkaidō",
    summary_zh: "**JR 東海道本線は 1872 明治 5 年新橋-横浜開通 153+ 年(国内最古鉄道路線)・国内最重要幹線・東京 R1 行 山手線並ぶ**(横浜+川崎+大船+小田原+熱海)。¥150-1,520/片道、JR Pass 可。",
    content_md: "- 起源:**1872 明治 5 年 新橋-横浜部分開通 153+ 年(国内最古鉄道路線)**\n- 認定:**国内最重要幹線**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_tokaido_1872", "national_oldest_route"], source: "manual",
  },
  {
    slug: "jr-yokosuka-line-1889",
    category: "transport", sub_type: "kanagawa_jr",
    title_zh: "JR 横須賀線(東京-久里浜・1889 明治 22 年大船-横須賀開通 136+ 年+ 1980 SM 分離(湘南新宿ライン+横須賀線分離)+ 大船+鎌倉+逗子+横須賀+久里浜・1 日 50 万人乗降+ 鎌倉観光主軸・¥150-1,520/片道)",
    title_ja: "JR 横須賀線", romaji: "JR Yokosuka",
    summary_zh: "**JR 横須賀線は 1889 大船-横須賀 136+ 年・1980 SM 分離・大船+鎌倉+逗子+横須賀+久里浜・1 日 50 万人乗降・鎌倉観光主軸**(東京-久里浜)。¥150-1,520/片道。",
    content_md: "- 起源:**1889 明治 22 年大船-横須賀開通 136+ 年**\n- 規模:**1980 SM 分離 + 大船 + 鎌倉 + 逗子 + 横須賀 + 久里浜 + 1 日 50 万人乗降**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["transport_hub"], lat: 35.3197, lon: 139.5519,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_yokosuka_1889"], source: "manual",
  },
  {
    slug: "jr-yokohama-line-1908",
    category: "transport", sub_type: "kanagawa_jr",
    title_zh: "JR 横浜線+ 湘南新宿ライン+ 京浜東北線(横浜-八王子+ 新宿+ 大宮 各方面・JR 横浜線 1908 開通 117+ 年+ JR 湘南新宿ライン 2001 開通 24+ 年+ JR 京浜東北線 1914 R2 東京既載派生・関東通勤主軸・¥150-820/片道)",
    title_ja: "JR 横浜線+湘南新宿+京浜東北", romaji: "JR Yokohama Multi",
    summary_zh: "**JR 横浜線 1908 117+ 年+湘南新宿 2001 24+ 年+京浜東北 1914 R2 派生・関東通勤主軸**(横浜-八王子+新宿+大宮)。¥150-820/片道。",
    content_md: "- 起源:**JR 横浜線 1908 開通 117+ 年 + JR 湘南新宿ライン 2001 開通 24+ 年 + JR 京浜東北線 1914 R2 東京既載派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_yokohama_1908", "shonan_shinjuku_2001"], source: "manual",
  },

  // 私鉄 4
  {
    slug: "keikyu-honsen-1898-kanagawa",
    category: "transport", sub_type: "kanagawa_private_railway",
    title_zh: "京浜急行電鉄(東京 R3 既載派生・1898 創業 127+ 年+ 全国私鉄最古候補+ 神奈川県内 横浜+横須賀+三崎口・京急本線+大師線+逗子線+久里浜線+ 三浦半島観光主軸・¥150-1,250/片道)",
    title_ja: "京急電鉄神奈川", romaji: "Keikyū Kanagawa",
    summary_zh: "**京浜急行電鉄(東京 R3 派生)は 1898 創業 127+ 年・全国私鉄最古候補・神奈川 横浜+横須賀+三崎口・京急本線+大師+逗子+久里浜・三浦半島観光主軸**(神奈川全)。¥150-1,250/片道。",
    content_md: "- 立地:**横浜市 + 川崎市 + 横須賀市 + 三浦市**\n- 関連:**東京 R3 既載派生**\n- 起源:**1898 創業 127+ 年**\n- 認定:**全国私鉄最古候補 + 三浦半島観光主軸**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["keikyū_kanagawa", "1898"], source: "manual",
  },
  {
    slug: "tokyu-toyoko-kanagawa",
    category: "transport", sub_type: "kanagawa_private_railway",
    title_zh: "東急東横線+ 田園都市線(横浜市+川崎市+ 神奈川川崎・東京 R3 既載派生・1932 開業 93+ 年+ 渋谷-横浜 24.2km・1 日 200 万人乗降+ みなとみらい線 2004 直通+ 関東通勤+観光主軸・¥130-580/片道)",
    title_ja: "東急東横線神奈川", romaji: "Tōkyū Tōyoko Kanagawa",
    summary_zh: "**東急東横線+田園都市線は東京 R3 派生・1932 93+ 年・渋谷-横浜 24.2km・1 日 200 万人乗降+みなとみらい線 2004 直通**(横浜+川崎)。¥130-580/片道。",
    content_md: "- 立地:**横浜市 + 川崎市**\n- 関連:**東京 R3 既載派生**\n- 起源:**1932 東急東横線開業 93+ 年**\n- 規模:**渋谷-横浜 24.2km + みなとみらい線 2004 直通 + 1 日 200 万人乗降**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tokyu_toyoko_kanagawa"], source: "manual",
  },
  {
    slug: "odakyu-odawara-1927-kanagawa",
    category: "transport", sub_type: "kanagawa_private_railway",
    title_zh: "小田急電鉄+ ロマンスカー(東京 R1 行 既載派生・1927 創業 98+ 年+ 神奈川県内 海老名+本厚木+小田原+箱根湯本・「ロマンスカー」特急 1957 +新宿-箱根湯本 1.5h+ 江ノ島線・1 日 200 万人乗降・¥180-1,500/片道)",
    title_ja: "小田急小田原線神奈川", romaji: "Odakyū Kanagawa",
    summary_zh: "**小田急電鉄+ロマンスカーは東京 R1 行 派生・1927 98+ 年・神奈川 海老名+本厚木+小田原+箱根湯本・「ロマンスカー」特急 1957・新宿-箱根湯本 1.5h**(神奈川全)。¥180-1,500/片道。",
    content_md: "- 立地:**海老名市 + 厚木市 + 小田原市 + 箱根町**\n- 関連:**東京 R1 行 既載派生**\n- 起源:**1927 創業 98+ 年**\n- 規模:**「ロマンスカー」特急 1957 + 新宿-箱根湯本 1.5h + 江ノ島線**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "小田原市", lg_code: "14206",
    area_types: ["transport_hub"], lat: 35.2581, lon: 139.1556,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["odakyu_kanagawa"], source: "manual",
  },
  {
    slug: "enoden-1902",
    category: "transport", sub_type: "kanagawa_private_railway",
    title_zh: "江ノ島電鉄(藤沢市+鎌倉市・1902 明治 35 年開業 123+ 年+ 全国 5 大老舗私鉄候補+ 藤沢-鎌倉 10km・15 駅+ 江ノ島+由比ガ浜+長谷+鎌倉観光主軸+ R1 育 鎌倉大仏徒歩 5 分+R1 楽 七里ヶ浜・¥260/片道・国際 SNS 海外旅行者代表)",
    title_ja: "江ノ島電鉄", romaji: "Enoden",
    summary_zh: "**江ノ島電鉄は 1902 開業 123+ 年・全国 5 大老舗私鉄候補・藤沢-鎌倉 10km・15 駅・観光主軸**(藤沢+鎌倉)。R1 育 大仏徒歩 5 分+R1 楽 七里ヶ浜、¥260/片道、海外代表。",
    content_md: "- 立地:**藤沢市 + 鎌倉市**\n- 起源:**1902 明治 35 年開業 123+ 年**\n- 認定:**全国 5 大老舗私鉄候補 + 藤沢-鎌倉 10km + 15 駅**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "鎌倉市", lg_code: "14204",
    area_types: ["transport_hub"], lat: 35.3197, lon: 139.5519,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["enoden_1902", "123_years"], source: "manual",
  },

  // 新幹線 1
  {
    slug: "shin-yokohama-1964",
    category: "transport", sub_type: "kanagawa_terminal",
    title_zh: "新横浜駅+ 東海道新幹線(横浜市港北区新横浜・1964 東海道新幹線開業時設置 61+ 年+ JR 東海道新幹線+JR 横浜線+横浜市営地下鉄ブルーライン+相鉄新横浜線 4 路線結節+ 1 日 12 万人乗降+ 日産スタジアム 1998 隣接)",
    title_ja: "新横浜駅", romaji: "Shin-Yokohama",
    summary_zh: "**新横浜駅+東海道新幹線は 1964 開業 61+ 年・JR 東海道新幹線+JR 横浜線+横浜市営地下鉄+相鉄新横浜線 4 路線結節・1 日 12 万人乗降・日産スタジアム 1998 隣接**(港北新横浜)。",
    content_md: "- 立地:**横浜市港北区新横浜**\n- 起源:**1964 東海道新幹線開業時設置 61+ 年**\n- 規模:**4 路線結節 + 1 日 12 万人乗降 + 日産スタジアム 1998 隣接**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.5103, lon: 139.6164,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["shin_yokohama_1964"], source: "manual",
  },

  // 地下鉄 1
  {
    slug: "yokohama-subway-1972",
    category: "transport", sub_type: "kanagawa_subway",
    title_zh: "横浜市営地下鉄+ みなとみらい線(横浜市・横浜市営地下鉄 1972 開業 53+ 年+ ブルーライン+グリーンライン 2 線 53.4km・40 駅+ みなとみらい線 2004 開業 21+ 年+ 横浜-元町中華街 4.1km・1 日 50 万人乗降・¥220-580/片道)",
    title_ja: "横浜市営地下鉄+みなとみらい線", romaji: "Yokohama Subway",
    summary_zh: "**横浜市営地下鉄+みなとみらい線は 1972 53+ 年・ブルー+グリーン 2 線 53.4km+40 駅+みなとみらい線 2004 21+ 年・横浜-元町中華街 4.1km・1 日 50 万人**(横浜)。¥220-580/片道。",
    content_md: "- 立地:**横浜市**\n- 起源:**横浜市営地下鉄 1972 開業 53+ 年 + みなとみらい線 2004 開業 21+ 年**\n- 規模:**ブルーライン + グリーンライン 2 線 53.4km + 40 駅 + 横浜-元町中華街 4.1km**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokohama_subway_1972", "minatomirai_2004"], source: "manual",
  },

  // ターミナル 2
  {
    slug: "kawasaki-station-1872",
    category: "transport", sub_type: "kanagawa_terminal",
    title_zh: "JR 川崎駅+ 京急川崎駅(川崎市川崎区・1872 明治 5 年新橋-横浜開通時開設 153+ 年(国内最古鉄道駅候補)+ JR 4 路線+京急 2 路線 6 路線結節+ 1 日 60 万人乗降全国 8 位・京浜工業地帯+ R1 育 川崎大師アクセス)",
    title_ja: "JR 川崎駅", romaji: "JR Kawasaki Station",
    summary_zh: "**JR 川崎駅+京急川崎駅は 1872 153+ 年(国内最古鉄道駅候補)・JR 4 路線+京急 2 路線 6 路線結節・1 日 60 万人乗降全国 8 位**(川崎区)。京浜工業+川崎大師アクセス。",
    content_md: "- 立地:**川崎市川崎区**\n- 起源:**1872 明治 5 年新橋-横浜開通時開設 153+ 年(国内最古鉄道駅候補)**\n- 規模:**JR 4 路線 + 京急 2 路線 6 路線結節 + 1 日 60 万人乗降全国 8 位**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "川崎市", lg_code: "14130",
    area_types: ["transport_hub"], lat: 35.5308, lon: 139.7028,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kawasaki_station_1872"], source: "manual",
  },
  {
    slug: "odawara-station-1920",
    category: "transport", sub_type: "kanagawa_terminal",
    title_zh: "JR 小田原駅+ 新幹線+ 小田急小田原線+ 箱根登山鉄道(小田原市・1920 大正 9 年熱海線開通時設置 105+ 年+ JR 東海道新幹線+JR 東海道本線+小田急+箱根登山+伊豆箱根 5 路線結節・1 日 13 万人乗降+ R1 育 小田原城+R1 食 蒲鉾連動)",
    title_ja: "JR 小田原駅", romaji: "JR Odawara Station",
    summary_zh: "**JR 小田原駅+新幹線+小田急+箱根登山は 1920 105+ 年・5 路線結節・1 日 13 万人乗降・R1 育 小田原城+R1 食 蒲鉾連動**(小田原)。",
    content_md: "- 立地:**小田原市**\n- 起源:**1920 大正 9 年熱海線開通時設置 105+ 年**\n- 規模:**JR 東海道新幹線 + JR 東海道本線 + 小田急 + 箱根登山 + 伊豆箱根 5 路線結節 + 1 日 13 万人乗降**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "小田原市", lg_code: "14206",
    area_types: ["transport_hub"], lat: 35.2581, lon: 139.1556,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["odawara_station_1920"], source: "manual",
  },

  // 箱根登山 3
  {
    slug: "hakone-tozan-railway-1888",
    category: "transport", sub_type: "kanagawa_hakone_transport",
    title_zh: "箱根登山鉄道(足柄下郡箱根町・1888 馬車鉄道開業-1919 電化開通 137+ 年+ 全国最古登山鉄道+ 小田原-強羅 15km・10 駅+ 標高差 446m+ 80 ‰ 急勾配国内最大級+ 6 月梅雨期紫陽花名所(沿線 1 万株)+ 国際 SNS 鉄道ファン代表・¥760/片道)",
    title_ja: "箱根登山鉄道", romaji: "Hakone Tozan",
    summary_zh: "**箱根登山鉄道は 1888 馬車鉄道-1919 電化 137+ 年・全国最古登山鉄道・小田原-強羅 15km+10 駅・80‰急勾配国内最大級・6 月紫陽花 1 万株**(箱根)。¥760/片道、鉄道ファン代表。",
    content_md: "- 立地:**足柄下郡箱根町**\n- 起源:**1888 馬車鉄道開業 - 1919 電化開通 137+ 年**\n- 認定:**全国最古登山鉄道 + 小田原-強羅 15km + 80 ‰ 急勾配国内最大級**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "足柄下郡", municipality_ja: "箱根町", lg_code: "14382",
    area_types: ["transport_hub", "nature_park"], lat: 35.2331, lon: 139.1064,
    season_start: "2026-06-15", season_end: "2026-07-15", event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["hakone_tozan_1888", "national_oldest_mountain_rail"], source: "manual",
  },
  {
    slug: "hakone-tozan-cable-1921",
    category: "transport", sub_type: "kanagawa_hakone_transport",
    title_zh: "箱根登山ケーブルカー(足柄下郡箱根町強羅-早雲山・1921 大正 10 年開通 104+ 年+ 全国最古ケーブルカー候補(滋賀坂本ケーブル 1927+滋賀八幡山ケーブル 1962 並ぶ)+ 強羅-早雲山 1.2km・標高差 214m・¥440/片道)",
    title_ja: "箱根登山ケーブル", romaji: "Hakone Cable",
    summary_zh: "**箱根登山ケーブルカーは 1921 開通 104+ 年・全国最古ケーブルカー候補(滋賀坂本 1927+八幡山 1962 並ぶ)・強羅-早雲山 1.2km・標高差 214m**(箱根強羅-早雲山)。¥440/片道。",
    content_md: "- 立地:**足柄下郡箱根町強羅 - 早雲山**\n- 起源:**1921 大正 10 年開通 104+ 年**\n- 認定:**全国最古ケーブルカー候補(滋賀坂本ケーブル 1927 + 滋賀八幡山ケーブル 1962 並ぶ)**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "足柄下郡", municipality_ja: "箱根町", lg_code: "14382",
    area_types: ["transport_hub", "nature_park"], lat: 35.2531, lon: 139.0314,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["hakone_cable_1921"], source: "manual",
  },
  {
    slug: "hakone-ropeway-1959",
    category: "transport", sub_type: "kanagawa_hakone_transport",
    title_zh: "箱根ロープウェイ(足柄下郡箱根町・1959 開通 66+ 年+ 早雲山-大涌谷-桃源台 4km・標高差 540m・関東有数ロープウェイ・R1 楽 大涌谷+芦ノ湖海賊船連動・¥1,500/片道・国際 SNS 海外旅行者代表)",
    title_ja: "箱根ロープウェイ", romaji: "Hakone Ropeway",
    summary_zh: "**箱根ロープウェイは 1959 開通 66+ 年・早雲山-大涌谷-桃源台 4km・標高差 540m・関東有数**(箱根)。R1 楽 大涌谷+芦ノ湖海賊船連動、¥1,500/片道、海外代表。",
    content_md: "- 立地:**足柄下郡箱根町**\n- 起源:**1959 開通 66+ 年**\n- 規模:**早雲山-大涌谷-桃源台 4km + 標高差 540m**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: "足柄下郡", municipality_ja: "箱根町", lg_code: "14382",
    area_types: ["transport_hub", "nature_park"], lat: 35.2444, lon: 139.0211,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["hakone_ropeway_1959"], source: "manual",
  },

  // 道路 2
  {
    slug: "daisan-keihin-1965",
    category: "transport", sub_type: "kanagawa_kosoku",
    title_zh: "第三京浜+ 横羽線首都高(横浜市+川崎市・1965 第三京浜開通 60+ 年+ 1968 横羽線首都高+ 東京-横浜 30 分+ 京浜工業地帯通勤主軸+ アクアラインへ接続+R1 行 横浜駅+羽田空港アクセス・通行料 ¥520-1,000)",
    title_ja: "第三京浜+横羽線", romaji: "Daisan Keihin",
    summary_zh: "**第三京浜+横羽線首都高は 1965 60+ 年+1968 横羽線・東京-横浜 30 分・京浜工業地帯通勤主軸**(横浜+川崎)。¥520-1,000、アクアライン+羽田アクセス。",
    content_md: "- 起源:**1965 第三京浜開通 60+ 年 + 1968 横羽線首都高**\n- 規模:**東京-横浜 30 分 + 京浜工業地帯通勤主軸**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.4658, lon: 139.6225,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["daisan_keihin_1965"], source: "manual",
  },
  {
    slug: "seisho-bypass-1971",
    category: "transport", sub_type: "kanagawa_kosoku",
    title_zh: "西湘バイパス+ 真鶴道路(平塚-小田原-真鶴・1971 部分開通 54+ 年+ 1979 全通+ 西湘 23km+真鶴道路 6km・湘南海岸沿+ 富士山眺望 + R1 楽 大磯ロングビーチ+R1 食 小田原蒲鉾+R1 育 小田原城・通行料 ¥320-520)",
    title_ja: "西湘+真鶴道路", romaji: "Seishō Manaduru",
    summary_zh: "**西湘バイパス+真鶴道路は 1971 部分開通 54+ 年+1979 全通・西湘 23km+真鶴 6km・湘南海岸沿+富士眺望**(平塚-小田原-真鶴)。¥320-520、R1 楽 大磯+R1 食 蒲鉾+R1 育 小田原城。",
    content_md: "- 起源:**1971 部分開通 54+ 年 + 1979 全通**\n- 規模:**西湘 23km + 真鶴道路 6km + 湘南海岸沿 + 富士山眺望**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "小田原市", lg_code: "14206",
    area_types: ["transport_hub", "beach_coast"], lat: 35.2581, lon: 139.1556,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["seisho_1971"], source: "manual",
  },

  // 港 1
  {
    slug: "yokohama-port-1859",
    category: "transport", sub_type: "kanagawa_yokohama_terminal",
    title_zh: "横浜港(横浜市中区+西区・1859 6 月 2 日横浜開港 166+ 年+ 全国 4 大港湾(神戸+大阪+名古屋並ぶ)+ 国際クルーズ船寄港+ 大さん橋国際客船ターミナル 2002+ 横浜ぷかり桟橋・国際 SNS 海外旅行者代表)",
    title_ja: "横浜港", romaji: "Yokohama Port",
    summary_zh: "**横浜港は 1859 6 月 2 日開港 166+ 年・全国 4 大港湾(神戸+大阪+名古屋並ぶ)・国際クルーズ船寄港・大さん橋ターミナル 2002**(中区+西区)。海外代表。",
    content_md: "- 立地:**横浜市中区 + 西区**\n- 起源:**1859 6 月 2 日横浜開港 166+ 年**\n- 認定:**全国 4 大港湾(神戸 + 大阪 + 名古屋並ぶ) + 大さん橋国際客船ターミナル 2002**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "横浜市", lg_code: "14100",
    area_types: ["transport_hub"], lat: 35.4533, lon: 139.6428,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yokohama_port_1859"], source: "manual",
  },

  // ローカル 1
  {
    slug: "oyama-cable-1965",
    category: "transport", sub_type: "kanagawa_kennō_transport",
    title_zh: "大山ケーブル+ 大山観光電鉄(伊勢原市大山・1965 開業 60+ 年+ R1 育 大山阿夫利神社派生・大山ケーブル駅-阿夫利神社駅 0.8km・標高差 278m+ 紅葉名所+ 山頂大山詣り・¥640/片道)",
    title_ja: "大山ケーブル", romaji: "Ōyama Cable",
    summary_zh: "**大山ケーブル+大山観光電鉄は 1965 開業 60+ 年・R1 育 大山阿夫利神社派生・大山ケーブル駅-阿夫利神社駅 0.8km+標高差 278m+紅葉名所**(伊勢原大山)。¥640/片道。",
    content_md: "- 立地:**伊勢原市大山**\n- 起源:**1965 開業 60+ 年**\n- 関連:**R1 育 大山阿夫利神社派生**",
    region: "kanto", prefecture_ja: "神奈川県", gun_ja: null, municipality_ja: "伊勢原市", lg_code: "14214",
    area_types: ["transport_hub", "nature_park"], lat: 35.4250, lon: 139.2367,
    season_start: "2026-11-01", season_end: "2026-12-10", event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["oyama_cable_1965"], source: "manual",
  },
];

seedMain(rows, "kanagawa-transport-r1");
