// Seed 宮城県 R5 補完(20 筆 / Sprint 5.x)
// 食 4 / 住 3 / 衣 3 / 育 4 / 楽 4 / 行 2 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "tohoku"; prefecture_ja: "宮城県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 食 (4)
  { slug: "sendai-zundamochi-modern-cafe", category: "food", sub_type: "miyagi_3_meibutsu", title_zh: "ずんだ茶寮+ずんだ Saryo 現代カフェ(仙台市青葉区+JR 仙台駅・R1 食 ずんだ餅+シェイク派生・カフェ系統+ ずんだバウムクーヘン+パフェ+ジェラート+ ¥600-1,200+ 観光客 SNS 拡散+ 全国百貨店展開)", title_ja: "ずんだ茶寮 現代カフェ", romaji: "Zunda Saryo Modern Cafe", summary_zh: "**ずんだ茶寮現代カフェ系統は R1 食 ずんだ餅+シェイク派生**(青葉区+仙台駅)。ずんだバウムクーヘン+パフェ+ジェラート、SNS 拡散、¥600-1,200。", content_md: "- 立地:**仙台市青葉区 + JR 仙台駅**\n- 関係:**R1 食 ずんだ餅 + シェイク派生**\n- 構成:**ずんだバウムクーヘン + パフェ + ジェラート**\n- 流通:**全国百貨店展開**\n- 価格:**¥600-1,200**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["restaurant_traditional", "shopping_district"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["zunda_saryo", "modern_cafe", "baumkuchen"], source: "manual" },
  { slug: "shiroishi-umen-noodle-rest", category: "food", sub_type: "miyagi_kyodo", title_zh: "白石うーめん 食事処(白石市・R1 衣 白石うーめん 江戸期派生・食事処+ 短い手延べ素麺・冷+温+ 白石市内 8+ 軒+ 1 人前 ¥800-1,500+ R2 育 白石城+ R1 楽 蔵王きつね村 観光と組合せ)", title_ja: "白石うーめん食事処", romaji: "Shiroishi Umen Restaurant", summary_zh: "**白石うーめん食事処は R1 衣 派生・冷+温**(白石市・**8+ 軒+短い手延べ素麺**)。¥800-1,500、R2 育 白石城+R1 楽 きつね村観光組合せ。", content_md: "- 立地:**白石市**\n- 関係:**R1 衣 白石うーめん(江戸期)派生**\n- 構成:**冷うーめん + 温うーめん**\n- 規模:**白石市内 8+ 軒**\n- 並列観光:**R2 育 白石城 + R1 楽 蔵王きつね村**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "白石市", lg_code: "04205", area_types: ["restaurant_traditional"], lat: 38.0017, lon: 140.6189, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["shiroishi_umen_rest", "8_stores"], source: "manual" },
  { slug: "matsushima-sasaki-anago-don", category: "food", sub_type: "miyagi_seafood", title_zh: "松島あなご丼 老舗松島佐々直(松島町・1908 創業 117 年+ R3 食 松島あなご派生・専門店+ 蒸あなご丼 ¥2,200-3,500+ R1 育 松島観光客向け代表+ 仙台駅売店 + 通販)", title_ja: "松島あなご丼 松島佐々直", romaji: "Matsushima Sasanao Anago Don", summary_zh: "**松島あなご丼松島佐々直は 1908 創業 117 年**(R3 食 松島あなご派生)。蒸あなご丼 ¥2,200-3,500、R1 育 松島観光客代表、仙台駅売店+通販。", content_md: "- 立地:**宮城郡松島町**\n- 起源:**1908 創業 117 年**\n- 関係:**R3 食 松島あなご派生**\n- 看板:**蒸あなご丼 ¥2,200-3,500**\n- 流通:**仙台駅売店 + 通販**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "松島町", lg_code: "04401", area_types: ["restaurant_traditional"], lat: 38.3742, lon: 141.0589, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["sasanao_anago_don", "1908", "117_years"], source: "manual" },
  { slug: "miyagi-kakuda-strawberry", category: "food", sub_type: "miyagi_fruit", title_zh: "角田いちご(角田市・R1 食 亘理いちごと並ぶ宮城南部いちご産地+ 1990 年代開発+ もういっこ・とちおとめ品種+ 12-5 月狩り+ 道の駅 + 仙台駅売店+ R2 楽 角田宇宙センター 観光と組合せ)", title_ja: "角田いちご", romaji: "Kakuda Ichigo", summary_zh: "**角田いちごは宮城南部いちご産地**(角田市・**1990 年代開発+もういっこ・とちおとめ**)。R1 食 亘理いちごと並ぶ、12-5 月、道の駅、R2 楽 宇宙センター観光組合せ。", content_md: "- 立地:**角田市**\n- 起源:**1990 年代開発**\n- 種:**もういっこ + とちおとめ**\n- 期:**12-5 月狩り**\n- 並列:**R1 食 亘理いちご + R5 食 角田いちご = 宮城南部いちご 2 大**\n- 並列観光:**R2 楽 角田宇宙センター**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "角田市", lg_code: "04207", area_types: ["farm_field"], lat: 37.9628, lon: 140.7783, season_start: "2026-12-01", season_end: "2027-05-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kakuda_ichigo", "1990s"], source: "manual" },

  // 住 (3)
  { slug: "sakunami-yokoyu", category: "lodging", sub_type: "miyagi_sakunami_onsen", title_zh: "ゆづくしの宿 一の坊作並温泉(仙台市青葉区作並・1985 開業+ 全 95 室+ R1 住 作並温泉郷代表大型旅館・R1 住 岩松 1796 と並ぶ+ 露天風呂 24h 利用+ 1 泊 2 食 ¥21,500-32,000+ 仙台都心 40 分)", title_ja: "ゆづくしの宿 一の坊作並", romaji: "Yuzukushi Ichinobo Sakunami", summary_zh: "**ゆづくしの宿一の坊作並は作並温泉郷代表**(仙台市・**1985 開業+全 95 室**)。R1 住 岩松 1796 と並ぶ、露天 24h 利用、¥21,500-32,000、仙台都心 40 分。", content_md: "- 立地:**仙台市青葉区作並**(R1 住 作並温泉郷)\n- 起源:**1985 開業 40 年**\n- 規模:**全 95 室**\n- 並列:**R1 住 岩松 1796 + R5 住 ゆづくし = 作並温泉 2 大老舗**\n- 看板:**露天風呂 24h 利用**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["onsen_field"], lat: 38.3447, lon: 140.6711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["yuzukushi_ichinobo", "1985", "95_rooms"], source: "manual" },
  { slug: "kesennuma-recovery-hotel", category: "lodging", sub_type: "miyagi_other_onsen", title_zh: "気仙沼スリープイン気仙沼+復興ホテル(気仙沼市・2014 開業 復興期+ 全 98 室+ R1 育 気仙沼港+R1 食 気仙沼ふかひれ+ 1 泊朝食付 ¥7,500-11,500+ R1 楽 気仙沼みなとまつり 観光客向け価格手頃)", title_ja: "気仙沼スリープイン", romaji: "Kesennuma Sleep Inn", summary_zh: "**気仙沼スリープインは 2014 開業復興期**(全 98 室・¥7,500-11,500)。R1 食 ふかひれ+R4 楽 みなとまつり観光、価格手頃。", content_md: "- 立地:**気仙沼市**\n- 起源:**2014 開業 復興期**\n- 規模:**全 98 室**\n- 並列観光:**R1 食 気仙沼ふかひれ + R4 楽 気仙沼みなとまつり**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "気仙沼市", lg_code: "04203", area_types: ["shopping_district"], lat: 38.9069, lon: 141.5703, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["kesennuma_sleep_inn", "2014_recovery"], source: "manual" },
  { slug: "shiroishi-zao-ranch-pension", category: "lodging", sub_type: "miyagi_other_onsen", title_zh: "蔵王ペンション村+グランピング(刈田郡蔵王町・1990 年代開設+ 全 8 軒ペンション・牧場併設+ R1 楽 蔵王御釜+R1 楽 きつね村 拠点+ 1 泊 2 食 ¥11,500-18,500+ ファミリー向け)", title_ja: "蔵王ペンション村", romaji: "Zaō Pension Mura", summary_zh: "**蔵王ペンション村は 1990 年代開設**(蔵王町・**全 8 軒+牧場併設**)。R1 楽 御釜+きつね村拠点、¥11,500-18,500、ファミリー向け。", content_md: "- 立地:**刈田郡蔵王町**\n- 起源:**1990 年代開設**\n- 規模:**全 8 軒・牧場併設**\n- 並列観光:**R1 楽 蔵王御釜 + きつね村 + エコーライン + みやぎ蔵王スキー**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "刈田郡", municipality_ja: "蔵王町", lg_code: "04301", area_types: ["onsen_field", "mountain_village"], lat: 38.1306, lon: 140.5550, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["zao_pension", "1990s", "ranch"], source: "manual" },

  // 衣 (3)
  { slug: "yamada-glasses-sendai", category: "fashion", sub_type: "miyagi_dept_store", title_zh: "山田眼鏡(仙台市青葉区一番町・1924 創業 101 年+ 県内最古眼鏡店+ R1 衣 藤崎 1819 + 三越 1933 と並ぶ仙台老舗+ 高級フレーム+検眼+ 観光客向け代表専門店)", title_ja: "山田眼鏡", romaji: "Yamada Megane", summary_zh: "**山田眼鏡は県内最古眼鏡店・1924 創業 101 年**(仙台市・**R1 衣 藤崎 1819+三越 1933 と並ぶ仙台老舗**)。高級フレーム+検眼。", content_md: "- 立地:**仙台市青葉区一番町**\n- 起源:**1924 創業 101 年**\n- 認定:**県内最古眼鏡店**\n- 並列:**R1 衣 藤崎 1819 + 三越 1933 + R5 衣 山田眼鏡 1924 = 仙台老舗 3 大**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["shopping_district"], lat: 38.2625, lon: 140.8722, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yamada_megane", "1924", "101_years"], source: "manual" },
  { slug: "ishinomaki-kawarayaki-craft", category: "fashion", sub_type: "miyagi_folk_craft", title_zh: "雄勝硯(石巻市雄勝・1240 鎌倉期発祥 785 年+ 国指定伝統的工芸品 1985+ 全国 5 大硯石(玄昌+赤間+雨畑+龍渓+雄勝)・宮城代表+ 黒色細密石材+ 工芸品店流通+ ¥3,500-25,000)", title_ja: "雄勝硯", romaji: "Ogatsu Suzuri", summary_zh: "**雄勝硯は 1240 鎌倉期 785 年・国指定伝統的工芸品 1985**(石巻市雄勝・**全国 5 大硯石**)。秋田 R4 衣 雄勝石(湯沢)と同名異物、宮城代表書道用、¥3,500-25,000。", content_md: "- 立地:**石巻市雄勝**\n- 起源:**1240 鎌倉期発祥 785 年**\n- 認定:**国指定伝統的工芸品 1985**\n- 並列:**全国 5 大硯石**(玄昌 + 赤間 + 雨畑 + 龍渓 + 雄勝)\n- 価格:**¥3,500-25,000**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "石巻市", lg_code: "04201", area_types: ["craft_workshop", "industrial_heritage"], lat: 38.4344, lon: 141.3033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ogatsu_suzuri", "1240_kamakura", "1985_dento"], source: "manual" },
  { slug: "miyagi-character-mascot-musubimaru", category: "fashion", sub_type: "miyagi_folk_craft", title_zh: "むすび丸関連グッズ+ ベガッ太(ベガルタ仙台マスコット)+ クリン(楽天イーグルスマスコット)(全域・県観光 PR + プロスポーツマスコット+ ぬいぐるみ+T シャツ+ ¥800-3,500+ R1 衣 ご当地キャラ派生)", title_ja: "むすび丸+ベガッ太+クリン", romaji: "Musubi Maru / Vegata / Clutch", summary_zh: "**むすび丸+ベガッ太+クリンは県観光+プロスポーツマスコット**(R1 衣 ご当地キャラ派生)。ぬいぐるみ+T シャツ、¥800-3,500。", content_md: "- 構成:**むすび丸(R1 衣 県観光 PR) + ベガッ太(R4 楽 ベガルタ) + クリン(R1 楽 楽天)**\n- 価格:**¥800-3,500**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["shopping_district"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["musubi_maru", "vegata", "clutch"], source: "manual" },

  // 育 (4)
  { slug: "matsushima-saigyou-modoshi-no-matsu", category: "culture", sub_type: "miyagi_matsushima", title_zh: "西行戻しの松公園(松島町・「西行戻しの松」鎌倉期歌人西行 1118-1190 ゆかり+ R1 育 松島湾眺望ポイント・松島四大観 R2 派生+ 入場無料+ 4 月桜名所+ 西行歌碑「ながむれば 心もしのに 我が思う 今日や昔の 春なるらん」)", title_ja: "西行戻しの松公園", romaji: "Saigyō Modoshi no Matsu", summary_zh: "**西行戻しの松は鎌倉期歌人西行ゆかり**(松島町・**R1 育 松島湾眺望ポイント**)。R2 育 松島四大観派生、4 月桜、無料、西行歌碑。", content_md: "- 立地:**宮城郡松島町**\n- 縁:**鎌倉期歌人西行 1118-1190 ゆかり**\n- 並列:**R1 育 松島 + R2 育 松島四大観派生**\n- 期:**4 月桜名所**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "松島町", lg_code: "04401", area_types: ["scenic_spot", "shrine_temple"], lat: 38.3742, lon: 141.0589, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["saigyo_modoshi", "kamakura_saigyo"], source: "manual" },
  { slug: "sendai-kokoro-jidai", category: "culture", sub_type: "miyagi_modern_art", title_zh: "宮城こけし館(大崎市鳴子温泉+ R1 衣 鳴子こけし派生施設・1975 開館 50 年+ 全国 11 系統こけし 5,000+ 体展示+ 鳴子+遠刈田+作並 + R1 衣 全国系統+ 入館 ¥400+ R1 楽 鳴子峡+R1 住 鳴子温泉郷拠点)", title_ja: "宮城こけし館", romaji: "Miyagi Kokeshi Kan", summary_zh: "**宮城こけし館は R1 衣 鳴子こけし派生施設**(大崎市・**1975 開館+全国 11 系統 5,000+ 体**)。鳴子+遠刈田+作並 R1 衣、入館 ¥400、R1 住+R1 楽 鳴子拠点。", content_md: "- 立地:**大崎市鳴子温泉**\n- 起源:**1975 開館 50 年**\n- 規模:**全国 11 系統こけし 5,000+ 体展示**\n- 関連:**R1 衣 鳴子+遠刈田+作並こけし**\n- 入館:**¥400**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "大崎市", lg_code: "04213", area_types: ["museum_art", "craft_workshop"], lat: 38.7375, lon: 140.7250, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["木"], external_urls: {}, tags: ["miyagi_kokeshi_kan", "1975", "5000_kokeshi"], source: "manual" },
  { slug: "yokota-jinja-natori", category: "culture", sub_type: "miyagi_shrine_temple", title_zh: "熊野神社(名取熊野三社)(名取市・1085 平安期 後三年の役・源義家奥州下向期創建+ 全国熊野神社東日本最大規模+ 本宮 + 新宮 + 那智の滝・3 社並立+ 県重要文化財+ 入場無料)", title_ja: "名取熊野三社", romaji: "Natori Kumano Sansha", summary_zh: "**名取熊野三社は 1085 平安期 源義家奥州下向創建**(名取市・**全国熊野神社東日本最大規模**)。**本宮+新宮+那智 3 社並立**、県重要文化財、無料。", content_md: "- 立地:**名取市**\n- 起源:**1085 平安期 源義家奥州下向期**\n- 構成:**本宮 + 新宮 + 那智の滝(3 社並立)**\n- 認定:**全国熊野神社東日本最大規模 + 県重要文化財**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "名取市", lg_code: "04206", area_types: ["shrine_temple"], lat: 38.1719, lon: 140.8917, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["natori_kumano_sansha", "1085_minamoto_yoshiie"], source: "manual" },
  { slug: "shichigahama-asuka-museum", category: "culture", sub_type: "miyagi_history_museum", title_zh: "七ヶ浜国際村(宮城郡七ヶ浜町・1996 開館 国際交流文化施設+ 大ホール 600 席+ ギャラリー+カフェ+ 海浜公園併設+ R4 食 七ヶ浜しらす+R1 育 多賀城跡 観光と組合せ+ 入館無料・コンサート ¥3,000-)", title_ja: "七ヶ浜国際村", romaji: "Shichigahama Kokusai Mura", summary_zh: "**七ヶ浜国際村は 1996 開館国際交流文化施設**(七ヶ浜町・**大ホール 600 席+海浜公園併設**)。R4 食 しらす+R1 育 多賀城跡組合せ、無料・コンサート ¥3,000-。", content_md: "- 立地:**宮城郡七ヶ浜町**\n- 起源:**1996 開館**\n- 構成:**大ホール 600 席 + ギャラリー + カフェ + 海浜公園併設**\n- 並列:**R4 食 七ヶ浜しらす + R1 育 多賀城跡**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "七ヶ浜町", lg_code: "04404", area_types: ["museum_art", "scenic_spot"], lat: 38.2933, lon: 141.0531, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["shichigahama_kokusaimura", "1996", "600_hall"], source: "manual" },

  // 楽 (4)
  { slug: "matsushima-tanabata-festival", category: "entertainment", sub_type: "miyagi_matsushima", title_zh: "松島流灯会海の盆(松島町・1953 開始 72 年+ 8 月 15-16 日盆迎え+ 燈籠流し+花火+ R1 育 松島湾沿岸+ R1 食 松島牡蠣ライブ併催+ 観覧無料+ 観光客 5 万人来場+ 三陸代表夏祭)", title_ja: "松島流灯会 海の盆", romaji: "Matsushima Ryūtōe Umi no Bon", summary_zh: "**松島流灯会海の盆は 1953 開始 72 年**(松島町・**8 月 15-16 日盆迎え+燈籠流し+花火**)。観覧無料、5 万人来場、三陸代表夏祭。", content_md: "- 立地:**宮城郡松島町**\n- 起源:**1953 開始 72 年**\n- 期:**毎年 8 月 15-16 日(盆迎え)**\n- 構成:**燈籠流し + 花火**\n- 来場:**5 万人**\n- 観覧:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "松島町", lg_code: "04401", area_types: ["festival_event"], lat: 38.3742, lon: 141.0589, season_start: null, season_end: null, event_start: "2026-08-15", event_end: "2026-08-16", price_tier: 1, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["matsushima_ryutoe", "1953", "obon"], source: "manual" },
  { slug: "kesennuma-iruka-watching", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "気仙沼イルカウォッチング(気仙沼市・三陸沿岸+ 1995 開始+ 5-9 月運航+ 90 分 ¥6,000+ ハナゴンドウ+カマイルカ群れ観察+ R1 食 気仙沼ふかひれ + R4 楽 気仙沼みなとまつり 観光客向け体験型)", title_ja: "気仙沼イルカウォッチング", romaji: "Kesennuma Iruka Watching", summary_zh: "**気仙沼イルカウォッチングは 1995 開始**(三陸沿岸・**5-9 月運航 90 分 ¥6,000**)。ハナゴンドウ+カマイルカ群、R1 食 ふかひれ+R4 楽 みなとまつり観光。", content_md: "- 立地:**気仙沼市**\n- 起源:**1995 開始**\n- 期:**5-9 月運航・90 分 ¥6,000**\n- 看板:**ハナゴンドウ + カマイルカ群れ観察**\n- 並列:**R1 食 気仙沼ふかひれ + R4 楽 みなとまつり**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "気仙沼市", lg_code: "04203", area_types: ["scenic_spot"], lat: 38.9069, lon: 141.5703, season_start: "2026-05-01", season_end: "2026-09-30", event_start: null, event_end: null, price_tier: 3, booking_window_days: 14, closed_days: [], external_urls: {}, tags: ["kesennuma_iruka", "1995", "dolphins"], source: "manual" },
  { slug: "matsushima-fukurajima-bridge", category: "entertainment", sub_type: "miyagi_matsushima", title_zh: "福浦島+渡月橋(松島町・赤い渡月橋 252m 大橋+ R1 育 松島湾島巡り徒歩可能 福浦島散策+ R1 食 松島牡蠣茶屋併設+ 渡橋料 ¥200+ 観光客必訪+ 朱色橋松島代表景観)", title_ja: "福浦島+渡月橋", romaji: "Fukurajima / Tozukyō Bridge", summary_zh: "**福浦島+渡月橋は赤い 252m 大橋**(松島町・**R1 育 松島湾徒歩散策**)。R1 食 牡蠣茶屋併設、渡橋料 ¥200、朱色橋松島代表景観。", content_md: "- 立地:**宮城郡松島町**\n- 規模:**渡月橋 252m**\n- 並列:**R1 育 松島湾島巡り徒歩可能**\n- 渡橋料:**¥200**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "松島町", lg_code: "04401", area_types: ["scenic_spot"], lat: 38.3742, lon: 141.0589, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["fukurajima", "tozukyo_252m"], source: "manual" },
  { slug: "ishinomaki-port-festival", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "石巻川開き祭り(石巻市・1916 開始 109 年+ 7 月最終週末+ 北上川河畔会場+ 川面パレード+花火+ R1 育 石ノ森萬画館+R3 楽 日和山公園 観光と組合せ+ 観覧無料+ 来場 50 万人+ 県南部夏祭代表)", title_ja: "石巻川開き祭り", romaji: "Ishinomaki Kawabiraki", summary_zh: "**石巻川開き祭りは 1916 開始 109 年**(石巻市・**7 月最終週末+北上川河畔**)。川面パレード+花火、観覧無料、50 万人、県南部夏祭代表。", content_md: "- 立地:**石巻市・北上川河畔**\n- 起源:**1916 開始 109 年**\n- 期:**毎年 7 月最終週末**\n- 構成:**川面パレード + 花火**\n- 来場:**50 万人**\n- 観覧:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "石巻市", lg_code: "04201", area_types: ["festival_event"], lat: 38.4344, lon: 141.3033, season_start: null, season_end: null, event_start: "2026-07-26", event_end: "2026-07-27", price_tier: 1, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["ishinomaki_kawabiraki", "1916", "109_years"], source: "manual" },

  // 行 (2)
  { slug: "loop-le-sendai-bus", category: "transport", sub_type: "miyagi_bus", title_zh: "るーぷる仙台 観光バス(仙台市・1996 開始+ 仙台駅西 ↔ 青葉城 ↔ 大崎八幡 ↔ 八木山動物公園 周遊+ 1 周 約 70 分・1 日券 ¥630+ 主要観光地ピンポイントカバー+ R1 楽 仙台観光客向け代表)", title_ja: "るーぷる仙台 観光バス", romaji: "Loople Sendai", summary_zh: "**るーぷる仙台は 1996 開始仙台観光周遊バス**(R1 育 仙台城跡+R1 育 大崎八幡+R1 楽 八木山動物 周遊)。1 周 70 分、1 日券 ¥630、観光客代表。", content_md: "- 区間:**仙台駅西口 ↔ 仙台城跡 ↔ 大崎八幡 ↔ 八木山動物公園**\n- 起源:**1996 開始**\n- 1 周:**約 70 分**\n- 料金:**1 日券 ¥630**\n- 並列観光:**R1 育 仙台城+大崎八幡+メディアテーク + R1 楽 八木山動物公園**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["transit_hub"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: { official: "https://www.kotsu.city.sendai.jp/loople/" }, tags: ["loople_sendai", "1996", "70min", "630yen"], source: "manual" },
  { slug: "marugoto-pass-miyagi", category: "transport", sub_type: "miyagi_pass_ticket", title_zh: "宮城まるごとパス(JR 東日本+宮城交通+秋保バス共通券・2 日 ¥3,300+ R1 行 JR 仙石線+東北本線+陸羽東線 + バス全線+ R4 行 JR EAST PASS Tohoku+ R4 行 松島・塩釜エリアパス と並ぶ宮城観光パス 3 大)", title_ja: "宮城まるごとパス", romaji: "Miyagi Marugoto Pass", summary_zh: "**宮城まるごとパスは 2 日 ¥3,300**(JR+宮城交通+秋保バス共通)。R1 行 JR 仙石+東北本線+陸羽東線+バス全線、R4 行 JR EAST PASS+R4 行 松島塩釜と並ぶ宮城観光パス 3 大。", content_md: "- 対象:**JR 東日本(宮城エリア) + 宮城交通 + 秋保バス**\n- 期:**2 日連続使用**\n- 料金:**¥3,300**\n- 並列:**R4 行 JR EAST PASS Tohoku + R4 行 松島塩釜エリアパス + R5 行 宮城まるごとパス = 宮城観光パス 3 大**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["transit_hub"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["miyagi_marugoto", "2_days", "3300yen"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[miyagi-r5] 尚無條目"); return; }
  console.log(`[miyagi-r5] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[miyagi-r5] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[miyagi-r5] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[miyagi-r5] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
