// Seed 徳島県 行 R1(19 筆 / Sprint 1.6 / 第十六卷)
// JR 4 / 私鉄 2 / ターミナル 2 / 道路 3 / 港 2 / 空港 1 / バス 3 / ロープ+その他 2 = 19
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  {
    slug: "jr-tokushima-station-1899",
    category: "transport", sub_type: "tokushima_terminal",
    title_zh: "JR 徳島駅+ ターミナル(徳島市寺島本町・1899 明治 32 年徳島鉄道開業 126+ 年+ JR 高徳線+牟岐線+徳島線+鳴門線 4 路線結節+ 1 日 3 万人乗降+ R1 行 ことでん徳島駅併設・国際 SNS 海外旅行者代表)",
    title_ja: "JR 徳島駅", romaji: "JR Tokushima Station",
    summary_zh: "**JR 徳島駅は 1899 徳島鉄道開業 126+ 年・JR 高徳+牟岐+徳島+鳴門 4 路線結節・1 日 3 万人乗降**(徳島寺島)。",
    content_md: "- 立地:**徳島市寺島本町**\n- 起源:**1899 明治 32 年徳島鉄道開業 126+ 年**\n- 規模:**4 路線結節 + 1 日 3 万人乗降**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_tokushima_1899"], source: "manual",
  },
  {
    slug: "jr-kotoku-line-tokushima",
    category: "transport", sub_type: "tokushima_jr",
    title_zh: "JR 高徳線(高松-徳島・1935 全通 90+ 年+ R1 行 香川 派生・高松-徳島 74.5km・25 駅+「うずしお」特急 1996 運行・¥1,000-1,520/片道+ JR Pass 全外国人 free+ 鳴門線分岐(池谷-鳴門)・¥150-1,520/片道)",
    title_ja: "JR 高徳線", romaji: "JR Kōtoku",
    summary_zh: "**JR 高徳線は 1935 全通 90+ 年・R1 行 香川派生・高松-徳島 74.5km+25 駅・「うずしお」特急 1996+鳴門線分岐**(高松-徳島)。¥150-1,520/片道、JR Pass 可。",
    content_md: "- 起源:**1935 全通 90+ 年**\n- 関連:**R1 行 香川派生 + 鳴門線分岐(池谷-鳴門)**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_kotoku_tokushima"], source: "manual",
  },
  {
    slug: "jr-mugi-line",
    category: "transport", sub_type: "tokushima_jr",
    title_zh: "JR 牟岐線(徳島-阿波海南・1937 全通 88+ 年+ 徳島-海部郡阿波海南 78.5km・25 駅+ 阿南+ 牟岐+ 海陽+ 美波経由+ R1 育 薬王寺 815 第 23 番アクセス+ 「むろと」特急・¥150-2,310/片道)",
    title_ja: "JR 牟岐線", romaji: "JR Mugi",
    summary_zh: "**JR 牟岐線は 1937 全通 88+ 年・徳島-阿波海南 78.5km+25 駅・阿南+牟岐+海陽+美波経由・R1 育 薬王寺 815 第 23 番アクセス**(徳島-阿波海南)。¥150-2,310/片道。",
    content_md: "- 起源:**1937 全通 88+ 年**\n- 規模:**徳島-海部郡阿波海南 78.5km + 25 駅 + 阿南 + 牟岐 + 海陽 + 美波経由**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_mugi_1937"], source: "manual",
  },
  {
    slug: "jr-tokushima-line",
    category: "transport", sub_type: "tokushima_jr",
    title_zh: "JR 徳島線(徳島-阿波池田・1914 全通 111+ 年+ 徳島-阿波池田 67.5km・27 駅+ 吉野川中流域並行+ 美馬+つるぎ+ 三好経由+ R1 育 阿波国分寺 第 15 番派生+ 「剣山」特急 1986 運行・¥150-1,520/片道)",
    title_ja: "JR 徳島線", romaji: "JR Tokushima Line",
    summary_zh: "**JR 徳島線は 1914 全通 111+ 年・徳島-阿波池田 67.5km+27 駅・吉野川中流並行・美馬+つるぎ+三好経由・「剣山」特急 1986**(徳島-阿波池田)。¥150-1,520/片道。",
    content_md: "- 起源:**1914 全通 111+ 年**\n- 規模:**徳島-阿波池田 67.5km + 27 駅 + 吉野川中流域並行**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_tokushima_line_1914"], source: "manual",
  },
  {
    slug: "asakaigan-railway-1992",
    category: "transport", sub_type: "tokushima_private_railway",
    title_zh: "阿佐海岸鉄道+ DMV(海部郡海陽町阿波海南-高知県東洋町甲浦・1992 開業 33+ 年+ 阿波海南-甲浦 8.5km・3 駅+ 2020 全国初 DMV(デュアル・モード・ビークル)導入+ JR 牟岐線阿波海南乗換+ ¥510/片道)",
    title_ja: "阿佐海岸鉄道", romaji: "Asakaigan Railway",
    summary_zh: "**阿佐海岸鉄道+DMV は 1992 開業 33+ 年・阿波海南-甲浦 8.5km+3 駅・2020 全国初 DMV 導入・JR 牟岐線乗換**(海陽-高知東洋)。¥510/片道。",
    content_md: "- 立地:**海部郡海陽町阿波海南 - 高知県東洋町甲浦**\n- 起源:**1992 開業 33+ 年**\n- 認定:**2020 全国初 DMV(デュアル・モード・ビークル)導入**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "海部郡", municipality_ja: "海陽町", lg_code: "36388",
    area_types: ["transport_hub"], lat: 33.5333, lon: 134.3000,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["asakaigan_1992", "dmv_2020"], source: "manual",
  },
  {
    slug: "jr-naruto-line-1916",
    category: "transport", sub_type: "tokushima_jr",
    title_zh: "JR 鳴門線(池谷-鳴門・1916 全通 109+ 年+ 池谷-鳴門 8.5km・5 駅+ JR 高徳線分岐・R1 行 大鳴門橋アクセス+ R1 育 鳴門の渦+大塚国際美術館アクセス・¥210/片道)",
    title_ja: "JR 鳴門線", romaji: "JR Naruto Line",
    summary_zh: "**JR 鳴門線は 1916 全通 109+ 年・池谷-鳴門 8.5km+5 駅・高徳線分岐・R1 行 大鳴門橋+R1 育 鳴門の渦+大塚国際美術館アクセス**(池谷-鳴門)。¥210/片道。",
    content_md: "- 起源:**1916 全通 109+ 年**\n- 規模:**池谷-鳴門 8.5km + 5 駅 + JR 高徳線分岐**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202",
    area_types: ["transport_hub"], lat: 34.1722, lon: 134.6086,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_naruto_1916"], source: "manual",
  },
  {
    slug: "jr-awa-ikeda-station",
    category: "transport", sub_type: "tokushima_terminal",
    title_zh: "JR 阿波池田駅(三好市池田町・1914 開業 111+ 年+ JR 徳島線+土讃線分岐ターミナル+ R1 育 大歩危・小歩危アクセス+ R1 育 祖谷渓+剣山アクセス+ 1 日 3000 人乗降+ ¥150-1,520/片道+ 国際 SNS 海外旅行者代表)",
    title_ja: "JR 阿波池田駅", romaji: "JR Awa-Ikeda",
    summary_zh: "**JR 阿波池田駅は 1914 開業 111+ 年・JR 徳島+土讃線分岐ターミナル・R1 育 大歩危+祖谷+剣山アクセス・1 日 3000 人乗降**(三好池田)。¥150-1,520/片道、海外代表。",
    content_md: "- 立地:**三好市池田町**\n- 起源:**1914 開業 111+ 年**\n- 規模:**JR 徳島線 + 土讃線分岐ターミナル**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208",
    area_types: ["transport_hub"], lat: 33.8728, lon: 133.8019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["awa_ikeda_station_1914"], source: "manual",
  },
  {
    slug: "tokushima-airport-1959",
    category: "transport", sub_type: "tokushima_airport",
    title_zh: "徳島阿波踊り空港(松茂町豊岡・1959 開港 66+ 年+ 2010 「徳島阿波踊り空港」改称・全国唯一の踊り名空港+ 国内羽田+福岡+札幌就航+ R1 衣 阿波踊り 1981 派生・1 日 25 便+ R1 食 すだちくん空港+ 全県マスコット代表)",
    title_ja: "徳島阿波踊り空港", romaji: "Tokushima Awa Odori Airport",
    summary_zh: "**徳島阿波踊り空港は 1959 開港 66+ 年・2010 改称・全国唯一の踊り名空港・国内羽田+福岡+札幌・1 日 25 便**(松茂豊岡)。R1 衣 1981 派生、すだちくん代表。",
    content_md: "- 立地:**板野郡松茂町豊岡**\n- 起源:**1959 開港 66+ 年 + 2010 「徳島阿波踊り空港」改称**\n- 認定:**全国唯一の踊り名空港**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "板野郡", municipality_ja: "松茂町", lg_code: "36404",
    area_types: ["transport_hub"], lat: 34.1325, lon: 134.6064,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tokushima_airport_1959"], source: "manual",
  },
  {
    slug: "naruto-ohashi-1985",
    category: "transport", sub_type: "tokushima_kosoku",
    title_zh: "大鳴門橋(鳴門市鳴門町+ 兵庫県南あわじ・1985 開通 40+ 年+ R1 育 鳴門の渦上を跨ぐ橋・全長 1629m+ 自動車道+ R5 育 渦の道 2000 (鉄道計画は中止)+ 神戸淡路鳴門自動車道一部・通行料 ¥6,330/片道(普通車))",
    title_ja: "大鳴門橋", romaji: "Naruto Ohashi",
    summary_zh: "**大鳴門橋は 1985 開通 40+ 年・R1 育 鳴門の渦上を跨ぐ橋・全長 1629m・自動車道・R5 育 渦の道 2000・神戸淡路鳴門自動車道一部**(鳴門+南あわじ)。¥6,330/片道。",
    content_md: "- 起源:**1985 開通 40+ 年**\n- 関連:**R1 育 鳴門の渦上を跨ぐ橋 + R5 育 渦の道 2000**\n- 認定:**全長 1629m + 神戸淡路鳴門自動車道一部**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202",
    area_types: ["transport_hub"], lat: 34.2497, lon: 134.6486,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["naruto_ohashi_1985"], source: "manual",
  },
  {
    slug: "tokushima-jidoshado",
    category: "transport", sub_type: "tokushima_kosoku",
    title_zh: "徳島自動車道+ 高松自動車道(全県+ 香川・1990 徳島自動車道部分開通 35+ 年+ R1 行 香川 高松自動車道 1992 連動・鳴門 IC-阿波池田 IC 87km+ R1 育 大歩危+祖谷+剣山アクセス・通行料 ¥520-3,500)",
    title_ja: "徳島自動車道", romaji: "Tokushima Expressway",
    summary_zh: "**徳島自動車道+高松自動車道は 1990 部分開通 35+ 年・R1 行 香川 1992 連動・鳴門-阿波池田 87km・R1 育 大歩危+祖谷+剣山アクセス**(全県+香川)。¥520-3,500。",
    content_md: "- 起源:**1990 徳島自動車道部分開通 35+ 年**\n- 関連:**R1 行 香川 高松自動車道 1992 連動**\n- 規模:**鳴門 IC-阿波池田 IC 87km**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tokushima_jidoshado_1990"], source: "manual",
  },
  {
    slug: "kobe-awaji-naruto-jido",
    category: "transport", sub_type: "tokushima_kosoku",
    title_zh: "神戸淡路鳴門自動車道(全県+ 兵庫淡路+ 神戸・1998 全線開通 27+ 年+ R1 行 大鳴門橋 1985+ 1998 明石海峡大橋・本州-淡路-四国直結高速道路+ 神戸-鳴門 89km・通行料 ¥6,330)",
    title_ja: "神戸淡路鳴門自動車道", romaji: "Kobe Awaji Naruto",
    summary_zh: "**神戸淡路鳴門自動車道は 1998 全線開通 27+ 年・R1 行 大鳴門橋+1998 明石海峡大橋・本州-淡路-四国直結・神戸-鳴門 89km**(全県+兵庫+神戸)。¥6,330。",
    content_md: "- 起源:**1998 全線開通 27+ 年**\n- 関連:**R1 行 大鳴門橋 1985 + 1998 明石海峡大橋**\n- 規模:**神戸-鳴門 89km**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202",
    area_types: ["transport_hub"], lat: 34.2497, lon: 134.6486,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kobe_awaji_naruto_1998"], source: "manual",
  },
  {
    slug: "tokushima-port",
    category: "transport", sub_type: "tokushima_terminal",
    title_zh: "徳島港+ 鳴門港+ 海部宍喰港(徳島市津田+ 鳴門+ 海部宍喰・古来から国際港+ 1885 徳島港県港指定 140+ 年+ 南海フェリー徳島-和歌山 1932 開航 93+ 年+ 鳴門港+ 宍喰港 R1 食 海部漁港派生・¥0-2,500)",
    title_ja: "徳島港+鳴門港", romaji: "Tokushima Naruto Port",
    summary_zh: "**徳島港+鳴門港+海部宍喰港は古来から+1885 徳島港県港指定 140+ 年・南海フェリー 1932 93+ 年・鳴門港+R1 食 海部漁港派生**(徳島津田+鳴門+海部宍喰)。¥0-2,500。",
    content_md: "- 立地:**徳島市津田 + 鳴門市 + 海部郡宍喰**\n- 起源:**古来から国際港 + 1885 徳島港県港指定 140+ 年**\n- 関連:**南海フェリー徳島-和歌山 1932 開航 93+ 年**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tokushima_naruto_port"], source: "manual",
  },
  {
    slug: "nankai-ferry-1932",
    category: "transport", sub_type: "tokushima_kosoku",
    title_zh: "南海フェリー(徳島港-和歌山港・1932 開航 93+ 年+ 全国老舗フェリー候補・徳島-和歌山 55km・2 時間+ 1 日 8 便+ 阪神圏-四国アクセス重要+ ¥2,500/片道+ R1 行 大鳴門橋 1985 並ぶ阪神四国経路)",
    title_ja: "南海フェリー", romaji: "Nankai Ferry",
    summary_zh: "**南海フェリーは 1932 開航 93+ 年・全国老舗フェリー候補・徳島-和歌山 55km・2 時間+1 日 8 便・阪神-四国アクセス重要**(徳島-和歌山)。¥2,500/片道、R1 行 大鳴門並ぶ。",
    content_md: "- 起源:**1932 開航 93+ 年**\n- 認定:**全国老舗フェリー候補 + 徳島-和歌山 55km + 2 時間 + 1 日 8 便**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["nankai_ferry_1932"], source: "manual",
  },
  {
    slug: "tokushima-bus-1924",
    category: "transport", sub_type: "tokushima_subway",
    title_zh: "徳島バス+ 鳴門バス+ ことでんバス(全県・1924 徳島バス創業 101+ 年+ 鳴門市バス 1955+ 全県 200+ 路線+ 1 日 5 万人乗降・¥220-1,500/片道+ 国内出張+観光客代表)",
    title_ja: "徳島バス", romaji: "Tokushima Bus",
    summary_zh: "**徳島バス+鳴門バス+ことでんバスは 1924 徳島バス 101+ 年+鳴門 1955・全県 200+ 路線・1 日 5 万人乗降**(全県)。¥220-1,500/片道。",
    content_md: "- 立地:**徳島県全域**\n- 起源:**1924 徳島バス創業 101+ 年 + 鳴門市バス 1955**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tokushima_bus_1924"], source: "manual",
  },
  {
    slug: "tokushima-route-11-55",
    category: "transport", sub_type: "tokushima_kosoku",
    title_zh: "国道 11 号+ 国道 55 号(全県・国道 11 号 1885 国道指定 140+ 年(徳島-香川-愛媛-広島)+ 国道 55 号 1953 国道指定 72+ 年(徳島-高知)・徳島県縦断幹線+ R1 行 高徳線+牟岐線並行・通行料無料)",
    title_ja: "国道 11+55 号", romaji: "Route 11+55",
    summary_zh: "**国道 11 号+55 号は 11 号 1885 140+ 年(徳島-香川-愛媛-広島)+55 号 1953 72+ 年(徳島-高知)・徳島県縦断幹線**(全県)。R1 行 高徳+牟岐並行、無料。",
    content_md: "- 起源:**国道 11 号 1885 国道指定 140+ 年 + 国道 55 号 1953 国道指定 72+ 年**\n- 規模:**徳島県縦断幹線 + R1 行 高徳線 + 牟岐線並行**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["route_11_55"], source: "manual",
  },
  {
    slug: "kaiyo-mugi-bus",
    category: "transport", sub_type: "tokushima_nanbu_transport",
    title_zh: "海陽+ 牟岐+ 美波コミュニティバス(海部郡海陽+牟岐+美波・R1 行 JR 牟岐線派生・1990 年代以降コミュニティバス 35+ 年+ 4 路線+ 海部漁港アクセス+ R1 楽 大浜海岸+うみがめ博物館アクセス・¥190-450/片道)",
    title_ja: "海陽コミュニティバス", romaji: "Kaiyo Bus",
    summary_zh: "**海陽+牟岐+美波コミュニティバスは R1 行 JR 牟岐派生・1990 年代以降 35+ 年・4 路線+海部漁港アクセス+R1 楽 大浜海岸+うみがめ博物館**(海陽+牟岐+美波)。¥190-450/片道。",
    content_md: "- 立地:**海部郡海陽町 + 牟岐町 + 美波町**\n- 関連:**R1 行 JR 牟岐線派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "海部郡", municipality_ja: "海陽町", lg_code: "36388",
    area_types: ["transport_hub"], lat: 33.5333, lon: 134.3000,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kaiyo_community_bus"], source: "manual",
  },
  {
    slug: "naka-katsuura-bus",
    category: "transport", sub_type: "tokushima_nanbu_transport",
    title_zh: "那賀+ 勝浦+ 上勝コミュニティバス(那賀町+勝浦+上勝・R1 衣 上勝ゼロウェイスト 2003 派生・1990 年代以降コミュニティバス 35+ 年+ 山中集落結節+ R1 食 阿波太布+R1 楽 那賀ラフティングアクセス・¥190-450/片道)",
    title_ja: "那賀コミュニティバス", romaji: "Naka Bus",
    summary_zh: "**那賀+勝浦+上勝コミュニティバスは R1 衣 ゼロウェイスト 2003 派生・1990 年代以降 35+ 年・山中集落結節+R1 食 太布+R1 楽 ラフティング**(那賀+勝浦+上勝)。¥190-450/片道。",
    content_md: "- 立地:**那賀郡那賀町 + 勝浦郡勝浦町 + 上勝町**\n- 関連:**R1 衣 上勝ゼロウェイスト 2003 + R1 食 阿波太布派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "那賀郡", municipality_ja: "那賀町", lg_code: "36368",
    area_types: ["transport_hub"], lat: 33.9000, lon: 134.3000,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["naka_katsuura_bus"], source: "manual",
  },
  {
    slug: "iya-shuttle-bus",
    category: "transport", sub_type: "tokushima_seibu_transport",
    title_zh: "祖谷+ 大歩危シャトルバス+ 祖谷渓道路(三好市西祖谷+ 大歩危・R1 育 祖谷渓+ かずら橋+ 大歩危派生・JR 大歩危駅-かずら橋-祖谷温泉シャトルバス 1 日 8 便+ 「ボンネットバス」観光バス・¥1,200-2,500・国際 SNS 海外秘境ファン代表)",
    title_ja: "祖谷シャトルバス", romaji: "Iya Shuttle",
    summary_zh: "**祖谷+大歩危シャトルバスは R1 育 派生・JR 大歩危-かずら橋-祖谷温泉シャトル 1 日 8 便+「ボンネットバス」観光**(三好西祖谷+大歩危)。¥1,200-2,500、海外秘境代表。",
    content_md: "- 立地:**三好市西祖谷 + 大歩危**\n- 関連:**R1 育 祖谷渓 + かずら橋 + 大歩危派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208",
    area_types: ["transport_hub"], lat: 33.8728, lon: 133.8019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["iya_shuttle"], source: "manual",
  },
  {
    slug: "tokushima-airport-bus",
    category: "transport", sub_type: "tokushima_terminal",
    title_zh: "徳島阿波踊り空港リムジンバス+ JR 徳島駅シャトル(松茂町豊岡+ 徳島市・R1 行 徳島阿波踊り空港 1959 派生・1959 開業 66+ 年+ 徳島バス運営・JR 徳島駅-空港 30 分+ 1 日 25 便+ R1 衣 阿波踊り装束 全国観衆代表・¥600/片道)",
    title_ja: "空港リムジン", romaji: "Airport Limousine",
    summary_zh: "**徳島阿波踊り空港リムジン+JR 徳島駅シャトルは R1 行 1959 派生・徳島バス運営・JR 徳島-空港 30 分+1 日 25 便**(松茂+徳島)。¥600/片道。",
    content_md: "- 立地:**板野郡松茂町豊岡 + 徳島市**\n- 関連:**R1 行 徳島阿波踊り空港 1959 派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["airport_limousine_1959"], source: "manual",
  },
];

seedMain(rows, "tokushima-transport-r1");
