// Seed 長崎県 R3 — 全カテゴリ補完(28 筆 / Sprint 22.x)
//
// 食 +5 / 住 +3 / 衣 +2 / 育 +10 / 楽 +5 / 行 +3 = 28
//
// 食:ハトシ発祥+ シースケーキ+ 京華園+ 島原具雑煮+ 平戸牛
// 住:日航+ JR 九州+ 雲仙宮崎旅館
// 衣:波佐見西の原エリア+ 西海陶器
// 育:旧五輪教会堂+ 黒崎教会+ 聖福寺+ オルト/リンガー/ザビエル教会+ 香港上海銀行+ 羅典神学校+ 雲仙お山+ 諫早城跡
// 楽:出島ライトアップ+ みなとまつり+ 思案橋夜+ 水ノ浦海水浴+ 諫早眼鏡橋ライト
// 行:出島ワーフ+ 長崎港国際ターミナル+ ぐらばー号観光バス

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: string;
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "kyushu";
  prefecture_ja: "長崎県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // 食 R3 (5)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "hayashimori-hatoshi",
    category: "food",
    sub_type: "nagasaki_chuka",
    title_zh: "林森商行(ハトシ発祥・卓袱料理由来・食パン+ エビすり身揚げ・新地中華街)",
    title_ja: "林森商行",
    romaji: "Hayashimori Shoukou",
    summary_zh: "**林森商行は長崎ハトシ発祥老舗**(長崎市新地町)。ハトシ(蝦多士)= エビすり身を食パンに挟んで揚げた長崎独自料理、卓袱料理由来で清国時代の華僑が伝えた中華料理が和洋折衷で進化。新地中華街の代表的食べ歩き品、1 個 ¥250-300 程度。揚げたて熱々をその場で。",
    content_md: "- 立地:長崎市新地町(新地中華街)\n- 名物:ハトシ(蝦多士)・1 個 ¥250-300\n- 由来:卓袱料理 + 清国華僑伝来\n- 食べ方:食パン+ エビすり身+ 揚げ\n- 営業:11:00-19:00(年中無休)\n- アクセス:長崎電軌「築町」電停 徒歩 3 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["restaurant_chinese"],
    lat: 32.7397,
    lon: 129.8755,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_chuka", "hayashimori", "hatoshi_origin", "shinchi_chinatown"],
    source: "manual",
  },
  {
    slug: "baigetsudo-shisukeki",
    category: "food",
    sub_type: "nagasaki_castella",
    title_zh: "梅月堂(1894 創業・シースケーキ発祥 1955・長崎独自洋菓子・浜の町本店)",
    title_ja: "梅月堂",
    romaji: "Baigetsudo",
    summary_zh: "**梅月堂は長崎独自洋菓子「シースケーキ」発祥の老舗**(長崎市浜町・1894 創業・130 年)。シースケーキ(1955 創作)はスポンジ+ 黄桃+ パイン+ カスタード+ ホイップの**長崎独自レイヤーケーキ**で、長崎の誕生日定番。**カステラ+ ハトシサンド** も人気、観光客向け+地元客の両方をカバー。",
    content_md: "- 創業:1894 年(明治 27)・130 年\n- 名物:シースケーキ(1955 創作・¥450)+ カステラ+ ハトシサンド\n- シースケーキ:スポンジ+ 黄桃+ パイン+ カスタード+ ホイップの長崎独自レイヤー\n- 営業:9:00-19:00(年中無休)\n- 店舗:浜町本店+ アミュプラザ店+ 長崎駅店\n- アクセス:長崎電軌「観光通り」電停 徒歩 3 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["restaurant_traditional"],
    lat: 32.7444,
    lon: 129.8761,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.baigetsudo.co.jp/" },
    tags: ["nagasaki_castella", "baigetsudo", "1894", "she_cake_origin", "1955"],
    source: "manual",
  },
  {
    slug: "keikaen-1925",
    category: "food",
    sub_type: "nagasaki_chuka",
    title_zh: "京華園(1925 創業・新地中華街老舗 100 年・卓袱中華+ 皿うどん+ 角煮)",
    title_ja: "京華園",
    romaji: "Keikaen",
    summary_zh: "**京華園は新地中華街の中華料理老舗**(長崎市新地町・1925 創業・100 年)。3 階建ての本格中華店で、**卓袱中華**(卓袱料理の中華アレンジ)+ 皿うどん+ 角煮+ 麻婆豆腐 等。新地中華街では四海樓+ 江山楼に並ぶ三大老舗、団体客も対応する大型店。",
    content_md: "- 創業:1925 年(大正 14)・100 年\n- 立地:長崎市新地町(新地中華街)\n- 名物:卓袱中華+ 皿うどん+ 角煮+ 麻婆豆腐\n- 規模:3 階建て大型中華料理店\n- 並ぶ老舗:四海樓+ 江山楼+ 京華園(三大老舗)\n- 営業:11:30-21:30(年中無休)\n- アクセス:長崎電軌「築町」電停 徒歩 3 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["restaurant_chinese"],
    lat: 32.7397,
    lon: 129.8744,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: { official: "https://www.keikaen.co.jp/" },
    tags: ["nagasaki_chuka", "keikaen", "1925", "100_years", "shinchi_chinatown"],
    source: "manual",
  },
  {
    slug: "shimabara-gusozoni-ginsui",
    category: "food",
    sub_type: "shimabara_kanzarashi_traditional",
    title_zh: "島原具雑煮 銀水(1915 創業・島原の乱起源郷土料理・餅+ 14 種具材)",
    title_ja: "銀水",
    romaji: "Ginsui",
    summary_zh: "**銀水は島原具雑煮の代表老舗**(島原市新町・1915 創業・110 年)。**島原具雑煮は島原の乱(1637-38)** 起源の郷土料理、籠城した天草四郎軍が餅+ 山海の具材を雑煮にして食べた伝統。餅+ 鶏肉+ 椎茸+ かまぼこ+ 野菜+ 14 種具材の豪華な雑煮、武家屋敷+ 鯉の泳ぐまち徒歩 3 分。",
    content_md: "- 創業:1915 年(大正 4)・110 年\n- 立地:島原市新町(武家屋敷+ 鯉の泳ぐまち隣接)\n- 名物:具雑煮(¥1100)\n- 起源:島原の乱(1637-38)・天草四郎軍籠城時の食料\n- 具材:餅+ 鶏肉+ 椎茸+ かまぼこ+ 牛蒡+ 大根+ 14 種\n- 営業:11:00-20:00(年中無休)\n- アクセス:島原鉄道 島原駅 徒歩 8 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "島原市",
    lg_code: "42203",
    area_types: ["restaurant_traditional"],
    lat: 32.7833,
    lon: 130.3650,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shimabara_kanzarashi_traditional", "ginsui", "1915", "gu_zoni", "shimabara_uprising_origin"],
    source: "manual",
  },
  {
    slug: "hirado-gyu-overview",
    category: "food",
    sub_type: "nagasaki_shima_san",
    title_zh: "平戸牛(平戸市黒毛和牛・全国和牛能力共進会 受賞多数・大坪牧場+ 里美牧場+ 平戸瀬戸食肉)",
    title_ja: "平戸牛",
    romaji: "Hirado Gyu",
    summary_zh: "**平戸牛は平戸市の黒毛和牛ブランド**(肉牛飼育数 県内 1 位)。**全国和牛能力共進会**(和牛オリンピック・5 年に 1 回)で受賞多数、九州和牛のトップクラス。平戸の海風+ 牧草地+ 寒暖差が良質な霜降りを生む。代表牧場:大坪牧場+ 里美牧場+ 平戸瀬戸食肉、平戸市内のレストラン+ ステーキハウスで提供。",
    content_md: "- 産地:平戸市(肉牛飼育数 県内 1 位)\n- 受賞:全国和牛能力共進会 受賞多数\n- 代表牧場:大坪牧場+ 里美牧場+ 平戸瀬戸食肉\n- 提供店:平戸市内 ステーキハウス+ 焼肉店+ 観光ホテル\n- 価格目安:ステーキランチ ¥3000-+ ディナー ¥6000-\n- 隣接観光:平戸城+ オランダ商館\n- アクセス:松浦鉄道 たびら平戸口駅 から バス 30 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "平戸市",
    lg_code: "42207",
    area_types: ["restaurant_traditional"],
    lat: 33.3681,
    lon: 129.5500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_shima_san", "hirado_gyu", "wagyu_olympic", "n1_pref_cattle"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 住 R3 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nikko-hotel-nagasaki-1989",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテル日航長崎(1989 開業・大波止・港眺望・ANA系列・225 室)",
    title_ja: "ホテル日航長崎",
    romaji: "Hotel Nikko Nagasaki",
    summary_zh: "**ホテル日航長崎は ANA 系列の老舗ハイクラスホテル**(長崎市大波止・1989 開業・225 室)。長崎港+ 稲佐山+ 三菱造船所眺望、出島+ 中華街徒歩圏。出島ワーフ徒歩 3 分の好立地、ビジネス+ 観光両用、長崎平和祈念式典(8/9)に併せた宿泊客が伝統的に多い。",
    content_md: "- 開業:1989 年(平成 1)・35 年\n- 立地:長崎市大波止町(出島ワーフ徒歩 3 分)\n- 室数:225 室\n- 系列:ANA ホテルグループ(現:日航は別)\n- 眺望:長崎港+ 稲佐山+ 三菱造船所\n- 料金目安:¥12000-25000/泊\n- アクセス:長崎電軌「大波止」電停 徒歩 3 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["urban_central"],
    lat: 32.7475,
    lon: 129.8689,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["luxury_hotel", "nikko", "1989", "ohato", "225_rooms"],
    source: "manual",
  },
  {
    slug: "jr-kyushu-hotel-nagasaki",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "JR 九州ホテル長崎(駅前直結・西九州新幹線対応・JR 九州系列・コスパ良 156 室)",
    title_ja: "JR 九州ホテル長崎",
    romaji: "JR Kyushu Hotel Nagasaki",
    summary_zh: "**JR 九州ホテル長崎は JR 長崎駅直結の駅前ホテル**(2000 開業・156 室)。西九州新幹線開業(2022)+ 駅高架化リニューアル(2020)で利便性向上、新幹線+ 路面電車+ 高速バスへの直結アクセス。コスパ・立地のバランスが評価、観光+ ビジネス両用。",
    content_md: "- 開業:2000 年(平成 12)\n- 立地:JR 長崎駅 直結(駅前ロータリー)\n- 室数:156 室\n- 系列:JR 九州ホテルズ\n- 朝食:¥1500(ビュッフェ)\n- 料金目安:¥7000-13000/泊\n- 隣接:アミュプラザ長崎+ 長崎駅 1 分\n- アクセス:JR 長崎駅 徒歩 1 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["urban_central"],
    lat: 32.7536,
    lon: 129.8717,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://www.jrk-hotels.co.jp/Nagasaki/" },
    tags: ["budget_hotel_chain", "jr_kyushu", "2000", "station_direct", "156_rooms"],
    source: "manual",
  },
  {
    slug: "unzen-miyazaki-ryokan-1830",
    category: "lodging",
    sub_type: "nagasaki_unzen_classical",
    title_zh: "雲仙温泉 宮崎旅館(1830 創業・雲仙最古級老舗・195 年・地獄温泉源泉掛流し)",
    title_ja: "雲仙宮崎旅館",
    romaji: "Unzen Miyazaki Ryokan",
    summary_zh: "**雲仙宮崎旅館は雲仙温泉最古級の老舗**(雲仙市・1830 創業・195 年)。**富貴屋(1730・R1)** に次ぐ雲仙古宿、地獄温泉の源泉掛流し+ 木造数寄屋風建築。皇室+ 文人(夏目漱石+ 与謝野晶子等)が宿泊した記録、現代も日本旅館の風情を保つ。雲仙地獄+ 仁田峠ロープウェイ徒歩圏。",
    content_md: "- 創業:1830 年(天保 1)・195 年\n- 立地:雲仙市小浜町雲仙温泉中心\n- 雲仙最古級:富貴屋(1730)に次ぐ古宿\n- 温泉:地獄温泉源泉掛流し(硫黄泉・88 ℃)\n- 著名宿泊:夏目漱石+ 与謝野晶子+ 皇室\n- 料金目安:¥18000-35000/泊(2 食付)\n- 隣接:雲仙地獄(徒歩 5 分)+ 仁田峠ロープウェイ(車 15 分)\n- アクセス:諫早駅 から バス 80 分・雲仙下車",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "雲仙市",
    lg_code: "42213",
    area_types: ["onsen_field"],
    lat: 32.7458,
    lon: 130.2592,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_unzen_classical", "miyazaki_ryokan", "1830", "195_years", "soseki_akiko"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 衣 R3 (2)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nishi-no-hara-hasami-area",
    category: "fashion",
    sub_type: "nagasaki_hasami_mikawachi",
    title_zh: "波佐見西の原エリア(現代陶器街・モンネ・ルギ・モック+ HIROPPA+ 直営店集積・カフェ併設)",
    title_ja: "西の原",
    romaji: "Nishi no Hara",
    summary_zh: "**西の原は波佐見焼の現代陶器街**(東彼杵郡波佐見町中尾郷)。古い陶磁器倉庫群を再生した複合エリアで、**モンネ・ルギ・モック**(カフェ+ 雑貨)+ **HIROPPA マルヒロ直営店** + 数件の窯元直営店+ 工房+ ガレットレストラン等が集積。波佐見観光のメインスポット、半日でゆっくり過ごせる。",
    content_md: "- 立地:東彼杵郡波佐見町中尾郷\n- 構成:モンネ・ルギ・モック(カフェ+ 雑貨)+ HIROPPA(マルヒロ直営)+ aiyu+ 工房数軒\n- 雰囲気:倉庫群再生+ モダン+ ガーデン併設\n- 営業:店舗により異なる(11:00-17:00 が標準・火水定休多)\n- 駐車場:無料 50 台\n- アクセス:JR 有田駅 から 車 15 分(東彼杵 IC 5 分)",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: "東彼杵郡",
    municipality_ja: "波佐見町",
    lg_code: "42323",
    area_types: ["historic_district", "shopping_district_urban"],
    lat: 33.1761,
    lon: 129.8631,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["tue", "wed"],
    external_urls: { official: "https://nishinohara.com/" },
    tags: ["nagasaki_hasami_mikawachi", "nishi_no_hara", "warehouse_renewal", "monne_legui_mooks", "hasami_modern"],
    source: "manual",
  },
  {
    slug: "saikai-toki-1969",
    category: "fashion",
    sub_type: "nagasaki_hasami_mikawachi",
    title_zh: "西海陶器(1969 創業・波佐見最大手・全国 1000+ 店舗流通・「Common」+ 「コモン」現代ライン)",
    title_ja: "西海陶器",
    romaji: "Saikai Toki",
    summary_zh: "**西海陶器は波佐見焼の最大手商社**(東彼杵郡波佐見町・1969 創業)。**全国 1000+ 店舗に流通**、波佐見焼を全国に届ける流通の主役。代表ブランド「Common」「コモン」「essence」など現代ラインを企画+ 卸、無印良品+ ロフト+ ハンズ+ 高島屋等で展開。直営店「OYANE」(波佐見町)で全ライン展示。",
    content_md: "- 創業:1969 年(昭和 44)\n- 立地:東彼杵郡波佐見町\n- 規模:全国 1000+ 店舗流通(波佐見焼最大手)\n- 主要ブランド:Common+ コモン+ essence+ Brick\n- 直営店:OYANE(波佐見町)・全ライン展示\n- 流通先:無印良品+ ロフト+ ハンズ+ 高島屋等\n- 営業:9:30-17:00(土日定休)\n- アクセス:JR 有田駅 から 車 15 分(東彼杵 IC 5 分)",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: "東彼杵郡",
    municipality_ja: "波佐見町",
    lg_code: "42323",
    area_types: ["historic_district"],
    lat: 33.1781,
    lon: 129.8694,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["sat", "sun"],
    external_urls: { official: "https://www.saikaitoki.com/" },
    tags: ["nagasaki_hasami_mikawachi", "saikai_toki", "1969", "1000_shops_distribution", "common_brand"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 育 R3 (10)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyu-gorin-tenshudo-1881",
    category: "culture",
    sub_type: "nagasaki_christian_history",
    title_zh: "旧五輪教会堂(久賀島・国重文 1881・現存日本最古の木造教会・潜伏キリシタン世遺構成)",
    title_ja: "旧五輪教会堂",
    romaji: "Kyu Gorin Tenshudo",
    summary_zh: "**旧五輪教会堂は現存日本最古の木造教会**(五島市久賀島・1881 完成・国重文 1999)。元は浜脇教会の旧聖堂を 1931 年に五輪集落へ移築、潜伏キリシタンの素朴な信仰を象徴する木造教会。**久賀島の集落** として 2018 世界遺産構成資産、五島列島キリシタン教会群の最重要 1。",
    content_md: "- 完成:1881 年(明治 14)\n- 元位置:浜脇教会(五島市久賀島)\n- 1931 移築:五輪集落へ\n- 国指定重要文化財:1999 年\n- 世界遺産:2018 潜伏キリシタン関連 12 構成資産\n- 史的価値:現存日本最古の木造教会\n- 立地:五島市蕨町(久賀島)\n- 訪問:事前連絡必須(教会守による解錠)\n- 連絡:長崎教区インフォメーションセンター\n- アクセス:福江港 から 田ノ浦港(船 30 分)+ 車 30 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "五島市",
    lg_code: "42211",
    area_types: ["world_heritage", "shrine_temple"],
    lat: 32.7944,
    lon: 128.9133,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 7,
    closed_days: [],
    external_urls: { official: "https://kirishitan.jp/components/com007" },
    tags: ["nagasaki_christian_history", "world_heritage_2018", "national_important_cultural_property", "1881", "oldest_wood"],
    source: "manual",
  },
  {
    slug: "kurosaki-kyokai-1920",
    category: "culture",
    sub_type: "nagasaki_christian_history",
    title_zh: "黒崎教会(長崎市・1920 完成・鉄川与助設計・遠藤周作『沈黙』ゆかりの地・外海地区)",
    title_ja: "黒崎教会",
    romaji: "Kurosaki Kyoukai",
    summary_zh: "**黒崎教会は遠藤周作小説『沈黙』ゆかりの地**(長崎市黒崎町・1920 完成)。鉄川与助設計のレンガ造ロマネスク様式、外海地区(出津+ 大野+ 黒崎+ 神浦)の潜伏キリシタンの末裔の信仰拠点。世界遺産構成資産ではないが、外海キリシタン文化の象徴的教会、遠藤周作文学館徒歩 5 分。",
    content_md: "- 完成:1920 年(大正 9)\n- 設計:鉄川与助\n- 様式:レンガ造ロマネスク\n- 立地:長崎市上黒崎町(外海地区)\n- 文学:遠藤周作『沈黙』のロケ地+ 物語の舞台\n- 隣接:遠藤周作文学館(徒歩 5 分)+ 出津教会(車 10 分)\n- 入場:無料(献金箱)\n- 営業:9:00-17:00(教会奉仕中除く)\n- アクセス:長崎駅 から バス 80 分・黒崎下車",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["shrine_temple"],
    lat: 32.8800,
    lon: 129.7361,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_christian_history", "1920", "tetsugawa_yosuke", "endo_shusaku_silence", "kurosaki"],
    source: "manual",
  },
  {
    slug: "shofukuji-1677",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "聖福寺(1677 創建・長崎四福寺最後・広東出身唐人寺・隠元 4 代孫鉄牛開山)",
    title_ja: "聖福寺",
    romaji: "Shofukuji",
    summary_zh: "**聖福寺は長崎四福寺の最後 1**(長崎市玉園町・1677 創建)。広東省出身唐人が建立、四福寺(崇福寺=福州/福済寺=漳州/興福寺=南京/聖福寺=広東)の最後の建立。**亀趺(かめのうえに碑)** 国重文 1 棟+ 山門+ 大雄宝殿が現存、四福寺巡りの最後の寺。",
    content_md: "- 創建:1677 年(延宝 5)・広東省出身唐人\n- 開山:鉄牛禅師(隠元 4 代孫)\n- 通称:広東寺\n- 国指定重要文化財:亀趺(亀の上に碑石・1 基)\n- 四福寺:崇福寺=福州寺+福済寺=漳州寺+興福寺=南京寺+聖福寺=広東寺\n- 入場料:¥200\n- 営業:8:00-17:00\n- 隣接:福済寺(徒歩 5 分)+ 長崎駅(徒歩 10 分)\n- アクセス:JR 長崎駅 徒歩 10 分(山腹)",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["shrine_temple"],
    lat: 32.7547,
    lon: 129.8753,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "shofukuji", "1677", "kanton_tera", "obaku_zen", "kifu"],
    source: "manual",
  },
  {
    slug: "kyu-orth-residence-1865",
    category: "culture",
    sub_type: "nagasaki_industrial_revolution",
    title_zh: "旧オルト住宅(国重文・1865・グラバー園内・英国貿易商ウィリアム・オルト邸・木造階段付)",
    title_ja: "旧オルト住宅",
    romaji: "Kyu Orth Jutaku",
    summary_zh: "**旧オルト住宅はグラバー園内の代表的洋館の 1**(長崎市南山手町・1865 完成・国重文 1972)。英国貿易商ウィリアム・オルト(製茶輸出)の邸宅、木造階段+ 大型ベランダが特徴。**旧グラバー住宅 1863+ 旧リンガー住宅 1869+ 旧オルト住宅 1865 は南山手洋館 3 大邸宅**。グラバー園入園で見学可。",
    content_md: "- 完成:1865 年(慶応 1)\n- 国指定重要文化財:1972 年\n- 居住者:ウィリアム・オルト(英国貿易商・製茶輸出)\n- 構造:木造ベランダ付+ 大階段\n- 三大邸宅:旧グラバー(1863)+ 旧オルト(1865)+ 旧リンガー(1869)\n- グラバー園入園料:¥620\n- 営業:8:00-18:00(夏期延長)\n- アクセス:長崎電軌「大浦天主堂」電停 徒歩 7 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["history_site_castle"],
    lat: 32.7339,
    lon: 129.8697,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.glover-garden.jp/" },
    tags: ["nagasaki_industrial_revolution", "kyu_orth", "1865", "national_important_cultural_property", "william_orth"],
    source: "manual",
  },
  {
    slug: "kyu-ringer-residence-1869",
    category: "culture",
    sub_type: "nagasaki_industrial_revolution",
    title_zh: "旧リンガー住宅(国重文・1869・グラバー園内・英国貿易商フレデリック・リンガー邸・石造)",
    title_ja: "旧リンガー住宅",
    romaji: "Kyu Ringer Jutaku",
    summary_zh: "**旧リンガー住宅は南山手洋館 3 大邸宅の最後**(長崎市南山手町・1869 完成・国重文 1966)。英国貿易商フレデリック・リンガー(茶+ 海産物輸出+ ホテル業)の邸宅、**石造ベランダ** が特徴で 3 大邸宅で唯一の石造。グラバー園内で見学可、内部にリンガー家関連史料展示。",
    content_md: "- 完成:1869 年(明治 2)\n- 国指定重要文化財:1966 年\n- 居住者:フレデリック・リンガー(英国貿易商・茶+ 海産物+ ホテル業)\n- 構造:石造ベランダ(3 大邸宅で唯一)\n- 内部:リンガー家史料展示\n- グラバー園入園料:¥620\n- 営業:8:00-18:00(夏期延長)\n- アクセス:長崎電軌「大浦天主堂」電停 徒歩 7 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["history_site_castle"],
    lat: 32.7339,
    lon: 129.8700,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.glover-garden.jp/" },
    tags: ["nagasaki_industrial_revolution", "kyu_ringer", "1869", "national_important_cultural_property", "frederick_ringer"],
    source: "manual",
  },
  {
    slug: "kyu-hongkong-shanghai-bank-1904",
    category: "culture",
    sub_type: "nagasaki_industrial_revolution",
    title_zh: "旧香港上海銀行長崎支店記念館(国重文・1904・下田菊太郎設計・現存最古の銀行建築・松が枝)",
    title_ja: "旧香港上海銀行長崎支店記念館",
    romaji: "Kyu Hongkong Shanghai Bank",
    summary_zh: "**旧香港上海銀行長崎支店記念館は明治期銀行建築の最高傑作**(長崎市松が枝町・1904 完成・国重文 1990)。**下田菊太郎**(東京駅赤レンガ駅舎の辰野金吾と並ぶ巨匠)設計、3 階建てネオ・ルネサンス様式の堂々たる銀行建築。現存日本最古級の銀行建築の 1。",
    content_md: "- 完成:1904 年(明治 37)\n- 設計:下田菊太郎(東京駅赤レンガと同時代の巨匠)\n- 様式:ネオ・ルネサンス・3 階建て石造\n- 国指定重要文化財:1990 年\n- 立地:長崎市松が枝町\n- 内部:長崎居留地史料館(無料)\n- 営業:9:00-17:00(月曜定休)\n- アクセス:長崎電軌「大浦天主堂」電停 徒歩 3 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["history_site_castle"],
    lat: 32.7361,
    lon: 129.8694,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["mon"],
    external_urls: {},
    tags: ["nagasaki_industrial_revolution", "hsbc_1904", "national_important_cultural_property", "shimoda_kikutaro", "neo_renaissance"],
    source: "manual",
  },
  {
    slug: "kyu-rakurin-school",
    category: "culture",
    sub_type: "nagasaki_christian_history",
    title_zh: "旧羅典神学校(国重文・1875・大浦天主堂隣・日本最古のカトリック神学校・木造 3 階)",
    title_ja: "旧羅典神学校",
    romaji: "Kyu Rakurin Shingakkou",
    summary_zh: "**旧羅典神学校は日本最古のカトリック神学校**(長崎市南山手町・1875 完成・国重文 1972)。**大浦天主堂隣接**、明治期日本のカトリック宣教師養成施設、ド・ロ神父も建設に関与。木造 3 階建の質素な建築、現在は **キリシタン博物館** として大浦天主堂と一体運営。",
    content_md: "- 完成:1875 年(明治 8)\n- 役割:日本最古のカトリック神学校(神父養成施設)\n- 国指定重要文化財:1972 年\n- 構造:木造 3 階建\n- 関与者:ド・ロ神父+ プチジャン神父\n- 現用途:キリシタン博物館(大浦天主堂と一体運営)\n- 入場料:大浦天主堂入場料 ¥1000 込\n- 営業:8:30-18:00(冬 17:00)\n- アクセス:長崎電軌「大浦天主堂」電停 徒歩 5 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["shrine_temple"],
    lat: 32.7339,
    lon: 129.8694,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_christian_history", "kyu_rakurin", "1875", "national_important_cultural_property", "oldest_seminary"],
    source: "manual",
  },
  {
    slug: "hirado-xavier-church-1931",
    category: "culture",
    sub_type: "nagasaki_christian_history",
    title_zh: "平戸ザビエル記念教会(1931 完成・聖フランシスコ・ザビエル来航 1550 記念・寺院併立絶景)",
    title_ja: "平戸ザビエル記念教会",
    romaji: "Hirado Xavier Memorial Church",
    summary_zh: "**平戸ザビエル記念教会は 1931 年完成のゴシック教会**(平戸市鏡川町)。1550 年聖フランシスコ・ザビエルの平戸来航を記念、エメラルドグリーンの尖塔が特徴的。**寺院(光明寺+ 瑞雲寺)+ 教会の併立眺望** が「寺院と教会の見える風景」として平戸観光の象徴シーン、平戸城+ 松浦史料博物館徒歩 5 分。",
    content_md: "- 完成:1931 年(昭和 6)・原型・1971 改築\n- 様式:ゴシック+ エメラルドグリーン尖塔\n- 立地:平戸市鏡川町\n- 由来:聖フランシスコ・ザビエル平戸来航 1550 記念\n- 撮影スポット:寺院と教会の見える風景(光明寺+ 瑞雲寺と並ぶ)\n- 入場:無料(献金箱)\n- 営業:8:00-17:00\n- 隣接:平戸城(徒歩 5 分)+ 松浦史料博物館(徒歩 5 分)\n- アクセス:松浦鉄道 たびら平戸口駅 から バス 30 分・平戸桟橋 徒歩 10 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "平戸市",
    lg_code: "42207",
    area_types: ["shrine_temple"],
    lat: 33.3669,
    lon: 129.5489,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_christian_history", "hirado_xavier", "1931", "1550_xavier_arrival", "temple_church_view"],
    source: "manual",
  },
  {
    slug: "unzen-oyama-info-center",
    category: "culture",
    sub_type: "museum_art",
    title_zh: "雲仙お山の情報館(国立公園案内・1934 雲仙国立公園・無料・地獄+ 普賢岳+ 動植物展示)",
    title_ja: "雲仙お山の情報館",
    romaji: "Unzen Oyama no Joho Kan",
    summary_zh: "**雲仙お山の情報館は雲仙天草国立公園のビジターセンター**(雲仙市・無料)。**1934 年指定 日本初の国立公園・第 1 号** に関する歴史+ 雲仙地獄の地学+ 普賢岳噴火 1990-95+ 動植物等を無料展示、雲仙温泉観光の出発点。地獄めぐり前に立寄ると理解深まる。",
    content_md: "- 立地:雲仙市小浜町雲仙温泉\n- 国立公園:雲仙天草国立公園(1934 指定・日本初 第 1 号)\n- 主要展示:地獄地学+ 普賢岳噴火 1990-95+ 動植物+ 国立公園史\n- 入場料:無料\n- 営業:9:00-17:00(年中無休)\n- 隣接:雲仙地獄(徒歩 3 分)+ 雲仙温泉街\n- アクセス:諫早駅 から バス 80 分・雲仙下車",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "雲仙市",
    lg_code: "42213",
    area_types: ["museum_art", "national_park"],
    lat: 32.7461,
    lon: 130.2589,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.env.go.jp/park/unzen/" },
    tags: ["museum_art", "unzen_visitor_center", "free", "1934_first_national_park", "fugendake_eruption"],
    source: "manual",
  },
  {
    slug: "isahaya-jou-ato",
    category: "culture",
    sub_type: "history_site_castle",
    title_zh: "諫早城跡・諫早公園(西郷氏築城・廃城後公園化・本明川沿い・桜+ 眼鏡橋集積)",
    title_ja: "諫早城跡",
    romaji: "Isahaya Jou Ato",
    summary_zh: "**諫早城跡は本明川沿いの平山城跡**(諫早市・諫早公園内)。中世西郷氏築城・1571 年龍造寺氏侵攻で落城、近世は諫早氏陣屋。明治廃城後公園化、現在は諫早眼鏡橋(国重文・移築)+ 桜+ 紅葉名所。城そのものは石垣のみ残存だが、諫早観光の中心地。",
    content_md: "- 築城:中世(15 世紀)西郷氏\n- 落城:1571 年 龍造寺隆信侵攻\n- 近世:諫早氏陣屋(諫早領主)\n- 廃城:1873 年(明治 6)\n- 現状:諫早公園内・石垣残存・桜+ 紅葉名所\n- 諫早眼鏡橋(国重文・1839)が公園内に移築\n- 入場料:無料(常時)\n- 隣接:諫早眼鏡橋(国重文)+ 諫早市街(徒歩 12 分)\n- アクセス:JR 諫早駅 徒歩 12 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "諫早市",
    lg_code: "42204",
    area_types: ["history_site_castle", "park_garden"],
    lat: 32.8439,
    lon: 130.0508,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["history_site_castle", "isahaya_jou", "saigo_clan", "isahaya_clan", "park_with_megane_bashi"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 楽 R3 (5)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "dejima-illumination-night",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "出島ライトアップ年中(日没-21:00・復元 16 棟が幻想的・国指定史跡夜景)",
    title_ja: "出島ライトアップ",
    romaji: "Dejima Light-up",
    summary_zh: "**出島は年中ライトアップで夜の景観も人気**(長崎市出島町・21:00 まで開園)。1996 復元事業で建立した 16 棟のオランダ商館建築群が幻想的に浮かび上がる、SNS 映え観光スポット。日没後-21:00 が最ベスト、特に夏場は涼しく快適。出島ワーフ+ 県美術館徒歩圏で夜散策コース定番。",
    content_md: "- 期間:年中(日没-21:00)\n- 営業:8:00-21:00(年中無休)\n- 入場料:¥520(夜間も同額)\n- 主要演出:復元 16 棟のオランダ商館建築群+ 庭園+ 街路灯\n- 撮影スポット:カピタン部屋+ ヘトル部屋+ 表門前\n- 隣接:出島ワーフ(レストラン+バー集積・徒歩 1 分)+ 長崎県美術館(徒歩 5 分)\n- アクセス:長崎電軌「出島」電停 徒歩 1 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["illumination", "historic_district"],
    lat: 32.7437,
    lon: 129.8731,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://nagasakidejima.jp/" },
    tags: ["illumination", "dejima_night", "year_round", "16_buildings", "national_historic_site"],
    source: "manual",
  },
  {
    slug: "nagasaki-port-festival-summer",
    category: "entertainment",
    sub_type: "nagasaki_lantern_fest",
    title_zh: "長崎みなとまつり(7 月最終週末・水辺の森公園・水辺花火大会と同期間・1948 起源)",
    title_ja: "長崎みなとまつり",
    romaji: "Nagasaki Minato Matsuri",
    summary_zh: "**長崎みなとまつりは 1948 年起源の港祭り**(7 月最終週末・水辺の森公園+ 出島ワーフ)。**みなとながさき水辺の花火大会**(R1 既出)と同期間で開催、屋台 200+ 軒+ ステージイベント+ 龍踊+ ペーロン+ 雑技団 等の演目。長崎の夏の風物詩で 50 万人来場、長崎港エリア全域がお祭り会場化。",
    content_md: "- 開催:7 月最終週末(2 日間)\n- 起源:1948 年(昭和 23)\n- 主会場:水辺の森公園+ 出島ワーフ+ 長崎港岸壁\n- 内容:屋台 200+ 軒+ ステージ+ 龍踊+ ペーロン体験+ 雑技団\n- 同期:水辺の花火大会(7/25 頃・8000 発)\n- 来場:約 50 万人\n- 入場:無料\n- アクセス:長崎電軌「大波止」電停 徒歩 5 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["festival_event"],
    lat: 32.7400,
    lon: 129.8728,
    season_start: null,
    season_end: null,
    event_start: "2026-07-25",
    event_end: "2026-07-26",
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_lantern_fest", "minato_matsuri", "1948", "july_last_weekend", "500k_visitors"],
    source: "manual",
  },
  {
    slug: "shianbashi-yokocho-night",
    category: "entertainment",
    sub_type: "nagasaki_night_view",
    title_zh: "思案橋横丁夜街(80+ 軒小路居酒屋集積・長崎夜の中心・ペーロン本場+ 角煮+ 一口餃子)",
    title_ja: "思案橋横丁",
    romaji: "Shianbashi Yokocho",
    summary_zh: "**思案橋横丁は長崎の夜の中心**(長崎市思案橋・80+ 軒の居酒屋+ バー集積)。江戸期から続く花街の名残を残す路地裏に小路居酒屋が密集、長崎の郷土料理(角煮+ 一口餃子+ ハトシ+ ペーロン)+ 地酒+ 焼酎。雲龍亭(R2)+ 桃太呂(R2)等の老舗もここに分店を持つ、深夜まで営業の店多数。",
    content_md: "- 立地:長崎市銅座町(思案橋電停周辺)\n- 規模:80+ 軒の居酒屋+ バー集積\n- 由来:江戸期花街の名残・「行こうか戻ろうか思案する橋」\n- 名物店:雲龍亭(一口餃子)+ 桃太呂(ぶたまん)+ 各種角煮屋+ 地酒バー\n- 営業:店舗により 18:00-翌 1:00 ・大部分が月曜定休\n- 散策:夜街全体を歩いて雰囲気を味わう\n- アクセス:長崎電軌「思案橋」電停 徒歩 1 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["nightlife"],
    lat: 32.7411,
    lon: 129.8767,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_night_view", "shianbashi_yokocho", "80_izakaya", "nagasaki_nightlife", "edo_hanamachi"],
    source: "manual",
  },
  {
    slug: "mizugaura-fukue-beach",
    category: "entertainment",
    sub_type: "nagasaki_kujukushima_marine",
    title_zh: "水ノ浦海水浴場(五島福江島・全国級透明度・海水浴+ シュノーケル+ サンセット)",
    title_ja: "水ノ浦海水浴場",
    romaji: "Mizugaura Beach",
    summary_zh: "**水ノ浦海水浴場は五島福江島の代表ビーチ**(五島市岐宿町)。**透明度 20 m 級** の絶景ビーチ、白砂+ エメラルドグリーンの海水でハワイ並みの美しさ。海水浴+ シュノーケル+ SUP+ サンセット名所、無料駐車場+ シャワー+ トイレ完備。福江島内で最アクセス良いビーチ、夏の家族旅行に人気。",
    content_md: "- 立地:五島市岐宿町(福江島北部)\n- 透明度:20 m 級(全国上位)\n- 規模:長さ 800 m × 幅 50 m\n- 設備:無料駐車場 50 台+ シャワー+ トイレ\n- 海水浴期間:7 月-8 月\n- アクティビティ:海水浴+ シュノーケル+ SUP\n- 隣接:鬼岳(車 20 分)+ 三井楽(車 30 分)\n- アクセス:福江港 から 車 25 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "五島市",
    lg_code: "42211",
    area_types: ["coast_seaside"],
    lat: 32.7758,
    lon: 128.7531,
    season_start: "2026-07-15",
    season_end: "2026-08-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_kujukushima_marine", "mizugaura", "20m_transparency", "fukue_north", "summer_beach"],
    source: "manual",
  },
  {
    slug: "isahaya-meganebashi-light",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "諫早眼鏡橋ライトアップ(年中・日没-22:00・国重文・現存最古アーチ石橋夜景・諫早公園)",
    title_ja: "諫早眼鏡橋ライトアップ",
    romaji: "Isahaya Megane Bashi Light-up",
    summary_zh: "**諫早眼鏡橋ライトアップは年中の夜景観賞スポット**(諫早市諫早公園・日没-22:00)。**現存日本最古のアーチ式石橋(国重文 1839)** が暖色 LED で照らされ、池に映る対称美が SNS 映え。無料 24 時間アクセス可、諫早駅徒歩 12 分。観光客より地元客に人気の隠れた夜景スポット。",
    content_md: "- 期間:年中(日没-22:00)\n- 入場:無料(常時公開)\n- 立地:諫早市諫早公園内\n- 撮影:橋の正面+ 池の対岸から橋+ 反射の対称美\n- 隣接:諫早城跡+ 諫早公園\n- 桜時期(3-4 月):桜+ ライトアップで二重絶景\n- アクセス:JR 諫早駅 徒歩 12 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "諫早市",
    lg_code: "42204",
    area_types: ["illumination", "park_garden"],
    lat: 32.8439,
    lon: 130.0508,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["illumination", "isahaya_megane_bashi_light", "year_round", "national_important_cultural_property", "free"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 行 R3 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "dejima-wharf-port-hub",
    category: "transport",
    sub_type: "nagasaki_island_routes",
    title_zh: "出島ワーフ(長崎港メイン hub・船+ 食+ 観光複合・1999 開業・離島フェリー+ 軍艦島ツアー集約)",
    title_ja: "出島ワーフ",
    romaji: "Dejima Wharf",
    summary_zh: "**出島ワーフは長崎港観光の最重要 hub**(長崎市出島町・1999 開業)。**長崎港ターミナル**(離島フェリー+ ジェットフォイル発着)+ **軍艦島ツアー船**(やまさ海運+ 第七ゑびす丸 等)+ レストラン 30 軒+ バー+ 出島・県美術館徒歩圏。観光+ 食事+ 出航の三重機能、夜景+ 港の風 で長崎観光の動線中心。",
    content_md: "- 開業:1999 年(平成 11)\n- 立地:長崎市出島町(出島隣・水辺の森公園隣)\n- 機能 1:長崎港ターミナル(五島+ 高島+ 端島フェリー発着)\n- 機能 2:軍艦島ツアー船発着(やまさ+ コンシェルジュ等 4 社)\n- 機能 3:レストラン 30 軒+ バー+ ショップ\n- 観光連絡:出島(徒歩 1 分)+ 県美術館(徒歩 5 分)+ 中華街(徒歩 8 分)\n- アクセス:長崎電軌「出島」電停 徒歩 3 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["transit_hub", "ferry_terminal"],
    lat: 32.7444,
    lon: 129.8675,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://dejimawharf.com/" },
    tags: ["nagasaki_island_routes", "dejima_wharf", "1999", "port_hub", "30_restaurants"],
    source: "manual",
  },
  {
    slug: "nagasaki-port-international",
    category: "transport",
    sub_type: "nagasaki_island_routes",
    title_zh: "長崎港国際ターミナル(クルーズ船寄港・年間 100+ 隻・松が枝岸壁・最大 22 万トン級)",
    title_ja: "長崎港国際ターミナル",
    romaji: "Nagasaki Port International Terminal",
    summary_zh: "**長崎港国際ターミナルは大型クルーズ船寄港の主要拠点**(長崎市松が枝町・松が枝岸壁)。**最大 22 万トン級** の世界最大級クルーズ船(クァンタム・オブ・ザ・シーズ等)が寄港、年間 100+ 隻+ 30 万人の外国人観光客流入。出島+ グラバー園+ 大浦天主堂徒歩 5 分の好立地で観光客を効率的に流す。",
    content_md: "- 立地:長崎市松が枝町(松が枝岸壁)\n- 寄港船:最大 22 万トン級(クァンタム・オブ・ザ・シーズ+ MSC スプレンディダ等)\n- 年間寄港数:約 100 隻(2019 PRE COVID)\n- 来場:約 30 万人/年(外国人観光客)\n- 隣接観光:出島(徒歩 5 分)+ グラバー園(徒歩 5 分)+ 大浦天主堂(徒歩 5 分)\n- 周辺:松が枝臨港駐車場+ 軍艦島デジタルミュージアム\n- アクセス:長崎電軌「大浦海岸通り」電停 徒歩 1 分",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["ferry_terminal"],
    lat: 32.7361,
    lon: 129.8694,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nagasaki_island_routes", "international_terminal", "matsugae", "100_ships_per_year", "300k_tourists"],
    source: "manual",
  },
  {
    slug: "nagasaki-tour-rabbit-bus",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "長崎観光「ぐらばー号」(2 階建てオープントップバス・60 分周遊・¥800・観光主要地カバー)",
    title_ja: "ぐらばー号",
    romaji: "Glover Go",
    summary_zh: "**「ぐらばー号」は長崎観光の 2 階建てオープントップバス**(長崎駅前発・60 分周遊コース・¥800)。**長崎駅前 → 平和公園 → 浜の町 → 出島 → グラバー園 → 戻り** の主要観光地を 60 分でカバー、車内英中韓ガイド放送付。雨天時は屋根付バス、夏は涼しい朝便+ 夜景便もある。",
    content_md: "- 運営:長崎バス\n- 所要:60 分(周遊コース)\n- 料金:¥800(大人・子供 ¥400)\n- 1 日本数:平日 4 便+ 週末 6 便\n- ルート:長崎駅前 → 平和公園 → 浜の町 → 出島 → グラバー園 → 駅前\n- 車両:2 階建てオープントップバス(雨天時屋根付)\n- 言語:日英中韓ガイド放送\n- 夏期夜景便:18:30 出発・稲佐山経由\n- 予約:電話 + 当日窓口(乗車券 長崎駅観光案内所)\n- アクセス:JR 長崎駅前 バスターミナル",
    region: "kyushu",
    prefecture_ja: "長崎県",
    gun_ja: null,
    municipality_ja: "長崎市",
    lg_code: "42201",
    area_types: ["transit_hub"],
    lat: 32.7536,
    lon: 129.8717,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.nagasaki-bus.co.jp/" },
    tags: ["area_access_guide", "glover_go", "open_top_bus", "60min_tour", "800yen"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[nagasaki-r3] 尚無條目");
    return;
  }
  console.log(`[nagasaki-r3] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const byCat = new Map<string, number>();
    for (const r of rows) byCat.set(r.category, (byCat.get(r.category) ?? 0) + 1);
    for (const [k, v] of [...byCat.entries()].sort()) {
      console.log(`  ${k.padEnd(15)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[nagasaki-r3] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[nagasaki-r3] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[nagasaki-r3] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
