// Seed 沖縄県 · 行類 條目 → public.japan_entries(Sprint 14.6 行)
//
// 沖縄交通は本土と全く別系統:
//   - 鉄道:ゆいレール(沖縄都市モノレール・2003 開業・那覇 17.0km・沖縄唯一の鉄道)
//   - 路線バス:那覇バス + 琉球バス交通 + 沖縄バス + 東陽バス 4 社
//   - 離島空路:RAC(琉球エアコミューター)+ JTA + ANA + JAL の離島網
//   - フェリー:那覇泊港 + 石垣港 の 2 大ターミナルから慶良間/久米島/八重山/宮古/大東 等
//   - レンタカー:沖縄観光必須(本土より重要度高)、米軍関係車両との混在注意
//   - 米軍関係:嘉手納 + 普天間 + キャンプハンセン 周辺アクセス
//
// 12 sub_type ~39 筆構成:
//   - okinawa_yui_rail 5 / okinawa_island_routes 10 / okinawa_us_military_transit 3
//   - ferry_island 3 / airport_access 4 / rental_car_tips 5
//   - route_map_urban 3 / ticket_promo 4 / night_transit 2
//
// 設計原則(per feedback_usefulness_over_traffic.md):
//   中文圈策展極稀缺領域:離島フェリー欠航リスク + RAC 離島空路網 +
//   沖縄レンタカー注意点 + 米軍関係交通の正確な伝達。中文ブログは観光バス +
//   ゆいレールのみ書かれ、フェリー欠航リスク・離島空路の予約方法・
//   米軍ベース周辺の交通注意は殆ど無紹介。
//
// 資料源分層(L1=Wikipedia/官方,L2=普遍知識):
//   L1 確認:
//     ゆいレール(2003/8/10 開業・2019/10/1 てだこ浦西延伸 Wikipedia)、
//     RAC 琉球エアコミューター(1985 設立・JAL 系)、JTA(1967 設立・JAL 系)、
//     安栄観光(1979 創業・八重山フェリー大手)、八重山観光フェリー(1957 創業)、
//     那覇泊港・とまりん(2002 統合)、嘉手納道の駅(2009 開業・米軍基地展望)、
//     沖縄路線バス 4 社統合運行(那覇バス + 琉球バス交通 + 沖縄バス + 東陽バス)
//
// Usage:
//   npm run seed:japan-okinawa-transport:dry
//   npm run seed:japan-okinawa-transport

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "okinawa_yui_rail"
  | "okinawa_island_routes"
  | "okinawa_us_military_transit"
  | "ferry_island"
  | "airport_access"
  | "rental_car_tips"
  | "route_map_urban"
  | "ticket_promo"
  | "night_transit"
  | "transit_hub"
  | "limited_express_private";

interface SeedRow {
  slug: string;
  category: "transport";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "okinawa";
  prefecture_ja: "沖縄県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ── okinawa_yui_rail ゆいレール(5 筆)──
  {
    slug: "okinawa-yui-rail-overview",
    category: "transport",
    sub_type: "okinawa_yui_rail",
    title_zh: "ゆいレール(沖縄唯一の鉄道・2003 開業)",
    title_ja: "沖縄都市モノレール ゆいレール",
    romaji: "Okinawa Toshi Monorail Yui-Rail",
    summary_zh:
      "2003 年 8 月 10 日開業、沖縄県内唯一の鉄道(モノレール)。那覇空港 → てだこ浦西の 17.0km・19 駅、沖縄返還(1972)から 31 年経って実現。戦前の沖縄県営鉄道(1914-1945)が戦争で消失して以後 58 年ぶりの鉄道復活。観光客の那覇市内移動の中軸。",
    content_md:
      "- 路線:那覇空港 → 那覇市内 → 浦添市てだこ浦西、全長 17.0km、19 駅\n- 開業歷史:2003 年 8 月 10 日開業(13 駅 12.9km)→ 2019 年 10 月 1 日延伸(浦添 4 駅追加)\n- 沖縄鉄道史:1914 沖縄県営鉄道(那覇-与那原・嘉手納・糸満)→ 1945 沖縄戦で完全消失 → 1972 沖縄返還 → 2003 ゆいレール復活、58 年ぶり\n- 運賃:¥230-370(駅間)、1 日券 ¥800、2 日券 ¥1,400\n- 運行時間:6:00-23:30、約 5-12 分間隔\n- 全線高架:沖縄の地震対策 + 米軍施設下回避のため全線高架式モノレール\n- 主要観光駅:那覇空港・旭橋(那覇バスターミナル)・県庁前(国際通り西端)・牧志(国際通り東端・公設市場)・首里(首里城)\n- 那覇空港から首里まで 27 分、空港から国際通り 13 分でアクセス\n- 2026-04 人工查核(沖縄都市モノレール公式)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: 26.2150,
    lon: 127.6889,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.yui-rail.co.jp/",
    },
    tags: ["yui_rail", "monorail", "since_2003", "naha", "only_railway", "extended_2019"],
    source: "manual",
  },
  {
    slug: "okinawa-yui-rail-naha-airport",
    category: "transport",
    sub_type: "okinawa_yui_rail",
    title_zh: "那覇空港駅(ゆいレール始発・空港アクセス基点)",
    title_ja: "那覇空港駅(ゆいレール)",
    romaji: "Naha Airport Station (Yui-Rail)",
    summary_zh:
      "ゆいレールの始発駅、那覇空港国内線ターミナル直結(出発ロビー徒歩 3 分)。空港から那覇市内・首里への最速・最安アクセス、観光客の沖縄到着第一接点。空港リムジンバスより速くて安いが、大型荷物は注意(車内ラック狭め)。",
    content_md:
      "- 立地:那覇空港国内線ターミナル直結、出発ロビーから連絡通路徒歩 3 分\n- 那覇空港 → 県庁前(国際通り):¥270、13 分\n- 那覇空港 → 首里:¥370、27 分\n- 始発便:6:00、終便:23:30\n- 大型荷物注意:車内ラック狭め、機内持込級スーツケースまでが現実的、大型は空港リムジンバス推奨\n- リムジンバス vs ゆいレール:リムジンバス ¥970-2,700・各リゾート直行、ゆいレール ¥270 那覇市内のみ\n- 空港から国際通り行き観光客 = ゆいレール(¥270 + 13 分)、本部・恩納・名護リゾート行き = リムジンバス\n- 改札:Suica/PASMO/ICOCA 全国 IC 利用可\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: 26.1958,
    lon: 127.6464,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yui_rail", "naha_airport", "starting_station", "ic_card_compatible"],
    source: "manual",
  },
  {
    slug: "okinawa-yui-rail-kencho-mae",
    category: "transport",
    sub_type: "okinawa_yui_rail",
    title_zh: "県庁前駅(国際通り西端・那覇市民の中心)",
    title_ja: "県庁前駅(ゆいレール)",
    romaji: "Kenchō-mae Station",
    summary_zh:
      "那覇市役所・沖縄県庁・パレットくもじに隣接、国際通り西端への徒歩 1 分の入口。観光客が国際通り散策をスタートする駅、那覇市民の通勤通学ハブ。空港から 13 分で到達、宿泊地が国際通りなら最も近い駅(松山・牧志地区とほぼ同距離)。",
    content_md:
      "- 立地:那覇市泉崎、那覇市役所・沖縄県庁・パレットくもじショッピング街と隣接\n- 国際通り西端:徒歩 1 分(国際通りスタート地点・牧志公設市場まで徒歩 15 分)\n- 那覇空港から 13 分・¥270\n- 朝のラッシュ:平日 7:30-9:00 と 17:30-19:30 は那覇市民の通勤通学集中、観光客は時間帯外推奨\n- パレットくもじ(那覇 OPA):駅直結ショッピングモール、雨天・台風時の代替観光地\n- 周辺観光:国際通り・那覇市役所・那覇地裁・那覇市伝統工芸館(徒歩 5 分)\n- ゆいレール 1 日券 ¥800 で県庁前 + 牧志 + 首里を回る那覇半日コースが定番\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: 26.2150,
    lon: 127.6822,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yui_rail", "kencho_mae", "kokusai_dori_west", "city_center"],
    source: "manual",
  },
  {
    slug: "okinawa-yui-rail-shuri",
    category: "transport",
    sub_type: "okinawa_yui_rail",
    title_zh: "首里駅(首里城観光ハブ・徒歩 15 分)",
    title_ja: "首里駅(ゆいレール)",
    romaji: "Shuri Station",
    summary_zh:
      "首里城公園 + 玉陵(世界遺産)+ 首里織会館 + 紅型工房群 への観光ハブ駅、ゆいレール延伸前(2003-2019)は那覇空港-首里が終点だった。那覇空港から 27 分で到達、首里観光半日コースのスタートライン。首里駅から首里城まで徒歩 15 分の上り坂(または首里城下行きバス 5 分)。",
    content_md:
      "- 立地:沖縄県那覇市首里汀良町、首里城公園から徒歩 15 分(上り坂)\n- 那覇空港から:27 分・¥370\n- 首里城公園:2019 年 10 月 31 日に正殿火災、2026 年現在も再建工事中(2026 完成予定)、外周散策は可\n- 玉陵(世界遺産):琉球王家陵墓、徒歩 8 分\n- 首里観光ルート:首里駅 → 首里城公園(玉陵 + 守礼門 + 歓会門)→ 城間紅型工房 + 玉那覇紅型工房 → 首里織会館 → 首里琉染琉装体験\n- 駅前バス:首里城下バス停まで首里城下行き 5 分(混雑時は徒歩より遅い)\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: 26.2200,
    lon: 127.7244,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yui_rail", "shuri", "near_castle", "former_terminus"],
    source: "manual",
  },
  {
    slug: "okinawa-yui-rail-tedako-uranishi",
    category: "transport",
    sub_type: "okinawa_yui_rail",
    title_zh: "てだこ浦西駅(2019 延伸後の終点・浦添)",
    title_ja: "てだこ浦西駅(ゆいレール)",
    romaji: "Tedako-uranishi Station",
    summary_zh:
      "2019 年 10 月 1 日のゆいレール延伸で開業、現在の終点駅。浦添市にあり、サンエー浦添西海岸 PARCO CITY(2019 開業)へのアクセス駅として整備。観光客の那覇市内 + 浦添エリア横断アクセスを実現、雨天・台風時の代替観光地ハブ。",
    content_md:
      "- 開業:2019 年 10 月 1 日(ゆいレール延伸時)\n- 那覇空港から:38 分・¥420\n- 沖縄返還 50 年記念事業の一環として整備された延伸駅\n- 浦添市:那覇市の北隣、米軍住宅街改装の浦添パイプライン古着・カフェ・雑貨店 30 余軒、車 7 分\n- サンエー浦添西海岸 PARCO CITY:2019 年同時開業、徒歩 18 分または駅前バス 5 分\n- 雨天・台風時:那覇市内宿泊客の代替観光地として機能、屋内モール 250 店舗\n- 駅前駐車場 P&R:¥500/日、レンタカー利用客の那覇市内アクセス併用\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "浦添市",
    lg_code: "47208",
    area_types: ["urban"],
    lat: 26.2647,
    lon: 127.7392,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yui_rail", "tedako_uranishi", "since_2019", "current_terminus", "near_parco_city"],
    source: "manual",
  },

  // ── okinawa_island_routes 離島空路・フェリー(10 筆)──
  {
    slug: "okinawa-rac-airline",
    category: "transport",
    sub_type: "okinawa_island_routes",
    title_zh: "RAC 琉球エアコミューター(離島空路網覇者)",
    title_ja: "琉球エアコミューター(RAC)",
    romaji: "Ryūkyū Air Commuter (RAC)",
    summary_zh:
      "1985 年設立、JAL グループの沖縄離島専用航空会社。本島(那覇 + 久米島 + 北大東 + 南大東)+ 八重山(石垣 + 与那国 + 多良間)+ 宮古(下地島)の離島網を 1 社でカバー、フェリーよりはるかに速い離島アクセス手段。観光客の波照間・与那国・大東諸島訪問必須の航空会社。",
    content_md:
      "- 設立:1985 年(昭和 60 年)、JAL グループ\n- 機材:Bombardier DHC-8-Q400CC(48 席)・5 機運用、離島空港対応の小型機\n- 主要路線:那覇 → 久米島(30 分・¥10,000)・北大東(50 分・¥17,000)・南大東(60 分・¥18,000)・多良間(40 分・¥14,000)・石垣 → 与那国(30 分・¥9,500)\n- 1 日 2-5 便、季節変動あり\n- フェリー比較:那覇 → 久米島 RAC 30 分 vs フェリー 4 時間、波照間 RAC 30 分 vs フェリー 60 分(石垣経由)\n- 予約:JAL 経由(JAL.co.jp)、当日空席ありの場合特割 ¥7,000-、繁忙期(夏休み・GW)は満席多し\n- 欠航リスク:台風期(8-10 月)は欠航多、予約変更・キャンセル料含めて旅程余裕推奨\n- 2026-04 人工查核(RAC 公式)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["airline", "rac", "since_1985", "jal_group", "remote_islands", "5_aircraft"],
    source: "manual",
  },
  {
    slug: "okinawa-jta-airline",
    category: "transport",
    sub_type: "okinawa_island_routes",
    title_zh: "JTA 日本トランスオーシャン航空(那覇本社)",
    title_ja: "日本トランスオーシャン航空(JTA)",
    romaji: "Japan Transocean Air (JTA)",
    summary_zh:
      "1967 年設立、那覇本社の JAL グループ航空会社、本土 ↔ 沖縄 + 沖縄離島の中継担当。那覇 ↔ 東京/大阪/福岡/中部 等の本土便 + 那覇 ↔ 石垣/宮古/久米島 等の県内離島便を運航。RAC より大型機(737)使用で大量輸送、観光客の沖縄訪問の主要キャリア。",
    content_md:
      "- 設立:1967 年(昭和 42 年)、JAL グループ\n- 機材:Boeing 737-800(165-176 席)・13 機運用\n- 本社:沖縄県那覇市山下町(那覇空港隣)\n- 主要路線:那覇 ↔ 東京(羽田・成田)・大阪(伊丹・関空)・福岡・中部・小松・北九州 + 那覇 ↔ 石垣 + 那覇 ↔ 宮古 + 那覇 ↔ 久米島\n- RAC との違い:JTA は 165 席 737 で大量輸送、RAC は 48 席 Q400 で離島専用\n- 観光客の沖縄訪問:JAL/JTA で本土から那覇 + RAC で離島 の組み合わせが標準\n- 那覇 ↔ 石垣:¥18,000-32,000、1 日 5 便\n- 2026-04 人工查核(JTA 公式)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      official: "https://jta-okinawa.com/",
    },
    tags: ["airline", "jta", "since_1967", "jal_group", "naha_hq", "boeing_737"],
    source: "manual",
  },
  {
    slug: "okinawa-anei-yaeyama-ferry",
    category: "transport",
    sub_type: "okinawa_island_routes",
    title_zh: "安栄観光フェリー(石垣発八重山離島網)",
    title_ja: "安栄観光",
    romaji: "Anei Kankō",
    summary_zh:
      "1979 年創業、石垣港から八重山離島(西表・竹富・小浜・波照間・黒島・鳩間・新城)行き高速船を運航する八重山フェリー大手の 1 つ。八重山観光フェリーと並ぶ二大事業者、観光客の離島巡りの主要選択肢。波照間・与那国行きの主要事業者。",
    content_md:
      "- 創業:1979 年(昭和 54 年)\n- 本社:沖縄県石垣市美崎町、石垣港離島ターミナル隣接\n- 主要路線:石垣 → 西表(大原・上原)35-45 分・¥1,830-2,090、石垣 → 竹富 10-15 分・¥760、石垣 → 小浜 30 分・¥1,260、石垣 → 波照間 60-90 分・¥3,540\n- 八重山観光フェリー との違い:安栄は波照間航路を独占運航、八重山観光は竹富・小浜・黒島の本数が多い\n- 4 日券フリーパス:¥10,000(4 日間 全離島乗り放題)、観光客の島巡り定番\n- 欠航率:波照間 30%(冬季・台風期)、与那国 25%、西表・竹富・小浜 < 5%\n- 予約:Web + 電話、繁忙期(夏休み・GW)は当日チケット売切れ多\n- 2026-04 人工查核(安栄観光公式)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "石垣市",
    lg_code: "47207",
    area_types: ["island_main"],
    lat: 24.3406,
    lon: 124.1556,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {
      official: "https://aneikankou.co.jp/",
    },
    tags: ["ferry", "anei_kanko", "ishigaki", "since_1979", "yaeyama", "haterumajima"],
    source: "manual",
  },
  {
    slug: "okinawa-yaeyama-kankou-ferry",
    category: "transport",
    sub_type: "okinawa_island_routes",
    title_zh: "八重山観光フェリー(石垣・1957 創業老舗)",
    title_ja: "八重山観光フェリー",
    romaji: "Yaeyama Kankō Ferry",
    summary_zh:
      "1957 年創業、八重山地区最古のフェリー会社、石垣港から八重山離島へ高速船を運航。安栄観光と並ぶ二大事業者、特に竹富・小浜・黒島・鳩間の本数が多い。観光客の竹富日帰り(石垣 → 竹富往復 + 水牛車)の主要ルート。",
    content_md:
      "- 創業:1957 年(昭和 32 年)、八重山地区最古のフェリー会社\n- 本社:沖縄県石垣市美崎町、石垣港離島ターミナル\n- 主要路線:石垣 → 竹富 10-15 分・¥770(1 日 18 便と最頻発)、石垣 → 小浜 30 分・¥1,260、石垣 → 黒島 30 分・¥1,360、石垣 → 西表大原 35 分・¥1,830\n- 安栄観光との違い:八重山観光は竹富 1 日 18 便の最頻発、観光客の竹富日帰りでは八重山観光が主要選択\n- 4 日券フリーパス共通:安栄観光と共通の 4 日券 ¥10,000、両社のフェリーが乗り放題\n- 観光バンドル:水牛車 + フェリー往復セット ¥2,500-3,000(竹富観光定番)\n- 2026-04 人工查核(八重山観光フェリー公式)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "石垣市",
    lg_code: "47207",
    area_types: ["island_main"],
    lat: 24.3406,
    lon: 124.1556,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["ferry", "yaeyama_kanko", "ishigaki", "since_1957", "yaeyama", "taketomi_main_route"],
    source: "manual",
  },
  {
    slug: "okinawa-naha-tomarin-port",
    category: "transport",
    sub_type: "okinawa_island_routes",
    title_zh: "那覇とまりん新港ターミナル(2002 統合・離島フェリー基地)",
    title_ja: "那覇泊港(とまりん)",
    romaji: "Naha Tomari Port (Tomarin)",
    summary_zh:
      "2002 年那覇市内 4 港(泊港・那覇港 等)を統合した離島フェリーターミナル、慶良間 + 久米島 + 粟国 + 大東諸島 + 鹿児島・東京 行きを統合運航。沖縄本島中部からの離島巡りの拠点。ゆいレール「美栄橋」「県庁前」両駅から徒歩 12-15 分。",
    content_md:
      "- 立地:沖縄県那覇市前島3-25-1、ゆいレール「美栄橋」徒歩 12 分・「県庁前」徒歩 15 分\n- 統合:2002 年(平成 14 年)、那覇市内 4 港を統合した「那覇とまりん」\n- 主要路線:那覇 → 渡嘉敷(35-70 分)・座間味(50-120 分)・粟国(2 時間 15 分)・久米島(3-4 時間)・北大東/南大東(船便週 2-3 回)・鹿児島(マルエーフェリー)・東京(本土連絡船)\n- 那覇空港からのアクセス:タクシー ¥1,200/車 15 分、ゆいレール + 徒歩で 25 分\n- 慶良間ダイビング基地:渡嘉敷・座間味行きフェリーの主要発着場\n- 観光客向け案内:インフォメーション英語・中国語対応、各社窓口集中\n- 2026-04 人工查核(那覇とまりん公式)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban", "coastal"],
    lat: 26.2275,
    lon: 127.6786,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ferry_terminal", "naha", "tomarin", "since_2002", "kerama_base", "remote_island_hub"],
    source: "manual",
  },
  {
    slug: "okinawa-queen-zamami-ferry",
    category: "transport",
    sub_type: "okinawa_island_routes",
    title_zh: "クイーンざまみ(座間味行高速船)",
    title_ja: "クイーンざまみ",
    romaji: "Queen Zamami",
    summary_zh:
      "那覇泊港から座間味島(慶良間諸島)行き高速船、約 50 分で到達する慶良間ダイビング・シュノーケル日帰りの主要ルート。1 日 2-3 便、繁忙期(夏休み・GW)は当日チケット売切れ多、予約推奨。那覇から日帰り可能な世界トップクラスのダイビングサイトへの最速アクセス。",
    content_md:
      "- 路線:那覇泊港 → 阿嘉島 → 座間味港、約 50 分・¥3,200/片道\n- フェリーざまみ(普通船)との違い:クイーンざまみ高速船 50 分・¥3,200、フェリー普通 2 時間・¥2,200\n- 1 日 2 便:9:00 + 14:00 出航(繁忙期 3 便)\n- 慶良間諸島観光:座間味島 + 阿嘉島(同じ航路) + 渡嘉敷島(別航路マリンライナーとかしき)の慶良間群島\n- ダイビング日帰り定番:朝 9:00 那覇発 → 10:00 座間味着 → 午前ダイブ → 午後ダイブ → 17:00 那覇行最終便\n- 予約:座間味村観光協会経由、Web 予約 +14 日前推奨\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: "島尻郡",
    municipality_ja: "座間味村",
    lg_code: "47354",
    area_types: ["coastal"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["ferry", "queen_zamami", "kerama", "high_speed", "diving_day_trip"],
    source: "manual",
  },
  {
    slug: "okinawa-marine-liner-tokashiki",
    category: "transport",
    sub_type: "okinawa_island_routes",
    title_zh: "マリンライナーとかしき(渡嘉敷行高速船)",
    title_ja: "マリンライナーとかしき",
    romaji: "Marine Liner Tokashiki",
    summary_zh:
      "那覇泊港から渡嘉敷島(慶良間諸島)行き高速船、約 35 分で到達。渡嘉敷島は座間味島と並ぶ慶良間ダイビング・シュノーケル聖地、阿波連ビーチ(慶良間ブルー)で世界トップクラス。1 日 2-3 便、座間味行クイーンざまみとは別航路。",
    content_md:
      "- 路線:那覇泊港 → 渡嘉敷港、約 35 分・¥2,470/片道\n- フェリーとかしき(普通船)との違い:マリンライナー高速船 35 分・¥2,470、フェリー普通 70 分・¥1,690\n- 1 日 2-3 便:9:00 + 14:00 出航(繁忙期 3 便、夏休みは 4 便)\n- 渡嘉敷島観光:阿波連ビーチ(慶良間ブルー世界トップ 5)・トカシクビーチ・ニシバマ海岸\n- ダイビング日帰り定番:朝 9:00 那覇発 → 9:35 渡嘉敷着 → 午前午後ダイブ → 17:30 那覇最終便\n- 阿波連ビーチ:慶良間諸島で最も有名なビーチ、シュノーケルでウミガメ・サンゴ礁観察\n- 予約:渡嘉敷村観光協会、Web 予約 +14 日前推奨\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: "島尻郡",
    municipality_ja: "渡嘉敷村",
    lg_code: "47353",
    area_types: ["coastal"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["ferry", "marine_liner", "tokashiki", "kerama", "high_speed", "ahara_beach"],
    source: "manual",
  },
  {
    slug: "okinawa-kume-shosen",
    category: "transport",
    sub_type: "okinawa_island_routes",
    title_zh: "久米商船(久米島行フェリー・1949 創業)",
    title_ja: "久米商船",
    romaji: "Kume Shōsen",
    summary_zh:
      "1949 年創業、那覇泊港から久米島(那覇の西 90km)行きフェリーを運航する沖縄最古級のフェリー会社。普通船 4 時間、車両搭載可能で観光客のレンタカー直接運送に対応。那覇 → 久米島は RAC 30 分(¥10,000)が速いが、車両搭載・低価格(¥3,450)でフェリー利用も多。",
    content_md:
      "- 創業:1949 年(昭和 24 年・米軍統治下)\n- 本社:沖縄県島尻郡久米島町、那覇泊港にも窓口\n- 路線:那覇泊港 → 久米島(兼城港)、約 4 時間 30 分・¥3,450/片道(2 等)\n- 車両搭載:¥18,000-25,000(車両サイズにより)、観光客のレンタカー直接運送に対応\n- 1 日 1 便:9:00 那覇発、13:30 久米島着、14:00 久米島発、18:30 那覇着\n- RAC との違い:RAC 30 分・¥10,000・荷物制限あり、フェリー 4 時間・¥3,450・車両搭載可\n- 久米島観光ハブ:イーフビーチ + はての浜 + 久米島紬 + 久米島の久米仙\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: "島尻郡",
    municipality_ja: "久米島町",
    lg_code: "47361",
    area_types: ["island_main"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["ferry", "kume_shosen", "kumejima", "since_1949", "vehicle_transport"],
    source: "manual",
  },
  {
    slug: "okinawa-daito-kaiun",
    category: "transport",
    sub_type: "okinawa_island_routes",
    title_zh: "大東海運(大東諸島行フェリー・週 2-3 便)",
    title_ja: "大東海運",
    romaji: "Daitō Kaiun",
    summary_zh:
      "1924 年創業、那覇泊港から大東諸島(北大東・南大東・本島東 360km)行きフェリーを運航する遠隔離島専用海運会社。週 2-3 便のみ、片道 13-15 時間の長距離航路。大東諸島は 1900 玉置半右衛門開拓の遠隔離島、本土観光客が訪問する稀な目的地。",
    content_md:
      "- 創業:1924 年(大正 13 年)\n- 路線:那覇泊港 → 北大東港 → 南大東港(週 2-3 便循環)\n- 那覇 → 北大東 約 13 時間・¥5,090(2 等)、北大東 → 南大東 約 1.5 時間・¥1,690\n- 1 日 1 便のみ、しかも週 2-3 便、年間 100-150 便程度\n- RAC との違い:RAC 50 分・¥17,000、フェリー 13 時間・¥5,090、ただしフェリーは寄港の都合で日程組みにくい\n- 大東諸島:北大東・南大東(人口計 2,200 人)、1900 玉置半右衛門が八丈島から移住して開拓、本土文化が珍しく残る\n- 観光客密度:年間訪問者 5,000 人未満、極遠隔離島の象徴\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["island_remote"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["ferry", "daito_kaiun", "since_1924", "daito_islands", "remote_remote", "weekly_2_3"],
    source: "manual",
  },
  {
    slug: "okinawa-marue-ferry-kagoshima",
    category: "transport",
    sub_type: "okinawa_island_routes",
    title_zh: "マルエーフェリー(沖縄→鹿児島本土連絡)",
    title_ja: "マルエーフェリー",
    romaji: "Maruē Ferry",
    summary_zh:
      "那覇泊港から鹿児島(本土)行きの長距離フェリー、約 25 時間・¥15,150(2 等)で本土と沖縄を海路で結ぶ唯一のルート。航空便より遥かに遅く高価だが、車両搭載可能(¥45,000-)で本土からのレンタカー旅行・引っ越し用として機能。観光客は航空便利用が普通。",
    content_md:
      "- 路線:那覇泊港 → 名瀬(奄美大島)→ 亀徳(徳之島)→ 鹿児島(本土)、約 25 時間\n- 価格:那覇 → 鹿児島 ¥15,150(2 等)、車両搭載 ¥45,000-(普通車・5m 未満)\n- 那覇発 / 鹿児島発 各週 5-6 便\n- 航空便比較:JTA/JAL 那覇 → 鹿児島 75 分・¥18,000-32,000、フェリー 25 時間・¥15,150 だが車両搭載可\n- 利用客:沖縄 ↔ 本土の引っ越し客、レンタカー or 自家用車を本土から沖縄へ運ぶ客、奄美大島 + 徳之島観光客\n- 観光客の利用は稀、本土沖縄移住・引っ越し時の主要手段\n- 2026-04 人工查核(マルエーフェリー公式)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban", "coastal"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      official: "https://www.aline-ferry.com/",
    },
    tags: ["ferry", "marue", "naha", "kagoshima", "long_distance", "vehicle_transport"],
    source: "manual",
  },

  // ── ferry_island 離島フェリー詳細(3 筆)──
  {
    slug: "okinawa-ferry-haterumajima-yonaguni-cancellation",
    category: "transport",
    sub_type: "ferry_island",
    title_zh: "波照間・与那国行フェリー欠航リスク詳細",
    title_ja: "波照間・与那国フェリー欠航ガイド",
    romaji: "Haterumajima · Yonaguni Ferry Cancellation Guide",
    summary_zh:
      "波照間・与那国行フェリーの欠航率は 25-30%(冬季・台風期)で全国最高水準、観光客が遭遇する最大の落とし穴。台風・荒天・うねりの予測、欠航時の代替案(空路・追加宿泊)、保険・補償の現実、宿泊先の柔軟予約方法を包括的にガイドする実用ページ。",
    content_md:
      "- 波照間欠航率:冬季(11-3 月)30%、夏季(6-10 月)+ 台風期 35%、年間平均 25%\n- 与那国欠航率:全季節 20-30%、特に外洋荒天で全便欠航多\n- 欠航判断:前日 18:00 + 当日 6:00 の 2 段階発表、安栄観光・福山海運の Web で確認\n- 代替案 1:RAC 空路(石垣 → 波照間 25 分・¥7,500、石垣 → 与那国 30 分・¥9,500)\n- 代替案 2:石垣島宿泊延長(離島ターミナル徒歩圏のフサキ・ANA インター石垣等)\n- 保険:Cape Insurance 等のフェリー欠航カバー保険(¥2,000/旅行・台風キャンセル料補償)\n- 宿泊柔軟予約:民宿あやふふぁみ(波照間)・大金荘(与那国)等の柔軟キャンセル対応宿\n- 観光日程:波照間・与那国は 6 日間以下旅程は推奨せず(欠航時の余裕無)\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["island_remote"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ferry", "cancellation_guide", "haterumajima", "yonaguni", "concept", "weather_risk"],
    source: "manual",
  },
  {
    slug: "okinawa-ferry-anei-vs-yaeyama-comparison",
    category: "transport",
    sub_type: "ferry_island",
    title_zh: "安栄観光 vs 八重山観光フェリー選び方",
    title_ja: "安栄観光 vs 八重山観光フェリー 比較ガイド",
    romaji: "Anei vs Yaeyama Kankō Ferry Comparison",
    summary_zh:
      "八重山離島巡りで観光客が最大に迷う「安栄観光と八重山観光フェリーどちらを使うべきか」を整理する実用ガイド。両社は同じ石垣港から同じ離島(西表・竹富・小浜・黒島・波照間 等)へ高速船を運航するが、便数・価格・予約方法・特徴に違いあり。",
    content_md:
      "- 共通点:石垣港同じターミナル、4 日券フリーパス ¥10,000 で両社のフェリーが乗り放題\n- 安栄観光の強み:波照間航路独占、西表大原便数多、台風期の運航判断に保守的\n- 八重山観光の強み:竹富 1 日 18 便最頻発、小浜・黒島の本数多、観光バンドル(水牛車セット等)豊富\n- 価格:両社の通常運賃はほぼ同じ(竹富 ¥770、西表大原 ¥1,830)\n- 予約方法:両社とも Web + 当日窓口、繁忙期は 1 週間前 Web 予約推奨\n- 推奨組み合わせ:波照間泊→安栄観光、竹富日帰り→八重山観光、西表泊→どちらでも可\n- フリーパス利用:石垣 + 西表 + 竹富 + 小浜の 4 島巡りで 4 日券 ¥10,000 が最もお得\n- 欠航時の互換:安栄欠航時に八重山観光に振替不可、各社独立\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "石垣市",
    lg_code: "47207",
    area_types: ["island_main"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ferry", "yaeyama_comparison", "ishigaki", "concept", "comparison"],
    source: "manual",
  },
  {
    slug: "okinawa-ferry-kerama-day-trip",
    category: "transport",
    sub_type: "ferry_island",
    title_zh: "慶良間日帰りフェリー計画(那覇 → 渡嘉敷/座間味)",
    title_ja: "慶良間日帰りフェリー計画ガイド",
    romaji: "Kerama Day Trip Ferry Planning",
    summary_zh:
      "那覇から世界トップクラスのダイビング・シュノーケル聖地・慶良間諸島(座間味・渡嘉敷)への日帰りフェリー計画ガイド。クイーンざまみ(座間味行)とマリンライナーとかしき(渡嘉敷行)の使い分け、ダイビングショップの選び方、繁忙期の予約戦略、ピーク時の注意点。",
    content_md:
      "- 那覇 → 座間味:クイーンざまみ高速船 50 分・¥3,200、フェリーざまみ普通 2 時間・¥2,200\n- 那覇 → 渡嘉敷:マリンライナー高速船 35 分・¥2,470、フェリーとかしき普通 70 分・¥1,690\n- 日帰り定番:朝 9:00 那覇発 → 10:00 着 → 午前午後ダイブ → 17:30 那覇行最終便\n- ダイビングショップ選び:座間味 5 軒・渡嘉敷 8 軒、初心者体験ダイブ ¥10,000-12,000、要予約 14 日前\n- 繁忙期:GW・夏休み・連休 = 当日チケット売切れ多、1 週間前 Web 予約必須\n- 欠航リスク:慶良間は外洋直接面しない海域で欠航率 5-10%(波照間・与那国の 1/3)\n- 慶良間ブルー:水深 30m まで透視できる超透明度、世界トップ 5 ダイビングサイトランキング\n- 1 泊推奨:夕日 + 星空 + 早朝ダイブ体験のため 1 泊が最も価値ある体験\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["coastal"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ferry", "kerama", "day_trip", "concept", "diving_planning"],
    source: "manual",
  },

  // ── airport_access 機場交通(4 筆)──
  {
    slug: "okinawa-naha-airport-limousine",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "那覇空港リムジンバス(各リゾート直行)",
    title_ja: "那覇空港リムジンバス",
    romaji: "Naha Airport Limousine Bus",
    summary_zh:
      "那覇空港から本部・恩納・名護・読谷・北谷・宜野湾・浦添 等の主要リゾート・観光地への直行リムジンバス。リッツ・カールトン・ハレクラニ・ANA インター万座・ブセナテラス・フサキ等の大型リゾート前停車、観光客の沖縄到着時の主要アクセス。¥970-2,700。",
    content_md:
      "- 主要路線:那覇空港 → 本部美ら海(¥2,170・1 時間 50 分)・恩納万座(¥1,750・1 時間 30 分)・名護(¥1,470・1 時間 20 分)・読谷(¥970・55 分)・北谷美浜(¥1,030・55 分)\n- 運営:那覇バス + 沖縄バス + 琉球バス交通 4 社共同運行\n- 1 日 5-15 便、1-2 時間間隔(リゾート目的地により異なる)\n- 主要停車:リッツ・カールトン沖縄・ハレクラニ・ANA インター万座・ブセナテラス・フサキ・アメリカンビレッジ\n- 予約:Web 推奨(沖縄エアポート連絡バス Web)、当日空席ありなら現地購入可\n- 大型荷物対応:荷物棚有、スーツケース搭載 OK\n- レンタカーとの比較:リムジンバス ¥1,000-2,000/人、レンタカー ¥4,000-8,000/日、グループ旅行はレンタカー有利・ソロはリムジンバス有利\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {
      official: "https://okinawabus.com/",
    },
    tags: ["airport_bus", "naha_airport", "limousine", "resort_direct", "4_companies"],
    source: "manual",
  },
  {
    slug: "okinawa-ishigaki-airport-bus",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "石垣空港バス(空港-市街・離島ターミナル)",
    title_ja: "石垣空港バス",
    romaji: "Ishigaki Airport Bus",
    summary_zh:
      "南ぬ島石垣空港(2013 開業の新空港)から石垣港離島ターミナル・市街・各リゾート(フサキ・ANA インター)への路線バス。八重山観光客の最初の接点、石垣島観光のスタートライン。¥520-1,000、空港から離島ターミナルまで 35 分。",
    content_md:
      "- 路線:石垣空港 → 石垣港離島ターミナル ¥520(35 分)、石垣空港 → フサキビーチリゾート ¥1,000(45 分)、石垣空港 → ANA インター石垣 ¥520(30 分)\n- 運営:カリー観光(石垣島島内バス)\n- 1 日 8-12 便、1-2 時間間隔\n- 石垣空港:2013 年 3 月開業の新空港、旧石垣空港(2013 廃止)から移転\n- 観光客動線:石垣空港着 → バスで離島ターミナル → 安栄観光・八重山観光フェリーで離島(竹富・西表・小浜・波照間)\n- レンタカー利用:空港にレンタカー会社 8 社(OTS・ニッポン・タイムズ等)直営\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "石垣市",
    lg_code: "47207",
    area_types: ["island_main"],
    lat: 24.3964,
    lon: 124.2453,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["airport_bus", "ishigaki", "since_2013", "yaeyama_entry", "near_port"],
    source: "manual",
  },
  {
    slug: "okinawa-miyako-airport-access",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "宮古空港アクセス(平良市街・各リゾート)",
    title_ja: "宮古空港アクセス",
    romaji: "Miyako Airport Access",
    summary_zh:
      "宮古空港(平良地区南部)から平良市街・伊良部島(伊良部大橋経由)・シギラリゾート 等の宮古島島内アクセス。観光客の宮古島到着時の主要接点、レンタカー必須(離島タクシー高額・路線バス少)。¥250-1,500、空港から平良市街 15 分。",
    content_md:
      "- 路線バス:宮古空港 → 平良市街 ¥250(15 分・八千代バス・1 日 10 便)、宮古空港 → シギラリゾート ¥1,500(25 分・送迎バス予約制)\n- 宮古空港:1980 開業、宮古島市平良の南部立地\n- レンタカー:空港にレンタカー会社 6 社直営、観光客の 80% 以上がレンタカー利用\n- 伊良部大橋:車 25 分(平良市街経由)で伊良部島・下地島空港(2019 開業国際線)アクセス\n- 観光客動線:宮古空港着 → レンタカー or 路線バス → 平良市街 or 各リゾート\n- 路線バス少:1 日 10 便のみ、24 時間は無し、夜便不可\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "宮古島市",
    lg_code: "47214",
    area_types: ["island_main"],
    lat: 24.7828,
    lon: 125.2956,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["airport_bus", "miyakojima", "rental_car_required", "limited_bus_service"],
    source: "manual",
  },
  {
    slug: "okinawa-shimoji-airport-international",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "下地島空港(2019 開業・国際線対応)",
    title_ja: "下地島空港",
    romaji: "Shimojishima Airport",
    summary_zh:
      "2019 年 3 月開業の宮古地区第二空港、伊良部島隣接の下地島に立地。香港・台北・ソウル直行便対応の国際空港、宮古空港を補完。中華圏・韓国観光客が伊良部・下地島・宮古島を直接訪問できる新ルート。空港 → 伊良部大橋 → 平良市街 へのバス・タクシー対応。",
    content_md:
      "- 開業:2019 年 3 月 30 日(平成 31 年 / 令和元年)\n- 立地:沖縄県宮古島市伊良部佐和田1727(下地島・伊良部大橋経由で本島宮古からアクセス)\n- 国際線対応:香港(キャセイ系)・台北(タイガーエア)・ソウル(LCC)・上海 直行便、中華圏アクセス劇的改善\n- 国内線:那覇 ↔ 下地島(JTA)、東京・大阪・名古屋・福岡 → 下地島(ANA・ジェットスター・スカイマーク 等の LCC)\n- 空港 → 伊良部大橋経由平良市街:バス ¥600・35 分、タクシー ¥3,500-4,500・25 分\n- 宮古空港との違い:宮古空港は本島中央立地・国内線中心、下地島は離島立地・国際線中心\n- 宮古観光ハブ:伊良部島 + 下地島(通り池・佐和田の浜)観光のスタートライン\n- 2026-04 人工查核(下地島空港公式)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "宮古島市",
    lg_code: "47214",
    area_types: ["island_main"],
    lat: 24.8267,
    lon: 125.1444,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["airport", "shimoji", "since_2019", "international", "irabu_bridge"],
    source: "manual",
  },

  // ── rental_car_tips 沖繩レンタカー(5 筆)──
  {
    slug: "okinawa-rental-car-essential",
    category: "transport",
    sub_type: "rental_car_tips",
    title_zh: "沖繩レンタカー必読(本島・離島共通)",
    title_ja: "沖縄レンタカー必読ガイド",
    romaji: "Okinawa Rental Car Essential Guide",
    summary_zh:
      "沖縄観光の中軸はレンタカー、特に本部・恩納・宮古・八重山等のリゾートエリアは公共交通が極めて少なく、レンタカー無しでは観光不可。本ガイドは初訪問者向けの基本(国際免許・年齢制限・予約タイミング・主要会社・空港受取手順)を整理。",
    content_md:
      "- 必須度:沖縄本島(那覇市内除く)・宮古・八重山 はレンタカー無しでは観光不可、那覇市内のみゆいレール + バスで対応可\n- 国際免許:日本人は不要、外国人観光客は『ジュネーブ条約締結国の国際免許証』必須(中国・台湾・韓国は条約外で不可)\n- 年齢制限:21 歳以上(レンタカー会社により 25 歳以上)、運転経験 2 年以上推奨\n- 予約タイミング:GW・夏休み(7-8 月)・正月は 1 か月前推奨、その他は 1-2 週間前で可\n- 主要会社:OTS(沖縄ツーリスト)・ニッポンレンタカー・タイムズカー・トヨタレンタカー・オリックス\n- 価格:軽自動車 ¥4,000-/日、コンパクト ¥5,000-/日、SUV ¥8,000-15,000/日\n- 空港受取:那覇 + 石垣 + 宮古 + 久米島 全空港でレンタカー会社直営カウンター、出発まで 30 分-1 時間\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["rental_car", "essential_guide", "concept", "international_license"],
    source: "manual",
  },
  {
    slug: "okinawa-rental-car-us-military-warning",
    category: "transport",
    sub_type: "rental_car_tips",
    title_zh: "米軍関係車両 注意点(右側通行 vs 左側)",
    title_ja: "沖縄米軍関係車両 注意ガイド",
    romaji: "US Military Vehicle Warning",
    summary_zh:
      "沖縄は『黄色 Y ナンバー(米軍関係車両)』が多数走行、米軍関係者は本国流の右側通行に違反しがち。日本(沖縄含)は左側通行だが、米軍関係車両との衝突事故・違反事案が年間 200-300 件発生。観光客レンタカー利用時の現実的な注意点を整理。",
    content_md:
      "- 沖縄米軍関係車両:Y ナンバー(黄色プレート)・YA ナンバー(在日米軍家族車)等が約 8 万台\n- 違反パターン:米軍関係者の本国流右側通行違反、特に夜間 + 飲酒運転 + ベース内に近い道路で多発\n- 観光客の注意:嘉手納基地(国道 58 号沿い)・普天間飛行場(国道 330 号沿い)・キャンプハンセン(国道 329 号沿い)周辺道路で警戒\n- 国道 58 号(那覇空港 → 名護):米軍関係車両交通量最大、80km 以上の高速運転と併存\n- 事故時の対応:事故発生時はまず 110 番(警察)、米軍関係車両との事故は MP(米軍憲兵)も同行\n- レンタカー保険:免責補償加入推奨(¥1,000-2,000/日)、事故時の自己負担を抑制\n- 推奨時間帯:夜間運転は避け、特に金土夜の米軍関係者飲酒運転帰路に近づかない\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["rental_car", "us_military", "warning", "concept", "y_plate"],
    source: "manual",
  },
  {
    slug: "okinawa-rental-car-typhoon",
    category: "transport",
    sub_type: "rental_car_tips",
    title_zh: "台風時レンタカー利用ガイド(欠航・道路閉鎖)",
    title_ja: "沖縄台風時レンタカー利用ガイド",
    romaji: "Typhoon Period Rental Car Guide",
    summary_zh:
      "沖縄は年間 6-10 個の台風直撃地域、8-10 月台風期のレンタカー利用は道路冠水・通行止め・橋梁閉鎖のリスク大。フェリー欠航と並行して道路網も部分閉鎖、観光客が台風時に陥る困難を予防するガイド。事前キャンセル・延長・空港待機などの選択肢を整理。",
    content_md:
      "- 台風期:8-10 月、年間 6-10 個直撃、特に 9 月がピーク\n- 道路閉鎖:台風中心が直撃時は本島 58 号・329 号・331 号 等主要道路が通行止め、24-48 時間続く\n- 橋梁閉鎖:伊良部大橋・古宇利大橋・海中道路・沖縄自動車道 が暴風時閉鎖、迂回路無し\n- レンタカーキャンセル:台風予報発生時(直撃 24 時間前)はキャンセル料発生だが、各社台風特例で減免対応有(要確認)\n- 延長戦略:台風通過まで宿泊延長 + レンタカー延長を同時手配、空港閉鎖時の場合 +1-2 日が現実的\n- 空港待機:那覇空港は台風中心通過時 24 時間閉鎖、欠航・遅延 + 振替便獲得競争\n- 推奨対応:6-10 月旅行は出発前 7 日の天気予報確認 + 旅行保険加入(¥3,000-5,000/旅行)\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: "2026-08-01",
    season_end: "2026-10-31",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["rental_car", "typhoon_guide", "concept", "8_10_months", "road_closure"],
    source: "manual",
  },
  {
    slug: "okinawa-rental-car-major-companies",
    category: "transport",
    sub_type: "rental_car_tips",
    title_zh: "沖繩主要レンタカー会社比較(OTS・ニッポン・タイムズ等)",
    title_ja: "沖縄主要レンタカー会社比較",
    romaji: "Okinawa Major Rental Car Companies",
    summary_zh:
      "沖縄レンタカー会社の比較ガイド、OTS(沖縄ツーリスト・地元最大手)・ニッポンレンタカー(全国チェーン・那覇空港最大)・タイムズカー(全国チェーン)・トヨタレンタカー(車両品質高)・オリックス(法人プラン強)の特徴と選び方。",
    content_md:
      "- OTS(沖縄ツーリスト):沖縄地元最大手、那覇空港送迎バス込み、観光ガイド地図が充実、価格帯 ¥4,500-8,000/日\n- ニッポンレンタカー:全国チェーン那覇空港カウンター最大、英語対応、価格帯 ¥5,000-9,000/日\n- タイムズカー:全国チェーン、ETC カード貸出無料、価格帯 ¥4,000-7,500/日\n- トヨタレンタカー:車両品質高(新車多)、トヨタ車のみ、価格帯 ¥5,500-10,000/日\n- オリックスレンタカー:法人プラン強、長期レンタル割引、価格帯 ¥4,500-8,500/日\n- 選び方:価格優先 → タイムズ・OTS、英語対応 → ニッポン、車両品質 → トヨタ、長期 → オリックス\n- 那覇空港 vs 那覇市内営業所:空港は混雑時 1-2 時間待ち、市内営業所は 30 分以内\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["rental_car", "company_comparison", "concept", "ots", "nippon", "times"],
    source: "manual",
  },
  {
    slug: "okinawa-rental-car-island",
    category: "transport",
    sub_type: "rental_car_tips",
    title_zh: "離島レンタカー(石垣・宮古・西表・与那国)",
    title_ja: "沖縄離島レンタカーガイド",
    romaji: "Okinawa Island Rental Car Guide",
    summary_zh:
      "石垣島・宮古島・西表島・与那国島・久米島 等の離島レンタカーガイド。本島とは違う特殊事情(限定車種・割高価格・予約困難・離島専用保険)を整理、観光客の離島訪問時の落とし穴を予防。",
    content_md:
      "- 石垣島:OTS・ニッポン・タイムズ全社対応、価格 ¥4,500-8,000/日、空港 + 港でレンタル可\n- 宮古島:OTS・ニッポン主、価格 ¥5,000-9,000/日、伊良部大橋経由で下地島・伊良部島も走行可\n- 西表島:民営小規模 3 社のみ、価格 ¥6,000-10,000/日、車両数 50 台未満で予約困難\n- 与那国島:民営 2 社のみ、価格 ¥7,000-12,000/日、車両 30 台のみ、台風期欠便影響大\n- 久米島:OTS・ニッポン対応、価格 ¥5,500-9,500/日、フェリー輸送で本島レンタカー持ち込みも可\n- 離島共通注意:小型車 + 軽自動車中心、SUV・ミニバン少、給油場所限定、予約 1 か月前推奨\n- フェリー車両搭載:那覇 → 久米島 久米商船 ¥18,000/車両、本島レンタカーで離島訪問する場合のオプション\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["island_main"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["rental_car", "remote_islands", "concept", "limited_supply", "advance_booking"],
    source: "manual",
  },

  // ── route_map_urban 那覇市內交通(3 筆)──
  {
    slug: "okinawa-naha-bus-network",
    category: "transport",
    sub_type: "route_map_urban",
    title_zh: "那覇市內バス網(4 社統合運行)",
    title_ja: "那覇市内バス網",
    romaji: "Naha City Bus Network",
    summary_zh:
      "那覇市内および沖縄本島の路線バスは那覇バス + 沖縄バス + 琉球バス交通 + 東陽バス の 4 社統合運行、IC カードで通用。那覇市内移動はゆいレール優先だが、バスは本島中部・北部リゾート行きの主要手段。¥230-2,000/区間、東京・関西バスより本数少。",
    content_md:
      "- 4 社統合:那覇バス + 沖縄バス + 琉球バス交通 + 東陽バス、運賃・IC カード共通(OKICA + Suica/PASMO/ICOCA 等全国 IC 対応)\n- 那覇市内主要路線:1・2・3・5・10・11 系統(国際通り・首里・那覇空港・小禄)\n- 本島南北路線:那覇 → 名護 急行(¥2,000・1 時間 30 分)、那覇 → 本部美ら海水族館(¥2,170・1 時間 50 分)\n- ゆいレール vs バス:ゆいレールは那覇市内のみ、バスは本島全域、観光客は併用\n- 東京・関西比較:本数少(1-3 便/時間)、夜便 21:00 まで、土日減便\n- 那覇バスターミナル:旭橋駅直結、4 社共通の発着場\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_network", "naha", "4_companies", "ic_card", "concept"],
    source: "manual",
  },
  {
    slug: "okinawa-tour-bus-day-trip",
    category: "transport",
    sub_type: "route_map_urban",
    title_zh: "沖繩定期觀光バス(那覇発各地日帰り)",
    title_ja: "沖縄定期観光バス",
    romaji: "Okinawa Sightseeing Tour Bus",
    summary_zh:
      "那覇発の定期観光バス、首里城 + 美ら海水族館 + 万座毛 + 古宇利大橋 等のメイン観光地を 1 日で周回するレンタカー無し観光客向け。OKINAWA HIP HOP BUS・沖縄バス観光・那覇バス観光 等の事業者、¥4,500-7,500/1 日、英語・中国語・韓国語ガイド対応。",
    content_md:
      "- 主要事業者:沖縄バス観光・那覇バス観光・OKINAWA HIP HOP BUS(英語ガイド)\n- 主要コース:1)美ら海水族館 + 古宇利大橋 + 万座毛(¥6,500・10 時間)、2)首里城 + 沖縄ワールド + ひめゆりの塔(¥4,500・8 時間)、3)海中道路 + 勝連城跡 + 浜比嘉島(¥5,500・8 時間)\n- 言語対応:英語・中国語・韓国語ガイド有(事業者により異なる)\n- レンタカー無し観光客向け:特に運転免許のない方・国際免許不可の中国・台湾・韓国観光客に重要\n- 予約:沖縄エアポート連絡バス Web + 各社 Web、観光繁忙期は 1 週間前推奨\n- 那覇発時間:朝 8:30-9:30 出発、夕方 17:30-19:30 帰着\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["tour_bus", "naha", "day_trip", "concept", "multilingual"],
    source: "manual",
  },
  {
    slug: "okinawa-okinawa-island-bus-overall",
    category: "transport",
    sub_type: "route_map_urban",
    title_zh: "沖繩本島路線バス全体マップ(南北・東西)",
    title_ja: "沖縄本島路線バス全体ガイド",
    romaji: "Okinawa Main Island Bus Overall Guide",
    summary_zh:
      "沖縄本島の路線バス全体マップ、那覇 → 名護 → 辺戸岬の南北路線(国道 58 号)、那覇 → 沖縄市 → うるま → 海中道路の東西路線(国道 330 号 + 329 号)を整理。レンタカー利用客が代替交通として、観光客がリゾート経路の確認用に使う実用ガイド。",
    content_md:
      "- 南北路線(国道 58 号沿い):那覇 → 浦添 → 北谷 → 嘉手納 → 読谷 → 恩納 → 名護 → 本部 → 辺戸岬\n- 東西路線(国道 330 号 + 329 号):那覇 → 宜野湾 → 北中城 → 沖縄市 → うるま → 海中道路 → 平安座島\n- 急行バス:那覇 → 名護 急行(琉球バス交通 117 番・1 日 12 便・¥2,000)、那覇 → 美ら海水族館 急行(¥2,170)\n- 一般路線バス:本数少(1 日 5-10 便)、夜便 18:00 以降稀\n- 主要観光地停車:アメリカンビレッジ・万座毛・古宇利大橋(徒歩 10-20 分)・美ら海水族館\n- レンタカー代替:雨天・台風時の運転回避・国際免許不可者の代替交通\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_network", "main_island", "concept", "north_south", "east_west"],
    source: "manual",
  },

  // ── ticket_promo 票券優惠(4 筆)──
  {
    slug: "okinawa-yui-rail-1day-pass",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "ゆいレール 1 日券(¥800)/2 日券(¥1,400)",
    title_ja: "ゆいレール 1 日券・2 日券",
    romaji: "Yui-Rail 1-Day · 2-Day Pass",
    summary_zh:
      "ゆいレール乗り放題の 1 日券 ¥800・2 日券 ¥1,400、那覇市内観光の必須チケット。那覇空港 → 国際通り → 首里 を 3 回乗れば元が取れる(片道 ¥270 × 3 = ¥810)、観光客の 80% 以上が利用する沖縄第 1 のお得切符。",
    content_md:
      "- 価格:1 日券 ¥800、2 日券 ¥1,400(大人)、子供半額\n- 購入場所:那覇空港駅・各駅自動券売機・那覇空港観光案内所\n- 利用範囲:ゆいレール 全 19 駅 + 17.0km の全路線、購入から 24/48 時間有効\n- 元が取れる回数:1 日券 → 3 回乗車(¥270 × 3 = ¥810)、2 日券 → 5-6 回乗車\n- 観光客定番ルート:那覇空港 → 県庁前(国際通り)→ 牧志 → 首里(首里城)→ 県庁前 → 那覇空港 で計 5 回乗車、2 日券で十分\n- 提携割引:首里城公園・那覇空港 DFS・那覇市伝統工芸館 等で割引提示\n- 那覇市内観光の第 1 のお得切符\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yui_rail", "1day_pass", "ticket", "concept"],
    source: "manual",
  },
  {
    slug: "okinawa-bus-pass-3days",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "沖繩路線バス周遊券(本島 3 日 ¥2,500)",
    title_ja: "沖縄路線バス周遊券",
    romaji: "Okinawa Bus Pass",
    summary_zh:
      "本島路線バス 3 日券 ¥2,500、4 社統合運行(那覇バス + 沖縄バス + 琉球バス + 東陽バス)で本島の主要観光地(美ら海・万座毛・古宇利・首里)に乗り放題。レンタカー利用しない観光客向け、3 日間で 4-5 か所周回が現実的。",
    content_md:
      "- 価格:1 日券 ¥1,000、3 日券 ¥2,500(大人)\n- 利用範囲:本島 4 社路線バス全路線(離島除く)、空港リムジンバス + 急行バス含む\n- 元が取れる回数:那覇 → 美ら海水族館 ¥2,170 + 美ら海 → 万座毛 + 万座毛 → 那覇で 3 日券 1 日分使い切り\n- 観光客動線:Day 1 那覇 → 美ら海水族館 + 古宇利大橋 + 名護宿泊、Day 2 名護 → 万座毛 + 恩納海岸 + 那覇帰着、Day 3 那覇市内ゆいレールで購入も可\n- 購入場所:那覇空港観光案内所・那覇バスターミナル・主要バス停の自動券売機\n- レンタカー比較:レンタカー ¥4,500/日 vs バス ¥833/日、運転不要 + 飲酒可のメリット\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_pass", "main_island", "ticket", "concept", "3_days"],
    source: "manual",
  },
  {
    slug: "okinawa-yaeyama-ferry-pass",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "八重山フェリーフリーパス(4 日 ¥10,000)",
    title_ja: "八重山フェリーフリーパス",
    romaji: "Yaeyama Ferry Free Pass",
    summary_zh:
      "石垣港経由 八重山離島(西表・竹富・小浜・黒島・波照間・鳩間・新城)行きフェリーが乗り放題の 4 日券 ¥10,000、安栄観光 + 八重山観光フェリー両社共通。観光客の八重山島巡り(石垣 + 西表 + 竹富 + 小浜)で 4 島回ると元が取れる、八重山訪問の必須チケット。",
    content_md:
      "- 価格:4 日券 ¥10,000(大人)、3 日券 ¥9,000\n- 利用範囲:安栄観光 + 八重山観光フェリー 共通、石垣 → 西表(大原・上原)・竹富・小浜・黒島・波照間・鳩間・新城\n- 4 日間有効:購入日から 4 日間連続(欠航日も含む)\n- 元が取れる回数:石垣 → 西表大原往復(¥3,660)+ 石垣 → 竹富往復(¥1,540)+ 石垣 → 小浜往復(¥2,520)+ 石垣 → 波照間往復(¥7,080)= ¥14,800、フリーパス ¥10,000 で大幅お得\n- 購入場所:石垣港離島ターミナル安栄観光カウンター・八重山観光フェリーカウンター\n- 観光客定番:石垣 1 泊 + 西表 2 泊 + 竹富 1 泊 の 4 日 4 島巡りで完璧に元が取れる\n- 注意:波照間航路は安栄観光独占、フリーパス対応\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "石垣市",
    lg_code: "47207",
    area_types: ["island_main"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ferry_pass", "yaeyama", "ticket", "concept", "4_days"],
    source: "manual",
  },
  {
    slug: "okinawa-tour-bus-1day",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "沖繩定期觀光バス 1 日券(¥3,500-7,500)",
    title_ja: "沖縄定期観光バス 1 日チケット",
    romaji: "Okinawa Sightseeing Bus 1-Day Ticket",
    summary_zh:
      "沖縄定期観光バスの 1 日チケット、那覇発 + ガイド付き + 主要観光地周回で ¥3,500-7,500。レンタカー無し・運転免許なし観光客向け、英語・中国語・韓国語ガイド対応。コース選択次第で美ら海水族館 + 古宇利大橋・首里城 + 沖縄ワールド + ひめゆりの塔 等が選べる。",
    content_md:
      "- 価格:¥3,500(8 時間南部コース・首里 + ひめゆり + 沖縄ワールド)〜 ¥7,500(10 時間北部コース・美ら海 + 古宇利 + 万座毛)\n- 含まれるもの:バス + ガイド + 主要観光地入場料 + ランチ\n- 言語対応:英語・中国語・韓国語ガイド(事業者により異なる)\n- 那覇発時間:朝 8:30-9:30 出発、夕方 17:30-19:30 帰着\n- 主要事業者:沖縄バス観光・那覇バス観光・OKINAWA HIP HOP BUS\n- 予約:沖縄エアポート連絡バス Web、観光繁忙期は 1 週間前推奨\n- レンタカー比較:レンタカー ¥4,500 + ガソリン + 観光地入場料 = 同程度、運転不要メリット + ガイド解説の文化的価値\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["tour_bus", "1day_ticket", "concept", "multilingual"],
    source: "manual",
  },

  // ── night_transit 沖繩夜間交通(2 筆)──
  {
    slug: "okinawa-naha-night-taxi",
    category: "transport",
    sub_type: "night_transit",
    title_zh: "那覇深夜タクシー(国際通り・栄町夜遊び)",
    title_ja: "那覇深夜タクシー",
    romaji: "Naha Night Taxi",
    summary_zh:
      "那覇市内深夜帯(23:00 以降)の交通、ゆいレール終便 23:30 後はタクシー一択。国際通り・栄町・那覇市内 → ホテル帰路の主要手段、深夜割増 22:00-翌 5:00 で 20% 増。沖縄観光客が国際通り屋台村・栄町夜遊び後の帰路の必読。",
    content_md:
      "- 深夜時間帯:22:00-翌 5:00 = タクシー深夜割増 20% 増(本州他都市と同水準)\n- 那覇市内タクシー初乗:¥460(深夜 ¥550)、その後 ¥80/240m(深夜 ¥96/240m)\n- 国際通り → 那覇空港:¥1,500-1,800(深夜 ¥1,800-2,200)、空港から市内ホテルもこの相場\n- 栄町・那覇国際通り屋台村 → ホテル:¥800-1,500(深夜)\n- ゆいレール終便:23:30(那覇空港発)・23:45(てだこ浦西発)、後はタクシー一択\n- 配車アプリ:DiDi・GO・S.RIDE 全社那覇対応、深夜の配車待ち時間 5-15 分\n- 米軍関係注意:夜の北谷・宜野湾は米軍関係者飲酒運転リスク、可能なら 0:00 以降の運転は避ける\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["night_transit", "taxi", "naha", "concept", "late_night"],
    source: "manual",
  },
  {
    slug: "okinawa-us-base-night-bus",
    category: "transport",
    sub_type: "night_transit",
    title_zh: "米軍関係夜間バス(嘉手納-那覇 24h 路線)",
    title_ja: "米軍関係夜間バス",
    romaji: "US Base Night Bus",
    summary_zh:
      "嘉手納基地・普天間飛行場 周辺は米軍関係者の夜間移動需要があり、特殊な 24 時間バス・タクシーサービスが存在。観光客が直接利用することは稀だが、北谷美浜・沖縄市コザ地区の夜遊び客がアメリカンビレッジ深夜バーから戻る際の移動手段として知られる。",
    content_md:
      "- 嘉手納-那覇 24h 路線:沖縄バス特殊路線、米軍関係者の通勤需要から発生、観光客も乗車可\n- 普天間-那覇 24h 路線:同じく米軍関係者向け、宜野湾米軍住宅街経由\n- 観光客利用シーン:美浜アメリカンビレッジで深夜バー(2:00-3:00)後の那覇帰路、ナイトクラブ後の移動\n- 路線運賃:¥1,500-2,500(那覇まで)、深夜割増無し(米軍関係者向け定額制)\n- 運行間隔:1 時間に 1-2 便、深夜帯は 1 時間以上空く\n- タクシー比較:タクシー深夜割増 ¥4,000-5,000、夜バス ¥1,500-2,500 で大幅お得\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["urban"],
    lat: null,
    lon: null,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["night_transit", "us_military", "kadena", "concept", "24h_route"],
    source: "manual",
  },

  // ── okinawa_us_military_transit 米軍関係交通(3 筆)──
  {
    slug: "okinawa-kadena-air-base-viewing",
    category: "transport",
    sub_type: "okinawa_us_military_transit",
    title_zh: "嘉手納米軍基地 展望デッキアクセス(道の駅かでな)",
    title_ja: "嘉手納米軍基地 展望デッキ",
    romaji: "Kadena Air Base Viewing Deck",
    summary_zh:
      "道の駅かでな(2009 開業)の屋上展望デッキから世界最大級の嘉手納空軍基地(全長 3,683m 滑走路 2 本)を一望できる稀有な観光地。F-15 戦闘機・KC-135 給油機の離発着が間近に見え、米軍機ファンの聖地。観光客にも開かれた米軍ベース見学の唯一の合法ルート。",
    content_md:
      "- 道の駅かでな:沖縄県中頭郡嘉手納町字屋良1026-3、那覇空港から車 45 分\n- 開業:2009 年(平成 21 年)\n- 嘉手納空軍基地:全長 3,683m 滑走路 × 2 本、世界最大級の海外米軍基地\n- 主要展示:F-15 イーグル戦闘機・KC-135 給油機・E-3 早期警戒機・F-22 ラプター(訪問時期で変動)\n- 屋上展望デッキ:4 階・無料・営業 9:00-22:00、米軍機離発着の最適スポット\n- F-15 離発着時間表:展望デッキ 3 階に当日離発着予定が掲示、米軍訓練日(火-木)が最も活発\n- アメリカンビレッジ + 嘉手納道の駅 セット観光:車 15 分で連結、半日コース\n- 写真撮影注意:基地内施設(管制塔・格納庫・特定航空機)の撮影規制有、展望デッキの掲示確認\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: "中頭郡",
    municipality_ja: "嘉手納町",
    lg_code: "47325",
    area_types: ["urban"],
    lat: 26.3553,
    lon: 127.7569,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["us_military", "kadena", "viewing_deck", "f15_spotting", "near_michinoeki"],
    source: "manual",
  },
  {
    slug: "okinawa-mihama-american-village-access",
    category: "transport",
    sub_type: "okinawa_us_military_transit",
    title_zh: "美浜美國村アクセス(北谷・嘉手納基地隣接)",
    title_ja: "美浜アメリカンビレッジアクセス",
    romaji: "Mihama American Village Access",
    summary_zh:
      "北谷町美浜の米軍文化テーマ商業地、嘉手納空軍基地隣接立地で米軍関係者と観光客が混在する独自エリア。那覇空港から車 40 分、ゆいレール + バスで 1 時間 15 分。F-15 戦闘機の離発着が至近で見える、夕食 + 夜景 + 米軍文化体験の家族コース。",
    content_md:
      "- 立地:沖縄県中頭郡北谷町美浜、那覇空港から車 40 分・那覇市内から車 30 分\n- 公共交通:那覇バスターミナル → 沖縄バス 28 番系統「桑江(美浜)」 1 時間・¥730\n- 嘉手納基地隣接:F-15 戦闘機・KC-135 給油機の離発着が至近で見える、特に展望デッキ無しで道路から目撃可\n- 米軍関係者と観光客混在:店舗の 30% が米軍関係者向けサービス、英語表示のみの店も多\n- 観覧車:60m・¥600、夜景観賞のシンボル\n- 北谷サンセットビーチ:アメリカンビレッジ南隣・徒歩 5 分、夕日鑑賞地\n- 観光バンドル:アメリカンビレッジ + 嘉手納道の駅 の半日コース、車 15 分で連結\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: "中頭郡",
    municipality_ja: "北谷町",
    lg_code: "47326",
    area_types: ["urban", "coastal"],
    lat: 26.3175,
    lon: 127.7550,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["us_military", "chatan", "mihama", "kadena_adjacent", "access_guide"],
    source: "manual",
  },
  {
    slug: "okinawa-futenma-ginowan-access",
    category: "transport",
    sub_type: "okinawa_us_military_transit",
    title_zh: "普天間飛行場 周辺アクセス(宜野湾市・移転問題ホットスポット)",
    title_ja: "普天間飛行場 周辺アクセス",
    romaji: "Futenma Air Station Area Access",
    summary_zh:
      "普天間飛行場(宜野湾市市街中心部)は移転問題で知られる米軍施設、滑走路 2,800m が市街地に直接隣接する世界的に異常な配置。観光客が直接見学できないが、隣接の佐喜眞美術館(2 階屋上)や嘉数公園展望台から飛行場全体を一望できる。沖縄返還問題の現代的象徴。",
    content_md:
      "- 普天間飛行場:沖縄県宜野湾市新城・佐真下、市街地中心に立地・滑走路 2,800m\n- 移転問題:1996 年日米合意で名護市辺野古移設・2024 年現在も完了せず、沖縄県政の重大政治課題\n- 佐喜眞美術館:宜野湾市上原・普天間飛行場フェンス隣接、2 階屋上から飛行場全体一望、入館料 ¥900\n- 嘉数公園展望台:宜野湾市嘉数・標高 92m・無料、普天間飛行場 + 周辺米軍住宅地区を一望\n- アクセス:那覇市内から車 25 分・公共交通 沖縄バス 28 番「神山入口」徒歩 5 分\n- 観光意義:沖縄返還(1972)から 50+ 年の米軍駐留問題、現代沖縄文化を理解する重要な視座\n- 中文圈策展極稀缺:日本本土・中文圏ともに普天間問題の現地視察コース紹介はほぼ無\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "宜野湾市",
    lg_code: "47205",
    area_types: ["urban"],
    lat: 26.2706,
    lon: 127.7517,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["us_military", "futenma", "ginowan", "relocation_issue", "sakima_museum"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // 老卷補完 expansion(2026-04-29・39 → 45)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "naha-bus-terminal-2018",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "那覇バスターミナル(2018 リニューアル・OPA 併設・那覇全 4 バス会社統合 hub)",
    title_ja: "那覇バスターミナル",
    romaji: "Naha Bus Terminal",
    summary_zh:
      "1948 創立 → 2018 全面建替リニューアル(那覇 OPA 併設の複合再開発)で,那覇市内 4 大バス会社(琉球バス + 那覇バス + 沖縄バス + 東陽バス)が統合運用する沖縄本島最大バス hub。離島 + 本島全方面の路線網。OPA + リウボウ百貨店徒歩 5 分。",
    content_md:
      "- 創立:1948 / 2018 リニューアル\n- 4 社統合:琉球 + 那覇 + 沖縄 + 東陽\n- OPA 併設\n- 沖縄本島最大バス hub\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.215,
    lon: 127.685,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_terminal", "naha", "since_1948", "renewed_2018", "4_companies"],
    source: "manual",
  },
  {
    slug: "yui-rail-omoromachi-station",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "おもろまち駅(那覇新都心・DFS T ギャラリア + メインプレイス直結)",
    title_ja: "おもろまち駅",
    romaji: "Omoromachi Station",
    summary_zh:
      "ゆいレールの那覇新都心駅。1995 那覇新都心(那覇北部・米軍住宅跡地再開発)中心に立地。DFS T ギャラリア沖縄(2004)+ 那覇メインプレイス(2002)+ 県立博物館・美術館(2007)直結の那覇北部最大商業 + 文化 hub。1 日乗降 1 万人。",
    content_md:
      "- 路線:ゆいレール\n- 立地:那覇新都心\n- DFS + メインプレイス + 県博美直結\n- 1 日乗降:1 万人\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.230,
    lon: 127.704,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["station", "omoromachi", "naha_shintoshin", "dfs_galleria"],
    source: "manual",
  },
  {
    slug: "yui-rail-makishi-station",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "牧志駅(国際通り中央・那覇市民の中心駅・1 日乗降 1.2 万人)",
    title_ja: "牧志駅",
    romaji: "Makishi Station",
    summary_zh:
      "ゆいレールの牧志駅。国際通り(那覇 1.6 km アーケード商店街)の中央に立地。県庁前駅(国際通り西端)+ 牧志駅(中央)+ 安里駅(東端)で国際通りを縦断。第一牧志公設市場 + 牧志市場通り徒歩 3 分。1 日乗降 1.2 万人。",
    content_md:
      "- 路線:ゆいレール\n- 立地:国際通り中央\n- 第一牧志公設市場徒歩 3 分\n- 1 日乗降:1.2 万人\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.218,
    lon: 127.697,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["station", "makishi", "yui_rail", "kokusai_dori"],
    source: "manual",
  },
  {
    slug: "yui-rail-asahibashi-station",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "旭橋駅(那覇バスターミナル接続・OPA + リウボウ徒歩 5 分)",
    title_ja: "旭橋駅",
    romaji: "Asahibashi Station",
    summary_zh:
      "ゆいレール旭橋駅。那覇バスターミナル(2018)直結で本島全方面のバス網接続 hub。OPA + リウボウ百貨店(那覇唯一百貨店)徒歩 5 分。那覇都心の交通核。1 日乗降 1.5 万人。",
    content_md:
      "- 路線:ゆいレール\n- 那覇バスターミナル直結\n- OPA + リウボウ徒歩 5 分\n- 1 日乗降:1.5 万人\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.213,
    lon: 127.683,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["station", "asahibashi", "yui_rail", "bus_terminal_direct"],
    source: "manual",
  },
  {
    slug: "ishigaki-port-rito-terminal-2007",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "石垣港離島ターミナル(2007 開業・八重山離島フェリー基地・年 200 万人)",
    title_ja: "石垣港離島ターミナル",
    romaji: "Ishigaki-kō Ritō Terminal",
    summary_zh:
      "2007 石垣市美崎町に開業の八重山離島フェリー基地。安栄観光 + 八重山観光の 2 社が運航し,竹富 + 西表 + 小浜 + 黒島 + 鳩間 + 波照間 + 与那国の 7 離島へ全便発着。年間利用 200 万人。隣接の 730 交差点モニュメント(1978 沖縄 7・30 復帰記念)。",
    content_md:
      "- 開業:2007\n- 立地:石垣市美崎町\n- 7 離島フェリー基地\n- 年間利用:200 万人\n- 730 モニュメント隣接\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "石垣市",
    lg_code: "47207",
    area_types: ["urban", "coastal"],
    lat: 24.336,
    lon: 124.157,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["port", "ishigaki", "rito_terminal", "since_2007", "yaeyama"],
    source: "manual",
  },
  {
    slug: "nago-bus-terminal",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "名護バスターミナル(本部 + やんばる入口・本島北部交通核)",
    title_ja: "名護バスターミナル",
    romaji: "Nago Bus Terminal",
    summary_zh:
      "名護市役所近くの本島北部最大バス hub。沖縄美ら海水族館(本部町)+ やんばる国立公園(国頭・大宜味)+ 古宇利島・恩納村・万座 + 那覇への放射状路線網。北部観光 + 名護パイナップル + ゴールドコースト・コロッセウム(2025 アリーナ)アクセス。",
    content_md:
      "- 立地:名護市役所近く\n- 本島北部最大バス hub\n- 美ら海 + やんばる + 古宇利島アクセス\n- 2026-04 人工查核",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "名護市",
    lg_code: "47209",
    area_types: ["urban"],
    lat: 26.591,
    lon: 127.978,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_terminal", "nago", "yanbaru_access", "north_okinawa"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R3 補完(老卷・2026-04-29)— ゆいレール残駅 5 + 空港 + 港 + 高速 + バス
  // 45 → 55(+10):美栄橋・赤嶺・儀保・経塚・市立病院前 + 那覇空港国際線 +
  //           平良港 + 与那国空港 + やんばる急行バス + 沖縄自動車道
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "yui-rail-miebashi-naha",
    category: "transport",
    sub_type: "okinawa_yui_rail",
    title_zh: "美栄橋駅(ゆいレール・国際通り入口・那覇市久米)",
    title_ja: "美栄橋駅(ゆいレール)",
    romaji: "Miebashi Station",
    summary_zh: "**美栄橋駅は那覇国際通りへの主要玄関口**(那覇市久米)。沖縄都市モノレール ゆいレール 19 駅中の中核駅、駅から国際通り北端まで徒歩 2 分。観光客の那覇宿泊・国際通り観光・那覇泊港(離島フェリー乗り場)アクセスの起点となる重要駅。",
    content_md: "- 路線:沖縄都市モノレール ゆいレール\n- 駅番号:7(那覇空港から数えて 7 駅目)\n- 立地:那覇市久米(国際通り北端 徒歩 2 分)\n- 1 日乗降:約 1.4 万人\n- 周辺主要施設:国際通り(沖縄観光メイン通り)・那覇泊港(とまりん・離島フェリー)\n- アクセス:那覇空港駅から 13 分・¥260\n- 駅徒歩圏ホテル多数:ホテルパークサイド那覇・ホテルアベスト那覇国際通り 等",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.221,
    lon: 127.683,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.yui-rail.co.jp/" },
    tags: ["okinawa_yui_rail", "miebashi", "kokusai_dori", "naha"],
    source: "manual",
  },
  {
    slug: "yui-rail-akamine-naha",
    category: "transport",
    sub_type: "okinawa_yui_rail",
    title_zh: "赤嶺駅(ゆいレール・那覇空港隣・那覇空港 1 駅・最南端モノレール駅)",
    title_ja: "赤嶺駅(ゆいレール)",
    romaji: "Akamine Station",
    summary_zh: "**赤嶺駅は那覇空港の次の駅**(那覇空港駅から 5 分・¥230)。日本最南端のモノレール駅・鉄道駅としても知られる、駅前にイオン那覇店(2017 開業大型 mall)+ 駅前駐車場(空港利用客の格安駐車利用)で観光客便利。",
    content_md: "- 路線:沖縄都市モノレール ゆいレール\n- 駅番号:2(那覇空港から数えて 2 駅目)\n- 立地:那覇市赤嶺(那覇空港の南東 隣接)\n- 日本最南端のモノレール駅・最南端の鉄道駅\n- 駅前:イオン那覇店(2017 開業・延床面積 5 万 m²)・赤嶺駅前駐車場\n- 1 日乗降:約 6 千人\n- 那覇空港駅から:5 分・¥230\n- 用途:空港利用客の格安駐車(¥500/日 → 1 駅でモノレールで空港)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.196,
    lon: 127.671,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.yui-rail.co.jp/" },
    tags: ["okinawa_yui_rail", "akamine", "japan_southernmost_monorail", "aeon_naha"],
    source: "manual",
  },
  {
    slug: "yui-rail-gibo-naha",
    category: "transport",
    sub_type: "okinawa_yui_rail",
    title_zh: "儀保駅(ゆいレール・首里駅手前・首里観光客の代替駅)",
    title_ja: "儀保駅(ゆいレール)",
    romaji: "Gibo Station",
    summary_zh: "**儀保駅は首里城観光の隠れ玄関**(那覇市首里)。ゆいレール首里駅の手前(那覇空港側)、首里駅と組合せて利用すれば歩行距離分散でき、首里城下の細路や赤瓦集落をゆっくり巡れる。1 日乗降 約 5 千人と空いていて、首里観光ピーク時の代替アクセスに優秀。",
    content_md: "- 路線:沖縄都市モノレール ゆいレール\n- 駅番号:13(那覇空港から数えて 13 駅目)\n- 立地:那覇市首里(首里駅の手前・南西)\n- 1 日乗降:約 5 千人(空いている)\n- 首里観光戦略:首里駅 + 儀保駅セットで使い、首里城・玉陵・金城町石畳道・首里赤瓦集落 を効率的に\n- 那覇空港駅から:25 分・¥330\n- 駅周辺:住宅街・観光地から少し離れる",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.222,
    lon: 127.728,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.yui-rail.co.jp/" },
    tags: ["okinawa_yui_rail", "gibo", "shuri_alt"],
    source: "manual",
  },
  {
    slug: "yui-rail-kyozuka-urasoe",
    category: "transport",
    sub_type: "okinawa_yui_rail",
    title_zh: "経塚駅(ゆいレール・浦添市・2019 延伸開業・郊外通勤駅)",
    title_ja: "経塚駅(ゆいレール)",
    romaji: "Kyozuka Station",
    summary_zh: "**経塚駅は 2019 年延伸開業の浦添市側駅**。ゆいレールが従来の首里駅 終点から浦添方面に 4 駅延伸(2019 10 月)、経塚 + 浦添前田 + 石嶺 + てだこ浦西 の 4 駅が新設された中の 1 つ。浦添市民の通勤通学駅、観光客は美術博物館や浦添ようどれ古墳群アクセスに使う。",
    content_md: "- 路線:沖縄都市モノレール ゆいレール\n- 駅番号:16(2019 延伸 17 駅化された 4 新駅の 1)\n- 開業:2019 年(令和元)10 月 1 日 延伸開業\n- 立地:浦添市経塚\n- 1 日乗降:約 4 千人\n- 観光的価値:浦添市美術博物館 + 浦添ようどれ古墳群(琉球王統墓・尚寧王陵)\n- 那覇空港駅から:35 分・¥370\n- 用途:浦添市民通勤通学 + 浦添観光",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "浦添市",
    lg_code: "47208",
    area_types: ["urban_central"],
    lat: 26.241,
    lon: 127.741,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.yui-rail.co.jp/" },
    tags: ["okinawa_yui_rail", "kyozuka", "urasoe", "2019_extension"],
    source: "manual",
  },
  {
    slug: "yui-rail-shimin-byoin-mae-naha",
    category: "transport",
    sub_type: "okinawa_yui_rail",
    title_zh: "市立病院前駅(ゆいレール・那覇市古島・通勤通学駅)",
    title_ja: "市立病院前駅(ゆいレール)",
    romaji: "Shiritsu Byoin-mae Station",
    summary_zh: "**市立病院前駅は那覇市古島の通勤通学駅**。ゆいレール 19 駅中の中部、那覇市立病院 + 古島駅 + 公務員官舎 + 沖縄県立博物館・美術館(おもろまち隣接)の重要日常駅。観光客向けには沖縄県立博物館・美術館へのアクセス駅として使われる。",
    content_md: "- 路線:沖縄都市モノレール ゆいレール\n- 駅番号:11(那覇空港から数えて 11 駅目)\n- 立地:那覇市古島(那覇市立病院の前)\n- 1 日乗降:約 7 千人\n- 観光的価値:沖縄県立博物館・美術館(徒歩 10 分・隣接駅おもろまちからもアクセス可)\n- 那覇空港駅から:21 分・¥320\n- 用途:那覇市民通勤通学",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.226,
    lon: 127.700,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.yui-rail.co.jp/" },
    tags: ["okinawa_yui_rail", "shimin_byoin_mae", "naha", "museum_access"],
    source: "manual",
  },
  {
    slug: "naha-airport-international-2014",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "那覇空港国際線ターミナル(2014 開業・LCC + 中華系・国内線旧国際線跡地)",
    title_ja: "那覇空港国際線ターミナル",
    romaji: "Naha Airport International",
    summary_zh: "**那覇空港国際線ターミナルは 2014 年開業の国際線専用棟**。1972 沖縄返還以来の国際便増加に対応、ピーチ・タイガーエア・キャセイパシフィック・チャイナエアライン等の LCC + 中華系航空が主力。日本本土の主要空港(羽田・成田・関空)に次ぐ、国際路線数日本第 4 位の地方空港。",
    content_md: "- 開業:2014 年(平成26)2 月 那覇空港\n- 構成:国内線ターミナル(旧)+ 国際線ターミナル(2014)+ 連絡橋\n- 国際路線:タイ・台湾・香港・韓国・上海・北京 等(LCC + 中華系航空)\n- 主要航空:ピーチ・タイガーエア・キャセイパシフィック・チャイナエアライン・エバー航空\n- 国内線同時利用:可(連絡橋で歩行 5 分)\n- 営業:6:30-21:00(便発着時)\n- アクセス:ゆいレール 那覇空港駅(国内線側・徒歩 8 分で国際線へ移動)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.196,
    lon: 127.645,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.naha-airport.co.jp/" },
    tags: ["airport_access", "naha_international_terminal", "2014", "lcc"],
    source: "manual",
  },
  {
    slug: "miyako-hirara-port-2007",
    category: "transport",
    sub_type: "ferry_island",
    title_zh: "宮古平良港(2007 整備・宮古諸島フェリー hub・伊良部/池間/来間 連絡)",
    title_ja: "宮古 平良港",
    romaji: "Miyako Hirara Port",
    summary_zh: "**平良港は宮古諸島のフェリー hub**(宮古島市平良)。2007 年整備、伊良部島(伊良部大橋 2015 開通で平良 - 伊良部 直行も可)・池間島(池間大橋)・来間島(来間大橋)・大神島(離島フェリーのみ)・多良間村 へのフェリー集約。鹿児島 - 宮古 のマルエーフェリー(週 1 往復)も発着。",
    content_md: "- 立地:宮古島市平良港湾\n- 整備:2007 年(平成19)現代化\n- 主要連絡:\n  - 大神島フェリー(片道 15 分・¥530・1 日 4 往復)\n  - 多良間フェリー(片道 2 時間・¥2400・1 日 1 往復・週末増便)\n  - 鹿児島-宮古マルエーフェリー(週 1 往復・¥17000)\n- 注:伊良部島・池間島・来間島 は架橋済(2015/1992/1995)で 自動車直行・フェリー不要\n- 国際線:中華系クルーズ船寄港地(コロナ前)\n- アクセス:宮古空港 から車 8 分(市内中心地隣接)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "宮古島市",
    lg_code: "47214",
    area_types: ["fishing_port", "urban_central"],
    lat: 24.804,
    lon: 125.281,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["ferry_island", "miyako_hirara_port", "2007", "outer_islands_hub"],
    source: "manual",
  },
  {
    slug: "yonaguni-airport-westernmost",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "与那国空港(日本最西端の空港・東経 122°56・JTA 1 日 1-2 往復)",
    title_ja: "与那国空港",
    romaji: "Yonaguni Airport",
    summary_zh: "**与那国空港は日本最西端の空港**(東経 122°56・与那国町)。1962 年開港・1999 年 2000m 滑走路に拡張、JTA(日本トランスオーシャン航空)が那覇 + 石垣 から 1 日 1-2 往復で運航。海底遺跡ダイビング客 + 沖縄最西端踏破客が主な利用者、年間 6 万人。",
    content_md: "- 立地:八重山郡与那国町(日本最西端・東経 122°56)\n- 開港:1962 年・1999 拡張(2000 m 滑走路)\n- 路線:那覇 ↔ 与那国(JTA・1 日 1-2 往復・所要 1 時間 35 分)・石垣 ↔ 与那国(JTA・1 日 1 往復・35 分)\n- 年間利用:約 6 万人(2019 ピーク)\n- 主要利用:海底遺跡ダイビング客・最西端踏破客・与那国島民通勤通学\n- 距離:石垣空港から南西 約 130 km・那覇から南西 約 510 km\n- アクセス:与那国空港 → 与那国島内中心地 約 5 km(タクシー or レンタカー)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: "八重山郡",
    municipality_ja: "与那国町",
    lg_code: "47382",
    area_types: ["urban_central"],
    lat: 24.467,
    lon: 122.978,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["airport_access", "yonaguni_airport", "japan_westernmost", "1962"],
    source: "manual",
  },
  {
    slug: "yanbaru-rapid-bus-okinawa",
    category: "transport",
    sub_type: "limited_express_private",
    title_zh: "やんばる急行バス(那覇 → 名護 → 国頭・本島大動脈・1 日 5 往復)",
    title_ja: "やんばる急行バス",
    romaji: "Yanbaru Rapid Bus",
    summary_zh: "**やんばる急行バスは那覇 → 名護 → 国頭 を結ぶ高速バス**(沖縄バス + 琉球バス交通 共同運行)。本島北部「やんばる(山原)」へのアクセス主役、那覇空港 + 那覇市内 → 万座 → 名護 → 国頭 を約 3 時間で。レンタカーを使わない場合の本島北部観光の必須路線、車内 Wi-Fi 完備。",
    content_md: "- 運行会社:沖縄バス + 琉球バス交通(共同運行)\n- 区間:那覇空港 + 那覇市 → 万座 → 名護 → 国頭(高速道路経由)\n- 所要:那覇 → 名護 約 1 時間 50 分・那覇 → 国頭 約 3 時間\n- 本数:1 日 5 往復(早朝便 + 夕方便あり)\n- 運賃:那覇空港 → 名護 ¥1900・那覇空港 → 国頭 ¥2600\n- 主要停車:万座ビーチ・部瀬名・名護・大宜味・国頭村役場\n- 観光価値:やんばる国立公園(2016 指定)・古宇利島(車で連絡)・美ら海水族館 アクセス\n- 車内:Wi-Fi + USB 充電\n- 予約:不要(現地乗車)・ピーク時(GW・夏)は早めに乗車",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.196,
    lon: 127.652,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://yanbaru-expressbus.com/" },
    tags: ["limited_express_private", "yanbaru_rapid_bus", "naha_nago_kunigami"],
    source: "manual",
  },
  {
    slug: "okinawa-jidoshado-1987",
    category: "transport",
    sub_type: "limited_express_private",
    title_zh: "沖縄自動車道(那覇 IC ↔ 許田 IC・57 km・1987 全線開通・本島大動脈)",
    title_ja: "沖縄自動車道",
    romaji: "Okinawa Expressway",
    summary_zh: "**沖縄自動車道は本島の大動脈高速道路**(57 km・1987 全線開通)。那覇 IC ↔ 許田 IC(名護市)を 60 分で結ぶ NEXCO 西日本の管理、沖縄唯一の高速道路。那覇 → 名護(美ら海水族館・北部観光)アクセス時間を約 4 時間 → 1.5 時間に短縮した、観光・物流の動脈。",
    content_md: "- 区間:那覇 IC ↔ 許田 IC(名護市・57 km)\n- 全線開通:1987 年(昭和62)6 月\n- 管理:NEXCO 西日本\n- 主要 IC:那覇 IC・西原 IC・北中城 IC・沖縄北 IC・宜野座 IC・金武 IC・許田 IC\n- 所要:那覇 IC → 許田 IC 約 60 分(従来下道 4 時間 → 1.5 時間に短縮)\n- 通行料:那覇 IC ↔ 許田 IC 普通車 ¥1170\n- 沖縄唯一の高速道路(他は一般国道のみ)\n- 観光価値:美ら海水族館 + 古宇利島 + やんばる国立公園 へのアクセス時間短縮\n- 注意:速度制限 80 km/h(本土の 100 km/h より低い)",
    region: "okinawa",
    prefecture_ja: "沖縄県",
    gun_ja: null,
    municipality_ja: "那覇市",
    lg_code: "47201",
    area_types: ["urban_central"],
    lat: 26.225,
    lon: 127.708,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.w-nexco.co.jp/" },
    tags: ["limited_express_private", "okinawa_expressway", "1987", "main_artery"],
    source: "manual",
  },
];

async function main() {
  console.log(`[seed] ${rows.length} rows to seed`);

  const byKind: Record<string, number> = {};
  for (const r of rows) byKind[r.sub_type] = (byKind[r.sub_type] ?? 0) + 1;
  console.log(`[seed] by sub_type: ${JSON.stringify(byKind)}`);

  if (DRY) {
    console.log("[seed] --dry-run, samples:");
    for (const r of rows) {
      console.log(
        `  [${r.sub_type.padEnd(28)}] ${r.title_zh} (${r.municipality_ja ?? "-"}/${r.lg_code ?? "-"})`,
      );
    }
    return;
  }

  const sb = createAdminClient();
  const { data, error } = await sb
    .from("japan_entries")
    .upsert(rows, { onConflict: "slug" })
    .select("id, slug");
  if (error) {
    console.error("[seed] upsert failed", error);
    process.exit(1);
  }
  console.log(`[seed] upserted ${data?.length ?? 0} rows`);
  for (const r of data ?? []) {
    console.log(`  #${r.id}  ${r.slug}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
