// Seed 兵庫県 · 衣類 條目 → public.japan_entries(Sprint 18.5 衣 R1)
//
// 兵庫の衣類軸:
//   - 神戸老舗百貨店:大丸神戸店(1913・元町・神戸最古)+ 神戸阪急(2019・旧そごう神戸店 1933)
//   - 神戸商店街:元町商店街(1880-・神戸最古アーケード)+ 三宮センター街(1949)+ トアロード(1868 神戸開港 European)
//   - 神戸モール:umie(2013 ハーバーランド)+ ミント神戸(2006)+ 三宮 OPA + 神戸国際会館 1999
//   - 北野工房のまち(1908 旧北野小学校・1998 体験工房モール)
//   - アウトレット:三井マリンピア神戸(1999)+ 神戸三田プレミアム(2007 関西最大)
//   - 姫路:みゆき通り(1934)+ ピオレ姫路(2017)+ グランフェスタ
//   - 西宮:西宮ガーデンズ(2008・関西最大級駅前)+ ららぽーと甲子園(2008)
//   - 有馬温泉土産街
//
// 19 筆構成
//
// Usage:
//   npm run seed:japan-hyogo-fashion:dry
//   npm run seed:japan-hyogo-fashion

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "shopping_district_urban"
  | "shopping_district_local"
  | "outlet_mall"
  | "hyogo_dept_store"
  | "hyogo_mall_building"
  | "craft_goods"
  | "kimono_rental"
  | "textile_traditional";

interface SeedRow {
  slug: string;
  category: "fashion";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "kansai";
  prefecture_ja: "兵庫県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ══════════════════════════════════════════════════════════════════
  // A. 神戸老舗百貨店(2 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "daimaru-kobe-1913",
    category: "fashion",
    sub_type: "hyogo_dept_store",
    title_zh: "大丸神戸店(1913 創業・元町・神戸最古百貨店・震災後 1997 再建)",
    title_ja: "大丸神戸店",
    romaji: "Daimaru Kobe-ten",
    summary_zh:
      "1913 神戸元町に開業した神戸最古百貨店。1995 阪神淡路大震災で全壊 → 1997 元位置に再建(現本館)。地下 1 階 + 地上 9 階,200 軒余。神戸開港 + 旧居留地隣接の歴史立地。元町商店街 + 南京町 + 旧居留地徒歩圏。",
    content_md:
      "- 創業:1913\n- 立地:元町(旧居留地隣)\n- 1995 震災で全壊 → 1997 再建\n- 構成:地下 1 + 地上 9 階・200 軒余\n- 営業:10:00-20:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central"],
    lat: 34.687,
    lon: 135.190,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.daimaru.co.jp/kobe/" },
    tags: ["dept_store", "daimaru", "kobe", "since_1913", "kobe_oldest"],
    source: "manual",
  },
  {
    slug: "kobe-hankyu-2019",
    category: "fashion",
    sub_type: "hyogo_dept_store",
    title_zh: "神戸阪急(2019 改名・旧そごう神戸店 1933 創業・三宮神戸阪急ビル)",
    title_ja: "神戸阪急",
    romaji: "Kobe Hankyu",
    summary_zh:
      "1933 そごう神戸店として三宮に開業 → 2019 阪急百貨店傘下化で『神戸阪急』へ改名。2020 阪急百貨店本体に統合。地下 1 階 + 地上 12 階,250 軒余。1995 阪神淡路大震災後 1997 改装,2024 大規模リニューアル。神戸三宮駅徒歩 1 分の駅前最高級百貨店。",
    content_md:
      "- 創業:1933(そごう神戸店)\n- 2019 神戸阪急へ改名\n- 2024 リニューアル\n- 構成:地下 1 + 地上 12 階・250 軒余\n- 神戸三宮駅徒歩 1 分\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central"],
    lat: 34.692,
    lon: 135.197,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["dept_store", "hankyu", "kobe", "former_sogo", "since_1933"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // B. 神戸商店街(4 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "motomachi-shotengai",
    category: "fashion",
    sub_type: "shopping_district_urban",
    title_zh: "元町商店街(1.2 km・神戸最古アーケード・大丸神戸 + 南京町連絡)",
    title_ja: "元町商店街",
    romaji: "Motomachi Shōtengai",
    summary_zh:
      "1880 創設の神戸最古アーケード商店街。元町駅 - 西元町駅 1.2 km の全蓋アーケードに 300 軒余。大丸神戸店(1913)+ 南京町(1868)隣接の神戸開港由来の中核商業地。1995 震災後復興。地元 + 観光客混合で神戸 No.1 商店街。",
    content_md:
      "- 創設:1880\n- 距離:1.2 km(神戸最古アーケード)\n- 店舗:300 軒余\n- 隣接:大丸 + 南京町\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central"],
    lat: 34.689,
    lon: 135.190,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://kobe-motomachi.or.jp/" },
    tags: ["shopping_street", "motomachi", "kobe_oldest", "since_1880"],
    source: "manual",
  },
  {
    slug: "sannomiya-center-gai",
    category: "fashion",
    sub_type: "shopping_district_urban",
    title_zh: "三宮センター街(1949 創設・神戸三宮中央 550 m アーケード・観光客 No.1)",
    title_ja: "三宮センター街",
    romaji: "Sannomiya Center-gai",
    summary_zh:
      "1949 神戸三宮中央に創設の 550 m 全蓋アーケード商店街。三宮駅 - 元町駅を結ぶ神戸都心の中核ファッションストリート。150 軒余・観光客向け店舗 + ファッション + ドラッグストア混合。",
    content_md:
      "- 創設:1949\n- 距離:550 m アーケード\n- 店舗:150 軒余\n- 三宮駅 - 元町駅連絡\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central"],
    lat: 34.694,
    lon: 135.196,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shopping_street", "sannomiya", "since_1949", "kobe_central"],
    source: "manual",
  },
  {
    slug: "tor-road-kobe",
    category: "fashion",
    sub_type: "shopping_district_urban",
    title_zh: "トアロード(1868 神戸開港 European avenue・北野異人館街連絡)",
    title_ja: "トアロード",
    romaji: "Tor Road",
    summary_zh:
      "1868 神戸開港同時に外国人居留地と北野異人館を結ぶ通りとして整備。European 風の坂道商店街で,Tor Road デリカテッセン(1957)+ ティンクル(老舗洋装店)+ 神戸ベーカリー街等の老舗 + 現代モダン店混在。神戸開港由来の独自雰囲気。",
    content_md:
      "- 整備:1868 神戸開港同時\n- European 風坂道\n- 旧居留地 → 北野異人館 連絡路\n- 老舗 + モダン店混在\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central"],
    lat: 34.694,
    lon: 135.193,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shopping_street", "tor_road", "since_1868", "european_avenue"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // C. 神戸モール・新世代(5 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "kobe-harborland-umie",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "神戸ハーバーランド umie(2013・神戸港湾再開発・関西大型モール)",
    title_ja: "神戸ハーバーランド umie",
    romaji: "Kobe Harborland umie",
    summary_zh:
      "2013 ハーバーランド再開発で開業の大型モール『umie』。地上 4 階・3 棟構成・225 軒余。NORTH モール + SOUTH モール + モザイク。神戸港夜景 + 神戸ポートタワー対岸。観覧車 + 神戸ハーバーランドの中核商業施設。",
    content_md:
      "- 開業:2013\n- 立地:神戸ハーバーランド\n- 構成:NORTH + SOUTH + MOSAIC 3 棟\n- 店舗:225 軒余\n- 神戸港夜景\n- 営業:10:00-21:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central", "coastal"],
    lat: 34.679,
    lon: 135.184,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://umie.jp/" },
    tags: ["mall", "umie", "harborland", "since_2013"],
    source: "manual",
  },
  {
    slug: "mint-kobe-2006",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "ミント神戸(2006・JR 三ノ宮駅前・若年向ファッション + 飲食 17 階)",
    title_ja: "ミント神戸",
    romaji: "Mint Kobe",
    summary_zh:
      "2006 JR 三ノ宮駅前に開業の若年向ファッション + 飲食複合ビル。17 階建・80 軒余。10-30 代女性向けセレクトショップ + 飲食街 + 映画館。神戸三宮駅徒歩 1 分の好立地。",
    content_md:
      "- 開業:2006\n- 立地:JR 三ノ宮駅前\n- 構成:17 階・80 軒余\n- 若年向ファッション + 映画館\n- 営業:11:00-22:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central"],
    lat: 34.694,
    lon: 135.197,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.mint-kobe.jp/" },
    tags: ["mall", "mint_kobe", "since_2006", "young_fashion"],
    source: "manual",
  },
  {
    slug: "sannomiya-opa-2008",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "三宮 OPA(2008・神戸三宮・10-20 代女性向 SHIBUYA109 系)",
    title_ja: "三宮 OPA",
    romaji: "Sannomiya OPA",
    summary_zh:
      "2008 神戸三宮駅前に開業の OPA(イオン系)。9 階・80 軒余。10-20 代女性向で SHIBUYA109 ABENO 系ブランド + 韓国 K ファッション。三宮センター街徒歩 3 分。",
    content_md:
      "- 開業:2008\n- 立地:神戸三宮\n- 9 階・80 軒余\n- 10-20 代女性向\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central"],
    lat: 34.694,
    lon: 135.197,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.opa-club.com/sannomiya/" },
    tags: ["mall", "opa", "sannomiya", "since_2008", "young_fashion"],
    source: "manual",
  },
  {
    slug: "kobe-international-1999",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "神戸国際会館 SOL(1999 開業・三宮御幸通・大型複合 + 国際ホール)",
    title_ja: "神戸国際会館 SOL",
    romaji: "Kobe International Hall SOL",
    summary_zh:
      "1999 神戸三宮御幸通に開業の大型複合ビル。地下 2 + 地上 16 階。神戸国際ホール(2000 席・コンサート + 演劇)+ 商業フロア『SOL』120 軒余。1995 阪神淡路大震災後の神戸復興 + 国際化象徴施設。",
    content_md:
      "- 開業:1999\n- 構成:地下 2 + 地上 16 階\n- 国際ホール:2000 席\n- 商業 SOL:120 軒余\n- 営業:10:00-22:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central"],
    lat: 34.692,
    lon: 135.197,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.kih.co.jp/" },
    tags: ["mall", "kobe_international", "since_1999", "concert_hall"],
    source: "manual",
  },
  {
    slug: "kobe-fashion-mart-1996",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "神戸ファッションマート(1996・六甲アイランド・関西アパレル B2B 拠点)",
    title_ja: "神戸ファッションマート",
    romaji: "Kobe Fashion Mart",
    summary_zh:
      "1996 六甲アイランドに開業の関西アパレル業界の B2B 拠点。アパレル卸 + デザイナー事務所 + ファッション関連企業 200 社余入居。一般客向け展示会 + イベント時のみ公開。神戸ファッション都市宣言(1973)の象徴施設。",
    content_md:
      "- 開業:1996\n- 立地:六甲アイランド\n- 業態:アパレル B2B 拠点\n- 入居:200 社余\n- 一般公開:イベント時のみ\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban", "coastal"],
    lat: 34.703,
    lon: 135.282,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["mall", "fashion_mart", "rokko_island", "since_1996", "b2b"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // D. 北野工房(1 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "kitano-koubou-1998",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "北野工房のまち(1998・1908 旧北野小学校改装・神戸体験工房モール)",
    title_ja: "北野工房のまち",
    romaji: "Kitano Kōbō no Machi",
    summary_zh:
      "1908 北野小学校(明治期木造 3 階建・登録有形文化財)を 1998 神戸市が体験工房モールに改装。20 軒余の体験工房(神戸スイーツ + 革製品 + 香水 + ステンドグラス + 陶芸 等)。北野異人館街徒歩 5 分のサブ観光地。入館無料。",
    content_md:
      "- 改装開業:1998\n- 建築:1908 旧北野小学校(登録文化財)\n- 工房:20 軒余\n- 体験:¥1500-5000\n- 入館:無料\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central"],
    lat: 34.700,
    lon: 135.190,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["craft_mall", "kitano_koubou", "since_1998", "登録文化財"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // E. アウトレット(2 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "mitsui-outlet-marinepia-1999",
    category: "fashion",
    sub_type: "outlet_mall",
    title_zh: "三井アウトレットパーク マリンピア神戸(1999・垂水・瀬戸内海ビュー)",
    title_ja: "三井アウトレットパーク マリンピア神戸",
    romaji: "Mitsui Outlet Park Marinepia Kobe",
    summary_zh:
      "1999 神戸垂水(瀬戸内海沿)に開業の三井アウトレット。140 軒余。瀬戸内海 + 明石海峡大橋ビューが特色の海辺アウトレット。JR 垂水駅徒歩 7 分・明石海峡大橋徒歩 15 分。",
    content_md:
      "- 開業:1999\n- 立地:垂水(瀬戸内海沿)\n- 店舗:140 軒余\n- 明石海峡大橋ビュー\n- 営業:10:00-20:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban", "coastal"],
    lat: 34.620,
    lon: 135.052,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://mitsui-shopping-park.com/mop/kobe/" },
    tags: ["outlet", "marinepia", "tarumi", "since_1999", "akashi_kaikyo"],
    source: "manual",
  },
  {
    slug: "kobe-sanda-premium-outlets-2007",
    category: "fashion",
    sub_type: "outlet_mall",
    title_zh: "神戸三田プレミアム・アウトレット(2007・三田・関西最大級・210 軒)",
    title_ja: "神戸三田プレミアム・アウトレット",
    romaji: "Kobe Sanda Premium Outlets",
    summary_zh:
      "2007 三田市赤坂に開業の関西最大級プレミアムアウトレット。米三菱地所サイモン系で,210 軒余の高級ブランド集積。関西の高級アウトレット No.1。神戸三田駅 + 神戸電鉄から無料シャトル。",
    content_md:
      "- 開業:2007\n- 立地:三田市赤坂\n- 店舗:210 軒余\n- 関西最大級プレミアム\n- 神戸電鉄無料シャトル\n- 営業:10:00-20:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "三田市",
    lg_code: "28219",
    area_types: ["urban", "rural"],
    lat: 34.886,
    lon: 135.224,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.premiumoutlets.co.jp/kobesanda/" },
    tags: ["outlet", "premium", "sanda", "since_2007", "kansai_largest"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // F. 姫路(3 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "miyuki-dori-himeji-1934",
    category: "fashion",
    sub_type: "shopping_district_urban",
    title_zh: "みゆき通り 姫路(1934・JR 姫路駅 - 姫路城 600 m アーケード)",
    title_ja: "みゆき通り",
    romaji: "Miyuki-dōri",
    summary_zh:
      "1934 JR 姫路駅 - 姫路城を結ぶ 600 m 全蓋アーケード商店街。姫路市の代表観光商店街で,姫路城観光客 + 地元客混合。100 軒余の店舗 + 飲食 + 姫路土産。姫路駅から姫路城へのメインアプローチ。",
    content_md:
      "- 創設:1934\n- 距離:600 m アーケード\n- 店舗:100 軒余\n- JR 姫路駅 - 姫路城 連絡\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "姫路市",
    lg_code: "28201",
    area_types: ["urban"],
    lat: 34.832,
    lon: 134.694,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shopping_street", "miyuki", "himeji", "since_1934"],
    source: "manual",
  },
  {
    slug: "piole-himeji-2017",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "ピオレ姫路(2017・JR 姫路駅併設・JR 西日本系駅ビル)",
    title_ja: "ピオレ姫路",
    romaji: "Piole Himeji",
    summary_zh:
      "2017 JR 姫路駅併設に開業の JR 西日本系駅ビル『ピオレ姫路』。本館 + プラザ館の 2 棟構成,200 軒余。20-40 代女性向ファッション + 食 + 雑貨。姫路観光のベース駅商業。2024 全面リニューアル。",
    content_md:
      "- 開業:2017\n- 立地:JR 姫路駅併設\n- 構成:本館 + プラザ館・200 軒余\n- 2024 リニューアル\n- 営業:10:00-21:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "姫路市",
    lg_code: "28201",
    area_types: ["urban"],
    lat: 34.832,
    lon: 134.692,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.piole.jp/himeji/" },
    tags: ["mall", "piole", "himeji", "since_2017", "jr_west"],
    source: "manual",
  },
  {
    slug: "grand-festa-himeji-2003",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "グランフェスタ 姫路(2003・JR 姫路駅地下街・100 軒)",
    title_ja: "グランフェスタ 姫路",
    romaji: "Grand Festa Himeji",
    summary_zh:
      "2003 JR 姫路駅地下に開業の地下街型商業施設。100 軒余の飲食 + ファッション + 雑貨。姫路駅地下を通過する観光客 + 通勤客の生活商業。",
    content_md:
      "- 開業:2003\n- 立地:JR 姫路駅地下\n- 店舗:100 軒余\n- 営業:10:00-21:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "姫路市",
    lg_code: "28201",
    area_types: ["urban"],
    lat: 34.832,
    lon: 134.692,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.grandfesta.com/" },
    tags: ["mall", "grand_festa", "himeji", "since_2003", "underground"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // G. 西宮・甲子園(2 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "nishinomiya-gardens-2008",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "阪急西宮ガーデンズ(2008・西宮北口・関西最大級駅前モール 260 軒)",
    title_ja: "阪急西宮ガーデンズ",
    romaji: "Hankyū Nishinomiya Gardens",
    summary_zh:
      "2008 阪急西宮北口駅前に開業の関西最大級駅前モール。地上 4 階・260 軒余。阪急百貨店 + 109 シネマズ + 飲食 + ファッション総合。西宮市民 + 阪急沿線住民の中核商業施設。屋上スカイガーデン。",
    content_md:
      "- 開業:2008\n- 立地:阪急西宮北口\n- 構成:地上 4 階・260 軒余\n- 阪急百貨店 + 109 シネマズ\n- 関西最大級駅前モール\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "西宮市",
    lg_code: "28204",
    area_types: ["urban"],
    lat: 34.730,
    lon: 135.339,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://nishinomiya-gardens.com/" },
    tags: ["mall", "nishinomiya_gardens", "hankyu", "since_2008", "kansai_largest"],
    source: "manual",
  },
  {
    slug: "lalaport-koshien-2008",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "ららぽーと甲子園(2008・西宮甲子園・三井不動産系・タイガース戦客併用)",
    title_ja: "ららぽーと甲子園",
    romaji: "Lalaport Kōshien",
    summary_zh:
      "2008 阪神甲子園球場対岸に開業のららぽーと(三井不動産系)。地上 3 階・210 軒余。阪神タイガース戦観客の試合前後利用 + 西宮 + 尼崎の家族客向。子供向け施設充実。",
    content_md:
      "- 開業:2008\n- 立地:西宮甲子園(球場対岸)\n- 店舗:210 軒余\n- タイガース戦客併用\n- 営業:10:00-21:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "西宮市",
    lg_code: "28204",
    area_types: ["urban"],
    lat: 34.713,
    lon: 135.371,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://mitsui-shopping-park.com/lalaport/koshien/" },
    tags: ["mall", "lalaport", "koshien", "since_2008", "tigers_adj"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // H. 有馬温泉土産街(1 筆)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "arima-onsen-omiyage-shotengai",
    category: "fashion",
    sub_type: "shopping_district_local",
    title_zh: "有馬温泉 土産商店街(湯本街 + 太閤通・炭酸せんべい + 玩具筆 + 有馬籠)",
    title_ja: "有馬温泉 湯本街",
    romaji: "Arima Onsen Yumoto-gai",
    summary_zh:
      "有馬温泉中心の土産商店街。湯本街 + 太閤通 + 太閤橋商店街の 3 街区,80 軒余の土産店 + 食堂。名物:有馬炭酸せんべい(1907 創始)+ 玩具筆 + 有馬籠 + 太閤の湯切手 + 黒豆。日本三古湯の温泉観光定番。",
    content_md:
      "- 範囲:湯本街 + 太閤通 + 太閤橋\n- 店舗:80 軒余\n- 名物:炭酸せんべい(1907)+ 玩具筆 + 有馬籠\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["mountain"],
    lat: 34.798,
    lon: 135.246,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shopping_street", "arima_omiyage", "tansan_senbei", "yumoto_gai"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // R3 expansion(2026-04-29・19 → 20)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "motomachi-koukashita-shotengai",
    category: "fashion",
    sub_type: "shopping_district_urban",
    title_zh: "元町高架下商店街(モトコー・1980s 形成・JR 元町駅高架下レトロ商店街)",
    title_ja: "元町高架下商店街",
    romaji: "Motomachi Kōkashita Shōtengai",
    summary_zh:
      "JR 元町駅 - 神戸駅間の高架下に 1980s 形成された 1.2 km の細長いレトロ商店街(通称『モトコー』)。100 軒余の小規模店 + 古着 + 雑貨 + 中古レコード + バー集積。神戸 1995 阪神淡路大震災後の復興象徴的商店街で,現代神戸下町文化のアイコン。",
    content_md:
      "- 形成:1980s\n- 距離:1.2 km(JR 元町 - 神戸高架下)\n- 通称:モトコー\n- 店舗:100 軒余\n- 古着 + 雑貨 + 中古レコード\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central"],
    lat: 34.689,
    lon: 135.185,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shopping_street", "motoko", "kokashita", "vintage", "kobe_shitamachi"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // R6 expansion(2026-04-29・20 → 25)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "aeon-mall-itami-2007",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "イオンモール伊丹(2007 リニューアル・1985 ジャスコ伊丹店起源・北摂大型モール)",
    title_ja: "イオンモール伊丹",
    romaji: "Aeon Mall Itami",
    summary_zh:
      "1985 ジャスコ伊丹店として開業 → 2001 イオン化 → 2007 イオンモール化リニューアル。地上 4 階・260 軒余の北摂大型モール。伊丹空港アクセス + 阪急伊丹駅徒歩 5 分。家族向けで尼崎・伊丹・宝塚の生活商業核。",
    content_md:
      "- 起源:1985 ジャスコ伊丹店\n- 2007 イオンモール化リニューアル\n- 構成:地上 4 階・260 軒余\n- 阪急伊丹駅徒歩 5 分\n- 営業:10:00-21:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "伊丹市",
    lg_code: "28207",
    area_types: ["urban"],
    lat: 34.785,
    lon: 135.402,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://itami-aeonmall.com/" },
    tags: ["mall", "aeon", "itami", "since_1985"],
    source: "manual",
  },
  {
    slug: "aeon-mall-kobe-kita-2008",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "イオンモール神戸北(2008・神戸北区上津台・北神戸 + 三田アクセス)",
    title_ja: "イオンモール神戸北",
    romaji: "Aeon Mall Kobe Kita",
    summary_zh:
      "2008 神戸北区上津台に開業の郊外型イオンモール。地上 3 階・220 軒余。神戸電鉄 + 北神急行アクセス + 中国自動車道神戸三田 IC 直近。北神戸 + 三田 + 三木の家族客向け。",
    content_md:
      "- 開業:2008\n- 立地:神戸北区上津台\n- 構成:地上 3 階・220 軒余\n- 中国自動車道神戸三田 IC 直近\n- 営業:10:00-21:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban", "suburban"],
    lat: 34.811,
    lon: 135.158,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://kobekita-aeonmall.com/" },
    tags: ["mall", "aeon", "kobe_kita", "since_2008"],
    source: "manual",
  },
  {
    slug: "aeon-mall-amagasaki-2009",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "イオンモール尼崎(2009・尼崎市潮江・JR 尼崎駅前・関西最大級イオン 270 軒)",
    title_ja: "イオンモール尼崎",
    romaji: "Aeon Mall Amagasaki",
    summary_zh:
      "2009 尼崎市潮江(JR 尼崎駅前)に開業の関西最大級イオンモール。地上 4 階・270 軒余。JR 神戸線・福知山線 + 阪神なんば線アクセスで,大阪 + 神戸両方からの集客。家族向け + ファッション充実。",
    content_md:
      "- 開業:2009\n- 立地:JR 尼崎駅前\n- 構成:地上 4 階・270 軒余\n- 関西最大級イオン\n- 営業:10:00-22:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "尼崎市",
    lg_code: "28202",
    area_types: ["urban"],
    lat: 34.736,
    lon: 135.421,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["mall", "aeon", "amagasaki", "since_2009", "kansai_largest"],
    source: "manual",
  },
  {
    slug: "aeon-mall-himeji-rivercity-2007",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "イオンモール姫路リバーシティ(2007・姫路飾磨・市川河畔・西播磨集客)",
    title_ja: "イオンモール姫路リバーシティ",
    romaji: "Aeon Mall Himeji Rivercity",
    summary_zh:
      "2007 姫路市飾磨区中島(市川河畔)に開業のイオンモール。地上 3 階・220 軒余。西播磨地域(姫路 + たつの + 赤穂 + 相生)からの郊外客向け。山陽電鉄『飾磨駅』+ JR 山陽本線『姫路駅』からシャトルバス。",
    content_md:
      "- 開業:2007\n- 立地:姫路市飾磨区(市川河畔)\n- 構成:地上 3 階・220 軒余\n- 西播磨集客\n- 営業:10:00-21:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "姫路市",
    lg_code: "28201",
    area_types: ["urban"],
    lat: 34.812,
    lon: 134.685,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["mall", "aeon", "himeji", "since_2007", "harima_west"],
    source: "manual",
  },
  {
    slug: "nikke-park-town-itami-1985",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "ニッケパークタウン(1985・伊丹美鈴町・ニッケ毛織旧工場跡・関西最古級モール)",
    title_ja: "ニッケパークタウン",
    romaji: "Nikke Park Town",
    summary_zh:
      "1985 伊丹市美鈴町(日本毛織伊丹工場跡地)に開業の関西最古級ショッピングモール。日本毛織(ニッケ・1896 創業)が工場閉鎖後の跡地を商業転用。地上 3 階・150 軒余。伊丹中心市街地からは離れ,郊外型大型店として発展。",
    content_md:
      "- 開業:1985(関西最古級モール)\n- 立地:伊丹市美鈴町(ニッケ毛織旧工場跡)\n- 構成:地上 3 階・150 軒余\n- 営業:10:00-21:00\n- 2026-04 人工查核",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "伊丹市",
    lg_code: "28207",
    area_types: ["urban"],
    lat: 34.787,
    lon: 135.402,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["mall", "nikke", "itami", "since_1985", "kansai_oldest_mall"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R2 補完(老卷・2026-04-29)— 兵庫衣 25 → 35(+10)
  // 5 国の伝統工芸 5(赤穂緞通・出石焼・丹波布・三木金物・淡路瓦)+
  // 浴衣文化 2(有馬・城崎)+ 百貨店 mall 2 + 南京町
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "akoo-dantsu-1786",
    category: "fashion",
    sub_type: "textile_traditional",
    title_zh: "赤穂緞通(1786 創業・国指定伝統的工芸品 1979・全国唯一の手織絨毯老舗産地)",
    title_ja: "赤穂緞通",
    romaji: "Akoo Dantsu",
    summary_zh: "**赤穂緞通は江戸期発祥の手織絨毯**(赤穂市・天明6年/1786 創業)。児島小三郎が中国緞通を改良して興した、日本初の純国産絨毯産地。畳に合う色彩感覚 + 手織の風合いで江戸期から将軍家・大名家への献上品として知られた、現存する全国唯一の伝統的緞通産地。経済産業大臣指定伝統的工芸品(1979)。",
    content_md: "- 創業:1786 年(天明6)赤穂市\n- 興起者:児島小三郎(中国緞通技術を改良)\n- 認定:経済産業大臣指定伝統的工芸品(1979)\n- 全国位置:現存する純国産絨毯の唯一の伝統的産地\n- 製法:手織・1 平米に半年〜1 年・1 反で 100+ 工程\n- 主要工房:赤穂緞通工房 ながいだに・赤穂緞通復元工房 ほぼかい\n- 価格帯:座布団大 ¥80000-200000・1 畳 ¥500000-1500000\n- 体験:手織体験 ¥3000-(要事前予約)\n- 立地:赤穂市内(赤穂城跡近く)\n- アクセス:JR 赤穂駅 から徒歩 + バス",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "赤穂市",
    lg_code: "28212",
    area_types: ["historic_district"],
    lat: 34.748,
    lon: 134.391,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 5,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["textile_traditional", "akoo_dantsu", "1786", "designated_craft_1979"],
    source: "manual",
  },
  {
    slug: "izushi-yaki-1789",
    category: "fashion",
    sub_type: "craft_goods",
    title_zh: "出石焼(1789 開発・国指定伝統的工芸品 1980・白磁器・但馬地方代表)",
    title_ja: "出石焼",
    romaji: "Izushi Yaki",
    summary_zh: "**出石焼は但馬地方の白磁器**(豊岡市出石町・寛政元年/1789 開発)。出石藩主 仙石氏が経済振興政策として始めた窯業、白い磁土で精緻な彫刻 + 透かし彫り技法が特徴。経済産業大臣指定伝統的工芸品(1980)。出石町の城下町(国選定重要伝統的建造物群保存地区 2007)と組合せて観光価値高。",
    content_md: "- 開発:1789 年(寛政元)豊岡市出石町\n- 興起:出石藩主 仙石氏の経済振興\n- 製法:純白の磁土+ 高度な彫刻 + 透かし彫り\n- 認定:経済産業大臣指定伝統的工芸品(1980)\n- 主要窯元:出石焼伝統産業会館 + 上田窯 + 兵左衛門窯 等\n- 出石町並み:国選定重要伝統的建造物群保存地区(2007)\n- 体験:絵付体験(¥1500-3000・各窯元)\n- 価格帯:小皿 ¥3000-・茶碗 ¥10000-・大皿 ¥20000+\n- 立地:豊岡市出石町(出石城跡周辺)\n- アクセス:JR 豊岡駅 から バス 30 分・出石下車",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "豊岡市",
    lg_code: "28209",
    area_types: ["historic_district", "rural_townscape"],
    lat: 35.461,
    lon: 134.872,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["craft_goods", "izushi_yaki", "1789", "designated_craft_1980", "tajima"],
    source: "manual",
  },
  {
    slug: "tanba-fu-1853",
    category: "fashion",
    sub_type: "textile_traditional",
    title_zh: "丹波布(1853 発祥・手織縞綿・丹波佐治・兵庫県指定伝統工芸品)",
    title_ja: "丹波布",
    romaji: "Tanba Fu",
    summary_zh: "**丹波布は丹波篠山発祥の手織縞綿織物**(丹波市青垣・嘉永6年/1853 発祥)。100 年以上途絶えていた江戸期の縞布を 1954 年柳宗悦の民藝運動で再生、丹波篠山の素朴な縞模様の手織綿として復興。兵庫県指定伝統工芸品。蒸し焼きにした絹糸を縦に、綿糸を横に織る半絹半綿が特徴。",
    content_md: "- 発祥:1853 年(嘉永6)丹波青垣\n- 復興:1954 年 柳宗悦(民藝運動)が再発見\n- 認定:兵庫県指定伝統工芸品\n- 製法:絹糸(縦)+ 綿糸(横)・半絹半綿の独特織り\n- 染料:藍 + 茜 + 栗皮 等の植物染料\n- 主要工房:丹波布伝承館(丹波市青垣)・丹波布手織体験館\n- 体験:手織体験(¥3000-5000・要事前予約)\n- 価格帯:小物 ¥3000-15000・反物 ¥80000-300000\n- 立地:丹波市青垣町大名草(JR 福知山線 黒井駅 + バス 25 分)\n- アクセス:JR 黒井駅 から バス 25 分",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "丹波市",
    lg_code: "28223",
    area_types: ["rural_townscape", "historic_district"],
    lat: 35.184,
    lon: 134.961,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["textile_traditional", "tanba_fu", "1853", "yanagi_soetsu_1954"],
    source: "manual",
  },
  {
    slug: "miki-kanamono-1996",
    category: "fashion",
    sub_type: "craft_goods",
    title_zh: "三木金物(東播州刃物・国指定伝統的工芸品 1996・大工道具発祥地)",
    title_ja: "三木金物(播州三木打刃物)",
    romaji: "Miki Kanamono",
    summary_zh: "**三木金物は東播州地方の鍛冶業集積**(三木市・古代~)。「東播州刃物」「播州三木打刃物」として国指定伝統的工芸品(1996)、大工道具(鋸・鉋・鑿・ノミ等)の全国 No.1 産地。豊臣秀吉の三木合戦(1578-1580)後、廃城材の鍛冶需要から発展、現在も三木金物まつり(11 月)で全国の大工が集まる。",
    content_md: "- 起源:古代(平安期から)・本格化は江戸期\n- 認定:経済産業大臣指定伝統的工芸品(1996)\n- 主要製品:鋸 + 鉋 + 鑿(のみ)+ 小刀 + 鏝(こて)+ 鎌\n- 全国位置:大工道具で日本 No.1 産地\n- 三木金物まつり:11 月初・全国の大工 + 金物職人が集結\n- 主要販売所:三木金物会館 + 三木金物資料館\n- 価格帯:鉋 ¥5000-50000・鋸 ¥3000-30000・小刀 ¥4000-20000\n- 立地:三木市内\n- アクセス:JR 三木駅 + 神戸電鉄三木駅",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "三木市",
    lg_code: "28215",
    area_types: ["urban_central", "industrial_heritage"],
    lat: 34.797,
    lon: 134.989,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["craft_goods", "miki_kanamono", "designated_craft_1996", "japan_no1_carpenter_tools"],
    source: "manual",
  },
  {
    slug: "awaji-kawara-1648",
    category: "fashion",
    sub_type: "craft_goods",
    title_zh: "淡路瓦(1648 発祥・国指定伝統的工芸品 2017・全国 3 大瓦産地の 1)",
    title_ja: "淡路瓦",
    romaji: "Awaji Kawara",
    summary_zh: "**淡路瓦は淡路島発祥の伝統瓦**(慶安元年/1648・南あわじ市)。江戸期 大坂城築城の余瓦工が淡路に移住、淡路の粘土と瀬戸内の海潮風土で「いぶし瓦」(銀燻調)を量産。三州(愛知)+ 石州(島根)と並ぶ「日本 3 大瓦産地」、国指定伝統的工芸品(2017)。社寺・古民家の屋根瓦に多用。",
    content_md: "- 発祥:1648 年(慶安元)淡路\n- 由来:大坂城築城の余瓦工が淡路移住\n- 認定:経済産業大臣指定伝統的工芸品(2017)\n- 全国位置:三州(愛知)+ 石州(島根)と並ぶ「日本 3 大瓦産地」\n- 主要製法:いぶし瓦(銀燻調・還元焼成)\n- 用途:社寺・古民家・現代和風建築の屋根瓦\n- 体験:淡路瓦工房 体験(¥1500-3000・要予約)\n- 主要工房:鬼瓦匠の里 + 淡路瓦工業組合\n- 立地:南あわじ市津井(瓦の里)\n- アクセス:JR 三宮駅 から高速バス 約 90 分・淡路島へ",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "南あわじ市",
    lg_code: "28224",
    area_types: ["industrial_heritage", "rural_townscape"],
    lat: 34.301,
    lon: 134.762,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["craft_goods", "awaji_kawara", "1648", "designated_craft_2017", "japan_3_kawara"],
    source: "manual",
  },
  {
    slug: "arima-onsen-yukata-rental",
    category: "fashion",
    sub_type: "kimono_rental",
    title_zh: "有馬温泉浴衣文化(日本三古湯・温泉街浴衣散策・湯本街風情)",
    title_ja: "有馬温泉 浴衣文化",
    romaji: "Arima Yukata Culture",
    summary_zh: "**有馬温泉では旅館宿泊客の浴衣街歩き文化が定着**。1300 年以上の歴史を持つ日本三古湯、太閤橋 + 金の湯 + 銀の湯 + 湯泉神社 を浴衣で巡る湯本街の伝統。温泉旅館の宿泊浴衣 + 太閤通り + 湯本坂の石畳と組合せて、関西を代表する温泉街浴衣風情。日帰り浴衣レンタル店も 2-3 軒。",
    content_md: "- 立地:神戸市北区有馬町(神戸の奥座敷)\n- 歴史:1300 年以上(日本三古湯・道後+白浜と並ぶ)\n- 文化:温泉旅館の浴衣で湯本坂・太閤通り散策\n- 主要散策スポット:金の湯(公衆湯)+ 銀の湯 + 湯泉神社 + 太閤橋 + 念仏寺\n- 日帰り浴衣レンタル:2-3 軒(¥3000-5000・着付け+草履付)\n- 営業:9:00-18:00\n- 似合うシーン:湯本坂石畳・太閤橋・金の湯前\n- アクセス:神戸電鉄 有馬温泉駅 徒歩 5 分・JR 三宮 + 阪急梅田 から有馬急行バス",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["onsen_town", "historic_district"],
    lat: 34.799,
    lon: 135.247,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 1,
    closed_days: [],
    external_urls: {},
    tags: ["kimono_rental", "arima_yukata", "japan_3_oldest_onsen", "kobe"],
    source: "manual",
  },
  {
    slug: "kinosaki-sotoyu-yukata",
    category: "fashion",
    sub_type: "kimono_rental",
    title_zh: "城崎温泉外湯巡り浴衣(7 つの外湯・1300 年の浴衣街道・全国級温泉浴衣聖地)",
    title_ja: "城崎温泉 外湯巡り浴衣",
    romaji: "Kinosaki Yukata",
    summary_zh: "**城崎温泉外湯巡り浴衣は全国級の温泉浴衣聖地**(豊岡市城崎温泉)。1300 年の歴史 + 7 つの外湯(一の湯・地蔵湯・柳湯・御所の湯・まんだら湯・鴻の湯・さとの湯)を浴衣 + 下駄 で巡る伝統。温泉宿の宿泊客は外湯入湯券無料、夕涼みの浴衣下駄カランコロンの音色が城崎の代名詞。志賀直哉「城の崎にて」の舞台。",
    content_md: "- 立地:豊岡市城崎温泉\n- 歴史:1300 年以上(舒明天皇期~)\n- 7 つの外湯:一の湯・地蔵湯・柳湯・御所の湯・まんだら湯・鴻の湯・さとの湯\n- 浴衣文化:温泉旅館の宿泊浴衣 + 下駄 で 7 外湯を巡る\n- 文学:志賀直哉「城の崎にて」(1917・大正6)の舞台\n- 入湯券:温泉宿宿泊客は外湯巡り入湯券無料 + 不泊客は ¥1300\n- 営業:外湯各 7:00-23:00(店舗別)\n- 浴衣レンタル:町内多数(¥3000-5000)・宿泊客は宿提供\n- アクセス:JR 城崎温泉駅 徒歩 5 分(温泉街中心)",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "豊岡市",
    lg_code: "28209",
    area_types: ["onsen_town", "historic_district"],
    lat: 35.625,
    lon: 134.806,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://kinosaki-spa.gr.jp/" },
    tags: ["kimono_rental", "kinosaki_yukata", "1300_years", "shiga_naoya", "7_sotoyu"],
    source: "manual",
  },
  {
    slug: "sanyo-himeji-1953",
    category: "fashion",
    sub_type: "hyogo_dept_store",
    title_zh: "山陽百貨店(姫路・1953 開業・JR 姫路駅前・地元上層客代表)",
    title_ja: "山陽百貨店",
    romaji: "Sanyo Department Store",
    summary_zh: "**山陽百貨店は姫路の老舗百貨店**(1953 開業・山陽電鉄系)。70 年余、JR 姫路駅前のランドマーク的百貨店、地元中・上層客の常用店。本館 + 別館の 2 棟体制、地下食品 + 婦人/紳士ファッション + 8F レストラン街の伝統的構成。姫路城観光客のお土産購入地としても定着。",
    content_md: "- 開業:1953 年(昭和28)姫路\n- 系列:山陽電鉄(山電)\n- 立地:JR 姫路駅 北口 徒歩 0 分(駅前)\n- 規模:本館 + 別館・延床面積 約 4 万 m²\n- 構成:B1F 食品・1F 化粧品・2-7F 婦人/紳士/子供 ファッション・8F レストラン街\n- 客層:姫路+西播磨地区の中・上層客\n- 営業:10:00-19:30\n- 周辺:姫路城(徒歩 12 分)・大手前通り\n- アクセス:JR 姫路駅 北口 徒歩 0 分・山陽電鉄 山陽姫路駅 直結",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "姫路市",
    lg_code: "28201",
    area_types: ["urban_central"],
    lat: 34.829,
    lon: 134.690,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.sanyo-dp.co.jp/" },
    tags: ["hyogo_dept_store", "sanyo_himeji", "1953", "himeji_landmark"],
    source: "manual",
  },
  {
    slug: "mosaic-harborland-1992",
    category: "fashion",
    sub_type: "hyogo_mall_building",
    title_zh: "神戸ハーバーランド モザイク(1992 開業・神戸港絶景・観覧車併設)",
    title_ja: "神戸ハーバーランド モザイク",
    romaji: "Mosaic Harborland",
    summary_zh: "**モザイクは神戸ハーバーランドの港湾型 mall**(1992 開業)。神戸港のメリケンパーク + ポートタワー + 神戸海洋博物館 を一望、地中海風建築 + 観覧車「アンパンマンこどもミュージアム」併設。約 60 店舗のファッション・カフェ・レストラン、神戸夜景デート定番。",
    content_md: "- 開業:1992 年(平成4)神戸\n- 立地:神戸市中央区東川崎町(ハーバーランド)\n- 構成:地中海風建築のショッピングストリート + 観覧車 + アンパンマンこどもミュージアム\n- 店舗数:約 60(ファッション + カフェ + レストラン + 雑貨)\n- 観覧車:大観覧車「神戸ハーバーランド モザイクの大観覧車」(高さ 50m・¥800)\n- 食事:海岸通りの海鮮レストラン + ハーバーランド内カフェ\n- 営業:10:00-20:00(レストラン 22:00 まで)\n- 周辺:神戸ポートタワー + メリケンパーク + 神戸海洋博物館 + 神戸大橋\n- アクセス:JR 神戸駅 徒歩 8 分・地下鉄ハーバーランド駅 徒歩 5 分",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central", "fishing_port"],
    lat: 34.681,
    lon: 135.183,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://umie.jp/" },
    tags: ["hyogo_mall_building", "mosaic", "harborland", "1992", "kobe_port"],
    source: "manual",
  },
  {
    slug: "nankin-machi-china-1868",
    category: "fashion",
    sub_type: "shopping_district_urban",
    title_zh: "神戸南京町(中華街・1868 神戸開港由来・約 100 軒・チャイナ雑貨+食+衣)",
    title_ja: "神戸南京町",
    romaji: "Kobe Nankin-machi",
    summary_zh: "**神戸南京町は神戸の中華街**(中央区元町・1868 神戸開港由来)。日本三大中華街(横浜中華街・長崎新地中華街・神戸南京町)の 1、約 100 軒の中華料理店 + チャイナ雑貨 + チャイナドレス販売店が集積。元町商店街隣接、観光客向けに横浜より小規模だがコンパクトに歩ける。",
    content_md: "- 立地:神戸市中央区元町通(元町商店街隣接)\n- 由来:1868 年(慶応4)神戸開港 + 中国人居留地として発展\n- 規模:東西約 200m・南北約 100m\n- 全国位置:日本三大中華街(横浜+長崎新地+神戸南京町)\n- 店舗:約 100 軒(中華料理 + 中華食材 + チャイナ雑貨 + チャイナドレス)\n- 衣関連:チャイナドレス専門店 3-4 軒(¥10000-50000)・中華雑貨 + アクセサリー\n- 営業:店舗別(平均 10:00-22:00)\n- 春節:1-2 月の中華旧正月期に大規模イベント\n- アクセス:JR 元町駅 + 阪神元町駅 徒歩 3 分",
    region: "kansai",
    prefecture_ja: "兵庫県",
    gun_ja: null,
    municipality_ja: "神戸市",
    lg_code: "28100",
    area_types: ["urban_central", "historic_district"],
    lat: 34.690,
    lon: 135.187,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://nankinmachi.or.jp/" },
    tags: ["shopping_district_urban", "nankin_machi", "kobe_chinatown", "1868"],
    source: "manual",
  },
];

async function main() {
  console.log(`[seed] ${rows.length} rows to seed`);
  const byKind: Record<string, number> = {};
  for (const r of rows) byKind[r.sub_type] = (byKind[r.sub_type] ?? 0) + 1;
  console.log(`[seed] by sub_type: ${JSON.stringify(byKind, null, 2)}`);

  if (DRY) {
    for (const r of rows) {
      console.log(
        `  [${r.sub_type.padEnd(28)}] ${r.title_zh} (${r.municipality_ja ?? "-"}/${r.lg_code ?? "-"})`,
      );
    }
    return;
  }

  const sb = createAdminClient();
  const { data, error } = await sb
    .from("japan_entries")
    .upsert(rows, { onConflict: "slug" })
    .select("id, slug");
  if (error) {
    console.error("[seed] upsert failed", error);
    process.exit(1);
  }
  console.log(`[seed] upserted ${data?.length ?? 0} rows`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
