// Seed 群馬県 食 R1(25 筆 / Sprint 1.1 / 第〇十卷 開卷)
//
// 群馬 3 大名物 5(上州牛+下仁田ねぎ+こんにゃく+水沢うどん+上州うどん) /
// 郷土食 4 / 川魚 2 / 果実 3 / 銘菓 5 / 酒 3 / 米肉野菜 3 = 25

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "群馬県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 群馬 3 大名物 (5)
  { slug: "joshu-gyu-1980", category: "food", sub_type: "gunma_3_meibutsu", title_zh: "上州牛(渋川+前橋+昭和村+ 1980 年代ブランド化 45 年+ 県内 約 250 戸生産・A4 以上限定+ 山形米沢牛+栃木とちぎ和牛と並ぶ北関東甲信ブランド和牛+ 老舗料亭+ステーキハウス 10+ 軒+ ¥6,500-15,000/100g)", title_ja: "上州牛", romaji: "Jōshū Gyū", summary_zh: "**上州牛は 1980 年代ブランド化 45 年・県内 250 戸生産・A4 以上限定**(渋川+前橋+昭和村)。米沢牛+とちぎ和牛と並ぶ北関東甲信ブランド和牛、¥6,500-15,000/100g。", content_md: "- 立地:**渋川市 + 前橋市 + 利根郡昭和村**\n- 起源:**1980 年代ブランド化 45 年**\n- 認定:**県内 約 250 戸生産・A4 以上限定**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["farm_field", "restaurant_traditional"], lat: 36.4886, lon: 138.9242, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["joshu_gyu", "1980", "wagyu_a4"], source: "manual" },
  { slug: "shimonita-negi-edo", category: "food", sub_type: "gunma_3_meibutsu", title_zh: "下仁田ねぎ(甘楽郡下仁田町・江戸期 1645 創出 380 年+ 「殿様ねぎ」幕府献上+ 全国白ねぎ品種代表+ 11-3 月旬+ 道の駅+地元食堂+全国百貨店流通+ R1 楽 下仁田ねぎ祭連動+ 1 束 ¥800-2,500)", title_ja: "下仁田ねぎ", romaji: "Shimonita Negi", summary_zh: "**下仁田ねぎは江戸期 1645 創出 380 年・「殿様ねぎ」幕府献上**(下仁田・**全国白ねぎ品種代表**)。11-3 月、道の駅+食堂+百貨店、¥800-2,500/束。", content_md: "- 立地:**甘楽郡下仁田町**\n- 起源:**江戸期 1645 創出 380 年**\n- 認定:**「殿様ねぎ」幕府献上 + 全国白ねぎ品種代表**\n- 期:**11-3 月旬**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "甘楽郡", municipality_ja: "下仁田町", lg_code: "10384", area_types: ["farm_field"], lat: 36.2542, lon: 138.7969, season_start: "2026-11-01", season_end: "2027-03-31", event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["shimonita_negi", "1645", "380_years", "shogun_negi"], source: "manual" },
  { slug: "gunma-konnyaku-no1-95", category: "food", sub_type: "gunma_3_meibutsu", title_zh: "群馬こんにゃく(下仁田+渋川+富岡・全国こんにゃく芋生産量 No.1 県・95% シェア+ 江戸期から栽培+ こんにゃくパーク無料工場見学・全国百貨店ヒット+ 刺身こんにゃく+田楽+おでん・¥150-1,200)", title_ja: "群馬こんにゃく", romaji: "Gunma Konnyaku", summary_zh: "**群馬こんにゃくは全国生産量 No.1 県・95% シェア**(下仁田+渋川+富岡・**江戸期から栽培**)。こんにゃくパーク無料工場見学、刺身+田楽+おでん、¥150-1,200。", content_md: "- 立地:**下仁田町 + 渋川市 + 富岡市**\n- 認定:**全国こんにゃく芋生産量 No.1 県・95% シェア**\n- 起源:**江戸期から栽培**\n- 関連:**こんにゃくパーク無料工場見学**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "甘楽郡", municipality_ja: "甘楽町", lg_code: "10383", area_types: ["industrial_heritage", "farm_field"], lat: 36.2517, lon: 138.8556, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["gunma_konnyaku", "no1_japan", "95_percent"], source: "manual" },
  { slug: "mizusawa-udon-440", category: "food", sub_type: "gunma_3_meibutsu", title_zh: "水沢うどん(渋川市伊香保水沢・天正 10 年 1582 創始 443 年+ 「日本三大うどん」候補(讃岐+稲庭+水沢)+ 13 軒老舗+ R1 住 伊香保温泉観光連動+ 1 杯 ¥1,200-2,500+ 国内+海外観光客代表)", title_ja: "水沢うどん", romaji: "Mizusawa Udon", summary_zh: "**水沢うどんは天正 10 年 1582 創始 443 年・「日本三大うどん」候補**(渋川伊香保・**讃岐+稲庭+水沢**)。13 軒老舗、R1 住 伊香保温泉、¥1,200-2,500、国内+海外観光客代表。", content_md: "- 立地:**渋川市伊香保水沢**\n- 起源:**天正 10 年 1582 創始 443 年**\n- 認定:**「日本三大うどん」候補(讃岐 + 稲庭 + 水沢)**\n- 規模:**13 軒老舗**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["restaurant_traditional"], lat: 36.4856, lon: 138.9233, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mizusawa_udon", "1582", "443_years", "japan_3_udon"], source: "manual" },
  { slug: "joshu-udon-edo", category: "food", sub_type: "gunma_3_meibutsu", title_zh: "上州うどん+ 桐生ひもかわうどん(全県・桐生+伊勢崎・江戸期から伝統+ 群馬小麦 No.2 県原料・桐生ひもかわ「幅広 5cm+」関東屈指麺・うどん店全県 200+ 軒+ 1 杯 ¥800-1,800+ 観光客向け)", title_ja: "上州うどん+ひもかわ", romaji: "Jōshū Udon", summary_zh: "**上州うどん+桐生ひもかわうどんは江戸期から伝統・群馬小麦 No.2 県原料**(全県・**桐生ひもかわ「幅広 5cm+」関東屈指麺**)。県内 200+ 軒、¥800-1,800。", content_md: "- 全域:**群馬県全域**(特に桐生 + 伊勢崎)\n- 起源:**江戸期から伝統**\n- 認定:**群馬小麦全国 No.2 県原料**\n- 構成:**桐生ひもかわ「幅広 5cm+」関東屈指麺**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "桐生市", lg_code: "10203", area_types: ["restaurant_traditional"], lat: 36.4044, lon: 139.3306, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["joshu_udon", "kiryu_himokawa"], source: "manual" },

  // 郷土食 (4)
  { slug: "gunma-motsuni-stew", category: "food", sub_type: "gunma_kyodo", title_zh: "群馬もつ煮(永井食堂 渋川市・1953 創業 72 年+ 北関東もつ煮代表・大鍋煮込み 4-5 時間+ 朝 5 時開店から行列・1 杯 ¥800-1,200+ 全国 B 級グルメファン代表+ 「もつ煮の聖地」として国内+海外観光客 SNS 拡散)", title_ja: "群馬もつ煮", romaji: "Gunma Motsuni", summary_zh: "**群馬もつ煮(永井食堂)は 1953 創業 72 年・北関東もつ煮代表**(渋川・**大鍋煮込み 4-5 時間+朝 5 時行列**)。¥800-1,200、「もつ煮の聖地」、国内+海外 SNS 拡散。", content_md: "- 立地:**渋川市**\n- 起源:**1953 創業 72 年**\n- 看板:**「もつ煮の聖地」**\n- 構成:**大鍋煮込み 4-5 時間 + 朝 5 時開店行列**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["restaurant_traditional"], lat: 36.4886, lon: 138.9242, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["gunma_motsuni", "1953", "72_years"], source: "manual" },
  { slug: "yaki-manju-gunma", category: "food", sub_type: "gunma_kyodo", title_zh: "焼まんじゅう(全県・江戸期末期 1850 年代発祥+ 群馬独自郷土食・四角酒種まんじゅう+味噌だれ+串焼き・全県 50+ 軒・1 串 4 個 ¥350-500+ 群馬代表 B 級+ 観光客向け代表土産)", title_ja: "焼まんじゅう", romaji: "Yaki Manjū", summary_zh: "**焼まんじゅうは江戸期末期 1850 年代発祥・群馬独自郷土食**(全県・**四角酒種まんじゅう+味噌だれ+串焼き**)。50+ 軒、¥350-500/4 個串、群馬 B 級代表。", content_md: "- 全域:**群馬県全域**\n- 起源:**江戸期末期 1850 年代発祥**\n- 認定:**群馬独自郷土食**\n- 構成:**四角酒種まんじゅう + 味噌だれ + 串焼き**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["restaurant_traditional"], lat: 36.3895, lon: 139.0635, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yaki_manju", "1850s_origin"], source: "manual" },
  { slug: "takasaki-sauce-katsudon", category: "food", sub_type: "gunma_kyodo", title_zh: "高崎ソースかつ丼+ B 級グルメ(高崎市・1899 創業説 126 年+ 「タレかつ丼」千キャベツ+ソースかつ・市内 30+ 軒+ 「高崎パスタの街」連動+ 1 杯 ¥1,200-2,200+ 観光客向け B 級代表)", title_ja: "高崎ソースかつ丼", romaji: "Takasaki Sauce Katsudon", summary_zh: "**高崎ソースかつ丼+B 級グルメは 1899 創業説 126 年・「タレかつ丼」千キャベツ+ソースかつ**(高崎・**市内 30+ 軒+高崎パスタの街連動**)。¥1,200-2,200、B 級代表。", content_md: "- 立地:**高崎市**\n- 起源:**1899 創業説 126 年**\n- 構成:**千キャベツ + ソースかつ**\n- 並列:**高崎パスタの街連動**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["restaurant_traditional"], lat: 36.3219, lon: 139.0033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["takasaki_katsudon", "1899", "126_years"], source: "manual" },
  { slug: "kiryu-himokawa-special", category: "food", sub_type: "gunma_kyodo", title_zh: "桐生ひもかわうどん(桐生市・江戸期 1700 年代+ 「ひもかわ」幅広 5-10cm 平打ち手打ち麺・市内 30+ 軒・道の駅・1 杯 ¥1,000-1,800+ R1 衣 桐生織 1300 年伝統 観光客向け代表 B 級+ ご当地代表)", title_ja: "桐生ひもかわうどん", romaji: "Kiryu Himokawa Udon", summary_zh: "**桐生ひもかわうどんは江戸期 1700 年代・「ひもかわ」幅広 5-10cm 平打ち手打ち麺**(桐生・**市内 30+ 軒**)。R1 衣 桐生織 1300 年連動、¥1,000-1,800、ご当地代表。", content_md: "- 立地:**桐生市**\n- 起源:**江戸期 1700 年代**\n- 構成:**「ひもかわ」幅広 5-10cm 平打ち手打ち麺**\n- 並列観光:**R1 衣 桐生織 1300 年伝統**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "桐生市", lg_code: "10203", area_types: ["restaurant_traditional"], lat: 36.4044, lon: 139.3306, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kiryu_himokawa", "edo_1700s"], source: "manual" },

  // 川魚 (2)
  { slug: "tone-river-ayu", category: "food", sub_type: "gunma_seafood", title_zh: "利根川あゆ(渋川+沼田+前橋・利根川+片品川 関東一級河川+ 友釣りあゆ伝承+ 6-9 月旬+ あゆ塩焼+刺身+南蛮漬+ R1 住 水上温泉+R1 育 谷川岳観光連動+ 1 尾 ¥800-1,800)", title_ja: "利根川あゆ", romaji: "Tone Ayu", summary_zh: "**利根川あゆは渋川+沼田+前橋・利根川+片品川関東一級河川**(**6-9 月旬・友釣りあゆ伝承**)。あゆ塩焼+刺身+南蛮漬、R1 住 水上+R1 育 谷川岳、¥800-1,800/尾。", content_md: "- 立地:**渋川市 + 沼田市 + 前橋市**\n- 河川:**利根川 + 片品川**\n- 期:**6-9 月旬**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["restaurant_traditional"], lat: 36.3895, lon: 139.0635, season_start: "2026-06-01", season_end: "2026-09-30", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tone_ayu"], source: "manual" },
  { slug: "minakami-yamame-trout", category: "food", sub_type: "gunma_seafood", title_zh: "みなかみヤマメ+ニジマス(利根郡みなかみ町+片品+川場・標高 600-1500m 高山渓流+ 養殖場+渓流釣り+ 11-3 月旬+ R1 住 水上温泉+R1 育 谷川岳+R1 楽 川下り観光連動+ 1 人前 ¥2,500-5,500)", title_ja: "みなかみヤマメ", romaji: "Minakami Yamame", summary_zh: "**みなかみヤマメ+ニジマスは標高 600-1500m 高山渓流**(みなかみ+片品+川場・**11-3 月旬**)。R1 住 水上温泉+R1 育 谷川岳+R1 楽 川下り、¥2,500-5,500。", content_md: "- 立地:**利根郡みなかみ町 + 片品村 + 川場村**\n- 規模:**標高 600-1500m 高山渓流**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["restaurant_traditional", "scenic_spot"], lat: 36.7847, lon: 138.9558, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["minakami_yamame"], source: "manual" },

  // 果実 (3)
  { slug: "numata-ringo-tone", category: "food", sub_type: "gunma_fruit", title_zh: "沼田りんご+利根沼田りんご(沼田市+片品+川場・標高 300-800m 山地気候+ 1900 年代開発+ ふじ+つがる+秋映+ 9-11 月旬+ 観光りんご狩り 30+ 園+ R1 育 谷川岳+R1 住 水上観光連動+ 1kg ¥1,200-2,500)", title_ja: "沼田りんご", romaji: "Numata Ringo", summary_zh: "**沼田りんご+利根沼田りんごは標高 300-800m 山地気候・1900 年代開発**(沼田+片品+川場)。ふじ+つがる+秋映、9-11 月、狩り 30+ 園、¥1,200-2,500/kg。", content_md: "- 立地:**沼田市 + 利根郡片品村 + 川場村**\n- 規模:**標高 300-800m 山地気候**\n- 起源:**1900 年代開発**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "沼田市", lg_code: "10206", area_types: ["farm_field"], lat: 36.6453, lon: 139.0444, season_start: "2026-09-15", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["numata_ringo"], source: "manual" },
  { slug: "minakami-blueberry", category: "food", sub_type: "gunma_fruit", title_zh: "みなかみブルーベリー(利根郡みなかみ町・1990 年代開発+ ブルーベリー狩り 15+ 観光園+ 7-9 月旬+ R1 住 水上温泉+R1 楽 みなかみ川下り観光連動+ 1kg ¥3,500-7,500+ 国内家族観光客代表)", title_ja: "みなかみブルーベリー", romaji: "Minakami Blueberry", summary_zh: "**みなかみブルーベリーは 1990 年代開発・狩り 15+ 観光園**(みなかみ・**7-9 月旬**)。R1 住 水上+R1 楽 川下り連動、¥3,500-7,500/kg、家族観光客代表。", content_md: "- 立地:**利根郡みなかみ町**\n- 起源:**1990 年代開発**\n- 期:**7-9 月旬**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["farm_field"], lat: 36.7847, lon: 138.9558, season_start: "2026-07-01", season_end: "2026-09-30", event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["minakami_blueberry"], source: "manual" },
  { slug: "harune-ume-takasaki", category: "food", sub_type: "gunma_fruit", title_zh: "榛名梅+高崎の梅(高崎市榛名+箕郷+ 全国梅生産量 No.2 県・1980 年代以降産地化+ 2 月-3 月梅まつり+ 梅干し+梅酒+梅菓子+ R1 育 榛名神社観光連動+ 1kg ¥1,500-3,500)", title_ja: "榛名梅+高崎の梅", romaji: "Harune Ume", summary_zh: "**榛名梅+高崎の梅は全国生産量 No.2 県・1980 年代以降産地化**(高崎榛名+箕郷)。2-3 月梅まつり、梅干し+梅酒+梅菓子、R1 育 榛名神社、¥1,500-3,500/kg。", content_md: "- 立地:**高崎市榛名 + 箕郷**\n- 認定:**全国梅生産量 No.2 県**\n- 起源:**1980 年代以降産地化**\n- 期:**2 月-3 月梅まつり**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["farm_field"], lat: 36.4256, lon: 138.8597, season_start: "2026-02-15", season_end: "2026-03-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["harune_ume", "no2_japan"], source: "manual" },

  // 銘菓 (5)
  { slug: "kusatsu-onsen-manju", category: "food", sub_type: "gunma_meika", title_zh: "草津温泉まんじゅう(吾妻郡草津町・1900 年代開発+ R1 住 草津温泉 日本三名泉派生・温泉まんじゅう代表・湯畑周辺老舗 5+ 軒+ 観光客代表土産+ 1 個 ¥150-300+ 海外観光客 SNS 拡散)", title_ja: "草津温泉まんじゅう", romaji: "Kusatsu Onsen Manjū", summary_zh: "**草津温泉まんじゅうは 1900 年代開発・R1 住 草津温泉 日本三名泉派生**(温泉まんじゅう代表・**湯畑周辺老舗 5+ 軒**)。¥150-300、海外 SNS 拡散。", content_md: "- 立地:**吾妻郡草津町**\n- 起源:**1900 年代開発**\n- 関係:**R1 住 草津温泉日本三名泉派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["restaurant_traditional", "shopping_district"], lat: 36.6228, lon: 138.5969, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kusatsu_manju"], source: "manual" },
  { slug: "ikaho-ishidan-manju", category: "food", sub_type: "gunma_meika", title_zh: "伊香保湯の花まんじゅう(渋川市伊香保・湯の花まんじゅう発祥地・1910 大正期創業 115 年+ R1 住 伊香保温泉 1900 創設+石段街派生・茶色温泉色まんじゅう+ ¥150-1,200+ 観光客代表土産)", title_ja: "湯の花まんじゅう", romaji: "Yu no Hana Manjū", summary_zh: "**伊香保湯の花まんじゅうは湯の花まんじゅう発祥地・1910 大正期創業 115 年**(渋川伊香保・**R1 住 伊香保温泉+石段街派生**)。茶色温泉色まんじゅう、¥150-1,200、観光客代表土産。", content_md: "- 立地:**渋川市伊香保**\n- 起源:**1910 大正期創業 115 年**\n- 認定:**湯の花まんじゅう発祥地**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["restaurant_traditional", "shopping_district"], lat: 36.4886, lon: 138.9242, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yu_no_hana_manju", "1910"], source: "manual" },
  { slug: "takasaki-daruma-monaka", category: "food", sub_type: "gunma_meika", title_zh: "高崎だるま最中+ R1 衣 高崎達磨派生(高崎市・R1 衣 高崎達磨全国 No.1 80% 派生・1950 年代開発・だるま型最中+ あんこ+クリーム+栗・JR 高崎駅売店+全国百貨店ヒット+ ¥350-1,500+ 観光客代表土産)", title_ja: "高崎だるま最中", romaji: "Takasaki Daruma Monaka", summary_zh: "**高崎だるま最中は R1 衣 高崎達磨 No.1 80% 派生・1950 年代開発**(だるま型+あん+クリーム+栗)。JR 高崎駅+全国百貨店、¥350-1,500、観光客代表土産。", content_md: "- 立地:**高崎市**\n- 関係:**R1 衣 高崎達磨全国 No.1 80% 派生**\n- 起源:**1950 年代開発**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["restaurant_traditional", "shopping_district"], lat: 36.3219, lon: 139.0033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["takasaki_daruma_monaka"], source: "manual" },
  { slug: "tomioka-silk-manju", category: "food", sub_type: "gunma_meika", title_zh: "富岡シルク饅頭+富岡製糸銘菓(富岡市・R1 育 富岡製糸場 1872 UNESCO 2014 派生・絹色まんじゅう+蚕シルクペーストパウンドケーキ・観光客向け代表土産+ ¥350-1,800+ 国際観光客 SNS 拡散)", title_ja: "富岡シルク饅頭", romaji: "Tomioka Silk Manjū", summary_zh: "**富岡シルク饅頭+富岡製糸銘菓は R1 育 富岡製糸場 1872 UNESCO 2014 派生**(絹色まんじゅう+蚕シルクペーストパウンドケーキ)。¥350-1,800、国際 SNS 拡散。", content_md: "- 立地:**富岡市**\n- 関係:**R1 育 富岡製糸場 1872 UNESCO 2014 派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "富岡市", lg_code: "10210", area_types: ["restaurant_traditional", "shopping_district"], lat: 36.2575, lon: 138.8939, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tomioka_silk_manju"], source: "manual" },
  { slug: "gunma-chan-meika", category: "food", sub_type: "gunma_meika", title_zh: "ぐんまちゃん饅頭+県マスコット銘菓(全県・2008 県マスコットぐんまちゃん 17 年・全国ゆるキャラグランプリ 2014 1 位・かわいい馬モチーフ饅頭+お菓子+クッキー・JR 駅売店+全国百貨店流通+ ¥350-1,500)", title_ja: "ぐんまちゃん饅頭", romaji: "Gunma-chan Manjū", summary_zh: "**ぐんまちゃん饅頭+県マスコット銘菓は 2008 県マスコット 17 年・全国ゆるキャラ 2014 1 位**(全県・**馬モチーフ饅頭+お菓子+クッキー**)。JR 駅+百貨店、¥350-1,500。", content_md: "- 全域:**群馬県全域**\n- 起源:**2008 県マスコット 17 年**\n- 認定:**全国ゆるキャラグランプリ 2014 1 位**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["shopping_district"], lat: 36.3895, lon: 139.0635, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["gunma_chan_meika", "2008", "2014_yuru1"], source: "manual" },

  // 酒 (3)
  { slug: "ryujin-shuzo-1665", category: "food", sub_type: "gunma_sake", title_zh: "龍神酒造(館林市・寛文 5 年 1665 創業 360 年+ 群馬最古酒蔵候補・「尾瀬の雪どけ」純米吟醸+大吟醸+ 全国新酒鑑評会金賞常連+ R1 育 つつじが岡公園 観光連動+ 720ml ¥2,500-7,500+ 海外輸出代表)", title_ja: "龍神酒造", romaji: "Ryūjin Shuzō", summary_zh: "**龍神酒造は寛文 5 年 1665 創業 360 年・群馬最古酒蔵候補**(館林・**全国新酒鑑評会金賞常連**)。「尾瀬の雪どけ」純米+大吟醸、R1 育 つつじが岡、¥2,500-7,500、海外輸出代表。", content_md: "- 立地:**館林市**\n- 起源:**寛文 5 年 1665 創業 360 年**\n- 認定:**群馬最古酒蔵候補 + 全国新酒鑑評会金賞常連**\n- 看板:**「尾瀬の雪どけ」純米吟醸 + 大吟醸**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "館林市", lg_code: "10207", area_types: ["industrial_heritage"], lat: 36.2453, lon: 139.5419, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ryujin", "1665", "360_years", "gunma_oldest"], source: "manual" },
  { slug: "nagai-shuzo-1886", category: "food", sub_type: "gunma_sake", title_zh: "永井酒造(利根郡川場村・1886 創業 139 年+ 「水芭蕉」純米吟醸+大吟醸+「MIZUBASHO PURE」スパークリング日本酒・国際品評会受賞多数・国際 SNS 海外輸出代表+ 720ml ¥3,500-12,000)", title_ja: "永井酒造 水芭蕉", romaji: "Nagai Mizubashō", summary_zh: "**永井酒造は 1886 創業 139 年・「水芭蕉」純米吟醸+大吟醸+「MIZUBASHO PURE」スパークリング**(川場村・**国際品評会受賞多数・国際 SNS 海外輸出代表**)。¥3,500-12,000/720ml。", content_md: "- 立地:**利根郡川場村**\n- 起源:**1886 創業 139 年**\n- 看板:**「水芭蕉」+「MIZUBASHO PURE」スパークリング日本酒**\n- 認定:**国際品評会受賞多数 + 海外輸出代表**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "川場村", lg_code: "10448", area_types: ["industrial_heritage"], lat: 36.6644, lon: 139.0719, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["nagai_mizubasho", "1886", "139_years", "sparkling"], source: "manual" },
  { slug: "tsuchida-shuzo-1907", category: "food", sub_type: "gunma_sake", title_zh: "土田酒造(利根郡川場村・1907 創業 118 年+ 「誉国光」純米山廃仕込・国産米 100% ナチュラル・国際 SOMM 推薦+ 全国新酒鑑評会金賞・720ml ¥3,500-7,500+ R1 食 永井酒造 1886 と並ぶ川場酒蔵 2 大代表)", title_ja: "土田酒造", romaji: "Tsuchida Shuzō", summary_zh: "**土田酒造は 1907 創業 118 年・「誉国光」純米山廃仕込・国産米 100% ナチュラル**(川場・**国際 SOMM 推薦+全国新酒鑑評会金賞**)。¥3,500-7,500、R1 食 永井 1886 と並ぶ川場酒蔵 2 大。", content_md: "- 立地:**利根郡川場村**\n- 起源:**1907 創業 118 年**\n- 看板:**「誉国光」純米山廃仕込・国産米 100% ナチュラル**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "川場村", lg_code: "10448", area_types: ["industrial_heritage"], lat: 36.6644, lon: 139.0719, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsuchida", "1907", "118_years", "yamahai"], source: "manual" },

  // 米肉野菜 (3)
  { slug: "tsumagoi-cabbage-no1", category: "food", sub_type: "gunma_kyodo", title_zh: "嬬恋キャベツ(吾妻郡嬬恋村・全国夏秋キャベツ生産量 No.1 産地・35% シェア+ 標高 800-1400m 高原栽培・1955 年代以降産地化+ 7-10 月旬+ 道の駅+全国百貨店流通+ 1 玉 ¥250-450+ R1 住 万座温泉観光連動)", title_ja: "嬬恋キャベツ", romaji: "Tsumagoi Cabbage", summary_zh: "**嬬恋キャベツは全国夏秋キャベツ生産量 No.1 産地・35% シェア**(嬬恋・**標高 800-1400m+1955 年代以降産地化**)。7-10 月、¥250-450/玉、R1 住 万座温泉連動。", content_md: "- 立地:**吾妻郡嬬恋村**\n- 認定:**全国夏秋キャベツ生産量 No.1 産地・35% シェア**\n- 規模:**標高 800-1400m 高原栽培**\n- 期:**7-10 月旬**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "嬬恋村", lg_code: "10425", area_types: ["farm_field"], lat: 36.5208, lon: 138.5097, season_start: "2026-07-01", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsumagoi_cabbage", "no1_japan", "35_percent"], source: "manual" },
  { slug: "gunma-koshihikari", category: "food", sub_type: "gunma_kyodo", title_zh: "群馬コシヒカリ+ゆめまつり(全県・全国コシヒカリ生産量上位県+ 1956 開発+ 県オリジナル「ゆめまつり」県開発品種・全国食味ランキング A+ 1kg ¥1,200-2,500+ JR 駅+全国百貨店流通)", title_ja: "群馬コシヒカリ", romaji: "Gunma Koshihikari", summary_zh: "**群馬コシヒカリ+ゆめまつりは全国上位県・1956 開発+県オリジナル「ゆめまつり」品種**(全県・**全国食味 A**)。¥1,200-2,500/kg、JR 駅+全国百貨店流通。", content_md: "- 全域:**群馬県全域**\n- 認定:**全国コシヒカリ生産量上位県 + 県オリジナル「ゆめまつり」品種**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["farm_field"], lat: 36.3895, lon: 139.0635, season_start: "2026-09-15", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["gunma_koshihikari", "yumematsuri"], source: "manual" },
  { slug: "takasaki-ham-1900", category: "food", sub_type: "gunma_meat", title_zh: "高崎ハム+群馬県畜産食品(高崎市+前橋・1900 年代開発・群馬畜産食品ブランド代表・ハム+ソーセージ+ベーコン+ 全国流通+ 高崎駅売店+全国百貨店ヒット+ 1 セット ¥1,500-5,500+ 観光客代表土産)", title_ja: "高崎ハム", romaji: "Takasaki Ham", summary_zh: "**高崎ハム+群馬県畜産食品は 1900 年代開発・群馬畜産食品ブランド代表**(高崎+前橋・**ハム+ソーセージ+ベーコン**)。全国流通、JR 高崎駅+百貨店、¥1,500-5,500、観光客代表土産。", content_md: "- 立地:**高崎市 + 前橋市**\n- 起源:**1900 年代開発**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["industrial_heritage"], lat: 36.3219, lon: 139.0033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["takasaki_ham"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[gunma-food-r1] 尚無條目"); return; }
  console.log(`[gunma-food-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[gunma-food-r1] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[gunma-food-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[gunma-food-r1] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
