// Seed 山形県 育 R1(21 筆 / Sprint 1.4)
// 山寺立石寺 3 / 出羽三山 3 / 米沢上杉 4 / 山形城+市内 3 / 庄内文化 3 / 美術館+科学 3 / 重要建築 2 = 21

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "tohoku"; prefecture_ja: "山形県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 山寺立石寺 (3)
  { slug: "yamadera-rikkyakuji-860", category: "culture", sub_type: "yamagata_yamadera", title_zh: "山寺(立石寺)(山形市・860 慈覚大師円仁開山 1165 年+ 国指定史跡 1932+ 重要文化財 本堂(根本中堂)+ 奥之院 1015 段石段+ 入山 ¥300+ R1 食 板そば+玉こんにゃく沿道+ 観光客必訪)", title_ja: "山寺(立石寺)", romaji: "Yamadera Rikkyakuji", summary_zh: "**山寺(立石寺)は 860 慈覚大師円仁開山 1165 年**(山形市・**国指定史跡 1932**)。重要文化財本堂+奥之院 1015 段、¥300、R1 食 板そば+玉こん沿道、観光必訪。", content_md: "- 立地:**山形市**(JR 仙山線 山寺駅徒歩 5 分)\n- 起源:**860 慈覚大師円仁開山 1165 年**\n- 認定:**国指定史跡 1932 + 重要文化財 本堂(根本中堂)**\n- 規模:**奥之院 1015 段石段**\n- 並列:**R1 食 板そば + 玉こんにゃく沿道**\n- 入山:**¥300**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "山形市", lg_code: "06201", area_types: ["shrine_temple", "scenic_spot"], lat: 38.3133, lon: 140.4400, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yamadera", "rikkyakuji", "860_ennin", "1165_years"], source: "manual" },
  { slug: "yamadera-okunoin-1015", category: "culture", sub_type: "yamagata_yamadera", title_zh: "山寺奥之院・五大堂展望(R1 育 山寺立石寺派生・1015 段石段最終+ 五大堂 1648 江戸期再建+ 山寺・面白山眺望+ 「山寺観光ハイライト」+ 入場 ¥300(R1 育 山寺込み)+ 健脚 1.5h 推奨)", title_ja: "山寺奥之院・五大堂", romaji: "Yamadera Okunoin / Godaidō", summary_zh: "**山寺奥之院・五大堂は R1 育 派生・1015 段最終**(山形・**五大堂 1648 江戸期再建+山寺面白山眺望**)。観光ハイライト、¥300 込み、健脚 1.5h。", content_md: "- 立地:**山形市山寺**(R1 育 立石寺奥)\n- 規模:**1015 段石段最終**\n- 起源:**五大堂 1648 江戸期再建**\n- 眺望:**山寺 + 面白山**\n- 健脚:**1.5h 推奨**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "山形市", lg_code: "06201", area_types: ["shrine_temple", "scenic_spot"], lat: 38.3133, lon: 140.4400, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yamadera_okunoin", "1015_steps", "1648_godaido"], source: "manual" },
  { slug: "yamadera-basho-haiku-monument", category: "culture", sub_type: "yamagata_yamadera", title_zh: "山寺芭蕉句碑「閑さや岩にしみ入る蝉の声」(R1 育 山寺立石寺・松尾芭蕉 1689 奥の細道訪問・代表名句発祥地+ 芭蕉記念碑+ 山寺風景代表+ 入場無料+ R1 育 山寺観光必訪歌碑)", title_ja: "山寺芭蕉句碑", romaji: "Yamadera Bashō Kuhi", summary_zh: "**山寺芭蕉句碑「閑さや岩にしみ入る蝉の声」は松尾芭蕉 1689 奥の細道代表名句**(R1 育 山寺立石寺・**芭蕉記念碑**)。山寺観光必訪歌碑、無料。", content_md: "- 立地:**山形市山寺**(R1 育 立石寺)\n- 起源:**松尾芭蕉 1689 奥の細道訪問**\n- 句:**「閑さや岩にしみ入る蝉の声」**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "山形市", lg_code: "06201", area_types: ["shrine_temple", "scenic_spot"], lat: 38.3133, lon: 140.4400, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["basho_kuhi", "1689", "okuno_hosomichi"], source: "manual" },

  // 出羽三山 (3)
  { slug: "haguroyama-5-tower", category: "culture", sub_type: "yamagata_dewasanzan", title_zh: "羽黒山五重塔(鶴岡市羽黒・1372 室町期創建+ 国宝 1966+ 杉並木参道 2,446 段石段沿道+ 出羽三山(羽黒+月山+湯殿)入口+ R1 食 出羽三山精進料理 R1 住 齋館宿坊拠点+ 入山無料 R1 楽 連動)", title_ja: "羽黒山五重塔", romaji: "Haguroyama 5 Tower", summary_zh: "**羽黒山五重塔は 1372 室町期創建・国宝 1966**(鶴岡・**杉並木参道 2,446 段沿道**)。出羽三山入口、R1 食 精進+R1 住 齋館宿坊拠点、無料。", content_md: "- 立地:**鶴岡市羽黒**\n- 起源:**1372 室町期創建**\n- 認定:**国宝 1966**\n- 構成:**杉並木参道 2,446 段石段沿道**\n- 並列:**出羽三山(羽黒山 + 月山 + 湯殿山)入口**\n- 並列観光:**R1 食 出羽三山精進料理 + R1 住 羽黒山齋館宿坊**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "鶴岡市", lg_code: "06203", area_types: ["shrine_temple", "scenic_spot"], lat: 38.6989, lon: 139.9744, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["haguro_5_tower", "1372_muromachi", "1966_kokuhou"], source: "manual" },
  { slug: "gassan-jinja-1984m", category: "culture", sub_type: "yamagata_dewasanzan", title_zh: "月山神社(西村山郡西川町月山山頂・標高 1984m+ 出羽三山中央・1400 年伝承+ 県史跡+ 7-10 月開山+ R1 楽 月山スキー(夏)拠点+ 入山 ¥500+ R1 食 月山ワイン 関連)", title_ja: "月山神社", romaji: "Gassan Jinja", summary_zh: "**月山神社は出羽三山中央・標高 1984m 山頂**(西川町・**1400 年伝承**)。県史跡、7-10 月開山、R1 楽 月山スキー(夏)拠点、入山 ¥500。", content_md: "- 立地:**西村山郡西川町月山山頂・標高 1984m**\n- 起源:**1400 年伝承**\n- 認定:**県史跡 + 出羽三山中央**\n- 期:**7-10 月開山**\n- 並列観光:**R1 楽 月山スキー(夏スキー全国唯一)**\n- 入山:**¥500**", region: "tohoku", prefecture_ja: "山形県", gun_ja: "西村山郡", municipality_ja: "西川町", lg_code: "06322", area_types: ["shrine_temple", "mountain_village"], lat: 38.5489, lon: 140.0294, season_start: "2026-07-01", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["gassan_jinja", "1984m", "1400_years"], source: "manual" },
  { slug: "yudonoyama-jinja-shugendo", category: "culture", sub_type: "yamagata_dewasanzan", title_zh: "湯殿山神社本宮(鶴岡市湯殿山・出羽三山修験秘所中心+ 1400 年伝承+ 「語るなかれ・聞くなかれ」秘儀本宮+ 大日如来本地+ R1 住 遠賢寺宿坊拠点+ 入山 ¥500+ 5-11 月開山)", title_ja: "湯殿山神社本宮", romaji: "Yudonoyama Jinja", summary_zh: "**湯殿山神社本宮は出羽三山修験秘所中心**(鶴岡市・**1400 年伝承+「語るなかれ・聞くなかれ」秘儀本宮**)。大日如来本地、R1 住 遠賢寺拠点、¥500、5-11 月。", content_md: "- 立地:**鶴岡市湯殿山**\n- 起源:**1400 年伝承**\n- 認定:**出羽三山修験秘所中心 + 大日如来本地**\n- 看板:**「語るなかれ・聞くなかれ」秘儀本宮**\n- 並列:**R1 住 遠賢寺宿坊**\n- 期:**5-11 月開山**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "鶴岡市", lg_code: "06203", area_types: ["shrine_temple", "mountain_village"], lat: 38.5664, lon: 139.9783, season_start: "2026-05-01", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yudonoyama", "1400_years", "shugendo"], source: "manual" },

  // 米沢上杉 (4)
  { slug: "uesugi-jinja-1876", category: "culture", sub_type: "yamagata_yonezawa_uesugi", title_zh: "上杉神社(米沢市・1876 上杉謙信(1530-1578)祀+ 米沢城跡内+ 県社+ 別格官幣社+ R1 衣 米沢織+R1 食 米沢牛発祥地+ 入場無料+ 米沢雪灯篭まつり R1 楽 メイン会場)", title_ja: "上杉神社", romaji: "Uesugi Jinja", summary_zh: "**上杉神社は 1876 上杉謙信祀・米沢城跡内**(米沢市・**県社+別格官幣社**)。R1 衣 米沢織+R1 食 米沢牛発祥地、入場無料、R1 楽 雪灯篭メイン。", content_md: "- 立地:**米沢市**(米沢城跡内)\n- 起源:**1876 上杉謙信(1530-1578)祀**\n- 認定:**県社・別格官幣社**\n- 並列観光:**R1 衣 米沢織 + R1 食 米沢牛発祥地 + R1 楽 米沢雪灯篭まつり**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "米沢市", lg_code: "06202", area_types: ["shrine_temple", "history_site_castle"], lat: 37.9219, lon: 140.1175, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["uesugi_jinja", "1876", "uesugi_kenshin"], source: "manual" },
  { slug: "yonezawa-castle-ato", category: "culture", sub_type: "yamagata_yonezawa_uesugi", title_zh: "米沢城跡(米沢市・1238 鎌倉期築城+ 上杉景勝 1601 入封・米沢藩 270 年中心+ 1872 廃城+ 国指定史跡 1991+ R1 育 上杉神社+R1 育 米沢市上杉博物館 隣接+ 入場無料・松ヶ岬公園化)", title_ja: "米沢城跡", romaji: "Yonezawa Jōato", summary_zh: "**米沢城跡は 1238 鎌倉期築城・上杉景勝 1601 入封**(米沢市・**米沢藩 270 年中心**)。国指定史跡 1991+R1 育 上杉神社+博物館隣接、入場無料・松ヶ岬公園化。", content_md: "- 立地:**米沢市**\n- 起源:**1238 鎌倉期築城 + 上杉景勝 1601 入封**\n- 期:**1238 築城 → 1872 廃城**\n- 認定:**国指定史跡 1991**\n- 並列観光:**R1 育 上杉神社 + 米沢市上杉博物館**\n- 入場:**無料(松ヶ岬公園化)**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "米沢市", lg_code: "06202", area_types: ["history_site_castle"], lat: 37.9219, lon: 140.1175, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yonezawa_jo", "1238_kamakura", "1991_shiseki"], source: "manual" },
  { slug: "yonezawa-uesugi-museum-2001", category: "culture", sub_type: "yamagata_yonezawa_uesugi", title_zh: "米沢市上杉博物館(米沢市・2001 開館+ 国宝「上杉本洛中洛外図屏風」(狩野永徳)+ R1 育 米沢城跡内・伝国の杜+ 上杉謙信+景勝+鷹山 270 年資料+ 入館 ¥620+ R1 衣 米沢織+R1 食 米沢牛展示)", title_ja: "米沢市上杉博物館", romaji: "Yonezawa Uesugi Hakubutsukan", summary_zh: "**米沢市上杉博物館は 2001 開館**(米沢市・**国宝「上杉本洛中洛外図屏風」狩野永徳**)。R1 育 城跡内・伝国の杜、上杉 270 年資料、入館 ¥620。", content_md: "- 立地:**米沢市**(R1 育 米沢城跡内・伝国の杜)\n- 起源:**2001 開館**\n- 看板:**国宝「上杉本洛中洛外図屏風」(狩野永徳)**\n- 内容:**上杉謙信 + 景勝 + 鷹山 270 年資料**\n- 入館:**¥620**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "米沢市", lg_code: "06202", area_types: ["museum_art", "history_site_castle"], lat: 37.9219, lon: 140.1175, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["uesugi_museum", "2001", "kano_eitoku"], source: "manual" },
  { slug: "kojokan-1697-yonezawa", category: "culture", sub_type: "yamagata_yonezawa_uesugi", title_zh: "興譲館(米沢市・1697 米沢藩校設立 328 年+ 上杉鷹山 R1 食 米沢牛 振興時期 学問奨励+ 県史跡+ 「人民共有」名言由来+ 米沢藩 270 年学問中心+ 入場無料・米沢城跡内)", title_ja: "興譲館", romaji: "Kōjōkan", summary_zh: "**興譲館は 1697 米沢藩校設立 328 年**(米沢市・**上杉鷹山学問奨励**)。「人民共有」名言由来、米沢藩 270 年学問中心、県史跡、無料。", content_md: "- 立地:**米沢市**(R1 育 米沢城跡内)\n- 起源:**1697 米沢藩校設立 328 年**\n- 縁:**上杉鷹山学問奨励**\n- 看板:**「人民共有」名言由来**\n- 認定:**県史跡**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "米沢市", lg_code: "06202", area_types: ["history_site_castle"], lat: 37.9219, lon: 140.1175, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kojokan", "1697", "uesugi_youzan"], source: "manual" },

  // 山形城+市内 (3)
  { slug: "yamagata-castle-1357", category: "culture", sub_type: "yamagata_history_museum", title_zh: "山形城跡(霞城公園)(山形市・1357 南北朝期 斯波兼頼築城+ 最上義光 1574-1614 全盛+ 1872 廃城+ 国指定史跡 1986+ R1 衣 七日町商店街中心 城下町+ 桜名所 4 月+ 入場無料)", title_ja: "山形城跡(霞城公園)", romaji: "Yamagata-jō / Kajō Kōen", summary_zh: "**山形城跡は 1357 南北朝期 斯波兼頼築城**(山形市・**最上義光 1574-1614 全盛+1872 廃城**)。国指定史跡 1986、R1 衣 七日町中心、桜名所、無料。", content_md: "- 立地:**山形市霞城公園**\n- 起源:**1357 南北朝期 斯波兼頼築城**\n- 期:**1357 築城 + 最上義光 1574-1614 全盛 → 1872 廃城**\n- 認定:**国指定史跡 1986**\n- 期:**桜名所 4 月**\n- 並列:**R1 衣 七日町商店街中心 城下町**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "山形市", lg_code: "06201", area_types: ["history_site_castle", "scenic_spot"], lat: 38.2522, lon: 140.3433, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yamagata_jo", "1357", "mogami_yoshiaki"], source: "manual" },
  { slug: "mogami-yoshiaki-museum", category: "culture", sub_type: "yamagata_history_museum", title_zh: "最上義光歴史館(山形市・1989 開館+ R1 育 山形城跡 隣接+ 最上義光(1546-1614)山形藩主 全盛期資料+ 国宝「上杉本洛中洛外図屏風」(米沢博 R1 育 所蔵)関連展示+ 入館 ¥220)", title_ja: "最上義光歴史館", romaji: "Mogami Yoshiaki Rekishikan", summary_zh: "**最上義光歴史館は 1989 開館**(山形市・**R1 育 山形城跡隣接**)。最上義光(1546-1614)山形藩主全盛期資料、入館 ¥220。", content_md: "- 立地:**山形市**(R1 育 山形城跡霞城公園内)\n- 起源:**1989 開館 36 年**\n- 縁:**最上義光 1546-1614 山形藩主全盛期**\n- 入館:**¥220**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "山形市", lg_code: "06201", area_types: ["museum_art", "history_site_castle"], lat: 38.2522, lon: 140.3433, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["mogami_yoshiaki", "1989", "1546_1614"], source: "manual" },
  { slug: "bunshōkan-yamagata", category: "culture", sub_type: "yamagata_modern_art", title_zh: "文翔館(旧山形県会議事堂・山形市・1916 完成 109 年+ 国重要文化財 1984+ ルネサンス様式英国風建築+ 県政資料館機能+ 入場無料+ R1 衣 七日町商店街隣接)", title_ja: "文翔館", romaji: "Bunshōkan", summary_zh: "**文翔館は 1916 完成 109 年・国重要文化財 1984**(山形市・**ルネサンス様式英国風建築**)。県政資料館、無料、R1 衣 七日町隣接。", content_md: "- 立地:**山形市**\n- 起源:**1916 完成 109 年**\n- 認定:**国重要文化財 1984 + ルネサンス様式英国風建築**\n- 並列観光:**R1 衣 七日町商店街隣接**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "山形市", lg_code: "06201", area_types: ["museum_art"], lat: 38.2503, lon: 140.3422, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["bunshokan", "1916", "1984_juyou"], source: "manual" },

  // 庄内文化 (3)
  { slug: "chido-museum-tsuruoka", category: "culture", sub_type: "yamagata_history_museum", title_zh: "致道博物館(鶴岡市・1950 開館+ 庄内藩 270 年資料+ 旧鶴岡警察署庁舎 1884(国重要文化財)+ 旧西田川郡役所 1881+ 民俗資料館 重文 群+ 入館 ¥800+ R1 衣 鶴岡シルク+R1 食 だだちゃ豆 観光客向け)", title_ja: "致道博物館", romaji: "Chidō Hakubutsukan", summary_zh: "**致道博物館は 1950 開館**(鶴岡市・**庄内藩 270 年資料**)。旧鶴岡警察署 1884+旧西田川郡役所 1881 重文、入館 ¥800、R1 衣 シルク+R1 食 だだちゃ豆観光。", content_md: "- 立地:**鶴岡市**\n- 起源:**1950 開館 75 年**\n- 内容:**庄内藩 270 年資料**\n- 認定:**旧鶴岡警察署 1884 + 旧西田川郡役所 1881 国重要文化財群**\n- 入館:**¥800**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "鶴岡市", lg_code: "06203", area_types: ["museum_art", "history_site_castle"], lat: 38.7269, lon: 139.8267, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["chido_hakubutsukan", "1950", "shonai_270"], source: "manual" },
  { slug: "chido-kan-bukeyashiki-1805", category: "culture", sub_type: "yamagata_history_museum", title_zh: "致道館(鶴岡市・1805 庄内藩学校設立 220 年+ 国指定史跡 1972+ 江戸期藩校建造物現存最古の一+ 「学制」由来東北最古藩校の一+ R1 育 致道博物館 隣接+ 入場無料+ 庄内学問中心)", title_ja: "致道館", romaji: "Chidōkan", summary_zh: "**致道館は 1805 庄内藩学校 220 年・国指定史跡 1972**(鶴岡市・**江戸期藩校建造物現存最古の一**)。R1 育 致道博物館隣接、無料、庄内学問中心。", content_md: "- 立地:**鶴岡市**\n- 起源:**1805 庄内藩学校設立 220 年**\n- 認定:**国指定史跡 1972 + 江戸期藩校建造物現存最古の一**\n- 並列観光:**R1 育 致道博物館 隣接**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "鶴岡市", lg_code: "06203", area_types: ["history_site_castle"], lat: 38.7269, lon: 139.8267, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["chidokan", "1805", "1972_shiseki"], source: "manual" },
  { slug: "sankyo-warehouse-sakata", category: "culture", sub_type: "yamagata_history_museum", title_zh: "山居倉庫(酒田市・1893 庄内米保管倉庫建設 132 年+ 国指定史跡 2018+ 9 棟 + ケヤキ並木背景・全国知名度高+ R1 食 庄内米(つや姫+はえぬき)発祥関連+ 入場無料・酒田夢の倶楽 ¥800)", title_ja: "山居倉庫", romaji: "Sankyo Sōko", summary_zh: "**山居倉庫は 1893 庄内米保管倉庫 132 年・国指定史跡 2018**(酒田市・**9 棟+ケヤキ並木**)。R1 食 庄内米(つや姫+はえぬき)発祥関連、無料・夢倶楽 ¥800。", content_md: "- 立地:**酒田市**\n- 起源:**1893 庄内米保管倉庫建設 132 年**\n- 認定:**国指定史跡 2018**\n- 規模:**9 棟 + ケヤキ並木背景**\n- 関連:**R1 食 庄内米(つや姫 + はえぬき)発祥**\n- 入場:**無料(酒田夢の倶楽 ¥800)**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "酒田市", lg_code: "06204", area_types: ["history_site_castle", "scenic_spot"], lat: 38.9144, lon: 139.8369, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["sankyo_soko", "1893", "2018_shiseki", "9_warehouses"], source: "manual" },

  // 美術館+科学 (3)
  { slug: "yamagata-prefectural-museum-art", category: "culture", sub_type: "yamagata_modern_art", title_zh: "山形美術館(山形市・1964 開館+ 平山郁夫作品 多数+ 江戸絵画+近代日本画+西洋絵画+ 県美術館代表+ R1 衣 七日町商店街隣接+ 入館 ¥800)", title_ja: "山形美術館", romaji: "Yamagata Bijutsukan", summary_zh: "**山形美術館は 1964 開館**(山形市・**平山郁夫作品多数+江戸絵画+近代日本画+西洋絵画**)。県美術館代表、R1 衣 七日町隣接、入館 ¥800。", content_md: "- 立地:**山形市**\n- 起源:**1964 開館 61 年**\n- 蔵品:**平山郁夫 + 江戸絵画 + 近代日本画 + 西洋絵画**\n- 入館:**¥800**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "山形市", lg_code: "06201", area_types: ["museum_art"], lat: 38.2503, lon: 140.3422, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["yamagata_bijutsukan", "1964"], source: "manual" },
  { slug: "honma-museum-of-art-sakata-1947", category: "culture", sub_type: "yamagata_modern_art", title_zh: "本間美術館(酒田市・1947 開館・庄内最古美術館+ 本間家(酒田大商人)寄贈 茶器+書画+陶磁器多数+ 国登録有形文化財 庭園 + 茶室「清遠閣」+ 入館 ¥1,000+ R1 育 山居倉庫観光と組合せ)", title_ja: "本間美術館", romaji: "Honma Bijutsukan", summary_zh: "**本間美術館は 1947 開館・庄内最古美術館**(酒田市・**本間家(酒田大商人)寄贈**)。茶器+書画+陶磁器、国登録庭園+清遠閣茶室、¥1,000、R1 育 山居倉庫組合せ。", content_md: "- 立地:**酒田市**\n- 起源:**1947 開館 78 年**\n- 認定:**庄内最古美術館 + 国登録有形文化財 庭園・茶室「清遠閣」**\n- 蔵品:**本間家寄贈 茶器 + 書画 + 陶磁器**\n- 入館:**¥1,000**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "酒田市", lg_code: "06204", area_types: ["museum_art"], lat: 38.9144, lon: 139.8369, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["honma_bijutsukan", "1947", "shonai_oldest"], source: "manual" },
  { slug: "yamagata-prefectural-museum", category: "culture", sub_type: "yamagata_history_museum", title_zh: "山形県立博物館(山形市・1971 開館+ 山形県内 縄文+古代+中世+近世+近代 通史+ 縄文遺跡出土品 + 米沢上杉藩+山形最上藩+庄内酒井藩 関連 多数+ 入館 ¥300+ R1 育 山形城跡霞城公園内)", title_ja: "山形県立博物館", romaji: "Yamagata Kenritsu Hakubutsukan", summary_zh: "**山形県立博物館は 1971 開館**(山形市・**縄文+古代+中世+近世+近代通史**)。米沢+山形+庄内 3 藩関連、入館 ¥300、R1 育 山形城跡霞城公園内。", content_md: "- 立地:**山形市**(R1 育 山形城跡霞城公園内)\n- 起源:**1971 開館 54 年**\n- 内容:**縄文 + 古代 + 中世 + 近世 + 近代 通史**\n- 入館:**¥300**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "山形市", lg_code: "06201", area_types: ["museum_art", "history_site_castle"], lat: 38.2522, lon: 140.3433, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["yamagata_pref_museum", "1971"], source: "manual" },

  // 重要建築 (2)
  { slug: "jion-ji-sagae", category: "culture", sub_type: "yamagata_shrine_temple", title_zh: "慈恩寺(寒河江市・746 奈良期創建 1279 年+ 国重要文化財 群(本堂+三重塔+仏像 多数)+ 国指定史跡 2014+ 江戸期 山形最上藩 寺社中心+ 入場 ¥700+ R1 食 さくらんぼ寒河江観光と組合せ)", title_ja: "慈恩寺", romaji: "Jion-ji", summary_zh: "**慈恩寺は 746 奈良期創建 1279 年**(寒河江市・**国重要文化財群+国指定史跡 2014**)。江戸期 山形最上藩寺社中心、¥700、R1 食 さくらんぼ寒河江観光組合せ。", content_md: "- 立地:**寒河江市**\n- 起源:**746 奈良期創建 1279 年**\n- 認定:**国重要文化財 群 + 国指定史跡 2014**\n- 構成:**本堂 + 三重塔 + 仏像 多数**\n- 入場:**¥700**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "寒河江市", lg_code: "06206", area_types: ["shrine_temple", "history_site_castle"], lat: 38.3878, lon: 140.2767, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["jionji", "746_nara", "1279_years", "2014_shiseki"], source: "manual" },
  { slug: "tsuruoka-park-shoji", category: "culture", sub_type: "yamagata_history_museum", title_zh: "鶴岡公園+鶴岡城跡(鶴岡市・庄内藩 1622 酒井家 270 年中心地・1872 廃城+ 桜名所 4 月+ R1 育 致道博物館+致道館隣接+ 入場無料+ 県史跡+ 鶴ヶ岡城ランドマーク復元計画)", title_ja: "鶴岡公園+鶴岡城跡", romaji: "Tsuruoka Park / Tsuruoka-jō Ato", summary_zh: "**鶴岡公園+城跡は庄内藩 1622 酒井家 270 年中心地・1872 廃城**(鶴岡市)。桜名所 4 月、R1 育 致道博物館+致道館隣接、無料、県史跡。", content_md: "- 立地:**鶴岡市**\n- 起源:**庄内藩 1622 酒井家 270 年中心地・1872 廃城**\n- 認定:**県史跡**\n- 期:**桜名所 4 月**\n- 並列観光:**R1 育 致道博物館 + 致道館 隣接**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "山形県", gun_ja: null, municipality_ja: "鶴岡市", lg_code: "06203", area_types: ["history_site_castle", "scenic_spot"], lat: 38.7269, lon: 139.8267, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsuruoka_park", "1622_shonai_sakai"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[yamagata-culture-r1] 尚無條目"); return; }
  console.log(`[yamagata-culture-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[yamagata-culture-r1] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[yamagata-culture-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[yamagata-culture-r1] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
