// Seed 奈良県 · 住類 條目 → public.japan_entries(Sprint 15.3)
//
// 奈良の宿泊文化:
//   - 奈良ホテル(1909・辰野金吾設計・関西の迎賓館)
//   - ならまち町家泊(京都町家とは別系統・古都圏古民家文化)
//   - 寺宿(東大寺・吉野金峯山寺・室生寺・長谷寺等)
//   - 吉野山参詣宿(桜・修験道 1300 年・千本桜 view)
//   - 大和高原・宇陀温泉・十津川温泉(秘湯・最大村)
//   - 明日香村古墳観光宿
//
// Round 1 構成 ~40 筆:
//   Phase 1 — 奈良ホテル + classical ~4
//   Phase 2 — 奈良市内現代ホテル ~5
//   Phase 3 — ならまち町家泊 ~5
//   Phase 4 — 寺宿(宿坊)~5
//   Phase 5 — 吉野山参詣宿 ~6
//   Phase 6 — 明日香村泊 ~3
//   Phase 7 — 十津川温泉 ~3
//   Phase 8 — 大和高原・宇陀 ~3
//   Phase 9 — 季節 + area guide ~4
//
// Usage:
//   npm run seed:japan-nara-lodging:dry
//   npm run seed:japan-nara-lodging

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "nara_hotel_classical"
  | "nara_machiya"
  | "yoshino_sankei_yado"
  | "luxury_hotel"
  | "budget_hotel_chain"
  | "onsen_ryokan"
  | "rural_minshuku"
  | "shukubo_temple"
  | "lodging_area_guide"
  | "seasonal_lodging"
  | "glamping_camp"
  | "capsule_hostel";

interface SeedRow {
  slug: string;
  category: "lodging";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "kansai";
  prefecture_ja: "奈良県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // Phase 1 — 奈良ホテル 1909 + classical
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nara-hotel-honkan",
    category: "lodging",
    sub_type: "nara_hotel_classical",
    title_zh: "奈良ホテル 本館(1909・辰野金吾・關西迎賓館)",
    title_ja: "奈良ホテル 本館",
    romaji: "Nara Hotel Honkan",
    summary_zh: "**1909 年開業の奈良ホテル本館は関西の迎賓館**。辰野金吾(東京駅と同設計者)+ 片岡安の和洋折衷建築、和瓦屋根 + 西洋木造、明治期最高級ホテルの形を保つ。皇族・国賓・チャールズ・チャップリン・アインシュタイン等の歴史宿泊。本館のみで 49 室、価格 ¥30,000-100,000。",
    content_md: "- 開業:1909(明治 42 年)\n- 設計:辰野金吾(東京駅と同設計者)+ 片岡安\n- 場所:奈良市高畑町・奈良公園に隣接\n- 建築:和洋折衷(和瓦屋根 + 西洋木造)\n- 客室:本館 49 室(他に新館あり)\n- 価格:¥30,000-100,000(部屋・季節による)\n- 歴史宿泊:皇族・チャップリン・アインシュタイン・ヘップバーン\n- 公共空間:メインダイニング三笠・ザ・バー(別 entry)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.679,
    lon: 135.836,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.narahotel.co.jp/" },
    tags: ["nara_hotel_classical", "nara_hotel", "1909", "tatsuno_kingo", "founder_brand"],
    source: "manual",
  },
  {
    slug: "nara-hotel-shinkan",
    category: "lodging",
    sub_type: "nara_hotel_classical",
    title_zh: "奈良ホテル 新館(1984・本館の現代版)",
    title_ja: "奈良ホテル 新館",
    romaji: "Nara Hotel Shinkan",
    summary_zh: "**1984 年に本館の隣に建てられた現代型客室棟**。本館の趣を踏襲しつつ設備は現代的、43 室。本館より少しリーズナブル(¥25,000-80,000)、本館の食堂・バーは共通利用可。歴史と現代の両立が魅力。",
    content_md: "- 開業:1984(本館 75 周年に増築)\n- 場所:奈良ホテル本館隣接\n- 客室:43 室\n- 価格:¥25,000-80,000\n- 設備:現代型バスルーム・wifi 完備\n- 共通利用:メインダイニング三笠・ザ・バー・大浴場\n- 用途:本館より予約しやすい・ファミリー向け",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.679,
    lon: 135.836,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://www.narahotel.co.jp/" },
    tags: ["nara_hotel_classical", "nara_hotel", "shinkan", "1984"],
    source: "manual",
  },
  {
    slug: "nara-hotel-history-guide",
    category: "lodging",
    sub_type: "nara_hotel_classical",
    title_zh: "奈良ホテル 歷史ガイド(關西迎賓館の 100 年)",
    title_ja: "奈良ホテル 歴史ガイド",
    romaji: "Nara Hotel History Guide",
    summary_zh: "**奈良ホテルは 1909-2026 年の 117 年で関西を代表する迎賓館として機能**。皇族・国賓宿泊地、文学者・科学者・俳優の名前が記名簿に残る。建築見学は宿泊客以外も可(ロビー + 廊下)、明治期 hospitality 文化の生きた博物館。",
    content_md: "- 開業:1909(明治 42 年)— 関西鉄道(現 JR)の系列\n- 役割:関西の迎賓館・国賓 hospitality\n- 著名宿泊客:昭和天皇・愛新覚羅溥儀・チャップリン・アインシュタイン・ヘップバーン・ダライ・ラマ\n- 建築見学:ロビー + 廊下は宿泊客以外も自由(コーヒー利用が礼儀)\n- 文化価値:現存最古級洋式リゾートホテル建築",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.679,
    lon: 135.836,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.narahotel.co.jp/" },
    tags: ["nara_hotel_classical", "history_guide", "kansai_geihinkan", "guide"],
    source: "manual",
  },
  {
    slug: "nara-saraswaty-classical",
    category: "lodging",
    sub_type: "nara_hotel_classical",
    title_zh: "奈良の歷史的洋館宿ガイド(奈良ホテル以外)",
    title_ja: "奈良 歴史洋館宿ガイド",
    romaji: "Nara Classical Western Hotel Guide",
    summary_zh: "**奈良ホテル以外の歴史的洋館・古典宿ガイド**。明治-大正期の建築を改装したブティックホテル、戦前洋館を活かした旅館等。奈良ホテルの規模はないが個性ある体験。",
    content_md: "- 主な対象:明治-大正期建築の宿\n- 特徴:洋館 + 和食 + 庭園\n- 価格:¥20,000-50,000\n- 部屋数:数室の小規模(プライベート感)\n- 観光線:奈良ホテルと比較して泊まる\n- 注:specific 老舗洋館は予約困難・要事前確認",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.805,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nara_hotel_classical", "western_classical", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 2 — 奈良市内現代ホテル
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "ana-crowne-plaza-nara",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ANA クラウンプラザホテル奈良(JR 奈良駅近)",
    title_ja: "ANA クラウンプラザホテル奈良",
    romaji: "ANA Crowne Plaza Nara",
    summary_zh: "**JR 奈良駅西口直結の中規模上級ホテル**。客室 320+、奈良観光のアクセス便利、京都・大阪へも 1 時間。¥15,000-40,000、家族・ビジネス・観光客の幅広い層対応。",
    content_md: "- 場所:JR 奈良駅西口・徒歩 1 分\n- 客室:約 320 室\n- 価格:¥15,000-40,000\n- 設備:大浴場・レストラン・宴会場\n- アクセス:JR 奈良駅・近鉄奈良駅まで徒歩 12 分\n- 観光線:京都(45 分)・大阪(50 分)直結",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.681,
    lon: 135.823,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["luxury_hotel", "ana_crowne_plaza", "jr_nara", "modern"],
    source: "manual",
  },
  {
    slug: "hotel-nikko-nara",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ホテル日航奈良(JR 奈良駅東口・国際ブランド)",
    title_ja: "ホテル日航奈良",
    romaji: "Hotel Nikko Nara",
    summary_zh: "**JR 奈良駅東口直結の日航ブランドホテル**。客室 330+、外国人観光客に人気、英語スタッフ常駐。¥18,000-45,000、JAL マイル提携可能。",
    content_md: "- 場所:JR 奈良駅東口・徒歩 1 分\n- 客室:約 330 室\n- 価格:¥18,000-45,000\n- ブランド:日航(JAL 系)\n- 多言語対応:英・中・韓常駐\n- アクセス:近鉄奈良駅徒歩 13 分・京都へ JR 45 分",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.681,
    lon: 135.824,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: [],
    external_urls: { official: "https://www.nikkonara.jp/" },
    tags: ["luxury_hotel", "nikko_nara", "jr_nara", "international"],
    source: "manual",
  },
  {
    slug: "courtyard-marriott-nara",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "コートヤード・バイ・マリオット奈良(2017 開業・近鉄沿線)",
    title_ja: "コートヤード・バイ・マリオット奈良",
    romaji: "Courtyard by Marriott Nara",
    summary_zh: "**2017 年開業のマリオット系ミッドスケールホテル**。客室 187 室、近鉄奈良駅徒歩 5 分、Bonvoy ポイント利用可。¥12,000-30,000、米系ブランド + 東洋的設備の融合。",
    content_md: "- 開業:2017\n- 場所:奈良市三条町・近鉄奈良駅徒歩 5 分\n- 客室:約 187 室\n- 価格:¥12,000-30,000\n- ブランド:Marriott(Bonvoy)\n- 設備:大浴場・レストラン・gym\n- 特色:Marriott Bonvoy ポイント利用可",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.681,
    lon: 135.825,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: [],
    external_urls: { official: "https://www.marriott.com/" },
    tags: ["luxury_hotel", "courtyard_marriott", "2017", "kintetsu_nara"],
    source: "manual",
  },
  {
    slug: "super-hotel-jr-nara",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "スーパーホテル JR 奈良駅(リーズナブル代表)",
    title_ja: "スーパーホテル JR 奈良駅",
    romaji: "Super Hotel JR Nara",
    summary_zh: "**JR 奈良駅近接のリーズナブルチェーンホテル**。¥6,000-12,000(朝食バイキング込)、ビジネス・低予算観光客向け定番。客室はシンプルだが清潔、無料朝食 + 大浴場が特徴。",
    content_md: "- 場所:JR 奈良駅徒歩 5 分\n- 価格:¥6,000-12,000(朝食込)\n- 朝食:無料バイキング(健康朝食 + ご当地食)\n- 大浴場:あり\n- ビジネス向け:wifi・卓電源・コーヒー\n- 系列:スーパーホテル(全国 100+ 店)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.681,
    lon: 135.823,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 1,
    closed_days: [],
    external_urls: { official: "https://www.superhotel.co.jp/" },
    tags: ["budget_hotel_chain", "super_hotel", "jr_nara", "value"],
    source: "manual",
  },
  {
    slug: "nara-business-hotel-guide",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "JR/近鐵奈良駅前 ビジネスホテルガイド",
    title_ja: "奈良駅前ビジネスホテルガイド",
    romaji: "Nara Station Business Hotel Guide",
    summary_zh: "**JR 奈良駅・近鉄奈良駅前のビジネスホテル/ビジネス系チェーンホテル**(¥6,000-12,000 価格帯)。スーパーホテル・東横イン・ホテルルートイン・コンフォートホテル等が選べる、観光客でも実用的。",
    content_md: "- 場所:JR 奈良駅・近鉄奈良駅近隣\n- 主な系列:スーパーホテル・東横イン・ホテルルートイン・コンフォートホテル\n- 価格帯:¥6,000-12,000\n- 朝食:無料 OR 別途 ¥800-1,500\n- アクセス:駅徒歩 5 分以内が定番\n- 注意:正倉院展期(11 月)・桜時期(4 月)は満室早い",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.681,
    lon: 135.823,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "business_hotel", "nara_station", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 3 — ならまち町家泊
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "naramachi-machiya-stay-guide",
    category: "lodging",
    sub_type: "nara_machiya",
    title_zh: "ならまち町家泊ガイド(古都圈の古民家泊)",
    title_ja: "ならまち町家泊ガイド",
    romaji: "Naramachi Machiya Stay Guide",
    summary_zh: "**ならまち地区の古い町家を改装した一棟貸し宿**。京都町家とは別系統で、奈良独自の中庭・坪庭・井戸・神棚を残す古都圏建築。¥15,000-40,000/棟(2-6 名)、家族・グループ向け、自炊可能な物件多数。",
    content_md: "- 場所:奈良市ならまち(古い町人地)\n- 一棟貸し:2-6 名 ¥15,000-40,000\n- 特徴:中庭 + 坪庭 + 井戸 + 神棚\n- 自炊:可能(キッチン付き物件多数)\n- 京都との違い:奈良はより素朴・庭広め\n- 主な系列:NIPPONIA・三五屋・他複数 brand\n- 観光線:春日大社・東大寺・興福寺 徒歩圏",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.679,
    lon: 135.829,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["nara_machiya", "naramachi", "machiya_stay", "guide"],
    source: "manual",
  },
  {
    slug: "nipponia-nara-naramachi",
    category: "lodging",
    sub_type: "nara_machiya",
    title_zh: "NIPPONIA 奈良 ならまち(2018・古民家ホテル)",
    title_ja: "NIPPONIA 奈良 ならまち",
    romaji: "NIPPONIA Nara Naramachi",
    summary_zh: "**2018 年開業、ならまちの古民家を分散して再生したホテル**(複数古民家を 1 ホテルとして運営)。各棟独立で 5-12 室、料亭風朝食 + 古都の静寂。¥30,000-80,000/室。",
    content_md: "- 開業:2018\n- 場所:奈良市ならまち各所(分散ホテル)\n- 客室:複数古民家に分散・5-12 室\n- 価格:¥30,000-80,000/室\n- 食事:料亭風朝食付プラン中心\n- 設備:プライベート空間 + キッチン\n- 文化価値:町家保存 + 観光業の融合モデル",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.679,
    lon: 135.829,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["nara_machiya", "nipponia", "2018", "machiya_hotel"],
    source: "manual",
  },
  {
    slug: "naramachi-airbnb-guide",
    category: "lodging",
    sub_type: "nara_machiya",
    title_zh: "ならまち Airbnb / 一棟貸しガイド",
    title_ja: "ならまち Airbnb ガイド",
    romaji: "Naramachi Airbnb Guide",
    summary_zh: "**ならまち地区の Airbnb / Vrbo / 楽天トラベル一棟貸しガイド**。家族・友人グループ向け、¥10,000-25,000/棟・人数による。住宅宿泊事業法(民泊新法)登録物件のみ営業可、合法物件を選ぶこと。",
    content_md: "- 場所:奈良市ならまち\n- 価格:¥10,000-25,000/棟(人数による)\n- 主なプラットフォーム:Airbnb・Vrbo・楽天トラベル\n- 注意:民泊新法 登録番号確認(M 番号)— 違法物件を避ける\n- 宿泊上限:1 物件年 180 日\n- 家族・友人向け:キッチン・洗濯機完備物件多数",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.679,
    lon: 135.829,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["nara_machiya", "airbnb", "minpaku", "guide"],
    source: "manual",
  },
  {
    slug: "kintetsu-nara-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "近鉄奈良駅周邊 宿泊エリアガイド",
    title_ja: "近鉄奈良駅周辺ガイド",
    romaji: "Kintetsu Nara Lodging Area Guide",
    summary_zh: "**近鉄奈良駅周辺は奈良観光の最便利エリア**。徒歩圏に春日大社・東大寺・興福寺・もちいどの・ならまち。宿泊価格は JR 奈良駅周辺より高めだが、観光時間最大化のため奨める。中・高級ホテル + 町家泊の混在。",
    content_md: "- アクセス:近鉄奈良駅 → 京都 35 分・大阪なんば 40 分\n- 徒歩圏:春日大社・東大寺・興福寺・もちいどの・ならまち\n- 価格帯:¥10,000-50,000/泊\n- 主な選択肢:ホテル日航奈良(東口)・コートヤード・町家泊\n- 観光モデル:1 泊 2 日でも全主要観光カバー\n- 注:正倉院展(11 月)・桜時期(4 月)早期予約推奨",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.683,
    lon: 135.83,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "kintetsu_nara", "convenient", "guide"],
    source: "manual",
  },
  {
    slug: "naramachi-villa-private",
    category: "lodging",
    sub_type: "nara_machiya",
    title_zh: "ならまち プライベート泊 specific 物件ガイド",
    title_ja: "ならまち プライベート泊",
    romaji: "Naramachi Private Villa Guide",
    summary_zh: "**ならまちのプライベート 1 棟貸し**(grouping・家族・お忍び向け)。坪庭・井戸・神棚 + 現代キッチン + 洗濯機の現代設備。¥20,000-60,000/棟(2-8 名)、京都祇園の町家泊と比較する旅行者多い。",
    content_md: "- 物件タイプ:1 棟貸しプライベート\n- 収容:2-8 名\n- 価格:¥20,000-60,000/棟\n- 設備:中庭 + 現代キッチン + 洗濯機 + バスルーム\n- 用途:家族旅行・お忍び・グループ\n- 観光線:春日大社・東大寺・興福寺 徒歩圏\n- 京都との比較:奈良はより静か・観光客少なめ",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.679,
    lon: 135.829,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["nara_machiya", "private_villa", "family", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 4 — 寺宿(宿坊)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shukubo-nara-guide",
    category: "lodging",
    sub_type: "shukubo_temple",
    title_zh: "奈良寺宿(宿坊)ガイド — 古都の修行體驗",
    title_ja: "奈良 宿坊ガイド",
    romaji: "Nara Shukubo Guide",
    summary_zh: "**奈良各地の寺院宿坊**(僧侶と同居・朝勤行参加可)。1300 年級の修行体験、精進料理 + 早朝勤行 + 写経。¥6,000-15,000/泊(2 食付)、東大寺周辺 + 室生寺 + 長谷寺 + 吉野金峯山寺等で受入。",
    content_md: "- 主な対象:東大寺周辺・室生寺・長谷寺・吉野金峯山寺・等\n- 体験:朝 5-6 時勤行参加・写経・座禅・精進料理\n- 価格:¥6,000-15,000/泊(2 食付)\n- 部屋:畳和室・共同風呂\n- 文化価値:1300 年級の修行体験\n- 予約:寺院により異なる(電話・FAX 多い、web 少ない)\n- 注:消灯 21:00・起床 5-6 時の規律",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.838,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["shukubo_temple", "shukubo", "1300_years", "guide"],
    source: "manual",
  },
  {
    slug: "kinpusenji-shukubo",
    category: "lodging",
    sub_type: "shukubo_temple",
    title_zh: "金峯山寺 宿坊(吉野・修驗道總本山)",
    title_ja: "金峯山寺 宿坊",
    romaji: "Kinpusen-ji Shukubo",
    summary_zh: "**吉野山金峯山寺の宿坊**(複数の塔頭が運営)。修験道(7 世紀役小角開創)の修行体験、早朝勤行・お勤め・精進料理。桜時期(4 月)は予約困難、修験 + 桜の組合せが最高。¥8,000-15,000/泊。",
    content_md: "- 場所:吉野郡吉野町吉野山\n- 主催:金峯山寺塔頭(複数)\n- 体験:修験道朝勤行・写経・精進料理\n- 価格:¥8,000-15,000/泊(2 食付)\n- 桜時期(4 月):予約 6 ヶ月前推奨\n- 文化価値:1300 年級の修験道伝統\n- アクセス:近鉄吉野駅 + ロープウェイ吉野山駅",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "吉野町",
    lg_code: "29441",
    area_types: ["mountain", "rural"],
    lat: 34.366,
    lon: 135.864,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.kinpusen.or.jp/" },
    tags: ["shukubo_temple", "kinpusenji", "yoshino", "shugendo"],
    source: "manual",
  },
  {
    slug: "muroji-shukubo",
    category: "lodging",
    sub_type: "shukubo_temple",
    title_zh: "室生寺 宿坊(女人高野・山寺體驗)",
    title_ja: "室生寺 宿坊",
    romaji: "Murō-ji Shukubo",
    summary_zh: "**宇陀市室生寺は『女人高野』として知られる山寺**。宿坊で女性も歓迎、五重塔(国宝)+ 女人高野の歴史 + 山中の静寂。¥9,000-13,000/泊、4-5 月新緑 + 11 月紅葉が最高。",
    content_md: "- 場所:宇陀市室生・室生寺周辺\n- 文化価値:女人高野(女性参拝可の真言宗)\n- 国宝:五重塔・金堂\n- 体験:朝勤行・写経・山中散策\n- 価格:¥9,000-13,000/泊(2 食付)\n- 季節:4-5 月新緑・11 月紅葉が見頃\n- アクセス:近鉄「室生口大野駅」からバス・車",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "宇陀市",
    lg_code: "29212",
    area_types: ["mountain", "rural"],
    lat: 34.541,
    lon: 136.077,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.murouji.or.jp/" },
    tags: ["shukubo_temple", "muroji", "nyonin_koya", "uda"],
    source: "manual",
  },
  {
    slug: "hasedera-shukubo",
    category: "lodging",
    sub_type: "shukubo_temple",
    title_zh: "長谷寺 宿坊(牡丹の寺・觀音信仰)",
    title_ja: "長谷寺 宿坊",
    romaji: "Hase-dera Shukubo",
    summary_zh: "**桜井市長谷寺は牡丹 + 観音信仰の名刹**。宿坊で観音信仰体験、4-5 月の牡丹(7,000 株)が見頃。¥8,000-12,000/泊、初瀬山中の静寂 + 観音長谷寺の風情。",
    content_md: "- 場所:桜井市初瀬・長谷寺周辺\n- 文化価値:観音信仰の聖地・西国三十三所第八番\n- 名物:牡丹(7,000 株・4-5 月)・登廊\n- 体験:朝勤行・観音参拝・精進料理\n- 価格:¥8,000-12,000/泊(2 食付)\n- 季節:4-5 月牡丹・11 月紅葉\n- アクセス:近鉄「長谷寺駅」徒歩 15 分",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "桜井市",
    lg_code: "29206",
    area_types: ["mountain", "rural"],
    lat: 34.535,
    lon: 135.907,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.hasedera.or.jp/" },
    tags: ["shukubo_temple", "hasedera", "kannon", "botan"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 5 — 吉野山参詣宿
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "yoshino-onsen-motoyu",
    category: "lodging",
    sub_type: "yoshino_sankei_yado",
    title_zh: "吉野溫泉 元湯(700 年級・大海人皇子由來説)",
    title_ja: "吉野温泉 元湯",
    romaji: "Yoshino Onsen Motoyu",
    summary_zh: "**吉野山唯一の温泉旅館**。大海人皇子(後の天武天皇・672 年壬申の乱)が傷を癒した由緒ある温泉、現代まで継承。¥15,000-30,000/泊(2 食付)、桜時期(4 月)は予約困難。",
    content_md: "- 場所:吉野郡吉野町吉野山\n- 由緒:大海人皇子(672 壬申の乱・後の天武天皇)\n- 温泉:単純硫黄泉・含弱放射能泉\n- 価格:¥15,000-30,000/泊(2 食付)\n- 桜時期予約:6 ヶ月以上前推奨\n- 客室:数室の小規模\n- アクセス:近鉄吉野駅 + ロープウェイ + 徒歩",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "吉野町",
    lg_code: "29441",
    area_types: ["mountain", "rural"],
    lat: 34.366,
    lon: 135.866,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 180,
    closed_days: [],
    external_urls: {},
    tags: ["yoshino_sankei_yado", "yoshino_onsen", "motoyu", "tenmu_origin"],
    source: "manual",
  },
  {
    slug: "yoshino-sakura-stay-guide",
    category: "lodging",
    sub_type: "yoshino_sankei_yado",
    title_zh: "吉野山 櫻時期參詣宿ガイド(4 月混雜警告)",
    title_ja: "吉野山 桜時期参詣宿ガイド",
    romaji: "Yoshino Sakura Lodging Guide",
    summary_zh: "**吉野山 4 月の桜時期は日本最難予約期**。下千本-上千本の参詣宿(50+ 軒)が 6 ヶ月前から予約埋まり、満月時の千本桜 view 客室は 1 年前予約も。¥20,000-50,000、価格は通常期の 2-3 倍。",
    content_md: "- 場所:吉野山下千本〜上千本\n- 軒数:参詣宿 50+ 軒\n- 桜時期:3 月下-4 月中(下千本→中千本→上千本→奥千本)\n- 予約:6 ヶ月-1 年前\n- 価格:¥20,000-50,000(通常期の 2-3 倍)\n- 千本桜 view 客室:超人気・1 年前予約\n- 代替:吉野駅周辺・五條市・桜井市の宿から日帰り",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "吉野町",
    lg_code: "29441",
    area_types: ["mountain", "rural"],
    lat: 34.394,
    lon: 135.857,
    season_start: "2000-03-25",
    season_end: "2000-04-30",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 180,
    closed_days: [],
    external_urls: {},
    tags: ["yoshino_sankei_yado", "sakura_season", "crowded_warning", "guide"],
    source: "manual",
  },
  {
    slug: "yoshino-sankei-yado-guide",
    category: "lodging",
    sub_type: "yoshino_sankei_yado",
    title_zh: "吉野山參詣宿ガイド(通年・修驗道體驗)",
    title_ja: "吉野山 参詣宿ガイド",
    romaji: "Yoshino Sankei Lodging Guide",
    summary_zh: "**吉野山参詣宿の通年ガイド**(桜時期以外)。修験道伝統の宿、簡素な部屋 + 山中精進料理 + 早朝参詣。¥8,000-15,000/泊(2 食付)が標準価格、4-5 月新緑・11 月紅葉が見頃。",
    content_md: "- 通年営業の参詣宿:30+ 軒\n- 価格:¥8,000-15,000/泊(2 食付・標準期)\n- 体験:朝参詣・精進料理・修験道入門\n- 季節:4 月桜・5 月新緑・11 月紅葉・2 月雪景色\n- 桜時期以外:予約しやすい\n- アクセス:近鉄吉野駅 + ロープウェイ吉野山駅",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "吉野町",
    lg_code: "29441",
    area_types: ["mountain", "rural"],
    lat: 34.366,
    lon: 135.864,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["yoshino_sankei_yado", "year_round", "shugendo", "guide"],
    source: "manual",
  },
  {
    slug: "yoshino-sakura-house",
    category: "lodging",
    sub_type: "yoshino_sankei_yado",
    title_zh: "吉野山 桜花壇(specific 老舗参詣宿)",
    title_ja: "吉野山 桜花壇",
    romaji: "Yoshino Sakura Kadan",
    summary_zh: "**吉野山中千本にある参詣宿**。桜時期は中千本桜 view が窓から見える絶好立地、5 室程度の小規模 + 家族経営。¥18,000-35,000/泊、桜時期は 1 年前予約。",
    content_md: "- 場所:吉野郡吉野町吉野山中千本\n- 客室:5 室程度の小規模\n- 価格:¥18,000-35,000/泊(2 食付)\n- 桜時期:中千本桜 view 客室は最高景\n- 家族経営:小規模 + 個人的サービス\n- 桜時期予約:1 年前以上\n- アクセス:吉野山ロープウェイ徒歩 15 分",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "吉野町",
    lg_code: "29441",
    area_types: ["mountain", "rural"],
    lat: 34.376,
    lon: 135.864,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 180,
    closed_days: [],
    external_urls: {},
    tags: ["yoshino_sankei_yado", "sakura_view", "small_inn"],
    source: "manual",
  },
  {
    slug: "yoshino-yamanoyado-yumesara",
    category: "lodging",
    sub_type: "yoshino_sankei_yado",
    title_zh: "吉野山の宿 specific area guide(中千本 vs 上千本選び方)",
    title_ja: "吉野山 宿選び ガイド",
    romaji: "Yoshino Lodging Selection Guide",
    summary_zh: "**吉野山の参詣宿エリア選び方ガイド**。下千本(ロープウェイ駅近・便利)・中千本(桜中心・観光定番)・上千本(静寂・桜咲くのが遅い・上級者)。桜時期にどこを選ぶかで体験が大きく変わる。",
    content_md: "- 下千本:ロープウェイ駅・最便利・桜咲くの早(3 月下-4 月初)\n- 中千本:吉野山中心・観光定番・桜 4 月中・最も予約困難\n- 上千本:登り 1-2 km・静寂・桜 4 月中-下\n- 奥千本:更に 30 分上・桜咲く最遅(4 月下)・最静寂\n- 選び方:体力 + 桜目当て期日 + 予算で決める",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "吉野町",
    lg_code: "29441",
    area_types: ["mountain", "rural"],
    lat: 34.376,
    lon: 135.864,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yoshino_sankei_yado", "area_selection", "guide"],
    source: "manual",
  },
  {
    slug: "yoshino-cable-station-yado",
    category: "lodging",
    sub_type: "yoshino_sankei_yado",
    title_zh: "近鐵吉野駅 + ケーブル下千本周邊宿",
    title_ja: "近鉄吉野駅周辺の宿",
    romaji: "Kintetsu Yoshino Station Lodging",
    summary_zh: "**近鉄吉野駅 + ロープウェイ下千本駅周辺の宿**。吉野山中の参詣宿より便利、当日早朝に山に登る人向け。¥10,000-25,000/泊、参詣宿予約取れない時の代替地。",
    content_md: "- 場所:吉野町下千本・近鉄吉野駅周辺\n- 価格:¥10,000-25,000/泊\n- 用途:吉野山参詣宿予約取れない時の代替\n- 早朝出発:5-6 時にロープウェイ下千本駅へ\n- 桜時期:山中宿より予約しやすい(混雑あり)\n- 1 泊 2 日モデル:早朝山頂 → 夕方下山",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "吉野町",
    lg_code: "29441",
    area_types: ["small_town", "rural"],
    lat: 34.385,
    lon: 135.852,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["yoshino_sankei_yado", "kintetsu_yoshino", "alternative"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 6 — 明日香村泊
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "asuka-village-minshuku-guide",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "明日香村 民宿ガイド(古墳觀光向け)",
    title_ja: "明日香村 民宿ガイド",
    romaji: "Asuka Minshuku Guide",
    summary_zh: "**明日香村の小規模民宿・古民家泊ガイド**。古墳・キトラ・高松塚観光客向け、村中は宿が少なく予約必須。¥6,000-15,000/泊(2 食付)、家族経営の素朴な民宿が大半。",
    content_md: "- 場所:明日香村全域\n- 軒数:村全体で 10+ 軒(小規模)\n- 価格:¥6,000-15,000/泊(2 食付)\n- 家族経営:大半\n- 食事:大和野菜・古代米・地鶏(飛鳥鍋)\n- 観光線:石舞台・キトラ・高松塚 自転車 1 日\n- 注:村中は宿少ない・予約必須",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "高市郡",
    municipality_ja: "明日香村",
    lg_code: "29402",
    area_types: ["rural"],
    lat: 34.467,
    lon: 135.821,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "asuka_village", "kofun_tourism", "guide"],
    source: "manual",
  },
  {
    slug: "asuka-kominka-stay",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "明日香村 古民家泊(伝統民家の改裝宿)",
    title_ja: "明日香村 古民家泊",
    romaji: "Asuka Kominka Stay",
    summary_zh: "**明日香村の伝統的な茅葺・瓦葺の古民家を改装した宿**。1 棟貸し中心、古墳観光客 + 写真愛好家に人気。¥20,000-50,000/棟(2-6 名)、自炊可能な物件も多い。",
    content_md: "- 物件:茅葺・瓦葺の古民家改装\n- 価格:¥20,000-50,000/棟(2-6 名)\n- 用途:家族・グループ・写真愛好家\n- 設備:現代キッチン + 古民家の趣\n- 観光線:石舞台 + キトラ + 高松塚 + 古代米田\n- 予約期:春・秋の観光最盛期は早めに",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "高市郡",
    municipality_ja: "明日香村",
    lg_code: "29402",
    area_types: ["rural"],
    lat: 34.467,
    lon: 135.821,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "asuka", "kominka", "private_villa"],
    source: "manual",
  },
  {
    slug: "kashihara-area-lodging-guide",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "橿原市 宿泊エリアガイド(明日香近接の代替)",
    title_ja: "橿原市 宿泊ガイド",
    romaji: "Kashihara Lodging Guide",
    summary_zh: "**橿原市は明日香村観光の代替宿泊エリア**。近鉄橿原神宮前駅 + 大和八木駅周辺にビジネスホテル + 中級ホテル多数、明日香へ車 / バス 15 分。¥8,000-20,000/泊、明日香民宿予約取れない時の便利な選択。",
    content_md: "- 場所:橿原市・近鉄橿原神宮前駅 + 大和八木駅\n- 主な選択肢:ビジネスホテル系 + 中級ホテル\n- 価格:¥8,000-20,000/泊\n- 明日香へ:車 / バス 15 分\n- 観光線:明日香 + 橿原神宮 + 神武天皇陵\n- 用途:明日香民宿予約取れない時の代替",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "橿原市",
    lg_code: "29205",
    area_types: ["urban_local"],
    lat: 34.488,
    lon: 135.789,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "kashihara", "asuka_alternative", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 7 — 十津川温泉
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "totsukawa-onsen-guide",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "十津川溫泉ガイド(日本最大村・秘湯)",
    title_ja: "十津川温泉ガイド",
    romaji: "Totsukawa Onsen Guide",
    summary_zh: "**十津川村は日本最大面積の村(672 km²)+ 全国で唯一の村全体『源泉かけ流し宣言』地区**。十津川温泉郷(三泉)+ 上湯温泉 + 湯泉地温泉、いずれも秘湯感。¥10,000-25,000/泊(2 食付)、車・バスのみ(JR 五条駅から 2-3 時間)。",
    content_md: "- 場所:吉野郡十津川村\n- 規模:672 km²(日本最大村・東京 23 区相当)\n- 温泉宣言:全国唯一の村全体『源泉かけ流し宣言』(2004)\n- 三大温泉郷:十津川温泉・上湯温泉・湯泉地温泉\n- 価格:¥10,000-25,000/泊(2 食付)\n- アクセス:JR 五条駅 + 奈良交通バス 2-3 時間\n- 注:車推奨・バス便少",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "十津川村",
    lg_code: "29449",
    area_types: ["mountain", "rural"],
    lat: 33.971,
    lon: 135.789,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://totsukawa.info/" },
    tags: ["onsen_ryokan", "totsukawa", "remote_village", "kakenagashi"],
    source: "manual",
  },
  {
    slug: "totsukawa-tsubomeyu-onsen",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "上湯溫泉(十津川秘湯・河原露天風呂)",
    title_ja: "上湯温泉",
    romaji: "Kamiyu Onsen",
    summary_zh: "**十津川温泉郷の中で最秘湯感ある上湯温泉**。河原に露天風呂(混浴・無料)・川沿いの素朴な旅館数軒。¥12,000-25,000/泊、温泉だけ目当ての旅人向け、村奥への秘湯巡り。",
    content_md: "- 場所:十津川村上湯川\n- 名物:上湯川河原露天風呂(無料・混浴・要水着)\n- 旅館:数軒の小規模\n- 価格:¥12,000-25,000/泊\n- アクセス:JR 五条駅から車 2 時間半\n- 季節:通年(冬は雪景色秘湯)\n- 文化価値:平家の落人伝説も残る秘境",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "十津川村",
    lg_code: "29449",
    area_types: ["mountain", "rural"],
    lat: 33.96,
    lon: 135.79,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["onsen_ryokan", "kamiyu", "totsukawa", "remote_hot_spring"],
    source: "manual",
  },
  {
    slug: "totsukawa-yusenji-onsen",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "湯泉地溫泉(十津川村・歴史的湯治)",
    title_ja: "湯泉地温泉",
    romaji: "Tōsenji Onsen",
    summary_zh: "**十津川村役場近くの湯泉地温泉**。江戸期からの湯治場、現在も数軒の旅館 + 公衆浴場。¥10,000-20,000/泊、十津川村観光の中心拠点として機能、玉置神社参拝の起点。",
    content_md: "- 場所:十津川村役場近隣\n- 由緒:江戸期からの湯治場\n- 旅館:数軒の中規模\n- 公衆浴場:あり\n- 価格:¥10,000-20,000/泊(2 食付)\n- 観光線:玉置神社 + 谷瀬の吊り橋 + 熊野古道\n- アクセス:JR 五条駅 + 奈良交通バス",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "十津川村",
    lg_code: "29449",
    area_types: ["mountain", "rural"],
    lat: 33.97,
    lon: 135.79,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["onsen_ryokan", "tosenji", "totsukawa", "edo_origin"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 8 — 大和高原・宇陀
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "uda-matsuyama-stay-guide",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "宇陀松山 古い町並み 宿泊ガイド",
    title_ja: "宇陀松山 宿泊ガイド",
    romaji: "Uda Matsuyama Lodging Guide",
    summary_zh: "**宇陀市大宇陀松山地区の古い町並み**(国の重要伝統的建造物群保存地区)。江戸期の薬の街として栄えた商家町、町家を改装した小規模宿数軒。¥15,000-35,000/泊、京都祇園や奈良ならまちと比較し非常に静か、歷史好きに最適。",
    content_md: "- 場所:宇陀市大宇陀松山\n- 文化価値:重要伝統的建造物群保存地区(2006 指定)\n- 由緒:江戸期の薬の街(置き薬・大和当帰)\n- 宿:町家改装の小規模(数軒)\n- 価格:¥15,000-35,000/泊\n- 観光線:松山町並み + 又兵衛桜(春)+ 室生寺\n- アクセス:近鉄榛原駅 + バス 10 分",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "宇陀市",
    lg_code: "29212",
    area_types: ["small_town", "rural"],
    lat: 34.481,
    lon: 135.943,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "uda_matsuyama", "preservation_district", "guide"],
    source: "manual",
  },
  {
    slug: "yamato-kogen-onsen",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "大和高原溫泉ガイド(月ヶ瀬・宇陀の自然湯)",
    title_ja: "大和高原温泉ガイド",
    romaji: "Yamato Kōgen Onsen Guide",
    summary_zh: "**奈良東部の大和高原(月ヶ瀬・宇陀・山添)の温泉旅館ガイド**。京都・奈良観光客が知らない隠れ家、茶畑 + 山郷の風景 + 温泉。¥12,000-25,000/泊、自然 + 静寂を求める旅人向け。",
    content_md: "- 場所:奈良市月ヶ瀬・宇陀市・山添村\n- 主な温泉:あきののゆ(宇陀)・あんもにて(月ヶ瀬)\n- 価格:¥12,000-25,000/泊\n- 季節:2-4 月梅・新茶・10-11 月紅葉\n- 観光線:茶畑 + 月ヶ瀬梅渓 + 室生寺\n- アクセス:近鉄榛原駅 + バス・車推奨",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "宇陀市",
    lg_code: "29212",
    area_types: ["mountain", "rural"],
    lat: 34.481,
    lon: 135.943,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["onsen_ryokan", "yamato_kogen", "uda", "rural_onsen", "guide"],
    source: "manual",
  },
  {
    slug: "akinonoyu-uda",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "あきののゆ(宇陀・万葉公園併設の溫泉)",
    title_ja: "あきののゆ",
    romaji: "Akinonoyu",
    summary_zh: "**宇陀市の万葉公園併設の日帰り温泉 + 宿泊施設**。大和高原の自然 + 万葉時代の歴史、入浴 ¥800・宿泊 ¥10,000-18,000。又兵衛桜・室生寺観光の起点。",
    content_md: "- 場所:宇陀市大宇陀拾生・万葉公園内\n- 入浴:¥800(11:00-22:00)\n- 宿泊:¥10,000-18,000/泊\n- 温泉:重曹泉(美肌の湯)\n- 設備:大浴場・露天風呂・サウナ\n- 観光線:又兵衛桜(春)+ 室生寺 + 大宇陀松山\n- アクセス:近鉄榛原駅 + バス 15 分",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "宇陀市",
    lg_code: "29212",
    area_types: ["mountain", "rural"],
    lat: 34.481,
    lon: 135.943,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["onsen_ryokan", "akinonoyu", "uda", "mannyo_park"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 9 — 季節 + area guide
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nara-shosoin-ten-lodging",
    category: "lodging",
    sub_type: "seasonal_lodging",
    title_zh: "正倉院展期間の奈良宿泊ガイド(10-11 月混雜警告)",
    title_ja: "正倉院展期間の奈良宿泊ガイド",
    romaji: "Shōsōin Ten Lodging Guide",
    summary_zh: "**正倉院展期間(10 月下-11 月初・17 日間)は奈良市内ホテル予約困難期**。1 日 5,000+ 観光客が集中、ホテル価格が通常期の 1.5-2 倍。早期予約(3 ヶ月前)+ 大阪/京都泊で日帰り(JR 45 分)代替も検討。",
    content_md: "- 期間:正倉院展(10 月下-11 月初・17 日間)\n- 混雑度:1 日 5,000+ 観光客\n- ホテル価格:通常期の 1.5-2 倍\n- 予約:3 ヶ月前推奨\n- 代替案:大阪・京都泊 + 日帰り(JR 45 分)\n- 別の代替:橿原市・JR 桜井駅周辺",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.834,
    season_start: "2000-10-25",
    season_end: "2000-11-13",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_lodging", "shosoin_ten", "crowded_warning", "guide"],
    source: "manual",
  },
  {
    slug: "nara-sakura-lodging-guide",
    category: "lodging",
    sub_type: "seasonal_lodging",
    title_zh: "奈良 春季桜時期 宿泊ガイド(吉野 + 奈良市)",
    title_ja: "奈良 桜時期 宿泊ガイド",
    romaji: "Nara Sakura Season Lodging",
    summary_zh: "**3 月下-4 月中の桜時期は奈良 + 吉野山が同時最盛期**。奈良公園(東大寺・興福寺・春日)+ 吉野千本桜の両地区を見るには 2 泊推奨、いずれも予約困難 6 ヶ月前推奨。",
    content_md: "- 桜地区:奈良市(奈良公園・吉城園)+ 吉野山(下中上奥千本)\n- 期間:3 月下旬-4 月中旬\n- 推奨日数:2 泊(奈良 1 + 吉野 1)\n- 予約:6 ヶ月前推奨\n- 価格:通常期の 1.5-2 倍\n- 移動:近鉄奈良 → 吉野 1 時間 30 分(乗換あり)\n- 代替:大阪・京都拠点で日帰り",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.805,
    season_start: "2000-03-25",
    season_end: "2000-04-15",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 180,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_lodging", "sakura", "yoshino", "nara_park", "guide"],
    source: "manual",
  },
  {
    slug: "nara-mantoro-lodging",
    category: "lodging",
    sub_type: "seasonal_lodging",
    title_zh: "春日萬燈籠 宿泊ガイド(8/14-15 夏夜の風物詩)",
    title_ja: "春日万灯籠 宿泊ガイド",
    romaji: "Kasuga Mantōrō Lodging",
    summary_zh: "**8/14-15 の春日万灯籠(春日大社 3,000 灯籠点灯)+ なら燈花会(8/5-14)時期は夏の混雑期**。お盆期 + 灯籠で奈良市内ホテル満室、3 ヶ月前予約推奨。¥18,000-40,000/泊。",
    content_md: "- 行事:春日万灯籠(8/14-15)+ なら燈花会(8/5-14)\n- 混雑度:お盆期 + 灯籠で満室必至\n- ホテル価格:¥18,000-40,000(通常期の 1.5 倍)\n- 予約:3 ヶ月前推奨\n- 観光モデル:夕方着付浴衣 → 万灯籠参拝 → 帰宿\n- 代替:大阪・京都泊 + 日帰り(夜行バス可)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.681,
    lon: 135.847,
    season_start: null,
    season_end: null,
    event_start: "2000-08-05",
    event_end: "2000-08-15",
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_lodging", "kasuga_mantoro", "summer_festival", "guide"],
    source: "manual",
  },
  {
    slug: "nara-momiji-lodging-guide",
    category: "lodging",
    sub_type: "seasonal_lodging",
    title_zh: "奈良 紅葉時期 宿泊ガイド(11 月・談山 + 室生寺)",
    title_ja: "奈良 紅葉時期 宿泊ガイド",
    romaji: "Nara Momiji Lodging Guide",
    summary_zh: "**奈良の紅葉名所は談山神社 + 室生寺 + 春日山遊歩道**。11 月中-下旬が見頃、正倉院展(10 月末-11 月初)と被るため宿泊予約は早めに。談山近隣には宇陀温泉、室生寺近隣に山郷宿あり。",
    content_md: "- 紅葉名所:談山神社(桜井)・室生寺(宇陀)・春日山遊歩道\n- 期間:11 月中-下旬\n- 注意:正倉院展(10/25-11/13)と被るので予約困難\n- 推奨:奈良市 + 山郷の 2 泊コース\n- 山郷宿:宇陀温泉・室生寺宿坊\n- 予約:3 ヶ月前推奨",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.805,
    season_start: "2000-11-10",
    season_end: "2000-11-30",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_lodging", "momiji", "tanzan", "muroji", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 10 — 奈良市他地区(Round 2)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nishinokyo-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "西ノ京エリア宿泊ガイド(薬師寺・唐招提寺周辺)",
    title_ja: "西ノ京エリア宿泊ガイド",
    romaji: "Nishi-no-Kyō Lodging Guide",
    summary_zh: "**奈良市西部・西ノ京エリア**(薬師寺・唐招提寺の世界遺産 2 寺院近辺)。観光客は少なめ、静かに泊まれる代替地。近鉄西ノ京駅周辺にビジネスホテル数軒、奈良駅前より少し安め(¥7,000-15,000)、観光は近鉄で奈良駅まで 5 分。",
    content_md: "- 場所:奈良市西ノ京・近鉄西ノ京駅周辺\n- 観光線:薬師寺・唐招提寺(世界遺産)+ 奈良駅まで近鉄 5 分\n- 価格:¥7,000-15,000(駅前より少し安め)\n- 雰囲気:静か・観光客少なめ\n- ホテル選択:ビジネスホテル系数軒\n- 用途:奈良駅前ホテル満室時の代替",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.668,
    lon: 135.785,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "nishinokyo", "yakushiji_nearby", "guide"],
    source: "manual",
  },
  {
    slug: "heijo-kyu-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "平城宮跡周邊 宿泊ガイド(大和西大寺駅近辺)",
    title_ja: "平城宮跡周辺 宿泊ガイド",
    romaji: "Heijō-kyū Lodging Guide",
    summary_zh: "**平城宮跡(710-784 都・世界遺産)近辺の宿泊エリア**。近鉄大和西大寺駅 + 平城駅徒歩圏、観光客が少なく静か。¥8,000-18,000、JR 奈良駅まで近鉄 6 分。古都発祥の地に泊まる体験。",
    content_md: "- 場所:奈良市佐紀町・近鉄大和西大寺駅 + 平城駅\n- 観光線:平城宮跡(世界遺産)+ 唐招提寺・薬師寺 + 西大寺\n- 価格:¥8,000-18,000\n- ホテル選択:近鉄大和西大寺駅前ホテル数軒\n- アクセス:JR 奈良駅まで近鉄 6 分\n- 文化価値:710-784 平城京 都の地",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.692,
    lon: 135.781,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "heijo_kyu", "saidaiji_station", "guide"],
    source: "manual",
  },
  {
    slug: "nara-jr-west-business-area",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "JR 奈良駅西側 ビジネスホテル area(関西他都市移動向け)",
    title_ja: "JR 奈良駅西側ガイド",
    romaji: "JR Nara West Business Guide",
    summary_zh: "**JR 奈良駅西口側のビジネスホテル area**。ANA Crowne Plaza 以外にも東横イン・ホテルルートイン・コンフォート等のチェーン系。京都(JR 45 分)・大阪(JR 50 分)へ朝動きやすい、関西複数都市観光の拠点に。",
    content_md: "- 場所:JR 奈良駅西口側\n- 主な系列:東横イン・ルートイン・コンフォート・スーパー\n- 価格:¥6,000-12,000\n- 用途:京都(JR 45 分)・大阪(JR 50 分)早朝移動\n- ビジネス向け:wifi・卓電源・無料朝食\n- 観光線:奈良観光は近鉄奈良駅まで徒歩 12 分",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.681,
    lon: 135.823,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "jr_nara_west", "kansai_hub", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 11 — 斑鳩・山辺の道
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "ikaruga-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "斑鳩町 宿泊ガイド(法隆寺周辺・世界遺產泊)",
    title_ja: "斑鳩町 宿泊ガイド",
    romaji: "Ikaruga Lodging Guide",
    summary_zh: "**法隆寺(現存最古木造・世界遺産)周辺の宿**。観光客は法隆寺日帰りが多く、宿泊は希少 — 朝の法隆寺を独占できる宿泊体験は希少価値。¥10,000-20,000、町内ビジネスホテル + 古民家泊数軒、奈良市まで JR 12 分。",
    content_md: "- 場所:生駒郡斑鳩町・JR 法隆寺駅周辺\n- 観光価値:朝の法隆寺独占体験\n- 宿の数:小規模(町内 5-10 軒程度)\n- 価格:¥10,000-20,000\n- アクセス:JR 法隆寺駅 → 奈良 12 分・大阪 35 分\n- 観光線:法隆寺・中宮寺・法輪寺・法起寺(世界遺産候補)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "生駒郡",
    municipality_ja: "斑鳩町",
    lg_code: "29344",
    area_types: ["small_town"],
    lat: 34.614,
    lon: 135.738,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "ikaruga", "horyuji_nearby", "world_heritage", "guide"],
    source: "manual",
  },
  {
    slug: "yamanobe-no-michi-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "山邊の道沿い 宿泊ガイド(天理・桜井・古道泊)",
    title_ja: "山辺の道 宿泊ガイド",
    romaji: "Yamanobe-no-Michi Lodging Guide",
    summary_zh: "**山辺の道(日本最古の街道・記紀時代)沿いの宿泊地**。天理・桜井市内に旅館 + 民宿が点在、古道ハイキング 2 日コース(三輪 → 大神神社 → 山辺の道 → 天理)向け。¥8,000-18,000/泊。",
    content_md: "- 場所:天理市 + 桜井市の山辺の道沿い\n- 文化価値:日本最古の街道(記紀『古事記』『日本書紀』に記載)\n- 主な宿:天理駅前・桜井駅前・大神神社近\n- 価格:¥8,000-18,000\n- ハイキング:三輪 ↔ 天理 約 16 km(2 日推奨)\n- 観光線:大神神社・檜原神社・崇神天皇陵・石上神宮\n- アクセス:JR / 近鉄桜井駅・JR 天理駅",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "桜井市",
    lg_code: "29206",
    area_types: ["small_town", "rural"],
    lat: 34.529,
    lon: 135.852,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "yamanobe_no_michi", "tenri", "sakurai", "guide"],
    source: "manual",
  },
  {
    slug: "omiwa-jinja-area-lodging",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "大神神社近隣 宿(三輪・参拝者向け)",
    title_ja: "大神神社近隣 宿",
    romaji: "Ōmiwa Jinja Lodging",
    summary_zh: "**大神神社(三輪・最古級神社)近隣の旅館・民宿**。早朝参拝(5 時開門)に対応する小規模宿、三輪そうめん夕食 + 朝参拝コース。¥10,000-18,000/泊、JR 三輪駅徒歩 5-10 分。",
    content_md: "- 場所:桜井市三輪・JR 三輪駅周辺\n- 文化価値:大神神社(日本最古級神社・本殿なし)\n- 早朝参拝:5 時開門に対応\n- 食事:三輪そうめん夕食定番\n- 価格:¥10,000-18,000\n- 観光線:大神神社 → 山辺の道 → 天理\n- アクセス:JR 三輪駅徒歩 5-10 分",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "桜井市",
    lg_code: "29206",
    area_types: ["small_town"],
    lat: 34.529,
    lon: 135.852,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "omiwa", "miwa", "early_morning"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 12 — 寺宿追加
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "saidaiji-shukubo",
    category: "lodging",
    sub_type: "shukubo_temple",
    title_zh: "西大寺 宿坊(真言律宗總本山)",
    title_ja: "西大寺 宿坊",
    romaji: "Saidai-ji Shukubo",
    summary_zh: "**西大寺の宿坊**(真言律宗総本山・765 年称徳天皇創建)。称徳天皇発願の歴史ある寺、宿坊で律宗の修行体験 + 大茶盛茶会(直径 30cm 茶碗)が独特。¥8,000-12,000/泊、近鉄大和西大寺駅徒歩 4 分のアクセス便利。",
    content_md: "- 場所:奈良市西大寺芝町・近鉄大和西大寺駅徒歩 4 分\n- 文化価値:真言律宗総本山(765 創建)\n- 体験:朝勤行・写経・大茶盛(直径 30cm 茶碗)\n- 価格:¥8,000-12,000/泊(2 食付)\n- 食事:精進料理\n- 大茶盛:不定期開催・要事前確認",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.692,
    lon: 135.781,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://saidaiji.or.jp/" },
    tags: ["shukubo_temple", "saidaiji", "shingon_risshu", "ochamori"],
    source: "manual",
  },
  {
    slug: "todaiji-area-shukubo",
    category: "lodging",
    sub_type: "shukubo_temple",
    title_zh: "東大寺周邊 宿坊ガイド(早朝大仏殿向け)",
    title_ja: "東大寺周辺 宿坊ガイド",
    romaji: "Tōdai-ji Shukubo Guide",
    summary_zh: "**東大寺塔頭・周辺の宿坊**。早朝(7:30 開門前)の大仏殿独占体験ができる、宿坊宿泊客の特別パターン。¥10,000-18,000/泊、東大寺観光 + 修二会(3 月)時期に人気。",
    content_md: "- 場所:奈良市東大寺周辺\n- 価値:早朝大仏殿(開門前)体験\n- 主な宿:塔頭の小規模宿坊数軒\n- 価格:¥10,000-18,000/泊\n- 食事:精進料理\n- 観光線:東大寺二月堂修二会(3/1-14)時期に人気\n- 注:web 予約少なく電話 / FAX 中心",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.689,
    lon: 135.84,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["shukubo_temple", "todaiji_area", "early_morning_daibutsuden", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 13 — 吉野南部追加
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "dorogawa-onsen-tenkawa",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "洞川溫泉(天川村・修驗道湯治場 1300 年)",
    title_ja: "洞川温泉",
    romaji: "Dorogawa Onsen",
    summary_zh: "**天川村の洞川温泉は大峯山(1719m)登拝の修験道湯治場**(1300 年級)。大峯山参拝者が下山後に湯治する伝統、現代も「女人結界」前の最終地点として機能。20+ 軒の旅館、¥10,000-20,000、夏(7-9 月)が登拝最盛期。",
    content_md: "- 場所:吉野郡天川村洞川\n- 文化価値:大峯山(1719m)修験道湯治場 1300 年\n- 大峯山:女人結界(女性入山禁止)— 役小角開山\n- 旅館:20+ 軒\n- 価格:¥10,000-20,000/泊(2 食付)\n- ピーク:夏 7-9 月(登拝期)\n- アクセス:近鉄下市口駅 + バス 1 時間\n- 文化価値:日本最古の修験道センター",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "天川村",
    lg_code: "29446",
    area_types: ["mountain", "rural"],
    lat: 34.262,
    lon: 135.876,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.dorogawaonsen.jp/" },
    tags: ["onsen_ryokan", "dorogawa", "tenkawa", "shugendo", "ominesan"],
    source: "manual",
  },
  {
    slug: "kawakami-onsen",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "川上村の溫泉宿(吉野林業の里)",
    title_ja: "川上村の温泉宿",
    romaji: "Kawakami Onsen",
    summary_zh: "**川上村は吉野林業の里(吉野杉の本場)、大滝ダム + 大台ヶ原入口の温泉宿数軒**。道の駅杉の湯川上が中心、ホテル杉の湯併設。¥10,000-22,000/泊、大台ヶ原ハイキング・大瀧ダム観光の拠点。",
    content_md: "- 場所:吉野郡川上村迫\n- 主な施設:ホテル杉の湯(道の駅併設)\n- 文化価値:吉野林業の本場・杉造林発祥\n- 価格:¥10,000-22,000/泊\n- 観光線:大台ヶ原(日本秘境)・大瀧ダム・吉野川源流\n- アクセス:近鉄大和上市駅 + バス 50 分・車推奨\n- 季節:5-10 月のハイキング期",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "川上村",
    lg_code: "29452",
    area_types: ["mountain", "rural"],
    lat: 34.241,
    lon: 135.927,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["onsen_ryokan", "kawakami", "yoshino_forestry", "odaigahara"],
    source: "manual",
  },
  {
    slug: "gojo-otou-area-lodging",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "五條大塔エリア 宿(山郷の中継拠点)",
    title_ja: "五條大塔エリア宿",
    romaji: "Gojō Ōtō Lodging",
    summary_zh: "**五條市大塔(旧大塔村)の山郷宿**。十津川温泉 + 高野山方面への中継拠点、道の駅吉野路大塔(コテージ・温泉付)が代表。¥8,000-18,000/泊、車旅の途中泊として機能。",
    content_md: "- 場所:五條市大塔町阪本\n- 主な施設:道の駅吉野路大塔(コテージ・夢乃湯温泉付)\n- 価格:¥8,000-18,000/泊\n- 用途:十津川温泉・高野山方面への中継\n- アクセス:JR 五条駅 + バス 1 時間・車推奨\n- 観光線:大塔渓谷・荒神社・天狗倉山",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "五條市",
    lg_code: "29207",
    area_types: ["mountain", "rural"],
    lat: 34.181,
    lon: 135.74,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "gojo", "otou", "stopover"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 14 — グランピング・新型
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nara-glamping-guide",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "奈良グランピング場ガイド(2010 年代以降の新型)",
    title_ja: "奈良グランピングガイド",
    romaji: "Nara Glamping Guide",
    summary_zh: "**2015-2025 年に増加した奈良のグランピング施設**。大和高原・室生・吉野・五條に分散、テント + ベッド + バーベキュー + 温泉のセット。¥15,000-35,000/泊・人、家族・カップル向けの非日常体験。",
    content_md: "- 出現時期:2015 年以降(全国グランピングブーム)\n- 主な分布:大和高原・室生・吉野・五條\n- 価格:¥15,000-35,000/人(1 泊 2 食付・温泉付)\n- 設備:テント + ベッド + 暖房 + バーベキューセット\n- 季節:4-11 月メイン(冬期一部営業)\n- 用途:家族・カップル・グループ\n- 予約:web 中心(楽天トラベル・じゃらん 等)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["mountain", "rural"],
    lat: 34.685,
    lon: 135.805,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "glamping", "modern_2015", "guide"],
    source: "manual",
  },
  {
    slug: "yamato-kogen-glamping",
    category: "lodging",
    sub_type: "glamping_camp",
    title_zh: "大和高原 グランピング(月ヶ瀬・宇陀の自然空間)",
    title_ja: "大和高原 グランピング",
    romaji: "Yamato Kōgen Glamping",
    summary_zh: "**大和高原の月ヶ瀬・宇陀地区にあるグランピング施設**。茶畑・梅渓・里山風景の中、星空観察 + 焚き火 + 地元食材バーベキュー。¥18,000-30,000/人、京都・奈良観光と組合せ可。",
    content_md: "- 場所:奈良市月ヶ瀬・宇陀市・山添村\n- 自然環境:茶畑・梅渓・星空観察\n- 価格:¥18,000-30,000/人\n- 食事:大和野菜・大和肉鶏 BBQ\n- 季節:4-11 月メイン\n- アクセス:近鉄榛原駅 + 車 / 送迎\n- 用途:京都・奈良観光のサイドトリップ",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "宇陀市",
    lg_code: "29212",
    area_types: ["mountain", "rural"],
    lat: 34.481,
    lon: 135.943,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["glamping_camp", "yamato_kogen", "tsukigase", "uda", "stargazing"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 15 — 信貴山・生駒山系
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shigisan-chogosonshiji-shukubo",
    category: "lodging",
    sub_type: "shukubo_temple",
    title_zh: "信貴山 朝護孫子寺 宿坊(聖德太子由緒・1400 年)",
    title_ja: "信貴山 朝護孫子寺 宿坊",
    romaji: "Shigisan Chōgosonshi-ji Shukubo",
    summary_zh: "**信貴山朝護孫子寺は聖徳太子(593 年信貴山戦勝祈願)由緒の 1400 年級古刹**。毘沙門天の総本山・初代として、大寅・中寅・小寅の張子虎が名物。宿坊で朝勤行参加 + 精進料理 + 大寅トラまつり。¥10,000-15,000/泊。",
    content_md: "- 場所:生駒郡平群町信貴山\n- 文化価値:聖徳太子 593 信貴山戦勝祈願・毘沙門天総本山\n- 宿坊:複数の塔頭運営\n- 体験:朝勤行・精進料理・張子虎見学\n- 価格:¥10,000-15,000/泊(2 食付)\n- 名物:大寅・中寅・小寅の張子虎(全長 6m)\n- アクセス:近鉄信貴山下駅 + バス・JR 王寺駅 + バス",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "生駒郡",
    municipality_ja: "平群町",
    lg_code: "29342",
    area_types: ["mountain", "rural"],
    lat: 34.609,
    lon: 135.665,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.sigisan.or.jp/" },
    tags: ["shukubo_temple", "shigisan", "chogosonshi", "shotoku_taishi"],
    source: "manual",
  },
  {
    slug: "shigisan-area-lodging-guide",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "信貴山周邊 宿泊エリアガイド(王寺・三郷)",
    title_ja: "信貴山周辺 宿泊ガイド",
    romaji: "Shigisan Area Lodging Guide",
    summary_zh: "**信貴山(437m)周辺の宿泊エリア**。山中宿坊以外に、王寺・三郷町のビジネスホテル数軒。¥8,000-15,000、奈良市まで JR 25 分・大阪まで JR 30 分。法隆寺観光と組合せ可。",
    content_md: "- 場所:生駒郡三郷町・王寺町\n- 主な選択肢:王寺駅前ビジネスホテル + 三郷駅周辺\n- 価格:¥8,000-15,000\n- アクセス:JR 王寺駅 → 奈良 25 分・大阪 30 分\n- 観光線:信貴山 + 法隆寺 + 王寺町\n- 用途:奈良 + 大阪両都市観光の中継",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "生駒郡",
    municipality_ja: "三郷町",
    lg_code: "29343",
    area_types: ["small_town"],
    lat: 34.598,
    lon: 135.679,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "shigisan", "oji", "guide"],
    source: "manual",
  },
  {
    slug: "ikoma-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "生駒市 宿泊ガイド(近鉄沿線・大阪通勤圈)",
    title_ja: "生駒市 宿泊ガイド",
    romaji: "Ikoma Lodging Guide",
    summary_zh: "**生駒市は近鉄沿線の住宅都市 + 大阪通勤圏**。生駒駅前にビジネスホテル + チェーン系数軒、奈良観光より大阪・京都通勤の利便。¥7,000-13,000、生駒山宝山寺(聖天さん)観光向けにも。",
    content_md: "- 場所:生駒市・近鉄生駒駅周辺\n- 主な系列:ビジネスホテル + チェーン系\n- 価格:¥7,000-13,000\n- アクセス:近鉄生駒駅 → 大阪なんば 25 分・奈良 25 分\n- 観光:生駒山宝山寺(聖天さん)+ 生駒山上遊園地\n- 用途:大阪・奈良両都市観光中継",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "生駒市",
    lg_code: "29209",
    area_types: ["urban_local"],
    lat: 34.685,
    lon: 135.701,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "ikoma", "kintetsu_line", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 16 — 天理エリア
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "tenri-station-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "天理駅前 宿泊ガイド(山辺の道入口・天理教都)",
    title_ja: "天理駅前 宿泊ガイド",
    romaji: "Tenri Station Lodging Guide",
    summary_zh: "**天理は世界でも珍しい『宗教都市』**(天理教本部の門前町)。天理駅前にビジネスホテル数軒、巡礼者・山辺の道ハイカー向け。¥7,000-15,000、奈良市まで近鉄 30 分。",
    content_md: "- 場所:天理市川原城町・JR 天理駅 + 近鉄天理駅周辺\n- 文化価値:天理教本部の門前町(世界的宗教都市)\n- 主な系列:ビジネスホテル系\n- 価格:¥7,000-15,000\n- 用途:山辺の道ハイカー・天理教巡礼者・奈良観光\n- アクセス:近鉄天理駅 → 奈良駅 30 分・京都 1 時間",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "天理市",
    lg_code: "29204",
    area_types: ["urban_local"],
    lat: 34.586,
    lon: 135.838,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "tenri", "religious_city", "yamanobe", "guide"],
    source: "manual",
  },
  {
    slug: "tenri-kyokai-honbu-area",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "天理教本部周邊 巡禮者向け宿(独特の街並み)",
    title_ja: "天理教本部周辺 宿",
    romaji: "Tenrikyō Honbu Lodging",
    summary_zh: "**天理教本部前の街並みは世界唯一級**(教団本部 + 集会施設 + 教徒宿舎が連なる宗教都市)。巡礼者向けの宿(布教所・詰所)、一般観光客は事前確認必要。商業ホテルは天理駅前推奨。",
    content_md: "- 場所:天理市三島町・天理教本部前\n- 街並み:世界唯一級の宗教都市景観\n- 主な施設:布教所・詰所(教徒向け)\n- 一般観光:商業ホテル(天理駅前)推奨\n- 観光価値:本部・教祖殿・お地場見学(自由)\n- 注:撮影マナー注意・教団施設の規律尊重",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "天理市",
    lg_code: "29204",
    area_types: ["urban_local"],
    lat: 34.594,
    lon: 135.841,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "tenrikyo", "religious_pilgrim"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 17 — 高畑町・春日山
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "takabatake-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "高畑町 宿泊エリアガイド(奈良ホテル裏・文人ゆかりの地)",
    title_ja: "高畑町 宿泊ガイド",
    romaji: "Takabatake Lodging Guide",
    summary_zh: "**高畑町は奈良公園南部・奈良ホテル裏側の文人ゆかりの地**(志賀直哉旧居・新薬師寺)。観光客少なく静か、町家泊 + 古民家 stay 数軒、奈良ホテル予約取れない時の隠れた高級代替地。¥15,000-30,000。",
    content_md: "- 場所:奈良市高畑町・奈良ホテル裏側\n- 文化価値:志賀直哉旧居(『暗夜行路』執筆地)・新薬師寺(天平期 12 神将)\n- 雰囲気:文人ゆかりの静かな町\n- 主な宿:町家泊 + 古民家 stay 数軒\n- 価格:¥15,000-30,000\n- アクセス:近鉄奈良駅徒歩 25 分・バス便あり",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.674,
    lon: 135.842,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "takabatake", "shiga_naoya", "shin_yakushiji", "guide"],
    source: "manual",
  },
  {
    slug: "kasugayama-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "春日山原始林 周邊 宿泊エリア(自然観察向け)",
    title_ja: "春日山原始林周辺ガイド",
    romaji: "Kasugayama Lodging Guide",
    summary_zh: "**春日山原始林**(世界遺産・1000 年伐採禁止の原始的森林)周辺の宿泊エリア。月日亭等の山中料亭が宿泊化、奈良ホテル + 高畑町からアクセス可。早朝の原始林散策が独特の体験。",
    content_md: "- 場所:奈良市春日野町・春日山原始林麓\n- 文化価値:世界遺産・1000 年級伐採禁止の原始林\n- 主な宿:月日亭(数寄屋)・周辺旅館数軒\n- 価格:¥20,000-50,000\n- 体験:早朝原始林散策・夜の鹿の鳴き声\n- アクセス:バス + 徒歩・車推奨\n- 季節:4-11 月散策最盛期",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central", "mountain"],
    lat: 34.683,
    lon: 135.853,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "kasugayama", "primeval_forest", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 18 — 山小屋(大台ヶ原・大峯)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "odaigahara-yamagoya",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "大台ヶ原 山小屋(日本秘境 100 選・1695m)",
    title_ja: "大台ヶ原 山小屋",
    romaji: "Ōdaigahara Yamagoya",
    summary_zh: "**大台ヶ原(1695m)は日本最多雨地点 + 日本秘境 100 選**。山頂に山小屋(心・湯・ビジターセンター)、ハイキング 1 周 4-7 時間。¥7,000-12,000/泊(2 食付)、星空観察・原生林・神武天皇銅像。",
    content_md: "- 場所:吉野郡上北山村・大台ヶ原\n- 標高:1695m(日出ヶ岳)\n- 文化価値:日本秘境 100 選・日本最多雨地点(年 4,500mm)\n- 山小屋:心の里・大台ヶ原山の家(計 2-3 軒)\n- 価格:¥7,000-12,000/泊(2 食付)\n- 営業:4 月下-11 月下(冬季封鎖)\n- ハイキング:1 周 4-7 時間\n- アクセス:大台ヶ原ドライブウェイ(自家用車・季節バス)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "上北山村",
    lg_code: "29451",
    area_types: ["mountain", "rural"],
    lat: 34.184,
    lon: 136.099,
    season_start: "2000-04-25",
    season_end: "2000-11-30",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "odaigahara", "yamagoya", "japan_secret_100", "kamikitayama"],
    source: "manual",
  },
  {
    slug: "ominesan-yamagamigoya",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "大峯山上 山小屋(修驗道女人結界・1719m)",
    title_ja: "大峯山上 山小屋",
    romaji: "Ōminesan Yamagamigoya",
    summary_zh: "**大峯山(1719m)は修験道発祥地 + 現存唯一の女人結界**(女性入山禁止 1300 年継続)。山頂に役小角ゆかりの山上ヶ岳本堂 + 山小屋数軒、登拝期(7-9 月)のみ営業。¥6,000-10,000/泊。",
    content_md: "- 場所:吉野郡天川村・大峯山(山上ヶ岳 1719m)\n- 文化価値:修験道発祥地 + 現存唯一女人結界(1300 年継続)\n- 山小屋:山上ヶ岳の宿坊数軒\n- 価格:¥6,000-10,000/泊(精進料理付)\n- 営業:5 月初-9 月末(登拝期のみ)\n- 登拝:洞川温泉から徒歩 4-5 時間\n- 注:女性は入山禁止(山麓まで・洞川温泉)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "天川村",
    lg_code: "29446",
    area_types: ["mountain", "rural"],
    lat: 34.244,
    lon: 135.911,
    season_start: "2000-05-03",
    season_end: "2000-09-22",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "ominesan", "shugendo", "nyonin_kekkai", "tenkawa"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 19 — 大和八木・橿原・桜井
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "yamato-yagi-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "大和八木駅前 宿泊ガイド(中和の hub・近鉄交点)",
    title_ja: "大和八木駅前 宿泊ガイド",
    romaji: "Yamato Yagi Lodging Guide",
    summary_zh: "**大和八木駅は近鉄橿原線 + 大阪線の交差点 + 中和の hub**。橿原市の中心駅、明日香・橿原神宮・桜井・天理観光の起点。駅前ビジネスホテル数軒、¥7,000-15,000、京都・大阪・奈良へ近鉄で 1 時間以内。",
    content_md: "- 場所:橿原市内膳町・近鉄大和八木駅前\n- 役割:中和の交通 hub(近鉄橿原線 + 大阪線交点)\n- 主な系列:ビジネスホテル + チェーン系\n- 価格:¥7,000-15,000\n- アクセス:近鉄で 大阪 35 分・奈良 30 分・京都 1 時間\n- 観光線:明日香・橿原神宮・桜井・三輪",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "橿原市",
    lg_code: "29205",
    area_types: ["urban_local"],
    lat: 34.504,
    lon: 135.794,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "yamato_yagi", "kintetsu_hub", "kashihara", "guide"],
    source: "manual",
  },
  {
    slug: "kashihara-jingu-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "橿原神宮前 宿泊エリア(神武天皇陵 + 明日香入口)",
    title_ja: "橿原神宮前 宿泊ガイド",
    romaji: "Kashihara Jingū Lodging Guide",
    summary_zh: "**橿原神宮前駅周辺は神武天皇即位の地 + 明日香村観光の入口**。駅前にビジネスホテル + 中級ホテル、¥8,000-18,000。明日香古墳観光のレンタサイクル拠点、初詣(1/1-3)時期は予約困難。",
    content_md: "- 場所:橿原市久米町・近鉄橿原神宮前駅前\n- 文化価値:神武天皇陵 + 即位地・明日香入口\n- 主な選択肢:ビジネスホテル + 中級ホテル\n- 価格:¥8,000-18,000\n- 観光線:橿原神宮 + 明日香古墳 + 飛鳥資料館\n- アクセス:近鉄で奈良駅 50 分・大阪 50 分\n- 注:正月 1/1-3 初詣で混雑",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "橿原市",
    lg_code: "29205",
    area_types: ["urban_local"],
    lat: 34.488,
    lon: 135.789,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "kashihara_jingu", "asuka_gateway", "guide"],
    source: "manual",
  },
  {
    slug: "sakurai-station-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "桜井駅前 宿泊ガイド(三輪 + 山辺の道入口)",
    title_ja: "桜井駅前 宿泊ガイド",
    romaji: "Sakurai Lodging Guide",
    summary_zh: "**桜井駅前は三輪・山辺の道・初瀬山(長谷寺)の交通起点**。駅前ビジネスホテル + 旅館数軒、¥7,000-15,000、三輪山周辺の早朝参拝に便利。長谷寺の牡丹(4-5 月)・桜井の桜時期に推奨。",
    content_md: "- 場所:桜井市・JR / 近鉄桜井駅前\n- 観光線:三輪山(大神神社)・山辺の道・長谷寺・談山神社\n- 主な系列:ビジネスホテル + 旅館数軒\n- 価格:¥7,000-15,000\n- アクセス:JR/近鉄で 奈良 40 分・大阪 50 分・天理 15 分\n- 季節:4-5 月長谷寺牡丹・11 月談山紅葉・3 月修二会",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "桜井市",
    lg_code: "29206",
    area_types: ["urban_local"],
    lat: 34.515,
    lon: 135.842,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "sakurai", "miwa_gateway", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 20 — ゲストハウス/カプセル
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nara-guesthouse-area",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "奈良 ゲストハウス area ガイド(バックパッカー向け)",
    title_ja: "奈良ゲストハウス area",
    romaji: "Nara Guesthouse Guide",
    summary_zh: "**奈良市内のゲストハウス・ドミトリー area guide**。¥3,000-6,000/泊で泊まれる、近鉄奈良駅・JR 奈良駅周辺に分散、外国人バックパッカー人気。ならまちにも町家改装ゲストハウス数軒、共有キッチン + 多言語スタッフ + 日本人 + 外国人交流の場。",
    content_md: "- 場所:近鉄奈良駅・JR 奈良駅・ならまち\n- 価格帯:¥3,000-6,000/泊(ドミトリー)・¥6,000-10,000(個室)\n- 設備:共有キッチン・wifi・洗濯機・ロッカー\n- 言語:多言語スタッフ常駐(英・中・韓)\n- 用途:バックパッカー・短期滞在・日本人外国人交流\n- 主な系列:Khaosan World・Backpacker 系・町家改装",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.683,
    lon: 135.829,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "guesthouse", "backpacker", "guide"],
    source: "manual",
  },
  {
    slug: "nara-capsule-hostel",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "奈良 カプセルホテル area ガイド(便宜 + 駅近)",
    title_ja: "奈良カプセルホテル area",
    romaji: "Nara Capsule Hotel Guide",
    summary_zh: "**奈良はカプセル系が少ない**(京都・大阪と比較して)。JR 奈良駅近 + ならまち周辺に数軒の小規模カプセル/個室カプセル、¥3,500-7,000/泊。ビジネスホテル満室時の代替として機能。",
    content_md: "- 場所:JR 奈良駅近 + ならまち周辺\n- 軒数:小規模(数軒)\n- 価格:¥3,500-7,000/泊\n- 設備:カプセルベッド・共有大浴場・ロッカー\n- 用途:深夜到着・ビジネスホテル満室時代替\n- 注:奈良はカプセル少なめ(京都・大阪が選択肢豊富)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.681,
    lon: 135.823,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["capsule_hostel", "capsule", "budget", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 21 — 当麻寺・斑鳩追加
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "taima-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "當麻寺周邊 宿泊 area(中將姫・葛城)",
    title_ja: "當麻寺周辺 宿泊ガイド",
    romaji: "Taima Area Lodging Guide",
    summary_zh: "**葛城市當麻寺周辺の宿泊 area**。中将姫蓮糸曼荼羅伝説の寺、町並み + 二上山(双峰)ハイキングと組合せ。観光客少なく静か、町家泊 + 民宿数軒、¥10,000-22,000。中将餅本舗朝食定番。",
    content_md: "- 場所:葛城市當麻・近鉄当麻寺駅周辺\n- 観光線:當麻寺 + 中将餅本舗 + 二上山ハイキング\n- 価格:¥10,000-22,000\n- 雰囲気:観光客少なく静か\n- 主な宿:町家泊 + 民宿数軒\n- アクセス:近鉄南大阪線「当麻寺駅」徒歩 8 分\n- 季節:4-5 月中将姫の蓮 + 牡丹",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "葛城市",
    lg_code: "29211",
    area_types: ["small_town"],
    lat: 34.515,
    lon: 135.695,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "taimadera", "katsuragi", "guide"],
    source: "manual",
  },
  {
    slug: "horyuji-walking-stay",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "斑鳩 古民家泊 specific area(法隆寺早朝獨占)",
    title_ja: "斑鳩 古民家泊 ガイド",
    romaji: "Ikaruga Kominka Stay Guide",
    summary_zh: "**斑鳩町の古民家泊 specific area guide**。江戸-大正期の町家 + 武家屋敷を改装した一棟貸し、法隆寺・中宮寺・法輪寺・法起寺の世界遺産候補 4 寺すべて徒歩圏。¥18,000-40,000/棟、家族・写真愛好家・歷史好き向け。",
    content_md: "- 場所:生駒郡斑鳩町・法隆寺周辺\n- 物件:町家・武家屋敷改装の一棟貸し\n- 観光線:法隆寺・中宮寺・法輪寺・法起寺(世界遺産候補 4 寺)徒歩圏\n- 価格:¥18,000-40,000/棟(2-6 名)\n- 早朝価値:7:30 開門前の法隆寺独占\n- アクセス:JR 法隆寺駅徒歩 15 分・近鉄筒井駅 + バス",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "生駒郡",
    municipality_ja: "斑鳩町",
    lg_code: "29344",
    area_types: ["small_town"],
    lat: 34.614,
    lon: 135.738,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "ikaruga_kominka", "horyuji_morning", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 22 — 季節 specific
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "todaiji-shunie-lodging",
    category: "lodging",
    sub_type: "seasonal_lodging",
    title_zh: "東大寺 修二會(お水取)宿泊ガイド(3/1-14・1270 年連続行事)",
    title_ja: "東大寺修二会 宿泊ガイド",
    romaji: "Tōdai-ji Shunie Lodging Guide",
    summary_zh: "**東大寺二月堂修二会(お水取り)は 752 年から 1270+ 年連続の不退転行事**。3/1-14 期間、3/12 のお水取り(松明大火)が最大ピーク、夜の参拝で奈良市内ホテル満室。3 ヶ月前予約推奨。",
    content_md: "- 期間:毎年 3/1-14(本行)\n- 文化価値:752 年連続(1270+ 回)・日本最古の不退転行事\n- ピーク:3/12 お水取り(松明・夜)・3/14 達陀\n- ホテル:奈良市内満室必至\n- 予約:3 ヶ月前推奨\n- 観光:夜の二月堂松明見学(無料・19:30 頃)\n- 価格:通常期の 1.3-1.5 倍",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.689,
    lon: 135.84,
    season_start: null,
    season_end: null,
    event_start: "2000-03-01",
    event_end: "2000-03-14",
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_lodging", "shunie", "omizutori", "1270_years", "guide"],
    source: "manual",
  },
  {
    slug: "nara-yukimi-lodging",
    category: "lodging",
    sub_type: "seasonal_lodging",
    title_zh: "奈良 雪見ガイド(冬の珍しい雪景色)",
    title_ja: "奈良 雪見ガイド",
    romaji: "Nara Yukimi Guide",
    summary_zh: "**奈良市は降雪頻度低い**(年数回・1-2 月)、雪化粧の東大寺大仏殿・春日大社・若草山が稀少景観。雪降ったら緊急で奈良泊が需要急増、当日空きはほぼなし。事前予測難しく、雪雲予報を見ながら直前予約が普通。",
    content_md: "- 降雪期:1-2 月(年数回)\n- 名所:東大寺大仏殿雪景色・春日大社灯籠雪・若草山雪化粧\n- 予測:気象庁・ウェザーニュース 数日前\n- 当日予約:空き極少\n- 価格:通常期\n- 注:雪後早朝(7-9 時)が最高景・歩行注意\n- 文化価値:奈良の雪は希少美 — 観光客向け広告は少ない",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.838,
    season_start: "2000-01-01",
    season_end: "2000-02-28",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 3,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_lodging", "yukimi", "winter", "rare_scenery", "guide"],
    source: "manual",
  },
  {
    slug: "nara-tsunokiri-lodging",
    category: "lodging",
    sub_type: "seasonal_lodging",
    title_zh: "鹿の角きり時期 宿泊ガイド(10 月体育の日連休)",
    title_ja: "鹿の角きり 宿泊ガイド",
    romaji: "Nara Tsunokiri Lodging",
    summary_zh: "**毎年 10 月体育の日連休の鹿の角きり行事(1671-)期間は奈良市内宿泊予約困難**。3 日連休 + 観光客集中、ホテル価格 1.3-1.5 倍、2 ヶ月前予約推奨。",
    content_md: "- 行事:鹿の角きり(1671-・350+ 年伝統)\n- 開催:10 月体育の日連休 3 日間\n- 場所:奈良公園鹿苑\n- ホテル:満室必至\n- 価格:通常期の 1.3-1.5 倍\n- 予約:2 ヶ月前推奨\n- 観覧料:¥1,000(中学生以上)\n- 観光モデル:角きり午前 + 東大寺午後 + 春日大社夕方",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.683,
    lon: 135.836,
    season_start: null,
    season_end: null,
    event_start: "2000-10-09",
    event_end: "2000-10-11",
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["seasonal_lodging", "tsunokiri", "october", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 23 — 五條新町・葛城地区
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "gojo-shinmachi-area",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "五條新町 古い町並み 宿泊エリア",
    title_ja: "五條新町 宿泊ガイド",
    romaji: "Gojō Shinmachi Lodging Guide",
    summary_zh: "**五條市新町通りは江戸期の重要伝統的建造物群保存地区**(2010 指定)。商家町の古い町並み、町家を改装した小規模宿数軒。¥12,000-25,000/泊、奈良 + 高野山 + 吉野方面の観光中継。",
    content_md: "- 場所:五條市新町・JR 五条駅徒歩 10 分\n- 文化価値:重要伝統的建造物群保存地区(2010 指定)\n- 由緒:江戸期の商家町(吉野街道宿場)\n- 主な宿:町家改装 小規模(数軒)\n- 価格:¥12,000-25,000\n- 観光線:五條新町 + 賀名生梅林(春)+ 谷瀬の吊り橋(十津川)\n- アクセス:JR 五条駅徒歩 10 分",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "五條市",
    lg_code: "29207",
    area_types: ["small_town"],
    lat: 34.348,
    lon: 135.713,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "gojo_shinmachi", "preservation_district", "guide"],
    source: "manual",
  },
  {
    slug: "katsuragi-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "葛城市 宿泊エリア(當麻寺・葛城高原・中將姫)",
    title_ja: "葛城市 宿泊ガイド",
    romaji: "Katsuragi Lodging Guide",
    summary_zh: "**葛城市は當麻寺(中将姫)+ 葛城山ロープウェイ + 二上山ハイキング + 葛城高原ツツジ(5 月)の観光地**。当麻町・新庄町の中規模ホテル + 中将餅本舗近隣の民宿。¥8,000-18,000、近鉄南大阪線で大阪まで 40 分。",
    content_md: "- 場所:葛城市當麻町・新庄町\n- 観光線:當麻寺 + 葛城山ロープウェイ + 二上山 + 葛城高原ツツジ\n- 主な選択肢:中規模ホテル + 民宿\n- 価格:¥8,000-18,000\n- アクセス:近鉄南大阪線で大阪 40 分・奈良 50 分\n- 季節:5 月葛城高原ツツジ(白橿)・4 月當麻寺牡丹",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "葛城市",
    lg_code: "29211",
    area_types: ["urban_local", "small_town"],
    lat: 34.512,
    lon: 135.71,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["lodging_area_guide", "katsuragi", "taimadera", "tsutsuji", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 24 — 古都体験 stay
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nara-asakatsuyo-shukubo",
    category: "lodging",
    sub_type: "shukubo_temple",
    title_zh: "朝勤行體驗 stay ガイド(僧侶と同時の祈り)",
    title_ja: "朝勤行体験 stay ガイド",
    romaji: "Asagongyo Shukubo Guide",
    summary_zh: "**奈良の宿坊で僧侶と同時に朝勤行(あさごんぎょう)に参加するパッケージ**。5-6 時起床 → 本堂で読経 + 焼香 + 法話、朝食精進料理。1300 年級の修行体験を 1 泊で味わう、外国人にも英語ガイド付プラン。",
    content_md: "- 体験内容:朝 5-6 時起床 → 本堂読経 + 焼香 + 法話 → 朝食精進料理\n- 主な対応寺:東大寺周辺・薬師寺・室生寺・長谷寺・金峯山寺\n- 価格:¥10,000-18,000/泊(2 食 + 体験込)\n- 言語:英語ガイド付プラン増加(2020 年代)\n- 文化価値:1300 年級修行体験\n- 体験期:通年(行事期間以外)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.805,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["shukubo_temple", "asagongyo", "monk_experience", "english_guide", "guide"],
    source: "manual",
  },
  {
    slug: "nara-cha-kaiseki-stay",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "茶懷石泊ガイド(茶道家元・茶人向け)",
    title_ja: "茶懐石泊ガイド",
    romaji: "Cha Kaiseki Stay Guide",
    summary_zh: "**茶懐石(茶事の本格懐石)+ 朝の茶事 体験ができる宿**。月日亭・奈良ホテル等の高級宿でプランあり、茶道家元・茶人・お茶好き向け。¥30,000-80,000/泊、要事前相談。",
    content_md: "- 体験内容:茶事の本格懐石 + 朝の茶事 + 茶道入門\n- 主な対応宿:月日亭・奈良ホテル(三笠でアレンジ)・高畑町古民家\n- 価格:¥30,000-80,000/泊\n- 要事前相談・予約\n- 用途:茶道家元・茶人・お茶好き・特別記念\n- 体験時間:夕食 3 h + 朝の茶事 2 h",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.685,
    lon: 135.805,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "cha_kaiseki", "tea_ceremony", "premium", "guide"],
    source: "manual",
  },
  {
    slug: "nara-shakyo-shukubo-stay",
    category: "lodging",
    sub_type: "shukubo_temple",
    title_zh: "寫經宿坊 stay ガイド(墨筆 + 集中の 1 泊)",
    title_ja: "写経宿坊 stay ガイド",
    romaji: "Shakyō Shukubo Stay Guide",
    summary_zh: "**写経(般若心経 等を 1 文字 1 文字書写する)を 1 泊体験できる宿坊**。薬師寺・東大寺等が代表、夕方写経 → 翌朝勤行 → 般若心経朗読の組合せ。¥10,000-18,000/泊、初心者歓迎。",
    content_md: "- 体験内容:夕方 写経(2-3 h)→ 朝勤行 → 般若心経朗読\n- 主な対応寺:薬師寺(写経勧進有名)・東大寺・長谷寺\n- 価格:¥10,000-18,000/泊\n- 写経時間:1 字 1-2 分 × 262 字(般若心経)= 約 2 時間\n- 集中の効果:深い瞑想状態に至りやすい\n- 初心者歓迎(用具・指導付き)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: null,
    municipality_ja: "奈良市",
    lg_code: "29201",
    area_types: ["urban_central"],
    lat: 34.668,
    lon: 135.785,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["shukubo_temple", "shakyo", "calligraphy_meditation", "yakushiji", "guide"],
    source: "manual",
  },
  {
    slug: "nara-shugendo-1day-stay",
    category: "lodging",
    sub_type: "shukubo_temple",
    title_zh: "修驗道 1 泊體驗 stay(吉野金峯山寺・1 日修行)",
    title_ja: "修験道 1 泊体験 stay",
    romaji: "Shugendō 1-Day Experience",
    summary_zh: "**金峯山寺・洞川温泉等で行われる修験道 1 泊体験**。白衣 + 法螺貝 + 金剛杖を借りて山岳修行(滝行・断食・登山)、夕方法話 + 精進料理。¥15,000-25,000、要事前相談・健康確認。",
    content_md: "- 場所:金峯山寺(吉野)・洞川温泉(天川)\n- 体験内容:白衣装着 → 法螺貝 → 滝行(夏)/ 雪行(冬)→ 法話 → 精進\n- 価格:¥15,000-25,000/泊\n- 健康要件:山道徒歩 4-5 時間可能なこと\n- 要事前相談(数週間前)\n- 季節:夏(滝行)・冬(雪行)で体験内容異なる\n- 注:女性参加可(大峯山頂は不可)",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "吉野町",
    lg_code: "29441",
    area_types: ["mountain", "rural"],
    lat: 34.366,
    lon: 135.864,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["shukubo_temple", "shugendo_experience", "1_day_training", "yoshino", "guide"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 25 — 奈良吉野郡 山中追加
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kurotaki-yoshino",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "黒滝村 宿(吉野郡北部・林業の里)",
    title_ja: "黒滝村 宿",
    romaji: "Kurotaki Lodging",
    summary_zh: "**吉野郡黒滝村は人口 600 人弱の超小規模山村**(吉野林業の里)。道の駅吉野路黒滝 + 周辺民宿数軒、¥7,000-13,000/泊、川魚料理 + 山菜の素朴な食事。大峰山系登山口にも。",
    content_md: "- 場所:吉野郡黒滝村\n- 人口:600 人弱(超小規模)\n- 文化価値:吉野林業の里\n- 主な施設:道の駅吉野路黒滝 + 周辺民宿\n- 価格:¥7,000-13,000/泊(2 食付)\n- 食事:川魚(あまご・あゆ)・山菜・地元米\n- アクセス:近鉄下市口駅 + バス・車推奨",
    region: "kansai",
    prefecture_ja: "奈良県",
    gun_ja: "吉野郡",
    municipality_ja: "黒滝村",
    lg_code: "29444",
    area_types: ["mountain", "rural"],
    lat: 34.302,
    lon: 135.829,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "kurotaki", "yoshino", "small_village"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[nara-lodging] 尚無條目");
    return;
  }
  console.log(`[nara-lodging] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(28)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch, { onConflict: "slug" });
    if (error) {
      console.error("[nara-lodging] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[nara-lodging] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[nara-lodging] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
