// Seed 千葉県 住 R1(20 筆 / Sprint 1.3 / 第十二卷)
// 成田前 4 / 鴨川+南房総 4 / 館山 3 / 木更津 2 / disney 3 / 銚子 2 / 佐原 1 / 千葉市 1 = 20
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 成田空港前 (4)
  {
    slug: "narita-view-hotel-1973",
    category: "lodging", sub_type: "chiba_narita_hotel",
    title_zh: "成田ビューホテル(成田市・1973 創業 52+ 年・成田空港 1978 開業前から営業・国際旅行者代表立地・成田空港シャトル直結+ 成田山新勝寺 5km・¥12,000-25,000/泊・国際 SNS 成田立寄り代表・国内最古級空港前ホテル候補)",
    title_ja: "成田ビューホテル", romaji: "Narita View Hotel",
    summary_zh: "**成田ビューホテルは 1973 創業 52+ 年・成田空港 1978 開業前から営業・国内最古級空港前ホテル候補**(成田・**国際旅行者代表立地**)。¥12,000-25,000/泊、国際 SNS 成田立寄り代表。",
    content_md: "- 立地:**成田市**\n- 起源:**1973 創業 52+ 年**\n- 認定:**国内最古級空港前ホテル候補 + 成田空港 1978 開業前から営業**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "成田市", lg_code: "12211",
    area_types: ["accommodation_hotel"], lat: 35.7669, lon: 140.3192,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["narita_view", "1973", "52_years"], source: "manual",
  },
  {
    slug: "hilton-narita",
    category: "lodging", sub_type: "chiba_narita_hotel",
    title_zh: "ヒルトン成田(成田市・1990 年代開業 30+ 年+ 国際ホテルチェーン Hilton+ 成田空港シャトル直結+ 国際向け英語対応スタッフ+ R1 食 成田うなぎ参道徒歩 15 分+ ¥18,000-45,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "ヒルトン成田", romaji: "Hilton Narita",
    summary_zh: "**ヒルトン成田は 1990 年代開業 30+ 年・国際ホテルチェーン Hilton・空港シャトル直結+英語対応**(成田・**R1 食 成田うなぎ参道徒歩 15 分**)。¥18,000-45,000/泊、国際 SNS 海外旅行者代表。",
    content_md: "- 立地:**成田市**\n- 起源:**1990 年代開業 30+ 年**\n- 認定:**国際ホテルチェーン Hilton + 英語対応スタッフ**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "成田市", lg_code: "12211",
    area_types: ["accommodation_hotel"], lat: 35.7711, lon: 140.3897,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["hilton_narita"], source: "manual",
  },
  {
    slug: "ana-crowne-narita",
    category: "lodging", sub_type: "chiba_narita_hotel",
    title_zh: "ANA クラウンプラザホテル成田(成田市・1991 旧 全日空ホテル成田 開業 34+ 年+ ANA グループ国際チェーン IHG+ 成田空港シャトル直結+ 英語対応+ R1 食 成田うなぎ参道徒歩 12 分+ ¥18,000-42,000/泊・国際 SNS 国際線乗客代表)",
    title_ja: "ANA クラウンプラザ成田", romaji: "ANA Crowne Narita",
    summary_zh: "**ANA クラウンプラザホテル成田は 1991 開業 34+ 年・ANA グループ国際チェーン IHG**(成田・**空港シャトル直結+英語対応**)。¥18,000-42,000/泊、国際線乗客代表。",
    content_md: "- 立地:**成田市**\n- 起源:**1991 開業 34+ 年**\n- 認定:**ANA グループ国際チェーン IHG + 英語対応**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "成田市", lg_code: "12211",
    area_types: ["accommodation_hotel"], lat: 35.7700, lon: 140.3878,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["ana_crowne_narita", "1991"], source: "manual",
  },
  {
    slug: "richmond-hotel-narita-2005",
    category: "lodging", sub_type: "chiba_narita_hotel",
    title_zh: "リッチモンドホテル成田(成田市・2005 開業 20+ 年+ 国内中堅ビジネスチェーン リッチモンドホテルズ+ 成田駅徒歩 5 分+ R1 食 成田参道うなぎ徒歩 10 分+ ¥9,000-18,000/泊・出張 + 観光客向け中価格帯代表)",
    title_ja: "リッチモンドホテル成田", romaji: "Richmond Hotel Narita",
    summary_zh: "**リッチモンドホテル成田は 2005 開業 20+ 年・国内中堅ビジネスチェーン**(成田・**駅徒歩 5 分+R1 食 参道うなぎ徒歩 10 分**)。¥9,000-18,000/泊、出張+観光客向け中価格帯代表。",
    content_md: "- 立地:**成田市**\n- 起源:**2005 開業 20+ 年**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "成田市", lg_code: "12211",
    area_types: ["accommodation_hotel"], lat: 35.7775, lon: 140.3175,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["richmond_narita", "2005"], source: "manual",
  },

  // 鴨川+ 南房総 (4)
  {
    slug: "kamogawa-grand-1939",
    category: "lodging", sub_type: "chiba_kamogawa_onsen",
    title_zh: "鴨川グランドホテル(鴨川市・1939 創業 86+ 年+ 千葉県最古級リゾートホテル候補+ 太平洋直面前浜温泉+ R1 楽 鴨川シーワールド徒歩 10 分+ R1 食 房総なめろう+鯨料理連動・¥18,000-45,000/泊+ 1 泊 2 食付プラン代表)",
    title_ja: "鴨川グランドホテル", romaji: "Kamogawa Grand",
    summary_zh: "**鴨川グランドホテルは 1939 創業 86+ 年・千葉県最古級リゾートホテル候補・太平洋直面前浜温泉**(鴨川・**シーワールド徒歩 10 分**)。¥18,000-45,000/泊、R1 食 なめろう連動。",
    content_md: "- 立地:**鴨川市前浜**\n- 起源:**1939 創業 86+ 年**\n- 認定:**千葉県最古級リゾートホテル候補**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "鴨川市", lg_code: "12223",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 35.1131, lon: 140.1003,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["kamogawa_grand", "1939", "86_years"], source: "manual",
  },
  {
    slug: "kamogawa-seaworld-hotel",
    category: "lodging", sub_type: "chiba_kamogawa_onsen",
    title_zh: "鴨川シーワールドホテル(鴨川市・1970 年代鴨川シーワールド R1 楽 派生ホテル 50+ 年+ 太平洋直面+ R1 楽 鴨川シーワールド入園券セットプラン+ R1 食 房総なめろう連動・¥15,000-32,000/泊・国内ファミリー観光客代表)",
    title_ja: "鴨川シーワールドホテル", romaji: "Kamogawa Seaworld Hotel",
    summary_zh: "**鴨川シーワールドホテルは 1970 年代 R1 楽 派生 50+ 年・太平洋直面**(鴨川・**シーワールド入園券セット**)。¥15,000-32,000/泊、国内ファミリー観光客代表。",
    content_md: "- 立地:**鴨川市**\n- 起源:**1970 年代開業 50+ 年**\n- 関連:**R1 楽 鴨川シーワールド派生**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "鴨川市", lg_code: "12223",
    area_types: ["accommodation_hotel", "beach_coast"], lat: 35.1131, lon: 140.1003,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kamogawa_seaworld_hotel"], source: "manual",
  },
  {
    slug: "shirahama-onsen-resort",
    category: "lodging", sub_type: "chiba_minami_boso",
    title_zh: "南房総白浜温泉(南房総市白浜町・房総南端温泉郷+ 江戸期から湯治場+ 太平洋直面オーシャンビュー+ 房総白浜オーシャンリゾート+ 白浜館+ 老舗旅館 6+ 軒+ R1 食 房総ビワ+海鮮連動・¥12,000-32,000/泊)",
    title_ja: "南房総白浜温泉", romaji: "Shirahama Onsen",
    summary_zh: "**南房総白浜温泉は江戸期から湯治場・房総南端温泉郷・太平洋直面オーシャンビュー**(南房総白浜・**老舗旅館 6+ 軒**)。R1 食 房総ビワ+海鮮連動、¥12,000-32,000/泊。",
    content_md: "- 立地:**南房総市白浜町**\n- 起源:**江戸期から湯治場**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "南房総市", lg_code: "12234",
    area_types: ["onsen_natural", "beach_coast"], lat: 34.9069, lon: 139.9019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["shirahama_onsen"], source: "manual",
  },
  {
    slug: "kominato-onsen",
    category: "lodging", sub_type: "chiba_minami_boso",
    title_zh: "小湊温泉(鴨川市小湊・誕生寺(日蓮宗大本山)門前 1276 開基 750+ 年・近代温泉旅館郷 8+ 軒+ R1 育 誕生寺観光連動+ 太平洋直面+ R1 食 房総なめろう+鯨料理連動・¥10,000-28,000/泊)",
    title_ja: "小湊温泉", romaji: "Kominato Onsen",
    summary_zh: "**小湊温泉は誕生寺(日蓮宗大本山)門前 1276 開基 750+ 年・近代温泉旅館郷 8+ 軒**(鴨川小湊)。R1 育 誕生寺+R1 食 なめろう連動、¥10,000-28,000/泊。",
    content_md: "- 立地:**鴨川市小湊**\n- 起源:**誕生寺 1276 開基 750+ 年**\n- 規模:**温泉旅館郷 8+ 軒**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "鴨川市", lg_code: "12223",
    area_types: ["onsen_natural", "history_site_castle"], lat: 35.1167, lon: 140.1842,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kominato_onsen", "tanjō_ji_1276"], source: "manual",
  },

  // 館山 (3)
  {
    slug: "kyukamura-tateyama",
    category: "lodging", sub_type: "chiba_tateyama_resort",
    title_zh: "休暇村館山(館山市・1971 国民休暇村制度開設 54+ 年+ 環境省管轄国立公園公認保養施設+ 南房総国定公園内+ 太平洋直面+ R1 食 房総ビワ+海鮮連動・¥9,500-22,000/泊・1 泊 2 食付プラン代表)",
    title_ja: "休暇村館山", romaji: "Kyūkamura Tateyama",
    summary_zh: "**休暇村館山は 1971 国民休暇村開設 54+ 年・環境省管轄国立公園公認保養施設・南房総国定公園内**(館山)。R1 食 房総ビワ+海鮮連動、¥9,500-22,000/泊。",
    content_md: "- 立地:**館山市**\n- 起源:**1971 国民休暇村制度開設 54+ 年**\n- 認定:**環境省管轄国立公園公認保養施設 + 南房総国定公園内**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "館山市", lg_code: "12205",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 34.9756, lon: 139.8369,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["kyukamura_tateyama", "1971"], source: "manual",
  },
  {
    slug: "nago-funagata-onsen",
    category: "lodging", sub_type: "chiba_tateyama_resort",
    title_zh: "那古船形温泉(館山市船形・JR 那古船形駅前+ 那古寺(坂東 33 観音 33 番結願寺・行基 717 開基 1308+ 年)門前温泉郷+ R1 育 那古寺観光連動+ 太平洋館山湾景観・¥10,000-22,000/泊)",
    title_ja: "那古船形温泉", romaji: "Nago Funagata Onsen",
    summary_zh: "**那古船形温泉は那古寺(坂東 33 観音 33 番結願寺・717 開基 1308+ 年)門前温泉郷**(館山船形・**JR 那古船形駅前**)。R1 育 那古寺連動、¥10,000-22,000/泊。",
    content_md: "- 立地:**館山市船形**\n- 認定:**那古寺 = 坂東 33 観音 33 番結願寺 + 行基 717 開基 1308+ 年**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "館山市", lg_code: "12205",
    area_types: ["onsen_natural", "history_site_castle"], lat: 35.0322, lon: 139.8361,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["nago_funagata", "nagoji_717"], source: "manual",
  },
  {
    slug: "tateyama-seaside-hotel",
    category: "lodging", sub_type: "chiba_tateyama_resort",
    title_zh: "館山シーサイドリゾート群(館山市北条+船形・館山駅周辺+ 北条海岸沿+ 中堅リゾートホテル 8+ 軒+ R1 食 房総アジ干物+海鮮連動+ R1 楽 沖ノ島観光連動・¥9,500-22,000/泊・国内 SNS ファミリー観光客代表)",
    title_ja: "館山シーサイド", romaji: "Tateyama Seaside",
    summary_zh: "**館山シーサイドリゾート群は北条海岸沿+中堅リゾートホテル 8+ 軒**(館山北条+船形)。R1 食 アジ干物+R1 楽 沖ノ島連動、¥9,500-22,000/泊。",
    content_md: "- 立地:**館山市北条 + 船形**\n- 規模:**中堅リゾートホテル 8+ 軒**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "館山市", lg_code: "12205",
    area_types: ["accommodation_hotel", "beach_coast"], lat: 34.9961, lon: 139.8694,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["tateyama_seaside"], source: "manual",
  },

  // 木更津 (2)
  {
    slug: "ryugujo-mikazuki-1992",
    category: "lodging", sub_type: "chiba_kisarazu_aqua",
    title_zh: "龍宮城スパホテル三日月(木更津市・1992 開業 33+ 年+ アクアライン東端立地・東京湾オーシャンビュー+ 大規模スパ+ 6 種温泉湯+ R1 行 アクアライン+海ほたる隣接+ ¥12,000-32,000/泊・国内ファミリー観光客代表)",
    title_ja: "龍宮城スパホテル三日月", romaji: "Ryūgūjō Mikazuki",
    summary_zh: "**龍宮城スパホテル三日月は 1992 開業 33+ 年・アクアライン東端立地・東京湾ビュー・大規模スパ 6 種温泉湯**(木更津)。R1 行 アクアライン隣接、¥12,000-32,000/泊。",
    content_md: "- 立地:**木更津市**\n- 起源:**1992 開業 33+ 年**\n- 認定:**アクアライン東端立地 + 大規模スパ 6 種温泉湯**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "木更津市", lg_code: "12206",
    area_types: ["accommodation_hotel", "onsen_natural"], lat: 35.4486, lon: 139.9094,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["ryugujo_mikazuki", "1992", "33_years"], source: "manual",
  },
  {
    slug: "kisarazu-business-hotels",
    category: "lodging", sub_type: "chiba_kisarazu_aqua",
    title_zh: "木更津駅前ビジネスホテル群(木更津市・JR 木更津駅前+ アクアライン高速バス東端ターミナル+ APA・東横イン・コンフォート 等中堅ビジネスチェーン 8+ 軒+ R1 食 東京湾あさり+R1 楽 三井アウトレットパーク連動・¥6,500-12,000/泊)",
    title_ja: "木更津駅前ビジネス", romaji: "Kisarazu Business",
    summary_zh: "**木更津駅前ビジネスホテル群は JR 木更津駅前+アクアライン東端ターミナル・中堅チェーン 8+ 軒**(木更津)。R1 食 あさり+R1 楽 アウトレット連動、¥6,500-12,000/泊。",
    content_md: "- 立地:**木更津市駅前**\n- 規模:**中堅ビジネスチェーン 8+ 軒**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "木更津市", lg_code: "12206",
    area_types: ["accommodation_hotel"], lat: 35.3781, lon: 139.9156,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["kisarazu_business"], source: "manual",
  },

  // disney resort (3)
  {
    slug: "disney-mira-costa-2001",
    category: "lodging", sub_type: "chiba_disney_hotel",
    title_zh: "東京ディズニーシー・ホテルミラコスタ(浦安市舞浜・2001 開業 24+ 年+ 東京ディズニーシー直結唯一の公式ホテル+ パーク内立地+ 全国国際ファミリー旅行者代表+ ¥45,000-150,000/泊+ 1 年前予約必須・国際 SNS 海外旅行者代表)",
    title_ja: "ホテルミラコスタ", romaji: "Hotel MiraCosta",
    summary_zh: "**東京ディズニーシー・ホテルミラコスタは 2001 開業 24+ 年・パーク内立地+ 直結唯一公式ホテル**(浦安舞浜・**国際ファミリー代表**)。¥45,000-150,000/泊、1 年前予約必須。",
    content_md: "- 立地:**浦安市舞浜**\n- 起源:**2001 開業 24+ 年**\n- 認定:**東京ディズニーシー直結唯一公式ホテル + パーク内立地**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "浦安市", lg_code: "12227",
    area_types: ["accommodation_hotel"], lat: 35.6256, lon: 139.8847,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 365, closed_days: [],
    external_urls: {}, tags: ["miracosta", "2001"], source: "manual",
  },
  {
    slug: "disneyland-hotel-2008",
    category: "lodging", sub_type: "chiba_disney_hotel",
    title_zh: "東京ディズニーランドホテル(浦安市舞浜・2008 開業 17+ 年+ 東京ディズニーランド真正面立地+ ヴィクトリア朝建築・全国国際ファミリー観光客代表+ ¥40,000-120,000/泊+ 半年前予約必須・国際 SNS 海外旅行者代表)",
    title_ja: "東京ディズニーランドホテル", romaji: "Disneyland Hotel",
    summary_zh: "**東京ディズニーランドホテルは 2008 開業 17+ 年・パーク真正面立地・ヴィクトリア朝建築**(浦安舞浜・**国際ファミリー代表**)。¥40,000-120,000/泊、半年前予約必須。",
    content_md: "- 立地:**浦安市舞浜**\n- 起源:**2008 開業 17+ 年**\n- 認定:**東京ディズニーランド真正面 + ヴィクトリア朝建築**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "浦安市", lg_code: "12227",
    area_types: ["accommodation_hotel"], lat: 35.6342, lon: 139.8819,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 180, closed_days: [],
    external_urls: {}, tags: ["disneyland_hotel", "2008"], source: "manual",
  },
  {
    slug: "hilton-tokyo-bay-1988",
    category: "lodging", sub_type: "chiba_disney_hotel",
    title_zh: "ヒルトン東京ベイ(浦安市舞浜・1988 開業 37+ 年+ 国際ホテルチェーン Hilton+ ディズニーリゾート公式パートナーホテル+ パーク間モノレール接続+ 国際向け英語対応+ ¥22,000-65,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "ヒルトン東京ベイ", romaji: "Hilton Tokyo Bay",
    summary_zh: "**ヒルトン東京ベイは 1988 開業 37+ 年・国際チェーン Hilton・ディズニーリゾート公式パートナー**(浦安舞浜・**英語対応**)。¥22,000-65,000/泊、国際 SNS 海外旅行者代表。",
    content_md: "- 立地:**浦安市舞浜**\n- 起源:**1988 開業 37+ 年**\n- 認定:**国際チェーン Hilton + ディズニーリゾート公式パートナー**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "浦安市", lg_code: "12227",
    area_types: ["accommodation_hotel"], lat: 35.6328, lon: 139.8836,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["hilton_tokyo_bay", "1988"], source: "manual",
  },

  // 銚子 (2)
  {
    slug: "inubo-kanko-hotel",
    category: "lodging", sub_type: "chiba_choshi_inubo",
    title_zh: "犬吠埼観光ホテル(銚子市犬吠埼・大正期 1923 創業 102+ 年+ 千葉県内最古級観光ホテル候補+ 太平洋直面+ 犬吠埼灯台 1874 隣接 R1 育・初日の出スポット+ ¥18,000-42,000/泊+ 1 月予約困難)",
    title_ja: "犬吠埼観光ホテル", romaji: "Inubō Kankō Hotel",
    summary_zh: "**犬吠埼観光ホテルは大正期 1923 創業 102+ 年・千葉県内最古級観光ホテル候補・太平洋直面・犬吠埼灯台 1874 隣接**(銚子)。初日の出スポット、¥18,000-42,000/泊、1 月予約困難。",
    content_md: "- 立地:**銚子市犬吠埼**\n- 起源:**大正期 1923 創業 102+ 年**\n- 認定:**千葉県内最古級観光ホテル候補 + 犬吠埼灯台 1874 隣接**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "銚子市", lg_code: "12202",
    area_types: ["accommodation_hotel", "beach_coast"], lat: 35.7081, lon: 140.8678,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["inubo_kanko", "1923", "102_years"], source: "manual",
  },
  {
    slug: "choshi-business-hotels",
    category: "lodging", sub_type: "chiba_choshi_inubo",
    title_zh: "銚子駅前ビジネスホテル群(銚子市・JR 銚子駅前+ 銚子電鉄起点+ APA・東横イン等中堅チェーン 6+ 軒+ R1 食 銚子港+ヤマサ醤油+R1 行 銚子電鉄+ R1 育 犬吠埼観光連動・¥6,500-12,000/泊)",
    title_ja: "銚子駅前ビジネス", romaji: "Chōshi Business",
    summary_zh: "**銚子駅前ビジネスホテル群は JR 銚子駅前+銚子電鉄起点・中堅チェーン 6+ 軒**(銚子)。R1 食 銚子港+ヤマサ+R1 行 銚子電鉄連動、¥6,500-12,000/泊。",
    content_md: "- 立地:**銚子市駅前**\n- 規模:**中堅ビジネスチェーン 6+ 軒**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "銚子市", lg_code: "12202",
    area_types: ["accommodation_hotel"], lat: 35.7344, lon: 140.8264,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["choshi_business"], source: "manual",
  },

  // 佐原 (1)
  {
    slug: "nipponia-sawara",
    category: "lodging", sub_type: "chiba_sawara_water",
    title_zh: "NIPPONIA SAWARA 商家町ホテル(香取市佐原・1900 年代古民家 + 商家リノベ・佐原伝統的建造物群保存地区(国選定 1996)内・小江戸佐原・伊能忠敬旧宅+ 北総の小江戸町並み+ R1 育 佐原観光中核・¥22,000-45,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "NIPPONIA SAWARA", romaji: "Nipponia Sawara",
    summary_zh: "**NIPPONIA SAWARA 商家町ホテルは佐原伝統的建造物群保存地区(国選定 1996)内古民家リノベ**(佐原小江戸・**伊能忠敬旧宅 + 北総の小江戸**)。¥22,000-45,000/泊、海外旅行者代表。",
    content_md: "- 立地:**香取市佐原**\n- 認定:**佐原伝統的建造物群保存地区 = 国選定 1996**\n- 関連:**伊能忠敬旧宅 + 北総の小江戸**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "香取市", lg_code: "12236",
    area_types: ["accommodation_ryokan", "history_site_castle"], lat: 35.8983, lon: 140.5053,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["nipponia_sawara", "1996_designation"], source: "manual",
  },

  // 千葉市 (1)
  {
    slug: "new-otani-makuhari-1993",
    category: "lodging", sub_type: "chiba_chiba_city",
    title_zh: "ホテルニューオータニ幕張(千葉市美浜区・1993 開業 32+ 年+ 国内大手ホテルチェーン ニューオータニ・幕張メッセ隣接+ 幕張新都心+ JR 海浜幕張駅徒歩 5 分+ R1 楽 幕張メッセ+ ZOZO マリンスタジアム連動・¥18,000-45,000/泊・国際 SNS ビジネス + コンサート観光代表)",
    title_ja: "ニューオータニ幕張", romaji: "New Otani Makuhari",
    summary_zh: "**ホテルニューオータニ幕張は 1993 開業 32+ 年・国内大手チェーン+幕張メッセ隣接+JR 海浜幕張駅徒歩 5 分**(千葉美浜)。R1 楽 幕張メッセ+ZOZO マリン連動、¥18,000-45,000/泊。",
    content_md: "- 立地:**千葉市美浜区幕張**\n- 起源:**1993 開業 32+ 年**\n- 認定:**国内大手チェーン ニューオータニ + 幕張メッセ隣接**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["accommodation_hotel"], lat: 35.6481, lon: 140.0356,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["new_otani_makuhari", "1993", "32_years"], source: "manual",
  },
];

seedMain(rows, "chiba-lodging-r1");
