// Seed 京都府 · 楽類 條目 → public.japan_entries(Sprint 14.7)
//
// 京都の娯楽は四季 + 文化体験中心。8 phase で ~50 entries:
//   Phase 1 — 桜の名所(花見)
//   Phase 2 — 紅葉の名所
//   Phase 3 — 花火大会
//   Phase 4 — Illumination + 夜景
//   Phase 5 — 動物園・水族館・遊園
//   Phase 6 — スポーツ観戦
//   Phase 7 — 劇場・ホール・音楽祭
//   Phase 8 — 季節 + 子供向 + 体験

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "sakura"
  | "momiji"
  | "firework_festival"
  | "fireworks_small"
  | "illumination"
  | "flower_field"
  | "aquarium_zoo"
  | "theme_park"
  | "music_festival"
  | "sports_spectate"
  | "ski_season"
  | "ancient_festival";

interface SeedRow {
  slug: string;
  category: "entertainment";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "kansai";
  prefecture_ja: "京都府";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // Phase 1 — 桜の名所(花見)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-sakura-best-5-guide",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "京都桜ベスト 5 ガイド",
    title_ja: "京都桜ベスト 5 ガイド",
    romaji: "Kyoto Sakura Top 5 Guide",
    summary_zh: "**京都の桜名所ベスト 5(主観 + 観光客評価)**:1. 醍醐寺(秀吉花見)・2. 円山公園しだれ・3. 哲学の道・4. 嵐山渡月橋・5. 仁和寺御室桜。3 月下旬-4 月上旬の見頃、各スポットで時間差(早咲・遅咲)あり、1 週間で全部回れる。",
    content_md: "- 1. 醍醐寺(3 月下旬-4 月初旬・桜 1,000 本・秀吉花見)\n- 2. 円山公園(4 月初旬・しだれ桜)\n- 3. 哲学の道(4 月初旬・桜並木 2 km)\n- 4. 嵐山渡月橋(4 月初旬・嵐山借景)\n- 5. 仁和寺御室桜(4 月中旬・遅咲き)\n- 観覧料:醍醐寺 ¥1,500・他無料",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: "2000-03-25",
    season_end: "2000-04-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura_best_5", "april", "guide"],
    source: "manual",
  },
  {
    slug: "kyoto-gosho-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "京都御苑 桜",
    title_ja: "京都御苑 桜",
    romaji: "Kyoto Gosho Sakura",
    summary_zh: "**京都御苑(京都御所周囲の公園)** の桜、3 月下旬-4 月中旬、**しだれ桜・山桜・八重桜 等 30 種 1,000 本+**。広大な敷地で人混雑分散、ピクニック向き。観覧無料、24 時間自由。",
    content_md: "- 範囲:京都御苑(京都御所周囲)\n- 期間:3 月下旬-4 月中旬\n- 桜種:30 種 1,000+ 本(しだれ・山桜・八重桜)\n- 観覧:24 時間自由・無料\n- 特色:広大で混雑分散・ピクニック可\n- アクセス:地下鉄烏丸線「丸太町」「今出川」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.025,
    lon: 135.762,
    season_start: "2000-03-25",
    season_end: "2000-04-15",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["gosho_sakura", "30_varieties", "picnic_friendly"],
    source: "manual",
  },
  {
    slug: "kyoto-yawata-sewaridutsumi",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "八幡背割堤 桜並木",
    title_ja: "背割堤桜並木",
    romaji: "Yawata Sewari-Dutsumi",
    summary_zh: "**八幡市の桂川 + 宇治川合流点の堤防の桜トンネル**、約 1.4 km。**ソメイヨシノ 220 本**が川風に揺れる絶景、4 月初旬がピーク。京阪「八幡市」徒歩 10 分、京都郊の隠れた桜名所、混雑も都心ほどではない。",
    content_md: "- 場所:八幡市八幡(桂川 + 宇治川合流点)\n- 規模:全長 1.4 km・ソメイヨシノ 220 本\n- 期間:4 月初旬\n- 観覧:無料\n- 名物:桜トンネル・川風\n- アクセス:京阪「八幡市」徒歩 10 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "八幡市",
    lg_code: "26210",
    area_types: ["urban_central"],
    lat: 34.879,
    lon: 135.7,
    season_start: "2000-04-01",
    season_end: "2000-04-10",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sewari_dutsumi", "yawata", "1_4_km_sakura", "uji_river"],
    source: "manual",
  },
  {
    slug: "kyoto-kiyamachi-yozakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "木屋町 高瀬川 夜桜",
    title_ja: "木屋町 高瀬川 夜桜",
    romaji: "Kiyamachi Yozakura",
    summary_zh: "**木屋町通の高瀬川沿い夜桜**、中京区四条 ↔ 三条の徒歩約 700 m。**川沿いの提灯 + 桜並木 + 京町家**の組合せ景観、夜の散策に最適。先斗町並列で京都の夜桜散策コース。",
    content_md: "- 範囲:木屋町通(四条 ↔ 三条 約 700 m)\n- 期間:3 月末-4 月初旬\n- 観覧:無料\n- 名物:高瀬川 + 桜 + 提灯・京町家\n- 散策ペア:先斗町・三条河原町\n- アクセス:京阪「祇園四条」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0058,
    lon: 135.77,
    season_start: "2000-03-25",
    season_end: "2000-04-10",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kiyamachi", "yozakura", "takasegawa_sakura", "night_walk"],
    source: "manual",
  },
  {
    slug: "kyoto-kamogawa-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "鴨川桜並木",
    title_ja: "鴨川 桜並木",
    romaji: "Kamogawa Sakura",
    summary_zh: "**鴨川河岸の桜並木**、出町柳 ↔ 三条 約 3 km。**ソメイヨシノ + しだれ桜**の混在、河川敷でピクニック・ジョギング・写真撮影 OK。京都市民が最も愛する身近な桜スポット、混雑度中庸。",
    content_md: "- 範囲:鴨川河岸(出町柳 ↔ 三条 約 3 km)\n- 期間:3 月末-4 月初旬\n- 観覧:無料・河川敷自由\n- 名物:桜並木・ピクニック・夜桜散歩\n- 特色:京都市民最愛・混雑緩和\n- アクセス:京阪沿線各駅",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.012,
    lon: 135.772,
    season_start: "2000-03-25",
    season_end: "2000-04-10",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kamogawa_sakura", "3_km", "picnic_friendly", "moderate_crowd"],
    source: "manual",
  },
  {
    slug: "kyoto-daigo-yozakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "醍醐寺 夜桜ライトアップ",
    title_ja: "醍醐寺 夜桜",
    romaji: "Daigo Yozakura",
    summary_zh: "**醍醐寺の夜桜ライトアップ(3 月下旬-4 月初旬)**、伏見区醍醐。**1,000 本の桜**(秀吉「醍醐の花見」の地)が幻想的に浮上、三宝院庭園 + 五重塔 + 桜の組合せ。¥1,500 で夜間特別拝観。",
    content_md: "- 期間:3 月下旬-4 月初旬\n- 時間:18:00-21:00\n- 拝観料:¥1,500(夜間特別)\n- 名物:桜 1,000 本ライトアップ・五重塔・三宝院庭園\n- 関連:豊臣秀吉「醍醐の花見」\n- アクセス:地下鉄東西線「醍醐」徒歩 10 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9518,
    lon: 135.8195,
    season_start: "2000-03-25",
    season_end: "2000-04-10",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["daigo_yozakura", "1000_sakura", "hideyoshi_hanami", "night_lightup"],
    source: "manual",
  },
  {
    slug: "kyoto-nijo-jo-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "二条城 桜ライトアップ",
    title_ja: "二条城 桜",
    romaji: "Nijo Jo Sakura",
    summary_zh: "**世界遺産二条城の春の桜 + ライトアップ**、3 月下旬-4 月中旬。**約 50 種 300 本**の桜(早咲き-遅咲き)で長期間楽しめる、夜のライトアップは ¥1,300、二の丸庭園と桜の組合せが幻想的。",
    content_md: "- 期間:3 月下旬-4 月中旬\n- 入場:8:45-17:00 / 夜間 18:00-21:00\n- 入城料:¥1,300(夜間ライトアップ別 ¥600)\n- 名物:50 種 300 本桜・夜間ライトアップ\n- 関連:世界遺産・徳川家康築城\n- アクセス:地下鉄東西線「二条城前」徒歩 1 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0142,
    lon: 135.7481,
    season_start: "2000-03-25",
    season_end: "2000-04-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["nijo_sakura", "50_varieties", "world_heritage", "night_lightup"],
    source: "manual",
  },
  {
    slug: "kyoto-keage-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "蹴上インクライン桜",
    title_ja: "蹴上インクライン 桜",
    romaji: "Keage Incline Sakura",
    summary_zh: "**蹴上インクライン廃線跡の桜**、左京区南禅寺。1891 年の廃線レール上を桜並木が覆う独特の風景、SNS 写真鉄板スポット。3 月末-4 月初旬、観覧無料、夜は街灯のみ。",
    content_md: "- 範囲:蹴上インクライン廃線跡 約 580 m\n- 期間:3 月末-4 月初旬\n- 観覧:24 時間自由・無料\n- 名物:廃線レール + 桜並木・SNS 写真聖地\n- 関連:Phase 17 育(産業遺産)\n- アクセス:地下鉄東西線「蹴上」徒歩 3 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.011,
    lon: 135.79,
    season_start: "2000-03-25",
    season_end: "2000-04-10",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["keage_sakura", "abandoned_rail", "instagram", "free"],
    source: "manual",
  },
  {
    slug: "kyoto-omuro-zakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "仁和寺 御室桜(遅咲き)",
    title_ja: "仁和寺 御室桜",
    romaji: "Ninnaji Omuro Zakura",
    summary_zh: "**仁和寺の御室桜(4 月中旬・京都最遅咲き)**、右京区。**約 200 本のオムロアリアケザクラ**(背丈の低い桜)、京都他所の桜終盤に楽しめる遅咲きの名所、世界遺産の境内で見もの。",
    content_md: "- 期間:4 月中旬-下旬(京都最遅)\n- 拝観:9:00-17:00\n- 拝観料:伽藍 ¥800\n- 名物:御室桜 200 本(背低・低樹の桜)\n- 文化:世界遺産境内\n- アクセス:嵐電「御室仁和寺」徒歩 3 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0312,
    lon: 135.7138,
    season_start: "2000-04-10",
    season_end: "2000-04-25",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["omuro_zakura", "late_bloom", "world_heritage", "200_trees"],
    source: "manual",
  },
  {
    slug: "kyoto-sakura-calendar",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "京都桜開花予測カレンダー",
    title_ja: "京都桜開花予測",
    romaji: "Kyoto Sakura Forecast",
    summary_zh: "**京都の桜開花予測ガイド**:**3 月下旬開花 → 4 月初旬満開 → 4 月中旬遅咲(御室桜)**。tenki.jp + 日本気象協会の予測 + 京都市観光協会の咲き具合情報を活用、年により 1 週間前後変動。",
    content_md: "- 開花:3 月下旬(早咲・河津桜・寒緋桜)\n- ソメイヨシノ満開:4 月初旬-中旬\n- 遅咲(御室桜):4 月中旬-下旬\n- 予測サイト:tenki.jp・日本気象協会・京都市観光協会\n- 注:年により 1 週間前後変動\n- 桜時期 1 週間でほぼ全京都を回れる",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: "2000-03-20",
    season_end: "2000-04-25",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura_forecast", "calendar", "tenki_jp"],
    source: "manual",
  },
  // ════════════════════════════════════════════════════════════════════
  // Phase 2 — 紅葉の名所(楽 視点)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-momiji-best-5-guide",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "京都紅葉ベスト 5 ガイド",
    title_ja: "京都紅葉ベスト 5",
    romaji: "Kyoto Momiji Top 5",
    summary_zh: "**京都紅葉ベスト 5**:1. 東福寺通天橋(2,000 本)・2. 永観堂(3,000 本)・3. 嵐山天龍寺・4. 真如堂・5. 高雄三尾。11 月中旬-下旬がピーク、各所で時間差。早朝 7-9 時で混雑回避。",
    content_md: "- 1. 東福寺通天橋(2,000 本)\n- 2. 永観堂(3,000 本・夜間ライトアップ)\n- 3. 嵐山天龍寺(嵐山借景)\n- 4. 真如堂(三重塔 + 紅葉)\n- 5. 高雄三尾(神護寺・西明寺・高山寺)\n- ピーク:11 月中旬-下旬\n- 観覧:寺社別 ¥500-1,000",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: "2000-11-15",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["momiji_best_5", "november", "guide"],
    source: "manual",
  },
  {
    slug: "kyoto-momiji-calendar",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "京都紅葉時期予測カレンダー",
    title_ja: "京都紅葉予測",
    romaji: "Kyoto Momiji Forecast",
    summary_zh: "**京都紅葉時期予測**:**10 月末色付き始め → 11 月中旬-下旬ピーク → 12 月初旬終盤**。山間部(高雄・大原・鞍馬)が早く色付き、京都市内中心部が遅い。年により 1 週間前後変動。",
    content_md: "- 色付き始め:10 月末(山間部)\n- 中旬-下旬:京都市内ピーク\n- 12 月初旬:終盤\n- 山間部 vs 市内:1-2 週間差\n- 予測サイト:tenki.jp・日本気象協会\n- 観覧モデル:11 月 20-30 日が黄金週",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: "2000-10-25",
    season_end: "2000-12-10",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["momiji_forecast", "calendar", "10_2_weeks_diff"],
    source: "manual",
  },
  {
    slug: "kyoto-arashiyama-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "嵐山紅葉エリア",
    title_ja: "嵐山 紅葉",
    romaji: "Arashiyama Momiji",
    summary_zh: "**嵐山の紅葉(11 月中旬-下旬)**、右京区嵐山。**渡月橋 + 嵐山借景 + 大堰川 + 天龍寺 + 常寂光寺**等のセット観光。京都西部紅葉の代表、観光客密集も京都ピークの一つ。",
    content_md: "- 期間:11 月中旬-下旬\n- 主要スポット:渡月橋・天龍寺・常寂光寺・宝筐院\n- 観光モデル:朝 8-10 時が混雑前\n- 関連:嵯峨野竹林・嵐山温泉\n- アクセス:JR「嵯峨嵐山」徒歩 5 分・嵐電「嵐山」即着",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0145,
    lon: 135.6776,
    season_start: "2000-11-15",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["arashiyama_momiji", "togetsukyo", "tenryu_ji", "western_kyoto"],
    source: "manual",
  },
  {
    slug: "kyoto-ohara-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "大原紅葉",
    title_ja: "大原 紅葉",
    romaji: "Ohara Momiji",
    summary_zh: "**大原の紅葉(11 月中旬-下旬)**、左京区大原。**三千院 + 寂光院 + 宝泉院 + 実光院**の塔頭群が苔庭 + 紅葉で見事、観光客密度低めで静寂を楽しめる。京都郊紅葉の隠れスポット。",
    content_md: "- 期間:11 月中旬-下旬\n- 主要寺院:三千院・寂光院・宝泉院・実光院\n- 観光客:京都市内中心部より少なめ\n- 関連:大原女文化\n- アクセス:京都バス「大原」(60 分・¥570)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.115,
    lon: 135.834,
    season_start: "2000-11-15",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ohara_momiji", "sanzen_in", "less_crowded"],
    source: "manual",
  },
  {
    slug: "kyoto-takao-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "高雄三尾紅葉",
    title_ja: "高雄三尾 紅葉",
    romaji: "Takao Sanbi Momiji",
    summary_zh: "**高雄(三尾:神護寺・西明寺・高山寺)の紅葉(11 月初-中旬・京都最早)**、右京区梅ヶ畑。京都の紅葉名所で最も早く色付き、神護寺の急な石段参道 + 紅葉が圧巻。観光客アクセス難で混雑緩和。",
    content_md: "- 期間:11 月初旬-中旬(京都最早)\n- 主要寺院:神護寺・西明寺・高山寺\n- アクセス:JR バス「高雄」徒歩 20 分\n- 観光客:アクセス難で京都市内より少なめ\n- 関連:Phase 17 育・もみじ家本館",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.069,
    lon: 135.668,
    season_start: "2000-11-01",
    season_end: "2000-11-25",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["takao_momiji", "early_bloom", "jingo_ji_steps"],
    source: "manual",
  },
  {
    slug: "kyoto-tofukuji-tsutenkyo-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "東福寺通天橋紅葉",
    title_ja: "東福寺 通天橋 紅葉",
    romaji: "Tofukuji Tsutenkyo Momiji",
    summary_zh: "**東福寺通天橋からの紅葉(11 月中旬-下旬)**、東山区。**もみじ 2,000 本** が眼下に広がる「紅葉の海」、京都紅葉名所の頂点。観覧客最大級で混雑、平日 + 朝 8-9 時推奨。",
    content_md: "- 期間:11 月中旬-下旬\n- 規模:もみじ 2,000 本\n- 拝観:9:00-16:30(11 月 8:30-)\n- 拝観料:通天橋 ¥1,000(11 月)\n- 注:京都紅葉最大混雑・平日朝推奨\n- アクセス:JR/京阪「東福寺」徒歩 8 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9764,
    lon: 135.7741,
    season_start: "2000-11-15",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["tsutenkyo_momiji", "2000_maples", "max_crowded", "kyoto_pinnacle"],
    source: "manual",
  },
  // ════════════════════════════════════════════════════════════════════
  // Phase 3 — 花火大会
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-uji-kawa-fireworks",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "宇治川花火大会",
    title_ja: "宇治川花火大会",
    romaji: "Ujikawa Hanabi Taikai",
    summary_zh: "**宇治市の宇治川での夏花火大会**、毎年 8 月初旬-中旬の夕方-夜。**約 7,000 発の花火**(京都府最大級)、宇治川対岸の平等院 + 平等院鳳凰堂を背景に幻想的。",
    content_md: "- 開催:8 月初旬-中旬(年により変動)\n- 場所:宇治川河川敷\n- 規模:約 7,000 発\n- 観覧:宇治川河岸 無料\n- 名物:平等院夜景 + 花火\n- アクセス:JR/京阪「宇治」徒歩 10 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "宇治市",
    lg_code: "26204",
    area_types: ["urban_central"],
    lat: 34.8896,
    lon: 135.8076,
    season_start: "2000-08-01",
    season_end: "2000-08-15",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ujikawa_hanabi", "7000_fireworks", "byodo_in_view", "august"],
    source: "manual",
  },
  {
    slug: "kyoto-maizuru-fireworks",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "舞鶴花火大会(海上花火)",
    title_ja: "舞鶴花火大会",
    romaji: "Maizuru Hanabi",
    summary_zh: "**舞鶴湾の海上花火大会**、毎年 8 月開催。**約 5,000 発**、海上 + 山並み + 海軍港を背景に演出。京都府北部の夏祭り代表。",
    content_md: "- 開催:8 月(年により変動)\n- 場所:舞鶴湾\n- 規模:約 5,000 発\n- 観覧:舞鶴港・赤レンガパーク 無料\n- 名物:海上花火・海軍港背景\n- アクセス:JR「東舞鶴」徒歩 15 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "舞鶴市",
    lg_code: "26202",
    area_types: ["urban_central"],
    lat: 35.4795,
    lon: 135.388,
    season_start: "2000-08-01",
    season_end: "2000-08-31",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["maizuru_hanabi", "5000_fireworks", "naval_port", "summer"],
    source: "manual",
  },
  {
    slug: "kyoto-amanohashidate-fireworks",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "天橋立花火大会",
    title_ja: "天橋立花火大会",
    romaji: "Amanohashidate Hanabi",
    summary_zh: "**日本三景天橋立の海上花火大会**、毎年 7-8 月。**約 3,000 発**、宮津湾 + 松林 + 天橋立の砂州を背景に。京都北部夏の風物詩、観光客 + 地元客で賑わう。",
    content_md: "- 開催:7-8 月(年により変動)\n- 場所:宮津湾(天橋立)\n- 規模:約 3,000 発\n- 観覧:宮津湾岸 無料\n- 名物:日本三景 + 海上花火\n- アクセス:京都丹後鉄道「天橋立」徒歩 10 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "宮津市",
    lg_code: "26205",
    area_types: ["coastal"],
    lat: 35.5563,
    lon: 135.193,
    season_start: "2000-07-15",
    season_end: "2000-08-15",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["amanohashidate_hanabi", "3000_fireworks", "japan_three_views"],
    source: "manual",
  },
  {
    slug: "kyoto-kameoka-heiwa-hanabi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "亀岡平和祭保津川市民花火大会",
    title_ja: "亀岡平和祭花火",
    romaji: "Kameoka Heiwa Sai Hanabi",
    summary_zh: "**亀岡市の保津川市民花火大会**、毎年 8 月 7 日(終戦記念日関連)。**約 7,000 発**(京都府最大級)、保津川堤防から打ち上げ、京都市内から JR で 30 分のアクセス便利な大型花火。",
    content_md: "- 開催:8 月 7 日(平和祭)\n- 場所:亀岡市保津川河川敷\n- 規模:約 7,000 発\n- 観覧:有料席(¥3,000)+ 無料堤防\n- アクセス:JR「亀岡」徒歩 10 分(京都駅から 30 分)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "亀岡市",
    lg_code: "26206",
    area_types: ["urban_central"],
    lat: 35.012,
    lon: 135.547,
    season_start: "2000-08-07",
    season_end: "2000-08-07",
    event_start: "2000-08-07",
    event_end: "2000-08-07",
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["kameoka_hanabi", "august_7", "7000_fireworks", "peace_day"],
    source: "manual",
  },
  {
    slug: "kyoto-yawata-hanabi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "八幡背割堤花火",
    title_ja: "八幡背割堤花火",
    romaji: "Yawata Sewari-Dutsumi Hanabi",
    summary_zh: "**八幡市の桂川 + 宇治川合流地での夏花火**、毎年 7-8 月。背割堤の桜並木地区で、川面に映る花火が美しい。京都南部の地域型花火大会、観光客より地元客中心。",
    content_md: "- 開催:7-8 月(年により変動)\n- 場所:八幡市背割堤(桜並木地区)\n- 観覧:堤防 無料\n- 名物:川面 + 花火・地元色強い\n- アクセス:京阪「八幡市」徒歩 10 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "八幡市",
    lg_code: "26210",
    area_types: ["urban_central"],
    lat: 34.879,
    lon: 135.7,
    season_start: "2000-07-15",
    season_end: "2000-08-15",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yawata_hanabi", "sewari_dutsumi", "local_festival"],
    source: "manual",
  },
  // ════════════════════════════════════════════════════════════════════
  // Phase 4 — Illumination + 夜景
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-arashiyama-hanatouro-history",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "嵐山花灯路(終了:2005-2021 歴史)",
    title_ja: "嵐山花灯路",
    romaji: "Arashiyama Hanatoro",
    summary_zh: "**2005-2021 年の冬の嵐山ライトアップ祭**、京都を代表した夜のイベント。**渡月橋 + 竹林 + 周辺寺院ライトアップ**で京都冬の鉄板観光だったが 2021 年で終了。代替として大覚寺・天龍寺の冬期特別ライトアップが部分継承。",
    content_md: "- 期間:2005-2021 年(終了)\n- 場所:嵐山一帯\n- 名物:竹林ライトアップ・渡月橋・嵐山寺院\n- 終了理由:京都市の予算 + コロナ\n- 代替:天龍寺・宝厳院 冬期ライト\n- 注:過去の風物詩として記録",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0145,
    lon: 135.6776,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["arashiyama_hanatoro", "2005_2021", "winter_lightup", "discontinued"],
    source: "manual",
  },
  {
    slug: "kyoto-higashiyama-hanatouro-history",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "東山花灯路(終了:2003-2022 歴史)",
    title_ja: "東山花灯路",
    romaji: "Higashiyama Hanatoro",
    summary_zh: "**2003-2022 年の春の東山ライトアップ祭**、清水寺・八坂神社・知恩院・青蓮院 等を含む東山一帯。**3 月初旬-中旬の 10 日間**、夜の散策イベントとして京都春観光の代表だったが 2022 年で終了。",
    content_md: "- 期間:2003-2022 年(終了)\n- 場所:東山一帯(清水寺-知恩院)\n- 開催月:3 月初旬-中旬 10 日\n- 名物:夜の東山散策・寺院ライトアップ・茶会\n- 終了理由:京都市予算 + コロナ\n- 代替:各寺院個別ライト",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["higashiyama_hanatoro", "2003_2022", "march_lightup", "discontinued"],
    source: "manual",
  },
  {
    slug: "kyoto-nijo-jo-aki-lightup",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "二条城 秋ライトアップ",
    title_ja: "二条城 秋季ライトアップ",
    romaji: "Nijo-jo Autumn Lightup",
    summary_zh: "**世界遺産二条城の秋夜間ライトアップ**、10 月下旬-12 月初旬。**二の丸庭園 + 紅葉 + プロジェクションマッピング** が新世代のライトアップ体験、京都秋の代表夜イベントの一つ。",
    content_md: "- 期間:10 月下旬-12 月初旬\n- 時間:18:00-21:00\n- 入城料:¥600(夜間別)\n- 名物:二の丸庭園・紅葉・プロジェクションマッピング\n- 関連:世界遺産二条城\n- アクセス:地下鉄東西線「二条城前」徒歩 1 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0142,
    lon: 135.7481,
    season_start: "2000-10-25",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["nijo_jo_aki", "world_heritage", "projection_mapping", "autumn_night"],
    source: "manual",
  },
  {
    slug: "kyoto-kiyomizu-night-lightup",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "清水寺 夜間特別拝観",
    title_ja: "清水寺 夜間特別拝観",
    romaji: "Kiyomizudera Night Lightup",
    summary_zh: "**清水寺の春・夏・秋の夜間特別拝観**、京都最古の寺院ライトアップ(1985-)。**清水の舞台 + 桜・新緑・紅葉**を夜間照明で幻想的に。世界遺産境内で開催する希少な夜イベント。",
    content_md: "- 開催:春 3 月下旬-4 月上旬・夏 8 月・秋 11 月中旬-12 月初旬\n- 時間:18:30-21:30(各期間)\n- 拝観料:¥500(夜間)\n- 名物:清水の舞台ライトアップ・夜桜 / 紅葉\n- 関連:世界遺産清水寺\n- アクセス:市バス「五条坂」徒歩 10 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9949,
    lon: 135.7849,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kiyomizu_night", "world_heritage", "since_1985", "spring_summer_autumn"],
    source: "manual",
  },
  {
    slug: "kyoto-station-illumination",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "京都駅イルミネーション",
    title_ja: "京都駅イルミネーション",
    romaji: "Kyoto Station Illumination",
    summary_zh: "**京都駅ビル + 京都タワーの冬のイルミネーション**、11 月中旬-2 月末。**京都駅大階段グラフィカルイルミネーション**(LED 演出)+ 京都タワーライトアップ + クリスマスツリー(12 月)。京都駅前広場で観覧無料。",
    content_md: "- 期間:11 月中旬-2 月末\n- 場所:京都駅ビル + 京都タワー + 駅前広場\n- 観覧:無料\n- 名物:大階段グラフィカル LED・クリスマスツリー(12 月)\n- 京都到着即体験可\n- アクセス:JR「京都」即着",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: "2000-11-15",
    season_end: "2000-02-28",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kyoto_station_illumination", "winter_lights", "free", "led_stairs"],
    source: "manual",
  },
  // ════════════════════════════════════════════════════════════════════
  // Phase 5 — 動物園・水族館・遊園
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-aquarium",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "京都水族館",
    title_ja: "京都水族館",
    romaji: "Kyoto Aquarium",
    summary_zh: "**2012 年開園、京都駅近の都市型水族館**、下京区梅小路。**オオサンショウウオ(京都府希少種)展示で著名**、海亀 + ペンギン + イルカショー 等。京都鉄道博物館 + 梅小路公園隣接、家族連れ鉄板。",
    content_md: "- 開園:2012 年\n- 入館:10:00-18:00\n- 入館料:¥2,400\n- 名物:オオサンショウウオ・イルカショー・ペンギン\n- 隣接:京都鉄道博物館・梅小路公園\n- アクセス:JR「梅小路京都西」徒歩 7 分・京都駅徒歩 18 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9856,
    lon: 135.7438,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.kyoto-aquarium.com/" },
    tags: ["kyoto_aquarium", "since_2012", "osanshouuo", "umekoji"],
    source: "manual",
  },
  {
    slug: "kyoto-shi-zoo",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "京都市動物園",
    title_ja: "京都市動物園",
    romaji: "Kyoto Shi Doubutsuen",
    summary_zh: "**1903 年開園、日本第二古の動物園**(東京上野が最古)、左京区岡崎。120 年の歴史、約 110 種 600 頭の動物。岡崎エリア(京セラ美術館・国立近代美術館 隣接)の家族向け定番。",
    content_md: "- 開園:1903 年(明治 36)・日本第二古\n- 入館:9:00-17:00\n- 入館料:¥750\n- 規模:約 110 種 600 頭\n- 名物:キリン・ゾウ・ライオン・ペンギン\n- 隣接:京セラ美術館・国立近代美術館\n- アクセス:地下鉄東西線「東山」徒歩 7 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0149,
    lon: 135.7847,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www5.city.kyoto.jp/zoo/" },
    tags: ["kyoto_zoo", "since_1903", "second_oldest_japan", "okazaki"],
    source: "manual",
  },
  {
    slug: "kyoto-eigamura-entertainment",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "東映太秦映画村(楽 視点)",
    title_ja: "東映太秦映画村",
    romaji: "Toei Uzumasa Eigamura",
    summary_zh: "**1975 年開園のテーマパーク**(育・楽 重複)、右京区太秦。**江戸の街並みセット + 時代劇撮影体験 + 忍者屋敷**等の体験型テーマパーク、子供 + 外国人観光客に人気。¥2,400 で半日コース。",
    content_md: "- 開園:1975 年\n- 入園:9:00-17:00\n- 入園料:¥2,400\n- 名物:江戸セット・忍者屋敷・撮影体験\n- 関連:Phase 22 育(映像文化)\n- アクセス:嵐電「太秦広隆寺」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.012,
    lon: 135.706,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.toei-eigamura.com/" },
    tags: ["uzumasa_eigamura_play", "since_1975", "edo_set", "ninja"],
    source: "manual",
  },
  {
    slug: "kyoto-orgeru-museum",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "嵐山オルゴール博物館",
    title_ja: "嵐山オルゴール博物館",
    romaji: "Arashiyama Orgel Museum",
    summary_zh: "**嵐山のオルゴール専門博物館**、右京区嵯峨。世界各国の 19 世紀オルゴール 150+ 点を展示、デモ演奏で当時の音楽を体感。子供 + カップル向きの嵐山小規模ミュージアム。",
    content_md: "- 入館:10:00-17:00\n- 入館料:¥1,000\n- 名物:19 世紀オルゴール 150+ 点・デモ演奏\n- 関連:嵐山観光圏\n- アクセス:JR「嵯峨嵐山」徒歩 10 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0145,
    lon: 135.6776,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["orgel_museum", "150_pieces", "arashiyama_kids"],
    source: "manual",
  },
  {
    slug: "kyoto-kagaku-center",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "京都市青少年科学センター",
    title_ja: "京都市青少年科学センター",
    romaji: "Kyoto Kagaku Center",
    summary_zh: "**1969 年開館の市立科学博物館**、伏見区深草。プラネタリウム + 体験型展示 + 恐竜化石 等、子供 + 教育的観光に。¥520 のリーズナブル価格。",
    content_md: "- 開館:1969 年\n- 入館:9:00-17:00 / 木休\n- 入館料:¥520(プラネタリウム +¥520)\n- 名物:プラネタリウム・恐竜化石・体験展示\n- アクセス:京阪「藤森」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.943,
    lon: 135.769,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["木"],
    external_urls: {},
    tags: ["science_center", "since_1969", "planetarium", "kids_education"],
    source: "manual",
  },
  // ════════════════════════════════════════════════════════════════════
  // Phase 6 — スポーツ観戦
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-sanga-fc",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "京都サンガ FC(J リーグ)",
    title_ja: "京都サンガ F.C.",
    romaji: "Kyoto Sanga FC",
    summary_zh: "**京都府の J リーグサッカークラブ**、亀岡市のサンガスタジアム by KYOCERA(2020 開業)が本拠。京都市民から熱狂的支持、紫色のチームカラー、年間 J1 / J2 で 20 試合主催。",
    content_md: "- 創設:1994 年\n- 本拠:サンガスタジアム by KYOCERA(亀岡市)\n- リーグ:J1 / J2(年により)\n- チケット:¥3,000-7,000\n- アクセス:JR「亀岡」徒歩 3 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "亀岡市",
    lg_code: "26206",
    area_types: ["urban_central"],
    lat: 35.012,
    lon: 135.547,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://www.sanga-fc.jp/" },
    tags: ["sanga_fc", "j_league", "kameoka", "purple"],
    source: "manual",
  },
  {
    slug: "kyoto-hannariis",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "京都ハンナリーズ(B リーグ)",
    title_ja: "京都ハンナリーズ",
    romaji: "Kyoto Hannaryz",
    summary_zh: "**京都府の B リーグバスケットボールクラブ**、本拠は **京都市体育館 + ハンナリーズアリーナ(亀岡)**。「ハンナリーズ」は京都弁「はんなり」(優雅)由来、京都らしい命名。",
    content_md: "- 創設:2009 年\n- 本拠:京都市体育館・ハンナリーズアリーナ(亀岡)\n- リーグ:B1\n- チケット:¥3,000-8,000\n- 関連:京都サンガ FC と並ぶ京都プロスポーツ",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.014,
    lon: 135.7481,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://hannaryz.jp/" },
    tags: ["hannaryz", "b_league", "basketball", "hannari"],
    source: "manual",
  },
  {
    slug: "kyoto-keibajo",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "京都競馬場(JRA)",
    title_ja: "京都競馬場",
    romaji: "Kyoto Keibajo",
    summary_zh: "**JRA(中央競馬会)の競馬場**、伏見区淀。**G1 京都記念・天皇賞(春)秋華賞 等**を主催する関西の名門競馬場、年間 30+ 開催。2020-2023 大規模改修で新装、観光客も入場可(¥200)。",
    content_md: "- 場所:伏見区淀池上町\n- 開催:年 30+ 日\n- 主要 G1:京都記念・秋華賞・天皇賞春\n- 入場料:¥200(レース日)\n- 改修:2020-2023 大規模\n- アクセス:京阪「淀」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.91,
    lon: 135.711,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 7,
    closed_days: [],
    external_urls: { official: "https://www.jra.go.jp/facilities/race/kyoto/" },
    tags: ["kyoto_keibajo", "jra", "g1_kyoto_kinen", "yodo"],
    source: "manual",
  },
  {
    slug: "kyoto-marathon",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "京都マラソン",
    title_ja: "京都マラソン",
    romaji: "Kyoto Marathon",
    summary_zh: "**毎年 2 月開催の市民マラソン大会**、世界中から 1.6 万人参加。**世界遺産 6 か所(西本願寺・天龍寺・金閣寺・上賀茂神社・銀閣寺・平安神宮)を巡る**京都市内 42.195 km コース、京都春の幕開け。",
    content_md: "- 開催:毎年 2 月中旬日曜日\n- 規模:1.6 万人参加(抽選)\n- コース:京都市内 42.195 km(世界遺産 6 か所)\n- 参加費:¥15,000-20,000\n- 観覧:沿道無料\n- 関連:京都市民の春の祭典",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.762,
    season_start: "2000-02-01",
    season_end: "2000-02-29",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.kyoto-marathon.com/" },
    tags: ["kyoto_marathon", "february", "world_heritage_route", "16000_runners"],
    source: "manual",
  },
  // ════════════════════════════════════════════════════════════════════
  // Phase 7 — 劇場・ホール・音楽祭
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-rohm-theatre",
    category: "entertainment",
    sub_type: "music_festival",
    title_zh: "ロームシアター京都",
    title_ja: "ロームシアター京都",
    romaji: "Rohm Theatre Kyoto",
    summary_zh: "**2016 年リニューアル開館の京都市総合公演会場**、左京区岡崎、ロームのネーミングライツ。**メインホール 2,005 席 + サウスホール 716 席**でクラシック・オペラ・現代音楽・舞台公演を主催、京都の現代芸術中心。",
    content_md: "- リニューアル:2016 年(旧 京都会館 1960)\n- 規模:メイン 2,005・サウス 716 席\n- 公演:クラシック・オペラ・舞踊・舞台劇\n- チケット:¥3,000-15,000(公演別)\n- アクセス:地下鉄東西線「東山」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.014,
    lon: 135.785,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://rohmtheatrekyoto.jp/" },
    tags: ["rohm_theatre", "since_2016", "naming_rights", "okazaki_culture"],
    source: "manual",
  },
  {
    slug: "kyoto-concert-hall",
    category: "entertainment",
    sub_type: "music_festival",
    title_zh: "京都コンサートホール",
    title_ja: "京都コンサートホール",
    romaji: "Kyoto Concert Hall",
    summary_zh: "**1995 年開館の京都府立クラシック専用ホール**、左京区下鴨半木町、植物園隣。**1,839 席 + 510 席**、京都市交響楽団の主拠点、世界的指揮者 + ソリストの定期公演。京都クラシック音楽の中心。",
    content_md: "- 開館:1995 年\n- 規模:大ホール 1,839 席・小ホール 510 席\n- 主拠点:京都市交響楽団\n- チケット:¥2,000-15,000\n- 設計:磯崎新\n- アクセス:地下鉄烏丸線「北山」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0476,
    lon: 135.7635,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.kyotoconcerthall.org/" },
    tags: ["concert_hall", "since_1995", "kyoto_symphony", "isozaki_arata"],
    source: "manual",
  },
  {
    slug: "kyoto-minamiza-kabuki",
    category: "entertainment",
    sub_type: "music_festival",
    title_zh: "南座(歌舞伎)",
    title_ja: "南座",
    romaji: "Minamiza",
    summary_zh: "**1696 年(元禄 9)以来の京都歌舞伎の本拠**、東山区四条大橋東詰。**毎年 12 月顔見世興行**は京都歳末の代表行事(衣 reference)、年中通じて歌舞伎・舞踊・新派劇 等を主催。",
    content_md: "- 開業:1696 年(元禄 9)・京都歌舞伎 320 年の歴史\n- 規模:1,082 席\n- 公演:歌舞伎・新派劇・舞踊\n- チケット:¥7,000-25,000\n- 名物:12 月顔見世興行(衣 reference)\n- アクセス:京阪「祇園四条」徒歩 1 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0027,
    lon: 135.7716,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.shochiku.co.jp/play/theater/minamiza/" },
    tags: ["minamiza", "since_1696", "kabuki", "kaomise_december"],
    source: "manual",
  },
  // ════════════════════════════════════════════════════════════════════
  // Phase 8 — 季節 + 子供向 + 体験
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-firefly-watching",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "京都の蛍(ホタル)観賞",
    title_ja: "京都 蛍観賞",
    romaji: "Kyoto Hotaru",
    summary_zh: "**京都の蛍(ゲンジホタル + ヘイケホタル)**、5 月末-6 月中旬。**哲学の道(若王子神社近)・貴船川・平岡八幡宮**等が代表的観賞地、夜 19:30-21:00 の幻想的な光のショー。",
    content_md: "- 期間:5 月末-6 月中旬\n- 主要観賞地:哲学の道(若王子付近)・貴船川・平岡八幡宮\n- 観賞時間:19:30-21:00\n- 観覧:無料(自然観察)\n- 種類:ゲンジホタル + ヘイケホタル\n- 注:静かに観察・フラッシュ禁止",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.024,
    lon: 135.794,
    season_start: "2000-05-25",
    season_end: "2000-06-15",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hotaru", "firefly", "may_june", "philosophy_path"],
    source: "manual",
  },
  {
    slug: "kyoto-kamogawa-yuka-summer",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "鴨川納涼床",
    title_ja: "鴨川納涼床",
    romaji: "Kamogawa Yuka",
    summary_zh: "**5-9 月の鴨川河岸の床料理体験**、二条 → 五条の鴨川西岸 + 先斗町 + 木屋町。江戸期からの伝統「川床」、京都老舗料亭が川面に床を出す。**夕方の涼風 + 京懐石 + 川面景観**は京都夏の鉄板体験。",
    content_md: "- 期間:5-9 月\n- 場所:鴨川西岸(二条-五条)+ 先斗町 + 木屋町\n- 料金:京懐石 ¥10,000-30,000(店別)\n- 名物:川面床・夕涼み・京料亭\n- 予約:夏期 1-2 か月前必須\n- アクセス:京阪「祇園四条」",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0058,
    lon: 135.77,
    season_start: "2000-05-01",
    season_end: "2000-09-30",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["kamogawa_yuka", "summer", "kawadoko", "edo_tradition"],
    source: "manual",
  },
  {
    slug: "kyoto-ajisai-spots",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "京都の紫陽花(あじさい)",
    title_ja: "京都 紫陽花",
    romaji: "Kyoto Ajisai",
    summary_zh: "**6 月中旬-7 月初旬の京都紫陽花(あじさい)観賞**:**三千院(大原)+ 善峯寺(西山)+ 楊谷寺(西山)+ 三室戸寺(宇治)**等が代表。雨の京都に最も似合う花、紅葉桜以外の隠れた季節体験。",
    content_md: "- 期間:6 月中旬-7 月初旬\n- 主要寺院:三千院・善峯寺・楊谷寺・三室戸寺\n- 入場料:各 ¥500-700\n- 名物:紫陽花 + 苔庭・雨の京都\n- 文化価値:梅雨の京都を楽しむ伝統",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: "2000-06-15",
    season_end: "2000-07-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ajisai", "june_rainy_season", "sanzen_in", "yoshimine"],
    source: "manual",
  },
  {
    slug: "kyoto-ume-spots",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "京都の梅(うめ)",
    title_ja: "京都 梅",
    romaji: "Kyoto Ume",
    summary_zh: "**2-3 月の京都梅観賞**:**北野天満宮 + 城南宮 + 二条城 + 梅小路公園**等が代表、桜より早く春を告げる花。北野天満宮の梅花祭(2/25)+ 城南宮の春の山(2-3 月)が見もの。",
    content_md: "- 期間:2 月初旬-3 月中旬\n- 主要場所:北野天満宮(1,500 本)・城南宮春の山(150 本しだれ)・二条城・梅小路\n- 入場料:北野梅苑 ¥1,000・城南宮 ¥1,000\n- 名物:梅花祭(2/25 北野)・しだれ梅(城南宮)\n- 関連:桜より早春の楽しみ",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.762,
    season_start: "2000-02-01",
    season_end: "2000-03-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ume", "early_spring", "kitano_baikasai", "jonangu_haru"],
    source: "manual",
  },
  {
    slug: "kyoto-tower-night-view",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "京都タワー(展望台 + 夜景)",
    title_ja: "京都タワー",
    romaji: "Kyoto Tower",
    summary_zh: "**1964 年開業の京都駅前ランドマーク**、高さ 131 m。**展望台(地上 100 m)から京都市内 360 度パノラマ**、夜景は京都の鉄板。京都駅徒歩 2 分のアクセス、子供連れ + カップル + 観光初心者に最適。",
    content_md: "- 開業:1964 年(東京オリンピック年)\n- 高さ:131 m\n- 入塔:9:00-21:00\n- 入場料:¥900\n- 名物:360 度パノラマ・夜景\n- アクセス:JR「京都」徒歩 2 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9871,
    lon: 135.7592,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.kyoto-tower.jp/" },
    tags: ["kyoto_tower", "since_1964", "131m", "panorama"],
    source: "manual",
  },
  {
    slug: "kyoto-zazen-experience",
    category: "entertainment",
    sub_type: "music_festival",
    title_zh: "京都 座禅体験ガイド",
    title_ja: "京都 座禅体験",
    romaji: "Kyoto Zazen Experience",
    summary_zh: "**京都市内の禅寺で座禅体験**、観光客向けに**建仁寺・南禅寺・天龍寺・東福寺・妙心寺東林院 等**が定期開催。30-60 分の座禅 + 茶礼で禅の入口、¥1,000-2,000、外国人参加歓迎。",
    content_md: "- 主要寺院:建仁寺・南禅寺・天龍寺・東福寺・妙心寺東林院\n- 体験時間:30-60 分(寺院により)\n- 体験料:¥1,000-2,000\n- 言語:日本語(英語パンフあり)\n- 予約:不要(通常)・大人数は要事前\n- 文化価値:禅文化の入口",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["zazen", "zen_experience", "buddhist_temples", "tourist_friendly"],
    source: "manual",
  },
  {
    slug: "kyoto-asakatsu-guide",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "京都早朝活動(朝活)ガイド",
    title_ja: "京都朝活ガイド",
    romaji: "Kyoto Asakatsu Guide",
    summary_zh: "**京都の早朝活動(6-9 時)推奨**:**伏見稲荷千本鳥居 + 永観堂 + 清水寺早朝 + 哲学の道**等。観光客が少ない静寂の京都体験、朝食(京都駅・烏丸の早朝開業店)とセットで充実。",
    content_md: "- 推奨時間:6-9 時\n- 主要スポット:伏見稲荷(24h)・清水寺(6:00 開門)・南禅寺(6:00 三門)・哲学の道\n- 朝食:イノダコーヒ・進々堂(7:00 開店)\n- 文化価値:京都の静寂を独占\n- 注:神社は 24 時間・寺は 6-7 時開門",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["asakatsu", "early_morning", "less_crowded", "kyoto_dawn"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 9 — 桜の名所追加(具体的スポット)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-nakaragi-no-michi-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "半木の道 しだれ桜並木",
    title_ja: "半木の道",
    romaji: "Nakaragi no Michi",
    summary_zh: "**賀茂川左岸の枝垂桜並木**(北山大橋〜北大路橋・約 800 m)。府立植物園に隣接、4 月初旬の見頃にはピンクのトンネル。地元定番の知る人ぞ知る花見スポット。",
    content_md: "- 場所:賀茂川左岸(北山大橋〜北大路橋)\n- 距離:約 800 m\n- 見頃:4 月初旬(植物園とほぼ同時期)\n- 特色:約 70 本のしだれ桜\n- アクセス:地下鉄烏丸線「北山駅」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.046,
    lon: 135.762,
    season_start: "2000-04-01",
    season_end: "2000-04-10",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "shidare_zakura", "kamogawa", "april_early", "free"],
    source: "manual",
  },
  {
    slug: "kyoto-heian-jingu-shin-en-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "平安神宮神苑 紅しだれ",
    title_ja: "平安神宮 神苑",
    romaji: "Heian Jingū Shin'en",
    summary_zh: "**東神苑の八重紅枝垂桜**で有名。谷崎潤一郎『細雪』にも登場、4 月初〜中旬の遅咲きしだれ桜。神苑入苑料 ¥600(本殿は無料)。夜間ライトアップ「紅しだれコンサート」も毎年開催。",
    content_md: "- 神苑:東神苑の八重紅枝垂桜\n- 見頃:4 月初〜中旬\n- 神苑入苑料:¥600\n- イベント:紅しだれコンサート(4 月上旬・夜間ライトアップ)\n- アクセス:地下鉄東西線「東山駅」徒歩 10 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0166,
    lon: 135.7826,
    season_start: "2000-04-05",
    season_end: "2000-04-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.heianjingu.or.jp/" },
    tags: ["sakura", "shidare_zakura", "shrine", "april_mid", "light_up"],
    source: "manual",
  },
  {
    slug: "kyoto-botanical-garden-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "京都府立植物園 桜林",
    title_ja: "京都府立植物園 桜林",
    romaji: "Kyōto Furitsu Shokubutsuen Sakurabayashi",
    summary_zh: "**約 130 種・450 本の桜**を 1 月-5 月にかけて順次咲かせる名所。早咲き(寒桜・河津桜)から遅咲き(御室桜)まで長期間楽しめる、府立植物園の春の目玉。入園 ¥200。",
    content_md: "- 規模:約 130 種・450 本\n- 早咲き:寒桜・河津桜(2-3 月)\n- ピーク:染井吉野(4 月初旬)\n- 遅咲き:御室桜・八重桜(4 月中旬)\n- 入園料:¥200\n- アクセス:地下鉄烏丸線「北山駅」直結",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0494,
    lon: 135.762,
    season_start: "2000-03-20",
    season_end: "2000-04-20",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.pref.kyoto.jp/plant/" },
    tags: ["sakura", "botanical_garden", "long_season", "early_late", "kid_friendly"],
    source: "manual",
  },
  {
    slug: "kyoto-tenryuji-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "天龍寺 桜",
    title_ja: "天龍寺",
    romaji: "Tenryū-ji",
    summary_zh: "**嵐山・世界遺産天龍寺の桜**。曹源池庭園と桜・嵐山借景の三層構図、4 月初旬が見頃。多宝殿前のしだれ桜が特に有名。庭園参拝 ¥500。",
    content_md: "- 世界遺産・臨済宗天龍寺派大本山\n- 見どころ:多宝殿前しだれ桜・曹源池庭園\n- 見頃:4 月初旬\n- 庭園拝観:¥500\n- アクセス:嵐電「嵐山駅」徒歩 1 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0157,
    lon: 135.6744,
    season_start: "2000-03-28",
    season_end: "2000-04-10",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.tenryuji.com/" },
    tags: ["sakura", "world_heritage", "arashiyama", "shidare_zakura", "garden"],
    source: "manual",
  },
  {
    slug: "kyoto-osawa-pond-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "大覚寺 大沢池 桜",
    title_ja: "大覚寺 大沢池",
    romaji: "Daikaku-ji Ōsawa-no-ike",
    summary_zh: "**嵯峨野大覚寺の大沢池桜**。日本最古の人工林泉(平安期)、池畔に染井吉野・しだれ桜が約 700 本。4 月初旬の朝桜と水面の反射が絶景。庭園 ¥300。",
    content_md: "- 日本最古の人工林泉(平安期 嵯峨天皇)\n- 桜:約 700 本(染井吉野・しだれ)\n- 見頃:4 月初旬\n- 名古曽の滝跡・水鏡が美しい\n- 庭園:¥300\n- アクセス:JR 「嵯峨嵐山駅」徒歩 20 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.029,
    lon: 135.677,
    season_start: "2000-04-01",
    season_end: "2000-04-12",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.daikakuji.or.jp/" },
    tags: ["sakura", "pond_reflection", "saga_no", "heian_garden", "less_crowded"],
    source: "manual",
  },
  {
    slug: "kyoto-keage-incline-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "蹴上インクライン 桜",
    title_ja: "蹴上インクライン",
    romaji: "Keage Incline",
    summary_zh: "**琵琶湖疏水の旧傾斜鉄道跡(明治期)**を歩く桜並木。線路上を歩ける珍しい花見スポット、4 月初旬が見頃。Instagram 映え必至、無料。",
    content_md: "- 構造:琵琶湖疏水の旧傾斜鉄道跡(明治 24 年〜)\n- 距離:約 582 m\n- 桜:約 90 本(染井吉野)\n- 見頃:4 月初旬\n- 特色:線路上を歩ける(廃線・遊歩道化)\n- アクセス:地下鉄東西線「蹴上駅」徒歩 3 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.011,
    lon: 135.792,
    season_start: "2000-04-01",
    season_end: "2000-04-08",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "incline", "meiji_heritage", "instagram", "free"],
    source: "manual",
  },
  {
    slug: "kyoto-haradanien-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "原谷苑 桜",
    title_ja: "原谷苑",
    romaji: "Haradanien",
    summary_zh: "**個人所有の桜苑**(金閣寺裏山・原谷地区)。30 種類以上のしだれ桜が密集、4 月中旬の遅咲き枝垂桜が圧巻。要予約・桜時期のみ開園、入園 ¥1,500-2,000(時期変動)。",
    content_md: "- 個人所有の桜苑(村岩農園)\n- 規模:30 種以上のしだれ桜・染井吉野\n- 見頃:4 月中旬(遅咲き)\n- 入園:¥1,500-2,000(時期変動)\n- 開園:桜時期のみ(3 月下旬-4 月下旬)\n- アクセス:バス「原谷」(本数少)・タクシー推奨",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.039,
    lon: 135.728,
    season_start: "2000-04-05",
    season_end: "2000-04-20",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "shidare_zakura", "private_garden", "april_mid", "hidden_gem"],
    source: "manual",
  },
  {
    slug: "kyoto-uji-park-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "宇治公園・宇治川 桜",
    title_ja: "宇治公園",
    romaji: "Uji Kōen",
    summary_zh: "**宇治川中之島の桜並木**。平等院・宇治上神社(両世界遺産)に近接、川と橋と桜の構図が美しい。4 月初旬の見頃、無料、地元民の花見定番。",
    content_md: "- 場所:宇治川中之島・朝霧通り\n- 桜:約 2,000 本\n- 見頃:4 月初旬\n- 周辺:平等院・宇治上神社(世界遺産)\n- 入園:無料\n- アクセス:JR / 京阪「宇治駅」徒歩 10 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "宇治市",
    lg_code: "26204",
    area_types: ["urban_local", "small_town"],
    lat: 34.892,
    lon: 135.808,
    season_start: "2000-04-01",
    season_end: "2000-04-10",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sakura", "uji", "river", "world_heritage_nearby", "free"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 10 — 紅葉の名所追加
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-gyoen-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "京都御苑 紅葉",
    title_ja: "京都御苑",
    romaji: "Kyōto Gyoen",
    summary_zh: "**京都御苑の紅葉**。中立売御門周辺・宗像神社・閑院宮邸跡で楓・銀杏が美しい。11 月下旬-12 月初旬の見頃、無料、24h、観光客が少ない地元民推薦スポット。",
    content_md: "- 規模:京都御所周辺の国民公園(63 ha)\n- 見どころ:中立売御門・宗像神社・閑院宮邸跡\n- 見頃:11 月下旬-12 月初旬\n- 入園:無料・24h\n- アクセス:地下鉄烏丸線「丸太町駅」徒歩 1 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.022,
    lon: 135.762,
    season_start: "2000-11-25",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["momiji", "imperial_palace", "free", "less_crowded", "december_early"],
    source: "manual",
  },
  {
    slug: "kyoto-botanical-garden-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "京都府立植物園 紅葉",
    title_ja: "京都府立植物園 紅葉",
    romaji: "Kyōto Furitsu Shokubutsuen Momiji",
    summary_zh: "**もみじ・楓 100 種以上**を園内で展示。紅葉の見頃 11 月中-12 月初旬、夜間ライトアップ「秋のライトアップ」も毎年開催。入園 ¥200(夜間別料金)。",
    content_md: "- 規模:約 100 種の楓・もみじ\n- 見頃:11 月中旬-12 月初旬\n- イベント:秋のライトアップ(11 月中下旬・夜間別料金)\n- 入園料:¥200(日中)\n- アクセス:地下鉄烏丸線「北山駅」直結",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0494,
    lon: 135.762,
    season_start: "2000-11-15",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.pref.kyoto.jp/plant/" },
    tags: ["momiji", "botanical_garden", "light_up", "kid_friendly", "varieties"],
    source: "manual",
  },
  {
    slug: "kyoto-ginkakuji-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "銀閣寺 紅葉",
    title_ja: "銀閣寺",
    romaji: "Ginkaku-ji",
    summary_zh: "**世界遺産・慈照寺(銀閣寺)の紅葉**。展望台から見下ろす京都市街と紅葉が圧巻。11 月下旬-12 月初旬の見頃、哲学の道との合わせ訪問が定番。拝観 ¥500。",
    content_md: "- 世界遺産・室町後期足利義政の山荘\n- 見どころ:展望所からの京都市街と紅葉\n- 見頃:11 月下旬-12 月初旬\n- 拝観料:¥500\n- アクセス:バス「銀閣寺前」徒歩 5 分\n- 哲学の道入口に隣接",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0269,
    lon: 135.7983,
    season_start: "2000-11-25",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.shokoku-ji.jp/ginkakuji/" },
    tags: ["momiji", "world_heritage", "ginkakuji", "tetsugaku_no_michi", "panorama"],
    source: "manual",
  },
  {
    slug: "kyoto-kitano-tenmangu-momiji-en",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "北野天満宮 もみじ苑",
    title_ja: "北野天満宮 もみじ苑",
    romaji: "Kitano Tenmangū Momiji-en",
    summary_zh: "**北野天満宮の御土居**(豊臣秀吉築造)沿いの紅葉苑。約 350 本の楓、11 月中-12 月初旬の見頃、夜間ライトアップ・茶菓子付き拝観 ¥1,200。",
    content_md: "- 御土居:豊臣秀吉が築いた京都囲み土塁\n- 規模:約 350 本の楓\n- 見頃:11 月中旬-12 月初旬\n- ライトアップ:11 月中-12 月初(夜間)\n- 拝観料:¥1,200(茶菓子付)\n- アクセス:バス「北野天満宮前」徒歩 1 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0312,
    lon: 135.7349,
    season_start: "2000-11-15",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://kitanotenmangu.or.jp/" },
    tags: ["momiji", "shrine", "odoi", "light_up", "tea_included"],
    source: "manual",
  },
  {
    slug: "kyoto-chion-in-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "知恩院 紅葉ライトアップ",
    title_ja: "知恩院 秋のライトアップ",
    romaji: "Chion-in Aki no Light-up",
    summary_zh: "**浄土宗総本山・知恩院の秋ライトアップ**。三門・友禅苑・方丈庭園が夜間特別公開、紅葉と巨大三門のスケール感が圧倒的。11 月初-12 月初旬、拝観 ¥800。",
    content_md: "- 浄土宗総本山(法然上人開基)\n- 見どころ:三門(国宝・日本最大級)・友禅苑\n- ライトアップ:11 月初-12 月初\n- 拝観料:夜間 ¥800\n- アクセス:バス「知恩院前」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0061,
    lon: 135.7825,
    season_start: "2000-11-01",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.chion-in.or.jp/" },
    tags: ["momiji", "light_up", "jodo_shu", "national_treasure", "san_mon"],
    source: "manual",
  },
  {
    slug: "kyoto-shogun-zuka-seiryuden-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "将軍塚青龍殿 紅葉",
    title_ja: "将軍塚青龍殿",
    romaji: "Shōgun-zuka Seiryūden",
    summary_zh: "**東山頂上の青蓮院門跡飛地**。京都市街全景の大舞台 + 紅葉の組み合わせで近年大人気、夜間ライトアップ + 京都の夜景が見える希少スポット。拝観 ¥600。",
    content_md: "- 青蓮院門跡の飛地境内・東山山頂\n- 大舞台:京都市街一望(清水寺の倍規模)\n- 見頃:11 月中-12 月初旬\n- 夜間ライトアップ:11 月初-12 月初\n- 拝観料:¥600\n- アクセス:バス「将軍塚」(便少)・タクシー推奨",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.001,
    lon: 135.797,
    season_start: "2000-11-15",
    season_end: "2000-12-10",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.shogunzuka.com/" },
    tags: ["momiji", "panorama", "night_view", "light_up", "higashiyama_summit"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 11 — 京都体験(着物・人力車・伝統芸能・観光列車)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-yumeyakata-kimono-rental",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "夢館 着物レンタル",
    title_ja: "夢館",
    romaji: "Yumeyakata",
    summary_zh: "**京都最大手の着物レンタル店**(五条・烏丸店)。約 1,000 着の着物・浴衣を取扱、ヘアセット込みプラン ¥3,300〜。海外観光客対応・多言語スタッフ常駐。",
    content_md: "- 在庫:約 1,000 着\n- プラン:着物 ¥3,300〜・ヘアセット ¥1,650〜\n- 営業:10:00-18:30\n- 多言語対応(英・中・韓)\n- 烏丸店:地下鉄烏丸線「五条駅」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9999,
    lon: 135.762,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 1,
    closed_days: [],
    external_urls: { official: "https://www.yumeyakata.com/" },
    tags: ["kimono_rental", "experience", "tourist_friendly", "multilingual", "gojo"],
    source: "manual",
  },
  {
    slug: "kyoto-ebisuya-jinrikisha-arashiyama",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "えびす屋 人力車 嵐山店",
    title_ja: "えびす屋 嵐山",
    romaji: "Ebisu-ya Arashiyama",
    summary_zh: "**京都人力車最大手・嵐山発祥の老舗**。渡月橋・竹林・嵐山一周コース、12 分 ¥4,000〜・60 分 ¥17,000〜。俥夫(車夫)が観光案内付き、若い男性スタッフが多くインスタ映え。",
    content_md: "- コース:12 分・30 分・60 分\n- 料金:12 分 ¥4,000(1 名)〜\n- 主要コース:渡月橋・竹林の道・天龍寺周辺\n- 営業:9:30-日没\n- 集合:渡月橋北詰",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0153,
    lon: 135.6776,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 1,
    closed_days: [],
    external_urls: { official: "https://ebisuya.com/branch/arashiyama/" },
    tags: ["jinrikisha", "experience", "arashiyama", "tour_guide", "instagram"],
    source: "manual",
  },
  {
    slug: "kyoto-samurai-ninja-museum",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "Samurai & Ninja Museum 京都",
    title_ja: "サムライ忍者ミュージアム 京都",
    romaji: "Samurai Ninja Museum Kyoto",
    summary_zh: "**錦市場近くの侍・忍者体験博物館**。甲冑試着・刀術体験・忍者武器投擲が含まれる英語ガイド付きツアー、外国人向け人気 No.1 京都体験。¥2,500〜(コースにより)。",
    content_md: "- 場所:錦市場近く・新京極通\n- コース:刀術・忍者武器・甲冑試着\n- 言語:英語ガイド主体(日本語可)\n- 料金:¥2,500〜\n- 営業:9:30-19:00\n- アクセス:阪急「京都河原町駅」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0044,
    lon: 135.766,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 0,
    closed_days: [],
    external_urls: { official: "https://www.mai-ko.com/samurai/" },
    tags: ["samurai", "ninja", "experience", "english_friendly", "museum"],
    source: "manual",
  },
  {
    slug: "kyoto-gion-corner",
    category: "entertainment",
    sub_type: "music_festival",
    title_zh: "ギオンコーナー(祇園コーナー)",
    title_ja: "ギオンコーナー",
    romaji: "Gion Corner",
    summary_zh: "**祇園の弥栄会館にて毎日上演される伝統芸能ダイジェスト**。京舞・茶道・華道・琴・狂言・雅楽・文楽の七芸を 1 時間で凝縮、海外観光客向け定番。¥3,500。",
    content_md: "- 場所:弥栄会館(祇園・四条南座近く)\n- 七芸:京舞・茶道・華道・琴・狂言・雅楽・文楽\n- 公演時間:18:00 / 19:00(各 50 分)\n- 料金:¥3,500\n- 多言語イヤホンガイド\n- アクセス:京阪「祇園四条駅」徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.003,
    lon: 135.7755,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 0,
    closed_days: [],
    external_urls: { official: "https://www.kyoto-gioncorner.com/" },
    tags: ["traditional_arts", "gion", "tourist_friendly", "multilingual", "daily_show"],
    source: "manual",
  },
  {
    slug: "kyoto-sagano-romantic-train",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "嵯峨野トロッコ列車",
    title_ja: "嵯峨野トロッコ列車",
    romaji: "Sagano Romantic Train",
    summary_zh: "**保津峡を走る観光列車**(トロッコ嵯峨↔トロッコ亀岡・7.3 km・25 分)。窓のないオープン車両も連結、桜・新緑・紅葉の見頃に絶景。指定席 ¥880・要予約。",
    content_md: "- 区間:トロッコ嵯峨〜トロッコ亀岡(7.3 km・25 分)\n- 季節:桜(4 月)・新緑(5 月)・紅葉(11 月)が圧巻\n- リッチ号:窓なしオープン車両(5 号車)\n- 料金:¥880(片道)\n- 運休:水曜・1-2 月\n- 要予約(JR みどりの窓口・KKday)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central", "small_town"],
    lat: 35.019,
    lon: 135.671,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 30,
    closed_days: ["wed"],
    external_urls: { official: "https://www.sagano-kanko.co.jp/" },
    tags: ["scenic_train", "arashiyama", "kameoka", "sakura", "momiji"],
    source: "manual",
  },
  {
    slug: "kyoto-hozugawa-kudari",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "保津川下り",
    title_ja: "保津川下り",
    romaji: "Hozugawa Kudari",
    summary_zh: "**亀岡から嵐山(渡月橋)まで保津川を 16 km・約 2 時間下る伝統舟遊び**。江戸期からの観光舟、急流・渓谷・四季の風景が楽しめる。¥4,500、要予約、雨天運休。",
    content_md: "- 区間:亀岡〜嵐山(16 km・約 2 時間)\n- 料金:¥4,500\n- 営業:3 月〜12 月(冬期は座敷舟)\n- 集合:JR 「亀岡駅」徒歩 8 分の乗船場\n- 要予約・雨天運休\n- トロッコ列車との周遊が定番",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "亀岡市",
    lg_code: "26206",
    area_types: ["urban_local", "small_town"],
    lat: 35.013,
    lon: 135.572,
    season_start: "2000-03-01",
    season_end: "2000-12-31",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: { official: "https://www.hozugawakudari.jp/" },
    tags: ["river_boat", "kameoka", "arashiyama", "edo_tradition", "scenic"],
    source: "manual",
  },
  {
    slug: "kyoto-eizan-kirara-koyo-tunnel",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "叡山電鉄 紅葉トンネル",
    title_ja: "叡山電鉄 紅葉トンネル",
    romaji: "Eizan Dentetsu Momiji Tunnel",
    summary_zh: "**鞍馬線市原-二ノ瀬駅間の約 250 m の楓トンネル**。「きらら号」展望列車が紅葉時期(11 月)に徐行運転、ライトアップも実施。乗車券のみで体験可、京都人気の秘景。",
    content_md: "- 場所:叡山電鉄 鞍馬線 市原〜二ノ瀬(約 250 m)\n- 楓:約 280 本\n- 見頃:11 月中-12 月初\n- きらら号:展望窓のパノラマ車両\n- ライトアップ:11 月中-12 月初\n- 乗車券:¥430(出町柳〜鞍馬)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.103,
    lon: 135.762,
    season_start: "2000-11-15",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://eizandensha.co.jp/" },
    tags: ["scenic_train", "momiji", "light_up", "kurama_line", "panorama"],
    source: "manual",
  },
  {
    slug: "kyoto-arashiyama-monkey-park-iwatayama",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "嵐山モンキーパーク いわたやま",
    title_ja: "嵐山モンキーパーク いわたやま",
    romaji: "Arashiyama Monkey Park Iwatayama",
    summary_zh: "**嵐山岩田山頂の野生ニホンザル放牧地**。約 120 頭のサルが自由に暮らす、山頂から京都市街一望。山道 20 分登山。¥600・子供 ¥300、サル餌やり別途 ¥100。",
    content_md: "- 規模:約 120 頭の野生ニホンザル\n- 山頂までの登山:約 20 分\n- 山頂展望:京都市街一望\n- 餌やり:¥100/カゴ\n- 入園料:大人 ¥600・子供 ¥300\n- 営業:9:00-16:30",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0098,
    lon: 135.6776,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://monkeypark.jp/" },
    tags: ["monkey_park", "arashiyama", "panorama", "wild_animals", "hiking"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 12 — 季節 / 大規模公園・レジャー
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-tsukimi-spots-guide",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "京都月見の名所ガイド",
    title_ja: "京都月見ガイド",
    romaji: "Kyoto Tsukimi Spots Guide",
    summary_zh: "**中秋(9 月中-10 月初)の月見スポット**:大覚寺「観月の夕べ」(大沢池龍頭舟)・松尾大社「観月祭」・上賀茂神社「賀茂観月祭」。平安期から続く伝統行事。要事前予約多。",
    content_md: "- 大覚寺「観月の夕べ」:大沢池の龍頭舟・¥1,000(舟は別)\n- 松尾大社「観月祭」:9 月中秋・無料\n- 上賀茂神社「賀茂観月祭」:雅楽奉納・無料\n- 期間:9 月中-10 月初\n- 多くは要事前予約",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: "2000-09-15",
    season_end: "2000-10-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["tsukimi", "moon_viewing", "autumn", "heian_tradition", "guide"],
    source: "manual",
  },
  {
    slug: "kyoto-yukimi-spots-guide",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "京都雪景色の名所ガイド",
    title_ja: "京都雪見ガイド",
    romaji: "Kyoto Yukimi Spots Guide",
    summary_zh: "**京都の雪景色名所**(1-2 月、年数回限定):金閣寺の雪化粧・銀閣寺の白屋根・常寂光寺の参道・貴船神社の灯篭。降雪は事前予測困難、雪情報を SNS でリアルタイム確認推奨。",
    content_md: "- 金閣寺:雪 + 金閣の対比が圧巻\n- 銀閣寺:白い屋根・寂び\n- 常寂光寺:雪の参道\n- 貴船神社:灯篭の雪景色\n- 時期:1 月中-2 月初(年数回・予測困難)\n- 朝早く SNS チェック必須",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: "2000-01-15",
    season_end: "2000-02-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yukimi", "snow_scenery", "winter", "limited_days", "guide"],
    source: "manual",
  },
  {
    slug: "kyoto-gozan-okuribi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "五山送り火(大文字焼)",
    title_ja: "五山送り火",
    romaji: "Gozan no Okuribi",
    summary_zh: "**8/16 夜・京都を囲む五山(大・妙法・船・左大文字・鳥居)に火文字を点火するお盆送り火**。室町期からの伝統、京都最大の夏祭り、市内各所から見えるが鴨川河岸が定番。",
    content_md: "- 開催日:毎年 8/16 夜\n- 順次点火:大文字 20:00 → 妙法 20:05 → 船 20:10 → 左大文字 20:15 → 鳥居 20:20\n- 観覧:鴨川河岸・京都駅ビル・船岡山\n- 室町期(15C)からの伝統\n- 入場無料",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.026,
    lon: 135.798,
    season_start: null,
    season_end: null,
    event_start: "2000-08-16",
    event_end: "2000-08-16",
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["okuribi", "summer_festival", "bon", "kyoto_iconic", "free"],
    source: "manual",
  },
  {
    slug: "kyoto-hotaru-spots-guide",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "京都蛍の名所ガイド",
    title_ja: "京都蛍ガイド",
    romaji: "Kyoto Hotaru Spots Guide",
    summary_zh: "**6 月初〜中旬の蛍観賞**:貴船・鞍馬の山間、宇治川左岸、雲ヶ畑(京都市北部)が定番。19:30-20:30 が活動ピーク、暗闇 + 川辺 + 自然湿気の三条件が必要。",
    content_md: "- 主要スポット:貴船・鞍馬・雲ヶ畑・宇治川\n- 時期:6 月初-中旬\n- ピーク時間:19:30-20:30\n- 必要条件:暗闇 + 川辺 + 湿気\n- アクセス:バス・タクシー(交通便少)\n- 注:雨天 / 強風時は出ない",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain", "rural"],
    lat: 35.121,
    lon: 135.762,
    season_start: "2000-06-01",
    season_end: "2000-06-20",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["firefly", "june", "kifune", "ujikawa", "nature"],
    source: "manual",
  },
  {
    slug: "kyoto-arashiyama-takao-parkway",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "嵐山-高雄パークウェイ",
    title_ja: "嵐山-高雄パークウェイ",
    romaji: "Arashiyama-Takao Parkway",
    summary_zh: "**嵐山〜高雄を結ぶ全長 10.7 km の有料ドライブウェイ**。展望台 7 箇所、桜・新緑・紅葉の絶景。子供向けゴーカート・ドッグラン・ボート遊びもあり、家族向けレジャー定番。¥1,200/普通車。",
    content_md: "- 全長:10.7 km(嵐山〜高雄)\n- 通行料:¥1,200(普通車)\n- 展望台:7 箇所\n- 設備:ゴーカート・ドッグラン・ボート・売店\n- 季節:桜(4 月)・新緑(5 月)・紅葉(11 月)\n- 自家用車・レンタカー必須",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central", "mountain"],
    lat: 35.041,
    lon: 135.661,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["drive_way", "family", "panorama", "go_kart", "rental_car"],
    source: "manual",
  },
  {
    slug: "kyoto-tango-matsushima",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "丹後松島(伊根町・若狭湾)",
    title_ja: "丹後松島",
    romaji: "Tango Matsushima",
    summary_zh: "**丹後半島東岸・伊根町の海岸絶景**。リアス式海岸に小さい島々が浮かぶ景観、宮城の松島と並ぶ「日本三景外」の名所。経ヶ岬展望台・丹後松島展望所が見どころ。",
    content_md: "- 場所:伊根町・経ヶ岬から本庄浜の海岸\n- 名:宮城松島と類似のリアス景観\n- 主展望:丹後松島展望所・経ヶ岬\n- アクセス:車推奨(京都市から 2.5h)\n- 季節:4-10 月が見頃",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: "与謝郡",
    municipality_ja: "伊根町",
    lg_code: "26465",
    area_types: ["coastal_seaside", "rural"],
    lat: 35.71,
    lon: 135.252,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["tango", "ine", "coastal", "scenery", "rias"],
    source: "manual",
  },
  {
    slug: "kyoto-amanohashidate-cycling",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "天橋立サイクリング",
    title_ja: "天橋立 サイクリング",
    romaji: "Amanohashidate Cycling",
    summary_zh: "**日本三景・天橋立(全長 3.6 km の砂州)を自転車で渡る体験**。レンタサイクル ¥400(2h)・大人気。徒歩 50 分が自転車 15 分、両端に展望台あり。",
    content_md: "- 砂州距離:約 3.6 km\n- 自転車所要:15 分(徒歩 50 分)\n- レンタル:¥400(2h)・¥600(1 日)\n- 借りる場所:駅前・天橋立観光協会\n- 両端:文殊側展望台・傘松公園\n- アクセス:京都丹後鉄道「天橋立駅」",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "宮津市",
    lg_code: "26205",
    area_types: ["coastal_seaside", "small_town"],
    lat: 35.566,
    lon: 135.197,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.amanohashidate.jp/" },
    tags: ["amanohashidate", "cycling", "miyazu", "three_views_japan", "sandbar"],
    source: "manual",
  },
  {
    slug: "kyoto-yuhigaura-sunset",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "夕日ヶ浦海岸 サンセット",
    title_ja: "夕日ヶ浦海岸",
    romaji: "Yūhigaura",
    summary_zh: "**京丹後・浜詰海岸の絶景サンセット**。日本海に沈む夕日と砂浜・ブランコの組み合わせがインスタ映え定番。「日本の夕陽 100 選」、大型ブランコ「ゆらり」(無料)が人気。",
    content_md: "- 場所:京丹後市網野町浜詰\n- 「日本の夕陽 100 選」選出\n- 大型ブランコ「ゆらり」:無料・夕陽 + ブランコでインスタ映え\n- 季節:4-9 月の夕陽が綺麗\n- アクセス:京都丹後鉄道「夕日ヶ浦木津温泉駅」徒歩 20 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京丹後市",
    lg_code: "26212",
    area_types: ["coastal_seaside", "small_town"],
    lat: 35.677,
    lon: 134.994,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sunset", "kyotango", "beach", "instagram", "japan_top_100"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R7 補完(老卷・2026-04-29)— 京都楽 75 → 85(+10)
  // 京都三大祭 + 鉄道博物館 + マンガミュージアム + 舞鶴赤レンガ +
  //   貴船川床 + 鞍馬山ハイキング + 叡山ケーブル + 京都駅ビル空中庭園
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-gion-matsuri-summer",
    category: "entertainment",
    sub_type: "ancient_festival",
    title_zh: "祇園祭(7 月・八坂神社主催・1100 年・京都最大祭礼・山鉾巡行ユネスコ無形文化遺産)",
    title_ja: "祇園祭",
    romaji: "Gion Matsuri",
    summary_zh: "**祇園祭は京都最大の祭礼**(7 月 1-31 日・八坂神社主催)。1100 年余の歴史(869 年疫病鎮圧祈願に始まる)、ハイライトの「山鉾巡行」(7/17 前祭+7/24 後祭)+「宵山」(7/14-16 + 7/21-23)が観光客集中。山鉾は国指定重要有形民俗文化財・「山・鉾・屋台行事」(2016)はユネスコ無形文化遺産。",
    content_md: "- 開催:7 月 1 日~31 日(全月)\n- 主催:八坂神社\n- 由来:869 年(貞観11)疫病鎮圧の祇園御霊会\n- 主要行事:\n  - 山鉾巡行 前祭:7 月 17 日(23 基・四条烏丸→四条河原町)\n  - 山鉾巡行 後祭:7 月 24 日(11 基・烏丸御池→四条烏丸)\n  - 宵山:7/14-16(前祭)+7/21-23(後祭)・夜の山鉾町\n  - 神輿渡御:7/17 夜+7/24 夜・四条御旅所\n- 山鉾:国指定重要有形民俗文化財・34 基保存\n- ユネスコ:山・鉾・屋台行事(2016)無形文化遺産登録\n- 動員:1 ヶ月で 100 万人以上\n- アクセス:山鉾町 = 四条烏丸~四条河原町 周辺(徒歩圏)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central", "historic_district"],
    lat: 35.003,
    lon: 135.768,
    season_start: "2026-07-01",
    season_end: "2026-07-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.gionmatsuri.or.jp/" },
    tags: ["ancient_festival", "gion_matsuri", "yasaka_jinja", "unesco_2016", "1100_years"],
    source: "manual",
  },
  {
    slug: "kyoto-aoi-matsuri-may",
    category: "entertainment",
    sub_type: "ancient_festival",
    title_zh: "葵祭(5 月 15 日・下鴨+上賀茂神社・京都三大祭の 1・平安王朝行列・1500 年)",
    title_ja: "葵祭",
    romaji: "Aoi Matsuri",
    summary_zh: "**葵祭は京都三大祭の最古祭礼**(5 月 15 日・下鴨神社+上賀茂神社)。古墳時代後期(6 世紀中頃)の起源とされる、500 名+ 騎馬+ 牛車 50 頭の平安王朝装束行列が京都御所→下鴨神社→上賀茂神社を 8 km 巡行。葵紋章を頭飾に飾るため「葵祭」、王朝絵巻の生きた展示として観光価値高。",
    content_md: "- 開催:5 月 15 日(年 1 回)\n- 主催:下鴨神社 + 上賀茂神社\n- 由来:古墳時代後期(6 世紀中頃)疫病鎮圧祈願\n- 京都三大祭:葵祭(5月)+ 祇園祭(7月)+ 時代祭(10月)の 1\n- 主要行事:\n  - 行列(路頭の儀):500 名 + 牛車 + 馬 約 50 頭\n  - ルート:京都御所 → 下鴨神社 → 上賀茂神社(全 8 km)\n  - 装束:平安期王朝装束(冠 + 直衣 + 衣冠 + 十二単)\n- 葵紋章:頭飾に二葉葵を飾る(由来)\n- 観賞料:無料(沿道)・有料席(京都御所 + 下鴨参道)¥2700\n- 動員:沿道に 10-15 万人\n- アクセス:京阪 出町柳駅 + 賀茂御祖神社近隣",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central", "historic_district"],
    lat: 35.039,
    lon: 135.773,
    season_start: "2026-05-15",
    season_end: "2026-05-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ancient_festival", "aoi_matsuri", "kyoto_3_festivals", "heian_court"],
    source: "manual",
  },
  {
    slug: "kyoto-jidai-matsuri-october",
    category: "entertainment",
    sub_type: "ancient_festival",
    title_zh: "時代祭(10 月 22 日・平安神宮・京都三大祭の 1・1895 創始・歴史絵巻行列)",
    title_ja: "時代祭",
    romaji: "Jidai Matsuri",
    summary_zh: "**時代祭は京都三大祭の最年少**(10 月 22 日・平安神宮・1895 創始)。明治 28 年に平安遷都 1100 周年記念に創始、約 2000 名の行列が「明治維新時代→江戸時代→安土桃山時代→室町時代→吉野時代→鎌倉時代→藤原時代→延暦時代」を逆順に時代旅行する歴史絵巻パレード。京都御所→平安神宮の 4.5 km。",
    content_md: "- 開催:10 月 22 日(年 1 回)\n- 主催:平安神宮(1895 平安遷都 1100 周年記念創始)\n- 京都三大祭:葵祭(5月)+ 祇園祭(7月)+ 時代祭(10月)の 1\n- 行列:約 2000 名 + 馬 70 頭\n- 時代逆順:明治維新 → 江戸 → 安土桃山 → 室町 → 吉野 → 鎌倉 → 藤原 → 延暦\n- ルート:京都御所建礼門 → 烏丸通 → 御池通 → 河原町通 → 三条通 → 平安神宮(4.5 km・所要 4 時間)\n- 装束:8 つの時代の正確な歴史装束を再現(衣装研究の生きた展示)\n- 観賞料:無料(沿道)・有料席 ¥2700-3500\n- 動員:沿道 約 6 万人\n- アクセス:地下鉄 丸太町駅 + 烏丸御池駅(沿道)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central", "historic_district"],
    lat: 35.016,
    lon: 135.782,
    season_start: "2026-10-22",
    season_end: "2026-10-22",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ancient_festival", "jidai_matsuri", "kyoto_3_festivals", "heian_jingu_1895"],
    source: "manual",
  },
  {
    slug: "kyoto-railway-museum-2016",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "京都鉄道博物館(2016 開館・梅小路公園・SL 53 両 + 新幹線 0 系・国内最大級鉄道博物館)",
    title_ja: "京都鉄道博物館",
    romaji: "Kyoto Railway Museum",
    summary_zh: "**京都鉄道博物館は国内最大級の鉄道博物館**(梅小路公園・2016 開館・JR 西日本系)。延床面積 30000 m² に SL 53 両(梅小路蒸気機関車館継承)+ 新幹線 0 系 + 500 系 + 在来線特急 26 両を実車展示、SL「義経号」+「C62 形」の動態保存運転(週末)も。子供~鉄道マニアの定番。",
    content_md: "- 開館:2016 年(平成28)4 月 京都\n- 立地:京都市下京区(梅小路公園内)\n- 規模:延床面積 30000 m²(国内最大級)\n- 展示車両:SL 53 両 + 新幹線 0 系・500 系 + 在来線特急 26 両 + 計 80 両以上\n- SL 動態保存:義経号(明治期 1880 年製)+ C62 形 + C53 形 の運転(週末・SL スチーム号)\n- 体験:運転シミュレーター・SL スチーム号乗車(¥300)\n- 入館料:¥1500・小人 ¥500\n- 営業:10:00-17:30\n- 定休:水曜・年末年始\n- 隣接:梅小路公園 + 京都水族館 + 京都市市民防災センター\n- アクセス:JR 嵯峨野線 梅小路京都西駅 徒歩 2 分・JR 京都駅 徒歩 20 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.987,
    lon: 135.738,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["wed"],
    external_urls: { official: "https://www.kyotorailwaymuseum.jp/" },
    tags: ["theme_park", "railway_museum", "2016", "japan_largest", "sl_53"],
    source: "manual",
  },
  {
    slug: "kyoto-manga-museum-2006",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "京都国際マンガミュージアム(2006 開館・元龍池小学校・約 30 万冊・自由閲覧)",
    title_ja: "京都国際マンガミュージアム",
    romaji: "Kyoto Manga Museum",
    summary_zh: "**京都国際マンガミュージアムはマンガ専門の博物館**(2006 開館・元 京都市立龍池小学校 1929 校舎活用)。約 30 万冊の蔵書(明治期~現代)を自由閲覧可能、館内の「マンガの壁」(廊下に蔵書を並べる)で芝生 + 廊下 + 講堂で読み放題。マンガ研究 + 観光客の定番、京都市と京都精華大学が共同運営。",
    content_md: "- 開館:2006 年(平成18)京都\n- 立地:京都市中京区烏丸御池(元 京都市立龍池小学校・1929 建築)\n- 規模:約 30 万冊(明治期~現代)\n- 自由閲覧:全館蔵書を自由に手に取って読める(芝生 + 廊下 + 講堂で読書可)\n- 運営:京都市 + 京都精華大学(国際マンガ研究センター)\n- 入館料:¥900・中高生 ¥400・小学生 ¥200\n- 営業:10:30-17:30\n- 定休:火曜・水曜\n- アクセス:地下鉄烏丸線 烏丸御池駅 直結",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.012,
    lon: 135.760,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: ["tue", "wed"],
    external_urls: { official: "https://kyotomm.jp/" },
    tags: ["theme_park", "manga_museum", "2006", "300000_manga"],
    source: "manual",
  },
  {
    slug: "maizuru-akarenga-park",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "舞鶴赤レンガパーク(明治期 1903 海軍兵器庫 12 棟・国指定重要文化財・近代産業遺産)",
    title_ja: "舞鶴赤レンガパーク",
    romaji: "Maizuru Akarenga Park",
    summary_zh: "**舞鶴赤レンガパークは明治期海軍兵器庫の保存施設**(舞鶴市・1903 完成)。日露戦争前の 1901-1903 に建造された海軍鎮守府の煉瓦倉庫 12 棟(現存)、舞鶴市が 2008 年国指定重要文化財に指定 → 観光施設化。1F 飲食店 + 展示館 + イベントホール、夜のライトアップ(年中)で全国ファイル映え。",
    content_md: "- 完成:1903 年(明治36)舞鶴\n- 用途:旧大日本帝国海軍 舞鶴鎮守府 兵器庫(2,4,5 号)+ 弾薬庫(他)\n- 認定:国指定重要文化財(2008・12 棟)\n- 構成:第 2-5 号棟 + 旧弾薬庫 + 旧造兵廠 等の 12 棟\n- 現代利用:\n  - 第 2 号棟:イベントホール\n  - 第 3 号棟:カフェ + 展示館 + 売店\n  - 第 4 号棟:工房 + ショップ\n- 夜ライトアップ:年中・日没 - 22:00\n- 入場料:無料(展示館 ¥400)\n- 営業:9:00-17:00\n- 定休:無休\n- アクセス:JR 舞鶴線 西舞鶴駅 から市バス 7 分・赤れんがパーク下車",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "舞鶴市",
    lg_code: "26202",
    area_types: ["industrial_heritage", "fishing_port"],
    lat: 35.479,
    lon: 135.380,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://akarenga-park.com/" },
    tags: ["theme_park", "maizuru_akarenga", "1903", "important_cultural_property", "12_buildings"],
    source: "manual",
  },
  {
    slug: "kifune-kawadoko-summer",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "貴船川床(5-9 月限定・渓流席・標高 280m・夏の京都料亭体験)",
    title_ja: "貴船川床",
    romaji: "Kifune Kawadoko",
    summary_zh: "**貴船川床は夏限定の渓流料亭席**(京都市左京区貴船・5-9 月)。鴨川納涼床(中心地・標高 60m)に対して、貴船は標高 280 m の山中渓流真上に席を組む涼しさ別格、川面 30 cm 上の床で京懐石を味わう。料亭「ふじや」「右源太」「兵衛」等 14 軒、1 人 ¥10000-25000(コース料理)で予約必須。",
    content_md: "- 開催:5 月初~9 月末(夏限定・京都の風物詩)\n- 立地:京都市左京区鞍馬貴船町(貴船川渓流沿い)\n- 標高:280 m(京都市内中心地より約 220 m 高)\n- 川面距離:30 cm 上(直接川風 + 渓流音)\n- 主要料亭:14 軒(ふじや・右源太・兵衛・喜多川・佐近・忠兵衛 等)\n- 価格帯:1 人 ¥10000-25000(夏限定懐石)・予約必須(2-3 ヶ月前推奨)\n- 名物料理:川魚(鮎・岩魚・山女)+ 鱧 + 京野菜会席\n- 比較:鴨川納涼床(¥6000-15000)より高価だが、涼しさ + 自然感が圧倒\n- アクセス:叡山電鉄 貴船口駅 から徒歩 30 分 or バス 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_village", "rural_townscape"],
    lat: 35.121,
    lon: 135.762,
    season_start: "2026-05-01",
    season_end: "2026-09-30",
    event_start: null,
    event_end: null,
    price_tier: 5,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["illumination", "kifune_kawadoko", "summer_only", "kyoto_tradition"],
    source: "manual",
  },
  {
    slug: "kurama-yama-hike",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "鞍馬山ハイキング(鞍馬寺~貴船神社・1.5h・牛若丸修行地・新緑+紅葉)",
    title_ja: "鞍馬山~貴船 ハイキング",
    romaji: "Kurama Yama Hike",
    summary_zh: "**鞍馬山ハイキングは京都最人気山間トレイル**(鞍馬寺~貴船神社・約 4 km・1.5 時間)。鞍馬寺(770 創建)~木の根道~奥の院魔王殿~貴船神社の修験道、源義経(牛若丸)が幼少期に修行した地として伝わる。新緑(5 月)+ 紅葉(11 月)が圧巻、叡山電鉄 鞍馬駅から開始 → 貴船口駅で下山する片道コース。",
    content_md: "- 区間:鞍馬寺(鞍馬駅)~貴船神社(貴船口駅)約 4 km\n- 所要:1.5-2 時間(健脚なら 1 時間)\n- 主要見どころ:\n  - 鞍馬寺(770 創建・牛若丸修行地)・本殿+ 義経堂\n  - 木の根道(古杉根が地表に露出する独特の道)\n  - 奥の院 魔王殿(鞍馬山山頂・古代宇宙信仰の地)\n  - 貴船神社(水神を祀る・絵馬発祥)\n- 入山料:鞍馬寺 ¥300・貴船神社 無料\n- 季節:新緑(5 月)+ 紅葉(11 月)が最佳\n- アクセス:叡山電鉄 出町柳駅 → 鞍馬駅(終点・40 分)\n- 帰路:貴船口駅 → 出町柳駅 30 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_village", "shrine_temple"],
    lat: 35.119,
    lon: 135.770,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["theme_park", "kurama_hike", "ushiwaka_maru", "kifune_combo"],
    source: "manual",
  },
  {
    slug: "eizan-cable-hieizan-1925",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "叡山ケーブル・ロープウェイ(1925 開業・八瀬比叡山口 ↔ 比叡山頂・桜紅葉絶景)",
    title_ja: "叡山ケーブル・ロープウェイ",
    romaji: "Eizan Cable",
    summary_zh: "**叡山ケーブル・ロープウェイは比叡山アクセスの主役**(1925 開業)。八瀬比叡山口駅 → ケーブル比叡駅 → 比叡山頂駅 の 2 段階で約 460m を登る、ケーブル + ロープウェイ連絡。京都側からの比叡山延暦寺アクセス、桜(4 月)+ 紅葉(11 月)が車窓絶景。",
    content_md: "- 開業:1925 年(大正14)\n- 区間:八瀬比叡山口駅 → ケーブル比叡駅(ケーブルカー・1.3 km)→ 比叡山頂駅(ロープウェイ・0.5 km)\n- 高低差:約 460 m(京都市内 → 比叡山頂)\n- 所要:ケーブル 9 分 + ロープウェイ 3 分\n- 運賃:ケーブル往復 ¥1100・ロープウェイ往復 ¥630\n- セット:ケーブル + ロープウェイ往復 ¥1700\n- 季節:桜(4 月初)+ 新緑(5 月)+ 紅葉(11 月)が圧倒的車窓絶景\n- 比叡山頂:延暦寺 + 比叡山ガーデンミュージアム + 京都市夜景\n- アクセス:叡山電鉄 八瀬比叡山口駅 徒歩 5 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_village", "luxury_resort"],
    lat: 35.062,
    lon: 135.823,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://eizandensha.co.jp/" },
    tags: ["theme_park", "eizan_cable", "1925", "hieizan", "ropeway"],
    source: "manual",
  },
  {
    slug: "kyoto-station-rooftop-garden",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "京都駅ビル空中經路(1997・原広司設計・無料屋上散策路・京都タワー絶景)",
    title_ja: "京都駅ビル 空中経路",
    romaji: "Kyoto Station Rooftop",
    summary_zh: "**京都駅ビル空中経路は無料の屋上絶景散策路**(1997 開業・原広司設計)。京都駅ビル(高さ 60 m・近代日本建築の代表)の 11F~大階段~屋上 を結ぶ歩行通路、京都タワー + 京都市内+ 東山連峰 を一望できる無料夜景スポット。「グレートステアズ」の幅 35m 大階段は映画ロケ地多数、現代建築の聖地。",
    content_md: "- 開業:1997 年(平成9)京都駅ビル開業時から\n- 設計:原広司(京都駅ビル全体・近代日本建築代表作)\n- 構造:京都駅ビル 11F → 大階段(170 段)→ 屋上「空中経路」(全長 147m)\n- 入場料:**無料**\n- 営業:10:00-22:00\n- 絶景:京都タワー + 京都市内 + 東山連峰 + 西山連峰\n- 大階段「グレートステアズ」:幅 35m・171 段・夜にイルミネーション\n- 映画ロケ:数十作品で使用(風の谷のナウシカ実写化候補地・千と千尋…候補)\n- アクセス:JR 京都駅 直結",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.985,
    lon: 135.758,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["illumination", "kyoto_station_rooftop", "1997", "hara_hiroshi", "free"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[kyoto-entertainment] 尚無條目");
    return;
  }
  console.log(`[kyoto-entertainment] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(24)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch, { onConflict: "slug" });
    if (error) {
      console.error("[kyoto-entertainment] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[kyoto-entertainment] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[kyoto-entertainment] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
