// Seed 群馬県 住 R1(20 筆 / Sprint 1.3)
// 草津+伊香保+万座+水上+四万+老神+ホテル代表

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "群馬県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  { slug: "kusatsu-onsen-japan-3", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "草津温泉(吾妻郡草津町・推定 1500+ 年湯治場+ 日本三名泉(草津+下呂+有馬)+ 自然湧出量 No.1・毎分 4 万 L+ 全 100+ 軒旅館・湯畑+西の河原+ 1 泊 2 食 ¥15,500-45,000+ 国際観光客代表)", title_ja: "草津温泉", romaji: "Kusatsu Onsen", summary_zh: "**草津温泉は推定 1500+ 年湯治場・日本三名泉・自然湧出量 No.1 毎分 4 万 L**(草津・**全 100+ 軒**)。湯畑+西の河原、¥15,500-45,000、国際観光客代表。", content_md: "- 立地:**吾妻郡草津町**\n- 起源:**推定 1500+ 年湯治場**\n- 認定:**日本三名泉(草津 + 下呂 + 有馬) + 自然湧出量 No.1 毎分 4 万 L**\n- 規模:**全 100+ 軒旅館**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["onsen_field"], lat: 36.6228, lon: 138.5969, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["kusatsu_onsen", "japan_3", "no1_volume"], source: "manual" },
  { slug: "ikaho-onsen-1900", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "伊香保温泉(渋川市伊香保・1900 大正期改修石段街+ 万葉集記載 1300+ 年伝承+ 黄金の湯+白銀の湯 2 源泉+ 全 60+ 軒+ 365 段石段街観光中核+ 1 泊 2 食 ¥12,500-32,000+ 国内+海外観光客代表)", title_ja: "伊香保温泉", romaji: "Ikaho Onsen", summary_zh: "**伊香保温泉は 1900 大正期改修石段街・万葉集記載 1300+ 年伝承**(渋川・**黄金の湯+白銀の湯 2 源泉・全 60+ 軒**)。365 段石段街観光中核、¥12,500-32,000、国内+海外観光客代表。", content_md: "- 立地:**渋川市伊香保**\n- 起源:**万葉集記載 1300+ 年伝承 + 1900 大正期改修**\n- 規模:**全 60+ 軒 + 365 段石段街**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["onsen_field"], lat: 36.4886, lon: 138.9242, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["ikaho_onsen", "1300_years", "365_steps"], source: "manual" },
  { slug: "manza-onsen-1800m", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "万座温泉(吾妻郡嬬恋村・標高 1800m 国内最高所級温泉+ 江戸期発見・現代開発 1932・全 6+ 軒・草津白根山系硫黄泉+乳白色源泉・1 泊 2 食 ¥18,500-35,000+ R1 育 草津白根観光連動)", title_ja: "万座温泉", romaji: "Manza Onsen", summary_zh: "**万座温泉は標高 1800m 国内最高所級温泉・江戸期発見・1932 開発**(嬬恋・**全 6+ 軒・硫黄泉+乳白色**)。¥18,500-35,000、R1 育 草津白根観光連動。", content_md: "- 立地:**吾妻郡嬬恋村**\n- 規模:**標高 1800m 国内最高所級温泉**\n- 起源:**江戸期発見 + 1932 現代開発**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "嬬恋村", lg_code: "10425", area_types: ["onsen_field", "scenic_spot"], lat: 36.6322, lon: 138.5044, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["manza_onsen", "1800m", "1932"], source: "manual" },
  { slug: "minakami-onsen-village", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "水上温泉郷(利根郡みなかみ町・1200+ 年伝承+ 谷川温泉+水上温泉+宝川温泉+湯檜曽温泉 4 大+ 全 80+ 軒+ R1 育 谷川岳+R1 楽 みなかみラフティング観光連動+ 1 泊 2 食 ¥10,500-28,000)", title_ja: "水上温泉郷", romaji: "Minakami Onsen", summary_zh: "**水上温泉郷は 1200+ 年伝承・谷川+水上+宝川+湯檜曽 4 大温泉**(みなかみ・**全 80+ 軒**)。R1 育 谷川岳+R1 楽 ラフティング、¥10,500-28,000。", content_md: "- 立地:**利根郡みなかみ町**\n- 起源:**1200+ 年伝承**\n- 規模:**全 80+ 軒・水上 + 谷川 + 宝川 + 湯檜曽 4 大**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["onsen_field"], lat: 36.7847, lon: 138.9558, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["minakami_onsen", "4_groups"], source: "manual" },
  { slug: "shima-onsen-1563", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "四万温泉(吾妻郡中之条町・永禄 6 年 1563 開湯 462 年+ 国民保養温泉地第 1 号 1954+ 「日本秘湯を守る会」+ 全 30+ 軒・温泉街レトロ景観+ R1 育 四万ブルー観光連動+ 1 泊 2 食 ¥12,500-25,000)", title_ja: "四万温泉", romaji: "Shima Onsen", summary_zh: "**四万温泉は永禄 6 年 1563 開湯 462 年・国民保養温泉地第 1 号 1954**(中之条・**全 30+ 軒・「日本秘湯を守る会」**)。R1 育 四万ブルー、¥12,500-25,000。", content_md: "- 立地:**吾妻郡中之条町**\n- 起源:**永禄 6 年 1563 開湯 462 年**\n- 認定:**国民保養温泉地第 1 号 1954**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "中之条町", lg_code: "10421", area_types: ["onsen_field"], lat: 36.6628, lon: 138.7708, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["shima_onsen", "1563", "462_years", "no1_kokumin"], source: "manual" },
  { slug: "oigami-onsen-1300", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "老神温泉(沼田市利根町・伝説 1185+ 年源頼朝伝来+ 全 12+ 軒小規模旅館+ 上州武尊山系・国民保養温泉地・5 月恐ろしい大蛇祭・1 泊 2 食 ¥9,500-18,500+ R1 食 沼田りんご観光連動)", title_ja: "老神温泉", romaji: "Oigami Onsen", summary_zh: "**老神温泉は 1185+ 年源頼朝伝来・全 12+ 軒小規模旅館**(沼田・**国民保養温泉地・5 月恐ろしい大蛇祭**)。¥9,500-18,500、R1 食 沼田りんご観光連動。", content_md: "- 立地:**沼田市利根町**\n- 起源:**1185+ 年源頼朝伝来**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "沼田市", lg_code: "10206", area_types: ["onsen_field"], lat: 36.7186, lon: 139.2147, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["oigami_onsen", "1185"], source: "manual" },
  { slug: "hoshi-onsen-1875", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "法師温泉長壽館(利根郡みなかみ町・明治 8 年 1875 創業 150 年+ 国登録有形文化財 1994 法師乃湯混浴大風呂+ 「日本秘湯を守る会」会員筆頭+ 全 35 室・1 泊 2 食 ¥18,500-35,000+ 海外秘湯ファン代表)", title_ja: "法師温泉長壽館", romaji: "Hōshi Onsen", summary_zh: "**法師温泉長壽館は明治 8 年 1875 創業 150 年・国登録有形文化財 1994・法師乃湯混浴大風呂**(みなかみ・**「日本秘湯を守る会」会員筆頭**)。¥18,500-35,000、海外秘湯ファン代表。", content_md: "- 立地:**利根郡みなかみ町**\n- 起源:**明治 8 年 1875 創業 150 年**\n- 認定:**国登録有形文化財 1994 + 「日本秘湯を守る会」筆頭**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["onsen_field", "history_site_castle"], lat: 36.7944, lon: 138.7572, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: 120, closed_days: [], external_urls: {}, tags: ["hoshi_onsen", "1875", "150_years"], source: "manual" },
  { slug: "kusatsu-hotel-classic", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "草津温泉ホテル一井+望雲(吾妻郡草津町・1622 江戸期創業 老舗・全 200-300 室・草津湯畑直結・伝統+モダン融合+ R1 食 草津温泉まんじゅう+R1 食 上州牛会席・1 泊 2 食 ¥18,500-45,000)", title_ja: "草津ホテル一井+望雲", romaji: "Kusatsu Classic Hotel", summary_zh: "**草津温泉ホテル一井+望雲は 1622 江戸期創業老舗・全 200-300 室**(草津湯畑直結・**伝統+モダン**)。R1 食 まんじゅう+上州牛会席、¥18,500-45,000。", content_md: "- 立地:**吾妻郡草津町**(湯畑直結)\n- 起源:**1622 江戸期創業老舗**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["onsen_field"], lat: 36.6228, lon: 138.5969, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["kusatsu_classic", "1622"], source: "manual" },
  { slug: "ikaho-grand-hotel-class", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "伊香保グランドホテル+伊香保温泉ホテルクラス(渋川市伊香保・1955-1990 年代開業大型・全 150-450 室・R1 住 伊香保温泉派生・展望大浴場・R1 食 水沢うどん+湯の花まんじゅう会席・1 泊 2 食 ¥12,500-28,000)", title_ja: "伊香保グランド+ホテル", romaji: "Ikaho Grand Hotel", summary_zh: "**伊香保グランドホテル+伊香保温泉ホテルは 1955-1990 年代開業大型・全 150-450 室**(渋川・**展望大浴場+R1 食 水沢うどん+湯の花まんじゅう**)。¥12,500-28,000。", content_md: "- 立地:**渋川市伊香保**\n- 起源:**1955-1990 年代開業**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["onsen_field"], lat: 36.4886, lon: 138.9242, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["ikaho_grand"], source: "manual" },
  { slug: "manza-prince-1965", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "万座プリンスホテル(吾妻郡嬬恋村・1965 開業 60 年+ 標高 1800m 国内最高所級リゾートホテル・全 270 室+ R1 住 万座温泉派生・スキー+夏期高原リゾート・1 泊 2 食 ¥18,500-35,000+ 海外観光客 SNS 拡散代表)", title_ja: "万座プリンス", romaji: "Manza Prince", summary_zh: "**万座プリンスホテルは 1965 開業 60 年・標高 1800m 国内最高所級リゾート・全 270 室**(嬬恋・**スキー+夏期高原リゾート**)。¥18,500-35,000、海外 SNS 拡散代表。", content_md: "- 立地:**吾妻郡嬬恋村**\n- 起源:**1965 開業 60 年**\n- 規模:**標高 1800m + 全 270 室**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "嬬恋村", lg_code: "10425", area_types: ["onsen_field", "scenic_spot"], lat: 36.6322, lon: 138.5044, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["manza_prince", "1965"], source: "manual" },
  { slug: "takasaki-business-cluster", category: "lodging", sub_type: "gunma_mito_chuou", title_zh: "高崎駅周辺ビジネスホテル群(高崎市・JR 高崎駅西口+東口+ 全国チェーン+地元 15+ 軒+ R1 行 上越+北陸新幹線+JR 高崎線+ R1 食 高崎ハム+R1 衣 高崎達磨観光客向け+ 1 泊朝食付 ¥7,500-12,500)", title_ja: "高崎駅周辺ビジネス", romaji: "Takasaki Business", summary_zh: "**高崎駅周辺ビジネスホテル群は JR 高崎駅西口+東口・全国チェーン+地元 15+ 軒**(高崎・**R1 行 新幹線接続**)。R1 食 高崎ハム+R1 衣 達磨、¥7,500-12,500。", content_md: "- 立地:**高崎市**(JR 高崎駅周辺)\n- 規模:**全国チェーン + 地元 15+ 軒**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["shopping_district"], lat: 36.3219, lon: 139.0033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["takasaki_business"], source: "manual" },
  { slug: "maebashi-plaza-hotel", category: "lodging", sub_type: "gunma_mito_chuou", title_zh: "前橋プラザホテル+ホテルメトロポリタン高崎(前橋+高崎・1973-2010 年代開業・県内シティホテル代表・全 200-450 室+ R1 衣 けやきウォーク前橋+前橋公園観光・1 泊 ¥9,500-15,500)", title_ja: "前橋プラザ+メトロポリタン高崎", romaji: "Maebashi Plaza", summary_zh: "**前橋プラザホテル+ホテルメトロポリタン高崎は 1973-2010 年代開業・県内シティホテル代表**(前橋+高崎・**全 200-450 室**)。R1 衣 けやきウォーク+前橋公園、¥9,500-15,500。", content_md: "- 立地:**前橋市 + 高崎市**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["shopping_district"], lat: 36.3895, lon: 139.0635, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["maebashi_plaza"], source: "manual" },
  { slug: "minakami-glamping-2018", category: "lodging", sub_type: "gunma_other_onsen", title_zh: "みなかみグランピング+ Forest Resort(利根郡みなかみ町・2018-2024 開発・グランピング+ロッジ・全 25+ 軒+ R1 楽 ラフティング+R1 食 ヤマメ釣り+R1 育 谷川岳観光連動・1 泊 ¥22,000-45,000+ 海外 SNS 拡散代表)", title_ja: "みなかみグランピング", romaji: "Minakami Glamping", summary_zh: "**みなかみグランピング+Forest Resort は 2018-2024 開発・全 25+ 軒**(みなかみ・**R1 楽 ラフティング+R1 食 ヤマメ+R1 育 谷川岳**)。¥22,000-45,000、海外 SNS 拡散代表。", content_md: "- 立地:**利根郡みなかみ町**\n- 起源:**2018-2024 開発**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["scenic_spot"], lat: 36.7847, lon: 138.9558, season_start: "2026-04-01", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["minakami_glamping"], source: "manual" },
  { slug: "yumura-onsen-modern", category: "lodging", sub_type: "gunma_other_onsen", title_zh: "湯宿温泉+猿ヶ京温泉(利根郡みなかみ町・1185 平安期発見・全 12+ 軒小規模旅館・R1 住 水上温泉郷の姉妹温泉・関越自動車道月夜野 IC 近接・R1 楽 ラフティング+猿ヶ京観光連動・¥9,500-18,500)", title_ja: "湯宿+猿ヶ京温泉", romaji: "Yumura Sarugakyo", summary_zh: "**湯宿温泉+猿ヶ京温泉は 1185 平安期発見・全 12+ 軒小規模旅館**(みなかみ・**R1 住 水上姉妹+月夜野 IC 近接**)。R1 楽 ラフティング、¥9,500-18,500。", content_md: "- 立地:**利根郡みなかみ町**\n- 起源:**1185 平安期発見**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["onsen_field"], lat: 36.7733, lon: 138.9050, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["yumura_sarugakyo"], source: "manual" },
  { slug: "kawaba-pension-village", category: "lodging", sub_type: "gunma_other_onsen", title_zh: "川場ペンション村+リゾート(利根郡川場村・1980-2010 年代開発・全 15+ 軒小規模ペンション+ロッジ+ R1 食 永井酒造 1886 +土田酒造 1907 観光連動+ 1 泊 2 食 ¥10,500-22,000)", title_ja: "川場ペンション村", romaji: "Kawaba Pension", summary_zh: "**川場ペンション村+リゾートは 1980-2010 年代開発・全 15+ 軒小規模**(川場・**R1 食 永井 1886+土田 1907 観光連動**)。¥10,500-22,000。", content_md: "- 立地:**利根郡川場村**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "川場村", lg_code: "10448", area_types: ["scenic_spot"], lat: 36.6644, lon: 139.0719, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["kawaba_pension"], source: "manual" },
  { slug: "numata-business-hotel", category: "lodging", sub_type: "gunma_mito_chuou", title_zh: "沼田ビジネスホテル+ R1 住 老神温泉接続(沼田市・全国チェーン+地元 4+ 軒・JR 上越線沼田駅+関越道沼田 IC 周辺+ R1 食 沼田りんご+R1 住 老神温泉観光客向け+ 1 泊朝食付 ¥6,500-10,500)", title_ja: "沼田ビジネス", romaji: "Numata Business", summary_zh: "**沼田ビジネスホテルは全国チェーン+地元 4+ 軒**(JR 沼田駅+関越道沼田 IC・**R1 食 沼田りんご+R1 住 老神温泉観光**)。¥6,500-10,500。", content_md: "- 立地:**沼田市**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "沼田市", lg_code: "10206", area_types: ["shopping_district"], lat: 36.6453, lon: 139.0444, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["numata_business"], source: "manual" },
  { slug: "takaragawa-onsen-rotenburo", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "宝川温泉汪泉閣(利根郡みなかみ町・1923 創業 102 年+ 全国露天風呂面積 No.1 級 470 ㎡・全 36 室+ 「日本の秘湯」+ ナショナルジオグラフィック日本の秘湯 100 選筆頭・1 泊 2 食 ¥18,500-35,000+ 海外秘湯ファン代表)", title_ja: "宝川温泉汪泉閣", romaji: "Takaragawa Onsen", summary_zh: "**宝川温泉汪泉閣は 1923 創業 102 年・全国露天風呂面積 No.1 級 470 ㎡**(みなかみ・**全 36 室・ナショジオ日本の秘湯 100 選筆頭**)。¥18,500-35,000、海外秘湯ファン代表。", content_md: "- 立地:**利根郡みなかみ町宝川**\n- 起源:**1923 創業 102 年**\n- 認定:**全国露天風呂面積 No.1 級 470 ㎡**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["onsen_field", "scenic_spot"], lat: 36.8228, lon: 139.0561, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: 120, closed_days: [], external_urls: {}, tags: ["takaragawa_onsen", "1923", "no1_rotenburo"], source: "manual" },
  { slug: "kusatsu-modern-resort", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "草津 ベルツ温泉+ザ・草津スパ(吾妻郡草津町・2018-2024 リノベ・モダン高級ホテル・5+ 軒・R1 住 草津温泉派生・大浴場+貸切露天+ R1 食 上州牛会席・1 泊 2 食 ¥35,000-85,000+ 海外 VIP 観光客代表)", title_ja: "草津モダンリゾート", romaji: "Kusatsu Modern Resort", summary_zh: "**草津 ベルツ温泉+ザ・草津スパは 2018-2024 リノベ・モダン高級ホテル 5+ 軒**(草津・**大浴場+貸切露天+R1 食 上州牛会席**)。¥35,000-85,000、海外 VIP 観光客代表。", content_md: "- 立地:**吾妻郡草津町**\n- 起源:**2018-2024 リノベ**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["onsen_field"], lat: 36.6228, lon: 138.5969, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["kusatsu_modern"], source: "manual" },
  { slug: "ikaho-bunjin-villa", category: "lodging", sub_type: "gunma_kaigan_onsen", title_zh: "伊香保 河鹿橋+文人別邸(渋川市伊香保・1900-1930 年代徳富蘆花+竹久夢二+萩原朔太郎ゆかり別邸+ 全 8+ 軒文学的滞在+ R1 衣 石段街+R1 育 伊香保観光連動+ 1 泊 2 食 ¥22,000-45,000)", title_ja: "伊香保文人別邸", romaji: "Ikaho Bunjin Villa", summary_zh: "**伊香保 河鹿橋+文人別邸は 1900-1930 年代徳富蘆花+竹久夢二+萩原朔太郎ゆかり別邸・全 8+ 軒文学的滞在**(渋川)。R1 衣 石段街+R1 育 伊香保連動、¥22,000-45,000。", content_md: "- 立地:**渋川市伊香保**\n- 起源:**1900-1930 年代文人別邸**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["onsen_field", "history_site_castle"], lat: 36.4886, lon: 138.9242, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["ikaho_bunjin"], source: "manual" },
  { slug: "tone-river-tonegawa-yado", category: "lodging", sub_type: "gunma_other_onsen", title_zh: "利根川 水沿いの宿+前橋ホテル(前橋市+渋川+沼田・利根川+片品川流域・1990-2020 年代開発・河川眺望ホテル+ペンション・15+ 軒+ R1 育 利根川あゆ+R1 楽 利根川下り観光連動+ ¥9,500-18,500)", title_ja: "利根川水沿いの宿", romaji: "Tonegawa Yado", summary_zh: "**利根川水沿いの宿+前橋ホテルは 1990-2020 年代開発・河川眺望ホテル+ペンション 15+ 軒**(前橋+渋川+沼田・**R1 育 利根川あゆ+R1 楽 利根川下り**)。¥9,500-18,500。", content_md: "- 立地:**前橋市 + 渋川市 + 沼田市**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["scenic_spot"], lat: 36.3895, lon: 139.0635, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["tonegawa_yado"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[gunma-lodging-r1] 尚無條目"); return; }
  console.log(`[gunma-lodging-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) return;
  const sb = createAdminClient();
  const { error } = await sb.from("japan_entries").upsert(rows as any, { onConflict: "slug" });
  if (error) { console.error("[gunma-lodging-r1] upsert failed:", error); process.exit(1); }
  console.log(`[gunma-lodging-r1] Done — ${rows.length} rows.`);
}
main().catch((err) => { console.error(err); process.exit(1); });
