// Seed 群馬県 衣 R1(18 筆 / Sprint 1.2)
// 高崎達磨+桐生織+富岡シルク+伊勢崎銘仙+百貨店+SC+グッズ

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "群馬県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  { slug: "takasaki-daruma-no1-80", category: "fashion", sub_type: "gunma_daruma", title_zh: "高崎達磨(高崎市・元禄 10 年 1697 創業 328 年+ 全国達磨生産量 No.1 県・80% シェア+ 少林山達磨寺由来+ 県伝統工芸品+ 紅白達磨+合格達磨+選挙達磨・1 個 ¥1,500-15,000+ 全国正月縁起物代表)", title_ja: "高崎達磨", romaji: "Takasaki Daruma", summary_zh: "**高崎達磨は元禄 10 年 1697 創業 328 年・全国達磨生産量 No.1 県・80% シェア**(高崎・**少林山達磨寺由来・県伝統工芸品**)。¥1,500-15,000、全国正月縁起物代表。", content_md: "- 立地:**高崎市**\n- 起源:**元禄 10 年 1697 創業 328 年**\n- 認定:**全国達磨生産量 No.1 県・80% シェア + 少林山達磨寺由来 + 県伝統工芸品**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["craft_workshop"], lat: 36.3219, lon: 139.0033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["takasaki_daruma", "1697", "no1_japan", "80_percent"], source: "manual" },
  { slug: "kiryu-ori-1300", category: "fashion", sub_type: "gunma_kiryu_ori", title_zh: "桐生織(桐生市・714 創始 1311 年伝承+ 国指定伝統的工芸品 1977+ 「西の西陣・東の桐生」+ 京西陣と並ぶ日本二大織物・現役 100+ 工房+ JR 桐生駅+全国百貨店流通+ 1 反 ¥35,000-450,000)", title_ja: "桐生織", romaji: "Kiryū Ori", summary_zh: "**桐生織は 714 創始 1311 年伝承・国指定伝統的工芸品 1977・「西の西陣・東の桐生」**(桐生・**現役 100+ 工房**)。¥35,000-450,000/反、全国百貨店。", content_md: "- 立地:**桐生市**\n- 起源:**714 創始 1311 年伝承**\n- 認定:**国指定伝統的工芸品 1977 + 「西の西陣・東の桐生」**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "桐生市", lg_code: "10203", area_types: ["craft_workshop"], lat: 36.4044, lon: 139.3306, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kiryu_ori", "714", "1311_years", "1977_designated"], source: "manual" },
  { slug: "tomioka-silk-products", category: "fashion", sub_type: "gunma_silk", title_zh: "富岡シルク製品(富岡市・R1 育 富岡製糸場 1872 UNESCO 2014 派生・絹スカーフ+ストール+ 着物+ Tシャツ+雑貨+ R1 食 富岡シルク饅頭観光連動+ 国際観光客代表土産+ ¥3,500-25,000)", title_ja: "富岡シルク製品", romaji: "Tomioka Silk", summary_zh: "**富岡シルク製品は R1 育 富岡製糸場 1872 UNESCO 2014 派生**(絹スカーフ+ストール+着物+T シャツ+雑貨)。R1 食 シルク饅頭連動、¥3,500-25,000、国際観光客代表土産。", content_md: "- 立地:**富岡市**\n- 関係:**R1 育 富岡製糸場 1872 UNESCO 2014 派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "富岡市", lg_code: "10210", area_types: ["craft_workshop", "shopping_district"], lat: 36.2575, lon: 138.8939, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tomioka_silk"], source: "manual" },
  { slug: "isesaki-meisen-edo", category: "fashion", sub_type: "gunma_silk", title_zh: "伊勢崎銘仙(伊勢崎市・大正期 1910-1930 年代モダン絹織物・群馬絹織物 4 大 一・大胆幾何学+大正ロマン柄+ 県伝統工芸品+ 現代復刻 着物+雑貨+ R1 衣 桐生織と並ぶ絹文化代表・¥45,000-180,000)", title_ja: "伊勢崎銘仙", romaji: "Isesaki Meisen", summary_zh: "**伊勢崎銘仙は大正期 1910-1930 年代モダン絹織物・群馬絹織物 4 大 一**(伊勢崎・**大胆幾何学+大正ロマン柄・県伝統工芸品**)。R1 衣 桐生織並ぶ絹文化代表、¥45,000-180,000。", content_md: "- 立地:**伊勢崎市**\n- 起源:**大正期 1910-1930 年代**\n- 認定:**群馬絹織物 4 大の一 + 県伝統工芸品**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "伊勢崎市", lg_code: "10204", area_types: ["craft_workshop"], lat: 36.3119, lon: 139.1969, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["isesaki_meisen", "taisho_era"], source: "manual" },
  { slug: "kiryu-merrias-knit", category: "fashion", sub_type: "gunma_kiryu_ori", title_zh: "桐生メリヤス+ニット(桐生市・1900 年代開発・桐生織派生メリヤス・ニット工業発展・全国 4 大ニット産地一+ 現代化 T シャツ+セーター+靴下・JR 桐生駅+全国百貨店流通+ ¥1,500-15,000)", title_ja: "桐生メリヤス", romaji: "Kiryu Merrias", summary_zh: "**桐生メリヤス+ニットは 1900 年代開発・桐生織派生・全国 4 大ニット産地の一**(桐生・**T シャツ+セーター+靴下**)。JR 桐生駅+全国百貨店、¥1,500-15,000。", content_md: "- 立地:**桐生市**\n- 起源:**1900 年代開発**\n- 関係:**R1 衣 桐生織派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "桐生市", lg_code: "10203", area_types: ["craft_workshop"], lat: 36.4044, lon: 139.3306, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kiryu_merrias"], source: "manual" },
  { slug: "takasaki-takashimaya", category: "fashion", sub_type: "gunma_dept_store", title_zh: "髙島屋高崎店+前橋スズラン百貨店(高崎+前橋・1980-2000 年代開業・県内老舗百貨店 2 大+ R1 食 上州牛+下仁田ねぎ+水沢うどん+焼まんじゅう+R1 衣 高崎達磨集約+ JR 高崎駅+前橋駅 連動)", title_ja: "髙島屋高崎+スズラン", romaji: "Takashimaya Suzuran", summary_zh: "**髙島屋高崎店+前橋スズラン百貨店は 1980-2000 年代開業・県内老舗 2 大**(高崎+前橋・**R1 食+R1 衣 集約**)。JR 高崎駅+前橋駅連動。", content_md: "- 立地:**高崎市 + 前橋市**\n- 起源:**1980-2000 年代開業**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["shopping_district"], lat: 36.3219, lon: 139.0033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["takashimaya_takasaki"], source: "manual" },
  { slug: "maebashi-keyaki-walk-sc", category: "fashion", sub_type: "gunma_dept_store", title_zh: "けやきウォーク前橋(前橋市・2007 開業 18 年+ 県内最大級 SC 200+ 店舗+ 全 4 階+映画館+飲食+ JR 前橋駅徒歩 12 分+ R1 食 焼まんじゅう+R1 衣 高崎達磨集約+ 地元観光客代表)", title_ja: "けやきウォーク前橋", romaji: "Keyaki Walk", summary_zh: "**けやきウォーク前橋は 2007 開業 18 年・県内最大級 SC 200+ 店舗**(前橋・**全 4 階+映画館+飲食**)。JR 前橋駅徒歩 12 分、R1 食+R1 衣 集約、地元観光客代表。", content_md: "- 立地:**前橋市**\n- 起源:**2007 開業 18 年**\n- 規模:**県内最大級 SC 200+ 店舗**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["shopping_district"], lat: 36.3856, lon: 139.0586, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["keyaki_walk", "2007", "200_shops"], source: "manual" },
  { slug: "takasaki-opa-2017", category: "fashion", sub_type: "gunma_dept_store", title_zh: "高崎オーパ+ JR 高崎駅 SC(高崎市・2017 開業 8 年+ JR 高崎駅直結+ 全 6 階 200+ 店舗+ 国際ブランド+ファストファッション+ R1 食 高崎ハム+R1 衣 高崎達磨売店+ 観光客向け代表 SC)", title_ja: "高崎オーパ", romaji: "Takasaki OPA", summary_zh: "**高崎オーパ+JR 高崎駅 SC は 2017 開業 8 年・JR 直結・全 6 階 200+ 店舗**(国際ブランド+ファストファッション)。R1 食 高崎ハム+R1 衣 達磨売店、観光客代表 SC。", content_md: "- 立地:**高崎市**(JR 高崎駅直結)\n- 起源:**2017 開業 8 年**\n- 規模:**全 6 階 200+ 店舗**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["shopping_district"], lat: 36.3219, lon: 139.0033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["takasaki_opa", "2017"], source: "manual" },
  { slug: "ota-aeon-mall", category: "fashion", sub_type: "gunma_dept_store", title_zh: "イオンモール太田(太田市・2007 開業 18 年+ 県東最大 SC 220+ 店舗+ 全 3 階+映画館+ R1 食 高崎ハム+群馬野菜直売連動+ R1 行 東武太田駅周辺+ 県東観光客代表 SC)", title_ja: "イオンモール太田", romaji: "Aeon Ōta", summary_zh: "**イオンモール太田は 2007 開業 18 年・県東最大 SC 220+ 店舗**(太田・**全 3 階+映画館+R1 食+R1 行 東武太田駅**)。県東観光客代表 SC。", content_md: "- 立地:**太田市**\n- 起源:**2007 開業 18 年**\n- 規模:**県東最大 SC 220+ 店舗**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "太田市", lg_code: "10205", area_types: ["shopping_district"], lat: 36.2900, lon: 139.3756, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aeon_ota"], source: "manual" },
  { slug: "yamada-denki-hq", category: "fashion", sub_type: "gunma_dept_store", title_zh: "ヤマダデンキ本店 LABI 高崎(高崎市・1973 創業 52 年+ 全国家電量販店 No.1+ ヤマダ発祥地・高崎本社+ JR 高崎駅前 LABI 高崎+ 全国 1100+ 店舗+ 群馬経済代表+ 観光客向け SC 観賞代表)", title_ja: "ヤマダ電機本店", romaji: "Yamada Denki HQ", summary_zh: "**ヤマダデンキ本店 LABI 高崎は 1973 創業 52 年・全国家電量販店 No.1・高崎本社**(JR 高崎駅前 LABI・**全国 1100+ 店舗**)。群馬経済代表、観光客向け代表。", content_md: "- 立地:**高崎市**(JR 高崎駅前)\n- 起源:**1973 創業 52 年**\n- 認定:**全国家電量販店 No.1 + 高崎本社**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["shopping_district"], lat: 36.3219, lon: 139.0033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yamada_denki", "1973", "no1_japan"], source: "manual" },
  { slug: "kusatsu-yubatake-shop", category: "fashion", sub_type: "gunma_dept_store", title_zh: "草津湯畑商店街(吾妻郡草津町・R1 住 草津温泉日本三名泉派生・湯畑周辺商店街 50+ 軒+ R1 食 草津まんじゅう+ 浴衣+温泉グッズ+ ¥350-3,500+ 海外観光客 SNS 拡散代表)", title_ja: "草津湯畑商店街", romaji: "Kusatsu Yubatake Shop", summary_zh: "**草津湯畑商店街は R1 住 草津温泉派生・湯畑周辺 50+ 軒**(草津・**R1 食 草津まんじゅう+浴衣+温泉グッズ**)。¥350-3,500、海外 SNS 拡散代表。", content_md: "- 立地:**吾妻郡草津町**\n- 関係:**R1 住 草津温泉派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["shopping_district", "onsen_field"], lat: 36.6228, lon: 138.5969, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kusatsu_shopping"], source: "manual" },
  { slug: "ikaho-ishidan-shop-365", category: "fashion", sub_type: "gunma_dept_store", title_zh: "伊香保石段街土産通り(渋川市伊香保・1903 大正期改修・現在 365 段石段街+ 30+ 軒土産屋+ R1 食 湯の花まんじゅう+R1 食 水沢うどん集約+ R1 住 伊香保温泉観光客代表+ ¥350-3,500)", title_ja: "伊香保石段街", romaji: "Ikaho Ishidan", summary_zh: "**伊香保石段街土産通りは 1903 大正期改修・365 段石段街**(渋川伊香保・**30+ 軒土産屋**)。R1 食 湯の花+R1 食 水沢うどん集約、R1 住 伊香保温泉、¥350-3,500。", content_md: "- 立地:**渋川市伊香保**\n- 起源:**1903 大正期改修**\n- 規模:**365 段石段街 + 30+ 軒土産屋**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["shopping_district", "onsen_field"], lat: 36.4886, lon: 138.9242, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ikaho_ishidan", "365_steps"], source: "manual" },
  { slug: "tomioka-museum-shop-unesco", category: "fashion", sub_type: "gunma_silk", title_zh: "富岡製糸場ミュージアムショップ(富岡市・R1 育 富岡製糸場 1872 UNESCO 2014 派生・公式絹製品+T シャツ+ぬいぐるみ+書籍+ 入場料 ¥1,000+ 国際観光客向け世界遺産公式土産代表)", title_ja: "富岡製糸 Shop", romaji: "Tomioka Museum Shop", summary_zh: "**富岡製糸場ミュージアムショップは R1 育 1872 UNESCO 2014 派生**(公式絹製品+T シャツ+ぬいぐるみ+書籍)。¥1,000、国際観光客向け世界遺産公式土産代表。", content_md: "- 立地:**富岡市**\n- 関係:**R1 育 富岡製糸場 1872 UNESCO 2014 派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "富岡市", lg_code: "10210", area_types: ["shopping_district", "history_site_castle"], lat: 36.2575, lon: 138.8939, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tomioka_shop_unesco"], source: "manual" },
  { slug: "gunma-chan-fashion", category: "fashion", sub_type: "gunma_folk_craft", title_zh: "ぐんまちゃんファッション+雑貨(R1 食 ぐんまちゃん饅頭+R1 衣 県マスコット 2008 派生・T シャツ+パーカー+トートバッグ+靴下+缶バッジ+ 全国百貨店ヒット+ ¥1,500-5,500+ 子供+大人向け代表)", title_ja: "ぐんまちゃんファッション", romaji: "Gunma-chan Fashion", summary_zh: "**ぐんまちゃんファッション+雑貨は 2008 県マスコット派生・全国ゆるキャラ 2014 1 位**(T シャツ+パーカー+トート+靴下+缶バッジ)。全国百貨店、¥1,500-5,500。", content_md: "- 全域:**群馬県全域**\n- 関係:**R1 食 ぐんまちゃん饅頭 + 県マスコット 2008 派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["shopping_district"], lat: 36.3895, lon: 139.0635, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["gunma_chan_fashion"], source: "manual" },
  { slug: "daruma-paint-experience", category: "fashion", sub_type: "gunma_daruma", title_zh: "高崎達磨絵付け体験+ DIY(高崎市・R1 衣 高崎達磨 No.1 派生・少林山達磨寺周辺 5+ 工房・絵付け体験 1 個 ¥1,500-3,500+ 観光客向け文化体験代表+ R1 育 少林山達磨寺観光連動+ 海外観光客 SNS 拡散)", title_ja: "達磨絵付け体験", romaji: "Daruma Paint", summary_zh: "**高崎達磨絵付け体験+DIY は R1 衣 No.1 派生・少林山達磨寺周辺 5+ 工房**(高崎・**絵付け 1 個 ¥1,500-3,500**)。文化体験代表、海外 SNS 拡散。", content_md: "- 立地:**高崎市**\n- 関係:**R1 衣 高崎達磨 No.1 派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["craft_workshop", "shrine_temple"], lat: 36.3219, lon: 139.0033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["daruma_paint"], source: "manual" },
  { slug: "kiryu-shinmachi-juden", category: "fashion", sub_type: "gunma_kiryu_ori", title_zh: "桐生新町重伝建+のこぎり屋根工場群(桐生市・1986 国指定重要伝統的建造物群保存地区+ R1 衣 桐生織 1300 年派生・明治-大正期織物工場 30+ 棟・「のこぎり屋根」象徴・観光客向け歴史散策・入場無料)", title_ja: "桐生新町重伝建", romaji: "Kiryu Shinmachi", summary_zh: "**桐生新町重伝建+のこぎり屋根工場群は 1986 国指定重伝建+R1 衣 桐生織派生**(明治-大正期織物工場 30+ 棟・「のこぎり屋根」象徴)。観光客向け歴史散策、無料。", content_md: "- 立地:**桐生市**\n- 認定:**1986 国指定重要伝統的建造物群保存地区**\n- 関係:**R1 衣 桐生織 1300 年派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "桐生市", lg_code: "10203", area_types: ["shopping_district", "history_site_castle"], lat: 36.4044, lon: 139.3306, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kiryu_juden", "1986"], source: "manual" },
  { slug: "minakami-outdoor-shop", category: "fashion", sub_type: "gunma_folk_craft", title_zh: "みなかみアウトドア物販(利根郡みなかみ町・1990-2010 年代開発・モンベル+地元アウトドアブランド 5+ 軒・ラフティング+SUP 用品+ R1 楽 みなかみラフティング派生・国際観光客向け代表)", title_ja: "みなかみアウトドア", romaji: "Minakami Outdoor", summary_zh: "**みなかみアウトドア物販は 1990-2010 年代開発・モンベル+地元アウトドアブランド 5+ 軒**(みなかみ・**ラフティング+SUP 用品**)。R1 楽 ラフティング派生、国際観光客代表。", content_md: "- 立地:**利根郡みなかみ町**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["shopping_district"], lat: 36.7847, lon: 138.9558, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["minakami_outdoor"], source: "manual" },
  { slug: "kiryu-kimono-rental", category: "fashion", sub_type: "gunma_kiryu_ori", title_zh: "桐生織着物レンタル+ 体験(桐生市・R1 衣 桐生織 1300 年伝統+R1 衣 桐生新町重伝建 派生・着物レンタル+着付け体験 5+ 軒・1 日 ¥4,500-12,000+ R1 楽 桐生八木節祭+R1 育 桐生天満宮観光連動+ 国際観光客 SNS 拡散代表文化体験)", title_ja: "桐生織着物レンタル", romaji: "Kiryu Kimono Rental", summary_zh: "**桐生織着物レンタル+体験は R1 衣 桐生織 1300 年+重伝建派生・着物レンタル+着付け体験 5+ 軒**(¥4,500-12,000)。R1 楽 八木節+R1 育 天満宮、国際観光客 SNS 拡散代表文化体験。", content_md: "- 立地:**桐生市**\n- 関係:**R1 衣 桐生織 1300 年 + 桐生新町重伝建派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "桐生市", lg_code: "10203", area_types: ["craft_workshop", "shopping_district"], lat: 36.4044, lon: 139.3306, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 7, closed_days: [], external_urls: {}, tags: ["kiryu_kimono_rental"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[gunma-fashion-r1] 尚無條目"); return; }
  console.log(`[gunma-fashion-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) return;
  const sb = createAdminClient();
  const { error } = await sb.from("japan_entries").upsert(rows as any, { onConflict: "slug" });
  if (error) { console.error("[gunma-fashion-r1] upsert failed:", error); process.exit(1); }
  console.log(`[gunma-fashion-r1] Done — ${rows.length} rows.`);
}
main().catch((err) => { console.error(err); process.exit(1); });
