// Seed 東京都 住 R1(20 筆 / Sprint 1.3 / 第十三卷)
// 都心 5 / 副都心 4 / 山の手 3 / 下町 2 / 多摩 2 / 島嶼 4 = 20
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 都心 5
  {
    slug: "imperial-hotel-1890",
    category: "lodging", sub_type: "tokyo_toshin_hotel",
    title_zh: "帝国ホテル(千代田区内幸町・1890 開業 135+ 年+ 全国最古級ホテル候補+ フランク・ロイド・ライト 2 代目本館 1923-1968(明治村移築保存)+ 現本館 1970+ 皇室御用達ホテル+ 国際 SNS 海外旅行者代表+ ¥45,000-150,000/泊)",
    title_ja: "帝国ホテル", romaji: "Imperial Hotel",
    summary_zh: "**帝国ホテルは 1890 開業 135+ 年・全国最古級ホテル候補・フランク・ロイド・ライト 2 代目本館 1923-1968(明治村移築)・皇室御用達**(千代田内幸町)。¥45,000-150,000/泊、海外代表。",
    content_md: "- 立地:**千代田区内幸町**\n- 起源:**1890 開業 135+ 年**\n- 認定:**全国最古級ホテル候補 + フランク・ロイド・ライト 2 代目本館 1923-1968 + 皇室御用達**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "千代田区", lg_code: "13101",
    area_types: ["accommodation_hotel"], lat: 35.6739, lon: 139.7595,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["imperial_hotel", "1890", "135_years"], source: "manual",
  },
  {
    slug: "peninsula-tokyo-2007",
    category: "lodging", sub_type: "tokyo_toshin_hotel",
    title_zh: "ザ・ペニンシュラ東京(千代田区有楽町・2007 開業 18+ 年+ 国際チェーン Peninsula(香港 1928 創業派生)+ 314 室+ 皇居・日比谷公園隣接+ 銀座徒歩 5 分+ ミシュラン 2 つ星レストラン+ ¥75,000-280,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "ペニンシュラ東京", romaji: "Peninsula Tokyo",
    summary_zh: "**ペニンシュラ東京は 2007 開業 18+ 年・国際チェーン Peninsula(香港 1928 派生)・314 室・皇居+日比谷隣接・銀座徒歩 5 分**(千代田有楽町)。¥75,000-280,000/泊、海外代表。",
    content_md: "- 立地:**千代田区有楽町**\n- 起源:**2007 開業 18+ 年**\n- 認定:**国際チェーン Peninsula(香港 1928 創業派生)+ 314 室 + ミシュラン 2 つ星レストラン**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "千代田区", lg_code: "13101",
    area_types: ["accommodation_hotel"], lat: 35.6736, lon: 139.7611,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 90, closed_days: [],
    external_urls: {}, tags: ["peninsula_tokyo", "2007"], source: "manual",
  },
  {
    slug: "mandarin-oriental-2005",
    category: "lodging", sub_type: "tokyo_toshin_hotel",
    title_zh: "マンダリン オリエンタル 東京(中央区日本橋・2005 開業 20+ 年+ 国際チェーン Mandarin Oriental(香港 1963 創業派生)+ 日本橋三井タワー 30-38 階+ 178 室+ 三越本店 1673 R1 衣 隣接+ ミシュラン 2 つ星+ ¥75,000-280,000/泊・国際 SNS 海外代表)",
    title_ja: "マンダリン東京", romaji: "Mandarin Oriental",
    summary_zh: "**マンダリン オリエンタル東京は 2005 開業 20+ 年・国際チェーン MO(香港 1963 派生)・三井タワー 30-38 階・178 室・三越 1673 隣接**(日本橋)。¥75,000-280,000/泊、海外代表。",
    content_md: "- 立地:**中央区日本橋**\n- 起源:**2005 開業 20+ 年**\n- 認定:**国際チェーン Mandarin Oriental(香港 1963)+ 日本橋三井タワー 30-38 階 + 178 室 + ミシュラン 2 つ星**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "中央区", lg_code: "13102",
    area_types: ["accommodation_hotel"], lat: 35.6839, lon: 139.7733,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 90, closed_days: [],
    external_urls: {}, tags: ["mandarin_oriental", "2005"], source: "manual",
  },
  {
    slug: "aman-tokyo-2014",
    category: "lodging", sub_type: "tokyo_toshin_hotel",
    title_zh: "アマン東京(千代田区大手町・2014 開業 11+ 年+ 国際チェーン Aman Resorts 都市型唯一・大手町タワー 33-38 階+ 84 室+ JR 東京駅徒歩 5 分・¥125,000-450,000/泊+ 国際 SNS 高級旅行者代表+ アジア 2 大都市型 Aman 候補)",
    title_ja: "アマン東京", romaji: "Aman Tokyo",
    summary_zh: "**アマン東京は 2014 開業 11+ 年・国際チェーン Aman Resorts 都市型唯一・大手町タワー 33-38 階・84 室・東京駅徒歩 5 分**(大手町)。¥125,000-450,000/泊、高級代表。",
    content_md: "- 立地:**千代田区大手町**\n- 起源:**2014 開業 11+ 年**\n- 認定:**国際チェーン Aman Resorts 都市型唯一 + 大手町タワー 33-38 階 + 84 室**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "千代田区", lg_code: "13101",
    area_types: ["accommodation_hotel"], lat: 35.6864, lon: 139.7672,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 90, closed_days: [],
    external_urls: {}, tags: ["aman_tokyo", "2014"], source: "manual",
  },
  {
    slug: "park-hyatt-shinjuku-1994",
    category: "lodging", sub_type: "tokyo_toshin_hotel",
    title_zh: "パーク ハイアット 東京(新宿区西新宿・1994 開業 31+ 年+ 国際チェーン Hyatt 旗艦+ 新宿パークタワー 39-52 階+ 178 室+ 映画「ロスト・イン・トランスレーション」2003 舞台地+ JR 新宿駅徒歩 12 分・¥85,000-280,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "パーク ハイアット東京", romaji: "Park Hyatt Tokyo",
    summary_zh: "**パーク ハイアット東京は 1994 開業 31+ 年・国際チェーン Hyatt 旗艦・新宿パークタワー 39-52 階・178 室・「ロスト・イン・トランスレーション」2003 舞台**(新宿西)。¥85,000-280,000/泊。",
    content_md: "- 立地:**新宿区西新宿**\n- 起源:**1994 開業 31+ 年**\n- 認定:**国際チェーン Hyatt 旗艦 + 新宿パークタワー 39-52 階 + 178 室 + 映画「ロスト・イン・トランスレーション」2003 舞台地**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "新宿区", lg_code: "13104",
    area_types: ["accommodation_hotel"], lat: 35.6856, lon: 139.6911,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["park_hyatt_tokyo", "1994", "lost_in_translation"], source: "manual",
  },

  // 副都心 4
  {
    slug: "hilton-tokyo-shinjuku-1963",
    category: "lodging", sub_type: "tokyo_fukutoshin_hotel",
    title_zh: "ヒルトン東京(新宿区西新宿・1963 開業 62+ 年+ 国際チェーン Hilton(米国 1919 創業派生)+ 国内 Hilton 創業店候補+ 新宿西口超高層ビル群+ 825 室+ JR 新宿駅徒歩 10 分・¥35,000-85,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "ヒルトン東京", romaji: "Hilton Tokyo",
    summary_zh: "**ヒルトン東京は 1963 開業 62+ 年・国際 Hilton(米 1919 派生)・国内 Hilton 創業店候補・新宿西口超高層 825 室**(新宿西)。¥35,000-85,000/泊、海外代表。",
    content_md: "- 立地:**新宿区西新宿**\n- 起源:**1963 開業 62+ 年**\n- 認定:**国際チェーン Hilton + 国内 Hilton 創業店候補 + 825 室**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "新宿区", lg_code: "13104",
    area_types: ["accommodation_hotel"], lat: 35.6928, lon: 139.6917,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["hilton_tokyo", "1963", "62_years"], source: "manual",
  },
  {
    slug: "cerulean-tower-shibuya-2001",
    category: "lodging", sub_type: "tokyo_fukutoshin_hotel",
    title_zh: "セルリアンタワー東急ホテル(渋谷区桜丘町・2001 開業 24+ 年+ 東急グループ旗艦・41 階建超高層ホテル+ 411 室+ JR 渋谷駅徒歩 5 分+ R1 楽 渋谷スクランブル+109 連動・¥35,000-95,000/泊)",
    title_ja: "セルリアンタワー東急", romaji: "Cerulean Tower",
    summary_zh: "**セルリアンタワー東急ホテルは 2001 開業 24+ 年・東急グループ旗艦・41 階建超高層・411 室・JR 渋谷徒歩 5 分**(渋谷桜丘)。R1 楽 渋谷スクランブル+109 連動、¥35,000-95,000/泊。",
    content_md: "- 立地:**渋谷区桜丘町**\n- 起源:**2001 開業 24+ 年**\n- 認定:**東急グループ旗艦 + 41 階建超高層ホテル + 411 室**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "渋谷区", lg_code: "13113",
    area_types: ["accommodation_hotel"], lat: 35.6562, lon: 139.6981,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["cerulean_tower", "2001"], source: "manual",
  },
  {
    slug: "sunshine-city-prince-1980",
    category: "lodging", sub_type: "tokyo_fukutoshin_hotel",
    title_zh: "サンシャインシティプリンスホテル(豊島区東池袋・1980 サンシャイン 60 開業 45+ 年+ プリンスホテルグループ・1166 室+ サンシャイン水族館+プラネタリウム隣接+ JR 池袋駅徒歩 8 分・¥18,000-45,000/泊・国内ファミリー観光客代表)",
    title_ja: "サンシャイン プリンス", romaji: "Sunshine Prince",
    summary_zh: "**サンシャインシティプリンスホテルは 1980 サンシャイン 60 開業 45+ 年・プリンスグループ 1166 室・水族館+プラネタリウム隣接**(豊島東池袋)。JR 池袋徒歩 8 分、¥18,000-45,000/泊。",
    content_md: "- 立地:**豊島区東池袋**\n- 起源:**1980 サンシャイン 60 開業 45+ 年**\n- 規模:**プリンスホテルグループ + 1166 室**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "豊島区", lg_code: "13116",
    area_types: ["accommodation_hotel"], lat: 35.7286, lon: 139.7197,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["sunshine_prince", "1980"], source: "manual",
  },
  {
    slug: "asakusa-view-hotel-1985",
    category: "lodging", sub_type: "tokyo_fukutoshin_hotel",
    title_zh: "浅草ビューホテル(台東区西浅草・1985 開業 40+ 年+ 浅草寺隣接立地+ 28 階建・325 室+ R1 育 浅草寺+ R1 食 浅草老舗+R1 衣 浅草着物レンタル一体観光・¥18,000-45,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "浅草ビューホテル", romaji: "Asakusa View Hotel",
    summary_zh: "**浅草ビューホテルは 1985 開業 40+ 年・浅草寺隣接・28 階建 325 室**(西浅草)。R1 育 浅草寺+R1 食+衣連動、¥18,000-45,000/泊、海外旅行者代表。",
    content_md: "- 立地:**台東区西浅草**\n- 起源:**1985 開業 40+ 年**\n- 規模:**28 階建 325 室**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "台東区", lg_code: "13106",
    area_types: ["accommodation_hotel"], lat: 35.7142, lon: 139.7919,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["asakusa_view", "1985"], source: "manual",
  },

  // 山の手 3
  {
    slug: "hotel-chinzanso-1992",
    category: "lodging", sub_type: "tokyo_yamanote_hotel",
    title_zh: "ホテル椿山荘東京(文京区関口・1992 ホテルとして開業 33+ 年+ 椿山荘庭園 1878 山県有朋私邸由来 147+ 年+ 6.6ha 庭園+ 国登録有形文化財 三重塔 14 世紀広島から移築・¥35,000-95,000/泊+ 国際 SNS 海外旅行者代表)",
    title_ja: "ホテル椿山荘", romaji: "Chinzansō",
    summary_zh: "**ホテル椿山荘東京は 1992 ホテル開業 33+ 年・椿山荘庭園 1878 山県有朋私邸 147+ 年・6.6ha 庭園・国登録三重塔 14 世紀広島移築**(文京関口)。¥35,000-95,000/泊。",
    content_md: "- 立地:**文京区関口**\n- 起源:**1992 ホテル開業 33+ 年 + 椿山荘庭園 1878 147+ 年**\n- 認定:**6.6ha 庭園 + 国登録有形文化財 三重塔 14 世紀広島から移築**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "文京区", lg_code: "13105",
    area_types: ["accommodation_hotel", "history_site_castle"], lat: 35.7106, lon: 139.7286,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["chinzanso", "1992", "1878"], source: "manual",
  },
  {
    slug: "shinagawa-prince-1971",
    category: "lodging", sub_type: "tokyo_yamanote_hotel",
    title_zh: "品川プリンスホテル(港区高輪+品川・1971 開業 54+ 年+ プリンスホテル国内最大級 3680 室・JR 品川駅徒歩 2 分+ アクアパーク水族館+ボウリング+ 映画館併設・¥14,000-35,000/泊・国内+海外団体ツアー代表)",
    title_ja: "品川プリンス", romaji: "Shinagawa Prince",
    summary_zh: "**品川プリンスホテルは 1971 開業 54+ 年・プリンス国内最大級 3680 室・JR 品川徒歩 2 分・アクアパーク+ボウリング+映画館併設**(港高輪+品川)。¥14,000-35,000/泊。",
    content_md: "- 立地:**港区高輪 + 品川区**\n- 起源:**1971 開業 54+ 年**\n- 規模:**プリンスホテル国内最大級 3680 室**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "港区", lg_code: "13103",
    area_types: ["accommodation_hotel"], lat: 35.6286, lon: 139.7397,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["shinagawa_prince", "1971"], source: "manual",
  },
  {
    slug: "okura-tokyo-1962",
    category: "lodging", sub_type: "tokyo_yamanote_hotel",
    title_zh: "ホテルオークラ東京(港区虎ノ門・1962 開業 63+ 年+ 旧本館 1962-2015(東京五輪 1964 主要会場)+ 新本館「The Okura Tokyo」2019 建替+ 全国 5 大ホテル候補(オークラ+帝国+ニューオータニ)+ 508 室・¥45,000-150,000/泊)",
    title_ja: "ホテルオークラ東京", romaji: "Okura Tokyo",
    summary_zh: "**ホテルオークラ東京は 1962 開業 63+ 年・旧本館 1962-2015(東京五輪 1964 主要)・新本館 2019 建替・全国 5 大ホテル候補・508 室**(港虎ノ門)。¥45,000-150,000/泊。",
    content_md: "- 立地:**港区虎ノ門**\n- 起源:**1962 開業 63+ 年**\n- 認定:**全国 5 大ホテル候補(オークラ + 帝国 + ニューオータニ)**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "港区", lg_code: "13103",
    area_types: ["accommodation_hotel"], lat: 35.6675, lon: 139.7456,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["okura_tokyo", "1962", "2019_rebuild"], source: "manual",
  },

  // 下町 2
  {
    slug: "tobu-skytree-east-2012",
    category: "lodging", sub_type: "tokyo_shitamachi_hotel",
    title_zh: "東武ホテルレバント東京+ スカイツリーイーストタワー(墨田区錦糸町+押上・スカイツリー 2012 開業 13+ 年連動・305 室・JR 錦糸町駅徒歩 3 分+ 東京スカイツリータウン徒歩 10 分・¥18,000-45,000/泊・国内ファミリー観光客代表)",
    title_ja: "東武レバント+スカイツリー", romaji: "Tobu Skytree",
    summary_zh: "**東武ホテルレバント東京+スカイツリーイーストは 2012 13+ 年連動・305 室・JR 錦糸町徒歩 3 分・スカイツリー徒歩 10 分**(墨田錦糸町+押上)。¥18,000-45,000/泊。",
    content_md: "- 立地:**墨田区錦糸町 + 押上**\n- 起源:**スカイツリー 2012 開業 13+ 年連動**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "墨田区", lg_code: "13107",
    area_types: ["accommodation_hotel"], lat: 35.6964, lon: 139.8139,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["tobu_skytree", "2012"], source: "manual",
  },
  {
    slug: "tokyo-bay-ariake-2009",
    category: "lodging", sub_type: "tokyo_shitamachi_hotel",
    title_zh: "東京ベイ有明ワシントン+ ヒルトン東京ベイ(江東区有明+ お台場・2009 ワシントン開業 16+ 年+ 国際展示場+ ビッグサイト隣接+ R1 楽 お台場+ 東京テレポート連動・¥14,000-32,000/泊・国内ビジネス+ファミリー代表)",
    title_ja: "東京ベイ有明", romaji: "Tokyo Bay Ariake",
    summary_zh: "**東京ベイ有明ワシントン+ヒルトン東京ベイは 2009 16+ 年・国際展示場+ビッグサイト隣接**(江東有明+お台場)。R1 楽 お台場+テレポート連動、¥14,000-32,000/泊。",
    content_md: "- 立地:**江東区有明 + お台場**\n- 起源:**2009 ワシントン開業 16+ 年**\n- 認定:**国際展示場 + ビッグサイト隣接**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "江東区", lg_code: "13108",
    area_types: ["accommodation_hotel"], lat: 35.6322, lon: 139.7917,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["tokyo_bay_ariake", "2009"], source: "manual",
  },

  // 多摩 2
  {
    slug: "takao-onsen-keio",
    category: "lodging", sub_type: "tokyo_tama_lodging",
    title_zh: "京王高尾山温泉「極楽湯」(八王子市高尾町・2015 開業 10+ 年+ 高尾山口駅前+ R1 楽 高尾山ケーブル+リフト連動+ 天然温泉日帰り入浴+ 個室レストラン+ 駐車場+ ¥1,000-3,500・国際 SNS 海外旅行者代表+ ミシュラン三つ星 高尾山連動)",
    title_ja: "高尾山温泉", romaji: "Takao Onsen",
    summary_zh: "**京王高尾山温泉「極楽湯」は 2015 開業 10+ 年・高尾山口駅前・天然温泉+個室レストラン**(八王子高尾)。R1 楽 高尾山連動、¥1,000-3,500、ミシュラン三つ星海外旅行者代表。",
    content_md: "- 立地:**八王子市高尾町**\n- 起源:**2015 開業 10+ 年**\n- 関連:**R1 楽 高尾山ケーブルカー + リフト派生**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "八王子市", lg_code: "13201",
    area_types: ["onsen_natural"], lat: 35.6325, lon: 139.2683,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["takao_onsen", "2015"], source: "manual",
  },
  {
    slug: "okutama-onsen",
    category: "lodging", sub_type: "tokyo_tama_lodging",
    title_zh: "奥多摩温泉郷+鶴の湯(西多摩郡奥多摩町+檜原村・1990 年代開発 35+ 年+ 多摩川源流山中温泉郷+ 鶴の湯+ 三河屋旅館+ 老舗旅館 6+ 軒+ R1 楽 奥多摩湖+ R1 食 多摩そば連動・¥9,500-22,000/泊+ JR 奥多摩線終点)",
    title_ja: "奥多摩温泉", romaji: "Okutama Onsen",
    summary_zh: "**奥多摩温泉郷+鶴の湯は 1990 年代開発 35+ 年・多摩川源流山中温泉郷・老舗旅館 6+ 軒**(奥多摩+檜原)。R1 楽 奥多摩湖+R1 食 多摩そば連動、¥9,500-22,000/泊、JR 奥多摩線終点。",
    content_md: "- 立地:**西多摩郡奥多摩町 + 檜原村**\n- 起源:**1990 年代開発 35+ 年**\n- 規模:**温泉旅館 6+ 軒**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: "西多摩郡", municipality_ja: "奥多摩町", lg_code: "13308",
    area_types: ["onsen_natural", "accommodation_ryokan", "nature_park"], lat: 35.8083, lon: 139.0972,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["okutama_onsen"], source: "manual",
  },

  // 島嶼 4
  {
    slug: "oshima-onsen-shimanoyu",
    category: "lodging", sub_type: "tokyo_islands_lodging",
    title_zh: "大島温泉ホテル+ 元町温泉郷(大島町元町+泉津・1969 開業 56+ 年+ 三原山火山温泉+ 太平洋直面 オーシャンビュー+ 老舗旅館 12+ 軒+ R1 楽 三原山+地層大切断面+ R1 食 伊豆明日葉連動・¥12,000-32,000/泊・東京から船 5h or 飛行機 25 分)",
    title_ja: "大島温泉", romaji: "Ōshima Onsen",
    summary_zh: "**大島温泉ホテル+元町温泉郷は 1969 開業 56+ 年・三原山火山温泉+太平洋オーシャンビュー・老舗 12+ 軒**(大島元町+泉津)。R1 楽 三原山+R1 食 明日葉連動、¥12,000-32,000/泊。",
    content_md: "- 立地:**大島町元町 + 泉津**\n- 起源:**1969 開業 56+ 年**\n- 規模:**温泉旅館 12+ 軒 + 三原山火山温泉**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "大島町", lg_code: "13361",
    area_types: ["onsen_natural", "accommodation_ryokan", "beach_coast"], lat: 34.7497, lon: 139.3567,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["oshima_onsen", "1969"], source: "manual",
  },
  {
    slug: "hachijojima-onsen",
    category: "lodging", sub_type: "tokyo_islands_lodging",
    title_zh: "八丈島温泉郷+ 末吉温泉「みはらしの湯」(八丈町末吉+底土+ 樫立・1990 年代開発 35+ 年+ 八丈富士火山温泉+ 太平洋オーシャンビュー+ 国際 SNS 海外旅行者代表+ R1 衣 黄八丈 + R1 食 くさや連動・¥12,000-32,000/泊)",
    title_ja: "八丈島温泉", romaji: "Hachijōjima Onsen",
    summary_zh: "**八丈島温泉郷+末吉「みはらしの湯」は 1990 年代開発 35+ 年・八丈富士火山温泉+太平洋オーシャンビュー**(八丈町)。R1 衣 黄八丈+R1 食 くさや連動、¥12,000-32,000/泊。",
    content_md: "- 立地:**八丈町末吉 + 底土 + 樫立**\n- 起源:**1990 年代開発 35+ 年**\n- 関連:**R1 衣 黄八丈 + R1 食 くさや派生**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "八丈町", lg_code: "13401",
    area_types: ["onsen_natural", "accommodation_ryokan"], lat: 33.1083, lon: 139.7900,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["hachijojima_onsen"], source: "manual",
  },
  {
    slug: "miyakejima-pension",
    category: "lodging", sub_type: "tokyo_islands_lodging",
    title_zh: "三宅島ペンション+ 民宿(三宅村・三宅島火山島(2000 大噴火 → 2005 全島民帰島)+ ダイビング+ 釣り+ ホエールウォッチング・1990 年代以降ペンション+民宿 12+ 軒・¥9,500-18,000/泊・東京から船 6.5h+ 飛行機 50 分)",
    title_ja: "三宅島ペンション", romaji: "Miyakejima",
    summary_zh: "**三宅島ペンション+民宿は三宅島火山島(2000 大噴火→2005 帰島)・ダイビング+釣り+ホエール・1990 年代以降 12+ 軒**(三宅村)。¥9,500-18,000/泊、船 6.5h+飛行機 50 分。",
    content_md: "- 立地:**三宅村**\n- 起源:**1990 年代以降ペンション + 民宿 12+ 軒**\n- 認定:**三宅島火山島 + 2000 大噴火 + 2005 全島民帰島**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "三宅村", lg_code: "13381",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 34.0833, lon: 139.5167,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["miyakejima"], source: "manual",
  },
  {
    slug: "ogasawara-chichijima-hotels",
    category: "lodging", sub_type: "tokyo_ogasawara_lodging",
    title_zh: "小笠原父島ホテル+ ペンション(小笠原村父島・1968 アメリカ統治返還 57+ 年+ 1876 開拓以来 150+ 年+ ホテル+民宿 30+ 軒+ R1 食 マグロ+トロピカル+ R1 楽 ホエールウォッチング+ ボニンブルー海連動・¥12,000-32,000/泊・東京から船「おがさわら丸」24 時間隔離)",
    title_ja: "小笠原父島ホテル", romaji: "Chichijima Hotels",
    summary_zh: "**小笠原父島ホテル+ペンションは 1876 開拓 150+ 年・1968 米国返還 57+ 年・ホテル+民宿 30+ 軒**(父島)。R1 食 マグロ+R1 楽 ホエール+ボニンブルー連動、¥12,000-32,000/泊、船 24h。",
    content_md: "- 立地:**小笠原村父島**\n- 起源:**1876 開拓以来 150+ 年 + 1968 アメリカ統治返還 57+ 年**\n- 規模:**ホテル + 民宿 30+ 軒**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "小笠原村", lg_code: "13421",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 27.0928, lon: 142.1925,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 90, closed_days: [],
    external_urls: {}, tags: ["chichijima_hotels", "1876", "1968"], source: "manual",
  },
];

seedMain(rows, "tokyo-lodging-r1");
