// Seed 香川県 行 R1(19 筆 / Sprint 1.6 / 第十五卷)
// JR 4 / 瀬戸大橋 2 / 私鉄 3 / 港 3 / 空港 1 / 道路 2 / ローカル 4 = 19
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // JR 4
  {
    slug: "jr-takamatsu-station-1897",
    category: "transport", sub_type: "kagawa_terminal",
    title_zh: "JR 高松駅(高松市浜ノ町・1897 明治 30 年讃岐鉄道高松-丸亀開通時開業 128+ 年+ JR 予讃線+JR 高徳線+JR 瀬戸大橋線+ ことでん高松築港駅 4 路線結節+ 1 日 4 万人乗降+ 2001 現代建築リニューアル+ R1 楽 高松シンボルタワー隣接)",
    title_ja: "JR 高松駅", romaji: "JR Takamatsu Station",
    summary_zh: "**JR 高松駅は 1897 讃岐鉄道高松-丸亀開通時開業 128+ 年・JR 予讃+高徳+瀬戸大橋+ことでん高松築港 4 路線結節・1 日 4 万人乗降+2001 現代建築リニューアル**(高松浜ノ町)。",
    content_md: "- 立地:**高松市浜ノ町**\n- 起源:**1897 明治 30 年讃岐鉄道高松-丸亀開通時開業 128+ 年**\n- 規模:**4 路線結節 + 1 日 4 万人乗降 + 2001 現代建築リニューアル**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub"], lat: 34.3527, lon: 134.0494,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_takamatsu_1897"], source: "manual",
  },
  {
    slug: "jr-yosan-line-1897",
    category: "transport", sub_type: "kagawa_jr",
    title_zh: "JR 予讃線(高松-松山-宇和島・1897 讃岐鉄道高松-丸亀部分開通 128+ 年+ 1924 全通+ 全長 297km(四国最長 JR 線)+ 高松+丸亀+坂出+観音寺+愛媛松山+宇和島・四国主要幹線+ JR Pass 全外国人 free・¥150-3,500/片道)",
    title_ja: "JR 予讃線", romaji: "JR Yosan",
    summary_zh: "**JR 予讃線は 1897 讃岐鉄道部分開通 128+ 年+1924 全通・全長 297km(四国最長)・四国主要幹線**(高松+丸亀+坂出+観音寺+松山+宇和島)。¥150-3,500/片道、JR Pass 可。",
    content_md: "- 起源:**1897 讃岐鉄道高松-丸亀部分開通 128+ 年 + 1924 全通**\n- 規模:**全長 297km(四国最長 JR 線)**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub"], lat: 34.3527, lon: 134.0494,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_yosan_1897"], source: "manual",
  },
  {
    slug: "jr-kotoku-line-1935",
    category: "transport", sub_type: "kagawa_jr",
    title_zh: "JR 高徳線(高松-徳島・1935 全通 90+ 年+ 高松-徳島 74.5km・25 駅+ 香川+徳島県境貫通+ さぬき市+東かがわ市経由+ 「うずしお」特急 1996 運行・¥150-1,520/片道+ R1 食 八栗寺+R1 育 屋島源平連動)",
    title_ja: "JR 高徳線", romaji: "JR Kōtoku",
    summary_zh: "**JR 高徳線は 1935 全通 90+ 年・高松-徳島 74.5km+25 駅・香川+徳島県境貫通・「うずしお」特急 1996**(高松+さぬき+東かがわ+徳島)。¥150-1,520/片道。",
    content_md: "- 起源:**1935 全通 90+ 年**\n- 規模:**高松-徳島 74.5km + 25 駅**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub"], lat: 34.3527, lon: 134.0494,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_kotoku_1935"], source: "manual",
  },
  {
    slug: "jr-dosan-line-1935",
    category: "transport", sub_type: "kagawa_jr",
    title_zh: "JR 土讃線(多度津-高知・1935 全通 90+ 年+ 多度津-高知-窪川 198.7km・39 駅+ 香川-高知県境貫通+ 善通寺+琴平+大歩危・小歩危絶景・「南風」特急 1972 運行・¥150-3,500/片道)",
    title_ja: "JR 土讃線", romaji: "JR Dosan",
    summary_zh: "**JR 土讃線は 1935 全通 90+ 年・多度津-高知-窪川 198.7km+39 駅・香川-高知県境貫通・善通寺+琴平+大歩危・小歩危絶景・「南風」特急 1972**(多度津+琴平+高知)。¥150-3,500/片道。",
    content_md: "- 起源:**1935 全通 90+ 年**\n- 規模:**多度津-高知-窪川 198.7km + 39 駅 + 善通寺 + 琴平 + 大歩危・小歩危絶景**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "仲多度郡", municipality_ja: "多度津町", lg_code: "37403",
    area_types: ["transport_hub"], lat: 34.2742, lon: 133.7517,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_dosan_1935"], source: "manual",
  },

  // 瀬戸大橋 2
  {
    slug: "seto-ohashi-1988",
    category: "transport", sub_type: "kagawa_seto_ohashi",
    title_zh: "瀬戸大橋(坂出市+ 倉敷市・1988 開通 37+ 年+ 全長 13.1km(全国最長橋梁系列+ 世界最長鉄道道路併用橋ギネス)+ JR 瀬戸大橋線+瀬戸中央自動車道+ 6 橋(下津井瀬戸大橋+櫃石島橋+岩黒島橋+与島橋+北備讃瀬戸大橋+南備讃瀬戸大橋)・¥7,420/片道(普通車))",
    title_ja: "瀬戸大橋", romaji: "Seto Ōhashi",
    summary_zh: "**瀬戸大橋は 1988 開通 37+ 年・全長 13.1km(全国最長橋梁系列+世界最長鉄道道路併用橋ギネス)・JR 瀬戸大橋線+瀬戸中央自動車道・6 橋**(坂出+倉敷)。¥7,420/片道。",
    content_md: "- 起源:**1988 開通 37+ 年**\n- 認定:**全長 13.1km(全国最長橋梁系列 + 世界最長鉄道道路併用橋ギネス) + JR 瀬戸大橋線 + 瀬戸中央自動車道 + 6 橋**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "坂出市", lg_code: "37203",
    area_types: ["transport_hub"], lat: 34.3833, lon: 133.8167,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["seto_ohashi_1988", "world_longest_combined"], source: "manual",
  },
  {
    slug: "jr-seto-ohashi-line-1988",
    category: "transport", sub_type: "kagawa_jr",
    title_zh: "JR 瀬戸大橋線(坂出-茶屋町・1988 開通 37+ 年+ R1 行 瀬戸大橋上鉄道線・四国-本州結節+ JR 予讃線分岐+ 「マリンライナー」 高松-岡山 1 時間+ 1 日 100 便+ ¥1,520/片道+ JR Pass 全外国人 free)",
    title_ja: "JR 瀬戸大橋線", romaji: "JR Seto Ohashi",
    summary_zh: "**JR 瀬戸大橋線は 1988 開通 37+ 年・R1 行 瀬戸大橋上鉄道・四国-本州結節・「マリンライナー」高松-岡山 1 時間・1 日 100 便**(坂出-茶屋町)。¥1,520/片道、JR Pass 可。",
    content_md: "- 起源:**1988 開通 37+ 年**\n- 関連:**R1 行 瀬戸大橋派生**\n- 規模:**「マリンライナー」 高松-岡山 1 時間 + 1 日 100 便**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "坂出市", lg_code: "37203",
    area_types: ["transport_hub"], lat: 34.3300, lon: 133.8167,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jr_seto_ohashi_1988"], source: "manual",
  },

  // 私鉄 3
  {
    slug: "kotoden-kotohira-1911",
    category: "transport", sub_type: "kagawa_private_railway",
    title_zh: "高松琴平電気鉄道(ことでん)琴平線(高松築港-琴電琴平・1911 高松電気軌道創業 114+ 年+ 32.9km・22 駅+ R1 育 金刀比羅宮アクセス+ 1 日 4 万人乗降・¥510-650/片道+ 「ことちゃん」マスコット・国際 SNS 海外旅行者代表)",
    title_ja: "ことでん琴平線", romaji: "Kotoden Kotohira",
    summary_zh: "**高松琴平電気鉄道(ことでん)琴平線は 1911 創業 114+ 年・32.9km+22 駅・R1 育 金刀比羅宮アクセス・1 日 4 万人乗降**(高松築港-琴電琴平)。¥510-650/片道、海外代表。",
    content_md: "- 起源:**1911 高松電気軌道創業 114+ 年**\n- 規模:**32.9km + 22 駅 + R1 育 金刀比羅宮アクセス + 1 日 4 万人乗降**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub"], lat: 34.3527, lon: 134.0494,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kotoden_kotohira_1911"], source: "manual",
  },
  {
    slug: "kotoden-shido-1909",
    category: "transport", sub_type: "kagawa_private_railway",
    title_zh: "ことでん志度線+ 長尾線(瓦町-琴電志度+ 高松築港-長尾・1909 東讃電気軌道創業 116+ 年+ 志度線 12.5km・15 駅+長尾線 14.6km・15 駅+ 高松+さぬき+三木 R1 育 八栗寺アクセス+ ¥260-510/片道)",
    title_ja: "ことでん志度+長尾", romaji: "Kotoden Shido Nagao",
    summary_zh: "**ことでん志度+長尾線は 1909 東讃電気軌道創業 116+ 年・志度 12.5km+15 駅+長尾 14.6km+15 駅・R1 育 八栗寺アクセス**(瓦町-琴電志度+高松築港-長尾)。¥260-510/片道。",
    content_md: "- 起源:**1909 東讃電気軌道創業 116+ 年**\n- 規模:**志度線 12.5km + 15 駅 + 長尾線 14.6km + 15 駅**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub"], lat: 34.3401, lon: 134.0434,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kotoden_shido_1909"], source: "manual",
  },
  {
    slug: "yakuri-cable-1964",
    category: "transport", sub_type: "kagawa_private_railway",
    title_zh: "八栗ケーブル(高松市八栗・1964 開業 61+ 年+ R1 育 八栗寺(第 85 番札所) 派生・八栗登山口駅-八栗山上駅 0.7km+ 標高差 167m+ 五剣山 366m 中腹アクセス+ 全国 4 国唯一現役ケーブル候補・¥1,000/往復)",
    title_ja: "八栗ケーブル", romaji: "Yakuri Cable",
    summary_zh: "**八栗ケーブルは 1964 開業 61+ 年・R1 育 八栗寺第 85 番派生・八栗登山口-山上 0.7km+標高差 167m・五剣山 366m 中腹・全国 4 国唯一現役ケーブル候補**(高松八栗)。¥1,000/往復。",
    content_md: "- 立地:**高松市八栗**\n- 起源:**1964 開業 61+ 年**\n- 関連:**R1 育 八栗寺(第 85 番札所)派生**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub", "history_site_castle"], lat: 34.3556, lon: 134.1267,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yakuri_cable_1964"], source: "manual",
  },

  // 港 3
  {
    slug: "takamatsu-port",
    category: "transport", sub_type: "kagawa_seto_ohashi",
    title_zh: "高松港+ 高松港旅客ターミナル(高松市サンポート・古来から国際港 1000+ 年+ R1 育 高松城 1588 港町・小豆島フェリー+直島フェリー+ 男木島・女木島フェリー+ 国際定期航路+ R1 楽 高松シンボルタワー+JR 高松駅徒歩 5 分・¥150-1,500/片道)",
    title_ja: "高松港", romaji: "Takamatsu Port",
    summary_zh: "**高松港+高松港旅客ターミナルは古来から国際港 1000+ 年・R1 育 高松城 1588 港町・小豆島+直島+男木+女木フェリー+国際定期航路**(高松サンポート)。¥150-1,500/片道。",
    content_md: "- 立地:**高松市サンポート**\n- 起源:**古来から国際港 1000+ 年**\n- 認定:**小豆島フェリー + 直島フェリー + 男木島・女木島フェリー + 国際定期航路**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub"], lat: 34.3527, lon: 134.0494,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["takamatsu_port"], source: "manual",
  },
  {
    slug: "shodoshima-ferry-1958",
    category: "transport", sub_type: "kagawa_seto_ohashi",
    title_zh: "小豆島フェリー(高松-土庄+池田・小豆島町+ 土庄町・四国フェリー 1958 創業 67+ 年+ ジャンボフェリー+ 国際両備フェリー競合+ 高松-土庄 1 時間+ 高松-池田 1 時間+ R1 楽 小豆島観光全アクセス・¥700/片道)",
    title_ja: "小豆島フェリー", romaji: "Shōdoshima Ferry",
    summary_zh: "**小豆島フェリーは四国フェリー 1958 創業 67+ 年・高松-土庄 1 時間+高松-池田 1 時間・R1 楽 小豆島観光全アクセス**(高松-土庄+池田)。¥700/片道。",
    content_md: "- 立地:**高松市 + 小豆郡土庄町 + 池田**\n- 起源:**四国フェリー 1958 創業 67+ 年**\n- 規模:**高松-土庄 1 時間 + 高松-池田 1 時間**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "小豆郡", municipality_ja: "土庄町", lg_code: "37322",
    area_types: ["transport_hub"], lat: 34.4847, lon: 134.2500,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shodoshima_ferry_1958"], source: "manual",
  },
  {
    slug: "naoshima-ferry-1968",
    category: "transport", sub_type: "kagawa_seto_ohashi",
    title_zh: "直島フェリー+ 四国汽船(高松-直島宮浦+ 本村+ 宇野-直島・四国汽船 1968 創業 57+ 年+ R1 楽 直島ベネッセアート 1992+ 瀬戸内国際芸術祭派生・高松-直島 1 時間+ 宇野-直島 20 分・¥520/片道+ 国際 SNS 海外アートファン代表)",
    title_ja: "直島フェリー", romaji: "Naoshima Ferry",
    summary_zh: "**直島フェリー+四国汽船は 1968 創業 57+ 年・R1 楽 ベネッセアート+瀬戸内国際芸術祭派生・高松-直島 1 時間+宇野-直島 20 分**(高松+宇野-直島)。¥520/片道、海外代表。",
    content_md: "- 立地:**高松市 + 香川郡直島町 + 岡山宇野**\n- 起源:**四国汽船 1968 創業 57+ 年**\n- 関連:**R1 楽 直島ベネッセアート 1992 + 瀬戸内国際芸術祭派生**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "香川郡", municipality_ja: "直島町", lg_code: "37364",
    area_types: ["transport_hub"], lat: 34.4583, lon: 133.9967,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["naoshima_ferry_1968"], source: "manual",
  },

  // 空港 1
  {
    slug: "takamatsu-airport-1989",
    category: "transport", sub_type: "kagawa_terminal",
    title_zh: "高松空港(高松市香南町・1989 6 月 6 日 新空港開港 36+ 年(旧高松空港 1958 廃止)+ 国内空港+ 国際線(羽田+成田+那覇+ ソウル+台北+上海)+ 1 日 50 便+ R1 住 高松空港前ホテル R1 派生・JR 高松駅+ 空港リムジンバス 40 分)",
    title_ja: "高松空港", romaji: "Takamatsu Airport",
    summary_zh: "**高松空港は 1989 6 月 6 日新空港開港 36+ 年(旧 1958 廃止)・国内+国際線(羽田+成田+那覇+ソウル+台北+上海)・1 日 50 便**(高松香南)。R1 住 連動、JR 高松+リムジン 40 分。",
    content_md: "- 立地:**高松市香南町**\n- 起源:**1989 6 月 6 日 新空港開港 36+ 年(旧高松空港 1958 廃止)**\n- 認定:**国内 + 国際線(羽田 + 成田 + 那覇 + ソウル + 台北 + 上海)**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub"], lat: 34.2161, lon: 134.0156,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["takamatsu_airport_1989"], source: "manual",
  },

  // 道路 2
  {
    slug: "takamatsu-expressway-1992",
    category: "transport", sub_type: "kagawa_kosoku",
    title_zh: "高松自動車道+ 瀬戸中央自動車道(全県+ 1988 瀬戸中央自動車道開通 37+ 年+ 1992 高松自動車道開通 33+ 年+ 全県縦断高速道路網+ 川之江東 JCT-高松-鳴門 IC 109km+ 高松東-鳴門 IC 直結+ 通行料 ¥520-3,500)",
    title_ja: "高松自動車道", romaji: "Takamatsu Expressway",
    summary_zh: "**高松自動車道+瀬戸中央自動車道は 1988 瀬戸中央 37+ 年+1992 高松 33+ 年・全県縦断高速網・川之江東 JCT-高松-鳴門 IC 109km**(全県)。¥520-3,500。",
    content_md: "- 起源:**1988 瀬戸中央自動車道開通 37+ 年 + 1992 高松自動車道開通 33+ 年**\n- 規模:**全県縦断高速道路網 + 川之江東 JCT-高松-鳴門 IC 109km**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub"], lat: 34.3401, lon: 134.0434,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["takamatsu_expressway_1992"], source: "manual",
  },
  {
    slug: "kagawa-route-11",
    category: "transport", sub_type: "kagawa_kosoku",
    title_zh: "国道 11 号線+ 高松外環状(高松+丸亀+坂出+ 観音寺・1885 国道指定 140+ 年+ 香川県縦断国道+ 香川県内 75km+ R1 行 JR 予讃線+高松自動車道並行・通行料無料)",
    title_ja: "国道 11 号線", romaji: "Route 11",
    summary_zh: "**国道 11 号線+高松外環状は 1885 国道指定 140+ 年・香川県縦断+県内 75km・JR 予讃線+高松自動車道並行**(高松+丸亀+坂出+観音寺)。無料。",
    content_md: "- 起源:**1885 国道指定 140+ 年**\n- 規模:**香川県縦断国道 + 県内 75km**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub"], lat: 34.3401, lon: 134.0434,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["route_11"], source: "manual",
  },

  // ローカル 4
  {
    slug: "kotoden-bus",
    category: "transport", sub_type: "kagawa_subway",
    title_zh: "ことでんバス+ 高松市営バス(高松市+ 全県・1928 高松市営バス開業 97+ 年+ ことでんバス 1909 派生+ 全県 200+ 路線+ 1 日 8 万人乗降+ R1 食 讃岐うどん+R1 育 屋島+栗林公園アクセス・¥220-820/片道)",
    title_ja: "ことでんバス", romaji: "Kotoden Bus",
    summary_zh: "**ことでんバス+高松市営バスは 1928 高松市営 97+ 年+ことでんバス 1909 派生・全県 200+ 路線・1 日 8 万人乗降・R1 育 屋島+栗林公園アクセス**(全県)。¥220-820/片道。",
    content_md: "- 立地:**高松市 + 全県**\n- 起源:**1928 高松市営バス開業 97+ 年 + ことでんバス 1909 派生**\n- 規模:**全県 200+ 路線 + 1 日 8 万人乗降**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["transport_hub"], lat: 34.3401, lon: 134.0434,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kotoden_bus_1928"], source: "manual",
  },
  {
    slug: "shodoshima-bus-1953",
    category: "transport", sub_type: "kagawa_islands_transport",
    title_zh: "小豆島オリーブバス(土庄町+ 小豆島町・1953 創業 72+ 年+ 小豆島内 11 路線・1 日 200 便+ R1 食 オリーブ 1908+R1 楽 オリーブ公園 1989+寒霞渓+ 24 の瞳村全アクセス・¥190-840/片道+ 1 日乗車券 ¥1,000)",
    title_ja: "小豆島オリーブバス", romaji: "Shōdoshima Olive Bus",
    summary_zh: "**小豆島オリーブバスは 1953 創業 72+ 年・島内 11 路線・1 日 200 便・R1 食 オリーブ+R1 楽 オリーブ公園+寒霞渓+24 の瞳村全アクセス**(土庄+小豆島)。¥190-840/片道。",
    content_md: "- 立地:**小豆郡土庄町 + 小豆島町**\n- 起源:**1953 創業 72+ 年**\n- 規模:**島内 11 路線 + 1 日 200 便**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "小豆郡", municipality_ja: "小豆島町", lg_code: "37324",
    area_types: ["transport_hub"], lat: 34.4847, lon: 134.2500,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shodoshima_olive_bus_1953"], source: "manual",
  },
  {
    slug: "naoshima-island-bus",
    category: "transport", sub_type: "kagawa_naoshima",
    title_zh: "直島町営バス+ ベネッセアートバス(香川郡直島町・直島町営バス 2002 開業 23+ 年+ 1992 ベネッセアートバス併設・直島宮浦港-本村-地中美術館 4 路線+ 1 日 80 便+ R1 楽 直島アート全アクセス・¥100/片道+ ベネッセシャトル無料)",
    title_ja: "直島町営バス", romaji: "Naoshima Bus",
    summary_zh: "**直島町営バス+ベネッセアートバスは 2002 23+ 年+1992 ベネッセシャトル併設・宮浦港-本村-地中美術館 4 路線+1 日 80 便**(直島)。R1 楽 アート全アクセス、¥100/片道、ベネッセ無料。",
    content_md: "- 立地:**香川郡直島町**\n- 起源:**直島町営バス 2002 開業 23+ 年 + 1992 ベネッセアートバス併設**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "香川郡", municipality_ja: "直島町", lg_code: "37364",
    area_types: ["transport_hub"], lat: 34.4583, lon: 133.9967,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["naoshima_bus_2002"], source: "manual",
  },
  {
    slug: "konpira-pilgrim-bus",
    category: "transport", sub_type: "kagawa_chusan_transport",
    title_zh: "金刀比羅参拝臨時バス+ シャトル(琴平町+ 高松市・R1 育 金刀比羅宮派生・琴平町営シャトルバス・1 月初詣 + 4 月例大祭 + 10 月秋の例大祭 季節限定運行・JR 琴平駅-琴電琴平駅-参道下 シャトル+ 高松-琴平直行バス 1 日 8 便)",
    title_ja: "金刀比羅シャトル", romaji: "Konpira Pilgrim Bus",
    summary_zh: "**金刀比羅参拝臨時バス+シャトルは R1 育 派生・琴平町営シャトル・1 月初詣+4 月例大祭+10 月秋例大祭季節限定・高松-琴平直行 1 日 8 便**(琴平+高松)。",
    content_md: "- 立地:**仲多度郡琴平町 + 高松市**\n- 関連:**R1 育 金刀比羅宮派生**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "仲多度郡", municipality_ja: "琴平町", lg_code: "37404",
    area_types: ["transport_hub"], lat: 34.1856, lon: 133.8200,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["konpira_shuttle"], source: "manual",
  },
];

seedMain(rows, "kagawa-transport-r1");
