// Seed 秋田県 R3 補完(20 筆 / Sprint 3.x)
// 食 5 / 住 3 / 衣 2 / 育 4 / 楽 3 / 行 3 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "tohoku"; prefecture_ja: "秋田県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 食 (5)
  { slug: "akita-shoryu-tonjuro-1875", category: "food", sub_type: "akita_meika", title_zh: "湯沢双鶴堂 1875(湯沢市・1875 創業 150 年・秋田南部老舗銘菓+ 落雁+干菓子+羊羹代表+ 稲庭うどん R1 食 + 両関 R1 食 と組合せ湯沢観光土産)", title_ja: "湯沢双鶴堂", romaji: "Yuzawa Sōkakudō", summary_zh: "**湯沢双鶴堂は秋田南部老舗銘菓**(湯沢市・**1875 創業 150 年**)。落雁+干菓子+羊羹代表。", content_md: "- 製造:**湯沢双鶴堂**(湯沢市・1875 創業 150 年)\n- 並列:R1 食 諸越屋 1860 + 山田桂月堂 1930 + R3 双鶴堂 1875 = 秋田銘菓老舗 3 大", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "湯沢市", lg_code: "05206", area_types: ["shopping_district"], lat: 39.1597, lon: 140.4953, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["sokakudo", "1875", "150_years"], source: "manual" },
  { slug: "tobe-yaki-akita", category: "food", sub_type: "akita_kyodo", title_zh: "とべ焼(秋田犬 R1 育 大館発祥+ 比内地鶏 R1 食 + ねぎ等を米で煮る郷土食+ 大館発祥+ 観光客向け食事処)", title_ja: "とべ焼", romaji: "Tobe Yaki", summary_zh: "**とべ焼は大館郷土食**(大館市・**比内地鶏煮込み米**)。", content_md: "- 立地:**大館市**\n- 構成:**比内地鶏 + ねぎ + 米**", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "大館市", lg_code: "05204", area_types: ["restaurant_traditional"], lat: 40.2722, lon: 140.5642, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tobe_yaki", "odate"], source: "manual" },
  { slug: "akita-konnyaku", category: "food", sub_type: "akita_kyodo", title_zh: "秋田こんにゃく(秋田全域・江戸期から伝承+ いぶりがっこ R1 食 と並ぶ郷土食+ 田楽+刺身+味噌汁・全国シェア上位)", title_ja: "秋田こんにゃく", romaji: "Akita Konnyaku", summary_zh: "**秋田こんにゃくは江戸期から伝承郷土食**(秋田全域・**全国シェア上位**)。", content_md: "- 産地:**秋田全域**\n- 並列:R1 食 いぶりがっこ + R3 食 秋田こんにゃく = 秋田保存食 2 系統", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "秋田市", lg_code: "05201", area_types: ["industrial_heritage"], lat: 39.7178, lon: 140.1031, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["akita_konnyaku"], source: "manual" },
  { slug: "yokote-jingisukan", category: "food", sub_type: "akita_kyodo", title_zh: "横手ジンギスカン(横手市・北上山地ラム文化+ 戦後普及+ 横手市内 + 大館市内食事処+ 北海道+遠野ジンギスカン R1 食 と並ぶ全国 3 大ジンギスカン)", title_ja: "横手ジンギスカン", romaji: "Yokote Jingisukan", summary_zh: "**横手ジンギスカンは戦後北東北ラム文化**(横手市・**北上山地伝承**)。", content_md: "- 立地:**横手市**\n- 並列:**北海道ジンギスカン R1 食 + 岩手遠野ジンギスカン R1 食 + 秋田横手ジンギスカン R3 = 全国 3 大ジンギスカン**", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "横手市", lg_code: "05203", area_types: ["restaurant_traditional"], lat: 39.3119, lon: 140.5567, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yokote_jingisukan"], source: "manual" },
  { slug: "akita-fugu", category: "food", sub_type: "akita_seafood", title_zh: "秋田 ふぐ(由利本荘+男鹿沖・冬旬+ 秋田藩献上品由来+ 刺身+ふぐ鍋+ にかほ + 由利本荘料亭 + 男鹿温泉郷 R1 住 提供)", title_ja: "秋田ふぐ", romaji: "Akita Fugu", summary_zh: "**秋田ふぐは由利本荘+男鹿沖冬旬**(秋田藩献上品由来)。", content_md: "- 産地:**由利本荘 + 男鹿沖**\n- 旬:**冬**\n- 提供:**にかほ料亭 + 男鹿温泉郷 R1 住**", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "にかほ市", lg_code: "05214", area_types: ["coastal", "restaurant_traditional"], lat: 39.2667, lon: 139.9089, season_start: "2026-12-01", season_end: "2027-02-28", event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["akita_fugu", "winter"], source: "manual" },

  // 住 (3)
  { slug: "ani-onsen", category: "lodging", sub_type: "akita_other_onsen", title_zh: "阿仁温泉郷(北秋田市阿仁・R2 食 阿仁マタギ料理 関連+ 1 軒宿 阿仁の森ぶなホテル+ 内陸縦貫鉄道 R1 楽 阿仁合駅+ 1 泊 2 食 ¥10,500-15,000)", title_ja: "阿仁温泉", romaji: "Ani Onsen", summary_zh: "**阿仁温泉郷は北秋田秘湯**(北秋田市阿仁・**1 軒宿**)。", content_md: "- 立地:**北秋田市阿仁**(秋田内陸縦貫鉄道 阿仁合駅 徒歩圏)\n- 並列:R2 食 阿仁マタギ料理 + R3 住 阿仁温泉", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "北秋田市", lg_code: "05213", area_types: ["onsen_field", "mountain_village"], lat: 40.0367, lon: 140.4181, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["ani_onsen"], source: "manual" },
  { slug: "noshiro-station-hotel", category: "lodging", sub_type: "akita_morioka_chuou", title_zh: "能代駅前ホテル群(能代市・JR 五能線 + 奥羽本線 能代駅徒歩+ 全国チェーン主要+ 五能線リゾートしらかみ R1 楽 観光ベース)", title_ja: "能代駅前ホテル", romaji: "Noshiro Eki Hotel", summary_zh: "**能代駅前ホテル群は能代観光ベース**(能代市・**JR 五能線+奥羽本線**)。", content_md: "- 立地:**能代市**\n- 並列観光:R1 行 五能線+リゾートしらかみ R1 楽", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "能代市", lg_code: "05202", area_types: ["urban", "transit_hub"], lat: 40.2122, lon: 140.0264, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["noshiro_eki_hotel"], source: "manual" },
  { slug: "kazuno-station-hotel", category: "lodging", sub_type: "akita_morioka_chuou", title_zh: "鹿角花輪駅前ホテル群(鹿角市・JR 鹿角花輪駅徒歩+ R1 食 鹿角桃 + R1 育 大湯環状列石 + R1 楽 八幡平アスピーテ秋田側 観光ベース)", title_ja: "鹿角花輪駅前ホテル", romaji: "Kazuno Eki Hotel", summary_zh: "**鹿角花輪駅前ホテル群は鹿角観光ベース**(鹿角市・**世遺観光基幹**)。", content_md: "- 立地:**鹿角市**\n- 並列観光:R1 育 大湯環状列石 + R1 食 鹿角桃 + R1 食 かづの牛", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "鹿角市", lg_code: "05209", area_types: ["urban", "transit_hub"], lat: 40.2153, lon: 140.7878, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["kazuno_eki_hotel"], source: "manual" },

  // 衣 (2)
  { slug: "akita-suzumushi-jinja-omamori", category: "fashion", sub_type: "akita_folk_craft", title_zh: "秋田鈴虫神社 R3 育 お守り(秋田市・縁結び+商売繁盛 鈴虫由来鈴形お守り+ 道の駅秋田 + 観光土産代表+ 唐松神社 R1 育 鈴形お守りと並ぶ秋田縁結びお守り 2 大)", title_ja: "鈴虫神社お守り", romaji: "Suzumushi Omamori", summary_zh: "**秋田鈴虫神社お守り**(秋田市・**縁結び鈴形**)。", content_md: "- 立地:**秋田市**\n- 並列:R1 育 唐松神社(縁結び女人神)+ R3 鈴虫神社お守り = 秋田縁結び 2 大", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "秋田市", lg_code: "05201", area_types: ["shrine_temple", "shopping_district"], lat: 39.7178, lon: 140.1031, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["suzumushi_omamori"], source: "manual" },
  { slug: "akita-shoju", category: "fashion", sub_type: "akita_folk_craft", title_zh: "秋田 樗(おうち)細工(秋田全域・センダン樹由来民芸+ 江戸期から伝承+ 数珠+珠玉+お守り素材代表+ 観光土産)", title_ja: "秋田樗細工", romaji: "Akita Ōchi", summary_zh: "**秋田樗細工はセンダン樹由来民芸**(秋田・**江戸期伝承**)。", content_md: "- 産地:**秋田全域**\n- 用途:**数珠+珠玉+お守り素材**", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "秋田市", lg_code: "05201", area_types: ["craft_workshop"], lat: 39.7178, lon: 140.1031, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ouchi_zaiku"], source: "manual" },

  // 育 (4)
  { slug: "ise-doukai-iseki", category: "culture", sub_type: "akita_jomon", title_zh: "伊勢堂岱遺跡(北秋田市・縄文後期 4,000 年前+ UNESCO 世界文化遺産 2021 構成資産+ 4 環状列石 + 国指定史跡 2001+ 入場無料・大湯 R1 育 と並ぶ秋田縄文世遺 2 大)", title_ja: "伊勢堂岱遺跡", romaji: "Ise Doukai", summary_zh: "**伊勢堂岱遺跡は秋田縄文世遺**(北秋田市・**4 環状列石・縄文後期 4,000 年前**)。UNESCO 2021 構成。", content_md: "- 立地:**北秋田市脇神**\n- 認定:**UNESCO 世遺 2021 構成資産 + 国指定史跡 2001**\n- 並列:**R1 育 大湯環状列石 + R3 伊勢堂岱遺跡 = 秋田縄文世遺 2 大**", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "北秋田市", lg_code: "05213", area_types: ["history_site_castle"], lat: 40.1944, lon: 140.3717, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ise_doukai", "4000_years", "unesco_2021"], source: "manual" },
  { slug: "kosaka-meiji-100-yen-mura", category: "culture", sub_type: "akita_meiji_taisho", title_zh: "小坂 明治百年通り(小坂町・小坂鉱山事務所 1905 + 康楽館 1910 + 旧小坂鉱山病院 等明治建築群+ 国指定重要文化財 2002+ 「日本最古」現役歌舞伎劇場 康楽館)", title_ja: "小坂明治百年通り", romaji: "Kosaka Meiji 100", summary_zh: "**小坂明治百年通りは明治建築群**(鹿角郡小坂町・**国指定重要文化財 2002**)。康楽館 1910「日本最古」現役歌舞伎劇場。", content_md: "- 立地:**鹿角郡小坂町**\n- 認定:**国指定重要文化財 2002**(康楽館 + 小坂鉱山事務所)\n- 並列:R1 育 旧黒澤家 1882 + 赤れんが郷土館 1912 + R3 小坂明治建築群 = 秋田明治洋館 3 大", region: "tohoku", prefecture_ja: "秋田県", gun_ja: "鹿角郡", municipality_ja: "小坂町", lg_code: "05303", area_types: ["museum_art", "historic_district"], lat: 40.3878, lon: 140.7325, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kosaka_meiji", "1905_1910", "2002_imp_cultural"],source: "manual" },
  { slug: "akita-yamabushi-shugen", category: "culture", sub_type: "akita_shrine_temple", title_zh: "太平山三吉神社 R1 育 派生 山伏修験道(秋田市・霊峰太平山 1170m + 江戸期から修験道伝承+ 修行者 山伏文化+ 秋田藩佐竹氏 1602- 御祈願関連)", title_ja: "秋田山伏修験", romaji: "Akita Yamabushi", summary_zh: "**秋田山伏修験は太平山三吉神社派生**(秋田市・**江戸期から修験道**)。", content_md: "- 立地:**秋田市・太平山**\n- 関連:R1 育 太平山三吉神社", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "秋田市", lg_code: "05201", area_types: ["shrine_temple", "mountain_village"], lat: 39.7350, lon: 140.1322, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yamabushi_shugen"], source: "manual" },
  { slug: "akita-toogi-akarengakan", category: "culture", sub_type: "akita_history_museum", title_zh: "秋田市赤れんが郷土館 + 関連明治建築群(R1 育 赤れんが郷土館派生・周辺旧秋田銀行支店 + 千秋公園隣接歴史地区+ 秋田明治期金融建築総合)", title_zh_short: null, title_ja: "秋田明治建築群", romaji: "Akita Meiji Architecture", summary_zh: "**秋田明治建築群は R1 育 赤れんが郷土館派生**(秋田市)。", content_md: "- 立地:**秋田市・千秋公園隣接**\n- 関連:R1 育 赤れんが郷土館", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "秋田市", lg_code: "05201", area_types: ["historic_district", "museum_art"], lat: 39.7211, lon: 140.0972, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["akita_meiji_arch"], source: "manual" },

  // 楽 (3)
  { slug: "yokote-bonten", category: "entertainment", sub_type: "akita_other_festivals", title_zh: "横手ぼんでん(横手市・2 月 17 日・国指定重要無形民俗 関連+ 旭岡山神社 奉納行事+ 5 メートル超の竹竿に幟+ R1 楽 横手かまくら祭翌日)", title_ja: "横手ぼんでん", romaji: "Yokote Bonten", summary_zh: "**横手ぼんでんは旭岡山神社奉納**(横手市・**2 月 17 日**)。R1 楽 横手かまくら祭翌日。", content_md: "- 開催:**毎年 2 月 17 日**\n- 並列:R1 楽 横手かまくら 2/15-16 + R3 ぼんでん 2/17 = 横手雪祭 3 日連続", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "横手市", lg_code: "05203", area_types: ["festival_event"], lat: 39.3119, lon: 140.5567, season_start: null, season_end: null, event_start: "2026-02-17", event_end: "2026-02-17", price_tier: 1, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["yokote_bonten", "february_17"], source: "manual" },
  { slug: "ani-skiing", category: "entertainment", sub_type: "akita_outdoor", title_zh: "阿仁スキー場(北秋田市阿仁・1981 開業 44 年+ 第三セクター系+ 全 8 コース+ 12-4 月運営+ 秋田内陸縦貫鉄道 R1 楽 阿仁合駅 から路線バス連絡+ R2 食 阿仁マタギ料理 と組合せ観光)", title_ja: "阿仁スキー場", romaji: "Ani Ski", summary_zh: "**阿仁スキー場は北秋田スキー場**(北秋田市阿仁・**1981 開業 44 年**)。", content_md: "- 立地:**北秋田市阿仁**\n- 開業:**1981 年・44 年**\n- 並列:**岩手安比 R1 楽 + 秋田阿仁 R3 + 雫石 R5 楽 = 北東北スキー 3 大**", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "北秋田市", lg_code: "05213", area_types: ["scenic_spot", "mountain_village"], lat: 40.0367, lon: 140.4181, season_start: "2026-12-01", season_end: "2027-04-15", event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["ani_ski", "1981"], source: "manual" },
  { slug: "tazawako-cycling", category: "entertainment", sub_type: "akita_tazawako", title_zh: "田沢湖一周サイクリング(R1 楽 田沢湖派生・全周 19km・90-120 分・湖畔自転車道整備+ 田沢湖駅前レンタサイクル ¥1,500/日)", title_ja: "田沢湖一周サイクリング", romaji: "Tazawako Cycling", summary_zh: "**田沢湖一周サイクリングは R1 楽 田沢湖派生**(仙北市・**全周 19km**)。", content_md: "- 立地:**仙北市田沢湖畔**\n- 規模:**全周 19km**\n- レンタサイクル:**¥1,500/日**", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "仙北市", lg_code: "05215", area_types: ["scenic_spot", "transit_hub"], lat: 39.7244, lon: 140.6589, season_start: "2026-04-01", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tazawako_cycling", "19km"], source: "manual" },

  // 行 (3)
  { slug: "akita-airport-direct-bus-tazawako", category: "transport", sub_type: "akita_bus", title_zh: "秋田空港-田沢湖直通バス(秋田空港 → 田沢湖 → 角館 観光バス・夏季限定+ 約 2 時間+ ¥3,500+ 観光客向け空港-観光地直通便利)", title_ja: "空港田沢湖直通", romaji: "Airport Tazawako Direct", summary_zh: "**秋田空港-田沢湖直通バスは観光客向け**(夏季限定・**約 2 時間 ¥3,500**)。", content_md: "- 区間:**秋田空港 → 田沢湖 → 角館**\n- 期:**夏季限定**", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "秋田市", lg_code: "05201", area_types: ["transit_hub"], lat: 39.6156, lon: 140.2189, season_start: "2026-04-25", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["airport_tazawako_bus", "summer_only"], source: "manual" },
  { slug: "akita-rental-cycle-network", category: "transport", sub_type: "akita_road", title_zh: "秋田レンタサイクル網(秋田駅 + 角館駅 + 横手駅 + 田沢湖畔 + 男鹿駅+ 1 日 ¥1,300-1,800+ 各観光地で受取可能+ レンタカー無し旅行者向け補完手段)", title_ja: "秋田レンタサイクル", romaji: "Akita Rental Cycle", summary_zh: "**秋田レンタサイクル網は各観光地で受取**(秋田駅 + 角館駅 + 横手駅 + 田沢湖畔 + 男鹿駅・**¥1,300-1,800/日**)。", content_md: "- 拠点:**秋田駅 + 角館駅 + 横手駅 + 田沢湖畔 + 男鹿駅**\n- 料金:**¥1,300-1,800/日**\n- 並列:岩手平泉レンタサイクル R3 行(¥1,300)+ 秋田レンタサイクル網 R3 = 北東北レンタサイクル 2 大", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "秋田市", lg_code: "05201", area_types: ["transit_hub"], lat: 39.7178, lon: 140.1031, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["rental_cycle"], source: "manual" },
  { slug: "akita-yamagata-bus", category: "transport", sub_type: "akita_bus", title_zh: "秋田-山形高速バス(東北自動車道+ 山形自動車道経由・約 4 時間 30 分・¥4,800+ 1 日 4-5 便+ 鳥海ブルーライン R1 行 経由 鳥海山+山形蔵王 観光連絡)", title_ja: "秋田-山形バス", romaji: "Akita Yamagata Bus", summary_zh: "**秋田-山形高速バスは秋田-山形連絡**(**約 4 時間 30 分・¥4,800**)。", content_md: "- 区間:**秋田駅 ↔ 山形駅**\n- 並列観光:**鳥海ブルーライン R1 行 経由 + 山形蔵王 連絡**", region: "tohoku", prefecture_ja: "秋田県", gun_ja: null, municipality_ja: "秋田市", lg_code: "05201", area_types: ["transit_hub"], lat: 39.7178, lon: 140.1031, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["akita_yamagata_bus"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[akita-r3] 尚無條目"); return; }
  console.log(`[akita-r3] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[akita-r3] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[akita-r3] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[akita-r3] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
