// Seed 宮城県 R4 補完(20 筆 / Sprint 4.x)
// 食 4 / 住 3 / 衣 3 / 育 4 / 楽 4 / 行 2 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "tohoku"; prefecture_ja: "宮城県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 食 (4)
  { slug: "matsushima-hotate", category: "food", sub_type: "miyagi_seafood", title_zh: "松島ホタテ(松島湾+ R1 食 松島牡蠣と並ぶ松島湾養殖魚介+ 通年養殖+ 焼ホタテ+刺身+海鮮丼+ 松島観光物産店+牡蠣小屋併設+ 1 個 ¥300-600+ R1 育 松島観光客向け)", title_ja: "松島ホタテ", romaji: "Matsushima Hotate", summary_zh: "**松島ホタテは松島湾養殖魚介**(R1 食 松島牡蠣と並ぶ・**通年養殖**)。焼+刺身+海鮮丼、観光物産店+牡蠣小屋、¥300-600/個。", content_md: "- 立地:**宮城郡松島町・松島湾**\n- 期:**通年養殖**\n- 並列:**R1 食 松島牡蠣 + R3 食 松島あなご + R4 食 松島ホタテ = 松島魚介 3 大**\n- 価格:**1 個 ¥300-600**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "松島町", lg_code: "04401", area_types: ["restaurant_traditional"], lat: 38.3742, lon: 141.0589, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["matsushima_hotate"], source: "manual" },
  { slug: "shichigahama-shirasu", category: "food", sub_type: "miyagi_seafood", title_zh: "七ヶ浜しらす(宮城郡七ヶ浜町・三陸沿岸 1 月旬 + 4-12 月+ 釜揚げしらす+生しらす+ R1 食 三陸海産+ 七ヶ浜港朝市+全国百貨店流通+ ¥400-800/100g+ 観光客向け沿岸代表海産)", title_ja: "七ヶ浜しらす", romaji: "Shichigahama Shirasu", summary_zh: "**七ヶ浜しらすは三陸沿岸海産**(七ヶ浜町・**1 月旬+4-12 月**)。釜揚げ+生しらす、港朝市+全国百貨店、¥400-800/100g。", content_md: "- 立地:**宮城郡七ヶ浜町**\n- 期:**1 月旬 + 4-12 月**\n- 用途:**釜揚げ + 生しらす**\n- 価格:**¥400-800/100g**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "七ヶ浜町", lg_code: "04404", area_types: ["restaurant_traditional", "industrial_heritage"], lat: 38.2933, lon: 141.0531, season_start: "2026-04-01", season_end: "2026-12-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["shichigahama_shirasu"], source: "manual" },
  { slug: "kurihara-uri-no-asazuke", category: "food", sub_type: "miyagi_kyodo", title_zh: "栗原瓜の浅漬(栗原市・江戸期から伝承+ 「栗原 7 まる漬」(うり+きゅうり+きゃべつ+大根 等)+ 道の駅 + R1 楽 伊豆沼+R2 楽 蕪栗沼観光と組合せ+ 1 袋 ¥500-1,500+ 観光土産)", title_ja: "栗原瓜の浅漬", romaji: "Kurihara Uri Asazuke", summary_zh: "**栗原瓜の浅漬は江戸期から伝承「栗原 7 まる漬」**(栗原市・**うり+きゅうり+きゃべつ+大根 等**)。道の駅、R1 楽 伊豆沼+R2 楽 蕪栗沼観光、¥500-1,500/袋。", content_md: "- 立地:**栗原市**\n- 起源:**江戸期から伝承**\n- 構成:**「栗原 7 まる漬」(うり + きゅうり + きゃべつ + 大根 等)**\n- 価格:**1 袋 ¥500-1,500**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "栗原市", lg_code: "04211", area_types: ["restaurant_traditional"], lat: 38.7178, lon: 141.1167, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kurihara_asazuke", "edo_origin"], source: "manual" },
  { slug: "miyagi-natto-sendai", category: "food", sub_type: "miyagi_kyodo", title_zh: "仙台納豆(仙台市・江戸期 仙台藩献上納豆+ 県内納豆メーカー 5+ 軒(亀千代+丸金+齋藤食品 等)+ 朝食定食+ 全国百貨店流通+ 1 パック ¥150-400+ R1 食 仙台味噌 と並ぶ仙台発酵食 2 大)", title_ja: "仙台納豆", romaji: "Sendai Nattō", summary_zh: "**仙台納豆は江戸期仙台藩献上**(仙台市・**メーカー 5+ 軒**)。R1 食 仙台味噌と並ぶ仙台発酵食 2 大、全国百貨店、¥150-400。", content_md: "- 立地:**仙台市**\n- 起源:**江戸期 仙台藩献上**\n- メーカー:**亀千代 + 丸金 + 齋藤食品 等 5+ 軒**\n- 並列:**R1 食 仙台味噌 + R4 食 仙台納豆 = 仙台発酵食 2 大**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["industrial_heritage"], lat: 38.2625, lon: 140.8814, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["sendai_natto", "edo_offering"], source: "manual" },

  // 住 (3)
  { slug: "sendai-monterey", category: "lodging", sub_type: "miyagi_sendai_chuou", title_zh: "ホテルモントレ仙台(仙台市青葉区・1992 開業+ 全 200 室+ 「ヨーロピアンクラシック」テーマ建築+ JR 仙台駅徒歩 2 分+ 1 泊 ¥10,500-16,500+ 観光客向け女性人気高い)", title_ja: "ホテルモントレ仙台", romaji: "Hotel Monterey Sendai", summary_zh: "**ホテルモントレ仙台はヨーロピアンクラシックテーマ**(青葉区・**1992 開業+全 200 室**)。JR 仙台駅徒歩 2 分、¥10,500-16,500、女性人気。", content_md: "- 立地:**仙台市青葉区**(JR 仙台駅徒歩 2 分)\n- 起源:**1992 開業 33 年**\n- 規模:**全 200 室**\n- 看板:**ヨーロピアンクラシックテーマ建築**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["shopping_district"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["monterey_sendai", "1992", "200_rooms"], source: "manual" },
  { slug: "sukawa-onsen-yado", category: "lodging", sub_type: "miyagi_other_onsen", title_zh: "須川温泉宿(栗原市・R1 楽 栗駒山登山口拠点+ 1500 年伝承+ 含硫黄塩化物泉+ 全 4 軒旅館・栗駒荘+大日岩+須川大芝・1 泊 2 食 ¥10,500-15,500+ 5-10 月営業 紅葉期混雑)", title_ja: "須川温泉宿", romaji: "Sukawa Onsen-yado", summary_zh: "**須川温泉宿は R1 楽 栗駒山登山口拠点**(栗原市・**1500 年伝承+含硫黄塩化物泉**)。全 4 軒、5-10 月営業、紅葉期混雑、¥10,500-15,500。", content_md: "- 立地:**栗原市**\n- 関係:**R1 楽 栗駒山登山口 + R3 楽 栗駒トレッキング**\n- 起源:**1500 年伝承**\n- 源泉:**含硫黄塩化物泉**\n- 規模:**全 4 軒**(栗駒荘 + 大日岩 + 須川大芝)\n- 期:**5-10 月営業**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "栗原市", lg_code: "04211", area_types: ["onsen_field", "mountain_village"], lat: 38.9697, lon: 140.7842, season_start: "2026-05-01", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 3, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["sukawa_onsen", "1500_years", "kurikoma_base"], source: "manual" },
  { slug: "matsushima-petite-hotel", category: "lodging", sub_type: "miyagi_matsushima_lodge", title_zh: "松島プチホテル+ペンション群(松島町+南三陸町・全 12 軒小規模+ 全 5-15 室+ 1 泊 2 食 ¥9,500-15,500+ R1 育 松島+R1 食 牡蠣 観光客向け価格手頃+ ファミリー+カップル向け)", title_ja: "松島プチホテル+ペンション", romaji: "Matsushima Petite Hotel", summary_zh: "**松島プチホテル+ペンション群は全 12 軒小規模**(松島+南三陸・**5-15 室**)。¥9,500-15,500、R1 育 松島+R1 食 牡蠣観光、ファミリー+カップル向け。", content_md: "- 立地:**宮城郡松島町 + 南三陸町**\n- 規模:**全 12 軒・5-15 室**\n- 価格:**¥9,500-15,500**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "松島町", lg_code: "04401", area_types: ["scenic_spot"], lat: 38.3742, lon: 141.0589, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["matsushima_petite", "12_inns"], source: "manual" },

  // 衣 (3)
  { slug: "naruko-shikki-modern", category: "fashion", sub_type: "miyagi_folk_craft", title_zh: "鳴子塗(大崎市鳴子・江戸期 1700 年代+ 国指定伝統的工芸品 1991+ 木地師+漆塗り工芸品+ 椀+盆+小箱+ R1 衣 仙台堆朱+R1 衣 玉虫塗 と並ぶ宮城漆芸 3 大+ ¥3,500-25,000)", title_ja: "鳴子塗", romaji: "Naruko Nuri", summary_zh: "**鳴子塗は江戸期 1700 年代+国指定伝統的工芸品 1991**(鳴子・**木地師+漆塗り**)。R1 衣 仙台堆朱+玉虫塗 と並ぶ宮城漆芸 3 大、¥3,500-25,000。", content_md: "- 立地:**大崎市鳴子温泉**\n- 起源:**江戸期 1700 年代**\n- 認定:**国指定伝統的工芸品 1991**\n- 構成:**木地師 + 漆塗り**\n- 並列:**R1 衣 仙台堆朱 + 玉虫塗 + R4 衣 鳴子塗 = 宮城漆芸 3 大**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "大崎市", lg_code: "04213", area_types: ["craft_workshop"], lat: 38.7375, lon: 140.7250, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["naruko_nuri", "1700s", "1991_dento"], source: "manual" },
  { slug: "iwadeyama-takeshikkougei", category: "fashion", sub_type: "miyagi_folk_craft", title_zh: "岩出山竹細工(大崎市岩出山・伊達政宗 1591 岩出山転居期に伝承+ 県伝統工芸品+ 篭+ザル+ 茶道具+花器+ R3 育 とよま明治村+ 道の駅+ ¥1,800-15,000)", title_ja: "岩出山竹細工", romaji: "Iwadeyama Takezaiku", summary_zh: "**岩出山竹細工は伊達政宗 1591 転居期伝承**(大崎市・**県伝統工芸品**)。篭+ザル+茶道具+花器、R3 育 とよま明治村+道の駅、¥1,800-15,000。", content_md: "- 立地:**大崎市岩出山**\n- 起源:**伊達政宗 1591 岩出山転居期伝承**\n- 認定:**県伝統工芸品**\n- 用途:**篭 + ザル + 茶道具 + 花器**\n- 価格:**¥1,800-15,000**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "大崎市", lg_code: "04213", area_types: ["craft_workshop"], lat: 38.5747, lon: 140.9536, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["iwadeyama_take", "1591_date_transit"], source: "manual" },
  { slug: "sendai-character-anime-shop", category: "fashion", sub_type: "miyagi_folk_craft", title_zh: "アニメイト+ ジャンプショップ仙台(仙台市青葉区・JR 仙台駅徒歩 5 分+ 全国アニメショップ仙台店+ 仮面ライダー (R1 衣 石ノ森) 関連 + ジャンプ作品+進撃の巨人 等+ 観光客向け+ ¥500-15,000)", title_ja: "アニメイト+ジャンプショップ仙台", romaji: "Animate / Jump Shop Sendai", summary_zh: "**アニメイト+ジャンプショップ仙台はアニメショップ拠点**(青葉区・**JR 仙台駅徒歩 5 分**)。仮面ライダー(石ノ森)+ジャンプ+進撃の巨人、¥500-15,000。", content_md: "- 立地:**仙台市青葉区**(JR 仙台駅徒歩 5 分)\n- 関連:**R1 衣 石ノ森萬画館グッズ + 仮面ライダー(石ノ森作)**\n- 構成:**ジャンプ作品 + 進撃の巨人 + アニメ全般**\n- 価格:**¥500-15,000**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["shopping_district"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["sendai_animate", "jump_shop", "anime"], source: "manual" },

  // 育 (4)
  { slug: "tagajou-hi-stelae-740", category: "culture", sub_type: "miyagi_history_museum", title_zh: "多賀城碑(多賀城市・国宝 2024 指定・「日本三古碑」(多賀城碑+那須国造碑+多胡碑)+ 762 古代陸奥国府碑文+ 万葉集大伴家持関連+ 入場無料・覆屋保存+ R1 育 多賀城跡 隣接)", title_ja: "多賀城碑", romaji: "Tagajō-hi", summary_zh: "**多賀城碑は国宝 2024 指定・日本三古碑**(多賀城+那須国造+多胡)。**762 古代陸奥国府碑文**、万葉集大伴家持関連、入場無料、R1 育 多賀城跡隣接。", content_md: "- 立地:**多賀城市**(R1 育 多賀城跡)\n- 起源:**762 古代陸奥国府碑文**\n- 認定:**国宝 2024 指定 + 「日本三古碑」**(多賀城 + 那須国造 + 多胡)\n- 関連:**万葉集大伴家持**\n- 入場:**無料・覆屋保存**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "多賀城市", lg_code: "04208", area_types: ["history_site_castle"], lat: 38.2956, lon: 140.9986, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tagajo_hi", "2024_kokuhou", "762", "japan_3_kokuhi"], source: "manual" },
  { slug: "miyagi-yagiyama-arena", category: "culture", sub_type: "miyagi_modern_art", title_zh: "せんだい青葉山公園(仙台市青葉区・R1 育 仙台城跡 周辺・1916 都市公園化+ 国指定史跡 2003+ 桜+紅葉名所+ 仙台青葉まつり R1 楽 メイン+ 入場無料・市民憩いの場代表)", title_ja: "せんだい青葉山公園", romaji: "Sendai Aobayama Kōen", summary_zh: "**せんだい青葉山公園は仙台城跡周辺都市公園**(青葉区・**1916 都市公園化+国指定史跡 2003**)。桜+紅葉名所、R1 楽 青葉まつりメイン、無料、市民憩いの場。", content_md: "- 立地:**仙台市青葉区**(R1 育 仙台城跡周辺)\n- 起源:**1916 都市公園化**\n- 認定:**国指定史跡 2003**\n- 期:**桜 4 月 + 紅葉 10-11 月**\n- 並列:**R1 楽 仙台青葉まつりメイン**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["scenic_spot", "history_site_castle"], lat: 38.2522, lon: 140.8567, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aobayama_park", "1916", "2003_shiseki"], source: "manual" },
  { slug: "ishinomori-kakuda-takasaki", category: "culture", sub_type: "miyagi_modern_art", title_zh: "石ノ森章太郎ふるさと記念館(登米市中田・1939-1998 石ノ森章太郎生家関連+ R1 衣 石ノ森+ R1 育 萬画館(石巻)派生・出身地展示+ 1996 開館+ 入館 ¥500+ 萬画館と組合せ)", title_ja: "石ノ森章太郎ふるさと記念館", romaji: "Ishinomori Furusato Kinenkan", summary_zh: "**石ノ森章太郎ふるさと記念館は出身地登米市派生**(R1 衣+R1 育 萬画館+R4 出身地・**1939-1998・1996 開館**)。入館 ¥500、萬画館組合せ。", content_md: "- 立地:**登米市中田**(石ノ森章太郎出身地)\n- 起源:**1996 開館**\n- 縁:**石ノ森章太郎 1939-1998 出身地**\n- 並列:**R1 衣 石ノ森グッズ + R1 育 萬画館(石巻) + R4 育 ふるさと記念館(登米) = 石ノ森 3 大施設**\n- 入館:**¥500**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "登米市", lg_code: "04210", area_types: ["museum_art"], lat: 38.6964, lon: 141.2719, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["火"], external_urls: {}, tags: ["ishinomori_furusato", "1996"], source: "manual" },
  { slug: "fujiwara-no-sanekata-kasugai", category: "culture", sub_type: "miyagi_shrine_temple", title_zh: "藤原実方塚(名取市笠島・平安期歌人 藤原実方 1000 年没・「実方の塚」+ 県史跡+ 西行+松尾芭蕉 訪問記録+ 入場無料+ 笠島道祖神社 隣接)", title_ja: "藤原実方塚", romaji: "Fujiwara Sanekata Tsuka", summary_zh: "**藤原実方塚は平安期歌人 藤原実方 1000 年没**(名取市・**西行+松尾芭蕉 訪問記録**)。県史跡、笠島道祖神社隣接、入場無料。", content_md: "- 立地:**名取市笠島**\n- 縁:**平安期歌人 藤原実方 1000 年没**\n- 認定:**県史跡**\n- 関連:**西行 + 松尾芭蕉 訪問記録**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "名取市", lg_code: "04206", area_types: ["shrine_temple", "history_site_castle"], lat: 38.1719, lon: 140.8917, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["sanekata_tsuka", "heian", "1000", "saigyo_basho"], source: "manual" },

  // 楽 (4)
  { slug: "matsushima-illumination-fes", category: "entertainment", sub_type: "miyagi_matsushima", title_zh: "松島ハーバーライトページェント+カキ祭り(松島町・1985 開始+ 12 月初-下旬+ R1 育 松島湾沿岸 25 万球イルミネーション+ R1 食 松島牡蠣 ライブ+ 観覧無料+ R1 楽 仙台光のページェント と並ぶ宮城冬イルミ 2 大)", title_ja: "松島ハーバーライトページェント", romaji: "Matsushima Harbor Light Pageant", summary_zh: "**松島ハーバーライトページェントは 1985 開始**(松島町・**12 月+25 万球+松島湾沿岸**)。R1 食 牡蠣ライブ併催、無料、R1 楽 仙台光ペと並ぶ宮城冬イルミ 2 大。", content_md: "- 立地:**宮城郡松島町**\n- 起源:**1985 開始 40 年**\n- 期:**12 月初-下旬**\n- 規模:**25 万球イルミネーション + 松島湾沿岸**\n- 並列:**R1 食 松島牡蠣ライブ + R1 楽 仙台光のページェント**\n- 観覧:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "松島町", lg_code: "04401", area_types: ["festival_event", "scenic_spot"], lat: 38.3742, lon: 141.0589, season_start: null, season_end: null, event_start: "2026-12-05", event_end: "2026-12-31", price_tier: 1, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["matsushima_illumination", "1985", "250k_lights"], source: "manual" },
  { slug: "kesennuma-fukahire-festival", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "気仙沼みなとまつり(気仙沼市・1953 開始 72 年+ 8 月第 1 週末+ 気仙沼港+魚市場会場+ 海上パレード+花火+ R1 食 気仙沼ふかひれ 直売+ 観覧無料+ 三陸代表夏祭)", title_ja: "気仙沼みなとまつり", romaji: "Kesennuma Minato Matsuri", summary_zh: "**気仙沼みなとまつりは 1953 開始 72 年**(気仙沼港+魚市場・**8 月第 1 週末**)。海上パレード+花火、R1 食 ふかひれ直売、観覧無料、三陸代表夏祭。", content_md: "- 立地:**気仙沼市**\n- 起源:**1953 開始 72 年**\n- 期:**毎年 8 月第 1 週末**\n- 構成:**海上パレード + 花火 + 魚市場縁日**\n- 並列:**R1 食 気仙沼ふかひれ直売**\n- 観覧:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "気仙沼市", lg_code: "04203", area_types: ["festival_event"], lat: 38.9069, lon: 141.5703, season_start: null, season_end: null, event_start: "2026-08-01", event_end: "2026-08-02", price_tier: 1, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["kesennuma_minato", "1953", "72_years"], source: "manual" },
  { slug: "rifu-grand-stadium", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "ベガルタ仙台 ユアテックスタジアム仙台(宮城郡利府町・1992 完成 33 年+ J リーグ ベガルタ仙台本拠地+ 全 19,694 席+ 仙台市内 タクシー 30 分+ 観戦 ¥2,500-8,500+ 4-11 月シーズン)", title_ja: "ユアテックスタジアム仙台", romaji: "Yurtec Stadium Sendai", summary_zh: "**ユアテックスタジアム仙台はベガルタ仙台本拠地**(利府町・**1992 完成+全 19,694 席**)。J リーグ、仙台市内タクシー 30 分、¥2,500-8,500、4-11 月。", content_md: "- 立地:**宮城郡利府町**\n- 起源:**1992 完成 33 年**\n- 規模:**全 19,694 席**\n- リーグ:**J リーグ ベガルタ仙台**\n- 並列:**R1 楽 楽天モバイルパーク(野球) + R4 楽 ユアテック(サッカー) = 仙台プロスポーツ 2 大**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "利府町", lg_code: "04406", area_types: ["scenic_spot"], lat: 38.3625, lon: 140.9817, season_start: "2026-04-01", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["yurtec_stadium", "1992", "vegalta"], source: "manual" },
  { slug: "naruko-hot-spring-festival", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "鳴子温泉まつり(大崎市・1955 開始+ 9 月第 2 土日+ R1 住 鳴子温泉郷 5 系統合同祭+ こけしパレード+ 流し踊り+ 屋台+ 全国温泉客集中+ 観覧無料+ R1 衣 鳴子こけしと組合せ)", title_ja: "鳴子温泉まつり", romaji: "Naruko Onsen Matsuri", summary_zh: "**鳴子温泉まつりは 1955 開始**(大崎市・**9 月第 2 土日+ R1 住 鳴子温泉郷 5 系統合同祭**)。こけしパレード+流し踊り+屋台、全国温泉客、無料。", content_md: "- 立地:**大崎市鳴子温泉**\n- 起源:**1955 開始 70 年**\n- 期:**毎年 9 月第 2 土日**\n- 構成:**こけしパレード + 流し踊り + 屋台**\n- 並列:**R1 衣 鳴子こけし + R1 住 鳴子温泉郷**\n- 観覧:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "大崎市", lg_code: "04213", area_types: ["festival_event"], lat: 38.7375, lon: 140.7250, season_start: null, season_end: null, event_start: "2026-09-12", event_end: "2026-09-13", price_tier: 1, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["naruko_onsen_matsuri", "1955", "kokeshi_parade"], source: "manual" },

  // 行 (2)
  { slug: "tohoku-jr-pass-area", category: "transport", sub_type: "miyagi_pass_ticket", title_zh: "JR 東日本パス・東北エリア+JR EAST PASS Tohoku(訪日外国人 + 居住者向け 5 日連続使用 ¥30,000-37,500+ R1 行 東北新幹線+在来線 乗り放題+ 仙台 → 青森+秋田+山形+福島+新潟一周可能+ 海外観光客代表)", title_ja: "JR EAST PASS Tohoku", romaji: "JR East Pass Tohoku", summary_zh: "**JR EAST PASS Tohoku は 5 日連続乗り放題 ¥30,000-37,500**(訪日外国人+居住者向け)。R1 行 東北新幹線+在来線、青森+秋田+山形+福島+新潟一周。", content_md: "- 対象:**訪日外国人 + 在住者向け**\n- 期:**5 日連続使用**\n- 料金:**¥30,000-37,500**\n- 対応:**R1 行 東北新幹線(仙台) + 在来線 乗り放題**\n- 範囲:**東北 6 県 + 新潟県**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["transit_hub"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 7, closed_days: [], external_urls: {}, tags: ["jr_east_pass_tohoku", "5_days", "30000yen"], source: "manual" },
  { slug: "shiogama-matsushima-pass", category: "transport", sub_type: "miyagi_pass_ticket", title_zh: "るーぷる仙台+松島・塩釜エリアパス(JR 東日本+市営地下鉄+るーぷる仙台共通券・1 日 ¥1,440+ JR 仙石線(本塩釜+松島海岸 含)+地下鉄+循環バス・観光ピンポイント代表+ 仙台駅売店 + 観光案内所購入)", title_ja: "松島・塩釜エリアパス", romaji: "Matsushima Shiogama Area Pass", summary_zh: "**松島・塩釜エリアパスは 1 日 ¥1,440**(JR 仙石線+地下鉄+るーぷる仙台共通)。JR 仙石線・本塩釜・松島海岸+地下鉄+循環バス、観光向け。", content_md: "- 対象:**JR 仙石線(松島海岸 + 本塩釜 含) + 地下鉄南北+東西 + るーぷる仙台**\n- 料金:**1 日 ¥1,440**\n- 並列観光:**R1 育 松島 + R1 楽 松島湾遊覧 + R1 育 鹽竈神社 + 仙台市内**\n- 購入:**仙台駅売店 + 観光案内所**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["transit_hub"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["matsushima_shiogama_pass", "1440yen"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[miyagi-r4] 尚無條目"); return; }
  console.log(`[miyagi-r4] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[miyagi-r4] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[miyagi-r4] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[miyagi-r4] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
