// Seed 茨城県 衣 R1(18 筆 / Sprint 1.2)
// 結城紬+笠間焼 5 / 真壁石燈籠+伝統工芸 3 / R1 食派生グッズ 3 / 商店街+百貨店 5 / ご当地キャラ 2 = 18

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "茨城県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 結城紬+笠間焼 (5)
  { slug: "yuki-tsumugi-unesco-2010", category: "fashion", sub_type: "ibaraki_yuki_tsumugi", title_zh: "結城紬(結城市・栃木県境跨ぎ・1500 年伝承(奈良期)・国指定伝統工芸 1956+ UNESCO 無形文化遺産 2010+ 真綿手紡ぎ+居坐機織り+ 1 反 ¥350,000-1,200,000+ 老舗 工房 5+ 軒+ 全国紬最高峰)", title_ja: "結城紬", romaji: "Yūki Tsumugi", summary_zh: "**結城紬は 1500 年伝承(奈良期)・国指定伝統工芸 1956+UNESCO 無形 2010**(結城・**真綿手紡ぎ+居坐機織り**)。¥350,000-1,200,000/反、老舗 5+ 軒、全国紬最高峰。", content_md: "- 立地:**結城市**(栃木県境跨ぎ)\n- 起源:**1500 年伝承(奈良期)**\n- 認定:**国指定伝統工芸 1956 + UNESCO 無形文化遺産 2010**\n- 構成:**真綿手紡ぎ + 居坐機織り**\n- 価格:**1 反 ¥350,000-1,200,000**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "結城市", lg_code: "08207", area_types: ["craft_workshop", "industrial_heritage"], lat: 36.3056, lon: 139.8758, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yuki_tsumugi", "1500_years", "1956_dento", "unesco_2010"], source: "manual" },
  { slug: "yuki-tsumugi-modern", category: "fashion", sub_type: "ibaraki_yuki_tsumugi", title_zh: "結城紬モダン(R1 衣 結城紬 1500 年派生・現代化バリエーション+ ストール+鞄+小物+アクセサリー+ 全国百貨店ヒット+ 海外輸出 結城紬館+JR 結城駅売店流通+ ¥3,500-25,000+ 観光客 SNS 拡散)", title_ja: "結城紬モダン", romaji: "Yūki Tsumugi Modern", summary_zh: "**結城紬モダンは R1 衣 1500 年派生現代化**(ストール+鞄+小物+アクセサリー)。全国百貨店+海外輸出、¥3,500-25,000、SNS 拡散。", content_md: "- 関係:**R1 衣 結城紬 1500 年派生**\n- 構成:**ストール + 鞄 + 小物 + アクセサリー**\n- 流通:**全国百貨店 + 海外輸出**\n- 価格:**¥3,500-25,000**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "結城市", lg_code: "08207", area_types: ["craft_workshop"], lat: 36.3056, lon: 139.8758, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yuki_tsumugi_modern"], source: "manual" },
  { slug: "kasama-yaki-1772", category: "fashion", sub_type: "ibaraki_kasama_yaki", title_zh: "笠間焼(笠間市・1772 江戸期発祥 253 年+ 関東最古陶器産地+ 国指定伝統工芸 1992+ 茶器+花器+食器+現代作家+ R1 育 笠間稲荷神社観光客向け+ 笠間焼祭り春・秋+ ¥3,500-50,000)", title_ja: "笠間焼", romaji: "Kasama Yaki", summary_zh: "**笠間焼は 1772 江戸期 253 年・関東最古陶器産地**(笠間・**国指定伝統工芸 1992**)。茶器+花器+食器+現代作家、R1 育 笠間稲荷神社観光、¥3,500-50,000。", content_md: "- 立地:**笠間市**\n- 起源:**1772 江戸期発祥 253 年**\n- 認定:**国指定伝統工芸 1992 + 関東最古陶器産地**\n- 構成:**茶器 + 花器 + 食器 + 現代作家**\n- 並列観光:**R1 育 笠間稲荷神社**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "笠間市", lg_code: "08216", area_types: ["craft_workshop", "industrial_heritage"], lat: 36.3858, lon: 140.2614, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kasama_yaki", "1772", "253_years", "1992_dento"], source: "manual" },
  { slug: "kasama-yaki-modern", category: "fashion", sub_type: "ibaraki_kasama_yaki", title_zh: "笠間焼モダン+デザイナーズ作品(R1 衣 笠間焼 1772 派生・現代作家 100+ 名+ コーヒーカップ+花瓶+デザイナーズ作品+ 道の駅+全国百貨店流通+ ¥1,500-25,000+ R1 楽 笠間焼祭り 観光客 SNS 拡散代表)", title_ja: "笠間焼モダン", romaji: "Kasama Yaki Modern", summary_zh: "**笠間焼モダンは R1 衣 1772 派生・現代作家 100+ 名**(コーヒーカップ+花瓶+デザイナーズ)。道の駅+百貨店、¥1,500-25,000、R1 楽 笠間焼祭り SNS 拡散。", content_md: "- 関係:**R1 衣 笠間焼 1772 派生**\n- 規模:**現代作家 100+ 名**\n- 構成:**コーヒーカップ + 花瓶 + デザイナーズ作品**\n- 価格:**¥1,500-25,000**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "笠間市", lg_code: "08216", area_types: ["craft_workshop"], lat: 36.3858, lon: 140.2614, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kasama_yaki_modern", "100_artists"], source: "manual" },
  { slug: "makabe-ishi-doro-1995", category: "fashion", sub_type: "ibaraki_kasama_yaki", title_zh: "真壁石燈籠(桜川市真壁・江戸期 1700 年代発祥 325 年+ 国指定伝統工芸 1995+ 真壁石(花崗岩)使用・庭園燈籠 + 寺社燈籠+ R1 楽 真壁ひなまつり連動+ 工房 5+ 軒+ 1 基 ¥150,000-1,500,000)", title_ja: "真壁石燈籠", romaji: "Makabe Ishi Dōrō", summary_zh: "**真壁石燈籠は江戸期 1700 年代 325 年・国指定伝統工芸 1995**(桜川真壁・**真壁石花崗岩+庭園燈籠+寺社燈籠**)。R1 楽 真壁ひなまつり連動、工房 5+ 軒、¥150,000-1,500,000。", content_md: "- 立地:**桜川市真壁**\n- 起源:**江戸期 1700 年代発祥 325 年**\n- 認定:**国指定伝統工芸 1995**\n- 構成:**真壁石(花崗岩)・庭園燈籠 + 寺社燈籠**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "桜川市", lg_code: "08231", area_types: ["craft_workshop", "industrial_heritage"], lat: 36.2972, lon: 140.0942, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["makabe_ishi_doro", "1700s", "325_years", "1995_dento"], source: "manual" },

  // 真壁伝統+伝統建築 (3)
  { slug: "makabe-historic-village", category: "fashion", sub_type: "ibaraki_folk_craft", title_zh: "真壁伝統的建造物群(桜川市真壁・1573 江戸期町人町形成・国選定重要伝統的建造物群保存地区 2010+ 在郷町建造物 100+ 棟+ R1 衣 真壁石燈籠発祥地+ R1 楽 真壁ひなまつり 2-3 月メイン会場+ 入場無料)", title_ja: "真壁伝統的建造物群", romaji: "Makabe Historic Village", summary_zh: "**真壁伝統的建造物群は江戸期 1573 町人町・重伝建 2010**(桜川真壁・**在郷町建造物 100+ 棟**)。R1 衣 石燈籠発祥+R1 楽 真壁ひなまつりメイン、無料。", content_md: "- 立地:**桜川市真壁**\n- 起源:**1573 江戸期町人町形成**\n- 認定:**国選定重要伝統的建造物群保存地区 2010**\n- 規模:**在郷町建造物 100+ 棟**\n- 並列:**R1 衣 真壁石燈籠発祥地 + R1 楽 真壁ひなまつり**\n- 入場:**無料**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "桜川市", lg_code: "08231", area_types: ["history_site_castle", "shopping_district"], lat: 36.2972, lon: 140.0942, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["makabe_jidenken", "1573", "2010_judenken", "100_buildings"], source: "manual" },
  { slug: "ibaraki-iwama-natto-craft", category: "fashion", sub_type: "ibaraki_folk_craft", title_zh: "岩間納豆 藁苞細工(笠間市岩間+水戸+ 1700 年代藁苞納豆発祥地・伝統的藁細工+ R1 食 水戸納豆全国 No.1 派生・伝統包装文化+ 道の駅+物産店流通+ ¥350-1,500+ 観光客向け文化体験土産)", title_ja: "岩間納豆藁苞細工", romaji: "Iwama Natto Wara Tsuto", summary_zh: "**岩間納豆藁苞細工は 1700 年代藁苞納豆発祥地・伝統藁細工**(笠間岩間+水戸・**R1 食 水戸納豆 No.1 派生**)。伝統包装文化、道の駅+物産店、¥350-1,500。", content_md: "- 立地:**笠間市岩間 + 水戸市**\n- 起源:**1700 年代藁苞納豆発祥地**\n- 関係:**R1 食 水戸納豆 No.1 派生・伝統包装文化**\n- 価格:**¥350-1,500**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "笠間市", lg_code: "08216", area_types: ["craft_workshop"], lat: 36.3858, lon: 140.2614, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["iwama_natto_tsuto", "1700s"], source: "manual" },
  { slug: "ibaraki-bamboo-takezaiku", category: "fashion", sub_type: "ibaraki_folk_craft", title_zh: "茨城竹細工(常陸大宮市+大子町+石岡・江戸期から伝承+ 山菜採集籠+花籠+食器+ 道の駅+物産店流通+ R1 食 常陸秋そば+大子りんご観光客向け+ ¥1,500-12,000+ 県北山地伝統工芸代表)", title_ja: "茨城竹細工", romaji: "Ibaraki Takezaiku", summary_zh: "**茨城竹細工は江戸期伝承**(常陸大宮+大子+石岡・**県北山地伝統工芸**)。山菜採集籠+花籠+食器、道の駅+物産店、R1 食 常陸秋そば+大子りんご観光、¥1,500-12,000。", content_md: "- 立地:**常陸大宮市 + 大子町 + 石岡市**\n- 起源:**江戸期から伝承**\n- 構成:**山菜採集籠 + 花籠 + 食器**\n- 並列観光:**R1 食 常陸秋そば + 大子りんご**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "常陸大宮市", lg_code: "08225", area_types: ["craft_workshop"], lat: 36.5403, lon: 140.4111, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ibaraki_takezaiku", "edo_origin"], source: "manual" },

  // R1 食派生グッズ (3)
  { slug: "mito-natto-character-goods", category: "fashion", sub_type: "ibaraki_folk_craft", title_zh: "水戸納豆キャラグッズ+ねば〜る君(R1 食 水戸納豆 No.1 派生・ねば〜る君(水戸納豆プロモーションキャラ 2011)+ ぬいぐるみ+T シャツ+文具+ JR 水戸駅+全国百貨店流通+ ¥350-2,500+ 海外観光客 SNS 拡散代表)", title_ja: "水戸納豆+ねば〜る君", romaji: "Mito Nattō / Nebaru-kun", summary_zh: "**水戸納豆キャラグッズ+ねば〜る君は R1 食 水戸納豆 No.1 派生**(2011 ねば〜る君プロモキャラ・**ぬいぐるみ+T シャツ+文具**)。水戸駅+百貨店、¥350-2,500、SNS 拡散。", content_md: "- 関係:**R1 食 水戸納豆 No.1 派生**\n- 縁:**ねば〜る君(水戸納豆プロモーションキャラ 2011)**\n- 構成:**ぬいぐるみ + T シャツ + 文具**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["shopping_district"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mito_natto_goods", "nebaru_kun_2011"], source: "manual" },
  { slug: "ibaraki-hassle-komon-goods", category: "fashion", sub_type: "ibaraki_folk_craft", title_zh: "ハッスル黄門+水戸黄門グッズ(水戸市・水戸黄門(徳川光圀 1628-1701)江戸期由来+ 水戸黄門マンガ・TV ドラマ 1969-2011 関連+ ぬいぐるみ+T シャツ+ R1 育 弘道館 R1 育 偕楽園 観光客向け+ ¥500-3,500)", title_ja: "ハッスル黄門+水戸黄門グッズ", romaji: "Hassle Komon Goods", summary_zh: "**ハッスル黄門+水戸黄門グッズは徳川光圀 1628-1701 江戸期由来**(水戸・**水戸黄門マンガ・TV ドラマ 1969-2011 関連**)。ぬいぐるみ+T シャツ+文具、¥500-3,500、R1 育 弘道館+偕楽園観光客向け。", content_md: "- 立地:**水戸市**\n- 縁:**徳川光圀 1628-1701 江戸期由来 + 水戸黄門マンガ・TV ドラマ 1969-2011**\n- 構成:**ぬいぐるみ + T シャツ + 文具**\n- 並列:**R1 育 弘道館 + R1 育 偕楽園**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["shopping_district"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["hassle_komon", "tokugawa_mitsukuni"], source: "manual" },
  { slug: "ooarai-girls-und-panzer-goods", category: "fashion", sub_type: "ibaraki_folk_craft", title_zh: "ガールズ&パンツァーグッズ(大洗町・2012 アニメ「ガールズ&パンツァー」聖地化・大洗町 全国アニメ聖地巡礼代表+ R1 食 鮟鱇鍋+R1 楽 アクアワールド観光客向け+ T シャツ+缶バッジ+痛車関連+ ¥350-3,500+ 海外アニメファン SNS 拡散)", title_ja: "ガールズ&パンツァーグッズ", romaji: "Girls und Panzer Goods", summary_zh: "**ガールズ&パンツァーグッズは大洗町 2012 アニメ聖地代表**(全国アニメ聖地巡礼)。R1 食 鮟鱇鍋+R1 楽 アクアワールド観光、T シャツ+缶バッジ、¥350-3,500、海外アニメファン SNS 拡散。", content_md: "- 立地:**大洗町**\n- 起源:**2012 アニメ「ガールズ&パンツァー」聖地化**\n- 認定:**全国アニメ聖地巡礼代表**\n- 並列:**R1 食 鮟鱇鍋 + R1 楽 アクアワールド大洗水族館**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "大洗町", lg_code: "08309", area_types: ["shopping_district"], lat: 36.3094, lon: 140.5750, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["girls_und_panzer", "2012", "anime_seichi"], source: "manual" },

  // 商店街+百貨店 (5)
  { slug: "mito-station-ekie", category: "fashion", sub_type: "ibaraki_dept_store", title_zh: "JR 水戸駅エクセル+京成百貨店(水戸市・JR 水戸駅構内+南口直結・1990-2000 開業+ R1 食 水戸納豆+R1 食 鮟鱇+メロン+水戸の梅銘菓 集約販売+ 観光土産集中拠点+ 京成百貨店全 9 階・茨城代表百貨店)", title_ja: "JR 水戸駅エクセル+京成百貨店", romaji: "JR Mito Excel / Keisei", summary_zh: "**JR 水戸駅エクセル+京成百貨店は 1990-2000 開業**(水戸・**R1 食 水戸納豆+鮟鱇+メロン+水戸の梅集約販売**)。京成百貨店全 9 階・茨城代表百貨店、観光土産集中拠点。", content_md: "- 立地:**水戸市**(JR 水戸駅構内 + 南口直結)\n- 起源:**1990-2000 開業**\n- 規模:**JR エクセル + 京成百貨店全 9 階・茨城代表百貨店**\n- 並列:**R1 食 水戸納豆 + 鮟鱇 + メロン + 水戸の梅銘菓**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["shopping_district", "transit_hub"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mito_keisei", "1990_2000", "9_floors"], source: "manual" },
  { slug: "tsukuba-creo-iias-mall", category: "fashion", sub_type: "ibaraki_dept_store", title_zh: "つくば iias+つくばクレオスクエア(つくば市・1985 つくば博関連商業施設+ 1990-2010 改修・つくばエクスプレス 2005 連動拡張+ 全 200+ 店舗+ R1 育 つくばエキスポセンター近く・JAXA 関連グッズ+ 学園都市 R1 行 連動)", title_ja: "つくば iias+クレオ", romaji: "Tsukuba iias / Creo", summary_zh: "**つくば iias+クレオスクエアは 1985 つくば博関連**(つくば・**つくばエクスプレス 2005 連動拡張+全 200+ 店舗**)。R1 育 つくばエキスポセンター近く・JAXA 関連グッズ、学園都市連動。", content_md: "- 立地:**つくば市**\n- 起源:**1985 つくば博関連 + 1990-2010 改修**\n- 関連:**つくばエクスプレス 2005 連動拡張**\n- 規模:**全 200+ 店舗**\n- 並列観光:**R1 育 つくばエキスポセンター + JAXA**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "つくば市", lg_code: "08220", area_types: ["shopping_district"], lat: 36.0833, lon: 140.0764, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsukuba_iias_creo", "1985", "200_stores"], source: "manual" },
  { slug: "kasama-yaki-pottery-village", category: "fashion", sub_type: "ibaraki_dept_store", title_zh: "笠間焼陶芸の里+陶炎祭(笠間市・R1 衣 笠間焼 1772 派生・全 30+ 軒陶器ギャラリー集約+ R1 楽 笠間焼祭り春・秋連動+ R1 育 笠間稲荷神社 隣接+ JR 水戸線 笠間駅徒歩 5 分+ ¥1,500-25,000)", title_ja: "笠間焼陶芸の里", romaji: "Kasama Yaki Pottery Village", summary_zh: "**笠間焼陶芸の里+陶炎祭は R1 衣 1772 派生・全 30+ 軒陶器ギャラリー集約**(R1 楽 春秋祭り連動+R1 育 笠間稲荷隣接)。JR 笠間駅徒歩 5 分、¥1,500-25,000。", content_md: "- 立地:**笠間市**\n- 関係:**R1 衣 笠間焼 1772 派生**\n- 規模:**全 30+ 軒陶器ギャラリー集約**\n- 並列:**R1 楽 笠間焼祭り + R1 育 笠間稲荷神社**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "笠間市", lg_code: "08216", area_types: ["shopping_district", "craft_workshop"], lat: 36.3858, lon: 140.2614, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kasama_pottery_village", "30_galleries"], source: "manual" },
  { slug: "ibaraki-aeon-mall-mito", category: "fashion", sub_type: "ibaraki_dept_store", title_zh: "イオンモール水戸+水戸内原(水戸市内原・2005 開業+ 全 200+ 店舗・茨城最大級+ R1 食 水戸納豆+メロン+笠間焼観光土産販売 集約+ JR 常磐線 内原駅徒歩 5 分+ 観光客向け+ ファミリー代表)", title_ja: "イオンモール水戸内原", romaji: "Aeon Mall Mito Uchihara", summary_zh: "**イオンモール水戸内原は 2005 開業・茨城最大級**(水戸内原・**全 200+ 店舗・JR 常磐線内原駅徒歩 5 分**)。R1 食 水戸納豆+メロン+笠間焼観光土産集約、ファミリー代表。", content_md: "- 立地:**水戸市内原**(JR 常磐線 内原駅徒歩 5 分)\n- 起源:**2005 開業 20 年**\n- 規模:**全 200+ 店舗・茨城最大級**\n- 並列:**R1 食 水戸納豆 + メロン + 笠間焼観光土産集約**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["shopping_district"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aeon_mito_uchihara", "2005", "200_stores"], source: "manual" },
  { slug: "ooarai-marine-tower-shop", category: "fashion", sub_type: "ibaraki_dept_store", title_zh: "大洗マリンタワー+海岸通り土産店(大洗町・1990 開業+ R1 食 鮟鱇+R1 楽 アクアワールド観光客向け・タワー高さ 60m 太平洋眺望+ 全 30+ 軒土産店集約・R1 衣 ガールズ&パンツァーグッズ+ 入場 ¥330)", title_ja: "大洗マリンタワー+海岸通り", romaji: "Ōarai Marine Tower", summary_zh: "**大洗マリンタワー+海岸通り土産店は 1990 開業**(大洗・**タワー 60m 太平洋眺望+全 30+ 軒土産店**)。R1 衣 ガルパングッズ集約、R1 食 鮟鱇+R1 楽 アクアワールド観光客、¥330。", content_md: "- 立地:**大洗町**\n- 起源:**1990 開業**\n- 規模:**タワー 60m + 全 30+ 軒土産店**\n- 並列:**R1 食 鮟鱇 + R1 楽 アクアワールド + R1 衣 ガールズ&パンツァーグッズ**\n- 入場:**¥330**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "大洗町", lg_code: "08309", area_types: ["shopping_district", "scenic_spot"], lat: 36.3094, lon: 140.5750, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ooarai_marine_tower", "1990", "60m"], source: "manual" },

  // ご当地キャラ (2)
  { slug: "ibaraki-mascot-kibarakichan", category: "fashion", sub_type: "ibaraki_folk_craft", title_zh: "ハッスル黄門+いばラッキー+ねば〜る君 茨城ご当地キャラ集約(全域・茨城県観光物産協会マスコット+ R1 育 水戸黄門+R1 食 水戸納豆派生+ ぬいぐるみ+T シャツ+文具+ JR 水戸駅+全国百貨店+ ¥500-3,500)", title_ja: "茨城ご当地キャラ", romaji: "Ibaraki Mascot", summary_zh: "**茨城ご当地キャラ集約は ハッスル黄門+いばラッキー+ねば〜る君**(R1 育 水戸黄門+R1 食 水戸納豆派生)。ぬいぐるみ+T シャツ+文具、水戸駅+百貨店、¥500-3,500。", content_md: "- 全域:**茨城県全域**\n- 構成:**ハッスル黄門 + いばラッキー + ねば〜る君**\n- 関係:**R1 育 水戸黄門 + R1 食 水戸納豆派生**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["shopping_district"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ibaraki_mascot"], source: "manual" },
  { slug: "ibaraki-fukuroda-falls-goods", category: "fashion", sub_type: "ibaraki_folk_craft", title_zh: "袋田の滝グッズ(久慈郡大子町・R1 育 袋田の滝 日本三名瀑派生・写真集+ポスター+T シャツ+缶バッジ+ R1 食 大子りんご+常陸秋そば 観光客向け+ 道の駅+物産店流通+ ¥500-3,500+ R1 楽 袋田の滝氷瀑観光土産代表)", title_ja: "袋田の滝グッズ", romaji: "Fukuroda Falls Goods", summary_zh: "**袋田の滝グッズは R1 育 日本三名瀑派生**(大子・**写真集+ポスター+T シャツ+缶バッジ**)。R1 食 大子りんご+常陸秋そば観光、道の駅+物産店、¥500-3,500、R1 楽 氷瀑土産代表。", content_md: "- 立地:**久慈郡大子町**(R1 育 袋田の滝)\n- 関係:**R1 育 袋田の滝 日本三名瀑派生**\n- 構成:**写真集 + ポスター + T シャツ + 缶バッジ**", region: "kanto", prefecture_ja: "茨城県", gun_ja: "久慈郡", municipality_ja: "大子町", lg_code: "08364", area_types: ["shopping_district"], lat: 36.7681, lon: 140.3556, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["fukuroda_falls_goods"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[ibaraki-fashion-r1] 尚無條目"); return; }
  console.log(`[ibaraki-fashion-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[ibaraki-fashion-r1] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[ibaraki-fashion-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[ibaraki-fashion-r1] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
