// Seed 熊本県 行 R1(20 筆 / Sprint 46.6)
//
// 新幹線 + 駅 3 / JR 在来 3 / 私鉄市電 3 / 空港 + バス + フェリー 6 / レンタル他 5 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: "transport";
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "kyushu";
  prefecture_ja: "熊本県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // 新幹線 + 駅 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyushu-shinkansen-2011-full",
    category: "transport",
    sub_type: "kumamoto_kyushu_shinkansen",
    title_zh: "九州新幹線(2004 部分・2011 全通+ 博多-鹿児島中央 257km+ 熊本駅・新八代駅 2 駅停車)",
    title_ja: "九州新幹線",
    romaji: "Kyushu Shinkansen",
    summary_zh: "**九州新幹線は熊本県縦断主動脈**(2004 部分開通・**2011 全通・博多-鹿児島中央 257km**)。**熊本駅(2011 開業)+ 新八代駅 2 駅停車**、関西-福岡-熊本-鹿児島の主要観光ルート、R1 行 JR 熊本駅(2018 安藤忠雄リニューアル)が熊本側 hub。",
    content_md: "- 部分開通:**2004 年(新八代-鹿児島中央)**\n- 全通:**2011 年 3 月 12 日(博多-鹿児島中央)**\n- 距離:**257km**(博多-鹿児島中央)\n- 熊本県内停車駅:**熊本駅 + 新八代駅**\n- 並列:**R1 行 JR 熊本駅 2018 安藤忠雄リニューアル**\n- 列車:みずほ + さくら + つばめ\n- 並列:R1 楽 観光列車 A 列車 + あそぼーい(JR 在来線)\n- 関西方面:**新大阪 → 熊本 約 3 時間**(山陽-九州新幹線直通)",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7886,
    lon: 130.6928,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kyushu_shinkansen", "2011_full", "hakata_kagoshima_257km", "kumamoto_shin_yatsushiro"],
    source: "manual",
  },
  {
    slug: "kumamoto-eki-2018-andou-tadao",
    category: "transport",
    sub_type: "kumamoto_kyushu_shinkansen",
    title_zh: "JR 熊本駅(熊本市・1891 開業・134 年+ 2018 リニューアル安藤忠雄設計+ 九州新幹線 hub)",
    title_ja: "JR 熊本駅",
    romaji: "JR Kumamoto Eki",
    summary_zh: "**JR 熊本駅は九州新幹線熊本側 hub**(熊本市・**1891 開業・134 年・2018 リニューアル**)。**安藤忠雄設計の現代建築**(打ちっぱなしコンクリート + 木組み天井)、九州新幹線 + JR 鹿児島本線 + 豊肥本線 + 三角線の総合 hub、R1 衣 サクラマチ 2019 + 桜町バスターミナルアクセスは市電 1 駅。",
    content_md: "- 開業:**1891 年・134 年**\n- 駅舎リニューアル:**2018 年・7 年**\n- 設計:**安藤忠雄**(打ちっぱなしコンクリート + 木組み天井)\n- 路線:**九州新幹線 + JR 鹿児島本線 + 豊肥本線 + 三角線**\n- 並列:R1 衣 サクラマチ熊本 2019 + 桜町バスターミナル(市電 1 駅)\n- 1 日乗降:約 4.5 万人\n- 熊本駅前:**熊本市電熊本駅前停留場**",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7886,
    lon: 130.6928,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kumamoto_eki", "1891", "134_years", "2018_renewal", "ando_tadao_design"],
    source: "manual",
  },
  {
    slug: "shin-yatsushiro-eki",
    category: "transport",
    sub_type: "kumamoto_kyushu_shinkansen",
    title_zh: "JR 新八代駅(八代市・2004 開業・21 年+ 九州新幹線開業時 hub+ 八代妙見祭(国指定無形民俗 2011)アクセス)",
    title_ja: "JR 新八代駅",
    romaji: "Shin-Yatsushiro Eki",
    summary_zh: "**JR 新八代駅は九州新幹線初期 hub**(八代市・**2004 開業・21 年**)。**九州新幹線部分開通(2004)時の終着駅**、現在は熊本駅 + 鹿児島中央駅の中間駅、八代妙見祭(R6 開卷 国指定無形民俗 2011)アクセス。",
    content_md: "- 開業:**2004 年・21 年**\n- 立地:八代市(R6 開卷 八代妙見祭 国指定無形民俗 2011 アクセス)\n- 系譜:**九州新幹線部分開通 2004 時の終着駅**\n- 現在:**熊本駅 + 鹿児島中央駅の中間駅**(全通 2011 後)\n- 並列:R6 開卷 八代妙見祭(国指定無形民俗 2011)\n- 1 日乗降:約 5,000 人",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "八代市",
    lg_code: "43202",
    area_types: ["transit_hub"],
    lat: 32.5022,
    lon: 130.6028,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shin_yatsushiro_eki", "2004", "21_years", "shinkansen_intermediate"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // JR 在来線 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "jr-hoyoji-line-1928",
    category: "transport",
    sub_type: "kumamoto_jr_local",
    title_zh: "JR 豊肥本線(熊本-大分・148km・1928 全通+ 阿蘇横断+ R1 楽 あそぼーい!観光列車運行)",
    title_ja: "JR 豊肥本線",
    romaji: "JR Hoyoji Line",
    summary_zh: "**JR 豊肥本線は阿蘇横断主動脈**(熊本-大分・**148km・1928 全通**)。**阿蘇カルデラ縦断 + 大分連結**、R1 楽 あそぼーい!観光列車運行、R1 楽 阿蘇山 + 大観峰 + R1 育 阿蘇神社アクセス。**2016 熊本地震で部分運休 → 2020 全線復旧**。",
    content_md: "- 全通:**1928 年・97 年**\n- 区間:**熊本-大分・148km**\n- 性格:**阿蘇横断本線**(阿蘇カルデラ縦断)\n- 並列観光列車:**R1 楽 あそぼーい!2011**\n- 並列観光地:R1 楽 阿蘇山 + 大観峰 + R1 育 阿蘇神社\n- 災害:2016 熊本地震 → **2020 全線復旧**\n- 主要駅:熊本 + 武蔵塚 + 三里木 + 肥後大津 + 立野 + 阿蘇 + 宮地",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7886,
    lon: 130.6928,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jr_hoyoji_line", "1928", "97_years", "148km", "aso_crossing"],
    source: "manual",
  },
  {
    slug: "jr-misumi-line-1899",
    category: "transport",
    sub_type: "kumamoto_jr_local",
    title_zh: "JR 三角線(熊本-三角・25km・1899 開通・126 年+ 天草五橋アクセス必須+ R1 楽 A 列車で行こう運行)",
    title_ja: "JR 三角線",
    romaji: "JR Misumi Line",
    summary_zh: "**JR 三角線は天草アクセス必須路線**(熊本-三角・**25km・1899 開通・126 年**)。**R1 楽 A 列車で行こう観光列車運行**、R1 楽 天草五橋 1966 + R1 育 天草キリシタン世界遺産 + R1 食 天草大王アクセス前段、現在は天草五橋経由のドライブ + 路線結合観光。",
    content_md: "- 開通:**1899 年・126 年**\n- 区間:**熊本-三角・25km**\n- 性格:**天草アクセス必須路線**\n- 並列観光列車:**R1 楽 A 列車で行こう 2011**\n- 並列観光地:R1 楽 天草五橋 + R1 育 天草キリシタン + R1 食 天草大王\n- 主要駅:熊本 + 宇土 + 三角",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7886,
    lon: 130.6928,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jr_misumi_line", "1899", "126_years", "25km", "amakusa_access"],
    source: "manual",
  },
  {
    slug: "jr-hisatsu-line-2020-suspended",
    category: "transport",
    sub_type: "kumamoto_jr_local",
    title_zh: "JR 肥薩線(熊本-八代-人吉-鹿児島・1909 全通+ 2020 7 月豪雨で大被災・運休継続中(2026 現在))",
    title_ja: "JR 肥薩線",
    romaji: "JR Hisatsu Line",
    summary_zh: "**JR 肥薩線は球磨人吉アクセス本線**(熊本-八代-人吉-鹿児島・**1909 全通・116 年**)。**2020 7 月豪雨で球磨川氾濫 → 八代-吉松間運休継続中(2026 現在)・運転再開時期未定**、R1 楽 かわせみ やませみ観光列車も運休、R6 育 人吉相良家 700 年文化アクセス困難。",
    content_md: "- 全通:**1909 年・116 年**\n- 区間:熊本-八代-人吉-吉松-鹿児島中央(全長 124km の熊本県内)\n- 災害:**2020 年 7 月豪雨で球磨川氾濫**\n- 運休:**八代-吉松間運休継続中(2026 現在)・再開時期未定**\n- 影響:R1 楽 かわせみ やませみ観光列車運休 + R6 育 人吉相良家文化アクセス困難\n- 代替:**くま川鉄道(2025 全線復旧)+ 高速バス**\n- アクセス advisory",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "人吉市",
    lg_code: "43203",
    area_types: ["transit_hub"],
    lat: 32.2117,
    lon: 130.7625,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jr_hisatsu_line", "1909", "116_years", "2020_flood_suspended", "kawasemi_yamasemi_paused"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 私鉄・市電 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kumamoto-ichi-densha-1924",
    category: "transport",
    sub_type: "kumamoto_local_railway",
    title_zh: "熊本市電(熊本市・1924 開業・101 年+ 全国最古級路面電車+ R6 育 熊本城前 + 上通商店街アクセス)",
    title_ja: "熊本市電",
    romaji: "Kumamoto Ichi Densha",
    summary_zh: "**熊本市電は全国最古級路面電車**(熊本市・**1924 開業・101 年**)。**広島電鉄 1912 + 京阪石山坂本線 1914 と並ぶ全国最古級**、R6 育 熊本城前 + R1 衣 上通 + 下通商店街 + 桜町バスターミナル + R1 育 水前寺成趣園アクセスの市内主動脈。",
    content_md: "- 開業:**1924 年(大正 13)・101 年**\n- 立地:熊本市内全域\n- 全国順位:**全国最古級路面電車**(広電 1912 + 京阪石山坂本 1914 + 熊本市電 1924)\n- 並列観光地:R6 育 熊本城 + R1 衣 上通 + 下通 + 桜町 + R1 育 水前寺成趣園\n- 路線:**A 系統 + B 系統(2 系統)**\n- 運賃:1 回 ¥180\n- 1 日乗車券:大人 ¥500",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.8033,
    lon: 130.7079,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kumamoto_ichi_densha", "1924", "101_years", "oldest_class_japan_tram"],
    source: "manual",
  },
  {
    slug: "minami-aso-tetsudou-1986",
    category: "transport",
    sub_type: "kumamoto_local_railway",
    title_zh: "南阿蘇鉄道(立野-高森・17.7km・1986 設立+ 旧 高森線継承+ 2016 地震 → 2023 全線復旧+ R1 楽 高森湧水アクセス)",
    title_ja: "南阿蘇鉄道",
    romaji: "Minami Aso Tetsudou",
    summary_zh: "**南阿蘇鉄道は阿蘇南部第三セクター**(立野-高森・**17.7km・1986 設立・39 年**)。**旧 国鉄高森線継承**、R1 楽 高森湧水隧道 + R1 育 阿蘇神社・五岳アクセス、観光トロッコ列車運行(夏期)。**2016 熊本地震で立野付近被災 → 2023 全線復旧**。",
    content_md: "- 設立:**1986 年・39 年**(第三セクター)\n- 区間:**立野-高森・17.7km**\n- 由来:**旧 国鉄高森線継承**\n- 並列観光:R1 楽 高森湧水隧道 + R1 育 阿蘇神社・五岳\n- 災害:**2016 熊本地震で立野付近被災**\n- 復旧:**2023 全線復旧**\n- 観光列車:トロッコ列車(夏期)\n- アクセス:JR 豊肥本線立野駅 → 乗換",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: "阿蘇郡",
    municipality_ja: "高森町",
    lg_code: "43428",
    area_types: ["transit_hub"],
    lat: 32.8222,
    lon: 131.1247,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["minami_aso_tetsudou", "1986", "39_years", "17.7km", "2023_full_recovery"],
    source: "manual",
  },
  {
    slug: "kuma-kawa-tetsudou-1989",
    category: "transport",
    sub_type: "kumamoto_local_railway",
    title_zh: "くま川鉄道(人吉温泉-湯前・24.8km・1989 設立+ 旧 JR 湯前線継承+ 2020 7 月豪雨被災 → 2025 全線復旧)",
    title_ja: "くま川鉄道",
    romaji: "Kuma Kawa Tetsudou",
    summary_zh: "**くま川鉄道は人吉球磨第三セクター**(人吉温泉-湯前・**24.8km・1989 設立・36 年**)。**旧 JR 湯前線継承**、R6 育 人吉相良家 700 年 + R1 食 球磨焼酎 4 大老舗 + R1 楽 球磨川下りアクセス。**2020 7 月豪雨被災 → 2025 全線復旧**。",
    content_md: "- 設立:**1989 年・36 年**(第三セクター)\n- 区間:**人吉温泉-湯前・24.8km**\n- 由来:**旧 JR 湯前線継承**\n- 並列観光:R6 育 人吉相良家 + R1 食 球磨焼酎 + R1 楽 球磨川下り\n- 災害:**2020 7 月豪雨で大被災**\n- 復旧:**2025 全線復旧**(2024 部分復旧 → 2025 完全)\n- 主要駅:人吉温泉 + あさぎり + 多良木 + 湯前\n- 並列:R1 行 JR 肥薩線(2020 水害で運休継続)",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "人吉市",
    lg_code: "43203",
    area_types: ["transit_hub"],
    lat: 32.2117,
    lon: 130.7625,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kuma_kawa_tetsudou", "1989", "36_years", "24.8km", "2025_full_recovery"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 空港 + バス + フェリー (6)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "aso-kumamoto-airport-1971",
    category: "transport",
    sub_type: "kumamoto_airport_bus_ferry",
    title_zh: "阿蘇くまもと空港(益城町・1971 開港・54 年+ 国内線 + 国際線+ R1 育 阿蘇神社徒歩圏外+ 2023 ターミナル新ビル開業)",
    title_ja: "阿蘇くまもと空港",
    romaji: "Aso Kumamoto Airport",
    summary_zh: "**阿蘇くまもと空港は熊本県主空港**(益城町・**1971 開港・54 年**)。**2023 新ターミナルビル開業**、東京羽田 + 大阪伊丹 + 名古屋 + 那覇 + 国際線(韓国・台湾等)、R1 行 熊本-阿蘇空港リムジンバス hub、2016 熊本地震被災 → 2023 完全復旧。",
    content_md: "- 開港:**1971 年・54 年**\n- 立地:**益城町**(熊本市東隣・上益城郡)\n- 2023:**新ターミナルビル開業**(復興プロジェクト)\n- 国内線:**東京羽田 + 大阪伊丹 + 名古屋 + 那覇 等**\n- 国際線:韓国 + 台湾 + 香港 等\n- 災害:2016 熊本地震 → 2023 復興\n- アクセス:**R1 行 熊本-阿蘇空港リムジンバス**(約 50 分)",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: "上益城郡",
    municipality_ja: "益城町",
    lg_code: "43443",
    area_types: ["transit_hub"],
    lat: 32.8372,
    lon: 130.8517,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.kumamoto-airport.co.jp/" },
    tags: ["aso_kumamoto_airport", "1971", "54_years", "2023_new_terminal", "international"],
    source: "manual",
  },
  {
    slug: "kumamoto-sakuramachi-bus-terminal-2019",
    category: "transport",
    sub_type: "kumamoto_airport_bus_ferry",
    title_zh: "熊本桜町バスターミナル(熊本市・2019 開業・6 年+ R1 衣 サクラマチ熊本 1F+ 熊本最大バスハブ+ 100+ 系統)",
    title_ja: "熊本桜町バスターミナル",
    romaji: "Kumamoto Sakuramachi Bus Terminal",
    summary_zh: "**熊本桜町バスターミナルは熊本最大バスハブ**(熊本市・**2019 開業・6 年・R1 衣 サクラマチ熊本 1F**)。**100+ 系統が集約・市内バス + 県内バス + 高速バス + 空港リムジン**、R1 行 福岡 + 大阪 + 鹿児島高速バスの起点、サクラマチ複合 SC + ホテルブラッサム熊本との一体施設。",
    content_md: "- 開業:**2019 年・6 年**\n- 立地:**熊本市中央区桜町**(R1 衣 サクラマチ熊本 1F)\n- 規模:**100+ バス系統集約**\n- 系統:市内バス + 県内バス + 高速バス + 空港リムジン\n- 並列:**R1 衣 サクラマチ熊本 + ホテルブラッサム熊本**\n- 並列:**R1 行 熊本-福岡 + 大阪高速バス hub**\n- アクセス:熊本市電花畑町 徒歩 1 分",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7964,
    lon: 130.7042,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.sakuramachi-kumamoto.jp/bus/" },
    tags: ["sakuramachi_bus_terminal", "2019", "6_years", "100_routes", "kumamoto_largest_bus_hub"],
    source: "manual",
  },
  {
    slug: "kumamoto-fukuoka-highway-bus",
    category: "transport",
    sub_type: "kumamoto_airport_bus_ferry",
    title_zh: "熊本-福岡高速バス(ひのくに号・約 2 時間+ 1 時間 4-6 便+ 西鉄バス + 産交バス共同運行)",
    title_ja: "熊本-福岡高速バス",
    romaji: "Kumamoto Fukuoka Highway Bus",
    summary_zh: "**熊本-福岡高速バス「ひのくに号」は九州主要連結バス**(**約 2 時間・1 時間 4-6 便**)。**西鉄バス + 九州産交バス共同運行**、九州新幹線(福岡-熊本約 35 分)に対する価格優位代替路、R1 行 桜町バスターミナル + JR 熊本駅前出発。",
    content_md: "- 名称:**ひのくに号**\n- 区間:**熊本桜町バスターミナル/JR 熊本駅 ↔ 博多バスターミナル/天神バスセンター**\n- 所要:**約 2 時間**\n- 便数:**1 時間 4-6 便**\n- 運行:**西鉄バス + 九州産交バス共同**\n- 価格:**¥2,500 前後**(片道)\n- 並列:R1 行 九州新幹線(福岡-熊本約 35 分・¥5,000+)\n- 役割:**価格優位の代替路**",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7964,
    lon: 130.7042,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hi_no_kuni_go", "kumamoto_fukuoka", "2h", "nishitetsu_sanko"],
    source: "manual",
  },
  {
    slug: "kumamoto-osaka-night-bus",
    category: "transport",
    sub_type: "kumamoto_airport_bus_ferry",
    title_zh: "熊本-大阪夜行バス(あそ号 + ぎんなん号・約 12 時間+ 関西連結代替路+ JR バス + 産交バス共同運行)",
    title_ja: "熊本-大阪夜行バス",
    romaji: "Kumamoto Osaka Night Bus",
    summary_zh: "**熊本-大阪夜行バスは関西連結代替路**(**あそ号 + ぎんなん号・約 12 時間**)。**JR バス + 九州産交バス共同運行**、九州新幹線(大阪-熊本約 3 時間・¥17,000+)に対する価格優位代替路、夜出発 → 翌朝到着で時間節約。",
    content_md: "- 名称:**あそ号**(JR バス)+ **ぎんなん号**(九州産交バス)\n- 区間:**熊本桜町バスターミナル ↔ 大阪駅 + 京都駅**\n- 所要:**約 12 時間**(夜行)\n- 便数:1 日 1-2 便\n- 価格:**¥10,000-13,000**(片道)\n- 並列:R1 行 九州新幹線(大阪-熊本 3h・¥17,000+)\n- 役割:**価格優位の関西連結代替路**\n- 並列:R1 行 ひのくに号(福岡)= 熊本主要高速バス 2 大",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7964,
    lon: 130.7042,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["aso_go_ginnan_go", "kumamoto_osaka", "12h_night", "kansai_alternative"],
    source: "manual",
  },
  {
    slug: "kumamoto-shimabara-ferry-30min",
    category: "transport",
    sub_type: "kumamoto_airport_bus_ferry",
    title_zh: "熊本港-島原港フェリー(熊本フェリー・30 分・1 時間 1-2 便+ 長崎島原半島連結+ 雲仙アクセス)",
    title_ja: "熊本-島原フェリー",
    romaji: "Kumamoto Shimabara Ferry",
    summary_zh: "**熊本港-島原港フェリーは九州西部短距離連結**(**約 30 分・1 時間 1-2 便**)。**熊本フェリー運航+ 長崎島原半島 + 雲仙アクセス**、R1 行 九州新幹線(熊本-諫早 → バス)に対する直結路、車載可能で天草 + 雲仙ドライブ周遊観光に便利。",
    content_md: "- 区間:**熊本港 ↔ 島原港**\n- 所要:**約 30 分**\n- 便数:**1 時間 1-2 便**\n- 運航:**熊本フェリー**\n- 連結:**長崎島原半島 + 雲仙温泉 + 普賢岳アクセス**\n- 並列:R1 行 九州新幹線(熊本 → 諫早 → バス)\n- 価格:**大人 ¥1,000 + 車両 ¥3,500-5,500**\n- 用途:車載可能で周遊ドライブに便利\n- アクセス:JR 鹿児島本線熊本駅 → バス 50 分(熊本港)",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub", "coastal"],
    lat: 32.7000,
    lon: 130.5667,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kumamoto_shimabara_ferry", "30min", "kumamoto_ferry", "shimabara_unzen_link"],
    source: "manual",
  },
  {
    slug: "kumamoto-airport-limousine",
    category: "transport",
    sub_type: "kumamoto_airport_bus_ferry",
    title_zh: "熊本駅・桜町-阿蘇くまもと空港リムジンバス(約 50 分+ R1 行 サクラマチバスターミナル + JR 熊本駅発着)",
    title_ja: "熊本-阿蘇空港リムジン",
    romaji: "Kumamoto Airport Limousine",
    summary_zh: "**熊本-阿蘇空港リムジンバスは空港主要交通**(**約 50 分・1 時間 2-3 便**)。**R1 行 サクラマチバスターミナル + JR 熊本駅 → 阿蘇くまもと空港 1971 直行**、R1 行 桜町バスターミナル 2019 出発、空港便連動運行。",
    content_md: "- 区間:**JR 熊本駅 + 桜町バスターミナル ↔ 阿蘇くまもと空港**\n- 所要:**約 50 分**\n- 便数:**1 時間 2-3 便**(空港便連動)\n- 価格:**¥1,000**(片道・大人)\n- 運行:産交バス\n- 並列:**R1 行 桜町バスターミナル 2019 + 阿蘇くまもと空港 1971**\n- アクセス:JR 熊本駅 + 桜町出発",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7964,
    lon: 130.7042,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kumamoto_airport_limousine", "50min", "1000yen", "1_hour_2_3_buses"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // レンタル他 (5)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kumamoto-rental-car-area",
    category: "transport",
    sub_type: "kumamoto_airport_bus_ferry",
    title_zh: "熊本県レンタカー(主要 8 社+ JR 熊本駅 + 阿蘇空港 + サクラマチ集積+ R1 楽 阿蘇 + 天草 + 球磨観光は車推奨)",
    title_ja: "熊本県レンタカー",
    romaji: "Kumamoto Rental Car",
    summary_zh: "**熊本県レンタカーは観光車推奨**(**主要 8 社・JR 熊本駅 + 阿蘇くまもと空港 + サクラマチ集積**)。**R1 楽 阿蘇 + 天草 + 球磨観光は車推奨**、R1 楽 天草五橋 1966 + R1 楽 阿蘇カルデラドライブ + R1 行 熊本-島原フェリー利用時に必須。",
    content_md: "- 範囲:熊本県全域\n- 主要拠点:**JR 熊本駅 + 阿蘇くまもと空港 + サクラマチ**\n- 主要 8 社:トヨタ + ニッポン + 日産 + オリックス + タイムズ + バジェット + 駅レンタカー 等\n- 推奨範囲:**R1 楽 阿蘇 + 天草 + 球磨観光は車推奨**\n- 並列観光:R1 楽 天草五橋 + 阿蘇カルデラ + R1 行 熊本-島原フェリー\n- 価格:1 日 ¥6,000-15,000",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7886,
    lon: 130.6928,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["kumamoto_rental_car", "8_companies", "aso_amakusa_recommended"],
    source: "manual",
  },
  {
    slug: "kumamoto-tour-taxi",
    category: "transport",
    sub_type: "kumamoto_airport_bus_ferry",
    title_zh: "熊本観光タクシー(熊本市・1 日 / 半日チャーター+ ガイド付+ R6 育 熊本城 + 水前寺 + 阿蘇周遊向け)",
    title_ja: "熊本観光タクシー",
    romaji: "Kumamoto Tour Taxi",
    summary_zh: "**熊本観光タクシーは効率最良の観光手段**(熊本市・**1 日 / 半日チャーター + ガイド付**)。**JR 熊本駅 + 主要ホテル発着+ 観光ルート提案**、R6 育 熊本城 + R1 育 水前寺成趣園 + R1 楽 阿蘇 を効率的に巡回、年配 + 家族客向け。",
    content_md: "- 形態:1 日 / 半日チャーター\n- ガイド:**運転手による観光ガイド付**\n- 主要事業者:熊本県タクシー協会加盟 各社\n- 並列:R1 行 桜町バスターミナル + R1 行 城下町ツアーバス\n- 価格:1 日 ¥30,000-50,000(8 時間)・半日 ¥18,000-25,000(4 時間)\n- 客層:年配 + 家族客 + 効率重視\n- アクセス:JR 熊本駅 + 主要ホテル発着",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7886,
    lon: 130.6928,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 5,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["kumamoto_tour_taxi", "1day_halfday", "guide_included", "efficient"],
    source: "manual",
  },
  {
    slug: "kumamoto-bus-1day-pass",
    category: "transport",
    sub_type: "kumamoto_local_railway",
    title_zh: "熊本市内バス + 市電 1 日乗車券(¥800・観光客必須+ R1 行 熊本市電 + 産交バス + 桜町バスターミナル発着)",
    title_ja: "熊本市内 1 日乗車券",
    romaji: "Kumamoto 1Day Pass",
    summary_zh: "**熊本市内 1 日乗車券は観光客必須交通券**(**¥800・市電 + バス全社**)。**R1 行 熊本市電 1924 + 産交バス + 桜町バスターミナル発着バス全社**、R6 育 熊本城 + R1 衣 上通 + 下通 + R1 育 水前寺成趣園アクセス全対応。",
    content_md: "- 価格:**¥800**(大人)\n- 範囲:**熊本市内市電 + 産交バス全社**\n- 並列:R1 行 熊本市電 1924 + 桜町バスターミナル 2019\n- 並列観光:R6 育 熊本城 + R1 衣 上通 + 下通 + R1 育 水前寺成趣園\n- 購入:**桜町バスターミナル + JR 熊本駅 + 主要バス停**\n- 役割:**観光客最頻使用乗車券**",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7964,
    lon: 130.7042,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kumamoto_1day_pass", "800yen", "tram_bus_all", "tourist_essential"],
    source: "manual",
  },
  {
    slug: "kumamoto-2016-quake-transport-impact",
    category: "transport",
    sub_type: "kumamoto_jr_local",
    title_zh: "熊本地震 2016 交通影響総覧(2016/4/14+4/16 M7.0+ R1 行 JR 豊肥本線 + 南阿蘇鉄道 + 熊本空港被災・全復興済)",
    title_ja: "熊本地震 2016 交通影響",
    romaji: "Kumamoto 2016 Quake Transport Impact",
    summary_zh: "**熊本地震 2016 交通影響は熊本県中部全域に深刻**(2016/4/14 + 4/16・**M7.0+**)。**R1 行 JR 豊肥本線 + 南阿蘇鉄道 + 熊本空港被災**、現在(2026)は全交通網が完全復旧、しかし R6 育 熊本城は 2032 完全修復予定で部分公開のみ。",
    content_md: "- 発生:**2016 年 4 月 14 日 + 4 月 16 日・M7.0+**\n- 主被災交通:**R1 行 JR 豊肥本線 + 南阿蘇鉄道 + 熊本空港**\n- 復興状況(2026 現在):\n  - **JR 豊肥本線:2020 全線復旧**\n  - **南阿蘇鉄道:2023 全線復旧**\n  - **阿蘇くまもと空港:2023 新ターミナル**\n  - 全交通網完全復旧\n- 関連:**R6 育 熊本城は 2032 完全修復予定**\n- 並列:R1 行 JR 肥薩線(2020 水害で別問題運休継続)",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "熊本市",
    lg_code: "43100",
    area_types: ["transit_hub"],
    lat: 32.7886,
    lon: 130.6928,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kumamoto_quake_2016_transport", "M7.0", "transport_impact", "recovery_complete", "advisory"],
    source: "manual",
  },
  {
    slug: "kumamoto-2020-flood-transport-impact",
    category: "transport",
    sub_type: "kumamoto_jr_local",
    title_zh: "球磨川 2020 7 月豪雨交通影響総覧(2020/7/4 球磨川氾濫+ JR 肥薩線 + くま川鉄道 + 球磨川下り被災)",
    title_ja: "球磨川 2020 水害交通影響",
    romaji: "Kuma River 2020 Flood Transport Impact",
    summary_zh: "**球磨川 2020 7 月豪雨交通影響は人吉球磨地方に深刻**(2020/7/4・**球磨川氾濫**)。**R1 行 JR 肥薩線(運休継続中・2026 現在)+ くま川鉄道(2025 全線復旧)+ R1 楽 球磨川下り(復興進行中)被災**、訪問前に各交通の最新運行状況確認推奨。",
    content_md: "- 発生:**2020 年 7 月 4 日豪雨水害**\n- 主被災交通:**R1 行 JR 肥薩線 + くま川鉄道 + R1 楽 球磨川下り**\n- 復興状況(2026 現在):\n  - **JR 肥薩線:八代-吉松間運休継続中・再開未定**\n  - **くま川鉄道:2025 全線復旧**\n  - **球磨川下り:復興進行中**\n  - **R1 楽 かわせみ やませみ観光列車:運休継続(肥薩線運休のため)**\n- **訪問前に必ず最新運行状況を確認**\n- 並列:R6 育 人吉相良家 700 年文化アクセス は くま川鉄道 + バスで可能",
    region: "kyushu",
    prefecture_ja: "熊本県",
    gun_ja: null,
    municipality_ja: "人吉市",
    lg_code: "43203",
    area_types: ["transit_hub"],
    lat: 32.2117,
    lon: 130.7625,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kuma_2020_flood_transport", "july_4_2020", "hisatsu_suspended", "kuma_kawa_2025_recovery", "advisory"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[kumamoto-transport-r1] 尚無條目");
    return;
  }
  console.log(`[kumamoto-transport-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(28)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[kumamoto-transport-r1] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[kumamoto-transport-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[kumamoto-transport-r1] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
