// Seed 京都府 · 行類 條目 → public.japan_entries(Sprint 14.4)
//
// 京都の交通は商業密度低めだが、深度自由行で「どう移動するか」は最重要。
// 9 phase に分けて投入(目標 ~67 entries):
//   Phase 1 — 鉄道会社 + 路線
//   Phase 2 — 1 日券・トラベルパス
//   Phase 3 — 空港アクセス
//   Phase 4 — 観光列車・観光バス
//   Phase 5 — エリア別アクセスガイド
//   Phase 6 — 主要 hub 解説
//   Phase 7 — タクシー・レンタル
//   Phase 8 — 散策路線・歩き旅
//   Phase 9 — 季節限定運行・早朝深夜・バリアフリー
//
// Usage:
//   npm run seed:japan-kyoto-transport:dry
//   npm run seed:japan-kyoto-transport

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "kyo_railway_company"
  | "kyo_one_day_pass"
  | "kyo_taxi_service"
  | "bicycle_rental"
  | "area_access_guide"
  | "walking_route"
  | "transit_hub"
  | "seasonal_transit"
  | "accessibility_info"
  | "ticket_promo"
  | "sightseeing_train"
  | "limited_express_private"
  | "airport_access"
  | "rental_car_tips"
  | "night_transit"
  | "cable_car_lift";

interface SeedRow {
  slug: string;
  category: "transport";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "kansai";
  prefecture_ja: "京都府";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // Phase 1 — 鉄道会社 + 路線
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-jr-kyoto-station",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "JR 西日本 京都站",
    title_ja: "JR西日本 京都駅",
    romaji: "JR West Kyoto Station",
    summary_zh: "**JR 西日本の京都ターミナル**、東海道新幹線・在来線のハブ。新幹線(東京 ↔ 博多)・JR京都線(大阪)・嵯峨野線(嵐山)・奈良線(伏見稲荷・宇治)・湖西線(琵琶湖)・北陸線(金沢)等の起点。**京都駅ビル**(1997 開業・原広司設計)は商業施設・ホテル・展望台を併設。",
    content_md: "- 駅:JR京都駅(下京区東塩小路町)\n- 路線:東海道新幹線・JR京都線・嵯峨野線・奈良線・湖西線・近江(北陸経由)\n- 大阪→京都:新幹線 14 分・JR新快速 28 分\n- 東京→京都:新幹線 のぞみ 2 時間 15 分\n- 駅ビル:京都拉麺小路・伊勢丹・カフェ・展望台 大空広場\n- 文化価値:1997 年駅ビル建設(原広司)で論争、京都駅シンボル化",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.westjr.co.jp/",
    },
    tags: ["jr_west", "shinkansen_hub", "kyoto_station_building", "1997_opening"],
    source: "manual",
  },
  {
    slug: "kyoto-jr-sagano-line",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "JR 嵯峨野線(山陰本線)",
    title_ja: "JR 嵯峨野線(山陰本線)",
    romaji: "JR Sagano Line",
    summary_zh: "**京都駅 ↔ 嵐山(嵯峨嵐山駅)を結ぶ JR 西日本の主要観光路線**。京都駅から嵯峨嵐山まで 17 分、二条駅(二条城)・円町・花園(妙心寺)・太秦(東映太秦映画村)等を経由。**嵯峨嵐山駅は嵯峨野トロッコ列車の起点**でもある。",
    content_md: "- 路線:JR京都駅 → 二条 → 円町 → 花園 → 太秦 → 嵯峨嵐山(嵐山)\n- 所要時間:京都 → 嵯峨嵐山 17 分(¥240)\n- 主要観光地:二条城(二条)・妙心寺(花園)・東映太秦映画村(太秦)・嵐山(嵯峨嵐山)\n- 嵯峨嵐山駅:嵯峨野トロッコ列車起点\n- 運行間隔:日中 15 分間隔・朝夕 7-10 分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0188,
    lon: 135.6815,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jr_west", "sagano_line", "arashiyama_access", "nijo_castle"],
    source: "manual",
  },
  {
    slug: "kyoto-jr-nara-line",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "JR 奈良線(伏見稲荷・宇治線)",
    title_ja: "JR 奈良線",
    romaji: "JR Nara Line",
    summary_zh: "**京都駅 ↔ 奈良駅を結ぶ JR 西日本の路線**、伏見稲荷大社(稲荷駅)・宇治平等院(宇治駅)へのアクセス起点。京都駅から稲荷 5 分・宇治 30 分。**みやこ路快速** で京都・奈良間 45 分。",
    content_md: "- 路線:JR京都駅 → 東福寺 → 稲荷 → 宇治 → 奈良\n- 所要時間:京都 → 稲荷 5 分(¥150)・京都 → 宇治 30 分(¥240)\n- みやこ路快速:京都 → 奈良 45 分\n- 主要観光地:東福寺(東福寺駅)・伏見稲荷(稲荷)・万福寺(黄檗)・平等院(宇治)\n- 注:伏見稲荷は早朝 6 時前から参拝可、JR + 京阪 の両方で行ける",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9676,
    lon: 135.7723,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jr_west", "nara_line", "fushimi_inari", "byodo_in_uji"],
    source: "manual",
  },
  {
    slug: "kyoto-keihan-line",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "京阪電鉄 京阪本線",
    title_ja: "京阪電鉄 京阪本線",
    romaji: "Keihan Main Line",
    summary_zh: "**京都(出町柳)↔ 大阪(淀屋橋)を鴨川沿いに結ぶ私鉄**、伏見稲荷・東福寺・三十三間堂・祇園・銀閣寺(出町柳経由)へのアクセス。**プレミアムカー**(指定座席・1 両 / 列車)が観光客に人気、追加 ¥500-900。",
    content_md: "- 路線:出町柳(京都北部)→ 三条 → 祇園四条 → 七条 → 東福寺 → 伏見稲荷 → 中書島(伏見) → 大阪 淀屋橋\n- 京都市内主要駅:出町柳・神宮丸太町・三条・祇園四条・清水五条・七条・東福寺・伏見稲荷\n- 京都 → 大阪:特急 47 分・準急 60 分\n- プレミアムカー:¥500-900 追加で確実な座席\n- 1 日券:京都・大阪 ¥1,000(京阪 1day)\n- 観光優位:鴨川沿いを走るため車窓も京都らしい",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.012,
    lon: 135.772,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.keihan.co.jp/",
    },
    tags: ["keihan", "main_line", "premium_car", "kamogawa_route"],
    source: "manual",
  },
  {
    slug: "kyoto-keihan-uji-line",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "京阪電鉄 宇治線",
    title_ja: "京阪電鉄 宇治線",
    romaji: "Keihan Uji Line",
    summary_zh: "**中書島(伏見)↔ 宇治を結ぶ京阪の支線**、平等院・宇治川・茶文化アクセス。京阪本線の伏見地区から宇治へ直結、JR 奈良線とは別ルート。中書島から宇治まで 16 分、京阪本線(京都市内)+ 宇治線で京都 → 宇治 約 35 分。",
    content_md: "- 路線:中書島 → 観月橋 → 桃山南口 → 六地蔵 → 木幡 → 黄檗 → 三室戸 → 宇治\n- 主要観光地:平等院 + 宇治上神社(宇治)・三室戸寺(三室戸)・万福寺(黄檗)\n- 中書島 → 宇治 16 分(¥330)\n- 京都(出町柳)→ 宇治 約 35 分(乗換込)\n- 注:宇治市内 + JR 宇治駅 + 京阪宇治駅 は別の駅",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "宇治市",
    lg_code: "26204",
    area_types: ["urban_central"],
    lat: 34.8898,
    lon: 135.8074,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["keihan", "uji_line", "byodo_in", "uji_river"],
    source: "manual",
  },
  {
    slug: "kyoto-hankyu-kyoto-line",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "阪急電鉄 京都本線",
    title_ja: "阪急電鉄 京都本線",
    romaji: "Hankyu Kyoto Line",
    summary_zh: "**京都(京都河原町)↔ 大阪(梅田)を結ぶ私鉄**。河原町・烏丸・大宮・桂・洛西口・東向日・西山天王山・上桂(嵐山線)等。**特急** で京都河原町 ↔ 大阪梅田 43 分、JR より安い + 街中(梅田)直結が利点。1 日券 関西版あり。",
    content_md: "- 路線:京都河原町 → 烏丸 → 大宮 → 西院 → 桂 → 大阪 梅田\n- 主要京都駅:京都河原町(終点・四条河原町徒歩 1 分)・烏丸(四条烏丸 徒歩 1 分)・大宮・西院\n- 京都 → 大阪:特急 43 分・準急 60 分(¥420)\n- 嵐山線:桂で乗換 → 嵐山駅(阪急嵐山駅)\n- 1 日券:阪急全線 ¥1,300\n- 観光優位:京都河原町は四条河原町ど真ん中で観光起点に最適",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0033,
    lon: 135.7689,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.hankyu.co.jp/",
    },
    tags: ["hankyu", "kyoto_line", "kawaramachi_terminal", "osaka_link"],
    source: "manual",
  },
  {
    slug: "kyoto-randen-arashiyama",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "嵐電(京福電気鉄道嵐山本線)",
    title_ja: "嵐電(京福電気鉄道)",
    romaji: "Randen / Keifuku Arashiyama Line",
    summary_zh: "**京都四条大宮 ↔ 嵐山を結ぶ路面電車**、1910 年開業の歴史路線。一両編成のレトロ電車で嵐山観光のシンボル、車窓から街並みを観賞しながらの 22 分の旅。**1 日券 ¥800**で全線乗り放題。**北野線**(帷子ノ辻 ↔ 北野白梅町)との接続で太秦映画村・北野天満宮 + 嵐山セット可。",
    content_md: "- 路線:嵐山本線(四条大宮 → 嵐山)+ 北野線(帷子ノ辻 ↔ 北野白梅町)\n- 開業:1910 年(明治 43)\n- 主要駅:四条大宮・西院・西大路三条・帷子ノ辻・太秦広隆寺・嵐山\n- 所要時間:四条大宮 → 嵐山 22 分(¥250)\n- 1 日券:¥800(全線乗り放題・嵐山以外含む)\n- 文化価値:1 両編成路面電車、京の景観と一体化\n- 注:車内アナウンス + 案内パネル英語あり",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.014,
    lon: 135.6776,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://randen.keifuku.co.jp/",
    },
    tags: ["randen", "since_1910", "tram_line", "arashiyama_iconic"],
    source: "manual",
  },
  {
    slug: "kyoto-eizan-railway",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "叡山電鉄(鞍馬線・八瀬比叡山口線)",
    title_ja: "叡山電鉄",
    romaji: "Eizan Railway",
    summary_zh: "**出町柳 ↔ 鞍馬・八瀬比叡山口を結ぶ私鉄**、1925 年開業。鞍馬線(出町柳 → 鞍馬)+ 八瀬比叡山口線(出町柳 → 八瀬比叡山口)の 2 路線。**観光列車「きらら」**(展望車両)が紅葉時期に絶景。秋の「もみじのトンネル」(市原 ↔ 二ノ瀬間)が名所。",
    content_md: "- 路線:出町柳起点 → 鞍馬線(出町柳 → 鞍馬)+ 八瀬比叡山口線\n- 主要駅:出町柳・修学院・宝ケ池・三宅八幡・八瀬比叡山口・市原・二ノ瀬・貴船口・鞍馬\n- 出町柳 → 鞍馬 30 分(¥430)・出町柳 → 八瀬比叡山口 14 分(¥270)\n- 観光列車「きらら」:展望車両、特に紅葉時期に絶景\n- もみじのトンネル:11 月中旬-下旬、市原 ↔ 二ノ瀬間\n- 1 日券:¥1,000(全線フリー)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.03,
    lon: 135.771,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://eizandensha.co.jp/",
    },
    tags: ["eizan", "since_1925", "kurama_line", "kirara_train", "momiji_tunnel"],
    source: "manual",
  },
  {
    slug: "kyoto-subway-karasuma",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "京都市営地下鉄 烏丸線",
    title_ja: "京都市営地下鉄 烏丸線",
    romaji: "Kyoto Subway Karasuma Line",
    summary_zh: "**京都市営地下鉄の南北縦貫線**、国際会館 ↔ 竹田の 13.7 km。京都駅・四条・烏丸御池・今出川 等の主要観光地直結、JR・近鉄・阪急との接続もハブ機能。",
    content_md: "- 路線:国際会館(京都北端)→ 北山 → 北大路 → 鞍馬口 → 今出川 → 丸太町 → 烏丸御池 → 四条 → 五条 → 京都駅 → 九条 → 十条 → 竹田\n- 13.7 km・全 15 駅\n- 京都駅 → 四条 4 分・京都駅 → 烏丸御池 6 分\n- 接続:京都駅(JR・近鉄)・烏丸御池(東西線)・四条(阪急)・竹田(近鉄)\n- 1 日券:¥800(地下鉄のみ)・¥1,100(地下鉄 + 市バス)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0036,
    lon: 135.7587,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www2.city.kyoto.lg.jp/kotsu/",
    },
    tags: ["kyoto_subway", "karasuma_line", "north_south_line", "15_stations"],
    source: "manual",
  },
  {
    slug: "kyoto-subway-tozai",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "京都市営地下鉄 東西線",
    title_ja: "京都市営地下鉄 東西線",
    romaji: "Kyoto Subway Tozai Line",
    summary_zh: "**京都市営地下鉄の東西横断線**、太秦天神川 ↔ 六地蔵の 17.5 km。二条城・京都市役所前・東山・蹴上・山科 等。**京阪との直通運転** で六地蔵 → 浜大津まで延伸可。",
    content_md: "- 路線:太秦天神川 → 西大路御池 → 二条城前 → 烏丸御池 → 京都市役所前 → 三条京阪 → 東山 → 蹴上 → 御陵 → 山科 → 六地蔵\n- 17.5 km・全 17 駅\n- 主要観光駅:二条城前(二条城)・東山(平安神宮 + 知恩院)・蹴上(南禅寺 + インクライン)\n- 接続:烏丸御池(烏丸線)・三条京阪(京阪)・山科(JR + 京阪山科線)\n- 注:京阪京津線と直通運転(浜大津まで)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.011,
    lon: 135.76,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www2.city.kyoto.lg.jp/kotsu/",
    },
    tags: ["kyoto_subway", "tozai_line", "east_west_line", "17_stations"],
    source: "manual",
  },
  {
    slug: "kyoto-tango-railway",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "京都丹後鉄道",
    title_ja: "京都丹後鉄道",
    romaji: "Kyoto Tango Railway",
    summary_zh: "**京都府北部の第三セクター鉄道**、福知山 ↔ 天橋立 ↔ 西舞鶴 を結ぶ。**観光列車「丹後の海」(あおまつ・あかまつ・くろまつ)** が日本海沿いの絶景を走る。京都市内から天橋立は JR + 京都丹後鉄道で約 2.5 時間。",
    content_md: "- 路線:宮舞線(西舞鶴 ↔ 宮津)+ 宮豊線(宮津 ↔ 豊岡)+ 宮福線(宮津 ↔ 福知山)\n- 観光列車:丹後の海(あおまつ・あかまつ・くろまつ)— 各曜日運行\n- 京都 → 天橋立:京都(JR山陰本線特急きのさき)→ 福知山(乗換)→ 天橋立 約 2.5 時間\n- 1 日券:京都丹後鉄道全線フリー ¥2,000\n- 文化価値:京都北部観光(天橋立・伊根・京丹後)の主要交通\n- 注:特急含む乗車券あり、京都市発着",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "宮津市",
    lg_code: "26205",
    area_types: ["rural"],
    lat: 35.535,
    lon: 135.1944,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://trains.willer.co.jp/",
    },
    tags: ["kyoto_tango_railway", "third_sector", "tango_no_umi", "amanohashidate_access"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 2 — 1 日券・トラベルパス
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-bus-one-day-pass",
    category: "transport",
    sub_type: "kyo_one_day_pass",
    title_zh: "市バス 1 日券",
    title_ja: "市バス 1 日券",
    romaji: "Kyoto City Bus 1-Day Pass",
    summary_zh: "**京都市交通局の市バス 1 日券**、¥700(2024 年改定後)。市バス全線 + 京都バス(嵐山・大原方面)+ 京阪バス(山科 + 醍醐)の指定区間が乗り放題。京都市内観光は市バスが主軸、3 回以上乗れば元が取れる(1 回 ¥230)。",
    content_md: "- 価格:¥700(2024 年改定)\n- 範囲:市バス全線 + 京都バス指定区間 + 京阪バス指定区間\n- 元取り:¥230 × 3 回 = ¥690 で元取り、3 回以上乗る予定なら買い\n- 購入:バス車内・市バス案内所・地下鉄駅・コンビニ\n- 使用法:初回乗車時に車内機械で打刻 → 以降は券を提示\n- 観光モデル:1 日 4-6 回乗ることが多い京都観光で必須\n- 注:夜間のバスも対象、最終便まで使える",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0036,
    lon: 135.7587,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www2.city.kyoto.lg.jp/kotsu/",
    },
    tags: ["bus_pass", "city_bus", "700_yen", "essential_for_kyoto"],
    source: "manual",
  },
  {
    slug: "kyoto-subway-bus-pass",
    category: "transport",
    sub_type: "kyo_one_day_pass",
    title_zh: "地下鉄 + 市バス 1 日券",
    title_ja: "地下鉄・バス 1 日券",
    romaji: "Subway & Bus 1-Day Pass",
    summary_zh: "**京都市の地下鉄 + 市バス + 京都バス 共通 1 日券**、¥1,100。地下鉄 + バス両方使う日に最適、市バス1日券(¥700)+ 地下鉄1日券(¥800)= ¥1,500 を ¥400 抑え。観光地が地下鉄沿線(東山・烏丸・北大路)+ バス区間(嵐山・銀閣寺)の両方混在する 1 日に。",
    content_md: "- 価格:¥1,100\n- 範囲:地下鉄全線 + 市バス + 京都バス指定区間\n- 元取り:地下鉄 ¥220 × 3 + バス ¥230 × 2 = ¥1,120 で取れる\n- 購入:地下鉄駅自動券売機・バス案内所・コンビニ\n- 観光モデル:嵐山(嵯峨野線)+ 銀閣寺(バス)+ 河原町(地下鉄)を 1 日で回る場合に最適",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0036,
    lon: 135.7587,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www2.city.kyoto.lg.jp/kotsu/",
    },
    tags: ["subway_bus_pass", "1100_yen", "combo_pass"],
    source: "manual",
  },
  {
    slug: "kyoto-randen-one-day",
    category: "transport",
    sub_type: "kyo_one_day_pass",
    title_zh: "嵐電 1 日券",
    title_ja: "嵐電 1 日フリー切符",
    romaji: "Randen 1-Day Pass",
    summary_zh: "**嵐電(京福電気鉄道)全線乗り放題 1 日券**、¥800。嵐山本線 + 北野線、嵐山 + 太秦映画村 + 北野天満宮 を 1 日で回る場合の鉄板。3 駅以上乗れば元取り。",
    content_md: "- 価格:¥800(大人)・¥400(子ども)\n- 範囲:嵐電全線(嵐山本線 + 北野線)\n- 元取り:3 駅以上(¥250 × 4 = ¥1,000)で取れる\n- 観光モデル:四条大宮 → 嵐山 → 帷子ノ辻 → 北野白梅町(北野天満宮)→ 帷子ノ辻 → 太秦広隆寺 → 四条大宮\n- 購入:嵐電車内・主要駅\n- 嵐山+太秦+北野 ダブル観光に最適",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.014,
    lon: 135.6776,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["randen_pass", "800_yen", "arashiyama_uzumasa_kitano"],
    source: "manual",
  },
  {
    slug: "kyoto-eizan-one-day",
    category: "transport",
    sub_type: "kyo_one_day_pass",
    title_zh: "叡山電車 1 日券",
    title_ja: "叡山電車 1 日券",
    romaji: "Eizan 1-Day Pass",
    summary_zh: "**叡山電車全線(鞍馬線 + 八瀬比叡山口線)1 日乗り放題**、¥1,000。鞍馬・貴船 + 八瀬・比叡山方面 を 1 日で回る場合に。出町柳 → 鞍馬往復だけで ¥860、+1 駅で元が取れる。",
    content_md: "- 価格:¥1,000(大人)・¥500(子ども)\n- 範囲:叡山電車全線\n- 元取り:出町柳 → 鞍馬往復 ¥860 + α で取れる\n- 観光モデル:出町柳 → 鞍馬寺 → 貴船 → 戻り → 八瀬比叡山口 → 出町柳(秋もみじのトンネル含む)\n- 購入:出町柳駅 + 主要駅",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.03,
    lon: 135.771,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["eizan_pass", "1000_yen", "kurama_yase"],
    source: "manual",
  },
  {
    slug: "kyoto-keihan-one-day",
    category: "transport",
    sub_type: "kyo_one_day_pass",
    title_zh: "京阪電車 京都・大阪 1 日券",
    title_ja: "京阪電車 京都・大阪観光 1 日券",
    romaji: "Keihan 1-Day Pass",
    summary_zh: "**京阪電車全線(大阪 + 京都)1 日乗り放題**、¥1,000(京阪 1day)。京都(出町柳)→ 大阪(淀屋橋)を含む全区間。**伏見稲荷 + 中書島(伏見) + 出町柳 + 三条** をハシゴする日に最適。",
    content_md: "- 価格:¥1,000(京阪 1day・全線)\n- 範囲:京阪電車全線(京都 + 大阪)\n- 観光モデル:京都(伏見稲荷 → 三条 祇園四条 → 出町柳)+ 大阪 で計 5-6 回乗り\n- 購入:駅自動券売機・京阪窓口\n- 関連:京阪 + 大阪メトロ共通の関西スルーパス もあり",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.012,
    lon: 135.772,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["keihan_pass", "1000_yen", "kyoto_osaka"],
    source: "manual",
  },
  {
    slug: "kyoto-hankyu-one-day-pass",
    category: "transport",
    sub_type: "kyo_one_day_pass",
    title_zh: "阪急電車 1 日乗車券",
    title_ja: "阪急 1 日乗車券",
    romaji: "Hankyu 1-Day Pass",
    summary_zh: "**阪急電車全線 1 日乗り放題**、¥1,300。京都(京都河原町・烏丸)+ 大阪(梅田・心斎橋)+ 神戸(三宮)+ 宝塚 を含む。**京都河原町 → 大阪梅田**(¥420)を 4 回以上乗れば元取り。",
    content_md: "- 価格:¥1,300(大人)\n- 範囲:阪急電鉄全線(京都・大阪・神戸・宝塚)\n- 元取り:京都 → 大阪 ¥420 × 4 = ¥1,680\n- 観光モデル:京都河原町 → 大阪梅田 → 心斎橋 → 神戸三宮 → 宝塚 → 京都\n- 購入:阪急主要駅(京都河原町・梅田 等)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0033,
    lon: 135.7689,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hankyu_pass", "1300_yen", "kansai_wide"],
    source: "manual",
  },
  {
    slug: "kyoto-kansai-thru-pass",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "関西スルーパス",
    title_ja: "関西スルーパス",
    romaji: "Kansai Thru Pass",
    summary_zh: "**関西全域(京都・大阪・神戸・奈良・和歌山・関西空港)の私鉄 + バス + 地下鉄共通の 2 日 / 3 日券**。¥4,800(2日)/ ¥6,000(3日)。JR は対象外だが、それ以外の主要交通網はカバー。京都に複数日滞在 + 大阪・奈良 観光する旅行者に最適。",
    content_md: "- 価格:¥4,800(2 日券)/ ¥6,000(3 日券)\n- 範囲:阪急・京阪・近鉄・阪神・南海・関西空港リムジン・地下鉄・私鉄バス 等(JR 除く)\n- 関西空港 ↔ 京都・大阪・奈良 等のアクセスも含む\n- 購入:関西空港 + 主要私鉄駅(海外発行版あり)\n- 観光モデル:関空到着 → 京都 → 大阪 → 奈良 → 関空 のトラベラー向け\n- 注:JR は対象外、JR利用予定なら別途",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0036,
    lon: 135.7587,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kansai_thru_pass", "2_day_3_day", "private_railways"],
    source: "manual",
  },
  {
    slug: "kyoto-jr-kyoto-1day",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "JR 京都・大阪 観光 1 日券",
    title_ja: "JR 京都・大阪 観光 1 日券",
    romaji: "JR Kyoto-Osaka Sightseeing Pass",
    summary_zh: "**JR 西日本の京都 + 大阪エリア限定 1 日乗り放題**、¥1,200(JR 西日本ホームページ)。京都・大阪の在来線乗り放題で、嵯峨野線(嵐山)・奈良線(伏見稲荷・宇治)・大阪環状線 等含む。",
    content_md: "- 価格:¥1,200(大人)\n- 範囲:京都 + 大阪エリアの JR 在来線(新幹線除く)\n- 元取り:嵐山往復 ¥480 + 伏見稲荷 ¥150 + α で取れる\n- 購入:JR京都駅みどりの窓口 + 主要 JR 駅\n- 観光モデル:嵐山 + 伏見稲荷 + 宇治 + 大阪城 を 1 日で回る\n- 注:JRエリアパスとは別商品",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jr_west_pass", "1200_yen", "kyoto_osaka"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 3 — 空港アクセス
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-haruka-kansai",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "JR 特急はるか(関空 ↔ 京都)",
    title_ja: "JR 特急 はるか",
    romaji: "JR Limited Express Haruka",
    summary_zh: "**関西国際空港 → 京都駅を 75 分で結ぶ JR 特急**。¥3,640(自由席)・¥4,170(指定席)。**ICOCA & HARUKA きっぷ**(海外旅行客向 ¥3,200)が割引、関空到着客の京都直行に最適。",
    content_md: "- 路線:関西空港駅 → 天王寺 → 新大阪 → 京都駅\n- 所要時間:75 分(関空 → 京都)\n- 料金:自由席 ¥3,640・指定席 ¥4,170\n- 海外旅行客向:ICOCA & HARUKA きっぷ ¥3,200(ICOCA + 片道 はるか)\n- 運行間隔:30 分間隔(朝夕は 15 分間隔)\n- 観光モデル:関空到着 → JR はるか → 京都駅(深夜便でも 24 時前に到着可能)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["haruka_express", "kix_kyoto", "75_min", "icoca_haruka_pass"],
    source: "manual",
  },
  {
    slug: "kyoto-kansai-airport-limousine",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "関空リムジンバス → 京都",
    title_ja: "関空リムジンバス → 京都",
    romaji: "Kansai Airport Limousine to Kyoto",
    summary_zh: "**関西空港 → 京都駅 八条口を結ぶリムジンバス**、¥2,800(2024 年改定後)、所要 1 時間 25 分。荷物多い客 + ホテル直接送迎(京都駅周辺ホテル)に便利。",
    content_md: "- 路線:関西空港 → 京都駅八条口 + 京都グランヴィア・新都ホテル等送迎\n- 所要時間:1 時間 25 分\n- 料金:¥2,800(片道)\n- 運行間隔:1 時間 1-2 本\n- 利点:荷物が多い・乗換不要・ホテル直送迎\n- 注:京都駅以外のホテルは結局タクシー利用、エリアによっては はるか + 地下鉄が早い",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9842,
    lon: 135.7619,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      official: "https://www.okkbus.co.jp/",
    },
    tags: ["airport_limousine", "kix_kyoto_bus", "85_min", "luggage_friendly"],
    source: "manual",
  },
  {
    slug: "kyoto-itami-airport-limousine",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "伊丹空港リムジンバス → 京都",
    title_ja: "伊丹空港リムジンバス → 京都",
    romaji: "Itami Airport Limousine to Kyoto",
    summary_zh: "**大阪伊丹空港 → 京都駅 八条口を結ぶリムジンバス**、¥1,340、所要 50 分。国内線で大阪到着 + 京都に行く場合の鉄板。",
    content_md: "- 路線:伊丹空港 → 京都駅八条口\n- 所要時間:50 分\n- 料金:¥1,340(片道)\n- 運行間隔:30 分間隔\n- 利点:大阪国内線到着 → 京都直行で最も簡単\n- 注:伊丹発着の航空便は ANA・JAL 国内線が中心",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9842,
    lon: 135.7619,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["airport_limousine", "itami_kyoto", "50_min", "domestic_arrival"],
    source: "manual",
  },
  {
    slug: "kyoto-kobe-airport-access",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "神戸空港 → 京都 アクセス",
    title_ja: "神戸空港 → 京都 アクセス",
    romaji: "Kobe Airport to Kyoto Access",
    summary_zh: "**神戸空港 → 京都の主要 ルート**。神戸空港 → ポートライナー → 三宮 → JR 新快速 → 京都駅 で約 1.5 時間、料金 ¥1,500。LCC 便を神戸空港利用 + 京都行きの場合。",
    content_md: "- 主要ルート:神戸空港 → ポートライナー(三宮)→ JR 新快速(京都)\n- 所要時間:約 1 時間 30 分\n- 料金合計:約 ¥1,500(ポートライナー ¥330 + JR ¥1,110)\n- 利用シーン:Skymark 等の LCC 便利用客\n- 比較:関空はるかより 30 分早く + 安いことも(神戸経由便利用時)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kobe_airport", "skymark_arrival", "port_liner_jr"],
    source: "manual",
  },
  {
    slug: "kyoto-mk-taxi-airport",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "MK タクシー定額(空港 ↔ 京都)",
    title_ja: "MK タクシー定額空港送迎",
    romaji: "MK Taxi Airport Fixed Fare",
    summary_zh: "**MK タクシー(京都発祥)の関空・伊丹 ↔ 京都市内ホテル定額送迎**。関空 ↔ 京都市内 1-4 名 ¥18,000-20,000(深夜割増あり)。**英語ドライバー指定可**、家族 / グループ + 大荷物時の鉄板。",
    content_md: "- 関空 → 京都市内:¥18,000-20,000(1-4 名・深夜割増 +20%)\n- 伊丹 → 京都市内:¥10,500-12,000\n- 英語対応:事前指定可(無料)\n- 予約:HP・電話・メール、3-4 名以上ならリムジンバス + タクシーより安い場合あり\n- 利点:ホテル直送迎・家族安心・荷物多い場合便利\n- MK タクシーの特色:京都発祥(1960 年)・観光ガイドサービス併設",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {
      official: "https://www.mktaxi-japan.com/",
    },
    tags: ["mk_taxi", "fixed_fare", "english_driver", "airport_transfer"],
    source: "manual",
  },
  {
    slug: "kyoto-thunderbird-northern",
    category: "transport",
    sub_type: "limited_express_private",
    title_zh: "JR 特急サンダーバード(北陸方面)",
    title_ja: "JR 特急 サンダーバード",
    romaji: "JR Limited Express Thunderbird",
    summary_zh: "**京都 ↔ 金沢・敦賀(北陸方面)を結ぶ JR 特急**、京都駅から敦賀 1 時間 / 福井 1 時間 30 分(2024 年北陸新幹線敦賀延伸後は敦賀乗換)。北陸 + 京都 セット観光に。",
    content_md: "- 路線:京都駅 → 大阪 → 敦賀(2024 年から北陸新幹線へ乗換)\n- 所要時間:京都 → 敦賀 1 時間\n- 北陸新幹線開業(2024.3):敦賀から先は新幹線\n- 料金:京都 → 金沢 約 ¥7,500(乗換含)\n- 利用:京都北部から離れた北陸(金沢・福井)観光のアクセス\n- 注:2024 年 3 月以降は敦賀で乗換が必要",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["thunderbird", "hokuriku_access", "tsuruga_transfer"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase 4 — 観光列車・観光バス
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kyoto-sagano-romantic-train",
    category: "transport",
    sub_type: "sightseeing_train",
    title_zh: "嵯峨野トロッコ列車",
    title_ja: "嵯峨野トロッコ列車",
    romaji: "Sagano Romantic Train",
    summary_zh: "**嵯峨嵐山 → トロッコ亀岡(7.3 km / 25 分)を結ぶ観光トロッコ列車**。1991 年運行開始。**保津川渓谷沿いの絶景**、特に春桜・夏新緑・秋紅葉時期は見事。**保津川下り**(亀岡 → 嵐山)とのセットで往復観光が定番。¥880(片道)。",
    content_md: "- 路線:トロッコ嵯峨 → トロッコ嵐山 → トロッコ保津峡 → トロッコ亀岡\n- 所要時間:25 分(7.3 km)\n- 料金:大人 ¥880・子ども ¥440(片道)\n- 運行期間:3 月 1 日 - 12 月 29 日(冬期休業)\n- 運行本数:1 日 8 往復(ピーク時 + 11 往復)\n- 観光モデル:嵐山 → トロッコ → 亀岡 → 保津川下り → 嵐山 戻り(1 日コース)\n- 文化価値:1991 年廃線復活路線、京都西部の観光列車代表",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0188,
    lon: 135.6815,
    season_start: "2000-03-01",
    season_end: "2000-12-29",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      official: "https://www.sagano-kanko.co.jp/",
    },
    tags: ["sagano_torokko", "since_1991", "hozugawa_canyon", "spring_summer_autumn"],
    source: "manual",
  },
  {
    slug: "kyoto-tango-no-umi-aomatsu",
    category: "transport",
    sub_type: "sightseeing_train",
    title_zh: "京都丹後鉄道 あおまつ",
    title_ja: "丹後の海 あおまつ",
    romaji: "Tango no Umi Aomatsu",
    summary_zh: "**京都丹後鉄道の観光列車「丹後の海」シリーズの 1 つ**、福知山 ↔ 天橋立を結ぶ。**水戸岡鋭治(JR 九州 ななつ星デザイナー)**が手がけた青色塗装の電車、車内は木目調インテリア。日本海絶景の車窓 + デザイン性の高さで人気。",
    content_md: "- 路線:福知山 → 宮津 → 天橋立(あおまつ) — 1 日 1-2 往復\n- 料金:乗車券 + 特急 1,400-2,000 円\n- 設計:水戸岡鋭治(JR 九州 ななつ星 + or 海幸山幸 等)\n- 内装:木目調・天井に青空デザイン・カウンター席\n- 運行日:あおまつ は土日祝中心\n- 関連:丹後の海シリーズ(あおまつ・あかまつ・くろまつ)各曜日異なる",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "宮津市",
    lg_code: "26205",
    area_types: ["rural"],
    lat: 35.535,
    lon: 135.1944,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["tango_no_umi", "aomatsu", "mitooka_eiji", "design_train"],
    source: "manual",
  },
  {
    slug: "kyoto-tango-no-umi-akamatsu",
    category: "transport",
    sub_type: "sightseeing_train",
    title_zh: "京都丹後鉄道 あかまつ",
    title_ja: "丹後の海 あかまつ",
    romaji: "Tango no Umi Akamatsu",
    summary_zh: "**「丹後の海」シリーズの赤色版**、軽食 + ドリンク付き観光列車。福知山 ↔ 天橋立、平日中心運行。¥3,300(乗車券 + 食事込み)で日本海の景色 + デザイン列車を一体験。",
    content_md: "- 路線:福知山 → 宮津 → 天橋立(あかまつ) — 平日 1 往復\n- 料金:¥3,300(乗車券 + 軽食ドリンク込み)\n- 設計:水戸岡鋭治(JR 九州ななつ星デザイナー)\n- 内装:赤色塗装・木目調・カウンター席\n- 関連:丹後の海 あおまつ・くろまつ と同じシリーズ",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "宮津市",
    lg_code: "26205",
    area_types: ["rural"],
    lat: 35.535,
    lon: 135.1944,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["tango_no_umi", "akamatsu", "mitooka_eiji", "weekday_only"],
    source: "manual",
  },
  {
    slug: "kyoto-tango-no-umi-kuromatsu",
    category: "transport",
    sub_type: "sightseeing_train",
    title_zh: "京都丹後鉄道 くろまつ",
    title_ja: "丹後の海 くろまつ",
    romaji: "Tango no Umi Kuromatsu",
    summary_zh: "**「丹後の海」シリーズ最高級版**、コース料理付き観光列車 ¥10,000-13,000。シェフ + 地元食材で「走るレストラン」、土日のみ運行。",
    content_md: "- 路線:福知山↔天橋立(土日)\n- 料金:¥10,000-13,000(コース料理付き)\n- 設計:水戸岡鋭治\n- 特色:走るレストラン、地元食材コース\n- 予約:数か月前推奨",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "宮津市",
    lg_code: "26205",
    area_types: ["rural"],
    lat: 35.535,
    lon: 135.1944,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["kuromatsu", "premium_dining_train", "weekend_only"],
    source: "manual",
  },
  {
    slug: "kyoto-sky-hop-bus",
    category: "transport",
    sub_type: "sightseeing_train",
    title_zh: "SKY HOP BUS 京都",
    title_ja: "SKY HOP BUS 京都",
    romaji: "SKY HOP BUS Kyoto",
    summary_zh: "**京都市内 2 階建てオープントップ観光バス**、京都駅出発で清水寺・八坂神社・銀閣寺・嵐山等の主要観光地を巡回。1 日券 ¥3,500、英語ガイド付。",
    content_md: "- 路線:京都駅→清水寺→八坂神社→銀閣寺→金閣寺→嵐山(各 1 時間ループ)\n- 料金:1 日券 ¥3,500・2 日券 ¥6,000\n- 出発:京都駅(烏丸口バスターミナル)\n- 多言語ガイド:英中韓\n- 観光客向け、初回京都に最適",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://skyhopbus.com/kyoto/" },
    tags: ["sky_hop_bus", "open_top", "english_guide", "1_day_pass"],
    source: "manual",
  },
  {
    slug: "kyoto-city-sightseeing-bus",
    category: "transport",
    sub_type: "sightseeing_train",
    title_zh: "京都市定期観光バス",
    title_ja: "京都市定期観光バス",
    romaji: "Kyoto City Sightseeing Bus",
    summary_zh: "**京都市交通局運営の定期観光バス**、半日・1 日コース複数。¥3,000-7,000、ガイド付きで主要観光地を効率良く回る。",
    content_md: "- 主要コース:京都半日(¥3,500)・京都 1 日(¥7,000)・嵐山+大原コース等\n- 出発:京都駅烏丸口\n- ガイド:日本語(英語コースもあり)\n- 予約:京阪バス公式・JTB 等\n- 観光客向け、効率重視旅行に最適",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["sightseeing_bus", "guided_tour", "half_full_day"],
    source: "manual",
  },
  {
    slug: "kyoto-keihan-premium-car",
    category: "transport",
    sub_type: "limited_express_private",
    title_zh: "京阪電車 プレミアムカー",
    title_ja: "京阪電車 プレミアムカー",
    romaji: "Keihan Premium Car",
    summary_zh: "**京阪電車特急の指定座席 1 両**、追加料金 ¥500-900 で確実な座席 + 広いリクライニング。京都(祇園四条等)↔大阪(淀屋橋)の朝夕混雑時に有用。",
    content_md: "- 編成:特急 8 両中 1 両がプレミアムカー\n- 追加料金:¥500-900(区間別)\n- 設備:広いリクライニング・電源・WiFi・荷物棚\n- 予約:駅自動券売機・公式アプリ\n- 観光客の混雑時間帯利用におすすめ",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.012,
    lon: 135.772,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["keihan_premium", "reserved_seat", "kyoto_osaka"],
    source: "manual",
  },
  {
    slug: "kyoto-access-arashiyama",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "嵐山 アクセス完全ガイド",
    title_ja: "嵐山 アクセスガイド",
    romaji: "Arashiyama Access Guide",
    summary_zh: "**嵐山への 4 ルート完全比較**:JR嵯峨野線・嵐電・阪急嵐山線・市バス。最速は JR(京都駅 → 嵯峨嵐山 17 分・¥240)、最景色良いのは嵐電(四条大宮 → 嵐山 22 分・¥250)。",
    content_md: "- JR(最速):京都駅→嵯峨嵐山 17 分 ¥240\n- 嵐電(最景色):四条大宮→嵐山 22 分 ¥250(1 両編成路面電車)\n- 阪急:京都河原町→桂(乗換)→嵐山 25 分 ¥240\n- 市バス:京都駅→嵐山 60 分 ¥230(1 日券利用)\n- 推奨:朝早く JR で行き、夕方嵐電で戻る(往復で違うルート)\n- 紅葉期は 9:00 前到着推奨(混雑回避)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0145,
    lon: 135.6776,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["arashiyama_access", "4_routes_compared", "morning_recommended"],
    source: "manual",
  },
  {
    slug: "kyoto-access-kurama-kibune",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "鞍馬・貴船 アクセス",
    title_ja: "鞍馬・貴船 アクセス",
    romaji: "Kurama-Kibune Access",
    summary_zh: "**鞍馬・貴船は叡山電鉄一択**。出町柳から鞍馬 30 分・¥430、貴船口で下車してバス 5 分(¥170)。叡山電鉄 1 日券 ¥1,000 で全区間フリー、もみじのトンネル(11 月)も楽しめる。",
    content_md: "- ルート:京都駅→地下鉄→今出川→市バス→出町柳(または直接京阪)→叡山電鉄\n- 出町柳→鞍馬 30 分 ¥430\n- 出町柳→貴船口 27 分 ¥420 → 京都バス貴船 5 分 ¥170\n- 1 日券:¥1,000(叡山電鉄全線)\n- 観光モデル:鞍馬寺登山 + 貴船下山 + 川床(夏)\n- もみじトンネル(11 月):市原↔二ノ瀬間",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.119,
    lon: 135.762,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kurama_access", "kibune_access", "eizan_essential", "momiji_tunnel"],
    source: "manual",
  },
  {
    slug: "kyoto-access-ohara",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "大原 アクセス",
    title_ja: "大原 アクセス",
    romaji: "Ohara Access",
    summary_zh: "**大原は京都市中心部から京都バスのみ**。京都駅から 60 分・¥570、地下鉄国際会館 + 京都バスで 35 分・¥430(短縮ルート)。市バス 1 日券は対象外、別途運賃。",
    content_md: "- ルート 1(直行):京都駅→京都バス 17 系統→大原 60 分 ¥570\n- ルート 2(短縮):地下鉄烏丸線→国際会館→京都バス 19 系統→大原 35 分(地下鉄 ¥290 + バス ¥430)\n- 市バス 1 日券は不可・地下鉄 + バス 1 日券は地下鉄部分のみカバー\n- 観光モデル:三千院 + 寂光院 + 宝泉院 で半日\n- 春秋の観光ピーク時は座席埋まる、早朝出発推奨",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.115,
    lon: 135.834,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ohara_access", "kyoto_bus_17", "international_hall_route"],
    source: "manual",
  },
  {
    slug: "kyoto-access-fushimi-inari",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "伏見稲荷 アクセス",
    title_ja: "伏見稲荷 アクセス",
    romaji: "Fushimi Inari Access",
    summary_zh: "**JR と京阪 2 ルート、いずれも徒歩 1-5 分**。JR京都駅から JR奈良線で稲荷駅まで 5 分・¥150 が最速。京阪は祇園四条等から伏見稲荷駅まで 10-15 分・¥220。",
    content_md: "- JR(最速):京都駅→稲荷 5 分 ¥150・参道徒歩 1 分\n- 京阪(祇園からアクセス可):祇園四条→伏見稲荷 10 分 ¥220\n- 24 時間参拝可、早朝 6 時前推奨(人少ない + 朝霧)\n- 1 日券:京都観光 1 日券(JR 含む)+ 京阪 1 日券 のいずれか\n- 観光モデル:朝 6:00 千本鳥居→朝食→他観光地",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9676,
    lon: 135.7723,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["fushimi_inari_access", "jr_keihan", "early_morning_recommended"],
    source: "manual",
  },
  {
    slug: "kyoto-access-kitayama-kamigamo",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "北山・上賀茂神社 アクセス",
    title_ja: "北山・上賀茂神社 アクセス",
    romaji: "Kitayama-Kamigamo Access",
    summary_zh: "**北山方面は地下鉄烏丸線 + 市バス**。地下鉄北山駅徒歩(府立植物園)、上賀茂神社は地下鉄北大路 + 市バスで 15 分。Aman Kyoto は鷹峯エリアでバスやタクシー必要。",
    content_md: "- 北山駅(地下鉄烏丸線):京都駅→18 分 ¥290\n- 上賀茂神社:地下鉄北大路+市バス 4 系統 約 30 分\n- Aman Kyoto:鷹峯バス停か MK タクシー定額(京都駅から ¥3,000)\n- 観光モデル:北山(植物園)+ 上賀茂神社+大徳寺 で半日\n- 1 日券:地下鉄+市バス 1 日券 ¥1,100 で対応",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.05,
    lon: 135.751,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kitayama_access", "kamigamo_jinja", "subway_bus_combo"],
    source: "manual",
  },
  {
    slug: "kyoto-access-miyama",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "美山 アクセス",
    title_ja: "美山 アクセス",
    romaji: "Miyama Access",
    summary_zh: "**美山かやぶきの里は京都市から車推奨**。公共交通は JR + 南丹市営バスで 90 分以上、不便。レンタカーまたは MK タクシー定額 ¥30,000(片道)が現実的。",
    content_md: "- 公共交通:JR京都駅→園部(山陰線)→市営バス→美山 約 2 時間\n- 自動車:京都市内→美山 約 90 分(京都縦貫道経由)\n- レンタカー推奨:京都駅周辺で借りる\n- MK タクシー定額:京都市内→美山 ¥30,000-35,000(片道)\n- バスツアー:京都市発の美山日帰りツアーも複数あり",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: "南丹市",
    municipality_ja: "南丹市",
    lg_code: "26213",
    area_types: ["rural"],
    lat: 35.302,
    lon: 135.594,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["miyama_access", "rental_car_recommended", "remote_area"],
    source: "manual",
  },
  {
    slug: "kyoto-access-tango",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "丹後 アクセス",
    title_ja: "丹後(京丹後)アクセス",
    romaji: "Tango Access",
    summary_zh: "**京丹後・丹後半島は JR + 京都丹後鉄道で 2.5-3 時間**。京都駅→特急きのさき→福知山(乗換)→京都丹後鉄道→西舞鶴・天橋立・京丹後・峰山。",
    content_md: "- 京都→天橋立 約 2.5 時間(¥4,800)\n- 京都→京丹後峰山 約 3 時間\n- 特急きのさき:京都駅→福知山 90 分\n- 京都丹後鉄道:福知山→西舞鶴・天橋立・峰山\n- レンタカー:京都市内 or 福知山 or 天橋立で借り\n- 観光モデル:1-2 泊で天橋立+伊根+京丹後+夕日浦温泉",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京丹後市",
    lg_code: "26212",
    area_types: ["rural"],
    lat: 35.6175,
    lon: 135.0625,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["tango_access", "kinosaki_express", "kyoto_tango_railway"],
    source: "manual",
  },
  {
    slug: "kyoto-access-amanohashidate",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "天橋立 アクセス",
    title_ja: "天橋立 アクセス",
    romaji: "Amanohashidate Access",
    summary_zh: "**京都市内から天橋立まで 2.5 時間**、JR特急きのさき + 京都丹後鉄道乗換。日本三景の一つで、伊根の舟屋(車 30 分)と組合せて 1-2 泊。",
    content_md: "- ルート:京都駅→JR特急きのさき→福知山→京都丹後鉄道→天橋立\n- 所要時間:約 2.5 時間(¥4,800)\n- 1 日往復:朝出発 + 夕方戻りで日帰り可能(滞在 4-5 時間)\n- 推奨 1-2 泊:文珠荘等の温泉旅館 + 伊根 + 京丹後\n- 天橋立観光:松林散策 + ロープウェイ展望台 + 笠松公園",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "宮津市",
    lg_code: "26205",
    area_types: ["coastal", "rural"],
    lat: 35.5563,
    lon: 135.193,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["amanohashidate_access", "japan_three_views", "2_5_hours"],
    source: "manual",
  },
  {
    slug: "kyoto-access-yase-hieizan",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "八瀬・比叡山 アクセス",
    title_ja: "八瀬・比叡山 アクセス",
    romaji: "Yase-Hieizan Access",
    summary_zh: "**八瀬比叡山口へは叡山電鉄**、出町柳→八瀬比叡山口 14 分・¥270。比叡山頂は八瀬からケーブル + ロープウェイ(¥2,500 往復)。京都市内から比叡山延暦寺は約 1 時間。",
    content_md: "- 出町柳→八瀬比叡山口(叡山電鉄)14 分 ¥270\n- 八瀬→比叡山頂:ケーブル比叡 + ロープ比叡 ¥2,500 往復\n- 比叡山延暦寺:山頂からシャトルバス\n- 京都駅→延暦寺 約 1 時間 30 分\n- 1 日券:叡山電鉄 ¥1,000 + ケーブルロープウェイは別\n- 冬期(1-2 月)はケーブル運休あり",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.0782,
    lon: 135.8146,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yase_access", "hieizan_cable_rope", "enryakuji"],
    source: "manual",
  },
  {
    slug: "kyoto-access-takao-sanbi",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "高雄(三尾)アクセス",
    title_ja: "高雄三尾 アクセス",
    romaji: "Takao Sanbi Access",
    summary_zh: "**高雄(神護寺・西明寺・高山寺)は JR バスのみ**、京都駅から JR バス高雄線で約 50 分・¥530。紅葉期(11 月)は混雑、レンタカーや MK タクシー定額も検討。",
    content_md: "- JR バス高雄線:京都駅→高雄 約 50 分 ¥530\n- レンタカー:京都市内→高雄 約 40 分\n- MK タクシー定額:京都駅→高雄 ¥4,500(目安)\n- 紅葉期(11 月):バス混雑、早朝出発推奨\n- 観光モデル:神護寺(急坂参道+紅葉)+ 西明寺 + 高山寺(鳥獣戯画)で半日",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.069,
    lon: 135.668,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["takao_access", "jr_bus", "momiji_pilgrimage"],
    source: "manual",
  },
  {
    slug: "kyoto-hub-station",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "京都駅 hub",
    title_ja: "京都駅 hub",
    romaji: "Kyoto Station Hub",
    summary_zh: "**全京都の交通中枢**、新幹線・JR・近鉄・地下鉄烏丸線・市バスが集結。烏丸口(北)+ 八条口(南)で構造異なり、初訪日客は迷いやすい。コインロッカー 1,000+ 個・観光案内所(2F)・京都拉麺小路(10F)。",
    content_md: "- 出口:中央口(烏丸口・北側)/ 八条口(南側)\n- 路線:東海道新幹線・JR(京都線・嵯峨野線・奈良線・湖西線・近江)・近鉄京都線・地下鉄烏丸線・市バス\n- コインロッカー:1,000+ 個(¥400-800・八条口が空きやすい)\n- 観光案内所:2F 京都市総合観光案内所(英中韓対応)\n- 食:京都拉麺小路(10F)・伊勢丹デパ地下\n- 時刻表 + 路線図必携",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kyoto_station", "main_hub", "coin_lockers", "info_center"],
    source: "manual",
  },
  {
    slug: "kyoto-hub-shijo-kawaramachi",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "四条河原町 hub",
    title_ja: "四条河原町 hub",
    romaji: "Shijo Kawaramachi Hub",
    summary_zh: "**京都市中心部の繁華街兼交通 hub**、阪急京都河原町駅 + 京阪祇園四条駅(徒歩 4 分)+ 市バス多数系統が集中。錦市場・先斗町・八坂神社徒歩圏で観光起点に最適。",
    content_md: "- 阪急 京都河原町駅 + 京阪 祇園四条駅(徒歩 4 分の隣駅)\n- 市バス:四条河原町・河原町三条 等の主要 BS\n- 観光地:錦市場 (歩 5 分)・先斗町 (歩 3 分)・八坂神社 (歩 10 分)\n- 食:京町家カフェ多数・大丸京都・寺町京極商店街\n- コインロッカー:阪急 + 京阪駅構内\n- 京都最も賑やかなエリア、夜の散策も",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0033,
    lon: 135.7689,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shijo_kawaramachi", "hankyu_keihan", "downtown_hub"],
    source: "manual",
  },
  {
    slug: "kyoto-hub-demachiyanagi",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "出町柳 hub",
    title_ja: "出町柳 hub",
    romaji: "Demachiyanagi Hub",
    summary_zh: "**京都北部観光起点**、京阪 + 叡山電鉄の終着駅。出町柳から鞍馬・貴船・八瀬比叡山口へのアクセス起点、京都北部で最も使う乗換 hub。",
    content_md: "- 路線:京阪本線 終点 + 叡山電鉄 起点\n- 出町柳から鞍馬 30 分・貴船口 27 分・八瀬比叡山口 14 分\n- 京都市バス:出町柳駅前 BS(京都駅から市バス 17 系統で 30 分)\n- 周辺:鴨川出町・下鴨神社(歩 12 分)・京都大学\n- 食:出町ふたば(豆餅老舗)・出町商店街\n- 観光モデル:朝出町柳→鞍馬→貴船→出町柳戻り",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0297,
    lon: 135.7715,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["demachiyanagi", "keihan_eizan", "northern_kyoto_hub"],
    source: "manual",
  },
  {
    slug: "kyoto-hub-saiin",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "西院 hub",
    title_ja: "西院 hub",
    romaji: "Saiin Hub",
    summary_zh: "**阪急 + 嵐電の乗換 hub**、四条大宮(嵐電起点)へ徒歩 5 分。京都西部観光(嵐山)の起点として、阪急で大阪から到着 + 嵐電で嵐山アクセスのルートに使う。",
    content_md: "- 阪急 京都本線 西院駅 + 嵐電 西院駅(徒歩 1 分・別駅)\n- 阪急→嵐電→嵐山 のルート起点\n- 大阪梅田から京都・嵐山アクセスの最効率\n- 周辺:商店街 + 食事処\n- 注:阪急の西院は「さいいん」、嵐電の西院は「さい」と発音違う",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0023,
    lon: 135.7393,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["saiin", "hankyu_randen_transfer", "western_kyoto"],
    source: "manual",
  },
  {
    slug: "kyoto-hub-arashiyama-station",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "嵯峨嵐山駅 hub",
    title_ja: "嵯峨嵐山駅 hub",
    romaji: "Saga-Arashiyama Station Hub",
    summary_zh: "**嵐山観光起点**、JR嵯峨野線終着 + 嵯峨野トロッコ起点。嵐電の嵐山駅(別位置・徒歩 12 分)とは別駅、観光客が混乱しがち。",
    content_md: "- JR嵯峨嵐山駅 + 嵯峨野トロッコ嵯峨駅(隣接)\n- 嵐電「嵐山」駅とは別駅(徒歩 12 分)\n- 渡月橋まで徒歩 10 分・天龍寺徒歩 5 分・竹林徒歩 7 分\n- コインロッカー:駅構内\n- 注:JR + 嵐電を間違えると遠回り",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0188,
    lon: 135.6815,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["saga_arashiyama", "jr_torokko_hub", "arashiyama_access"],
    source: "manual",
  },
  {
    slug: "kyoto-mk-taxi-service",
    category: "transport",
    sub_type: "kyo_taxi_service",
    title_zh: "MK タクシー",
    title_ja: "MK タクシー",
    romaji: "MK Taxi",
    summary_zh: "**京都発祥(1960 年)の大手タクシー**、英語ドライバー指定可・観光ガイドサービス併設。空港送迎定額・観光チャーター(¥6,000/時)・通常メーター制。京都観光の鉄板。",
    content_md: "- 創業:1960 年(京都発祥)\n- サービス:通常タクシー・空港定額・観光チャーター(¥6,000/時)\n- 英語ドライバー:事前指定可(無料)\n- 観光ガイド:エキスパート観光ドライバー(歴史 + 文化解説)\n- アプリ:MK Taxi App(配車)\n- 海外旅行客に人気",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: [],
    external_urls: { official: "https://www.mktaxi-japan.com/" },
    tags: ["mk_taxi", "since_1960", "english_driver", "tourist_charter"],
    source: "manual",
  },
  {
    slug: "kyoto-yasaka-taxi",
    category: "transport",
    sub_type: "kyo_taxi_service",
    title_zh: "ヤサカタクシー",
    title_ja: "ヤサカタクシー",
    romaji: "Yasaka Taxi",
    summary_zh: "**京都の大手タクシー**、社章の「三葉のクローバー」が京都市内で見つかると幸運になる都市伝説あり。**四つ葉タクシー**(全 1,400 台中 4 台)を見つけたら超ラッキー。",
    content_md: "- 京都市内最大手タクシー会社の一つ\n- 社章:三葉のクローバー(緑色)\n- 四つ葉タクシー:全 1,400 台中 4 台限定、見つけたら幸運\n- 通常メーター制 + 観光チャーター\n- 写真撮影スポット:四つ葉が来たら撮影が伝統",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0036,
    lon: 135.7587,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: [],
    external_urls: { official: "https://www.yasaka.jp/" },
    tags: ["yasaka_taxi", "four_leaf_clover", "kyoto_legend"],
    source: "manual",
  },
  {
    slug: "kyoto-bicycle-rental",
    category: "transport",
    sub_type: "bicycle_rental",
    title_zh: "京都市内 レンタサイクル",
    title_ja: "京都市内 レンタサイクル",
    romaji: "Kyoto City Bicycle Rental",
    summary_zh: "**京都は自転車観光に最適**、平地が多く、寺社間の距離も自転車で 10-20 分。1 日 ¥1,000-1,500、京都駅周辺・嵐山・出町柳に多数のレンタル店。",
    content_md: "- 主要店舗:京都サイクリングツアープロジェクト・京都駅前レンタサイクル各種\n- 料金:¥1,000-1,500/日\n- 推奨ルート:京都駅→東寺→西本願寺→錦市場→八坂神社→平安神宮→銀閣寺→京都駅(15-20 km)\n- 注:寺社境内は乗車禁止、駐輪場必須\n- 嵐山:嵐山レンタサイクルあり",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bicycle_rental", "city_cycling", "1000_1500_yen"],
    source: "manual",
  },
  {
    slug: "kyoto-rental-car",
    category: "transport",
    sub_type: "rental_car_tips",
    title_zh: "京都 レンタカー",
    title_ja: "京都 レンタカー",
    romaji: "Kyoto Rental Car",
    summary_zh: "**京都市内観光はレンタカー不要**(駐車場高 + 渋滞)、ただし**美山・丹後・天橋立**等の郊外には必須。トヨタ・日産・タイムズカー等が京都駅前に集結。1 日 ¥6,000-12,000。",
    content_md: "- 京都市内:不推奨(駐車場 ¥1,000-2,000/時・渋滞)\n- 推奨対象:美山・丹後・天橋立・京丹後・伊根 等の郊外\n- 主要会社:トヨタ・日産・タイムズカー・ニッポンレンタカー\n- 料金:1 日 ¥6,000-12,000(車種 + シーズン)\n- 京都駅前/八条口に複数営業所\n- 注:返却時にガソリン満タン必須",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["rental_car", "rural_areas", "kyoto_station_pickup"],
    source: "manual",
  },
  {
    slug: "kyoto-walking-philosophy-path",
    category: "transport",
    sub_type: "walking_route",
    title_zh: "哲学の道",
    title_ja: "哲学の道",
    romaji: "Tetsugaku no Michi",
    summary_zh: "**銀閣寺 ↔ 南禅寺(若王子神社)を結ぶ約 2 km の散策路**、琵琶湖疏水沿い。哲学者西田幾多郎が思索しながら歩いたことから命名。**春桜・秋紅葉が圧巻**、京都散策路の代表。",
    content_md: "- 範囲:銀閣寺橋 → 若王子橋 約 2 km\n- 所要時間:30-45 分(寺社拝観込で 半日)\n- 主要観光:銀閣寺・法然院・大豊神社・永観堂・南禅寺\n- ベスト時期:4 月桜・11 月紅葉\n- アクセス起点:銀閣寺(市バス)or 南禅寺(地下鉄蹴上)\n- カフェ多数、休憩しやすい",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.024,
    lon: 135.794,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["philosophy_path", "kawabata_yasunari", "spring_autumn", "2km"],
    source: "manual",
  },
  {
    slug: "kyoto-walking-randen-line",
    category: "transport",
    sub_type: "walking_route",
    title_zh: "嵐電沿線歩き",
    title_ja: "嵐電沿線歩き",
    romaji: "Randen Line Walk",
    summary_zh: "**嵐電(京福嵐山本線)沿いの徒歩観光ルート**、四条大宮から嵐山まで途中下車しながら散策。太秦広隆寺・帷子ノ辻・車折神社・嵐山と各駅で寺社観光。",
    content_md: "- 範囲:四条大宮 → 嵐山(嵐電全線)\n- 主要下車:太秦広隆寺・車折神社・嵐山\n- 1 日券:¥800 で乗降自由\n- 各駅停車のローカル感が観光客に人気\n- 観光モデル:朝四条大宮→太秦→嵐山(夕方戻り)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.014,
    lon: 135.6776,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["randen_walking", "uzumasa", "kurumazaki", "1_day_pass"],
    source: "manual",
  },
  {
    slug: "kyoto-walking-nanakuchi",
    category: "transport",
    sub_type: "walking_route",
    title_zh: "京の七口巡り",
    title_ja: "京の七口巡り",
    romaji: "Kyo no Nanakuchi",
    summary_zh: "**平安京以来の京都への 7 つの古い入口**(東寺口・鳥羽口・粟田口・荒神口・鞍馬口・伏見口・丹波口)を巡る歴史散策。各口に石碑 + 解説、京都の街道史を体感。",
    content_md: "- 七口:東寺口・鳥羽口・粟田口・荒神口・鞍馬口・伏見口・丹波口\n- 起源:平安京以来の都市門\n- 各口に石碑 + 解説\n- 全部回ると 1 日 + 自転車 or レンタカー必要\n- 主に文化好きの専門観光、一般観光客は 2-3 か所のみ\n- 推奨:粟田口(蹴上)+ 伏見口 + 鞍馬口 を組合せ",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.011,
    lon: 135.78,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["seven_gates", "heian_kyoto", "history_walk", "specialist"],
    source: "manual",
  },
  {
    slug: "kyoto-walking-kamogawa",
    category: "transport",
    sub_type: "walking_route",
    title_zh: "鴨川河岸散策",
    title_ja: "鴨川河岸散策",
    romaji: "Kamogawa Riverside Walk",
    summary_zh: "**鴨川河岸の散策ルート**、出町柳の合流点から伏見まで約 8 km。**夏の納涼床**(5-9 月)+ **桜並木**(春)で京都の四季を体感。京都市民の日常散策路。",
    content_md: "- 範囲:出町柳合流点 → 伏見(鳥羽伏見)約 8 km\n- 主要観光:三条大橋・四条大橋・先斗町・木屋町・五条大橋\n- 春:桜並木(3 月下旬-4 月上旬)\n- 夏:鴨川納涼床(5-9 月)\n- 朝のジョギング・夕方の散歩・夜の納涼床と多面利用\n- ベスト区間:出町柳→四条 約 3 km",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.011,
    lon: 135.7715,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kamogawa_walk", "kawadoko_summer", "sakura_spring", "8km"],
    source: "manual",
  },
  {
    slug: "kyoto-walking-bamboo-grove",
    category: "transport",
    sub_type: "walking_route",
    title_zh: "嵯峨野竹林の小径",
    title_ja: "嵯峨野竹林の小径",
    romaji: "Sagano Bamboo Grove Path",
    summary_zh: "**嵯峨野の竹林を抜ける約 400 m の散策路**、京都を象徴する写真スポット。野宮神社↔大河内山荘の間。**早朝 6-8 時** の人少ない時間が最美、日中は混雑。",
    content_md: "- 範囲:野宮神社 → 大河内山荘 約 400 m\n- 所要時間:10-15 分(撮影込で 30 分)\n- ベスト時間:早朝 6-8 時(人少ない)\n- アクセス:JR嵯峨嵐山徒歩 7 分・嵐電嵐山徒歩 10 分\n- 撮影:京都観光の鉄板写真スポット、SNS で著名\n- 関連:近隣 天龍寺・常寂光寺・落柿舎",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0185,
    lon: 135.671,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bamboo_grove", "sagano", "early_morning_recommended", "iconic_photo"],
    source: "manual",
  },
  {
    slug: "kyoto-seasonal-aoi-matsuri-traffic",
    category: "transport",
    sub_type: "seasonal_transit",
    title_zh: "葵祭日 交通規制(5/15)",
    title_ja: "葵祭日 交通規制",
    romaji: "Aoi Matsuri Traffic Restriction",
    summary_zh: "**毎年 5 月 15 日の葵祭日**は京都御所 ↔ 下鴨神社 ↔ 上賀茂神社の行列ルート(約 8 km)で交通規制。市バス迂回・タクシー大幅遅延。沿道散策が逆に便利。",
    content_md: "- 期間:5 月 15 日 10:00-15:30\n- 規制ルート:京都御所→下鴨神社→上賀茂神社 約 8 km\n- 市バス:大幅迂回、所要時間 30-60 分増\n- タクシー:沿道進入不可、地下鉄推奨\n- 観光客向け:行列見物中は徒歩で十分、規制路は車両無\n- 雨天時翌日順延",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.025,
    lon: 135.768,
    season_start: "2000-05-15",
    season_end: "2000-05-15",
    event_start: "2000-05-15",
    event_end: "2000-05-15",
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["aoi_matsuri_traffic", "may_15", "bus_detour"],
    source: "manual",
  },
  {
    slug: "kyoto-seasonal-gion-matsuri-traffic",
    category: "transport",
    sub_type: "seasonal_transit",
    title_zh: "祇園祭山鉾巡行 交通規制(7/17・7/24)",
    title_ja: "祇園祭山鉾巡行 交通規制",
    romaji: "Gion Matsuri Traffic Restriction",
    summary_zh: "**祇園祭山鉾巡行(7 月 17 日前祭・7 月 24 日後祭)**は四条通・河原町通・御池通で大規模交通規制。市バス全面迂回、観覧客は早朝 8 時前到着 + 徒歩推奨。",
    content_md: "- 規制日:7 月 17 日(前祭・9:00-11:30)・7 月 24 日(後祭・9:30-12:00)\n- 規制ルート:四条烏丸→四条河原町→河原町御池→烏丸御池\n- 市バス:全面迂回 / 一部運休\n- 観覧推奨:四条河原町・御池通の観覧席(¥3,800-7,000)\n- 早朝 8:00 前到着推奨\n- 7 月 14-16 + 21-23 の宵山は夜歩きで賑やか",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0033,
    lon: 135.7689,
    season_start: "2000-07-15",
    season_end: "2000-07-25",
    event_start: "2000-07-17",
    event_end: "2000-07-24",
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["gion_matsuri_traffic", "july_17_24", "yamaboko_junko"],
    source: "manual",
  },
  {
    slug: "kyoto-seasonal-kurama-fire-festival",
    category: "transport",
    sub_type: "seasonal_transit",
    title_zh: "鞍馬の火祭 夜行バス(10/22)",
    title_ja: "鞍馬の火祭 夜行バス",
    romaji: "Kurama Fire Festival Night Bus",
    summary_zh: "**鞍馬の火祭(10 月 22 日)**は深夜まで催行のため、叡山電鉄が**24 時前後の臨時運行**を実施。臨時バスも追加。観覧客は事前予約 + 終電確認必須。",
    content_md: "- 開催日:10 月 22 日(時代祭と同日)\n- 火祭:鞍馬寺で夜祭・松明行列(20:00-22:30)\n- 叡山電鉄:臨時夜間運行(深夜 1 時頃まで)\n- 注意:鞍馬駅は祭観客で混雑、入場規制も\n- 京都市内戻りは 24 時前推奨\n- 観覧無料(沿道)・観覧席チケット販売もあり",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.119,
    lon: 135.762,
    season_start: "2000-10-22",
    season_end: "2000-10-22",
    event_start: "2000-10-22",
    event_end: "2000-10-22",
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["kurama_fire_festival", "october_22", "late_night_train"],
    source: "manual",
  },
  {
    slug: "kyoto-early-morning-fushimi",
    category: "transport",
    sub_type: "seasonal_transit",
    title_zh: "伏見稲荷 早朝アクセス",
    title_ja: "伏見稲荷 早朝アクセス",
    romaji: "Fushimi Inari Early Morning",
    summary_zh: "**伏見稲荷大社は 24 時間参拝可**、早朝 6 時前に到着すれば人少なく千本鳥居を独占。JR奈良線初電(京都発 5:00 頃)で 5:05 稲荷駅着、参拝開始可能。",
    content_md: "- 参拝時間:24 時間自由\n- 始発:JR奈良線(京都→稲荷)5:00 頃発・5:05 着\n- 京阪電鉄:5:30 頃から運行\n- ベスト時間:5:30-7:30(人少+朝霧)\n- 参拝後:朝食(京都駅周辺の早朝開業店)+ 他観光\n- 注:山頂まで往復 2 時間、早朝なら涼しく登れる",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9676,
    lon: 135.7723,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["early_morning", "fushimi_inari", "5am_start", "torii_alone"],
    source: "manual",
  },
  {
    slug: "kyoto-early-morning-temples",
    category: "transport",
    sub_type: "seasonal_transit",
    title_zh: "京都早朝 寺社アクセス",
    title_ja: "京都早朝 寺社アクセス",
    romaji: "Kyoto Early Morning Temple Access",
    summary_zh: "**永観堂・南禅寺・哲学の道は 7 時開門**、混雑前の早朝散策が最美。市バスは 5:30 頃から運行、地下鉄は 5:30-6:00 始発。早起きで京都の朝霧 + 静寂を独占。",
    content_md: "- 永観堂:7:00 開門(秋ライトアップ期間以外)\n- 南禅寺:6:00 三門・8:40 方丈庭園\n- 銀閣寺:8:30 開門\n- 清水寺:6:00 開門(年中)\n- 市バス:5:30 頃から運行\n- 地下鉄:5:30-6:00 始発\n- 早朝モデル:5:30 出発→ 7:00 永観堂→ 8:00 哲学の道→ 9:00 銀閣寺",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.011,
    lon: 135.79,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["early_morning_temples", "6am_7am_opening", "kyoto_dawn"],
    source: "manual",
  },
  {
    slug: "kyoto-accessibility-bus",
    category: "transport",
    sub_type: "accessibility_info",
    title_zh: "京都市バス バリアフリー",
    title_ja: "京都市バス バリアフリー情報",
    romaji: "Kyoto City Bus Accessibility",
    summary_zh: "**京都市バスはノンステップバス + 車椅子スロープ完備車両** が大半。乗降時にドライバーが補助、車椅子固定スペース 1-2 台分。**音声案内 + 多言語電子案内**も標準装備。",
    content_md: "- 全市バスの 90%+ がノンステップバス\n- 車椅子スロープ:全車装備、ドライバー補助\n- 車椅子固定:1-2 台分(中扉付近)\n- 視覚障害者:音声案内・点字運賃表\n- 多言語:英中韓電子案内(主要系統)\n- 助けが必要時はドライバーに声かけ",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0036,
    lon: 135.7587,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["accessibility", "non_step_bus", "wheelchair_ramp"],
    source: "manual",
  },
  {
    slug: "kyoto-accessibility-train",
    category: "transport",
    sub_type: "accessibility_info",
    title_zh: "京都鉄道 バリアフリー(JR + 嵐電 + 叡電)",
    title_ja: "京都鉄道 バリアフリー",
    romaji: "Kyoto Railway Accessibility",
    summary_zh: "**JR西日本・嵐電・叡電・地下鉄 等のバリアフリー対応**、主要駅にエレベーター・車椅子トイレ・点字・音声案内完備。**事前連絡で介助サービス**もあり。",
    content_md: "- JR西日本:全主要駅エレベーター・介助予約可(電話 / オンライン)\n- 嵐電:四条大宮 + 嵐山駅にスロープ・バリアフリートイレ\n- 叡電:出町柳・修学院・八瀬比叡山口にスロープ\n- 地下鉄:全駅エレベーター + 車椅子トイレ\n- 介助予約:JR は 1 日前、私鉄も 1-2 日前推奨\n- 注:小駅は介助なし時間帯あり",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["accessibility_train", "elevator_all_main", "assist_reservation"],
    source: "manual",
  },
  {
    slug: "kyoto-night-kibune-shuttle",
    category: "transport",
    sub_type: "night_transit",
    title_zh: "夜の貴船川床 送迎",
    title_ja: "貴船川床 送迎バス",
    romaji: "Kibune Kawadoko Night Shuttle",
    summary_zh: "**5-9 月の貴船川床料理**で食事した客向け、各旅館が叡山電鉄貴船口駅 + 川床店間のシャトル運行。最終バス 22:00 頃、終電(叡山電鉄)23:00 頃で京都市内戻り可。",
    content_md: "- 期間:5-9 月の川床営業日\n- ルート:叡山電鉄貴船口駅 ↔ 各川床店\n- 各旅館・川床店が個別運行(無料 or ¥200-300)\n- 最終便:22:00 頃\n- 叡山電鉄終電:23:00 頃(出町柳行)\n- 注:夏夜は涼しい、薄手羽織必須",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.1224,
    lon: 135.7625,
    season_start: "2000-05-01",
    season_end: "2000-09-30",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["kibune_shuttle", "summer_kawadoko", "night_transit"],
    source: "manual",
  },
  {
    slug: "kyoto-bus-100-tourist-loop",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "市バス 100 系統(観光急行)",
    title_ja: "市バス 100 系統(観光急行)",
    romaji: "City Bus 100 (Tourist Express)",
    summary_zh: "**京都駅→清水寺→平安神宮→銀閣寺の観光急行**、停車駅を絞った観光特化バス。¥230/回・1 日券対応。京都駅烏丸口から発車、東山観光ルートの定番。",
    content_md: "- ルート:京都駅烏丸口→博物館三十三間堂前→清水道→祇園→東山仁王門→銀閣寺道\n- 停車:観光地のみ(通常路線より早い)\n- 運行間隔:平日 10-15 分・休日 5-10 分\n- 1 日券対応\n- 観光客向け鉄板系統",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_100", "tourist_express", "higashiyama_loop"],
    source: "manual",
  },
  {
    slug: "kyoto-bus-101-kinkakuji",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "市バス 101 系統(金閣寺・北野)",
    title_ja: "市バス 101 系統",
    romaji: "City Bus 101 (Kinkakuji/Kitano)",
    summary_zh: "**京都駅→二条城→北野天満宮→金閣寺の観光急行**、京都北西部の主要観光地直結。¥230/回・1 日券対応。北野→金閣寺セット観光に最適。",
    content_md: "- ルート:京都駅→二条城前→北野天満宮前→金閣寺道\n- 停車:観光地のみ(急行)\n- 運行間隔:15-20 分\n- 1 日券対応\n- 観光モデル:京都駅→二条城→北野天満宮→金閣寺",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_101", "kinkakuji_route", "kitano_tenmangu"],
    source: "manual",
  },
  {
    slug: "kyoto-bus-102-kinkakuji-ginkakuji",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "市バス 102 系統(金閣寺↔銀閣寺)",
    title_ja: "市バス 102 系統",
    romaji: "City Bus 102 (Kinkakuji-Ginkakuji)",
    summary_zh: "**金閣寺↔銀閣寺直結の観光急行**、京都の二大金閣銀閣セット観光に。北大路・大徳寺方面経由で京都北部の主要観光地横断。",
    content_md: "- ルート:銀閣寺道→大徳寺前→北大路→金閣寺道\n- 停車:観光地のみ(急行)\n- 運行間隔:30 分間隔\n- 1 日券対応\n- 観光モデル:銀閣寺→哲学の道→大徳寺→金閣寺",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.027,
    lon: 135.74,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_102", "kinkakuji_ginkakuji", "north_kyoto"],
    source: "manual",
  },
  {
    slug: "kyoto-bus-5-ginkakuji",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "市バス 5 系統(京都駅→銀閣寺)",
    title_ja: "市バス 5 系統",
    romaji: "City Bus 5",
    summary_zh: "**京都駅→四条河原町→平安神宮→銀閣寺の主要系統**、京都市内中心部を縦貫。観光客 + 通勤客両用、運行間隔短く便利。",
    content_md: "- ルート:京都駅→烏丸→四条河原町→東山→平安神宮→銀閣寺道\n- 運行間隔:5-10 分(京都市バス最頻系統の一つ)\n- 1 日券対応\n- 観光モデル:京都駅→平安神宮→銀閣寺→哲学の道",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.77,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_5", "ginkakuji", "kawaramachi", "frequent"],
    source: "manual",
  },
  {
    slug: "kyoto-bus-28-arashiyama",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "市バス 28 系統(京都駅→嵐山)",
    title_ja: "市バス 28 系統",
    romaji: "City Bus 28",
    summary_zh: "**京都駅→嵐山天龍寺前の主要系統**、JR・嵐電に次ぐ嵐山アクセスの 3 番目選択肢。所要 50-60 分(渋滞時 90 分)、市バス 1 日券対応。",
    content_md: "- ルート:京都駅→四条大宮→西院→西京極→嵐山天龍寺前\n- 所要時間:50-60 分(JR は 17 分・嵐電は 22 分)\n- 1 日券対応\n- 注:渋滞時は所要時間倍増、JR/嵐電が早い\n- 利点:1 日券で完結 + 京都市内通過観光",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0145,
    lon: 135.6776,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_28", "arashiyama_bus", "60_min"],
    source: "manual",
  },
  {
    slug: "kyoto-bus-206-higashiyama",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "市バス 206 系統(東山ループ)",
    title_ja: "市バス 206 系統",
    romaji: "City Bus 206",
    summary_zh: "**京都駅→東山七条→祇園→千本通の主要環状系統**、東山観光地横断の鉄板。三十三間堂・清水寺・祇園・八坂神社 全部経由。",
    content_md: "- ルート:京都駅→博物館三十三間堂前→清水道→祇園→八坂神社→千本通→京都駅\n- 環状運行(時計回り)\n- 運行間隔:5-10 分\n- 1 日券対応\n- 観光客最頻使用系統の一つ",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9952,
    lon: 135.7745,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_206", "higashiyama_loop", "kiyomizu_gion"],
    source: "manual",
  },
  {
    slug: "kyoto-bus-17-ohara",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "京都バス 17 系統(京都駅→大原)",
    title_ja: "京都バス 17 系統",
    romaji: "Kyoto Bus 17",
    summary_zh: "**京都駅→大原直行バス**(京都バス・市バス1日券対象外)、所要 60 分・¥570。三千院・寂光院アクセスの主軸。冬期(雪)運休リスクあり、要事前確認。",
    content_md: "- ルート:京都駅→四条河原町→出町柳→大原\n- 所要時間:60 分\n- 料金:¥570(京都バス・市バス1日券対象外)\n- 運行間隔:30 分間隔\n- 別ルート:地下鉄国際会館 + 京都バス 19 系統(35 分)\n- 雪の日:冬期運休あり",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.115,
    lon: 135.834,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kyoto_bus_17", "ohara_direct", "60_min"],
    source: "manual",
  },
  {
    slug: "kyoto-bus-32-kibune-kurama",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "京都バス 32 系統(出町柳→貴船)",
    title_ja: "京都バス 32 系統",
    romaji: "Kyoto Bus 32",
    summary_zh: "**出町柳→貴船・鞍馬方面の補助バス**(叡山電鉄に並走)、雪の日や叡電運休時の代替交通。¥420、所要 30 分。",
    content_md: "- ルート:出町柳→八瀬→貴船口→鞍馬\n- 料金:¥420\n- 所要時間:30 分\n- 主に叡電補完・雪の日や運休時利用\n- 観光客は叡電(¥430)が時間正確で推奨",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.119,
    lon: 135.762,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kyoto_bus_32", "kibune_backup", "snow_day_alt"],
    source: "manual",
  },
  {
    slug: "kyoto-hieizan-cable",
    category: "transport",
    sub_type: "cable_car_lift",
    title_zh: "比叡山ケーブル(八瀬↔比叡山頂)",
    title_ja: "叡山ケーブル + ロープウェイ",
    romaji: "Hieizan Cable & Ropeway",
    summary_zh: "**八瀬→比叡山頂を結ぶケーブル + ロープウェイ**、所要 18 分・往復 ¥2,500。比叡山延暦寺(世界遺産)アクセスの主軸、京都最古の鉄道遺産の一つ(1925 年開業)。",
    content_md: "- ルート:八瀬比叡山口(叡山電鉄)→ケーブル八瀬→ケーブル比叡(山頂)→ロープウェイ比叡(山頂駅)\n- 所要時間:ケーブル 9 分 + ロープウェイ 3 分 = 約 12 分\n- 往復料金:¥2,500\n- 開業:1925 年(大正 14)\n- 冬期(1-2 月):雪 + 強風で運休日あり\n- 山頂から:延暦寺シャトルバスで根本中堂方面",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.0782,
    lon: 135.8146,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hieizan_cable", "since_1925", "enryakuji_access", "world_heritage"],
    source: "manual",
  },
  {
    slug: "kyoto-otokoyama-cable",
    category: "transport",
    sub_type: "cable_car_lift",
    title_zh: "石清水八幡宮 男山ケーブル",
    title_ja: "男山ケーブル",
    romaji: "Otokoyama Cable",
    summary_zh: "**石清水八幡宮(国宝・全国八幡宮総本宮)へのケーブル**、京阪八幡市駅 → 男山山上駅 約 3 分。**1926 年開業**の古いケーブル、八幡市の象徴。¥300/片道。",
    content_md: "- ルート:京阪八幡市駅→男山山上駅\n- 所要時間:3 分\n- 料金:¥300/片道\n- 開業:1926 年(大正 15)\n- アクセス:京阪 八幡市駅(京都中心から京阪 30 分)\n- 山上:石清水八幡宮(国宝・徒歩 5 分)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "八幡市",
    lg_code: "26210",
    area_types: ["urban_central"],
    lat: 34.879,
    lon: 135.7,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["otokoyama_cable", "iwashimizu_hachimangu", "since_1926"],
    source: "manual",
  },
  {
    slug: "kyoto-hozugawa-kudari",
    category: "transport",
    sub_type: "sightseeing_train",
    title_zh: "保津川下り(亀岡↔嵐山)",
    title_ja: "保津川下り",
    romaji: "Hozugawa Boat Ride",
    summary_zh: "**亀岡→嵐山を屋形船で 16 km・2 時間下る観光船**、¥4,500。保津川渓谷の急流 + 桜・新緑・紅葉が見事、嵯峨野トロッコ(亀岡行き)+ 保津川下り(嵐山戻り)で 1 日コース。",
    content_md: "- ルート:亀岡(乗船場)→保津峡→嵐山\n- 距離:16 km・所要 2 時間\n- 料金:¥4,500\n- 運航期間:3-12 月(冬期休業)\n- 観光モデル:嵐山→嵯峨野トロッコ→亀岡→保津川下り→嵐山(1 日)\n- 急流ポイント数か所、雨衣支給(船内防水)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "亀岡市",
    lg_code: "26206",
    area_types: ["rural"],
    lat: 35.012,
    lon: 135.547,
    season_start: "2000-03-01",
    season_end: "2000-12-29",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://www.hozugawakudari.jp/" },
    tags: ["hozugawa_boat", "kameoka_arashiyama", "2_hours", "trolley_combo"],
    source: "manual",
  },
  {
    slug: "kyoto-arashiyama-rickshaw",
    category: "transport",
    sub_type: "sightseeing_train",
    title_zh: "嵐山 人力車(えびす屋)",
    title_ja: "えびす屋 嵐山",
    romaji: "Arashiyama Rickshaw",
    summary_zh: "**嵐山観光地の人力車**、えびす屋等の専門会社が運営。1 区間 ¥4,000-9,000(2 名・距離別)、車夫が観光案内 + 写真撮影 + 隠れスポット案内。30 分-1 時間コース。",
    content_md: "- 主要会社:えびす屋・京都祇園えびす屋\n- 範囲:渡月橋・天龍寺・竹林の小径・常寂光寺方面\n- 料金:30 分 ¥4,000・60 分 ¥9,000(2 名)\n- 車夫案内:歴史 + 文化解説 + 隠れスポット\n- 撮影:車夫が写真撮影代行\n- 観光客向け、特に外国人 + カップル + 高齢者に人気",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0145,
    lon: 135.6776,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: [],
    external_urls: { official: "https://ebisuya.com/" },
    tags: ["rickshaw", "ebisuya", "arashiyama", "personal_guide"],
    source: "manual",
  },
  {
    slug: "kyoto-arashiyama-yakatabune",
    category: "transport",
    sub_type: "sightseeing_train",
    title_zh: "嵐山 屋形船・貸ボート",
    title_ja: "嵐山 屋形船",
    romaji: "Arashiyama Yakatabune",
    summary_zh: "**嵐山大堰川の屋形船**、4-9 月運航。1 隻 ¥5,500-15,000(料理付プランあり)、3-6 名乗船。**夏夜の鵜飼い** も観賞可能(7-9 月)、京の夏の風物詩。",
    content_md: "- 場所:渡月橋下流大堰川\n- 期間:4-9 月\n- 料金:1 時間 ¥5,500-15,000(プラン別)\n- 鵜飼い:7-9 月の夜、追加料金\n- 貸ボート:¥1,400/30 分(自分で漕ぐ)\n- 観光モデル:夕方屋形船 + 京懐石(料理付プラン)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0145,
    lon: 135.6776,
    season_start: "2000-04-01",
    season_end: "2000-09-30",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["yakatabune", "arashiyama_river", "ukai_summer"],
    source: "manual",
  },
  {
    slug: "kyoto-icoca-card",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "ICOCA(JR西日本 IC 乗車券)",
    title_ja: "ICOCA",
    romaji: "ICOCA",
    summary_zh: "**JR西日本のIC乗車券**、京都全鉄道 + バス + 一部商店で使用可能。デポジット ¥500 + チャージ式、関東 Suica/Pasmo とも相互利用。**ICOCA & HARUKA**(¥3,200)で関空 → 京都直結 + 街中も使える。",
    content_md: "- 種類:ICOCA(¥500 デポジット + チャージ)\n- 使用範囲:JR・私鉄・地下鉄・バス・コンビニ・自販機 全国相互利用\n- 購入:JR西日本主要駅・関西空港\n- ICOCA & HARUKA:訪日客限定 ¥3,200(片道はるか + ICOCA)\n- 払戻:JR西日本駅で ¥220 手数料 + 残額返金\n- 観光客向け:大阪 + 京都 + 神戸の鉄道に最適",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["icoca", "ic_card", "jr_west", "haruka_combo"],
    source: "manual",
  },
  {
    slug: "kyoto-welcome-suica",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "Welcome Suica(訪日客向)",
    title_ja: "Welcome Suica",
    romaji: "Welcome Suica",
    summary_zh: "**訪日外国人観光客向けの IC カード**、デポジット不要、28 日間有効後使い切り。羽田・成田で配布、京都でも使用可能(全国相互利用)。",
    content_md: "- 配布:羽田・成田空港(訪日客限定)\n- デポジット:不要(発行手数料無し)\n- 有効期間:28 日間(その後使い切り)\n- 使用範囲:全国 IC 相互利用(京都の鉄道・バス含む)\n- 払戻不可(残額は使い切り)\n- 関西到着客は ICOCA がより便利",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["welcome_suica", "tourist_card", "no_deposit", "28_days"],
    source: "manual",
  },
  {
    slug: "kyoto-jr-pass",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "JR Pass(全国版)京都使用",
    title_ja: "JR Pass",
    romaji: "JR Pass",
    summary_zh: "**訪日外国人専用の JR 全国乗り放題パス**、7/14/21 日選択可。¥50,000-100,000、京都・東京・大阪間の新幹線(のぞみ除外)+ 在来線乗り放題。京都中心の旅でも東京・広島往復で元取り。",
    content_md: "- 種類:7 日 ¥50,000・14 日 ¥80,000・21 日 ¥100,000(2024 年改定後)\n- 対象:訪日外国人(短期滞在ビザ)\n- 範囲:JR 全線(在来線 + 新幹線・のぞみ/みずほ除く)\n- 京都発着のぞみ NG だが、ひかり/こだま は OK\n- 元取り:京都→東京 1 往復 + 広島 1 回で取れる\n- 注:2023.10 改定で値上げ + 制度変更",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://japanrailpass.net/" },
    tags: ["jr_pass", "tourist_only", "50000_yen", "shinkansen"],
    source: "manual",
  },
  {
    slug: "kyoto-kansai-wide-pass",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "JR 関西 Wide Area Pass",
    title_ja: "JR 関西 Wide Area Pass",
    romaji: "JR Kansai Wide Area Pass",
    summary_zh: "**JR西日本の関西広域 5 日券**、訪日外国人向け ¥12,000。京都 + 大阪 + 神戸 + 奈良 + 姫路 + 城崎温泉 + 鳥取 までカバー。新幹線(京都・新大阪間)も利用可能。",
    content_md: "- 期間:連続 5 日\n- 価格:¥12,000(訪日外国人限定)\n- 範囲:京都・大阪・神戸・奈良・姫路・関空・城崎温泉・鳥取・岡山\n- 新幹線:京都↔新大阪のみ\n- 元取り:京都↔姫路往復 ¥6,560 × 2 = ¥13,120\n- 関西多都市旅行者に最適、京都だけなら ICOCA で十分",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["jr_kansai_wide", "5_days", "tourist_only", "12000_yen"],
    source: "manual",
  },
  {
    slug: "kyoto-pitapa-card",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "PiTaPa(関西私鉄 IC)",
    title_ja: "PiTaPa",
    romaji: "PiTaPa",
    summary_zh: "**関西私鉄(京阪・阪急・近鉄・阪神・南海)系の IC カード**、後払い式。京都旅行で観光客が使うのは稀(ICOCA で十分)、地元住民向けの定期 + 利用カード。",
    content_md: "- 種類:後払い式(クレカ連携)・定期券機能あり\n- 主に関西在住者向け\n- 京都の私鉄で使用可だが、観光客は ICOCA が圧倒的に便利\n- 注:発行に審査あり、訪日客は ICOCA を選ぶべき",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["pitapa", "kansai_private_railways", "postpay", "resident_oriented"],
    source: "manual",
  },
  {
    slug: "kyoto-spring-arashiyama-traffic",
    category: "transport",
    sub_type: "seasonal_transit",
    title_zh: "桜時期 嵐山交通混雑回避",
    title_ja: "桜時期 嵐山アクセス対策",
    romaji: "Spring Arashiyama Traffic Tips",
    summary_zh: "**3 月下旬-4 月上旬の嵐山桜時期**は観光客集中で渋滞 + バス満員。早朝 7-9 時到着 + JR/嵐電利用 + 自転車推奨。市バスは 60-90 分かかる、JR(17 分)が圧倒的に有利。",
    content_md: "- 期間:3 月下旬-4 月初旬(桜)\n- 渋滞時:市バス 28 系統 60-90 分(平常 50 分)\n- 推奨:JR嵯峨野線(17 分)or 嵐電(22 分)\n- 早朝:7-9 時着で人少+撮影自由\n- 自転車:嵐山周辺レンタサイクル ¥1,000/日\n- 注:18 時以降は人混雑緩和、夜桜可",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0145,
    lon: 135.6776,
    season_start: "2000-03-25",
    season_end: "2000-04-15",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["spring_arashiyama", "cherry_blossom_traffic", "early_morning"],
    source: "manual",
  },
  {
    slug: "kyoto-autumn-higashiyama-traffic",
    category: "transport",
    sub_type: "seasonal_transit",
    title_zh: "紅葉時期 東山交通対策",
    title_ja: "紅葉時期 東山アクセス対策",
    romaji: "Autumn Higashiyama Traffic Tips",
    summary_zh: "**11 月中旬-12 月初旬の紅葉時期**は東山(清水寺・永観堂・南禅寺)で交通麻痺。早朝 7-9 時 + 徒歩 + 京阪電鉄推奨。市バス 100/206 系統は超混雑、立ち見も。",
    content_md: "- 期間:11 月中旬-12 月初旬\n- 混雑:市バス 100/206 立ち見・所要時間 1.5-2 倍\n- 推奨:京阪七条/祇園四条 + 徒歩\n- 早朝:7-9 時推奨(永観堂 7:00 開門)\n- 京阪 1 日券 ¥1,000 でバス回避\n- ライトアップ:夕方-夜の混雑も",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.005,
    lon: 135.78,
    season_start: "2000-11-15",
    season_end: "2000-12-05",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["autumn_higashiyama", "momiji_traffic", "early_morning_keihan"],
    source: "manual",
  },
  {
    slug: "kyoto-snow-ohara-kurama",
    category: "transport",
    sub_type: "seasonal_transit",
    title_zh: "雪の日 大原・鞍馬交通",
    title_ja: "雪の日 大原・鞍馬アクセス",
    romaji: "Snow Day Ohara-Kurama Access",
    summary_zh: "**1-2 月の雪の日**、京都北部(大原・鞍馬・貴船・美山)はバス運休 + 道路閉鎖リスク。当日朝に運行情報確認、レンタカーは雪用タイヤ必須。雪見観光は楽しいが事前調査必須。",
    content_md: "- 期間:1-2 月(年 5-10 日)\n- 運休リスク:京都バス 17 系統(大原)・叡山電鉄(鞍馬・貴船)・京都丹後鉄道\n- 運行情報:当日朝に各社 HP 確認\n- レンタカー:雪用タイヤ必須(京都駅周辺レンタカー店で確認)\n- 雪見モデル:銀閣寺・金閣寺・嵐山(市内は問題なし)、大原・鞍馬は要確認",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["mountain_satellite"],
    lat: 35.115,
    lon: 135.834,
    season_start: "2000-01-10",
    season_end: "2000-02-28",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["winter_snow", "ohara_kurama_risk", "service_disruption"],
    source: "manual",
  },
  {
    slug: "kyoto-summer-kawadoko-traffic",
    category: "transport",
    sub_type: "seasonal_transit",
    title_zh: "夏 鴨川納涼床アクセス",
    title_ja: "夏 鴨川納涼床アクセス",
    romaji: "Summer Kawadoko Traffic",
    summary_zh: "**5-9 月の鴨川納涼床期間**は先斗町・木屋町に観光客集中。地下鉄(京都市役所前・三条京阪)+ 徒歩推奨、駐車場は満杯前提でレンタカー不向き。",
    content_md: "- 期間:5-9 月(納涼床営業期間)\n- 推奨アクセス:京阪三条京阪 or 阪急京都河原町 + 徒歩\n- 駐車場:先斗町 + 木屋町は駐車場満杯、コインパーキング ¥800/時+\n- タクシー:夜 22 時以降の確保困難(納涼床帰り客)\n- 食事予約:1-2 か月前必須(老舗料亭)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0058,
    lon: 135.7715,
    season_start: "2000-05-01",
    season_end: "2000-09-30",
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["summer_kawadoko", "pontocho_access", "subway_walk"],
    source: "manual",
  },
  {
    slug: "kyoto-taxi-pricing",
    category: "transport",
    sub_type: "kyo_taxi_service",
    title_zh: "京都市内 タクシー価格相場",
    title_ja: "京都市内 タクシー価格",
    romaji: "Kyoto Taxi Pricing",
    summary_zh: "**京都市内タクシー初乗 ¥600(1.5 km)・以降 ¥80/350m**(2024 年改定後)。京都駅↔清水寺 約 ¥1,500・京都駅↔嵐山 約 ¥3,000。深夜 22 時以降 +20% 割増、観光ピーク時(桜紅葉)はつかまりにくい。",
    content_md: "- 初乗:¥600(1.5 km)\n- 以降:¥80/350m\n- 深夜割増(22-5 時):+20%\n- 主要 fare:京都駅→清水寺 ¥1,500・嵐山 ¥3,000・大原 ¥6,000・Aman Kyoto ¥3,000\n- 観光ピーク時:タクシー確保困難・電話配車推奨\n- 配車アプリ:GO・DiDi・S.Ride",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0036,
    lon: 135.7587,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["taxi_pricing", "fare_guide", "go_app"],
    source: "manual",
  },
  {
    slug: "kyoto-station-info-center",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "京都総合観光案内所「京なび」",
    title_ja: "京都総合観光案内所 京なび",
    romaji: "Kyoto Tourist Information Center Kyo-Nabi",
    summary_zh: "**京都駅 2F の総合観光案内所**、英中韓フランス語対応。地図 + 観光パンフレット + 1 日券販売 + 宿泊予約サポート。営業 8:30-19:00、京都到着初日に立ち寄るのが定番。",
    content_md: "- 場所:京都駅ビル 2F (中央改札出てすぐ)\n- 営業:8:30-19:00\n- 多言語:英中韓フランス語スタッフ\n- サービス:無料地図・1日券販売・観光ツアー予約・宿泊紹介\n- ATM・コインロッカー隣接\n- Wi-Fi 提供",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["tourist_info", "kyo_nabi", "multilingual", "kyoto_station"],
    source: "manual",
  },
  {
    slug: "kyoto-bus-info-center",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "京都市バス・地下鉄案内所",
    title_ja: "京都市バス・地下鉄案内所",
    romaji: "Kyoto City Bus & Subway Information",
    summary_zh: "**京都駅前・烏丸口の市バス案内所**、1 日券販売 + 路線案内 + バス時刻表配布。営業 7:30-19:30、市バス 1 日券は車内でも買えるが事前購入が並ばずスムーズ。",
    content_md: "- 場所:京都駅前烏丸口・北側\n- 営業:7:30-19:30\n- 主要販売:市バス1日券・地下鉄+バス1日券・回数券\n- 案内:多言語パンフレット・路線図無料\n- 注:朝の混雑時は車内購入が早い場合も",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.987,
    lon: 135.7589,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: null,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bus_info_center", "1_day_pass_purchase", "kyoto_station_north"],
    source: "manual",
  },
  {
    slug: "kyoto-coin-locker-strategy",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "京都駅 コインロッカー戦略",
    title_ja: "京都駅 コインロッカー戦略",
    romaji: "Kyoto Station Coin Locker Strategy",
    summary_zh: "**京都駅 1,000+ 個のコインロッカー**、桜紅葉時期は早朝 9 時には埋まる。**地下中央改札外** が最大規模、八条口側が空きやすい。¥400-800、サイズ別。荷物預けて身軽に観光が定番。",
    content_md: "- 規模:1,000+ 個(全国最大級)\n- 主要場所:地下中央改札外(最大)・八条口・新幹線改札内\n- 価格:¥400(小)・¥600(中)・¥800(大)\n- ピーク時:9-10 時に空き枯渇(桜紅葉)\n- 推奨:8:00 着 → 即ロッカー → 観光\n- 代替:ホテル一時預け・手ぶら観光サービス(ヤマト運輸)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["coin_locker", "kyoto_station", "1000_lockers", "early_arrival"],
    source: "manual",
  },
  {
    slug: "kyoto-bicycle-parking-rules",
    category: "transport",
    sub_type: "bicycle_rental",
    title_zh: "京都 自転車駐輪場ルール",
    title_ja: "京都 自転車駐輪場ルール",
    romaji: "Kyoto Bicycle Parking Rules",
    summary_zh: "**京都市内の自転車駐輪は登録制 + 有料駐輪場使用**、放置自転車は撤去 + 撤去料 ¥2,300。寺社境内は乗車禁止 + 駐輪指定場所利用。市営駐輪場は ¥150/日、コインパーキング ¥200-500。",
    content_md: "- ルール:歩道放置禁止・市営駐輪場 ¥150/日\n- 撤去料:¥2,300(放置の場合)\n- 寺社境内:乗車禁止・指定駐輪場利用\n- 主要駐輪場:京都駅周辺・四条河原町・銀閣寺・嵐山\n- レンタル時:店舗から駐輪マップ + ロック貸与\n- 観光客:寺社観光時は降りて押し歩き",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0036,
    lon: 135.7587,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["bicycle_parking", "rules", "city_parking_lots"],
    source: "manual",
  },
  {
    slug: "kyoto-keihan-keishin-line",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "京阪京津線(三条京阪→浜大津)",
    title_ja: "京阪京津線",
    romaji: "Keihan Keishin Line",
    summary_zh: "**京阪電車の京都↔大津 直通線**、地下鉄東西線と相互運転。三条京阪→浜大津 25 分・¥430、琵琶湖アクセスの最便利ルート。**逢坂越えの急勾配**で著名。",
    content_md: "- 路線:三条京阪→御陵→山科→四宮→浜大津(琵琶湖)\n- 所要時間:三条京阪→浜大津 25 分・¥430\n- 地下鉄東西線と相互運転(直通)\n- 観光モデル:京都市内→琵琶湖湖畔(浜大津 + ミシガン船)\n- 注:逢坂越え急勾配を 40‰(40 パーミル)で走る",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 35.0098,
    lon: 135.78,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["keihan_keishin", "biwa_lake_access", "subway_through"],
    source: "manual",
  },
  {
    slug: "kyoto-kintetsu-kyoto-line",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "近鉄京都線(京都→奈良)",
    title_ja: "近鉄京都線",
    romaji: "Kintetsu Kyoto Line",
    summary_zh: "**近鉄電車の京都↔奈良直通**、京都駅から近鉄奈良 46 分・¥760。**特急** で 35 分・¥1,290。JR奈良線と並ぶ奈良アクセス、近鉄は奈良駅(東大寺至近)、JR は奈良駅(中心部やや離れる)が違い。",
    content_md: "- 路線:京都→竹田→大久保→新田辺→大和西大寺→近鉄奈良\n- 所要時間:急行 46 分・特急 35 分\n- 料金:¥760(急行)・¥1,290(特急)\n- 京都駅:JR京都駅とは別の近鉄改札(地下)\n- 観光モデル:京都→近鉄奈良→東大寺・春日大社\n- 注:JR奈良駅と近鉄奈良駅は徒歩 15 分の別駅",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kintetsu", "nara_access", "tokaido_kyoto"],
    source: "manual",
  },
  {
    slug: "kyoto-jr-biwako-line",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "JR 琵琶湖線(京都→大津・米原)",
    title_ja: "JR 琵琶湖線",
    romaji: "JR Biwako Line",
    summary_zh: "**京都→大津→草津→米原を結ぶ JR 路線**、琵琶湖湖南観光のアクセス。京都→大津 9 分・¥200、京都→米原 50 分・¥1,170。新幹線 米原 乗換でも便利。",
    content_md: "- 路線:京都→山科→大津→草津→米原\n- 所要時間:京都→大津 9 分・米原 50 分\n- 主要観光地:大津(琵琶湖湖畔)・草津(草津宿)・近江八幡(滋賀)\n- 新幹線米原乗換:北陸方面へのもう一つのルート\n- 1 日券:JR 京都・大阪 1 日券で対応",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jr_biwako_line", "lake_biwa_south", "maibara_transfer"],
    source: "manual",
  },
  {
    slug: "kyoto-jr-kosei-line",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "JR 湖西線(京都→近江舞子・敦賀)",
    title_ja: "JR 湖西線",
    romaji: "JR Kosei Line",
    summary_zh: "**京都→琵琶湖西岸→敦賀を結ぶ JR 路線**、琵琶湖湖西観光 + 北陸接続。京都→近江舞子 30 分・¥770、京都→敦賀 80 分・¥2,640(特急)。",
    content_md: "- 路線:京都→比叡山坂本→堅田→近江舞子→敦賀\n- 所要時間:京都→近江舞子 30 分・敦賀 80 分(特急)\n- 主要観光地:比叡山坂本(延暦寺西側)・近江舞子(湖水浴)\n- 北陸新幹線敦賀延伸後:湖西線 + 敦賀乗換 が金沢方面アクセス\n- 観光モデル:京都→比叡山坂本→延暦寺(裏比叡)",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jr_kosei_line", "lake_biwa_west", "tsuruga_hokuriku"],
    source: "manual",
  },
  {
    slug: "kyoto-jr-sanin-fukuchiyama",
    category: "transport",
    sub_type: "kyo_railway_company",
    title_zh: "JR 山陰本線(京都→園部・福知山)",
    title_ja: "JR 山陰本線",
    romaji: "JR Sanin Line",
    summary_zh: "**京都→嵯峨嵐山→亀岡→園部→福知山の JR 路線**、嵯峨野線と一体運用。京都→園部 35 分・福知山 90 分(特急きのさき)。京都北部観光(美山・丹後)アクセスの主軸。",
    content_md: "- 路線:京都→嵯峨嵐山→亀岡→園部→福知山\n- 所要時間:京都→園部 35 分・福知山 90 分(特急きのさき)\n- 嵯峨野線と一体運用(京都→嵯峨嵐山が嵯峨野線扱)\n- 主要観光地:嵐山・嵯峨野・亀岡(保津川下り)・福知山城\n- 北部接続:福知山で京都丹後鉄道乗換 → 天橋立・京丹後",
    region: "kansai",
    prefecture_ja: "京都府",
    gun_ja: null,
    municipality_ja: "京都市",
    lg_code: "26100",
    area_types: ["urban_central"],
    lat: 34.9858,
    lon: 135.7588,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jr_sanin", "fukuchiyama_express", "tango_connection"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[kyoto-transport] 尚無條目");
    return;
  }
  console.log(`[kyoto-transport] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(24)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch, { onConflict: "slug" });
    if (error) {
      console.error("[kyoto-transport] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[kyoto-transport] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[kyoto-transport] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
