// Seed 徳島県 住 R1(20 筆 / Sprint 1.3 / 第十六卷)
// 東部 5 / 西部 4 / 吉野川 2 / 南部 5 / その他 4 = 20
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  {
    slug: "clement-tokushima-1996",
    category: "lodging", sub_type: "tokushima_tobu_lodging",
    title_zh: "JR ホテルクレメント徳島(徳島市寺島本町・1996 開業 29+ 年+ JR 西日本グループ・JR 徳島駅直結+ 13 階建+ 250 室・¥12,000-32,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "JR クレメント徳島", romaji: "JR Clement Tokushima",
    summary_zh: "**JR ホテルクレメント徳島は 1996 開業 29+ 年・JR 西日本・JR 徳島駅直結・13 階建・250 室**(徳島寺島)。¥12,000-32,000/泊。",
    content_md: "- 立地:**徳島市寺島本町**\n- 起源:**1996 開業 29+ 年**\n- 認定:**JR 西日本グループ + JR 徳島駅直結 + 250 室**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["accommodation_hotel"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["clement_tokushima_1996"], source: "manual",
  },
  {
    slug: "tokushima-station-business",
    category: "lodging", sub_type: "tokushima_tobu_lodging",
    title_zh: "徳島駅前ビジネスホテル群(徳島市寺島本町+ 元町・JR 徳島駅前+ ことでん徳島駅・東横イン+ アパ+ コンフォート+ 中堅ビジネス 15+ 軒・¥6,500-12,000/泊・出張+観光客代表)",
    title_ja: "徳島駅前ビジネス", romaji: "Tokushima Business",
    summary_zh: "**徳島駅前ビジネスホテル群は JR 徳島+ことでん徳島駅前・東横イン+アパ+コンフォート+中堅 15+ 軒**(徳島寺島+元町)。¥6,500-12,000/泊。",
    content_md: "- 立地:**徳島市寺島本町 + 元町**\n- 規模:**中堅ビジネスチェーン 15+ 軒**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["accommodation_hotel"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["tokushima_business"], source: "manual",
  },
  {
    slug: "naruto-kanko-hotel",
    category: "lodging", sub_type: "tokushima_tobu_lodging",
    title_zh: "鳴門観光ホテル+ 鳴門グランドホテル(鳴門市鳴門町+ 撫養・1965 鳴門観光開業 60+ 年+ R1 食 鳴門の渦+R1 育 大鳴門橋連動・150+ 室・オーシャンビュー+ 渦潮眺望・¥15,000-32,000/泊)",
    title_ja: "鳴門観光ホテル", romaji: "Naruto Kanko Hotel",
    summary_zh: "**鳴門観光ホテル+グランドは 1965 開業 60+ 年・R1 食 渦+R1 育 大鳴門橋連動・150+ 室・オーシャンビュー+渦潮眺望**(鳴門+撫養)。¥15,000-32,000/泊。",
    content_md: "- 立地:**鳴門市鳴門町 + 撫養**\n- 起源:**1965 鳴門観光開業 60+ 年**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202",
    area_types: ["accommodation_hotel", "beach_coast"], lat: 34.1722, lon: 134.6086,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["naruto_kanko_1965"], source: "manual",
  },
  {
    slug: "naruto-uzunoyado",
    category: "lodging", sub_type: "tokushima_tobu_lodging",
    title_zh: "鳴門ウチノ海観光ホテル+ 渦の宿(鳴門市瀬戸町・R1 育 鳴門の渦+大鳴門橋派生・「アオアヲナルトリゾート」 2014 リブランド+ オーシャンビュー全室+ 150 室・¥22,000-65,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "アオアヲナルト", romaji: "Aoawo Naruto",
    summary_zh: "**鳴門ウチノ海+「アオアヲナルトリゾート」は 2014 リブランド・R1 育 派生・オーシャンビュー全室+150 室**(鳴門瀬戸)。¥22,000-65,000/泊、海外代表。",
    content_md: "- 立地:**鳴門市瀬戸町**\n- 起源:**「アオアヲナルトリゾート」 2014 リブランド**\n- 関連:**R1 育 鳴門の渦 + 大鳴門橋派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202",
    area_types: ["accommodation_hotel", "beach_coast"], lat: 34.1722, lon: 134.6086,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["aoawo_naruto_2014"], source: "manual",
  },
  {
    slug: "ohtsuka-art-hotel",
    category: "lodging", sub_type: "tokushima_tobu_lodging",
    title_zh: "大塚国際美術館前ホテル(鳴門市鳴門町・R4 育 大塚国際美術館 1998 派生・「ル・グランドホテル鳴門」+ 「リゾートホテルモアナコースト」 美術館徒歩 5 分+ オーシャンビュー・¥18,000-45,000/泊+ 国際 SNS 海外アートファン代表)",
    title_ja: "大塚アート前ホテル", romaji: "Ohtsuka Art Hotel",
    summary_zh: "**大塚国際美術館前ホテルは R4 育 1998 派生・「ル・グランドホテル鳴門」+「モアナコースト」・美術館徒歩 5 分+オーシャンビュー**(鳴門)。¥18,000-45,000/泊、海外アート代表。",
    content_md: "- 立地:**鳴門市鳴門町**\n- 関連:**R4 育 大塚国際美術館 1998 派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202",
    area_types: ["accommodation_hotel"], lat: 34.1722, lon: 134.6086,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["ohtsuka_art_hotel"], source: "manual",
  },
  {
    slug: "iya-onsen-1900",
    category: "lodging", sub_type: "tokushima_seibu_lodging",
    title_zh: "祖谷温泉郷+「ホテル祖谷温泉」 1972(三好市西祖谷山村・古来から平家落人湯治場 850+ 年伝承+ 1972 ホテル祖谷温泉開業 53+ 年+ 全国 3 大秘湯候補・祖谷渓谷ケーブルカー宿泊者専用 220m 高低差・¥35,000-95,000/泊+ 国際 SNS 海外旅行者代表)",
    title_ja: "ホテル祖谷温泉", romaji: "Iya Onsen",
    summary_zh: "**祖谷温泉郷+「ホテル祖谷温泉」 1972 は古来から平家落人湯治場 850+ 年・1972 開業 53+ 年・全国 3 大秘湯候補・宿泊者専用ケーブル 220m**(三好西祖谷)。¥35,000-95,000/泊。",
    content_md: "- 立地:**三好市西祖谷山村**\n- 起源:**古来から平家落人湯治場 850+ 年伝承 + 1972 ホテル祖谷温泉開業 53+ 年**\n- 認定:**全国 3 大秘湯候補 + 祖谷渓谷ケーブルカー宿泊者専用 220m 高低差**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208",
    area_types: ["onsen_natural", "accommodation_ryokan"], lat: 33.8728, lon: 133.8019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["iya_onsen_1972", "national_top3_secret"], source: "manual",
  },
  {
    slug: "oboke-koboke-ryokan",
    category: "lodging", sub_type: "tokushima_seibu_lodging",
    title_zh: "大歩危・小歩危ペンション+ 旅館(三好市山城+ 大歩危・R1 食 祖谷そば+R1 育 大歩危派生・1900 年代以降観光ペンション郷+ ラフティング基地+ JR 大歩危駅徒歩 5 分・¥9,500-22,000/泊)",
    title_ja: "大歩危ペンション", romaji: "Ōboke Pension",
    summary_zh: "**大歩危・小歩危ペンション+旅館は R1 食+R1 育 派生・1900 年代以降観光ペンション郷・ラフティング基地・JR 大歩危徒歩 5 分**(三好山城+大歩危)。¥9,500-22,000/泊。",
    content_md: "- 立地:**三好市山城町 + 大歩危**\n- 関連:**R1 食 祖谷そば + R1 育 大歩危派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208",
    area_types: ["accommodation_ryokan", "nature_park"], lat: 33.8728, lon: 133.8019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["oboke_pension"], source: "manual",
  },
  {
    slug: "kazura-bashi-onsen",
    category: "lodging", sub_type: "tokushima_seibu_lodging",
    title_zh: "祖谷かずら橋温泉+ 善徳温泉(三好市西祖谷山村・R1 育 かずら橋 1100+ 年派生・「祖谷美人」+「ホテルかずら橋」 老舗 6+ 軒+ 渓谷ビュー+ 平家落人伝統湯治・¥22,000-65,000/泊)",
    title_ja: "かずら橋温泉", romaji: "Kazura-bashi Onsen",
    summary_zh: "**祖谷かずら橋温泉+善徳温泉は R1 育 かずら橋 1100+ 年派生・「祖谷美人」+「ホテルかずら橋」 6+ 軒・渓谷ビュー+平家落人湯治**(三好西祖谷)。¥22,000-65,000/泊。",
    content_md: "- 立地:**三好市西祖谷山村**\n- 関連:**R1 育 かずら橋 1100+ 年派生**\n- 規模:**老舗 6+ 軒**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208",
    area_types: ["onsen_natural", "accommodation_ryokan"], lat: 33.8728, lon: 133.8019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["kazura_onsen"], source: "manual",
  },
  {
    slug: "mima-tsurugi-business",
    category: "lodging", sub_type: "tokushima_seibu_lodging",
    title_zh: "美馬+ つるぎ駅前ビジネス(美馬市美馬+ つるぎ町・R1 食 半田そうめん+R3 食 司菊酒造 1894 派生・「みまの里」+「貞光の里」 中堅ホテル 5+ 軒+ JR 徳島線美馬駅徒歩 10 分・¥6,500-12,000/泊)",
    title_ja: "美馬つるぎビジネス", romaji: "Mima Tsurugi",
    summary_zh: "**美馬+つるぎ駅前ビジネスは R1 食 半田そうめん+R1 食 司菊 1894 派生・「みまの里」+「貞光の里」中堅 5+ 軒・JR 徳島線美馬徒歩 10 分**(美馬+つるぎ)。¥6,500-12,000/泊。",
    content_md: "- 立地:**美馬市美馬町 + つるぎ町**\n- 関連:**R1 食 半田そうめん + 司菊酒造 1894 派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "美馬市", lg_code: "36207",
    area_types: ["accommodation_hotel"], lat: 34.0500, lon: 134.0167,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["mima_tsurugi"], source: "manual",
  },
  {
    slug: "awa-ikeda-station",
    category: "lodging", sub_type: "tokushima_yoshinogawa_lodging",
    title_zh: "阿波池田駅前ホテル+ 三好駅前(三好市池田町+ 全市・JR 阿波池田駅+ JR 土讃線分岐+ 「サンリバー大歩危」+「祖谷観光ホテル」 中堅 8+ 軒+ R1 食 祖谷そば+R1 育 大歩危連動・¥7,500-15,000/泊)",
    title_ja: "阿波池田駅前", romaji: "Awa Ikeda",
    summary_zh: "**阿波池田駅前ホテル+三好駅前は JR 阿波池田+土讃線分岐・「サンリバー大歩危」+「祖谷観光」 8+ 軒・R1 食 祖谷+R1 育 大歩危連動**(三好池田)。¥7,500-15,000/泊。",
    content_md: "- 立地:**三好市池田町**\n- 関連:**R1 食 祖谷そば + R1 育 大歩危連動**\n- 規模:**中堅ホテル 8+ 軒**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208",
    area_types: ["accommodation_hotel"], lat: 33.8728, lon: 133.8019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["awa_ikeda_station"], source: "manual",
  },
  {
    slug: "yoshinogawa-awa-hotels",
    category: "lodging", sub_type: "tokushima_yoshinogawa_lodging",
    title_zh: "吉野川市+ 阿波市ホテル(吉野川市鴨島+ 阿波市・R1 食 阿波和三盆糖+R1 衣 阿波藍 1585 派生・「ホテル阿波池田」+「サンライズインアワ」 中堅 5+ 軒+ 吉野川中流域・¥6,500-12,000/泊)",
    title_ja: "吉野川阿波ホテル", romaji: "Yoshinogawa Awa Hotel",
    summary_zh: "**吉野川市+阿波市ホテルは R1 食 和三盆+R1 衣 藍 1585 派生・「阿波池田」+「サンライズアワ」中堅 5+ 軒・吉野川中流域**(吉野川鴨島+阿波)。¥6,500-12,000/泊。",
    content_md: "- 立地:**吉野川市鴨島 + 阿波市**\n- 関連:**R1 食 阿波和三盆糖 + R1 衣 阿波藍 1585 派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "吉野川市", lg_code: "36205",
    area_types: ["accommodation_hotel"], lat: 34.0656, lon: 134.3556,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["yoshinogawa_awa"], source: "manual",
  },
  {
    slug: "anan-tachibana-hotel",
    category: "lodging", sub_type: "tokushima_nanbu_lodging",
    title_zh: "阿南橘湾ホテル+ オーシャンビュー(阿南市橘+ 椿・R1 食 阿南橘湾朝市+R1 衣 阿南 LED 派生・「ホテルニュー阿南」+「橘湾観光ホテル」 5+ 軒+ 太平洋オーシャンビュー+ 1900 年代以降漁業観光地・¥9,500-22,000/泊)",
    title_ja: "阿南橘湾ホテル", romaji: "Anan Tachibana Hotel",
    summary_zh: "**阿南橘湾ホテル+オーシャンビューは R1 食+R1 衣 LED 派生・「ニュー阿南」+「橘湾観光」 5+ 軒・太平洋オーシャンビュー**(阿南橘+椿)。¥9,500-22,000/泊。",
    content_md: "- 立地:**阿南市橘 + 椿**\n- 関連:**R1 食 阿南橘湾朝市 + R1 衣 阿南 LED 派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "阿南市", lg_code: "36204",
    area_types: ["accommodation_hotel", "beach_coast"], lat: 33.9217, lon: 134.6594,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["anan_tachibana_hotel"], source: "manual",
  },
  {
    slug: "kaibu-mugi-minshuku",
    category: "lodging", sub_type: "tokushima_nanbu_lodging",
    title_zh: "海部牟岐+ 海陽民宿+ 太平洋海岸宿(海部郡牟岐町+ 海陽町+ 美波・R1 食 ぼうぜの姿寿司+R1 衣 海部漁師袢纏派生・1900 年代以降漁師民宿 100+ 年+ 民宿 25+ 軒+ オーシャンビュー・¥9,500-18,000/泊)",
    title_ja: "海部漁師民宿", romaji: "Kaibu Minshuku",
    summary_zh: "**海部牟岐+海陽民宿+太平洋海岸宿は R1 食+R1 衣 派生・1900 年代以降民宿 100+ 年・民宿 25+ 軒+オーシャンビュー**(海部牟岐+海陽+美波)。¥9,500-18,000/泊。",
    content_md: "- 立地:**海部郡牟岐町 + 海陽町 + 美波町**\n- 関連:**R1 食 ぼうぜの姿寿司 + R1 衣 海部漁師袢纏派生**\n- 規模:**民宿 25+ 軒**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "海部郡", municipality_ja: "海陽町", lg_code: "36388",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 33.5333, lon: 134.3000,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kaibu_minshuku"], source: "manual",
  },
  {
    slug: "minami-hiwasa-onsen",
    category: "lodging", sub_type: "tokushima_nanbu_lodging",
    title_zh: "美波町日和佐温泉+ 「うみがめ温泉」(海部郡美波町日和佐・R3 楽 大浜海岸ウミガメ産卵地派生(国指定天然記念物 1972)+「日和佐うみがめ温泉」開業 1996 + 30+ 年・ウミガメ眺望温泉宿 4+ 軒+ JR 牟岐線日和佐駅徒歩 5 分・¥12,000-32,000/泊)",
    title_ja: "日和佐うみがめ温泉", romaji: "Hiwasa Umigame",
    summary_zh: "**美波町日和佐温泉+「うみがめ温泉」は大浜海岸ウミガメ産卵地国天記 1972 派生・1996 開業 30+ 年・ウミガメ眺望温泉宿 4+ 軒**(美波日和佐)。¥12,000-32,000/泊。",
    content_md: "- 立地:**海部郡美波町日和佐**\n- 起源:**「日和佐うみがめ温泉」 1996 開業 30+ 年**\n- 関連:**大浜海岸ウミガメ産卵地国指定天然記念物 1972**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "海部郡", municipality_ja: "美波町", lg_code: "36383",
    area_types: ["onsen_natural", "accommodation_ryokan"], lat: 33.7311, lon: 134.5306,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["hiwasa_umigame_1996"], source: "manual",
  },
  {
    slug: "naka-katsuura-bnb",
    category: "lodging", sub_type: "tokushima_nanbu_lodging",
    title_zh: "那賀+ 勝浦民宿+ 山中宿(那賀郡那賀町+ 勝浦郡勝浦町+ 上勝・R1 衣 阿波太布 1973+R1 衣 上勝ゼロウェイスト 2003 派生・1990 年代以降山中民泊 35+ 年+ 民宿 12+ 軒・¥7,500-18,000/泊・国際 SNS 海外サステナファン代表)",
    title_ja: "那賀勝浦民宿", romaji: "Naka Katsuura",
    summary_zh: "**那賀+勝浦民宿+山中宿は R1 衣 阿波太布 1973+R1 衣 上勝ゼロウェイスト 2003 派生・1990 年代以降山中民泊 35+ 年・民宿 12+ 軒**(那賀+勝浦+上勝)。¥7,500-18,000/泊。",
    content_md: "- 立地:**那賀郡那賀町 + 勝浦郡勝浦町 + 上勝町**\n- 関連:**R1 衣 阿波太布 1973 + 上勝ゼロウェイスト 2003 派生**\n- 規模:**民宿 12+ 軒**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "那賀郡", municipality_ja: "那賀町", lg_code: "36368",
    area_types: ["accommodation_ryokan", "nature_park"], lat: 33.9000, lon: 134.3000,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["naka_katsuura"], source: "manual",
  },
  {
    slug: "kamatsushima-hotel",
    category: "lodging", sub_type: "tokushima_nanbu_lodging",
    title_zh: "小松島駅前+ 阿南国道沿ホテル(小松島市+ 阿南市・JR 牟岐線小松島駅+ JR 阿南駅前+ R1 衣 阿南 LED 産業ビジネス派生・「ホテル AZ 徳島阿南店」+ 中堅 6+ 軒・¥6,500-12,000/泊+ 出張+観光客代表)",
    title_ja: "小松島阿南ホテル", romaji: "Komatsushima Anan",
    summary_zh: "**小松島駅前+阿南国道沿ホテルは JR 牟岐線小松島+阿南駅前・R1 衣 阿南 LED ビジネス派生・「ホテル AZ 徳島阿南店」+中堅 6+ 軒**(小松島+阿南)。¥6,500-12,000/泊。",
    content_md: "- 立地:**小松島市 + 阿南市**\n- 関連:**R1 衣 阿南 LED 産業ビジネス派生**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "小松島市", lg_code: "36203",
    area_types: ["accommodation_hotel"], lat: 34.0033, lon: 134.5856,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["komatsushima_anan_hotel"], source: "manual",
  },
  {
    slug: "kamiyama-creative-stay",
    category: "lodging", sub_type: "tokushima_tobu_lodging",
    title_zh: "神山町クリエイティブステイ+ サテライトオフィス民泊(名西郡神山町・R1 衣 神山クリエイティブ 2010 派生・1990 年代以降民泊+ クリエイター移住 35+ 年+ 古民家+ サテライトオフィス併設・「WEEK 神山」+「えんがわオフィス」・¥9,500-22,000/泊)",
    title_ja: "神山クリエイティブ宿", romaji: "Kamiyama Creative Stay",
    summary_zh: "**神山町クリエイティブステイ+サテライト民泊は R1 衣 2010 派生・1990 年代以降民泊+クリエイター移住 35+ 年・「WEEK 神山」+「えんがわオフィス」**(神山)。¥9,500-22,000/泊。",
    content_md: "- 立地:**名西郡神山町**\n- 関連:**R1 衣 神山クリエイティブ 2010 派生**\n- 起源:**1990 年代以降民泊 + クリエイター移住 35+ 年**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "名西郡", municipality_ja: "神山町", lg_code: "36341",
    area_types: ["accommodation_ryokan"], lat: 33.9486, lon: 134.3608,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kamiyama_creative_stay"], source: "manual",
  },
  {
    slug: "kamikatsu-zero-waste-hotel",
    category: "lodging", sub_type: "tokushima_nanbu_lodging",
    title_zh: "上勝町ゼロウェイストホテル「WHY」+ サステナビリティステイ(勝浦郡上勝町・R1 衣 上勝ゼロウェイスト 2003 派生・「HOTEL WHY」 2020 開業 5+ 年+ 国際初のゼロウェイストホテル候補・SDGs サステナ宿+ 国際 SNS 海外サステナファン代表・¥18,000-45,000/泊)",
    title_ja: "上勝 HOTEL WHY", romaji: "Kamikatsu WHY",
    summary_zh: "**上勝町ゼロウェイストホテル「WHY」は R1 衣 2003 派生・2020 開業 5+ 年・国際初のゼロウェイストホテル候補・SDGs サステナ宿**(上勝)。¥18,000-45,000/泊、海外代表。",
    content_md: "- 立地:**勝浦郡上勝町**\n- 関連:**R1 衣 上勝ゼロウェイスト 2003 派生**\n- 起源:**「HOTEL WHY」 2020 開業 5+ 年**\n- 認定:**国際初のゼロウェイストホテル候補**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: "勝浦郡", municipality_ja: "上勝町", lg_code: "36369",
    area_types: ["accommodation_hotel"], lat: 33.9000, lon: 134.4167,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["kamikatsu_why_2020"], source: "manual",
  },
  {
    slug: "naruto-bridge-memorial-hotel",
    category: "lodging", sub_type: "tokushima_tobu_lodging",
    title_zh: "鳴門大塚スポーツパーク前ホテル(鳴門市+ 板野郡・R1 衣 徳島ヴォルティス 1989 派生・大塚製薬本社前+ 鳴門大塚スポーツパーク隣接ホテル 5+ 軒・¥9,500-22,000/泊・スポーツファン+J リーグ観戦客代表)",
    title_ja: "鳴門大塚前ホテル", romaji: "Naruto Ohtsuka Hotel",
    summary_zh: "**鳴門大塚スポーツパーク前ホテルは R1 衣 ヴォルティス 1989 派生・大塚製薬本社前+鳴門大塚スポーツパーク隣接 5+ 軒**(鳴門+板野)。¥9,500-22,000/泊。",
    content_md: "- 立地:**鳴門市 + 板野郡**\n- 関連:**R1 衣 徳島ヴォルティス 1989 派生 + 大塚製薬本社前**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202",
    area_types: ["accommodation_hotel"], lat: 34.1722, lon: 134.6086,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["naruto_ohtsuka_hotel"], source: "manual",
  },
  {
    slug: "tokushima-awa-odori-hotel-aug",
    category: "lodging", sub_type: "tokushima_tobu_lodging",
    title_zh: "徳島阿波踊り 8 月限定+ 桟敷席ホテル(徳島市・R1 衣 阿波踊り装束 1981+R1 食 屋台食派生・8 月 12-15 日「阿波踊り」期間限定 全国観衆 100 万人来県・全市ホテル満員予約必至+ 民泊+ R1 住 クレメント徳島 1996 連動+ ¥18,000-65,000/泊(8 月限定))",
    title_ja: "阿波踊り限定ホテル", romaji: "Awa Odori Aug Hotel",
    summary_zh: "**徳島阿波踊り 8 月限定+桟敷席ホテルは R1 衣+R1 食 派生・8/12-15 期間限定 全国観衆 100 万人・全市満員予約必至**(徳島)。¥18,000-65,000/泊(8 月限定)。",
    content_md: "- 立地:**徳島市**\n- 関連:**R1 衣 阿波踊り装束 1981 + R1 食 阿波踊り屋台食派生**\n- 認定:**8 月 12-15 日全国観衆 100 万人来県 + 全市ホテル満員予約必至**",
    region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201",
    area_types: ["accommodation_hotel", "history_site_castle"], lat: 34.0658, lon: 134.5594,
    season_start: null, season_end: null, event_start: "2026-08-12T15:00:00+09:00", event_end: "2026-08-15T23:00:00+09:00",
    price_tier: 5, booking_window_days: 365, closed_days: [],
    external_urls: {}, tags: ["awa_odori_aug_hotel"], source: "manual",
  },
];

seedMain(rows, "tokushima-lodging-r1");
