// Seed 秋田県 衣 R1(18 筆 / Sprint 1.2)
//
// 樺細工 4 / 川連漆器 3 / なまはげ面 2 / 大館曲げわっぱ 2 / 銀線細工 2 /
// 百貨店 2 / 民芸 3 = 18

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: "fashion";
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "tohoku";
  prefecture_ja: "秋田県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // 樺細工 (4)
  {
    slug: "kakunodate-kabazaiku-overview",
    category: "fashion",
    sub_type: "akita_kakunodate_kabazaiku",
    title_zh: "角館樺細工(仙北市角館・経産省指定伝統的工芸品 1976+ 1781 角館藩士藤村彦六が学ぶ→ 244+ 年伝統+ 山桜樹皮の独特光沢+ 茶筒+小箱+小物入が代表+ 角館武家屋敷 R1 育 沿道工房集積)",
    title_ja: "樺細工",
    romaji: "Kabazaiku",
    summary_zh: "**角館樺細工は経産省指定伝統的工芸品 1976**(仙北市角館・**1781 角館藩士藤村彦六が学ぶ→ 244+ 年伝統**)。**山桜樹皮の独特光沢 + 茶筒+小箱+小物入が代表**、青森津軽塗 R1 衣 + 岩手南部鉄器 R1 衣 に並ぶ北東北伝統工芸 3 大、角館武家屋敷 R1 育 沿道工房集積。",
    content_md: "- 立地:**仙北市角館町**(JR 秋田新幹線 角館駅 徒歩 15 分)\n- 起源:**1781 角館藩士 藤村彦六が阿仁の杣山民から技法習得 → 244+ 年**\n- 認定:**経済産業大臣指定伝統的工芸品 1976**\n- 素材:**山桜樹皮**(独特光沢 + 経年で深い飴色化)\n- 主要品:**茶筒 + 小箱 + 小物入 + 文箱 + 印籠**\n- 並列:**青森津軽塗 1646 R1 衣(漆) + 岩手南部鉄器 17 世紀 R1 衣(鉄) + 秋田樺細工 1781 R1 衣(樹皮) = 北東北伝統工芸 3 大**\n- 価格:茶筒 ¥8,000-25,000 / 小物入 ¥4,500-15,000",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "仙北市",
    lg_code: "05215",
    area_types: ["craft_workshop"],
    lat: 39.5961,
    lon: 140.5594,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kabazaiku", "1976_designated", "1781_origin", "244_years", "yamazakura"],
    source: "manual",
  },
  {
    slug: "kakunodate-densho-kan",
    category: "fashion",
    sub_type: "akita_kakunodate_kabazaiku",
    title_zh: "角館樺細工伝承館(仙北市角館表町・1978 開館+ 樺細工歴史展示 + 老舗工房実演 + 物販 + 体験コーナー+ 武家屋敷青柳家 R1 育 隣接+ 入館 ¥300+ 角館観光ルート上の工芸 hub)",
    title_ja: "樺細工伝承館",
    romaji: "Kabazaiku Denshōkan",
    summary_zh: "**角館樺細工伝承館は工芸 hub**(仙北市角館表町・**1978 開館 47 年**)。**樺細工歴史展示 + 老舗工房実演 + 物販 + 体験コーナー**、武家屋敷青柳家 R1 育 隣接、入館 ¥300、青森津軽塗会館たくみ R1 衣 + 岩手盛岡手づくり村 R1 育 に並ぶ北東北工芸集積。",
    content_md: "- 立地:**仙北市角館町表町下丁 10-1**(JR 角館駅 徒歩 15 分・武家屋敷沿道)\n- 開館:**1978 年・47 年**\n- 構成:**歴史展示 + 老舗工房実演 + 物販 + 体験**\n- 並列観光:**R1 育 角館武家屋敷 + 青柳家 + 石黒家**\n- 入館:**¥300**\n- 営業:9:00-17:00",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "仙北市",
    lg_code: "05215",
    area_types: ["craft_workshop", "museum_art"],
    lat: 39.5944,
    lon: 140.5611,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kabazaiku_denshokan", "1978", "free_demonstration"],
    source: "manual",
  },
  {
    slug: "kakunodate-kabazaiku-shops",
    category: "fashion",
    sub_type: "akita_kakunodate_kabazaiku",
    title_zh: "角館樺細工 老舗工房群(仙北市角館・藤木伝四郎商店 1851 + 八柳商店 1900 等老舗 8+ 軒+ 武家屋敷沿道 + 表町・東勝楽丁集積+ 観光客現代的小物代表+ 全国百貨店流通)",
    title_ja: "角館樺細工老舗",
    romaji: "Kakunodate Kabazaiku Shops",
    summary_zh: "**角館樺細工老舗工房群は仙北市角館の伝統工房集積**(仙北市角館・**藤木伝四郎商店 1851 + 八柳商店 1900 等老舗 8+ 軒**)。**武家屋敷沿道 + 表町・東勝楽丁集積 + 全国百貨店流通**、青森田中屋 R1 衣(津軽塗 1837)+ 岩手鈴木盛久 R1 衣(南部鉄器 1625)に並ぶ北東北工芸老舗。",
    content_md: "- 立地:**仙北市角館町表町・東勝楽丁**(武家屋敷沿道)\n- 主要老舗:**藤木伝四郎商店(1851)+ 八柳商店(1900)+ 冨岡商店 + 仁手古商店 等 8+ 軒**\n- 並列:**青森田中屋 1837(津軽塗)+ 岩手鈴木盛久 1625(南部鉄器)+ 秋田藤木伝四郎 1851(樺細工)= 北東北工芸老舗**\n- 物販:**全国百貨店 + 角館武家屋敷沿道**",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "仙北市",
    lg_code: "05215",
    area_types: ["shopping_district", "craft_workshop"],
    lat: 39.5944,
    lon: 140.5611,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kakunodate_shops", "fujiki_denshiro_1851", "yatsuyanagi_1900"],
    source: "manual",
  },
  {
    slug: "kabazaiku-experience",
    category: "fashion",
    sub_type: "akita_kakunodate_kabazaiku",
    title_zh: "樺細工体験(角館樺細工伝承館 + 工房・茶筒+小物入+ストラップ ¥2,000-4,500+ 90-180 分所要+ 即日持ち帰り可+ 観光客向け予約制 角館武家屋敷観光と組合せ)",
    title_ja: "樺細工体験",
    romaji: "Kabazaiku Taiken",
    summary_zh: "**樺細工体験は角館工芸体験**(仙北市角館・**伝承館 + 工房**)。**茶筒 + 小物入 + ストラップ ¥2,000-4,500 + 90-180 分所要 + 即日持ち帰り可**、青森津軽塗体験 R1 衣 + 岩手南部鉄器体験 R1 衣 に並ぶ北東北工芸体験 3 大、角館武家屋敷観光と組合せ便利。",
    content_md: "- 体験内容:**茶筒 + 小物入 + ストラップ**\n- 所要時間:**90-180 分**\n- 価格:**¥2,000-4,500**\n- 完成:**即日持ち帰り可**(漆塗のような半年待ちなし)\n- 主要場所:**樺細工伝承館 + 老舗工房**\n- 予約:**3-7 日前推奨**\n- 並列:**青森津軽塗体験 R1 + 岩手南部鉄器体験 R1 + 秋田樺細工体験 R1 = 北東北工芸体験 3 大**",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "仙北市",
    lg_code: "05215",
    area_types: ["craft_workshop"],
    lat: 39.5944,
    lon: 140.5611,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["kabazaiku_taiken", "90_180min", "instant_takeaway"],
    source: "manual",
  },

  // 川連漆器 (3)
  {
    slug: "kawatsura-shikki-overview",
    category: "fashion",
    sub_type: "akita_kawatsura_shikki",
    title_zh: "川連漆器(湯沢市川連町・経産省指定伝統的工芸品 1976+ 鎌倉時代 1193 起源 832+ 年・全国最古級漆器+ 秋田藩 御料漆器+ 椀+重箱+酒器代表+ 雪国保存技法+ 全国百貨店流通)",
    title_ja: "川連漆器",
    romaji: "Kawatsura Shikki",
    summary_zh: "**川連漆器は経産省指定伝統的工芸品 1976**(湯沢市川連町・**鎌倉時代 1193 起源 832+ 年**)。**全国最古級漆器 + 秋田藩 御料漆器 + 椀+重箱+酒器代表 + 雪国保存技法**、青森津軽塗 R1 衣(1646)+ 岩手浄法寺塗 R1 衣(8 世紀 1985)に並ぶ北東北漆器 3 大、湯沢稲庭うどん R1 食 と組合せ可。",
    content_md: "- 立地:**湯沢市川連町**(JR 奥羽本線 湯沢駅 → バス 約 30 分)\n- 起源:**鎌倉時代 1193 + 全国最古級漆器・832+ 年**\n- 認定:**経済産業大臣指定伝統的工芸品 1976**\n- 由来:**秋田藩 御料漆器**\n- 主要品:**椀 + 重箱 + 酒器**\n- 並列:**岩手浄法寺塗 R1 衣(8 世紀)+ 青森津軽塗 R1 衣(1646)+ 秋田川連漆器 R1 衣(1193 鎌倉)= 北東北漆器 3 大**\n- 価格:椀 ¥4,500-25,000",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "湯沢市",
    lg_code: "05206",
    area_types: ["craft_workshop"],
    lat: 39.0597,
    lon: 140.5375,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kawatsura_shikki", "1976_designated", "1193_origin_kamakura", "832_years"],
    source: "manual",
  },
  {
    slug: "kawatsura-densho-kan",
    category: "fashion",
    sub_type: "akita_kawatsura_shikki",
    title_zh: "川連漆器伝統工芸館(湯沢市川連町・1985 開館+ 川連漆器歴史展示+ 鎌倉期から現代までの漆器変遷+ 老舗工房実演 + 物販+ R1 食 稲庭うどん佐藤養助 1860 と組合せ観光・入館 ¥200)",
    title_ja: "川連漆器伝統工芸館",
    romaji: "Kawatsura Densho Kōgeikan",
    summary_zh: "**川連漆器伝統工芸館は湯沢工芸 hub**(湯沢市川連町・**1985 開館 40 年**)。**川連漆器歴史展示 + 老舗工房実演 + 物販 + 体験コーナー**、岩手浄法寺漆芸美術館 R1 衣 + 青森津軽塗会館たくみ R1 衣 に並ぶ北東北漆器伝承施設、R1 食 稲庭うどん佐藤養助 1860 と組合せ観光便利。",
    content_md: "- 立地:**湯沢市川連町大舘字中野 142-1**(JR 湯沢駅 → バス 約 30 分)\n- 開館:**1985 年・40 年**\n- 構成:**歴史展示 + 老舗工房実演 + 物販 + 体験**\n- 並列:**岩手浄法寺漆芸美術館 R1 衣 + 青森津軽塗会館たくみ R1 衣 + 秋田川連漆器伝統工芸館 R1 衣 = 北東北漆器 3 伝承館**\n- 入館:**¥200**",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "湯沢市",
    lg_code: "05206",
    area_types: ["museum_art", "craft_workshop"],
    lat: 39.0597,
    lon: 140.5375,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kawatsura_densho", "1985", "40_years"],
    source: "manual",
  },
  {
    slug: "kawatsura-shikki-experience",
    category: "fashion",
    sub_type: "akita_kawatsura_shikki",
    title_zh: "川連漆器体験(湯沢市川連工房・椀蒔絵体験 ¥3,500-5,500+ 90-180 分+ 漆乾燥仕上げ後 後日郵送+ 北東北漆器体験 3 大の秋田川連系統+ 川連漆器伝統工芸館 体験コーナー)",
    title_ja: "川連漆器体験",
    romaji: "Kawatsura Shikki Taiken",
    summary_zh: "**川連漆器体験は湯沢漆器体験**(湯沢市川連・**椀蒔絵体験 ¥3,500-5,500**)。**90-180 分 + 漆乾燥仕上げ後 後日郵送**、青森津軽塗体験 R1 衣 + 岩手浄法寺塗体験 R1 衣 + 秋田川連漆器体験 R1 = 北東北漆器体験 3 大、川連漆器伝統工芸館の体験コーナー。",
    content_md: "- 体験内容:**椀蒔絵 + 簡易塗装 + コースター絵付け**\n- 所要時間:**90-180 分**\n- 価格:**¥3,500-5,500**\n- 完成:**漆乾燥仕上げ後 後日郵送**(青森津軽塗 + 岩手浄法寺塗体験と同様)\n- 並列:**北東北漆器体験 3 大**(青森津軽塗 + 岩手浄法寺塗 + 秋田川連漆器)\n- 予約:**3-7 日前推奨**",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "湯沢市",
    lg_code: "05206",
    area_types: ["craft_workshop"],
    lat: 39.0597,
    lon: 140.5375,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["kawatsura_taiken", "90_180min", "post_delivery"],
    source: "manual",
  },

  // なまはげ面 (2)
  {
    slug: "namahage-mask-overview",
    category: "fashion",
    sub_type: "akita_oga_namahage",
    title_zh: "なまはげ面制作(男鹿半島・国指定重要無形民俗 1978 + UNESCO 無形 2018 R1 育 関連+ 赤鬼/青鬼面+杉皮頭+ なまはげ仮面職人 男鹿半島内 数 10 工房+ 観光客向けミニ面物販)",
    title_ja: "なまはげ面",
    romaji: "Namahage Men",
    summary_zh: "**なまはげ面は男鹿半島民俗工芸**(男鹿市・**国指定重要無形民俗 1978 + UNESCO 無形 2018 R1 育 関連**)。**赤鬼/青鬼面+杉皮頭 + なまはげ仮面職人 男鹿半島内 数 10 工房**、青森ねぶた小屋 R2 衣(青森ねぶた制作)+ 岩手鬼剣舞衣装 R5 衣 に並ぶ北東北祭具民俗、観光客向けミニ面物販。",
    content_md: "- 立地:**男鹿市男鹿半島**(JR 男鹿線 男鹿駅 → バス 約 30 分)\n- 認定関連:**国指定重要無形民俗 1978 + UNESCO 無形 2018(R1 育 なまはげ柴灯祭・R1 育 真山神社)**\n- 構成:**赤鬼/青鬼面 + 杉皮頭**\n- 規模:**男鹿半島内 数 10 工房**\n- 並列:**青森ねぶた小屋 R2 衣(青森ねぶた制作) + 岩手鬼剣舞衣装 R5 衣 + 秋田なまはげ面 R1 衣 = 北東北祭具民俗 3 大**\n- 物販:**観光客向けミニ面 ¥1,500-5,000 / 大型面 ¥15,000-50,000**",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "男鹿市",
    lg_code: "05206",
    area_types: ["craft_workshop", "festival_event"],
    lat: 39.8861,
    lon: 139.8447,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["namahage_men", "1978_designated", "unesco_2018"],
    source: "manual",
  },
  {
    slug: "namahage-museum-shinzan",
    category: "fashion",
    sub_type: "akita_oga_namahage",
    title_zh: "男鹿真山伝承館(男鹿市・1990 開館+ なまはげ面 100+ 種類展示+ 民家でなまはげ訪問再現体験+ 真山神社 R1 育 隣接+ 入館 ¥880(なまはげ館 共通)+ 観光客向けなまはげ文化体験 hub)",
    title_ja: "男鹿真山伝承館",
    romaji: "Oga Shinzan Denshōkan",
    summary_zh: "**男鹿真山伝承館は なまはげ文化体験 hub**(男鹿市・**1990 開館 35 年**)。**なまはげ面 100+ 種類展示 + 民家でなまはげ訪問再現体験 + 真山神社 R1 育 隣接**、青森ねぶたの家ワ・ラッセ R1 育(2011)+ 岩手鬼の館 R3 育(1994)に並ぶ北東北民俗体験館 3 大、入館 ¥880(なまはげ館 共通)。",
    content_md: "- 立地:**男鹿市北浦真山**(JR 男鹿駅 → バス 約 35 分・真山神社 R1 育 隣接)\n- 開館:**1990 年・35 年**\n- 規模:**なまはげ面 100+ 種類展示**\n- 体験:**民家でなまはげ訪問再現体験**(なまはげが来訪する江戸期 民家)\n- 並列:**青森ねぶたの家ワ・ラッセ R1(2011)+ 岩手鬼の館 R3(1994)+ 秋田男鹿真山伝承館 R1(1990)= 北東北民俗体験館 3 大**\n- 入館:**¥880(なまはげ館 共通券)**",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "男鹿市",
    lg_code: "05206",
    area_types: ["museum_art", "craft_workshop"],
    lat: 39.9389,
    lon: 139.8350,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://namahage.co.jp/namahagekan/" },
    tags: ["shinzan_denshokan", "1990", "100_masks", "shinzan_jinja_adjacent"],
    source: "manual",
  },

  // 大館曲げわっぱ (2)
  {
    slug: "odate-magewappa-1980",
    category: "fashion",
    sub_type: "akita_odate_magewappa",
    title_zh: "大館曲げわっぱ(大館市・経産省指定伝統的工芸品 1980+ 江戸期 1602 大館藩主秋田氏由来+ 杉一枚板を曲げて作る飯椀+弁当箱+ 全国弁当箱代表+ 大館市内工房集積)",
    title_ja: "大館曲げわっぱ",
    romaji: "Ōdate Magewappa",
    summary_zh: "**大館曲げわっぱは経産省指定伝統的工芸品 1980**(大館市・**江戸期 1602 大館藩主秋田氏由来**)。**杉一枚板を曲げて作る飯椀+弁当箱**、青森津軽塗 R1 衣 + 岩手南部鉄器 R1 衣 + 秋田樺細工 R1 衣 + 大館曲げわっぱ R1 = 北東北工芸 4 大、全国弁当箱代表、大館市内工房集積。",
    content_md: "- 立地:**大館市**(JR 東北新幹線 大館駅 徒歩圏)\n- 認定:**経済産業大臣指定伝統的工芸品 1980**\n- 起源:**江戸期 1602 大館藩主秋田氏由来**\n- 素材:**秋田杉一枚板を曲げる**\n- 主要品:**飯椀 + 弁当箱 + 米櫃**(全国弁当箱代表)\n- 並列:**津軽塗 R1 + 南部鉄器 R1 + 樺細工 R1 + 大館曲げわっぱ R1 = 北東北工芸 4 大**\n- 価格:弁当箱 ¥8,000-25,000",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "大館市",
    lg_code: "05204",
    area_types: ["craft_workshop"],
    lat: 40.2722,
    lon: 140.5642,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["odate_magewappa", "1980_designated", "1602_origin", "akita_sugi"],
    source: "manual",
  },
  {
    slug: "odate-magewappa-experience",
    category: "fashion",
    sub_type: "akita_odate_magewappa",
    title_zh: "大館曲げわっぱ体験(大館市内工房・小物入+小弁当箱体験 ¥3,000-6,000+ 120-180 分+ 即日持ち帰り可+ 秋田犬 R1 育 大館 + 比内地鶏 R1 食 大館 と組合せ観光)",
    title_ja: "大館曲げわっぱ体験",
    romaji: "Ōdate Magewappa Taiken",
    summary_zh: "**大館曲げわっぱ体験は大館工芸体験**(大館市・**¥3,000-6,000**)。**120-180 分 + 即日持ち帰り可**、青森津軽塗 + 岩手南部鉄器 + 秋田樺細工 + 大館曲げわっぱ = 北東北工芸体験 4 大、秋田犬 R1 育 大館 + 比内地鶏 R1 食 大館 と組合せ観光。",
    content_md: "- 体験内容:**小物入 + 小弁当箱**\n- 所要時間:**120-180 分**\n- 価格:**¥3,000-6,000**\n- 完成:**即日持ち帰り可**\n- 主要場所:**大館市内工房**\n- 並列観光:R1 育 秋田犬 + R1 食 比内地鶏 + R1 食 きりたんぽ鍋(大館) = 大館 4 大",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "大館市",
    lg_code: "05204",
    area_types: ["craft_workshop"],
    lat: 40.2722,
    lon: 140.5642,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["magewappa_taiken", "120_180min"],
    source: "manual",
  },

  // 銀線細工 (2)
  {
    slug: "akita-ginsen-zaiku-1976",
    category: "fashion",
    sub_type: "akita_ginsen_zaiku",
    title_zh: "秋田銀線細工(秋田市・経産省指定伝統的工芸品 1976+ 江戸期 1685 秋田藩士金山師 鈴木氏由来+ 銀線(直径 0.2mm)極細糸状+ ブローチ+ペンダント+簪 等装飾品+ 全国シェア 100% 独自工芸)",
    title_ja: "秋田銀線細工",
    romaji: "Akita Ginsen Zaiku",
    summary_zh: "**秋田銀線細工は経産省指定伝統的工芸品 1976**(秋田市・**江戸期 1685 秋田藩士金山師 鈴木氏由来**)。**銀線(直径 0.2mm)極細糸状 + ブローチ+ペンダント+簪 等装飾品 + 全国シェア 100% 独自工芸**、青森こぎん刺し R1 衣 + 岩手ホームスパン R1 衣 に並ぶ北東北独自手工芸。",
    content_md: "- 立地:**秋田市**(JR 秋田駅 徒歩圏 + 県内工房)\n- 認定:**経済産業大臣指定伝統的工芸品 1976**\n- 起源:**江戸期 1685 秋田藩士金山師 鈴木氏由来**\n- 素材:**銀線(直径 0.2mm)極細糸状**\n- 主要品:**ブローチ + ペンダント + 簪 + イヤリング**\n- 認定:**全国シェア 100% 独自工芸**\n- 並列:**青森こぎん刺し R1(津軽刺繍) + 岩手ホームスパン R1(羊毛織) + 秋田銀線細工 R1(銀工芸) = 北東北独自手工芸 3 大**\n- 価格:ブローチ ¥8,000-50,000",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "秋田市",
    lg_code: "05201",
    area_types: ["craft_workshop"],
    lat: 39.7178,
    lon: 140.1031,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ginsen_zaiku", "1976_designated", "1685_origin", "100pct_share"],
    source: "manual",
  },
  {
    slug: "akita-ginsen-experience",
    category: "fashion",
    sub_type: "akita_ginsen_zaiku",
    title_zh: "秋田銀線細工体験(秋田市内工房・ペンダント+ブローチ ¥4,500-8,000+ 90-180 分・銀線扱う繊細手作業+ 完成品 即日持ち帰り可+ 秋田駅前 + アトリオン内体験コーナー)",
    title_ja: "銀線細工体験",
    romaji: "Ginsen Zaiku Taiken",
    summary_zh: "**秋田銀線細工体験は秋田市内工房体験**(秋田市・**¥4,500-8,000**)。**90-180 分 + 銀線扱う繊細手作業 + 完成品 即日持ち帰り可**、青森こぎん刺し体験 R1 衣 + 岩手南部鉄器体験 R1 衣 + 秋田樺細工体験 R1 + 銀線細工体験 R1 = 北東北体験 4 大の女性人気代表。",
    content_md: "- 体験内容:**ペンダント + ブローチ**\n- 所要時間:**90-180 分**\n- 価格:**¥4,500-8,000**\n- 完成:**即日持ち帰り可**\n- 場所:**秋田駅前 + アトリオン(秋田市文化会館)体験コーナー**",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "秋田市",
    lg_code: "05201",
    area_types: ["craft_workshop"],
    lat: 39.7178,
    lon: 140.1031,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["ginsen_taiken", "90_180min", "delicate_handwork"],
    source: "manual",
  },

  // 百貨店 (2)
  {
    slug: "seibu-akita",
    category: "fashion",
    sub_type: "akita_dept_store",
    title_zh: "西武秋田店(秋田市・JR 秋田駅西口直結+ 全 7 階 + 秋田中心地百貨店+ 全国チェーン西武+ 食料 + 衣料 + 雑貨 + 銀線細工 R1 衣 + 樺細工 R1 衣 物販コーナー入る)",
    title_ja: "西武秋田",
    romaji: "Seibu Akita",
    summary_zh: "**西武秋田は秋田市内中心百貨店**(秋田市・**JR 秋田駅西口直結**)。**全 7 階 + 全国チェーン西武 + 食料 + 衣料 + 雑貨 + 銀線細工 R1 衣 + 樺細工 R1 衣 物販コーナー入る**、青森中三 R1 衣 + 岩手川徳 R1 衣 + 秋田西武 R1 = 北東北百貨店 3 大、駅前直結アクセス便利。",
    content_md: "- 立地:**秋田市中通 2-6-1**(JR 秋田駅西口 直結)\n- 規模:**全 7 階建**\n- 取扱:**食料 + 衣料 + 雑貨 + 銀線細工 R1 衣 + 樺細工 R1 衣 物販コーナー**\n- 並列:**青森中三 R1(1896 老舗)+ 岩手川徳 R1(1866 老舗)+ 秋田西武 R1(全国チェーン)= 北東北百貨店 3 大**\n- 営業:10:00-19:00",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "秋田市",
    lg_code: "05201",
    area_types: ["shopping_district", "transit_hub"],
    lat: 39.7178,
    lon: 140.1031,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["seibu_akita", "station_west", "7_floors"],
    source: "manual",
  },
  {
    slug: "akita-orupotsu-station-mall",
    category: "fashion",
    sub_type: "akita_dept_store",
    title_zh: "秋田駅構内 トピコ + アルス(秋田市・JR 秋田駅構内 SC・2002 開業 23 年+ 全 200+ 店舗+ 食料 + 土産 + 衣料 + ファッション+ 観光客の主要土産購入拠点+ 西武秋田 R1 衣 と並ぶ駅前商業 2 大)",
    title_ja: "秋田駅 トピコ + アルス",
    romaji: "Akita Topiko + Aluss",
    summary_zh: "**秋田駅 トピコ + アルスは駅構内 SC**(秋田市・**2002 開業 23 年**)。**JR 秋田駅構内 + 全 200+ 店舗 + 観光客の主要土産購入拠点**、西武秋田(R1 衣)+ 秋田駅 トピコアルス(R1) = 駅前商業 2 大、青森ヒロロ R5 衣 + 岩手さくら野盛岡 R1 衣 に並ぶ北東北駅前 SC。",
    content_md: "- 立地:**秋田市中通 7-1**(JR 秋田駅構内・改札直結)\n- 開業:**2002 年・23 年**\n- 規模:**全 200+ 店舗**(駅構内 SC)\n- 取扱:**食料 + 土産 + 衣料 + ファッション + R1 食 もろこし R1 食 金萬 等銘菓直販**\n- 並列:**西武秋田 R1(駅西)+ トピコ・アルス R1(駅構内) = 秋田駅前商業 2 大**\n- 並列:**青森ヒロロ R5 衣 + 岩手さくら野盛岡 R1 衣 + 秋田トピコアルス R1 = 北東北駅前 SC 3 大**\n- 営業:10:00-21:00",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "秋田市",
    lg_code: "05201",
    area_types: ["shopping_district", "transit_hub"],
    lat: 39.7178,
    lon: 140.1031,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["topiko_aluss", "2002", "station_mall", "200_stores"],
    source: "manual",
  },

  // 民芸 (3)
  {
    slug: "yatsuhashi-ningyo-akita",
    category: "fashion",
    sub_type: "akita_folk_craft",
    title_zh: "八橋人形(秋田市八橋・1700 年代起源 320+ 年+ 江戸期から伝承土人形+ 雛人形+干支土人形+小物+ 県重要無形民俗文化財+ 道川家 5 代継承+ 観光土産代表)",
    title_ja: "八橋人形",
    romaji: "Yatsuhashi Ningyō",
    summary_zh: "**八橋人形は秋田市の伝統土人形**(秋田市八橋・**1700 年代起源 320+ 年**)。**江戸期から伝承土人形 + 雛人形+干支土人形+小物 + 県重要無形民俗文化財 + 道川家 5 代継承**、青森下川原焼 R1 衣(1804 阿保家)+ 岩手花巻人形 R1 衣(1781)に並ぶ北東北土人形 3 大、観光土産代表。",
    content_md: "- 立地:**秋田市八橋**(JR 秋田駅 → バス 約 15 分)\n- 起源:**1700 年代・320+ 年**\n- 認定:**県重要無形民俗文化財**\n- 継承:**道川家 5 代**\n- 主要品:**雛人形 + 干支土人形 + 小物**\n- 並列:**青森下川原焼 R1(1804 阿保家)+ 岩手花巻人形 R1(1781 阿部家)+ 秋田八橋人形 R1(1700 年代 道川家)= 北東北土人形 3 大**\n- 価格:¥1,500-5,500",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "秋田市",
    lg_code: "05201",
    area_types: ["craft_workshop"],
    lat: 39.7256,
    lon: 140.0856,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yatsuhashi_ningyo", "1700s_origin", "320_years", "michikawa_5gen"],
    source: "manual",
  },
  {
    slug: "akita-inu-products",
    category: "fashion",
    sub_type: "akita_folk_craft",
    title_zh: "秋田犬グッズ(大館市・秋田犬 R1 育 国指定天然記念物 1931 + 渋谷ハチ公由来+ 秋田犬人形 + 木彫秋田犬 + ぬいぐるみ + 公式秋田犬関連商品+ 大館市秋田犬関連店舗 + 観光土産代表)",
    title_ja: "秋田犬グッズ",
    romaji: "Akita Inu Goods",
    summary_zh: "**秋田犬グッズは大館民芸代表**(大館市・**秋田犬 R1 育 国指定天然記念物 1931**)。**渋谷ハチ公由来 + 秋田犬人形 + 木彫秋田犬 + ぬいぐるみ**、青森八幡馬 R1 衣(日本三大駒)+ 岩手七夕馬 R1 衣 に並ぶ北東北民芸動物像、大館市秋田犬関連店舗。",
    content_md: "- 立地:**大館市**(JR 大館駅 徒歩圏 + 大館秋田犬関連施設)\n- 認定関連:**秋田犬 国指定天然記念物 1931 R1 育・渋谷ハチ公由来**\n- 主要品:**秋田犬人形 + 木彫秋田犬 + ぬいぐるみ + キーホルダー**\n- 並列:**青森八幡馬 R1(日本三大駒)+ 岩手七夕馬 R1 + 秋田犬グッズ R1 = 北東北民芸動物像 3 大**\n- 価格:¥600-15,000",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "大館市",
    lg_code: "05204",
    area_types: ["craft_workshop", "shopping_district"],
    lat: 40.2722,
    lon: 140.5642,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["akita_inu_goods", "1931_natural_treasure", "hachiko"],
    source: "manual",
  },
  {
    slug: "kakunodate-namari-zaiku",
    category: "fashion",
    sub_type: "akita_folk_craft",
    title_zh: "角館 鉛細工(仙北市角館・江戸期から伝承+ 武家屋敷文化由来鉛工芸+ ペンダント+ペーパーウェイト+小物 角館武家屋敷 R1 育 沿道工房・観光土産+ 樺細工 R1 衣 と並ぶ角館 2 大工芸)",
    title_ja: "角館鉛細工",
    romaji: "Kakunodate Namari Zaiku",
    summary_zh: "**角館鉛細工は武家屋敷文化由来鉛工芸**(仙北市角館・**江戸期から伝承**)。**ペンダント+ペーパーウェイト+小物 + 角館武家屋敷 R1 育 沿道工房**、青森あけび蔓細工 R1 衣 + 岩手平泉菅笠 R1 衣 に並ぶ北東北稀少民芸、樺細工 R1 衣 と並ぶ角館 2 大工芸。",
    content_md: "- 立地:**仙北市角館町**(JR 角館駅 徒歩 15 分・武家屋敷沿道)\n- 起源:**江戸期から伝承**(武家屋敷文化由来)\n- 主要品:**ペンダント + ペーパーウェイト + 小物**\n- 並列:**樺細工 R1 衣 + 角館鉛細工 R1 衣 = 角館 2 大工芸**\n- 物販:**角館武家屋敷沿道工房 + 観光土産店**",
    region: "tohoku",
    prefecture_ja: "秋田県",
    gun_ja: null,
    municipality_ja: "仙北市",
    lg_code: "05215",
    area_types: ["craft_workshop"],
    lat: 39.5944,
    lon: 140.5611,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["namari_zaiku", "edo_origin", "kakunodate"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[akita-fashion-r1] 尚無條目");
    return;
  }
  console.log(`[akita-fashion-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(28)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[akita-fashion-r1] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[akita-fashion-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[akita-fashion-r1] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
