// Seed 茨城県 育 R1(21 筆 / Sprint 1.4)
// 偕楽園+水戸藩 4 / 鹿島+笠間 3 / 牛久大仏+巨大建造 2 / 袋田+滝景 2 / 五浦+岡倉天心 2 / 美術館+科学 5 / つくば+JAXA 3 = 21

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "茨城県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 偕楽園+水戸藩 (4)
  { slug: "kairakuen-1842-3-meien", category: "culture", sub_type: "ibaraki_mito_castle", title_zh: "偕楽園(水戸市・1842 徳川斉昭(水戸藩 9 代)創設 183 年+ 「日本三大名園」(後楽園+兼六園+偕楽園)+ 国指定史跡 1922+ 3000 本梅・100 種+ 入園 ¥300+ R1 楽 偕楽園梅まつり 2-3 月メイン+ 全国観光客代表)", title_ja: "偕楽園", romaji: "Kairakuen", summary_zh: "**偕楽園は 1842 徳川斉昭創設 183 年・「日本三大名園」**(水戸・**国指定史跡 1922+3000 本梅 100 種**)。¥300、R1 楽 梅まつり 2-3 月メイン、全国観光客代表。", content_md: "- 立地:**水戸市**\n- 起源:**1842 徳川斉昭(水戸藩 9 代)創設 183 年**\n- 認定:**「日本三大名園」**(後楽園 + 兼六園 + 偕楽園) + **国指定史跡 1922**\n- 規模:**3000 本梅・100 種**\n- 入園:**¥300**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["scenic_spot", "history_site_castle"], lat: 36.3658, lon: 140.4711, season_start: "2026-02-15", season_end: "2026-03-31", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: { official: "https://ibaraki-kairakuen.jp/" }, tags: ["kairakuen", "1842_nariaki", "japan_3_meien", "1922_shiseki"], source: "manual" },
  { slug: "kodokan-1841", category: "culture", sub_type: "ibaraki_mito_castle", title_zh: "弘道館(水戸市・1841 徳川斉昭創設・水戸藩校 184 年+ 国指定特別史跡 1952+ 国重要文化財・正庁+至善堂+ 水戸学発祥地+ R1 育 偕楽園 1842 と並ぶ徳川斉昭事業 2 大+ 入場 ¥400+ JR 水戸駅徒歩 8 分)", title_ja: "弘道館", romaji: "Kōdōkan", summary_zh: "**弘道館は 1841 徳川斉昭創設水戸藩校 184 年・国指定特別史跡 1952**(水戸・**国重要文化財・水戸学発祥地**)。R1 育 偕楽園 1842 と並ぶ徳川斉昭事業 2 大、¥400、JR 水戸駅徒歩 8 分。", content_md: "- 立地:**水戸市**(JR 水戸駅徒歩 8 分)\n- 起源:**1841 徳川斉昭創設・水戸藩校 184 年**\n- 認定:**国指定特別史跡 1952 + 国重要文化財・正庁+至善堂**\n- 看板:**水戸学発祥地**\n- 入場:**¥400**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["history_site_castle"], lat: 36.3722, lon: 140.4783, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kodokan", "1841_nariaki", "184_years", "1952_tokushuhi"], source: "manual" },
  { slug: "mito-jou-ato-tokugawa", category: "culture", sub_type: "ibaraki_mito_castle", title_zh: "水戸城跡(水戸市・1190 鎌倉期築城+ 1609 徳川頼房 入封 水戸藩 270 年+ 1872 廃城+ 1981 国指定史跡+ R1 育 弘道館 1841 隣接・水戸城三の丸+ 水戸黄門 1628-1701 由来地+ 入場無料・三の丸復元門観覧)", title_ja: "水戸城跡", romaji: "Mito-jō Ato", summary_zh: "**水戸城跡は 1190 鎌倉期築城+1609 徳川頼房入封水戸藩 270 年**(水戸・**1872 廃城・国指定史跡 1981**)。R1 育 弘道館 1841 隣接、水戸黄門由来地、無料・三の丸復元門観覧。", content_md: "- 立地:**水戸市**\n- 起源:**1190 鎌倉期築城 + 1609 徳川頼房 入封水戸藩 270 年**\n- 期:**1190 築城 → 1872 廃城**\n- 認定:**国指定史跡 1981**\n- 縁:**水戸黄門 1628-1701 由来地**\n- 並列:**R1 育 弘道館 1841 隣接(水戸城三の丸跡)**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["history_site_castle"], lat: 36.3722, lon: 140.4783, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mito_jo", "1190_kamakura", "1609_tokugawa", "1981_shiseki"], source: "manual" },
  { slug: "mito-art-museum-1990", category: "culture", sub_type: "ibaraki_modern_art", title_zh: "水戸芸術館(水戸市・1990 開館・磯崎新設計+ 茨城県+水戸市運営現代芸術館+ コンサートホール+音楽+演劇+美術 複合+ 100m タワーシンボル+ 入場無料(展示一部 ¥800)+ R1 衣 京成百貨店徒歩 5 分)", title_ja: "水戸芸術館", romaji: "Art Tower Mito", summary_zh: "**水戸芸術館は 1990 開館・磯崎新設計**(水戸・**茨城県+水戸市運営現代芸術館**)。コンサート+音楽+演劇+美術複合、100m タワーシンボル、無料(展示一部 ¥800)、R1 衣 京成徒歩 5 分。", content_md: "- 立地:**水戸市**\n- 起源:**1990 開館 35 年**\n- 設計:**磯崎新**\n- 構成:**コンサートホール + 音楽 + 演劇 + 美術 複合**\n- 看板:**100m タワーシンボル**\n- 入場:**無料(展示一部 ¥800)**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["museum_art"], lat: 36.3722, lon: 140.4783, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: { official: "https://www.arttowermito.or.jp/" }, tags: ["art_tower_mito", "1990", "isozaki_arata", "100m_tower"], source: "manual" },

  // 鹿島+笠間 (3)
  { slug: "kashima-jingu-bc-660", category: "culture", sub_type: "ibaraki_shrine_temple", title_zh: "鹿島神宮(鹿嶋市・紀元前 660 神武天皇創建伝承・「常陸国一之宮」+ 国宝・直刀+ 国重要文化財・本殿+楼門+奥宮+ 全国鹿島神宮 600+ 軒総本宮+ 入場無料(宝物館 ¥300)+ 観光客必訪)", title_ja: "鹿島神宮", romaji: "Kashima Jingū", summary_zh: "**鹿島神宮は紀元前 660 神武天皇創建伝承・常陸国一之宮**(鹿嶋・**全国鹿島神宮 600+ 軒総本宮**)。国宝直刀+国重文本殿+楼門、無料(宝物館 ¥300)、必訪。", content_md: "- 立地:**鹿嶋市**\n- 起源:**紀元前 660 神武天皇創建伝承**\n- 認定:**「常陸国一之宮」 + 全国鹿島神宮 600+ 軒総本宮**\n- 蔵品:**国宝・直刀 + 国重文・本殿+楼門+奥宮**\n- 入場:**無料(宝物館 ¥300)**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "鹿嶋市", lg_code: "08222", area_types: ["shrine_temple"], lat: 35.9656, lon: 140.6447, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kashima_jingu", "bc_660", "hitachi_ichinomiya", "600_branches"], source: "manual" },
  { slug: "kasama-inari-1500", category: "culture", sub_type: "ibaraki_shrine_temple", title_zh: "笠間稲荷神社(笠間市・651 大化年間創建 1374 年+ 「関東 3 大稲荷」(伏見+豊川+笠間)候補+ R1 衣 笠間焼+R1 食 そばまんじゅう参道+ 県重要文化財・本殿+ 入場無料+ 観光客年間 350 万人来場)", title_ja: "笠間稲荷神社", romaji: "Kasama Inari", summary_zh: "**笠間稲荷神社は 651 大化年間創建 1374 年・関東 3 大稲荷候補**(笠間・**伏見+豊川+笠間**)。R1 衣 笠間焼+R1 食 そばまんじゅう参道、年間 350 万人来場、無料。", content_md: "- 立地:**笠間市**\n- 起源:**651 大化年間創建 1374 年**\n- 認定:**「関東 3 大稲荷」候補**(伏見 + 豊川 + 笠間) + **県重要文化財・本殿**\n- 並列:**R1 衣 笠間焼 + R1 食 そばまんじゅう参道**\n- 来場:**年間 350 万人**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "笠間市", lg_code: "08216", area_types: ["shrine_temple"], lat: 36.3858, lon: 140.2614, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kasama_inari", "651_taika", "1374_years", "kanto_3_inari"], source: "manual" },
  { slug: "kasama-nichido-museum-1972", category: "culture", sub_type: "ibaraki_modern_art", title_zh: "笠間日動美術館(笠間市・1972 開館 53 年+ 国内最大級個人美術館+ 印象派+モディリアーニ+ピカソ+ルノワール 等+ 県内重要美術館・約 4000 点蔵品+ R1 育 笠間稲荷+R1 衣 笠間焼観光と組合せ+ 入館 ¥1,200)", title_ja: "笠間日動美術館", romaji: "Kasama Nichidō Bijutsukan", summary_zh: "**笠間日動美術館は 1972 開館 53 年・国内最大級個人美術館**(笠間・**印象派+モディリアーニ+ピカソ+ルノワール 4000 点**)。R1 育 笠間稲荷+R1 衣 笠間焼観光、入館 ¥1,200。", content_md: "- 立地:**笠間市**\n- 起源:**1972 開館 53 年**\n- 認定:**国内最大級個人美術館**\n- 蔵品:**印象派 + モディリアーニ + ピカソ + ルノワール 約 4000 点**\n- 入館:**¥1,200**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "笠間市", lg_code: "08216", area_types: ["museum_art"], lat: 36.3858, lon: 140.2614, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: ["月"], external_urls: { official: "https://www.nichido-museum.or.jp/" }, tags: ["kasama_nichido", "1972", "japan_largest_private", "4000_works"], source: "manual" },

  // 牛久大仏 (2)
  { slug: "ushiku-daibutsu-1993-120m", category: "culture", sub_type: "ibaraki_shrine_temple", title_zh: "牛久大仏(牛久市・1993 完成・浄土真宗東本願寺派+ 立像高 120m(像高 100m+台座 20m)・ギネス世界記録「世界最大青銅製仏像」+ 入場 ¥800・展望台 85m 地点+ R1 食 牛久シャトーカミヤ 1903 観光と組合せ)", title_ja: "牛久大仏", romaji: "Ushiku Daibutsu", summary_zh: "**牛久大仏は 1993 完成・ギネス世界記録「世界最大青銅製仏像」**(牛久・**立像高 120m(100m+20m 台座)**)。¥800・展望台 85m、R1 食 牛久シャトー 1903 観光組合せ。", content_md: "- 立地:**牛久市**\n- 起源:**1993 完成 32 年**\n- 認定:**ギネス世界記録「世界最大青銅製仏像」**\n- 規模:**立像高 120m(像高 100m + 台座 20m)**\n- 入場:**¥800・展望台 85m 地点**\n- 並列:**R1 食 牛久シャトーカミヤ 1903**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "牛久市", lg_code: "08219", area_types: ["shrine_temple", "scenic_spot"], lat: 35.9806, lon: 140.1408, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: { official: "https://daibutu.net/" }, tags: ["ushiku_daibutsu", "1993", "120m", "guinness_world_record"], source: "manual" },
  { slug: "ooarai-isosaki-jinja-856", category: "culture", sub_type: "ibaraki_shrine_temple", title_zh: "大洗磯前神社(大洗町・856 平安期創建 1169 年+ 太平洋海中鳥居・「神磯の鳥居」全国知名度+ 県重要文化財・本殿+ R1 食 鮟鱇鍋+R1 楽 アクアワールド観光客向け+ 入場無料+ 朝日眺望 SNS 拡散代表)", title_ja: "大洗磯前神社", romaji: "Ōarai Isosaki Jinja", summary_zh: "**大洗磯前神社は 856 平安期創建 1169 年**(大洗・**太平洋海中鳥居「神磯の鳥居」全国知名度**)。県重要文化財・本殿、R1 食 鮟鱇+R1 楽 アクアワールド観光、無料、朝日 SNS 拡散。", content_md: "- 立地:**大洗町**\n- 起源:**856 平安期創建 1169 年**\n- 看板:**太平洋海中鳥居・「神磯の鳥居」全国知名度**\n- 認定:**県重要文化財・本殿**\n- 並列:**R1 食 鮟鱇 + R1 楽 アクアワールド + R1 衣 ガルパン聖地**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "大洗町", lg_code: "08309", area_types: ["shrine_temple", "scenic_spot"], lat: 36.3094, lon: 140.5750, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ooarai_isosaki", "856_heian", "kamiiso_torii"], source: "manual" },

  // 袋田+滝景 (2)
  { slug: "fukuroda-falls-3-meibaku", category: "culture", sub_type: "ibaraki_history_museum", title_zh: "袋田の滝(久慈郡大子町・「日本三名瀑」(那智+華厳+袋田)+ 国指定名勝 1953+ 西行 鎌倉期 1186 訪問記録+ 落差 120m+幅 73m 4 段瀑+ 4 シーズン景観・氷瀑+紅葉名所+ 入場 ¥300+ R1 食 大子りんご観光客向け代表)", title_ja: "袋田の滝", romaji: "Fukuroda no Taki", summary_zh: "**袋田の滝は「日本三名瀑」**(大子・**国指定名勝 1953+落差 120m+幅 73m 4 段瀑**)。西行鎌倉期 1186 訪問、4 シーズン景観・氷瀑+紅葉、¥300、R1 食 大子りんご観光客代表。", content_md: "- 立地:**久慈郡大子町**\n- 認定:**「日本三名瀑」**(那智 + 華厳 + 袋田) + **国指定名勝 1953**\n- 規模:**落差 120m + 幅 73m 4 段瀑**\n- 縁:**西行 鎌倉期 1186 訪問記録**\n- 期:**4 シーズン・氷瀑(1-2 月) + 紅葉(10-11 月)**\n- 入場:**¥300**", region: "kanto", prefecture_ja: "茨城県", gun_ja: "久慈郡", municipality_ja: "大子町", lg_code: "08364", area_types: ["scenic_spot"], lat: 36.7681, lon: 140.3556, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["fukuroda_falls", "japan_3_meibaku", "1953_meisho", "120m_73m"], source: "manual" },
  { slug: "tsukubasan-jinja-mountain", category: "culture", sub_type: "ibaraki_shrine_temple", title_zh: "筑波山神社+筑波山(つくば市+桜川市・3000+ 年伝承+ 「西の富士+東の筑波」全国知名度+ 標高 877m 男体山+女体山 双耳峰+ 県重要文化財・本殿+ R1 行 筑波山ロープウェイ+ケーブルカー+ 入場無料・登山+ 全国百名山)", title_ja: "筑波山神社+筑波山", romaji: "Tsukubasan Jinja", summary_zh: "**筑波山神社+筑波山は 3000+ 年伝承・「西の富士+東の筑波」**(つくば+桜川・**標高 877m+男体山+女体山双耳峰**)。R1 行 ロープウェイ+ケーブルカー、無料・登山、全国百名山。", content_md: "- 立地:**つくば市 + 桜川市**\n- 起源:**3000+ 年伝承**\n- 認定:**「西の富士 + 東の筑波」全国知名度 + 全国百名山**\n- 規模:**標高 877m 男体山 + 女体山 双耳峰**\n- 並列:**R1 行 筑波山ロープウェイ + ケーブルカー**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "つくば市", lg_code: "08220", area_types: ["shrine_temple", "mountain_village"], lat: 36.2253, lon: 140.1058, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsukubasan", "877m", "3000_years", "japan_100_yama"], source: "manual" },

  // 五浦+岡倉天心 (2)
  { slug: "itsuura-rokkakudo-1905", category: "culture", sub_type: "ibaraki_modern_art", title_zh: "五浦六角堂(北茨城市・1905 岡倉天心(1862-1913)隠居所建立 120 年+ 国指定史跡 1955+ 太平洋崖上六角朱塗堂+ 2011 東日本大震災津波被災・2012 再建+ R1 育 茨城県天心記念五浦美術館 1997 隣接+ 入場 ¥300)", title_ja: "五浦六角堂", romaji: "Itsuura Rokkakudō", summary_zh: "**五浦六角堂は 1905 岡倉天心隠居所建立 120 年・国指定史跡 1955**(北茨城・**太平洋崖上六角朱塗堂**)。2011 震災被災 → 2012 再建、R1 育 天心記念五浦美 1997 隣接、¥300。", content_md: "- 立地:**北茨城市五浦**\n- 起源:**1905 岡倉天心(1862-1913)隠居所建立 120 年**\n- 認定:**国指定史跡 1955**\n- 縁:**2011 東日本大震災津波被災 → 2012 再建**\n- 並列:**R1 育 茨城県天心記念五浦美術館 1997 隣接**\n- 入場:**¥300**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "北茨城市", lg_code: "08215", area_types: ["history_site_castle", "scenic_spot"], lat: 36.8278, lon: 140.7506, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["rokkakudo", "1905_okakura_tenshin", "1955_shiseki", "2012_rebuilt"], source: "manual" },
  { slug: "tenshin-kinen-itsuura-museum", category: "culture", sub_type: "ibaraki_modern_art", title_zh: "茨城県天心記念五浦美術館(北茨城市・1997 開館+ R1 育 五浦六角堂派生・岡倉天心+横山大観+菱田春草+下村観山 等 「日本美術院」関連+ 太平洋眺望美術館+ 入館 ¥320)", title_ja: "茨城県天心記念五浦美術館", romaji: "Tenshin Itsuura Bijutsukan", summary_zh: "**茨城県天心記念五浦美術館は 1997 開館**(北茨城・**R1 育 五浦六角堂派生**)。岡倉天心+横山大観+菱田春草+下村観山「日本美術院」関連、太平洋眺望、¥320。", content_md: "- 立地:**北茨城市五浦**(R1 育 五浦六角堂隣接)\n- 起源:**1997 開館 28 年**\n- 関係:**R1 育 五浦六角堂 1905 岡倉天心派生**\n- 蔵品:**岡倉天心 + 横山大観 + 菱田春草 + 下村観山「日本美術院」関連**\n- 入館:**¥320**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "北茨城市", lg_code: "08215", area_types: ["museum_art"], lat: 36.8278, lon: 140.7506, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["tenshin_itsuura_museum", "1997"], source: "manual" },

  // 美術館+科学+歴史 (5)
  { slug: "ibaraki-prefectural-museum-art", category: "culture", sub_type: "ibaraki_modern_art", title_zh: "茨城県近代美術館(水戸市千波湖・1988 開館+ R1 育 偕楽園隣接千波湖畔+ 横山大観+菱田春草+ 県内出身画家 中村彝・小川芋銭 等+ 入館 ¥320+ R1 育 偕楽園・水戸芸術館と並ぶ茨城美術館 3 大)", title_ja: "茨城県近代美術館", romaji: "Ibaraki Kindai Bijutsukan", summary_zh: "**茨城県近代美術館は 1988 開館**(水戸千波湖畔・**R1 育 偕楽園隣接**)。横山大観+菱田春草+中村彝・小川芋銭、¥320、R1 育 偕楽園+水戸芸術館と並ぶ茨城美術館 3 大。", content_md: "- 立地:**水戸市千波湖**(R1 育 偕楽園隣接)\n- 起源:**1988 開館 37 年**\n- 蔵品:**横山大観 + 菱田春草 + 中村彝 + 小川芋銭 等**\n- 並列:**R1 育 偕楽園 + 水戸芸術館 + R1 育 県近代美 = 茨城美術館 3 大**\n- 入館:**¥320**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["museum_art"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["ibaraki_kindai_bijutsukan", "1988"], source: "manual" },
  { slug: "ibaraki-prefectural-history-museum-1974", category: "culture", sub_type: "ibaraki_history_museum", title_zh: "茨城県立歴史館(水戸市・1974 開館+ R1 育 偕楽園隣接+ 茨城県内 縄文+古代+中世+近世+近代 通史+ 旧水海道小学校本館 国登録有形文化財 1881 移築+ 入館 ¥160)", title_ja: "茨城県立歴史館", romaji: "Ibaraki Rekishikan", summary_zh: "**茨城県立歴史館は 1974 開館**(水戸・**R1 育 偕楽園隣接**)。縄文-近代通史+旧水海道小学校本館 1881 国登録有形文化財移築、¥160。", content_md: "- 立地:**水戸市**(R1 育 偕楽園隣接)\n- 起源:**1974 開館 51 年**\n- 内容:**縄文 + 古代 + 中世 + 近世 + 近代 通史**\n- 認定:**旧水海道小学校本館 国登録有形文化財 1881 移築**\n- 入館:**¥160**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "水戸市", lg_code: "08201", area_types: ["museum_art", "history_site_castle"], lat: 36.3658, lon: 140.4711, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["ibaraki_rekishikan", "1974"], source: "manual" },
  { slug: "tsukuba-expo-center-1985", category: "culture", sub_type: "ibaraki_modern_art", title_zh: "つくばエキスポセンター(つくば市・1985 つくば博覧会記念開館 40 年+ プラネタリウム ¥500+ 全 4 階科学体験館+ 入館 ¥500(プラネ別)+ R1 育 つくば学園都市+JAXA 観光客向け代表+ 子供連れ向け代表)", title_ja: "つくばエキスポセンター", romaji: "Tsukuba Expo Center", summary_zh: "**つくばエキスポセンターは 1985 つくば博覧会記念開館 40 年**(つくば・**プラネタリウム+全 4 階科学体験館**)。R1 育 学園都市+JAXA 観光、¥500(プラネ別)、子供連れ代表。", content_md: "- 立地:**つくば市**\n- 起源:**1985 つくば博覧会記念 開館 40 年**\n- 構成:**プラネタリウム + 全 4 階科学体験館**\n- 入館:**¥500(プラネタリウム別)**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "つくば市", lg_code: "08220", area_types: ["museum_art"], lat: 36.0833, lon: 140.0764, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["tsukuba_expo_center", "1985"], source: "manual" },
  { slug: "tsukuba-jaxa-space-center", category: "culture", sub_type: "ibaraki_modern_art", title_zh: "JAXA 筑波宇宙センター(つくば市・1972 開設 53 年+ 日本宇宙開発機構本部・国際宇宙ステーション「きぼう」運用+ ロケット展示+宇宙服+ 入場無料(展示館)+ 観光客年間 30 万人来場+ R1 育 つくばエキスポセンターと並ぶ つくば科学観光 2 大)", title_ja: "JAXA 筑波宇宙センター", romaji: "JAXA Tsukuba Space Center", summary_zh: "**JAXA 筑波宇宙センターは 1972 開設 53 年**(つくば・**ISS「きぼう」運用+ロケット展示+宇宙服**)。年間 30 万人来場、無料(展示館)、R1 育 エキスポと並ぶ科学観光 2 大。", content_md: "- 立地:**つくば市**\n- 起源:**1972 開設 53 年**\n- 認定:**日本宇宙開発機構(JAXA)本部**\n- 構成:**国際宇宙ステーション「きぼう」運用 + ロケット展示 + 宇宙服**\n- 来場:**年間 30 万人**\n- 入場:**無料(展示館)**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "つくば市", lg_code: "08220", area_types: ["museum_art", "industrial_heritage"], lat: 36.0833, lon: 140.0764, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: 30, closed_days: ["月"], external_urls: { official: "https://fanfun.jaxa.jp/visit/tsukuba/" }, tags: ["jaxa_tsukuba", "1972", "kibo_iss"], source: "manual" },
  { slug: "kanto-3-tojo-tsuchiura", category: "culture", sub_type: "ibaraki_history_museum", title_zh: "土浦城跡+亀城公園(土浦市・1429 室町期築城+ 1873 廃城+ 国登録有形文化財・東櫓+ 西櫓 1998 復元+ 県史跡+ R1 衣 真壁石燈籠 関東 と組合せ+ 入場無料・櫓内 ¥105+ 桜名所 4 月)", title_ja: "土浦城跡+亀城公園", romaji: "Tsuchiura-jō / Kijo Park", summary_zh: "**土浦城跡+亀城公園は 1429 室町期築城+1873 廃城・1998 西櫓復元**(土浦・**国登録有形文化財・東櫓**)。県史跡、桜名所、無料・櫓内 ¥105。", content_md: "- 立地:**土浦市**\n- 起源:**1429 室町期築城・1873 廃城・1998 西櫓復元**\n- 認定:**国登録有形文化財・東櫓 + 県史跡**\n- 期:**桜名所 4 月**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "土浦市", lg_code: "08203", area_types: ["history_site_castle", "scenic_spot"], lat: 36.0786, lon: 140.2042, season_start: "2026-04-01", season_end: "2026-04-15", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tsuchiura_jo", "1429", "1873_abolished"], source: "manual" },

  // つくば+JAXA (3)
  { slug: "ushiku-shaen-park-japan-3-largest", category: "culture", sub_type: "ibaraki_history_museum", title_zh: "牛久シャトーカミヤ庭園(牛久市・R1 食 牛久シャトー 1903 派生・国登録有形文化財・大規模赤レンガ建造物+ 「日本三大ワイナリー」候補+ 神谷伝兵衛醸造所+ 入場無料・庭園+ R1 育 牛久大仏 120m と組合せ)", title_ja: "牛久シャトー庭園", romaji: "Ushiku Chateau Garden", summary_zh: "**牛久シャトーカミヤ庭園は R1 食 1903 派生・国登録有形文化財**(牛久・**大規模赤レンガ建造物・神谷伝兵衛醸造所**)。「日本三大ワイナリー」候補、無料・庭園、R1 育 牛久大仏組合せ。", content_md: "- 立地:**牛久市**\n- 関係:**R1 食 牛久シャトーカミヤ 1903 派生**\n- 認定:**国登録有形文化財・大規模赤レンガ建造物**\n- 縁:**神谷伝兵衛醸造所**\n- 並列:**R1 育 牛久大仏 120m**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "牛久市", lg_code: "08219", area_types: ["history_site_castle", "industrial_heritage"], lat: 35.9806, lon: 140.1408, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ushiku_chateau_garden"], source: "manual" },
  { slug: "kasama-craft-village", category: "culture", sub_type: "ibaraki_history_museum", title_zh: "茨城県陶芸美術館(笠間市・2000 開館+ R1 衣 笠間焼 1772 派生 公立陶芸専門美術館+ 全国陶芸作品 6000+ 点蔵品+ R1 衣 笠間焼陶芸の里隣接+ 入館 ¥320+ 県観光ハイライト陶芸文化拠点)", title_ja: "茨城県陶芸美術館", romaji: "Ibaraki Tōgei Bijutsukan", summary_zh: "**茨城県陶芸美術館は 2000 開館・公立陶芸専門美術館**(笠間・**R1 衣 笠間焼 1772 派生・全国陶芸 6000+ 点**)。R1 衣 笠間焼陶芸の里隣接、¥320。", content_md: "- 立地:**笠間市**(R1 衣 笠間焼陶芸の里隣接)\n- 起源:**2000 開館 25 年**\n- 関係:**R1 衣 笠間焼 1772 派生**\n- 認定:**公立陶芸専門美術館**\n- 蔵品:**全国陶芸作品 6000+ 点**\n- 入館:**¥320**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "笠間市", lg_code: "08216", area_types: ["museum_art"], lat: 36.3858, lon: 140.2614, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["ibaraki_togei_bijutsukan", "2000", "6000_works"], source: "manual" },
  { slug: "ooarai-isosaki-tortoise-shrine", category: "culture", sub_type: "ibaraki_shrine_temple", title_zh: "御岩神社(日立市・3000+ 年伝承・「日本最強パワースポット」全国 SNS 拡散・参拝対象 188 柱(日本国内最多)+ 県重要文化財・本殿+杉並木+三本杉(国指定天然記念物)+ 入場無料+ JR 常磐線 日立駅 タクシー 30 分)", title_ja: "御岩神社", romaji: "Oiwa Jinja", summary_zh: "**御岩神社は 3000+ 年伝承・「日本最強パワースポット」**(日立・**参拝対象 188 柱(日本国内最多)+三本杉国指定天然記念物**)。県重要文化財・本殿、無料、SNS 拡散。", content_md: "- 立地:**日立市**(JR 常磐線 日立駅 タクシー 30 分)\n- 起源:**3000+ 年伝承**\n- 認定:**「日本最強パワースポット」全国 SNS 拡散 + 参拝対象 188 柱(日本国内最多)**\n- 看板:**県重要文化財・本殿 + 杉並木 + 三本杉(国指定天然記念物)**", region: "kanto", prefecture_ja: "茨城県", gun_ja: null, municipality_ja: "日立市", lg_code: "08202", area_types: ["shrine_temple", "scenic_spot"], lat: 36.5961, lon: 140.6517, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["oiwa_jinja", "3000_years", "power_spot", "188_kami"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[ibaraki-culture-r1] 尚無條目"); return; }
  console.log(`[ibaraki-culture-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[ibaraki-culture-r1] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[ibaraki-culture-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[ibaraki-culture-r1] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
