// Seed 香川県 住 R1(20 筆 / Sprint 1.3 / 第十五卷)
// 高松 4 / 小豆島 5 / 直島 3 / 中讃 4 / 西讃 2 / 塩江温泉 2 = 20
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 高松 4
  {
    slug: "okura-takamatsu-1972",
    category: "lodging", sub_type: "kagawa_takamatsu_lodging",
    title_zh: "ホテルオークラ高松(高松市末広町・1972 開業 53+ 年+ 国内大手チェーン オークラホテルズ&リゾーツ・JR 高松駅徒歩 5 分・180 室+ 高松港+玉藻公園 R1 育 高松城跡隣接・¥18,000-45,000/泊+ 国際 SNS 海外旅行者代表)",
    title_ja: "ホテルオークラ高松", romaji: "Okura Takamatsu",
    summary_zh: "**ホテルオークラ高松は 1972 開業 53+ 年・国内大手チェーン オークラホテルズ&リゾーツ・JR 高松徒歩 5 分・180 室・高松港+玉藻公園隣接**(高松末広町)。¥18,000-45,000/泊。",
    content_md: "- 立地:**高松市末広町**\n- 起源:**1972 開業 53+ 年**\n- 規模:**180 室 + 国内大手チェーン オークラホテルズ&リゾーツ**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["accommodation_hotel"], lat: 34.3501, lon: 134.0494,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["okura_takamatsu_1972"], source: "manual",
  },
  {
    slug: "jr-clement-takamatsu-2000",
    category: "lodging", sub_type: "kagawa_takamatsu_lodging",
    title_zh: "JR ホテルクレメント高松(高松市浜ノ町・2000 開業 25+ 年+ JR 西日本グループ・JR 高松駅直結+ 高松港+ サンポート高松+ 高松シンボルタワー 2004 隣接+ 300 室+ 瀬戸内海眺望・¥15,000-32,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "JR クレメント高松", romaji: "JR Clement Takamatsu",
    summary_zh: "**JR ホテルクレメント高松は 2000 開業 25+ 年・JR 西日本グループ・JR 高松駅直結+サンポート高松+高松シンボルタワー 2004 隣接・300 室・瀬戸内海眺望**(高松浜ノ町)。¥15,000-32,000/泊。",
    content_md: "- 立地:**高松市浜ノ町**\n- 起源:**2000 開業 25+ 年**\n- 認定:**JR 西日本グループ + JR 高松駅直結 + サンポート高松 + 高松シンボルタワー 2004 隣接**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["accommodation_hotel"], lat: 34.3527, lon: 134.0494,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["jr_clement_2000"], source: "manual",
  },
  {
    slug: "rihga-zest-takamatsu-2003",
    category: "lodging", sub_type: "kagawa_takamatsu_lodging",
    title_zh: "リーガホテルゼスト高松(高松市古新町・2003 開業 22+ 年+ ロイヤルホテルチェーン・「ゼスト」JR 高松駅徒歩 8 分+ 高松丸亀町商店街 R1 食 1588 隣接+ 122 室・¥12,000-25,000/泊・国内+海外旅行者代表)",
    title_ja: "リーガゼスト高松", romaji: "Rihga Zest",
    summary_zh: "**リーガホテルゼスト高松は 2003 開業 22+ 年・ロイヤルホテル・JR 高松徒歩 8 分+丸亀町商店街 R1 食 1588 隣接・122 室**(高松古新町)。¥12,000-25,000/泊。",
    content_md: "- 立地:**高松市古新町**\n- 起源:**2003 開業 22+ 年**\n- 認定:**ロイヤルホテルチェーン + JR 高松駅徒歩 8 分 + 122 室**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["accommodation_hotel"], lat: 34.3401, lon: 134.0434,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["rihga_zest_2003"], source: "manual",
  },
  {
    slug: "takamatsu-station-business",
    category: "lodging", sub_type: "kagawa_takamatsu_lodging",
    title_zh: "高松駅前ビジネスホテル群(高松市浜ノ町+ 古馬場町・JR 高松駅+琴電瓦町駅前・東横イン+ アパ+ コンフォート+ 中堅ビジネスチェーン 25+ 軒+ 1 日 4 万人乗降観光客向・¥6,500-12,000/泊・出張+観光客代表)",
    title_ja: "高松駅前ビジネス", romaji: "Takamatsu Business",
    summary_zh: "**高松駅前ビジネスホテル群は JR 高松駅+琴電瓦町駅前・東横イン+アパ+コンフォート+中堅 25+ 軒・1 日 4 万人乗降**(高松浜ノ町+古馬場町)。¥6,500-12,000/泊。",
    content_md: "- 立地:**高松市浜ノ町 + 古馬場町**\n- 規模:**東横イン + アパ + コンフォート + 中堅ビジネスチェーン 25+ 軒**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["accommodation_hotel"], lat: 34.3401, lon: 134.0434,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["takamatsu_business"], source: "manual",
  },

  // 小豆島 5
  {
    slug: "shodoshima-olive-beach-hotel",
    category: "lodging", sub_type: "kagawa_islands_lodging",
    title_zh: "小豆島オリーブビーチホテル+ オリーブパレス(小豆島町・1990 年代以降オリーブテーマリゾート 35+ 年+ R1 食 オリーブ 1908+ R1 衣 オリーブアパレル派生・オリーブパレス+ オリーブガーデン+ オーシャンビュー+ ¥18,000-45,000/泊)",
    title_ja: "オリーブパレス", romaji: "Olive Palace",
    summary_zh: "**小豆島オリーブビーチホテル+オリーブパレスは 1990 年代以降オリーブテーマリゾート 35+ 年・R1 食+衣 派生・オリーブパレス+ガーデン+オーシャンビュー**(小豆島)。¥18,000-45,000/泊。",
    content_md: "- 立地:**小豆郡小豆島町**\n- 起源:**1990 年代以降オリーブテーマリゾート 35+ 年**\n- 関連:**R1 食 オリーブ 1908 + R1 衣 オリーブアパレル派生**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "小豆郡", municipality_ja: "小豆島町", lg_code: "37324",
    area_types: ["accommodation_hotel", "beach_coast"], lat: 34.4847, lon: 134.2500,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["olive_palace"], source: "manual",
  },
  {
    slug: "shodoshima-onsen",
    category: "lodging", sub_type: "kagawa_islands_lodging",
    title_zh: "小豆島温泉郷+ 塩湯温泉(土庄町+ 小豆島町・1973 開発 52+ 年+ 内海+ 池田+ 塩湯 3 大温泉郷・「ベイリゾートホテル小豆島」+ 「ホテル小豆島湯ノ里オリビアン」 老舗 12+ 軒+ オーシャンビュー・¥18,000-45,000/泊)",
    title_ja: "小豆島温泉", romaji: "Shōdoshima Onsen",
    summary_zh: "**小豆島温泉郷+塩湯温泉は 1973 開発 52+ 年・内海+池田+塩湯 3 大温泉郷・「ベイリゾート」+「オリビアン」老舗 12+ 軒**(土庄+小豆島町)。¥18,000-45,000/泊。",
    content_md: "- 立地:**小豆郡土庄町 + 小豆島町**\n- 起源:**1973 開発 52+ 年**\n- 規模:**内海 + 池田 + 塩湯 3 大温泉郷 + 老舗 12+ 軒**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "小豆郡", municipality_ja: "小豆島町", lg_code: "37324",
    area_types: ["onsen_natural", "accommodation_ryokan"], lat: 34.4847, lon: 134.2500,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["shodoshima_onsen"], source: "manual",
  },
  {
    slug: "kankakei-resort",
    category: "lodging", sub_type: "kagawa_islands_lodging",
    title_zh: "寒霞渓+ 二十四の瞳エリアホテル(小豆島町+ 土庄町・寒霞渓(全国 3 大渓谷美 1934 国指定名勝)+ 11 月紅葉名所+ R1 衣 24 の瞳映画村 1987 派生・「サン・オリーブ」+ 「マリン・パレスサヌキ」+ オーシャンビュー旅館 8+ 軒+ ¥15,000-35,000/泊)",
    title_ja: "寒霞渓リゾート", romaji: "Kankakei Resort",
    summary_zh: "**寒霞渓+24 の瞳エリアホテルは寒霞渓 国名勝 1934(全国 3 大渓谷美)・11 月紅葉名所・「サン・オリーブ」+「マリン・パレス」 8+ 軒**(小豆島+土庄)。¥15,000-35,000/泊。",
    content_md: "- 立地:**小豆郡小豆島町 + 土庄町**\n- 認定:**寒霞渓(全国 3 大渓谷美 1934 国指定名勝) + 11 月紅葉名所**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "小豆郡", municipality_ja: "小豆島町", lg_code: "37324",
    area_types: ["accommodation_ryokan", "nature_park"], lat: 34.4889, lon: 134.2378,
    season_start: "2026-11-01", season_end: "2026-11-30", event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kankakei_1934"], source: "manual",
  },
  {
    slug: "shodoshima-fukuya",
    category: "lodging", sub_type: "kagawa_islands_lodging",
    title_zh: "小豆島伝統旅館「福田屋」+ 旧家民宿(小豆島町福田・江戸期から漁師宿 250+ 年+ 福田港旧家民宿+ 海岸沿伝統旅館 8+ 軒+ R1 食 オリーブ三畜+つくだに連動・¥9,500-22,000/泊+ 1 泊 2 食付)",
    title_ja: "小豆島福田屋", romaji: "Shōdoshima Fukuya",
    summary_zh: "**小豆島伝統旅館「福田屋」+旧家民宿は江戸期から漁師宿 250+ 年・福田港旧家民宿+海岸沿伝統旅館 8+ 軒**(小豆島福田)。R1 食 オリーブ+つくだに連動、¥9,500-22,000/泊。",
    content_md: "- 立地:**小豆郡小豆島町福田**\n- 起源:**江戸期から漁師宿 250+ 年**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "小豆郡", municipality_ja: "小豆島町", lg_code: "37324",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 34.4847, lon: 134.2500,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["shodoshima_fukuya"], source: "manual",
  },
  {
    slug: "shodoshima-bnb",
    category: "lodging", sub_type: "kagawa_islands_lodging",
    title_zh: "小豆島民泊+ オリーブヴィラ+ 古民家ステイ(土庄町+小豆島町・1990 年代以降民泊 35+ 年+ 古民家リノベ+ オリーブ畑ヴィラ・「Olive Bay Hotel」+「島宿真里」 高級古民家・¥9,500-32,000/泊+ 国際 SNS 海外旅行者代表)",
    title_ja: "小豆島民泊", romaji: "Shōdoshima BnB",
    summary_zh: "**小豆島民泊+オリーブヴィラ+古民家は 1990 年代以降 35+ 年・古民家リノベ+オリーブ畑ヴィラ・「Olive Bay」+「島宿真里」**(土庄+小豆島)。¥9,500-32,000/泊、海外代表。",
    content_md: "- 立地:**小豆郡土庄町 + 小豆島町**\n- 起源:**1990 年代以降民泊 35+ 年**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "小豆郡", municipality_ja: "土庄町", lg_code: "37322",
    area_types: ["accommodation_ryokan"], lat: 34.4847, lon: 134.2500,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["shodoshima_bnb"], source: "manual",
  },

  // 直島 3
  {
    slug: "benesse-house-1992",
    category: "lodging", sub_type: "kagawa_naoshima_lodging",
    title_zh: "ベネッセハウス(香川郡直島町・1992 安藤忠雄設計開業 33+ 年+ 全国アート系ホテル発祥+ 65 室+ ベネッセハウスミュージアム併設+ 瀬戸内国際芸術祭 R1 楽 派生+ R1 衣 草間彌生連動・¥45,000-180,000/泊・国際 SNS 海外アートファン代表)",
    title_ja: "ベネッセハウス", romaji: "Benesse House",
    summary_zh: "**ベネッセハウスは 1992 安藤忠雄設計 33+ 年・全国アート系ホテル発祥・65 室・ミュージアム併設**(直島)。R1 楽+R1 衣 草間彌生連動、¥45,000-180,000/泊、海外アート代表。",
    content_md: "- 立地:**香川郡直島町**\n- 起源:**1992 安藤忠雄設計開業 33+ 年**\n- 認定:**全国アート系ホテル発祥 + 65 室 + ベネッセハウスミュージアム併設**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "香川郡", municipality_ja: "直島町", lg_code: "37364",
    area_types: ["accommodation_hotel", "museum_art"], lat: 34.4583, lon: 133.9967,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 90, closed_days: [],
    external_urls: {}, tags: ["benesse_house_1992", "ando_tadao"], source: "manual",
  },
  {
    slug: "naoshima-tsutsujiso",
    category: "lodging", sub_type: "kagawa_naoshima_lodging",
    title_zh: "直島つつじ荘+ 直島民宿(香川郡直島町・1992 ベネッセアート派生民宿+ つつじ荘 1990 年代開業+ パオ・コテージ・テント宿泊・直島港徒歩 5 分・¥7,500-22,000/泊・国際 SNS 海外バックパッカー代表)",
    title_ja: "直島つつじ荘", romaji: "Naoshima Tsutsujisō",
    summary_zh: "**直島つつじ荘+直島民宿は 1992 ベネッセ派生民宿・1990 年代開業・パオ+コテージ+テント宿泊・直島港徒歩 5 分**(直島)。¥7,500-22,000/泊、海外バックパッカー代表。",
    content_md: "- 立地:**香川郡直島町**\n- 起源:**1990 年代開業 35+ 年**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "香川郡", municipality_ja: "直島町", lg_code: "37364",
    area_types: ["accommodation_ryokan"], lat: 34.4583, lon: 133.9967,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["naoshima_tsutsujiso"], source: "manual",
  },
  {
    slug: "naoshima-island-bnb",
    category: "lodging", sub_type: "kagawa_naoshima_lodging",
    title_zh: "直島古民家民泊+ アート系ステイ(香川郡直島町本村+宮浦・本村地区古民家リノベ民泊 25+ 軒+「家プロジェクト」 1998 派生・地中美術館 2004+ R1 楽 草間彌生かぼちゃ連動・¥9,500-32,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "直島古民家", romaji: "Naoshima Kominka",
    summary_zh: "**直島古民家民泊+アート系ステイは本村古民家民泊 25+ 軒・「家プロジェクト」 1998 派生・地中美術館 2004+R1 楽 かぼちゃ連動**(直島本村+宮浦)。¥9,500-32,000/泊。",
    content_md: "- 立地:**香川郡直島町本村 + 宮浦**\n- 関連:**「家プロジェクト」 1998 派生 + 地中美術館 2004 + R1 楽 草間彌生かぼちゃ連動**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "香川郡", municipality_ja: "直島町", lg_code: "37364",
    area_types: ["accommodation_ryokan", "history_site_castle"], lat: 34.4583, lon: 133.9967,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["naoshima_kominka"], source: "manual",
  },

  // 中讃 4
  {
    slug: "kotohira-onsen-yumoto",
    category: "lodging", sub_type: "kagawa_chusan_lodging",
    title_zh: "琴平温泉+ 湯元ことひら温泉旅館(琴平町・1997 琴平温泉開湯 28+ 年+ R1 育 金刀比羅宮派生・「湯元こんぴら温泉華の湯紅梅亭」+「琴平花壇」+ 老舗旅館 12+ 軒+ ¥18,000-65,000/泊・JR 琴平駅徒歩 10 分)",
    title_ja: "琴平温泉", romaji: "Kotohira Onsen",
    summary_zh: "**琴平温泉+湯元ことひら旅館は 1997 開湯 28+ 年・R1 育 金刀比羅宮派生・「湯元こんぴら温泉華の湯紅梅亭」+「琴平花壇」 老舗 12+ 軒**(琴平)。¥18,000-65,000/泊。",
    content_md: "- 立地:**仲多度郡琴平町**\n- 起源:**1997 琴平温泉開湯 28+ 年**\n- 関連:**R1 育 金刀比羅宮派生**\n- 老舗:**「湯元こんぴら温泉華の湯紅梅亭」 + 「琴平花壇」 + 老舗旅館 12+ 軒**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "仲多度郡", municipality_ja: "琴平町", lg_code: "37404",
    area_types: ["onsen_natural", "accommodation_ryokan"], lat: 34.1856, lon: 133.8200,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["kotohira_onsen_1997"], source: "manual",
  },
  {
    slug: "marugame-station-business",
    category: "lodging", sub_type: "kagawa_chusan_lodging",
    title_zh: "丸亀駅前ビジネスホテル(丸亀市・JR 丸亀駅前+ 国宝丸亀城 R1 育 派生・東横イン+アパ+ ヴィアイン中堅 8+ 軒+ R1 食 丸亀骨付鳥+R1 衣 丸亀うちわ連動・¥6,500-12,000/泊+ 出張+観光客代表)",
    title_ja: "丸亀駅前ビジネス", romaji: "Marugame Business",
    summary_zh: "**丸亀駅前ビジネスホテルは JR 丸亀駅前+国宝丸亀城派生・東横イン+アパ+ヴィアイン 8+ 軒**(丸亀)。R1 食 骨付鳥+R1 衣 うちわ連動、¥6,500-12,000/泊、出張+観光代表。",
    content_md: "- 立地:**丸亀市**\n- 関連:**R1 育 国宝丸亀城派生 + R1 食 丸亀骨付鳥 + R1 衣 丸亀うちわ連動**\n- 規模:**東横イン + アパ + ヴィアイン中堅 8+ 軒**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "丸亀市", lg_code: "37202",
    area_types: ["accommodation_hotel"], lat: 34.2867, lon: 133.7944,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["marugame_business"], source: "manual",
  },
  {
    slug: "zentsuji-hotels",
    category: "lodging", sub_type: "kagawa_chusan_lodging",
    title_zh: "善通寺前ホテル+ 札所巡礼宿(善通寺市・R1 育 善通寺(第 75 番札所・空海生誕地)派生・「いろは旅館」「善通寺会館」遍路宿 6+ 軒+ R1 衣 四国遍路装束派生・¥7,500-22,000/泊+ JR 善通寺駅徒歩 10 分)",
    title_ja: "善通寺巡礼宿", romaji: "Zentsuji Pilgrim",
    summary_zh: "**善通寺前ホテル+札所巡礼宿は R1 育 善通寺(第 75 番空海生誕地)派生・「いろは旅館」「善通寺会館」遍路宿 6+ 軒**(善通寺)。R1 衣 遍路装束派生、¥7,500-22,000/泊。",
    content_md: "- 立地:**善通寺市**\n- 関連:**R1 育 善通寺(第 75 番札所・空海生誕地) + R1 衣 四国遍路装束派生**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "善通寺市", lg_code: "37204",
    area_types: ["accommodation_ryokan", "history_site_castle"], lat: 34.2244, lon: 133.7833,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["zentsuji_pilgrim"], source: "manual",
  },
  {
    slug: "tadotsu-station-hotels",
    category: "lodging", sub_type: "kagawa_chusan_lodging",
    title_zh: "多度津+ 坂出駅前ホテル(多度津町+坂出市・JR 多度津駅+JR 坂出駅前・瀬戸大橋 R1 行 派生+ 1988 瀬戸大橋開通連動ホテル開発・中堅 8+ 軒+ ¥6,500-12,000/泊・出張+ 瀬戸内観光客代表)",
    title_ja: "多度津坂出ホテル", romaji: "Tadotsu Sakaide",
    summary_zh: "**多度津+坂出駅前ホテルは JR 多度津+坂出駅前・1988 瀬戸大橋開通連動ホテル開発・中堅 8+ 軒**(多度津+坂出)。¥6,500-12,000/泊、瀬戸内観光客代表。",
    content_md: "- 立地:**仲多度郡多度津町 + 坂出市**\n- 関連:**1988 瀬戸大橋開通連動ホテル開発**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "仲多度郡", municipality_ja: "多度津町", lg_code: "37403",
    area_types: ["accommodation_hotel"], lat: 34.2742, lon: 133.7517,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["tadotsu_sakaide_hotels"], source: "manual",
  },

  // 西讃 2
  {
    slug: "kanonji-hotels",
    category: "lodging", sub_type: "kagawa_seisan_lodging",
    title_zh: "観音寺+ 三豊ホテル(観音寺市+三豊市・JR 観音寺駅+JR 詫間駅前+ R1 衣 父母ヶ浜+ 銭形砂絵+ 寛永通宝派生・「ホテルニュー観音寺」 + 「リゾートホテル オリビアン」 父母ヶ浜近接・¥9,500-25,000/泊)",
    title_ja: "観音寺三豊ホテル", romaji: "Kanonji Hotel",
    summary_zh: "**観音寺+三豊ホテルは JR 観音寺+詫間駅前・R1 衣 父母ヶ浜+銭形派生・「ニュー観音寺」+「オリビアン」父母ヶ浜近接**(観音寺+三豊)。¥9,500-25,000/泊。",
    content_md: "- 立地:**観音寺市 + 三豊市**\n- 関連:**R1 衣 父母ヶ浜 + 銭形砂絵 + 寛永通宝派生**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "観音寺市", lg_code: "37205",
    area_types: ["accommodation_hotel"], lat: 34.1267, lon: 133.6611,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kanonji_hotel"], source: "manual",
  },
  {
    slug: "chichibugahama-coastal",
    category: "lodging", sub_type: "kagawa_seisan_lodging",
    title_zh: "三豊父母ヶ浜+ 仁尾沿岸ヴィラ(三豊市仁尾+ 詫間町・R1 衣 父母ヶ浜 SNS 撮影聖地派生・1990 年代以降オーシャンビュー民泊 35+ 年+ 「ホテル感太呂」+「父母ヶ浜近接ヴィラ」+ ¥12,000-32,000/泊+ 国際 SNS 海外旅行者代表)",
    title_ja: "父母ヶ浜ヴィラ", romaji: "Chichibugahama Villa",
    summary_zh: "**三豊父母ヶ浜+仁尾沿岸ヴィラは R1 衣 SNS 撮影聖地派生・1990 年代以降民泊 35+ 年・「感太呂」+「父母ヶ浜近接ヴィラ」**(三豊仁尾+詫間)。¥12,000-32,000/泊、海外代表。",
    content_md: "- 立地:**三豊市仁尾 + 詫間町**\n- 関連:**R1 衣 父母ヶ浜 SNS 撮影聖地派生**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "三豊市", lg_code: "37207",
    area_types: ["accommodation_ryokan", "beach_coast"], lat: 34.2167, lon: 133.6500,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["chichibugahama_villa"], source: "manual",
  },

  // 塩江温泉 2
  {
    slug: "shionoe-onsen",
    category: "lodging", sub_type: "kagawa_takamatsu_lodging",
    title_zh: "塩江温泉郷(高松市塩江町・行基 729 開湯伝承 1296+ 年+ 県内最古温泉候補+ 香川県唯一の「塩江温泉郷」+ 「ホテルセカンドステージ」+ 「行基の湯」 老舗 8+ 軒+ ¥9,500-22,000/泊・JR 高松駅+バス 50 分)",
    title_ja: "塩江温泉郷", romaji: "Shionoe Onsen",
    summary_zh: "**塩江温泉郷は行基 729 開湯伝承 1296+ 年・県内最古温泉候補・香川県唯一の「塩江温泉郷」・「セカンドステージ」+「行基の湯」 老舗 8+ 軒**(高松塩江)。¥9,500-22,000/泊。",
    content_md: "- 立地:**高松市塩江町**\n- 起源:**行基 729 開湯伝承 1296+ 年**\n- 認定:**県内最古温泉候補 + 香川県唯一の「塩江温泉郷」**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["onsen_natural", "accommodation_ryokan"], lat: 34.2017, lon: 134.0306,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["shionoe_onsen_729"], source: "manual",
  },
  {
    slug: "takamatsu-airport-hotels",
    category: "lodging", sub_type: "kagawa_takamatsu_lodging",
    title_zh: "高松空港前ホテル+ 仏生山温泉(高松市仏生山+空港前・1989 高松空港開港 36+ 年+ 1898 仏生山温泉開湯 127+ 年+ 「仏生山温泉天平湯」+ 高松空港前ホテル 5+ 軒+ ¥9,500-18,000/泊・国際 SNS 海外旅行者代表)",
    title_ja: "高松空港前+仏生山", romaji: "Takamatsu Airport Hotel",
    summary_zh: "**高松空港前ホテル+仏生山温泉は 1989 空港 36+ 年+1898 仏生山温泉 127+ 年・「天平湯」+空港前 5+ 軒**(高松仏生山+空港)。¥9,500-18,000/泊、海外代表。",
    content_md: "- 立地:**高松市仏生山 + 空港前**\n- 起源:**1989 高松空港開港 36+ 年 + 1898 仏生山温泉開湯 127+ 年**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["accommodation_hotel", "onsen_natural"], lat: 34.2161, lon: 134.0156,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["takamatsu_airport_hotel"], source: "manual",
  },
];

seedMain(rows, "kagawa-lodging-r1");
