// Seed 岩手県 楽 R1(20 筆 / Sprint 1.5)
//
// 祭 4 / 平泉行事 2 / 三陸景勝 4 / 内陸景勝 3 / 観光列車 3 / アウトドア 4 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: "entertainment";
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "tohoku";
  prefecture_ja: "岩手県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // 祭 (4)
  {
    slug: "morioka-sansa-odori",
    category: "entertainment",
    sub_type: "iwate_festivals",
    title_zh: "盛岡さんさ踊り(盛岡市・8 月 1-4 日 4 日間+ 太鼓同時演奏ギネス世界記録 2007 認定+ 全国最大太鼓パフォーマンス・盛岡市中央通+ 1,万人参加+ 来訪 150 万人+ 東北 5 大祭の一)",
    title_ja: "盛岡さんさ踊り",
    romaji: "Morioka Sansa Odori",
    summary_zh: "**盛岡さんさ踊りは全国最大太鼓パフォーマンス**(盛岡市・**8 月 1-4 日 4 日間**)。**太鼓同時演奏ギネス世界記録 2007 認定 + 1,万人参加 + 来訪 150 万人 + 東北 5 大祭(青森ねぶた + 仙台七夕 + 秋田竿燈 + 盛岡さんさ + 山形花笠)の一**、青森ねぶた(R1 楽)と並ぶ岩手代表夏祭。",
    content_md: "- 開催:**毎年 8 月 1-4 日**(4 日間)\n- 認定:**ギネス世界記録 2007**(太鼓同時演奏数)\n- 規模:**1 万人参加 + 太鼓 + 笛 + 踊り**\n- 来訪:**毎年 150 万人**\n- 並列:**東北 5 大祭(青森ねぶた + 仙台七夕 + 秋田竿燈 + 盛岡さんさ + 山形花笠)**\n- 並列宿:R1 住 メトロポリタン盛岡 + アパ青森駅前(6 ヶ月前予約)\n- 場所:盛岡市中央通(JR 盛岡駅 徒歩 15 分)",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "盛岡市",
    lg_code: "03201",
    area_types: ["festival_event"],
    lat: 39.7011,
    lon: 141.1547,
    season_start: null,
    season_end: null,
    event_start: "2026-08-01",
    event_end: "2026-08-04",
    price_tier: 1,
    booking_window_days: 180,
    closed_days: [],
    external_urls: { official: "https://www.sansaodori.jp/" },
    tags: ["sansa_odori", "august_1_4", "guinness_2007", "tohoku_5_matsuri"],
    source: "manual",
  },
  {
    slug: "hanamaki-matsuri",
    category: "entertainment",
    sub_type: "iwate_festivals",
    title_zh: "花巻まつり(花巻市・9 月第 2 金土日 3 日間+ 県内最大山車祭+ 24 山車 + 鹿踊り(国指定重要無形民俗)+ 神輿 100 基(全国最多)+ 1593 起源 432 年+ 来訪 50 万人)",
    title_ja: "花巻まつり",
    romaji: "Hanamaki Matsuri",
    summary_zh: "**花巻まつりは県内最大山車祭**(花巻市・**9 月第 2 金土日 3 日間**)。**24 山車 + 鹿踊り(国指定重要無形民俗)+ 神輿 100 基(全国最多)+ 1593 起源 432 年**、宮沢賢治記念館 R1 育 観光と組合せ、JR 花巻駅徒歩、来訪 50 万人。",
    content_md: "- 開催:**毎年 9 月第 2 金土日**(3 日間)\n- 起源:**1593 年・432 年**\n- 規模:**24 山車 + 鹿踊り(国指定重要無形民俗)+ 神輿 100 基(全国最多)**\n- 来訪:**毎年 50 万人**\n- 並列観光:R1 育 宮沢賢治記念館 + R1 食 花巻まなめん + R1 住 花巻温泉郷",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "花巻市",
    lg_code: "03205",
    area_types: ["festival_event"],
    lat: 39.3886,
    lon: 141.1175,
    season_start: null,
    season_end: null,
    event_start: "2026-09-11",
    event_end: "2026-09-13",
    price_tier: 1,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["hanamaki_matsuri", "september_2nd_weekend", "1593_origin", "100_mikoshi"],
    source: "manual",
  },
  {
    slug: "kitakami-michinoku-geino-matsuri",
    category: "entertainment",
    sub_type: "iwate_festivals",
    title_zh: "北上みちのく芸能まつり(北上市・8 月第 1 金土日 3 日間+ 1962 起源 63 年+ 北東北芸能 100+ 団体集結 + 鬼剣舞 + 鹿踊り 等東北 民俗芸能の祭典+ 北上展勝地 + 北上駅前)",
    title_ja: "北上みちのく芸能まつり",
    romaji: "Michinoku Geinō Matsuri",
    summary_zh: "**北上みちのく芸能まつりは北東北民俗芸能の祭典**(北上市・**8 月第 1 金土日 3 日間 + 1962 起源 63 年**)。**北東北芸能 100+ 団体集結 + 鬼剣舞 + 鹿踊り 等東北民俗芸能**、岩手代表民俗芸能の祭、北上展勝地 + 北上駅前会場、来訪 30 万人。",
    content_md: "- 開催:**毎年 8 月第 1 金土日**(3 日間)\n- 起源:**1962 年・63 年**\n- 規模:**北東北芸能 100+ 団体集結**\n- 主要芸能:**鬼剣舞 + 鹿踊り + さんさ踊り + 神楽**\n- 並列観光:**北上展勝地桜(R1 育 楽)+ 北上駅前**\n- 来訪:**毎年 30 万人**",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "北上市",
    lg_code: "03206",
    area_types: ["festival_event"],
    lat: 39.2872,
    lon: 141.1167,
    season_start: null,
    season_end: null,
    event_start: "2026-08-07",
    event_end: "2026-08-09",
    price_tier: 1,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["michinoku_geino", "august_1st_weekend", "1962_origin", "100_groups"],
    source: "manual",
  },
  {
    slug: "kitakami-tenshochi-sakura",
    category: "entertainment",
    sub_type: "iwate_festivals",
    title_zh: "北上展勝地桜まつり(北上市・1921 開園 104 年+ 4 月中-下旬+ 桜 1 万本(全国 5 大桜名所)+ 北上川沿岸 2km 桜並木+ 観光船 + 馬車 + 期間ライトアップ+ 来訪 100 万人)",
    title_ja: "北上展勝地桜",
    romaji: "Kitakami Tenshōchi Sakura",
    summary_zh: "**北上展勝地は全国 5 大桜名所**(北上市・**1921 開園 104 年**)。**4 月中-下旬 + 桜 1 万本 + 北上川沿岸 2km 桜並木 + 観光船 + 馬車 + 期間ライトアップ**、青森弘前公園(R1 楽・日本三大桜)に並ぶ北東北桜名所、JR 東北新幹線 北上駅徒歩 25 分、来訪 100 万人。",
    content_md: "- 立地:**北上市立花**(JR 東北新幹線 北上駅 徒歩 25 分・北上川沿岸)\n- 開園:**1921 年・104 年**\n- 規模:**桜 1 万本 + 2km 桜並木**\n- 認定:**全国 5 大桜名所**(青森弘前 + 福島鶴ヶ城 + 山梨実相寺 + 京都嵐山 + 北上展勝地)\n- 期:**4 月中-下旬**(年により変動)\n- 行事:**観光船 + 馬車 + 期間ライトアップ**\n- 来訪:**毎年 100 万人**\n- 並列:**青森弘前さくらまつり R1(三大桜)+ 岩手北上展勝地(5 大桜)= 北東北桜 2 大**",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "北上市",
    lg_code: "03206",
    area_types: ["festival_event", "scenic_spot"],
    lat: 39.2992,
    lon: 141.1342,
    season_start: null,
    season_end: null,
    event_start: "2026-04-15",
    event_end: "2026-04-30",
    price_tier: 1,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["kitakami_tenshochi", "1921", "10000_sakura", "japan_5_sakura"],
    source: "manual",
  },

  // 平泉行事 (2)
  {
    slug: "haru-no-fujiwara-matsuri",
    category: "entertainment",
    sub_type: "iwate_hiraizumi_event",
    title_zh: "春の藤原まつり(平泉町・5 月 1-5 日 5 日間+ 中尊寺 R1 育 + 毛越寺 R1 育 中心+ 義経公東下り行列 + 平泉時代行列+ 1965 開始 60 年+ 来訪 30 万人+ 平泉観光ピーク期)",
    title_ja: "春の藤原まつり",
    romaji: "Haru no Fujiwara Matsuri",
    summary_zh: "**春の藤原まつりは平泉観光ピーク期**(西磐井郡平泉町・**5 月 1-5 日 5 日間**)。**中尊寺 + 毛越寺中心 + 義経公東下り行列 + 平泉時代行列 + 1965 開始 60 年**、奥州藤原氏 4 代世遺の年に 2 回ある祭の春祭、来訪 30 万人、JR 平泉駅徒歩各寺院。",
    content_md: "- 開催:**毎年 5 月 1-5 日**(5 日間・GW 包含)\n- 開始:**1965 年・60 年**\n- 中心会場:**中尊寺 + 毛越寺(R1 育 平泉世遺)**\n- 名物:**義経公東下り行列 + 平泉時代行列**\n- 来訪:**毎年 30 万人**\n- 並列:R1 楽 春の藤原まつり(5 月)+ 秋の藤原まつり(11 月)= 平泉年 2 大祭",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: "西磐井郡",
    municipality_ja: "平泉町",
    lg_code: "03402",
    area_types: ["festival_event", "shrine_temple"],
    lat: 38.9914,
    lon: 141.0986,
    season_start: null,
    season_end: null,
    event_start: "2026-05-01",
    event_end: "2026-05-05",
    price_tier: 1,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["haru_fujiwara", "may_1_5", "1965_started", "yoshitsune_gyoretsu"],
    source: "manual",
  },
  {
    slug: "aki-no-fujiwara-matsuri",
    category: "entertainment",
    sub_type: "iwate_hiraizumi_event",
    title_zh: "秋の藤原まつり(平泉町・11 月 1-3 日 3 日間+ 紅葉ピーク期重複+ 中尊寺 R1 育 紅葉ライトアップ + 毛越寺特別公開+ 来訪 20 万人+ 春祭 GW 期 vs 秋祭 紅葉期 で観光客分散)",
    title_ja: "秋の藤原まつり",
    romaji: "Aki no Fujiwara Matsuri",
    summary_zh: "**秋の藤原まつりは紅葉ピーク期の平泉祭**(西磐井郡平泉町・**11 月 1-3 日 3 日間**)。**紅葉ピーク期重複 + 中尊寺紅葉ライトアップ + 毛越寺特別公開**、春祭(GW)+ 秋祭(紅葉)で観光客分散、来訪 20 万人、平泉観光秋ピーク。",
    content_md: "- 開催:**毎年 11 月 1-3 日**(3 日間)\n- 重複期:**紅葉ピーク期**\n- 中心:**中尊寺紅葉ライトアップ + 毛越寺特別公開**\n- 来訪:**毎年 20 万人**\n- 並列:R1 楽 春の藤原まつり(5 月 GW)+ 秋の藤原まつり(11 月紅葉)= 平泉年 2 大祭\n- 並列観光:R1 楽 厳美渓・猊鼻渓紅葉",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: "西磐井郡",
    municipality_ja: "平泉町",
    lg_code: "03402",
    area_types: ["festival_event", "scenic_spot"],
    lat: 38.9914,
    lon: 141.0986,
    season_start: null,
    season_end: null,
    event_start: "2026-11-01",
    event_end: "2026-11-03",
    price_tier: 1,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["aki_fujiwara", "november_1_3", "koyo_peak"],
    source: "manual",
  },

  // 三陸景勝 (4)
  {
    slug: "jodogahama-miyako",
    category: "entertainment",
    sub_type: "iwate_sanriku_scenic",
    title_zh: "浄土ヶ浜(宮古市・三陸復興国立公園・1996 国立公園+ 白色凝灰岩 + 松の緑 + エメラルドグリーン海面 = 「浄土」絶景+ 遊覧船+海水浴+ 浄土ヶ浜パークホテル R1 住 隣接)",
    title_ja: "浄土ヶ浜",
    romaji: "Jōdogahama",
    summary_zh: "**浄土ヶ浜は三陸復興国立公園代表景勝**(宮古市・**白色凝灰岩 + 松の緑 + エメラルドグリーン海面**)。**「浄土」絶景 + 遊覧船 + 海水浴**、青森仏ヶ浦(R1 楽・凝灰岩奇岩)に並ぶ太平洋側絶景、浄土ヶ浜パークホテル(R1 住)隣接、JR 山田線 + 三陸鉄道 宮古駅 → バス約 15 分。",
    content_md: "- 立地:**宮古市日立浜町**(JR 宮古駅 → バス 約 15 分)\n- 認定:**三陸復興国立公園 1996 → 2013 拡張**\n- 名物:**白色凝灰岩 + 松の緑 + エメラルドグリーン海面**\n- 並列:**青森仏ヶ浦(日本海凝灰岩奇岩)+ 岩手浄土ヶ浜(太平洋凝灰岩奇岩)= 北東北凝灰岩絶景 2 大**\n- 並列観光:R1 食 宮古鮭 + R1 住 浄土ヶ浜パークホテル + R1 楽 三陸鉄道リアス線\n- 入場:**無料**(遊覧船 ¥1,500-)",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "宮古市",
    lg_code: "03202",
    area_types: ["scenic_spot", "coastal"],
    lat: 39.6411,
    lon: 141.9722,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jodogahama", "national_park", "tuff_cliffs", "emerald_green"],
    source: "manual",
  },
  {
    slug: "kitayamazaki-tanohata",
    category: "entertainment",
    sub_type: "iwate_sanriku_scenic",
    title_zh: "北山崎海岸(下閉伊郡田野畑村・三陸復興国立公園・200m 断崖絶壁 8km+ 全国海岸景観評価日本一+ 5-7 月新緑 + 9-11 月紅葉+ 遊覧船+三陸鉄道リアス線島越駅から)",
    title_ja: "北山崎海岸",
    romaji: "Kitayamazaki",
    summary_zh: "**北山崎海岸は全国海岸景観評価日本一**(下閉伊郡田野畑村・**三陸復興国立公園**)。**200m 断崖絶壁 8km + 5-7 月新緑 + 9-11 月紅葉 + 遊覧船**、浄土ヶ浜(R1 楽 凝灰岩)と異なる断崖絶壁系絶景、三陸鉄道リアス線島越駅から、レンタカー推奨。",
    content_md: "- 立地:**下閉伊郡田野畑村**(三陸鉄道リアス線 島越駅 → バス約 15 分)\n- 認定:**全国海岸景観評価日本一**(国土交通省評価)\n- 規模:**200m 断崖絶壁 8km**\n- 旬:**5-7 月新緑 + 9-11 月紅葉**\n- 並列:R1 楽 浄土ヶ浜(凝灰岩) + 北山崎(断崖) + 龍泉洞(鍾乳洞) + 碁石海岸(玄武岩) = 三陸景勝 4 大\n- 入場:**無料**(遊覧船 ¥1,500-)",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: "下閉伊郡",
    municipality_ja: "田野畑村",
    lg_code: "03485",
    area_types: ["scenic_spot", "coastal"],
    lat: 40.0150,
    lon: 141.8939,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kitayamazaki", "200m_cliffs", "8km", "national_top"],
    source: "manual",
  },
  {
    slug: "ryusendo-iwaizumi-cave",
    category: "entertainment",
    sub_type: "iwate_sanriku_scenic",
    title_zh: "龍泉洞(下閉伊郡岩泉町・日本三大鍾乳洞+ 国指定天然記念物 1938+ 全長 5 km(うち 700m 公開)+ 第 3 地底湖の「ドラゴンブルー」絶景+ 入洞 ¥1,100+ 三陸鉄道リアス線岩泉小本駅 → バス)",
    title_ja: "龍泉洞",
    romaji: "Ryūsendō",
    summary_zh: "**龍泉洞は日本三大鍾乳洞**(下閉伊郡岩泉町・**国指定天然記念物 1938**)。**全長 5 km(うち 700m 公開)+ 第 3 地底湖の「ドラゴンブルー」絶景**、山口秋芳洞 + 高知龍河洞 + 岩手龍泉洞 = 日本三大鍾乳洞、入洞 ¥1,100、三陸鉄道リアス線 岩泉小本駅 → バス約 30 分。",
    content_md: "- 立地:**下閉伊郡岩泉町**(三陸鉄道リアス線 岩泉小本駅 → バス 約 30 分)\n- 認定:**日本三大鍾乳洞**(山口秋芳洞 + 高知龍河洞 + 岩手龍泉洞)\n- 認定:**国指定天然記念物 1938**\n- 規模:**全長 5 km(うち 700m 公開)**\n- 名物:**第 3 地底湖「ドラゴンブルー」絶景**\n- 入洞:**¥1,100**\n- 営業:8:30-18:00",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: "下閉伊郡",
    municipality_ja: "岩泉町",
    lg_code: "03483",
    area_types: ["scenic_spot"],
    lat: 39.8467,
    lon: 141.7972,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.iwate-ryusendo.jp/" },
    tags: ["ryusendo", "japan_3_cave", "1938_natural", "dragon_blue"],
    source: "manual",
  },
  {
    slug: "goishi-kaigan-ofunato",
    category: "entertainment",
    sub_type: "iwate_sanriku_scenic",
    title_zh: "碁石海岸(大船渡市・三陸復興国立公園・国指定名勝+天然記念物 1937+ 玄武岩 + 礫が碁石(囲碁)に似て命名+ 「雷岩」「穴通磯」海食地形+ 大船渡駅から車 20 分)",
    title_ja: "碁石海岸",
    romaji: "Goishi Kaigan",
    summary_zh: "**碁石海岸は三陸復興国立公園の海食地形景勝**(大船渡市・**国指定名勝+天然記念物 1937**)。**玄武岩 + 礫が碁石(囲碁)に似て命名 + 「雷岩」「穴通磯」海食地形**、浄土ヶ浜(凝灰岩)+ 北山崎(断崖)+ 龍泉洞(鍾乳洞)+ 碁石(玄武岩)= 三陸景勝 4 大の南端、大船渡駅から車 20 分。",
    content_md: "- 立地:**大船渡市末崎町**(JR 三陸鉄道リアス線 盛駅 → 車 20 分)\n- 認定:**国指定名勝 + 天然記念物 1937**\n- 由来:**玄武岩礫が碁石(囲碁)に似て命名**\n- 名物:**「雷岩」「穴通磯」海食地形 + 遊歩道 6km**\n- 並列:R1 楽 浄土ヶ浜 + 北山崎 + 龍泉洞 + 碁石 = 三陸景勝 4 大\n- 入場:**無料**",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "大船渡市",
    lg_code: "03203",
    area_types: ["scenic_spot", "coastal"],
    lat: 39.0353,
    lon: 141.8042,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["goishi_kaigan", "1937_meisho", "basalt_cliffs"],
    source: "manual",
  },

  // 内陸景勝 (3)
  {
    slug: "genbikei-ichinoseki",
    category: "entertainment",
    sub_type: "iwate_inland_scenic",
    title_zh: "厳美渓(一関市・国指定名勝+天然記念物 1927+ 磐井川 2km の渓谷美+ 「空飛ぶだんご」名物(対岸からロープでだんご運搬)+ 平泉観光ルート上+ JR 一関駅 → バス約 20 分)",
    title_ja: "厳美渓",
    romaji: "Genbikei",
    summary_zh: "**厳美渓は一関代表渓谷景勝**(一関市・**国指定名勝+天然記念物 1927**)。**磐井川 2km の渓谷美 + 「空飛ぶだんご」名物(対岸からロープでだんご運搬)**、平泉観光ルート上、JR 一関駅 → バス約 20 分、一関餅本膳(R1 食)+ 平泉観光と組合せ、入場無料。",
    content_md: "- 立地:**一関市厳美町**(JR 一関駅 → バス 約 20 分)\n- 認定:**国指定名勝 + 天然記念物 1927**\n- 規模:**磐井川 2km 渓谷**\n- 名物:**「空飛ぶだんご」**(対岸からロープでだんご運搬・観光名物)\n- 並列観光:**平泉中尊寺 + 一関餅本膳 R1 食 + 猊鼻渓**\n- 並列:R1 楽 厳美渓 + 猊鼻渓 + 八幡平アスピーテライン = 岩手内陸景勝 3 大\n- 入場:**無料**",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "一関市",
    lg_code: "03209",
    area_types: ["scenic_spot"],
    lat: 38.9794,
    lon: 141.0481,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["genbikei", "1927_meisho", "flying_dango", "iwai_river"],
    source: "manual",
  },
  {
    slug: "geibikei-ichinoseki",
    category: "entertainment",
    sub_type: "iwate_inland_scenic",
    title_zh: "猊鼻渓(一関市東山町・国指定名勝 1925+ 砂鉄川 2km の渓谷+ 「日本三大渓谷美」+ 舟下り観光 90 分(船頭 「げいび追分」生唄)+ 厳美渓と並ぶ一関 2 大渓谷+ JR 大船渡線 猊鼻渓駅徒歩 5 分)",
    title_ja: "猊鼻渓",
    romaji: "Geibikei",
    summary_zh: "**猊鼻渓は日本三大渓谷美**(一関市東山町・**国指定名勝 1925**)。**砂鉄川 2km の渓谷 + 舟下り観光 90 分(船頭「げいび追分」生唄)**、厳美渓(R1 楽)と並ぶ一関 2 大渓谷、JR 大船渡線 猊鼻渓駅徒歩 5 分、舟下り ¥1,800、平泉+一関観光ルート上。",
    content_md: "- 立地:**一関市東山町長坂**(JR 大船渡線 猊鼻渓駅 徒歩 5 分)\n- 認定:**国指定名勝 1925 + 日本三大渓谷美**\n- 規模:**砂鉄川 2km 渓谷**\n- 舟下り:**90 分・¥1,800・船頭「げいび追分」生唄**\n- 並列:R1 楽 厳美渓 + 猊鼻渓 = 一関 2 大渓谷",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "一関市",
    lg_code: "03209",
    area_types: ["scenic_spot"],
    lat: 38.9961,
    lon: 141.4239,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["geibikei", "1925_meisho", "japan_3_keikoku", "geibi_oiwake"],
    source: "manual",
  },
  {
    slug: "hachimantai-aspite-line",
    category: "entertainment",
    sub_type: "iwate_inland_scenic",
    title_zh: "八幡平アスピーテライン(八幡平市・27.5km 山岳道路+ 4 月下-5 月上「雪の回廊」(雪壁 8m)+ 9-10 月紅葉+ 11-4 月通行止+ 八幡平温泉郷 R1 住 アクセス + JR 盛岡駅 → JR バス 約 90 分)",
    title_ja: "八幡平アスピーテライン",
    romaji: "Hachimantai Aspite Line",
    summary_zh: "**八幡平アスピーテラインは八幡平山岳ドライブ道路**(八幡平市・**27.5km 山岳道路**)。**4 月下-5 月上「雪の回廊」(雪壁 8m)+ 9-10 月紅葉 + 11-4 月通行止**、青森城ヶ倉大橋(R2 住)に並ぶ北東北山岳絶景、八幡平温泉郷 + 安比高原(R1 住)アクセス。",
    content_md: "- 立地:**八幡平市**(JR 盛岡駅 → JR バス 約 90 分)\n- 規模:**27.5km 山岳道路**\n- 旬:**4 月下-5 月上 雪の回廊(雪壁 8m)+ 9-10 月紅葉**\n- 通行可能期:**5-10 月**(11-4 月積雪通行止)\n- 並列観光:R1 住 八幡平温泉郷 + 安比高原 + 松川温泉 + R1 食 八幡平国産ホップ\n- 並列:R1 楽 厳美渓 + 猊鼻渓 + アスピーテライン = 内陸景勝 3 大",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "八幡平市",
    lg_code: "03214",
    area_types: ["scenic_spot", "mountain_village", "transit_hub"],
    lat: 39.9583,
    lon: 140.8597,
    season_start: "2026-04-25",
    season_end: "2026-10-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["aspite_line", "27_5km", "snow_corridor_8m", "may_october"],
    source: "manual",
  },

  // 観光列車 (3)
  {
    slug: "sanriku-railway-rias-line",
    category: "entertainment",
    sub_type: "iwate_local_train",
    title_zh: "三陸鉄道リアス線(久慈-盛 163km+ 2019 全通(東日本大震災 2011 後復興)+ 全国最長第三セクター鉄道+ NHK あまちゃん 2013 ロケ地効果+ 三陸沿岸 6 市 4 町 2 村 結ぶ復興道路)",
    title_ja: "三陸鉄道リアス線",
    romaji: "Sanriku Tetsudō Rias",
    summary_zh: "**三陸鉄道リアス線は全国最長第三セクター鉄道**(全 163km・**久慈-盛**)。**2019 全通(2011 大震災後復興)+ NHK あまちゃん 2013 ロケ地効果 + 三陸沿岸 6 市 4 町 2 村結ぶ復興道路**、青森八戸線リゾートうみねこ(R1 行)+ 三陸鉄道 = 三陸海岸鉄道 2 大、復興 + 観光双方の象徴。",
    content_md: "- 運行:**三陸鉄道**(久慈-盛 163km)\n- 全通:**2019 年・6 年**(2011 大震災後復興)\n- 認定:**全国最長第三セクター鉄道**\n- 効果:**NHK あまちゃん 2013 ロケ地観光ブースト**\n- 沿線:**久慈 + 田野畑 + 宮古 + 山田 + 大槌 + 釜石 + 大船渡 = 6 市 4 町 2 村**\n- 全区間:**¥3,780 / 約 4 時間**\n- 並列:**青森五能線リゾートしらかみ R1(青森-秋田 5h)+ 岩手三陸鉄道リアス線(163km 4h)= 北東北観光列車 2 大**",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "宮古市",
    lg_code: "03202",
    area_types: ["transit_hub", "scenic_spot"],
    lat: 39.6411,
    lon: 141.9553,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.sanrikutetsudou.com/" },
    tags: ["sanriku_railway", "2019_reopened", "163km", "amachan_2013", "third_sector"],
    source: "manual",
  },
  {
    slug: "jr-kamaishi-line-sl-ginga",
    category: "entertainment",
    sub_type: "iwate_local_train",
    title_zh: "JR 釜石線銀河ドリームライン(花巻-釜石 90km+ 宮沢賢治『銀河鉄道の夜』モチーフ+ SL 銀河 2014-2023 運行(現在引退)+ 現在は通常列車だが「銀河ドリームライン」愛称継承+ JR 花巻駅+遠野駅+釜石駅)",
    title_ja: "JR 釜石線銀河ドリームライン",
    romaji: "Kamaishi Line Ginga Dream",
    summary_zh: "**JR 釜石線銀河ドリームラインは宮沢賢治「銀河鉄道の夜」モチーフ路線**(JR 釜石線・**花巻-釜石 90km**)。**SL 銀河 2014-2023 運行(現在引退)+ 現在は通常列車だが「銀河ドリームライン」愛称継承**、宮沢賢治記念館 R1 育 + 遠野物語 R1 育 + 釜石ラグビー観光と組合せ。",
    content_md: "- 運行:**JR 釜石線**(花巻-釜石 90km)\n- モチーフ:**宮沢賢治『銀河鉄道の夜』(1934 発表)**\n- 過去:**SL 銀河 2014-2023 運行**(蒸気機関車 C58 239・2023 引退済)\n- 現在:**通常列車 + 「銀河ドリームライン」愛称継承**\n- 並列観光:R1 育 宮沢賢治記念館 + 遠野物語 + 釜石鉄博物館\n- 並列:R1 楽 三陸鉄道リアス線 + JR 釜石線銀河ドリーム = 岩手鉄道 2 大",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "花巻市",
    lg_code: "03205",
    area_types: ["transit_hub", "scenic_spot"],
    lat: 39.3886,
    lon: 141.1175,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kamaishi_line", "ginga_dream", "kenji_motif", "sl_2014_2023_retired"],
    source: "manual",
  },
  {
    slug: "amachan-rocation-tour",
    category: "entertainment",
    sub_type: "iwate_local_train",
    title_zh: "あまちゃん ロケ地巡り(久慈市・NHK 朝ドラ「あまちゃん」2013 ロケ地・小袖海岸+久慈駅+琥珀博物館+海女ふるさと食堂等+ 久慈市観光戦略の中心+ 三陸鉄道久慈駅徒歩 + 路線バス)",
    title_ja: "あまちゃんロケ地巡り",
    romaji: "Amachan Locations",
    summary_zh: "**あまちゃんロケ地巡りは久慈市観光戦略の中心**(久慈市・**NHK 朝ドラ「あまちゃん」2013 ロケ地**)。**小袖海岸(海女ふるさと)+ 久慈駅 + 琥珀博物館 + 海女ふるさと食堂 等**、2013 放送以来観光客大量訪問、三陸鉄道久慈駅徒歩 + 路線バス、NHK ドラマ効果の代表観光成功事例。",
    content_md: "- 立地:**久慈市**(JR 八戸線 + 三陸鉄道 久慈駅)\n- 効果:**NHK 朝ドラ「あまちゃん」2013 放送ロケ地**\n- 主要スポット:**小袖海岸(海女ふるさと) + 久慈駅 + 琥珀博物館 + 海女ふるさと食堂**\n- アクセス:**三陸鉄道久慈駅徒歩 + 小袖海岸まで バス 約 30 分**\n- 並列観光:R1 食 久慈うに丼 + R1 行 三陸鉄道リアス線\n- 並列:R1 楽 あまちゃんロケ地(久慈) + 銀河ドリームライン(花巻-釜石) + 三陸鉄道(久慈-盛) = 岩手観光列車+ロケ地 3 大",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "久慈市",
    lg_code: "03207",
    area_types: ["scenic_spot", "coastal"],
    lat: 40.1908,
    lon: 141.7753,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["amachan_2013", "kosode_kaigan", "nhk_drama_effect"],
    source: "manual",
  },

  // アウトドア (4)
  {
    slug: "hachimantai-trekking",
    category: "entertainment",
    sub_type: "iwate_outdoor",
    title_zh: "八幡平登山(八幡平山(1,613m)山頂・標高 1,541m 山頂駐車場 → 山頂往復 60 分の初心者向け+ 八幡平山頂湿原+ 6-10 月旬+ JR 盛岡駅 → JR バス 約 90 分・山頂レストハウス)",
    title_ja: "八幡平登山",
    romaji: "Hachimantai Tozan",
    summary_zh: "**八幡平登山は初心者向け山頂ハイキング**(八幡平市・**八幡平山 1,613m**)。**標高 1,541m 山頂駐車場 → 山頂往復 60 分の初心者向け + 八幡平山頂湿原 + 6-10 月旬**、青森八甲田大岳登山(R4 楽・1,584m 5-6h 中級)に対し岩手最高峰だが車で 1,541m まで・徒歩 60 分の超初心者向け。",
    content_md: "- 立地:**八幡平市八幡平**(JR 盛岡駅 → JR バス 約 90 分・山頂レストハウス)\n- 標高:**山頂 1,613m + 駐車場 1,541m**\n- 所要:**山頂往復 60 分**(初心者向け)\n- 旬:**6-10 月**(11-5 月積雪閉鎖)\n- 名物:**八幡平山頂湿原 + 八幡沼**\n- 並列:**青森八甲田大岳 R4(1,584m 5-6h 中級)+ 岩手八幡平(1,613m 60 分超初心者)= 北東北山岳 2 タイプ**",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "八幡平市",
    lg_code: "03214",
    area_types: ["scenic_spot", "mountain_village"],
    lat: 39.9472,
    lon: 140.8533,
    season_start: "2026-06-01",
    season_end: "2026-10-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hachimantai_tozan", "1613m", "60min_easy"],
    source: "manual",
  },
  {
    slug: "iwatesan-tozan",
    category: "entertainment",
    sub_type: "iwate_outdoor",
    title_zh: "岩手山登山(岩手県最高峰 2,038m・「南部富士」+ 6-10 月旬+ 馬返し登山口 → 山頂 5-6 時間中級+ 雫石町スキー場麓+ 雫石プリンス R1 住 + 鶯宿温泉ベース+ 山岳ベテラン向け)",
    title_ja: "岩手山登山",
    romaji: "Iwatesan Tozan",
    summary_zh: "**岩手山登山は岩手県最高峰**(岩手郡雫石町・**2,038m 「南部富士」**)。**6-10 月旬 + 馬返し登山口 → 山頂 5-6 時間中級**、青森岩木山(R1 楽・1,625m「津軽富士」)に並ぶ北東北富士、雫石町スキー場麓 + 雫石プリンス(R1 住)+ 鶯宿温泉(R1 住)ベース、山岳ベテラン向け。",
    content_md: "- 立地:**岩手郡雫石町**(JR 盛岡駅 → 路線バス 約 60 分・馬返し登山口)\n- 標高:**2,038m**(岩手県最高峰)\n- 別称:**「南部富士」**\n- 所要:**馬返し-山頂往復 5-6 時間**(中級)\n- 旬:**6 月-10 月**\n- 並列:**青森岩木山 R1(1,625m 津軽富士)+ 岩手山(2,038m 南部富士)= 北東北富士 2 大**\n- 並列宿:R1 住 鶯宿温泉 + 雫石プリンス + R1 育 小岩井農場",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: "岩手郡",
    municipality_ja: "雫石町",
    lg_code: "03301",
    area_types: ["scenic_spot", "mountain_village"],
    lat: 39.8528,
    lon: 141.0008,
    season_start: "2026-06-01",
    season_end: "2026-10-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["iwatesan", "2038m", "nanbu_fuji", "5_6h_intermediate"],
    source: "manual",
  },
  {
    slug: "appi-ski-resort",
    category: "entertainment",
    sub_type: "iwate_outdoor",
    title_zh: "安比高原スキー場(八幡平市・1981 開業 + 全国最大級+ 21 コース 47 ゲレンデ+ 12-5 月運営+ ホテル安比グランド R1 住 519 室直結+ JR 盛岡駅 → JR バス 約 50 分・全国スキーランク上位)",
    title_ja: "安比高原スキー場",
    romaji: "Appi Ski",
    summary_zh: "**安比高原スキー場は全国最大級スキーリゾート**(R1 住 安比高原で詳細・**1981 開業 44 年**)。**21 コース 47 ゲレンデ + 12-5 月運営**、青森八甲田スキー(R6 楽・上級オフピステ)+ 大鰐温泉スキー(R5 楽・中級 21 コース)に対し岩手最大スキー、ホテル安比グランド(R1 住・519 室)直結。",
    content_md: "- 立地:**八幡平市安比高原**(JR 盛岡駅 → JR バス 約 50 分)\n- 開業:**1981 年・44 年**\n- 規模:**21 コース 47 ゲレンデ**(全国最大級)\n- ホテル:**ホテル安比グランド R1 住 519 室直結**\n- 営業期:**12 月-5 月**\n- リフト 1 日券:**¥6,500**\n- 並列:**北海道ニセコ + 安比高原 + 蔵王 = 東北 3 大スキー**\n- 並列:**青森八甲田 R6(上級)+ 大鰐温泉 R5(中級)+ 安比高原(全レベル)= 北東北スキー 3 大**",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "八幡平市",
    lg_code: "03214",
    area_types: ["scenic_spot", "mountain_village"],
    lat: 39.9786,
    lon: 140.9972,
    season_start: "2026-12-01",
    season_end: "2027-05-15",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.appi.co.jp/" },
    tags: ["appi_ski", "1981", "21_courses_47_gerende", "all_levels"],
    source: "manual",
  },
  {
    slug: "koiwai-farm-shizukuishi-1891",
    category: "entertainment",
    sub_type: "iwate_outdoor",
    title_zh: "小岩井農場(雫石町・1891 創業 134 年+ 日本最古級民間総合農場+ 国登録有形文化財 21 棟(2008+2017 認定)+ 一本桜+岩手山眺望+ 観光乳業 + ジンギスカン+ JR 盛岡駅 → 路線バス 35 分)",
    title_ja: "小岩井農場",
    romaji: "Koiwai Nōjō",
    summary_zh: "**小岩井農場は日本最古級民間総合農場**(岩手郡雫石町・**1891 創業 134 年**)。**国登録有形文化財 21 棟(2008+2017 認定)+ 一本桜+岩手山眺望 + 観光乳業 + ジンギスカン**、東京三菱財閥小野義眞 + 岩崎彌之助 + 井上勝の 3 創業者 + 名前から命名、JR 盛岡駅 → 路線バス 35 分。",
    content_md: "- 立地:**岩手郡雫石町丸谷地 36-1**(JR 盛岡駅 → 路線バス 約 35 分)\n- 創業:**1891 年(明治 24)・134 年**\n- 規模:**3,000 ヘクタール**(東京山手線内側面積 5 倍)\n- 認定:**国登録有形文化財 21 棟(2008 + 2017)**\n- 名物:**一本桜(4 月下旬-5 月上旬)+ 岩手山眺望 + 観光乳業 + ジンギスカン**\n- 由来:**小野義眞 + 岩崎彌之助 + 井上勝**(明治期 3 創業者・各人名から命名)\n- 並列:R1 育 小岩井農場 + 岩手山 + 雫石プリンス R1 住 = 雫石町観光 3 大\n- 入園:**¥800**(まきば園)",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: "岩手郡",
    municipality_ja: "雫石町",
    lg_code: "03301",
    area_types: ["farm_field", "scenic_spot"],
    lat: 39.7894,
    lon: 141.0383,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.koiwai.co.jp/" },
    tags: ["koiwai", "1891", "134_years", "3000ha", "21_registered_cultural"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[iwate-entertainment-r1] 尚無條目");
    return;
  }
  console.log(`[iwate-entertainment-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(28)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[iwate-entertainment-r1] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[iwate-entertainment-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[iwate-entertainment-r1] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
