// Seed 岩手県 住 R1(20 筆 / Sprint 1.3)
//
// 花巻温泉郷 5 / 八幡平 3 / 盛岡市 3 / 平泉 2 / 三陸 4 / 他 3 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: "lodging";
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "tohoku";
  prefecture_ja: "岩手県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // 花巻温泉郷 (5)
  {
    slug: "hanamaki-onsen-overview",
    category: "lodging",
    sub_type: "iwate_hanamaki_onsen",
    title_zh: "花巻温泉郷(花巻市・1923 開湯 + 大規模開発・東北代表温泉郷+ 12 軒旅館 + 共同浴場+ 宮沢賢治ゆかり地+ 花巻空港 + JR 新花巻駅から無料シャトル)",
    title_ja: "花巻温泉",
    romaji: "Hanamaki Onsen",
    summary_zh: "**花巻温泉郷は東北代表温泉郷**(花巻市・**1923 開湯 + 大規模開発**)。**12 軒旅館 + 共同浴場 + 宮沢賢治ゆかり地**、いわて花巻空港 + JR 新花巻駅から無料シャトル、花巻温泉ホテル(花巻温泉株式会社運営の総合リゾート)が中心、青森浅虫温泉(R1 住 1190)に対し岩手代表内陸温泉。",
    content_md: "- 立地:**花巻市湯本**(JR 新花巻駅 → 無料シャトル 約 25 分)\n- 開湯:**1923 年・102 年(大規模開発)**\n- 規模:**12 軒旅館 + 共同浴場**\n- 中心:**花巻温泉ホテル**(総合リゾート)\n- 並列:**R1 食 花巻まなめん + R1 育 宮沢賢治記念館** 観光と組合せ\n- 価格:1 泊 2 食 ¥12,000-30,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "花巻市",
    lg_code: "03205",
    area_types: ["onsen_field"],
    lat: 39.4275,
    lon: 141.0936,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.hanamakionsen.co.jp/" },
    tags: ["hanamaki_onsen", "1923", "kenji_legend", "12_ryokans"],
    source: "manual",
  },
  {
    slug: "osawa-onsen-jisuibu",
    category: "lodging",
    sub_type: "iwate_hanamaki_onsen",
    title_zh: "大沢温泉(花巻市・1200 年開湯+ 自炊湯治宿(山水閣 + 自炊部 + 菊水館 3 棟)+ 国民保養温泉地+ 茅葺屋根 + 川沿露天風呂・全国湯治宿代表+ 花巻南温泉郷 5 湯の中心)",
    title_ja: "大沢温泉",
    romaji: "Ōsawa Onsen",
    summary_zh: "**大沢温泉は全国湯治宿代表**(花巻市・**1200 年開湯**)。**自炊湯治宿(山水閣 + 自炊部 + 菊水館 3 棟)+ 国民保養温泉地 + 茅葺屋根 + 川沿露天風呂**、花巻南温泉郷 5 湯の中心、青森酸ヶ湯(R1 住・1684 国民保養第 1 号)に並ぶ東北 2 大湯治宿、現代湯治文化の聖地。",
    content_md: "- 立地:**花巻市湯口**(JR 新花巻駅 → 路線バス 約 30 分)\n- 開湯:**1200 年(平安期)・825 年**\n- 構成:**山水閣(現代旅館) + 自炊部(湯治宿) + 菊水館(離れ)** 3 棟\n- 認定:**国民保養温泉地**\n- 名物:**茅葺屋根 + 川沿露天風呂(豊沢川沿岸)**\n- 並列:**青森酸ヶ湯 R1(国民保養第 1 号)+ 岩手大沢 = 東北 2 大湯治**\n- 価格:山水閣 ¥10,000-25,000 / 自炊部 ¥4,000-7,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "花巻市",
    lg_code: "03205",
    area_types: ["onsen_field", "mountain_village"],
    lat: 39.3736,
    lon: 141.0639,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.oosawaonsen.com/" },
    tags: ["osawa_onsen", "1200_year", "jisuibu", "national_health_spa"],
    source: "manual",
  },
  {
    slug: "namari-onsen-fujisanryo",
    category: "lodging",
    sub_type: "iwate_hanamaki_onsen",
    title_zh: "鉛温泉 藤三旅館(花巻市・600 年開湯+ 国登録有形文化財 1996+ 「白猿の湯」立ち湯(深さ 125cm 立位入浴)+ 自炊湯治宿+ 花巻南温泉郷 5 湯の一+ 川沿木造旅館)",
    title_ja: "鉛温泉 藤三旅館",
    romaji: "Namari Onsen Fujisan",
    summary_zh: "**鉛温泉 藤三旅館は 600 年開湯の湯治宿**(花巻市・**国登録有形文化財 1996**)。**「白猿の湯」立ち湯(深さ 125cm 立位入浴)+ 自炊湯治宿 + 川沿木造旅館**、花巻南温泉郷 5 湯の一、大沢温泉(R1 住)と並ぶ花巻代表湯治、宮沢賢治幼少期通い宿伝説。",
    content_md: "- 立地:**花巻市鉛**(JR 新花巻駅 → 路線バス 約 35 分)\n- 開湯:**600 年・室町期**\n- 認定:**国登録有形文化財 1996**\n- 名物:**「白猿の湯」立ち湯**(深さ 125cm 立位入浴・全国稀少)\n- 性格:**自炊湯治宿 + 川沿木造旅館**\n- 縁:**宮沢賢治幼少期通い宿伝説**\n- 並列:R1 住 大沢温泉 + 鉛温泉藤三 + 花巻温泉 = 花巻 3 大",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "花巻市",
    lg_code: "03205",
    area_types: ["onsen_field", "mountain_village"],
    lat: 39.3494,
    lon: 141.0306,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["namari_fujisan", "600_year", "1996_registered", "tachiyu_125cm"],
    source: "manual",
  },
  {
    slug: "shidotaira-onsen-hanamaki",
    category: "lodging",
    sub_type: "iwate_hanamaki_onsen",
    title_zh: "志戸平温泉(花巻市・660 年開湯+ 大型ホテル 系統+ 全 218 室+ 大浴場 + 露天 + 川沿風呂+ 家族向け花巻南温泉郷 5 湯の一+ 花巻空港 + JR 新花巻駅シャトル運行)",
    title_ja: "志戸平温泉",
    romaji: "Shidotaira Onsen",
    summary_zh: "**志戸平温泉は花巻南温泉郷の大型ホテル**(花巻市・**660 年開湯**)。**全 218 室 + 大浴場 + 露天 + 川沿風呂**、家族向け花巻南温泉郷 5 湯の一、いわて花巻空港 + JR 新花巻駅 シャトル運行、大沢温泉(湯治)+ 鉛温泉(立ち湯)+ 志戸平(現代大型)= 花巻南 3 タイプ。",
    content_md: "- 立地:**花巻市湯口**(JR 新花巻駅 → シャトル 約 25 分)\n- 開湯:**660 年・室町期**\n- 規模:**全 218 室**(花巻南温泉郷最大)\n- 性格:**家族向け現代大型ホテル**\n- 並列:R1 住 大沢温泉(湯治) + 鉛温泉(立ち湯) + 志戸平(現代大型) = 花巻南 3 タイプ\n- 価格:1 泊 2 食 ¥12,000-25,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "花巻市",
    lg_code: "03205",
    area_types: ["onsen_field"],
    lat: 39.3811,
    lon: 141.0794,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.shidotaira.co.jp/" },
    tags: ["shidotaira", "660_year", "218_rooms", "family"],
    source: "manual",
  },
  {
    slug: "oshuku-onsen-shizukuishi",
    category: "lodging",
    sub_type: "iwate_hanamaki_onsen",
    title_zh: "鶯宿温泉(雫石町・450 年開湯+ 盛岡藩主湯治場+ 7 軒旅館の温泉郷+ 花巻ではなく雫石町だが盛岡郊外の代表温泉郷+ 盛岡駅から路線バス 約 70 分・小岩井農場近接)",
    title_ja: "鶯宿温泉",
    romaji: "Ōshuku Onsen",
    summary_zh: "**鶯宿温泉は盛岡藩主湯治場由来温泉郷**(岩手郡雫石町・**450 年開湯**)。**7 軒旅館 + 盛岡郊外の代表温泉郷**、JR 盛岡駅から路線バス 約 70 分、R1 育 小岩井農場近接、青森大鰐温泉(R1 住・1190 津軽藩主湯治場)に相当する岩手藩主湯治場、花巻系とは別系統。",
    content_md: "- 立地:**岩手郡雫石町**(盛岡駅 → 路線バス 約 70 分)\n- 開湯:**450 年・戦国期**\n- 起源:**盛岡藩主湯治場**(青森大鰐温泉 R1 住・津軽藩主湯治場と並列)\n- 規模:**7 軒旅館**\n- 並列観光:**小岩井農場 + 雫石スキー場 + 岩手山登山**\n- 並列:R1 住 花巻南温泉郷 4(花巻+大沢+鉛+志戸平)+ 鶯宿(盛岡郊外)= 岩手内陸温泉 5 大\n- 価格:1 泊 2 食 ¥10,500-22,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: "岩手郡",
    municipality_ja: "雫石町",
    lg_code: "03301",
    area_types: ["onsen_field"],
    lat: 39.6900,
    lon: 140.9939,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["oshuku_onsen", "450_year", "morioka_han_yujiba", "shizukuishi"],
    source: "manual",
  },

  // 八幡平 (3)
  {
    slug: "hachimantai-onsen-overview",
    category: "lodging",
    sub_type: "iwate_hachimantai_onsen",
    title_zh: "八幡平温泉郷(八幡平市・八幡平山(1,613m)山麓+ 多数小規模温泉+ 国立公園内+ アスピーテライン雪の回廊春+ 紅葉秋+ スキー冬+ 4 季 4 用の登山+温泉拠点)",
    title_ja: "八幡平温泉",
    romaji: "Hachimantai Onsen",
    summary_zh: "**八幡平温泉郷は八幡平山麓の温泉拠点**(八幡平市・**八幡平山 1,613m 山麓**)。**多数小規模温泉 + 国立公園内 + アスピーテライン雪の回廊春 + 紅葉秋 + スキー冬**、青森八甲田秘湯(R1 住・酸ヶ湯+蔦+谷地)に並ぶ岩手代表山岳温泉、4 季 4 用の登山+温泉拠点。",
    content_md: "- 立地:**八幡平市**(JR 東北新幹線 盛岡駅 → JR バス 約 90 分)\n- 名物:**アスピーテライン雪の回廊(4-5 月)+ 紅葉(10 月)+ スキー(12-3 月)**\n- 規模:**多数小規模温泉 + 国立公園内**\n- 並列:**青森八甲田 4 秘湯(R1 住)+ 岩手八幡平温泉 = 北東北山岳温泉 2 大**\n- 並列観光:R1 楽 八幡平登山 + R1 食 八幡平国産ホップ\n- 価格:1 泊 2 食 ¥10,000-22,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "八幡平市",
    lg_code: "03214",
    area_types: ["onsen_field", "mountain_village"],
    lat: 39.9472,
    lon: 141.0772,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["hachimantai_onsen", "1613m", "national_park", "4_seasons"],
    source: "manual",
  },
  {
    slug: "appi-kogen-resort",
    category: "lodging",
    sub_type: "iwate_hachimantai_onsen",
    title_zh: "安比高原(八幡平市・1981 開業+ 全国最大級スキーリゾート+ 21 コース + 47 ゲレンデ+ ホテル安比グランド+ 全 519 室+ 国際 5 つ星級スキー場+ 12-5 月スキー期 + 6-11 月夏アクティビティ)",
    title_ja: "安比高原",
    romaji: "Appi Kōgen",
    summary_zh: "**安比高原は全国最大級スキーリゾート**(八幡平市・**1981 開業 44 年**)。**21 コース + 47 ゲレンデ + ホテル安比グランド + 全 519 室**、国際 5 つ星級スキー場、12-5 月スキー期 + 6-11 月夏アクティビティ、青森八甲田スキー(上級・R6 楽)+ 大鰐温泉スキー(R5 楽)に対し全国級リゾート。",
    content_md: "- 立地:**八幡平市安比高原**(JR 東北新幹線 盛岡駅 → JR バス 約 50 分)\n- 開業:**1981 年・44 年**\n- 規模:**21 コース + 47 ゲレンデ**(全国最大級)\n- ホテル:**ホテル安比グランド 全 519 室**\n- 営業期:**スキー 12-5 月 + 夏アクティビティ 6-11 月**\n- リフト 1 日券:**¥6,500**(2026 現在)\n- 並列:**北海道ニセコ + 安比高原 + 蔵王 = 東北 3 大スキー**",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "八幡平市",
    lg_code: "03214",
    area_types: ["scenic_spot", "mountain_village"],
    lat: 39.9786,
    lon: 140.9972,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.appi.co.jp/" },
    tags: ["appi_kogen", "1981", "44_years", "519_rooms", "21_courses"],
    source: "manual",
  },
  {
    slug: "matsukawa-onsen-iwate",
    category: "lodging",
    sub_type: "iwate_hachimantai_onsen",
    title_zh: "松川温泉(八幡平市・350 年開湯+ 国民保養温泉地+ 3 軒一軒宿(松楓荘+峡雲荘+松川荘)+ 白濁硫黄泉 + 露天風呂代表+ 八幡平アスピーテライン経由・冬期閉鎖あり)",
    title_ja: "松川温泉",
    romaji: "Matsukawa Onsen",
    summary_zh: "**松川温泉は八幡平の国民保養温泉地秘湯**(八幡平市・**350 年開湯**)。**国民保養温泉地 + 3 軒一軒宿(松楓荘 + 峡雲荘 + 松川荘)+ 白濁硫黄泉**、八幡平アスピーテライン経由・冬期閉鎖あり、青森酸ヶ湯(R1 住)に並ぶ東北秘湯の代表級。",
    content_md: "- 立地:**八幡平市松尾寄木**(JR 盛岡駅 → JR バス 約 100 分)\n- 開湯:**350 年・江戸初期**\n- 認定:**国民保養温泉地**\n- 規模:**3 軒一軒宿**(松楓荘 + 峡雲荘 + 松川荘)\n- 泉質:**白濁硫黄泉**\n- 営業期:**冬期(12-3 月)アスピーテライン閉鎖でアクセス制限**\n- 並列:**青森酸ヶ湯 R1(国民保養第 1 号)+ 岩手松川温泉(国民保養)= 東北秘湯 2 大**\n- 価格:1 泊 2 食 ¥10,500-18,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "八幡平市",
    lg_code: "03214",
    area_types: ["onsen_field", "mountain_village"],
    lat: 39.8917,
    lon: 140.9444,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["matsukawa_onsen", "350_year", "national_health_spa", "3_inns"],
    source: "manual",
  },

  // 盛岡市 (3)
  {
    slug: "metropolitan-morioka-hotel",
    category: "lodging",
    sub_type: "iwate_morioka_hotel",
    title_zh: "ホテル メトロポリタン盛岡(JR 盛岡駅前+ 1987 開業 38 年+ 全 374 室・盛岡市最大級ホテル+ JR 東日本グループ運営+ 観光・ビジネス両用+ 3 大麺 + 南部鉄器物販コーナー)",
    title_ja: "ホテル メトロポリタン盛岡",
    romaji: "Hotel Metropolitan Morioka",
    summary_zh: "**ホテル メトロポリタン盛岡は盛岡市最大級ホテル**(盛岡市・**1987 開業 38 年・JR 東日本グループ運営**)。**JR 盛岡駅前直結 + 全 374 室 + 観光・ビジネス両用**、青森ホテル青森(184 室・R1 住)に対する岩手代表大型ホテル、3 大麺 + 南部鉄器物販コーナー入り。",
    content_md: "- 立地:**盛岡市盛岡駅前北通 1-44**(JR 盛岡駅 徒歩 1 分)\n- 開業:**1987 年・38 年**\n- 規模:**全 374 室**(盛岡市最大級)\n- 運営:**JR 東日本グループ**\n- 設備:**全室バス付 + レストラン 5 軒 + 結婚式場**\n- 並列:**青森ホテル青森(184 室)+ 岩手メトロポリタン盛岡(374 室)= 北東北大型ホテル**\n- 価格:1 泊素泊 ¥12,000-25,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "盛岡市",
    lg_code: "03201",
    area_types: ["urban", "transit_hub"],
    lat: 39.7019,
    lon: 141.1361,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 180,
    closed_days: [],
    external_urls: { official: "https://morioka.metropolitan.jp/" },
    tags: ["metropolitan_morioka", "1987", "374_rooms", "jr_east"],
    source: "manual",
  },
  {
    slug: "mitsui-garden-morioka",
    category: "lodging",
    sub_type: "iwate_morioka_hotel",
    title_zh: "三井ガーデンホテル盛岡(盛岡市菜園・JR 盛岡駅 徒歩 13 分+ 2010 開業+ 全 158 室+ 大浴場あり+ 川徳百貨店徒歩 5 分・盛岡市内中心地+ 観光客 + ビジネス両用)",
    title_ja: "三井ガーデンホテル盛岡",
    romaji: "Mitsui Garden Morioka",
    summary_zh: "**三井ガーデンホテル盛岡は盛岡市内中心地中堅ホテル**(盛岡市菜園・**2010 開業 15 年**)。**JR 盛岡駅徒歩 13 分 + 全 158 室 + 大浴場あり**、川徳百貨店(R1 衣)徒歩 5 分の市内中心地、メトロポリタン(駅前 374 室)+ 三井ガーデン(中心地 158 室)= 盛岡市内 2 大。",
    content_md: "- 立地:**盛岡市菜園 1-3-7**(JR 盛岡駅 徒歩 13 分)\n- 開業:**2010 年・15 年**\n- 規模:**全 158 室**(中規模)\n- 設備:**全室バス付 + 大浴場あり**\n- 並列観光:**川徳百貨店(R1 衣) + 紺屋町商店街 R1 衣 鈴木盛久 釜定 徒歩**\n- 並列:R1 住 メトロポリタン(駅前) + 三井ガーデン(中心地) + ドーミーイン = 盛岡市 3 大\n- 価格:1 泊素泊 ¥10,500-18,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "盛岡市",
    lg_code: "03201",
    area_types: ["urban"],
    lat: 39.7011,
    lon: 141.1547,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["mitsui_garden_morioka", "2010", "158_rooms"],
    source: "manual",
  },
  {
    slug: "dormy-inn-morioka",
    category: "lodging",
    sub_type: "iwate_morioka_hotel",
    title_zh: "ドーミーイン盛岡(盛岡市・JR 盛岡駅 徒歩 7 分+ 全 198 室+ 天然温泉大浴場+ 夜泣きそば無料サービス+ 全国チェーン+ 観光・ビジネス両用代表中堅+ 朝食バイキング地元食材)",
    title_ja: "ドーミーイン盛岡",
    romaji: "Dormy Inn Morioka",
    summary_zh: "**ドーミーイン盛岡は全国チェーン中堅**(盛岡市・**JR 盛岡駅 徒歩 7 分**)。**全 198 室 + 天然温泉大浴場 + 夜泣きそば無料サービス + 朝食バイキング地元食材**、メトロポリタン(駅前 374 室)+ 三井ガーデン(中心地 158 室)+ ドーミーイン(駅近 198 室)= 盛岡市 3 大。",
    content_md: "- 立地:**盛岡市盛岡駅前通 7-15**(JR 盛岡駅 徒歩 7 分)\n- 規模:**全 198 室**\n- 名物:**天然温泉大浴場 + 夜泣きそば無料サービス**\n- 朝食:**バイキング・地元食材中心**\n- 並列:R1 住 メトロポリタン + 三井ガーデン + ドーミーイン = 盛岡市 3 大\n- 価格:1 泊素泊 ¥9,000-16,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "盛岡市",
    lg_code: "03201",
    area_types: ["urban", "transit_hub"],
    lat: 39.7028,
    lon: 141.1389,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.hotespa.net/hotels/morioka/" },
    tags: ["dormy_inn_morioka", "198_rooms", "natural_hot_spring", "yonaki_soba"],
    source: "manual",
  },

  // 平泉 (2)
  {
    slug: "hiraizumi-hotel-musashibo",
    category: "lodging",
    sub_type: "iwate_hiraizumi_lodge",
    title_zh: "平泉ホテル武蔵坊(平泉町・1957 創業 68 年+ 平泉中尊寺隣接ホテル+ 全 64 室+ 平泉観光の代表宿泊+ 中尊寺金色堂(R1 育)徒歩 5 分・毛越寺徒歩 8 分+ 平泉駅シャトル)",
    title_ja: "平泉ホテル武蔵坊",
    romaji: "Hiraizumi Hotel Musashibo",
    summary_zh: "**平泉ホテル武蔵坊は平泉中尊寺隣接ホテル**(西磐井郡平泉町・**1957 創業 68 年**)。**全 64 室 + 平泉観光の代表宿泊**、中尊寺金色堂(R1 育)徒歩 5 分 + 毛越寺徒歩 8 分、平泉駅シャトル運行、世界遺産観光に最便利の宿。",
    content_md: "- 立地:**平泉町平泉花立 39**(中尊寺金色堂 徒歩 5 分)\n- 創業:**1957 年・68 年**\n- 規模:**全 64 室**\n- 並列観光:**R1 育 中尊寺金色堂(国宝・世遺) + 毛越寺 + 観自在王院跡**\n- アクセス:**JR 東北本線 平泉駅 → ホテルシャトル 約 5 分**\n- 価格:1 泊 2 食 ¥13,000-25,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: "西磐井郡",
    municipality_ja: "平泉町",
    lg_code: "03402",
    area_types: ["onsen_field", "shrine_temple"],
    lat: 38.9931,
    lon: 141.1108,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["musashibo", "1957", "chusonji_adjacent"],
    source: "manual",
  },
  {
    slug: "ichinoseki-grand-hotel",
    category: "lodging",
    sub_type: "iwate_hiraizumi_lodge",
    title_zh: "一関グランドホテル(一関市・JR 一関駅徒歩 5 分・東北新幹線アクセス+ 全 145 室+ 平泉観光ベース+ 一関+平泉観光最便利ホテル+ R1 食 一関餅本膳提供レストランあり)",
    title_ja: "一関グランドホテル",
    romaji: "Ichinoseki Grand Hotel",
    summary_zh: "**一関グランドホテルは平泉観光ベース**(一関市・**JR 東北新幹線 一関駅徒歩 5 分**)。**全 145 室 + 一関+平泉観光最便利ホテル + R1 食 一関餅本膳提供レストランあり**、平泉ホテル武蔵坊(R1 住・平泉直近)+ 一関グランド(新幹線駅前)= 平泉宿 2 大。",
    content_md: "- 立地:**一関市駅前 1**(JR 東北新幹線 一関駅 徒歩 5 分)\n- 規模:**全 145 室**\n- 設備:**R1 食 一関餅本膳提供レストランあり**\n- 並列観光:**平泉中尊寺(車 15 分)+ 厳美渓 + 猊鼻渓**\n- 並列:R1 住 武蔵坊(平泉直近)+ 一関グランド(新幹線駅前)= 平泉宿 2 大\n- 価格:1 泊素泊 ¥9,500-16,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "一関市",
    lg_code: "03209",
    area_types: ["urban", "transit_hub"],
    lat: 38.9342,
    lon: 141.1264,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["ichinoseki_grand", "145_rooms", "shinkansen_front"],
    source: "manual",
  },

  // 三陸 (4)
  {
    slug: "jodogahama-park-hotel",
    category: "lodging",
    sub_type: "iwate_sanriku_lodge",
    title_zh: "浄土ヶ浜パークホテル(宮古市・浄土ヶ浜国立公園内・1971 開業 54 年+ 全 102 室+ 太平洋絶景大浴場+ 浄土ヶ浜遊覧船発着場徒歩+ 三陸鉄道リアス線 + JR 山田線宮古駅シャトル)",
    title_ja: "浄土ヶ浜パークホテル",
    romaji: "Jōdogahama Park Hotel",
    summary_zh: "**浄土ヶ浜パークホテルは浄土ヶ浜絶景宿**(宮古市・**1971 開業 54 年・浄土ヶ浜国立公園内**)。**全 102 室 + 太平洋絶景大浴場 + 浄土ヶ浜遊覧船発着場徒歩**、三陸鉄道リアス線 + JR 山田線宮古駅シャトル、青森不老ふ死(R1 住・日本海絶景)に対する太平洋側絶景代表。",
    content_md: "- 立地:**宮古市日立浜町 32-4**(浄土ヶ浜国立公園内)\n- 開業:**1971 年・54 年**\n- 規模:**全 102 室**\n- 名物:**太平洋絶景大浴場 + 浄土ヶ浜遊覧船発着場徒歩**\n- 並列:**青森不老ふ死(日本海絶景 R1)+ 岩手浄土ヶ浜パーク(太平洋絶景)= 三陸海岸絶景宿 2 大**\n- アクセス:**JR 山田線+三陸鉄道 宮古駅 → ホテルシャトル**\n- 価格:1 泊 2 食 ¥15,000-28,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "宮古市",
    lg_code: "03202",
    area_types: ["scenic_spot", "coastal"],
    lat: 39.6411,
    lon: 141.9722,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["jodogahama_park", "1971", "national_park", "pacific_view"],
    source: "manual",
  },
  {
    slug: "kamaishi-bay-city-hotel",
    category: "lodging",
    sub_type: "iwate_sanriku_lodge",
    title_zh: "釜石ベイシティホテル(釜石市・JR 釜石駅前 + 三陸鉄道リアス線・全 108 室+ 三陸沿岸観光ベース+ 釜石ラグビーワールドカップ 2019 後人気上昇+ 復興後の三陸代表ホテル)",
    title_ja: "釜石ベイシティホテル",
    romaji: "Kamaishi Bay City Hotel",
    summary_zh: "**釜石ベイシティホテルは三陸沿岸観光ベース**(釜石市・**JR 釜石駅 + 三陸鉄道リアス線徒歩**)。**全 108 室 + 釜石ラグビーワールドカップ 2019 後人気上昇 + 復興後の三陸代表ホテル**、釜石ラグビー + R1 食 釜石サンマ + R1 育 釜石鉄の博物館観光と組合せ。",
    content_md: "- 立地:**釜石市鈴子町 1-1**(JR 釜石駅 徒歩 1 分)\n- 規模:**全 108 室**\n- 影響:**釜石ラグビーワールドカップ 2019 後人気上昇**\n- 並列観光:R1 食 釜石サンマ + R1 育 釜石鉄の博物館\n- 並列:R1 住 浄土ヶ浜パーク(宮古) + 釜石ベイシティ + 久慈グランド + 三陸民宿 = 三陸 4 大\n- 価格:1 泊素泊 ¥8,500-15,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "釜石市",
    lg_code: "03203",
    area_types: ["urban", "coastal", "transit_hub"],
    lat: 39.2761,
    lon: 141.8839,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["kamaishi_bay_city", "108_rooms", "rugby_2019_boost"],
    source: "manual",
  },
  {
    slug: "kuji-grand-hotel",
    category: "lodging",
    sub_type: "iwate_sanriku_lodge",
    title_zh: "久慈グランドホテル(久慈市・JR 八戸線 + 三陸鉄道久慈駅徒歩 5 分+ 全 80 室+ 北三陸観光基幹+ NHK あまちゃん 2013 ロケ地観光宿泊基地+ R1 食 久慈うに丼 + 北三陸観光と組合せ)",
    title_ja: "久慈グランドホテル",
    romaji: "Kuji Grand Hotel",
    summary_zh: "**久慈グランドホテルは北三陸観光基幹**(久慈市・**JR 八戸線 + 三陸鉄道 久慈駅徒歩 5 分**)。**全 80 室 + NHK あまちゃん 2013 ロケ地観光宿泊基地 + R1 食 久慈うに丼観光と組合せ**、北三陸観光ベース、青森八戸 + 岩手久慈の三陸 trip 組合せに最適。",
    content_md: "- 立地:**久慈市中央 1-1-9**(JR 八戸線 + 三陸鉄道 久慈駅 徒歩 5 分)\n- 規模:**全 80 室**\n- 影響:**NHK あまちゃん 2013 ロケ地観光ブースト**\n- 並列観光:R1 食 久慈うに丼 + R1 楽 三陸鉄道リアス線\n- 並列宿:R1 住 浄土ヶ浜 + 釜石 + 久慈 + 三陸民宿 = 三陸 4 大\n- 価格:1 泊素泊 ¥8,000-14,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "久慈市",
    lg_code: "03207",
    area_types: ["urban", "coastal", "transit_hub"],
    lat: 40.1908,
    lon: 141.7753,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["kuji_grand", "80_rooms", "amachan_2013"],
    source: "manual",
  },
  {
    slug: "sanriku-minshuku-cluster",
    category: "lodging",
    sub_type: "iwate_sanriku_lodge",
    title_zh: "三陸沿岸民宿群(宮古 + 山田 + 大槌 + 大船渡 + 陸前高田・約 50 軒民宿+ 三陸海鮮料理付プラン+ 漁師まかない朝食+ 寒締ホタテ + 牡蠣 + サンマ + ホヤ料理代表+ レンタカー必須)",
    title_ja: "三陸民宿群",
    romaji: "Sanriku Minshuku",
    summary_zh: "**三陸沿岸民宿群は三陸海鮮料理付家族経営宿**(宮古-陸前高田・**約 50 軒民宿**)。**三陸海鮮料理付プラン + 漁師まかない朝食 + 寒締ホタテ + 牡蠣 + サンマ + ホヤ料理代表**、青森大間民宿(R1 住・本州最北鮪)に並ぶ漁村民宿、レンタカー推奨。",
    content_md: "- 立地:**宮古 + 山田 + 大槌 + 大船渡 + 陸前高田**(三陸沿岸全域)\n- 規模:**約 50 軒民宿**(家族経営密着型)\n- 食事:**三陸海鮮料理付 + 漁師まかない朝食**\n- 名物:**寒締ホタテ + 牡蠣 + サンマ + ホヤ + 鮭**\n- 並列:**青森大間民宿(R1 住・本州最北鮪)+ 岩手三陸民宿 = 北東北漁村民宿 2 大**\n- アクセス:**レンタカー推奨**(三陸鉄道 + 路線バスでも可)\n- 価格:1 泊 2 食 ¥9,000-18,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "宮古市",
    lg_code: "03202",
    area_types: ["coastal"],
    lat: 39.6411,
    lon: 141.9553,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["sanriku_minshuku", "50_inns", "fisherman_makanai"],
    source: "manual",
  },

  // 他 (3) — 北上 + 遠野 + 雫石プリンス
  {
    slug: "kitakami-station-hotel",
    category: "lodging",
    sub_type: "iwate_kitakami_lodge",
    title_zh: "北上駅前ホテル群(北上市・JR 東北新幹線 北上駅徒歩・全国チェーン主要+ アパホテル + ホテルメッツ等+ 北上展勝地桜 + 北上盆地観光ベース+ R1 食 花巻まなめん + 遠野ジンギスカン アクセス)",
    title_ja: "北上駅前ホテル",
    romaji: "Kitakami Eki Hotel",
    summary_zh: "**北上駅前ホテル群は北上盆地観光ベース**(北上市・**JR 東北新幹線 北上駅徒歩**)。**アパホテル + ホテルメッツ等 全国チェーン**、北上展勝地桜(R1 楽)+ 北上盆地観光、R1 食 花巻まなめん + 遠野ジンギスカン アクセス、北上市自体は中規模都市だが Day-trip 拠点として便利。",
    content_md: "- 立地:**北上市**(JR 東北新幹線 北上駅 徒歩圏)\n- 主要:**アパホテル北上駅前 + ホテルメッツ北上 + 北上シティホテル**\n- 並列観光:R1 楽 北上展勝地桜 + R1 育 北上盆地縄文遺跡 + R1 食 遠野ジンギスカン\n- 並列:R1 住 北上駅前 + 遠野民宿 + 雫石プリンス = 内陸他 3 大\n- 価格:1 泊素泊 ¥7,500-13,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "北上市",
    lg_code: "03206",
    area_types: ["urban", "transit_hub"],
    lat: 39.2872,
    lon: 141.1167,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["kitakami_eki_hotel", "shinkansen_station", "national_chains"],
    source: "manual",
  },
  {
    slug: "tono-folk-village-minshuku",
    category: "lodging",
    sub_type: "iwate_kitakami_lodge",
    title_zh: "遠野民宿群(遠野市・遠野物語 + 河童淵観光ベース・約 15 軒民宿+ 茅葺曲り家(まがりや)伝統民家+ ジンギスカン料理付+ JR 釜石線 遠野駅徒歩 + 自転車観光便利)",
    title_ja: "遠野民宿",
    romaji: "Tōno Minshuku",
    summary_zh: "**遠野民宿群は遠野物語観光ベース**(遠野市・**約 15 軒民宿 + 茅葺曲り家(まがりや)伝統民家**)。**ジンギスカン料理付(R1 食) + JR 釜石線 遠野駅徒歩 + 自転車観光便利**、青森津軽民宿に対する岩手内陸民宿、R1 育 遠野物語館 + 河童淵観光と組合せ。",
    content_md: "- 立地:**遠野市**(JR 釜石線 遠野駅 徒歩圏)\n- 規模:**約 15 軒民宿**(家族経営)\n- 特色:**茅葺曲り家(まがりや)伝統民家**\n- 食事:**ジンギスカン料理付**(R1 食 遠野ジンギスカン)\n- 並列観光:R1 育 遠野物語館 + 河童淵 + 遠野ふるさと村\n- 価格:1 泊 2 食 ¥9,000-15,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: null,
    municipality_ja: "遠野市",
    lg_code: "03208",
    area_types: ["mountain_village"],
    lat: 39.3294,
    lon: 141.5347,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["tono_minshuku", "magariya", "tono_monogatari"],
    source: "manual",
  },
  {
    slug: "shizukuishi-prince-hotel",
    category: "lodging",
    sub_type: "iwate_kitakami_lodge",
    title_zh: "雫石プリンスホテル(岩手郡雫石町・1989 開業 36 年+ 西武リゾート系・全 366 室+ 雫石スキー場 1993 世界スキー選手権開催+ 岩手山(2,038m)眺望+ 鶯宿温泉徒歩・小岩井農場近接)",
    title_ja: "雫石プリンスホテル",
    romaji: "Shizukuishi Prince Hotel",
    summary_zh: "**雫石プリンスホテルは雫石スキー場併設リゾート**(岩手郡雫石町・**1989 開業 36 年・西武リゾート系**)。**全 366 室 + 1993 世界スキー選手権開催 + 岩手山眺望**、鶯宿温泉(R1 住・450 年)徒歩 + 小岩井農場近接、安比高原(R1 住・1981)に並ぶ岩手代表大型リゾート。",
    content_md: "- 立地:**岩手郡雫石町**(JR 盛岡駅 → 路線バス 約 60 分)\n- 開業:**1989 年・36 年**\n- 規模:**全 366 室**(雫石町最大)\n- 縁:**1993 世界スキー選手権開催**\n- 並列観光:R1 育 小岩井農場 1891 + R1 住 鶯宿温泉徒歩\n- 並列:**安比高原 R1(全国級)+ 雫石プリンス(西武系) = 岩手大型リゾート 2 大**\n- 価格:1 泊 2 食 ¥18,000-35,000",
    region: "tohoku",
    prefecture_ja: "岩手県",
    gun_ja: "岩手郡",
    municipality_ja: "雫石町",
    lg_code: "03301",
    area_types: ["scenic_spot", "mountain_village"],
    lat: 39.7461,
    lon: 140.9994,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["shizukuishi_prince", "1989", "366_rooms", "1993_ski_championship"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[iwate-lodging-r1] 尚無條目");
    return;
  }
  console.log(`[iwate-lodging-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(28)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[iwate-lodging-r1] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[iwate-lodging-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[iwate-lodging-r1] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
