// Seed 栃木県 住 R1(20 筆 / Sprint 1.3)
// 鬼怒川+那須+塩原+日光奥+湯西川+ホテル代表

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "栃木県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  { slug: "nikko-kanaya-hotel-1873", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "日光金谷ホテル(日光市・1873 創業 152 年+ 日本最古リゾート級ホテル候補+ 国登録有形文化財・本館+別館+ 全 70 室・R1 育 日光東照宮 1617 UNESCO 1999 徒歩+ 1 泊 2 食 ¥25,000-65,000+ 海外 VIP 観光客代表)", title_ja: "日光金谷ホテル", romaji: "Nikkō Kanaya Hotel", summary_zh: "**日光金谷ホテルは 1873 創業 152 年・日本最古リゾート級ホテル候補・国登録有形文化財**(日光・**全 70 室**)。R1 育 日光東照宮徒歩、¥25,000-65,000、海外 VIP 観光客代表。", content_md: "- 立地:**日光市**\n- 起源:**1873 創業 152 年**\n- 認定:**日本最古リゾート級ホテル候補 + 国登録有形文化財**\n- 規模:**全 70 室・本館 + 別館**\n- 並列観光:**R1 育 日光東照宮 1617 UNESCO 1999**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["onsen_field", "history_site_castle"], lat: 36.7503, lon: 139.6133, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["nikko_kanaya", "1873", "152_years"], source: "manual" },
  { slug: "kinugawa-onsen-village-1691", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "鬼怒川温泉郷(日光市・1691 開湯 334 年+ 関東屈指温泉地+ 約 30 軒大型旅館+ 鬼怒川+川治源泉+ R1 行 東武鬼怒川線・浅草直通・1 泊 2 食 ¥12,500-35,000+ 国内+海外観光客最大温泉地代表)", title_ja: "鬼怒川温泉郷", romaji: "Kinugawa Onsen", summary_zh: "**鬼怒川温泉郷は 1691 開湯 334 年・関東屈指温泉地**(日光・**約 30 軒大型旅館**)。鬼怒川+川治源泉、R1 行 東武浅草直通、¥12,500-35,000、最大温泉地代表。", content_md: "- 立地:**日光市鬼怒川温泉**\n- 起源:**1691 開湯 334 年**\n- 認定:**関東屈指温泉地**\n- 規模:**約 30 軒大型旅館**\n- 並列交通:**R1 行 東武鬼怒川線・浅草直通**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["onsen_field"], lat: 36.8181, lon: 139.7022, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["kinugawa_onsen", "1691", "334_years"], source: "manual" },
  { slug: "kawaji-onsen-village", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "川治温泉(日光市・江戸期会津西街道宿場+ 鬼怒川温泉北 5km・全 10+ 軒小規模旅館+ 静かな大人の温泉地・R1 住 鬼怒川温泉郷 と並ぶ姉妹温泉+ 1 泊 2 食 ¥9,500-22,000)", title_ja: "川治温泉", romaji: "Kawaji Onsen", summary_zh: "**川治温泉は江戸期会津西街道宿場・鬼怒川温泉北 5km**(日光・**全 10+ 軒小規模旅館**)。静かな大人温泉地、R1 住 鬼怒川温泉郷姉妹、¥9,500-22,000。", content_md: "- 立地:**日光市川治**\n- 起源:**江戸期会津西街道宿場**\n- 距離:**鬼怒川温泉北 5km**\n- 規模:**全 10+ 軒小規模旅館**\n- 関係:**R1 住 鬼怒川温泉郷姉妹温泉**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["onsen_field"], lat: 36.8889, lon: 139.7083, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["kawaji_onsen", "edo_aizu_route"], source: "manual" },
  { slug: "nasu-onsen-village-630", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "那須温泉郷(那須町・630 創湯 1395 年+ 関東最古温泉郷候補・那須七湯・鹿の湯+大丸+三斗小屋+ 全 40+ 軒・R1 育 那須高原+R1 食 那須牛+1 泊 2 食 ¥10,500-30,000+ 海外 VIP 御用邸関連)", title_ja: "那須温泉郷", romaji: "Nasu Onsen", summary_zh: "**那須温泉郷は 630 創湯 1395 年・関東最古温泉郷候補**(那須・**那須七湯・鹿の湯+大丸+三斗小屋**)。全 40+ 軒、R1 育 那須高原+R1 食 那須牛、¥10,500-30,000、海外 VIP 御用邸関連。", content_md: "- 立地:**那須郡那須町**\n- 起源:**630 創湯 1395 年**\n- 認定:**関東最古温泉郷候補 + 那須七湯**\n- 規模:**全 40+ 軒**", region: "kanto", prefecture_ja: "栃木県", gun_ja: "那須郡", municipality_ja: "那須町", lg_code: "09407", area_types: ["onsen_field"], lat: 37.1247, lon: 139.9722, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["nasu_onsen", "630", "1395_years", "kanto_oldest"], source: "manual" },
  { slug: "shiobara-onsen-village-806", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "塩原温泉郷(那須塩原市・806 創湯 1219 年+ 「塩原十一湯」 那須塩原と並ぶ温泉地・全 60+ 軒+ R1 楽 紅葉名所 100 選+ 1 泊 2 食 ¥10,500-22,000+ 国内観光客向け代表)", title_ja: "塩原温泉郷", romaji: "Shiobara Onsen", summary_zh: "**塩原温泉郷は 806 創湯 1219 年・「塩原十一湯」**(那須塩原・**那須塩原温泉地、全 60+ 軒**)。R1 楽 紅葉名所 100 選、¥10,500-22,000、国内観光客代表。", content_md: "- 立地:**那須塩原市塩原**\n- 起源:**806 創湯 1219 年**\n- 認定:**「塩原十一湯」**\n- 規模:**全 60+ 軒**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "那須塩原市", lg_code: "09213", area_types: ["onsen_field"], lat: 36.9947, lon: 139.7794, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["shiobara_onsen", "806", "1219_years"], source: "manual" },
  { slug: "chuzenji-onsen-okunikko", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "中禅寺湖温泉+奥日光湯元温泉(日光市・標高 1269m+1500m 高原温泉・788 開湯候補+ 全 25+ 軒+ R1 育 中禅寺湖+華厳の滝(三名瀑) 観光連動+ 1 泊 2 食 ¥15,500-35,000+ 海外観光客代表)", title_ja: "中禅寺湖温泉+奥日光湯元", romaji: "Chūzenji Onsen", summary_zh: "**中禅寺湖温泉+奥日光湯元温泉は標高 1269m+1500m 高原温泉・788 開湯候補**(日光・**全 25+ 軒**)。R1 育 中禅寺湖+華厳の滝、¥15,500-35,000、海外観光客代表。", content_md: "- 立地:**日光市中禅寺湖 + 奥日光湯元**\n- 規模:**標高 1269m + 1500m 高原温泉**\n- 起源:**788 開湯候補**\n- 規模:**全 25+ 軒**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["onsen_field", "scenic_spot"], lat: 36.7375, lon: 139.4856, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["chuzenji_onsen", "788", "1500m"], source: "manual" },
  { slug: "yunishigawa-onsen-heike", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "湯西川温泉(日光市・1185 平家落人伝説 840 年+ 関東屈指秘湯+ 全 25+ 軒+ 「平家の里」R1 育 観光・1-2 月「かまくら祭り」雪国情緒+ 1 泊 2 食 ¥12,500-22,000+ R1 行 野岩鉄道湯西川温泉駅)", title_ja: "湯西川温泉", romaji: "Yunishigawa Onsen", summary_zh: "**湯西川温泉は 1185 平家落人伝説 840 年・関東屈指秘湯**(日光・**全 25+ 軒・「平家の里」**)。1-2 月かまくら祭り、¥12,500-22,000、R1 行 野岩鉄道湯西川温泉駅。", content_md: "- 立地:**日光市湯西川**\n- 起源:**1185 平家落人伝説 840 年**\n- 認定:**関東屈指秘湯**\n- 規模:**全 25+ 軒**\n- 並列文化:**「平家の里」+ 1-2 月かまくら祭**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["onsen_field", "history_site_castle"], lat: 36.9869, lon: 139.6736, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["yunishigawa_onsen", "heike_1185", "840_years"], source: "manual" },
  { slug: "kinugawa-asaya-hotel", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "鬼怒川温泉あさやホテル(日光市・1888 創業 137 年+ R1 住 鬼怒川温泉郷 1691 派生大型代表+ 全 168 室・本館+別館・展望露天+R1 食 鬼怒川あゆ+R1 食 日光ゆば会席+ 1 泊 2 食 ¥18,500-35,000)", title_ja: "鬼怒川あさやホテル", romaji: "Kinugawa Asaya", summary_zh: "**鬼怒川温泉あさやホテルは 1888 創業 137 年・R1 住 鬼怒川温泉郷大型代表**(日光・**全 168 室・本館+別館・展望露天**)。R1 食 あゆ+ゆば会席、¥18,500-35,000。", content_md: "- 立地:**日光市鬼怒川温泉**\n- 起源:**1888 創業 137 年**\n- 規模:**全 168 室 + 本館 + 別館 + 展望露天**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["onsen_field"], lat: 36.8181, lon: 139.7022, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["asaya_hotel", "1888"], source: "manual" },
  { slug: "kinugawa-park-hotels-modern", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "鬼怒川グランドホテル+パークホテルズ(日光市・1960-1990 年代開業大型観光ホテル群・全 200-450 室+ R1 住 鬼怒川温泉郷 派生・宴会大広間+大浴場+ 1 泊 2 食 ¥10,500-22,000+ 団体観光客向け代表)", title_ja: "鬼怒川グランド+パークホテルズ", romaji: "Kinugawa Grand Park", summary_zh: "**鬼怒川グランドホテル+パークホテルズは 1960-1990 年代開業大型観光ホテル群**(日光・**全 200-450 室**)。R1 住 鬼怒川温泉郷派生、団体観光客代表、¥10,500-22,000。", content_md: "- 立地:**日光市鬼怒川温泉**\n- 起源:**1960-1990 年代開業**\n- 規模:**全 200-450 室・大型観光ホテル群**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["onsen_field"], lat: 36.8181, lon: 139.7022, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["kinugawa_grand_park"], source: "manual" },
  { slug: "nasu-epinard-resort", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "ホテルエピナール那須(那須町・1989 開業 36 年+ 那須リゾートの中核ホテル+ 全 280 室・温泉+プール+体験+ R1 食 那須牛+R1 育 那須リゾート観光客代表+ 1 泊 2 食 ¥18,500-35,000)", title_ja: "ホテルエピナール那須", romaji: "Hotel Epinard Nasu", summary_zh: "**ホテルエピナール那須は 1989 開業 36 年・那須リゾートの中核ホテル**(那須・**全 280 室・温泉+プール+体験**)。R1 食 那須牛+R1 育 那須リゾート観光、¥18,500-35,000。", content_md: "- 立地:**那須郡那須町**\n- 起源:**1989 開業 36 年**\n- 規模:**全 280 室・那須リゾート中核**\n- 並列観光:**R1 食 那須牛 + R1 育 那須リゾート**", region: "kanto", prefecture_ja: "栃木県", gun_ja: "那須郡", municipality_ja: "那須町", lg_code: "09407", area_types: ["scenic_spot", "onsen_field"], lat: 36.9925, lon: 140.1175, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["epinard_nasu", "1989"], source: "manual" },
  { slug: "ritz-carlton-nikko-2020", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "ザ・リッツ・カールトン日光(日光市中禅寺湖・2020 開業 5 年+ 標高 1269m 中禅寺湖畔+ 全 94 室・国際 5 つ星ホテル・温泉+男体山眺望+ R1 育 華厳の滝+中禅寺湖観光連動+ 1 泊 ¥75,000-180,000+ 海外 VIP 代表)", title_ja: "リッツ・カールトン日光", romaji: "Ritz-Carlton Nikko", summary_zh: "**ザ・リッツ・カールトン日光は 2020 開業 5 年・標高 1269m 中禅寺湖畔・全 94 室・国際 5 つ星**(日光奥日光・**温泉+男体山眺望**)。R1 育 華厳の滝+中禅寺湖、¥75,000-180,000、海外 VIP 代表。", content_md: "- 立地:**日光市奥日光中禅寺湖畔**\n- 起源:**2020 開業 5 年**\n- 規模:**全 94 室 + 国際 5 つ星**\n- 並列観光:**R1 育 華厳の滝 + 中禅寺湖**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["scenic_spot", "onsen_field"], lat: 36.7375, lon: 139.4856, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: 120, closed_days: [], external_urls: {}, tags: ["ritz_carlton_nikko", "2020", "5_star"], source: "manual" },
  { slug: "utsunomiya-tobu-grande", category: "lodging", sub_type: "tochigi_mito_chuou", title_zh: "宇都宮東武ホテルグランデ(宇都宮市・1973 開業 52 年+ 県内老舗シティホテル代表・全 220 室+ JR 宇都宮駅西口徒歩 8 分+ R1 食 宇都宮餃子+R1 育 大谷資料館 観光客向け+ 1 泊 ¥10,500-18,500)", title_ja: "宇都宮東武ホテルグランデ", romaji: "Utsunomiya Tobu Grande", summary_zh: "**宇都宮東武ホテルグランデは 1973 開業 52 年・県内老舗シティホテル代表**(宇都宮・**全 220 室・JR 西口徒歩 8 分**)。R1 食 餃子+R1 育 大谷資料館、¥10,500-18,500。", content_md: "- 立地:**宇都宮市**(JR 宇都宮駅西口徒歩 8 分)\n- 起源:**1973 開業 52 年**\n- 規模:**全 220 室 + 県内老舗シティホテル代表**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["shopping_district"], lat: 36.5586, lon: 139.8836, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["tobu_grande", "1973"], source: "manual" },
  { slug: "utsunomiya-richmond-hotel", category: "lodging", sub_type: "tochigi_mito_chuou", title_zh: "リッチモンドホテル宇都宮駅前(宇都宮市・2007 開業 18 年+ 全国チェーン・全 244 室+ JR 宇都宮駅東口徒歩 1 分・R1 食 宇都宮餃子集約+ R1 行 宇都宮 LRT 2023 接続+ 1 泊朝食付 ¥9,500-13,500)", title_ja: "リッチモンドホテル宇都宮", romaji: "Richmond Utsunomiya", summary_zh: "**リッチモンドホテル宇都宮駅前は 2007 開業 18 年・全国チェーン全 244 室**(JR 東口徒歩 1 分)。R1 食 餃子集約+R1 行 LRT 接続、¥9,500-13,500。", content_md: "- 立地:**宇都宮市**(JR 宇都宮駅東口徒歩 1 分)\n- 起源:**2007 開業 18 年**\n- 規模:**全国チェーン・全 244 室**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["shopping_district"], lat: 36.5586, lon: 139.8980, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["richmond_utsunomiya", "2007"], source: "manual" },
  { slug: "utsunomiya-route-inn", category: "lodging", sub_type: "tochigi_mito_chuou", title_zh: "ホテルルートイン宇都宮駅前(宇都宮市・2010 開業+ 全国チェーン全 280 室+ JR 宇都宮駅東口徒歩 4 分・R1 食 宇都宮餃子集約+ 1 泊朝食付 ¥7,500-11,500+ 価格手頃ビジネス代表)", title_ja: "ホテルルートイン宇都宮", romaji: "Route Inn Utsunomiya", summary_zh: "**ホテルルートイン宇都宮駅前は 2010 開業全国チェーン全 280 室**(JR 東口徒歩 4 分)。R1 食 餃子集約、¥7,500-11,500、価格手頃ビジネス代表。", content_md: "- 立地:**宇都宮市**(JR 宇都宮駅東口徒歩 4 分)\n- 起源:**2010 開業**\n- 規模:**全国チェーン・全 280 室**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["shopping_district"], lat: 36.5586, lon: 139.8980, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["route_inn_utsunomiya"], source: "manual" },
  { slug: "nasu-pension-network", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "那須ペンション村(那須町・1970-2000 年代以降ペンション村集約・全 600+ 軒小規模+ R1 育 那須リゾート観光客向け+ 別荘ライフスタイル+ 1 泊 ¥8,500-18,500+ 国内観光客代表ペンション村)", title_ja: "那須ペンション村", romaji: "Nasu Pension Village", summary_zh: "**那須ペンション村は 1970-2000 年代以降ペンション村集約・全 600+ 軒小規模**(那須・**別荘ライフスタイル**)。R1 育 那須リゾート、¥8,500-18,500、国内代表ペンション村。", content_md: "- 立地:**那須郡那須町**\n- 起源:**1970-2000 年代以降**\n- 規模:**全 600+ 軒小規模ペンション**", region: "kanto", prefecture_ja: "栃木県", gun_ja: "那須郡", municipality_ja: "那須町", lg_code: "09407", area_types: ["scenic_spot"], lat: 36.9925, lon: 140.1175, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["nasu_pension_600"], source: "manual" },
  { slug: "tochigi-camp-glamping", category: "lodging", sub_type: "tochigi_other_onsen", title_zh: "栃木グランピング+キャンプ(那須+塩原+日光・2018-2024 開発・全 30+ 軒・R1 育 那須+R1 楽 紅葉観光連動+ 海外観光客 SNS 拡散+ 1 泊 ¥18,500-45,000+ 現代化アウトドア代表)", title_ja: "栃木グランピング", romaji: "Tochigi Glamping", summary_zh: "**栃木グランピング+キャンプは 2018-2024 開発・全 30+ 軒**(那須+塩原+日光・**R1 育 那須+R1 楽 紅葉観光連動**)。海外 SNS 拡散、¥18,500-45,000、現代化代表。", content_md: "- 立地:**那須郡那須町 + 那須塩原市 + 日光市**\n- 起源:**2018-2024 開発**\n- 規模:**全 30+ 軒**", region: "kanto", prefecture_ja: "栃木県", gun_ja: "那須郡", municipality_ja: "那須町", lg_code: "09407", area_types: ["scenic_spot"], lat: 36.9925, lon: 140.1175, season_start: "2026-04-01", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["tochigi_glamping"], source: "manual" },
  { slug: "ashikaga-business-hotel", category: "lodging", sub_type: "tochigi_mito_chuou", title_zh: "足利ビジネスホテル群(足利市・全国チェーン+地元 8+ 軒・JR 両毛線足利駅+東武伊勢崎線足利市駅周辺+ R1 育 足利学校 1432+鑁阿寺 1196 観光客向け+ 1 泊朝食付 ¥6,500-11,500)", title_ja: "足利ビジネスホテル", romaji: "Ashikaga Business", summary_zh: "**足利ビジネスホテル群は全国チェーン+地元 8+ 軒**(JR 両毛線+東武足利市駅周辺・**R1 育 足利学校+鑁阿寺観光**)。¥6,500-11,500。", content_md: "- 立地:**足利市**(JR 足利駅 + 東武足利市駅周辺)\n- 規模:**全国チェーン + 地元 8+ 軒**\n- 並列観光:**R1 育 足利学校 1432 + 鑁阿寺 1196**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "足利市", lg_code: "09202", area_types: ["shopping_district"], lat: 36.3403, lon: 139.4486, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["ashikaga_business"], source: "manual" },
  { slug: "sano-rich-business-hotel", category: "lodging", sub_type: "tochigi_mito_chuou", title_zh: "佐野ビジネスホテル群(佐野市・全国チェーン+地元 6+ 軒・JR 両毛線佐野駅+東武佐野線+佐野アウトレット周辺+ R1 食 佐野ラーメン+R1 育 佐野厄除け大師 観光客向け+ 1 泊朝食付 ¥6,500-12,500)", title_ja: "佐野ビジネスホテル", romaji: "Sano Business", summary_zh: "**佐野ビジネスホテル群は全国チェーン+地元 6+ 軒**(JR 佐野駅+東武佐野線+佐野アウトレット周辺・**R1 食 佐野ラーメン+R1 育 厄除け大師観光**)。¥6,500-12,500。", content_md: "- 立地:**佐野市**\n- 規模:**全国チェーン + 地元 6+ 軒**\n- 並列観光:**R1 食 佐野ラーメン + R1 育 佐野厄除け大師 + 佐野アウトレット**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "佐野市", lg_code: "09204", area_types: ["shopping_district"], lat: 36.3147, lon: 139.5786, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["sano_business"], source: "manual" },
  { slug: "mashiko-historic-inn", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "益子伝統旅館+ B&B(芳賀郡益子町・R1 衣 益子焼 1853 派生・全 6+ 軒小規模古民家旅館+ R1 衣 陶器市春秋連動+ 観光客の益子焼ファン向け体験滞在型+ 1 泊朝食付 ¥9,500-15,500)", title_ja: "益子伝統旅館", romaji: "Mashiko Historic Inn", summary_zh: "**益子伝統旅館+B&B は R1 衣 益子焼 1853 派生・全 6+ 軒小規模古民家旅館**(益子・**R1 衣 陶器市連動**)。陶器ファン体験滞在型、¥9,500-15,500。", content_md: "- 立地:**芳賀郡益子町**\n- 関係:**R1 衣 益子焼 1853 派生**\n- 規模:**全 6+ 軒小規模古民家**", region: "kanto", prefecture_ja: "栃木県", gun_ja: "芳賀郡", municipality_ja: "益子町", lg_code: "09342", area_types: ["history_site_castle"], lat: 36.4661, lon: 140.1006, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["mashiko_inn"], source: "manual" },
  { slug: "utsunomiya-mitsui-garden", category: "lodging", sub_type: "tochigi_mito_chuou", title_zh: "三井ガーデンホテル宇都宮(宇都宮市・2018 開業 7 年+ 全 173 室+ JR 宇都宮駅西口徒歩 5 分・モダンデザイン・R1 食 宇都宮餃子+R1 行 宇都宮 LRT 2023 接続+ 1 泊 ¥11,500-15,500+ 国内観光客代表)", title_ja: "三井ガーデン宇都宮", romaji: "Mitsui Garden Utsunomiya", summary_zh: "**三井ガーデンホテル宇都宮は 2018 開業 7 年・全 173 室**(JR 西口徒歩 5 分・**モダンデザイン**)。R1 食 餃子+R1 行 LRT、¥11,500-15,500、国内代表。", content_md: "- 立地:**宇都宮市**(JR 西口徒歩 5 分)\n- 起源:**2018 開業 7 年**\n- 規模:**全 173 室・モダンデザイン**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["shopping_district"], lat: 36.5586, lon: 139.8836, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["mitsui_garden_utsunomiya", "2018"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[tochigi-lodging-r1] 尚無條目"); return; }
  console.log(`[tochigi-lodging-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) return;
  const sb = createAdminClient();
  const { error } = await sb.from("japan_entries").upsert(rows as any, { onConflict: "slug" });
  if (error) { console.error("[tochigi-lodging-r1] upsert failed:", error); process.exit(1); }
  console.log(`[tochigi-lodging-r1] Done — ${rows.length} rows.`);
}
main().catch((err) => { console.error(err); process.exit(1); });
