// Seed 青森県 食 R1(25 筆 / Sprint 1.1)
//
// 林檎 3 / 津軽郷土 4 / 南部郷土 3 / 大間鮪 2 / 青森ラーメン 3 /
// 陸奥湾海鮮 4 / 銘菓 4 / 田子にんにく 2 = 25
//
// sub_type +8:aomori_apple / tsugaru_local / nanbu_local / maguro_oma /
// aomori_ramen / mutsu_seafood / aomori_meika / garlic_takko

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: "food";
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "tohoku";
  prefecture_ja: "青森県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // 林檎 (3) — 全国シェア 60%・ふじ発祥
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "a-factory-aomori",
    category: "food",
    sub_type: "aomori_apple",
    title_zh: "A-FACTORY(青森駅前・JR 東日本 2010 開業+ 林檎物販+ 自家シードル醸造所+ 駅徒歩 1 分)",
    title_ja: "エーファクトリー",
    romaji: "A-Factory",
    summary_zh: "**A-FACTORY 是青森駅前的林檎物販+ シードル醸造所**(青森市・**2010 年 12 月開業・JR 東日本運営**)。**1F 林檎・銘菓物販+ 2F 自家シードル工房 + ガラス越し見学+ テイスティング**、**青森駅徒歩 1 分・青森湾大橋直下**、第一站採買林檎商品最方便,有 5 種 自家シードル試飲。",
    content_md: "- 立地:**青森駅徒歩 1 分**(青森ベイエリア・青森湾大橋直下)\n- 開業:**2010 年 12 月 4 日**(JR 東日本運営)\n- 構成:**1F 物販** + **2F 自家シードル工房 + テイスティング**\n- 物販:林檎・林檎ジュース・林檎銘菓・酒 全県セレクト\n- シードル:**5 種(辛口/中辛/甘口/季節限定 等)**ガラス越し醸造見学可\n- 並列:旅程開頭基地・青森駅で乗換待ち時間に立寄可\n- 営業:9:00-20:00(店舗により異なる)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "青森市",
    lg_code: "02201",
    area_types: ["shopping_district", "transit_hub"],
    lat: 40.8290,
    lon: 140.7295,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.jre-abc.com/wp/afactory/" },
    tags: ["a_factory", "2010_open", "jr_east", "cider_brewery", "aomori_station"],
    source: "manual",
  },
  {
    slug: "hirosaki-apple-park",
    category: "food",
    sub_type: "aomori_apple",
    title_zh: "弘前市りんご公園(弘前市営・1985 開園 40 年+ 80 品種 2,300 本+ 8-11 月収穫体験+ 入園無料)",
    title_ja: "弘前市りんご公園",
    romaji: "Hirosaki Ringo Kōen",
    summary_zh: "**弘前市りんご公園是弘前市営林檎テーマパーク**(弘前市清水富田・**1985 年開園・40 年**)。**約 80 品種 2,300 本+ 入園無料+ 8-11 月有料収穫体験(¥250-/1 個)**、岩木山眺望、館内「すり下ろしりんごジュース」現絞販売、弘前駅から土手町循環バス「いいせ前」下車徒歩 7 分。",
    content_md: "- 立地:弘前市清水富田字寺沢 125-2(岩木山麓)\n- 開園:**1985 年・40 年**(弘前市営)\n- 規模:**80 品種 2,300 本+ 入園無料**\n- 体験:**収穫もぎとり ¥250/1 個**(8-11 月旬)\n- 名物:**現絞りすり下ろしりんごジュース**\n- アクセス:弘前駅 → 土手町循環バス「常盤坂入口」徒歩 7 分\n- 営業:9:00-17:00 通年(収穫体験は 8-11 月のみ)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "弘前市",
    lg_code: "02202",
    area_types: ["farm_field", "scenic_spot"],
    lat: 40.5862,
    lon: 140.4253,
    season_start: "2026-08-01",
    season_end: "2026-11-30",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hirosaki_apple_park", "1985_open", "80_varieties", "harvest_experience", "iwakisan_view"],
    source: "manual",
  },
  {
    slug: "fuji-apple-birthplace-fujisaki",
    category: "food",
    sub_type: "aomori_apple",
    title_zh: "ふじ発祥地(藤崎町・1962 命名登録+ 世界林檎生産 60% 占有品種+ 記念碑+ 旧農林省盛岡支場藤崎試験地)",
    title_ja: "「ふじ」発祥の地",
    romaji: "Fuji Hassho no Chi",
    summary_zh: "**藤崎町是世界林檎主力品種「ふじ」の発祥地**(南津軽郡・**1962 年 11 月 1 日 命名登録**)。**旧農林省果樹試験場盛岡支場藤崎試験地で交配・選抜**、現代世界林檎生産 60% 占有(中国主体)、町内に**「ふじ発祥の地」記念碑** + **林檎史料館**、藤崎駅徒歩 15 分。",
    content_md: "- 立地:藤崎町(南津軽郡・弘前市北東隣)\n- 命名登録:**1962 年 11 月 1 日**(旧農林省果樹試験場盛岡支場藤崎試験地)\n- 由来:**「国光 × デリシャス」交配・1939 育成開始 23 年経て命名**\n- 世界生産:**林檎総生産の 60% がふじ系品種**(中国主体)\n- 記念碑:町内 1 号木跡に「ふじ発祥の地」碑\n- アクセス:JR 奥羽本線 藤崎駅 徒歩 15 分\n- 並列:R1 食 弘前りんご公園 + A-Factory = 林檎 3 大スポット",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: "南津軽郡",
    municipality_ja: "藤崎町",
    lg_code: "02361",
    area_types: ["farm_field", "history_site_castle"],
    lat: 40.6533,
    lon: 140.4961,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["fuji_birthplace", "1962", "fujisaki_town", "world_apple_60pct"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 津軽郷土食 (4) — 弘前藩文化・冬の保存食
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kenojiru-tsugaru",
    category: "food",
    sub_type: "tsugaru_local",
    title_zh: "けの汁(津軽郷土食・小正月 1/16 精進+ 大豆+ 7 種野菜微塵切+ 昆布出汁+ 冬保存食代表+ 農水省「郷土料理百選」)",
    title_ja: "けの汁",
    romaji: "Ke no Jiru",
    summary_zh: "**けの汁是津軽 小正月の精進汁**(津軽全域・**小正月 1 月 16 日 嫁が実家帰省中の家族非常食**)。**大豆 + 大根 + 人参 + ごぼう + 蕗 + 蕨 + 油揚げ等を全て微塵切り** + 昆布出汁 + 味噌、農水省「**農山漁村の郷土料理百選 2007 選定**」、津軽全域で家庭+ 食堂 + 道の駅で提供。",
    content_md: "- 起源:**津軽小正月 1 月 16 日**(嫁が実家帰省中・家族の作り置き精進汁)\n- 命名:「**粥(かゆ)→ かよ → け**」の津軽訛り\n- 構成:**大豆 + 7 種野菜全て微塵切り** + 昆布出汁 + 味噌(肉魚なしの精進)\n- 特徴:**全具材を細かく刻む**(大鍋で 3 日分作り置き・冬の保存食)\n- 認定:**農水省 郷土料理百選 2007**\n- 提供:津軽全域の家庭 + 道の駅 + 居酒屋(冬季中心)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "弘前市",
    lg_code: "02202",
    area_types: ["restaurant_traditional"],
    lat: 40.6063,
    lon: 140.4641,
    season_start: "2026-01-01",
    season_end: "2026-03-31",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kenojiru", "ko_shogatsu", "shojin", "kyodo_ryori_100"],
    source: "manual",
  },
  {
    slug: "kayakimiso-tsugaru",
    category: "food",
    sub_type: "tsugaru_local",
    title_zh: "貝焼味噌(津軽郷土・大型ホタテ殻 鍋代用+ 味噌出汁 + 卵 +ねぎ+ 津軽家庭朝食代表+ 殻の取手で持ち上げ食)",
    title_ja: "貝焼き味噌",
    romaji: "Kayaki Miso",
    summary_zh: "**貝焼味噌是津軽郷土の卵料理**(津軽全域・**大型ホタテ殻 = 鍋代用**)。**昆布出汁+ 味噌 + 溶き卵 + ねぎ + 鰹節**を直火で煮立てる、ホタテ殻が両手取手付の天然耐熱鍋になる、津軽の朝食定番、家庭+ 居酒屋+ 民宿で提供。",
    content_md: "- 起源:陸奥湾大型ホタテ殻 = 直火耐熱鍋として活用\n- 構成:**昆布出汁 + 味噌 + 溶き卵 + ねぎ + 鰹節**(具シンプル)\n- 特徴:**大型ホタテ殻が天然鍋**(両手取手付・直火可・1 人前ピッタリ)\n- 提供:津軽全域の家庭朝食 + 居酒屋 + 民宿\n- 並列:R1 食 けの汁 + じゃっぱ汁 = 津軽冬郷土 3 大\n- 価格:1 椀 ¥600-1,200(店舗による)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "弘前市",
    lg_code: "02202",
    area_types: ["restaurant_traditional"],
    lat: 40.6063,
    lon: 140.4641,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kayaki_miso", "scallop_shell_pot", "tsugaru_breakfast"],
    source: "manual",
  },
  {
    slug: "jappa-jiru-tsugaru",
    category: "food",
    sub_type: "tsugaru_local",
    title_zh: "じゃっぱ汁(津軽冬郷土・寒鱈アラ汁+ 大根 + 葱 + 味噌+ 「じゃっぱ」=津軽弁「アラ(魚骨)」+ 厳冬期 12-2 月旬)",
    title_ja: "じゃっぱ汁",
    romaji: "Jappa Jiru",
    summary_zh: "**じゃっぱ汁是津軽冬の鱈アラ汁**(津軽全域・**12-2 月厳冬期旬**)。**「じゃっぱ」=津軽弁「アラ(魚骨)」、寒鱈の頭+骨+内臓+白子+大根+ねぎ+味噌**、寒さで脂のった寒鱈が最旨、津軽の冬が来た合図の郷土料理、居酒屋+食堂で 12-2 月限定提供多数。",
    content_md: "- 命名:「**じゃっぱ**」=津軽弁「アラ(魚の骨・頭・内臓)」\n- 構成:**寒鱈のアラ + 白子 + 大根 + ねぎ + 味噌**(出汁は鱈骨から)\n- 旬:**12-2 月**(厳冬期の寒鱈・脂が最ものる)\n- 提供:**冬季限定**(津軽の居酒屋・食堂・市場食堂)\n- 並列:R1 食 けの汁 + 貝焼味噌 + じゃっぱ汁 = 津軽冬郷土 3 大\n- 価格:1 椀 ¥800-1,500(店舗による)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "青森市",
    lg_code: "02201",
    area_types: ["restaurant_traditional"],
    lat: 40.8244,
    lon: 140.7406,
    season_start: "2026-12-01",
    season_end: "2027-02-28",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jappa_jiru", "kandara_ara", "tsugaru_winter", "december_february"],
    source: "manual",
  },
  {
    slug: "hoshimochi-tsugaru",
    category: "food",
    sub_type: "tsugaru_local",
    title_zh: "津軽干し餅(寒中乾燥餅+ 餅米 + 黒砂糖 + 胡麻+ 厳冬-15℃ 凍結乾燥+ 津軽冬保存食+ ストーブで炙って食)",
    title_ja: "干し餅",
    romaji: "Hoshi Mochi",
    summary_zh: "**干し餅是津軽寒中乾燥餅**(津軽全域・**1-2 月厳冬期-15℃凍結乾燥**)。**餅米+黒砂糖+胡麻+塩**を凍結→ 解凍→ 乾燥を繰り返す保存食、ストーブ+焼き網で炙ってサクサク食、津軽冬の保存食代表、道の駅+土産屋で通年販売。",
    content_md: "- 起源:**津軽厳冬期(1-2 月)の凍結乾燥保存食**\n- 製法:**餅米 + 黒砂糖 + 胡麻 + 塩** → 厳冬-15℃ 凍結 + 解凍 + 乾燥 繰返\n- 食法:**ストーブ + 焼き網で炙ってサクサク**(膨らむ)\n- 種類:黒砂糖 + 白砂糖 + よもぎ + 胡麻 等\n- 提供:道の駅 + 土産屋 + JR 駅売店 通年\n- 価格:1 袋(8-10 枚)¥500-1,000",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "弘前市",
    lg_code: "02202",
    area_types: ["shopping_district"],
    lat: 40.6063,
    lon: 140.4641,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hoshi_mochi", "minus_15_freeze_dry", "tsugaru_winter_preserve"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 南部郷土食 (3) — 八戸藩文化
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "senbei-jiru-hachinohe",
    category: "food",
    sub_type: "nanbu_local",
    title_zh: "八戸せんべい汁(南部煎餅入り鍋+ 八戸南部藩郷土+ B-1 グランプリ 2012 優勝+ 農水省「郷土料理百選」+ 八戸せんべい汁研究所運営)",
    title_ja: "八戸せんべい汁",
    romaji: "Hachinohe Senbei Jiru",
    summary_zh: "**八戸せんべい汁是南部藩郷土鍋**(八戸市・**南部煎餅(かやき煎餅)を割入鍋**)。**B-1 グランプリ 2012 第 7 回優勝(北九州大会)**、**農水省 郷土料理百選 2007 選定**、せんべいが汁を吸って もちもち食感、鶏+野菜+醤油+南部煎餅、市内 200+ 店舗で提供。",
    content_md: "- 起源:八戸南部藩・**鍋専用「かやき煎餅」を割入**(白い無味煎餅)\n- 構成:**鶏 + ごぼう + ねぎ + 人参 + 南部煎餅** + 醤油出汁\n- 認定:**B-1 グランプリ 2012 優勝**(北九州大会・第 7 回)\n- 認定:**農水省 郷土料理百選 2007**\n- 提供:**八戸市内 200+ 店舗**(専門店・居酒屋・食堂)\n- 八戸せんべい汁研究所(B-1 運営団体)が普及活動\n- 価格:1 鍋 ¥1,200-2,500",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "八戸市",
    lg_code: "02203",
    area_types: ["restaurant_traditional"],
    lat: 40.5121,
    lon: 141.4884,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.senbei-jiru.com/" },
    tags: ["senbei_jiru", "b1_grandprix_2012", "nanbu_senbei", "kyodo_ryori_100"],
    source: "manual",
  },
  {
    slug: "ichigoni-hashikami",
    category: "food",
    sub_type: "nanbu_local",
    title_zh: "いちご煮(階上町発祥・南部藩郷土+ 雲丹 + 鮑 吸物+ 雲丹が苺の実に見える+ 農水省「郷土料理百選」+ 高級慶事料理)",
    title_ja: "いちご煮",
    romaji: "Ichigo-ni",
    summary_zh: "**いちご煮是階上町(三戸郡)発祥の高級吸物**(南部藩郷土・**雲丹 + 鮑 + 大葉吸物**)。**雲丹が湯に開いて苺の実のように見える**ため命名(果物の苺は無関係)、**農水省 郷土料理百選 2007**、慶事料理代表、八戸+階上の旅館+割烹で提供、缶詰版も土産販売。",
    content_md: "- 起源:**階上町(三戸郡・八戸南隣)発祥**(明治期漁師まかない)\n- 構成:**雲丹 + 鮑 + 大葉 + 出汁**(吸物・煮物)\n- 命名由来:**雲丹が湯で開いて苺の赤い実のように見える**(果物の苺は無関係)\n- 認定:**農水省 郷土料理百選 2007**\n- 提供:八戸 + 階上の旅館 + 割烹 + 一部土産缶詰版\n- 価格:1 椀 ¥2,500-5,000(高級慶事料理)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: "三戸郡",
    municipality_ja: "階上町",
    lg_code: "02446",
    area_types: ["restaurant_traditional", "coastal"],
    lat: 40.4503,
    lon: 141.6275,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ichigoni", "hashikami_origin", "uni_awabi", "kyodo_ryori_100"],
    source: "manual",
  },
  {
    slug: "keiran-nanbu",
    category: "food",
    sub_type: "nanbu_local",
    title_zh: "けいらん(南部藩贈答菓子+ 米粉団子+ 黒糖蜜+ 卵形に似て命名+ 慶事+正月伝統+ 八戸+三戸の老舗和菓子店)",
    title_ja: "けいらん",
    romaji: "Keiran",
    summary_zh: "**けいらん是南部藩贈答菓子**(八戸+三戸郡・**米粉団子+黒糖蜜)**。**「鶏卵」=団子の形が卵に似ている**ため命名、慶事+正月+婚礼贈答に使用、白玉団子+小豆あん+黒糖蜜の組合せ、和菓子の中でもシンプルだが南部藩らしい素朴さ、八戸+三戸老舗和菓子店で通年販売。",
    content_md: "- 起源:南部藩贈答菓子(慶事 + 正月 + 婚礼用)\n- 命名:**「鶏卵」=団子の形が卵に似ている**\n- 構成:**米粉白玉団子 + 小豆あん + 黒糖蜜**(温かい)\n- 提供:八戸+ 三戸老舗和菓子店 + 一部食堂\n- 並列:R1 食 せんべい汁 + いちご煮 + けいらん = 南部郷土 3 大\n- 価格:1 椀 ¥600-1,200",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "八戸市",
    lg_code: "02203",
    area_types: ["restaurant_traditional"],
    lat: 40.5121,
    lon: 141.4884,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["keiran", "nanbu_zoto_kashi", "rice_dumpling_kuro_mitsu"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 大間鮪 (2) — 下北・本マグロ初競り日本一
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "oma-tuna-port-shimokita",
    category: "food",
    sub_type: "maguro_oma",
    title_zh: "大間漁港 本マグロ初競り(下北郡大間町・1月豊洲初競り日本一+ 2019 年 278kg 1 尾 3.3 億円 過去最高+ 本マグロ生産日本最高峰)",
    title_ja: "大間港・本マグロ初競り",
    romaji: "Ōma Honmaguro Hatsuseri",
    summary_zh: "**大間漁港是日本本マグロ最高峰水揚港**(下北郡大間町・**本州最北端**)。**1 月豊洲市場初競りで連年最高値 → 2019 年 278kg 1 尾 3.3 億円 過去最高記録**、一本釣+ 延縄漁の伝統漁法、町内に大間鮪が食べられる漁港食堂が複数、JR 下北駅(むつ市)から路線バスで約 100 分。",
    content_md: "- 立地:**下北郡大間町**(本州最北端・津軽海峡側)\n- 漁法:**一本釣 + 延縄**(伝統漁法・大間町本マグロ漁業協同組合)\n- 初競り記録:**2019 年 1 月 5 日 豊洲市場 278kg 1 尾 3 億 3,360 万円**(過去最高)\n- 旬:**9-1 月**(秋から冬の青森津軽海峡 高脂本鮪)\n- 食事:町内 漁港食堂 + 浜寿司 + 海峡荘 等\n- アクセス:JR 下北駅(むつ市)→ 下北交通バス約 100 分\n- 並列:R1 行 大間崎+ 仏ヶ浦遊覧",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: "下北郡",
    municipality_ja: "大間町",
    lg_code: "02423",
    area_types: ["coastal", "industrial_heritage"],
    lat: 41.5286,
    lon: 140.9094,
    season_start: "2026-09-01",
    season_end: "2027-01-31",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://oma-wide.net/" },
    tags: ["oma_honmaguro", "hatsuseri_no1", "2019_record_333m_yen", "shimokita"],
    source: "manual",
  },
  {
    slug: "oma-misakitei-shokudo",
    category: "food",
    sub_type: "maguro_oma",
    title_zh: "大間崎食事処群(本州最北端大間崎周辺・大間鮪丼+ 鮪刺身 食事処複数+ マグロ一筋本店+ 浜寿司 等+ 大間崎観光時の代表昼食)",
    title_ja: "大間崎食事処群",
    romaji: "Ōmazaki Shokudo-gun",
    summary_zh: "**大間崎食事処群是本州最北端の大間鮪食事拠点**(下北郡大間町大間崎・**マグロ一筋本店+ 浜寿司+ 海峡荘 等多店舗**)。**大間鮪丼 ¥2,500-5,000+ 鮪刺身単品+ 鮪寿司**、本州最北端碑+ 大間崎灯台観光と組合せが定番、夏冬で営業時間異なり、繁忙期は予約推奨。",
    content_md: "- 立地:**本州最北端 大間崎周辺**(下北郡大間町)\n- 主要店:**マグロ一筋・浜寿司・海峡荘**(マグロ丼+刺身+寿司)\n- 価格:**マグロ丼 ¥2,500-5,000**(中トロ + 大トロ + 赤身)\n- 観光組合:**本州最北端碑 + 大間崎灯台 + 弁天島**\n- 営業時間:夏期 通年営業 / 冬期 短縮営業多数\n- 予約:1 月豊洲初競り後の繁忙期は予約推奨\n- アクセス:JR 下北駅(むつ市)→ 下北交通バス 大間崎方面",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: "下北郡",
    municipality_ja: "大間町",
    lg_code: "02423",
    area_types: ["coastal", "restaurant_traditional"],
    lat: 41.5346,
    lon: 140.9111,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["omazaki", "honshu_northernmost", "oma_maguro_don"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 青森ラーメン (3) — 津軽煮干し+南部南蛮+味噌カレー牛乳
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "tsugaru-niboshi-ramen-overview",
    category: "food",
    sub_type: "aomori_ramen",
    title_zh: "津軽煮干しラーメン(青森ラーメン代表系+ 大量煮干し白濁スープ+ 長尾中華そば 2002 + たかはし中華そば 等+ 弘前+青森市中心)",
    title_ja: "津軽煮干しラーメン",
    romaji: "Tsugaru Niboshi Ramen",
    summary_zh: "**津軽煮干しラーメンは青森ラーメン主流系**(津軽全域・**大量煮干し+白濁濃厚煮干スープ**)。**長尾中華そば 2002 創業(青森市)+ たかはし中華そば 1944 創業 81 年(青森市)+ 麺屋 ゆきかげ(弘前)等代表店**、煮干が際立つ清湯+濃厚 2 系統、青森ラーメンと言えば津軽煮干し系。",
    content_md: "- 系統:**津軽煮干し系**(青森ラーメン主流)\n- 特徴:**大量煮干し白濁濃厚スープ**(青森近海煮干し)\n- 代表店:**長尾中華そば**(青森市・2002 創業)\n- 代表店:**たかはし中華そば**(青森市・1944 創業 81 年)\n- 代表店:麺屋 ゆきかげ(弘前市)\n- 並列系統:**清湯 + 濃厚 2 系**(店舗による)\n- 価格:¥800-1,200/杯",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "青森市",
    lg_code: "02201",
    area_types: ["restaurant_traditional"],
    lat: 40.8244,
    lon: 140.7406,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["tsugaru_niboshi", "nagao_chukasoba_2002", "takahashi_chukasoba_1944"],
    source: "manual",
  },
  {
    slug: "miso-curry-milk-ramen-aomori",
    category: "food",
    sub_type: "aomori_ramen",
    title_zh: "味噌カレー牛乳ラーメン(青森市発祥・1980 年代「味の札幌大西」確立+ 札幌系味噌+カレー粉+牛乳+バター+ 青森市内 数 10 店舗+ 寒冷地高カロリー)",
    title_ja: "味噌カレー牛乳ラーメン",
    romaji: "Miso Curry Milk Ramen",
    summary_zh: "**味噌カレー牛乳ラーメンは青森市発祥の独自系**(青森市・**1980 年代「味の札幌大西」確立**)。**札幌系味噌スープ+カレー粉+牛乳+バター+ もやし+ ねぎ + 挽肉**、寒冷地向け高カロリー、青森市内に「**味の札幌大西・味の札幌 浅利**」等数10店舗、青森ラーメンの一翼。",
    content_md: "- 起源:**青森市・1980 年代「味の札幌大西」が確立**\n- 構成:**札幌系味噌 + カレー粉 + 牛乳 + バター**(寒冷地高カロリー設計)\n- 具:もやし + 挽肉 + わかめ + ねぎ + バター 1 個\n- 主要店:**味の札幌大西**(青森市古川 1-15-6)\n- 主要店:**味の札幌 浅利**(青森市本町 5-2)\n- 提供:**青森市内 数 10 店舗**(冬の代表ラーメン)\n- 価格:¥850-1,200",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "青森市",
    lg_code: "02201",
    area_types: ["restaurant_traditional"],
    lat: 40.8244,
    lon: 140.7406,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["miso_curry_milk", "aomori_origin", "1980s", "ajinosapporo"],
    source: "manual",
  },
  {
    slug: "hachinohe-nanban-ramen",
    category: "food",
    sub_type: "aomori_ramen",
    title_zh: "八戸ラーメン(南部煮干+鶏ガラ系・八戸魚類市場食堂代表+ 朝ラー文化+ 八食センター市場ラーメン+ 5:00-営業店も)",
    title_ja: "八戸ラーメン",
    romaji: "Hachinohe Ramen",
    summary_zh: "**八戸ラーメンは南部地方ラーメン代表系**(八戸市・**煮干 + 鶏ガラ + 醤油あっさり**)。**八戸魚類市場 5:00- 営業の朝ラー文化**、**八食センター市場ラーメン**、津軽煮干しと違ってあっさり系、八戸漁港+市場観光と組合せ可能、漁港早朝食事の代表。",
    content_md: "- 系統:**南部煮干 + 鶏ガラ + 醤油あっさり**(津軽濃厚と差別化)\n- 朝ラー文化:**八戸魚類市場・八食センター 5:00-開店店舗**\n- 主要場所:**八食センター ラーメン店街**(八戸市 河原木字神才)\n- 主要場所:八戸魚菜小売市場(陸奥湊駅前)\n- 並列:R1 食 せんべい汁 + 八戸前沖鯖 = 八戸食 3 大\n- 価格:¥600-1,000(あっさり系)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "八戸市",
    lg_code: "02203",
    area_types: ["restaurant_traditional", "shopping_district"],
    lat: 40.5345,
    lon: 141.5145,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hachinohe_ramen", "morning_ramen", "hassyoku_center"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 陸奥湾海鮮 (4) — 三方海・帆立+鯖+烏賊+鮪
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "mutsu-bay-hotate-hiranai",
    category: "food",
    sub_type: "mutsu_seafood",
    title_zh: "陸奥湾帆立(平内町養殖発祥+ 全国シェア 2 位+ 寒締帆立 1-3 月旬+ 浅虫温泉手前産地+ 平内町ホタテ広場直売)",
    title_ja: "陸奥湾ホタテ",
    romaji: "Mutsu-Wan Hotate",
    summary_zh: "**陸奥湾帆立是平内町養殖発祥+ 全国 2 位産地**(東津軽郡平内町・**1958 年養殖開始**)。**寒締帆立(1-3 月旬)+ 夏帆立で年中提供**、平内町は浅虫温泉手前で青森市から車 30 分、**ホタテ広場(平内町直売所)+ 全道の駅で購入可**、青森市内寿司+ 居酒屋全店で提供。",
    content_md: "- 産地:**東津軽郡平内町**(浅虫温泉手前・青森湾沿岸)\n- 養殖発祥:**1958 年 平内町ホタテ養殖開始**\n- 全国順位:**全国シェア 2 位**(1 位 北海道)\n- 旬:**寒締帆立 1-3 月**(冬の身締まり)+ **夏帆立 6-8 月**(産卵前)\n- 直売:**ホタテ広場**(平内町山口・国道 4 号沿)\n- 提供:青森市内寿司 + 居酒屋 + 浅虫温泉旅館全般",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: "東津軽郡",
    municipality_ja: "平内町",
    lg_code: "02301",
    area_types: ["coastal", "industrial_heritage"],
    lat: 40.9112,
    lon: 140.9286,
    season_start: "2026-01-01",
    season_end: "2026-03-31",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["mutsu_wan_hotate", "hiranai_origin_1958", "no2_japan", "winter_kanjime"],
    source: "manual",
  },
  {
    slug: "hachinohe-saba-brand",
    category: "food",
    sub_type: "mutsu_seafood",
    title_zh: "八戸前沖鯖(八戸ブランド・脂含 27% 高品質+ 9-1 月旬 寒鯖+ 八戸八幡 + 北浦定置網漁+ 居酒屋+寿司提供)",
    title_ja: "八戸前沖鯖",
    romaji: "Hachinohe Mae-oki Saba",
    summary_zh: "**八戸前沖鯖是八戸ブランド寒鯖**(八戸市・**脂含 27% 以上の規格認証**)。**9-1 月旬・八戸前沖の寒気で脂のった真鯖**、八戸八幡+北浦の定置網漁が中心、**八戸前沖さば=10 月以降漁獲・脂含 10% 以上+ 八戸前沖銀さば=11 月以降・脂含 27% 以上**ブランド規格。",
    content_md: "- 産地:**八戸前沖**(三陸沖 + 太平洋・八戸漁港水揚)\n- ブランド規格:**「八戸前沖さば」= 10 月以降 + 脂含 10% 以上**\n- 上位規格:**「八戸前沖銀さば」= 11 月以降 + 脂含 27% 以上**\n- 漁法:八戸八幡 + 北浦の定置網\n- 旬:**9-1 月**(寒鯖の脂のる時期)\n- 提供:八戸魚菜小売市場 + 八食センター + 居酒屋 + 寿司全般",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "八戸市",
    lg_code: "02203",
    area_types: ["coastal", "industrial_heritage"],
    lat: 40.5121,
    lon: 141.4884,
    season_start: "2026-09-01",
    season_end: "2027-01-31",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hachinohe_mae_oki_saba", "fat_27pct", "winter_brand"],
    source: "manual",
  },
  {
    slug: "hachinohe-ika",
    category: "food",
    sub_type: "mutsu_seafood",
    title_zh: "八戸イカ(全国有数水揚港+ 八戸スルメイカ夏旬 6-12 月+ いか刺身 + イカ素麺 + 八戸前沖一夜干+ 朝市+市場で生活感ある提供)",
    title_ja: "八戸イカ",
    romaji: "Hachinohe Ika",
    summary_zh: "**八戸イカは全国有数水揚港**(八戸漁港・**スルメイカ夏旬 6-12 月**)。**いか刺身+イカ素麺(刻みイカ)+一夜干が代表料理**、八戸魚菜小売市場(陸奥湊駅前)朝市+八食センターで購入+食事可能、近年水揚減傾向だが八戸イカブランドは健在。",
    content_md: "- 産地:**八戸漁港**(全国有数イカ水揚港)\n- 種類:**スルメイカ**(主要・夏旬 6-12 月)\n- 代表料理:**いか刺身 + イカ素麺**(細切りイカで素麺風)+ **一夜干**\n- 朝市:**八戸魚菜小売市場(陸奥湊駅前)5:00-開市**\n- 食事+土産:**八食センター**(河原木字神才)\n- 並列:R1 食 八戸前沖鯖 + せんべい汁 = 八戸食 3 大\n- 価格:刺身 ¥800-1,500/皿 + 一夜干 ¥600-1,200",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "八戸市",
    lg_code: "02203",
    area_types: ["coastal", "shopping_district"],
    lat: 40.5121,
    lon: 141.4884,
    season_start: "2026-06-01",
    season_end: "2026-12-31",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hachinohe_ika", "surume_ika", "ika_somen"],
    source: "manual",
  },
  {
    slug: "fukaura-maguro-don",
    category: "food",
    sub_type: "mutsu_seafood",
    title_zh: "深浦マグロステーキ丼(深浦町観光施策・本マグロ三種食べ比べ+ 漬+焼+刺身+ ふかうら山海荘等 8 提供店+ 五能線 + 千畳敷観光時昼食)",
    title_ja: "深浦マグロステーキ丼",
    romaji: "Fukaura Maguro Steak Don",
    summary_zh: "**深浦マグロステーキ丼是深浦町観光ご当地丼**(西津軽郡深浦町・**深浦漁港本マグロ三種食べ比べ**)。**赤身漬+ステーキ焼+刺身=三種一杯**、町内 8 店舗で提供共通レシピ、五能線+千畳敷海岸観光時の代表昼食、JR リゾートしらかみ列車旅行と組合せが定番。",
    content_md: "- 立地:**西津軽郡深浦町**(日本海側・五能線沿線)\n- 構成:**漬マグロ + マグロステーキ焼 + マグロ刺身 + ご飯 + 出汁**(共通規格)\n- 提供店:**町内 8 店舗**(ふかうら山海荘 + 食事処 西海 + 等)\n- 並列観光:**五能線リゾートしらかみ + 千畳敷海岸 + 行合崎**\n- アクセス:JR 五能線 深浦駅\n- 価格:**統一 ¥2,200-2,800**(店舗共通価格帯)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: "西津軽郡",
    municipality_ja: "深浦町",
    lg_code: "02323",
    area_types: ["coastal", "restaurant_traditional"],
    lat: 40.6483,
    lon: 139.9315,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["fukaura_maguro_steak_don", "gono_line", "8_stores"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 銘菓 (4) — 林檎パイ + 老舗和菓子
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "ki-ni-naru-ringo-ragnao",
    category: "food",
    sub_type: "aomori_meika",
    title_zh: "気になるリンゴ(ラグノオささき・1990 年代発売 35 年+ 紅玉まるごと一玉パイ包+ 青森銘菓代表+ 青森駅+弘前駅+ 全国百貨店販売)",
    title_ja: "気になるリンゴ",
    romaji: "Ki ni Naru Ringo",
    summary_zh: "**気になるリンゴ是ラグノオささきの代表林檎パイ**(弘前本社・**紅玉まるごと一玉をパイで包む**)。**1990 年代発売・全国百貨店+青森空港+JR駅売店販売**、青森土産代表、賞味期限 30 日で日持ちする、ラグノオは弘前 1885 創業 140 年の老舗菓子店。",
    content_md: "- 製造:**ラグノオささき**(弘前本社・**1885 創業 140 年**)\n- 構成:**紅玉一玉まるごと + バターパイ生地包み**\n- 発売:1990 年代(35 年前後・青森銘菓代表)\n- 賞味期限:**30 日**(土産日持ち良い)\n- 販売:**全国百貨店 + 青森空港 + JR 青森・弘前・新青森駅**\n- 並列:R1 食 らぷる + 嶽きみ = ラグノオ姉妹品\n- 価格:**¥325/個**(目安)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "弘前市",
    lg_code: "02202",
    area_types: ["shopping_district"],
    lat: 40.6063,
    lon: 140.4641,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.rag-s.com/" },
    tags: ["ki_ni_naru_ringo", "ragnao", "1885_founded", "kogyoku_apple_pie"],
    source: "manual",
  },
  {
    slug: "rappuru-ragnao",
    category: "food",
    sub_type: "aomori_meika",
    title_zh: "らぷる(ラグノオささき・1971 発売 54 年+ 林檎ジャムサンドケーキ+ ラグノオ最古ヒット商品+ 軽量+日持ち青森駅売店定番土産)",
    title_ja: "らぷる",
    romaji: "Rappuru",
    summary_zh: "**らぷる是ラグノオささきの林檎ジャムサンドケーキ**(弘前本社・**1971 発売 54 年・ラグノオ最古ヒット**)。**フランボワーズ風林檎ジャムをスポンジでサンド+チョコ片**、軽量+ 日持ち+ 価格手頃で青森駅売店定番、気になるリンゴ前のラグノオ看板商品、5 個入から販売。",
    content_md: "- 製造:**ラグノオささき**(弘前本社・1885 創業)\n- 発売:**1971 年・54 年**(ラグノオ最古ヒット商品)\n- 構成:**林檎ジャム + スポンジケーキ + チョコ片**\n- 賞味期限:**45 日**(気になるリンゴより日持ち)\n- 販売:**青森空港 + JR 青森・弘前・新青森駅 + 県内土産店**\n- 並列:R1 食 気になるリンゴ + 嶽きみ = ラグノオ 3 大",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "弘前市",
    lg_code: "02202",
    area_types: ["shopping_district"],
    lat: 40.6063,
    lon: 140.4641,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.rag-s.com/" },
    tags: ["rappuru", "ragnao", "1971_launched", "apple_jam_sandwich"],
    source: "manual",
  },
  {
    slug: "dake-kimi-iwakisan",
    category: "food",
    sub_type: "aomori_meika",
    title_zh: "嶽きみ(岩木山麓 嶽高原産+ ホワイトコーン+ 糖度 16-19% 桃級甘味+ 8-10 月旬 期間限定+ 弘前 嶽きみロード直売)",
    title_ja: "嶽きみ",
    romaji: "Dake Kimi",
    summary_zh: "**嶽きみは岩木山麓 嶽高原産ホワイトコーン**(弘前市・**糖度 16-19%・桃級甘味**)。**標高 400-500m + 朝晩寒暖差 10℃+ 嶽地区限定栽培**、生で齧れる極甘ホワイトコーン、**8-10 月旬限定**、弘前から岩木山方面の県道 3 号「嶽きみロード」直売所が観光ルート。",
    content_md: "- 産地:**弘前市嶽高原**(岩木山麓・標高 400-500m)\n- 品種:**ホワイトコーン**(白粒)\n- 糖度:**16-19%**(桃級甘味)\n- 旬:**8-10 月限定**\n- 直売:県道 3 号沿「**嶽きみロード**」露店多数(夏期)\n- 食法:**茹で・焼・生**(極甘で生齧り可能)\n- 価格:1 本 ¥300-500(直売)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "弘前市",
    lg_code: "02202",
    area_types: ["farm_field", "scenic_spot"],
    lat: 40.6386,
    lon: 140.3306,
    season_start: "2026-08-01",
    season_end: "2026-10-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["dake_kimi", "white_corn", "iwakisan_foothills", "august_october"],
    source: "manual",
  },
  {
    slug: "hakkoda-no-tsuki",
    category: "food",
    sub_type: "aomori_meika",
    title_zh: "八甲田の月(株式会社 さくら堂・青森市銘菓+ 黄味餡カステラ生地包+ 八甲田 motif の名月模+ 青森駅+空港土産+ 県内老舗和菓子)",
    title_ja: "八甲田の月",
    romaji: "Hakkōda no Tsuki",
    summary_zh: "**八甲田の月是さくら堂の青森市銘菓**(青森市・**黄味餡 + カステラ生地包**)。**八甲田山名月をかたどった円盤型銘菓**、しっとりカステラ + やわらか黄味餡、青森空港 + JR 青森駅売店 + 県内土産店、ラグノオ系の林檎パイと別系統(和菓子寄り)、慶事+進物に好まれる。",
    content_md: "- 製造:**さくら堂**(青森市)\n- 構成:**黄味餡 + カステラ生地包**(円盤型)\n- 模:**八甲田山に懸かる名月**\n- 賞味期限:**14 日**(やや短め)\n- 販売:**青森空港 + JR 青森駅売店 + 県内土産店**\n- 並列:R1 食 気になるリンゴ + らぷる = 林檎系銘菓 vs 和菓子系の代表\n- 価格:1 個 ¥160-200",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: null,
    municipality_ja: "青森市",
    lg_code: "02201",
    area_types: ["shopping_district"],
    lat: 40.8244,
    lon: 140.7406,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hakkoda_no_tsuki", "sakurado", "kimi_an_castella"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 田子にんにく (2) — 全国 1 位産地
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "takko-garlic-brand",
    category: "food",
    sub_type: "garlic_takko",
    title_zh: "田子にんにく(三戸郡田子町・全国 1 位生産シェア+ 寒冷地 福地ホワイト六片種+ 1 球 6 片大粒+ 黒にんにく加工 発祥+ 「ガーリックタウン」称号)",
    title_ja: "田子にんにく",
    romaji: "Takko Ninniku",
    summary_zh: "**田子にんにくは全国 1 位生産シェアブランド**(三戸郡田子町・**「ガーリックタウン」称号**)。**寒冷地 福地ホワイト六片種主体・1 球 6 片の大粒+ 高糖度+ 高アリシン**、町内に**黒にんにく(発酵加工)発祥業者複数**、町は青森県南端 + 岩手県二戸隣接、JR 八戸駅から南部バス約 90 分。",
    content_md: "- 産地:**三戸郡田子町**(全国 1 位にんにく生産シェア)\n- 品種:**福地ホワイト六片種**(寒冷地大粒種)\n- 特徴:1 球 6 片 + 大粒 + 高糖度 + 高アリシン\n- 加工:**黒にんにく発祥地**(発酵+ 熟成)\n- 称号:**「ガーリックタウン」**(町ブランド戦略)\n- アクセス:JR 八戸駅 → 南部バス 約 90 分\n- 並列:R1 食 嶽きみ + 大間鮪 = 青森地域 1 位農水産",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: "三戸郡",
    municipality_ja: "田子町",
    lg_code: "02443",
    area_types: ["farm_field"],
    lat: 40.3467,
    lon: 141.1683,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.town.takko.lg.jp/" },
    tags: ["takko_garlic", "no1_japan", "fukuchi_white_6", "garlic_town"],
    source: "manual",
  },
  {
    slug: "michinoeki-takko-garlic-center",
    category: "food",
    sub_type: "garlic_takko",
    title_zh: "道の駅たっこ ガーリックセンター(田子町国道 4 号沿+ 田子にんにく直売+ ガーリックステーキ丼+ 黒にんにく+ 青森-岩手県境隣接 立寄観光拠点)",
    title_ja: "道の駅たっこ ガーリックセンター",
    romaji: "Michi no Eki Takko Garlic Center",
    summary_zh: "**道の駅たっこ ガーリックセンターは田子にんにく直売 + 食事拠点**(三戸郡田子町・**国道 4 号沿**)。**田子にんにく + 黒にんにく直売 + ガーリックステーキ丼 + ガーリックラーメン**、青森-岩手県境隣接で東北道八戸 IC 経由ドライブ立寄に最適、レンタカー観光拠点。",
    content_md: "- 立地:**三戸郡田子町・国道 4 号沿**(青森-岩手県境隣接)\n- 直売:**田子にんにく + 黒にんにく + にんにく加工品**\n- 食事:**ガーリックステーキ丼 + ガーリックラーメン + にんにくソフト**\n- 並列観光:R1 食 田子にんにく + R1 食 けいらん = 三戸郡食 2 大\n- アクセス:**東北道 八戸 IC 約 50 分** / JR 八戸駅 → 南部バス 約 90 分\n- 営業:9:00-18:00 通年(冬期短縮)",
    region: "tohoku",
    prefecture_ja: "青森県",
    gun_ja: "三戸郡",
    municipality_ja: "田子町",
    lg_code: "02443",
    area_types: ["shopping_district", "transit_hub"],
    lat: 40.3467,
    lon: 141.1683,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["michinoeki_takko", "garlic_center", "garlic_steak_don"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[aomori-food-r1] 尚無條目");
    return;
  }
  console.log(`[aomori-food-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(28)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[aomori-food-r1] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[aomori-food-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[aomori-food-r1] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
