// Seed 栃木県 R6 完結卷(20 筆 / Sprint 6.x — 第〇九卷栃木県收卷 → 累積 223)
// 食 4 / 住 3 / 衣 3 / 育 4 / 楽 4 / 行 2 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "栃木県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 食 (4) — 完結卷
  { slug: "nasu-chestnut-kuri", category: "food", sub_type: "tochigi_fruit", title_zh: "那須栗+栃木山栗(那須町+塩谷郡塩谷+大田原・1700-1900 年代山地栽培伝統+ R6 食 笠間栗(茨城)系統 + 9-10 月収穫期+ 道の駅+地元菓子店流通+ ¥1,200-2,500/kg+ R1 食 那須牛+R6 食 笠間栗観光連動)", title_ja: "那須栗+栃木山栗", romaji: "Nasu Chestnut", summary_zh: "**那須栗+栃木山栗は 1700-1900 年代山地栽培伝統+R6 食 笠間栗系統**(那須+塩谷+大田原)。9-10 月、道の駅+地元菓子店、¥1,200-2,500/kg。", content_md: "- 立地:**那須町 + 塩谷郡塩谷町 + 大田原市**\n- 期:**9-10 月収穫期**", region: "kanto", prefecture_ja: "栃木県", gun_ja: "那須郡", municipality_ja: "那須町", lg_code: "09407", area_types: ["farm_field"], lat: 36.9925, lon: 140.1175, season_start: "2026-09-01", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["nasu_chestnut"], source: "manual" },
  { slug: "tochigi-soba-modern", category: "food", sub_type: "tochigi_kyodo", title_zh: "栃木そば+ R4 食 足利そば現代化+ 山間そば手打ち(R4 食 足利そば派生・那須+塩原+鹿沼山間そば手打ち専門店 30+ 軒+ R1 衣 益子焼器そば膳と並ぶ栃木そば文化拡大・¥1,200-2,500)", title_ja: "栃木そばモダン", romaji: "Tochigi Soba Modern", summary_zh: "**栃木そば+R4 食 足利そば現代化+山間そばは R4 食派生・那須+塩原+鹿沼手打ち 30+ 軒**(R1 衣 益子焼器そば膳と並ぶ拡大)。¥1,200-2,500。", content_md: "- 全域:**那須 + 塩原 + 鹿沼 + 足利**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "鹿沼市", lg_code: "09205", area_types: ["restaurant_traditional"], lat: 36.5681, lon: 139.7456, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tochigi_soba_modern"], source: "manual" },
  { slug: "yashio-tsubaki-flower-tea", category: "food", sub_type: "tochigi_meika", title_zh: "ヤシオツツジ+栃木県花スイーツ+ハーブティー(R3 食 ヤシオマス+R4 食 那須ハーブ系統・栃木県花ヤシオツツジ由来スイーツ+ ハーブティー+ ジャム+ クッキー+ 道の駅+全国百貨店+ ¥350-1,800)", title_ja: "ヤシオツツジスイーツ", romaji: "Yashio Tsutsuji Sweets", summary_zh: "**ヤシオツツジ+栃木県花スイーツ+ハーブティーは R3 食 ヤシオマス+R4 食 ハーブ系統**(県花ヤシオツツジ由来)。スイーツ+ティー+ジャム+クッキー、¥350-1,800。", content_md: "- 全域:**栃木県全域**\n- 関係:**県花ヤシオツツジ由来**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["restaurant_traditional"], lat: 36.5658, lon: 139.8836, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yashio_tsutsuji"], source: "manual" },
  { slug: "tochigi-direct-sales-market", category: "food", sub_type: "tochigi_kyodo", title_zh: "栃木県農産物直売所+ R1 行 道の駅 closing 集約(全県 50+ 軒・R1 食 とちおとめ+スカイベリー+かんぴょう+ R1 食 那須牛+大田原牛+ R1 食 ニラ+栃木コシヒカリ全網羅+ R1 行 道の駅+農協ヒット+ 観光客代表)", title_ja: "栃木県直売所網羅", romaji: "Tochigi Direct Sales", summary_zh: "**栃木県農産物直売所+R1 行 道の駅 closing 集約は全県 50+ 軒**(R1 食 いちご+かんぴょう+牛+ニラ+コシヒカリ全網羅)。R1 行 道の駅+農協、観光客代表。", content_md: "- 全域:**栃木県全域**\n- 規模:**全県 50+ 軒**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["shopping_district", "farm_field"], lat: 36.5658, lon: 139.8836, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tochigi_direct_sales"], source: "manual" },

  // 住 (3) — 完結卷
  { slug: "yumoto-okukichu-onsen", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "奥日光湯元温泉総覧(日光市奥日光・788 開湯候補+ 標高 1500m+ R1 住 中禅寺湖温泉派生+ 全 12+ 軒小規模旅館・R1 楽 日光湯元スキー+R1 育 男体山連動+ 1 泊 2 食 ¥18,500-35,000+ 海外秘湯ファン代表)", title_ja: "奥日光湯元温泉総覧", romaji: "Yumoto Okunikko", summary_zh: "**奥日光湯元温泉総覧は 788 開湯候補・標高 1500m+R1 住 中禅寺湖派生**(日光・**全 12+ 軒小規模**)。R1 楽 湯元スキー+R1 育 男体山、¥18,500-35,000、海外秘湯ファン代表。", content_md: "- 立地:**日光市奥日光湯元**\n- 起源:**788 開湯候補**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["onsen_field"], lat: 36.7956, lon: 139.4225, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["yumoto_okunikko"], source: "manual" },
  { slug: "heike-yado-yunishigawa", category: "lodging", sub_type: "tochigi_kaigan_onsen", title_zh: "湯西川 平家落人民宿+古民家の宿(日光市湯西川・R1 住 湯西川温泉 1185 平家伝説派生+ 全 8+ 軒平家末裔系古民家+ R1 楽 雪まつり連動+ 1 泊 2 食 ¥9,500-18,500+ 海外文化体験観光客代表)", title_ja: "平家落人民宿", romaji: "Heike Yado", summary_zh: "**湯西川平家落人民宿+古民家の宿は R1 住 1185 平家伝説派生・全 8+ 軒平家末裔系古民家**(日光湯西川・**R1 楽 雪まつり連動**)。¥9,500-18,500、海外文化体験観光客代表。", content_md: "- 立地:**日光市湯西川**\n- 関係:**R1 住 湯西川温泉 1185 平家派生**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["onsen_field", "history_site_castle"], lat: 36.9869, lon: 139.6736, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["heike_yado"], source: "manual" },
  { slug: "mashiko-pottery-stay", category: "lodging", sub_type: "tochigi_other_onsen", title_zh: "益子陶芸の宿+滞在型工房(芳賀郡益子町・R1 衣 益子焼+R1 育 益子参考館派生・滞在型陶芸体験 1-7 日プラン+ 個別工房 5+ 軒+ R1 衣 陶器市連動+ 1 泊 2 食 ¥18,500-45,000+ 海外陶芸ファン代表)", title_ja: "益子陶芸の宿", romaji: "Mashiko Pottery Stay", summary_zh: "**益子陶芸の宿+滞在型工房は R1 衣 益子焼+R1 育 参考館派生・滞在型陶芸体験 1-7 日プラン**(益子・**個別工房 5+ 軒**)。R1 衣 陶器市連動、¥18,500-45,000、海外陶芸ファン代表。", content_md: "- 立地:**芳賀郡益子町**\n- 関係:**R1 衣 益子焼 + R1 育 参考館派生**", region: "kanto", prefecture_ja: "栃木県", gun_ja: "芳賀郡", municipality_ja: "益子町", lg_code: "09342", area_types: ["craft_workshop"], lat: 36.4661, lon: 140.1006, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["mashiko_pottery_stay"], source: "manual" },

  // 衣 (3) — 完結卷
  { slug: "mashiko-yaki-finale-set", category: "fashion", sub_type: "tochigi_mashiko_yaki", title_zh: "益子焼 closing 名作セット+人間国宝シリーズ(R1 衣 益子焼 1853+ R3 衣 モダン雑貨+ R5 衣 若手作家統合・濱田庄司人間国宝 1955+ 島岡達三 1996+ 現代名匠 5+ 名作家集約・¥15,000-150,000+ 国際美術館購買代表)", title_ja: "益子焼 closing 名作", romaji: "Mashiko Finale", summary_zh: "**益子焼 closing 名作セット+人間国宝シリーズは R1 衣+R3 衣+R5 衣 統合**(濱田庄司 1955+島岡達三 1996+現代名匠 5+ 名)。¥15,000-150,000、国際美術館購買代表。", content_md: "- 関係:**R1 衣 益子焼 1853 + R3 衣 + R5 衣 統合**", region: "kanto", prefecture_ja: "栃木県", gun_ja: "芳賀郡", municipality_ja: "益子町", lg_code: "09342", area_types: ["craft_workshop"], lat: 36.4661, lon: 140.1006, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["mashiko_finale_set"], source: "manual" },
  { slug: "tochigi-mascot-finale", category: "fashion", sub_type: "tochigi_folk_craft", title_zh: "とちまるくん+栃木県マスコット closing セット(R1 衣 とちまるくん 2011+R5 衣 スカイベリーグッズ統合・公式コラボ商品+お菓子+雑貨+T シャツセット・¥1,500-7,500+ 国内+海外観光客 closing 代表土産)", title_ja: "とちまるくん closing", romaji: "Tochimaru Finale", summary_zh: "**とちまるくん+栃木県マスコット closing セットは R1 衣 2011+R5 衣 スカイベリー統合**(コラボ商品+お菓子+雑貨+T シャツ)。¥1,500-7,500、closing 代表土産。", content_md: "- 関係:**R1 衣 とちまるくん 2011 + R5 衣 スカイベリーグッズ統合**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["shopping_district"], lat: 36.5658, lon: 139.8836, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tochimaru_finale"], source: "manual" },
  { slug: "nikko-unesco-souvenir", category: "fashion", sub_type: "tochigi_dept_store", title_zh: "日光 UNESCO 公式土産 closing(日光市・R1 育 日光東照宮+二荒山+輪王寺 UNESCO 1999 派生・公式マスコット+お守り+ご朱印帳+ T シャツ+食品・1999 UNESCO 認定 27 周年記念 closing セット ¥1,800-7,500・国際観光客 closing 代表)", title_ja: "日光 UNESCO 土産 closing", romaji: "Nikkō UNESCO Souvenir", summary_zh: "**日光 UNESCO 公式土産 closing は R1 育 日光東照宮+二荒山+輪王寺 UNESCO 1999 派生**(日光・**公式マスコット+お守り+ご朱印帳+T シャツ+食品**)。¥1,800-7,500、国際観光客 closing 代表。", content_md: "- 立地:**日光市**\n- 関係:**R1 育 日光二社一寺 UNESCO 1999 派生**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["shopping_district", "shrine_temple"], lat: 36.7197, lon: 139.6989, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["nikko_unesco_finale"], source: "manual" },

  // 育 (4) — 完結卷
  { slug: "tochigi-tachiki-kannon", category: "culture", sub_type: "tochigi_shrine_temple", title_zh: "立木観音(中禅寺・日光市・天応 2 年 782 創建 1243 年+ R1 育 日光二荒山神社派生+ 立木観音(国指定重要文化財)・千手観音菩薩立像 6m+ 中禅寺湖畔・入場 ¥500+ 海外観光客代表)", title_ja: "立木観音 中禅寺", romaji: "Tachiki Kannon", summary_zh: "**立木観音 中禅寺は天応 2 年 782 創建 1243 年・R1 育 二荒山派生**(日光中禅寺湖畔・**千手観音菩薩立像 6m・国指定重要文化財**)。¥500、海外観光客代表。", content_md: "- 立地:**日光市中禅寺湖畔**\n- 起源:**天応 2 年 782 創建 1243 年**\n- 認定:**国指定重要文化財**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["shrine_temple", "scenic_spot"], lat: 36.7375, lon: 139.4856, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tachiki_kannon", "782"], source: "manual" },
  { slug: "ootani-stone-mining", category: "culture", sub_type: "tochigi_history_museum", title_zh: "大谷石採掘場群+大谷観音(宇都宮市大谷町・R1 育 大谷資料館派生+ 大谷観音 (大谷寺)810 創建 1215 年+ 大谷石彫刻 千手観音磨崖仏 国指定特別史跡+ 入場 ¥500・大谷石建築見学コース連動)", title_ja: "大谷石採掘場群+大谷観音", romaji: "Ōya Stone & Kannon", summary_zh: "**大谷石採掘場群+大谷観音は R1 育 大谷資料館派生・大谷観音 810 創建 1215 年**(宇都宮・**千手観音磨崖仏国指定特別史跡**)。¥500、大谷石建築見学コース連動。", content_md: "- 立地:**宇都宮市大谷町**\n- 起源:**810 創建 1215 年**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["shrine_temple", "industrial_heritage"], lat: 36.6033, lon: 139.8275, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ootani_kannon", "810"], source: "manual" },
  { slug: "ozeguchi-park-3-bridge", category: "culture", sub_type: "tochigi_outdoor", title_zh: "尾瀬国立公園 栃木側+小尾瀬+三本松(日光市奥日光・1934 国立公園指定・標高 1400m 高層湿原+ 戦場ヶ原+小田代ヶ原+ ニッコウキスゲ群生地+ R1 育 中禅寺湖+R1 楽 紅葉観光連動+ 入場無料)", title_ja: "尾瀬国立公園 栃木側", romaji: "Oze Park Tochigi", summary_zh: "**尾瀬国立公園 栃木側+小尾瀬+三本松は 1934 国立公園指定・標高 1400m 高層湿原**(日光奥日光・**戦場ヶ原+小田代ヶ原+ニッコウキスゲ**)。R1 育 中禅寺湖+R1 楽 紅葉、無料。", content_md: "- 立地:**日光市奥日光**\n- 起源:**1934 国立公園指定**\n- 規模:**標高 1400m 高層湿原**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["scenic_spot"], lat: 36.7517, lon: 139.4475, season_start: "2026-06-01", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["oze_park_tochigi", "1934"], source: "manual" },
  { slug: "tochigi-ino-tadataka-route", category: "culture", sub_type: "tochigi_history_museum", title_zh: "栃木県奥州街道+日光街道宿場跡(R2 育 日光杉並木 1625 派生・宇都宮宿+間々田宿+小山宿+小金井宿+石橋宿+雀宮宿 6 宿場・国指定史跡候補+ 江戸期街道散策ルート 観光客向け代表+ 入場無料)", title_ja: "栃木奥州+日光街道宿場跡", romaji: "Tochigi Highway Stations", summary_zh: "**栃木県奥州街道+日光街道宿場跡は R2 育 杉並木 1625 派生・宇都宮+間々田+小山+小金井+石橋+雀宮 6 宿場**(国指定史跡候補)。江戸期街道散策ルート、観光客代表、無料。", content_md: "- 全域:**栃木県全域**\n- 関係:**R2 育 日光杉並木 1625 派生**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["history_site_castle"], lat: 36.5658, lon: 139.8836, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tochigi_highway_stations"], source: "manual" },

  // 楽 (4) — 完結卷
  { slug: "ootawara-yukimatsu-fest", category: "entertainment", sub_type: "tochigi_outdoor", title_zh: "大田原雪まつり+ R1 育 那須野が原冬季イベント(大田原市+那須塩原・1995 開催 30 年+ 1 月-2 月雪像コンテスト+雪燈籠+ R1 食 大田原牛+R3 食 大田原鶏肉飯観光客向け+ 観覧無料・国内観光客代表)", title_ja: "大田原雪まつり", romaji: "Ōtawara Yuki Matsuri", summary_zh: "**大田原雪まつり+R1 育 那須野が原冬季イベントは 1995 開催 30 年・1-2 月雪像+雪燈籠**(大田原+那須塩原・**R1 食 大田原牛+R3 食 鶏肉飯観光**)。観覧無料、国内観光客代表。", content_md: "- 立地:**大田原市 + 那須塩原市**\n- 起源:**1995 開催 30 年**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "大田原市", lg_code: "09210", area_types: ["festival_event"], lat: 36.8714, lon: 140.0153, season_start: null, season_end: null, event_start: "2026-01-25", event_end: "2026-02-15", price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ootawara_yuki"], source: "manual" },
  { slug: "kura-no-machi-cruise", category: "entertainment", sub_type: "tochigi_outdoor", title_zh: "蔵の街観光遊覧船+巴波川下り(栃木市・R1 育 蔵の街栃木派生・1975 開設 50 年+ 巴波川舟運体験+蔵見学+ R2 楽 蔵の街灯篭流し連動+ ¥1,000+ 国内観光客代表)", title_ja: "蔵の街遊覧船", romaji: "Kura Cruise", summary_zh: "**蔵の街観光遊覧船+巴波川下りは R1 育 蔵の街派生・1975 開設 50 年**(栃木市・**舟運体験+蔵見学**)。R2 楽 灯篭流し連動、¥1,000、国内観光客代表。", content_md: "- 立地:**栃木市巴波川**\n- 起源:**1975 開設 50 年**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "栃木市", lg_code: "09203", area_types: ["scenic_spot"], lat: 36.3811, lon: 139.7339, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kura_cruise"], source: "manual" },
  { slug: "nasu-art-stained-glass", category: "entertainment", sub_type: "tochigi_outdoor", title_zh: "那須ステンドグラス美術館+アート巡り(那須町・1995 開館 30 年+ ヨーロッパ古典+現代ステンドグラス 100+ 点+ 那須テラス+お菓子の城観光連動+ 入館 ¥1,300+ R1 住 那須リゾート 海外観光客 SNS 拡散代表)", title_ja: "那須ステンドアート", romaji: "Nasu Stained Art", summary_zh: "**那須ステンドグラス美術館+アート巡りは 1995 開館 30 年・ヨーロッパ古典+現代 100+ 点**(那須・**那須テラス+お菓子の城連動**)。¥1,300、海外 SNS 拡散代表。", content_md: "- 立地:**那須郡那須町**\n- 起源:**1995 開館 30 年**", region: "kanto", prefecture_ja: "栃木県", gun_ja: "那須郡", municipality_ja: "那須町", lg_code: "09407", area_types: ["museum_art"], lat: 36.9925, lon: 140.1175, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: ["火"], external_urls: {}, tags: ["nasu_stained_art"], source: "manual" },
  { slug: "tochigi-prefecture-finale-tour", category: "entertainment", sub_type: "tochigi_outdoor", title_zh: "栃木全県周遊観光ルート closing(R1-R6 統合・日光+鬼怒川+那須+塩原+栃木市+佐野+足利+益子 8 拠点周遊・3-5 日推奨・R1 行 LRT+R4 行 東武 2 日 pass 使用・国際観光客 closing 代表 全県体験)", title_ja: "栃木全県周遊 closing", romaji: "Tochigi Prefecture Tour", summary_zh: "**栃木全県周遊観光ルート closing は R1-R6 統合・8 拠点周遊**(日光+鬼怒川+那須+塩原+栃木市+佐野+足利+益子)。3-5 日推奨、LRT+東武 2 日 pass 使用、国際観光客 closing 代表。", content_md: "- 全域:**栃木県全域**\n- 構成:**日光 + 鬼怒川 + 那須 + 塩原 + 栃木市 + 佐野 + 足利 + 益子 8 拠点**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["scenic_spot"], lat: 36.5658, lon: 139.8836, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tochigi_prefecture_finale"], source: "manual" },

  // 行 (2) — 完結卷
  { slug: "tochigi-tour-mvp-pass", category: "transport", sub_type: "tochigi_pass_ticket", title_zh: "栃木 MVP 県内観光 pass(JR 在来線+東武日光線+鬼怒川+真岡鐵道+わたらせ渓谷+宇都宮 LRT 共通券・3 日 ¥7,500+ R1 育 日光東照宮+鹿島神宮+大洗+つくば+袋田全県周遊+ JR 駅売店購入+ 海外観光客代表)", title_ja: "栃木 MVP pass", romaji: "Tochigi MVP Pass", summary_zh: "**栃木 MVP 県内観光 pass は JR 在来線+東武日光+鬼怒川+真岡+わたらせ+LRT 共通**(3 日 ¥7,500・**R1 育 全県周遊**)。JR 駅売店、海外観光客代表。", content_md: "- 全域:**栃木県全域**\n- 期:**3 日連続使用**\n- 料金:**¥7,500**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "宇都宮市", lg_code: "09201", area_types: ["transit_hub"], lat: 36.5658, lon: 139.8836, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tochigi_mvp", "3_days", "7500yen"], source: "manual" },
  { slug: "tochigi-airport-helicopter", category: "transport", sub_type: "tochigi_airport", title_zh: "栃木県内ヘリコプター遊覧+VIP プレミアム交通(那須+日光+鬼怒川・地元事業者 3 社・1 機 ¥45,000-180,000・国際 VIP+海外団体観光客向け代表+ R1 育 日光東照宮+R1 育 中禅寺湖空中眺望ツアー)", title_ja: "栃木ヘリ遊覧 VIP", romaji: "Tochigi Helicopter VIP", summary_zh: "**栃木県内ヘリコプター遊覧+VIP プレミアム交通は地元事業者 3 社**(那須+日光+鬼怒川・**¥45,000-180,000/機**)。R1 育 東照宮+中禅寺湖空中眺望、国際 VIP+海外団体代表。", content_md: "- 全域:**那須町 + 日光市 + 鬼怒川**\n- 規模:**地元事業者 3 社**", region: "kanto", prefecture_ja: "栃木県", gun_ja: null, municipality_ja: "日光市", lg_code: "09206", area_types: ["transit_hub"], lat: 36.7197, lon: 139.6989, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 5, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["tochigi_helicopter_vip"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[tochigi-r6] 尚無條目"); return; }
  console.log(`[tochigi-r6] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) return;
  const sb = createAdminClient();
  const { error } = await sb.from("japan_entries").upsert(rows as any, { onConflict: "slug" });
  if (error) { console.error("[tochigi-r6] upsert failed:", error); process.exit(1); }
  console.log(`[tochigi-r6] Done — ${rows.length} rows.`);
}
main().catch((err) => { console.error(err); process.exit(1); });
