// Seed 千葉県 育 R1(21 筆 / Sprint 1.4 / 第十二卷)
// 成田山 4 / 佐原香取 4 / 安房上総一宮 3 / 城跡 2 / 博物館 3 / 寺社自然 5 = 21
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 成田山 (4)
  {
    slug: "naritasan-shinshoji-940",
    category: "culture", sub_type: "chiba_naritasan",
    title_zh: "成田山新勝寺(成田市・天慶 3 年 940 朱雀天皇代寛朝大僧正開基 1085+ 年+ 真言宗智山派大本山+ 全国年間参拝者第 2 位 1000 万人(1 位は明治神宮 + 川崎大師)+ 三重塔(国重文 1712)+ 大本堂+ 釈迦堂・参拝無料)",
    title_ja: "成田山新勝寺", romaji: "Naritasan Shinshōji",
    summary_zh: "**成田山新勝寺は 940 寛朝大僧正開基 1085+ 年・真言宗智山派大本山・全国年間参拝者第 2 位 1000 万人**(成田・**三重塔国重文 1712**)。参拝無料、R1 食 成田うなぎ + R1 衣 御朱印帳連動。",
    content_md: "- 立地:**成田市**\n- 起源:**天慶 3 年 940 寛朝大僧正開基 1085+ 年**\n- 認定:**真言宗智山派大本山 + 全国年間参拝者第 2 位 1000 万人 + 三重塔国重文 1712**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "成田市", lg_code: "12211",
    area_types: ["history_site_castle"], lat: 35.7864, lon: 140.3192,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["naritasan", "940", "1085_years", "national_no2_pilgrimage"], source: "manual",
  },
  {
    slug: "naritasan-park",
    category: "culture", sub_type: "chiba_naritasan",
    title_zh: "成田山公園(成田市・成田山新勝寺裏手 16.5ha 大庭園+ 1928 開園 97+ 年+ 3 池+ 渓谷+ 桜 350 本(4 月旬)+紅葉(11 月旬)+ 茶室・書道美術館併設+ R1 育 成田山新勝寺派生・入園無料)",
    title_ja: "成田山公園", romaji: "Naritasan Park",
    summary_zh: "**成田山公園は新勝寺裏手 16.5ha 大庭園・1928 開園 97+ 年・3 池+渓谷**(成田・**桜 350 本 4 月+紅葉 11 月**)。茶室+書道美術館併設、入園無料。",
    content_md: "- 立地:**成田市**\n- 起源:**1928 開園 97+ 年**\n- 構成:**16.5ha + 3 池 + 渓谷 + 桜 350 本 + 紅葉**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "成田市", lg_code: "12211",
    area_types: ["nature_park", "history_site_castle"], lat: 35.7867, lon: 140.3206,
    season_start: "2026-04-01", season_end: "2026-04-30", event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["naritasan_park", "1928"], source: "manual",
  },
  {
    slug: "naritasan-shodo-museum-1992",
    category: "culture", sub_type: "chiba_naritasan",
    title_zh: "成田山書道美術館(成田市・1992 開館 33+ 年+ 成田山新勝寺所蔵 6000+ 点書道作品・近代書道+ 中国清朝書道+ 日中書道交流展示+ R1 育 成田山公園内・観覧 ¥500)",
    title_ja: "成田山書道美術館", romaji: "Naritasan Shodō Museum",
    summary_zh: "**成田山書道美術館は 1992 開館 33+ 年・新勝寺所蔵 6000+ 点書道作品・近代+清朝+日中書道交流**(成田・**成田山公園内**)。観覧 ¥500。",
    content_md: "- 立地:**成田市**\n- 起源:**1992 開館 33+ 年**\n- 規模:**所蔵 6000+ 点書道作品**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "成田市", lg_code: "12211",
    area_types: ["museum_art"], lat: 35.7867, lon: 140.3206,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["naritasan_shodō", "1992"], source: "manual",
  },
  {
    slug: "narita-gion-matsuri",
    category: "culture", sub_type: "chiba_naritasan",
    title_zh: "成田祇園祭(成田市・成田山新勝寺御祭礼+ 江戸期 1721 享保 6 年発祥 304+ 年・千葉県指定無形民俗文化財候補・10 台山車屋台練り歩き+ 7 月初旬土日 3 日間+ 国際観光客向け解説あり・参加無料)",
    title_ja: "成田祇園祭", romaji: "Narita Gion Matsuri",
    summary_zh: "**成田祇園祭は新勝寺御祭礼・江戸期 1721 享保 6 年発祥 304+ 年・10 台山車屋台練り歩き**(成田・**7 月初旬土日 3 日間**)。国際観光客向け解説、参加無料。",
    content_md: "- 立地:**成田市**\n- 起源:**江戸期 1721 享保 6 年発祥 304+ 年**\n- 規模:**10 台山車屋台**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "成田市", lg_code: "12211",
    area_types: ["history_site_castle"], lat: 35.7864, lon: 140.3192,
    season_start: null, season_end: null, event_start: "2026-07-10T09:00:00+09:00", event_end: "2026-07-12T20:00:00+09:00",
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["narita_gion", "1721"], source: "manual",
  },

  // 佐原+ 香取 (4)
  {
    slug: "katori-jingu-1977",
    category: "culture", sub_type: "chiba_sawara_katori",
    title_zh: "香取神宮(香取市・下総国一宮+ 古代神武東征伝承+ 経津主大神祀る+ 全国 400+ 香取神社総本社+ 本殿+楼門+ 国指定重要文化財 1977+ R1 衣 神官装束派生・参拝無料)",
    title_ja: "香取神宮", romaji: "Katori Jingū",
    summary_zh: "**香取神宮は下総国一宮・古代神武東征伝承・経津主大神祀る・全国 400+ 香取神社総本社・本殿+楼門国重文 1977**(香取・**R1 衣 神官装束派生**)。参拝無料。",
    content_md: "- 立地:**香取市**\n- 認定:**下総国一宮 + 全国 400+ 香取神社総本社 + 本殿+楼門 国指定重要文化財 1977**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "香取市", lg_code: "12236",
    area_types: ["history_site_castle"], lat: 35.8861, lon: 140.5283,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["katori_jingū", "1977_designation", "ichinomiya_shimōsa"], source: "manual",
  },
  {
    slug: "ino-tadataka-museum-1998",
    category: "culture", sub_type: "chiba_sawara_katori",
    title_zh: "伊能忠敬記念館(香取市佐原・1998 開館 27+ 年+ 伊能忠敬 1745-1818 全国測量地図 1800-1816(大日本沿海輿地全図)+ 国指定史跡 1930+ 国宝 2010(伊能忠敬関係資料 2345 点)・観覧 ¥500)",
    title_ja: "伊能忠敬記念館", romaji: "Inō Tadataka Museum",
    summary_zh: "**伊能忠敬記念館は 1998 開館 27+ 年・伊能忠敬 1745-1818 全国測量地図(大日本沿海輿地全図)・国宝 2010 関係資料 2345 点**(佐原・**国指定史跡 1930**)。観覧 ¥500。",
    content_md: "- 立地:**香取市佐原**\n- 起源:**1998 開館 27+ 年**\n- 認定:**伊能忠敬関係資料国宝 2010 2345 点 + 旧宅国指定史跡 1930**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "香取市", lg_code: "12236",
    area_types: ["museum_art", "history_site_castle"], lat: 35.8983, lon: 140.5028,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["ino_tadataka", "1998", "national_treasure_2010"], source: "manual",
  },
  {
    slug: "sawara-dento-kenzo-1996",
    category: "culture", sub_type: "chiba_sawara_katori",
    title_zh: "佐原伝統的建造物群保存地区(香取市佐原・1996 国選定+ 関東圏初の重要伝建選定+ 江戸期商家町並み 200+ 年+ 小野川沿+ 北総の小江戸+ 伊能忠敬旧宅+ 商家 80+ 軒・小江戸さわらの大祭(7 + 10 月)・無料散策)",
    title_ja: "佐原伝建群", romaji: "Sawara Dentō Kenzō",
    summary_zh: "**佐原伝統的建造物群保存地区は 1996 国選定・関東圏初の重要伝建・江戸期商家町並み 200+ 年・北総の小江戸**(佐原・**小野川沿+商家 80+ 軒**)。大祭 7+10 月、無料。",
    content_md: "- 立地:**香取市佐原**\n- 認定:**1996 国選定 重要伝統的建造物群保存地区 + 関東圏初**\n- 規模:**江戸期商家町並み 200+ 年 + 商家 80+ 軒**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "香取市", lg_code: "12236",
    area_types: ["history_site_castle"], lat: 35.8983, lon: 140.5053,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["sawara_dentō_1996", "kanto_first"], source: "manual",
  },
  {
    slug: "sawara-no-taisai-2016",
    category: "culture", sub_type: "chiba_sawara_katori",
    title_zh: "佐原の大祭(香取市佐原・夏(7 月本宿祇園祭)+秋(10 月新宿諏訪祭)・国指定重要無形民俗文化財 2004+ ユネスコ無形文化遺産 2016「山・鉾・屋台行事」33 件中・関東 3 大山車祭+ 24 台山車練り歩き・参加無料)",
    title_ja: "佐原の大祭", romaji: "Sawara no Taisai",
    summary_zh: "**佐原の大祭は国指定重要無形民俗 2004+UNESCO 無形 2016「山・鉾・屋台行事」33 件中・関東 3 大山車祭・24 台山車練り歩き**(佐原・**夏 7 月+秋 10 月**)。参加無料。",
    content_md: "- 立地:**香取市佐原**\n- 認定:**国指定重要無形民俗 2004 + UNESCO 無形文化遺産 2016「山・鉾・屋台行事」33 件中**\n- 規模:**24 台山車 + 関東 3 大山車祭**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "香取市", lg_code: "12236",
    area_types: ["history_site_castle"], lat: 35.8983, lon: 140.5053,
    season_start: null, season_end: null, event_start: "2026-07-10T09:00:00+09:00", event_end: "2026-07-12T20:00:00+09:00",
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["sawara_taisai", "unesco_2016", "national_2004"], source: "manual",
  },

  // 安房+上総一宮 (3)
  {
    slug: "awa-jinja-ichinomiya",
    category: "culture", sub_type: "chiba_boso_shrine",
    title_zh: "安房神社(館山市大神宮・安房国一宮+ 古代天太玉命祀る+ 神武東征伝承 2685+ 年+ 全国忌部氏神社総本社系・上総一宮 玉前神社+下総一宮 香取神宮と並ぶ千葉 3 国一宮+ R1 衣 神楽装束派生・参拝無料)",
    title_ja: "安房神社", romaji: "Awa Jinja",
    summary_zh: "**安房神社は安房国一宮・古代天太玉命祀る・神武東征伝承 2685+ 年・全国忌部氏神社総本社系**(館山大神宮・**千葉 3 国一宮揃**)。R1 衣 神楽連動、参拝無料。",
    content_md: "- 立地:**館山市大神宮**\n- 認定:**安房国一宮 + 神武東征伝承 2685+ 年 + 全国忌部氏神社総本社系**\n- 並列:**安房 + 上総玉前 + 下総香取 = 千葉 3 国一宮**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "館山市", lg_code: "12205",
    area_types: ["history_site_castle"], lat: 34.9419, lon: 139.8347,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["awa_jinja", "ichinomiya_awa"], source: "manual",
  },
  {
    slug: "tamasaki-jinja-kazusa",
    category: "culture", sub_type: "chiba_boso_shrine",
    title_zh: "玉前神社(長生郡一宮町・上総国一宮+ 古代玉依姫命祀る+ 創建 1300+ 年+ 国指定重要文化財 1907 本殿(1687 再建)+ 9 月 13 日上総裸祭(千葉県指定無形民俗 1969)+ R1 衣 上総木綿派生・参拝無料)",
    title_ja: "玉前神社", romaji: "Tamasaki Jinja",
    summary_zh: "**玉前神社は上総国一宮・古代玉依姫命祀る・創建 1300+ 年・本殿国重文 1907**(一宮町・**9 月 13 日 上総裸祭千葉県指定民俗 1969**)。R1 衣 上総木綿連動、参拝無料。",
    content_md: "- 立地:**長生郡一宮町**\n- 認定:**上総国一宮 + 本殿 国指定重要文化財 1907 + 上総裸祭 千葉県指定無形民俗 1969**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: "長生郡", municipality_ja: "一宮町", lg_code: "12421",
    area_types: ["history_site_castle"], lat: 35.3739, lon: 140.3633,
    season_start: null, season_end: null, event_start: "2026-09-13T09:00:00+09:00", event_end: "2026-09-13T20:00:00+09:00",
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tamasaki_jinja", "ichinomiya_kazusa", "1907_designation"], source: "manual",
  },
  {
    slug: "nagoji-bando-33",
    category: "culture", sub_type: "chiba_boso_shrine",
    title_zh: "那古寺(館山市船形・717 養老 1 年 行基開基 1308+ 年・坂東三十三観音 33 番札所結願寺(千葉県内唯一の坂東結願寺)・国指定重要文化財 銅造千手観音立像 + 多宝塔 1761・参拝無料)",
    title_ja: "那古寺", romaji: "Nagoji",
    summary_zh: "**那古寺は 717 行基開基 1308+ 年・坂東三十三観音 33 番札所結願寺(千葉県内唯一)・銅造千手観音立像 + 多宝塔 1761 国重文**(館山船形)。参拝無料。",
    content_md: "- 立地:**館山市船形**\n- 起源:**717 養老 1 年 行基開基 1308+ 年**\n- 認定:**坂東 33 観音 33 番札所結願寺(千葉県内唯一)+ 銅造千手観音立像 + 多宝塔 1761 国重文**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "館山市", lg_code: "12205",
    area_types: ["history_site_castle"], lat: 35.0322, lon: 139.8361,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["nagoji", "717", "1308_years", "bando_33"], source: "manual",
  },

  // 城跡 (2)
  {
    slug: "tateyama-castle-hakkenden",
    category: "culture", sub_type: "chiba_castle",
    title_zh: "館山城+八犬伝記念館(館山市館山・里見氏 1580 築城 445+ 年+ 1781 廃城+ 1982 復元天守模型館・滝沢馬琴「南総里見八犬伝」1814-1842 28 年連載・舞台地・館山城跡千葉県指定史跡・観覧 ¥400)",
    title_ja: "館山城", romaji: "Tateyama Castle",
    summary_zh: "**館山城は里見氏 1580 築城 445+ 年・1781 廃城・1982 復元天守模型館・滝沢馬琴「南総里見八犬伝」1814-1842 舞台地**(館山・**千葉県指定史跡**)。観覧 ¥400。",
    content_md: "- 立地:**館山市館山**\n- 起源:**里見氏 1580 築城 445+ 年 + 1781 廃城**\n- 認定:**千葉県指定史跡 + 滝沢馬琴「南総里見八犬伝」1814-1842 舞台地**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "館山市", lg_code: "12205",
    area_types: ["history_site_castle", "museum_art"], lat: 34.9911, lon: 139.8442,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["tateyama_castle", "hakkenden", "1580"], source: "manual",
  },
  {
    slug: "sakura-castle-1962",
    category: "culture", sub_type: "chiba_castle",
    title_zh: "佐倉城跡(佐倉市・1611 慶長 16 年 土井利勝築城 414+ 年+ 1873 廃城・国指定史跡 1962+ 千葉県最大級城跡公園+ 城内国立歴史民俗博物館 1981 開館・1500 本桜 4 月旬+ R1 衣 佐倉武家屋敷観光連動・無料散策)",
    title_ja: "佐倉城跡", romaji: "Sakura Castle",
    summary_zh: "**佐倉城跡は 1611 土井利勝築城 414+ 年・国指定史跡 1962・千葉県最大級城跡公園・城内国立歴史民俗博物館 1981**(佐倉・**1500 本桜 4 月旬**)。R1 衣 武家屋敷連動、無料。",
    content_md: "- 立地:**佐倉市**\n- 起源:**1611 慶長 16 年 土井利勝築城 414+ 年**\n- 認定:**国指定史跡 1962 + 千葉県最大級城跡公園**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "佐倉市", lg_code: "12212",
    area_types: ["history_site_castle", "nature_park"], lat: 35.7236, lon: 140.2233,
    season_start: "2026-04-01", season_end: "2026-04-30", event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["sakura_castle", "1611", "1962_designation"], source: "manual",
  },

  // 博物館 (3)
  {
    slug: "rekihaku-1981",
    category: "culture", sub_type: "chiba_museum",
    title_zh: "国立歴史民俗博物館(佐倉市・1981 開館 44+ 年+ 国立 4 大博物館の 1+ 日本歴史総合展示+ 旧石器時代-現代まで 6 大時代・展示室総床 13,000 m²・R1 育 佐倉城跡内・常設観覧 ¥600)",
    title_ja: "国立歴史民俗博物館", romaji: "Rekihaku",
    summary_zh: "**国立歴史民俗博物館は 1981 開館 44+ 年・国立 4 大博物館の 1・日本歴史総合展示・展示室 13,000 m²**(佐倉・**佐倉城跡内**)。常設観覧 ¥600。",
    content_md: "- 立地:**佐倉市**\n- 起源:**1981 開館 44+ 年**\n- 認定:**国立 4 大博物館の 1 + 日本歴史総合展示**\n- 規模:**展示室 13,000 m²**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "佐倉市", lg_code: "12212",
    area_types: ["museum_art"], lat: 35.7222, lon: 140.2289,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["rekihaku", "1981", "national_4_great"], source: "manual",
  },
  {
    slug: "chiba-pref-museum-chuo",
    category: "culture", sub_type: "chiba_museum",
    title_zh: "千葉県立中央博物館(千葉市中央区・1989 開館 36+ 年+ 千葉県唯一の総合博物館+ 房総自然史+古代-現代房総通史+ 房総三国歴史特化+ 大利根分館(香取)+ 大多喜分館(大多喜)分館 2+ 観覧 ¥300)",
    title_ja: "千葉県立中央博物館", romaji: "Chiba Pref Chūō Museum",
    summary_zh: "**千葉県立中央博物館は 1989 開館 36+ 年・千葉県唯一の総合博物館・房総自然史+古代-現代房総通史**(千葉中央・**大利根+大多喜分館 2**)。観覧 ¥300。",
    content_md: "- 立地:**千葉市中央区**\n- 起源:**1989 開館 36+ 年**\n- 規模:**本館 + 大利根分館(香取) + 大多喜分館 = 分館 2**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["museum_art"], lat: 35.5961, lon: 140.1361,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["chiba_pref_museum", "1989"], source: "manual",
  },
  {
    slug: "hoki-museum-2010",
    category: "culture", sub_type: "chiba_museum",
    title_zh: "ホキ美術館(千葉市緑区・2010 開館 15+ 年+ 写実絵画専門美術館・国内唯一+ 保木将夫氏個人コレクション 480+ 点・現代写実絵画森本草介+磯江毅+島村信之+ 建築日本建築学会賞 2011・観覧 ¥1,830-2,300)",
    title_ja: "ホキ美術館", romaji: "Hoki Museum",
    summary_zh: "**ホキ美術館は 2010 開館 15+ 年・写実絵画専門美術館国内唯一・480+ 点コレクション・建築日本建築学会賞 2011**(千葉緑区)。観覧 ¥1,830-2,300。",
    content_md: "- 立地:**千葉市緑区**\n- 起源:**2010 開館 15+ 年**\n- 認定:**写実絵画専門美術館国内唯一 + 建築日本建築学会賞 2011**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["museum_art"], lat: 35.5392, lon: 140.1981,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: ["tuesday"],
    external_urls: {}, tags: ["hoki_museum", "2010", "shasai_kaiga"], source: "manual",
  },

  // 寺社+ 自然 (5)
  {
    slug: "nokogiriyama-nihonji-725",
    category: "culture", sub_type: "chiba_boso_nature",
    title_zh: "鋸山日本寺(安房郡鋸南町・725 神亀 2 年 行基開基 1300+ 年+ 関東最古寺院候補+ 標高 329m 鋸山山上・大仏 31m(日本最大の磨崖石仏 1783)+ 1500 羅漢像+ 地獄のぞき展望・JR 浜金谷駅+ 内房線・観覧 ¥700)",
    title_ja: "鋸山日本寺", romaji: "Nokogiriyama Nihonji",
    summary_zh: "**鋸山日本寺は 725 行基開基 1300+ 年・関東最古寺院候補・大仏 31m 日本最大磨崖石仏 1783+1500 羅漢像+地獄のぞき**(鋸南・**標高 329m**)。観覧 ¥700。",
    content_md: "- 立地:**安房郡鋸南町鋸山**\n- 起源:**725 神亀 2 年 行基開基 1300+ 年**\n- 認定:**関東最古寺院候補 + 大仏 31m 日本最大磨崖石仏 1783**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: "安房郡", municipality_ja: "鋸南町", lg_code: "12463",
    area_types: ["history_site_castle", "nature_park"], lat: 35.1597, lon: 139.8281,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["nihonji", "725", "1300_years", "kanto_oldest"], source: "manual",
  },
  {
    slug: "inubo-saki-lighthouse-1874",
    category: "culture", sub_type: "chiba_choshi_inubo",
    title_zh: "犬吠埼灯台(銚子市犬吠埼・1874 明治 7 年点灯 151+ 年+ 国指定重要文化財 2020+ 国登録有形文化財・関東最東端+ 北緯 35°42'27\"+ 元日初日の出スポット全国 3 大候補・登塔 ¥300・R1 育 銚子地球の丸く見える丘隣接)",
    title_ja: "犬吠埼灯台", romaji: "Inubō-saki Lighthouse",
    summary_zh: "**犬吠埼灯台は 1874 明治 7 年点灯 151+ 年・国指定重要文化財 2020・関東最東端・元日初日の出全国 3 大候補**(銚子)。登塔 ¥300、地球の丸く見える丘隣接。",
    content_md: "- 立地:**銚子市犬吠埼**\n- 起源:**1874 明治 7 年点灯 151+ 年**\n- 認定:**国指定重要文化財 2020 + 国登録有形文化財 + 関東最東端**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "銚子市", lg_code: "12202",
    area_types: ["history_site_castle", "beach_coast"], lat: 35.7081, lon: 140.8678,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["inubo_saki_1874", "national_designation_2020", "kanto_easternmost"], source: "manual",
  },
  {
    slug: "chikyu-marukumi-1985",
    category: "culture", sub_type: "chiba_choshi_inubo",
    title_zh: "地球の丸く見える丘展望館(銚子市犬吠埼・1985 開館 40+ 年+ 標高 73.6m 愛宕山+ 関東最東端展望台+ 太平洋 330 度パノラマ+ 利根川河口+ 鹿島灘+ 富士山 50km 望遠+ R1 育 犬吠埼灯台+ヤマサ醤油観光連動・観覧 ¥420)",
    title_ja: "地球の丸く見える丘", romaji: "Chikyū Marukumi",
    summary_zh: "**地球の丸く見える丘展望館は 1985 開館 40+ 年・標高 73.6m 愛宕山・関東最東端 330 度パノラマ・利根川河口+鹿島灘+富士山 50km 望遠**(銚子)。観覧 ¥420。",
    content_md: "- 立地:**銚子市犬吠埼愛宕山**\n- 起源:**1985 開館 40+ 年**\n- 規模:**標高 73.6m + 太平洋 330 度パノラマ**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "銚子市", lg_code: "12202",
    area_types: ["nature_park", "history_site_castle"], lat: 35.7028, lon: 140.8606,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["chikyu_marukumi", "1985"], source: "manual",
  },
  {
    slug: "kururi-castle-satomi",
    category: "culture", sub_type: "chiba_castle",
    title_zh: "久留里城+里見氏記念館(君津市久留里・1456 康正 2 年 上総武田氏築城 569+ 年+ 後の里見氏支城 1565-1590・1979 復元天守 + 君津市立久留里城址資料館 1979・千葉県指定史跡候補・観覧 ¥100)",
    title_ja: "久留里城", romaji: "Kururi Castle",
    summary_zh: "**久留里城は 1456 康正 2 年 上総武田氏築城 569+ 年・1565-1590 里見氏支城・1979 復元天守 + 久留里城址資料館 1979**(君津久留里)。観覧 ¥100。",
    content_md: "- 立地:**君津市久留里**\n- 起源:**1456 康正 2 年 上総武田氏築城 569+ 年**\n- 認定:**1979 復元天守 + 久留里城址資料館 1979**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "君津市", lg_code: "12225",
    area_types: ["history_site_castle", "museum_art"], lat: 35.3119, lon: 140.0922,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["kururi_castle", "1456"], source: "manual",
  },
  {
    slug: "yoro-keikoku-1934",
    category: "culture", sub_type: "chiba_boso_nature",
    title_zh: "養老渓谷(市原市+大多喜町・1934 県立公園指定 91+ 年+ 房総中部最大級渓谷+ 11 月下旬-12 月上旬紅葉名所(関東紅葉最終地候補)・粟又の滝(房総 3 大滝+落差 30m)・小湊鉄道+いすみ鉄道沿線+ R1 行 鉄道観光連動・無料散策)",
    title_ja: "養老渓谷", romaji: "Yōrō Keikoku",
    summary_zh: "**養老渓谷は 1934 県立公園指定 91+ 年・房総中部最大級渓谷・11 月下旬-12 月上旬紅葉名所(関東紅葉最終地候補)・粟又の滝落差 30m**(市原+大多喜)。R1 行 鉄道連動、無料。",
    content_md: "- 立地:**市原市 + 大多喜町**\n- 起源:**1934 県立公園指定 91+ 年**\n- 認定:**11 月下旬-12 月上旬紅葉名所(関東紅葉最終地候補)+ 粟又の滝(房総 3 大滝)**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "市原市", lg_code: "12219",
    area_types: ["nature_park"], lat: 35.2853, lon: 140.1606,
    season_start: "2026-11-20", season_end: "2026-12-10", event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yoro_keikoku", "1934", "kanto_last_momiji"], source: "manual",
  },
];

seedMain(rows, "chiba-culture-r1");
