// Seed 福島県 R3 補完(20 筆 / Sprint 3.x)
// 食 5 / 住 4 / 衣 3 / 育 3 / 楽 3 / 行 2 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "tohoku"; prefecture_ja: "福島県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 食 (5)
  { slug: "yamato-soba-kitakata", category: "food", sub_type: "fukushima_kyodo", title_zh: "山都そば(喜多方市山都町・「日本三大そば」(出雲+戸隠+山都)候補+ 江戸期から伝承+ 蕎麦店 30+ 軒+ 「水そば」「天ぷらそば」代表+ R1 食 会津そば+板そば(山形)と並ぶ東北そば文化+ 1 杯 ¥1,000-2,200)", title_ja: "山都そば", romaji: "Yamato Soba", summary_zh: "**山都そばは「日本三大そば」候補**(喜多方山都・**江戸期から伝承+蕎麦店 30+ 軒**)。「水そば」+天ぷらそば代表、R1 食 会津そば+山形板そばと並ぶ、¥1,000-2,200。", content_md: "- 立地:**喜多方市山都町**\n- 起源:**江戸期から伝承**\n- 認定:**「日本三大そば」候補**(出雲 + 戸隠 + 山都)\n- 構成:**「水そば」 + 天ぷらそば代表**\n- 規模:**30+ 軒**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "喜多方市", lg_code: "07208", area_types: ["restaurant_traditional"], lat: 37.6500, lon: 139.8742, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yamato_soba", "japan_3_soba", "edo_origin"], source: "manual" },
  { slug: "fukushima-asaichi", category: "food", sub_type: "fukushima_kyodo", title_zh: "ふくしま朝市+郡山朝市(福島市+郡山市・1945 戦後闇市起源 80 年+ JR 福島駅+郡山駅徒歩 5 分+ R1 食 桃+R1 食 会津地鶏+三陸海産 直売 50+ 軒+ 朝食定食 ¥800-1,500+ 観光客向け朝食代表)", title_ja: "ふくしま朝市", romaji: "Fukushima Asaichi", summary_zh: "**ふくしま朝市+郡山朝市は 1945 戦後闇市起源 80 年**(JR 福島駅+郡山駅徒歩 5 分・**50+ 軒**)。R1 食 桃+地鶏+三陸海産直売、朝食 ¥800-1,500、観光客代表。", content_md: "- 立地:**福島市 + 郡山市**(JR 駅徒歩 5 分)\n- 起源:**1945 戦後闇市起源 80 年**\n- 規模:**50+ 軒**\n- 構成:**R1 食 桃 + 会津地鶏 + 三陸海産 直売**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["restaurant_traditional", "shopping_district"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["日"], external_urls: {}, tags: ["fukushima_asaichi", "1945_post_war"], source: "manual" },
  { slug: "fukushima-yubeshi", category: "food", sub_type: "fukushima_meika", title_zh: "ゆべし(福島市+郡山+二本松+会津・江戸期 仙台藩+米沢藩献上系統共有+ もち米+黒砂糖+くるみ+醤油 練菓子+ R1 食 ままどおる+薄皮饅頭と並ぶ福島銘菓 3 大派生+ 老舗 5+ 軒+ 1 個 ¥150-400)", title_ja: "ゆべし", romaji: "Yubeshi", summary_zh: "**ゆべしは江戸期仙台藩+米沢藩献上系統共有**(福島+郡山+二本松+会津・**もち米+黒砂糖+くるみ+醤油練菓子**)。R1 食 ままどおる+薄皮饅頭並ぶ銘菓 3 大派生、¥150-400。", content_md: "- 立地:**福島市 + 郡山市 + 二本松市 + 会津若松市**\n- 起源:**江戸期 仙台藩 + 米沢藩献上系統共有**\n- 構成:**もち米 + 黒砂糖 + くるみ + 醤油 練菓子**\n- 並列:**R1 食 ままどおる + 薄皮饅頭 + R3 ゆべし = 福島銘菓 3 大派生**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["restaurant_traditional"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yubeshi", "edo_offering"], source: "manual" },
  { slug: "fukushima-iwakaki-natsuyasai", category: "food", sub_type: "fukushima_seafood", title_zh: "いわき夏野菜(いわき市+小名浜・常磐沿岸海風野菜・トマト+きゅうり+ナス+とうもろこし 等+ 1980 年代開発+ 道の駅 + 全国百貨店流通+ 6-9 月旬+ R1 食 メヒカリ+サンマと並ぶいわき特産)", title_ja: "いわき夏野菜", romaji: "Iwaki Natsuyasai", summary_zh: "**いわき夏野菜は常磐沿岸海風野菜**(いわき+小名浜・**1980 年代開発+トマト+きゅうり+ナス+とうもろこし**)。6-9 月旬、道の駅+百貨店、R1 食 メヒカリ+サンマと並ぶ。", content_md: "- 立地:**いわき市 + 小名浜**\n- 起源:**1980 年代開発**\n- 構成:**トマト + きゅうり + ナス + とうもろこし**\n- 期:**6-9 月旬**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "いわき市", lg_code: "07204", area_types: ["farm_field"], lat: 37.0539, lon: 140.8869, season_start: "2026-06-01", season_end: "2026-09-30", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["iwaki_natsuyasai", "1980s"], source: "manual" },
  { slug: "fukushima-aizu-miso-shoyu", category: "food", sub_type: "fukushima_kyodo", title_zh: "会津味噌+会津醤油(会津若松市+喜多方市+南会津・江戸期 会津藩献上発酵食品+ 米味噌・赤系・長期熟成+ R1 食 仙台味噌(R1 食 宮城)系統共有+ 老舗 8+ 軒(会津醸造+柏屋醸造)+ 全国百貨店流通+ ¥800-2,500/kg)", title_ja: "会津味噌+会津醤油", romaji: "Aizu Miso / Shoyu", summary_zh: "**会津味噌+醤油は江戸期会津藩献上**(会津若松+喜多方+南会津・**米味噌・赤系・長期熟成**)。R1 食 仙台味噌(宮城)系統共有、老舗 8+ 軒、¥800-2,500/kg。", content_md: "- 立地:**会津若松市 + 喜多方市 + 南会津郡**\n- 起源:**江戸期 会津藩献上発酵食品**\n- 構成:**米味噌・赤系・長期熟成**\n- 老舗:**会津醸造 + 柏屋醸造 等 8+ 軒**\n- 並列:**R1 食 仙台味噌(宮城) と並ぶ東北発酵食品**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["industrial_heritage"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aizu_miso_shoyu", "edo_aizu"], source: "manual" },

  // 住 (4)
  { slug: "shirakawa-business-citystay", category: "lodging", sub_type: "fukushima_other_onsen", title_zh: "白河セントラルホテル+ホテルアベスト白河(白河市・1995-2010 開業+ 全 80-130 室+ JR 東北本線 白河駅徒歩 3 分+ R1 楽 白河小峰城+R3 育 白河関跡 観光客向け+ 1 泊朝食付 ¥7,500-10,500)", title_ja: "白河セントラル+アベスト", romaji: "Shirakawa Central / AB", summary_zh: "**白河セントラル+アベストは 1995-2010 開業**(白河・**全 80-130 室+JR 白河駅徒歩 3 分**)。R1 楽 小峰城+R3 育 関跡観光、¥7,500-10,500。", content_md: "- 立地:**白河市**(JR 東北本線 白河駅徒歩 3 分)\n- 起源:**1995-2010 開業**\n- 規模:**全 80-130 室**\n- 並列観光:**R1 楽 白河小峰城 + R3 育 白河関跡**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "白河市", lg_code: "07205", area_types: ["shopping_district"], lat: 37.1264, lon: 140.2117, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["shirakawa_central"], source: "manual" },
  { slug: "soma-business-hotel", category: "lodging", sub_type: "fukushima_other_onsen", title_zh: "相馬市内+南相馬ビジネスホテル(相馬市+南相馬市・1985-2010 開業+ 全 60-100 室+ JR 常磐線 相馬駅+原ノ町駅徒歩 3-5 分+ R1 食 相馬うに+ホッキ+R1 楽 相馬野馬追 1300 年観光客向け+ 1 泊朝食付 ¥7,500-10,500)", title_ja: "相馬市内ビジネスホテル", romaji: "Sōma Business Hotel", summary_zh: "**相馬市内+南相馬ビジネスは 1985-2010 開業**(相馬+南相馬・**全 60-100 室+JR 常磐線駅徒歩 3-5 分**)。R1 食 うに+ホッキ+R1 楽 野馬追観光、¥7,500-10,500。", content_md: "- 立地:**相馬市 + 南相馬市**(JR 常磐線 相馬駅 + 原ノ町駅徒歩 3-5 分)\n- 起源:**1985-2010 開業**\n- 規模:**全 60-100 室**\n- 並列:**R1 食 相馬うに+ホッキ + R1 楽 相馬野馬追 1300 年**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "相馬市", lg_code: "07209", area_types: ["shopping_district"], lat: 37.7967, lon: 140.9189, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["soma_business"], source: "manual" },
  { slug: "aizu-tsuruga-pension", category: "lodging", sub_type: "fukushima_aizu_onsen", title_zh: "会津ペンション村+グランピング(会津若松市+磐梯町+猪苗代・1990 年代開設+ 全 12 軒小規模ペンション+ R1 育 鶴ヶ城+R1 楽 五色沼+磐梯山 観光体験型+ 1 泊 2 食 ¥10,500-15,500+ ファミリー+カップル向け)", title_ja: "会津ペンション村", romaji: "Aizu Pension Mura", summary_zh: "**会津ペンション村+グランピングは 1990 年代開設**(会津若松+磐梯+猪苗代・**全 12 軒小規模**)。R1 育 鶴ヶ城+R1 楽 五色沼+磐梯山観光、¥10,500-15,500、ファミリー+カップル。", content_md: "- 立地:**会津若松市 + 磐梯町 + 猪苗代町**\n- 起源:**1990 年代開設**\n- 規模:**全 12 軒小規模ペンション**\n- 並列観光:**R1 育 鶴ヶ城 + R1 楽 五色沼 + 磐梯山**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["scenic_spot"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["aizu_pension", "1990s"], source: "manual" },
  { slug: "iwaki-spa-resort-hotel", category: "lodging", sub_type: "fukushima_iwaki_onsen", title_zh: "いわきハワイアンズホテルハワイアンズ(いわき市・R1 楽 スパリゾートハワイアンズ 1966 派生・モノリスタワー 2003 拡張+ 全 580 室・東北最大級リゾート+ ファミリー向け代表+ R1 食 メヒカリ+サンマ会席+ 1 泊 2 食 ¥18,500-32,000)", title_ja: "ホテルハワイアンズ", romaji: "Hotel Hawaiians", summary_zh: "**ホテルハワイアンズは R1 楽 1966 派生・モノリスタワー 2003 拡張**(いわき・**全 580 室・東北最大級**)。ファミリー代表+R1 食 メヒカリ+サンマ会席、¥18,500-32,000。", content_md: "- 立地:**いわき市**(R1 楽 スパリゾートハワイアンズ 1966 派生)\n- 起源:**モノリスタワー 2003 拡張**\n- 規模:**全 580 室・東北最大級リゾート**\n- 看板:**ファミリー向け代表**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "いわき市", lg_code: "07204", area_types: ["onsen_field", "festival_event"], lat: 37.0539, lon: 140.8869, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["hawaiians_hotel", "2003_monolith", "580_rooms"], source: "manual" },

  // 衣 (3)
  { slug: "fukushima-ramen-yamato-soba-goods", category: "fashion", sub_type: "fukushima_dept_store", title_zh: "ラーメン+そばグッズ(R1 食 喜多方ラーメン+R3 食 山都そば派生・乾麺パック+どんぶり+ 食器+ T シャツ+ 道の駅+全国百貨店+ ¥500-3,500+ R1 衣 喜多方蔵造り街並み観光客向け代表)", title_ja: "ラーメン+そばグッズ", romaji: "Ramen / Soba Goods", summary_zh: "**ラーメン+そばグッズは R1 食 喜多方+R3 食 山都派生**(乾麺パック+どんぶり+食器+T シャツ)。道の駅+全国百貨店、¥500-3,500、R1 衣 喜多方蔵造り観光代表。", content_md: "- 関係:**R1 食 喜多方ラーメン + R3 食 山都そば派生**\n- 構成:**乾麺パック + どんぶり + 食器 + T シャツ**\n- 価格:**¥500-3,500**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "喜多方市", lg_code: "07208", area_types: ["shopping_district"], lat: 37.6500, lon: 139.8742, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ramen_soba_goods"], source: "manual" },
  { slug: "fukushima-ouchijuku-craft", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "大内宿藁細工+草履(南会津郡下郷町・R1 育 大内宿 1640 重伝建 1981+R1 衣 土産物店派生・伝統藁工芸+ 草履+草帽+米俵オブジェ+ ¥600-3,500+ 海外観光客 SNS 拡散+ 江戸期農村工芸代表)", title_ja: "大内宿藁細工", romaji: "Ōuchijuku Wara Zaiku", summary_zh: "**大内宿藁細工+草履は R1 育 1640 重伝建 1981+R1 衣 土産派生**(下郷・**草履+草帽+米俵オブジェ**)。¥600-3,500、SNS 拡散、江戸期農村工芸代表。", content_md: "- 立地:**南会津郡下郷町大内宿**\n- 関係:**R1 育 大内宿 1640 重伝建 1981 + R1 衣 土産物店街 派生**\n- 構成:**草履 + 草帽 + 米俵オブジェ**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "南会津郡", municipality_ja: "下郷町", lg_code: "07362", area_types: ["craft_workshop", "shopping_district"], lat: 37.3258, lon: 139.8606, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ouchijuku_wara"], source: "manual" },
  { slug: "fukushima-bandai-mountain-grade", category: "fashion", sub_type: "fukushima_folk_craft", title_zh: "磐梯山+五色沼グッズ(R1 育 磐梯山 1819m+R1 楽 五色沼派生・自然写真集+ ポスター+T シャツ+缶バッジ+ 道の駅+全国百貨店+ ¥500-3,500+ R1 楽 観光客 SNS 拡散ハイキング派遣土産代表)", title_ja: "磐梯山+五色沼グッズ", romaji: "Bandai / Goshikinuma Goods", summary_zh: "**磐梯山+五色沼グッズは R1 育+R1 楽 派生**(自然写真集+ポスター+T シャツ+缶バッジ)。道の駅+全国百貨店、¥500-3,500、SNS 拡散ハイキング派土産代表。", content_md: "- 関係:**R1 育 磐梯山 1819m + R1 楽 五色沼派生**\n- 構成:**自然写真集 + ポスター + T シャツ + 缶バッジ**\n- 価格:**¥500-3,500**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "耶麻郡", municipality_ja: "猪苗代町", lg_code: "07408", area_types: ["shopping_district"], lat: 37.5567, lon: 140.1058, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["bandai_goshiki_goods"], source: "manual" },

  // 育 (3)
  { slug: "miharu-rekishi-mingu-yakata", category: "culture", sub_type: "fukushima_history_museum", title_zh: "三春町歴史民俗資料館(田村郡三春町・1985 開館+ R1 衣 三春駒+人形派生・三春藩 270 年資料+ R1 食 ままどおる三万石(三春)関連展示+ R1 育 三春滝桜 1000 年関連+ 入館 ¥300+ JR 磐越東線 三春駅徒歩 5 分)", title_ja: "三春町歴史民俗資料館", romaji: "Miharu Rekishi Mingu Yakata", summary_zh: "**三春町歴史民俗資料館は 1985 開館**(三春・**R1 衣 三春駒+人形+三春藩 270 年資料**)。R1 食 ままどおる+R1 育 滝桜関連、¥300、JR 三春駅徒歩 5 分。", content_md: "- 立地:**田村郡三春町**(JR 磐越東線 三春駅徒歩 5 分)\n- 起源:**1985 開館 40 年**\n- 関連:**R1 衣 三春駒+人形 + R1 食 ままどおる + R1 育 三春滝桜 1000 年**\n- 入館:**¥300**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "田村郡", municipality_ja: "三春町", lg_code: "07521", area_types: ["museum_art"], lat: 37.4444, lon: 140.4842, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["miharu_rekishi", "1985"], source: "manual" },
  { slug: "fukushima-mineral-museum-iwaki", category: "culture", sub_type: "fukushima_history_museum", title_zh: "いわき石炭・化石館 ほるる(R1 楽 いわきほるる派生詳細・1984 開館・福島炭鉱産業 100+ 年伝統+ フタバスズキリュウ 国指定 1973 化石+ R1 楽 ハワイアンズ近く 観光客代表+ 入館 ¥660)", title_ja: "いわき石炭・化石館 ほるる", romaji: "Iwaki Horuru Detail", summary_zh: "**いわき石炭・化石館ほるるは R1 楽 派生詳細**(1984 開館・**福島炭鉱産業 100+ 年+フタバスズキリュウ国指定 1973 化石**)。R1 楽 ハワイアンズ近く、¥660、観光客代表。", content_md: "- 立地:**いわき市**\n- 起源:**1984 開館 41 年**\n- 関係:**R1 楽 いわきほるる派生詳細**\n- 構成:**福島炭鉱産業 100+ 年 + フタバスズキリュウ 国指定 1973 化石**\n- 入館:**¥660**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "いわき市", lg_code: "07204", area_types: ["museum_art", "industrial_heritage"], lat: 37.0539, lon: 140.8869, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["iwaki_horuru_detail"], source: "manual" },
  { slug: "soma-nakamura-castle", category: "culture", sub_type: "fukushima_history_museum", title_zh: "中村城跡(相馬市・1611 相馬利胤築城+ 1871 廃城+ R1 楽 相馬野馬追 1300 年関連歴史拠点+ 県指定史跡+ 桜名所 4 月+ 入場無料+ 馬陵公園として整備+ R1 食 相馬うに+ホッキ観光客向け)", title_ja: "中村城跡", romaji: "Nakamura-jō Ato", summary_zh: "**中村城跡は 1611 相馬利胤築城・1871 廃城**(相馬・**R1 楽 野馬追 1300 年関連歴史拠点**)。県指定史跡、桜名所、無料、馬陵公園、R1 食 うに+ホッキ観光。", content_md: "- 立地:**相馬市**\n- 起源:**1611 相馬利胤築城・1871 廃城**\n- 関連:**R1 楽 相馬野馬追 1300 年関連歴史拠点**\n- 認定:**県指定史跡**\n- 構成:**馬陵公園として整備**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "相馬市", lg_code: "07209", area_types: ["history_site_castle", "scenic_spot"], lat: 37.7967, lon: 140.9189, season_start: "2026-04-15", season_end: "2026-04-25", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["nakamura_jo", "1611_soma"], source: "manual" },

  // 楽 (3)
  { slug: "kitakata-zo-tour-detail", category: "entertainment", sub_type: "fukushima_outdoor", title_zh: "喜多方蔵見学ツアー(喜多方市・R1 衣 蔵造り街並み 4000+ 棟派生・蔵商家+蔵蕎麦+蔵漆器博物館 巡り+ R1 楽 喜多方蔵まつり関連通年観光+ ガイド付ツアー ¥1,500-3,500+ 海外観光客 SNS 拡散代表)", title_ja: "喜多方蔵見学ツアー", romaji: "Kitakata Zō Tour", summary_zh: "**喜多方蔵見学ツアーは R1 衣 蔵造り 4000+ 棟派生**(蔵商家+蔵蕎麦+蔵漆器博物館巡り)。R1 楽 喜多方蔵まつり連動、¥1,500-3,500、SNS 拡散。", content_md: "- 立地:**喜多方市**\n- 関係:**R1 衣 喜多方蔵造り 4000+ 棟派生 + R1 楽 喜多方蔵まつり連動**\n- 構成:**蔵商家 + 蔵蕎麦 + 蔵漆器博物館 巡り**\n- 価格:**ガイド付ツアー ¥1,500-3,500**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "喜多方市", lg_code: "07208", area_types: ["festival_event", "scenic_spot"], lat: 37.6500, lon: 139.8742, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["kitakata_zo_tour"], source: "manual" },
  { slug: "iizaka-fireworks", category: "entertainment", sub_type: "fukushima_outdoor", title_zh: "飯坂温泉花火大会(福島市飯坂・R1 住 飯坂温泉郷派生・1985 開始 40 年+ 8 月最終週末+ 5,000 発花火+ 観覧無料+ R1 食 円盤餃子+R1 楽 花見山観光と組合せ+ 来場 10 万人)", title_ja: "飯坂温泉花火大会", romaji: "Iizaka Hanabi", summary_zh: "**飯坂温泉花火大会は R1 住 派生・1985 開始 40 年**(福島飯坂・**8 月最終週末+5000 発**)。観覧無料、R1 食 円盤餃子+R1 楽 花見山観光、10 万人来場。", content_md: "- 立地:**福島市飯坂**(R1 住 飯坂温泉郷)\n- 起源:**1985 開始 40 年**\n- 期:**8 月最終週末**\n- 規模:**5,000 発花火 + 来場 10 万人**\n- 観覧:**無料**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["festival_event"], lat: 37.8244, lon: 140.4633, season_start: null, season_end: null, event_start: "2026-08-29", event_end: "2026-08-29", price_tier: 1, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["iizaka_hanabi", "1985"], source: "manual" },
  { slug: "fukushima-strawberry-house", category: "entertainment", sub_type: "fukushima_outdoor", title_zh: "ふくしまいちご狩り園+いちごハウス(郡山+須賀川+いわき・1990 年代開発+ 12-5 月旬+ もういっこ・とちおとめ・ベリーツ品種+ 観光いちご狩り 30+ 園+ ¥1,500-2,500/30 分食べ放題+ R1 食 桃+ラ・フランス観光園と並ぶ通年フルーツ観光)", title_ja: "ふくしまいちご狩り", romaji: "Fukushima Ichigo", summary_zh: "**ふくしまいちご狩り園は 1990 年代開発**(郡山+須賀川+いわき・**12-5 月+30+ 園**)。¥1,500-2,500/30 分食べ放題、R1 食 桃と並ぶ通年フルーツ観光。", content_md: "- 立地:**郡山市 + 須賀川市 + いわき市**\n- 起源:**1990 年代開発**\n- 種:**もういっこ + とちおとめ + ベリーツ**\n- 期:**12-5 月旬**\n- 規模:**観光園 30+ 園**\n- 料金:**¥1,500-2,500/30 分食べ放題**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "郡山市", lg_code: "07203", area_types: ["scenic_spot", "farm_field"], lat: 37.4006, lon: 140.3597, season_start: "2026-12-01", season_end: "2027-05-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: 7, closed_days: [], external_urls: {}, tags: ["fukushima_ichigo", "1990s"], source: "manual" },

  // 行 (2)
  { slug: "aizu-tour-bus-pass-2day", category: "transport", sub_type: "fukushima_pass_ticket", title_zh: "会津エリアパス・2 日券(R1 行 会津バス 1 日券派生・JR 会津鉄道+磐越西線+会津バス 2 日 ¥3,500+ R1 育 鶴ヶ城+大内宿+R1 楽 五色沼+R1 食 喜多方ラーメン+R1 衣 喜多方蔵 全会津周遊+ 観光客代表)", title_ja: "会津エリアパス 2 日券", romaji: "Aizu Area Pass 2-Day", summary_zh: "**会津エリアパス 2 日券は ¥3,500**(JR 会津鉄道+磐越西+会津バス・**R1 育 鶴ヶ城+大内宿+R1 楽 五色沼+R1 食 喜多方+R1 衣 喜多方蔵全会津周遊**)。観光代表。", content_md: "- 対象:**JR 会津鉄道 + 磐越西線 + 会津バス**\n- 期:**2 日連続使用**\n- 料金:**¥3,500**\n- 並列観光:**R1 育 鶴ヶ城 + 大内宿 + R1 楽 五色沼 + R1 食 喜多方 + R1 衣 喜多方蔵**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["transit_hub"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aizu_2day_pass", "3500yen"], source: "manual" },
  { slug: "fukushima-ouchijuku-shuttle", category: "transport", sub_type: "fukushima_bus", title_zh: "会津若松-大内宿シャトルバス(R1 行 会津バス派生・会津若松駅 ↔ 湯野上温泉駅 ↔ 大内宿・1 日 6-8 便+ ¥1,200/区間+ R1 育 大内宿 1640 重伝建 1981 観光客 唯一直行アクセス+ 4-11 月運航+ 海外観光客向け代表)", title_ja: "会津-大内宿シャトル", romaji: "Aizu Ōuchijuku Shuttle", summary_zh: "**会津若松-大内宿シャトルバスは R1 行 派生**(会津若松駅 ↔ 湯野上温泉駅 ↔ 大内宿・**1 日 6-8 便+¥1,200/区間**)。R1 育 大内宿 1640 重伝建唯一直行、4-11 月、海外観光客代表。", content_md: "- 区間:**会津若松駅 ↔ 湯野上温泉駅 ↔ 大内宿**\n- 便数:**1 日 6-8 便**\n- 料金:**¥1,200/区間**\n- 期:**4-11 月運航**\n- 並列:**R1 育 大内宿 1640 重伝建 1981 唯一直行アクセス**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "下郷町", lg_code: "07362", area_types: ["transit_hub"], lat: 37.3258, lon: 139.8606, season_start: "2026-04-15", season_end: "2026-11-15", event_start: null, event_end: null, price_tier: 1, booking_window_days: 7, closed_days: [], external_urls: {}, tags: ["ouchijuku_shuttle"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[fukushima-r3] 尚無條目"); return; }
  console.log(`[fukushima-r3] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[fukushima-r3] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[fukushima-r3] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[fukushima-r3] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
