// Seed 香川県 育 R1(21 筆 / Sprint 1.4 / 第十五卷)
// 寺社 6 / 寺城 4 / 博物館 5 / 文化財 6 = 21
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 寺社 6
  {
    slug: "kotohira-gu",
    category: "culture", sub_type: "kagawa_shrine_temple",
    title_zh: "金刀比羅宮(琴平町・1001 創建伝承 1024+ 年+ 大物主神+ 崇徳天皇祀る・「こんぴらさん」海上交通安全総本社+ 1368 段石段(本宮 785 段+奥社 1368 段)+ 国指定重要文化財 表書院 円山応挙 1788+ 年間参拝者 300 万人・参拝無料・JR 琴平駅徒歩 15 分)",
    title_ja: "金刀比羅宮", romaji: "Kotohira-gū",
    summary_zh: "**金刀比羅宮は 1001 創建伝承 1024+ 年・大物主神+崇徳天皇祀る・「こんぴらさん」海上交通安全総本社・1368 段石段・国重文 表書院 1788(円山応挙)・年間 300 万人**(琴平)。参拝無料。",
    content_md: "- 立地:**仲多度郡琴平町**\n- 起源:**1001 創建伝承 1024+ 年**\n- 認定:**「こんぴらさん」海上交通安全総本社 + 1368 段石段(本宮 785 段 + 奥社 1368 段) + 国指定重要文化財 表書院 円山応挙 1788 + 年間参拝者 300 万人**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "仲多度郡", municipality_ja: "琴平町", lg_code: "37404",
    area_types: ["history_site_castle"], lat: 34.1856, lon: 133.8200,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kotohira_gu", "1024_years", "1368_steps"], source: "manual",
  },
  {
    slug: "zentsuji-774",
    category: "culture", sub_type: "kagawa_shrine_temple",
    title_zh: "善通寺(善通寺市・774 宝亀 5 年 空海(弘法大師)生誕地+ 807 大同 2 年 空海開創 1218+ 年+ 真言宗善通寺派総本山+ 四国八十八ヶ所第 75 番札所+ 国指定重要文化財 五重塔 1902+ 金堂 1699+ 高野山+京都東寺と並ぶ「弘法大師 3 大霊場」・参拝無料)",
    title_ja: "善通寺", romaji: "Zentsuji",
    summary_zh: "**善通寺は 774 空海生誕地+807 空海開創 1218+ 年・真言宗善通寺派総本山・第 75 番札所・国重文 五重塔 1902+金堂 1699・高野山+京都東寺並ぶ「弘法大師 3 大霊場」**(善通寺)。参拝無料。",
    content_md: "- 立地:**善通寺市**\n- 起源:**774 宝亀 5 年 空海生誕地 + 807 大同 2 年 空海開創 1218+ 年**\n- 認定:**真言宗善通寺派総本山 + 四国八十八ヶ所第 75 番札所 + 国指定重要文化財 五重塔 1902 + 金堂 1699 + 「弘法大師 3 大霊場」**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "善通寺市", lg_code: "37204",
    area_types: ["history_site_castle"], lat: 34.2244, lon: 133.7833,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["zentsuji_774", "kobo_birthplace", "75th_temple"], source: "manual",
  },
  {
    slug: "yashima-ji-754",
    category: "culture", sub_type: "kagawa_shrine_temple",
    title_zh: "屋島寺(高松市屋島・754 天平勝宝 6 年 鑑真和上開基 1271+ 年+ 真言宗御室派寺院+ 四国八十八ヶ所第 84 番札所+ 国指定重要文化財 本堂 1618+ 屋島山頂源平古戦場 1185 派生・参拝無料)",
    title_ja: "屋島寺", romaji: "Yashima-ji",
    summary_zh: "**屋島寺は 754 天平勝宝 6 年 鑑真和上開基 1271+ 年・真言宗御室派・第 84 番札所・国重文 本堂 1618・屋島山頂源平古戦場 1185 派生**(高松屋島)。参拝無料。",
    content_md: "- 立地:**高松市屋島**\n- 起源:**754 天平勝宝 6 年 鑑真和上開基 1271+ 年**\n- 認定:**真言宗御室派寺院 + 四国八十八ヶ所第 84 番札所 + 国指定重要文化財 本堂 1618 + 屋島山頂源平古戦場 1185 派生**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["history_site_castle"], lat: 34.3611, lon: 134.1056,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yashima_ji_754", "84th_temple"], source: "manual",
  },
  {
    slug: "yakuri-ji-829",
    category: "culture", sub_type: "kagawa_shrine_temple",
    title_zh: "八栗寺(高松市八栗・829 天長 6 年 空海開基 1196+ 年+ 真言宗大覚寺派・四国八十八ヶ所第 85 番札所+ 五剣山(366m) 山頂寺院+ 八栗ケーブル 1964 派生(R1 行)・聖天信仰本尊・参拝無料)",
    title_ja: "八栗寺", romaji: "Yakuri-ji",
    summary_zh: "**八栗寺は 829 空海開基 1196+ 年・真言宗大覚寺派・第 85 番札所・五剣山 366m 山頂・八栗ケーブル 1964 派生**(高松八栗)。聖天信仰本尊、参拝無料。",
    content_md: "- 立地:**高松市八栗**\n- 起源:**829 天長 6 年 空海開基 1196+ 年**\n- 認定:**真言宗大覚寺派 + 四国八十八ヶ所第 85 番札所 + 五剣山(366m) 山頂寺院**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["history_site_castle", "nature_park"], lat: 34.3556, lon: 134.1267,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yakuri_ji_829", "85th_temple"], source: "manual",
  },
  {
    slug: "tamura-jinja-ichinomiya",
    category: "culture", sub_type: "kagawa_shrine_temple",
    title_zh: "田村神社+ 讃岐国一宮(高松市一宮町・古代讃岐国一宮 1300+ 年+ 大水主大明神+猿田彦命+稚日女命他祀る・延喜式内社・国指定無形民俗文化財「御神幸祭」候補・JR 琴平線一宮駅徒歩 5 分・参拝無料)",
    title_ja: "田村神社", romaji: "Tamura Jinja",
    summary_zh: "**田村神社+讃岐国一宮は古代讃岐国一宮 1300+ 年・大水主大明神+猿田彦命+稚日女命祀る・延喜式内社**(高松一宮町)。JR 琴平線一宮徒歩 5 分、参拝無料。",
    content_md: "- 立地:**高松市一宮町**\n- 起源:**古代讃岐国一宮 1300+ 年**\n- 認定:**延喜式内社 + 大水主大明神 + 猿田彦命 + 稚日女命他祀る**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["history_site_castle"], lat: 34.2517, lon: 134.0117,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tamura_jinja", "ichinomiya_sanuki"], source: "manual",
  },
  {
    slug: "shiramine-ji-815",
    category: "culture", sub_type: "kagawa_shrine_temple",
    title_zh: "白峯寺+ 崇徳上皇陵(坂出市青海町・815 弘仁 6 年 空海開基 1210+ 年+ 真言宗御室派・四国八十八ヶ所第 81 番札所+ 1164 崇徳上皇陵 (国指定史跡 1936)+ 国指定重要文化財 客殿+護摩堂 1690・参拝無料)",
    title_ja: "白峯寺+崇徳上皇陵", romaji: "Shiramine-ji",
    summary_zh: "**白峯寺+崇徳上皇陵は 815 空海開基 1210+ 年・第 81 番札所・1164 崇徳上皇陵(国史跡 1936)・国重文 客殿+護摩堂 1690**(坂出青海)。参拝無料。",
    content_md: "- 立地:**坂出市青海町**\n- 起源:**815 弘仁 6 年 空海開基 1210+ 年**\n- 認定:**真言宗御室派 + 四国八十八ヶ所第 81 番札所 + 1164 崇徳上皇陵(国指定史跡 1936) + 国指定重要文化財 客殿 + 護摩堂 1690**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "坂出市", lg_code: "37203",
    area_types: ["history_site_castle"], lat: 34.3300, lon: 133.8167,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shiramine_ji_815", "sutoku_emperor"], source: "manual",
  },

  // 寺城 4
  {
    slug: "kokubun-ji-741",
    category: "culture", sub_type: "kagawa_shrine_temple",
    title_zh: "讃岐国分寺(高松市国分寺町・741 聖武天皇命建立 1284+ 年+ 真言宗御室派+ 四国八十八ヶ所第 80 番札所+ 国指定史跡 1922 讃岐国分寺跡+ 国指定重要文化財 本堂 1300 鎌倉時代・参拝無料・JR 国分駅徒歩 5 分)",
    title_ja: "讃岐国分寺", romaji: "Sanuki Kokubun-ji",
    summary_zh: "**讃岐国分寺は 741 聖武天皇命建立 1284+ 年・真言宗御室派・第 80 番札所・国史跡 1922 国分寺跡・国重文 本堂 1300 鎌倉時代**(高松国分寺町)。JR 国分徒歩 5 分、参拝無料。",
    content_md: "- 立地:**高松市国分寺町**\n- 起源:**741 聖武天皇命建立 1284+ 年**\n- 認定:**第 80 番札所 + 国指定史跡 1922 讃岐国分寺跡 + 国指定重要文化財 本堂 1300 鎌倉時代**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["history_site_castle"], lat: 34.2517, lon: 133.9550,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["sanuki_kokubun_741", "80th_temple"], source: "manual",
  },
  {
    slug: "takamatsu-castle-1588",
    category: "culture", sub_type: "kagawa_castle",
    title_zh: "高松城+ 玉藻公園(高松市玉藻町・1588 天正 16 年 生駒親正築城 437+ 年+ 1642 松平頼重入封・国指定史跡 1955 高松城跡+ 月見櫓+艮櫓+水手御門+渡櫓 国指定重要文化財・全国 3 大水城(松山+今治+高松)・¥200・JR 高松駅徒歩 3 分)",
    title_ja: "高松城+玉藻公園", romaji: "Takamatsu Castle",
    summary_zh: "**高松城+玉藻公園は 1588 生駒親正築城 437+ 年・1642 松平頼重入封・国史跡 1955・国重文 月見櫓+艮櫓+水手御門+渡櫓・全国 3 大水城**(高松玉藻)。¥200、JR 高松徒歩 3 分。",
    content_md: "- 立地:**高松市玉藻町**\n- 起源:**1588 天正 16 年 生駒親正築城 437+ 年 + 1642 松平頼重入封**\n- 認定:**国指定史跡 1955 + 月見櫓 + 艮櫓 + 水手御門 + 渡櫓 国指定重要文化財 + 全国 3 大水城(松山 + 今治 + 高松)**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["history_site_castle"], lat: 34.3517, lon: 134.0494,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["takamatsu_castle_1588", "1955_designation"], source: "manual",
  },
  {
    slug: "marugame-castle-1597",
    category: "culture", sub_type: "kagawa_castle",
    title_zh: "国宝丸亀城(丸亀市一番丁・1597 慶長 2 年 生駒親正築城 428+ 年+ 1660 京極家入封後天守+ 1950 国宝指定・現存 12 天守の 1+ 全国最高石垣 60m(全国 3 段石垣 No.1)+ R1 衣 丸亀うちわ 1633 派生・¥400・JR 丸亀駅徒歩 15 分)",
    title_ja: "国宝丸亀城", romaji: "Marugame Castle",
    summary_zh: "**国宝丸亀城は 1597 生駒親正築城 428+ 年・1660 京極入封後天守・1950 国宝指定・現存 12 天守の 1・全国最高石垣 60m(全国 3 段石垣 No.1)**(丸亀)。¥400、JR 丸亀徒歩 15 分。",
    content_md: "- 立地:**丸亀市一番丁**\n- 起源:**1597 慶長 2 年 生駒親正築城 428+ 年 + 1660 京極家入封後天守**\n- 認定:**1950 国宝指定 + 現存 12 天守の 1 + 全国最高石垣 60m(全国 3 段石垣 No.1)**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "丸亀市", lg_code: "37202",
    area_types: ["history_site_castle"], lat: 34.2867, lon: 133.7944,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["marugame_castle_1597", "national_treasure_1950", "current_12_tenshu"], source: "manual",
  },
  {
    slug: "ritsurin-koen-1745",
    category: "culture", sub_type: "kagawa_castle",
    title_zh: "栗林公園(高松市栗林町・1625 高松藩主松平頼重 造園起源+ 1745 完成 280+ 年+ 国指定特別名勝 1953(全国 36 件中の 1)+ 75ha 大名庭園(全国最大級)+ 「一歩一景」ミシュラン三つ星 2009 + 6 池+13 築山+ R1 衣 栗林公園着物連動・¥410)",
    title_ja: "栗林公園", romaji: "Ritsurin Kōen",
    summary_zh: "**栗林公園は 1625 松平頼重造園+1745 完成 280+ 年・国特別名勝 1953(全国 36 件中)・75ha 大名庭園・ミシュラン三つ星 2009**(高松栗林)。¥410、R1 衣 着物連動。",
    content_md: "- 立地:**高松市栗林町**\n- 起源:**1625 高松藩主松平頼重 造園起源 + 1745 完成 280+ 年**\n- 認定:**国指定特別名勝 1953(全国 36 件中の 1) + 75ha 大名庭園(全国最大級) + ミシュラン三つ星 2009**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["nature_park", "history_site_castle"], lat: 34.3300, lon: 134.0428,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["ritsurin_1745", "1953_special_meishō", "michelin_2009"], source: "manual",
  },

  // 博物館 5
  {
    slug: "kagawa-pref-museum-1999",
    category: "culture", sub_type: "kagawa_museum",
    title_zh: "香川県立ミュージアム(高松市玉藻町・1999 開館 26+ 年+ 香川県立歴史博物館+ 美術館合築・2014 リニューアル+ 香川 6000 年通史展示+ 弘法大師空海+ 讃岐藩 + 屋島源平古戦場史料・観覧 ¥410・R1 育 高松城跡隣接)",
    title_ja: "香川県立ミュージアム", romaji: "Kagawa Pref Museum",
    summary_zh: "**香川県立ミュージアムは 1999 開館 26+ 年・歴史博+美術館合築・2014 リニューアル・6000 年通史+空海+讃岐藩+屋島源平**(高松玉藻)。¥410、R1 育 高松城隣接。",
    content_md: "- 立地:**高松市玉藻町**\n- 起源:**1999 開館 26+ 年 + 2014 リニューアル**\n- 認定:**香川県立歴史博物館 + 美術館合築**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["museum_art"], lat: 34.3517, lon: 134.0494,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["kagawa_pref_museum_1999"], source: "manual",
  },
  {
    slug: "chichu-museum-2004",
    category: "culture", sub_type: "kagawa_naoshima",
    title_zh: "地中美術館(直島町・2004 安藤忠雄設計開館 21+ 年+ 全国唯一の地中(地下)美術館・建築自体が芸術作品+ クロード・モネ「睡蓮」+ ジェームズ・タレル+ ウォルター・デ・マリア 3 作家常設展示・¥2,100・国際 SNS 海外建築・現代美術代表)",
    title_ja: "地中美術館", romaji: "Chichu Art Museum",
    summary_zh: "**地中美術館は 2004 安藤忠雄設計 21+ 年・全国唯一の地中美術館・建築自体が芸術作品・モネ「睡蓮」+タレル+デ・マリア 3 作家常設**(直島)。¥2,100、海外建築+現代美術代表。",
    content_md: "- 立地:**香川郡直島町**\n- 起源:**2004 安藤忠雄設計開館 21+ 年**\n- 認定:**全国唯一の地中(地下)美術館 + 建築自体が芸術作品 + クロード・モネ「睡蓮」+ ジェームズ・タレル + ウォルター・デ・マリア 3 作家常設展示**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "香川郡", municipality_ja: "直島町", lg_code: "37364",
    area_types: ["museum_art"], lat: 34.4583, lon: 133.9967,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: ["monday"],
    external_urls: {}, tags: ["chichu_2004", "ando_tadao", "monet_naoshima"], source: "manual",
  },
  {
    slug: "lee-ufan-museum-2010",
    category: "culture", sub_type: "kagawa_naoshima",
    title_zh: "李禹煥美術館(直島町・2010 安藤忠雄設計開館 15+ 年+ 韓国現代美術家李禹煥(リ・ウーファン) 個人美術館+ 「もの派」代表作家+ R1 楽 直島ベネッセアート 1992 派生・¥1,050・国際 SNS 海外現代アート代表)",
    title_ja: "李禹煥美術館", romaji: "Lee Ufan Museum",
    summary_zh: "**李禹煥美術館は 2010 安藤忠雄設計 15+ 年・韓国現代美術家李禹煥個人美術館・「もの派」代表作家・R1 楽 ベネッセアート 1992 派生**(直島)。¥1,050、海外現代アート代表。",
    content_md: "- 立地:**香川郡直島町**\n- 起源:**2010 安藤忠雄設計開館 15+ 年**\n- 認定:**韓国現代美術家李禹煥(リ・ウーファン)個人美術館 + 「もの派」代表作家**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "香川郡", municipality_ja: "直島町", lg_code: "37364",
    area_types: ["museum_art"], lat: 34.4583, lon: 133.9967,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["lee_ufan_2010"], source: "manual",
  },
  {
    slug: "benesse-house-museum-1992",
    category: "culture", sub_type: "kagawa_naoshima",
    title_zh: "ベネッセハウスミュージアム(直島町・1992 安藤忠雄設計開館 33+ 年+ 全国アート系美術館 + ホテル合築発祥(R1 住 派生)+ 草間彌生+ジャスパー・ジョーンズ+デ・クーニング 国際現代美術家展示・¥1,300)",
    title_ja: "ベネッセハウスミュージアム", romaji: "Benesse House Museum",
    summary_zh: "**ベネッセハウスミュージアムは 1992 安藤忠雄設計 33+ 年・全国アート系美術館+ホテル合築発祥(R1 住 派生)・草間彌生+ジャスパー+デ・クーニング**(直島)。¥1,300。",
    content_md: "- 立地:**香川郡直島町**\n- 起源:**1992 安藤忠雄設計開館 33+ 年**\n- 認定:**全国アート系美術館 + ホテル合築発祥(R1 住 ベネッセハウス派生)**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "香川郡", municipality_ja: "直島町", lg_code: "37364",
    area_types: ["museum_art"], lat: 34.4583, lon: 133.9967,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["benesse_museum_1992"], source: "manual",
  },
  {
    slug: "kyu-kompira-oshibai-1835",
    category: "culture", sub_type: "kagawa_chusan_culture",
    title_zh: "旧金毘羅大芝居「金丸座」(琴平町・1835 天保 6 年建立 190+ 年+ 国指定重要文化財 1970+ 全国最古現役歌舞伎劇場+ 江戸期金毘羅参詣文化派生・現役歌舞伎公演毎年 4 月 「四国こんぴら歌舞伎大芝居」 1985 復活+ 740 席・観覧 ¥500)",
    title_ja: "旧金毘羅大芝居", romaji: "Kompira Ōshibai",
    summary_zh: "**旧金毘羅大芝居「金丸座」は 1835 天保 6 年建立 190+ 年・国重文 1970・全国最古現役歌舞伎劇場・現役公演毎年 4 月「こんぴら歌舞伎大芝居」 1985 復活**(琴平)。¥500。",
    content_md: "- 立地:**仲多度郡琴平町**\n- 起源:**1835 天保 6 年建立 190+ 年**\n- 認定:**国指定重要文化財 1970 + 全国最古現役歌舞伎劇場 + 「四国こんぴら歌舞伎大芝居」 1985 復活**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "仲多度郡", municipality_ja: "琴平町", lg_code: "37404",
    area_types: ["history_site_castle"], lat: 34.1856, lon: 133.8200,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kompira_oshibai_1835", "national_oldest_kabuki"], source: "manual",
  },

  // 文化財 6
  {
    slug: "yashima-genpei-battle",
    category: "culture", sub_type: "kagawa_takamatsu_culture",
    title_zh: "屋島源平古戦場+ 屋島山頂(高松市屋島・1185 屋島源平合戦 840+ 年+ 那須与一扇の的射伝説・源義経屋島の戦い勝利・国指定史跡 1934+ 国指定天然記念物 1934(屋島樹叢)+ 屋島寺 R1 育 隣接・無料散策)",
    title_ja: "屋島源平古戦場", romaji: "Yashima Genpei",
    summary_zh: "**屋島源平古戦場+屋島山頂は 1185 840+ 年・那須与一扇の的射・源義経屋島の戦い勝利・国指定史跡 1934+国指定天然記念物 1934**(高松屋島)。R1 育 屋島寺隣接、無料。",
    content_md: "- 立地:**高松市屋島**\n- 起源:**1185 屋島源平合戦 840+ 年**\n- 認定:**国指定史跡 1934 + 国指定天然記念物 1934(屋島樹叢) + 那須与一扇の的射伝説 + 源義経屋島の戦い勝利**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["history_site_castle", "nature_park"], lat: 34.3611, lon: 134.1056,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yashima_genpei_1185", "1934_designation"], source: "manual",
  },
  {
    slug: "kankakei-meisho-1934",
    category: "culture", sub_type: "kagawa_islands_culture",
    title_zh: "寒霞渓(小豆島町+ 内海+ 池田・1934 国指定名勝 91+ 年+ 全国 3 大渓谷美(妙義+耶馬溪と並ぶ)+ 11 月紅葉名所(関西紅葉名所 1 位候補)+ 寒霞渓ロープウェイ 1962 派生・¥1,890/往復・標高 612m 星ヶ城山+ 第 4 紀火山地形)",
    title_ja: "寒霞渓", romaji: "Kankakei",
    summary_zh: "**寒霞渓は 1934 国指定名勝 91+ 年・全国 3 大渓谷美(妙義+耶馬溪)・11 月紅葉名所(関西 1 位候補)・ロープウェイ 1962 派生・標高 612m 星ヶ城山**(小豆島)。¥1,890/往復。",
    content_md: "- 立地:**小豆郡小豆島町 + 内海 + 池田**\n- 起源:**1934 国指定名勝 91+ 年**\n- 認定:**全国 3 大渓谷美(妙義 + 耶馬溪と並ぶ) + 11 月紅葉名所(関西紅葉名所 1 位候補) + 標高 612m 星ヶ城山**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "小豆郡", municipality_ja: "小豆島町", lg_code: "37324",
    area_types: ["nature_park"], lat: 34.4889, lon: 134.2378,
    season_start: "2026-11-01", season_end: "2026-11-30", event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kankakei_1934"], source: "manual",
  },
  {
    slug: "24-eyes-village-1987",
    category: "culture", sub_type: "kagawa_islands_culture",
    title_zh: "二十四の瞳映画村(小豆島町苗羽・1987 開園 38+ 年+ 1928 壺井栄「二十四の瞳」原作派生+ 1954 木下惠介映画派生+ 1987 朝倉摂セット保存・大正期分校再現・小豆島観光中核・¥890+ R1 衣 24 の瞳アパレル連動)",
    title_ja: "二十四の瞳映画村", romaji: "24 Eyes Village",
    summary_zh: "**二十四の瞳映画村は 1987 開園 38+ 年・1928 壺井栄原作+1954 木下惠介映画派生・1987 朝倉摂セット保存・大正期分校再現**(小豆島苗羽)。¥890、R1 衣 アパレル連動。",
    content_md: "- 立地:**小豆郡小豆島町苗羽**\n- 起源:**1987 開園 38+ 年**\n- 関連:**1928 壺井栄「二十四の瞳」原作 + 1954 木下惠介映画派生**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: "小豆郡", municipality_ja: "小豆島町", lg_code: "37324",
    area_types: ["history_site_castle", "museum_art"], lat: 34.4847, lon: 134.2500,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["24_eyes_1987"], source: "manual",
  },
  {
    slug: "zenigata-1633",
    category: "culture", sub_type: "kagawa_seisan_culture",
    title_zh: "観音寺銭形+ 寛永通宝砂絵琴弾公園(観音寺市・1633 寛永 10 年伝承 392+ 年+ 国指定史跡 1932 琴弾公園+ 砂絵 122m × 90m 寛永通宝模様+ 江戸期讃岐藩主丸亀京極家伝承・R1 衣 銭形アパレル派生・無料散策)",
    title_ja: "観音寺銭形琴弾公園", romaji: "Zenigata Kotohiki",
    summary_zh: "**観音寺銭形+寛永通宝砂絵琴弾公園は 1633 伝承 392+ 年・国史跡 1932 琴弾公園・砂絵 122m × 90m 寛永通宝・江戸期讃岐藩京極家伝承**(観音寺)。R1 衣 派生、無料。",
    content_md: "- 立地:**観音寺市**\n- 起源:**1633 寛永 10 年伝承 392+ 年**\n- 認定:**国指定史跡 1932 琴弾公園 + 砂絵 122m × 90m 寛永通宝模様**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "観音寺市", lg_code: "37205",
    area_types: ["history_site_castle", "nature_park"], lat: 34.1267, lon: 133.6611,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["zenigata_1633", "1932_designation"], source: "manual",
  },
  {
    slug: "ichinomiya-ji-83rd",
    category: "culture", sub_type: "kagawa_shrine_temple",
    title_zh: "一宮寺(高松市一宮町・703 大宝 3 年 義淵僧正開基 1322+ 年+ 真言宗御室派+ 四国八十八ヶ所第 83 番札所+ R1 育 田村神社隣接(讃岐国一宮の本地仏寺院)・参拝無料・JR 琴平線一宮駅徒歩 8 分)",
    title_ja: "一宮寺", romaji: "Ichinomiya-ji",
    summary_zh: "**一宮寺は 703 大宝 3 年 義淵僧正開基 1322+ 年・真言宗御室派・第 83 番札所・R1 育 田村神社(讃岐国一宮)隣接の本地仏寺院**(高松一宮)。JR 琴平線一宮徒歩 8 分、参拝無料。",
    content_md: "- 立地:**高松市一宮町**\n- 起源:**703 大宝 3 年 義淵僧正開基 1322+ 年**\n- 認定:**第 83 番札所 + R1 育 田村神社(讃岐国一宮)の本地仏寺院**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["history_site_castle"], lat: 34.2517, lon: 134.0117,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["ichinomiya_ji_703", "83rd_temple"], source: "manual",
  },
  {
    slug: "shikoku-mura",
    category: "culture", sub_type: "kagawa_takamatsu_culture",
    title_zh: "四国村ミウゼアム(高松市屋島中町・1976 開園 49+ 年+ 5ha 野外古民家博物館+ 四国 4 県古民家 33 棟移築復原+ 国指定重要文化財建築 12 棟+ R1 育 屋島源平古戦場 1185 隣接・観覧 ¥1,600・JR 屋島駅徒歩 5 分)",
    title_ja: "四国村ミウゼアム", romaji: "Shikoku Mura",
    summary_zh: "**四国村ミウゼアムは 1976 開園 49+ 年・5ha 野外古民家博物館・四国 4 県古民家 33 棟移築復原・国重文 12 棟・R1 育 屋島源平古戦場 1185 隣接**(高松屋島)。¥1,600、JR 屋島徒歩 5 分。",
    content_md: "- 立地:**高松市屋島中町**\n- 起源:**1976 開園 49+ 年**\n- 認定:**5ha 野外古民家博物館 + 四国 4 県古民家 33 棟移築復原 + 国指定重要文化財建築 12 棟**",
    region: "shikoku", prefecture_ja: "香川県", gun_ja: null, municipality_ja: "高松市", lg_code: "37201",
    area_types: ["museum_art", "history_site_castle"], lat: 34.3611, lon: 134.1056,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: ["tuesday"],
    external_urls: {}, tags: ["shikoku_mura_1976"], source: "manual",
  },
];

seedMain(rows, "kagawa-culture-r1");
