// Seed 静岡県 · 行類 條目 → public.japan_entries(Sprint 19.6 行 R1)
//
// 静岡 = 東海道の大動脈 + 7 私鉄 + 伊豆アクセス:
//   - 東海道新幹線(東京 ↔ 京阪神の大動脈・県内 6 駅:熱海・三島・新富士・静岡・掛川・浜松)
//   - JR 在来線:東海道本線・伊東線・御殿場線(富士山眺望)・身延線
//   - 7 私鉄:静鉄 1908・遠鉄 1923・大井川 1925(SL)・天浜 1935(国登録駅多数)
//             伊豆急 1961・伊豆箱根駿豆線 1898・岳南電車 1949
//   - 静岡空港(2009 開港・牧之原・FDA・国内/中韓便)
//   - 駿河湾フェリー(清水 ↔ 土肥・伊豆連絡)・初島連絡船
//   - バス:しずてつ・遠鉄・東海バス(伊豆全域)
//   - 高速バス:東京 ↔ 静岡/浜松/沼津/三島/伊豆
//   - フリーパス:伊豆急 2 日・東海バス伊豆フリー・しずてつ
//
// 28 筆構成:
//   Phase A 新幹線駅 hub 5(概論・熱海・三島・静岡・浜松)
//   Phase B JR 在来線 3(東海道本線・伊東線・御殿場線)
//   Phase C 7 私鉄 7(静鉄・遠鉄・大井川・天浜・伊豆急・伊豆箱根・岳南)
//   Phase D 空港 1(静岡空港 2009)
//   Phase E フェリー・連絡船 2(駿河湾フェリー・初島)
//   Phase F バス 3(しずてつ・遠鉄・東海バス)
//   Phase G 高速バス 2(東京-静岡・東京-浜松)
//   Phase H フリーパス 2(伊豆急 2 日・東海バス伊豆)
//   Phase I 観光船・空港アクセス・駅 hub 3(下田クルーズ・空港リムジン・沼津駅)
//
// Usage:
//   npm run seed:japan-shizuoka-transport:dry
//   npm run seed:japan-shizuoka-transport

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "shizuoka_tokaido_shinkansen"
  | "shizuoka_local_railway"
  | "shizuoka_izu_access"
  | "transit_hub"
  | "limited_express_private"
  | "ticket_promo"
  | "route_map_urban"
  | "ferry_island"
  | "airport_access"
  | "area_access_guide"
  | "rental_car_tips";

interface SeedRow {
  slug: string;
  category: "transport";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "chubu";
  prefecture_ja: "静岡県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // Phase A — 新幹線駅 hub(5 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "tokaido-shinkansen-shizuoka-overview",
    category: "transport",
    sub_type: "shizuoka_tokaido_shinkansen",
    title_zh: "東海道新幹線・靜岡縣內 6 駅(熱海/三島/新富士/靜岡/掛川/浜松)",
    title_ja: "東海道新幹線(静岡県内)",
    romaji: "Tokaido Shinkansen",
    summary_zh: "**東海道新幹線は静岡県を東西に横断する大動脈**。1964 年開業以来、東京~新大阪 515 km の中間 200 km を静岡県が占め、6 駅(熱海・三島・新富士・静岡・掛川・浜松)が県内に並ぶ全国最多の県別駅数。「のぞみ」全通過、「ひかり」一部停車、「こだま」全駅停車の 3 種列車。",
    content_md: "- 開業:1964 年(昭和39)10 月 1 日 東京オリンピック開幕直前\n- 静岡県内駅数:6(全国最多・47 都道府県中)\n  - 熱海(伊豆玄関・全国 1 位の温泉観光駅)\n  - 三島(伊豆+箱根西側 hub・1969 開業)\n  - 新富士(1988 開業・富士市・浅間大社アクセス)\n  - 静岡(県庁所在地・全列車停車除く「のぞみ」)\n  - 掛川(1988 開業・掛川城・遠州西部 hub)\n  - 浜松(政令市・全列車停車除く「のぞみ」一部)\n- 所要(東京から):熱海 50 分・静岡 1h・浜松 1h35 分\n- 運賃:東京-熱海 ¥3740・東京-静岡 ¥6470・東京-浜松 ¥7900\n- 全列車本数:1 日 約 350 本(両方向)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["urban_central"],
    lat: 34.972,
    lon: 138.388,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://railway.jr-central.co.jp/" },
    tags: ["shizuoka_tokaido_shinkansen", "tokaido", "shinkansen", "1964", "6_stations"],
    source: "manual",
  },
  {
    slug: "atami-station-hub-shinkansen",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "JR 熱海駅(東海道新幹線+伊東線・伊豆東岸玄関口・全国観光駅 1 位級)",
    title_ja: "JR 熱海駅",
    romaji: "Atami Station",
    summary_zh: "**JR 熱海駅は伊豆東岸の最大玄関口**。東海道新幹線+東海道本線+JR 伊東線(伊豆急直通)が交わる、伊豆観光客の 70% が経由する hub。1 日乗降客数 1.6 万人、駅前は商店街+海岸沿い徒歩 10 分、東口に「ラスカ熱海」(2016 開業の駅商業施設)。",
    content_md: "- 路線:東海道新幹線(全列車停車)+ 東海道本線 + 伊東線\n- 1 日乗降:約 1.6 万人(うち新幹線 60%)\n- 駅商業施設:ラスカ熱海(東口・2016 開業・100+ 店)\n- 駅前:熱海銀座商店街・海岸通・サンビーチ徒歩 10 分\n- 観光客占有率:伊豆観光客の 70%(残り 30% は三島駅 + 伊豆箱根経由)\n- アクセス:東京 50 分(新幹線)・小田原 30 分(在来線)\n- 隣接:駅徒歩圏に多数温泉旅館",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "熱海市",
    lg_code: "22205",
    area_types: ["urban_central"],
    lat: 35.106,
    lon: 139.078,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["transit_hub", "atami_station", "izu_gateway", "shinkansen"],
    source: "manual",
  },
  {
    slug: "mishima-station-hub-shinkansen",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "JR 三島駅(東海道新幹線+伊豆箱根駿豆線・伊豆中部 + 箱根西側 hub・1969)",
    title_ja: "JR 三島駅",
    romaji: "Mishima Station",
    summary_zh: "**JR 三島駅は伊豆半島中部 + 箱根西側の hub**(1969 新幹線駅増設)。新幹線+東海道本線+伊豆箱根鉄道駿豆線(三島~修善寺)が連結、伊豆温泉(修善寺・湯ヶ島・松崎)アクセスの起点。北口に三島スカイウォーク行きバス、南口は富士山三島東急ホテル直結。",
    content_md: "- 開業:在来線 1898・新幹線 1969\n- 路線:東海道新幹線(全列車停車除く「のぞみ」)+ 東海道本線 + 伊豆箱根鉄道駿豆線\n- 1 日乗降:約 4 万人\n- 連絡:駿豆線 → 修善寺(40 分)→ 湯ヶ島・天城・松崎(バス連絡)\n- バス:三島スカイウォーク・富士山五合目登山口・箱根西側\n- 駅商業:富士山三島東急ホテル(2018・南口直結)\n- 北口:伊豆方面バス連結\n- 南口:箱根西側バス連結\n- アクセス:東京 45 分(新幹線)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "三島市",
    lg_code: "22206",
    area_types: ["urban_central"],
    lat: 35.124,
    lon: 138.911,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["transit_hub", "mishima_station", "izu_central", "izuhakone_connect"],
    source: "manual",
  },
  {
    slug: "shizuoka-station-hub-shinkansen",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "JR 靜岡駅(東海道新幹線+靜岡鐵道靜岡清水線・縣庁所在地 hub)",
    title_ja: "JR 静岡駅",
    romaji: "Shizuoka Station",
    summary_zh: "**JR 静岡駅は静岡県庁所在地の最大 hub**。東海道新幹線(全列車停車除く「のぞみ」)+ 東海道本線 + 静岡鉄道静岡清水線が接続、1 日乗降客数 12 万人(在来線 + 静鉄合計)で県内 1 位。北口に「ASTY 静岡」「JR 静岡駅ビル パルシェ」+ 松坂屋 + パルコ + マルイ + 新静岡セノバの百貨店密集地区。",
    content_md: "- 路線:東海道新幹線(「のぞみ」一部除き全停車)+ 東海道本線 + 静岡鉄道静岡清水線\n- 1 日乗降:約 12 万人(JR 6 万 + 静鉄 6 万)\n- 駅ビル:ASTY 静岡(駅構内)・パルシェ(駅ビル)\n- 駅周辺商業:松坂屋静岡 + 静岡パルコ + マルイ + 新静岡セノバ + 呉服町通り\n- 静鉄連絡:JR 北口 → 新静岡駅(徒歩 8 分)\n- アクセス:東京 1h(新幹線)・名古屋 1h\n- 駿府城:北口徒歩 10 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["urban_central"],
    lat: 34.972,
    lon: 138.388,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["transit_hub", "shizuoka_station", "prefecture_capital"],
    source: "manual",
  },
  {
    slug: "hamamatsu-station-hub-shinkansen",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "JR 浜松駅(東海道新幹線+遠州鐵道+天竜浜名湖鐵道・遠江西部 hub)",
    title_ja: "JR 浜松駅",
    romaji: "Hamamatsu Station",
    summary_zh: "**JR 浜松駅は遠江西部の最大 hub**。東海道新幹線(全列車停車除く「のぞみ」一部)+ 東海道本線 + 遠州鉄道(新浜松駅で連結)+ 天竜浜名湖鉄道(掛川経由)。1 日乗降客 11 万人。駅ビル「メイワン」+ 隣接「アクトシティ浜松」(45F オークラホテル + コンサートホール)で複合発展。",
    content_md: "- 路線:東海道新幹線(「のぞみ」一部除き全停車)+ 東海道本線\n- 連絡:遠州鉄道(新浜松駅・徒歩 3 分)+ 天竜浜名湖鉄道(掛川 1h 経由)\n- 1 日乗降:約 11 万人\n- 駅ビル:メイワン(駅直結・ファッション + JR ホテル浜松)\n- 隣接複合施設:アクトシティ浜松(45F・オークラホテル + コンサートホール + 浜松市楽器博物館)\n- アクセス:東京 1h35 分(新幹線)・名古屋 30 分\n- 駅前バスターミナル:遠鉄バス(浜松市内全域)・舘山寺温泉行・空港リムジン",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["urban_central"],
    lat: 34.703,
    lon: 137.734,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["transit_hub", "hamamatsu_station", "totoumi_west"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase B — JR 在来線(3 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "jr-tokaido-line-shizuoka",
    category: "transport",
    sub_type: "limited_express_private",
    title_zh: "JR 東海道本線(静岡県内・熱海 ↔ 豊橋・約 200km)",
    title_ja: "JR 東海道本線(静岡県内)",
    romaji: "JR Tōkaidō Main Line",
    summary_zh: "**JR 東海道本線は静岡県を貫く JR 東海の大動脈**(熱海 ↔ 豊橋・約 200km)。在来線として新幹線駅と同区間を走り、各駅停車中心、特急「ふじかわ」(身延線連絡)も。新幹線で飛ばすより、各駅停車で由比・蒲原・三保・由良越え等の沿岸景観を楽しむ旅向け。",
    content_md: "- 区間:熱海 ↔ 豊橋(愛知県境)・静岡県内 約 200km\n- 開業:1889 年(明治22)\n- 列車:普通(各駅停車)+ 特急「ふじかわ」(静岡 ↔ 甲府・身延線直通)+ 「サンライズ瀬戸/出雲」(東京 ↔ 出雲・夜行)\n- 主要駅:熱海・三島・沼津・富士・清水・静岡・焼津・島田・掛川・磐田・浜松・豊橋\n- 観光価値:沿岸景観(由比・蒲原区間)・薩埵峠通過\n- 1 日乗降(沿線合計):約 25 万人\n- 運賃:JR 普通運賃(距離別)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["urban_central"],
    lat: 34.972,
    lon: 138.388,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://railway.jr-central.co.jp/" },
    tags: ["limited_express_private", "jr_tokaido", "main_line", "1889"],
    source: "manual",
  },
  {
    slug: "jr-ito-line-1938",
    category: "transport",
    sub_type: "limited_express_private",
    title_zh: "JR 伊東線(熱海 ↔ 伊東・1938 開業・伊豆東岸 access)",
    title_ja: "JR 伊東線",
    romaji: "JR Ito Line",
    summary_zh: "**JR 伊東線は熱海 ↔ 伊東(16 km)の伊豆東岸路線**(1938 全線開通)。伊東駅で伊豆急行(伊豆急下田行)に直通連絡、東京~下田を 1 本(踊り子号・サフィール踊り子)で結ぶ。沿線は相模湾沿いで、車窓から海と伊豆諸島が一望。",
    content_md: "- 区間:熱海 ↔ 伊東(16km・JR)\n- 開業:全線 1938 年(昭和13)\n- 直通:伊豆急行(伊東 ↔ 伊豆急下田)・東京 ↔ 下田 「踊り子」「サフィール踊り子」\n- 「踊り子」:185 系 2021 年まで・現在 E257 系\n- 「サフィール踊り子」:E261 系プレミアム特急(2020 デビュー)\n- 主要駅:熱海・来宮・伊豆多賀・網代・宇佐美・伊東\n- 沿線:相模湾沿岸絶景\n- 1 日乗降:約 1.5 万人(伊東駅含む)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["urban_central"],
    lat: 34.965,
    lon: 139.099,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://railway.jr-central.co.jp/" },
    tags: ["limited_express_private", "jr_ito_line", "1938", "izu_east"],
    source: "manual",
  },
  {
    slug: "jr-gotemba-line-1889",
    category: "transport",
    sub_type: "limited_express_private",
    title_zh: "JR 御殿場線(国府津 ↔ 沼津・1889・富士山眺望ローカル線)",
    title_ja: "JR 御殿場線",
    romaji: "JR Gotemba Line",
    summary_zh: "**JR 御殿場線は国府津(神奈川)~沼津の単線ローカル**(60 km・1889 開業)。元東海道本線の旧ルート(丹那トンネル開通 1934 まで)、現在は富士山麓の御殿場・裾野経由の絶景路線。富士山西側を走り、晴天時は車窓 全長で富士山が伴走、撮影鉄道家の聖地。",
    content_md: "- 区間:国府津(神奈川)~沼津(60 km)\n- 開業:1889 年(明治22)・元東海道本線\n- 主要駅:国府津・松田・山北・御殿場・裾野・沼津\n- 単線・ディーゼル車中心(電化部分あり)\n- 列車:特急「ふじさん」(新宿 ↔ 御殿場・小田急乗入れ)+ 普通\n- 富士山眺望:晴天時 全区間で富士山が車窓に\n- 御殿場:プレミアム・アウトレットアクセス hub\n- 1 日乗降(沿線合計):約 5 万人",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "御殿場市",
    lg_code: "22215",
    area_types: ["urban_central", "rural_townscape"],
    lat: 35.302,
    lon: 138.934,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://railway.jr-central.co.jp/" },
    tags: ["limited_express_private", "jr_gotemba_line", "1889", "fuji_view"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase C — 7 私鉄(7 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shizuoka-tetsudo-line-1908",
    category: "transport",
    sub_type: "shizuoka_local_railway",
    title_zh: "靜岡鐵道靜岡清水線(新靜岡 ↔ 新清水・1908 開業・縣央通勤線)",
    title_ja: "静岡鉄道 静岡清水線",
    romaji: "Shizuoka Tetsudo",
    summary_zh: "**静岡鉄道(略称・静鉄)は静岡市の通勤通学線**。新静岡 ↔ 新清水 11 km・1908 開業の老舗私鉄、新静岡駅(新静岡セノバ直結)~新清水駅を 21 分で結ぶ。日中 6 分間隔の高頻度運転、JR 静岡駅と新静岡駅は徒歩 8 分連絡。「しずてつ」グループの基幹路線。",
    content_md: "- 区間:新静岡 ↔ 新清水(11 km・15 駅)\n- 開業:1908 年(明治41)\n- 所要:21 分\n- 運賃:全線 ¥320\n- 運行:日中 6 分間隔(朝夕 4 分)\n- 主要駅:新静岡(新静岡セノバ直結)・春日町・古庄・桜橋・新清水(エスパルスドリームプラザ近)\n- 1 日乗降(全駅合計):約 6 万人\n- 系列:静岡鉄道 = しずてつグループ(バス + 不動産 + 観光)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["urban_central"],
    lat: 34.975,
    lon: 138.388,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shizuoka_local_railway", "shizuoka_tetsudo", "1908", "shizutetsu"],
    source: "manual",
  },
  {
    slug: "enstetsu-line-1923",
    category: "transport",
    sub_type: "shizuoka_local_railway",
    title_zh: "遠州鉄道(西鹿島線・新浜松 ↔ 西鹿島・1923 開業・浜松通勤通学線)",
    title_ja: "遠州鉄道 西鹿島線",
    romaji: "Enstetsu (Enshu Tetsudo)",
    summary_zh: "**遠州鉄道(略称・遠鉄)は浜松市の通勤通学線**。新浜松 ↔ 西鹿島 17 km・1923 開業の私鉄、新浜松駅(JR 浜松駅徒歩 3 分)~西鹿島駅(天竜区・天竜浜名湖鉄道接続)を 33 分で。「赤電」(赤色電車)の愛称で親しまれる、日中 12 分間隔。",
    content_md: "- 区間:新浜松 ↔ 西鹿島(17 km・15 駅)\n- 開業:1923 年(大正12)\n- 所要:33 分\n- 運賃:全線 ¥530\n- 運行:日中 12 分間隔\n- 愛称:「赤電」(赤色車体)\n- 主要駅:新浜松(JR 浜松駅徒歩 3 分)・遠州病院・八幡・第一通り・西鹿島(天竜浜名湖鉄道乗換)\n- 1 日乗降(全駅合計):約 4 万人\n- 系列:遠鉄グループ(遠鉄バス + 遠鉄百貨店 + 遠鉄ホテル)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["urban_central"],
    lat: 34.703,
    lon: 137.734,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.entetsu.co.jp/" },
    tags: ["shizuoka_local_railway", "enstetsu", "1923", "akaden"],
    source: "manual",
  },
  {
    slug: "oigawa-tetsudo-overview-1925",
    category: "transport",
    sub_type: "shizuoka_local_railway",
    title_zh: "大井川鐵道(金谷 ↔ 千頭 + 千頭 ↔ 井川・1925 開業・SL 観光列車)",
    title_ja: "大井川鐵道",
    romaji: "Oigawa Tetsudo",
    summary_zh: "**大井川鐵道は SL 観光列車で全国級の私鉄**(1925 開業)。本線(金谷 ↔ 千頭・40 km)+ 井川線(千頭 ↔ 井川・25 km・アプト式)の 2 路線。本線は SL「かわね路」が現役運行、井川線は日本唯一のアプト式(歯車式)で南アルプス山中へ。鉄道+秘境の二面性で観光価値高。",
    content_md: "- 路線:本線(金谷 ↔ 千頭・40 km)+ 井川線(千頭 ↔ 井川・25 km)\n- 開業:本線 1925・井川線 1959\n- 本線 SL:C11形・C56形・C108形(現役 SL の中で国内最大級)\n- 井川線:日本唯一の現役アプト式鉄道(機関車にラックアンドピニオン)\n- 沿線:大井川渓谷・茶畑・寸又峡・接岨峡・南アルプス麓\n- 主要駅:金谷(JR 接続)・新金谷(SL 始発)・千頭(乗換)・接岨峡温泉・井川\n- 運賃:本線 SL 急行 ¥4500・井川線 ¥1340\n- 体験:SL 1 日 1-2 往復・井川線 1 日 4 往復\n- 注意:2022 台風で井川線一部区間長期運休中",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "島田市",
    lg_code: "22209",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 34.823,
    lon: 138.139,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://oigawa-railway.co.jp/" },
    tags: ["shizuoka_local_railway", "oigawa", "1925", "sl", "abt_system"],
    source: "manual",
  },
  {
    slug: "tenryu-hamanako-line-1935",
    category: "transport",
    sub_type: "shizuoka_local_railway",
    title_zh: "天竜浜名湖鉄道(掛川 ↔ 新所原・67 km・1935 開業・国登録駅 17)",
    title_ja: "天竜浜名湖鉄道",
    romaji: "Tenryu Hamanako Tetsudo",
    summary_zh: "**天竜浜名湖鉄道は浜名湖を北側周遊する第三セクター**(67 km・39 駅)。1935 国鉄二俣線として開業、1987 第三セクター化。駅舎の半数(36 駅中 17 駅)が国登録有形文化財という鉄道遺産、観光列車「ナディア号」で浜名湖+ 天竜川の景観を楽しめる。",
    content_md: "- 区間:掛川 ↔ 新所原(67 km・39 駅)\n- 開業:1935 年(昭和10)国鉄二俣線として\n- 第三セクター化:1987(JR 民営化時)\n- 国登録有形文化財:36 駅中 17 駅(駅舎・プラットホーム・上家)\n- 観光列車:TH9200 形「ナディア号」(浜名湖周遊)・TH3000 形(通常車両)\n- 主要駅:掛川 + 天竜二俣 + 西気賀(浜名湖畔・登録駅) + 新所原(JR 接続)\n- 沿線:浜名湖北岸 + 天竜川 + 天浜線温泉(西気賀・三ヶ日)\n- 1 日乗車券:¥1750(全線フリー)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["rural_townscape", "industrial_heritage"],
    lat: 34.722,
    lon: 137.620,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.tenhama.co.jp/" },
    tags: ["shizuoka_local_railway", "tenhama", "1935", "registered_heritage"],
    source: "manual",
  },
  {
    slug: "izukyu-line-1961",
    category: "transport",
    sub_type: "shizuoka_local_railway",
    title_zh: "伊豆急行線(伊東 ↔ 伊豆急下田・45 km・1961 開業・伊豆東岸大動脈)",
    title_ja: "伊豆急行線",
    romaji: "Izukyu Line",
    summary_zh: "**伊豆急行線は伊豆東岸の大動脈**(45 km・1961 開業)。JR 伊東線(熱海)と直通運転、東京 ↔ 伊豆急下田を 1 本で結ぶ最重要路線。観光特急「踊り子」「サフィール踊り子」+ 観光車両「リゾート 21」で、伊豆観光客の主交通手段。沿線は相模湾沿岸+伊豆諸島眺望。",
    content_md: "- 区間:伊東 ↔ 伊豆急下田(45 km・15 駅)\n- 開業:1961 年(昭和36)\n- 直通:JR 伊東線・伊豆急で東京 ↔ 下田 直通\n- 観光特急:踊り子(E257 系)・サフィール踊り子(E261 系プレミアム)\n- 観光車両:リゾート 21(海眺座席+黒船仕様)\n- 主要駅:伊東(JR 接続)・伊豆高原・河津・伊豆急下田\n- 沿線:相模湾絶景・伊豆諸島眺望\n- フリー:伊豆急 2 日フリー乗車券 ¥1900\n- 1 日乗降:約 4 万人",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["urban_central", "luxury_resort"],
    lat: 34.965,
    lon: 139.099,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.izukyu.co.jp/" },
    tags: ["shizuoka_local_railway", "izukyu", "1961", "izu_east_main"],
    source: "manual",
  },
  {
    slug: "izuhakone-sunzu-line-1898",
    category: "transport",
    sub_type: "shizuoka_local_railway",
    title_zh: "伊豆箱根鉄道駿豆線(三島 ↔ 修善寺・1898 開業・伊豆中部 access)",
    title_ja: "伊豆箱根鉄道 駿豆線",
    romaji: "Izuhakone Sunzu Line",
    summary_zh: "**伊豆箱根鉄道駿豆線は伊豆中部 access**(三島 ↔ 修善寺・19 km・1898 開業)。JR 三島駅で新幹線連絡、修善寺~湯ヶ島・天城~下田方面のバス連結 hub として機能。沿線は田園+山間で、特急「踊り子」も一部経由。",
    content_md: "- 区間:三島 ↔ 修善寺(19 km・13 駅)\n- 開業:1898 年(明治31)・伊豆地方最古の私鉄\n- 連絡:JR 三島駅で新幹線\n- 主要駅:三島 + 三島広小路(うなぎ桜家近) + 大仁 + 伊豆長岡 + 修善寺\n- 修善寺発バス:湯ヶ島・天城・松崎方面\n- 観光列車:特急「踊り子」(東京 ↔ 修善寺)も乗入れ\n- フリー:伊豆箱根 1 日フリー切符 ¥1080\n- 1 日乗降:約 3 万人",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "三島市",
    lg_code: "22206",
    area_types: ["urban_central", "rural_townscape"],
    lat: 35.124,
    lon: 138.911,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.izuhakone.co.jp/" },
    tags: ["shizuoka_local_railway", "izuhakone", "sunzu_line", "1898"],
    source: "manual",
  },
  {
    slug: "gakunan-densha-1949",
    category: "transport",
    sub_type: "shizuoka_local_railway",
    title_zh: "岳南電車(吉原 ↔ 岳南江尾・9.2 km・1949 開業・富士山眺望ミニ私鉄)",
    title_ja: "岳南電車",
    romaji: "Gakunan Densha",
    summary_zh: "**岳南電車は富士市の超ミニ私鉄**(9.2 km・10 駅・1949 開業)。富士山眺望路線として「日本夜景遺産」(2011)+ 「全国初の鉄道夜景遺産」、2 つ目の駅「ジヤトコ前」から終点までほぼ全駅で富士山が見える。日中 30 分間隔・運賃 ¥360・1 日 700 人の超ローカル。",
    content_md: "- 区間:吉原 ↔ 岳南江尾(9.2 km・10 駅)\n- 開業:1949 年(昭和24)\n- 所要:21 分\n- 運賃:全線 ¥370\n- 運行:日中 30 分間隔\n- 認定:日本夜景遺産(2011)・鉄道夜景遺産(2011・全国初)\n- 富士山眺望:全 10 駅中 8 駅で富士山が見える\n- 特別:JR 吉原駅のみ JR 連絡(他は単独私鉄駅)\n- 1 日乗降:約 700 人(超ローカル)\n- 沿線:富士市工業地帯 + 富士山\n- 1 日フリー乗車券 ¥720",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "富士市",
    lg_code: "22210",
    area_types: ["industrial_heritage", "urban_central"],
    lat: 35.157,
    lon: 138.694,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.gakutetsu.jp/" },
    tags: ["shizuoka_local_railway", "gakunan", "1949", "fuji_view_railway"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase D — 空港(1 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shizuoka-airport-2009",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "靜岡空港(2009 開港・牧之原市・FDA 中心・国内 + 中韓便)",
    title_ja: "富士山静岡空港",
    romaji: "Mt. Fuji Shizuoka Airport",
    summary_zh: "**富士山静岡空港は 2009 年開港の地方空港**(牧之原市・JR 静岡駅から車 50 分)。フジドリームエアラインズ(FDA・本社・主力)中心、国内便(新千歳・福岡・那覇・出雲・松山)+ 中韓便(上海・西安・台北・ソウル・香港)。茶畑の中の空港として観光的にもユニーク。",
    content_md: "- 開港:2009 年(平成21)6 月\n- 立地:牧之原市・島田市の境界(JR 静岡駅 から車 50 分・空港リムジンバス 60 分)\n- 主力:FDA(フジドリームエアラインズ・本社)\n- 国内便:新千歳・福岡・那覇・出雲・松山(FDA + ANA)\n- 国際便:上海・西安・台北・ソウル・香港(中華系航空主体)\n- 年間利用者:約 70 万人(2019 ピーク)\n- 駐車場:無料 約 2000 台\n- 注意:茶畑の中の空港・自動車アクセスが基本(駅未直結)\n- リムジンバス:静岡駅・浜松駅・三島駅・富士駅 から運行",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "牧之原市",
    lg_code: "22226",
    area_types: ["urban_central", "rural_townscape"],
    lat: 34.797,
    lon: 138.187,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.mtfuji-shizuokaairport.jp/" },
    tags: ["airport_access", "shizuoka_airport", "2009", "fda_main"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase E — フェリー・連絡船(2 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "suruga-bay-ferry",
    category: "transport",
    sub_type: "ferry_island",
    title_zh: "駿河湾フェリー(清水 ↔ 土肥・伊豆連絡・1958 開業)",
    title_ja: "駿河湾フェリー",
    romaji: "Suruga Bay Ferry",
    summary_zh: "**駿河湾フェリーは清水 ↔ 西伊豆土肥の連絡船**(65 分・1958 開業)。陸路 静岡市~西伊豆 3-4 時間に対して、海路 1 時間で到達できる伊豆 access 短縮ルート。富士山絶景を駿河湾上で楽しめる観光価値も高く、自家用車積載可。",
    content_md: "- 区間:清水港 ↔ 土肥港(伊豆市)・約 30 km\n- 所要:65 分\n- 開業:1958 年(昭和33)\n- 運航:1 日 4 往復(夏季 5)\n- 料金:大人 ¥2400(自動車別途 ¥6800-)\n- 自家用車積載:可(片道 ¥6800-9600 サイズ別)\n- 富士山眺望:航路全長で(晴天時)\n- 比較:陸路 静岡 ~ 西伊豆 3-4 時間 vs フェリー 1 時間\n- 注意:荒天時欠航・冬季は便数減\n- 公式:伊豆フェリー株式会社",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["fishing_port", "urban_central"],
    lat: 35.013,
    lon: 138.498,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.223-ferry.or.jp/" },
    tags: ["ferry_island", "suruga_bay", "1958", "izu_shortcut"],
    source: "manual",
  },
  {
    slug: "hatsushima-ferry-atami",
    category: "transport",
    sub_type: "ferry_island",
    title_zh: "熱海 ↔ 初島連絡船(高速船・30 分・本州最近の有人離島へ)",
    title_ja: "熱海 ↔ 初島 高速船",
    romaji: "Atami-Hatsushima Ferry",
    summary_zh: "**熱海 ↔ 初島の高速船は本州最近の有人離島連絡**。30 分・1 日 8 往復、初島(住人 200 人)へのアクセス。PICA 初島リゾート + 海水浴 + 釣り + アジアンガーデンの離島リゾート気分が日帰りで味わえる。",
    content_md: "- 区間:熱海港 ↔ 初島港・約 10 km\n- 所要:30 分\n- 運航:1 日 8 往復(夏季 10)\n- 料金:大人往復 ¥2800・小人 ¥1400\n- 運航会社:富士急マリンリゾート(初島ハーバー)\n- 特徴:本州最近の有人離島(住人 200 人)\n- 初島の魅力:PICA 初島(リゾート)・海水浴・釣り・アジアンガーデン R-Asia\n- 注意:荒天時欠航・冬季は便数減",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "熱海市",
    lg_code: "22205",
    area_types: ["fishing_port", "luxury_resort"],
    lat: 35.097,
    lon: 139.082,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.hatsushima.jp/" },
    tags: ["ferry_island", "atami", "hatsushima", "high_speed_boat"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase F — バス(3 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shizutetsu-just-line",
    category: "transport",
    sub_type: "route_map_urban",
    title_zh: "しずてつジャストライン(靜岡市・清水バス・全 200+ 系統・最大バス)",
    title_ja: "しずてつジャストライン",
    romaji: "Shizutetsu Just Line",
    summary_zh: "**しずてつジャストラインは静岡市内+清水の最大バス事業者**。静鉄グループのバス部門、全 200+ 系統で県中部のバス路線をほぼ独占。日本平+三保の松原+久能山等の主要観光地アクセスもこの路線。1 日乗車券(¥600)で市内自由乗降可能。",
    content_md: "- 系列:静鉄グループ\n- 規模:全 200+ 系統・車両 600+\n- カバー:静岡市葵区・駿河区・清水区+郊外\n- 主要路線:日本平・三保松原・久能山・登呂遺跡・東静岡駅・清水港\n- 1 日乗車券:¥600(市内バス全路線・主要観光地アクセス)\n- アプリ:しずてつ Bus Locator(リアルタイム運行情報)\n- 主な hub:JR 静岡駅・新静岡バスターミナル・清水駅",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["urban_central"],
    lat: 34.972,
    lon: 138.388,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.justline.co.jp/" },
    tags: ["route_map_urban", "shizutetsu", "just_line", "shizuoka_city"],
    source: "manual",
  },
  {
    slug: "enstetsu-bus-hamamatsu",
    category: "transport",
    sub_type: "route_map_urban",
    title_zh: "遠鉄バス(浜松バス・全 100+ 系統・浜松市最大バス)",
    title_ja: "遠鉄バス",
    romaji: "Entetsu Bus",
    summary_zh: "**遠鉄バスは浜松市の最大バス事業者**(遠州鉄道グループ)。全 100+ 系統で浜松市内+周辺をカバー、舘山寺温泉・浜松フラワーパーク・浜松城・浜名湖等の観光地アクセスも。新浜松駅と JR 浜松駅前にバスターミナル、ワンデーパス ¥800。",
    content_md: "- 系列:遠州鉄道(遠鉄)グループ\n- 規模:全 100+ 系統\n- カバー:浜松市中央区・西区・北区・東区・南区・天竜区+郊外\n- 主要路線:舘山寺温泉・浜松城公園・浜松フラワーパーク・浜松市楽器博物館・浜松動物園\n- ワンデーパス:¥800(浜松バス全路線)\n- 主な hub:新浜松駅前ロータリー(遠鉄百貨店地下)・JR 浜松駅前\n- 空港リムジン:浜松駅~静岡空港 約 70 分(¥1500)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["urban_central"],
    lat: 34.704,
    lon: 137.731,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://bus.entetsu.co.jp/" },
    tags: ["route_map_urban", "entetsu_bus", "hamamatsu"],
    source: "manual",
  },
  {
    slug: "tokai-bus-izu-overview",
    category: "transport",
    sub_type: "shizuoka_izu_access",
    title_zh: "東海バス(伊豆全域バス・伊豆観光交通の動脈・伊豆フリーパス)",
    title_ja: "東海バス",
    romaji: "Tokai Bus",
    summary_zh: "**東海バスは伊豆半島全域のバス事業者**。伊東~下田~松崎~修善寺~天城越えの路線網で伊豆観光の交通動脈、特に天城越えバス(下田 ↔ 修善寺・1 日 5 往復)は文学聖地アクセスとして文学ファン愛用。伊豆フリーパス(2 日 ¥3700)で全区間自由乗降。",
    content_md: "- 系列:小田急電鉄系\n- カバー:伊豆半島ほぼ全域(伊東・下田・松崎・西伊豆・修善寺・天城・河津)\n- 主要路線:\n  - 天城越え路線(下田 ↔ 修善寺・3h・伊豆の踊子の道)\n  - 西海岸路線(松崎 ↔ 修善寺・1.5h)\n  - 河津七滝アクセス(下田 ↔ 七滝)\n  - 弓ヶ浜南伊豆路線(下田 ↔ 弓ヶ浜)\n- フリーパス:伊豆フリーパス Q (¥3900・2 日)・伊豆フリーパス全エリア(¥4500・2 日)\n- 主な hub:伊東バスターミナル・下田バスターミナル・修善寺駅前",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["urban_central", "rural_townscape"],
    lat: 34.965,
    lon: 139.099,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.tokaibus.jp/" },
    tags: ["shizuoka_izu_access", "tokai_bus", "izu_full"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase G — 高速バス(2 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shizuoka-tokyo-highway-bus",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "靜岡 ↔ 東京 高速バス(JR バス関東「ドリーム号」+ しずてつ 等・3-3.5h)",
    title_ja: "静岡 ↔ 東京 高速バス",
    romaji: "Shizuoka-Tokyo Highway Bus",
    summary_zh: "**静岡 ↔ 東京の高速バス**は JR バス関東「ドリーム号」+ しずてつジャストライン + 富士急行 の 3 社運行。静岡駅・新富士駅・三島駅から東京駅・新宿駅へ、3-3.5 時間・¥3000-5500。新幹線 ¥6470 の半額でアクセス可能、夜行便もあり。",
    content_md: "- 主要運行:JR バス関東「ドリーム号」+ しずてつジャストライン + 富士急行\n- 区間:静岡駅・新富士駅・三島駅 ↔ 東京駅 + 新宿駅 + 横浜駅\n- 所要:3-3.5 時間\n- 運賃:¥3000-5500(時期・グレードで変動)\n- 比較:新幹線 ¥6470 の半額\n- 夜行便:JR バス + 富士急 が東京 → 静岡 1 往復(¥4000-)\n- 予約:発車オーライネット・楽天バス\n- 発着:静岡駅北口バスターミナル・新宿バスタ",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["urban_central"],
    lat: 34.972,
    lon: 138.388,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["area_access_guide", "highway_bus", "shizuoka_tokyo"],
    source: "manual",
  },
  {
    slug: "hamamatsu-tokyo-highway-bus",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "浜松 ↔ 東京 高速バス(JR バス + 遠鉄バス・夜行 + 昼行・4-4.5h)",
    title_ja: "浜松 ↔ 東京 高速バス",
    romaji: "Hamamatsu-Tokyo Highway Bus",
    summary_zh: "**浜松 ↔ 東京の高速バス**は JR バス関東 + 遠鉄バス + WILLER 運行。浜松駅 ↔ 東京駅・新宿駅・横浜駅、4-4.5 時間・¥3500-7000(夜行 3 列シート ¥6500-)。新幹線 ¥7900 の半額で、夜行は 1 泊代わりにも。",
    content_md: "- 主要運行:JR バス関東 + 遠鉄バス + WILLER\n- 区間:浜松駅 ↔ 東京駅 + 新宿駅 + 横浜駅\n- 所要:4-4.5 時間\n- 運賃:¥3500-7000(夜行 3 列シート ¥6500-)\n- 比較:新幹線 ¥7900 の半額\n- 夜行便:JR + WILLER 中心(夜 11 時発・朝 5-6 時着)\n- 予約:発車オーライネット・WILLER 公式\n- 発着:浜松駅北口バスターミナル・新宿バスタ",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["urban_central"],
    lat: 34.704,
    lon: 137.731,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["area_access_guide", "highway_bus", "hamamatsu_tokyo"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase H — フリーパス(2 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "izukyu-2day-free-pass",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "伊豆急 2 日フリー乗車券(伊東 ↔ 伊豆急下田 自由乗降・¥1900)",
    title_ja: "伊豆急 2 日フリー乗車券",
    romaji: "Izukyu Free Pass",
    summary_zh: "**伊豆急 2 日フリー乗車券は伊豆東岸観光の必携パス**(¥1900・連続 2 日)。伊東 ↔ 伊豆急下田の全区間+ 全駅で自由乗降可能、伊豆高原・河津桜・下田を 1 旅程で巡るなら必須。河津桜時期(2-3 月)+ 夏休み海水浴シーズンに特に活躍。",
    content_md: "- 範囲:JR 伊東駅 ↔ 伊豆急下田駅(全 16 駅・自由乗降)\n- 期間:連続 2 日\n- 料金:大人 ¥1900・小人 ¥950\n- 比較:単純往復 ¥3920(2 倍以上)で元取れる\n- 含む観光地:伊豆高原(伊豆シャボテン公園・伊豆ぐらんぱる公園)・河津桜・下田開国遺産\n- 別売:JR 伊東線(熱海 ↔ 伊東)は別料金\n- 購入:JR 伊東駅・主要伊豆急駅・コンビニ電子チケット\n- ピーク時期:2-3 月(河津桜)・7-8 月(海水浴)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["urban_central"],
    lat: 34.965,
    lon: 139.099,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.izukyu.co.jp/freepass/" },
    tags: ["ticket_promo", "izukyu_free_pass", "izu_east"],
    source: "manual",
  },
  {
    slug: "tokai-bus-izu-2day-pass",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "東海バス伊豆フリーパス(伊豆全域・天城越え+西海岸+南伊豆・¥3900)",
    title_ja: "東海バス伊豆フリーパス",
    romaji: "Tokai Bus Izu Free Pass",
    summary_zh: "**東海バス伊豆フリーパスは伊豆半島全域のバス自由乗降券**(2 日 ¥3900・全エリア ¥4500)。天城越えバス(下田 ↔ 修善寺・3h)+ 西海岸(松崎・堂ヶ島)+ 南伊豆(弓ヶ浜)+ 東海岸支線を全カバー、伊豆を車を持たず周遊するなら必須パス。",
    content_md: "- 範囲:東海バス全路線(伊東・下田・松崎・修善寺・天城・河津 等の伊豆半島ほぼ全域)\n- 期間:連続 2 日\n- 料金:Q コース ¥3900・全エリア ¥4500・小人半額\n- カバー:天城越えバス + 西海岸バス + 南伊豆バス + 東海岸支線\n- 比較:単純利用 1 路線 ¥1500-2500 → 2 路線で元取れる\n- 文学的価値:天城越えバスは『伊豆の踊子』の道\n- 購入:伊豆急下田駅 + 修善寺駅 + 伊東駅 + 主要バスターミナル\n- 公式:東海バス公式サイト",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "下田市",
    lg_code: "22219",
    area_types: ["urban_central", "rural_townscape"],
    lat: 34.679,
    lon: 138.945,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ticket_promo", "tokai_bus_izu", "free_pass", "izu_full"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // Phase I — 観光船・空港アクセス・駅 hub(3 筆)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shimoda-cruise-susquehanna",
    category: "transport",
    sub_type: "shizuoka_izu_access",
    title_zh: "下田クルーズ「サスケハナ号」(黒船型遊覧船・1854 ペリー艦隊再現)",
    title_ja: "下田クルーズ サスケハナ号",
    romaji: "Shimoda Cruise Susquehanna",
    summary_zh: "**サスケハナ号は黒船型の遊覧船**(下田港・所要 20 分)。1854 ペリー提督の旗艦「Susquehanna」を模した観光船で、下田湾内をペリー来航時の海ルートで航行。船上でペリー来航の歴史解説アナウンスあり、観光と歴史学習を兼ねた体験。",
    content_md: "- 船名:サスケハナ号(1854 ペリー艦隊旗艦から命名)\n- 立地:下田港(下田クルーズ乗船場)\n- 所要:20 分(下田湾内一周)\n- 料金:大人 ¥1500・子供 ¥750\n- 運航:9:30-15:30(1 時間に 1 便)\n- 解説:ペリー来航時のエピソード+ 黒船祭の歴史\n- 周辺:了仙寺(日米下田条約締結地)・下田開国博物館・ペリーロード\n- アクセス:伊豆急 下田駅 から徒歩 12 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "下田市",
    lg_code: "22219",
    area_types: ["fishing_port", "urban_central"],
    lat: 34.677,
    lon: 138.943,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shizuoka_izu_access", "shimoda_cruise", "susquehanna", "kurofune"],
    source: "manual",
  },
  {
    slug: "shizuoka-airport-shuttle-bus",
    category: "transport",
    sub_type: "airport_access",
    title_zh: "靜岡空港リムジンバス(空港 ↔ 靜岡駅/浜松駅/三島駅/富士駅)",
    title_ja: "静岡空港リムジンバス",
    romaji: "Shizuoka Airport Shuttle",
    summary_zh: "**静岡空港リムジンバスは空港アクセスの主要交通**。静岡駅(60 分・¥1100)・浜松駅(70 分・¥1500)・三島駅(110 分・¥2400)・富士駅(70 分・¥1300)・島田駅(40 分・¥800)を結ぶ 5 路線、いずれも空港駐車場無料併用で車不要。",
    content_md: "- 運行:しずてつジャストライン + 遠鉄バス\n- 路線:\n  - 静岡駅 ↔ 空港 60 分 ¥1100(1 日 12 往復)\n  - 浜松駅 ↔ 空港 70 分 ¥1500(1 日 8 往復)\n  - 三島駅 ↔ 空港 110 分 ¥2400(1 日 4 往復)\n  - 富士駅 ↔ 空港 70 分 ¥1300(1 日 6 往復)\n  - 島田駅 ↔ 空港 40 分 ¥800(1 日 14 往復)\n- 空港駐車場:無料 約 2000 台(代替手段)\n- 公式予約:不要(現地購入)・運行情報は しずてつ・遠鉄サイト",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "牧之原市",
    lg_code: "22226",
    area_types: ["urban_central"],
    lat: 34.797,
    lon: 138.187,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["airport_access", "shizuoka_airport", "limousine_bus"],
    source: "manual",
  },
  {
    slug: "numazu-station-hub",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "JR 沼津駅(東海道本線+御殿場線・伊豆西側 + 富士山麓 hub)",
    title_ja: "JR 沼津駅",
    romaji: "Numazu Station",
    summary_zh: "**JR 沼津駅は伊豆西側 + 富士山南麓の hub**。東海道本線+御殿場線が交わる主要駅、沼津港+大瀬崎+西伊豆+三島スカイウォーク+富士急沼津方面のバス連結。新幹線駅は隣の三島駅(在来線 5 分)で、沼津は在来線中心の地元利用駅。",
    content_md: "- 路線:東海道本線 + 御殿場線\n- 1 日乗降:約 3 万人\n- バス連絡:\n  - 沼津港(15 分)\n  - 大瀬崎(60 分・西伊豆観光)\n  - 三島スカイウォーク(25 分)\n  - 御殿場プレミアム・アウトレット(60 分)\n- 駅周辺:沼津港深海水族館 + 沼津魚河岸丸天 + 千本松原\n- 新幹線:三島駅(隣・在来線 5 分)が最寄\n- アクセス:JR 東海道本線 三島駅から 5 分・東京駅から 1.5 時間",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "沼津市",
    lg_code: "22203",
    area_types: ["urban_central"],
    lat: 35.099,
    lon: 138.866,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["transit_hub", "numazu_station", "izu_west", "fuji_south"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R2 補完(2026-04-29)— 井川線アプト式 + 久能山ロープウェイ +2
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "oigawa-ikawa-line-abt",
    category: "transport",
    sub_type: "shizuoka_local_railway",
    title_zh: "大井川鐵道井川線(日本唯一現役アプト式・1959 開業・南アルプス秘境)",
    title_ja: "大井川鐵道井川線",
    romaji: "Oigawa Ikawa Line",
    summary_zh: "**大井川鐵道井川線は日本唯一の現役アプト式鉄道**(千頭~井川・25 km)。本線(SL かわね路)で千頭駅まで来た観光客が乗継ぎ、南アルプス麓の秘境(寸又峡・接岨峡・井川)へ。アプト式は急勾配区間を機関車のラックギアと線路のラックレールで登る特殊機構、ヨーロッパの山岳鉄道由来。一部区間 2022 台風以来運休中(部分運転)。",
    content_md: "- 区間:千頭 ↔ 井川(25 km・14 駅)\n- 開業:1959 年(昭和34)\n- アプト式区間:アプトいちしろ ~ 長島ダムの 1.5 km(90‰ の急勾配)\n- アプト式:機関車のラックギアが線路のラックレールに噛む山岳鉄道機構(日本で他に箱根登山鉄道+大井川井川線のみ・後者のみ現役アプト)\n- 機関車:ED90 形(電気機関車・ラックギア装備)\n- 沿線:大井川渓谷・接岨峡温泉・寸又峡(隣接バス連絡)・南アルプス麓\n- 運賃:全線 ¥1340\n- 注意:2022 台風で接岨峡温泉~井川間 長期運休中(2025 部分復旧予定)\n- アクセス:大井川鐵道本線で金谷 → 千頭(2 時間)→ 井川線乗換",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: "榛原郡",
    municipality_ja: "川根本町",
    lg_code: "22429",
    area_types: ["mountain_village", "industrial_heritage"],
    lat: 35.119,
    lon: 138.176,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://oigawa-railway.co.jp/ikawa" },
    tags: ["shizuoka_local_railway", "oigawa", "ikawa_line", "1959", "abt_system_only"],
    source: "manual",
  },
  {
    slug: "kuno-zan-ropeway-1957",
    category: "transport",
    sub_type: "limited_express_private",
    title_zh: "久能山東照宮ロープウェイ(日本平 ↔ 久能山頂・1957 開業・所要 5 分)",
    title_ja: "日本平 ↔ 久能山ロープウェイ",
    romaji: "Kunozan Ropeway",
    summary_zh: "**久能山東照宮ロープウェイは日本平山頂と久能山東照宮を結ぶ索道**(1957 開業・所要 5 分)。徒歩で久能山参拝するなら 1159 段の石段を登る必要があるところ、ロープウェイなら 5 分で山頂へ。途中の駿河湾絶景、富士山眺望も楽しめる。1 日 利用客 3000+(国宝東照宮効果)。",
    content_md: "- 開業:1957 年(昭和32)\n- 区間:日本平 ↔ 久能山(直線距離 1.1 km)\n- 所要:5 分\n- 高低差:約 100 m\n- 運営:静岡鉄道(静鉄)\n- 運賃:大人往復 ¥1500・小人 ¥750\n- 運行:1 日 18 往復(約 30 分間隔)・年間無休(整備休運休 1 日)\n- 比較:徒歩参拝(久能海岸からの 1159 段石段)も可能だが ロープウェイ 圧倒的時短\n- 絶景:駿河湾 + 富士山(晴天時)\n- アクセス:JR 静岡駅 から しずてつバス 40 分・日本平山頂下車(ロープウェイ駅併設)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["luxury_resort", "rural_townscape"],
    lat: 34.974,
    lon: 138.476,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["limited_express_private", "kunozan_ropeway", "1957", "shizutetsu"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R3 補完(2026-04-29)— サフィール踊り子 + しずてつ 1day pass +2
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "saphire-odoriko-e261-2020",
    category: "transport",
    sub_type: "limited_express_private",
    title_zh: "「サフィール踊り子」(E261 系 プレミアム特急・東京 ↔ 伊豆急下田・2020 デビュー)",
    title_ja: "サフィール踊り子",
    romaji: "Saphir Odoriko",
    summary_zh: "**「サフィール踊り子」は JR 東日本のプレミアム特急**(2020 デビュー)。東京 ↔ 伊豆急下田を 2 時間 30 分で結ぶ全車グリーン車・8 両編成、最高ランクの「プレミアムグリーン」(¥10000+ 追加)+ ヌードルバー(車内麺料理)+ 海眺座席で、新幹線級の高速性 + 観光列車の体験。料金は通常の特急「踊り子」の 1.5-2 倍。",
    content_md: "- 開業:2020 年(令和2)3 月 14 日\n- 区間:東京 ↔ 伊豆急下田(JR 東海道線 + 伊豆急線・所要 2h30 分)\n- 編成:8 両 全車グリーン車(プレミアムグリーン 6 両 + プレミアムグリーン個室 2 両)\n- 設備:海側全席窓向き・ヌードルバー(車内麺レストラン・¥1300-)\n- 料金:プレミアムグリーン 東京 → 下田 ¥9990(乗車券 + 特急料金 + プレミアム)\n- 比較:通常「踊り子」 ¥6510(同区間)\n- 運行:1 日 1 往復(土日 + 春休み 2 往復)\n- 予約:JR 東日本 オンライン or 駅窓口\n- 登場意義:伊豆観光高級化路線・修善寺方面はカバーせず",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["luxury_resort", "urban_central"],
    lat: 34.965,
    lon: 139.099,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 5,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.jreast.co.jp/saphir/" },
    tags: ["limited_express_private", "saphir_odoriko", "e261", "2020", "premium_green"],
    source: "manual",
  },
  {
    slug: "shizutetsu-1day-pass",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "しずてつ全線 1 日乗車券(靜岡市 + 清水バス・¥600・観光客便利)",
    title_ja: "しずてつ 1 日乗車券",
    romaji: "Shizutetsu 1Day Pass",
    summary_zh: "**しずてつ 1 日乗車券は静岡市内交通の万能パス**(¥600・大人)。しずてつジャストライン全 200+ バス系統 + 静岡鉄道線(新静岡 ↔ 新清水)が 1 日自由乗降可能。日本平 + 三保松原 + 久能山 + 登呂遺跡 + 駿府城 + 清水港 を 1 日で巡る観光客に最適、¥800-1500 相当の交通費を ¥600 でカバー。",
    content_md: "- 料金:大人 ¥600・子供 ¥300\n- 期間:発売日のみ有効(連続 24 時間ではなく営業日)\n- 範囲:しずてつジャストライン全 200+ 系統 + 静岡鉄道線(新静岡 ↔ 新清水)\n- カバー観光地:日本平 + 三保松原 + 久能山 + 登呂遺跡 + 駿府城 + 清水港 + エスパルスドリームプラザ\n- 比較:単純利用の場合、3 路線で ¥800-1500 相当 → 余裕で元取れる\n- 購入:JR 静岡駅前バスターミナル + しずてつ案内所 + 主要バス車内\n- 公式:しずてつジャストラインアプリ + Web 予約",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["urban_central"],
    lat: 34.972,
    lon: 138.388,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.justline.co.jp/" },
    tags: ["ticket_promo", "shizutetsu_1day", "shizuoka_city", "tourist_pass"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R4 補完(2026-04-29)— 踊り子 E257 + 富士山五合目バス +2
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "odoriko-e257-tokyo-shuzenji",
    category: "transport",
    sub_type: "limited_express_private",
    title_zh: "特急「踊り子」(E257 系・東京 ↔ 修善寺/伊豆急下田・1981 ~ 現在)",
    title_ja: "特急 踊り子",
    romaji: "Odoriko Express",
    summary_zh: "**「踊り子」は東京 ↔ 伊豆を結ぶ JR 東日本特急**(1981 開業)。川端康成『伊豆の踊子』に由来する列車名、東京駅から修善寺方面 + 伊豆急下田方面の 2 系統で運行。長年 185 系で運行されたが 2021 年から E257 系(中央線特急由来の改造車)に世代交代、サフィール踊り子の登場で日常の伊豆観光の主力に。",
    content_md: "- 開業:1981 年(昭和56)\n- 区間:東京 ↔ 修善寺(伊豆箱根駿豆線直通)・東京 ↔ 伊豆急下田(伊豆急線直通)\n- 名称由来:川端康成『伊豆の踊子』(1926)\n- 車両:E257 系(2021 - 現在・185 系から世代交代)\n- 編成:9 両(下田編成 5 両 + 修善寺編成 5 両は熱海で分割併合)\n- 所要:東京 → 伊豆急下田 2 時間 35 分 / 東京 → 修善寺 2 時間\n- 料金:東京 → 下田 ¥6510(自由席 ¥6190)\n- 比較:サフィール踊り子(2020-) ¥9990(プレミアム)・本「踊り子」が標準級\n- 運行:1 日 5-7 往復\n- 連絡:伊豆箱根駿豆線(修善寺方面)+ 伊豆急行(下田方面)直通",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["urban_central", "luxury_resort"],
    lat: 34.965,
    lon: 139.099,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://www.jreast.co.jp/" },
    tags: ["limited_express_private", "odoriko", "e257", "1981", "kawabata_naming"],
    source: "manual",
  },
  {
    slug: "fujikyu-fujisan-5gome-bus",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "富士山 5 合目登山バス(御殿場口 + 富士宮口・夏季限定 7-9 月・登山客専用)",
    title_ja: "富士山 5 合目登山バス",
    romaji: "Mt. Fuji 5th Station Bus",
    summary_zh: "**富士山 5 合目登山バスは登山シーズン(7-9 月)限定運行**。御殿場口 5 合目(1440m)+ 富士宮口 5 合目(2400m)を経由する 2 系統(富士急静岡バス + 富士急モビリティ運行)。マイカー規制中(7-8 月の週末)は登山客全員このバス利用が必須。御殿場駅 + 富士宮駅から各 5 合目まで 80-90 分。",
    content_md: "- 運行期間:7 月 10 日 ~ 9 月 10 日(富士山開山期)\n- 路線:\n  - 御殿場口バス:御殿場駅 → 御殿場口 5 合目(1440m・往復 ¥2780)\n  - 富士宮口バス:富士宮駅 → 富士宮口 5 合目(2400m・往復 ¥3000)\n  - 須走口バス:御殿場駅 → 須走口 5 合目(2000m・往復 ¥2200)\n- 運行会社:富士急静岡バス + 富士急モビリティ\n- 所要:80-90 分(各路線)\n- マイカー規制:7-8 月の週末・連休中は 5 合目以上マイカー不可 → バス必須\n- 予約:現地販売・WEB 予約\n- 注意:強風時運休・登山届必要",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "富士宮市",
    lg_code: "22207",
    area_types: ["mountain_village", "luxury_resort"],
    lat: 35.336,
    lon: 138.732,
    season_start: "2026-07-10",
    season_end: "2026-09-10",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: { official: "https://bus.fujikyu.co.jp/" },
    tags: ["shizuoka_fujisan_view", "mt_fuji_5th_station_bus", "climbing_season"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R5 補完(2026-04-29)— 駅レンタカー + 沼津バス T + 伊豆箱根 1 日 +3
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "jr-shizuoka-rental-car",
    category: "transport",
    sub_type: "rental_car_tips",
    title_zh: "JR 静岡駅レンタカー(駅レンタカー静岡・浜松・三島・空港アクセスの代替)",
    title_ja: "JR 静岡駅レンタカー",
    romaji: "JR Shizuoka Rental Car",
    summary_zh: "**JR 駅レンタカーは静岡駅+浜松駅+三島駅で展開**。新幹線到着→ 駅前で即レンタル可、伊豆東岸(伊豆急電車のみだと遅い)+ 西伊豆(公共交通薄い)+ 富士山麓(御殿場・富士宮 etc.)へのアクセスに有効。トヨタレンタカー + 日産レンタカー + ニコニコレンタカー 等の複数業者が駅前ロータリーに集中。",
    content_md: "- 主要駅:JR 静岡駅・浜松駅・三島駅・沼津駅\n- 主要業者:トヨタレンタカー + 日産レンタカー + ニコニコレンタカー + タイムズカー + Honda レンタリース\n- 料金:軽自動車 ¥4500-6500/日・コンパクト ¥6000-9000/日(平日)・週末 1.5 倍\n- 推奨ルート:\n  - 西伊豆周遊(土肥+堂ヶ島+西伊豆スカイライン)= 静岡駅 or 三島駅から\n  - 富士山麓(白糸の滝+朝霧高原)= 富士駅 or 富士宮駅から\n  - 大井川流域(蓬莱橋+SL 駅+寸又峡)= 静岡駅から\n- 予約:楽天トラベル + じゃらん + 各社公式\n- アクセス:各 JR 駅前ロータリー(徒歩 0-3 分)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["urban_central"],
    lat: 34.972,
    lon: 138.388,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["rental_car_tips", "jr_station_rental", "shizuoka_strategy"],
    source: "manual",
  },
  {
    slug: "numazu-bus-terminal-hub",
    category: "transport",
    sub_type: "transit_hub",
    title_zh: "沼津駅前バスターミナル(沼津港+西伊豆+富士山麓・伊豆 + 富士の起点)",
    title_ja: "沼津駅前バスターミナル",
    romaji: "Numazu Bus Terminal",
    summary_zh: "**沼津駅前バスターミナルは伊豆+富士の主要バス hub**。JR 沼津駅 北口・南口 + 駅 1 分の三島駅(新幹線駅)の中間立地、東海バス(西伊豆方面)+ 富士急静岡バス(富士山方面)+ 沼津登山東海バス(伊豆中央)の 3 社のバスがここで連絡。沼津港(深海水族館)+ 大瀬崎(西伊豆富士絶景)+ 三島スカイウォーク(箱根西側)へのアクセス起点。",
    content_md: "- 立地:JR 沼津駅 北口・南口(駅前ロータリー)\n- 主要バス会社:東海バス + 富士急静岡バス + 沼津登山東海バス\n- 主要路線:\n  - 沼津港(15 分・¥210)\n  - 大瀬崎(60 分・¥1100)西伊豆\n  - 三島スカイウォーク(25 分・¥820)\n  - 御殿場プレミアム・アウトレット(60 分・¥1700)\n  - 富士山須走口 5 合目(夏季・90 分・¥2200)\n- バスターミナル機能:複数会社が同一ターミナル使用・共通待合室\n- アクセス:JR 沼津駅 徒歩 0 分・JR 三島駅(隣・新幹線駅)から在来線 5 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "沼津市",
    lg_code: "22203",
    area_types: ["urban_central"],
    lat: 35.099,
    lon: 138.866,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["transit_hub", "numazu_bus_terminal", "izu_fuji_gateway"],
    source: "manual",
  },
  {
    slug: "izuhakone-1day-pass",
    category: "transport",
    sub_type: "ticket_promo",
    title_zh: "伊豆箱根鉄道 1 日フリー切符(三島〜修善寺 19km・全駅自由乗降・¥1080)",
    title_ja: "伊豆箱根鉄道 1 日フリー切符",
    romaji: "Izuhakone 1 Day Pass",
    summary_zh: "**伊豆箱根 1 日フリー切符は伊豆中部観光の便利パス**(¥1080・1 日有効)。三島駅 ↔ 修善寺駅 19 km の駿豆線全駅で自由乗降、三嶋大社+楽寿園+伊豆長岡(温泉郷)+ 修善寺温泉 を 1 日で巡る観光客に最適。三島駅で新幹線連絡、修善寺駅から東海バスで天城+下田方面 access も可能。",
    content_md: "- 範囲:伊豆箱根鉄道駿豆線 全 13 駅 自由乗降\n- 期間:発売日 1 日有効\n- 料金:大人 ¥1080・小人 ¥540\n- 比較:単純往復 ¥1290 → 1 日で 2-3 駅訪問なら元取れる\n- 含む観光地:\n  - 三島大社(三島田町駅 徒歩 8 分)\n  - 楽寿園(三島駅 徒歩 4 分)\n  - 伊豆長岡温泉(伊豆長岡駅)\n  - 修善寺温泉(修善寺駅 + バス)\n- 別売:特急踊り子料金は別途\n- 購入:三島駅・修善寺駅 + 主要駅窓口\n- 公式:伊豆箱根鉄道公式サイト",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "三島市",
    lg_code: "22206",
    area_types: ["urban_central"],
    lat: 35.124,
    lon: 138.911,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ticket_promo", "izuhakone", "1day_pass", "sunzu_line"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // R6 補完(2026-04-29)— 空港駐車場 + 三島スカイウォークバス +2
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shizuoka-airport-parking-free",
    category: "transport",
    sub_type: "rental_car_tips",
    title_zh: "靜岡空港駐車場(無料 2000 台・最大駐車期間 2 週間・国内空港最大級無料駐車場)",
    title_ja: "静岡空港駐車場",
    romaji: "Shizuoka Airport Parking",
    summary_zh: "**静岡空港駐車場は国内最大級の無料駐車場**(牧之原市・約 2000 台)。福岡・新千歳・那覇等の遠距離便利用客向け、最大 2 週間まで完全無料・予約不要。新幹線 + 飛行機の組合せ旅行(東海道新幹線 静岡駅 → 静岡空港リムジン → 国内便)、地方便でリムジン直結の便利。羽田 + 成田と異なる地方空港のメリット。",
    content_md: "- 立地:富士山静岡空港(牧之原市)\n- 規模:約 2000 台(国内空港最大級の無料駐車場)\n- 料金:**完全無料**(羽田 1 日 ¥1500-2500・成田 ¥2000+ と比較)\n- 最大駐車期間:14 日(2 週間)\n- 予約:不要(現場到着順)\n- 空港アクセス:駐車場から空港ターミナルまで徒歩 3-5 分(無料シャトルなし・徒歩のみ)\n- 注意:夏休み・GW・年末年始 ピーク時は満車の場合あり\n- 混雑時代替:JR 静岡駅前駐車場 ¥1500/日 + 空港リムジンバス\n- アクセス:東名 牧之原 IC 車 8 分・JR 島田駅 から車 20 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "牧之原市",
    lg_code: "22226",
    area_types: ["urban_central", "rural_townscape"],
    lat: 34.797,
    lon: 138.187,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["rental_car_tips", "shizuoka_airport_parking", "free_2000_cars", "japan_largest_free"],
    source: "manual",
  },
  {
    slug: "mishima-skywalk-bus-shuttle",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "三島スカイウォークアクセスバス(JR 三島駅 ↔ スカイウォーク・1 日 6+ 往復)",
    title_ja: "三島スカイウォーク連絡バス",
    romaji: "Mishima Skywalk Shuttle",
    summary_zh: "**三島スカイウォークアクセスバスは JR 三島駅から日本最長吊橋へ直行**。富士急シティバスが運行、所要 25 分・¥820。1 日 6-8 往復(平日)・10 往復(土日祝)、スカイウォーク + 富士山眺望 + 周辺ジップライン体験へ車なしでアクセス可能。三島大社観光と組合せて 1 日コース。",
    content_md: "- 運行:富士急シティバス\n- 区間:JR 三島駅 南口 ↔ 三島スカイウォーク(8 km)\n- 所要:25 分\n- 運賃:大人 ¥820・小人 ¥410(片道)\n- 運行頻度:平日 6-8 往復・土日祝 10 往復\n- 始発/終便:9:00 始発 / 17:30 終便(スカイウォーク発)\n- 連絡:JR 三島駅 南口 1 番乗り場(スカイウォーク・元箱根行)\n- 帰路注意:終便 17:30 後は無いので、夕陽見物等は時間管理を\n- アクセス:JR 三島駅 南口バスターミナル",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "三島市",
    lg_code: "22206",
    area_types: ["urban_central", "luxury_resort"],
    lat: 35.124,
    lon: 138.911,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["area_access_guide", "mishima_skywalk_bus", "fujikyu_city_bus"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[shizuoka-transport] 尚無條目");
    return;
  }
  console.log(`[shizuoka-transport] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(28)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch, { onConflict: "slug" });
    if (error) {
      console.error("[shizuoka-transport] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[shizuoka-transport] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[shizuoka-transport] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
