// Seed 宮城県 楽 R1(20 筆 / Sprint 1.5)
// 仙台 3 大祭 3 / 蔵王 4 / 鳴子峡+三陸景勝 4 / 楽天 + 動物水族館 3 / 松島湾遊覧 2 / 屋外+登山 4 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "tohoku"; prefecture_ja: "宮城県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 仙台 3 大祭 (3)
  { slug: "sendai-tanabata-festival", category: "entertainment", sub_type: "miyagi_3_grand_festivals", title_zh: "仙台七夕まつり(仙台市青葉区・8/6-8(旧暦準拠)+ 伊達政宗 1610 期奨励起源 415 年+ 国指定無形民俗 1968+ 東北 4 大祭(青森ねぶた+秋田竿燈+仙台七夕+山形花笠)+ 200 万人来場+ R1 衣 クリスロード メイン会場)", title_ja: "仙台七夕まつり", romaji: "Sendai Tanabata Matsuri", summary_zh: "**仙台七夕まつりは伊達政宗 1610 期奨励起源 415 年**(8/6-8・**国指定無形民俗 1968**)。東北 4 大祭、200 万人来場、R1 衣 クリスロード メイン会場。", content_md: "- 立地:**仙台市青葉区(R1 衣 クリスロード商店街メイン会場)**\n- 起源:**伊達政宗 1610 期奨励 415 年**\n- 期:**毎年 8/6-8(旧暦準拠)**\n- 認定:**国指定無形民俗 1968**\n- 並列:**東北 4 大祭**(青森ねぶた + 秋田竿燈 + 仙台七夕 + 山形花笠)\n- 規模:**200 万人来場**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["festival_event"], lat: 38.2625, lon: 140.8722, season_start: null, season_end: null, event_start: "2026-08-06", event_end: "2026-08-08", price_tier: 1, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["sendai_tanabata", "1610_date_oshu", "1968_iccn", "tohoku_4_festivals", "2_million"], source: "manual" },
  { slug: "sendai-aoba-matsuri", category: "entertainment", sub_type: "miyagi_3_grand_festivals", title_zh: "仙台青葉まつり(仙台市青葉区・5 月第 3 日曜+ 伊達政宗 1655 仙台藩祭礼起源+ 雀踊り 仙台代表郷土芸能+ 山鉾 11 基巡行+ R1 育 大崎八幡宮 関連+ 入場無料・観覧自由)", title_ja: "仙台青葉まつり", romaji: "Sendai Aoba Matsuri", summary_zh: "**仙台青葉まつりは伊達政宗 1655 仙台藩祭礼起源**(5 月第 3 日曜・**雀踊り郷土芸能**)。山鉾 11 基巡行、R1 育 大崎八幡宮関連、無料。", content_md: "- 立地:**仙台市青葉区**\n- 起源:**伊達政宗 1655 仙台藩祭礼**\n- 期:**毎年 5 月第 3 日曜**\n- 構成:**雀踊り + 山鉾 11 基巡行**\n- 並列:**R1 育 大崎八幡宮 関連**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["festival_event"], lat: 38.2625, lon: 140.8722, season_start: null, season_end: null, event_start: "2026-05-17", event_end: "2026-05-17", price_tier: 1, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["aoba_matsuri", "1655_date", "suzume_odori"], source: "manual" },
  { slug: "sendai-pageant-of-light", category: "entertainment", sub_type: "miyagi_3_grand_festivals", title_zh: "SENDAI 光のページェント(仙台市青葉区定禅寺通+ 1986 開始 39 年+ 12 月初-下旬 60 万球イルミネーション+ 定禅寺通 ケヤキ並木 700m+ 入場無料+ 全国冬イルミネーション ランキング上位+ 観光客 280 万人)", title_ja: "SENDAI 光のページェント", romaji: "SENDAI Hikari no Pageant", summary_zh: "**SENDAI 光のページェントは 1986 開始 39 年**(定禅寺通・**12 月 60 万球+ケヤキ並木 700m**)。全国冬イルミネーション上位、280 万人来場、無料。", content_md: "- 立地:**仙台市青葉区定禅寺通**\n- 起源:**1986 開始 39 年**\n- 期:**12 月初-下旬**\n- 規模:**60 万球イルミネーション + ケヤキ並木 700m**\n- 来場:**280 万人**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["festival_event", "scenic_spot"], lat: 38.2667, lon: 140.8722, season_start: null, season_end: null, event_start: "2026-12-05", event_end: "2026-12-31", price_tier: 1, booking_window_days: 90, closed_days: [], external_urls: { official: "https://www.sendaihikape.jp/" }, tags: ["sendai_pageant", "1986", "600k_lights", "winter_illumination"], source: "manual" },

  // 蔵王 (4)
  { slug: "zao-okama-crater", category: "entertainment", sub_type: "miyagi_zao_scenic", title_zh: "蔵王御釜(刈田郡蔵王町・蔵王連峰火口湖 直径 325m + 深さ 27.6m+ エメラルドグリーン水色+ 蔵王エコーライン 4-11 月+ 山頂駐車場 ¥390+ 入場無料・展望は車道+R1 衣 遠刈田こけし発祥地と組合せ)", title_ja: "蔵王御釜", romaji: "Zaō Okama", summary_zh: "**蔵王御釜は蔵王連峰火口湖**(蔵王町・**直径 325m+深さ 27.6m+エメラルドグリーン**)。エコーライン 4-11 月、山頂駐車場 ¥390、R1 衣 遠刈田組合せ。", content_md: "- 立地:**刈田郡蔵王町(蔵王エコーライン経由)**\n- 規模:**火口湖 直径 325m + 深さ 27.6m**\n- 看板:**エメラルドグリーン水色**\n- 期:**4-11 月開通**(冬期閉鎖)\n- 並列:**R1 衣 遠刈田こけし発祥地 + R1 住 遠刈田温泉**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "刈田郡", municipality_ja: "蔵王町", lg_code: "04301", area_types: ["scenic_spot", "mountain_village"], lat: 38.1428, lon: 140.4583, season_start: "2026-04-15", season_end: "2026-11-15", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["zao_okama", "crater_lake", "325m", "emerald_green"], source: "manual" },
  { slug: "zao-fox-village", category: "entertainment", sub_type: "miyagi_zao_scenic", title_zh: "蔵王きつね村(白石市・1990 開館+ 全国唯一きつね 100+ 匹放牧型動物園+ 6 種類きつね・抱っこ体験 ¥600 別+ SNS 海外観光客集中+ 入場 ¥1,200+ JR 白石駅 タクシー 20 分)", title_ja: "蔵王きつね村", romaji: "Zaō Kitsune-mura", summary_zh: "**蔵王きつね村は全国唯一きつね 100+ 匹放牧型**(白石市・**1990 開館+6 種類**)。抱っこ体験 ¥600、SNS 海外客集中、入場 ¥1,200。", content_md: "- 立地:**白石市福岡八宮**(JR 東北本線 白石駅 タクシー 20 分)\n- 起源:**1990 開館 35 年**\n- 規模:**きつね 100+ 匹放牧型・6 種類**\n- 体験:**抱っこ体験 ¥600 別**\n- 入場:**¥1,200**\n- 認定:**SNS 海外観光客集中**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "白石市", lg_code: "04205", area_types: ["museum_art", "scenic_spot"], lat: 38.0339, lon: 140.5667, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: ["水"], external_urls: { official: "https://zao-fox-village.com/" }, tags: ["zao_fox_village", "1990", "100_foxes", "free_range"], source: "manual" },
  { slug: "zao-eco-line-toll", category: "entertainment", sub_type: "miyagi_zao_scenic", title_zh: "蔵王エコーライン(刈田郡蔵王町・宮城-山形県境 26km 山岳道路+ 1962 開通+ R1 楽 御釜 + 蔵王ハイライン直結+ 4-11 月開通+ 通行無料(蔵王ハイライン ¥390 別)+ 紅葉名所 9-10 月)", title_ja: "蔵王エコーライン", romaji: "Zaō Echo Line", summary_zh: "**蔵王エコーラインは宮城-山形県境 26km 山岳道路**(蔵王町・**1962 開通**)。R1 楽 御釜+蔵王ハイライン直結、4-11 月、通行無料、紅葉名所。", content_md: "- 区間:**宮城蔵王町 ↔ 山形蔵王町(26km 県境道路)**\n- 起源:**1962 開通**\n- 期:**4 月中-11 月中(冬期閉鎖)**\n- 並列:**R1 楽 蔵王御釜 + 蔵王ハイライン直結**\n- 紅葉:**9-10 月名所**\n- 通行:**無料**(蔵王ハイライン御釜方面 ¥390)", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "刈田郡", municipality_ja: "蔵王町", lg_code: "04301", area_types: ["scenic_spot", "transit_hub"], lat: 38.1428, lon: 140.4583, season_start: "2026-04-15", season_end: "2026-11-15", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["zao_echo_line", "1962", "26km", "miyagi_yamagata"], source: "manual" },
  { slug: "miyagi-zao-ski-resort", category: "entertainment", sub_type: "miyagi_zao_scenic", title_zh: "みやぎ蔵王スキー場(蔵王町・宮城蔵王側 4 ゲレンデ統合(澄川+えぼし+白石+セントメリー)+ 12-3 月+ 1 日リフト券 ¥4,500-5,500+ 樹氷ライトアップ 1-2 月+ 仙台市内アクセス便)", title_ja: "みやぎ蔵王スキー場", romaji: "Miyagi Zaō Ski Resort", summary_zh: "**みやぎ蔵王スキー場は宮城蔵王側 4 ゲレンデ統合**(澄川+えぼし+白石+セントメリー)。12-3 月、リフト券 ¥4,500-5,500、樹氷ライトアップ 1-2 月。", content_md: "- 立地:**刈田郡蔵王町**\n- 規模:**4 ゲレンデ統合**(澄川 + えぼし + 白石 + セントメリー)\n- 期:**12-3 月**\n- 料金:**1 日リフト券 ¥4,500-5,500**\n- 看板:**樹氷ライトアップ 1-2 月**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "刈田郡", municipality_ja: "蔵王町", lg_code: "04301", area_types: ["scenic_spot", "mountain_village"], lat: 38.1306, lon: 140.5550, season_start: "2026-12-15", season_end: "2027-03-31", event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["miyagi_zao_ski", "4_gerendre", "juhyou"], source: "manual" },

  // 鳴子峡+三陸景勝 (4)
  { slug: "naruko-kyou-momiji", category: "entertainment", sub_type: "miyagi_zao_scenic", title_zh: "鳴子峡(大崎市鳴子温泉・全長 2.5km 大谷川渓谷+ 紅葉名所 10-11 月東北 No.1+ 国名勝 1989+ 鳴子峡 大深沢橋眺望ポイント+ R1 住 鳴子温泉郷組合せ+ 入場無料)", title_ja: "鳴子峡", romaji: "Naruko Kyō", summary_zh: "**鳴子峡は大谷川渓谷 2.5km 紅葉名所東北 No.1**(大崎市・**国名勝 1989**)。10-11 月、大深沢橋眺望ポイント、R1 住 鳴子温泉郷組合せ、無料。", content_md: "- 立地:**大崎市鳴子温泉(R1 住 鳴子温泉郷)**\n- 規模:**全長 2.5km 大谷川渓谷**\n- 認定:**国名勝 1989 + 紅葉名所東北 No.1**\n- 期:**10-11 月紅葉**\n- 看板:**大深沢橋眺望ポイント**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "大崎市", lg_code: "04213", area_types: ["scenic_spot"], lat: 38.7375, lon: 140.7250, season_start: "2026-10-15", season_end: "2026-11-15", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["naruko_kyou", "1989_meisho", "2_5km", "tohoku_no1_momiji"], source: "manual" },
  { slug: "akiu-otaki-falls", category: "entertainment", sub_type: "miyagi_zao_scenic", title_zh: "秋保大滝(仙台市太白区秋保・落差 55m 三段瀑+ 国名勝 2015+ 「日本三大瀑布」候補(那智+華厳+秋保)+ 入場無料+ R1 住 秋保温泉郷組合せ+ 4-11 月見頃)", title_ja: "秋保大滝", romaji: "Akiu Ōtaki", summary_zh: "**秋保大滝は落差 55m 三段瀑**(仙台市・**国名勝 2015 + 日本三大瀑布候補**)。R1 住 秋保温泉郷組合せ、4-11 月、無料。", content_md: "- 立地:**仙台市太白区秋保**\n- 規模:**落差 55m 三段瀑**\n- 認定:**国名勝 2015 + 「日本三大瀑布」候補**(那智 + 華厳 + 秋保)\n- 期:**4-11 月見頃**\n- 並列:**R1 住 秋保温泉郷拠点**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["scenic_spot"], lat: 38.2606, lon: 140.6708, season_start: "2026-04-15", season_end: "2026-11-15", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["akiu_otaki", "55m", "2015_meisho", "japan_3_falls"], source: "manual" },
  { slug: "matsushima-bay-cruise", category: "entertainment", sub_type: "miyagi_matsushima", title_zh: "松島湾遊覧船(松島町・R1 育 松島日本三景・260+ 島巡覧+ 1 周 50 分・¥1,500-2,000+ 1924 開業 101 年・全国湾遊覧最古の一+ 仁王丸 + 第三仁王丸 等 5+ 隻+ 通年運航)", title_ja: "松島湾遊覧船", romaji: "Matsushima-wan Yūransen", summary_zh: "**松島湾遊覧船は 1924 開業 101 年・全国湾遊覧最古の一**(R1 育 松島・**260+ 島巡覧 50 分 ¥1,500-2,000**)。仁王丸 等 5+ 隻、通年運航。", content_md: "- 立地:**宮城郡松島町(R1 育 松島日本三景)**\n- 起源:**1924 開業 101 年**\n- 規模:**260+ 島巡覧・50 分・¥1,500-2,000**\n- 船:**仁王丸 + 第三仁王丸 等 5+ 隻**\n- 期:**通年運航**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "松島町", lg_code: "04401", area_types: ["scenic_spot", "transit_hub"], lat: 38.3742, lon: 141.0589, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 7, closed_days: [], external_urls: {}, tags: ["matsushima_cruise", "1924", "260_islands"], source: "manual" },
  { slug: "tashirojima-cat-island", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "田代島(石巻市・「猫の島」全国知名度+ 全島民 50 人 vs 猫 200+ 匹+ 江戸期から養蚕農家ネズミ駆除に猫飼育起源+ 海外観光客集中(SNS)+ 石巻港 → フェリー 60 分 ¥1,250)", title_ja: "田代島", romaji: "Tashirojima", summary_zh: "**田代島は「猫の島」全国知名度**(石巻市・**全島民 50 人 vs 猫 200+ 匹**)。江戸期養蚕ネズミ駆除起源、海外観光客 SNS 集中、石巻 → フェリー 60 分 ¥1,250。", content_md: "- 立地:**石巻市田代島**\n- 規模:**全島民 50 人 vs 猫 200+ 匹**\n- 起源:**江戸期 養蚕農家ネズミ駆除に猫飼育**\n- 認定:**「猫の島」全国 + 海外観光客集中**\n- アクセス:**石巻港 → フェリー 60 分 ¥1,250**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "石巻市", lg_code: "04201", area_types: ["scenic_spot"], lat: 38.3056, lon: 141.4239, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tashirojima", "cat_island", "200_cats", "sns_famous"], source: "manual" },

  // 楽天 + 動物水族館 (3)
  { slug: "rakuten-mobile-park-miyagi", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "楽天モバイルパーク宮城(仙台市宮城野区・1950 仙台球場創設・2005 楽天イーグルス本拠地+ 全 30,508 席+ R1 衣 楽天イーグルスグッズ拠点+ プロ野球 NPB パ・リーグ+ 4-10 月シーズン+ 観戦 ¥2,000-15,000)", title_ja: "楽天モバイルパーク宮城", romaji: "Rakuten Mobile Park Miyagi", summary_zh: "**楽天モバイルパーク宮城は楽天イーグルス本拠地**(仙台市・**1950 球場+2005 球団**)。全 30,508 席、R1 衣 グッズ拠点、4-10 月シーズン、¥2,000-15,000。", content_md: "- 立地:**仙台市宮城野区**\n- 起源:**1950 仙台球場創設 + 2005 楽天イーグルス本拠地**\n- 規模:**全 30,508 席**\n- 並列:**R1 衣 楽天イーグルスグッズ**\n- 期:**4-10 月プロ野球シーズン**\n- 価格:**¥2,000-15,000**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["scenic_spot"], lat: 38.2569, lon: 140.9019, season_start: "2026-04-01", season_end: "2026-10-31", event_start: null, event_end: null, price_tier: 3, booking_window_days: 30, closed_days: [], external_urls: { official: "https://rakuteneagles.jp/" }, tags: ["rakuten_park", "1950", "30508_seats"], source: "manual" },
  { slug: "sendai-uminomori-aquarium", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "仙台うみの杜水族館(仙台市宮城野区・2015 開館+ 東日本大震災 2011 後復興象徴施設+ 全 50,000 種類+ 三陸+松島湾再現大水槽+ イルカショー+ 入館 ¥2,400+ 仙台駅 タクシー 20 分)", title_ja: "仙台うみの杜水族館", romaji: "Sendai Umino-Mori Suizokukan", summary_zh: "**仙台うみの杜水族館は震災後 2015 開館復興象徴**(50,000 種+三陸+松島湾再現大水槽)。イルカショー、¥2,400、仙台駅 タクシー 20 分。", content_md: "- 立地:**仙台市宮城野区**\n- 起源:**2015 開館・震災 2011 後復興象徴**\n- 規模:**全 50,000 種類**\n- 看板:**三陸 + 松島湾再現大水槽**\n- 入館:**¥2,400**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["museum_art"], lat: 38.2625, lon: 141.0028, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: { official: "https://www.uminomori.jp/" }, tags: ["uminomori", "2015", "50000_species", "post_disaster"], source: "manual" },
  { slug: "yagiyama-zoo-benyland", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "八木山動物公園+ベニーランド(仙台市太白区・1965 動物公園開園+ 1968 ベニーランド遊園地併設+ 動物 100+ 種・遊園地アトラクション 30++ 動物 ¥480 + ベニーランド ¥1,300+ 子供連れ仙台代表)", title_ja: "八木山動物公園+ベニーランド", romaji: "Yagiyama Zoo / Benny Land", summary_zh: "**八木山動物公園+ベニーランドは 1965+1968 開園・子供連れ仙台代表**(動物 100+ 種+アトラクション 30+)。動物 ¥480・ベニーランド ¥1,300。", content_md: "- 立地:**仙台市太白区**\n- 起源:**1965 動物公園 + 1968 ベニーランド遊園地**\n- 規模:**動物 100+ 種類 + アトラクション 30+**\n- 入場:**動物 ¥480 + ベニーランド ¥1,300**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["scenic_spot", "museum_art"], lat: 38.2461, lon: 140.8347, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yagiyama_zoo", "benny_land", "1965", "100_species"], source: "manual" },

  // 屋外+登山 (4)
  { slug: "izunuma-uchinuma-ramsar", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "伊豆沼・内沼(栗原市+登米市・ラムサール条約 1985 国内 5 番目登録+ 渡り鳥 ハクチョウ+ガン 数万羽飛来+ 11-3 月観察期+ 入場無料+ サンクチュアリセンター ¥200)", title_ja: "伊豆沼・内沼", romaji: "Izunuma Uchinuma", summary_zh: "**伊豆沼・内沼はラムサール条約 1985 国内 5 番目登録**(栗原+登米・**ハクチョウ+ガン数万羽**)。11-3 月観察期、入場無料、サンクチュアリ ¥200。", content_md: "- 立地:**栗原市+登米市**\n- 認定:**ラムサール条約 1985 国内 5 番目登録**\n- 看板:**ハクチョウ + ガン 数万羽飛来**\n- 期:**11-3 月観察期**\n- 入場:**無料(サンクチュアリ ¥200)**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "栗原市", lg_code: "04211", area_types: ["scenic_spot"], lat: 38.7178, lon: 141.1167, season_start: "2026-11-01", season_end: "2027-03-31", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["izunuma", "ramsar_1985", "swans_geese"], source: "manual" },
  { slug: "kinkasan-island-shrine", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "金華山黄金山神社(石巻市鮎川+ 749 日本初産金記念神社派生+ R1 育 涌谷黄金山神社 同期姉妹+ 「金運+商売繁盛」全国信仰+ 鮎川港 → 渡船 30 分+ 入場無料・島内拝観 ¥500)", title_ja: "金華山黄金山神社", romaji: "Kinkasan Koganeyama Jinja", summary_zh: "**金華山黄金山神社は 749 日本初産金記念派生**(石巻市・**R1 育 涌谷黄金山神社姉妹**)。「金運+商売繁盛」全国信仰、鮎川港 → 渡船 30 分、無料・拝観 ¥500。", content_md: "- 立地:**石巻市鮎川金華山島**\n- 起源:**749 日本初産金記念派生**\n- 関連:**R1 育 涌谷黄金山神社 姉妹**\n- 信仰:**金運 + 商売繁盛 全国**\n- アクセス:**鮎川港 → 渡船 30 分**\n- 入場:**無料(島内拝観 ¥500)**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "石巻市", lg_code: "04201", area_types: ["shrine_temple", "scenic_spot"], lat: 38.2825, lon: 141.5808, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kinkasan", "749", "wakuya_partner", "kinun"], source: "manual" },
  { slug: "miyagi-jazz-festival-jozenji", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "定禅寺ストリートジャズフェスティバル(仙台市青葉区定禅寺通+ 1991 開始 34 年+ 9 月第 2 土日+ 全国 700+ バンド 出演+ 路上ストリート無料ライブ+ 仙台秋音楽祭代表+ 観光客 80 万人来場)", title_ja: "定禅寺ストリートジャズフェスティバル", romaji: "Jōzenji Street Jazz Festival", summary_zh: "**定禅寺ストリートジャズは 1991 開始 34 年・無料ライブ**(仙台市・**9 月第 2 土日 + 700+ バンド**)。観光客 80 万人、仙台秋音楽祭代表。", content_md: "- 立地:**仙台市青葉区定禅寺通**\n- 起源:**1991 開始 34 年**\n- 期:**毎年 9 月第 2 土日**\n- 規模:**全国 700+ バンド出演**\n- 来場:**80 万人**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["festival_event"], lat: 38.2667, lon: 140.8722, season_start: null, season_end: null, event_start: "2026-09-12", event_end: "2026-09-13", price_tier: 1, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["jozenji_jazz", "1991", "700_bands", "free"], source: "manual" },
  { slug: "kurihara-bunaichi-trekking", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "栗駒山(栗原市・1626m 標高 + 宮城+岩手+秋田 3 県境+ 紅葉名所「神の絨毯」全国 No.1 候補+ 9 月下-10 月初+ 須川温泉登山口 アクセス+ 登山無料・須川温泉 R1 住 観光と組合せ)", title_ja: "栗駒山", romaji: "Kurikoma-yama", summary_zh: "**栗駒山は宮城+岩手+秋田 3 県境 1626m**(栗原市・**紅葉「神の絨毯」全国 No.1 候補**)。9 月下-10 月初、須川温泉登山口、登山無料。", content_md: "- 立地:**栗原市(宮城+岩手+秋田 3 県境)**\n- 規模:**標高 1626m**\n- 看板:**紅葉「神の絨毯」全国 No.1 候補**\n- 期:**9 月下-10 月初紅葉**\n- アクセス:**須川温泉登山口**\n- 登山:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "栗原市", lg_code: "04211", area_types: ["scenic_spot", "mountain_village"], lat: 38.9697, lon: 140.7842, season_start: "2026-09-15", season_end: "2026-10-15", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kurikoma", "1626m", "kami_no_juutan", "3_pref_border"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[miyagi-entertainment-r1] 尚無條目"); return; }
  console.log(`[miyagi-entertainment-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[miyagi-entertainment-r1] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[miyagi-entertainment-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[miyagi-entertainment-r1] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
