// Seed 静岡県 R9 補完(20 筆 / Sprint 38.x)
//
// 食 +3 / 住 +2 / 衣 +2 / 育 +5 / 楽 +5 / 行 +3 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: string;
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "chubu";
  prefecture_ja: "静岡県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // 食 R9 (3) — 丁子屋 1596 とろろ汁老舗+ 戸田深海えび+ 河津金目鯛
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "cho-jiya-1596-mariko",
    category: "food",
    sub_type: "local_specialty",
    title_zh: "丁子屋(静岡市丸子・1596 創業・429 年・東海道丸子宿とろろ汁老舗・歌川広重浮世絵モチーフ)",
    title_ja: "丁子屋",
    romaji: "Cho-jiya",
    summary_zh: "**丁子屋は東海道丸子宿とろろ汁老舗**(静岡市駿河区・**1596 創業・429 年**)。**東海道五十三次「丸子」歌川広重浮世絵に描かれた茶屋**、駿河自然薯+ 白味噌+ 麦飯の郷土食、芭蕉句碑「梅若菜まりこの宿のとろろ汁」併設。R1 育既出 由比宿 + R3 育 駿府城公園と並ぶ静岡市東海道文化遺産 3 大柱。",
    content_md: "- 創業:1596 年(慶長 1)・429 年\n- 立地:静岡市駿河区丸子(東海道丸子宿)\n- 名物:とろろ汁(駿河自然薯+ 白味噌+ 麦飯)\n- 文化遺産:**東海道五十三次「丸子」歌川広重浮世絵モチーフ**\n- 芭蕉句碑:「梅若菜まりこの宿のとろろ汁」\n- 茅葺き屋根古民家の建物保存\n- 営業:11:00-19:00(木曜+ 第 3 水曜休)\n- アクセス:JR 静岡駅 → 中部国道線バス 30 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "静岡市",
    lg_code: "22100",
    area_types: ["restaurant_traditional"],
    lat: 34.9617,
    lon: 138.3275,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: ["thu"],
    external_urls: { official: "https://chojiya.info/" },
    tags: ["chojiya", "1596", "429_years", "tororo_jiru", "mariko_shukuba", "hiroshige_ukiyoe"],
    source: "manual",
  },
  {
    slug: "heda-fukai-ebi",
    category: "food",
    sub_type: "local_specialty",
    title_zh: "戸田深海えび料理(沼津市戸田・水深 200m+ 駿河湾深海漁・「メギス・トヤマエビ・ヒメアマエビ」郷土食)",
    title_ja: "戸田深海えび料理",
    romaji: "Heda Fukai Ebi",
    summary_zh: "**戸田深海えび料理は駿河湾深海漁の独自郷土食**(沼津市戸田・**水深 200m 級漁場**)。**メギス + トヤマエビ + ヒメアマエビ等の深海甲殻類**、戸田漁港(西伊豆)で水揚げ即料理、本州一深い駿河湾の最大資産。R1 楽既出 大瀬崎+ R7 楽 沼津港深海水族館と一体観光ルート。",
    content_md: "- 産地:沼津市戸田(西伊豆・駿河湾)\n- 漁場:水深 200m 級駿河湾深海\n- 主要種:メギス(本州唯一商業漁)+ トヤマエビ+ ヒメアマエビ\n- 食堂:戸田漁港周辺 数軒(水揚げ直送)\n- 季節:通年(冬深海漁繁忙期)\n- 価格:深海定食 ¥2500-4000\n- 関連:沼津港深海水族館展示+ 戸田造船郷土資料館\n- アクセス:沼津駅 → 東海バス戸田行 約 60 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "沼津市",
    lg_code: "22203",
    area_types: ["restaurant_traditional", "coastal"],
    lat: 35.0028,
    lon: 138.7822,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["heda", "deep_sea_shrimp", "suruga_bay", "200m_depth", "megisu", "regional"],
    source: "manual",
  },
  {
    slug: "kawazu-kinmedai",
    category: "food",
    sub_type: "local_specialty",
    title_zh: "河津金目鯛料理(河津町・伊豆半島南東水揚げ・全国 1 位の高級魚)",
    title_ja: "河津金目鯛",
    romaji: "Kawazu Kinmedai",
    summary_zh: "**河津金目鯛は伊豆半島南東部の高級魚名物**(河津町・**全国水揚げ 1 位**)。**煮付け+ 刺身+ 鍋の郷土調理**、R1 食既出 下田金目鯛と隣接漁港、河津桜まつり期(2 月-3 月)+ 通年に旬。下田-河津-伊東の伊豆東海岸金目鯛圏の中核。",
    content_md: "- 産地:河津町・伊豆半島南東\n- 全国順位:**金目鯛水揚げ 1 位**(下田+ 河津+ 伊東統合)\n- 名物調理:煮付け(関東風砂糖醤油)+ 刺身+ 鍋\n- 季節:旬は通年(特に冬-早春)\n- 関連祭:河津桜まつり期(2-3 月)グルメ集積\n- 食堂:河津駅周辺 + 河津港 数軒\n- 価格:煮付け定食 ¥2500-4500\n- アクセス:伊豆急行河津駅 徒歩 5 分(港 + 食堂)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: "賀茂郡",
    municipality_ja: "河津町",
    lg_code: "22302",
    area_types: ["restaurant_traditional", "coastal"],
    lat: 34.7458,
    lon: 138.9933,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kawazu", "kinmedai", "izu_southeast", "1st_landing", "regional"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 住 R9 (2) — 戸田温泉旅館圏+ 松崎温泉旅館圏
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "heda-onsen-area",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "戸田温泉旅館圏(沼津市戸田・西伊豆漁村+ 駿河湾view+ 深海えび料理付き)",
    title_ja: "戸田温泉旅館圏",
    romaji: "Heda Onsen Ryokan",
    summary_zh: "**戸田温泉は西伊豆漁村型温泉**(沼津市戸田・**駿河湾view 主体**)。**漁師経営民宿+ 深海えび料理付き宿+ 温泉旅館 数十軒**、R1 食既出 西伊豆民宿圏(西伊豆町)に隣接、富士山眺望+ 漁港食事の独自構造。",
    content_md: "- 立地:沼津市戸田(西伊豆・駿河湾)\n- 性格:漁村型温泉宿圏\n- 食事:**戸田深海えび料理付**(メギス+ トヤマエビ等)\n- view:駿河湾+ 富士山眺望\n- 軒数:数十軒(漁師民宿+ 温泉旅館の混合)\n- 価格:1 泊 2 食 ¥12,000-25,000\n- アクセス:沼津駅 → 東海バス戸田行 約 60 分(車推奨)\n- 並列圏:西伊豆町・松崎町・修善寺",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "沼津市",
    lg_code: "22203",
    area_types: ["onsen_field", "coastal"],
    lat: 35.0028,
    lon: 138.7822,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["heda_onsen", "nishi_izu", "fishing_village", "deep_sea_shrimp", "fuji_view"],
    source: "manual",
  },
  {
    slug: "matsuzaki-onsen-area",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "松崎温泉旅館圏(松崎町・なまこ壁伝建保存地区+ 桜葉産地+ 西伊豆海岸温泉宿)",
    title_ja: "松崎温泉旅館圏",
    romaji: "Matsuzaki Onsen Ryokan",
    summary_zh: "**松崎温泉は西伊豆代表的温泉宿圏**(松崎町・**なまこ壁伝建保存地区併存**)。**伊豆桜葉産地全国 70%+ 漁港金目鯛**、R6 楽既出 河津桜まつりと並ぶ西伊豆代表観光地。R1 食既出 西伊豆民宿圏 に隣接、レトロ歴史町並み+ 温泉宿の独自魅力。",
    content_md: "- 立地:松崎町(西伊豆中部)\n- 性格:伝建保存地区併設の温泉宿圏\n- 文化遺産:**なまこ壁伝建保存地区**(白漆喰+ 黒瓦交差)\n- 産物:桜葉(全国 70% シェア)+ 金目鯛+ 干物\n- 軒数:旅館 + 民宿 + ホテル 計 30+ 軒\n- 価格:1 泊 2 食 ¥12,000-30,000\n- アクセス:伊豆急下田駅 → 東海バス松崎行 約 50 分\n- 周辺:堂ヶ島(西隣)+ 雲見(南)+ 黄金崎(北)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: "賀茂郡",
    municipality_ja: "松崎町",
    lg_code: "22305",
    area_types: ["onsen_field", "coastal", "historic_district"],
    lat: 34.7508,
    lon: 138.7903,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["matsuzaki", "namako_kabe", "sakura_leaf_70%", "kinmedai", "nishi_izu"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 衣 R9 (2) — 浜松雛人形+ 焼津駅前商店街
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "hamamatsu-hina-ningyo",
    category: "fashion",
    sub_type: "craft_goods",
    title_zh: "浜松雛人形(浜松市・東海地方 雛人形主産地・遠州雛 + 工房 数十軒)",
    title_ja: "浜松雛人形",
    romaji: "Hamamatsu Hina Ningyo",
    summary_zh: "**浜松雛人形は東海地方代表的雛人形産地**(浜松市・**遠州雛として独自系譜**)。**京都・埼玉岩槻と並ぶ全国 3 大雛人形産地**、R1 衣既出 遠州織物 (遠州縞・遠州ジーンズ)と同系譜の遠州職人文化、3 月雛祭シーズン全国出荷。",
    content_md: "- 産地:浜松市 + 静岡県西部一帯\n- 系譜:遠州雛(京風基調 + 関東風混合)\n- 全国順位:京都(京雛)+ 岩槻(関東雛)+ 浜松雛 の 3 大産地\n- 製法:衣装着雛(衣装人形)+ 木目込み雛 兼業\n- 関連工芸:遠州織物 + 遠州刺繍\n- 季節:1-3 月雛祭シーズン\n- 工房:浜松市内 数十軒(伝統 + 現代)\n- 購入:浜松市内雛人形店 + 全国百貨店",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["craft_workshop"],
    lat: 34.7106,
    lon: 137.7261,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hamamatsu_hina", "enshu_hina", "doll_craft", "top3_japan", "tokai"],
    source: "manual",
  },
  {
    slug: "yaizu-eki-mae-shotengai",
    category: "fashion",
    sub_type: "shopping_district_local",
    title_zh: "焼津駅前商店街(焼津市・まぐろ + 鰹節 土産集積+ 港町商店街)",
    title_ja: "焼津駅前商店街",
    romaji: "Yaizu Eki Mae Shotengai",
    summary_zh: "**焼津駅前商店街は焼津港町中心商店街**(焼津市・**まぐろ + 鰹節 土産集積**)。**R1 食既出 焼津まぐろ + 焼津さかなセンター + 丸七鰹節店 1929 等のお土産源**、JR 焼津駅 徒歩 5 分の好立地、港町日常+ 観光物産の併存空間。",
    content_md: "- 立地:焼津市 JR 焼津駅周辺\n- 集積:まぐろ加工品+ 鰹節+ 駿河湾海産\n- 並列スポット:焼津さかなセンター(駅から車 10 分)\n- 老舗:丸七鰹節店 1929(R1 食既出)\n- 観光土産:鰹節+ 缶詰+ 干物+ ふりかけ\n- 営業:店舗ごとに異なる(平均 9:00-18:00)\n- アクセス:JR 焼津駅 徒歩 5 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "焼津市",
    lg_code: "22213",
    area_types: ["shopping_district"],
    lat: 34.8694,
    lon: 138.3144,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yaizu", "eki_mae", "tuna_souvenir", "katsuobushi", "port_town"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 育 R9 (5) — 秋葉神社+ 願成就院+ 龍潭寺+ 横須賀城跡+ 修禅寺
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "akiha-jinja-tenryu",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "秋葉山本宮秋葉神社(浜松市天竜区・1300+ 年・全国秋葉信仰総本宮+ 火防神)",
    title_ja: "秋葉山本宮秋葉神社",
    romaji: "Akihasan Hongū Akiha Jinja",
    summary_zh: "**秋葉山本宮秋葉神社は全国秋葉信仰総本宮**(浜松市天竜区・**1300+ 年・火防神**)。**全国秋葉神社 800+ 社の総本社**、東京の秋葉原地名語源、R3 育既出 法多山尊永寺+ 油山寺(遠州三山)と並ぶ浜松北部 4 大霊場。標高 866m 上社 + 下社の二社構造。",
    content_md: "- 創建:709 年(和銅 2)・1300+ 年\n- 立地:浜松市天竜区春野町(標高 866m 上社)\n- 系譜:**全国秋葉神社 800+ 社の総本宮**\n- 主祭神:火之迦具土大神(火防神)\n- 信仰圏:全国の防火祈願・関東の秋葉原地名語源\n- 二社構造:上社(山頂)+ 下社(山麓)\n- 例祭:12/15-16 火祭(火渡り神事)\n- アクセス:JR 浜松駅 → 遠鉄バス気田 → 車 30 分(山道)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["shrine_temple", "mountain"],
    lat: 34.9269,
    lon: 137.8794,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.akihasanhongu.jp/" },
    tags: ["akiha_hongu", "fire_god", "1300_years", "akiba_root", "800_shrines"],
    source: "manual",
  },
  {
    slug: "ganjyojuin-1189-izunokuni",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "願成就院(伊豆の国市・1189 北条時政建立+ 国宝 運慶 五仏 2013 指定+ 鎌倉幕府執権氏祈願寺)",
    title_ja: "願成就院",
    romaji: "Ganjyojuin",
    summary_zh: "**願成就院は鎌倉幕府執権氏 北条時政祈願寺**(伊豆の国市・**1189 創建+ 国宝運慶五仏 2013 指定**)。**奥州征伐戦勝祈願に建立**、運慶最高傑作の阿弥陀+ 不動明王+ 毘沙門天等 5 体国宝、伊豆国国宝仏像の最高峰。R3 育既出 韮山反射炉と隣接、伊豆の国市 2 大文化遺産。",
    content_md: "- 創建:1189 年(文治 5)・836 年\n- 建立者:北条時政(鎌倉幕府初代執権)\n- 由緒:奥州征伐戦勝祈願\n- 文化財:**国宝 運慶五仏 2013 指定**(阿弥陀如来+ 不動明王+ 矜羯羅+ 制咜迦+ 毘沙門天)\n- 評価:運慶最高傑作群+ 伊豆国宝仏像最高峰\n- 立地:伊豆の国市寺家\n- 拝観:9:00-16:30(月+ 火休)\n- 拝観料:大人 700 円\n- アクセス:伊豆箱根鉄道伊豆長岡駅 徒歩 18 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊豆の国市",
    lg_code: "22225",
    area_types: ["shrine_temple"],
    lat: 35.0464,
    lon: 138.9489,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["mon", "tue"],
    external_urls: {},
    tags: ["ganjyojuin", "1189", "hojo_tokimasa", "unkei_5_gokuho", "national_treasure"],
    source: "manual",
  },
  {
    slug: "ryotanji-1340-hamamatsu",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "龍潭寺(浜松市北区・1340 創建+ 井伊家菩提寺+ 井伊直虎ゆかり+ 小堀遠州 庭園 国指定名勝)",
    title_ja: "龍潭寺",
    romaji: "Ryotanji",
    summary_zh: "**龍潭寺は井伊家菩提寺**(浜松市北区・**1340 創建+ 井伊家 40 代墓所**)。**戦国女城主 井伊直虎ゆかり+ 後の彦根藩井伊家の発祥地**、小堀遠州作庭園 国指定名勝、2017 大河ドラマ「おんな城主直虎」の聖地。R3 育既出 井伊谷宮 + 浜松城と並ぶ井伊家ゆかり 3 大史跡。",
    content_md: "- 創建:1340 年(暦応 3)・685 年\n- 立地:浜松市北区引佐町井伊谷\n- 系譜:**井伊家菩提寺**(40 代墓所)\n- 著名:**戦国女城主 井伊直虎ゆかり**\n- 後継:後の彦根藩井伊家(井伊直政)発祥地\n- 文化財:**小堀遠州作庭園 国指定名勝**\n- 大河:2017 おんな城主直虎 聖地\n- 拝観:9:00-16:30(8/15+ 12/22-27 休)\n- 拝観料:大人 500 円\n- アクセス:JR 浜松駅 → バス 50 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["shrine_temple"],
    lat: 34.8392,
    lon: 137.6347,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.ryotanji.com/" },
    tags: ["ryotanji", "1340", "ii_naotora", "hikone_root", "kobori_enshu", "national_scenic"],
    source: "manual",
  },
  {
    slug: "yokosuka-jou-ato-kakegawa",
    category: "culture",
    sub_type: "history_site_castle",
    title_zh: "横須賀城跡(掛川市・1578 高天神城合戦の徳川築城+ 国指定史跡 1981+ 玉石垣独自構造)",
    title_ja: "横須賀城跡",
    romaji: "Yokosuka Jou Ato",
    summary_zh: "**横須賀城は徳川 vs 武田高天神城合戦拠点**(掛川市・**1578 築城+ 国指定史跡 1981**)。**全国稀少の玉石垣構造**(普通の切石垣でなく自然石を丸く配置)、徳川家康+ 大須賀康高築城、廃城後 完全消滅したが石垣現存。R3 育既出 掛川城+ R1 育 蓬莱橋と並ぶ掛川市歴史 3 大遺跡。",
    content_md: "- 築城:1578 年(天正 6)\n- 築城者:大須賀康高(徳川家康家臣)\n- 由緒:武田家高天神城合戦の徳川拠点\n- 文化財:**国指定史跡 1981**\n- 特異:**玉石垣構造**(全国稀少・自然丸石使用)\n- 廃城:1873 廃城令\n- 現状:玉石垣 + 城跡公園\n- 入場:無料(24h 開放)\n- アクセス:JR 袋井駅 → バス 30 分・JR 掛川駅 → バス 35 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "掛川市",
    lg_code: "22213",
    area_types: ["history_site_castle", "historic_district"],
    lat: 34.6975,
    lon: 138.0444,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["yokosuka_jou", "1578", "tokugawa", "tamishigaki", "national_historic_1981"],
    source: "manual",
  },
  {
    slug: "shuzenji-temple-807",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "修禅寺(伊豆市・807 空海開基+ 修善寺温泉発祥地+ 鎌倉源氏ゆかり源頼家暗殺地)",
    title_ja: "修禅寺",
    romaji: "Shuzenji",
    summary_zh: "**修禅寺は弘法大師空海 807 開基**(伊豆市・**1218 年・修善寺温泉発祥地**)。**807 空海地中井戸が独鈷の湯発祥**、伊豆最古級寺院、R1 育既出 韮山反射炉+ 江川邸と並ぶ伊豆中部 3 大歴史拠点。**鎌倉幕府 2 代将軍源頼家暗殺地 1204** の悲劇舞台、岡本綺堂「修禅寺物語」の故郷。",
    content_md: "- 創建:807 年(大同 2)・1218 年\n- 開基:**弘法大師空海**\n- 立地:伊豆市修善寺\n- 由緒:修善寺温泉発祥地(空海地中井戸 → 独鈷の湯)\n- 歴史:**1204 鎌倉幕府 2 代将軍源頼家暗殺地**\n- 文学:岡本綺堂「修禅寺物語」(1911) の故郷\n- 周辺:独鈷の湯+ 竹林の小径+ 修善寺温泉街\n- 拝観:9:00-16:30\n- 拝観料:無料(宝物殿 300 円)\n- アクセス:伊豆箱根鉄道修善寺駅 徒歩 15 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊豆市",
    lg_code: "22222",
    area_types: ["shrine_temple", "onsen_field"],
    lat: 34.9669,
    lon: 138.9325,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["shuzenji", "807", "kukai", "onsen_origin", "minamoto_yoriie", "kido_okamoto"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 楽 R9 (5) — 堂ヶ島天窓洞+ 黄金崎夕日+ 松崎なまこ壁+ 戸田まぐろ祭+ 熱海桜
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "dougashima-cave-cruise",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "堂ヶ島天窓洞クルーズ(西伊豆町・国指定天然記念物+ 海蝕洞窟+ 天井穴から差し込む光)",
    title_ja: "堂ヶ島天窓洞遊覧船",
    romaji: "Dougashima Tenmadou Cruise",
    summary_zh: "**堂ヶ島天窓洞は国指定天然記念物の海蝕洞窟**(西伊豆町・**洞窟天井穴から差し込む光が幻想的**)。**遊覧船で内部進入可能の独自体験**、伊豆ジオパークの代表ジオサイト、R1 楽既出 伊豆半島ジオパーク 2018 の中核観光地。R6 楽既出 河津桜まつりに次ぐ西伊豆代表観光地。",
    content_md: "- 立地:西伊豆町仁科 堂ヶ島港\n- 文化財:**国指定天然記念物**\n- 特異:**遊覧船で洞窟内進入可能**(全国稀有)\n- 名物:洞窟天井穴から差し込む太陽光\n- ジオパーク:伊豆ジオパーク代表ジオサイト\n- 所要:遊覧 20 分\n- 料金:大人 1500 円\n- 運航:9:15-16:15(波高 1m 超で欠航)\n- アクセス:伊豆急下田駅 → 東海バス堂ヶ島行 約 50 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: "賀茂郡",
    municipality_ja: "西伊豆町",
    lg_code: "22306",
    area_types: ["scenic_spot", "coastal"],
    lat: 34.7836,
    lon: 138.7689,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://izudougasima-yuransen.com/" },
    tags: ["dougashima", "tenmadou", "cave_cruise", "natural_monument", "izu_geopark"],
    source: "manual",
  },
  {
    slug: "koganezaki-sunset",
    category: "entertainment",
    sub_type: "shizuoka_nature_spot",
    title_zh: "黄金崎(西伊豆町・「日本の夕陽百選」+ プロピライト岩 国指定天然記念物+ 馬の蹄岩奇景)",
    title_ja: "黄金崎",
    romaji: "Koganezaki",
    summary_zh: "**黄金崎は「日本の夕陽百選」西伊豆代表夕日スポット**(西伊豆町・**プロピライト岩 国指定天然記念物**)。**夕日に黄金色に輝く岩肌+ 馬の蹄形奇岩**、R1 楽既出 大瀬崎+ 三島スカイウォークと並ぶ静岡富士山+ 駿河湾眺望 3 大柱。",
    content_md: "- 立地:西伊豆町宇久須\n- 認定:**「日本の夕陽百選」**\n- 文化財:**プロピライト岩 国指定天然記念物**\n- 特異:**夕日に黄金色に輝く岩肌**(プロピライト変質岩)\n- 奇岩:馬の蹄形奇岩+ 富士山遠景\n- 入場:無料(駐車場 + 散策路完備)\n- ベスト時間:夕日 30 分前\n- アクセス:伊豆急下田駅 → 東海バス約 60 分(車推奨)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: "賀茂郡",
    municipality_ja: "西伊豆町",
    lg_code: "22306",
    area_types: ["scenic_spot", "coastal"],
    lat: 34.8167,
    lon: 138.7681,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["koganezaki", "sunset_top100", "propylite", "natural_monument", "horseshoe_rock"],
    source: "manual",
  },
  {
    slug: "matsuzaki-namako-kabe",
    category: "entertainment",
    sub_type: "model_course",
    title_zh: "松崎なまこ壁通り(松崎町・重要伝統的建造物群保存地区候補+ 白漆喰 + 黒瓦交差伝統町並み)",
    title_ja: "松崎なまこ壁通り",
    romaji: "Matsuzaki Namako Kabe",
    summary_zh: "**松崎なまこ壁通りは西伊豆代表的歴史町並み**(松崎町・**白漆喰 + 黒瓦の格子状ナマコ壁建築**)。**伊豆地方独自の漆喰防火建築 + 港町商家**、R6 育既出 伝建保存地区候補、R7 楽既出 河津桜まつりと並ぶ西伊豆代表観光地。江戸後期-明治期建築 100+ 棟現存。",
    content_md: "- 立地:松崎町松崎(松崎港 周辺)\n- 性格:伊豆代表的なまこ壁建築群\n- 構造:**白漆喰 + 黒瓦交差ナマコ壁**(防火 + 装飾)\n- 数:江戸後期-明治期建築 100+ 棟現存\n- 主要施設:伊豆文邸+ 中瀬邸+ 旧依田邸\n- 体験:町並み散策(無料)+ 一部施設拝観有料\n- 認定:伝統的建造物群保存地区候補\n- 周辺:松崎港+ 桜葉産地+ 雲見温泉\n- アクセス:伊豆急下田駅 → 東海バス松崎港行 約 50 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: "賀茂郡",
    municipality_ja: "松崎町",
    lg_code: "22305",
    area_types: ["historic_district", "coastal"],
    lat: 34.7508,
    lon: 138.7903,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["matsuzaki", "namako_kabe", "edo_late", "shikkui_kawara", "100_buildings"],
    source: "manual",
  },
  {
    slug: "heda-tuna-festival-jan",
    category: "entertainment",
    sub_type: "seasonal_food",
    title_zh: "戸田 まぐろ祭り(沼津市戸田・1 月開催+ 冬まぐろ + 深海えび試食+ 西伊豆漁師まつり)",
    title_ja: "戸田まぐろ祭り",
    romaji: "Heda Maguro Matsuri",
    summary_zh: "**戸田まぐろ祭りは西伊豆漁師まつり**(沼津市戸田・**1 月開催+ 冬まぐろ + 深海えび試食**)。**戸田漁港広場で生まぐろ解体ショー + 深海えび販売**、R9 食既出 戸田深海えび料理 + R9 住 戸田温泉と一体イベント。冬の駿河湾恵みを堪能する漁村祭。",
    content_md: "- 開催:1 月下旬 1 日\n- 立地:戸田漁港広場(沼津市戸田)\n- 内容:生まぐろ解体ショー + 深海えび販売 + 港町屋台\n- 主役:冬まぐろ + 駿河湾深海えび(メギス + トヤマエビ)\n- 入場:無料\n- 並列:R9 食 戸田深海えび料理 + R9 住 戸田温泉旅館圏\n- アクセス:沼津駅 → 東海バス戸田行 約 60 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "沼津市",
    lg_code: "22203",
    area_types: ["festival_event", "coastal"],
    lat: 35.0028,
    lon: 138.7822,
    season_start: null,
    season_end: null,
    event_start: "2026-01-25",
    event_end: "2026-01-25",
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["heda", "tuna_festival", "winter", "deep_sea_shrimp", "fishing_village"],
    source: "manual",
  },
  {
    slug: "atami-cherry-blossom-jan",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "熱海桜(熱海市・1-2 月開花の全国級早咲き+ 糸川遊歩道桜並木 1 月開催)",
    title_ja: "熱海桜",
    romaji: "Atami Zakura",
    summary_zh: "**熱海桜は全国級早咲き桜**(熱海市・**1 月-2 月上旬開花+ 河津桜より早い**)。**糸川遊歩道沿桜並木+ あたみ桜糸川桜まつり 1 月開催**、R3 楽既出 河津桜まつり(2-3 月)に先駆ける東日本最早桜、温泉旅行+ 早春桜の組合せ独自魅力。",
    content_md: "- 開花:1 月上旬-2 月上旬(全国最早級)\n- 立地:熱海市 糸川遊歩道沿(全長 800m)\n- 並木:約 60 本\n- 祭:あたみ桜糸川桜まつり 1 月下旬-2 月上旬\n- 系譜:インドのヒマラヤ桜系 → カンザクラ系統\n- 並列:**河津桜(2-3 月)より早い+ 全国最早桜**\n- 入場:無料(遊歩道散策)\n- アクセス:JR 熱海駅 徒歩 15 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "熱海市",
    lg_code: "22205",
    area_types: ["scenic_spot"],
    lat: 35.0967,
    lon: 139.0689,
    season_start: "2026-01-10",
    season_end: "2026-02-10",
    event_start: "2026-01-25",
    event_end: "2026-02-08",
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["atami_zakura", "earliest_japan", "itokawa", "60_trees", "before_kawazu"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 行 R9 (3) — JR 身延線+ 浜名湖遊覧船+ 伊東港大島フェリー
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "jr-minobu-line-shizuoka",
    category: "transport",
    sub_type: "shizuoka_local_railway",
    title_zh: "JR 身延線(富士-甲府・88km・1928 全通+ 富士川渓谷沿縦貫+ 富士宮 + 富士両駅 結節)",
    title_ja: "JR 身延線",
    romaji: "JR Minobu Line",
    summary_zh: "**JR 身延線は富士-甲府結節 88km 縦貫線**(JR 東海・**1928 全通+ 富士川渓谷沿**)。**富士山本宮浅間大社最寄りの富士宮駅 + 富士駅で東海道本線と接続**、富士川+ 身延山 + 甲府盆地への山岳路線。R1 行既出 JR 東海道本線 + R1 行 JR 御殿場線と並ぶ静岡側 JR 在来線 3 大柱。",
    content_md: "- 全通:1928 年(昭和 3)・97 年\n- 区間:富士駅(静岡県富士市)〜 甲府駅(山梨県)\n- 距離:88km(45 駅)\n- 運営:JR 東海\n- 主要駅(静岡側):富士+ 富士宮+ 入山瀬+ 富士根+ 西富士宮 等\n- 関連:**富士山本宮浅間大社最寄り 富士宮駅**\n- 風景:富士川渓谷+ 身延山(山梨)+ 甲府盆地\n- 運行:特急ワイドビューふじかわ(JR 静岡-甲府)+ 普通\n- 接続:富士駅で JR 東海道本線",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "富士市",
    lg_code: "22210",
    area_types: ["transit_hub"],
    lat: 35.1611,
    lon: 138.6803,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jr_minobu", "fuji_kofu", "88km", "1928", "fujikawa", "fujisan_taisha_access"],
    source: "manual",
  },
  {
    slug: "hamanako-yuran-sen",
    category: "transport",
    sub_type: "ferry_island",
    title_zh: "浜名湖遊覧船(浜松市西区・舘山寺発着+ 約 30 分周遊+ 浜名湖一帯観光連絡)",
    title_ja: "浜名湖遊覧船",
    romaji: "Hamanako Yuransen",
    summary_zh: "**浜名湖遊覧船は浜名湖観光主交通**(浜松市西区・**舘山寺港発着+ 約 30 分周遊**)。**舘山寺温泉 + 浜名湖パルパル + 浜名湖ガーデンパーク連絡**、R1 行既出 天竜浜名湖鉄道 + R1 楽 浜名湖パルパルと一体観光ルート。汽水湖の独特な景観 + 養殖筏 view。",
    content_md: "- 立地:浜松市西区舘山寺 浜名湖遊覧船舘山寺港\n- 所要:約 30-40 分(コース別)\n- 主要発着:舘山寺港 ↔ 浜名湖ガーデンパーク+ 瀬戸\n- 風景:汽水湖+ 養殖筏+ うなぎ筏+ 弁天島鳥居\n- 料金:大人 1450 円(基本コース)\n- 運航:約 30 分間隔(夏期繁忙)+ 冬減便\n- 並列:R1 楽 浜名湖パルパル+ R3 楽 浜名湖ガーデンパーク\n- アクセス:JR 浜松駅 → 遠鉄バス舘山寺温泉行 約 45 分",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "浜松市",
    lg_code: "22130",
    area_types: ["transit_hub", "coastal"],
    lat: 34.7400,
    lon: 137.6450,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hamanako", "yuransen", "kanzanji", "30min", "freshwater_lake", "eel_raft"],
    source: "manual",
  },
  {
    slug: "ito-port-oshima-ferry",
    category: "transport",
    sub_type: "shizuoka_izu_access",
    title_zh: "伊東港 → 伊豆大島フェリー(伊東市・東海汽船運航+ 約 1.5h+ 大島椿祭 1-3 月需要)",
    title_ja: "伊東-大島フェリー",
    romaji: "Itou-Oshima Ferry",
    summary_zh: "**伊東港 → 伊豆大島フェリーは伊豆東海岸 → 伊豆諸島連絡**(伊東市・**東海汽船運航+ 約 1.5 時間**)。**1-3 月の伊豆大島椿祭シーズン需要**、R1 行既出 JR 伊東線+ 伊豆急行と接続、東京竹芝-伊豆大島の代替航路。",
    content_md: "- 航路:伊東港 ↔ 伊豆大島(元町港)\n- 所要:約 1 時間 35 分\n- 運営:**東海汽船**\n- 運賃:大人 3700 円(片道 2 等)\n- 季節:1-3 月椿祭+ 夏海水浴需要繁忙\n- 並列:東京竹芝 → 大島 大型船 1.75 時間\n- 接続:JR 伊東線+ 伊豆急行+ 伊東駅\n- 注意:風波で欠航多い+ 要事前確認\n- アクセス:JR 伊東駅 → 徒歩 10 分(伊東港)",
    region: "chubu",
    prefecture_ja: "静岡県",
    gun_ja: null,
    municipality_ja: "伊東市",
    lg_code: "22208",
    area_types: ["transit_hub", "coastal"],
    lat: 34.9692,
    lon: 139.1003,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["ito_port", "oshima_ferry", "tokai_kisen", "1h35min", "tsubaki_festival"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[shizuoka-r9] 尚無條目");
    return;
  }
  console.log(`[shizuoka-r9] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const byCat = new Map<string, number>();
    for (const r of rows) byCat.set(r.category, (byCat.get(r.category) ?? 0) + 1);
    for (const [k, v] of [...byCat.entries()].sort()) {
      console.log(`  ${k.padEnd(15)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[shizuoka-r9] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[shizuoka-r9] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[shizuoka-r9] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
