// Seed 徳島県 R2 補完(20 筆 / Sprint 2.x / 第十六卷)
// 食 5 / 衣 3 / 住 3 / 育 3 / 楽 4 / 行 2 = 20 累積 122 + 20 = 142
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 食 5
  { slug: "awa-bancha", category: "food", sub_type: "tokushima_kyodo", title_zh: "阿波番茶+ 山茶(美馬市+ 三好+ つるぎ・国指定無形民俗 2019・上勝町・那賀町山茶 200+ 年伝統+ 乳酸発酵後発酵茶+ 全国唯一の発酵茶+ ¥1,500-3,500/100g・国際 SNS 海外発酵茶ファン代表)", title_ja: "阿波番茶", romaji: "Awa Bancha", summary_zh: "**阿波番茶+山茶は国指定無形民俗 2019・上勝+那賀山茶 200+ 年・全国唯一の乳酸発酵後発酵茶**(美馬+三好+つるぎ)。¥1,500-3,500/100g、海外発酵茶ファン代表。", content_md: "- 立地:**美馬市 + 三好市 + つるぎ町 + 上勝町 + 那賀町**\n- 起源:**山茶 200+ 年伝統**\n- 認定:**国指定重要無形民俗文化財 2019 + 全国唯一の発酵茶**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "美馬市", lg_code: "36207", area_types: ["restaurant_traditional", "industrial_heritage"], lat: 34.0500, lon: 134.0167, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["awa_bancha_2019"], source: "manual" },
  { slug: "naruto-wakame-tsukudani", category: "food", sub_type: "tokushima_seafood", title_zh: "鳴門わかめ加工品+ 佃煮(鳴門市・R1 食 鳴門わかめ派生・1900 年代以降産業化 100+ 年+ わかめ佃煮+ 茎わかめ漬け+ わかめふりかけ+ 鳴門金時芋けんぴ・¥800-3,500/箱・JR 鳴門駅+全国百貨店流通)", title_ja: "鳴門わかめ加工", romaji: "Wakame Tsukudani", summary_zh: "**鳴門わかめ加工品+佃煮は R1 食派生・1900 年代以降 100+ 年・佃煮+茎わかめ漬け+ふりかけ**(鳴門)。¥800-3,500/箱、JR 鳴門+百貨店。", content_md: "- 立地:**鳴門市**\n- 関連:**R1 食 鳴門わかめ派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202", area_types: ["restaurant_traditional", "shopping_district"], lat: 34.1722, lon: 134.6086, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["wakame_tsukudani"], source: "manual" },
  { slug: "iya-yamasai-iwana", category: "food", sub_type: "tokushima_seibu_food", title_zh: "祖谷山菜+ 岩魚料理(三好市祖谷+ 大歩危・R1 食 祖谷そば 850 年派生・平家落人伝統山中料理+ 山菜天ぷら+ 岩魚塩焼き+ 鹿肉味噌煮+ 「祖谷美人」+「もみじ亭」 老舗 8+ 軒・¥3,500-9,500)", title_ja: "祖谷山菜岩魚", romaji: "Iya Yamasai", summary_zh: "**祖谷山菜+岩魚料理は R1 食 そば 850 年派生・平家落人伝統山中料理・山菜天ぷら+岩魚塩焼+鹿肉味噌煮**(三好祖谷+大歩危)。¥3,500-9,500。", content_md: "- 立地:**三好市祖谷 + 大歩危**\n- 関連:**R1 食 祖谷そば 850 年派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "三好市", lg_code: "36208", area_types: ["restaurant_traditional"], lat: 33.8728, lon: 133.8019, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["iya_yamasai"], source: "manual" },
  { slug: "mima-hand-stretched-somen", category: "food", sub_type: "tokushima_seibu_food", title_zh: "美馬+ 半田手延べそうめん「半田の麺」(美馬郡つるぎ町半田+ 美馬・R1 食 半田そうめん派生・「半田の麺」協同組合認定+ 手延べ太麺特長+ 1 束 ¥350-1,200・道の駅+JR 駅売店)", title_ja: "半田手延べ", romaji: "Handa Hand-Stretched", summary_zh: "**美馬+半田手延べそうめん「半田の麺」は R1 食派生・「半田の麺」協同組合・手延べ太麺特長**(つるぎ半田+美馬)。¥350-1,200/束、道の駅+JR 駅。", content_md: "- 立地:**美馬郡つるぎ町半田 + 美馬市**\n- 関連:**R1 食 半田そうめん派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: "美馬郡", municipality_ja: "つるぎ町", lg_code: "36468", area_types: ["restaurant_traditional", "shopping_district"], lat: 34.0167, lon: 134.0167, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["handa_hand_stretched"], source: "manual" },
  { slug: "awa-odori-chicken-products", category: "food", sub_type: "tokushima_meat", title_zh: "阿波尾鶏加工品+ ハム+ ソーセージ(全県・R1 食 阿波尾鶏 1990 派生・1990 年代以降鶏ガラスープ+ ハム+ ソーセージ+ 鳥肉味噌漬け加工・¥800-3,500/パック・道の駅+全国百貨店流通)", title_ja: "阿波尾鶏加工品", romaji: "Awa Odori Products", summary_zh: "**阿波尾鶏加工品+ハム+ソーセージは R1 食 1990 派生・1990 年代以降鶏ガラ+ハム+ソーセージ+味噌漬け加工**(全県)。¥800-3,500/パック、道の駅+百貨店。", content_md: "- 立地:**全県**\n- 関連:**R1 食 阿波尾鶏 1990 派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201", area_types: ["restaurant_traditional", "shopping_district"], lat: 34.0658, lon: 134.5594, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["awa_odori_products"], source: "manual" },
  // 衣 3
  { slug: "awa-shijira-yukata", category: "fashion", sub_type: "tokushima_dento", title_zh: "阿波しじら織浴衣+ 派生着物(徳島市国府+ 板野・R1 衣 阿波しじら織 1978 派生・1900 年代以降浴衣+ シャツ+ ハンカチ派生・¥9,500-65,000/着・国際 SNS 海外伝統工芸代表)", title_ja: "阿波しじら浴衣", romaji: "Shijira Yukata", summary_zh: "**阿波しじら織浴衣+派生着物は R1 衣 1978 派生・1900 年代以降浴衣+シャツ+ハンカチ**(徳島国府+板野)。¥9,500-65,000/着、海外代表。", content_md: "- 立地:**徳島市国府 + 板野郡**\n- 関連:**R1 衣 阿波しじら織 1978 派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201", area_types: ["industrial_heritage", "shopping_district"], lat: 34.0658, lon: 134.5594, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["shijira_yukata"], source: "manual" },
  { slug: "otani-yaki-small", category: "fashion", sub_type: "tokushima_dento", title_zh: "大谷焼小型品+ アクセサリー(鳴門市大麻町・R1 衣 大谷焼 2003 派生・小型茶器+ ぐい呑+ アクセサリー+ ペンダント・「大谷焼陶器祭」 11 月+ ¥1,500-25,000・国際 SNS 海外伝統陶器代表)", title_ja: "大谷焼小型品", romaji: "Ōtani Small", summary_zh: "**大谷焼小型品+アクセサリーは R1 衣 2003 派生・小型茶器+ぐい呑+アクセサリー+ペンダント・「大谷焼陶器祭」 11 月**(鳴門大麻)。¥1,500-25,000、海外代表。", content_md: "- 立地:**鳴門市大麻町**\n- 関連:**R1 衣 大谷焼 2003 派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202", area_types: ["industrial_heritage", "shopping_district"], lat: 34.1722, lon: 134.6086, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["otani_small"], source: "manual" },
  { slug: "kamiyama-sudachi-design", category: "fashion", sub_type: "tokushima_tobu_clothing", title_zh: "神山町すだち柄デザインアパレル(名西郡神山町・R1 食 すだち+R1 衣 神山クリエイティブ 2010 派生・すだち柄 T シャツ+ ハンカチ+ エコバッグ・「すだち協同組合」+「神山アーティストインレジデンス」コラボ・¥1,500-9,500)", title_ja: "神山すだち柄", romaji: "Kamiyama Sudachi", summary_zh: "**神山町すだち柄デザインアパレルは R1 食 すだち+R1 衣 神山 2010 派生・すだち柄 T+ハンカチ+エコバッグ・協同組合+AIR コラボ**(神山)。¥1,500-9,500。", content_md: "- 立地:**名西郡神山町**\n- 関連:**R1 食 すだち + R1 衣 神山クリエイティブ 2010 派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: "名西郡", municipality_ja: "神山町", lg_code: "36341", area_types: ["shopping_district"], lat: 33.9486, lon: 134.3608, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kamiyama_sudachi"], source: "manual" },
  // 住 3
  { slug: "naruto-tsuruta", category: "lodging", sub_type: "tokushima_tobu_lodging", title_zh: "鳴門大塚国際美術館前+ 海近接ヴィラ(鳴門市鳴門公園+ 大麻町・R1 育 大塚 1998+R1 育 鳴門の渦派生・「リゾートホテルモアナコースト」 1998+ 「アオアヲ」 R1 住派生・オーシャンビューヴィラ・¥22,000-65,000/泊・国際 SNS 海外旅行者代表)", title_ja: "鳴門海近ヴィラ", romaji: "Naruto Coast Villa", summary_zh: "**鳴門大塚国際美術館前+海近接ヴィラは R1 育 1998+R1 育 渦派生・「モアナコースト」 1998+「アオアヲ」派生・オーシャンビューヴィラ**(鳴門公園+大麻)。¥22,000-65,000/泊。", content_md: "- 立地:**鳴門市鳴門公園 + 大麻町**\n- 関連:**R1 育 大塚 1998 + R1 育 鳴門の渦 + R1 住 アオアヲ派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202", area_types: ["accommodation_hotel", "beach_coast"], lat: 34.2497, lon: 134.6486, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["naruto_coast_villa"], source: "manual" },
  { slug: "udatsu-kominka-stay", category: "lodging", sub_type: "tokushima_seibu_lodging", title_zh: "美馬うだつの町並み古民家民泊(美馬市脇町+ つるぎ町貞光・R3 育 美馬うだつ町並み(国伝建 1988)派生・1988 国伝建選定 37+ 年+ 江戸期豪商屋敷リノベ古民家民泊 8+ 軒+ ¥12,000-32,000/泊+ 国際 SNS 海外旅行者代表)", title_ja: "うだつ古民家", romaji: "Udatsu Kominka", summary_zh: "**美馬うだつの町並み古民家民泊は R3 育 国伝建 1988 派生・1988 選定 37+ 年・江戸期豪商屋敷リノベ古民家民泊 8+ 軒**(美馬脇町+つるぎ貞光)。¥12,000-32,000/泊。", content_md: "- 立地:**美馬市脇町 + つるぎ町貞光**\n- 関連:**R3 育 美馬うだつ町並み(国伝建 1988)派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "美馬市", lg_code: "36207", area_types: ["accommodation_ryokan", "history_site_castle"], lat: 34.0500, lon: 134.0167, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["udatsu_kominka"], source: "manual" },
  { slug: "kaiyo-umigame-terrace", category: "lodging", sub_type: "tokushima_nanbu_lodging", title_zh: "海陽町うみがめテラス+ 大里海岸民宿(海部郡海陽町大里+ 海陽・R1 楽 阿南海陽サーフ派生+R1 楽 うみがめ博物館派生・「ホテル白い燈台」 1995+ オーシャンビュー民宿 6+ 軒・¥9,500-22,000/泊・国際 SNS 海外サーファー+ウミガメファン代表)", title_ja: "海陽うみがめテラス", romaji: "Kaiyo Umigame Terrace", summary_zh: "**海陽町うみがめテラス+大里海岸民宿は R1 楽 サーフ+うみがめ派生・「白い燈台」 1995+オーシャンビュー民宿 6+ 軒**(海陽大里+海陽)。¥9,500-22,000/泊。", content_md: "- 立地:**海部郡海陽町大里 + 海陽**\n- 関連:**R1 楽 阿南海陽サーフ + うみがめ博物館派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: "海部郡", municipality_ja: "海陽町", lg_code: "36388", area_types: ["accommodation_ryokan", "beach_coast"], lat: 33.5333, lon: 134.3000, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["kaiyo_umigame_terrace"], source: "manual" },
  // 育 3
  { slug: "udatsu-machinami-1988", category: "culture", sub_type: "tokushima_seibu_culture", title_zh: "美馬うだつの町並み(美馬市脇町+ つるぎ町貞光・1988 国指定重要伝統的建造物群保存地区+ 江戸期豪商屋敷町並み 250+ 年+ 「うだつ」(防火壁) 商家・うだつの町並み観光中心・無料散策・国際 SNS 海外伝統町並みファン代表)", title_ja: "うだつ町並み", romaji: "Udatsu Machinami", summary_zh: "**美馬うだつの町並みは 1988 国伝建選定+江戸期豪商屋敷町並み 250+ 年・「うだつ」(防火壁)商家・うだつの町並み観光中心**(美馬脇町+つるぎ貞光)。無料、海外代表。", content_md: "- 立地:**美馬市脇町 + つるぎ町貞光**\n- 認定:**1988 国指定重要伝統的建造物群保存地区 + 江戸期豪商屋敷町並み 250+ 年 + 「うだつ」(防火壁)商家**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "美馬市", lg_code: "36207", area_types: ["history_site_castle"], lat: 34.0500, lon: 134.0167, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 0, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["udatsu_1988"], source: "manual" },
  { slug: "ai-jukan-1992", category: "culture", sub_type: "tokushima_yoshinogawa_culture", title_zh: "藍住町歴史館・藍の館(板野郡藍住町・1992 開館 33+ 年+ R1 衣 阿波藍 1585+「ジャパンブルー」派生・全国唯一の藍染専門博物館候補+ 江戸期藍商奥村家屋敷リノベ+ 藍染体験+ ¥300・国際 SNS 海外伝統染色代表)", title_ja: "藍住藍の館", romaji: "Ai no Yakata", summary_zh: "**藍住町歴史館・藍の館は 1992 開館 33+ 年・R1 衣 阿波藍 1585 派生・全国唯一の藍染専門博物館候補・奥村家屋敷+藍染体験**(板野藍住)。¥300、海外代表。", content_md: "- 立地:**板野郡藍住町**\n- 関連:**R1 衣 阿波藍 1585 + 「ジャパンブルー」派生**\n- 起源:**1992 開館 33+ 年**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: "板野郡", municipality_ja: "藍住町", lg_code: "36402", area_types: ["museum_art", "industrial_heritage"], lat: 34.1389, lon: 134.4778, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["tuesday"], external_urls: {}, tags: ["ai_no_yakata_1992"], source: "manual" },
  { slug: "naka-aioi-machinami", category: "culture", sub_type: "tokushima_nanbu_culture", title_zh: "那賀町相生町並み+ 山中歴史村(那賀郡那賀町相生・江戸期から那賀川流域山中宿場町 200+ 年+ R1 衣 阿波太布 1973 派生・木地師伝統+ 鹿野川流域古民家・無料散策・国内 SNS 山中文化ファン代表)", title_ja: "相生町並み", romaji: "Aioi Machinami", summary_zh: "**那賀町相生町並み+山中歴史村は江戸期から山中宿場 200+ 年・R1 衣 太布派生・木地師+鹿野川古民家**(那賀相生)。無料、山中ファン代表。", content_md: "- 立地:**那賀郡那賀町相生**\n- 関連:**R1 衣 阿波太布 1973 派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: "那賀郡", municipality_ja: "那賀町", lg_code: "36368", area_types: ["history_site_castle"], lat: 33.9000, lon: 134.3000, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 0, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aioi_machinami"], source: "manual" },
  // 楽 4
  { slug: "naruto-uzunooka-pano", category: "entertainment", sub_type: "tokushima_tobu_entertainment", title_zh: "鳴門ボードウォーク+ 渦の丘大鳴門橋展望台(鳴門市鳴門町・1985 大鳴門橋 R1 行 派生+R1 楽 鳴門公園派生・橋下展望ボードウォーク+ 渦の丘 360 度展望+ R1 楽 渦観潮船発着・無料・国際 SNS 海外旅行者代表)", title_ja: "鳴門ボードウォーク", romaji: "Naruto Boardwalk", summary_zh: "**鳴門ボードウォーク+渦の丘展望台は R1 行 大鳴門橋+R1 楽 鳴門公園派生・橋下展望+360 度展望+渦観潮船発着**(鳴門)。無料、海外代表。", content_md: "- 立地:**鳴門市鳴門町**\n- 関連:**R1 行 大鳴門橋 1985 + R1 楽 鳴門公園派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202", area_types: ["nature_park", "transport_hub"], lat: 34.2497, lon: 134.6486, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 0, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["naruto_boardwalk"], source: "manual" },
  { slug: "ohtsuka-back-stage", category: "entertainment", sub_type: "tokushima_tobu_entertainment", title_zh: "大塚国際美術館裏方ツアー+ システィーナ礼拝堂特別解説(鳴門市・R1 育 大塚国際美術館 1998 派生・年間 50 万人来館+ 全国アート観光客 No.1 候補+ システィーナ礼拝堂全壁面複製ツアー+ ガイド付き 90 分・¥3,300+ガイド ¥1,000)", title_ja: "大塚裏方ツアー", romaji: "Ohtsuka Back Stage", summary_zh: "**大塚国際美術館裏方ツアー+システィーナ特別解説は R1 育 1998 派生・年 50 万人来館+全国アート観光 No.1 候補+システィーナ全壁面複製+90 分**(鳴門)。¥3,300+¥1,000。", content_md: "- 立地:**鳴門市**\n- 関連:**R1 育 大塚国際美術館 1998 派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202", area_types: ["museum_art"], lat: 34.1722, lon: 134.6086, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 30, closed_days: ["monday"], external_urls: {}, tags: ["ohtsuka_back"], source: "manual" },
  { slug: "naka-suisha", category: "entertainment", sub_type: "tokushima_nanbu_entertainment", title_zh: "那賀町水車郷+ 宮浜公園(那賀郡那賀町相生+ 鷲敷・R1 衣 阿波太布+R2 育 那賀町相生町並み派生・1990 年代以降水車郷整備+ 那賀川川辺公園+ 鮎釣り場・無料散策+ 川泳ぎ場・国内 SNS ファミリー観光客代表)", title_ja: "那賀水車郷", romaji: "Naka Suisha", summary_zh: "**那賀町水車郷+宮浜公園は R1 衣 太布+R2 育 相生町並み派生・1990 年代以降水車郷整備+川辺公園+鮎釣り**(那賀相生+鷲敷)。無料+川泳ぎ、ファミリー代表。", content_md: "- 立地:**那賀郡那賀町相生 + 鷲敷**\n- 関連:**R1 衣 阿波太布 + R2 育 那賀町相生町並み派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: "那賀郡", municipality_ja: "那賀町", lg_code: "36368", area_types: ["nature_park"], lat: 33.9000, lon: 134.3000, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 0, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["naka_suisha"], source: "manual" },
  { slug: "udatsu-machinami-fest", category: "entertainment", sub_type: "tokushima_seibu_entertainment", title_zh: "美馬うだつの町並み夜景祭+ 「うだつ茂町並み雛祭」(美馬市脇町・R2 育 うだつ町並み 1988 派生・「うだつ」町並みライトアップ・春雛祭(2 月-3 月)+ 秋灯篭祭(10 月)・参加無料+ 国内 SNS 春秋夜景代表)", title_ja: "うだつ夜景祭", romaji: "Udatsu Night Fest", summary_zh: "**美馬うだつの町並み夜景祭+「うだつ茂町並み雛祭」は R2 育 1988 派生・町並みライトアップ・春雛祭(2-3 月)+秋灯篭祭(10 月)**(美馬脇町)。参加無料。", content_md: "- 立地:**美馬市脇町**\n- 関連:**R2 育 美馬うだつの町並み 1988 派生**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "美馬市", lg_code: "36207", area_types: ["history_site_castle"], lat: 34.0500, lon: 134.0167, season_start: "2026-02-15", season_end: "2026-03-31", event_start: null, event_end: null, price_tier: 0, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["udatsu_night_fest"], source: "manual" },
  // 行 2
  { slug: "kotoden-tokushima-station", category: "transport", sub_type: "tokushima_terminal", title_zh: "ことでん徳島駅+ 阿波シャトルバス(徳島市寺島本町+ 全県・R1 行 ことでん志度線徳島駅併設+ 1909 開業 116+ 年+ 全県阿波シャトルバス 12 路線+ R1 行 JR 徳島駅徒歩 1 分・¥190-510/片道)", title_ja: "ことでん徳島", romaji: "Kotoden Tokushima", summary_zh: "**ことでん徳島駅+阿波シャトルバスは R1 行 志度線併設・1909 開業 116+ 年・全県シャトル 12 路線・JR 徳島徒歩 1 分**(徳島寺島+全県)。¥190-510/片道。", content_md: "- 立地:**徳島市寺島本町 + 全県**\n- 関連:**R1 行 ことでん志度線併設**\n- 起源:**1909 開業 116+ 年**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "徳島市", lg_code: "36201", area_types: ["transport_hub"], lat: 34.0658, lon: 134.5594, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kotoden_tokushima_1909"], source: "manual" },
  { slug: "naruto-shi-bus", category: "transport", sub_type: "tokushima_subway", title_zh: "鳴門市バス+ 大鳴門橋シャトル(鳴門市・1955 鳴門市バス開業 70+ 年+ R1 行 大鳴門橋+大塚国際美術館アクセス+ ¥220-510/片道+ 1 日 30 便+ 国際 SNS 海外旅行者代表)", title_ja: "鳴門市バス", romaji: "Naruto Bus", summary_zh: "**鳴門市バス+大鳴門橋シャトルは 1955 開業 70+ 年・R1 行 大鳴門橋+大塚国際美術館アクセス+1 日 30 便**(鳴門)。¥220-510/片道、海外代表。", content_md: "- 立地:**鳴門市**\n- 起源:**1955 鳴門市バス開業 70+ 年**\n- 関連:**R1 行 大鳴門橋 + 大塚国際美術館アクセス**", region: "shikoku", prefecture_ja: "徳島県", gun_ja: null, municipality_ja: "鳴門市", lg_code: "36202", area_types: ["transport_hub"], lat: 34.1722, lon: 134.6086, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["naruto_bus_1955"], source: "manual" },
];

seedMain(rows, "tokushima-r2");
