// Seed 63 筆北海道 · 樂類 條目 → public.japan_entries。
//
// 依 docs/japan-prep-plan.md §11.1 C1-C7 清單。內容為編輯整理,
// admin 上線後可在 /admin/japan-entries 逐筆微調。
//
// 注意:
//   - season_start / season_end 為 DATE,以 2000 年為「任何年」語意佔位。
//     雪季橫跨年底的寫成 2000-12-01 → 2001-04-30(UI 用 month-day 比對)。
//   - lat/lon 為概略值,不是精確場地定位。
//   - external_urls 為已知官方/觀光協會網址,若 admin 發現失效可直接改。
//   - 全部 upsert,slug 當 conflict key,重跑安全。
//
// 日期來源驗證(2026-04 Level-1 人工查核):
//   已驗證: 五稜郭(goryokaku-tower.co.jp + tenki.jp), 松前(Wikipedia),
//          二十間道路(Wikipedia 2019-2023 平均), トマム(snowtomamu.jp),
//          ルスツ(rusutsu.com), Greenland(h-greenland.com),
//          函館港まつり(minatomatsuri.org), 四季彩(shikisainooka.jp),
//          白色燈樹節(Wikipedia), 函館 Xmas(Wikipedia),
//          富良野滑雪場(Wikipedia)。
//   估算中(查無官方明示,以普遍資料取值): 黑岳紅葉、定山溪紅葉、
//          北龍ひまわり、釧路道新花火、ニセコ/キロロ 具體雪期。
//   前端會於條目頁加註「日期為編輯整理,以官方公告為準」。
//
// Usage:
//   npm run seed:japan-hokkaido:dry
//   npm run seed:japan-hokkaido

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "sakura"
  | "momiji"
  | "ski_season"
  | "firework_festival"
  | "illumination"
  | "flower_field"
  | "theme_park"
  | "aquarium_zoo"
  | "sports_spectate"
  | "music_festival";

interface SeedRow {
  slug: string;
  category: "entertainment";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "hokkaido";
  prefecture_ja: "北海道";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ── sakura (C1 · 3 筆) ──────────────────────────────
  {
    slug: "hokkaido-goryokaku-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "五稜郭公園 櫻花",
    title_ja: "五稜郭公園の桜",
    romaji: "Goryōkaku Kōen no Sakura",
    summary_zh:
      "日本最北端的星形稜堡,約 1,600 株染井吉野開到整圈星形城郭。滿開時從五稜郭塔俯瞰整片粉紅五角星,是北海道最具辨識度的賞櫻地之一。",
    content_md:
      "- 開花:約 4 月中旬 ~ 5 月初(2026 年預測滿開 4/20)\n- 夜間電飾「五稜星の夢」:滿開後約 2 週每晚 19:00-21:00(2026 年為 4/21 ~ 5/6)\n- 免費,24 小時開放\n- 最佳觀景:五稜郭塔展望台(收費 ¥1,000)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["urban", "castle_town"],
    lat: 41.7971,
    lon: 140.7569,
    season_start: "2000-04-18",
    season_end: "2000-05-06",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.goryokaku-tower.co.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E4%BA%94%E7%A8%9C%E9%83%AD",
    },
    tags: ["night_illumination", "castle", "top_100_sakura"],
    source: "manual",
  },
  {
    slug: "hokkaido-matsumae-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "松前公園 櫻花",
    title_ja: "松前公園の桜",
    romaji: "Matsumae Kōen no Sakura",
    summary_zh:
      "北海道唯一城下町 · 松前藩本家,日本櫻花名所 100 選。園內約 8,000-10,000 株、250 品種的櫻花,從早開到晚櫻可連續賞約 2 個月。松前町獨有品種「マツマエハヤザキ」「ベニユタカ」。",
    content_md:
      "- 開花:約 4 月中旬 ~ 5 月下旬(早中晚品種接力)\n- 「松前さくらまつり」與滿開期同步\n- 免費入園,松前城資料館另收費\n- 由函館市區車程約 1.5 小時,觀光巴士不多,建議自駕\n- 松前町自訂「桜前線本道上陸標準木」在松前城資料館前",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "松前",
    municipality_ja: "松前町",
    lg_code: "01331",
    area_types: ["rural", "castle_town", "coastal"],
    lat: 41.4319,
    lon: 140.1161,
    season_start: "2000-04-15",
    season_end: "2000-05-25",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E6%9D%BE%E5%89%8D%E5%85%AC%E5%9C%92",
    },
    tags: ["top_100_sakura", "castle", "multiple_varieties"],
    source: "manual",
  },
  {
    slug: "hokkaido-shizunai-nijukken-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "靜內二十間道路 櫻花並木",
    title_ja: "静内二十間道路桜並木",
    romaji: "Shizunai Nijūkken Dōro Sakura-namiki",
    summary_zh:
      "綿延 7 公里、寬 36 公尺(20 間),兩側 2,122 株蝦夷山櫻、霞櫻、深山櫻的筆直道路,為日本の道 100 選。日高牧馬地貌+櫻花隧道,畫面極具北海道風情。",
    content_md:
      "- 開花:近 5 年(2019-2023)平均 4/26、滿開 4/30\n- 長期平均(1981-2023)開花 5/3、滿開 5/6,暖化後整體提早約一週\n- 品種:エゾヤマザクラ、カスミザクラ、ミヤマザクラ 3 種共 2,122 株\n- 免費,全日開放。道路可通車,推薦平日避開人潮\n- 「しずない桜まつり」滿開週舉辦,來場約 20 萬人\n- 建議順遊:浦河町、樣似町的日高山脈海岸線",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "新ひだか町",
    lg_code: "01610",
    area_types: ["rural", "coastal"],
    lat: 42.3631,
    lon: 142.3703,
    season_start: "2000-04-26",
    season_end: "2000-05-10",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E4%BA%8C%E5%8D%81%E9%96%93%E9%81%93%E8%B7%AF%E6%A1%9C%E4%B8%A6%E6%9C%A8",
    },
    tags: ["top_100_road", "horse_ranch", "long_avenue"],
    source: "manual",
  },

  // ── momiji (C2 · 2 筆) ──────────────────────────────
  {
    slug: "hokkaido-daisetsuzan-kurodake-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "大雪山黑岳 紅葉",
    title_ja: "大雪山黒岳の紅葉",
    romaji: "Daisetsuzan Kurodake no Kōyō",
    summary_zh:
      "日本全境最早紅葉,約 9 月中從稜線往下染。搭層雲峡黑岳纜車+升降機登上 7 合目,俯瞰整片紅黃翠綠漸層,是「日本一早い紅葉」的代名詞。",
    content_md:
      "- 紅葉:約 9 月 10 日 ~ 10 月 10 日(高所先染)\n- 層雲峡至黑岳纜車:來回約 ¥2,400\n- 7 合目之上建議登山裝備,稜線風大氣溫低\n- 同區建議順遊:銀河・流星の滝、層雲峡溫泉",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川",
    municipality_ja: "上川町",
    lg_code: "01457",
    area_types: ["mountain", "rural"],
    lat: 43.705,
    lon: 142.885,
    season_start: "2000-09-10",
    season_end: "2000-10-10",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.rinyu.co.jp/kurodake/",
    },
    tags: ["earliest_momiji", "ropeway", "mountain_hike"],
    source: "manual",
  },
  {
    slug: "hokkaido-jozankei-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "定山溪 紅葉",
    title_ja: "定山渓の紅葉",
    romaji: "Jōzankei no Kōyō",
    summary_zh:
      "札幌市後花園,從市中心車程約 1 小時的溫泉峽谷。豐平峽水壩+二見公園的紅葉倒映在翡翠綠水面上,秋日泡湯配紅葉是北海道的都會近郊經典。",
    content_md:
      "- 紅葉:約 9 月 25 日 ~ 10 月 20 日\n- 定山溪観光協会官方 Kappa Bus 從札幌站發車\n- 免費景點:二見公園、月見橋、ヘリパッド展望\n- 溫泉旅館可當日泡湯(日帰り温泉)約 ¥1,500",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["onsen_town", "mountain"],
    lat: 42.9656,
    lon: 141.1731,
    season_start: "2000-09-25",
    season_end: "2000-10-20",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://jozankei.jp/",
    },
    tags: ["onsen", "day_trip_from_sapporo", "valley"],
    source: "manual",
  },

  // ── ski_season (C3 · 5 筆) ──────────────────────────
  {
    slug: "hokkaido-niseko-ski",
    category: "entertainment",
    sub_type: "ski_season",
    title_zh: "二世谷(ニセコ) 滑雪區",
    title_ja: "ニセコ",
    romaji: "Niseko",
    summary_zh:
      "全球粉雪聖地。Niseko United 四大滑雪場共用 lift pass,年均積雪 14 公尺。12 月初~5 月初營業,1-2 月最佳粉雪期。",
    content_md:
      "- 四大場域:Grand Hirafu、Niseko Village、Annupuri、Hanazono,一張 Niseko United Pass 通用\n- 雪期:12 月初 ~ 5 月初(Annupuri 最晚收山)\n- 新千歲機場巴士約 3 小時;札幌站巴士 2.5 小時\n- 台/港澳旅客集中,繁中招牌多;英語通用\n- 住宿旺季(1-2 月)需至少半年前訂",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田",
    municipality_ja: "倶知安町",
    lg_code: "01400",
    area_types: ["mountain", "rural"],
    lat: 42.805,
    lon: 140.6867,
    season_start: "2000-12-01",
    season_end: "2001-05-05",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 180,
    closed_days: [],
    external_urls: {
      official: "https://www.niseko.ne.jp/",
    },
    tags: ["powder_snow", "english_ok", "lift_pass_united"],
    source: "manual",
  },
  {
    slug: "hokkaido-furano-ski",
    category: "entertainment",
    sub_type: "ski_season",
    title_zh: "富良野滑雪場",
    title_ja: "富良野スキー場",
    romaji: "Furano Ski Resort",
    summary_zh:
      "道央老牌大型滑雪場,FIS Alpine World Cup 賽事場地。比二世谷安靜、家庭友善,23 條雪道初中高 4:4:2。富良野 zone 雪期 11 月下旬 ~ 5 月上旬。",
    content_md:
      "- 雪期:富良野 zone 11 月下旬 ~ 5 月上旬;北の峰 zone 12 月中旬 ~ 3 月下旬\n- 雪道 23 條,最長 4,000m,最大斜度 34°\n- New Furano Prince Hotel 位於山腳,ski-in/ski-out\n- 新千歲機場直達巴士約 2.5 小時\n- 北の峰第 1 高速 lift 與プリンスロマンス lift 有夜滑運行\n- 夏季纜車 6 月中旬 ~ 10 月中旬(空中散策)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "富良野市",
    lg_code: "01229",
    area_types: ["mountain"],
    lat: 43.3567,
    lon: 142.3875,
    season_start: "2000-11-25",
    season_end: "2001-05-05",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      official: "https://www.princehotels.com/ski/furano/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E5%AF%8C%E8%89%AF%E9%87%8E%E3%82%B9%E3%82%AD%E3%83%BC%E5%A0%B4",
    },
    tags: ["family_friendly", "world_cup_course", "night_ski"],
    source: "manual",
  },
  {
    slug: "hokkaido-rusutsu-ski",
    category: "entertainment",
    sub_type: "ski_season",
    title_zh: "Rusutsu Resort(留壽都)",
    title_ja: "ルスツリゾート",
    romaji: "Rusutsu Resort",
    summary_zh:
      "北海道最大單一滑雪場,3 座山 37 條雪道。家庭渡假村型,含樹下樹林滑雪(tree-run)區豐富。冬季到 3 月底,夏季遊樂園 4/29 起。",
    content_md:
      "- 冬季雪期:11 月下旬 ~ 3 月 31 日(2025-2026 季確認 3/31 closed)\n- 夏季遊樂園:4 月 29 日 ~ 10 月下旬(2026 年 4/29 開)\n- 三山:West Mountain、East Mountain、Mt. Isola\n- 新千歲機場巴士約 2 小時\n- tree-run 自由度高為愛好者最愛",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田",
    municipality_ja: "留寿都村",
    lg_code: "01397",
    area_types: ["mountain", "rural"],
    lat: 42.7383,
    lon: 140.8486,
    season_start: "2000-11-25",
    season_end: "2001-03-31",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 120,
    closed_days: [],
    external_urls: {
      official: "https://rusutsu.com/",
    },
    tags: ["tree_run", "largest_single_resort", "family_friendly"],
    source: "manual",
  },
  {
    slug: "hokkaido-tomamu-ski",
    category: "entertainment",
    sub_type: "ski_season",
    title_zh: "星野 TOMAMU(トマム)",
    title_ja: "星野リゾート トマム",
    romaji: "Hoshino Resorts Tomamu",
    summary_zh:
      "星野リゾート旗艦度假村。冬季滑雪+「霧氷テラス」雲海纜車,住 The Tower 或 RISONARE 全包式體驗。2025-2026 雪期 12/1 ~ 4/5。",
    content_md:
      "- 冬季雪期:12 月 1 日 ~ 翌年 4 月 5 日(2025-2026 確切)\n- 代表景點「雲海 Terrace」夏秋季限定、纜車清晨 5:00 起運行\n- 冬季特有「霧氷 Terrace」在滑雪區山頂\n- 占冠駅有 JR 石勝線,新千歲約 1.5 小時\n- 村內無便利商店,補給仰賴度假村內\n- 需預約溫泉「木林の湯」",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "勇払",
    municipality_ja: "占冠村",
    lg_code: "01463",
    area_types: ["mountain", "rural", "depopulated"],
    lat: 43.0761,
    lon: 142.6811,
    season_start: "2000-12-01",
    season_end: "2001-04-05",
    event_start: null,
    event_end: null,
    price_tier: 5,
    booking_window_days: 180,
    closed_days: [],
    external_urls: {
      official: "https://www.snowtomamu.jp/winter/",
    },
    tags: ["luxury_resort", "unkai_terrace", "hoshino_resorts"],
    source: "manual",
  },
  {
    slug: "hokkaido-kiroro-ski",
    category: "entertainment",
    sub_type: "ski_season",
    title_zh: "Kiroro Resort(キロロ)",
    title_ja: "キロロリゾート",
    romaji: "Kiroro Resort",
    summary_zh:
      "小樽近郊、粉雪質感最被推崇的中型度假村。Club Med Kiroro Peak / Grand 相鄰。11 月下旬 ~ 5 月上旬,雪期超長。",
    content_md:
      "- 雪期:11 月下旬 ~ 5 月初(北海道最長之一)\n- 小樽駅接駁約 45 分鐘,新千歲約 2 小時\n- Club Med Kiroro 全包式為近年熱門\n- 夜間滑雪、樹林滑雪皆完整",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "余市",
    municipality_ja: "赤井川村",
    lg_code: "01409",
    area_types: ["mountain", "rural"],
    lat: 43.0589,
    lon: 140.9586,
    season_start: "2000-11-25",
    season_end: "2001-05-05",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 180,
    closed_days: [],
    external_urls: {
      official: "https://www.kiroro.co.jp/",
    },
    tags: ["powder_snow", "club_med", "long_season"],
    source: "manual",
  },

  // ── firework_festival (C4 · 2 筆) ───────────────────
  {
    slug: "hokkaido-doshin-kushiro-hanabi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "道新釧路 大花火大會",
    title_ja: "道新花火大会 in 釧路",
    romaji: "Dōshin Hanabi Taikai in Kushiro",
    summary_zh:
      "道東夏季壓軸、釧路港灣畔約 10,000 發煙火。音樂同步的大型 Star Mine 是一大特色,海風涼爽 + 夜霧氛圍絕佳。",
    content_md:
      "- 每年 8 月 ~ 下旬之間一個週末舉辦,正式日期約 6 月公告\n- 會場:釧路港(幣舞橋~ぬさまい橋一帶)\n- 付費觀賞席需要事前購票\n- 同期可訪幣舞橋夕景、和商市場",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "釧路市",
    lg_code: "01206",
    area_types: ["coastal", "urban"],
    lat: 42.9858,
    lon: 144.3806,
    season_start: "2000-08-01",
    season_end: "2000-08-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["music_sync", "port_view", "summer"],
    source: "manual",
  },
  {
    slug: "hokkaido-hakodate-minato-hanabi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "函館港まつり 花火大會",
    title_ja: "函館港まつり 花火大会",
    romaji: "Hakodate Minato Matsuri Hanabi Taikai",
    summary_zh:
      "函館夏日三大行事之一,道新花火大會。8 月 1 日固定開幕日夜 19:45-20:50 約 1 小時煙火。搭配翌日「ワッショイはこだて」遊行,整週熱鬧。赤レンガ倉庫前觀賞最佳。",
    content_md:
      "- 道新花火大會:8 月 1 日 19:45-20:50(雨天預備日 8 月 5 日)\n- 港まつり整體期間:8 月 1 日 ~ 8 月 5 日\n- 會場:函館港(豊川埠頭付近)\n- 赤レンガ倉庫、十字街、元町一帶都能看到\n- 建議傍晚先到元町觀夜景,再往港邊走",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["urban", "coastal", "castle_town"],
    lat: 41.7833,
    lon: 140.7283,
    season_start: "2000-08-01",
    season_end: "2000-08-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.hakodate-minatomatsuri.org/",
    },
    tags: ["free", "port_view", "matsuri_week"],
    source: "manual",
  },

  // ── illumination (C5 · 2 筆) ────────────────────────
  {
    slug: "hokkaido-sapporo-white-illumi",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "札幌白色燈樹節",
    title_ja: "さっぽろホワイトイルミネーション",
    romaji: "Sapporo White Illumination",
    summary_zh:
      "日本最早的大規模都市聖誕燈飾(1981 年起,最初 1,048 顆燈泡)。大通公園、駅前通、南一条通三大會場同步,11 月中開幕直到翌年 2 月中。",
    content_md:
      "- 大通公園 1 丁目:11 月中 ~ 翌年 2 月 11-12 日(約 2.5 個月)\n- 大通公園 2-12 丁目:11 月下旬 ~ 12 月 25 日(約 4 週)\n- 駅前通:11 月中 ~ 翌年 2 月 11-12 日\n- 南一条通:11 月下旬 ~ 翌年 2 月 14 日(約 80 天)\n- 點燈時間:16:30 ~ 22:30;12/23-25 延至深夜\n- 與 2 月「さっぽろ雪まつり」時段部分重疊\n- 免費",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0599,
    lon: 141.3469,
    season_start: "2000-11-22",
    season_end: "2001-02-14",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://white-illumination.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%81%95%E3%81%A3%E3%81%BD%E3%82%8D%E3%83%9B%E3%83%AF%E3%82%A4%E3%83%88%E3%82%A4%E3%83%AB%E3%83%9F%E3%83%8D%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3",
    },
    tags: ["free", "longest_winter_lights", "downtown"],
    source: "manual",
  },
  {
    slug: "hokkaido-hakodate-christmas-fantasy",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "函館聖誕幻想",
    title_ja: "はこだてクリスマスファンタジー",
    romaji: "Hakodate Christmas Fantasy",
    summary_zh:
      "12 月 1 日 ~ 25 日每晚,金森赤レンガ倉庫前海上立起 20m+ 聖誕樹。樹來自姊妹市加拿大 Nova Scotia 州 Halifax 每年捐贈(1998 年起,靈感取自紐約洛克斐勒中心)。",
    content_md:
      "- 期間:12 月 1 日 ~ 25 日每日舉辦\n- 會場:金森赤レンガ倉庫ベイエリア\n- 點燈:16:30 ~ 17:45 + 18:00 ~ 02:00(12/22-24 與週末延至 07:00,12/25 僅到 20:00)\n- 18:00 點燈儀式同時每晚施放煙火\n- 本樹:加拿大 Halifax 捐贈(2003、2019、2023 因運輸問題改用道內蝦夷松)\n- 同區:元町教會群、函館山夜景",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["urban", "coastal"],
    lat: 41.7658,
    lon: 140.7253,
    season_start: "2000-12-01",
    season_end: "2000-12-25",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.hakodatexmas.com/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%81%AF%E3%81%93%E3%81%A0%E3%81%A6%E3%82%AF%E3%83%AA%E3%82%B9%E3%83%9E%E3%82%B9%E3%83%95%E3%82%A1%E3%83%B3%E3%82%BF%E3%82%B8%E3%83%BC",
    },
    tags: ["free", "sister_city_tree", "nightly_fireworks"],
    source: "manual",
  },

  // ── flower_field (C6 · 3 筆) ────────────────────────
  {
    slug: "hokkaido-farm-tomita-lavender",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "富田農場 薰衣草",
    title_ja: "ファーム富田",
    romaji: "Farm Tomita",
    summary_zh:
      "日本最知名的薰衣草農場,1958 年建園。約 15 公頃薰衣草田加上其他季節花卉接力。7 月中旬「紫花 + 黃花 + 紅花」彩虹花田是北海道明信片畫面。免費入園。",
    content_md:
      "- 花期:4 月中(番紅花)→ 5 月(水仙、鬱金香)→ 6 月(玫瑰、牡丹)→ 6 月下旬 ~(薰衣草開花)→ 10 月\n- 薰衣草滿開:約 7 月 10-25 日\n- 免費入園,停車免費\n- 代表花田:Lavender Traditional、森の彩り、彩り、Spring Colors、Autumn Colors 等\n- 園內有薰衣草冰淇淋、哈密瓜冷餐\n- JR 富良野線「ラベンダー畑駅」夏季限定徒步 7 分",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "空知",
    municipality_ja: "中富良野町",
    lg_code: "01461",
    area_types: ["rural"],
    lat: 43.4178,
    lon: 142.4358,
    season_start: "2000-05-01",
    season_end: "2000-10-31",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.farm-tomita.co.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0%E5%AF%8C%E7%94%B0",
    },
    tags: ["free", "lavender_peak_mid_july", "famous"],
    source: "manual",
  },
  {
    slug: "hokkaido-shikisai-no-oka-biei",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "四季彩之丘",
    title_ja: "四季彩の丘",
    romaji: "Shikisai-no-oka",
    summary_zh:
      "美瑛「青池」附近的大型花田,15 公頃坡地上依季節 30+ 品種排出彩色條紋。冬季變銀白,可搭雪上摩托車。",
    content_md:
      "- 花期:4 月下旬 ~ 10 月下旬(7-8 月最華麗)\n- 冬季(12-3 月)積雪,可玩雪上摩托車\n- 入園付「維護協力金」¥500\n- 拖拉機巴士(Norokko)園內繞一圈 ¥600\n- JR 美瑛駅搭計程車約 10 分鐘",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川",
    municipality_ja: "美瑛町",
    lg_code: "01459",
    area_types: ["rural"],
    lat: 43.5636,
    lon: 142.4775,
    season_start: "2000-04-25",
    season_end: "2000-10-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.shikisainooka.jp/",
    },
    tags: ["hillside_patchwork", "winter_snowmobile", "biei"],
    source: "manual",
  },
  {
    slug: "hokkaido-hokuryu-sunflower",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "北龍町 向日葵之里",
    title_ja: "北竜町ひまわりの里",
    romaji: "Hokuryū-chō Himawari no Sato",
    summary_zh:
      "日本最大向日葵田 · 23 公頃約 150 萬株。7 月下旬 ~ 8 月中旬,整片金黃在空知内陸的小鎮一望無際,人口 1,700 的過疎地因這一週年年吸引 30 萬觀光客。",
    content_md:
      "- 花期:7 月 20 日 ~ 8 月 20 日\n- 免費入園(迷宮活動付費 ¥300)\n- 札幌車程約 2 小時\n- 同期:「ひまわりまつり」期間有地方美食攤販\n- 午後光線最適合拍照",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "雨竜",
    municipality_ja: "北竜町",
    lg_code: "01437",
    area_types: ["rural", "depopulated"],
    lat: 43.9661,
    lon: 141.7683,
    season_start: "2000-07-20",
    season_end: "2000-08-20",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://portal.hokuryu.info/himawari/",
    },
    tags: ["largest_in_japan", "free", "obscure_town"],
    source: "manual",
  },

  // ── theme_park (C7 · 1 筆) ──────────────────────────
  {
    slug: "hokkaido-greenland-sunagawa",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "北海道 Greenland",
    title_ja: "北海道グリーンランド",
    romaji: "Hokkaidō Greenland",
    summary_zh:
      "北海道最大的遊樂園,岩見沢+砂川之間。30+ 遊樂設施、大型摩天輪 90 公尺是北海道最高。4 月下旬 ~ 11 月上旬營業(2026 年 4/24 開園),冬季閉園。",
    content_md:
      "- 營業:4 月下旬 ~ 11 月上旬(冬季閉園,2026 年 4/24 開)\n- 入園 ¥1,200,一日 passport ¥3,900\n- 札幌駅搭 JR 函館本線約 1 小時至岩見沢,轉計程車 15 分\n- 夏季週末有煙火活動\n- 相鄰「ホテルサンプラザ」有泳池溫泉",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "岩見沢市",
    lg_code: "01210",
    area_types: ["rural"],
    lat: 43.2147,
    lon: 141.7989,
    season_start: "2000-04-24",
    season_end: "2000-11-05",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.h-greenland.com/",
    },
    tags: ["ferris_wheel", "family", "seasonal_close_winter"],
    source: "manual",
  },

  // ═══ Phase 1.1 擴充(18→33 筆)2026-04 ═════════════════

  // ── sakura 追加 3 筆 ────────────────────────────────
  {
    slug: "hokkaido-maruyama-park-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "円山公園 櫻花",
    title_ja: "円山公園の桜",
    romaji: "Maruyama Kōen no Sakura",
    summary_zh:
      "札幌市中心最經典的賞櫻名所,與北海道神宮相連。68.8 公頃的原生林公園,蝦夷山櫻為主、1875 年起由福玉仙吉在神社參道植 150 株起家,如今全園 1,400+ 株。",
    content_md:
      "- 開花:約 4 月中旬 ~ 下旬(2026 札幌 tenki.jp 預測 開花 4/18 滿開 4/23)\n- 免費,24 小時開放\n- 北海道神宮內亦有大量櫻花,建議一併徒步\n- 地下鐵東西線「円山公園駅」徒步 5 分\n- 園內設有「円山原始林」、圓山動物園",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0531,
    lon: 141.3239,
    season_start: "2000-04-18",
    season_end: "2000-04-30",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E5%86%86%E5%B1%B1%E5%85%AC%E5%9C%92_(%E6%9C%AD%E5%B9%8C%E5%B8%82)",
      tenki: "https://tenki.jp/sakura/1/1/",
    },
    tags: ["free", "downtown_sapporo", "hokkaido_jingu"],
    source: "manual",
  },
  {
    slug: "hokkaido-moerenuma-park-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "モエレ沼公園 櫻花",
    title_ja: "モエレ沼公園の桜",
    romaji: "Moerenuma Kōen no Sakura",
    summary_zh:
      "彫刻家 Isamu Noguchi(イサム・ノグチ)全面規劃的大地藝術公園,「サクラの森」約 2,600 株櫻花環繞玻璃金字塔 HIDAMARI、海噴水、モエレ山。",
    content_md:
      "- 開花:約 5 月上旬 ~ 中旬(比札幌市中心稍晚)\n- サクラの森:約 2,600 株(園內為エゾヤマザクラ主)\n- 免費入園,停車免費\n- 地下鐵東豐線「環状通東駅」轉中央巴士約 25 分\n- 特色設施:玻璃金字塔 HIDAMARI(32.3m 高)、海の噴水、モエレ山(52m)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.1267,
    lon: 141.4236,
    season_start: "2000-05-01",
    season_end: "2000-05-15",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://moerenumapark.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%83%A2%E3%82%A8%E3%83%AC%E6%B2%BC%E5%85%AC%E5%9C%92",
    },
    tags: ["free", "isamu_noguchi", "art_park"],
    source: "manual",
  },
  {
    slug: "hokkaido-hakodate-park-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "函館公園 櫻花",
    title_ja: "函館公園の桜",
    romaji: "Hakodate Kōen no Sakura",
    summary_zh:
      "北海道最早的西洋式都市公園(1879 年開園)。5 月初期約 400 株染井吉野、蝦夷山櫻,位於函館山山麓,夜間打燈配函館山夜景。",
    content_md:
      "- 開花:約 4 月下旬 ~ 5 月初(2026 函館 tenki.jp 預測 4/18 開、4/20 滿)\n- 夜間點燈:滿開期間週末 18:00-21:00\n- 免費,24 小時開放\n- 市電「青柳町駅」徒步 10 分\n- 園內設函館市博物館、舊函館博物館(明治建築)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["urban", "castle_town"],
    lat: 41.7594,
    lon: 140.7217,
    season_start: "2000-04-18",
    season_end: "2000-05-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E5%87%BD%E9%A4%A8%E5%85%AC%E5%9C%92",
      tenki: "https://tenki.jp/sakura/1/1/",
    },
    tags: ["free", "oldest_western_park", "night_illumination"],
    source: "manual",
  },

  // ── momiji 追加 2 筆 ────────────────────────────────
  {
    slug: "hokkaido-sounkyo-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "層雲峽 紅葉",
    title_ja: "層雲峡の紅葉",
    romaji: "Sōunkyō no Kōyō",
    summary_zh:
      "大雪山國立公園內 24 公里長的峽谷,黑岳纜車+銀河・流星の滝(日本の滝百選)+紅葉谷。9 月下旬從上往下染,10 月上旬達峽谷底。",
    content_md:
      "- 紅葉:約 9 月下旬 ~ 10 月中旬(高所先染,峽谷底約晚 2 週)\n- 看點:黑岳纜車山頂、銀河の滝、流星の滝、紅葉谷\n- 層雲峽温泉可日帰り泡湯\n- 旭川駅巴士約 2 小時,JR 上川駅巴士 30 分\n- 冬季(1-3 月)同區有「層雲峽冰瀑まつり」",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川",
    municipality_ja: "上川町",
    lg_code: "01457",
    area_types: ["mountain", "onsen_town"],
    lat: 43.7239,
    lon: 142.9542,
    season_start: "2000-09-20",
    season_end: "2000-10-15",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.sounkyo.net/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E5%B1%A4%E9%9B%B2%E5%B3%A1%E6%B8%A9%E6%B3%89",
    },
    tags: ["waterfall", "gorge", "onsen"],
    source: "manual",
  },
  {
    slug: "hokkaido-onuma-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "大沼國定公園 紅葉",
    title_ja: "大沼国定公園の紅葉",
    romaji: "Ōnuma Kokutei Kōen no Kōyō",
    summary_zh:
      "日本紅葉百選(2010 年選定),函館北 16 公里。大沼+小沼+蓴菜沼 3 湖圍繞駒ヶ岳活火山,湖中 126 座小島以遊步道橋連接。10 月中 ~ 11 月上最佳。",
    content_md:
      "- 紅葉:約 10 月中旬 ~ 11 月上旬\n- 遊步道:大島之道 50 分、島巡之道 25 分\n- 自行車租借繞湖一圈(14km)、遊覽船 30 分\n- JR 函館本線「大沼公園駅」徒步 3 分\n- 同區:駒ヶ岳登山(需事前登錄)、大沼ビール\n- 日本新三景(1915)、拉姆薩爾濕地公約(2012)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "茅部",
    municipality_ja: "七飯町",
    lg_code: "01337",
    area_types: ["rural", "mountain"],
    lat: 41.9967,
    lon: 140.6772,
    season_start: "2000-10-15",
    season_end: "2000-11-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E5%A4%A7%E6%B2%BC%E5%9B%BD%E5%AE%9A%E5%85%AC%E5%9C%92",
    },
    tags: ["top_100_momiji", "lake", "volcano_view"],
    source: "manual",
  },

  // ── ski_season 追加 1 筆 ────────────────────────────
  {
    slug: "hokkaido-asahidake-ski",
    category: "entertainment",
    sub_type: "ski_season",
    title_zh: "旭岳(Asahidake)",
    title_ja: "旭岳",
    romaji: "Asahidake",
    summary_zh:
      "北海道最高峰 2,291m,日本最早開山也最晚收山的粉雪滑雪場。少 lift 靠纜車+自由 off-piste,適合進階者。11 月中 ~ 5 月下旬。",
    content_md:
      "- 雪期:11 月中旬 ~ 5 月下旬(北海道最長)\n- 纜車:山麓駅 1,100m ~ 姿見駅 1,600m(10 分,來回 ¥3,200)\n- 夏季(6-10 月)為大雪山登山基地,姿見の池周邊紅葉 9 月初\n- JR 旭川駅巴士約 1.5 小時(いでゆ號)\n- 住宿:旭岳溫泉 5-6 間旅館",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川",
    municipality_ja: "東川町",
    lg_code: "01458",
    area_types: ["mountain", "rural"],
    lat: 43.6653,
    lon: 142.8306,
    season_start: "2000-11-15",
    season_end: "2001-05-31",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E6%97%AD%E5%B2%B3%E3%83%AD%E3%83%BC%E3%83%97%E3%82%A6%E3%82%A7%E3%82%A4",
    },
    tags: ["longest_season", "powder_snow", "advanced"],
    source: "manual",
  },

  // ── firework_festival 追加 1 筆 ─────────────────────
  {
    slug: "hokkaido-toyako-longrun-hanabi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "洞爺湖 Long-run 花火大會",
    title_ja: "洞爺湖ロングラン花火大会",
    romaji: "Tōyako Long-run Hanabi Taikai",
    summary_zh:
      "日本最長期間的花火大會 · 4 月底 ~ 10 月底每晚約 20 分鐘、450 發。從溫泉街前的遊覽船同步放,全世界最「日常」的煙火。",
    content_md:
      "- 期間:每年 4 月 28 日 ~ 10 月 31 日(約 6 個月)\n- 時間:每晚 20:45 ~ 21:05(約 20 分鐘)\n- 會場:洞爺湖溫泉街湖岸(免費)\n- 付費觀賞船(約 ¥1,600):隨花火船巡湖最佳視角\n- 立地:洞爺湖溫泉街\n- JR 洞爺駅巴士約 15 分",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田",
    municipality_ja: "洞爺湖町",
    lg_code: "01584",
    area_types: ["onsen_town", "rural"],
    lat: 42.5636,
    lon: 140.8578,
    season_start: "2000-04-28",
    season_end: "2000-10-31",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.laketoya.com/",
    },
    tags: ["free", "longest_hanabi_period", "onsen"],
    source: "manual",
  },

  // ── illumination 追加 1 筆 ──────────────────────────
  {
    slug: "hokkaido-otaru-yukiakari",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "小樽雪燈之路",
    title_ja: "小樽雪あかりの路",
    romaji: "Otaru Yukiakari no Michi",
    summary_zh:
      "每年 2 月上旬 10 天,小樽運河 + 手宮線鐵道跡邊沿上萬支蠟燭照映雪雕。2000 位志工支撐的小鎮冬夜奇景,比札幌雪まつり更安靜文藝。",
    content_md:
      "- 期間:每年 2 月第 2 週左右 10 天(具體日依年度公告)\n- 時間:17:00 ~ 21:00(免費)\n- 會場:小樽運河會場、手宮線會場、朝里川温泉會場 3 處\n- 運河倒映 + 雪景攝影絕佳\n- JR 函館本線「小樽駅」徒步 10 分到運河",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "小樽市",
    lg_code: "01203",
    area_types: ["urban", "coastal"],
    lat: 43.1994,
    lon: 140.9947,
    season_start: "2000-02-08",
    season_end: "2000-02-17",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://yukiakarinomichi.org/",
    },
    tags: ["free", "candle", "canal_view"],
    source: "manual",
  },

  // ── flower_field 追加 3 筆 ──────────────────────────
  {
    slug: "hokkaido-biei-blue-pond",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "美瑛 青池",
    title_ja: "青い池",
    romaji: "Aoi Ike",
    summary_zh:
      "1989 年十勝岳泥流對策堰堤偶然形成的人造池,水中氫氧化鋁讓池水呈現幻夢藍綠。2012 年被 Apple OS X 選為桌布後爆紅。通年可訪,冬季限期點燈。",
    content_md:
      "- 通年可訪(旺季 5 月 ~ 10 月)\n- 冬季點燈:11 月 ~ 4 月下旬,日落至 20:30 或 21:00\n- 門票免費,停車 ¥500(夏)/ ¥300(冬)\n- 顏色受天氣影響:晴天+無雨最藍\n- JR 美瑛駅車程 15 分(約 18km),夏季有道北巴士「青い池線」\n- 同遊:白鬚之瀑、白金溫泉",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川",
    municipality_ja: "美瑛町",
    lg_code: "01459",
    area_types: ["rural", "mountain"],
    lat: 43.4956,
    lon: 142.5850,
    season_start: "2000-05-01",
    season_end: "2000-10-31",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E9%9D%92%E3%81%84%E6%B1%A0",
    },
    tags: ["apple_wallpaper", "volcanic_pond", "winter_illumi"],
    source: "manual",
  },
  {
    slug: "hokkaido-kamiyubetsu-tulip",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "上湧別 鬱金香公園",
    title_ja: "かみゆうべつチューリップ公園",
    romaji: "Kamiyūbetsu Tulip Kōen",
    summary_zh:
      "北海道代表鬱金香園,7 公頃 200 品種 120 萬株。每年 5 月 GW 至月底「チューリップフェア」,荷蘭風車下的漸層花毯是鄂霍次克海側限定風景。",
    content_md:
      "- 花期:約 5 月 5 日 ~ 6 月 5 日(「チューリップフェア」約期間同)\n- 入園:成人 ¥600、花祭期間延長 ¥700、學生免費\n- 交通:JR 石北本線「遠軽駅」轉巴士約 25 分\n- 園內荷蘭風車、軌道巴士「Flower-go-round」\n- 同週順遊:サロマ湖、網走監獄",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "紋別",
    municipality_ja: "湧別町",
    lg_code: "01559",
    area_types: ["rural"],
    lat: 44.1389,
    lon: 143.5878,
    season_start: "2000-05-05",
    season_end: "2000-06-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://town.yubetsu.lg.jp/",
    },
    tags: ["tulip", "okhotsk_coast", "golden_week"],
    source: "manual",
  },
  {
    slug: "hokkaido-takino-park",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "滝野鈴蘭丘陵公園",
    title_ja: "国営滝野すずらん丘陵公園",
    romaji: "Kokuei Takino Suzuran Kyūryō Kōen",
    summary_zh:
      "北海道唯一国営公園,400 公頃四季花卉接力。5 月鈴蘭/鬱金香、6-7 月薔薇/芍藥、8-9 月向日葵、10 月鼠尾草、冬季滑雪區。距札幌市中心車程 40 分。",
    content_md:
      "- 開園期:4 月 20 日 ~ 11 月 10 日(花季)、12 月 23 日 ~ 3 月 31 日(冬季雪遊戲)\n- 閉園期:11 月 11 日 ~ 12 月 22 日、4 月 1 日 ~ 19 日\n- 花卉:5 月鈴蘭 + 鬱金香、6-7 月薔薇、8-9 月向日葵、10 月コキア/鼠尾草\n- 門票:成人 ¥450\n- 地下鐵南北線「真駒内駅」轉中央巴士約 30 分\n- 冬季:雪橇、越野滑雪、雪上迷宮",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["rural", "urban"],
    lat: 42.9756,
    lon: 141.3656,
    season_start: "2000-04-20",
    season_end: "2000-11-10",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.takinopark.com/",
    },
    tags: ["national_park", "all_season_flowers", "day_trip_sapporo"],
    source: "manual",
  },

  // ── aquarium_zoo 3 筆(新 sub_type) ─────────────────
  {
    slug: "hokkaido-asahiyama-zoo",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "旭山動物園",
    title_ja: "旭川市旭山動物園",
    romaji: "Asahikawa-shi Asahiyama Dōbutsuen",
    summary_zh:
      "讓動物園脫胎換骨的「行動展示」先驅。企鵝散步(冬)、北極熊水中跳水、海豹柱狀水槽是教科書級設計。夏冬兩季分別開園。",
    content_md:
      "- 夏期:4 月 27 日 ~ 11 月 3 日(9:30-17:15 → 10 月後 16:30)\n- 冬期:11 月 11 日 ~ 12 月 29 日、1 月 2 日 ~ 4 月 7 日(10:30-15:30)\n- 休園:4 月上、11 月上、12/30-1/1\n- 夜之動物園「夜の動物園」:8 月 10-16 日(9:30-21:00)\n- 冬季名物:企鵝散步每日 2 場(11 月下 ~ 3 月中)\n- 門票:成人 ¥1,000\n- JR 旭川駅巴士約 40 分",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "旭川市",
    lg_code: "01204",
    area_types: ["urban"],
    lat: 43.7667,
    lon: 142.4806,
    season_start: "2000-04-27",
    season_end: "2000-11-03",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E6%97%AD%E5%B7%9D%E5%B8%82%E6%97%AD%E5%B1%B1%E5%8B%95%E7%89%A9%E5%9C%92",
    },
    tags: ["behavioral_exhibit", "penguin_walk", "famous"],
    source: "manual",
  },
  {
    slug: "hokkaido-otaru-aquarium",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "小樽水族館",
    title_ja: "おたる水族館",
    romaji: "Otaru Suizokukan",
    summary_zh:
      "道內最大水族館,主打寒帶+北極海生物。海獸公園 13 種海洋哺乳類、海豚與海獅表演、約 250 種 12,000 隻。與相鄰遊園地可套票。",
    content_md:
      "- 通常期:3 月中旬 ~ 11 月下旬(9:00-17:00)\n- 冬期:12 月中 ~ 12 月下 + 1 月 2 日 ~ 2 月下旬(縮短開園)\n- 休園期:11 月下 ~ 12 月中、2 月下 ~ 3 月中\n- 門票:通常期成人 ¥1,800、冬期 ¥1,100\n- JR 小樽駅中央巴士「水族館線」約 25 分\n- 立地祝津,緊鄰展望台與青の洞窟クルーズ",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "小樽市",
    lg_code: "01203",
    area_types: ["urban", "coastal"],
    lat: 43.2317,
    lon: 140.9608,
    season_start: "2000-03-16",
    season_end: "2000-11-30",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://otaru-aq.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%81%8A%E3%81%9F%E3%82%8B%E6%B0%B4%E6%97%8F%E9%A4%A8",
    },
    tags: ["cold_water", "marine_mammal", "largest_hokkaido"],
    source: "manual",
  },
  {
    slug: "hokkaido-noboribetsu-bear-park",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "登別熊牧場",
    title_ja: "のぼりべつクマ牧場",
    romaji: "Noboribetsu Kuma Bokujō",
    summary_zh:
      "全世界最早的棕熊多頭集団飼育(1958 年起)。登別溫泉纜車上山,約 70 隻蝦夷棕熊在「第 2 牧場」招牌「おねだりポーズ」討飼料。附博物館+愛奴文化館。",
    content_md:
      "- 全年營業 9:00 ~ 16:30(纜車運行中)\n- 纜車 1,260m 7 分鐘,含入場費套票\n- 飼育熊約 70 隻\n- 秋季「ドングリ割引」:帶橡實入場有折扣\n- 小人、老人折扣\n- JR 登別駅巴士約 15 分、登別溫泉巴士站徒步 8 分",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "登別市",
    lg_code: "01230",
    area_types: ["onsen_town", "rural"],
    lat: 42.4919,
    lon: 141.1431,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://bearpark.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%81%AE%E3%81%BC%E3%82%8A%E3%81%B9%E3%81%A4%E3%82%AF%E3%83%9E%E7%89%A7%E5%A0%B4",
    },
    tags: ["brown_bear", "ropeway", "noboribetsu_onsen"],
    source: "manual",
  },

  // ── sports_spectate 1 筆(新 sub_type) ──────────────
  {
    slug: "hokkaido-escon-field",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "Escon Field Hokkaido(日本火腿主場)",
    title_ja: "エスコンフィールドHOKKAIDO",
    romaji: "Escon Field Hokkaido",
    summary_zh:
      "2023 年開幕的日本首座「天然草皮 × 可開合屋頂」球場,北海道日本火腿鬥士隊主場。所在地北廣島 F Village 區內含溫泉、啤酒廠、住宿,是可逗留半日的運動觀光區。",
    content_md:
      "- 職棒賽季:3 月下旬 ~ 10 月上旬(季後賽可能至 11 月)\n- 容量:約 35,000 人(座位 29,000)\n- 球隊:北海道日本ハムファイターズ\n- 屋頂 25 分鐘開合,日本最大可動式\n- JR「北廣島駅」徒步 20 分 or 從札幌駅/新千歲機場直達巴士\n- 園區設施:溫泉 tower eleven onsen、啤酒廠、住宿\n- 非賽事日可購入園參觀",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "北広島市",
    lg_code: "01234",
    area_types: ["urban"],
    lat: 42.9903,
    lon: 141.4519,
    season_start: "2000-03-25",
    season_end: "2000-10-10",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      official: "https://www.hkdballpark.com/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%82%A8%E3%82%B9%E3%82%B3%E3%83%B3%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89HOKKAIDO",
    },
    tags: ["npb", "retractable_roof", "fighters"],
    source: "manual",
  },

  // ── Phase 1.2 追加 15 筆(2026-04-22 Level-1 第二輪) ────────
  // sakura +1 / momiji +3 / ski +2 / firework +1 / illumi +3 /
  // flower_field +2 / aquarium_zoo +1 / music_festival +1 / theme_park +1

  // ── sakura 追加 1 筆(北海道神宮) ──────────────────
  {
    slug: "hokkaido-hokkaido-jingu-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "北海道神宮 櫻花",
    title_ja: "北海道神宮の桜",
    romaji: "Hokkaidō Jingū no Sakura",
    summary_zh:
      "札幌總鎮守、道內一宮,與円山公園相連。境內約 1,400 株櫻花(蝦夷山櫻、染井吉野、八重櫻)並開梅花,賞櫻賞梅同時可觀。1953-2010 年間曾為札幌管區氣象台的櫻花標本木所在地。",
    content_md:
      "- 開花:約 4 月下旬 ~ 5 月上旬(2026 札幌 tenki.jp 開花 4/18 滿開 4/23)\n- 例祭「札幌まつり」:6/14-16 三大神輿渡御(非賞櫻期)\n- 境內免費,開門 6:00 / 閉門因季節 16:00-18:00\n- 地下鐵東西線「円山公園駅」徒步 15 分\n- 櫻花與梅花同時開,「櫻梅同開」為北國特色",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban", "shrine"],
    lat: 43.0544,
    lon: 141.3069,
    season_start: "2000-04-18",
    season_end: "2000-05-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.hokkaidojingu.or.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E5%8C%97%E6%B5%B7%E9%81%93%E7%A5%9E%E5%AE%AE",
      tenki: "https://tenki.jp/sakura/1/1/",
    },
    tags: ["free", "shrine", "plum_blossom", "sapporo_matsuri"],
    source: "manual",
  },

  // ── momiji 追加 3 筆(登別地獄谷、支笏湖、旭岳姿見) ──
  {
    slug: "hokkaido-noboribetsu-jigokudani-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "登別地獄谷 紅葉",
    title_ja: "登別地獄谷の紅葉",
    romaji: "Noboribetsu Jigokudani no Momiji",
    summary_zh:
      "日本紅葉百選之一,火山爆裂口噴湯,直徑 450m、面積約 11 公頃的地獄景觀。9 月下旬 ~ 10 月下旬楓葉配白色蒸氣與硫磺味,氛圍獨特。",
    content_md:
      "- 見頃:約 10 月中旬 ~ 下旬\n- 免費(散策路 24 小時開放,夜間地獄谷鬼火之路 17:30-21:00)\n- JR「登別駅」轉巴士 15 分「登別温泉」下車徒步 10 分\n- 周邊溫泉旅館多可當日入浴(日帰り)\n- 湯煙含硫磺,雨天路滑注意",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "登別市",
    lg_code: "01230",
    area_types: ["hot_spring", "mountain"],
    lat: 42.5003,
    lon: 141.1731,
    season_start: "2000-10-10",
    season_end: "2000-10-31",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://noboribetsu-spa.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E7%99%BB%E5%88%A5%E6%B8%A9%E6%B3%89",
    },
    tags: ["free", "hundred_momiji", "volcanic", "hot_spring"],
    source: "manual",
  },
  {
    slug: "hokkaido-shikotsu-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "支笏湖 紅葉",
    title_ja: "支笏湖の紅葉",
    romaji: "Shikotsu-ko no Momiji",
    summary_zh:
      "連續多年獲環境省「日本第一水質」的不凍湖,最深 360m(日本第二深)。湖周楓葉配「支笏湖ブルー」透明度世界級,10 月下旬紅葉節於湖畔舉辦。",
    content_md:
      "- 見頃:約 10 月中旬 ~ 下旬\n- 支笏湖紅葉節:通常 10 月中一週末(攤販、湖畔散策路徑開放)\n- 免費,24 小時開放\n- JR「千歳駅」轉巴士約 44 分「支笏湖」下車\n- 推薦散策路:「紅葉谷」、「苔の洞門」、「美笛川」\n- 湖面遊覽船、透明獨木舟(4-11 月)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "千歳市",
    lg_code: "01224",
    area_types: ["lake", "mountain"],
    lat: 42.7544,
    lon: 141.3447,
    season_start: "2000-10-10",
    season_end: "2000-10-31",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E6%94%AF%E7%AC%8F%E6%B9%96",
    },
    tags: ["free", "caldera_lake", "clear_water", "shikotsu_blue"],
    source: "manual",
  },
  {
    slug: "hokkaido-asahidake-shimizu-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "旭岳姿見の池 紅葉",
    title_ja: "旭岳姿見の池の紅葉",
    romaji: "Asahidake Sugatami-no-Ike no Momiji",
    summary_zh:
      "北海道最高峰(2,291m)旭岳山腰,標高 1,600m 的姿見之池周圍為日本全國最早紅葉名所,9 月上旬即進入見頃,纜車可直達。",
    content_md:
      "- 見頃:約 9 月上旬 ~ 9 月下旬(全日本最早紅葉之一)\n- 旭岳纜車:來回成人 ¥3,200(秋期)\n- 營業時間因季節變動(夏季 6:00-17:30)\n- JR「旭川駅」轉巴士約 1 時間 30 分「旭岳」下車\n- 散策路線:姿見之池循環 1.7km(約 1 小時)\n- 9 月山頂氣溫 5-10℃、可能降雪,穿防風外套",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川郡",
    municipality_ja: "東川町",
    lg_code: "01458",
    area_types: ["mountain", "national_park"],
    lat: 43.6586,
    lon: 142.8547,
    season_start: "2000-09-05",
    season_end: "2000-09-30",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 0,
    closed_days: [],
    external_urls: {
      official: "https://asahidake.hokkaido.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E6%97%AD%E5%B2%B3",
    },
    tags: ["ropeway", "earliest_momiji", "highest_peak_hokkaido"],
    source: "manual",
  },

  // ── ski 追加 2 筆(サッポロテイネ、札幌国際) ─────────
  {
    slug: "hokkaido-sapporo-teine-ski",
    category: "entertainment",
    sub_type: "ski_season",
    title_zh: "サッポロテイネ Sapporo Teine",
    title_ja: "サッポロテイネ",
    romaji: "Sapporo Teine",
    summary_zh:
      "1972 札幌冬奧回轉/大回轉比賽場地。ハイランド(上部)+ オリンピア(下部)2 區,6 條纜車 15 條雪道,從札幌市中心搭巴士 40 分可達,北國最親民都市近郊雪場。",
    content_md:
      "- 雪期:約 11 月下旬 ~ 5 月上旬(依雪況)\n- 最長滑走距離:6,000m(オリンピア ダウンヒル)\n- 垂直落差:683m(上部 1,023m ~ 340m)\n- 從札幌駅搭 JR + 巴士約 40-50 分\n- 1 日券成人約 ¥6,000\n- 1972 冬奧回轉/大回轉場地,「女子回轉」金牌コース現在仍可滑",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["ski", "urban"],
    lat: 43.0856,
    lon: 141.2028,
    season_start: "2000-11-25",
    season_end: "2001-05-05",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 0,
    closed_days: [],
    external_urls: {
      official: "https://www.sapporo-teine.com/snow/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%82%B5%E3%83%83%E3%83%9D%E3%83%AD%E3%83%86%E3%82%A4%E3%83%8D",
    },
    tags: ["winter_olympics_1972", "urban_ski", "near_sapporo"],
    source: "manual",
  },
  {
    slug: "hokkaido-sapporo-kokusai-ski",
    category: "entertainment",
    sub_type: "ski_season",
    title_zh: "札幌国際スキー場",
    title_ja: "札幌国際スキー場",
    romaji: "Sapporo Kokusai Ski-jō",
    summary_zh:
      "北海道公認「札幌近郊最晚關」雪場,雪期 11 月下旬 ~ 5 月初。7 條雪道、縱走 3.6km、最長滑走長,雪質粉雪。從札幌駅搭巴士約 1 小時直達。",
    content_md:
      "- 雪期:約 11 月下旬 ~ 5 月上旬\n- 7 條雪道(初中級 5 條、上級 2 條)\n- 最長滑走:3,600m\n- 札幌駅直達巴士:約 1 時間 30 分\n- 1 日券成人約 ¥5,500\n- 一般多 day-trip 無住宿,但定山溪溫泉近\n- 兒童設施(ちびっこ広場)充實",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["ski", "mountain"],
    lat: 43.0125,
    lon: 141.0747,
    season_start: "2000-11-25",
    season_end: "2001-05-05",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 0,
    closed_days: [],
    external_urls: {
      official: "https://www.sapporo-kokusai.jp/",
    },
    tags: ["powder_snow", "late_season", "near_sapporo", "family_friendly"],
    source: "manual",
  },

  // ── firework_festival 追加 1 筆(小樽潮まつり花火) ──
  {
    slug: "hokkaido-otaru-ushio-hanabi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "小樽潮まつり花火",
    title_ja: "おたる潮まつり花火大会",
    romaji: "Otaru Ushio Matsuri Hanabi",
    summary_zh:
      "1967 年首屆,每年 7 月最後一個週五~週日舉辦,最終日晚間色內埠頭公園約 4,000 發花火,運河倒影是小樽夏天的代名詞。",
    content_md:
      "- 開催:每年 7 月最終週末(金~日 3 日)\n- 花火日:最終日 19:30-20:30,色內埠頭公園海上\n- 發數:約 4,000 發\n- 免費觀覽;運河沿岸最佳\n- JR「小樽駅」徒步 10 分\n- 交通管制:當日中央通、運河邊行人天國\n- 週末與潮ねりこみ(6,000 人巡行)同時段",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "小樽市",
    lg_code: "01203",
    area_types: ["urban", "coast"],
    lat: 43.1986,
    lon: 140.9956,
    season_start: "2000-07-25",
    season_end: "2000-07-31",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://otaru.ushiomatsuri.net/",
    },
    tags: ["free", "canal", "summer_matsuri", "4000_shots"],
    source: "manual",
  },

  // ── illumination 追加 3 筆(札幌雪祭、旭川冬祭、支笏湖氷濤) ──
  {
    slug: "hokkaido-sapporo-snow-festival",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "札幌雪まつり",
    title_ja: "さっぽろ雪まつり",
    romaji: "Sapporo Yuki Matsuri",
    summary_zh:
      "1950 年開始,日本最大規模冬季祭,2 月上旬 7 日間,大通公園 × つどーむ × すすきの三會場約 200 座雪像/冰像,每年 175 萬人來訪,夜間燈光秀 17:00-22:00。",
    content_md:
      "- 會期:每年 2/4 ~ 2/11 原則(7 日間)\n- 大通會場:大通 1-12 丁目,大雪像 5 座 + 市民雪像 120 座\n- つどーむ會場:親子雪滑梯、雪筏\n- すすきの氷彫刻:國際氷彫刻競賽作品\n- 全會場免費\n- 夜間點燈:大通 17:00-22:00 / すすきの 17:00-23:00(週末到 24:00)\n- 地下鐵南北線「大通駅」直達",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban", "park"],
    lat: 43.0617,
    lon: 141.3500,
    season_start: "2001-02-04",
    season_end: "2001-02-11",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://www.snowfes.com/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%81%95%E3%81%A3%E3%81%BD%E3%82%8D%E9%9B%AA%E3%81%BE%E3%81%A4%E3%82%8A",
    },
    tags: ["free", "snow_sculpture", "ice_sculpture", "largest_winter_festival"],
    source: "manual",
  },
  {
    slug: "hokkaido-asahikawa-winter-festival",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "旭川冬まつり",
    title_ja: "あさひかわ冬まつり",
    romaji: "Asahikawa Fuyu Matsuri",
    summary_zh:
      "1959 年首屆,石狩川河川敷主會場,曾有世界最大雪像(1994 年金氏紀錄 Guinness 高 25.1m)。2 月上旬 6 日間,約 100 萬人,平和通買物公園步行者天國氷彫刻世界大會。",
    content_md:
      "- 會期:每年 2 月上旬 6 日間(通常與札幌雪祭重疊)\n- 主會場:石狩川旭橋下河川敷\n- 大雪像、雪像迷宮、雪滑梯\n- 氷彫刻世界大會:平和通買物公園(徒步圈)\n- 免費\n- JR「旭川駅」徒步 15 分\n- 夜間點燈 17:30-21:00(花火有日)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "旭川市",
    lg_code: "01204",
    area_types: ["urban", "river"],
    lat: 43.7706,
    lon: 142.3650,
    season_start: "2001-02-04",
    season_end: "2001-02-11",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["free", "snow_sculpture", "ice_sculpture_world", "guinness_record"],
    source: "manual",
  },
  {
    slug: "hokkaido-shikotsu-hyoto",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "千歳・支笏湖氷濤まつり",
    title_ja: "千歳・支笏湖氷濤まつり",
    romaji: "Chitose Shikotsu-ko Hyōtō Matsuri",
    summary_zh:
      "1979 年首屆,支笏湖畔將湖水層層澆結冰造出青色氷濤(冰雕),全場青く透ける「支笏湖ブルー」。1 月底 ~ 2 月中,夜間七彩燈光與花火(週末)。",
    content_md:
      "- 會期:每年 1 月下旬 ~ 2 月中旬(約 3 週)\n- 入場:成人 ¥500(夜間協力金)\n- 花火:會期中週末 18:30 約 5 分\n- 點燈時間:16:30-22:00\n- 溜冰、狗拉雪橇、雪滑梯\n- JR「千歳駅」轉巴士約 44 分「支笏湖」\n- 冬期氣溫 -10℃,需重裝",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "千歳市",
    lg_code: "01224",
    area_types: ["lake", "nature"],
    lat: 42.7544,
    lon: 141.3447,
    season_start: "2001-01-25",
    season_end: "2001-02-20",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ice_sculpture", "shikotsu_blue", "fireworks_weekend"],
    source: "manual",
  },

  // ── flower_field 追加 2 筆(滝上芝櫻、ぜるぶの丘) ──
  {
    slug: "hokkaido-takinoue-shibazakura",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "滝上公園 芝櫻",
    title_ja: "滝上公園の芝ざくら",
    romaji: "Takinoue Kōen no Shibazakura",
    summary_zh:
      "1957 年由一杯的芝櫻苗起家,今日成為 10 萬 m²(約 2 個東京巨蛋)、粉色地毯的日本第一芝櫻名所。5 月上旬 ~ 6 月上旬開花,覆蓋山坡全紅粉的「桃源郷」。",
    content_md:
      "- 見頃:約 5 月上旬 ~ 6 月上旬\n- 入園料:成人 ¥500 / 中學生以下免費\n- 面積:約 10 萬 m²(日本第一)\n- 開園 8:00-18:00(見頃期間)\n- 滝上芝櫻まつり:5 月上旬 ~ 下旬\n- JR「旭川駅」轉巴士約 3 時間(偏遠)\n- 最佳交通:租車自駕",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "紋別郡",
    municipality_ja: "滝上町",
    lg_code: "01560",
    area_types: ["mountain", "rural"],
    lat: 44.1903,
    lon: 143.0683,
    season_start: "2000-05-05",
    season_end: "2000-06-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://town.takinoue.hokkaido.jp/",
    },
    tags: ["shibazakura", "largest_japan", "pink_carpet"],
    source: "manual",
  },
  {
    slug: "hokkaido-biei-zerubu-no-oka",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "ぜるぶの丘",
    title_ja: "ぜるぶの丘",
    romaji: "Zerubu no Oka",
    summary_zh:
      "美瑛町北西的丘陵花田,面積 8 公頃、30 種季節花卉。4 月下鬱金香 → 6 月魯冰花 → 7-8 月薰衣草、向日葵 → 9 月百日草,從春到秋每月換色。",
    content_md:
      "- 開花期:4 月下旬 ~ 10 月中旬\n- 入園免費,停車免費\n- バギー/カート レンタル:¥600-2,000(10 分 ~ 30 分)\n- JR「美瑛駅」搭觀光巴士「ビューバス」下車,或租車 5 分\n- 花種:鬱金香、ルピナス、薰衣草、向日葵、百日草\n- 「ケンとメリーの木」鄰接",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川郡",
    municipality_ja: "美瑛町",
    lg_code: "01459",
    area_types: ["rural", "hill"],
    lat: 43.6144,
    lon: 142.4431,
    season_start: "2000-04-25",
    season_end: "2000-10-15",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["free", "multi_season", "30_species", "near_ken_and_mary_tree"],
    source: "manual",
  },

  // ── aquarium_zoo 追加 1 筆(サンピアザ水族館) ───────
  {
    slug: "hokkaido-sunpiazza-aquarium",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "サンピアザ水族館",
    title_ja: "サンピアザ水族館",
    romaji: "Sunpiazza Aquarium",
    summary_zh:
      "1982 年開業,新札幌副都心サンピアザ商場 2F 的都心型水族館。約 200 種 1 萬隻、北海道近海魚類展示中心,電鰻放電秀、海豹餵食秀等全年可看。",
    content_md:
      "- 全年開館(1/1 與 5 月維修日除外)\n- 開館:10:00-18:30(冬期 18:00)\n- 入館:成人 ¥1,000 / 高中生 ¥400 / 中小學 ¥300 / 幼兒 ¥200\n- 地下鐵東西線「新さっぽろ駅」直通\n- 展示亮點:電鰻放電、海豹、水瀨、企鵝、北海道鮭魚\n- 商場內用餐、購物便利,全天候行程適合",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban", "indoor"],
    lat: 43.0358,
    lon: 141.4728,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 0,
    closed_days: [],
    external_urls: {
      official: "https://www.sunpiazza-aquarium.com/",
    },
    tags: ["urban_aquarium", "all_weather", "new_sapporo"],
    source: "manual",
  },

  // ── music_festival 追加 1 筆(新 sub_type) ─────────
  {
    slug: "hokkaido-rising-sun-rock-festival",
    category: "entertainment",
    sub_type: "music_festival",
    title_zh: "Rising Sun Rock Festival in EZO",
    title_ja: "RISING SUN ROCK FESTIVAL",
    romaji: "Rising Sun Rock Festival",
    summary_zh:
      "1999 年首屆,日本最北的大型野外音樂祭,8 月中旬週末 2 日,石狩湾新港特設會場。2023 起場地略縮小仍吸引 5-6 萬人,10 餘舞台、200+ 組演出。",
    content_md:
      "- 開催:每年 8 月中旬週末(金夜 ~ 土)\n- 會場:石狩湾新港樽川埠頭横特設會場\n- 2 日通票約 ¥27,000(含露營權)\n- 從札幌駅有シャトルバス(約 1 時間)\n- オールナイト演唱,日落後至翌朝\n- テント(露營)持参 or 現地レンタル\n- 雨具、防寒(海風凍)必備\n- 2020/2021 因疫情停辦,2022 復活",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "石狩市",
    lg_code: "01235",
    area_types: ["coast", "outdoor"],
    lat: 43.1947,
    lon: 141.2636,
    season_start: "2000-08-14",
    season_end: "2000-08-17",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      official: "https://rsr.wess.co.jp/",
    },
    tags: ["rock_festival", "camping", "all_night", "northernmost"],
    source: "manual",
  },

  // ── theme_park 追加 1 筆(ノーザンホースパーク) ────
  {
    slug: "hokkaido-northern-horse-park",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ノーザンホースパーク Northern Horse Park",
    title_ja: "ノーザンホースパーク",
    romaji: "Northern Horse Park",
    summary_zh:
      "新千歲機場車程 15 分,社台 Group 經營的馬主題複合樂園。80 頭各品種馬、乘馬體驗、馬車、騎射、觀光馬場,配 200 萬坪原生林。",
    content_md:
      "- 夏期(4/15-11/5):開園 9:00-17:00(入園成人 ¥1,600)\n- 冬期(11/6-4/14):開園 10:00-16:00(入園免費)\n- 冬期雪上活動:狗拉雪橇、馬拉雪橇、雪遊樂\n- 新千歲機場直達巴士 15 分\n- 乘馬體驗:¥2,000-20,000(依體驗)\n- 原生林散策、湿原デッキ、野鳥觀察\n- 場內餐廳「和_KOKO」馬肉料理",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "苫小牧市",
    lg_code: "01213",
    area_types: ["rural", "forest"],
    lat: 42.7739,
    lon: 141.6919,
    season_start: "2000-04-15",
    season_end: "2000-11-05",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 0,
    closed_days: [],
    external_urls: {
      official: "https://www.northern-horsepark.jp/",
    },
    tags: ["horse_riding", "near_airport", "shadai_group", "year_round"],
    source: "manual",
  },

  // ── Phase 1.3 追加 15 筆(2026-04-22 · 超詳細版) ─────────
  // sakura +1 / momiji +1 / firework +1 / illumi +1 / flower +2 /
  // theme_park +5 / aquarium_zoo +1 / sports_spectate +2 / music_festival +1

  // ── sakura 追加 1 筆(根室清隆寺 千島桜) ──────────
  {
    slug: "hokkaido-seiryuji-chishima-sakura",
    category: "entertainment",
    sub_type: "sakura",
    title_zh: "根室 清隆寺 千島櫻",
    title_ja: "清隆寺の千島桜",
    romaji: "Seiryūji no Chishima Zakura",
    summary_zh:
      "1892 年創建於日本最東端根室市的真言宗寺院。境內的千島櫻為昭和 8 年從國後島移植而來,被認定為「日本最晚開花的櫻花」,每年 5 月下旬 ~ 6 月上旬盛開。與本州的染井吉野大異其趣,花色更深桃紅,是北方櫻花迷必訪。",
    content_md:
      "- 見頃:5 月下旬 ~ 6 月上旬(日本最晚開花)\n- 品種:千島櫻(チシマザクラ)3 株,含根室市指定天然記念物\n- 由來:昭和 8 年(1933)從國後島(今俄國實效管轄)移植\n- 境內免費,自由參拜\n- 交通:JR「根室駅」徒步 15 分\n- 寺宗派:真言宗智山派,北海道三十三観音靈場第 22 番\n- 主尊:不動明王;本尊阿彌陀佛(1700 年作,上品蓮台寺傳來)\n- 花期短(約 1 週),建議當年 5 月中查詢花況再出發\n- 周邊:納沙布岬(日本最東端)車 30 分、根室金比羅神社\n- 最佳搭配:5 月下根室 → 6 月初釧路 → 往札幌方向回程",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "根室市",
    lg_code: "01223",
    area_types: ["temple", "coast", "easternmost"],
    lat: 43.3289,
    lon: 145.5669,
    season_start: "2000-05-20",
    season_end: "2000-06-05",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E6%B8%85%E9%9A%86%E5%AF%BA",
    },
    tags: ["free", "chishima_sakura", "latest_bloom_japan", "easternmost", "shingon"],
    source: "manual",
  },

  // ── momiji 追加 1 筆(昭和新山紅葉) ───────────────
  {
    slug: "hokkaido-showa-shinzan-momiji",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "昭和新山 紅葉",
    title_ja: "昭和新山の紅葉",
    romaji: "Shōwa Shinzan no Momiji",
    summary_zh:
      "1943-1945 年戰時從麥田隆起的活火山熔岩圓頂,標高 398m,國家特別天然記念物。紅色岩體與楓葉相映,搭配旁邊有珠山纜車從空中俯瞰洞爺湖,是道南秋天代表景觀。",
    content_md:
      "- 見頃:10 月中旬 ~ 10 月下旬\n- 有珠山ロープウェイ:來回成人 ¥2,000 / 小學生 ¥1,000(15 分抵標高 691m 山頂駅)\n- 運行時間:夏期 8:15-18:00 / 秋期 8:45-16:45(依季節變動)\n- 火山活動:1943-45 年戰時隆起,仍為活火山(最近噴火 2000 年有珠山)\n- 交通:JR「洞爺駅」轉道南巴士約 20 分「昭和新山」下車\n- 入山:昭和新山本身為私有地,由三松家管理,不得登山\n- 展望:山頂駅可俯瞰洞爺湖、羊蹄山、太平洋內浦灣\n- 鄰接:昭和新山熊牧場(¥850)、三松正夫記念館\n- 火山博物館:洞爺湖畔「洞爺湖ビジターセンター」可免費學火山知識\n- 深秋冷風強,建議外套 + 防風",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "有珠郡",
    municipality_ja: "壮瞥町",
    lg_code: "01575",
    area_types: ["volcano", "mountain", "lake_view"],
    lat: 42.5422,
    lon: 140.8706,
    season_start: "2000-10-10",
    season_end: "2000-10-31",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 0,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E6%98%AD%E5%92%8C%E6%96%B0%E5%B1%B1",
    },
    tags: ["active_volcano", "ropeway", "toya_lake_view", "special_natural_monument"],
    source: "manual",
  },

  // ── firework_festival 追加 1 筆(勝毎花火大会) ────
  {
    slug: "hokkaido-katsumai-hanabi",
    category: "entertainment",
    sub_type: "firework_festival",
    title_zh: "勝毎花火大會",
    title_ja: "勝毎花火大会",
    romaji: "Katsumai Hanabi Taikai",
    summary_zh:
      "1929 年由十勝每日新聞社倡議「北海道最初の花火大會」創設,至今近百年歷史,道東最大規模煙火盛事。每年 8/13 晚間於帯広市十勝大橋下游舉辦,五段式主題構成、最終段連發「錦冠菊」。2009 年已達 18 萬人觀眾。",
    content_md:
      "- 開催日:每年 8/13(雨天予備 8/14、8/17)\n- 時間:19:30-20:45(約 75 分)\n- 會場:帯広市 十勝川 十勝大橋下游河岸特設會場\n- 歷史:1929 年十勝每日新聞創始人在鯉養殖池首辦,戰後 1956 復活\n- 發數:約 2 萬發(道內最大級)\n- 構成:五段式主題演出 + 結尾「錦冠菊」連發\n- 限制:2002 年意外後 8 號玉以上禁用;2012 年起事前場所取不可\n- 觀眾:2009 年約 18 萬人\n- 觀覽:免費自由席(河川敷);有料席每年釋出 → 詳見官方\n- 交通:JR「帯広駅」徒步 20 分;臨時 P 有,路線管制\n- 備注:盂蘭盆假期中,帯広市內住宿 3 個月前訂光",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "帯広市",
    lg_code: "01207",
    area_types: ["urban", "river"],
    lat: 42.9201,
    lon: 143.1967,
    season_start: "2000-08-13",
    season_end: "2000-08-13",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E5%8B%9D%E6%AF%8E%E8%8A%B1%E7%81%AB%E5%A4%A7%E4%BC%9A",
    },
    tags: ["free", "20000_shots", "obon_holiday", "tokachi", "since_1929"],
    source: "manual",
  },

  // ── illumination 追加 1 筆(もんべつ流氷まつり) ──
  {
    slug: "hokkaido-monbetsu-ryuhyo-matsuri",
    category: "entertainment",
    sub_type: "illumination",
    title_zh: "紋別流氷祭",
    title_ja: "もんべつ流氷まつり",
    romaji: "Monbetsu Ryūhyō Matsuri",
    summary_zh:
      "1963 年首屆,道內第三古老冬祭(僅次於札幌雪祭、旭川冬祭)。每年 2 月上旬於紋別海洋交流館旁舉辦,陸自遠軽駐屯地 25 普連擔當大雪像製作,配合流氷鄰接地的冰柱 illumination,是鄂霍次克海流氷觀光的核心活動之一。",
    content_md:
      "- 會期:每年 2 月上旬(通常 2/4-2/10 前後)\n- 會場:紋別市 海洋交流館(ガリヤゾーン)隣接駐車場\n- 雪像:陸上自衛隊遠軽駐屯地 第 25 普通科連隊 製作,每年主題變更\n- 冰雕:紋別市漁協協力\n- 點燈:17:00-22:00\n- 免費入場\n- 交通:紋別巴士ターミナル ~ 會場 シャトルバス 有料運行(會期中)\n- 航空:自羽田飛紋別空港,北海道エアシステム(HAC)每日 1 班\n- 搭配活動:砕氷船ガリンコ号III(IMERU · 拉利)同期運行,¥4,000 觀流氷 1 小時\n- 其他看點:北方紀念館、オホーツクとっかりセンター(海獅展示)\n- 氣溫:2 月紋別 -10℃ 以下,厚手 + 防風 + 防滑鞋必備",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "紋別市",
    lg_code: "01219",
    area_types: ["coast", "urban"],
    lat: 44.3561,
    lon: 143.3539,
    season_start: "2001-02-04",
    season_end: "2001-02-10",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%82%82%E3%82%93%E3%81%B9%E3%81%A4%E6%B5%81%E6%B0%B7%E3%81%BE%E3%81%A4%E3%82%8A",
    },
    tags: ["free", "drift_ice", "jsdf_sculpture", "okhotsk", "third_oldest_winter_fes"],
    source: "manual",
  },

  // ── flower_field 追加 2 筆(百合が原、上富良野) ──
  {
    slug: "hokkaido-yurigahara-park-flower",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "百合が原公園",
    title_ja: "百合が原公園",
    romaji: "Yurigahara Kōen",
    summary_zh:
      "1983 年因昭和天皇即位 50 年紀念開園,札幌北區 25.4 公頃大型綜合公園。6,400 種植物、100 品種百合、600 種以上高山植物,溫室、世界花園(與姐妹都市造園)、リリートレイン園內周遊。1986 年札幌花與綠博覽會主會場。",
    content_md:
      "- 開園:戶外 24 小時自由(冬期部分設施休止)\n- 溫室:9:00-17:00 / 成人 ¥130\n- リリートレイン(園內遊覽小火車):4 月下-10 月中 / 成人 ¥360\n- 花時序:\n  - 5 月中:Tulip、スイセン\n  - 5 月下-6 月:ムスカリ、Primula、ライラック\n  - 6 月下-7 月:Lily(百合)全盛\n  - 7-8 月:ダリア、バラ\n  - 9-10 月:コスモス、紅葉\n- 世界花園:9 區(札幌姐妹都市ミュンヘン、Portland、瀋陽、大田、ノボシビルスク等)\n- 面積:25.4 公頃(含百合之原綠地)\n- 交通:JR「百合が原駅」徒步 10 分;地下鉄南北線「麻生駅」轉巴士 15 分\n- 植物再生:園内廃枝廃葉堆肥化,札幌最大リサイクル設施",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban", "park"],
    lat: 43.1306,
    lon: 141.3819,
    season_start: "2000-05-15",
    season_end: "2000-10-20",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://yuri-park.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E7%99%BE%E5%90%88%E3%81%8C%E5%8E%9F%E5%85%AC%E5%9C%92",
    },
    tags: ["25ha", "6400_species", "lily_train", "greenhouse", "sister_cities"],
    source: "manual",
  },
  {
    slug: "hokkaido-flower-land-kamifurano",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "フラワーランド上富良野",
    title_ja: "フラワーランドかみふらの",
    romaji: "Flower Land Kamifurano",
    summary_zh:
      "上富良野町西 5 線 10 萬 m² 丘陵花田,免費入園,俯瞰富良野盆地與十勝岳連峰 360 度景觀。從旭川空港、富良野駅各 30 分可達,是富良野花田中最開闊、最常見「薰衣草 × 黃色向日葵 × 十勝岳」攝影構圖之地。",
    content_md:
      "- 開園:9:00-17:00(最終入園 16:00,會期 4 月下-10 月中)\n- 入園免費\n- 面積:10 萬 m²(約 2 個東京巨蛋)\n- 主要花序:\n  - 4 月下-5 月:鬱金香\n  - 6 月:ルピナス、ポピー\n  - 7 月:薰衣草、向日葵(代表月)\n  - 8 月:ダリア、サルビア、マリーゴールド\n  - 9-10 月:ケイトウ、ジニア\n- 看點:十勝岳連峰前景構圖、ラベンダー畑斜坡\n- トラクターバス:園內遊覽 10 分 ¥500\n- 販売:薰衣草乾燥品、富良野蜂蜜、自家野菜\n- 食堂:自社農場直送メロン、ラベンダーソフト\n- 交通:JR「上富良野駅」車 10 分(徒步 30 分);旭川空港車 30 分",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "空知郡",
    municipality_ja: "上富良野町",
    lg_code: "01460",
    area_types: ["rural", "hill"],
    lat: 43.4497,
    lon: 142.4703,
    season_start: "2000-04-25",
    season_end: "2000-10-15",
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {
      official: "https://flower-land.co.jp/",
    },
    tags: ["free", "100000sqm", "tokachi_range_view", "tractor_bus", "panorama"],
    source: "manual",
  },

  // ── theme_park 追加 5 筆 ─────────────────────────
  {
    slug: "hokkaido-rusutsu-summer-park",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "Rusutsu Resort 夏期遊園地",
    title_ja: "ルスツリゾート 遊園地",
    romaji: "Rusutsu Resort Yūenchi",
    summary_zh:
      "留寿都村 Rusutsu Resort 夏期(4 月下 ~ 10 月上)開放的北海道最大遊園地。擁有 60 種以上遊具,含日本唯一「木製雲霄飛車 MOUNTAIN COASTER」、水上遊具「ウォータープラザ」,2026 年觀覽車重建中。",
    content_md:
      "- 開園期間:2026/4/29 ~ 10 月上旬(4 月下旬開)\n- 時間:9:30-17:00(夜間營業限夏休み期間至 21:00)\n- 入園料:成人(中學以上)¥3,000 / 小學生 ¥2,000 / 幼兒 ¥1,200(3 歲以下免費)\n- 1 日乘放題「遊び放題パス」:成人 ¥6,400 / 小學生 ¥5,200\n- 遊具數:60+(含木製 Coaster MOUNTAIN COASTER、流れるプール、觀覽車等)\n- 2026 新観覽車:再建工事中,開放時程未定\n- 活動:忍者 eNINJA、レーザーバトル、寶物ハント、お面作り\n- 夏休み超巨大プール「ウォータープラザ」:7 月中 ~ 8 月中\n- 交通:新千歲空港 / 札幌駅 シャトルバス 每日直達(約 90 分)\n- 周邊:冬期同 Resort 滑雪(既有 hokkaido-rusutsu-ski 條目)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "留寿都村",
    lg_code: "01397",
    area_types: ["amusement", "mountain"],
    lat: 42.7544,
    lon: 140.8839,
    season_start: "2000-04-29",
    season_end: "2000-10-10",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 0,
    closed_days: [],
    external_urls: {
      official: "https://rusutsu.com/",
    },
    tags: ["largest_in_hokkaido", "wooden_coaster", "summer_pool", "shuttle_bus"],
    source: "manual",
  },
  {
    slug: "hokkaido-north-safari-sapporo",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "North Safari Sapporo",
    title_ja: "ノースサファリサッポロ",
    romaji: "North Safari Sapporo",
    summary_zh:
      "札幌市南区豊滝的「体験型動物テーマパーク」,以「看て、ふれて、癒される」為概念,可直接接觸猛獸(獅子、老虎)、與小動物拍照、騎駱駝。附屬格蘭平(動物共宿)、冬期狗拉雪橇,是札幌市內唯一能近距離接觸大型動物的設施。",
    content_md:
      "- 夏期(4/25 ~ 9/30):9:00-17:00\n- 冬期(12 月 ~ 3 月):短縮運營,活動項目變更\n- 入園料(夏期):成人(中學以上)¥1,900 / 小學以下 ¥700 / 2 歲以下免費\n- 温泉パック(豊平峡温泉 + 入園):¥2,900\n- 主要體驗:\n  - 猛獣エリア:獅子、虎、熊の至近距離\n  - フクロウ・爬蟲類の肩のせ\n  - カピバラ・ヤギ 餌やり\n  - 駱駝ライド(¥500-1,000)\n  - グランピング泊(動物小屋隣接、夏 ¥30,000~)\n- 冬期限定:犬ぞり、スノーモービル、かまくらキャンプ\n- BBQ ゾーン:手ぶらで利用可\n- 交通:JR 札幌駅 ~ 地下鉄真駒内駅 ~ じょうてつバス「豊滝」下車徒步 5 分(全程約 45 分)\n- 注意事項:有些體驗需事前預約;雨天部分戶外項目中止",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["amusement", "mountain"],
    lat: 42.9550,
    lon: 141.1994,
    season_start: "2000-04-25",
    season_end: "2000-09-30",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 0,
    closed_days: [],
    external_urls: {
      official: "https://www.north-safari.com/",
    },
    tags: ["interactive_animal", "glamping", "near_sapporo", "onsen_package"],
    source: "manual",
  },
  {
    slug: "hokkaido-noboribetsu-date-jidaimura",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "登別伊達時代村",
    title_ja: "登別伊達時代村",
    romaji: "Noboribetsu Date Jidaimura",
    summary_zh:
      "1992 年開業、投資 120 億日圓的江戶‧戰國主題歷史樂園,位於登別溫泉東入口。忍者咖啡屋、花魁道中、武士劇、忍者體驗(手裡劍、弓道),全長 2.3 公頃的江戶街並與大時代服裝租賃,為訪日外客人氣熱門地。",
    content_md:
      "- 開園:1992 年 4 月 23 日\n- 時間:夏期(4-10 月)9:00-17:00 / 冬期(11-3 月)9:00-16:00\n- 入園料:大人(中學以上)¥3,300 / 小學生 ¥1,700 / 幼兒(4 歲以上)¥600\n- 忍者體驗パス(含全忍者ショー):成人 +¥1,000\n- 見所:\n  - 忍者霞谷一族屋敷(仕掛け満載)\n  - 日本伝統文化劇場(歌舞伎 / 花魁)\n  - 侍屋敷 Samurai Action Show\n  - 手裏剣·弓道道場(追加料金)\n  - 時代衣裝レンタル(武士、お姬樣、花魁、¥3,000~)\n- 主題區:江戶街並、武家屋敷、商家町、神社\n- 交通:JR「登別駅」~ 道南バス 6 分「時代村前」下車\n- 車:道央道 登別東 IC 3 分\n- 歷史:開園首年 70 萬人、後低迷 → 2005 年再生,現年 30+ 萬人\n- 建議:和服體驗建議事前予約、時代劇場 1 日 4 場需調時序",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "登別市",
    lg_code: "01230",
    area_types: ["amusement", "historical"],
    lat: 42.4958,
    lon: 141.1547,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 0,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E7%99%BB%E5%88%A5%E4%BC%8A%E9%81%94%E6%99%82%E4%BB%A3%E6%9D%91",
    },
    tags: ["edo_theme", "ninja_show", "costume_rental", "historical_theater", "year_round"],
    source: "manual",
  },
  {
    slug: "hokkaido-abashiri-aurora-ryuhyo",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "網走砕冰船 極光號",
    title_ja: "網走流氷観光砕氷船おーろら",
    romaji: "Abashiri Ryūhyō Kankō Saihyōsen Aurora",
    summary_zh:
      "網走灣冬季流氷觀光招牌砕冰船,1/20 ~ 4/3 左右運行。船體 491 噸、全長 45m,以船首鋼板推壓方式破冰前進,乘客可在甲板近距離觀流氷漂移、Clione(氷の妖精)、海鷲、虎頭海雕。",
    content_md:
      "- 運航期間:每年 1 月下旬 ~ 4 月上旬(依流氷來臨變動)\n- 乘船時間:約 1 時間\n- 料金:大人 ¥4,500 / 小學生 ¥2,250 / 幼兒免費(2024 年度)\n- 特別席:¥1,600 追加(展望席)\n- 出航:1 日 5-6 便(9:30/11:00/12:30/14:00/15:30 目安)\n- 出發港:道の駅「流氷街道網走」附屬第二埠頭\n- 觀覽動物:オオワシ(虎頭海雕)、オジロワシ、アザラシ、キタキツネ\n- Clione(氷の妖精):船上水族館展示\n- 防寒対策:船上氣溫 -5℃ ~ -15℃,レンタルコート有(¥1,000)\n- 交通:JR「網走駅」~ 網走バス 10 分「道の駅流氷街道網走」\n- 預約:春節·2 月最旺,建議 1 個月前;當天無流氷則改走一般觀光港\n- 姐妹船:春~秋期「知床 Aurora」在宇登呂港運行\n- 競合:紋別「ガリンコ号」(鋸齒式破冰,體感不同)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "網走市",
    lg_code: "01211",
    area_types: ["coast", "ice"],
    lat: 44.0242,
    lon: 144.2697,
    season_start: "2001-01-20",
    season_end: "2001-04-03",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      official: "https://ms-aurora.com/abashiri/",
    },
    tags: ["drift_ice", "icebreaker", "1hr_cruise", "steller_sea_eagle", "clione"],
    source: "manual",
  },
  {
    slug: "hokkaido-furano-biei-norokko",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "富良野・美瑛 NOROKKO 觀光列車",
    title_ja: "富良野・美瑛ノロッコ号",
    romaji: "Furano Biei Norokko",
    summary_zh:
      "1997 年運行開始,JR 北海道夏季限定觀光列車,行駛旭川~富良野區間。「ノロノロ走るトロッコ」(慢慢跑的車輛)之意,50 系客車改造開放式窗戶,經過薰衣草田時會減速,配車掌中文說明,是必搭的花田移動手段。",
    content_md:
      "- 運行期間:每年 6 月中 ~ 10 月上(依 JR 時刻表,會期每年告知)\n- 運行區間:旭川 ~ 美瑛 ~ 富良野(1 日 3 往復)\n- 所要:旭川 ~ 富良野 約 1 時間 40 分(普通列車 1 時間 20 分)\n- 料金:旭川~富良野乘車券 ¥1,290 + ノロッコ指定席特急券 ¥840\n- 臨時駅「ラベンダー畑駅」:薰衣草シーズン(6 月下 ~ 8 月上)時開放,ファーム富田徒步 5 分\n- 車輛:50 系改造オープンエア客車 × DE15 機關車牽引\n- 特色:最大看點區段減速行駛、木製內裝、展望臺窗\n- 附屬班:ピーク期併用「ふらの·びえい号」(キハ 183 系、ノロッコ滿席時予備)\n- 便利利用:上富良野下車 → フラワーランド / 中富良野下車 → ファーム富田 / 美瑛下車 → 青池\n- 予約:みどりの窓口 / JR 北海道網上 1 個月前 10:00 受付開始\n- 2020-22 COVID 中斷過一段,2023 復活",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "富良野市",
    lg_code: "01229",
    area_types: ["train", "countryside"],
    lat: 43.3455,
    lon: 142.3833,
    season_start: "2000-06-15",
    season_end: "2000-10-10",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/%E5%AF%8C%E8%89%AF%E9%87%8E%E3%83%BB%E7%BE%8E%E7%91%9B%E3%83%8E%E3%83%AD%E3%83%83%E3%82%B3%E5%8F%B7",
    },
    tags: ["jr_hokkaido", "sightseeing_train", "lavender_access", "open_air_car", "since_1997"],
    source: "manual",
  },

  // ── aquarium_zoo 追加 1 筆(円山動物園) ──────────
  {
    slug: "hokkaido-maruyama-zoo",
    category: "entertainment",
    sub_type: "aquarium_zoo",
    title_zh: "札幌市円山動物園",
    title_ja: "札幌市円山動物園",
    romaji: "Sapporo-shi Maruyama Dōbutsuen",
    summary_zh:
      "1951 年開園,北海道最大、日本最北的正規動物園。22.5 公頃,約 169 種動物。2018 年新象舍(泰國 4 頭象)、2024 年 5 月新「オランウータンとボルネオの森」開放,是札幌親子行程必訪,地下鐵直達。",
    content_md:
      "- 開園:1951 年 5 月 5 日(初為「児童遊園」、1952 正式動物園)\n- 時間:3 月-10 月 9:30-16:30 / 11 月-2 月 9:30-16:00(閉園 30 分前入園)\n- 休園日:4 月 / 11 月 第 2 水-木、12/29-31、每月第 2 第 4 水\n- 入園料:成人 ¥800 / 高校生 ¥400 / 中學生以下免費 / 札幌市民 70 歲以上免費\n- 動物種:169 種 / 約 770 隻(2018 年 4 月)\n- 面積:22.5 公頃\n- 主要設施:\n  - ゾウ舎「象舎」:2018 新築,4 頭のタイ象\n  - ホッキョクグマ館(2000 年以來北海道最多繁殖實績)\n  - アムールトラ、ユキヒョウ、レッサーパンダ\n  - オランウータンとボルネオの森:2024/5 開放,最新設施\n  - 熱帯動物館、アフリカゾーン\n- 交通:地下鉄東西線「円山公園駅」徒步 15 分\n- 車:中央自動車道 札幌北 IC 20 分;園內駐車 ¥700\n- 鄰接:円山公園、北海道神宮(可與 sakura 條目串聯)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban", "park"],
    lat: 43.0519,
    lon: 141.3094,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 0,
    closed_days: ["2nd_wed", "2nd_thu_apr_nov", "12/29-31"],
    external_urls: {
      official: "https://www.city.sapporo.jp/zoo/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E6%9C%AD%E5%B9%8C%E5%B8%82%E5%86%86%E5%B1%B1%E5%8B%95%E7%89%A9%E5%9C%92",
    },
    tags: ["169_species", "northernmost_zoo", "polar_bear_breeding", "since_1951", "near_jingu"],
    source: "manual",
  },

  // ── sports_spectate 追加 2 筆 ────────────────────
  {
    slug: "hokkaido-consadole-sapporo",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "北海道 Consadole 札幌(足球)",
    title_ja: "北海道コンサドーレ札幌",
    romaji: "Hokkaidō Consadole Sapporo",
    summary_zh:
      "J2 所屬足球俱樂部,主場「大和ハウス プレミストドーム(札幌ドーム)」容量 38,794 人。1935 年前身「東芝堀川町」1996 年移至札幌,是 Escon Field 雙雄(與日本火腿)之一,吉祥物 Dōre-kun(島梟)。",
    content_md:
      "- 賽季:3 月 ~ 12 月(30+ 主場戰)\n- 主場:大和ハウス プレミストドーム(札幌ドーム,容量 38,794)\n- 副場:厚別公園競技場(氣候適合屋外用;容量 20,084)\n- 練習場:宮の沢白い恋人サッカー場(白色戀人公園併設,可自由見學)\n- 聯盟:2025 シーズン J2 12 位(2024 降格 J1 → J2)\n- 歷史:1935 年「東芝堀川町サッカー部」創部、1996 札幌移轉、1998 J 聯盟加盟\n- 吉祥物:ドーレくん(島梟モチーフ)、ちょこさん(ドーレくん妹)\n- チケット:¥2,000 ~ ¥15,000(自由席 ~ SS 席)\n- 交通:札幌ドーム = 地下鉄東豊線「福住駅」徒步 10 分;厚別 = JR「新札幌駅」徒步 30 分(シャトルバス有)\n- 2023 曾為 AFC Champions League 參戰\n- 觀戰文化:道產子熱烈,主場應援歌「We're SAPPORO」在北海道青年耳熟能詳",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban", "stadium"],
    lat: 42.9850,
    lon: 141.4100,
    season_start: "2000-03-01",
    season_end: "2000-12-10",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      official: "https://www.consadole-sapporo.jp/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E5%8C%97%E6%B5%B7%E9%81%93%E3%82%B3%E3%83%B3%E3%82%B5%E3%83%89%E3%83%BC%E3%83%AC%E6%9C%AD%E5%B9%8C",
    },
    tags: ["jleague", "j2", "sapporo_dome", "shiro_koibito", "dore_kun"],
    source: "manual",
  },
  {
    slug: "hokkaido-levanga-hokkaido",
    category: "entertainment",
    sub_type: "sports_spectate",
    title_zh: "Levanga 北海道(籃球)",
    title_ja: "レバンガ北海道",
    romaji: "Levanga Hokkaidō",
    summary_zh:
      "B.LEAGUE Division 1(東 Conference)所屬籃球俱樂部,主場「北海きたえーる」。2011 年前身「レラカムイ」再編後由折茂武彥組成選手經營型俱樂部,2024/12/28 在 Escon Field 締造 B リーグ史上最高動員 19,762 人紀錄。",
    content_md:
      "- 賽季:10 月 ~ 4 月(60 試合,30 主場)\n- 主場:北海道立総合体育センター(北海きたえーる,容量 10,000)\n- 副場:白老町、千歳市、ESCON FIELD(特別試合)\n- 聯盟:B.LEAGUE Division 1 East\n- 團隊色:綠、薰衣草紫、金\n- 團名由來:「頑張れ」逆讀的バックネーム\n- 歷史:2007 レラカムイ北海道創立 → 2011 經營破綻 → 折茂武彥結成レバンガ\n- 2024/12/28:Escon Field 特別試合、19,762 人(B リーグ史上最高)\n- 2026-27 目標:B.LEAGUE PREMIER 加盟(需 2028/9 前アリーナ増設)\n- チケット:¥2,500 ~ ¥10,000\n- 交通:北海きたえーる = 地下鉄東豊線「豊平公園駅」徒步 8 分\n- ファンクラブ特典:主場優先、Discord 交流\n- 選手經營型:日本唯一,折茂武彥仍為筆頭株主",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban", "arena"],
    lat: 43.0306,
    lon: 141.3883,
    season_start: "2000-10-05",
    season_end: "2001-04-30",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {
      official: "https://www.levanga.com/",
      wikipedia: "https://ja.wikipedia.org/wiki/%E3%83%AC%E3%83%90%E3%83%B3%E3%82%AC%E5%8C%97%E6%B5%B7%E9%81%93",
    },
    tags: ["bleague", "b1", "kitaeru_arena", "orimo_takehiko", "record_attendance_19762"],
    source: "manual",
  },

  // ── music_festival 追加 1 筆(JOIN ALIVE) ────────
  {
    slug: "hokkaido-join-alive",
    category: "entertainment",
    sub_type: "music_festival",
    title_zh: "JOIN ALIVE 音樂祭",
    title_ja: "JOIN ALIVE",
    romaji: "JOIN ALIVE",
    summary_zh:
      "2010 年首屆,岩見沢「いわみざわ公園」為會場的夏季音樂祭,「J」+「O」+「I」+「N」代表 July、Oasis、Iwamizawa、Nature。主舞台 ROSE STAGE 14,000 人、遊園地共存「ピクニック型フェス」特色,2024 年 2 日動員約 3.8 萬人。",
    content_md:
      "- 開催:每年 7 月中 ~ 下旬週末 2 日(2025 年 7/19-20)\n- 會場:北海道 岩見沢市「いわみざわ公園」(北海道グリーンランド遊園地隣接)\n- 主催:Mount Alive(HTB 北海道テレビ系列)\n- 舞台構成:\n  - ROSE STAGE(主,容量 14,000)\n  - VELVET CIRCUS(4,000)\n  - FUTURE FLOWERS(4,000)\n  - NEO WALTZ(2,000)\n  - MIRACLE LEAF\n- 2 日通票:¥20,000 前後(露營別途 ¥6,000)\n- 單日:¥12,000 前後\n- 歷代出演:BUMP OF CHICKEN、ONE OK ROCK、Perfume、Suchmos、あいみょん、きゃりーぱみゅぱみゅ\n- 動員:年 3-4 萬人(2024 約 38,000)\n- 交通:札幌駅 / 旭川駅 有料シャトルバス 約 1 時間;JR「岩見沢駅」車 20 分\n- 遊園地同時開放:祭チケで北海道グリーンランド 入園無料\n- 2020-21 COVID 中止 → 2022/9 復活 → 2023 回歸 7 月",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "岩見沢市",
    lg_code: "01210",
    area_types: ["park", "outdoor"],
    lat: 43.2014,
    lon: 141.7678,
    season_start: "2000-07-15",
    season_end: "2000-07-25",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 120,
    closed_days: [],
    external_urls: {
      wikipedia: "https://ja.wikipedia.org/wiki/JOIN_ALIVE",
    },
    tags: ["picnic_fes", "family_friendly", "14000_cap", "greenland_adjacent", "htb"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // 老卷補完 expansion(2026-04-29・66 → 74)
  // ══════════════════════════════════════════════════════════════════
  {
    slug: "okhotsk-monbetsu-garinko-go",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ガリンコ号(紋別流氷砕氷船・冬期 1-3 月・オホーツク海最大氷上体験)",
    title_ja: "ガリンコ号",
    romaji: "Garinko-go",
    summary_zh:
      "オホーツク海紋別市の流氷砕氷船。1987 初代ガリンコ号 → 1997 ガリンコ号 II → 2021 ガリンコ号 III と進化。1-3 月のオホーツク流氷期に運航,船首の巨大ドリル(アルキメデススクリュー)で氷を砕きながら進む独自設計。網走の砕冰船と並ぶ流氷観光の双璧。1 便 ¥3500-5000。",
    content_md:
      "- 運航期:1-3 月(流氷期)\n- 立地:紋別港\n- ドリル砕氷(アルキメデススクリュー)\n- ガリンコ号 III(2021)\n- 1 便:¥3500-5000\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "紋別市",
    lg_code: "01219",
    area_types: ["coastal"],
    lat: 44.345,
    lon: 143.353,
    season_start: "2027-01-15",
    season_end: "2027-03-31",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["icebreaker", "garinko", "monbetsu", "okhotsk", "ryuhyo"],
    source: "manual",
  },
  {
    slug: "shikaribetsu-kotan-winter",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "然別湖コタン(冬期氷上集落・1980 年代開設・1 月-3 月限定)",
    title_ja: "然別湖コタン",
    romaji: "Shikaribetsu-ko Kotan",
    summary_zh:
      "鹿追町然別湖の冬期氷上集落。1980 年代開設・1 月下旬-3 月下旬に湖が完全結氷した上に氷の集落(露天風呂 + バー + 教会 + igloo 等)を毎年再建する希有のイベント。北海道独特の冬期観光体験。",
    content_md:
      "- 期間:1 月下旬-3 月下旬\n- 立地:鹿追町然別湖\n- 開設:1980 年代-\n- 氷上集落:露天風呂 + バー + 教会 + igloo\n- 入村:¥1500\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "河東郡",
    municipality_ja: "鹿追町",
    lg_code: "01631",
    area_types: ["mountain", "rural"],
    lat: 43.222,
    lon: 143.103,
    season_start: "2027-01-25",
    season_end: "2027-03-25",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["winter_event", "shikaribetsu", "kotan", "ice_village", "since_1980s"],
    source: "manual",
  },
  {
    slug: "akan-ainu-kotan",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "阿寒湖アイヌコタン(120 人余アイヌ集落・古式舞踊 + 民芸品)",
    title_ja: "阿寒湖アイヌコタン",
    romaji: "Akan Ainu Kotan",
    summary_zh:
      "釧路市阿寒湖温泉街隣接のアイヌ民族集落。北海道最大級のアイヌコタン(集落)で 120 人余のアイヌが居住。古式舞踊『アイヌ古式舞踊』(2009 ユネスコ世界遺産)+ アイヌ民芸品(木彫・刺繍)+ アイヌシアター『イコㇿ』で観光客向け実演。アイヌ文化体験のメイン地。",
    content_md:
      "- 立地:阿寒湖温泉街隣接\n- 規模:120 人余アイヌ居住\n- 古式舞踊:2009 ユネスコ無形文化遺産\n- アイヌシアター『イコㇿ』:¥1500\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "釧路市",
    lg_code: "01206",
    area_types: ["mountain", "rural"],
    lat: 43.451,
    lon: 144.097,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.akanainu.jp/" },
    tags: ["ainu_kotan", "akan", "unesco_intangible", "traditional_dance"],
    source: "manual",
  },
  {
    slug: "shiretoko-cruise-summer",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "知床クルーズ(知床国立公園・世界自然遺産・夏期 6-9 月遊覧)",
    title_ja: "知床クルーズ",
    romaji: "Shiretoko Cruise",
    summary_zh:
      "2005 ユネスコ世界自然遺産登録の知床国立公園を海から見るクルーズ。ウトロ港発・カムイワッカの滝 → 知床岬の北 100 km コース。所要 1.5-3.5 時間・¥3500-9000。野生ヒグマ + 知床山系 + カムイワッカの滝(40 m)観賞。夏期 6 月-9 月が運航期。",
    content_md:
      "- 期間:6-9 月\n- 出航:ウトロ港(斜里町)\n- 知床国立公園(2005 世界自然遺産)\n- 所要:1.5-3.5 時間\n- 価格:¥3500-9000\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "斜里郡",
    municipality_ja: "斜里町",
    lg_code: "01544",
    area_types: ["coastal", "mountain"],
    lat: 44.078,
    lon: 144.985,
    season_start: "2026-06-01",
    season_end: "2026-09-30",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://www.ms-aurora.com/shiretoko/" },
    tags: ["cruise", "shiretoko", "world_heritage", "ezo_higuma", "kamuiwakka"],
    source: "manual",
  },
  {
    slug: "nikka-yoichi-distillery-1934",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "ニッカウヰスキー余市蒸溜所(1934 創業・登録有形文化財 9 件・無料見学)",
    title_ja: "ニッカウヰスキー余市蒸溜所",
    romaji: "Nikka Whisky Yoichi Distillery",
    summary_zh:
      "1934 余市町に創業した日本初の本格ウイスキー蒸溜所(竹鶴政孝創業・NHK 朝ドラ『マッサン』2014-15 のモデル)。創業当時の石造建築物 9 件が国登録有形文化財。蒸溜棟 + 旧事務所 + リタハウス(竹鶴の妻リタの旧居)等。蒸溜見学 + 試飲 + ショップ無料。年間 70 万人来訪。",
    content_md:
      "- 創業:1934(日本初本格ウイスキー)\n- 創業者:竹鶴政孝(マッサン モデル)\n- 9 件 国登録有形文化財\n- 入場:無料(試飲込)\n- 営業:9:00-17:00 月曜休\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "余市郡",
    municipality_ja: "余市町",
    lg_code: "01408",
    area_types: ["urban", "rural"],
    lat: 43.193,
    lon: 140.785,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: ["mon"],
    external_urls: { official: "https://www.nikka.com/distilleries/yoichi/" },
    tags: ["distillery", "nikka", "yoichi", "since_1934", "登録文化財", "massan"],
    source: "manual",
  },
  {
    slug: "sapporo-odori-beer-garden",
    category: "entertainment",
    sub_type: "music_festival",
    title_zh: "札幌大通ビアガーデン(8 月・大通公園・北海道最大級ビアガーデン)",
    title_ja: "札幌大通ビアガーデン",
    romaji: "Sapporo Odori Beer Garden",
    summary_zh:
      "毎年 8 月初-中旬に札幌大通公園 5-11 丁目で開催される北海道最大級ビアガーデン。サッポロ + アサヒ + キリン + サントリー + 海外クラフトビールの 5 ゾーンで,1 万人余の同時開催規模。1981 札幌夏まつり同時開始の歴史。動員 100 万人余。",
    content_md:
      "- 開催:8 月初-中旬\n- 立地:大通公園 5-11 丁目\n- 規模:北海道最大級\n- 5 ゾーン(サッポロ + アサヒ + キリン + サントリー + クラフト)\n- 動員:100 万人余\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban_central"],
    lat: 43.060,
    lon: 141.354,
    season_start: null,
    season_end: null,
    event_start: "2026-08-01",
    event_end: "2026-08-15",
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["beer_garden", "sapporo_odori", "since_1981", "summer_festival"],
    source: "manual",
  },
  {
    slug: "hakodate-yunokawa-onsen-1453",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "函館湯の川温泉(1453 開湯・北海道最古温泉郷・函館湾沿)",
    title_ja: "函館湯の川温泉",
    romaji: "Hakodate Yunokawa Onsen",
    summary_zh:
      "1453(享徳 2 年)開湯と伝の北海道最古温泉郷。函館市湯川町(函館湾東部)に立地,500 年余の歴史。津軽藩主松前氏の湯治場として発展,現在 30 軒余の旅館 + ホテル + 公衆湯(湯の川公衆浴場 + 河童の湯 等)集積の温泉郷。函館空港バス 5 分・市電湯の川温泉駅徒歩 5 分。",
    content_md:
      "- 開湯:1453(北海道最古温泉郷)\n- 立地:函館市湯川町\n- 旅館・ホテル:30 軒余\n- 公衆湯:湯の川公衆浴場・河童の湯\n- 函館空港バス 5 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["urban", "coastal"],
    lat: 41.785,
    lon: 140.788,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://hakodate-yunokawa.jp/" },
    tags: ["onsen_town", "yunokawa", "hakodate", "since_1453", "hokkaido_oldest"],
    source: "manual",
  },
  {
    slug: "mashu-ko-observatory",
    category: "entertainment",
    sub_type: "theme_park",
    title_zh: "摩周湖第三展望台(神秘湖・透明度世界 1 位 1931 + アイヌ霊湖・夜景百選)",
    title_ja: "摩周湖第三展望台",
    romaji: "Mashū-ko Observatory",
    summary_zh:
      "弟子屈町阿寒摩周国立公園内の摩周湖展望台。1931 透明度 41.6 m を計測した世界最高透明度湖(後のバイカル湖発見で世界 2 位)。アイヌ霊湖『神の山の湖』として古来神聖視。第三展望台が眺望最良で,夜は満天星空 + 摩周湖の夜景百選。",
    content_md:
      "- 1931 透明度 41.6 m(当時世界 1 位)\n- アイヌ霊湖\n- 第三展望台が眺望最良\n- 夜景百選(満天星空)\n- 入場:24h 無料\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "川上郡",
    municipality_ja: "弟子屈町",
    lg_code: "01665",
    area_types: ["mountain", "rural"],
    lat: 43.587,
    lon: 144.504,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["scenic", "mashu_ko", "world_clearest", "ainu_sacred", "yakei_100"],
    source: "manual",
  },
];

async function main() {
  console.log(`[seed] ${rows.length} rows to seed`);

  const byKind: Record<string, number> = {};
  for (const r of rows) byKind[r.sub_type] = (byKind[r.sub_type] ?? 0) + 1;
  console.log(`[seed] by sub_type: ${JSON.stringify(byKind)}`);

  if (DRY) {
    console.log("[seed] --dry-run, samples:");
    for (const r of rows) {
      console.log(
        `  [${r.sub_type.padEnd(18)}] ${r.title_zh} (${r.municipality_ja ?? "-"}/${r.lg_code ?? "-"})`,
      );
    }
    return;
  }

  const sb = createAdminClient();
  const { data, error } = await sb
    .from("japan_entries")
    .upsert(rows, { onConflict: "slug" })
    .select("id, slug");
  if (error) {
    console.error("[seed] upsert failed", error);
    process.exit(1);
  }
  console.log(`[seed] upserted ${data?.length ?? 0} rows`);
  for (const r of data ?? []) {
    console.log(`  #${r.id}  ${r.slug}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
