// Seed 福島県 住 R1(20 筆 / Sprint 1.3)
// 会津温泉 4 / 福島市温泉 3 / 二本松+郡山温泉 3 / いわき+常磐 2 / 裏磐梯+猪苗代 3 / 都心ホテル 4 / 民宿 1 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "tohoku"; prefecture_ja: "福島県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 会津温泉 (4)
  { slug: "aizu-higashiyama-onsen", category: "lodging", sub_type: "fukushima_aizu_onsen", title_zh: "会津東山温泉(会津若松市・1300 年伝承(行基開湯)+ 「奥羽 3 名湯」(東山+秋保+飯坂)候補+ 全 28 軒老舗旅館+ R1 育 鶴ヶ城+R1 食 馬刺し観光拠点+ JR 会津若松駅 タクシー 10 分+ 1 泊 2 食 ¥15,500-32,000)", title_ja: "会津東山温泉", romaji: "Aizu Higashiyama Onsen", summary_zh: "**会津東山温泉は 1300 年伝承(行基開湯)・「奥羽 3 名湯」候補**(会津若松・**全 28 軒老舗**)。R1 育 鶴ヶ城+R1 食 馬刺し拠点、¥15,500-32,000。", content_md: "- 立地:**会津若松市**(JR 会津若松駅 タクシー 10 分)\n- 起源:**1300 年伝承(行基開湯)**\n- 認定:**「奥羽 3 名湯」候補**(東山 + 秋保(宮城) + 飯坂(福島))\n- 規模:**全 28 軒老舗旅館**\n- 並列観光:**R1 育 鶴ヶ城 + R1 食 馬刺し**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["onsen_field"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["higashiyama_onsen", "1300_years", "ouu_3_meito"], source: "manual" },
  { slug: "ashinomaki-onsen-aizu", category: "lodging", sub_type: "fukushima_aizu_onsen", title_zh: "芦ノ牧温泉(会津若松市・1192 鎌倉期発祥 833 年+ 大川渓谷沿+ 全 13 軒旅館+ R1 育 大内宿+R1 育 塔のへつり 観光拠点+ JR 会津鉄道線 芦ノ牧温泉駅 連絡バス+ 1 泊 2 食 ¥13,500-22,500+ 「猫駅長」全国知名度)", title_ja: "芦ノ牧温泉", romaji: "Ashinomaki Onsen", summary_zh: "**芦ノ牧温泉は 1192 鎌倉期発祥 833 年**(会津若松・**大川渓谷沿+全 13 軒**)。R1 育 大内宿+塔のへつり拠点、「猫駅長」全国知名度、¥13,500-22,500。", content_md: "- 立地:**会津若松市**(JR 会津鉄道 芦ノ牧温泉駅 連絡バス)\n- 起源:**1192 鎌倉期発祥 833 年**\n- 規模:**全 13 軒旅館・大川渓谷沿**\n- 看板:**「猫駅長」全国知名度**\n- 並列:**R1 育 大内宿 + 塔のへつり**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["onsen_field", "scenic_spot"], lat: 37.3667, lon: 139.9417, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["ashinomaki", "1192_kamakura", "neko_ekicho"], source: "manual" },
  { slug: "yunokami-onsen-shimogo", category: "lodging", sub_type: "fukushima_aizu_onsen", title_zh: "湯野上温泉(南会津郡下郷町・1300 年伝承+ 茅葺駅舎・JR 会津鉄道線 湯野上温泉駅で全国唯一+ 全 9 軒小規模+ R1 育 大内宿 観光拠点+ 1 泊 2 食 ¥10,500-15,500+ 鄙びた湯治場代表)", title_ja: "湯野上温泉", romaji: "Yunokami Onsen", summary_zh: "**湯野上温泉は 1300 年伝承・茅葺駅舎全国唯一**(下郷町・**全 9 軒小規模**)。R1 育 大内宿拠点、¥10,500-15,500、鄙びた湯治場代表。", content_md: "- 立地:**南会津郡下郷町**(JR 会津鉄道 湯野上温泉駅・茅葺駅舎全国唯一)\n- 起源:**1300 年伝承**\n- 規模:**全 9 軒小規模**\n- 並列:**R1 育 大内宿 観光拠点**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "南会津郡", municipality_ja: "下郷町", lg_code: "07362", area_types: ["onsen_field"], lat: 37.3258, lon: 139.8606, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["yunokami_onsen", "1300_years", "kayabuki_station"], source: "manual" },
  { slug: "higashiyama-mukaitaki-1873", category: "lodging", sub_type: "fukushima_aizu_onsen", title_zh: "向瀧旅館(会津東山温泉・1873 創業 152 年+ 国登録有形文化財建造物+ 全 22 室+ R1 住 会津東山温泉郷代表 老舗+ R1 食 こづゆ+馬刺し会席+ 1 泊 2 食 ¥35,000-65,000+ R1 育 鶴ヶ城 タクシー 10 分)", title_ja: "向瀧", romaji: "Mukaitaki", summary_zh: "**向瀧は 1873 創業 152 年・国登録有形文化財建造物**(東山温泉・**全 22 室**)。R1 住 東山温泉郷代表、R1 食 こづゆ+馬刺し会席、¥35,000-65,000。", content_md: "- 立地:**会津若松市東山温泉**(R1 住 東山温泉郷)\n- 起源:**1873 創業 152 年**\n- 認定:**国登録有形文化財建造物**\n- 規模:**全 22 室**\n- 食事:**R1 食 こづゆ + 馬刺し会席**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "会津若松市", lg_code: "07202", area_types: ["onsen_field"], lat: 37.4944, lon: 139.9300, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 90, closed_days: [], external_urls: { official: "https://www.mukaitaki.com/" }, tags: ["mukaitaki", "1873", "152_years", "kuniroku"], source: "manual" },

  // 福島市温泉 (3)
  { slug: "iizaka-onsen-fukushima", category: "lodging", sub_type: "fukushima_fukushima_chuou", title_zh: "飯坂温泉(福島市・1990 年伝承(日本武尊由来候補)+ 「奥羽 3 名湯」(秋保+鳴子+飯坂 vs 東山候補)+ 全 30+ 軒旅館+ JR 福島交通飯坂線 飯坂温泉駅+ R1 食 円盤餃子+R1 食 桃観光客向け+ 1 泊 2 食 ¥12,500-22,500)", title_ja: "飯坂温泉", romaji: "Iizaka Onsen", summary_zh: "**飯坂温泉は 1990 年伝承(日本武尊候補)・「奥羽 3 名湯」**(福島市・**全 30+ 軒+JR 福島交通飯坂線**)。R1 食 円盤餃子+桃観光、¥12,500-22,500。", content_md: "- 立地:**福島市飯坂**(JR 福島交通飯坂線 飯坂温泉駅)\n- 起源:**1990 年伝承(日本武尊由来候補)**\n- 認定:**「奥羽 3 名湯」**(秋保 + 鳴子 + 飯坂)\n- 規模:**全 30+ 軒旅館**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["onsen_field"], lat: 37.8244, lon: 140.4633, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["iizaka_onsen", "1990_years", "ouu_3_meito"], source: "manual" },
  { slug: "takayu-onsen-fukushima", category: "lodging", sub_type: "fukushima_fukushima_chuou", title_zh: "高湯温泉(福島市・1607 江戸期発祥 418 年+ 全 8 軒小規模旅館+ 「日本秘湯を守る会」加盟+ 標高 750m 山中・含硫黄温泉+ R1 楽 浄土平+磐梯吾妻スカイライン拠点+ 1 泊 2 食 ¥13,500-22,500)", title_ja: "高湯温泉", romaji: "Takayu Onsen", summary_zh: "**高湯温泉は 1607 江戸期発祥 418 年**(福島市・**全 8 軒+「日本秘湯を守る会」加盟**)。標高 750m 含硫黄温泉、R1 楽 浄土平+磐梯吾妻スカイライン拠点、¥13,500-22,500。", content_md: "- 立地:**福島市高湯**\n- 起源:**1607 江戸期発祥 418 年**\n- 認定:**「日本秘湯を守る会」加盟**\n- 規模:**全 8 軒小規模旅館・標高 750m 山中・含硫黄温泉**\n- 並列:**R1 楽 浄土平 + 磐梯吾妻スカイライン**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["onsen_field", "mountain_village"], lat: 37.7333, lon: 140.3247, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["takayu_onsen", "1607", "418_years", "hito_mamoru_kai"], source: "manual" },
  { slug: "tsuchiyu-onsen-fukushima", category: "lodging", sub_type: "fukushima_fukushima_chuou", title_zh: "土湯温泉(福島市・1300 年伝承(行基開湯候補)+ R1 衣 土湯系こけし発祥地+ 全 16 軒旅館+ 全国 11 系統こけし発祥地+ 1 泊 2 食 ¥12,500-18,500+ R1 楽 浄土平+磐梯吾妻スカイライン拠点+ JR 福島駅バス 40 分)", title_ja: "土湯温泉", romaji: "Tsuchiyu Onsen", summary_zh: "**土湯温泉は 1300 年伝承(行基開湯候補)・R1 衣 こけし発祥地**(福島市・**全 16 軒**)。全国 11 系統こけし発祥、R1 楽 浄土平拠点、¥12,500-18,500。", content_md: "- 立地:**福島市土湯**(JR 福島駅バス 40 分)\n- 起源:**1300 年伝承(行基開湯候補)**\n- 並列:**R1 衣 土湯系こけし発祥地・全国 11 系統発祥**\n- 規模:**全 16 軒旅館**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["onsen_field"], lat: 37.7000, lon: 140.3500, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["tsuchiyu_onsen", "1300_years", "kokeshi_origin"], source: "manual" },

  // 二本松+郡山温泉 (3)
  { slug: "dake-onsen-nihonmatsu", category: "lodging", sub_type: "fukushima_other_onsen", title_zh: "岳温泉(二本松市・1500 年伝承(坂上田村麻呂由来候補)+ 全 8 軒旅館+ R1 育 安達太良山登山口+ R1 食 大七酒造観光拠点+ 1 泊 2 食 ¥12,500-18,500+ JR 東北本線 二本松駅 タクシー 25 分)", title_ja: "岳温泉", romaji: "Dake Onsen", summary_zh: "**岳温泉は 1500 年伝承(坂上田村麻呂候補)**(二本松・**全 8 軒+R1 育 安達太良山登山口**)。R1 食 大七酒造拠点、¥12,500-18,500、JR 二本松駅タクシー 25 分。", content_md: "- 立地:**二本松市**(JR 二本松駅 タクシー 25 分)\n- 起源:**1500 年伝承(坂上田村麻呂由来候補)**\n- 規模:**全 8 軒**\n- 並列:**R1 育 安達太良山登山口 + R1 食 大七酒造**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "二本松市", lg_code: "07210", area_types: ["onsen_field", "mountain_village"], lat: 37.5847, lon: 140.4314, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["dake_onsen", "1500_years"], source: "manual" },
  { slug: "iwakiyu-onsen-koriyama", category: "lodging", sub_type: "fukushima_other_onsen", title_zh: "磐梯熱海温泉(郡山市・900 年伝承+ JR 磐越西線 磐梯熱海駅 直結+ 全 12 軒旅館+ R1 育 磐梯山+R1 楽 猪苗代湖観光拠点+ R1 行 東北新幹線郡山駅から 20 分+ 1 泊 2 食 ¥12,500-22,500)", title_ja: "磐梯熱海温泉", romaji: "Bandai Atami Onsen", summary_zh: "**磐梯熱海温泉は 900 年伝承**(郡山・**JR 磐越西線磐梯熱海駅直結+全 12 軒**)。R1 育 磐梯山+R1 楽 猪苗代湖拠点、¥12,500-22,500、新幹線郡山駅 20 分。", content_md: "- 立地:**郡山市**(JR 磐越西線 磐梯熱海駅直結)\n- 起源:**900 年伝承**\n- 規模:**全 12 軒旅館**\n- 並列:**R1 育 磐梯山 + R1 楽 猪苗代湖 拠点**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "郡山市", lg_code: "07203", area_types: ["onsen_field"], lat: 37.5836, lon: 140.2628, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["bandai_atami", "900_years"], source: "manual" },
  { slug: "tamagawa-onsen-fukushima", category: "lodging", sub_type: "fukushima_other_onsen", title_zh: "玉梨温泉+ 沼沢湖周辺温泉郷(大沼郡金山町・1300 年伝承+ 県南部山中秘湯+ 全 5 軒小規模+ R1 育 沼沢湖+只見線観光拠点+ 1 泊 2 食 ¥10,500-15,500+ JR 只見線 会津川口駅 連絡バス)", title_ja: "玉梨温泉+沼沢湖温泉郷", romaji: "Tamagayama Onsen", summary_zh: "**玉梨温泉+沼沢湖温泉郷は 1300 年伝承**(金山・**県南部山中秘湯+全 5 軒**)。R1 育 沼沢湖+R6 行 只見線拠点、¥10,500-15,500。", content_md: "- 立地:**大沼郡金山町**(JR 只見線 会津川口駅 連絡バス)\n- 起源:**1300 年伝承**\n- 規模:**全 5 軒小規模・県南部山中秘湯**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "大沼郡", municipality_ja: "金山町", lg_code: "07445", area_types: ["onsen_field", "mountain_village"], lat: 37.4519, lon: 139.5106, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["tamagawa_onsen", "1300_years", "tadami"], source: "manual" },

  // いわき+常磐 (2)
  { slug: "iwaki-yumoto-onsen", category: "lodging", sub_type: "fukushima_iwaki_onsen", title_zh: "いわき湯本温泉(いわき市・1300 年伝承(白鳥伝説起源)+ 「奥羽 3 古湯」(湯本+秋保+鳴子)候補+ R1 育 R1 楽 スパリゾートハワイアンズ 1966 拠点+ 全 22 軒旅館+ 1 泊 2 食 ¥12,500-18,500+ JR 常磐線 湯本駅徒歩)", title_ja: "いわき湯本温泉", romaji: "Iwaki Yumoto Onsen", summary_zh: "**いわき湯本温泉は 1300 年伝承(白鳥伝説起源)・「奥羽 3 古湯」候補**(いわき・**全 22 軒**)。R1 楽 スパハワイアンズ 1966 拠点、¥12,500-18,500、JR 湯本駅徒歩。", content_md: "- 立地:**いわき市**(JR 常磐線 湯本駅徒歩)\n- 起源:**1300 年伝承(白鳥伝説起源)**\n- 認定:**「奥羽 3 古湯」候補**(湯本 + 秋保 + 鳴子)\n- 規模:**全 22 軒旅館**\n- 並列観光:**R1 楽 スパリゾートハワイアンズ 1966 拠点**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "いわき市", lg_code: "07204", area_types: ["onsen_field"], lat: 37.0539, lon: 140.8869, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["iwaki_yumoto", "1300_years", "ouu_3_kokuon"], source: "manual" },
  { slug: "spa-resort-hawaiians-1966", category: "lodging", sub_type: "fukushima_iwaki_onsen", title_zh: "スパリゾートハワイアンズ(いわき市・1966 開業 59 年「常磐ハワイアンセンター」起源+ 全国唯一複合温泉リゾート+ ハワイアンショー+プール+温泉+ ホテルハワイアンズ 全 580 室+ 1 泊 2 食 ¥18,500-32,000+ R1 楽 観光複合代表)", title_ja: "スパリゾートハワイアンズ", romaji: "Spa Resort Hawaiians", summary_zh: "**スパリゾートハワイアンズは 1966 開業「常磐ハワイアンセンター」起源・全国唯一複合温泉リゾート**(いわき・**ハワイアンショー+プール+温泉+全 580 室**)。¥18,500-32,000。", content_md: "- 立地:**いわき市**\n- 起源:**1966 開業 59 年「常磐ハワイアンセンター」**\n- 認定:**全国唯一複合温泉リゾート**\n- 規模:**ハワイアンショー + プール + 温泉 + ホテル全 580 室**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "いわき市", lg_code: "07204", area_types: ["onsen_field", "festival_event"], lat: 37.0539, lon: 140.8869, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 90, closed_days: [], external_urls: { official: "https://www.hawaiians.co.jp/" }, tags: ["hawaiians", "1966", "59_years", "580_rooms"], source: "manual" },

  // 裏磐梯+猪苗代 (3)
  { slug: "urabandai-resort", category: "lodging", sub_type: "fukushima_other_onsen", title_zh: "裏磐梯リゾートホテル群(耶麻郡北塩原村・1888 磐梯山噴火後形成湖沼地帯+ R1 楽 五色沼+R1 育 諸橋近代美術館 観光拠点+ 全 25+ 軒リゾート+ 1 泊 2 食 ¥15,500-32,000+ JR 磐越西線 猪苗代駅 連絡バス)", title_ja: "裏磐梯リゾート", romaji: "Urabandai Resort", summary_zh: "**裏磐梯リゾートホテル群は 1888 磐梯山噴火後湖沼地帯**(北塩原・**全 25+ 軒**)。R1 楽 五色沼+R1 育 諸橋近代美術館拠点、¥15,500-32,000。", content_md: "- 立地:**耶麻郡北塩原村**(JR 磐越西線 猪苗代駅 連絡バス)\n- 起源:**1888 磐梯山噴火後形成湖沼地帯**\n- 規模:**全 25+ 軒リゾート**\n- 並列観光:**R1 楽 五色沼 + R1 育 諸橋近代美術館(ダリ)**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "耶麻郡", municipality_ja: "北塩原村", lg_code: "07402", area_types: ["onsen_field", "scenic_spot"], lat: 37.6453, lon: 140.0853, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 4, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["urabandai", "1888_eruption", "25_resorts"], source: "manual" },
  { slug: "inawashiro-shore-resort", category: "lodging", sub_type: "fukushima_other_onsen", title_zh: "猪苗代湖畔リゾート(耶麻郡猪苗代町・標高 514m 湖+ 全国 4 大湖の一+ R1 育 野口英世記念館・諸橋近代美術館拠点+ 全 35+ 軒リゾート+民宿+ R1 楽 猪苗代スキー場併設+ 1 泊 2 食 ¥13,500-25,000)", title_ja: "猪苗代湖畔リゾート", romaji: "Inawashiro Shore Resort", summary_zh: "**猪苗代湖畔リゾートは標高 514m 全国 4 大湖の一**(猪苗代・**全 35+ 軒+民宿**)。R1 育 野口英世記念館+諸橋近代美術館+R1 楽 スキー場拠点、¥13,500-25,000。", content_md: "- 立地:**耶麻郡猪苗代町**(湖標高 514m)\n- 認定:**全国 4 大湖の一**\n- 規模:**全 35+ 軒リゾート + 民宿**\n- 並列観光:**R1 育 野口英世記念館 + 諸橋近代美術館 + R1 楽 猪苗代スキー場**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "耶麻郡", municipality_ja: "猪苗代町", lg_code: "07408", area_types: ["scenic_spot", "onsen_field"], lat: 37.5567, lon: 140.1058, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["inawashiro_resort", "514m", "japan_4_lakes"], source: "manual" },
  { slug: "nishi-aizu-shukubo", category: "lodging", sub_type: "fukushima_aizu_onsen", title_zh: "西会津温泉郷+宿坊群(耶麻郡西会津町+柳津町・江戸期+ 全 8 軒小規模旅館+ R1 育 喜多方蔵造り街並み+R1 食 喜多方ラーメン観光拠点+ JR 磐越西線 野沢駅 連絡バス+ 1 泊 2 食 ¥10,500-15,500)", title_ja: "西会津温泉+宿坊", romaji: "Nishi Aizu Onsen / Shukubo", summary_zh: "**西会津温泉+宿坊群は江戸期**(西会津+柳津・**全 8 軒**)。R1 育 喜多方蔵+R1 食 喜多方ラーメン観光拠点、¥10,500-15,500、JR 磐越西線野沢駅。", content_md: "- 立地:**耶麻郡西会津町 + 河沼郡柳津町**\n- 起源:**江戸期**\n- 規模:**全 8 軒小規模**\n- 並列:**R1 育 喜多方蔵造り + R1 食 喜多方ラーメン**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "耶麻郡", municipality_ja: "西会津町", lg_code: "07405", area_types: ["onsen_field"], lat: 37.6128, lon: 139.6736, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["nishi_aizu_shukubo"], source: "manual" },

  // 都心ホテル (4)
  { slug: "fukushima-station-hotel", category: "lodging", sub_type: "fukushima_fukushima_chuou", title_zh: "ホテル福島グリーンパレス(福島市・1990 開業+ 全 156 室+ JR 福島駅徒歩 8 分+ R1 衣 福島駅 S-PAL+R1 食 円盤餃子+桃観光拠点+ 1 泊朝食付 ¥9,500-13,500+ R1 行 東北新幹線福島駅連動)", title_ja: "ホテル福島グリーンパレス", romaji: "Fukushima Green Palace", summary_zh: "**ホテル福島グリーンパレスは 1990 開業**(福島市・**全 156 室+JR 福島駅徒歩 8 分**)。R1 衣 S-PAL+R1 食 円盤餃子+桃拠点、¥9,500-13,500。", content_md: "- 立地:**福島市**(JR 福島駅徒歩 8 分)\n- 起源:**1990 開業 35 年**\n- 規模:**全 156 室**\n- 並列観光:**R1 衣 福島駅 S-PAL + R1 食 円盤餃子 + 桃**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "福島市", lg_code: "07201", area_types: ["shopping_district"], lat: 37.7503, lon: 140.4683, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["green_palace", "1990", "156_rooms"], source: "manual" },
  { slug: "koriyama-station-view-hotel", category: "lodging", sub_type: "fukushima_fukushima_chuou", title_zh: "ホテルハマツ郡山(郡山市・1985 開業+ 全 282 室+ JR 郡山駅徒歩 5 分+ R1 食 薄皮饅頭(柏屋 1852 県内最古菓子店)観光拠点+ 1 泊朝食付 ¥9,500-15,500+ R1 行 東北新幹線郡山駅連動)", title_ja: "ホテルハマツ郡山", romaji: "Hotel Hamatsu Kōriyama", summary_zh: "**ホテルハマツ郡山は 1985 開業**(郡山・**全 282 室+JR 郡山駅徒歩 5 分**)。R1 食 薄皮饅頭(柏屋 1852)拠点、¥9,500-15,500、東北新幹線連動。", content_md: "- 立地:**郡山市**(JR 郡山駅徒歩 5 分)\n- 起源:**1985 開業 40 年**\n- 規模:**全 282 室**\n- 並列観光:**R1 食 薄皮饅頭(柏屋 1852)**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "郡山市", lg_code: "07203", area_types: ["shopping_district"], lat: 37.4006, lon: 140.3597, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["hamatsu_koriyama", "1985", "282_rooms"], source: "manual" },
  { slug: "richmond-koriyama-business", category: "lodging", sub_type: "fukushima_fukushima_chuou", title_zh: "リッチモンドホテル郡山駅前(郡山市・JR 郡山駅徒歩 1 分+ 2008 開業+ 全 187 室・全国チェーン+ 1 泊朝食付 ¥7,500-10,500+ R1 食 薄皮饅頭+ままどおる R1 食 観光客向け+ 価格手頃ビジネス代表)", title_ja: "リッチモンドホテル郡山駅前", romaji: "Richmond Kōriyama", summary_zh: "**リッチモンドホテル郡山駅前は JR 郡山駅徒歩 1 分・2008 開業**(全 187 室・全国チェーン)。¥7,500-10,500、R1 食 薄皮饅頭+ままどおる観光客、価格手頃。", content_md: "- 立地:**郡山市**(JR 郡山駅徒歩 1 分)\n- 起源:**2008 開業**\n- 規模:**全 187 室・全国チェーン**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "郡山市", lg_code: "07203", area_types: ["shopping_district"], lat: 37.4006, lon: 140.3597, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["richmond_koriyama", "2008", "187_rooms"], source: "manual" },
  { slug: "iwaki-business-hotel", category: "lodging", sub_type: "fukushima_iwaki_onsen", title_zh: "いわきグランドホテル+ホテル J-Style いわき(いわき市・1980-2005 開業+ 全 100-180 室+ JR 常磐線 いわき駅徒歩 5-8 分+ R1 食 メヒカリ+サンマ観光拠点+ R1 楽 アクアマリン+ハワイアンズ アクセス便+ 1 泊朝食付 ¥7,500-11,500)", title_ja: "いわきグランドホテル", romaji: "Iwaki Grand Hotel", summary_zh: "**いわきグランドホテル+J-Style は 1980-2005 開業**(いわき・**全 100-180 室+JR 常磐線いわき駅徒歩 5-8 分**)。R1 食 メヒカリ+サンマ+R1 楽 アクアマリン+ハワイアンズ拠点、¥7,500-11,500。", content_md: "- 立地:**いわき市**(JR 常磐線 いわき駅徒歩 5-8 分)\n- 起源:**1980-2005 開業**\n- 規模:**全 100-180 室**\n- 並列観光:**R1 食 メヒカリ + サンマ + R1 楽 アクアマリンふくしま + ハワイアンズ**", region: "tohoku", prefecture_ja: "福島県", gun_ja: null, municipality_ja: "いわき市", lg_code: "07204", area_types: ["shopping_district"], lat: 37.0539, lon: 140.8869, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["iwaki_grand", "1980_2005"], source: "manual" },

  // 民宿 (1)
  { slug: "ouchijuku-minshuku", category: "lodging", sub_type: "fukushima_aizu_onsen", title_zh: "大内宿民宿(南会津郡下郷町・R1 育 大内宿 1640 江戸宿場町 重伝建 1981+ 茅葺民家改装宿+ 全 8 軒民宿+ 1 泊 2 食 ¥12,500-18,500+ R1 食 高遠そば+焼き餅会席+ 海外観光客 SNS 拡散代表+ 江戸期宿場体験)", title_ja: "大内宿民宿", romaji: "Ōuchijuku Minshuku", summary_zh: "**大内宿民宿は R1 育 大内宿 1640 重伝建 1981・茅葺民家改装**(下郷町・**全 8 軒**)。R1 食 高遠そば+焼き餅会席、¥12,500-18,500、SNS 拡散、江戸期宿場体験。", content_md: "- 立地:**南会津郡下郷町大内宿**(R1 育 大内宿)\n- 関係:**R1 育 大内宿 1640 江戸宿場町 重伝建 1981 派生**\n- 構造:**茅葺民家改装宿**\n- 規模:**全 8 軒民宿**\n- 食事:**R1 食 高遠そば + 焼き餅会席**", region: "tohoku", prefecture_ja: "福島県", gun_ja: "南会津郡", municipality_ja: "下郷町", lg_code: "07362", area_types: ["history_site_castle", "onsen_field"], lat: 37.3258, lon: 139.8606, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["ouchijuku_minshuku", "kayabuki", "8_inns"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[fukushima-lodging-r1] 尚無條目"); return; }
  console.log(`[fukushima-lodging-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[fukushima-lodging-r1] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[fukushima-lodging-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[fukushima-lodging-r1] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
