// Seed 広島県 R6 補完(20 筆 / Sprint 36.x)
//
// 食 +3 / 住 +2 / 衣 +2 / 育 +5 / 楽 +5 / 行 +3 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: string;
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "chugoku";
  prefecture_ja: "広島県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // 食 R6 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "yaezakura-shuzo-mihara-1860",
    category: "food",
    sub_type: "hiroshima_brewery",
    title_zh: "醉心山根本店(三原市・1860 創業・165 年・備後地方代表酒蔵・「醉心」軟水仕込独自製法)",
    title_ja: "醉心山根本店",
    romaji: "Suishin Yamaneji Honten",
    summary_zh: "**醉心山根本店は備後地方代表酒蔵**(三原市・1860 創業・165 年)。**「醉心」銘柄+ 軟水仕込独自製法** で 全国新酒鑑評会受賞多数。R1 食既出 西条 7 蔵+ R5 食 竹鶴酒造に並ぶ広島県内 第 3 主要酒蔵、三原市内+ 全国流通。",
    content_md: "- 創業:1860 年(万延 1)・165 年\n- 立地:三原市東町(JR 三原駅 徒歩 10 分)\n- 主要銘柄:醉心\n- 製法:軟水仕込独自製法\n- 全国新酒鑑評会:受賞多数\n- 蔵見学+ 試飲:可能(要予約)\n- 営業:9:00-17:00(土日休)\n- アクセス:JR 三原駅 徒歩 10 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "三原市",
    lg_code: "34204",
    area_types: ["restaurant_traditional"],
    lat: 34.4031,
    lon: 133.0786,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: ["sat", "sun"],
    external_urls: { official: "https://suishinsake.co.jp/" },
    tags: ["hiroshima_brewery", "suishin_yamaneji", "1860", "165_years", "soft_water_method"],
    source: "manual",
  },
  {
    slug: "setouchi-tsukudani",
    category: "food",
    sub_type: "hiroshima_setouchi_san",
    title_zh: "瀬戸内佃煮(因島+ 尾道+ 鞆・小魚+ 海藻+ 醤油煮詰め保存食・お土産代表)",
    title_ja: "瀬戸内佃煮",
    romaji: "Setouchi Tsukudani",
    summary_zh: "**瀬戸内佃煮は備後沿岸の伝統保存食**(因島+ 尾道+ 鞆等)。**小魚+ 海藻+ 醤油煮詰めた郷土食**、瀬戸内海の小型漁の活用文化。R1 衣既出の鞆の浦商店街+ R3 食 因島八朔と並ぶ瀬戸内お土産文化の 1。",
    content_md: "- 産地:備後沿岸(因島+ 尾道+ 鞆+ 三原)\n- 主要食材:小魚(イカナゴ+ ちりめん)+ 海藻(あおさ)\n- 用途:お茶請け+ ご飯のお供+ お土産\n- 価格目安:1 袋 ¥800-2500\n- 主要販売:R1 衣 鞆商店街+ R1 衣 onomichi-shotengai+ 各市道の駅\n- アクセス:備後沿岸各観光地",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["restaurant_traditional"],
    lat: 34.4089,
    lon: 133.1956,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_setouchi_san", "setouchi_tsukudani", "preserved_food", "small_fish", "souvenir"],
    source: "manual",
  },
  {
    slug: "shobara-michi-no-eki-overview",
    category: "food",
    sub_type: "hiroshima_hokubu",
    title_zh: "庄原みのり園(備北道の駅・地元野菜+ 比婆牛+ ジビエ+ 山菜・R1 食 hibagyu+ jinseki-jibie 集積販売所)",
    title_ja: "庄原みのり園",
    romaji: "Shobara Minori En",
    summary_zh: "**庄原みのり園は備北の道の駅**(庄原市)。R1 食既出 比婆牛+ 神石ジビエの主要販売所、**地元野菜+ 山菜+ 米+ 加工品** 集積。R1 育既出 帝釈峡+ R5 育 三次風土記の丘+ R3 楽 大久野島と一体の備北観光ベース。",
    content_md: "- 立地:庄原市内(備北中心)\n- 主要販売:比婆牛(R1 食)+ ジビエ(R1 食)+ 山菜+ 地元野菜+ 米\n- 営業:9:00-18:00(年中無休)\n- 隣接観光:R1 育 帝釈峡+ R3 楽 大久野島(車 1 時間 30 分)\n- アクセス:JR 芸備線 備後庄原駅 徒歩 / 車",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "庄原市",
    lg_code: "34210",
    area_types: ["restaurant_traditional"],
    lat: 34.8567,
    lon: 133.0203,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_hokubu", "shobara_minori", "michi_no_eki", "hibagyu_jibie_sales", "bihoku"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 住 R6 (2)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "nakamoto-ryokan-takehara",
    category: "lodging",
    sub_type: "hiroshima_setouchi_classical",
    title_zh: "仲本旅館(竹原市本町・町並み保存地区内・古民家旅館・竹鶴酒造 R5 食隣接・町並み景観体験)",
    title_ja: "仲本旅館",
    romaji: "Nakamoto Ryokan",
    summary_zh: "**仲本旅館は竹原町並み保存地区内の古民家旅館**(竹原市本町・R2 衣 takehara-machinami 内)。**江戸-明治期町家** をリノベ、R5 食 竹鶴酒造 1733(ニッカ創業者生家)隣接の好立地。料金 ¥15000-25000(2 食付・地酒コース)、町並み景観体験ハイライト。",
    content_md: "- 立地:竹原市本町(R2 衣 takehara-machinami 保存地区内)\n- 由来:江戸-明治期町家リノベ\n- 室数:6+ 室(小規模古民家)\n- 料金目安:¥15000-25000/泊(2 食付・地酒コース)\n- 隣接:R5 食 竹鶴酒造+ R2 衣 takehara-machinami 全体+ R2 楽 たけはら竹灯まつり\n- アクセス:JR 呉線 竹原駅 徒歩 15 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "竹原市",
    lg_code: "34203",
    area_types: ["onsen_field", "historic_district"],
    lat: 34.3411,
    lon: 132.9089,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_setouchi_classical", "nakamoto_ryokan", "takehara_machinami", "kominka_reno", "taketsuru_neighbor"],
    source: "manual",
  },
  {
    slug: "shobara-yumegasaki-onsen",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "庄原ゆめがさき温泉(備北山間温泉・1990s 整備・比婆山系眺望+ 比婆牛料理対応)",
    title_ja: "ゆめがさき温泉",
    romaji: "Yumegasaki Onsen",
    summary_zh: "**庄原ゆめがさき温泉は備北山間温泉**(庄原市・1990s 整備)。**比婆山系眺望+ R1 食 hibagyu(比婆牛)料理+ 山菜** で観光客対応。R1 育 既出 帝釈峡+ R3 楽 大久野島(車経由)観光のベース、料金 ¥12000-18000。",
    content_md: "- 整備:1990s\n- 立地:庄原市(比婆山系麓)\n- 室数:30+ 室\n- 温泉:単純温泉\n- 料理:比婆牛(R1 食)+ 山菜+ ジビエ\n- 料金目安:¥12000-18000/泊(2 食付)\n- 隣接:R1 育 帝釈峡(車 30 分)+ R5 育 三次風土記の丘(車 40 分)\n- アクセス:JR 芸備線 備後庄原駅 から バス 30 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "庄原市",
    lg_code: "34210",
    area_types: ["onsen_field", "mountain_village"],
    lat: 34.8567,
    lon: 133.0203,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["rural_minshuku", "yumegasaki_onsen", "1990s", "hibagyu_view", "bihoku_highland"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 衣 R6 (2)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shobara-knitwear",
    category: "fashion",
    sub_type: "craft_goods",
    title_zh: "庄原ニット(備北山間ウール・温暖差気候+ 山羊飼育・地場ブランド・冬向け衣料)",
    title_ja: "庄原ニット",
    romaji: "Shobara Knit",
    summary_zh: "**庄原ニットは備北山間ウール製品**(庄原市)。**寒暖差気候+ 山羊飼育の伝統** に基づく地場ブランド、冬向けニット+ マフラー+ 帽子等。R1 食 hibagyu+ R6 食 庄原みのり園と並ぶ備北の地場文化、観光客のお土産。",
    content_md: "- 産地:庄原市(備北山間)\n- 由来:寒暖差気候+ 山羊飼育伝統\n- 主要商品:ニット+ マフラー+ 帽子+ セーター\n- 価格目安:¥3500-15000\n- 主要販売:R6 食 庄原みのり園+ 庄原市内土産店\n- アクセス:JR 芸備線 備後庄原駅 徒歩 / 車",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "庄原市",
    lg_code: "34210",
    area_types: ["historic_district"],
    lat: 34.8567,
    lon: 133.0203,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["craft_goods", "shobara_knit", "highland_wool", "bihoku_local", "winter_wear"],
    source: "manual",
  },
  {
    slug: "miyajima-aki-bori",
    category: "fashion",
    sub_type: "craft_goods",
    title_zh: "宮島彫(廿日市市宮島・伝統木工・1900 起源・神社木彫+ 観光土産・宮島杓子 R1 衣と双璧)",
    title_ja: "宮島彫",
    romaji: "Miyajima Bori",
    summary_zh: "**宮島彫は宮島の伝統木工**(廿日市市宮島町・1900 起源)。R1 衣既出 miyajima-shamoji(杓子・1800 起源)に並ぶ宮島の伝統木工 2 大柱、**神社用具+ 観光土産** が主体。R1 衣 表参道商店街で販売、宮島観光のお土産。",
    content_md: "- 産地:廿日市市宮島町(1900 起源)\n- 系統:R1 衣 miyajima-shamoji(杓子)と並ぶ宮島伝統木工 2 大柱\n- 主要商品:神社用具+ 観光土産+ 木彫オブジェ\n- 価格目安:¥3000-15000\n- 主要販売:R1 衣 miyajima-omotesandou-shotengai\n- アクセス:宮島フェリー 宮島桟橋 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "廿日市市",
    lg_code: "34213",
    area_types: ["historic_district"],
    lat: 34.2961,
    lon: 132.3194,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["craft_goods", "miyajima_bori", "1900_origin", "wood_carving", "miyajima_traditional"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 育 R6 (5)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "miyajima-daishoin-806",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "大聖院(廿日市市宮島・806 創建・1200 年・弘法大師開山伝・宮島最古寺・国指定重文)",
    title_ja: "大聖院",
    romaji: "Daishoin",
    summary_zh: "**大聖院は宮島最古寺**(廿日市市宮島町・806 創建・1200 年)。**弘法大師空海開山伝**(R1 育 miyajima-misen 弥山も同年開山)、本堂+ 仏像+ 障壁画 等の文化財群。R1 育既出 厳島神社+ 弥山と並ぶ宮島の宗教的中心の 1、世界遺産構成資産候補だった寺。",
    content_md: "- 創建:806 年(大同 1)・1200 年\n- 開山:弘法大師空海\n- 国指定重要文化財:本堂+ 仏像\n- 立地:廿日市市宮島町\n- 入場料:無料(本堂)+ 一部有料区域\n- 営業:8:00-17:00\n- 隣接:R1 育 厳島神社+ 弥山(R1 育 miyajima-misen)+ R4 住 宮島宿坊\n- アクセス:宮島フェリー 宮島桟橋 徒歩 20 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "廿日市市",
    lg_code: "34213",
    area_types: ["shrine_temple"],
    lat: 34.2933,
    lon: 132.3194,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "daishoin", "806_kobo_daishi", "1200_years", "miyajima_oldest"],
    source: "manual",
  },
  {
    slug: "saijo-okumura-jinja",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "御建神社(東広島市西条・807 創建・1200 年・西条酒造の守護神・酒祭り 10 月本宮)",
    title_ja: "御建神社",
    romaji: "Mitate Jinja",
    summary_zh: "**御建神社は西条酒造の守護神**(東広島市西条・807 創建)。**R1 食 saijo-shuzo-michi-7 の精神的拠点**、酒蔵 7 蔵 + 蔵人の信仰中心。R1 楽 既出 西条酒祭り(10 月 25 万人)の本宮として神事を主導、西条観光と一体。",
    content_md: "- 創建:807 年(大同 2)・1200 年\n- 立地:東広島市西条本町(R1 食 saijo-shuzo-michi 内)\n- 史的価値:西条酒造 7 蔵守護神\n- 例祭:酒祭り(10 月)の本宮神事\n- 入場:無料\n- 営業:24 時間(社務所 9:00-17:00)\n- 隣接:R1 食 saijo-shuzo-michi-7+ R1 楽 saijo-sake-festival\n- アクセス:JR 山陽本線 西条駅 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "東広島市",
    lg_code: "34212",
    area_types: ["shrine_temple"],
    lat: 34.4267,
    lon: 132.7456,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "mitate_jinja", "807", "saijo_sake_guardian", "october_sake_fes_main"],
    source: "manual",
  },
  {
    slug: "yoshida-koriyama-jou-ato",
    category: "culture",
    sub_type: "history_site_castle",
    title_zh: "吉田郡山城跡(安芸高田市・国指定史跡・1523-1591 毛利氏本拠+ 1540 尼子軍撃退の合戦地)",
    title_ja: "吉田郡山城跡",
    romaji: "Yoshida Koriyama Jou",
    summary_zh: "**吉田郡山城跡は戦国大名毛利氏の本拠城**(安芸高田市・1523-1591・国指定史跡)。**1540 年尼子軍 3 万 vs 毛利軍 8 千の合戦地**(尼子撃退で毛利元就名声)、戦国 100 名城選定。R2 育 既出 mouri-motonari-haka(毛利元就墓)+ R5 育 ankokuji と並ぶ安芸高田 戦国遺産。",
    content_md: "- 築城:1523 年(大永 3)\n- 廃城:1591 年(天正 19・広島城遷移)\n- 国指定史跡:1940 年\n- 1540 合戦:尼子軍 3 万 vs 毛利軍 8 千・尼子撃退で毛利元就名声\n- 立地:安芸高田市吉田町\n- 入場:無料(常時)\n- 隣接:R2 育 毛利元就墓所+ R5 育 安国寺\n- アクセス:JR 芸備線 吉田口駅 から バス 30 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "安芸高田市",
    lg_code: "34214",
    area_types: ["history_site_castle"],
    lat: 34.6717,
    lon: 132.7344,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["history_site_castle", "yoshida_koriyama", "1523_1591", "mouri_clan_base", "1540_amago_battle"],
    source: "manual",
  },
  {
    slug: "fukuyama-myo-myo-jin",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "妙宣寺(福山市鞆町・1271 創建・日蓮宗備後本寺・国指定重文 鎌倉期)",
    title_ja: "妙宣寺",
    romaji: "Myosenji",
    summary_zh: "**妙宣寺は備後の日蓮宗本寺**(福山市鞆町・1271 創建)。鞆の浦内陸部に位置、**鎌倉期創建+ 国指定重要文化財の本堂** で 750+ 年の歴史。R1 育既出 鞆の浦観光+ R2 育 福禅寺対潮楼と並ぶ鞆の宗教遺産。",
    content_md: "- 創建:1271 年(文永 8)・754 年\n- 国指定重要文化財:本堂\n- 立地:福山市鞆町(鞆の浦内陸)\n- 宗派:日蓮宗\n- 入場:無料(参拝)\n- 営業:9:00-17:00\n- 隣接:R1 鞆の浦観光+ R2 育 福禅寺対潮楼\n- アクセス:JR 福山駅 から バス 30 分・鞆の浦下車",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "福山市",
    lg_code: "34207",
    area_types: ["shrine_temple"],
    lat: 34.3811,
    lon: 133.3839,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "myosenji", "1271", "nichiren_bingo", "kamakura_origin"],
    source: "manual",
  },
  {
    slug: "kibitsu-jinja-bingo-kagura",
    category: "culture",
    sub_type: "temple_shrine",
    title_zh: "備中神楽起源神社(三次+ 庄原・備中神楽 国重要無形民俗文化財・備北神楽の系統)",
    title_ja: "備中神楽起源神社",
    romaji: "Bichu Kagura Origin",
    summary_zh: "**備中神楽起源神社は備北神楽の系統的拠点**(三次+ 庄原)。R3 楽 既出 安芸高田神楽+ R4 楽 三次八岐大蛇神楽 の元、**備中神楽は岡山発祥** だが備北系統が広島側に独自発展。複数神社が公演主催、年中神楽公演で観光客。",
    content_md: "- 系統:備中神楽(国重要無形民俗文化財・岡山発祥)\n- 立地:三次+ 庄原 複数神社\n- 関連:R3 楽 akitakata-kagura+ R4 楽 miyoshi-orochi-kagura\n- 公演:年中(週末中心)\n- 入場料:¥1500-3000(公演)\n- アクセス:JR 芸備線 備後庄原駅 + 三次駅 から 各地",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "三次市",
    lg_code: "34209",
    area_types: ["shrine_temple"],
    lat: 34.8047,
    lon: 132.8508,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["temple_shrine", "bichu_kagura_origin", "national_intangible", "bihoku_lineage", "year_round"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 楽 R6 (5)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "miyajima-tamatori-fes-aug",
    category: "entertainment",
    sub_type: "ancient_festival",
    title_zh: "玉取祭(廿日市市宮島・8 月第 4 日曜・厳島神社海上神事・若者 100 人参加 福玉取り)",
    title_ja: "玉取祭",
    romaji: "Tamatori Sai",
    summary_zh: "**玉取祭は厳島神社夏の海上神事**(廿日市市宮島町・8 月第 4 日曜)。**若者 100 人がふんどし姿で海上の福玉(直径 30 cm)を取り合う祭**、厳島神社例大祭の 1。R1 楽既出 管絃祭+ R4 楽 水中花火大会と並ぶ宮島夏の 3 大祭。",
    content_md: "- 開催:8 月第 4 日曜\n- 立地:廿日市市宮島町(厳島神社海上)\n- 内容:若者 100 人 福玉取り(直径 30 cm の福玉)\n- 由来:厳島神社例大祭の 1\n- 入場:無料(海岸観覧)\n- 隣接:R1 育 厳島神社\n- アクセス:宮島フェリー 宮島桟橋 徒歩 10 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "廿日市市",
    lg_code: "34213",
    area_types: ["festival_event"],
    lat: 34.2956,
    lon: 132.3197,
    season_start: null,
    season_end: null,
    event_start: "2026-08-23",
    event_end: "2026-08-23",
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["ancient_festival", "tamatori_sai", "august_4_sun", "100_youths", "shinto_marine"],
    source: "manual",
  },
  {
    slug: "saijo-akiyo-walk",
    category: "entertainment",
    sub_type: "scenic_spot",
    title_zh: "西条酒蔵通り夜散策(東広島市・R1 食 saijo-shuzo-michi 夜 angle・酒蔵ライトアップ+ 静寂町並み)",
    title_ja: "西条酒蔵通り夜",
    romaji: "Saijo Yoru",
    summary_zh: "**西条酒蔵通り夜散策は酒蔵 7 蔵の夜の風情**(東広島市・R1 食 saijo-shuzo-michi 夜 angle)。**酒蔵ライトアップ+ 静寂町並み**、伝統的造りの酒蔵が夜に浮かび上がる幻想風景。R1 食 既出 7 蔵+ R5 食 賀茂鶴の夜は雰囲気が違う、地酒バー付きで観光客に人気。",
    content_md: "- 立地:東広島市西条本町(R1 食 saijo-shuzo-michi)\n- ベスト時間:18:00-22:00\n- ライトアップ:酒蔵 7 蔵+ 通り\n- 関連:R1 食 saijo-shuzo-michi-7+ R5 食 賀茂鶴(酒祭り R1 楽 saijo-sake-fes 期は特別ライト)\n- 入場:無料(常時散策)\n- アクセス:JR 山陽本線 西条駅 徒歩 5 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "東広島市",
    lg_code: "34212",
    area_types: ["scenic_spot", "historic_district"],
    lat: 34.4267,
    lon: 132.7456,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["scenic_spot", "saijo_yoru", "night_walk", "7_breweries_lightup", "free"],
    source: "manual",
  },
  {
    slug: "mihara-yakitori-zone",
    category: "entertainment",
    sub_type: "scenic_spot",
    title_zh: "三原やきとり街(三原市・全国名物・1957 起源・市内 50+ 軒・「三原やきとり」B1 グランプリ常連)",
    title_ja: "三原やきとり街",
    romaji: "Mihara Yakitori",
    summary_zh: "**三原やきとり街は全国名物のご当地焼鳥街**(三原市・1957 起源)。**市内 50+ 軒の焼鳥専門店**、B1 グランプリ常連。R1 食 mihara-tako+ R1 衣 mihara-daruma+ R1 楽 mihara-yatsui-aug+ R4 食 mihara-towel と並ぶ三原観光の食ハイライト。",
    content_md: "- 立地:三原市内(JR 三原駅周辺)\n- 起源:1957 年(昭和 32)\n- 軒数:50+ 軒(専門店)\n- 受賞:B1 グランプリ常連\n- 価格目安:1 人前 ¥1500-3000\n- 営業:店舗による(17:00-23:00 が標準)\n- アクセス:JR 三原駅 徒歩 5-15 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "三原市",
    lg_code: "34204",
    area_types: ["nightlife", "restaurant_traditional"],
    lat: 34.4031,
    lon: 133.0786,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["scenic_spot", "mihara_yakitori", "1957_origin", "50_specialty", "b1_grand_prix"],
    source: "manual",
  },
  {
    slug: "kake-momiji-spot",
    category: "entertainment",
    sub_type: "momiji",
    title_zh: "大鼓滝(安芸太田町・R1 育 sandankyo 内・滝紅葉名所・11 月見頃・三段峡周辺の隠れスポット)",
    title_ja: "大鼓滝",
    romaji: "Daiko Daki",
    summary_zh: "**大鼓滝は三段峡内の滝紅葉名所**(R1 育 sandankyo-1925・安芸太田町)。三段峡内 30+ 滝の代表、**11 月紅葉時期の絶景**。R1 楽 既出 sandankyo-rafting+ R3 楽 sandankyo-spring-flowers と並ぶ三段峡の春-紅葉観光。",
    content_md: "- 立地:山県郡安芸太田町(R1 育 sandankyo 内)\n- 紅葉時期:11 月中旬-12 月初\n- 規模:三段峡 30+ 滝の代表 1 つ\n- 入場:無料(R1 育 sandankyo に準じる)\n- 隣接:R1 楽 sandankyo-rafting\n- アクセス:JR 横川駅 から バス 1 時間 30 分・三段峡口 から 徒歩",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: "山県郡",
    municipality_ja: "安芸太田町",
    lg_code: "34368",
    area_types: ["scenic_spot"],
    lat: 34.5547,
    lon: 132.1819,
    season_start: "2026-11-01",
    season_end: "2026-12-05",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["momiji", "daiko_daki", "sandankyo_inner", "30_falls_top", "november"],
    source: "manual",
  },
  {
    slug: "innoshima-flower-center",
    category: "entertainment",
    sub_type: "flower_field",
    title_zh: "因島フラワーセンター(尾道市因島・1991 開園・年中花畑・ばら+ 桜+ アジサイ・しまなみ海道立寄り)",
    title_ja: "因島フラワーセンター",
    romaji: "Innoshima Flower Center",
    summary_zh: "**因島フラワーセンターはしまなみ海道立寄り花畑**(尾道市因島・1991 開園)。**ばら園+ 桜並木+ アジサイ群+ シバザクラ**等の年中花畑、しまなみ サイクリスト+ 観光客の休憩 hub。R4 楽 既出 因島水軍まつり+ R5 楽 因島水軍城 と一体の因島観光。",
    content_md: "- 開園:1991 年(平成 3)\n- 立地:尾道市因島(R1 楽 しまなみ海道沿線)\n- 主要花:ばら+ 桜+ アジサイ+ シバザクラ+ ヒマワリ\n- 入園:無料\n- 営業:9:00-17:00(年中無休)\n- 隣接:R4 楽 innoshima-suigun-fes+ R5 楽 innoshima-suigun-castle\n- アクセス:しまなみ海道 因島(JR 尾道 から 高速船+ レンタカー)",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["flower_field", "park_garden"],
    lat: 34.3669,
    lon: 133.1581,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["flower_field", "innoshima_flower", "1991", "shimanami_stop", "year_round"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 行 R6 (3)
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "shimanami-cycling-toll",
    category: "transport",
    sub_type: "hiroshima_shimanami",
    title_zh: "しまなみ海道自転車道通行料(R1 楽 shimanami-kaido 60km・橋通行料 ¥30-200・無料パス可能)",
    title_ja: "しまなみ自転車道通行料",
    romaji: "Shimanami Cycling Toll",
    summary_zh: "**しまなみ海道自転車道は無料化されたが橋によって通行料あり**(R1 楽 shimanami の補完)。**5 大橋(因島大橋+ 生口橋+ 多々羅大橋+ 大三島橋+ 来島海峡大橋)に通行料 ¥30-200**、ただし観光促進で無料化期間あり。R1 楽 cycling 体験 計画時の重要情報。",
    content_md: "- 主要橋:5 大橋通行料(¥30-200)\n- 因島大橋(R1 行)+ 生口橋+ 多々羅大橋+ 大三島橋+ 来島海峡大橋\n- 無料化期間:2014 年 から 観光促進で部分的無料化\n- 1 日券:¥500(R4 行 既出関連)\n- 関連:R1 楽 shimanami-kaido 60km+ R3 行 shimanami-ferry-routes(NULL)\n- アクセス:しまなみ海道 各橋通行所",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "尾道市",
    lg_code: "34205",
    area_types: ["road_route"],
    lat: 34.4089,
    lon: 133.1956,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_shimanami", "cycling_toll", "5_bridges", "30_200_yen", "free_period"],
    source: "manual",
  },
  {
    slug: "takehara-jr-station",
    category: "transport",
    sub_type: "hiroshima_jr_local",
    title_zh: "JR 竹原駅(竹原市・1932 開業・JR 呉線・R2 衣 takehara-machinami+ R5 食 竹鶴酒造アクセス hub)",
    title_ja: "JR 竹原駅",
    romaji: "JR Takehara Eki",
    summary_zh: "**JR 竹原駅は竹原観光の起点**(竹原市・1932 開業・JR 呉線)。**R2 衣 takehara-machinami(国指定 1982)+ R5 食 竹鶴酒造 1733+ R2 楽 たけはら竹灯まつり** 観光の主要 hub。R1 行 呉駅 hub の対比、備後地方の中継駅。",
    content_md: "- 開業:1932 年(昭和 7)\n- 立地:竹原市中央(JR 呉線)\n- 観光連絡:R2 衣 takehara-machinami(徒歩 15 分)+ R5 食 竹鶴酒造(徒歩 15 分)+ R2 楽 たけはら竹灯まつり\n- 1 日乗車人員:約 5000 人\n- アクセス:広島駅 から JR 呉線 1 時間 30 分・三原駅 から 30 分",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "竹原市",
    lg_code: "34203",
    area_types: ["transit_hub"],
    lat: 34.3411,
    lon: 132.9089,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["hiroshima_jr_local", "takehara_eki", "1932", "kure_line", "machinami_hub"],
    source: "manual",
  },
  {
    slug: "tomonoura-kanko-bus",
    category: "transport",
    sub_type: "area_access_guide",
    title_zh: "鞆の浦観光バス(JR 福山駅-鞆の浦・30 分・¥530・1 日 30+ 便・西鉄+ 鞆鉄共同・観光客向け)",
    title_ja: "鞆の浦観光バス",
    romaji: "Tomonoura Kanko Bus",
    summary_zh: "**鞆の浦観光バスは鞆観光のメインアクセス**(JR 福山駅-鞆の浦・30 分・¥530・1 日 30+ 便)。**R1 食 保命酒+ R1 育 鞆常夜灯+ R2 育 福禅寺対潮楼+ R2 住 御舟宿いろは+ R6 育 妙宣寺** 観光の生命線、観光客の必須交通。",
    content_md: "- 区間:JR 福山駅 ↔ 鞆の浦\n- 所要:30 分\n- 料金:¥530(片道)\n- 1 日本数:30+ 便/日\n- 共同運行:西鉄バス+ 鞆鉄道\n- 観光連絡:R1 食 保命酒+ R1 育 鞆常夜灯+ R2 育 福禅寺対潮楼+ R6 育 妙宣寺\n- 予約:不要(自由乗車)\n- アクセス:JR 福山駅 バスセンター",
    region: "chugoku",
    prefecture_ja: "広島県",
    gun_ja: null,
    municipality_ja: "福山市",
    lg_code: "34207",
    area_types: ["transit_hub"],
    lat: 34.4889,
    lon: 133.3633,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["area_access_guide", "tomonoura_kanko_bus", "30min", "530yen", "30_per_day"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[hiroshima-r6] 尚無條目");
    return;
  }
  console.log(`[hiroshima-r6] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const byCat = new Map<string, number>();
    for (const r of rows) byCat.set(r.category, (byCat.get(r.category) ?? 0) + 1);
    for (const [k, v] of [...byCat.entries()].sort()) {
      console.log(`  ${k.padEnd(15)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[hiroshima-r6] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[hiroshima-r6] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[hiroshima-r6] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
