// Seed 石川県 食 R1(25 筆 / Sprint 39.1)
//
// 加賀料理 +4 / 金沢寿司 +4 / おでん +4 / 銘菓 +6 / 酒蔵 +4 / 能登産物 +3 = 25

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string;
  category: "food";
  sub_type: string;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "chubu";
  prefecture_ja: "石川県";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ════════════════════════════════════════════════════════════════════
  // 加賀料理 (4) — 大友楼+ 治部煮+ 加賀野菜+ 大野醤油
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kanazawa-jibuni-otomatsu-1830",
    category: "food",
    sub_type: "ishikawa_kaga_ryori",
    title_zh: "大友楼(金沢市・1830 創業・195 年・加賀藩御用達料亭+ 治部煮老舗+ 駅前ホテル日航金沢出店)",
    title_ja: "大友楼",
    romaji: "Otomotsu",
    summary_zh: "**大友楼は加賀藩御用達料亭**(金沢市・**1830 創業・195 年**)。**治部煮(鴨葛+ 醤油)代表店**、加賀料理発祥的料亭、現在は金沢駅前ホテル日航金沢内 + 香林坊本店の二店構え。R1 育既出 兼六園+ 金沢城公園と並ぶ加賀百万石文化拠点。",
    content_md: "- 創業:1830 年(天保 1)・195 年\n- 立地:金沢市尾張町本店 + ホテル日航金沢店\n- 系譜:**加賀藩御用達料亭**(前田家公式料理)\n- 名物:**治部煮**(鴨ささみ+ 葛粉+ 醤油+ すだれ麸)\n- 文化:加賀料理伝統を継承する数少ない 老舗\n- 価格:昼会席 ¥5,500-+ 治部煮膳 ¥3,500-\n- 営業:本店 11:30-14:30 / 17:00-21:00\n- 予約:推奨\n- アクセス:JR 金沢駅 徒歩 15 分(本店)・駅直結(日航店)",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional"],
    lat: 36.5731,
    lon: 136.6597,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["otomotsu", "1830", "195_years", "kaga_goyotashi", "jibuni"],
    source: "manual",
  },
  {
    slug: "jibuni-overview",
    category: "food",
    sub_type: "ishikawa_kaga_ryori",
    title_zh: "治部煮(加賀料理代表・鴨ささみ + 葛粉 + 醤油 + すだれ麸の煮物・前田家武家文化)",
    title_ja: "治部煮",
    romaji: "Jibuni",
    summary_zh: "**治部煮は加賀料理代表的煮物**(石川県全域・**鴨ささみ + 葛粉 + 醤油 + すだれ麸**)。**前田家武家文化が生んだ独自料理**、葛粉でとろみを付ける独特技法、室町期からの料亭料理が庶民にも広がった。R1 食既出 大友楼 1830 + 主要加賀料理店で提供、家庭でも日常的に作られる。",
    content_md: "- 主材料:鴨ささみ(現代は鶏も)+ 葛粉+ 醤油+ すだれ麸+ 季節野菜\n- 調理特徴:葛粉でとろみを付け+ 具材の旨味閉じ込め\n- 起源:加賀藩武家文化・前田家公式料理として発展\n- 名前語源:諸説(治部少輔・じぶじぶ煮る音 等)\n- 提供店:大友楼+ 金沢おでん各店+ 加賀料理料亭\n- 家庭料理:石川県内日常メニュー\n- 価格:外食 ¥1,500-3,500\n- 季節:通年(冬肌寒い時期に最適)",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional"],
    lat: 36.5681,
    lon: 136.6620,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["jibuni", "kaga_ryori", "duck_kuzu", "samurai_culture", "regional_signature"],
    source: "manual",
  },
  {
    slug: "kaga-yasai-overview",
    category: "food",
    sub_type: "ishikawa_kaga_ryori",
    title_zh: "加賀野菜(15 品目認定 1997・加賀蓮根 + 五郎島金時 + 源助だいこん + 金沢春菊 等の伝統野菜)",
    title_ja: "加賀野菜",
    romaji: "Kaga Yasai",
    summary_zh: "**加賀野菜は加賀地方伝統野菜のブランド総称**(石川県・**15 品目認定 1997・金沢市農産物ブランド協会**)。**加賀蓮根+ 五郎島金時+ 源助だいこん+ 金沢春菊+ 打木赤皮甘栗かぼちゃ等**、近江町市場 + 加賀料理店 + 県外百貨店流通。R1 育既出 兼六園 と並ぶ加賀文化遺産の食 angle。",
    content_md: "- 認定:1997 年 金沢市農産物ブランド協会\n- 認定品目数:**15 品目**\n- 主要野菜:加賀蓮根・五郎島金時・源助だいこん・金沢春菊・打木赤皮甘栗かぼちゃ・タケノコ・赤ずいき・ヘタ紫なす・くわい・せり・金時草・小坂れんこん・二塚からしな・金沢一本太ねぎ・加賀つるまめ\n- 流通:**近江町市場 + 加賀料理店 + 県外百貨店**\n- 季節:品目別(春-秋が中心)\n- 購買:近江町市場 + JA 直売所",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["farm_field", "shopping_district"],
    lat: 36.5694,
    lon: 136.6594,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kaga_yasai", "1997_certified", "15_items", "kaga_renkon", "goro_island_kintoki"],
    source: "manual",
  },
  {
    slug: "ono-shoyu-1644-overview",
    category: "food",
    sub_type: "ishikawa_kaga_ryori",
    title_zh: "大野醤油(金沢市大野町・1644 創業 380 年+ 全国 5 大醤油郷+ 加賀料理基調)",
    title_ja: "大野醤油",
    romaji: "Ono Shoyu",
    summary_zh: "**大野醤油は全国 5 大醤油郷の 1**(金沢市大野町・**1644 創業・380 年**)。**加賀料理 + 金沢おでんの旨味基調**、現在も 14 軒前後の醤油蔵が稼働、千葉野田 + 千葉銚子 + 兵庫龍野 + 香川小豆島 と並ぶ。R1 食既出 大友楼治部煮 + R1 食 金沢おでんの旨味の根源。",
    content_md: "- 創業:1644 年(正保 1)・380 年(産地として)\n- 立地:金沢市大野町(港町)\n- 全国順位:**5 大醤油郷の 1**(大野・野田・銚子・龍野・小豆島)\n- 蔵数:現在 14 軒前後\n- 特徴:**甘口濃口**(関西寄りの甘め醤油)\n- 用途:加賀料理 + 金沢おでん旨味基調\n- 主要蔵:ヤマト醤油味噌・直源醤油・ヤマシン醤油・松本健太郎商店 等\n- 観光:大野からくり記念館 + 醤油蔵見学(要予約)\n- アクセス:JR 金沢駅 → バス 30 分(大野経由)",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["historic_district", "industrial_heritage"],
    lat: 36.6097,
    lon: 136.6072,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["ono_shoyu", "1644", "380_years", "5_great_soy_regions", "amakuchi"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 金沢寿司 (4) — もりもり+ 近江町市場 1721+ 廻る金沢概論+ 海鮮丼
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "morimori-zushi-kanazawa-1995",
    category: "food",
    sub_type: "ishikawa_kanazawa_sushi",
    title_zh: "もりもり寿司 金沢駅前店(金沢市・1995 創業・30 年+ 金沢回転寿司代表+ 北陸新幹線後の観光寿司爆発)",
    title_ja: "もりもり寿司 金沢駅前店",
    romaji: "Morimori Sushi",
    summary_zh: "**もりもり寿司は金沢回転寿司の代表チェーン**(金沢市・**1995 創業・30 年**)。**北陸新幹線 2015 開業後の観光寿司爆発の中核**、金沢駅前店 + 県内 8 店舗、能登地物 + 北陸海産が看板。R3 育既出 金沢駅鼓門の徒歩圏、観光客にとって金沢寿司の入門店。",
    content_md: "- 創業:1995 年・30 年\n- 立地:金沢駅前店 + 県内 8 店舗\n- ジャンル:回転寿司(北陸海鮮特化)\n- 看板:**能登のどぐろ + ブリ + 甘えび + 加能ガニ**\n- 観光客対応:**北陸新幹線 2015 開業後爆発的人気**\n- 価格:1 皿 ¥150-700\n- 営業:11:00-22:00 通年\n- 待ち時間:夕食時 1-2 時間(整理券推奨)\n- アクセス:JR 金沢駅鼓門口 徒歩 1 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional"],
    lat: 36.5783,
    lon: 136.6481,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["morimori_sushi", "1995", "30_years", "conveyor_belt", "kanazawa_eki"],
    source: "manual",
  },
  {
    slug: "omicho-ichiba-1721",
    category: "food",
    sub_type: "ishikawa_kanazawa_sushi",
    title_zh: "近江町市場(金沢市・1721 開設・304 年+ 金沢の台所+ 海鮮丼集積+ 加能ガニ + 加賀野菜流通中心)",
    title_ja: "近江町市場",
    romaji: "Omicho Ichiba",
    summary_zh: "**近江町市場は金沢の台所**(金沢市・**1721 開設・304 年**)。**約 170 店舗の鮮魚 + 加賀野菜 + 食堂集積**、加能ガニ + のどぐろ + 甘えびの北陸海産+ 加賀野菜 R1 食既出 15 品目流通の中核。R1 育既出 兼六園 + 金沢城公園 徒歩圏、海鮮丼食堂 多数営業。",
    content_md: "- 開設:1721 年(享保 6)・**304 年**\n- 立地:金沢市青草町(香林坊 + 武蔵北側)\n- 規模:**約 170 店舗**(鮮魚 + 加賀野菜 + 食堂)\n- 別名:**「金沢の台所」**\n- 主要商品:加能ガニ + のどぐろ + 甘えび + 加賀野菜\n- 食堂:海鮮丼 + 寿司 + 加賀料理 数十軒\n- 営業:店舗ごとに異なる(おおむね 9:00-17:00)\n- 定休:水曜定休店多い\n- アクセス:JR 金沢駅 → 北鉄バス 6 分・徒歩 15 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["shopping_district", "historic_district"],
    lat: 36.5719,
    lon: 136.6584,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: ["wed"],
    external_urls: { official: "https://ohmicho-ichiba.com/" },
    tags: ["omicho", "1721", "304_years", "170_shops", "kanazawa_kitchen"],
    source: "manual",
  },
  {
    slug: "kanazawa-mawaru-zushi-overview",
    category: "food",
    sub_type: "ishikawa_kanazawa_sushi",
    title_zh: "廻る金沢(金沢回転寿司激戦区・もりもり寿司 + 廻る寿司 もりもり庵 + 金沢まいもん寿司 + 廻る寿し わたなべ等)",
    title_ja: "廻る金沢",
    romaji: "Mawaru Kanazawa",
    summary_zh: "**廻る金沢は金沢回転寿司激戦区の総称**(金沢市内・**5+ チェーン+ 60+ 店舗**)。**もりもり寿司+ 金沢まいもん寿司+ 廻る寿し わたなべ+ 廻る金沢まいもん寿司**等、北陸新幹線開業後の観光寿司ブーム発信地。R1 食既出 もりもり寿司+ 近江町市場 と一体観光ルート、北陸新幹線 2015 開業の最大恩恵業界。",
    content_md: "- 範囲:金沢市内全域(主に駅前 + 武蔵 + 香林坊 + 片町)\n- 主要チェーン:**もりもり寿司・金沢まいもん寿司・廻る寿し わたなべ・廻る金沢まいもん寿司・回転寿司 海鮮アトム**\n- 店舗数:**60+ 店舗**\n- 観光客対応:北陸新幹線開業後の観光客爆発で対応\n- 看板:能登のどぐろ + 加能ガニ + 甘えび + ブリ\n- 価格帯:1 皿 ¥150-700\n- 待ち時間:夕食時 1-3 時間(整理券推奨)\n- 並列文化:近江町市場 1721 + 加賀料理老舗",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional"],
    lat: 36.5681,
    lon: 136.6620,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["mawaru_kanazawa", "60_shops", "shinkansen_2015_boom", "battle_zone"],
    source: "manual",
  },
  {
    slug: "kanazawa-kaisendon-omicho",
    category: "food",
    sub_type: "ishikawa_kanazawa_sushi",
    title_zh: "近江町海鮮丼集積(金沢近江町市場内+ 海鮮丼食堂 数十軒+ 加能ガニ + のどぐろ + ブリの北陸海鮮丼集積)",
    title_ja: "近江町海鮮丼",
    romaji: "Omicho Kaisendon",
    summary_zh: "**近江町海鮮丼は金沢市場内丼食堂集積**(金沢市・**近江町市場 1721 内・数十軒**)。**加能ガニ+ のどぐろ + ブリ + 甘えびの北陸海鮮丼**、近江町コロッケ + 海鮮串焼き + 立ち寿司 等の市場内グルメ集積。R1 食既出 近江町市場 と同一拠点・別 angle、観光客向けランチの中核。",
    content_md: "- 立地:近江町市場内 + 周辺(金沢市青草町)\n- 食堂数:**数十軒**(井ノ弥+ 山さん寿司+ 大畠商店+ 近江町市場寿し+ 廻る寿し 等)\n- 名物:**北陸海鮮丼**(加能ガニ + のどぐろ + ブリ + 甘えび + うに + イクラ)\n- 並列商品:近江町コロッケ + 海鮮串焼き + 立ち寿司\n- 価格:海鮮丼 ¥2,000-4,500\n- ベスト時期:11 月-3 月加能ガニ漁期\n- 営業:大半の店 9:00-15:00 ランチ営業\n- アクセス:JR 金沢駅 → バス 6 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional", "shopping_district"],
    lat: 36.5719,
    lon: 136.6584,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: ["wed"],
    external_urls: {},
    tags: ["omicho_kaisendon", "kano_gani", "nodoguro", "buri", "ama_ebi"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 金沢おでん (4) — 高砂 1936+ 黒百合 1953+ 三幸+ 車麩
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "kanazawa-oden-takasa-1936",
    category: "food",
    sub_type: "ishikawa_kanazawa_oden",
    title_zh: "高砂(金沢市・1936 創業・89 年+ 金沢おでん老舗代表+ 加能ガニ甲羅おでん + 車麩 + 梅貝)",
    title_ja: "高砂",
    romaji: "Takasa",
    summary_zh: "**高砂は金沢おでん最古級老舗**(金沢市・**1936 創業・89 年**)。**加能ガニ甲羅おでん + 車麩 + 梅貝の金沢三大おでん**、片町近くの夜食定番、R1 食既出 大野醤油の旨味基調が活きる代表店。R1 楽既出 兼六園夜散策後の食事拠点。",
    content_md: "- 創業:1936 年(昭和 11)・89 年\n- 立地:金沢市片町(繁華街)\n- 名物:**加能ガニ甲羅おでん + 車麩 + 梅貝 + 赤巻**\n- 旨味基調:**大野醤油 1644 380 年伝統**\n- 名物時期:11-3 月加能ガニ漁期に甲羅おでん\n- 営業:17:00-23:00(日休)\n- 価格:1 品 ¥250-1,500\n- アクセス:北鉄バス 香林坊 徒歩 5 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional", "nightlife"],
    lat: 36.5639,
    lon: 136.6543,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: ["sun"],
    external_urls: {},
    tags: ["takasa_oden", "1936", "89_years", "kano_gani_kourayaki", "katamachi"],
    source: "manual",
  },
  {
    slug: "kanazawa-oden-kuroyuri-1953",
    category: "food",
    sub_type: "ishikawa_kanazawa_oden",
    title_zh: "黒百合(金沢市・1953 創業・72 年+ 金沢駅 100 番街内+ 観光客必訪おでん老舗)",
    title_ja: "黒百合",
    romaji: "Kuroyuri",
    summary_zh: "**黒百合は金沢駅 100 番街内の老舗おでん**(金沢市・**1953 創業・72 年**)。**金沢駅構内立地で観光客アクセス最良**、加賀料理 R1 食既出 治部煮 + 金沢おでん名物 + 加賀地酒の併設、北陸新幹線駅から徒歩 1 分。",
    content_md: "- 創業:1953 年(昭和 28)・72 年\n- 立地:**JR 金沢駅 100 番街「あんと」内**\n- 名物:金沢おでん(車麩 + 梅貝 + 赤巻)\n- 並列:加賀料理 + 加賀地酒\n- 観光対応:北陸新幹線駅から徒歩 1 分の最良アクセス\n- 営業:11:00-22:00 通年\n- 価格:1 品 ¥250-800\n- アクセス:JR 金沢駅 兼六園口 徒歩 1 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional"],
    lat: 36.5783,
    lon: 136.6481,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kuroyuri_oden", "1953", "72_years", "anto_kanazawa_eki", "tourist_friendly"],
    source: "manual",
  },
  {
    slug: "kanazawa-oden-sanko-1958",
    category: "food",
    sub_type: "ishikawa_kanazawa_oden",
    title_zh: "三幸(金沢市・1958 創業・67 年+ 金沢おでん名店+ 片町地元向け)",
    title_ja: "三幸",
    romaji: "Sankou",
    summary_zh: "**三幸は片町金沢おでん名店**(金沢市・**1958 創業・67 年**)。**地元客中心の金沢らしい夜おでん**、観光客より地元客重視の老舗、R1 食既出 高砂 1936(片町同地区)と並ぶ片町金沢おでん 2 大柱。深夜まで営業。",
    content_md: "- 創業:1958 年(昭和 33)・67 年\n- 立地:金沢市片町(繁華街中心)\n- 性格:**地元客中心の夜おでん**\n- 名物:車麩 + 梅貝 + 赤巻 + 加能ガニ\n- 営業:17:00-翌 1:00(深夜営業)\n- 並列:R1 食 高砂 1936 と片町 2 大柱\n- 価格:1 品 ¥250-1,200\n- アクセス:北鉄バス 香林坊 徒歩 5 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional", "nightlife"],
    lat: 36.5642,
    lon: 136.6547,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["sankou_oden", "1958", "67_years", "katamachi", "late_night"],
    source: "manual",
  },
  {
    slug: "kuruma-bu-ishikawa-overview",
    category: "food",
    sub_type: "ishikawa_kanazawa_oden",
    title_zh: "車麩(石川県独自・金沢おでん必須具材+ 加賀料理基本食材+ 武家文化由来)",
    title_ja: "車麩",
    romaji: "Kuruma Bu",
    summary_zh: "**車麩は石川県独自の麸料理**(石川県全域・**金沢おでん必須具材**)。**車輪型に巻いた焼き麩**、出汁を吸う特性で金沢おでんの代表具材、加賀料理 + 治部煮にも使用される武家文化由来食材。R1 食既出 高砂 + 黒百合 + 三幸 等の金沢おでん各店で必ず提供される郷土食。",
    content_md: "- 形状:車輪型に巻いた焼き麩(直径 5-7cm)\n- 用途:金沢おでん必須具材+ 治部煮+ 加賀料理\n- 特性:出汁を吸う+ 食感ふんわり+ 旨味受容力高い\n- 起源:加賀藩武家文化(精進料理由来)\n- 製法:小麦グルテン → 棒巻焼成 → 切り分け\n- 入手:石川県内 ほぼ全スーパー + 麸専門店\n- 並列:加賀の麸文化(車麩 + すだれ麩 + 角麩)\n- 主要メーカー:加賀麸不室屋 1865 等",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional"],
    lat: 36.5681,
    lon: 136.6620,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kuruma_bu", "regional_only", "oden_essential", "samurai_origin", "fubaya_1865"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 金沢銘菓 (6) — 森八+ 諸江屋+ 丸八製茶場+ 中田屋+ 福梅+ 加賀棒茶
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "moriya-1625-kanazawa",
    category: "food",
    sub_type: "ishikawa_kanazawa_meika",
    title_zh: "森八(金沢市・1625 創業・400 年+ 加賀藩御用菓子+ 全国 4 大老舗和菓子+ 長生殿落雁)",
    title_ja: "森八",
    romaji: "Moriya",
    summary_zh: "**森八は加賀藩御用達 400 年老舗**(金沢市・**1625 創業・400 年**)。**全国 4 大老舗和菓子**(虎屋+ とらや黒川+ 鶴屋八幡+ 森八)の 1、**長生殿(三大銘菓 1 つの落雁)**+ 福梅 + 干菓子で全国知名。R1 育既出 兼六園 1822 + 金沢城公園 徒歩 5 分の尾張町本店。",
    content_md: "- 創業:1625 年(寛永 2)・400 年\n- 立地:金沢市尾張町本店 + 県内 + 県外百貨店\n- 系譜:**加賀藩御用菓子**(前田家公式)\n- 全国順位:**全国 4 大老舗和菓子**\n- 名物:**長生殿落雁**(日本三大銘菓・福井 五感餅・愛媛 山川と並ぶ)\n- その他:**福梅**(金沢正月菓子)+ 加賀干菓子\n- 営業:9:30-18:00 通年\n- アクセス:JR 金沢駅 → バス 6 分・尾張町徒歩 1 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional", "shopping_district"],
    lat: 36.5689,
    lon: 136.6647,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.morihachi.co.jp/" },
    tags: ["moriya", "1625", "400_years", "kaga_goyotashi", "choseiden_rakugan", "top4_japan"],
    source: "manual",
  },
  {
    slug: "morohachi-rakugan-1849",
    category: "food",
    sub_type: "ishikawa_kanazawa_meika",
    title_zh: "諸江屋(金沢市・1849 創業・176 年+ 落雁専門老舗+ 兼六園参道+ 干菓子伝統)",
    title_ja: "諸江屋",
    romaji: "Morohachi",
    summary_zh: "**諸江屋は落雁専門老舗**(金沢市・**1849 創業・176 年**)。**兼六園参道 野町本店**、加賀干菓子 + 落雁の専門店として 6 代続く、R1 食既出 森八 1625(全国 4 大)の対極に位置する庶民派老舗。落雁の名品 + 季節干菓子で観光客 + 茶道家両対応。",
    content_md: "- 創業:1849 年(嘉永 2)・176 年\n- 立地:金沢市野町本店(兼六園参道)\n- 系譜:**落雁専門老舗 6 代**\n- 名物:**加賀干菓子 + 落雁**(米粉 + 砂糖 + 木型成形)\n- 役割:R1 食既出 森八 1625 と対極の 庶民派老舗\n- 顧客:観光客 + 茶道家両対応\n- 営業:9:00-19:00 通年\n- アクセス:北鉄バス 野町広小路 徒歩 1 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional"],
    lat: 36.5572,
    lon: 136.6608,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["morohachi", "1849", "176_years", "rakugan_specialty", "nomachi"],
    source: "manual",
  },
  {
    slug: "maruhachi-bocha-1863",
    category: "food",
    sub_type: "ishikawa_kanazawa_meika",
    title_zh: "丸八製茶場(加賀市・1863 創業・162 年+ 加賀棒茶発祥+ 茎茶焙煎独自製法)",
    title_ja: "丸八製茶場",
    romaji: "Maruhachi Seichajo",
    summary_zh: "**丸八製茶場は加賀棒茶の発祥老舗**(加賀市・**1863 創業・162 年**)。**茎茶を焙煎する加賀独自製法**を完成、明治期に「献上加賀棒茶」が確立、R1 食既出 森八 1625 落雁 + 加賀料理と並ぶ加賀百万石食文化の柱。R1 楽既出 加賀温泉郷からのアクセス良好、JR 加賀温泉駅近接。",
    content_md: "- 創業:1863 年(文久 3)・162 年\n- 立地:加賀市動橋町本店\n- 発祥:**加賀棒茶**(茎茶焙煎独自製法)\n- 著名:献上加賀棒茶(明治期確立)\n- 特性:**茎茶 + 焙煎香 + 苦みが少なく旨味中心**\n- 用途:加賀料理後茶 + 朝食茶 + 観光客土産\n- 営業:9:30-17:00 通年\n- アクセス:JR 加賀温泉駅 → バス 7 分・JR 動橋駅 徒歩 5 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "加賀市",
    lg_code: "17206",
    area_types: ["restaurant_traditional"],
    lat: 36.3022,
    lon: 136.3097,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.kagaboucha.com/" },
    tags: ["maruhachi_seichajo", "1863", "162_years", "kagabocha_origin", "kuki_cha"],
    source: "manual",
  },
  {
    slug: "nakatani-kintsuba-1934",
    category: "food",
    sub_type: "ishikawa_kanazawa_meika",
    title_zh: "中田屋(金沢市・1934 創業・91 年+ きんつば専門老舗+ うぐいすあん独自製法)",
    title_ja: "中田屋",
    romaji: "Nakatani",
    summary_zh: "**中田屋は金沢きんつば老舗**(金沢市・**1934 創業・91 年**)。**うぐいすあん(青えんどう)の独自製法**で全国きんつば 名店、R1 食既出 森八 1625 + 諸江屋 1849 と並ぶ金沢和菓子 3 大柱。横安江町本店 + 県内 + 北陸新幹線駅出店、JR 金沢駅 100 番街 内も買える観光客対応。",
    content_md: "- 創業:1934 年(昭和 9)・91 年\n- 立地:金沢市横安江町本店 + 金沢駅 100 番街\n- 名物:**きんつば**(うぐいすあん独自製法)\n- 特性:**青えんどう餡(うぐいすあん)+ 焼皮の香ばしさ**\n- 並列:R1 食 森八 1625 + 諸江屋 1849 と金沢和菓子 3 大柱\n- 営業:9:00-19:00 通年\n- アクセス:JR 金沢駅 → バス 8 分(横安江町)・駅 100 番街徒歩 1 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional"],
    lat: 36.5797,
    lon: 136.6500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.kintuba.co.jp/" },
    tags: ["nakatani", "1934", "91_years", "kintsuba", "uguisuan", "yokoyasue"],
    source: "manual",
  },
  {
    slug: "fukume-shogatsu-kanazawa",
    category: "food",
    sub_type: "ishikawa_kanazawa_meika",
    title_zh: "福梅(金沢市・加賀藩流れ正月菓子+ 紅白梅形+ 1 月限定+ 森八 + 諸江屋等で製造)",
    title_ja: "福梅",
    romaji: "Fukume",
    summary_zh: "**福梅は金沢正月菓子**(石川県全域・**加賀藩流れ伝統+ 紅白梅形+ 1 月限定**)。**前田家家紋「梅鉢」をモチーフ**、R1 育既出 第十七卷 motif と完全一致、森八 1625 + 諸江屋 1849 + 中田屋 1934 等の金沢和菓子各店が製造、年末-1 月の家庭祝い菓子。",
    content_md: "- 性格:加賀藩流れ正月菓子\n- 形状:**紅白梅形**(前田家家紋「梅鉢」由来)\n- モチーフ:**第十七卷 ishikawa_umebachi motif と完全一致**\n- 季節:12 月-1 月限定販売\n- 製造:森八 1625 + 諸江屋 1849 + 中田屋 1934 + 多数の金沢和菓子店\n- 用途:年末年始の家庭祝い菓子 + 茶席菓子\n- 価格:5-10 個入 ¥1,500-3,500\n- 購買:近江町市場 + 各和菓子店",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional"],
    lat: 36.5681,
    lon: 136.6620,
    season_start: "2026-12-15",
    season_end: "2026-01-31",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["fukume", "umebachi_form", "shogatsu", "maeda_kamon", "regional_seasonal"],
    source: "manual",
  },
  {
    slug: "kaga-bocha-overview",
    category: "food",
    sub_type: "ishikawa_kanazawa_meika",
    title_zh: "加賀棒茶(石川県全域・茎茶焙煎独自製法+ 丸八製茶場 1863 発祥+ 全国茶郷 北限)",
    title_ja: "加賀棒茶",
    romaji: "Kaga Bocha",
    summary_zh: "**加賀棒茶は石川県独自の茶文化**(石川県全域・**茎茶焙煎独自製法**)。**茶葉の茎部分を焙煎+ 苦み少なく旨味中心**、R1 食既出 丸八製茶場 1863 が発祥、加賀料理 + 加賀和菓子の伴茶として定着、現在は石川県内全域 + 北陸新幹線でブームに。",
    content_md: "- 産地:石川県全域(加賀市 + 金沢市中心)\n- 製法:**茎茶を焙煎+ 焙烙香 + 旨味中心**\n- 発祥:**丸八製茶場 1863 創業 162 年**(R1 食既出)\n- 特性:カフェイン少なめ + 苦みなし + 食事と相性良\n- 用途:加賀料理 + 加賀和菓子 + 朝食茶 + 老人 + 子供向け\n- 流通:全国茶ブランドとして拡散\n- 主要販売店:丸八製茶場 + 一保堂茶舗(京都老舗扱い)+ 全国百貨店\n- 価格:100g ¥800-1,800",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional"],
    lat: 36.5681,
    lon: 136.6620,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["kaga_bocha", "kuki_cha", "regional_signature", "low_caffeine", "northern_tea_origin"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 石川酒蔵 (4) — 福光屋 1625+ 萬歳楽 1716+ 農口尚彦+ 数馬酒造 1869
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "fukumitsuya-1625-kanazawa",
    category: "food",
    sub_type: "ishikawa_brewery",
    title_zh: "福光屋(金沢市・1625 創業・400 年+ 石川県最古酒蔵+ 純米酒蔵元化 1976 業界先駆)",
    title_ja: "福光屋",
    romaji: "Fukumitsuya",
    summary_zh: "**福光屋は石川県最古酒蔵**(金沢市・**1625 創業・400 年**)。**1976 純米酒蔵元化 業界先駆者**、加賀百万石の都の蔵元、R1 食既出 森八 1625(同年創業)と並ぶ加賀 400 年文化遺産 2 大柱。直営 SAKE SHOP「福光屋」で蔵見学 + 試飲可能。",
    content_md: "- 創業:1625 年(寛永 2)・400 年\n- 立地:金沢市石引(本店 + 蔵)\n- 全国順位:**石川県最古酒蔵**\n- 革新:**1976 全銘柄純米酒蔵元化**(全国先駆者)\n- 主要銘柄:加賀鳶 + 黒帯 + 福正宗\n- 並列:R1 食 森八 1625(同年創業)= 加賀 400 年文化 2 大柱\n- 蔵見学:直営 SAKE SHOP「福光屋」金沢で試飲 + 購入\n- 営業:10:00-19:00 通年(直営店)\n- アクセス:JR 金沢駅 → 北鉄バス 15 分(石引地区)",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "金沢市",
    lg_code: "17201",
    area_types: ["restaurant_traditional", "industrial_heritage"],
    lat: 36.5836,
    lon: 136.6850,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: null,
    closed_days: [],
    external_urls: { official: "https://www.fukumitsuya.co.jp/" },
    tags: ["fukumitsuya", "1625", "400_years", "oldest_ishikawa", "junmai_pioneer_1976"],
    source: "manual",
  },
  {
    slug: "manzairaku-shuzo-1716",
    category: "food",
    sub_type: "ishikawa_brewery",
    title_zh: "小堀酒造店(白山市鶴来・1716 創業・309 年+ 萬歳楽銘柄+ 白山伏流水仕込)",
    title_ja: "小堀酒造店(萬歳楽)",
    romaji: "Kobori Shuzoten",
    summary_zh: "**小堀酒造店は加賀國代表酒蔵**(白山市鶴来・**1716 創業・309 年**)。**萬歳楽銘柄+ 白山伏流水仕込独自製法**、R1 食既出 福光屋 1625(金沢)に次ぐ石川 2 番目老舗、R1 育既出 白山比咩神社 御用酒として奉納。蔵見学 + 試飲可能、加能ガニシーズン人気。",
    content_md: "- 創業:1716 年(享保 1)・309 年\n- 立地:白山市鶴来(鶴来駅近接)\n- 主要銘柄:**萬歳楽 + 加賀の酒**\n- 仕込:**白山伏流水**(白山比咩神社 御神水系)\n- 並列:R1 食 福光屋 1625 と石川県内 1+ 2 老舗\n- 蔵見学:可能(要予約)・試飲 + 購入\n- 並列拠点:R1 育 白山比咩神社 (徒歩 10 分)\n- 営業:9:00-17:00(月休)\n- アクセス:北鉄石川線鶴来駅 徒歩 5 分",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "白山市",
    lg_code: "17210",
    area_types: ["restaurant_traditional", "industrial_heritage"],
    lat: 36.4364,
    lon: 136.6342,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 7,
    closed_days: ["mon"],
    external_urls: { official: "https://www.manzairaku.co.jp/" },
    tags: ["kobori_shuzoten", "manzairaku", "1716", "309_years", "hakusan_water"],
    source: "manual",
  },
  {
    slug: "noguchi-naohiko-shuzo-2017",
    category: "food",
    sub_type: "ishikawa_brewery",
    title_zh: "農口尚彦研究所(小松市・2017 設立+ 「現代の名工」農口杜氏研究蔵+ 卓越技術伝承拠点)",
    title_ja: "農口尚彦研究所",
    romaji: "Noguchi Naohiko Sake Institute",
    summary_zh: "**農口尚彦研究所は伝説杜氏の技術伝承蔵**(小松市・**2017 設立**)。**「現代の名工」農口尚彦杜氏(85+ 歳・60+ 年酒造経験)の研究蔵**、R1 食既出 福光屋 1625 + 萬歳楽 1716 の伝統老舗とは別軸の現代日本酒の最先端。蔵見学+ 試飲予約制、希少銘柄。",
    content_md: "- 設立:2017 年・8 年\n- 立地:小松市瀬領町\n- 杜氏:**農口尚彦氏(現代の名工)**\n- 経歴:60+ 年の酒造経験+ 数々の名酒造り\n- 性格:**伝説杜氏研究蔵+ 技術伝承施設**\n- 銘柄:農口尚彦研究所 数種(年生産限定)\n- 蔵見学:**完全予約制・有料**\n- 並列:R1 食 福光屋 + 萬歳楽の伝統老舗とは別軸\n- アクセス:JR 小松駅 → 車 30 分・公共交通限定的(車推奨)",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "小松市",
    lg_code: "17203",
    area_types: ["industrial_heritage", "rural"],
    lat: 36.3917,
    lon: 136.4561,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["noguchi_naohiko", "2017", "modern_master", "research_brewery", "premium"],
    source: "manual",
  },
  {
    slug: "kazuma-shuzo-1869-noto",
    category: "food",
    sub_type: "ishikawa_brewery",
    title_zh: "数馬酒造(能登町・1869 創業・156 年+ 竹葉銘柄+ 能登半島代表酒蔵+ 能登杜氏発祥地)",
    title_ja: "数馬酒造",
    romaji: "Kazuma Shuzo",
    summary_zh: "**数馬酒造は能登半島代表酒蔵**(能登町・**1869 創業・156 年**)。**竹葉(ちくは)銘柄+ 能登杜氏発祥地**、R1 食既出 福光屋 1625(加賀國)と対をなす能登國代表蔵、能登町宇出津港近隣の港町酒蔵。**2024 元日能登半島地震で被災**、復旧中(2026 現在)も歴史継続。",
    content_md: "- 創業:1869 年(明治 2)・156 年\n- 立地:能登町宇出津(うしつ)\n- 主要銘柄:**竹葉(ちくは)**\n- 系譜:**能登杜氏発祥地の代表蔵**\n- 並列:R1 食 福光屋 1625(加賀國)と能登國代表蔵\n- 災害:**2024 元日 能登半島地震で被災**(復旧中)\n- 営業:9:00-17:00(被災状況により変動・要事前確認)\n- アクセス:JR 七尾線 + 能登バス・公共交通限定的(車推奨)",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: "鳳珠郡",
    municipality_ja: "能登町",
    lg_code: "17463",
    area_types: ["industrial_heritage", "coastal"],
    lat: 37.3072,
    lon: 137.2306,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 14,
    closed_days: [],
    external_urls: { official: "https://chikuha.co.jp/" },
    tags: ["kazuma_shuzo", "chikuha", "1869", "156_years", "noto_toji_origin", "2024_quake"],
    source: "manual",
  },

  // ════════════════════════════════════════════════════════════════════
  // 能登産物 (3) — 輪島朝市+ 能登ふぐ+ 珠洲塩
  // ════════════════════════════════════════════════════════════════════
  {
    slug: "wajima-asaichi-1000-years",
    category: "food",
    sub_type: "ishikawa_noto_san",
    title_zh: "輪島朝市(輪島市・千年市場+ 日本三大朝市の 1+ 200+ 軒の海産物 + 干物 + 自家製品)",
    title_ja: "輪島朝市",
    romaji: "Wajima Asaichi",
    summary_zh: "**輪島朝市は日本三大朝市の 1**(輪島市本通り・**千年市場・平安期からの伝統**)。**200+ 軒の海産物 + 干物 + 自家製品集積**、岐阜高山宮川朝市 + 千葉勝浦朝市と並ぶ全国 3 大、能登半島観光の中核。**2024 元日能登半島地震で大火被災**、復興中(2026 現在は規模縮小ながら継続営業)。",
    content_md: "- 起源:平安期(1000+ 年・伝承)\n- 立地:輪島市河井町本通り\n- 全国順位:**日本三大朝市**(高山 + 勝浦 + 輪島)\n- 規模:**200+ 軒**(被災前)・現在 100+ 軒(復興中)\n- 商品:海産物 + 干物 + 自家製品 + 輪島塗\n- 開催:8:00-12:00 毎日(火 + 第 2/4 水休)\n- 災害:**2024 元日 能登半島地震 + 大火で被災**\n- 復興:2026 現在 規模縮小ながら継続営業\n- アクセス:JR 七尾線 → 能登バス 約 1.5 時間",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "輪島市",
    lg_code: "17204",
    area_types: ["shopping_district", "historic_district"],
    lat: 37.3917,
    lon: 136.9008,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: ["tue"],
    external_urls: {},
    tags: ["wajima_asaichi", "1000_years", "top3_japan", "200_shops", "2024_quake_recovery"],
    source: "manual",
  },
  {
    slug: "noto-fugu-overview",
    category: "food",
    sub_type: "ishikawa_noto_san",
    title_zh: "能登ふぐ(能登半島・天然ふぐ全国シェア大+ 白子珍味+ 11-3 月旬+ 能登町輪島市集積)",
    title_ja: "能登ふぐ",
    romaji: "Noto Fugu",
    summary_zh: "**能登ふぐは石川独自のふぐ食文化**(能登半島全域・**天然ふぐ漁獲全国上位**)。**白子+ 刺身+ 鍋+ から揚げの郷土調理**、能登町宇出津港 + 輪島港 中心、11-3 月旬。下関ふぐ + 大阪ふぐと並ぶ全国 3 大ふぐ食文化の 1。",
    content_md: "- 産地:能登半島(能登町宇出津港 + 輪島港 中心)\n- 全国順位:**天然ふぐ漁獲全国上位**\n- 旬:**11 月-3 月**(冬 4 ヶ月)\n- 名物調理:刺身(てっさ)+ 鍋(てっちり)+ 白子焼 + から揚げ\n- 並列:下関ふぐ + 大阪ふぐと全国 3 大ふぐ食文化\n- 食堂:輪島市 + 能登町 多数\n- 価格:ふぐ会席 ¥8,000-15,000\n- アクセス:JR 七尾線 → 能登バス + 車推奨",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "能登町",
    lg_code: "17463",
    area_types: ["restaurant_traditional", "coastal"],
    lat: 37.3072,
    lon: 137.2306,
    season_start: "2026-11-01",
    season_end: "2026-03-31",
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["noto_fugu", "wild_caught", "winter_delicacy", "shirako", "top3_japan"],
    source: "manual",
  },
  {
    slug: "suzu-shio-agehama-350",
    category: "food",
    sub_type: "ishikawa_noto_san",
    title_zh: "珠洲塩 揚浜式塩田(珠洲市・350+ 年伝統+ 国指定無形民俗文化財 2008+ 全国唯一現役揚浜式)",
    title_ja: "珠洲塩 揚浜式塩田",
    romaji: "Suzu Shio Agehama",
    summary_zh: "**珠洲揚浜式塩田は全国唯一現役の伝統製塩**(珠洲市・**350+ 年伝統+ 国指定無形民俗文化財 2008**)。**桶で海水を汲み上げ砂浜に撒く揚浜式**、現代では珠洲市 数軒のみ継承、塩田奥能登 + 道の駅すず塩田村で見学 + 体験可能。**2024 能登半島地震で被災**、復興中。",
    content_md: "- 立地:珠洲市清水町(揚浜式塩田)\n- 起源:**350+ 年伝統**(江戸期から)\n- 文化財:**国指定無形民俗文化財 2008**\n- 製法:**揚浜式**(桶汲海水 → 砂浜撒 → 塩水濃縮 → 釜煎)\n- 全国順位:**全国唯一現役の伝統揚浜式**\n- 体験:塩田奥能登 + 道の駅すず塩田村で見学 + 体験予約可\n- 災害:**2024 能登半島地震で被災**(復興中)\n- 商品:珠洲塩(味噌 + 漬物 + パスタ等で全国流通)\n- アクセス:JR 七尾線 → 能登バス約 2 時間 + 車推奨",
    region: "chubu",
    prefecture_ja: "石川県",
    gun_ja: null,
    municipality_ja: "珠洲市",
    lg_code: "17205",
    area_types: ["industrial_heritage", "coastal"],
    lat: 37.4750,
    lon: 137.3306,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 7,
    closed_days: [],
    external_urls: {},
    tags: ["suzu_shio", "agehama", "350_years", "national_intangible_2008", "only_japan", "2024_quake"],
    source: "manual",
  },
];

async function main() {
  if (rows.length === 0) {
    console.log("[ishikawa-food-r1] 尚無條目");
    return;
  }
  console.log(`[ishikawa-food-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) {
      console.log(`  ${k.padEnd(28)} ${v}`);
    }
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) {
      console.error("[ishikawa-food-r1] upsert failed:", error);
      process.exit(1);
    }
    written += batch.length;
    process.stdout.write(`\r[ishikawa-food-r1] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[ishikawa-food-r1] Done — ${written} rows.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
