// Seed 愛媛県 住 R1(20 筆 / Sprint 17.3)
// 道後温泉 5 / 松山+ 中予 4 / 今治+ 東予 4 / 宇和島+ 南予 4 / 山地+ しまなみ 3 = 20
// 累積 45 + 20 = 65 entries
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  {
    slug: "dogo-onsen-honkan-stay",
    category: "lodging", sub_type: "ehime_onsen",
    title_zh: "道後温泉本館+ 周辺旅館宿(松山市道後・1894 年道後温泉本館創建 131+ 年+ 国指定重要文化財 1994+ 日本最古 3000 年伝承+ 道後 30+ 旅館・「ふなや」 1627 創業 398+ 年+ 「大和屋本店」 1868 157+ 年・¥18,000-65,000/泊)",
    title_ja: "道後温泉本館旅館", romaji: "Dōgo Onsen Honkan",
    summary_zh: "**道後温泉本館+周辺旅館は 1894 創建 131+ 年+国重文 1994+日本最古 3000 年伝承+道後 30+ 旅館・ふなや 1627 398+ 年+大和屋本店 1868 157+ 年**(松山道後)。¥18,000-65,000/泊。",
    content_md: "- 立地:**松山市道後温泉**\n- 起源:**1894 年道後温泉本館創建 131+ 年 + 国指定重要文化財 1994 + 日本最古 3000 年伝承**\n- 派生:**道後 30+ 旅館 → 「ふなや」 1627 創業 398+ 年 + 「大和屋本店」 1868 157+ 年**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["lodging_traditional"],
    lat: 33.8517, lon: 132.7864,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["dogo_onsen_honkan_1894"], source: "manual",
  },
  {
    slug: "dogo-asuka-no-yu",
    category: "lodging", sub_type: "ehime_onsen",
    title_zh: "道後温泉別館飛鳥乃湯泉+ 飛鳥時代再現(松山市道後・2017 道後温泉別館飛鳥乃湯泉開館 8+ 年+ R1 住 道後 1894 派生・飛鳥時代再現+ 仏具+ 山伏湯+ 観光客代表新名所・入湯 ¥600+ 個室 ¥1,690)",
    title_ja: "飛鳥乃湯泉", romaji: "Asuka no Yu",
    summary_zh: "**道後温泉別館飛鳥乃湯泉は 2017 開館 8+ 年・R1 住 1894 派生・飛鳥時代再現+仏具+山伏湯**(松山道後)。入湯 ¥600+個室 ¥1,690、観光代表新名所。",
    content_md: "- 立地:**松山市道後温泉**\n- 起源:**2017 道後温泉別館飛鳥乃湯泉開館 8+ 年**\n- 関連:**R1 住 道後 1894 派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["lodging_traditional"],
    lat: 33.8517, lon: 132.7864,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["dogo_asuka_2017"], source: "manual",
  },
  {
    slug: "dogo-tsubaki-yu",
    category: "lodging", sub_type: "ehime_onsen",
    title_zh: "道後温泉椿の湯+ 地元市民湯(松山市道後・1953 道後温泉椿の湯開館 72+ 年+ R1 住 道後 1894 派生・地元市民湯+ 伊予椿伝承+ 入湯 ¥450+ 朝 6 時開館・地元代表)",
    title_ja: "道後椿の湯", romaji: "Dōgo Tsubaki no Yu",
    summary_zh: "**道後温泉椿の湯+地元市民湯は 1953 開館 72+ 年・R1 住 1894 派生・地元市民湯+伊予椿伝承+入湯 ¥450+朝 6 時開館**(松山道後)。地元代表。",
    content_md: "- 立地:**松山市道後温泉**\n- 起源:**1953 道後温泉椿の湯開館 72+ 年**\n- 関連:**R1 住 道後 1894 派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["lodging_traditional"],
    lat: 33.8517, lon: 132.7864,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["dogo_tsubaki_yu_1953"], source: "manual",
  },
  {
    slug: "matsuyama-ana-bus-stay",
    category: "lodging", sub_type: "ehime_business",
    title_zh: "松山 ANA クラウンプラザ+ 松山駅前+ 大街道(松山市・1995 ANA クラウンプラザ松山開業 30+ 年+ 松山駅徒歩 5 分+ 大街道徒歩 10 分+ R1 食 松山郷土料理+ R1 衣 大街道商店街派生・¥12,000-32,000/泊)",
    title_ja: "ANA クラウン松山", romaji: "ANA Crown Matsuyama",
    summary_zh: "**松山 ANA クラウンプラザは 1995 開業 30+ 年・駅徒歩 5 分+大街道徒歩 10 分+R1 食+衣 派生**(松山)。¥12,000-32,000/泊。",
    content_md: "- 立地:**松山市駅前+ 大街道**\n- 起源:**1995 ANA クラウンプラザ松山開業 30+ 年**\n- 関連:**R1 食 松山郷土料理 + R1 衣 大街道商店街派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["lodging_business"],
    lat: 33.8392, lon: 132.7655,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["matsuyama_ana_crown_1995"], source: "manual",
  },
  {
    slug: "matsuyama-tokyu-rei-hotel",
    category: "lodging", sub_type: "ehime_business",
    title_zh: "松山東急 REI ホテル+ 松山駅前(松山市駅前・2007 松山東急 REI 開業 18+ 年+ 松山駅徒歩 1 分+ R1 食 松山郷土料理+ R1 衣 大街道派生+ ビジネス客代表・¥9,500-22,000/泊)",
    title_ja: "松山東急 REI", romaji: "Matsuyama Tōkyū REI",
    summary_zh: "**松山東急 REI ホテルは 2007 開業 18+ 年・松山駅徒歩 1 分+R1 食+衣 派生・ビジネス客代表**(松山駅前)。¥9,500-22,000/泊。",
    content_md: "- 立地:**松山市駅前**\n- 起源:**2007 松山東急 REI 開業 18+ 年**\n- 関連:**R1 食 松山郷土料理 + R1 衣 大街道派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["lodging_business"],
    lat: 33.8392, lon: 132.7655,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["matsuyama_tokyu_rei_2007"], source: "manual",
  },
  {
    slug: "matsuyama-castle-stay",
    category: "lodging", sub_type: "ehime_traditional",
    title_zh: "松山城周辺旅館宿+ 大街道(松山市・松山城江戸期 1602 加藤嘉明築城 423+ 年+ 大街道周辺旅館 30+ 軒・「東屋」 1880 創業 145+ 年+「ホテル ECCEE 松山」 2014・¥8,500-25,000/泊)",
    title_ja: "松山城旅館", romaji: "Matsuyama Castle Stay",
    summary_zh: "**松山城周辺旅館は松山城 1602 加藤嘉明 423+ 年+大街道周辺 30+ 軒・東屋 1880 145+ 年+ホテル ECCEE 松山 2014**(松山)。¥8,500-25,000/泊。",
    content_md: "- 立地:**松山市大街道**\n- 起源:**松山城江戸期 1602 加藤嘉明築城 423+ 年**\n- 派生:**大街道周辺旅館 30+ 軒 → 「東屋」 1880 創業 145+ 年 + 「ホテル ECCEE 松山」 2014**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "松山市", lg_code: "38201",
    area_types: ["lodging_traditional"],
    lat: 33.8392, lon: 132.7655,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["matsuyama_castle_ryokan"], source: "manual",
  },
  {
    slug: "imabari-kokusai-hotel",
    category: "lodging", sub_type: "ehime_business",
    title_zh: "今治国際ホテル+ しまなみ海道玄関(今治市駅前・2014 今治国際ホテル新装 11+ 年+ 今治駅徒歩 5 分+ R1 衣 タオル 1894+ R1 食 今治焼鳥派生・しまなみ海道玄関ビジネス・¥12,000-25,000/泊)",
    title_ja: "今治国際ホテル", romaji: "Imabari Kokusai",
    summary_zh: "**今治国際ホテル+しまなみ海道玄関は 2014 新装 11+ 年・駅徒歩 5 分+R1 衣 タオル+R1 食 焼鳥派生**(今治駅前)。¥12,000-25,000/泊。",
    content_md: "- 立地:**今治市駅前**\n- 起源:**2014 今治国際ホテル新装 11+ 年**\n- 関連:**R1 衣 今治タオル 1894 + R1 食 今治焼鳥派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "今治市", lg_code: "38202",
    area_types: ["lodging_business"],
    lat: 34.0660, lon: 132.9988,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["imabari_kokusai_2014"], source: "manual",
  },
  {
    slug: "shimanami-cycling-pension",
    category: "lodging", sub_type: "ehime_pension",
    title_zh: "しまなみ海道サイクリングペンション+ 大三島(今治市大三島・1999 しまなみ海道開通 26+ 年+ 全国サイクリングロード 70km+ サイクリスト向けペンション 50+ 軒・「ホテル大三島」 2005 20+ 年・¥8,500-22,000/泊)",
    title_ja: "しまなみペンション", romaji: "Shimanami Pension",
    summary_zh: "**しまなみサイクリングペンション+大三島は 1999 開通 26+ 年+全国 70km+サイクリスト向け 50+ 軒・大三島 2005 20+ 年**(今治大三島)。¥8,500-22,000/泊。",
    content_md: "- 立地:**今治市大三島**\n- 起源:**1999 しまなみ海道開通 26+ 年 + 全国サイクリングロード 70km**\n- 派生:**サイクリスト向けペンション 50+ 軒 → 「ホテル大三島」 2005 20+ 年**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "今治市", lg_code: "38202",
    area_types: ["lodging_pension"],
    lat: 34.2547, lon: 133.0119,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shimanami_pension_1999"], source: "manual",
  },
  {
    slug: "saijo-uchinuki-spa",
    category: "lodging", sub_type: "ehime_onsen",
    title_zh: "西条うちぬき水温泉宿+ 名水温泉(西条市・西条「うちぬき」 自噴湧水 環境省名水 100 選 1985+ R1 食 うちぬき豆腐派生・名水温泉ホテル 5+ 軒+ 西条祭り 1670 連動・¥9,500-25,000/泊)",
    title_ja: "西条うちぬき温泉", romaji: "Saijō Uchinuki Onsen",
    summary_zh: "**西条うちぬき水温泉宿は名水 100 選 1985+R1 食 うちぬき豆腐派生・名水温泉ホテル 5+ 軒+西条祭り 1670 連動**(西条)。¥9,500-25,000/泊。",
    content_md: "- 立地:**西条市本町**\n- 起源:**西条「うちぬき」自噴湧水 環境省名水 100 選 1985**\n- 関連:**R1 食 うちぬき豆腐派生 + 西条祭り 1670 連動**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "西条市", lg_code: "38206",
    area_types: ["lodging_onsen"],
    lat: 33.9192, lon: 133.1809,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["saijo_uchinuki_spa"], source: "manual",
  },
  {
    slug: "uwajima-castle-stay",
    category: "lodging", sub_type: "ehime_traditional",
    title_zh: "宇和島城周辺旅館宿+ 中央町(宇和島市中央町・宇和島城江戸期 1601 藤堂高虎築城 424+ 年+ 国指定重要文化財 1934+ 中央町旅館 30+ 軒・「松屋旅館」 1893 132+ 年・¥8,500-22,000/泊)",
    title_ja: "宇和島城旅館", romaji: "Uwajima Castle Stay",
    summary_zh: "**宇和島城周辺旅館は 1601 藤堂高虎 424+ 年+国重文 1934+中央町 30+ 軒・松屋 1893 132+ 年**(宇和島中央町)。¥8,500-22,000/泊。",
    content_md: "- 立地:**宇和島市中央町**\n- 起源:**宇和島城江戸期 1601 藤堂高虎築城 424+ 年 + 国指定重要文化財 1934**\n- 派生:**中央町旅館 30+ 軒 → 「松屋旅館」 1893 創業 132+ 年**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "宇和島市", lg_code: "38203",
    area_types: ["lodging_traditional"],
    lat: 33.2235, lon: 132.5611,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["uwajima_castle_stay_1601"], source: "manual",
  },
  {
    slug: "ozu-kawanoyado-machiya",
    category: "lodging", sub_type: "ehime_machiya",
    title_zh: "大洲 NIPPONIA 町家ホテル+ 古民家(大洲市本町・大洲城 1617+ NIPPONIA HOTEL 大洲 城下町 2020 開業 5+ 年+ 古民家リノベーション+ 城下町分散ホテル 30+ 軒+ 全国古民家ブランド代表・¥18,000-65,000/泊)",
    title_ja: "NIPPONIA 大洲", romaji: "Nipponia Ōzu",
    summary_zh: "**大洲 NIPPONIA 町家ホテルは大洲城 1617+2020 開業 5+ 年・古民家リノベ+城下町分散 30+ 軒+全国古民家ブランド代表**(大洲本町)。¥18,000-65,000/泊。",
    content_md: "- 立地:**大洲市本町**\n- 起源:**大洲城 1617 + NIPPONIA HOTEL 大洲 城下町 2020 開業 5+ 年**\n- 派生:**古民家リノベーション + 城下町分散ホテル 30+ 軒 → 全国古民家ブランド代表**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "大洲市", lg_code: "38207",
    area_types: ["lodging_machiya"],
    lat: 33.5061, lon: 132.5461,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["nipponia_ozu_2020"], source: "manual",
  },
  {
    slug: "uchiko-machiya-stay",
    category: "lodging", sub_type: "ehime_machiya",
    title_zh: "内子古民家民宿+ 八日市護国(喜多郡内子町・1804 木蝋業 220+ 年+ 国指定伝建群 1982+ 八日市古民家民宿 5+ 軒・「あさもや」 2018+ 「鶴亀」 古民家・¥9,500-22,000/泊)",
    title_ja: "内子古民家民宿", romaji: "Uchiko Machiya",
    summary_zh: "**内子古民家民宿+八日市護国は 1804 220+ 年+国指定伝建群 1982+古民家 5+ 軒・あさもや 2018+鶴亀**(喜多郡内子)。¥9,500-22,000/泊。",
    content_md: "- 立地:**喜多郡内子町本町・八日市護国地区**\n- 起源:**1804 木蝋業 220+ 年 + 国指定伝統的建造物群保存地区 1982**\n- 派生:**八日市古民家民宿 5+ 軒 → 「あさもや」 2018 + 「鶴亀」古民家**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "喜多郡", municipality_ja: "内子町", lg_code: "38422",
    area_types: ["lodging_machiya"],
    lat: 33.5400, lon: 132.6586,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["uchiko_machiya"], source: "manual",
  },
  {
    slug: "kuma-kogen-onsen",
    category: "lodging", sub_type: "ehime_onsen",
    title_zh: "久万高原山地温泉+ 古岩屋温泉(上浮穴郡久万高原町・標高 800m+ 古岩屋温泉 1985 開業 40+ 年+ 山地天然温泉+ R1 食 久万高原じゃがいも派生+ 久万高原町ふるさと納税代表・¥9,500-18,000/泊)",
    title_ja: "久万高原温泉", romaji: "Kuma Kōgen Onsen",
    summary_zh: "**久万高原山地温泉+古岩屋温泉は標高 800m+1985 開業 40+ 年・山地天然+R1 食 じゃがいも派生**(上浮穴郡久万高原)。¥9,500-18,000/泊。",
    content_md: "- 立地:**上浮穴郡久万高原町**\n- 起源:**標高 800m + 古岩屋温泉 1985 開業 40+ 年**\n- 関連:**R1 食 久万高原じゃがいも派生 + 久万高原町ふるさと納税代表**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "上浮穴郡", municipality_ja: "久万高原町", lg_code: "38386",
    area_types: ["lodging_onsen"],
    lat: 33.6562, lon: 132.9011,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kuma_kogen_onsen_1985"], source: "manual",
  },
  {
    slug: "iyo-tobata-spa",
    category: "lodging", sub_type: "ehime_onsen",
    title_zh: "伊予とば温泉+ 海岸温泉(伊予市港町・1985 とば温泉開業 40+ 年+ R1 食 伊予いけ貝派生・伊予灘海岸温泉ホテル 5+ 軒・¥9,500-22,000/泊)",
    title_ja: "伊予とば温泉", romaji: "Iyo Tobata Onsen",
    summary_zh: "**伊予とば温泉+海岸温泉は 1985 開業 40+ 年・R1 食 いけ貝派生・伊予灘海岸 5+ 軒**(伊予港町)。¥9,500-22,000/泊。",
    content_md: "- 立地:**伊予市港町**\n- 起源:**1985 とば温泉開業 40+ 年**\n- 関連:**R1 食 伊予いけ貝派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "伊予市", lg_code: "38210",
    area_types: ["lodging_onsen"],
    lat: 33.7531, lon: 132.7050,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["iyo_tobata_1985"], source: "manual",
  },
  {
    slug: "yawatahama-port-stay",
    category: "lodging", sub_type: "ehime_business",
    title_zh: "八幡浜港町ビジネス宿+ どーや市場前(八幡浜市港町・1980 年代以降港町ホテル開業 45+ 年+ R1 食 じゃこ天+ R1 衣 どーや市場派生・八幡浜港 5+ 軒・¥6,500-15,000/泊)",
    title_ja: "八幡浜港町ホテル", romaji: "Yawatahama Port",
    summary_zh: "**八幡浜港町ビジネス宿は 1980 年代以降 45+ 年・R1 食 じゃこ天+R1 衣 どーや市場派生・港 5+ 軒**(八幡浜港町)。¥6,500-15,000/泊。",
    content_md: "- 立地:**八幡浜市港町**\n- 起源:**1980 年代以降港町ホテル開業 45+ 年**\n- 関連:**R1 食 じゃこ天 + R1 衣 どーや市場派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "八幡浜市", lg_code: "38204",
    area_types: ["lodging_business"],
    lat: 33.4659, lon: 132.4226,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yawatahama_port_stay"], source: "manual",
  },
  {
    slug: "niihama-besshi-stay",
    category: "lodging", sub_type: "ehime_business",
    title_zh: "新居浜駅前ビジネス宿+ 別子玄関(新居浜市駅前・1990 年代以降駅前ホテル開業 35+ 年+ R1 衣 別子銅山 1690+ R1 食 新居浜マーマレード派生・新居浜駅 5+ 軒・¥7,500-16,000/泊)",
    title_ja: "新居浜駅前ホテル", romaji: "Niihama Eki",
    summary_zh: "**新居浜駅前ビジネス宿は 1990 年代以降 35+ 年・R1 衣 別子+R1 食 マーマレード派生・新居浜駅 5+ 軒**(新居浜駅前)。¥7,500-16,000/泊。",
    content_md: "- 立地:**新居浜市駅前**\n- 起源:**1990 年代以降駅前ホテル開業 35+ 年**\n- 関連:**R1 衣 別子銅山 1690 + R1 食 新居浜マーマレード派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: null, municipality_ja: "新居浜市", lg_code: "38205",
    area_types: ["lodging_business"],
    lat: 33.9603, lon: 133.2829,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["niihama_eki_stay"], source: "manual",
  },
  {
    slug: "ainan-pearl-resort",
    category: "lodging", sub_type: "ehime_pension",
    title_zh: "愛南町深浦真珠リゾート+ 宇和海(南宇和郡愛南町深浦・1907 御木本真珠 118+ 年+ R1 衣 愛南真珠派生・深浦真珠リゾート 1990 年代以降 35+ 年+ 海陽サーフ+ ダイビング・¥9,500-22,000/泊)",
    title_ja: "愛南真珠リゾート", romaji: "Ainan Pearl",
    summary_zh: "**愛南町深浦真珠リゾートは 1907 真珠 118+ 年+R1 衣 愛南真珠派生・1990 年代以降 35+ 年+サーフ+ダイビング**(南宇和郡愛南深浦)。¥9,500-22,000/泊。",
    content_md: "- 立地:**南宇和郡愛南町深浦**\n- 起源:**1907 御木本真珠養殖 118+ 年 + 1990 年代以降深浦真珠リゾート 35+ 年**\n- 関連:**R1 衣 愛南真珠派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "南宇和郡", municipality_ja: "愛南町", lg_code: "38506",
    area_types: ["lodging_pension"],
    lat: 32.9617, lon: 132.5814,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["ainan_pearl_resort"], source: "manual",
  },
  {
    slug: "kamijima-island-pension",
    category: "lodging", sub_type: "ehime_pension",
    title_zh: "上島町島ペンション+ レモン宿(越智郡上島町岩城+ 弓削+ 生名・R1 食 上島レモン 1985 派生・1990 年代以降島ペンション 35+ 年+ レモン農園体験+ サイクリング+ しまなみ海道支援・¥7,500-18,000/泊)",
    title_ja: "上島町ペンション", romaji: "Kamijima Pension",
    summary_zh: "**上島町島ペンション+レモン宿は R1 食 1985 派生・1990 年代以降 35+ 年+レモン農園体験+サイクリング+しまなみ支援**(越智郡上島)。¥7,500-18,000/泊。",
    content_md: "- 立地:**越智郡上島町岩城+ 弓削+ 生名**\n- 関連:**R1 食 上島町レモン 1985 派生**\n- 派生:**1990 年代以降島ペンション 35+ 年 → レモン農園体験+サイクリング+しまなみ海道支援**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "越智郡", municipality_ja: "上島町", lg_code: "38356",
    area_types: ["lodging_pension"],
    lat: 34.2631, lon: 133.2017,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kamijima_pension"], source: "manual",
  },
  {
    slug: "ikata-misaki-pension",
    category: "lodging", sub_type: "ehime_pension",
    title_zh: "伊方町佐田岬ペンション+ 風車宿(西宇和郡伊方町・佐田岬日本一細長い半島 40km+ 風力発電 1996+ R1 衣 佐田岬風車派生・佐田岬ペンション 5+ 軒+ 海洋夕日+ 国立公園・¥8,500-18,000/泊)",
    title_ja: "佐田岬ペンション", romaji: "Sadamisaki Pension",
    summary_zh: "**伊方町佐田岬ペンション+風車宿は半島 40km+1996 風力+R1 衣 風車派生・5+ 軒+海洋夕日+国立公園**(西宇和郡伊方)。¥8,500-18,000/泊。",
    content_md: "- 立地:**西宇和郡伊方町**\n- 起源:**佐田岬日本一細長い半島 40km + 風力発電 1996**\n- 関連:**R1 衣 佐田岬風車派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "西宇和郡", municipality_ja: "伊方町", lg_code: "38442",
    area_types: ["lodging_pension"],
    lat: 33.4894, lon: 132.3559,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["ikata_misaki_pension"], source: "manual",
  },
  {
    slug: "tobe-yaki-yado",
    category: "lodging", sub_type: "ehime_traditional",
    title_zh: "砥部焼陶芸の里旅館+ 砥部温泉(伊予郡砥部町・1777 砥部焼開窯 248+ 年+ R1 衣 砥部焼+ R1 食 砥部焼器懐石派生・陶芸の里旅館 5+ 軒+ 砥部焼料理・¥12,000-32,000/泊)",
    title_ja: "砥部焼旅館", romaji: "Tobe Yaki Ryokan",
    summary_zh: "**砥部焼陶芸の里旅館+砥部温泉は 1777 248+ 年+R1 衣+R1 食 派生・里旅館 5+ 軒+砥部焼料理**(伊予郡砥部)。¥12,000-32,000/泊。",
    content_md: "- 立地:**伊予郡砥部町・砥部焼陶芸の里**\n- 起源:**1777 砥部焼開窯 248+ 年**\n- 関連:**R1 衣 砥部焼 + R1 食 砥部焼器懐石派生**",
    region: "shikoku", prefecture_ja: "愛媛県", gun_ja: "伊予郡", municipality_ja: "砥部町", lg_code: "38402",
    area_types: ["lodging_traditional"],
    lat: 33.7344, lon: 132.7872,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["tobe_yaki_ryokan"], source: "manual",
  },
];

seedMain(rows, "ehime-lodging-r1");
