// Seed 東京都 R3 補完(20 筆 / Sprint 3.x / 第十三卷)
// 食 5 / 衣 3 / 住 3 / 育 4 / 楽 3 / 行 2 = 20 累積 140 + 20 = 160
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 食 5
  {
    slug: "ginza-yoshoku-rengaitei-1895",
    category: "food", sub_type: "tokyo_b_kyu_gurume",
    title_zh: "銀座洋食+ 煉瓦亭 1895(中央区銀座・煉瓦亭 1895 創業 130+ 年+ 「とんかつ」+「ハヤシライス」+「オムライス」発祥店候補・全国洋食発祥地代表+ 銀座資生堂パーラー 1902 + 銀座千疋屋 1894 並ぶ銀座洋食 3 大老舗・¥1,800-4,500)",
    title_ja: "銀座洋食 煉瓦亭", romaji: "Ginza Rengaitei",
    summary_zh: "**銀座洋食+煉瓦亭 1895 は創業 130+ 年・とんかつ+ハヤシ+オムライス発祥候補・銀座洋食 3 大老舗(資生堂パーラー 1902+千疋屋 1894)**(銀座)。¥1,800-4,500、洋食発祥代表。",
    content_md: "- 立地:**中央区銀座**\n- 起源:**煉瓦亭 1895 創業 130+ 年**\n- 認定:**「とんかつ」「ハヤシライス」「オムライス」発祥店候補 + 全国洋食発祥地代表**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "中央区", lg_code: "13102",
    area_types: ["restaurant_traditional"], lat: 35.6717, lon: 139.7656,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["rengaitei_1895", "tonkatsu_origin"], source: "manual",
  },
  {
    slug: "tokyo-kissaten-paulista-1911",
    category: "food", sub_type: "tokyo_kissaten",
    title_zh: "東京老舗喫茶店+ 銀座カフェーパウリスタ 1911(中央区銀座+台東区上野・カフェーパウリスタ 1911 創業 114+ 年(全国最古喫茶店候補)+ 上野古城 1947+ 銀座ルパン 1928+ 神田神保町ラドリオ 1948・¥800-2,500・国際 SNS 海外旅行者代表)",
    title_ja: "東京喫茶店", romaji: "Tokyo Kissaten",
    summary_zh: "**東京老舗喫茶店+カフェーパウリスタ 1911 は 114+ 年(全国最古喫茶店候補)・上野古城 1947+銀座ルパン 1928+ラドリオ 1948**(銀座+上野+神保町)。¥800-2,500、海外代表。",
    content_md: "- 立地:**中央区銀座 + 台東区上野 + 千代田区神田神保町**\n- 起源:**カフェーパウリスタ 1911 創業 114+ 年(全国最古喫茶店候補)**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "中央区", lg_code: "13102",
    area_types: ["restaurant_traditional"], lat: 35.6720, lon: 139.7647,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["paulista_1911", "tokyo_kissaten"], source: "manual",
  },
  {
    slug: "tsukiji-uogashi-kaisendon",
    category: "food", sub_type: "tokyo_market",
    title_zh: "築地+豊洲海鮮丼老舗(中央区築地+江東区豊洲・R1 食 築地豊洲市場 R1 派生・大江戸 1965+築地虎杖 1979+ 寿司清 1893+ 海鮮丼+寿司丼+マグロ漬丼・¥2,500-5,500・市場早朝開店 5 時-午後 2 時+ 国際 SNS 海外旅行者代表)",
    title_ja: "築地海鮮丼", romaji: "Tsukiji Kaisendon",
    summary_zh: "**築地+豊洲海鮮丼老舗は R1 食 R1 派生・大江戸 1965+築地虎杖 1979+寿司清 1893・海鮮丼+寿司丼+マグロ漬丼**(築地+豊洲)。¥2,500-5,500、市場 5h-14h、海外代表。",
    content_md: "- 立地:**中央区築地 + 江東区豊洲**\n- 関連:**R1 食 築地豊洲市場派生**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "中央区", lg_code: "13102",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 35.6647, lon: 139.7706,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: ["sunday"],
    external_urls: {}, tags: ["tsukiji_kaisendon"], source: "manual",
  },
  {
    slug: "kanda-curry-street",
    category: "food", sub_type: "tokyo_b_kyu_gurume",
    title_zh: "神田神保町カレー街(千代田区神田神保町・1900 年代以降カレー文化集積 100+ 年+ 全国最大カレー店密集街 400+ 軒(全国 1 位)+ ボンディ 1973+ ガビアル 1985+ エチオピア 1988+ R3 食 ナイル 1949(R2 派生)・¥800-2,500・神田カレーグランプリ毎年開催)",
    title_ja: "神保町カレー街", romaji: "Jimbocho Curry",
    summary_zh: "**神田神保町カレー街は 1900 年代以降 100+ 年・全国最大カレー密集 400+ 軒(全国 1 位)・ボンディ 1973+ガビアル 1985+エチオピア 1988**(神保町)。¥800-2,500、神田カレーグランプリ毎年。",
    content_md: "- 立地:**千代田区神田神保町**\n- 起源:**1900 年代以降カレー文化集積 100+ 年**\n- 認定:**全国最大カレー店密集街 400+ 軒(全国 1 位)**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "千代田区", lg_code: "13101",
    area_types: ["restaurant_traditional"], lat: 35.6961, lon: 139.7575,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jimbocho_curry"], source: "manual",
  },
  {
    slug: "ekisoba-tokyo",
    category: "food", sub_type: "tokyo_b_kyu_gurume",
    title_zh: "東京駅そば+立ち食いそば文化(全都駅+ JR 駅構内・1900 年代以降駅そば発祥 100+ 年+ 富士そば 1966 創業 59+ 年(店舗 70+ 軒)+ 小諸そば 1972+ 名代そば+ そばいち+ JR 駅構内駅そば・¥350-1,200・国内通勤客代表)",
    title_ja: "東京駅そば", romaji: "Tokyo Eki-soba",
    summary_zh: "**東京駅そば+立ち食いそば文化は 1900 年代以降 100+ 年・富士そば 1966 59+ 年 店舗 70+ 軒+小諸 1972+名代+JR 構内**(全都駅)。¥350-1,200、通勤客代表。",
    content_md: "- 立地:**全都駅 + JR 駅構内**\n- 起源:**1900 年代以降駅そば発祥 100+ 年**\n- 規模:**富士そば 1966 創業 59+ 年 店舗 70+ 軒**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "千代田区", lg_code: "13101",
    area_types: ["restaurant_traditional"], lat: 35.6812, lon: 139.7671,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["ekisoba", "fuji_soba_1966"], source: "manual",
  },

  // 衣 3
  {
    slug: "jimbocho-old-books",
    category: "fashion", sub_type: "tokyo_old_books",
    title_zh: "神田神保町古書店街(千代田区神田神保町・1880 年代以降古書街発祥 145+ 年+ 全国最大古書店街 130+ 軒(全国 1 位)+ 三省堂 1881+ 岩波書店 1913+ 一誠堂書店 1903+ 老舗書店+ 神田古本まつり 10 月+ 国際 SNS 海外文学愛好者代表)",
    title_ja: "神保町古書店街", romaji: "Jimbocho Old Books",
    summary_zh: "**神田神保町古書店街は 1880 年代以降 145+ 年・全国最大古書街 130+ 軒(全国 1 位)・三省堂 1881+岩波 1913+一誠堂 1903・神田古本まつり 10 月**(神保町)。海外代表。",
    content_md: "- 立地:**千代田区神田神保町**\n- 起源:**1880 年代以降古書街発祥 145+ 年**\n- 認定:**全国最大古書店街 130+ 軒(全国 1 位)**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "千代田区", lg_code: "13101",
    area_types: ["shopping_district"], lat: 35.6961, lon: 139.7575,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["jimbocho_old_books", "1880s"], source: "manual",
  },
  {
    slug: "omotesando-issey-yamamoto",
    category: "fashion", sub_type: "tokyo_designer_fashion",
    title_zh: "表参道+青山 国際ファッションデザイナー街(港区南青山+ 渋谷区神宮前・三宅一生 1970+ 山本耀司 1972+ 川久保玲 COMME des GARÇONS 1969 全国 3 大日本人デザイナー旗艦店+ 表参道ヒルズ 2006+ 安藤忠雄設計建築・¥45,000-450,000・国際 SNS 海外ファッション業界代表)",
    title_ja: "表参道デザイナー", romaji: "Omotesandō Designer",
    summary_zh: "**表参道+青山国際ファッションデザイナー街は三宅 1970+山本 1972+川久保 1969 全国 3 大日本人デザイナー・表参道ヒルズ 2006**(港南青山+渋谷神宮前)。¥45,000-450,000。",
    content_md: "- 立地:**港区南青山 + 渋谷区神宮前**\n- 起源:**三宅一生 1970 + 山本耀司 1972 + 川久保玲 1969**\n- 認定:**全国 3 大日本人デザイナー旗艦店 + 表参道ヒルズ 2006 安藤忠雄設計**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "港区", lg_code: "13103",
    area_types: ["shopping_district"], lat: 35.6650, lon: 139.7144,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["omotesando_designer", "issey_1970", "yamamoto_1972"], source: "manual",
  },
  {
    slug: "asakusa-nakamise",
    category: "fashion", sub_type: "tokyo_temple_shrine",
    title_zh: "浅草仲見世商店街(台東区浅草・1685 起源 340+ 年+ 全国最古仲見世+ 浅草寺雷門-本堂 250m 商店街 89+ 軒+ 観光土産+人形焼+雷おこし+ 着物・浴衣+人気観光客代表+ 1 日 5 万人来街・無料散策・国際 SNS 海外旅行者代表)",
    title_ja: "浅草仲見世", romaji: "Asakusa Nakamise",
    summary_zh: "**浅草仲見世商店街は 1685 起源 340+ 年・全国最古仲見世・雷門-本堂 250m 商店街 89+ 軒・1 日 5 万人来街**(浅草)。海外旅行者代表、無料。",
    content_md: "- 立地:**台東区浅草**\n- 起源:**1685 起源 340+ 年**\n- 認定:**全国最古仲見世 + 雷門-本堂 250m 商店街 89+ 軒**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "台東区", lg_code: "13106",
    area_types: ["shopping_district", "history_site_castle"], lat: 35.7128, lon: 139.7964,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["asakusa_nakamise_1685"], source: "manual",
  },

  // 住 3
  {
    slug: "shibuya-stream-2018",
    category: "lodging", sub_type: "tokyo_fukutoshin_hotel",
    title_zh: "渋谷ストリームエクセルホテル東急(渋谷区渋谷・2018 開業 7+ 年+ 渋谷ストリーム高層複合ビル併設+ 東急グループ・JR 渋谷駅徒歩 1 分+ R1 楽 渋谷スクランブル隣接・¥18,000-45,000/泊・国内ビジネス+海外旅行者代表)",
    title_ja: "渋谷ストリーム", romaji: "Shibuya Stream",
    summary_zh: "**渋谷ストリームエクセルホテル東急は 2018 開業 7+ 年・渋谷ストリーム高層併設+東急グループ・JR 渋谷徒歩 1 分**(渋谷)。R1 楽 スクランブル隣接、¥18,000-45,000/泊。",
    content_md: "- 立地:**渋谷区渋谷**\n- 起源:**2018 開業 7+ 年**\n- 認定:**渋谷ストリーム高層複合ビル併設 + 東急グループ**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "渋谷区", lg_code: "13113",
    area_types: ["accommodation_hotel"], lat: 35.6584, lon: 139.7011,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["shibuya_stream_2018"], source: "manual",
  },
  {
    slug: "tachikawa-hachioji-hotels",
    category: "lodging", sub_type: "tokyo_tama_lodging",
    title_zh: "立川+八王子+府中ホテル群(立川市+八王子市+府中市・JR 立川駅+八王子駅+ 京王八王子駅+ 多摩都市モノレール+ 中堅+ビジネスホテル 30+ 軒(京王プラザホテル多摩+ホテルメッツ立川+京王プラザ八王子)・¥6,500-15,000/泊・R1 育 高尾山 連動)",
    title_ja: "立川八王子ホテル", romaji: "Tachikawa Hachioji Hotel",
    summary_zh: "**立川+八王子+府中ホテル群は JR+京王+多摩都市モノレール・中堅+ビジネス 30+ 軒(京王プラザ多摩+メッツ立川+京王プラザ八王子)**(多摩 3 市)。R1 育 高尾山連動、¥6,500-15,000/泊。",
    content_md: "- 立地:**立川市 + 八王子市 + 府中市**\n- 規模:**中堅 + ビジネスホテル 30+ 軒**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "立川市", lg_code: "13202",
    area_types: ["accommodation_hotel"], lat: 35.6964, lon: 139.4136,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["tama_business_hotels"], source: "manual",
  },
  {
    slug: "nishi-shinjuku-business",
    category: "lodging", sub_type: "tokyo_fukutoshin_hotel",
    title_zh: "西新宿超高層ビジネスホテル群(新宿区西新宿・1971 京王プラザホテル開業 54+ 年(全国超高層ホテル先駆け)+ 京王プラザ+ヒルトン+ハイアットリージェンシー+ パークハイアット+ 西新宿摩天楼 ホテル 12+ 軒・¥18,000-45,000/泊)",
    title_ja: "西新宿摩天楼", romaji: "Nishi-Shinjuku Skyscraper",
    summary_zh: "**西新宿超高層ビジネスホテル群は 1971 京王プラザ開業 54+ 年(全国超高層ホテル先駆け)・西新宿摩天楼 ホテル 12+ 軒**(新宿西)。¥18,000-45,000/泊。",
    content_md: "- 立地:**新宿区西新宿**\n- 起源:**1971 京王プラザホテル開業 54+ 年(全国超高層ホテル先駆け)**\n- 規模:**ホテル 12+ 軒**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "新宿区", lg_code: "13104",
    area_types: ["accommodation_hotel"], lat: 35.6892, lon: 139.6928,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["nishi_shinjuku", "1971"], source: "manual",
  },

  // 育 4
  {
    slug: "tocho-1991",
    category: "culture", sub_type: "tokyo_castle",
    title_zh: "東京都庁舎+ 展望台(新宿区西新宿・1991 開業 34+ 年+ 丹下健三設計第一本庁舎 243m(当時東京最高層)+ 第二本庁舎 163m+ 都議会棟・展望室 45 階 202m 無料+ 富士山+横浜+スカイツリー望遠+ 国際 SNS 海外旅行者代表)",
    title_ja: "東京都庁", romaji: "Tochō",
    summary_zh: "**東京都庁舎+展望台は 1991 開業 34+ 年・丹下健三設計第一本庁舎 243m(当時東京最高層)・展望室 45 階 202m 無料・富士山+横浜+スカイツリー望遠**(新宿西)。海外代表。",
    content_md: "- 立地:**新宿区西新宿**\n- 起源:**1991 開業 34+ 年**\n- 認定:**丹下健三設計第一本庁舎 243m(当時東京最高層) + 展望室 45 階 202m 無料**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "新宿区", lg_code: "13104",
    area_types: ["history_site_castle", "theme_park"], lat: 35.6896, lon: 139.6917,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tocho_1991"], source: "manual",
  },
  {
    slug: "kokuritsu-kyogijo-2019",
    category: "culture", sub_type: "tokyo_castle",
    title_zh: "国立競技場+ 旧国立競技場跡(新宿区霞ヶ丘+渋谷区・1958 旧国立競技場竣工 67+ 年+ 1964+2020 東京五輪主要会場+ 2019 新国立競技場開業(隈研吾設計)・6 万 8000 人収容+ ラグビー W 杯 2019+ パラリンピック・国際 SNS 海外スポーツ代表)",
    title_ja: "国立競技場", romaji: "Kokuritsu Kyogijō",
    summary_zh: "**国立競技場は 1958 旧国立 67+ 年+1964+2020 東京五輪・2019 新国立(隈研吾設計)・6 万 8000 人収容・ラグビー W 杯 2019+パラ五輪**(新宿霞ヶ丘+渋谷)。海外代表。",
    content_md: "- 立地:**新宿区霞ヶ丘 + 渋谷区**\n- 起源:**1958 旧国立競技場竣工 67+ 年 + 2019 新国立競技場開業(隈研吾設計)**\n- 認定:**1964 + 2020 東京五輪主要会場 + ラグビー W 杯 2019 + パラリンピック**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "新宿区", lg_code: "13104",
    area_types: ["theme_park", "history_site_castle"], lat: 35.6781, lon: 139.7144,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["kokuritsu_kyogijo", "1958", "2019_kuma"], source: "manual",
  },
  {
    slug: "tokyo-international-forum-1996",
    category: "culture", sub_type: "tokyo_castle",
    title_zh: "東京国際フォーラム(千代田区丸の内・1996 開業 29+ 年+ ラファエル・ヴィニオリ設計+ ガラスホール 11,500 m² 国際的建築賞多数受賞・大ホール A 5012 席+ 中ホール 1502 席+ JR 有楽町駅徒歩 1 分・¥1,500-12,000・国際 SNS 海外建築ファン代表)",
    title_ja: "東京国際フォーラム", romaji: "International Forum",
    summary_zh: "**東京国際フォーラムは 1996 開業 29+ 年・ラファエル・ヴィニオリ設計・ガラスホール 11,500 m²・大ホール A 5012 席+中ホール 1502 席**(千代田丸の内)。¥1,500-12,000、海外建築代表。",
    content_md: "- 立地:**千代田区丸の内**\n- 起源:**1996 開業 29+ 年**\n- 認定:**ラファエル・ヴィニオリ設計 + ガラスホール 11,500 m² 国際的建築賞**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "千代田区", lg_code: "13101",
    area_types: ["history_site_castle"], lat: 35.6764, lon: 139.7639,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["international_forum_1996", "vinoly"], source: "manual",
  },
  {
    slug: "asakusa-jinja-sanja-matsuri",
    category: "culture", sub_type: "tokyo_temple_shrine",
    title_zh: "浅草神社+ 三社祭(台東区浅草・1649 慶安 2 年浅草神社創建 376+ 年(浅草寺ご開帳の檜前浜成・竹成兄弟祀る)+ 三社祭 5 月第 3 土日(国指定無形民俗候補)・江戸三大祭+ 100+ 神輿+ 200 万人観衆・参拝無料)",
    title_ja: "浅草神社+三社祭", romaji: "Asakusa Jinja",
    summary_zh: "**浅草神社+三社祭は 1649 慶安 2 年創建 376+ 年・三社祭 5 月第 3 土日(国指定民俗候補)・江戸三大祭・100+ 神輿+200 万人**(台東浅草)。参拝無料。",
    content_md: "- 立地:**台東区浅草**\n- 起源:**1649 慶安 2 年浅草神社創建 376+ 年**\n- 認定:**江戸三大祭 + 100+ 神輿 + 200 万人観衆**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "台東区", lg_code: "13106",
    area_types: ["history_site_castle"], lat: 35.7150, lon: 139.7972,
    season_start: null, season_end: null, event_start: "2026-05-15T09:00:00+09:00", event_end: "2026-05-17T20:00:00+09:00",
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["asakusa_jinja", "sanja_matsuri", "1649"], source: "manual",
  },

  // 楽 3
  {
    slug: "shinjuku-gyoen-vs-meguro-cherry",
    category: "entertainment", sub_type: "tokyo_park",
    title_zh: "目黒川桜並木(目黒区中目黒+品川+ 大田・1927 整備開始 98+ 年+ 800 本ソメイヨシノ 4km+ 中目黒桜まつり 4 月第 1 週末・東京 5 大桜名所候補・無料散策・東急東横線中目黒駅徒歩 5 分・国際 SNS 海外旅行者代表)",
    title_ja: "目黒川桜", romaji: "Meguro River Cherry",
    summary_zh: "**目黒川桜並木は 1927 整備 98+ 年・800 本ソメイヨシノ 4km・中目黒桜まつり 4 月第 1 週末・東京 5 大桜名所候補**(目黒中目黒+品川+大田)。中目黒徒歩 5 分、無料、海外代表。",
    content_md: "- 立地:**目黒区中目黒 + 品川区 + 大田区**\n- 起源:**1927 整備開始 98+ 年**\n- 規模:**800 本ソメイヨシノ 4km**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "目黒区", lg_code: "13110",
    area_types: ["nature_park", "shopping_district"], lat: 35.6433, lon: 139.6981,
    season_start: "2026-03-25", season_end: "2026-04-10", event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["meguro_river_cherry", "1927"], source: "manual",
  },
  {
    slug: "tokyo-firework-festivals",
    category: "entertainment", sub_type: "tokyo_seasonal",
    title_zh: "東京花火大会(7-8 月・隅田川花火大会 1733 8 代将軍吉宗代起源 292+ 年(全国最古花火大会候補)+ 江戸川区花火大会+足立区花火大会+ 東京湾花火大会・1 万発+ 100 万人観衆・無料観覧)",
    title_ja: "東京花火大会", romaji: "Tokyo Hanabi",
    summary_zh: "**東京花火大会は隅田川花火 1733 8 代将軍吉宗代起源 292+ 年(全国最古花火大会候補)・江戸川+足立+東京湾・1 万発+100 万人**(全都)。7-8 月、無料観覧。",
    content_md: "- 立地:**墨田区 + 江東区 + 足立区 + 江戸川区 + 港区**\n- 起源:**隅田川花火大会 1733 8 代将軍吉宗代起源 292+ 年**\n- 認定:**全国最古花火大会候補**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "墨田区", lg_code: "13107",
    area_types: ["theme_park", "history_site_castle"], lat: 35.7106, lon: 139.8108,
    season_start: null, season_end: null, event_start: "2026-07-25T19:00:00+09:00", event_end: "2026-07-25T20:30:00+09:00",
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["sumida_hanabi_1733", "292_years"], source: "manual",
  },
  {
    slug: "takadanobaba-waseda-student",
    category: "entertainment", sub_type: "tokyo_park",
    title_zh: "高田馬場+早稲田学生街(新宿区高田馬場+西早稲田・R1 育 早稲田大学派生・1882 早稲田大学創立以来 143+ 年+ 学生街文化+ ラーメン+居酒屋+古本屋+大学グッズ・1 食 ¥600-2,500・国内若者文化代表)",
    title_ja: "高田馬場早稲田学生街", romaji: "Takadanobaba",
    summary_zh: "**高田馬場+早稲田学生街は R1 育 早稲田大学派生・1882 創立 143+ 年・学生街文化+ラーメン+居酒屋+古本屋+大学グッズ**(新宿高田馬場+西早稲田)。¥600-2,500、若者代表。",
    content_md: "- 立地:**新宿区高田馬場 + 西早稲田**\n- 関連:**R1 育 早稲田大学 1882 派生**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "新宿区", lg_code: "13104",
    area_types: ["shopping_district"], lat: 35.7128, lon: 139.7036,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["takadanobaba"], source: "manual",
  },

  // 行 2
  {
    slug: "keikyu-line-1898",
    category: "transport", sub_type: "tokyo_private_railway",
    title_zh: "京浜急行電鉄(京急本線・1898 創業 127+ 年+ 全国私鉄最古候補+ 品川-横浜-横須賀-三崎口 56km+ 京急蒲田-羽田空港 国内空港アクセス+ 1 日 130 万人乗降+ R1 行 羽田空港アクセス主軸・¥150-1,250/片道)",
    title_ja: "京浜急行電鉄", romaji: "Keikyū",
    summary_zh: "**京浜急行電鉄は 1898 創業 127+ 年・全国私鉄最古候補・品川-横浜-横須賀-三崎口 56km・京急蒲田-羽田空港・1 日 130 万人**(品川+大田+神奈川)。¥150-1,250/片道。",
    content_md: "- 立地:**品川区 + 大田区 + 神奈川**\n- 起源:**1898 創業 127+ 年**\n- 認定:**全国私鉄最古候補 + 京急蒲田-羽田空港 国内空港アクセス**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "品川区", lg_code: "13109",
    area_types: ["transport_hub"], lat: 35.6286, lon: 139.7397,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["keikyū_1898", "127_years", "national_oldest_private"], source: "manual",
  },
  {
    slug: "tokyu-toyoko-line-1932",
    category: "transport", sub_type: "tokyo_private_railway",
    title_zh: "東急東横線+ 田園都市線(渋谷区+目黒+大田+ 神奈川・1932 東急東横線開業 93+ 年+ 1966 田園都市線・渋谷-横浜 24.2km+渋谷-中央林間 31.5km・関東通勤+観光主軸・1 日 200 万人乗降・¥130-580/片道)",
    title_ja: "東急東横線", romaji: "Tokyu Toyoko",
    summary_zh: "**東急東横線+田園都市線は 1932 東横開業 93+ 年+1966 田園都市・渋谷-横浜 24.2km+渋谷-中央林間 31.5km・関東通勤+観光主軸・1 日 200 万人**(渋谷+目黒+大田)。¥130-580/片道。",
    content_md: "- 立地:**渋谷区 + 目黒区 + 大田区 + 神奈川**\n- 起源:**1932 東急東横線開業 93+ 年 + 1966 田園都市線**\n- 規模:**東横 24.2km + 田園都市 31.5km + 1 日 200 万人乗降**",
    region: "kanto", prefecture_ja: "東京都", gun_ja: null, municipality_ja: "渋谷区", lg_code: "13113",
    area_types: ["transport_hub"], lat: 35.6595, lon: 139.7004,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["tokyu_toyoko_1932"], source: "manual",
  },
];

seedMain(rows, "tokyo-r3");
