// Seed 宮城県 R3 補完(20 筆 / Sprint 3.x)
// 食 5 / 住 4 / 衣 3 / 育 3 / 楽 3 / 行 2 = 20

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "tohoku"; prefecture_ja: "宮城県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  // 食 (5)
  { slug: "sendai-asaichi", category: "food", sub_type: "miyagi_kyodo", title_zh: "仙台朝市(仙台市青葉区中央・1945 戦後闇市起源 80 年+ JR 仙台駅西口徒歩 5 分+ 鮮魚+青果+総菜 70+ 軒+ R1 食 三陸海産・松島牡蠣 直売+ 朝食定食 ¥800-1,500+ 観光客向け仙台朝食代表)", title_ja: "仙台朝市", romaji: "Sendai Asaichi", summary_zh: "**仙台朝市は戦後闇市起源 80 年**(青葉区中央・**JR 仙台駅徒歩 5 分**)。鮮魚+青果+総菜 70+ 軒、R1 食 三陸海産直売、朝食定食 ¥800-1,500。", content_md: "- 立地:**仙台市青葉区中央**(JR 仙台駅徒歩 5 分)\n- 起源:**1945 戦後闇市起源 80 年**\n- 規模:**70+ 軒**(鮮魚 + 青果 + 総菜)\n- 並列:**R1 食 三陸海産 + 松島牡蠣 + 浦霞酒造 直売**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["restaurant_traditional", "shopping_district"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["日"], external_urls: {}, tags: ["sendai_asaichi", "1945_post_war", "70_stores"], source: "manual" },
  { slug: "sendai-aburafu-don", category: "food", sub_type: "miyagi_kyodo", title_zh: "あぶら麩丼(R1 食 仙台麩派生・登米市+大崎市内 食堂+ 卵とじ + 仙台麩 + 醤油つゆ 丼物代表+ 戦後発祥 80 年+ 1 杯 ¥800-1,200+ 仙台観光客向け B 級代表)", title_ja: "あぶら麩丼", romaji: "Aburafu Don", summary_zh: "**あぶら麩丼は R1 食 仙台麩派生・卵とじ丼**(登米+大崎・**戦後発祥 80 年**)。¥800-1,200、B 級代表。", content_md: "- 立地:**登米市 + 大崎市**\n- 関係:**R1 食 仙台麩(車麩)派生**\n- 構成:**仙台麩 + 卵とじ + 醤油つゆ**\n- 起源:**戦後発祥 80 年**\n- 価格:**1 杯 ¥800-1,200**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "登米市", lg_code: "04210", area_types: ["restaurant_traditional"], lat: 38.6964, lon: 141.2719, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["aburafu_don", "fu_egg_donburi", "post_war"], source: "manual" },
  { slug: "tomi-toyo-no-yu-tofu", category: "food", sub_type: "miyagi_kyodo", title_zh: "登米油揚げ・とよのゆ(登米市・江戸期 仙台藩献上+ 全国最大級厚揚げ 直径 20cm+ 醤油+生姜つけ+ 道の駅+全国百貨店流通+ 1 枚 ¥250-400+ R1 食 三角油揚げ(仙台定義山)系・東北 2 大油揚げ)", title_ja: "登米油揚げ・とよのゆ", romaji: "Tomi Aburaage Toyo-no-yu", summary_zh: "**登米油揚げは江戸期 仙台藩献上**(登米市・**全国最大級厚揚げ 20cm**)。R1 食 仙台三角油揚げ系・東北 2 大油揚げ、¥250-400/枚、道の駅+全国百貨店。", content_md: "- 立地:**登米市**\n- 起源:**江戸期 仙台藩献上**\n- 規模:**全国最大級厚揚げ 直径 20cm**\n- 並列:**R1 食 仙台三角油揚げ + R3 食 登米油揚げ = 東北 2 大油揚げ**\n- 価格:**1 枚 ¥250-400**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "登米市", lg_code: "04210", area_types: ["industrial_heritage", "restaurant_traditional"], lat: 38.6964, lon: 141.2719, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tomi_aburaage", "edo_origin", "20cm"], source: "manual" },
  { slug: "matsushima-anago", category: "food", sub_type: "miyagi_seafood", title_zh: "松島あなご(松島町+塩竈・松島湾産アナゴ+ 江戸期 仙台藩献上+ R1 食 松島牡蠣と並ぶ松島代表魚介+ 蒸しあなご丼+寿司+焼アナゴ+ ¥1,800-3,500+ R1 育 松島観光客向け)", title_ja: "松島あなご", romaji: "Matsushima Anago", summary_zh: "**松島あなごは松島湾産アナゴ・江戸期仙台藩献上**(松島町・**R1 食 牡蠣と並ぶ松島代表魚介**)。蒸あなご丼+寿司+焼、¥1,800-3,500。", content_md: "- 立地:**宮城郡松島町 + 塩竈市**\n- 起源:**江戸期 仙台藩献上**\n- 用途:**蒸あなご丼 + 寿司 + 焼アナゴ**\n- 並列:**R1 食 松島牡蠣 + R3 食 松島あなご = 松島魚介 2 大**\n- 価格:**¥1,800-3,500**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "宮城郡", municipality_ja: "松島町", lg_code: "04401", area_types: ["restaurant_traditional", "scenic_spot"], lat: 38.3742, lon: 141.0589, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["matsushima_anago", "edo_offering"], source: "manual" },
  { slug: "kesennuma-shark", category: "food", sub_type: "miyagi_seafood", title_zh: "気仙沼サメ(気仙沼市・全国サメ水揚げ量 No.1 港+ R1 食 気仙沼ふかひれ素材源+ サメ肉ステーキ+ サメみそ煮+ サメすり身ハンバーグ+ 道の駅 + 仙台駅売店+ ¥800-2,500)", title_ja: "気仙沼サメ", romaji: "Kesennuma Same", summary_zh: "**気仙沼サメは全国サメ水揚げ量 No.1 港**(気仙沼市・**R1 食 ふかひれ素材源**)。サメ肉+みそ煮+ハンバーグ、道の駅+仙台駅売店、¥800-2,500。", content_md: "- 立地:**気仙沼市**\n- 認定:**全国サメ水揚げ量 No.1 港**\n- 関係:**R1 食 気仙沼ふかひれ素材源**\n- 用途:**サメ肉ステーキ + みそ煮 + すり身ハンバーグ**\n- 価格:**¥800-2,500**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "気仙沼市", lg_code: "04203", area_types: ["restaurant_traditional", "industrial_heritage"], lat: 38.9069, lon: 141.5703, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kesennuma_same", "no1_shark"], source: "manual" },

  // 住 (4)
  { slug: "sendai-jr-east-hotel", category: "lodging", sub_type: "miyagi_sendai_chuou", title_zh: "ホテル JR 東日本 メッツ仙台(仙台市青葉区・JR 仙台駅西口直結+ 1990 メトロポリタン姉妹+ 全 137 室+ 1 泊朝食付 ¥9,500-13,500+ JR 利用客向け+ R1 衣 S-PAL アクセス便)", title_ja: "ホテル JR 東日本 メッツ仙台", romaji: "JR East Mets Sendai", summary_zh: "**ホテル JR 東日本 メッツ仙台は仙台駅西口直結**(青葉区・**1990・全 137 室**)。R1 住 メトロポリタン姉妹、¥9,500-13,500、JR 利用客向け。", content_md: "- 立地:**仙台市青葉区**(JR 仙台駅西口直結)\n- 起源:**1990 開業 35 年**\n- 規模:**全 137 室**\n- 系列:**JR 東日本ホテルメッツ**\n- 並列:**R1 住 メトロポリタン仙台 姉妹**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["shopping_district", "transit_hub"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["jr_east_mets_sendai", "1990", "137_rooms"], source: "manual" },
  { slug: "naruko-kankou-hotel", category: "lodging", sub_type: "miyagi_naruko_onsen", title_zh: "鳴子観光ホテル(大崎市・1970 開業+ 全 72 室+ 鳴子温泉郷代表大型旅館+ R1 住 鳴子温泉郷+R1 楽 鳴子峡+R1 衣 鳴子こけし館 拠点+ 1 泊 2 食 ¥15,500-23,000+ 観光客向け代表)", title_ja: "鳴子観光ホテル", romaji: "Naruko Kankō Hotel", summary_zh: "**鳴子観光ホテルは鳴子代表大型旅館**(1970 開業+全 72 室)。R1 住+R1 楽 鳴子峡+R1 衣 こけし館 拠点、¥15,500-23,000。", content_md: "- 立地:**大崎市鳴子温泉(R1 住 鳴子温泉郷)**\n- 起源:**1970 開業 55 年**\n- 規模:**全 72 室**\n- 並列観光:**R1 楽 鳴子峡 + R1 衣 鳴子こけし館 + R2 住 鬼首温泉**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "大崎市", lg_code: "04213", area_types: ["onsen_field"], lat: 38.7375, lon: 140.7250, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["naruko_kankou", "1970", "72_rooms"], source: "manual" },
  { slug: "ishinomaki-grand-hotel", category: "lodging", sub_type: "miyagi_other_onsen", title_zh: "石巻グランドホテル(石巻市・1980 開業+ 全 105 室+ 2011 震災復興拠点+ R1 食 石巻焼きそば+R1 育 石ノ森萬画館+R1 楽 田代島 観光客向け+ 1 泊朝食付 ¥9,500-13,500+ 石巻代表ビジネスホテル)", title_ja: "石巻グランドホテル", romaji: "Ishinomaki Grand Hotel", summary_zh: "**石巻グランドホテルは石巻代表 1980 開業**(全 105 室+2011 震災復興拠点)。R1 食 石巻焼そば+R1 育 萬画館+田代島観光、¥9,500-13,500。", content_md: "- 立地:**石巻市**\n- 起源:**1980 開業 + 2011 震災復興**\n- 規模:**全 105 室**\n- 並列観光:**R1 育 石ノ森萬画館 + R1 楽 田代島 + R2 食 石巻焼そば**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "石巻市", lg_code: "04201", area_types: ["shopping_district"], lat: 38.4344, lon: 141.3033, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["ishinomaki_grand", "1980", "105_rooms"], source: "manual" },
  { slug: "sendai-airport-richmond", category: "lodging", sub_type: "miyagi_sendai_chuou", title_zh: "リッチモンドホテル仙台空港(名取市仙台空港+ 2018 開業+ 全 178 室+ R1 行 仙台空港 1956 直結 タクシー 5 分+ 1 泊朝食付 ¥8,500-12,500+ 早朝便+夜遅着便利用客向け)", title_ja: "リッチモンドホテル仙台空港", romaji: "Richmond Sendai Airport", summary_zh: "**リッチモンドホテル仙台空港は仙台空港直結**(名取市・**2018 開業+全 178 室**)。R1 行 空港タクシー 5 分、¥8,500-12,500、早朝・夜便客向け。", content_md: "- 立地:**名取市仙台空港**\n- 起源:**2018 開業**\n- 規模:**全 178 室**\n- 並列:**R1 行 仙台空港直結タクシー 5 分**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "名取市", lg_code: "04206", area_types: ["transit_hub", "shopping_district"], lat: 38.1394, lon: 140.9183, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["richmond_airport", "2018", "178_rooms"], source: "manual" },

  // 衣 (3)
  { slug: "sendai-loft-2010", category: "fashion", sub_type: "miyagi_dept_store", title_zh: "仙台ロフト(仙台市青葉区・2010 開業+ JR 仙台駅徒歩 8 分+ 全 8 階生活雑貨専門店+ 文具+コスメ+雑貨+書籍+ R1 衣 PARCO + 三越 + 藤崎 と並ぶ仙台ファッション +商業 5 大 拠点)", title_ja: "仙台ロフト", romaji: "Sendai Loft", summary_zh: "**仙台ロフトは生活雑貨専門 8 階**(青葉区・**2010 開業**)。R1 衣 PARCO+三越+藤崎+R3 ロフト = 仙台商業 5 大、JR 仙台駅徒歩 8 分。", content_md: "- 立地:**仙台市青葉区**(JR 仙台駅徒歩 8 分)\n- 起源:**2010 開業**\n- 規模:**全 8 階・生活雑貨専門**\n- 並列:**R1 衣 藤崎 + 三越 + R2 衣 PARCO + R3 衣 ロフト + ekie = 仙台商業 5 大**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["shopping_district"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["sendai_loft", "2010", "8_floors"], source: "manual" },
  { slug: "sendai-utsunomiya-arts", category: "fashion", sub_type: "miyagi_folk_craft", title_zh: "仙台堤焼(仙台市青葉区・1690 伊達綱村期創始+ 古窯陶器・茶器+花器+ 県伝統工芸品+ 老舗工房 3+ 軒+ 仙台駅売店 + 工芸店流通+ ¥3,500-25,000+ R1 衣 玉虫塗 と並ぶ仙台陶芸代表)", title_ja: "仙台堤焼", romaji: "Sendai Tsutsumiyaki", summary_zh: "**仙台堤焼は 1690 伊達綱村期創始古窯陶器**(仙台市・**県伝統工芸品**)。茶器+花器、老舗 3+ 軒、¥3,500-25,000、R1 衣 玉虫塗 と並ぶ仙台陶芸代表。", content_md: "- 立地:**仙台市青葉区**\n- 起源:**1690 伊達綱村期創始**\n- 認定:**県伝統工芸品**\n- 用途:**茶器 + 花器**\n- 並列:**R1 衣 玉虫塗 + R3 衣 堤焼 = 仙台陶漆 2 大**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["craft_workshop"], lat: 38.2625, lon: 140.8814, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["sendai_tsutsumiyaki", "1690_date_tsunamura"], source: "manual" },
  { slug: "tagajou-mannyou-shu-bunko", category: "fashion", sub_type: "miyagi_folk_craft", title_zh: "多賀城万葉グッズ+古代文房具(多賀城市・R1 育 多賀城跡 724 派生・万葉集大伴家持関連+ 木簡+復元筆+古代和紙便箋+ 多賀城碑関連工芸品+ 多賀城跡 物販+ ¥800-5,500+ 観光土産)", title_ja: "多賀城万葉グッズ", romaji: "Tagajō Manyō Goods", summary_zh: "**多賀城万葉グッズは R1 育 多賀城跡 724 派生**(多賀城市・**万葉集大伴家持関連**)。木簡+復元筆+古代和紙、跡地物販、¥800-5,500。", content_md: "- 立地:**多賀城市**(R1 育 多賀城跡)\n- 関係:**R1 育 多賀城跡 724 派生 + 万葉集大伴家持関連**\n- 構成:**木簡 + 復元筆 + 古代和紙便箋 + 多賀城碑関連**\n- 価格:**¥800-5,500**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "多賀城市", lg_code: "04208", area_types: ["craft_workshop", "shopping_district"], lat: 38.2956, lon: 140.9986, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tagajo_manyou", "724", "ancient_calligraphy"], source: "manual" },

  // 育 (3)
  { slug: "sendai-tenmondai-2008", category: "culture", sub_type: "miyagi_modern_art", title_zh: "仙台市天文台(仙台市青葉区・2008 移転リニューアル+ 直径 1.3m 反射望遠鏡(東北最大級)+ プラネタリウム ¥600+ 「ひとみ」展示+ 入館 ¥610(プラネ別)+ R1 育 メディアテーク と並ぶ仙台科学施設)", title_ja: "仙台市天文台", romaji: "Sendai-shi Tenmondai", summary_zh: "**仙台市天文台は 2008 移転リニューアル**(青葉区・**直径 1.3m 反射望遠鏡 東北最大級+プラネタリウム**)。¥610、R1 育 メディアテーク と並ぶ仙台科学施設。", content_md: "- 立地:**仙台市青葉区錦ヶ丘**\n- 起源:**2008 移転リニューアル**\n- 規模:**直径 1.3m 反射望遠鏡 東北最大級**\n- 看板:**プラネタリウム ¥600**\n- 入館:**¥610**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["museum_art"], lat: 38.2667, lon: 140.7833, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["水"], external_urls: {}, tags: ["sendai_tenmondai", "2008", "1_3m_telescope"], source: "manual" },
  { slug: "rokugo-nuki-toikan", category: "culture", sub_type: "miyagi_history_museum", title_zh: "東北歴史博物館(多賀城市・1999 開館+ 東北 6 県歴史総合博物館・宮城代表+ R1 育 多賀城跡 1300 年祭関連展示+ 縄文+ 古代国府+伊達 + 戦後 通史+ 入館 ¥460+ JR 国府多賀城駅 直結)", title_ja: "東北歴史博物館", romaji: "Tōhoku Rekishi Hakubutsukan", summary_zh: "**東北歴史博物館は東北 6 県歴史総合博物館**(多賀城市・**1999 開館**)。R1 育 多賀城跡 1300 年祭関連、縄文-戦後通史、¥460、JR 国府多賀城駅直結。", content_md: "- 立地:**多賀城市**(JR 東北本線 国府多賀城駅直結)\n- 起源:**1999 開館 26 年**\n- 認定:**東北 6 県歴史総合博物館・宮城代表**\n- 内容:**縄文 + 古代国府 + 伊達 + 戦後通史**\n- 入館:**¥460**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "多賀城市", lg_code: "04208", area_types: ["museum_art", "history_site_castle"], lat: 38.2956, lon: 140.9986, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["月"], external_urls: {}, tags: ["tohoku_rekishi", "1999", "tohoku_6_pref"], source: "manual" },
  { slug: "tomi-yokoyama-folk-village", category: "culture", sub_type: "miyagi_history_museum", title_zh: "とよま明治村(登米市・「明治村」名称+ 武家屋敷+水沢県庁舎 1872+教育資料館 1888+登米警察署 1889+ 国登録有形文化財 群+ 入館 ¥800+ 江戸-明治期建築群保存)", title_ja: "とよま明治村", romaji: "Toyoma Meiji Mura", summary_zh: "**とよま明治村は登米市江戸-明治期建築群保存**(国登録有形文化財群・**水沢県庁舎 1872+教育資料館 1888**)。入館 ¥800、武家屋敷+登米警察署。", content_md: "- 立地:**登米市登米町**\n- 構成:**水沢県庁舎 1872 + 教育資料館 1888 + 登米警察署 1889 + 武家屋敷**\n- 認定:**国登録有形文化財 群**\n- 入館:**¥800**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "登米市", lg_code: "04210", area_types: ["history_site_castle", "museum_art"], lat: 38.6964, lon: 141.2719, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["toyoma_meiji_mura", "1872", "1888", "1889"], source: "manual" },

  // 楽 (3)
  { slug: "ishinomaki-hiyoriyama", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "石巻日和山公園(石巻市・標高 60m+ R1 育 石巻 3.11 関連 震災後復興象徴+ 桜名所 4 月+ 石巻港+太平洋眺望+ R1 食 石巻焼そば + R1 育 萬画館 観光必訪+ 入場無料)", title_ja: "石巻日和山公園", romaji: "Ishinomaki Hiyoriyama", summary_zh: "**石巻日和山公園は震災後復興象徴**(石巻市・**標高 60m+桜名所**)。石巻港+太平洋眺望、R1 食 焼そば+R1 育 萬画館観光、無料。", content_md: "- 立地:**石巻市**\n- 規模:**標高 60m**\n- 縁:**R1 育 石巻 3.11 関連 震災後復興象徴**\n- 期:**桜名所 4 月**\n- 入場:**無料**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "石巻市", lg_code: "04201", area_types: ["scenic_spot"], lat: 38.4344, lon: 141.3033, season_start: "2026-04-10", season_end: "2026-04-25", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["hiyoriyama", "60m", "post_disaster_recovery"], source: "manual" },
  { slug: "shichinohe-ski", category: "entertainment", sub_type: "miyagi_zao_scenic", title_zh: "七ヶ宿スキー場(刈田郡七ヶ宿町・蔵王連峰山形県境近く+ 1980 開設+ 全 6 コース+ R1 楽 みやぎ蔵王スキー場 と並ぶ宮城スキー 2 大+ 1 日リフト券 ¥3,800-4,500+ 12-3 月+ 価格手頃)", title_ja: "七ヶ宿スキー場", romaji: "Shichinohe Ski-jō", summary_zh: "**七ヶ宿スキー場は蔵王連峰山形県境**(刈田郡・**1980 開設+全 6 コース**)。R1 楽 みやぎ蔵王スキー と並ぶ宮城スキー 2 大、リフト券 ¥3,800-4,500。", content_md: "- 立地:**刈田郡七ヶ宿町**\n- 起源:**1980 開設 45 年**\n- 規模:**全 6 コース**\n- 期:**12-3 月**\n- 並列:**R1 楽 みやぎ蔵王スキー場 + R3 楽 七ヶ宿スキー = 宮城スキー 2 大**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: "刈田郡", municipality_ja: "七ヶ宿町", lg_code: "04302", area_types: ["scenic_spot", "mountain_village"], lat: 38.0103, lon: 140.4486, season_start: "2026-12-15", season_end: "2027-03-15", event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["shichinohe_ski", "1980", "6_courses"], source: "manual" },
  { slug: "kurihara-yumeoka-trekking", category: "entertainment", sub_type: "miyagi_outdoor", title_zh: "栗駒山温泉郷+R1 楽 栗駒山登山(栗原市・須川温泉登山口拠点+ R1 楽 栗駒山 1626m 神の絨毯紅葉+ 9 月下-10 月初+ 須川温泉 R3 住 拠点+ 仙台 → タクシー 2 時間+ 観光客向け秘境)", title_ja: "栗駒山温泉郷+登山", romaji: "Kurikoma Yumeoka Trekking", summary_zh: "**栗駒山温泉郷+登山は R1 楽 神の絨毯紅葉拠点**(栗原市・**須川温泉登山口**)。9 月下-10 月初、仙台 → タクシー 2 時間、観光客向け秘境。", content_md: "- 立地:**栗原市須川温泉**\n- 並列:**R1 楽 栗駒山(1626m)登山口拠点**\n- 期:**9 月下-10 月初紅葉「神の絨毯」**\n- アクセス:**仙台 → タクシー 2 時間**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "栗原市", lg_code: "04211", area_types: ["mountain_village", "scenic_spot"], lat: 38.9697, lon: 140.7842, season_start: "2026-09-15", season_end: "2026-10-15", event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kurikoma_trekking", "sukawa_onsen"], source: "manual" },

  // 行 (2)
  { slug: "sendai-koriyama-bus", category: "transport", sub_type: "miyagi_bus", title_zh: "仙台-郡山高速バス(仙台駅 ↔ 郡山駅・約 2 時間+ 1 日 12+ 便+ ¥2,200+ JR バス東北 + 福島交通共同+ R2 行 仙台-福島 1h30m と並ぶ福島県アクセス便+ 観光客向け)", title_ja: "仙台-郡山高速バス", romaji: "Sendai Kōriyama Bus", summary_zh: "**仙台-郡山高速バス**(JR バス東北+福島交通・**2h・¥2,200・1 日 12+ 便**)。R2 行 仙台-福島 1h30m と並ぶ福島県アクセス。", content_md: "- 区間:**仙台駅 ↔ 郡山駅**\n- 所要:**約 2 時間**\n- 料金:**¥2,200**\n- 便数:**1 日 12+ 便**\n- 並列:**R2 行 仙台-福島 + R3 行 仙台-郡山 = 福島県アクセス 2 大**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["transit_hub"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: 7, closed_days: [], external_urls: {}, tags: ["sendai_koriyama_bus", "2h", "12_buses"], source: "manual" },
  { slug: "sendai-akita-bus-akita-go", category: "transport", sub_type: "miyagi_bus", title_zh: "仙台-秋田高速バス・ジェイアール 仙秋号(仙台駅 ↔ 秋田駅・約 3 時間 30 分+ 1 日 4-5 便+ ¥4,500+ JR バス東北 + 秋北バス共同+ R1 行 東北本線+陸羽東線経由よりアクセス便)", title_ja: "仙台-秋田高速バス 仙秋号", romaji: "Sendai Akita Senshū-go", summary_zh: "**仙台-秋田高速バス仙秋号**(JR バス東北+秋北バス・**3h30m・¥4,500・1 日 4-5 便**)。R1 行 東北本線+陸羽東線経由よりアクセス便。", content_md: "- 区間:**仙台駅 ↔ 秋田駅**\n- 所要:**約 3 時間 30 分**\n- 料金:**¥4,500**\n- 便数:**1 日 4-5 便**\n- 共同運営:**JR バス東北 + 秋北バス**\n- 並列:**秋田 R2 行 秋田-盛岡 + R3 行 仙台-秋田 = 秋田 → 仙台アクセス 2 大**", region: "tohoku", prefecture_ja: "宮城県", gun_ja: null, municipality_ja: "仙台市", lg_code: "04101", area_types: ["transit_hub"], lat: 38.2606, lon: 140.8819, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["sendai_akita_senshu", "3_5h", "4500yen"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[miyagi-r3] 尚無條目"); return; }
  console.log(`[miyagi-r3] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) {
    const bySub = new Map<string, number>();
    for (const r of rows) bySub.set(r.sub_type, (bySub.get(r.sub_type) ?? 0) + 1);
    for (const [k, v] of [...bySub.entries()].sort()) console.log(`  ${k.padEnd(28)} ${v}`);
    return;
  }
  const sb = createAdminClient();
  const CHUNK = 50;
  let written = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const batch = rows.slice(i, i + CHUNK);
    const { error } = await sb.from("japan_entries").upsert(batch as any, { onConflict: "slug" });
    if (error) { console.error("[miyagi-r3] upsert failed:", error); process.exit(1); }
    written += batch.length;
    process.stdout.write(`\r[miyagi-r3] upsert: ${written}/${rows.length}`);
  }
  process.stdout.write("\n");
  console.log(`[miyagi-r3] Done — ${written} rows.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
