// Seed 埼玉県 R6 收卷(20 筆 / Sprint 6.x — 第十一卷埼玉県完結)
// 食 4 / 住 3 / 衣 3 / 育 4 / 楽 4 / 行 2 = 20
// 累積 203 + 20 = 223 達成 = 第十一卷完結
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 食 4
  {
    slug: "yakumo-yamamichi-shoku",
    category: "food", sub_type: "saitama_kyodo",
    title_zh: "八雲山道郷土料理(秩父市大滝・荒川源流秩父山地+ 山菜+地鶏+岩魚伝統料理・国道 140 号雁坂峠ライン沿い・道の駅大滝温泉 R1 住周辺・郷土食事処 4+ 軒+ 1 人前 ¥1,800-3,500)",
    title_ja: "八雲山道郷土料理", romaji: "Yakumo Yamamichi",
    summary_zh: "**八雲山道郷土料理は荒川源流秩父山地の山菜+地鶏+岩魚伝統**(秩父市大滝・**国道 140 号雁坂峠沿い**)。¥1,800-3,500。",
    content_md: "- 立地:**秩父市大滝(荒川源流秩父山地)**\n- 規模:**郷土食事処 4+ 軒**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "秩父市", lg_code: "11207",
    area_types: ["restaurant_traditional"], lat: 35.9522, lon: 138.9508,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["yakumo_yamamichi"], source: "manual",
  },
  {
    slug: "kawajima-yasai-kome",
    category: "food", sub_type: "saitama_kyodo",
    title_zh: "川島町野菜+米(比企郡川島町・1700 年代以降「武蔵野」野菜の里+ 川島町ブランド野菜+ コシヒカリ + R1 育 遠山記念館周辺農家直売・1kg ¥600-2,500)",
    title_ja: "川島町野菜", romaji: "Kawajima Yasai",
    summary_zh: "**川島町野菜+米は 1700 年代以降「武蔵野」野菜の里**(川島町・**ブランド野菜+コシヒカリ**)。¥600-2,500/kg、R1 育 遠山記念館連動。",
    content_md: "- 立地:**比企郡川島町**\n- 起源:**1700 年代以降「武蔵野」野菜の里**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: "比企郡", municipality_ja: "川島町", lg_code: "11346",
    area_types: ["farm_field"], lat: 35.9772, lon: 139.4717,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kawajima_yasai"], source: "manual",
  },
  {
    slug: "fukaya-negi-processed",
    category: "food", sub_type: "saitama_meika",
    title_zh: "深谷ねぎ加工品(深谷市・R1 食 深谷ねぎ派生・ねぎせんべい+ねぎラーメン+ねぎ味噌+ねぎチョコ・道の駅おかべ+ 全国百貨店流通+ ¥350-1,500)",
    title_ja: "深谷ねぎ加工品", romaji: "Fukaya Negi Processed",
    summary_zh: "**深谷ねぎ加工品は R1 食 深谷ねぎ派生・ねぎせんべい+ねぎラーメン+ねぎ味噌+ねぎチョコ**(深谷)。道の駅おかべ+全国百貨店、¥350-1,500。",
    content_md: "- 立地:**深谷市**\n- 関連:**R1 食 深谷ねぎ派生**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "深谷市", lg_code: "11218",
    area_types: ["restaurant_traditional"], lat: 36.1969, lon: 139.2811,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["fukaya_negi_processed"], source: "manual",
  },
  {
    slug: "higashi-matsuyama-yamasato",
    category: "food", sub_type: "saitama_kyodo",
    title_zh: "東松山山里料理(東松山市+滑川町+嵐山町・武蔵丘陵山里・1700 年代から伝統田舎料理+ 鴨蕎麦+山菜+猪鍋・郷土食事処 4+ 軒・R1 楽 武蔵丘陵森林公園 観光連動)",
    title_ja: "東松山山里料理", romaji: "Higashi Matsuyama Yamasato",
    summary_zh: "**東松山山里料理は武蔵丘陵山里・1700 年代から伝統田舎料理・鴨蕎麦+山菜+猪鍋**(東松山+滑川+嵐山・**郷土食事処 4+ 軒**)。R1 楽 武蔵丘陵連動。",
    content_md: "- 立地:**東松山市 + 比企郡(滑川 + 嵐山)**\n- 起源:**1700 年代以降**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "東松山市", lg_code: "11212",
    area_types: ["restaurant_traditional"], lat: 36.0419, lon: 139.3997,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["higashi_matsuyama_yamasato"], source: "manual",
  },

  // 住 3
  {
    slug: "ranzan-onsen-hotel",
    category: "lodging", sub_type: "saitama_central_business",
    title_zh: "嵐山温泉ホテル群(比企郡嵐山町・R1 楽 嵐山渓谷+R3 育 菅谷館跡周辺・全 3+ 軒小規模温泉旅館・1 泊 2 食 ¥10,500-16,500・武蔵丘陵森林公園 R1 楽 観光連動)",
    title_ja: "嵐山温泉ホテル", romaji: "Ranzan Onsen Hotel",
    summary_zh: "**嵐山温泉ホテル群は R1 楽 嵐山渓谷+R3 育 菅谷館周辺・全 3+ 軒**(嵐山町)。¥10,500-16,500、武蔵丘陵連動。",
    content_md: "- 立地:**比企郡嵐山町**\n- 規模:**全 3+ 軒**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: "比企郡", municipality_ja: "嵐山町", lg_code: "11342",
    area_types: ["onsen_town"], lat: 36.0556, lon: 139.3203,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["ranzan_onsen_hotel"], source: "manual",
  },
  {
    slug: "hanno-picnic-bnb",
    category: "lodging", sub_type: "saitama_hanno_onsen",
    title_zh: "飯能ピクニックB&B+ 山中宿(飯能市山間・R1 楽 ムーミンバレー+棒の嶺ハイキング起点・全 4+ 軒小規模 B&B+ 1 泊 2 食 ¥9,500-15,500・自然豊かな西武池袋線山中ステイ)",
    title_ja: "飯能 B&B", romaji: "Hannō B&B",
    summary_zh: "**飯能ピクニックB&B+山中宿は R1 楽 ムーミンバレー+棒の嶺ハイキング起点・全 4+ 軒**(飯能)。¥9,500-15,500。",
    content_md: "- 立地:**飯能市山間**\n- 規模:**全 4+ 軒**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "飯能市", lg_code: "11209",
    area_types: ["onsen_town"], lat: 35.8631, lon: 139.3017,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["hanno_picnic_bnb"], source: "manual",
  },
  {
    slug: "kawagoe-premium-suites",
    category: "lodging", sub_type: "saitama_kawagoe_modern",
    title_zh: "川越プレミアム蔵造り客室(川越市仲町・蔵造り街内 R1 住 町家旅館の最高級室+ 1 泊 ¥35,500-65,500/室・全 5+ 軒・国際観光客 + 富裕層向け・1 か月予約必須・R1 育 蔵造り街観光最深体験)",
    title_ja: "川越プレミアム蔵造り客室", romaji: "Kawagoe Premium Suites",
    summary_zh: "**川越プレミアム蔵造り客室は R1 住 町家旅館の最高級室・全 5+ 軒**(川越仲町)。¥35,500-65,500/室、富裕層向け。",
    content_md: "- 立地:**川越市仲町(蔵造り街内)**\n- 規模:**全 5+ 軒最高級室**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "川越市", lg_code: "11201",
    area_types: ["history_site_castle", "urban"], lat: 35.9251, lon: 139.4858,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 60, closed_days: [],
    external_urls: {}, tags: ["kawagoe_premium"], source: "manual",
  },

  // 衣 3
  {
    slug: "bushu-aizome-accessories",
    category: "fashion", sub_type: "saitama_aizome",
    title_zh: "武州正藍染アクセサリー(羽生市+加須市・R1 衣 武州正藍染派生・指輪+ブレスレット+ピアス・組合員工房 8+ 軒・¥3,500-25,000+ 国際 SNS 観光客代表)",
    title_ja: "武州藍アクセサリー", romaji: "Bushū Aizome Accessories",
    summary_zh: "**武州正藍染アクセサリーは R1 衣 派生・指輪+ブレスレット+ピアス**(羽生+加須・**組合員 8+ 軒**)。¥3,500-25,000、Instagram 代表。",
    content_md: "- 立地:**羽生市 + 加須市**\n- 関連:**R1 衣 武州正藍染派生**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "羽生市", lg_code: "11216",
    area_types: ["industrial_heritage", "shopping_district"], lat: 36.1722, lon: 139.5478,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["bushu_aizome_jewelry"], source: "manual",
  },
  {
    slug: "iwatsuki-haru-hina-zome",
    category: "fashion", sub_type: "saitama_doll_costume",
    title_zh: "岩槻春雛人形装束(さいたま市岩槻区・R1 衣 岩槻人形派生・3 月節句限定春雛+段飾衣装・東玉+東久 R1 老舗・¥35,000-2,500,000・春雛シーズン 1-3 月集客)",
    title_ja: "岩槻春雛装束", romaji: "Iwatsuki Haru Hina",
    summary_zh: "**岩槻春雛人形装束は R1 衣 派生・3 月節句限定春雛+段飾衣装**(岩槻区・**東玉+東久 R1 老舗**)。¥35,000-2,500,000、1-3 月集客。",
    content_md: "- 立地:**さいたま市岩槻区**\n- 関連:**R1 衣 岩槻人形装束派生**\n- 季節:**1-3 月春雛シーズン集客**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "さいたま市岩槻区", lg_code: "11100",
    area_types: ["industrial_heritage"], lat: 35.9489, lon: 139.6953,
    season_start: "2026-01-15", season_end: "2026-03-15", event_start: null, event_end: null,
    price_tier: 5, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["iwatsuki_haru_hina"], source: "manual",
  },
  {
    slug: "fukaya-momen-modern",
    category: "fashion", sub_type: "saitama_textile_other",
    title_zh: "深谷木綿+ R3 育 競進社派生現代織物(深谷市・1894 競進社模範蚕室派生 130 年+ 木綿織物復興工房 2+ 軒+ R3 育 競進社模範蚕室観光連動・着尺 ¥45,000-150,000)",
    title_ja: "深谷木綿", romaji: "Fukaya Momen",
    summary_zh: "**深谷木綿は 1894 競進社模範蚕室派生 130 年・木綿織物復興工房 2+ 軒**(深谷)。R3 育 競進社観光連動、¥45,000-150,000。",
    content_md: "- 立地:**深谷市**\n- 派生:**1894 競進社模範蚕室派生 130 年**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "深谷市", lg_code: "11218",
    area_types: ["industrial_heritage"], lat: 36.1969, lon: 139.2811,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 4, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["fukaya_momen", "1894_派生"], source: "manual",
  },

  // 育 4
  {
    slug: "kitain-500-rakan-detail",
    category: "culture", sub_type: "saitama_kawagoe_culture",
    title_zh: "喜多院五百羅漢詳解(川越市小仙波町・R1 育 喜多院派生+ 1782-1825 天明 2-文政 8 年 44 年間奉納 538 体+ 国指定重要文化財・1 体ずつ表情異なる江戸期木彫芸術代表+ 入観 ¥400 大人)",
    title_ja: "喜多院五百羅漢詳解", romaji: "Kitain 500 Rakan",
    summary_zh: "**喜多院五百羅漢は 1782-1825 天明 2-文政 8 年 44 年間奉納 538 体・1 体ずつ表情異なる**(川越・**国指定重要文化財**)。入観 ¥400、江戸期木彫芸術代表。",
    content_md: "- 立地:**川越市小仙波町**\n- 起源:**1782-1825 天明 2-文政 8 年 44 年間**\n- 規模:**538 体 + 1 体ずつ表情異なる**\n- 認定:**国指定重要文化財**\n- 入観:**¥400 大人**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "川越市", lg_code: "11201",
    area_types: ["temple_shrine"], lat: 35.9156, lon: 139.4928,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["500_rakan", "1782", "538_statues"], source: "manual",
  },
  {
    slug: "ishida-tsutsumi-mizuzeme",
    category: "culture", sub_type: "saitama_north_culture",
    title_zh: "石田堤跡・忍城水攻歴史散策道(行田市+鴻巣市・1590 石田三成水攻時築造 28km・国指定史跡 2014・現存 2.6km+ 散策道・R1 育 忍城+さきたま古墳 観光連動・「のぼうの城」歴史記憶)",
    title_ja: "石田堤跡", romaji: "Ishida Tsutsumi",
    summary_zh: "**石田堤跡は 1590 石田三成水攻時築造 28km・2014 国指定史跡・現存 2.6km**(行田+鴻巣・**「のぼうの城」歴史記憶**)。R1 育 忍城+さきたま古墳連動。",
    content_md: "- 立地:**行田市 + 鴻巣市**\n- 起源:**1590 石田三成水攻時築造 28km**\n- 認定:**2014 国指定史跡**\n- 現存:**2.6km + 散策道**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "行田市", lg_code: "11206",
    area_types: ["history_site_castle"], lat: 36.1389, lon: 139.4556,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["ishida_tsutsumi", "1590", "2014_national"], source: "manual",
  },
  {
    slug: "hodosan-jinja-nagatoro",
    category: "culture", sub_type: "saitama_chichibu_culture",
    title_zh: "宝登山神社+ロープウェイ(秩父郡長瀞町・110 景行天皇代日本武尊創建説 1900 年+ 秩父三社の 1+ 標高 497m 宝登山+ ロープウェイ 1961 開業 64 年+ 関東屈指のパワースポット+ 1-2 月ロウバイ + 4 月桜)",
    title_ja: "宝登山神社", romaji: "Hodosan Jinja",
    summary_zh: "**宝登山神社+ロープウェイは 110 景行天皇代日本武尊創建説 1900 年・秩父三社の 1**(長瀞町・**標高 497m + 1961 ロープウェイ**)。1-2 月ロウバイ+4 月桜。",
    content_md: "- 立地:**秩父郡長瀞町**\n- 起源:**110 景行天皇代日本武尊創建説**\n- 並列:**秩父三社(秩父神社+三峯神社+宝登山神社)**\n- 標高:**497m**\n- ロープウェイ:**1961 開業 64 年**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: "秩父郡", municipality_ja: "長瀞町", lg_code: "11363",
    area_types: ["temple_shrine", "scenic_spot"], lat: 36.0978, lon: 139.1083,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["hodosan_jinja", "110_yamato_takeru", "1900_years", "1961_ropeway"], source: "manual",
  },
  {
    slug: "fukaya-station-tokyo-omotemai",
    category: "culture", sub_type: "saitama_north_culture",
    title_zh: "深谷駅(深谷市・1996 開業 30 年+ 東京駅丸の内駅舎(1914)を擬す 1/2 サイズ駅舎+ 設計者 辰野金吾派生「日本煉瓦製造」R3 育 派生展示・観光客撮影名所・「東京駅の弟」と呼ばれる JR 高崎線駅)",
    title_ja: "深谷駅", romaji: "Fukaya Station",
    summary_zh: "**深谷駅は 1996 開業 30 年・東京駅丸の内駅舎(1914)を擬す 1/2 サイズ・「東京駅の弟」**(深谷・**辰野金吾派生「日本煉瓦製造」R3 育 派生**)。観光客撮影名所。",
    content_md: "- 立地:**深谷市**\n- 起源:**1996 開業 30 年**\n- 看板:**東京駅丸の内駅舎(1914)を擬す 1/2 サイズ駅舎**\n- 関連:**R3 育 深谷煉瓦資料館 派生(日本煉瓦製造 1888・東京駅レンガ供給産地)**\n- 別名:**「東京駅の弟」**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "深谷市", lg_code: "11218",
    area_types: ["transit_hub", "history_site_castle"], lat: 36.1969, lon: 139.2811,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["fukaya_station", "1996", "30_years", "tokyo_imitation"], source: "manual",
  },

  // 楽 4
  {
    slug: "chichibu-yomatsuri-hanabi",
    category: "entertainment", sub_type: "saitama_other_festivals",
    title_zh: "秩父夜祭花火大会(秩父市・R1 育 秩父夜祭(UNESCO 2016)花火部分・12/3 大祭夜・約 6,000 発・冬季の花火大会全国でも珍しい・観客 30 万人/夜)",
    title_ja: "秩父夜祭花火", romaji: "Chichibu Yomatsuri Hanabi",
    summary_zh: "**秩父夜祭花火大会は R1 育 秩父夜祭花火部分・12/3 大祭夜・約 6,000 発・冬季花火全国稀**(秩父)。観客 30 万人/夜。",
    content_md: "- 立地:**秩父市**\n- 開催:**12/3 秩父夜祭大祭夜**\n- 規模:**約 6,000 発 + 観客 30 万人/夜**\n- 看板:**冬季の花火大会・全国でも珍しい**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "秩父市", lg_code: "11207",
    area_types: ["festival_grounds"], lat: 35.9978, lon: 139.0894,
    season_start: "2026-11-25", season_end: "2026-12-04",
    event_start: "2026-12-03T19:30:00+09:00", event_end: "2026-12-03T22:00:00+09:00",
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["chichibu_yomatsuri_hanabi", "winter_hanabi"], source: "manual",
  },
  {
    slug: "fukaya-mokuren-matsuri",
    category: "entertainment", sub_type: "saitama_other_festivals",
    title_zh: "深谷もくれん祭(深谷市・4 月初旬+ 渋沢栄一旧宅周辺もくれん 1,000+ 株開花・ R2 育 渋沢栄一旧宅 観光連動・観客 5 万人/シーズン+ 入園無料)",
    title_ja: "深谷もくれん祭", romaji: "Fukaya Mokuren",
    summary_zh: "**深谷もくれん祭は 4 月初旬・渋沢栄一旧宅周辺もくれん 1,000+ 株開花**(深谷)。R2 育 渋沢栄一連動、観客 5 万人/シーズン。",
    content_md: "- 立地:**深谷市(R2 育 渋沢栄一旧宅周辺)**\n- 開花:**4 月初旬**\n- 規模:**もくれん 1,000+ 株**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "深谷市", lg_code: "11218",
    area_types: ["scenic_spot"], lat: 36.2056, lon: 139.2856,
    season_start: "2026-03-25", season_end: "2026-04-15", event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["fukaya_mokuren"], source: "manual",
  },
  {
    slug: "saitama-shogyo-hanabi-omiya",
    category: "entertainment", sub_type: "saitama_other_festivals",
    title_zh: "さいたま市花火大会・大宮花火(さいたま市大宮区+西区・荒川河川敷+大宮公園・8 月中旬 + 1956 起源 69 年伝統・約 5,000 発+ 観客 50 万人/3 日・関東屈指県都花火)",
    title_ja: "さいたま市花火", romaji: "Saitama City Hanabi",
    summary_zh: "**さいたま市花火大会・大宮花火は 8 月中旬・1956 起源 69 年伝統・約 5,000 発**(大宮区+西区)。観客 50 万人/3 日、関東屈指県都花火。",
    content_md: "- 立地:**さいたま市大宮区 + 西区(荒川河川敷+大宮公園)**\n- 起源:**1956・69 年**\n- 規模:**約 5,000 発 + 観客 50 万人/3 日**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "さいたま市大宮区", lg_code: "11100",
    area_types: ["festival_grounds"], lat: 35.9156, lon: 139.6308,
    season_start: "2026-08-01", season_end: "2026-08-25",
    event_start: "2026-08-08T19:00:00+09:00", event_end: "2026-08-10T20:30:00+09:00",
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["saitama_city_hanabi", "1956", "69_years"], source: "manual",
  },
  {
    slug: "kawagoe-hatsumode",
    category: "entertainment", sub_type: "saitama_other_festivals",
    title_zh: "川越初詣(川越市・1/1-3・R1 育 喜多院+R5 育 川越東照宮+R1 育 川越熊野神社+蓮馨寺・「川越七福神霊場」+ 観客 50 万人/3 日 関東屈指の伝統初詣ルート)",
    title_ja: "川越初詣", romaji: "Kawagoe Hatsumōde",
    summary_zh: "**川越初詣は 1/1-3・R1 育 喜多院+R5 育 川越東照宮+蓮馨寺・「川越七福神霊場」**(川越)。観客 50 万人/3 日、関東屈指の伝統初詣ルート。",
    content_md: "- 立地:**川越市**\n- 開催:**1/1-3**\n- 規模:**観客 50 万人/3 日**\n- ルート:**R1 育 喜多院 + R5 育 川越東照宮 + 蓮馨寺(川越七福神霊場)**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "川越市", lg_code: "11201",
    area_types: ["temple_shrine", "festival_grounds"], lat: 35.9156, lon: 139.4928,
    season_start: "2025-12-31", season_end: "2026-01-05",
    event_start: "2026-01-01T00:00:00+09:00", event_end: "2026-01-03T22:00:00+09:00",
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kawagoe_hatsumode", "kawagoe_seven_god"], source: "manual",
  },

  // 行 2
  {
    slug: "seibu-chichibu-station-terminal",
    category: "transport", sub_type: "saitama_seibu",
    title_zh: "西武秩父駅(秩父市野坂町・1969 開業 56 年・西武秩父線終着駅+ 西武鉄道直営「西武秩父駅前温泉 祭の湯」R1 住直結+ 「ラビュー」LAVIEW 終着駅・観光客 1 日 1.5 万人 関東山岳線終点 hub)",
    title_ja: "西武秩父駅", romaji: "Seibu Chichibu Station",
    summary_zh: "**西武秩父駅は 1969 開業 56 年・西武秩父線終着駅・「ラビュー」LAVIEW 終着駅**(秩父市)。R1 住 祭の湯直結、観光 1 日 1.5 万人。",
    content_md: "- 立地:**秩父市野坂町**\n- 起源:**1969 開業 56 年**\n- 看板:**西武秩父線終着駅 + 「ラビュー」LAVIEW 終着駅**\n- 関連:**R1 住 祭の湯直結 + 関東山岳線終点 hub**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "秩父市", lg_code: "11207",
    area_types: ["transit_hub"], lat: 35.9914, lon: 139.0833,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["seibu_chichibu_station", "1969", "56_years", "laview_terminus"], source: "manual",
  },
  {
    slug: "kawagoe-station-multi-line",
    category: "transport", sub_type: "saitama_terminal",
    title_zh: "川越駅(川越市・JR 川越線+東武東上線結節+ 1916 開業 109 年+ 1 日乗降 13 万人 県内 4 位+ 「小江戸名所めぐり」観光客起点・川越プリンス R1 住 + 蔵造り街徒歩 15 分)",
    title_ja: "川越駅", romaji: "Kawagoe Station",
    summary_zh: "**川越駅は JR 川越線+東武東上線結節・1916 開業 109 年・1 日 13 万人県内 4 位**(川越)。「小江戸名所めぐり」観光客起点。",
    content_md: "- 立地:**川越市**\n- 起源:**1916 開業 109 年**\n- 結節:**JR 川越線 + 東武東上線**\n- 1 日:**13 万人 県内 4 位**\n- 関連:**R1 住 川越プリンスホテル + R1 育 蔵造り街徒歩 15 分**",
    region: "kanto", prefecture_ja: "埼玉県", gun_ja: null, municipality_ja: "川越市", lg_code: "11201",
    area_types: ["transit_hub"], lat: 35.9095, lon: 139.4858,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kawagoe_station", "1916", "109_years"], source: "manual",
  },
];

seedMain(rows, "saitama-r6");
