// Seed 群馬県 楽 R1(20 筆 / Sprint 1.5)
// 草津湯もみ+祭+花火+紅葉+冬+スポーツ+ ラフティング

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

interface SeedRow {
  slug: string; category: string; sub_type: string;
  title_zh: string; title_ja: string | null; romaji: string | null;
  summary_zh: string; content_md: string | null;
  region: "kanto"; prefecture_ja: "群馬県";
  gun_ja: string | null; municipality_ja: string | null; lg_code: string | null;
  area_types: string[]; lat: number | null; lon: number | null;
  season_start: string | null; season_end: string | null;
  event_start: string | null; event_end: string | null;
  price_tier: number | null; booking_window_days: number | null;
  closed_days: string[]; external_urls: Record<string, string>; tags: string[]; source: "manual";
}

const rows: SeedRow[] = [
  { slug: "kusatsu-yumomi-show", category: "entertainment", sub_type: "gunma_3_grand_festivals", title_zh: "草津温泉湯もみショー(吾妻郡草津町・湯畑横「熱の湯」・1947 開始 78 年+ R1 育 草津湯畑派生・草津民謡+伝統湯もみ・1 日 6 回上演+ 入場 ¥700+ 海外観光客代表文化体験・国際 SNS 拡散)", title_ja: "草津湯もみショー", romaji: "Kusatsu Yumomi", summary_zh: "**草津温泉湯もみショーは 1947 開始 78 年・R1 育 草津湯畑派生・草津民謡+伝統湯もみ**(草津・**1 日 6 回上演**)。¥700、海外観光客代表文化体験、国際 SNS 拡散。", content_md: "- 立地:**吾妻郡草津町**(湯畑横「熱の湯」)\n- 起源:**1947 開始 78 年**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["festival_event"], lat: 36.6228, lon: 138.5969, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yumomi_show", "1947"], source: "manual" },
  { slug: "kusatsu-international-music-fest", category: "entertainment", sub_type: "gunma_3_grand_festivals", title_zh: "草津国際音楽祭(吾妻郡草津町・1980 開催 45 年+ 国際クラシック音楽アカデミー+祭・8 月開催・国内+海外音楽家+受講生 1000+ 名参加+ 国際的音楽イベント代表+ R1 住 草津温泉観光連動・観覧 ¥3,500-12,000)", title_ja: "草津国際音楽祭", romaji: "Kusatsu Intl Music Fest", summary_zh: "**草津国際音楽祭は 1980 開催 45 年・国際クラシック音楽アカデミー+祭・8 月開催**(草津・**国内+海外音楽家+受講生 1000+ 名**)。R1 住 草津温泉、¥3,500-12,000。", content_md: "- 立地:**吾妻郡草津町**\n- 起源:**1980 開催 45 年**\n- 規模:**国内 + 海外音楽家 + 受講生 1000+ 名参加**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["festival_event"], lat: 36.6228, lon: 138.5969, season_start: null, season_end: null, event_start: "2026-08-15", event_end: "2026-08-30", price_tier: 3, booking_window_days: 90, closed_days: [], external_urls: {}, tags: ["kusatsu_intl_music", "1980", "45_years"], source: "manual" },
  { slug: "kiryu-yagibushi-fest", category: "entertainment", sub_type: "gunma_3_grand_festivals", title_zh: "桐生八木節まつり(桐生市・1963 開催 62 年+ 国指定無形民俗文化財「八木節」群馬+栃木両毛代表民謡+ 8 月第 1 金土日開催・動員 50 万人+ 駅前+市内一斉踊り+ R1 衣 桐生織観光連動・観覧無料)", title_ja: "桐生八木節まつり", romaji: "Kiryu Yagibushi", summary_zh: "**桐生八木節まつりは 1963 開催 62 年・国指定無形民俗文化財「八木節」両毛代表民謡**(桐生・**8 月第 1 金土日+動員 50 万人**)。R1 衣 桐生織連動、無料。", content_md: "- 立地:**桐生市**\n- 起源:**1963 開催 62 年**\n- 認定:**国指定無形民俗文化財「八木節」**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "桐生市", lg_code: "10203", area_types: ["festival_event"], lat: 36.4044, lon: 139.3306, season_start: null, season_end: null, event_start: "2026-08-07", event_end: "2026-08-09", price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["yagibushi_fest", "1963"], source: "manual" },
  { slug: "takasaki-fireworks-1990", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "高崎まつり花火大会(高崎市・1990 開催 35 年+ 関東屈指 15,000 発+ 動員 80 万人+ 8 月第 1 土曜開催+ 烏川河川敷+ R1 食 高崎ハム+R1 衣 高崎達磨観光連動+ 観覧無料)", title_ja: "高崎まつり花火", romaji: "Takasaki Hanabi", summary_zh: "**高崎まつり花火大会は 1990 開催 35 年・関東屈指 15,000 発・動員 80 万人**(高崎・**8 月第 1 土曜+烏川河川敷**)。R1 食+R1 衣 連動、無料。", content_md: "- 立地:**高崎市烏川河川敷**\n- 起源:**1990 開催 35 年**\n- 規模:**15,000 発 + 動員 80 万人**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "高崎市", lg_code: "10202", area_types: ["festival_event"], lat: 36.3219, lon: 139.0033, season_start: null, season_end: null, event_start: "2026-08-01", event_end: "2026-08-01", price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["takasaki_hanabi", "1990", "800k"], source: "manual" },
  { slug: "tatebayashi-cosmos-fest", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "館林つつじまつり+ つつじが岡公園(館林市・1928 開園 97 年+ つつじ 100 種 1 万株・国指定名勝 1934+ 4-5 月つつじまつり+ 動員 25 万人+ R1 育 茂林寺観光連動・入場 ¥630)", title_ja: "館林つつじまつり", romaji: "Tatebayashi Tsutsuji", summary_zh: "**館林つつじまつり+つつじが岡公園は 1928 開園 97 年・つつじ 100 種 1 万株・国指定名勝 1934**(館林・**4-5 月+動員 25 万人**)。R1 育 茂林寺、¥630。", content_md: "- 立地:**館林市**\n- 起源:**1928 開園 97 年**\n- 認定:**国指定名勝 1934**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "館林市", lg_code: "10207", area_types: ["festival_event", "scenic_spot"], lat: 36.2453, lon: 139.5419, season_start: null, season_end: null, event_start: "2026-04-10", event_end: "2026-05-15", price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tatebayashi_tsutsuji", "1928", "1934"], source: "manual" },
  { slug: "minakami-rafting", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "みなかみラフティング(利根郡みなかみ町・1990 年代以降産業化・関東屈指ラフティング名所+ 利根川急流・全国 100+ ツアー会社+ 4-11 月運営+ 1 人 ¥6,500-12,500+ R1 住 水上温泉郷+R1 育 谷川岳観光連動+ 国際観光客代表)", title_ja: "みなかみラフティング", romaji: "Minakami Rafting", summary_zh: "**みなかみラフティングは 1990 年代以降産業化・関東屈指ラフティング名所**(みなかみ・**利根川急流+全国 100+ ツアー会社**)。4-11 月、¥6,500-12,500、R1 住 水上+R1 育 谷川岳、国際代表。", content_md: "- 立地:**利根郡みなかみ町**\n- 起源:**1990 年代以降産業化**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["scenic_spot"], lat: 36.7847, lon: 138.9558, season_start: "2026-04-15", season_end: "2026-11-15", event_start: null, event_end: null, price_tier: 3, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["minakami_rafting"], source: "manual" },
  { slug: "tanigawa-ropeway", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "谷川岳ロープウェイ+天神平(利根郡みなかみ町・1960 開業 65 年+ R1 育 谷川岳 1977m 派生・標高 1319m 天神平+ 4-10 月+12-3 月運行+ 紅葉+冬スキー・往復 ¥3,000+ 国内+海外観光客代表)", title_ja: "谷川岳ロープウェイ", romaji: "Tanigawa Ropeway", summary_zh: "**谷川岳ロープウェイ+天神平は 1960 開業 65 年・R1 育 谷川岳派生・標高 1319m 天神平**(みなかみ・**4-10 月+12-3 月運行・紅葉+冬スキー**)。¥3,000、国内+海外観光客代表。", content_md: "- 立地:**利根郡みなかみ町**\n- 起源:**1960 開業 65 年**\n- 規模:**標高 1319m**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["transit_hub", "scenic_spot"], lat: 36.7919, lon: 138.9342, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 2, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tanigawa_ropeway", "1960", "1319m"], source: "manual" },
  { slug: "akagi-koyo-100", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "赤城山紅葉+大沼+小沼(R1 育 赤城山 1828m 派生・10 月中-11 月初紅葉ピーク+ 紅葉名所 100 選+ 大沼湖畔+小沼湖畔・観光客代表ハイキング・無料・関東屈指紅葉景観)", title_ja: "赤城山紅葉", romaji: "Akagi Kōyō", summary_zh: "**赤城山紅葉+大沼+小沼は R1 育派生・10 月中-11 月初・紅葉名所 100 選**(前橋・**大沼+小沼湖畔**)。観光客代表ハイキング、無料、関東屈指紅葉景観。", content_md: "- 立地:**前橋市赤城山**\n- 関係:**R1 育 赤城山 1828m 派生**\n- 期:**10 月中-11 月初紅葉ピーク**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["scenic_spot"], lat: 36.5536, lon: 139.1747, season_start: "2026-10-15", season_end: "2026-11-10", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["akagi_koyo", "100_koyo"], source: "manual" },
  { slug: "tanigawa-koyo-route", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "谷川+水上紅葉ドライブ(利根郡みなかみ・R1 育 谷川岳+R1 楽 ロープウェイ派生・10 月中-11 月初紅葉+ 一の倉沢+湯桧曽川+ 関越自動車道月夜野 IC+水上 IC・国内観光客代表ドライブ)", title_ja: "谷川+水上紅葉", romaji: "Tanigawa Kōyō", summary_zh: "**谷川+水上紅葉ドライブは R1 育+R1 楽派生・10 月中-11 月初**(みなかみ・**一の倉沢+湯桧曽川**)。関越月夜野+水上 IC、国内観光客代表。", content_md: "- 立地:**利根郡みなかみ町**\n- 関係:**R1 育 谷川岳 + R1 楽 ロープウェイ派生**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["scenic_spot"], lat: 36.7847, lon: 138.9558, season_start: "2026-10-15", season_end: "2026-11-10", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tanigawa_koyo"], source: "manual" },
  { slug: "kusatsu-snow-fest", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "草津温泉雪まつり+ R1 行 草津白根スキー場(吾妻郡草津町・1991 開催 34 年+ 1-2 月雪像 30+ 体+ 草津国際スキー場(1914 開発・全国 7 大スキー場)・1 日券 ¥4,500-6,500+ R1 住 草津温泉観光連動)", title_ja: "草津温泉雪まつり", romaji: "Kusatsu Snow Fest", summary_zh: "**草津温泉雪まつり+R1 行 草津白根スキー場は 1991 開催 34 年・1-2 月雪像 30+ 体・草津国際スキー場 1914**(草津・**全国 7 大スキー場**)。¥4,500-6,500、R1 住 連動。", content_md: "- 立地:**吾妻郡草津町**\n- 起源:**1991 雪まつり + 1914 草津国際スキー場**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "草津町", lg_code: "10426", area_types: ["festival_event", "scenic_spot"], lat: 36.6228, lon: 138.5969, season_start: "2026-12-15", season_end: "2027-03-31", event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kusatsu_snow", "1914_ski"], source: "manual" },
  { slug: "ikaho-toy-museum", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "伊香保おもちゃと人形自動車博物館(渋川市伊香保・2000 開園 25 年+ 全 30,000+ 点ヴィンテージおもちゃ+人形+クラシックカー・国内最大級コレクション・入館 ¥1,300+ R1 住 伊香保温泉観光連動+ 国内家族観光客代表)", title_ja: "伊香保おもちゃ博物館", romaji: "Ikaho Toy Museum", summary_zh: "**伊香保おもちゃと人形自動車博物館は 2000 開園 25 年・全 30,000+ 点ヴィンテージ**(渋川・**国内最大級コレクション**)。¥1,300、R1 住 伊香保連動、家族観光客代表。", content_md: "- 立地:**渋川市伊香保**\n- 起源:**2000 開園 25 年**\n- 規模:**全 30,000+ 点**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["scenic_spot"], lat: 36.4886, lon: 138.9242, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ikaho_toy_museum", "2000"], source: "manual" },
  { slug: "gunma-flower-park", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "ぐんまフラワーパーク(前橋市柏倉・1992 開園 33 年+ 18.4 万 ㎡ 県立花公園+ 4-5 月チューリップ+夏ハイドランジア+秋コスモス+冬イルミ+ R1 育 赤城山観光連動・入館 ¥720+ 国内家族観光客代表)", title_ja: "ぐんまフラワーパーク", romaji: "Gunma Flower Park", summary_zh: "**ぐんまフラワーパークは 1992 開園 33 年・18.4 万 ㎡ 県立花公園**(前橋柏倉・**チューリップ+紫陽花+コスモス+冬イルミ**)。R1 育 赤城山連動、¥720、家族観光客代表。", content_md: "- 立地:**前橋市柏倉**\n- 起源:**1992 開園 33 年**\n- 規模:**18.4 万 ㎡ 県立花公園**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["scenic_spot"], lat: 36.4519, lon: 139.1706, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["gunma_flower_park", "1992"], source: "manual" },
  { slug: "konnyaku-park-tour", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "こんにゃくパーク+富岡製糸場ツアー(甘楽郡甘楽町・2014 開園 11 年+ R1 食 こんにゃく No.1 95% 派生・無料工場見学+食べ放題+ R1 育 富岡製糸場観光連動+ 動員 1 日 5000 人+ 観光客代表)", title_ja: "こんにゃくパーク", romaji: "Konnyaku Park", summary_zh: "**こんにゃくパーク+富岡製糸場ツアーは 2014 開園 11 年・R1 食 こんにゃく No.1 派生**(甘楽・**無料工場見学+食べ放題+R1 育 富岡製糸場連動**)。動員 5000 人/日、観光客代表。", content_md: "- 立地:**甘楽郡甘楽町**\n- 起源:**2014 開園 11 年**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "甘楽郡", municipality_ja: "甘楽町", lg_code: "10383", area_types: ["scenic_spot", "industrial_heritage"], lat: 36.2517, lon: 138.8556, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: ["木"], external_urls: {}, tags: ["konnyaku_park", "2014"], source: "manual" },
  { slug: "tsumagoi-cabbage-marathon", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "嬬恋キャベツマラソン(吾妻郡嬬恋村・1995 開催 30 年+ R1 食 嬬恋キャベツ No.1 35% 派生・標高 1000m+ 全国マラソンランナー大会・10 月開催・5000+ 名動員+ R1 住 万座温泉観光連動)", title_ja: "嬬恋キャベツマラソン", romaji: "Tsumagoi Marathon", summary_zh: "**嬬恋キャベツマラソンは 1995 開催 30 年・R1 食 No.1 35% 派生・標高 1000m**(嬬恋・**10 月+5000+ 名動員**)。R1 住 万座連動。", content_md: "- 立地:**吾妻郡嬬恋村**\n- 起源:**1995 開催 30 年**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "吾妻郡", municipality_ja: "嬬恋村", lg_code: "10425", area_types: ["festival_event"], lat: 36.5208, lon: 138.5097, season_start: null, season_end: null, event_start: "2026-10-04", event_end: "2026-10-04", price_tier: 2, booking_window_days: 60, closed_days: [], external_urls: {}, tags: ["tsumagoi_marathon"], source: "manual" },
  { slug: "thezawell-thermal-pavillion", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "ザスパ群馬+群馬県スポーツ J リーグ(前橋・1995 創設 30 年+ J リーグ 2 サッカークラブ+ 正田醤油スタジアム前橋 15,253 席+ R1 楽 鹿島アントラーズ+栃木 SC 系統 関東 J リーグ・観戦 ¥2,500-6,500+ 4-11 月)", title_ja: "ザスパ群馬", romaji: "Thespa Gunma", summary_zh: "**ザスパ群馬+群馬県スポーツ J リーグは 1995 創設 30 年・J リーグ 2 サッカー**(前橋・**正田醤油スタジアム 15,253 席**)。R1 楽 鹿島+栃木 SC と並ぶ、¥2,500-6,500、4-11 月。", content_md: "- 立地:**前橋市**\n- 起源:**1995 創設 30 年**\n- 規模:**全 15,253 席正田醤油スタジアム**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["scenic_spot"], lat: 36.3856, lon: 139.0586, season_start: "2026-04-01", season_end: "2026-11-30", event_start: null, event_end: null, price_tier: 2, booking_window_days: 30, closed_days: [], external_urls: {}, tags: ["thespa_gunma", "1995", "j2"], source: "manual" },
  { slug: "ikaho-onsen-festival", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "伊香保まつり(渋川市伊香保・1953 開催 72 年+ R1 住 伊香保温泉派生・9 月第 3 土日開催・伊香保神社例大祭・神輿+山車+石段街渡御+ R1 衣 石段街観光連動・観覧無料)", title_ja: "伊香保まつり", romaji: "Ikaho Festival", summary_zh: "**伊香保まつりは 1953 開催 72 年・R1 住派生・9 月第 3 土日伊香保神社例大祭**(渋川・**神輿+山車+石段街渡御**)。R1 衣 石段街連動、無料。", content_md: "- 立地:**渋川市伊香保**\n- 起源:**1953 開催 72 年**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "渋川市", lg_code: "10208", area_types: ["festival_event"], lat: 36.4886, lon: 138.9242, season_start: null, season_end: null, event_start: "2026-09-19", event_end: "2026-09-21", price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["ikaho_festival", "1953"], source: "manual" },
  { slug: "tanigawa-skiing", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "水上+谷川+尾瀬岩鞍スキー(利根郡みなかみ+片品・1955-1990 年代開発・全 5+ スキー場+ 12-3 月運営+ 1 日券 ¥4,500-6,500+ R1 住 水上温泉郷+R1 育 谷川岳観光連動+ 海外スキーヤー代表)", title_ja: "水上+谷川+尾瀬岩鞍スキー", romaji: "Minakami Ski", summary_zh: "**水上+谷川+尾瀬岩鞍スキーは 1955-1990 年代開発・全 5+ スキー場**(みなかみ+片品・**12-3 月**)。¥4,500-6,500、R1 住 水上+R1 育 谷川岳、海外スキーヤー代表。", content_md: "- 立地:**利根郡みなかみ町 + 片品村**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "みなかみ町", lg_code: "10449", area_types: ["scenic_spot"], lat: 36.7847, lon: 138.9558, season_start: "2026-12-15", season_end: "2027-03-31", event_start: null, event_end: null, price_tier: 3, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["minakami_ski"], source: "manual" },
  { slug: "kawaba-shiroi-village", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "川場田園プラザ+ 道の駅 No.1(利根郡川場村・1998 開設 27 年+ 全国道の駅人気ランキング 1 位連覇・年間動員 200 万人+ R1 食 永井 1886+土田 1907 酒蔵+ R1 食 沼田りんご観光連動+ 入場無料)", title_ja: "川場田園プラザ", romaji: "Kawaba Denen Plaza", summary_zh: "**川場田園プラザ+道の駅 No.1 は 1998 開設 27 年・全国道の駅人気ランキング 1 位連覇・動員 200 万人/年**(川場・**R1 食 永井+土田酒蔵+沼田りんご**)。無料。", content_md: "- 立地:**利根郡川場村**\n- 起源:**1998 開設 27 年**\n- 認定:**全国道の駅人気ランキング 1 位連覇**", region: "kanto", prefecture_ja: "群馬県", gun_ja: "利根郡", municipality_ja: "川場村", lg_code: "10448", area_types: ["scenic_spot", "shopping_district"], lat: 36.6644, lon: 139.0719, season_start: null, season_end: null, event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["kawaba_denen", "1998", "no1_michinoeki"], source: "manual" },
  { slug: "maebashi-fireworks", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "前橋まつり+前橋花火大会(前橋市・1939 開催 86 年+ 10 月第 2 土日開催・神輿+山車+踊りパレード+ 8 月利根川河川敷花火 12,000 発+ 動員 50 万人+ R1 育 けやきウォーク前橋観光連動・入場無料)", title_ja: "前橋まつり+花火", romaji: "Maebashi Festival", summary_zh: "**前橋まつり+花火大会は 1939 開催 86 年・10 月第 2 土日**(前橋・**神輿+山車+踊り+8 月花火 12,000 発・動員 50 万人**)。R1 育 けやきウォーク連動、無料。", content_md: "- 立地:**前橋市利根川河川敷**\n- 起源:**1939 開催 86 年**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "前橋市", lg_code: "10201", area_types: ["festival_event"], lat: 36.3895, lon: 139.0635, season_start: null, season_end: null, event_start: "2026-10-10", event_end: "2026-10-11", price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["maebashi_festival", "1939"], source: "manual" },
  { slug: "tomioka-cherry-jou-yama", category: "entertainment", sub_type: "gunma_outdoor", title_zh: "富岡桜+ 城山公園+ R1 育 富岡製糸場桜(富岡市・桜並木 500+ 本+ 桜まつり 4 月初-中・R1 育 富岡製糸場 UNESCO 観光連動+ 観覧無料・SNS 拡散・国内+海外観光客代表)", title_ja: "富岡桜+城山公園", romaji: "Tomioka Sakura", summary_zh: "**富岡桜+城山公園+R1 育 富岡製糸場桜は桜並木 500+ 本・4 月初-中桜まつり**(富岡・**R1 育 UNESCO 連動**)。無料、SNS 拡散、国内+海外観光客代表。", content_md: "- 立地:**富岡市**\n- 規模:**桜並木 500+ 本**", region: "kanto", prefecture_ja: "群馬県", gun_ja: null, municipality_ja: "富岡市", lg_code: "10210", area_types: ["scenic_spot"], lat: 36.2575, lon: 138.8939, season_start: "2026-03-25", season_end: "2026-04-15", event_start: null, event_end: null, price_tier: 1, booking_window_days: null, closed_days: [], external_urls: {}, tags: ["tomioka_sakura"], source: "manual" },
];

async function main() {
  if (rows.length === 0) { console.log("[gunma-entertainment-r1] 尚無條目"); return; }
  console.log(`[gunma-entertainment-r1] ${rows.length} 筆 ${DRY ? "(dry-run)" : ""}`);
  if (DRY) return;
  const sb = createAdminClient();
  const { error } = await sb.from("japan_entries").upsert(rows as any, { onConflict: "slug" });
  if (error) { console.error("[gunma-entertainment-r1] upsert failed:", error); process.exit(1); }
  console.log(`[gunma-entertainment-r1] Done — ${rows.length} rows.`);
}
main().catch((err) => { console.error(err); process.exit(1); });
