// Seed 50 筆北海道 · 住類 條目 → public.japan_entries。
//
// 6 sub_type(Phase 1 + 補平衡,複用 japan-entries.ts 既有定義,不新增):
//   - onsen_ryokan (溫泉旅館) 25 筆:
//       登別(2)/定山渓(2)/洞爺湖(2)/阿寒湖(2)/層雲峡(2)/十勝川(2)/湯の川(2)/ニセコ湯本(1)/支笏湖(1)
//       + 天人峡(1)/吹上(1)/旭岳(1)/十勝岳(1)/濁川(1)/羅臼(1)/鹿部(1)/豊富(1)/カルルス(1)
//   - luxury_hotel (高級飯店) 9 筆:
//       星野トマム/星野 OMO3 すすきの/ヒルトンニセコ/パークハイアット HANAZONO/ルスツ/函館ラビスタベイ/ザ・ウィンザー洞爺
//       + 星野 OMO5 小樽(2022)/知床北こぶし(ウトロ)
//   - budget_hotel_chain (商務連鎖) 8 筆:
//       JR タワー日航/JR イン札幌/ドーミーイン ANNEX/モントレ/リッチモンド/JR イン旭川
//       + ラビスタ函館五稜郭/コンフォート新千歲空港
//   - rural_minshuku (偏鄉民宿) 1 筆:岩尾別温泉 ホテル地の涯(知床羅臼岳登山口)
//   - capsule_hostel (膠囊/青旅) 4 筆:
//       ナインアワーズ札幌/札幌国際ユースホステル/AMANEK カプセル札幌 + ナインアワーズ新千歲空港
//   - glamping_camp (Glamping/營地) 3 筆:
//       然別湖コタン(冬季氷村)/RECAMP 洞爺 + オートリゾート苫小牧アルテン
//
// 注意:
//   - 旅館無「季節」,season_start/end 為 null;然別湖コタン 有冬季 1-3 月 event_start/end。
//   - 價格為 2026-04 參考,實際依訂房日期波動 3-10 倍,content_md 末尾註明查核日期。
//   - 地址精度至番地,lg_code 採市町村レベル(札幌 01100、定山渓屬札幌市南区但統一 01100)。
//   - external_urls 只放 official(官網)+ wikipedia(若有),不放 Jalan/樂天(robots 禁止且污染合規)。
//   - 全部 upsert,slug 當 conflict key,重跑安全。
//
// 資料來源分層(合規見 docs/japan-sources-hokkaido-lodging.md):
//   L1 確認(Wikipedia JP / 各温泉観光協會 / 自治體観光課):
//     登別温泉(1858 第一滝本館・9 種泉質)、定山渓温泉(1866 美泉定山開湯)、
//     洞爺湖温泉(1917 湧出)、阿寒湖温泉(明治初期開湯・まりも伝説)、
//     層雲峡温泉(1923 本格開湯・大雪山国立公園)、十勝川温泉(世界 2 大モール泉)、
//     湯の川温泉(1653 松前藩 発見)、ニセコ温泉郷(多数源泉)、
//     支笏湖 丸駒温泉(1915 創業・湖水同水位露天)、
//     星野リゾート トマム(1983 アルファリゾート開業・2004 星野買収・雲海テラス)、
//     パークハイアット ニセコ HANAZONO(2020 開業)、ザ・ウィンザー洞爺(2008 G8 会場)、
//     然別湖コタン(1980 開催・冬季 1-3 月 氷上村)
//   L2 普遍知識(確知但未抓到 Wikipedia 独立条目):
//     個別旅館の公称年(滝乃家・章月・乃の風・鶴雅・朝陽亭・啄木亭 等)、
//     都市飯店(JR タワー日航 2003・ドーミーイン ANNEX・モントレ・リッチモンド)、
//     膠囊(ナインアワーズ・国際ユース・AMANEK)、岩尾別地の涯(1964 創業・山小屋型)
//
// Usage:
//   npm run seed:japan-hokkaido-lodging:dry
//   npm run seed:japan-hokkaido-lodging

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { createAdminClient } from "../src/lib/supabase/admin";

const DRY = process.argv.includes("--dry-run");

type SubType =
  | "onsen_ryokan"
  | "luxury_hotel"
  | "budget_hotel_chain"
  | "rural_minshuku"
  | "capsule_hostel"
  | "glamping_camp"
  | "lodging_area_guide";

interface SeedRow {
  slug: string;
  category: "lodging";
  sub_type: SubType;
  title_zh: string;
  title_ja: string | null;
  romaji: string | null;
  summary_zh: string;
  content_md: string | null;
  region: "hokkaido";
  prefecture_ja: "北海道";
  gun_ja: string | null;
  municipality_ja: string | null;
  lg_code: string | null;
  area_types: string[];
  lat: number | null;
  lon: number | null;
  season_start: string | null;
  season_end: string | null;
  event_start: string | null;
  event_end: string | null;
  price_tier: number | null;
  booking_window_days: number | null;
  closed_days: string[];
  external_urls: Record<string, string>;
  tags: string[];
  source: "manual";
}

const rows: SeedRow[] = [
  // ── onsen_ryokan (25 筆) ──────────────────────────────
  {
    slug: "hokkaido-noboribetsu-daiichi-takimotokan",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "登別温泉 第一滝本館",
    title_ja: "第一滝本館",
    romaji: "Dai-ichi Takimotokan",
    summary_zh:
      "登別温泉最古老且規模最大的旅館,1858 年(安政 5)創業近 170 年。地獄谷前立地,擁有 35 座露天/內湯,可一次體驗 5 種不同泉質(硫黃泉/酸性泉/食鹽泉/芒硝泉/鐵泉),是日本少見一館 5 泉質並存的溫泉旅館。",
    content_md:
      "- 地址:登別市登別温泉町 55 番地(JR 登別駅→道南バス 15 分)\n- 立地:地獄谷入口正前方,客室窗外直接望地獄谷噴氣\n- 溫泉:35 座浴槽 × 5 種泉質(硫黃/芒硝/食鹽/酸性鐵/酸性硫黃),全室掛け流し\n- 規模:客室約 400 室,登別最大級\n- 歷史:1858 年(安政 5)初代 瀧本金藏 開業、登別温泉の原点\n- 料金:1 泊 2 食 平日 ¥16,000〜 / 旺季 ¥35,000〜(和洋室による)\n- チェックイン 15:00 / チェックアウト 10:00\n- 送迎:JR 登別駅 / 新千歲空港 需預約\n- 周辺:地獄谷(徒歩 3 分)・大湯沼(車 5 分)・クマ牧場\n- 2026-04 人工查核(官網 + Wikipedia 登別温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "登別市",
    lg_code: "01230",
    area_types: ["onsen_town"],
    lat: 42.4915,
    lon: 141.1494,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://takimotokan.co.jp/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E7%99%BB%E5%88%A5%E6%B8%A9%E6%B3%89",
    },
    tags: ["noboribetsu", "since_1858", "five_springs", "jigokudani", "largest_scale"],
    source: "manual",
  },
  {
    slug: "hokkaido-noboribetsu-takinoya",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "登別温泉 滝乃家",
    title_ja: "滝乃家",
    romaji: "Takinoya",
    summary_zh:
      "登別代表的純和風高級旅館,1917 年(大正 6)創業。館內日本庭園 + 屋上露天「雲海」以俯視地獄谷聞名。全 28 室,懷石料理專精北海道山海食材,氣氛靜謐對比鄰家的第一滝本館。",
    content_md:
      "- 地址:登別市登別温泉町 162 番地(JR 登別駅→道南バス 15 分)\n- 立地:地獄谷旁高台、屋上「雲海」露天可眺溪谷\n- 溫泉:屋上雲海露天 + 庭園露天 + 大浴場,掛け流し 硫黃泉+芒硝泉\n- 規模:28 室(本館 + 翠山亭別館)、客室數少身のおもてなし\n- 歷史:1917 年(大正 6)創業\n- 料金:1 泊 2 食 平日 ¥35,000〜 / 旺季 ¥60,000〜\n- 食事:北海道季節食材懷石、部屋食 or 個室食事処\n- 受賞:プロが選ぶ日本のホテル旅館 100 選 連年\n- 周辺:地獄谷(徒歩 5 分)、大湯沼、登別マリンパーク\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "登別市",
    lg_code: "01230",
    area_types: ["onsen_town"],
    lat: 42.4925,
    lon: 141.1481,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      official: "https://takinoya.co.jp/",
    },
    tags: ["noboribetsu", "since_1917", "luxury_japanese", "kaiseki", "100_selection"],
    source: "manual",
  },
  {
    slug: "hokkaido-jozankei-shogetsu-grand",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "定山渓温泉 章月グランドホテル",
    title_ja: "章月グランドホテル",
    romaji: "Shōgetsu Grand Hotel",
    summary_zh:
      "定山渓温泉的代表大型旅館,1956 年(昭和 31)創業。札幌中心車程 50 分可達,溫泉湧出量豐沛。春櫻、夏涼、秋楓、冬雪四季分明,是札幌人週末短程逃逸的首選。",
    content_md:
      "- 地址:札幌市南区定山渓温泉西 4 丁目 32 番地(定山渓温泉巴士站徒歩 3 分)\n- 立地:豊平川渓谷沿い、紅葉の名所「二見吊橋」徒歩圏\n- 溫泉:鈉氯化物泉、大浴場「渓流の湯」+ 露天「空中四季の湯」\n- 規模:165 室、大規模旅館\n- 歷史:1956 年(昭和 31)創業、定山渓開湯(1866 美泉定山)地歷 160 年\n- 料金:1 泊 2 食 平日 ¥17,000〜 / 旺季 ¥30,000〜\n- アクセス:札幌駅からじょうてつバス 約 60 分、車 50 分\n- 無料送迎:札幌駅北口 1 日 1 便 要予約\n- 周辺:二見公園紅葉(10 月)、定山渓神社、足湯「足の湯」\n- 2026-04 人工查核(官網 + Wikipedia 定山渓温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["onsen_town"],
    lat: 42.9675,
    lon: 141.1694,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E5%AE%9A%E5%B1%B1%E6%B8%93%E6%B8%A9%E6%B3%89",
    },
    tags: ["jozankei", "since_1956", "sapporo_nearby", "autumn_leaves", "free_shuttle"],
    source: "manual",
  },
  {
    slug: "hokkaido-jozankei-suizantei",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "定山渓温泉 翠山亭倶楽部定山渓",
    title_ja: "翠山亭倶楽部 定山渓",
    romaji: "Suizantei Club Jōzankei",
    summary_zh:
      "定山渓の和モダン系小規模高級旅館,2006 年開業。全 30 室室内露天風呂付き、會員制風格。料理旅館的定位,以北海道食材×京風懷石著名。",
    content_md:
      "- 地址:札幌市南区定山渓温泉東 3 丁目 228 番地(定山渓温泉巴士站徒歩 5 分)\n- 立地:紅葉渓谷「かっぱ淵」眺望、二見公園徒歩 8 分\n- 溫泉:鈉氯化物泉、全 30 室室内露天風呂付き + 大浴場・露天\n- 規模:30 室、隠れ宿系\n- 開業:2006 年、野口観光系列\n- 料金:1 泊 2 食 平日 ¥28,000〜 / 旺季 ¥45,000〜\n- 食事:京風懷石 × 北海道食材、個室食事処\n- 特色:全室檜風呂 or 岩風呂、禁煙館\n- 周辺:二見公園(徒歩 8 分)、定山源泉公園\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["onsen_town"],
    lat: 42.9666,
    lon: 141.1706,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["jozankei", "wa_modern", "inroom_onsen", "kaiseki", "noguchi_group"],
    source: "manual",
  },
  {
    slug: "hokkaido-toya-nonokaze-resort",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "洞爺湖温泉 乃の風リゾート",
    title_ja: "乃の風リゾート",
    romaji: "Nonokaze Resort",
    summary_zh:
      "洞爺湖畔大型溫泉度假村,2014 年全面リニューアル開業。湖正面眺望、夏季毎晚 20:45 洞爺湖花火大會直接從客室看。和モダン客室 100% 湖景。",
    content_md:
      "- 地址:虻田郡洞爺湖町洞爺湖温泉 29-1(洞爺湖温泉巴士站徒歩 3 分)\n- 立地:洞爺湖畔正面、全室レイクビュー\n- 溫泉:鈉氯化物泉、展望浴場「天風」+ 露天、掛け流し\n- 規模:102 室、和モダン\n- 開業:1968 年 → 2014 年全面リニューアル(前身:洞爺湖温泉ホテル)\n- 料金:1 泊 2 食 平日 ¥20,000〜 / 旺季 ¥45,000〜\n- 花火:洞爺湖ロングラン花火大會(4/28-10/31 毎晚 20:45)從客室直接観覧\n- 食事:北海道ビュッフェ + 別注でカニ追加\n- アクセス:JR 洞爺駅から道南バス 15 分、新千歲空港から車 2 時間\n- 2026-04 人工查核(官網 + Wikipedia 洞爺湖温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "洞爺湖町",
    lg_code: "01584",
    area_types: ["onsen_town", "coastal"],
    lat: 42.5617,
    lon: 140.8603,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://www.nonokaze-resort.com/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E6%B4%9E%E7%88%BA%E6%B9%96%E6%B8%A9%E6%B3%89",
    },
    tags: ["toya", "lake_view", "fireworks_view", "renewed_2014"],
    source: "manual",
  },
  {
    slug: "hokkaido-toya-sun-palace",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "洞爺湖温泉 洞爺サンパレス リゾート&スパ",
    title_ja: "洞爺サンパレス リゾート&スパ",
    romaji: "Toya Sun Palace Resort & Spa",
    summary_zh:
      "洞爺湖最大規模温泉リゾート,1974 年創業。家族向けウォーターパーク + 屋外プール夏季開放 + 源泉掛け流し。親子二世代旅行の定番。",
    content_md:
      "- 地址:虻田郡洞爺湖町洞爺湖温泉 7-1(洞爺湖温泉巴士站徒歩 10 分 / 無料送迎有)\n- 立地:洞爺湖畔、全客室レイクビュー\n- 溫泉:鈉氯化物泉、「ラグーン温泉」水着着用混浴(通年)、大浴場・露天別棟\n- 規模:414 室、洞爺湖最大\n- 開業:1974 年創業、2010 年リニューアル\n- 料金:1 泊 2 食 平日 ¥15,000〜 / 旺季 ¥32,000〜\n- 設備:屋内プール(通年)、屋外プール(夏季)、ボーリング、卓球、カラオケ\n- 食事:150 種類以上ビュッフェ、子連れ家族向け\n- アクセス:JR 洞爺駅から無料送迎 15 分、新千歲から 2 時間\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "洞爺湖町",
    lg_code: "01584",
    area_types: ["onsen_town", "coastal"],
    lat: 42.5636,
    lon: 140.8572,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 45,
    closed_days: [],
    external_urls: {
      official: "https://www.toyasunpalace.co.jp/",
    },
    tags: ["toya", "family_friendly", "water_park", "since_1974", "largest_toya"],
    source: "manual",
  },
  {
    slug: "hokkaido-akan-tsuruga-hinanoza",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "阿寒湖温泉 あかん鶴雅別荘 鄙の座",
    title_ja: "あかん鶴雅別荘 鄙の座",
    romaji: "Akan Tsuruga Bessō Hinanoza",
    summary_zh:
      "阿寒湖頂級隠れ宿,2003 年開業,全 25 室(全室 露天風呂付き)。鶴雅集團最高端格,アイヌ文化融合客室設計。湖畔日本庭園 + 京風懷石,夫婦/ハネムーン人気。",
    content_md:
      "- 地址:釧路市阿寒町阿寒湖温泉 2-8-1(阿寒湖温泉巴士停留所徒歩 5 分)\n- 立地:阿寒湖畔、湖面と雄阿寒岳を眺望\n- 溫泉:含硫黃-鈉-塩化物泉、全 25 室露天付、大浴場「鄙の座 湯浴み処」\n- 規模:25 室、全室露天・全室 80m² 以上\n- 開業:2003 年、鶴雅グループ\n- 料金:1 泊 2 食 平日 ¥60,000〜 / 旺季 ¥90,000〜\n- 食事:北海道食材 × 京風懷石、個室食事処\n- 特色:アイヌ 木彫アート、ラウンジ「夜想」無料ドリンク\n- 受賞:プロが選ぶ日本のホテル旅館 100 選 連年\n- 周辺:阿寒湖畔アイヌコタン(徒歩 5 分)、まりも展示観察センター\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "釧路市",
    lg_code: "01206",
    area_types: ["onsen_town"],
    lat: 43.4389,
    lon: 144.1003,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 5,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      official: "https://www.hinanoza.com/",
    },
    tags: ["akan", "luxury_hideaway", "all_room_onsen", "ainu_culture", "100_selection"],
    source: "manual",
  },
  {
    slug: "hokkaido-akan-tsuruga-yuku-no-sato",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "阿寒湖温泉 あかん遊久の里鶴雅",
    title_ja: "あかん遊久の里鶴雅",
    romaji: "Akan Yuku-no-Sato Tsuruga",
    summary_zh:
      "阿寒湖温泉の代表大型旅館,鶴雅集團旗艦。8 階屋上「天の原」露天可 360°眺望阿寒湖と雄阿寒岳。まりも文化展示 + アイヌ古式舞踊 夜晚ライブ。",
    content_md:
      "- 地址:釧路市阿寒町阿寒湖温泉 4-6-10(阿寒湖温泉巴士停留所徒歩 3 分)\n- 立地:阿寒湖畔中心部\n- 溫泉:含硫黃-鈉-塩化物泉、屋上露天「天の原」(8F)+ 大浴場「空」\n- 規模:240 室、大型\n- 開業:1953 年(昭和 28)創業、2005 年全面リニューアル\n- 料金:1 泊 2 食 平日 ¥18,000〜 / 旺季 ¥36,000〜\n- 食事:ビュッフェ「HAL」北海道 100 種類、追加でカニしゃぶ\n- 特色:アイヌ古式舞踊ショー 毎晚 20:30(無料)、まりも展示コーナー\n- 周辺:アイヌコタン(徒歩 3 分)、阿寒湖遊覧船(夏季)、ボッケ自然遊歩道\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "釧路市",
    lg_code: "01206",
    area_types: ["onsen_town"],
    lat: 43.4401,
    lon: 144.0987,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://www.tsuruga.com/",
    },
    tags: ["akan", "since_1953", "ainu_dance", "marimo", "tsuruga_group"],
    source: "manual",
  },
  {
    slug: "hokkaido-sounkyo-choyotei",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "層雲峡温泉 朝陽亭",
    title_ja: "朝陽亭",
    romaji: "Chōyōtei",
    summary_zh:
      "層雲峡温泉の高台立地、大雪山国立公園眺望。大江本家系列、1969 年創業,層雲峡黒岳眺望露天風呂「空山」以日出 5 時開放聞名。冬季氷瀑まつり 期間最佳住宿點。",
    content_md:
      "- 地址:上川郡上川町層雲峡温泉(層雲峡温泉巴士停留所徒歩 8 分 / 無料送迎)\n- 立地:層雲峡温泉街の高台、大雪山(黒岳)眺望\n- 溫泉:単純温泉 + 硫黃-鈉-塩化物泉、展望露天「空山」+ 大浴場\n- 規模:192 室、大型\n- 開業:1969 年(昭和 44)、大江本家グループ\n- 料金:1 泊 2 食 平日 ¥16,000〜 / 旺季 ¥32,000〜\n- 食事:ビュッフェ + 和膳プラン\n- 露天「空山」:5:00-9:00 / 14:00-24:00、黒岳日出眺望\n- 氷瀑まつり(1 月下-3 月中)徒歩 10 分\n- アクセス:JR 上川駅から道北バス 30 分、旭川空港 1.5 時間\n- 2026-04 人工查核(官網 + Wikipedia 層雲峡)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川郡",
    municipality_ja: "上川町",
    lg_code: "01457",
    area_types: ["onsen_town", "mountain"],
    lat: 43.7289,
    lon: 142.9753,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://www.choyotei.com/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E5%B1%A4%E9%9B%B2%E5%B3%A1%E6%B8%A9%E6%B3%89",
    },
    tags: ["sounkyo", "since_1969", "daisetsuzan_view", "hyobaku_festival", "oe_honke"],
    source: "manual",
  },
  {
    slug: "hokkaido-sounkyo-choyo-resort",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "層雲峡温泉 朝陽リゾートホテル",
    title_ja: "朝陽リゾートホテル",
    romaji: "Chōyō Resort Hotel",
    summary_zh:
      "朝陽亭の姊妹館,比朝陽亭更新(1997 リニューアル)且大眾価格帯。層雲峡渓谷沿い立地,屋上露天 + 岩盤浴無料利用可,預算中間層の温泉家族旅行定番。",
    content_md:
      "- 地址:上川郡上川町層雲峡温泉(層雲峡温泉巴士停留所徒歩 5 分)\n- 立地:層雲峡渓谷沿い、銀河の滝方面\n- 溫泉:単純温泉、屋上露天「妙の湯」+ 大浴場 + 岩盤浴無料\n- 規模:190 室、中大型\n- 開業:1974 年、1997 年リニューアル、大江本家グループ姉妹館\n- 料金:1 泊 2 食 平日 ¥13,000〜 / 旺季 ¥25,000〜 朝陽亭より安い\n- 食事:和洋中ビュッフェ(カニ・ステーキ含)\n- 特色:岩盤浴 無料(通常 ¥1,500)、ラウンジ無料ドリンク 17-22 時\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川郡",
    municipality_ja: "上川町",
    lg_code: "01457",
    area_types: ["onsen_town", "mountain"],
    lat: 43.7293,
    lon: 142.9749,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 45,
    closed_days: [],
    external_urls: {},
    tags: ["sounkyo", "mid_budget", "free_ganbanyoku", "oe_honke", "sister_hotel"],
    source: "manual",
  },
  {
    slug: "hokkaido-tokachigawa-daiichi-hotel",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "十勝川温泉 第一ホテル 豊洲亭・豊泉閣",
    title_ja: "十勝川温泉 第一ホテル",
    romaji: "Tokachigawa Daiichi Hotel",
    summary_zh:
      "十勝川温泉代表大型旅館、モール温泉世界 2 大の 1 つ。1955 年創業。植物性有機物由来「植物性温泉」で美肌効果突出,「北海道遺産」指定。",
    content_md:
      "- 地址:河東郡音更町十勝川温泉南 12 丁目 1(JR 帯広駅→十勝バス 25 分)\n- 立地:十勝川沿い、広大な十勝平野\n- 溫泉:モール温泉(植物性腐植質泉)、世界でハンガリー ヘーヴィーズ と 2 大\n- 泉質特徴:pH 9.0 弱アルカリ性、美人の湯として北海道遺産指定(2004)\n- 規模:174 室、豊洲亭(新館)+ 豊泉閣(本館)\n- 歷史:1913 年(大正 2)温泉湧出 → 1955 年(昭和 30)第一ホテル開業\n- 料金:1 泊 2 食 平日 ¥14,000〜 / 旺季 ¥28,000〜\n- 食事:北海道十勝ビュッフェ、地元食材多用\n- 特色:白鳥フライト(11-3 月)、庭園露天、茶房「松風」\n- 2026-04 人工查核(官網 + Wikipedia 十勝川温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "河東郡",
    municipality_ja: "音更町",
    lg_code: "01631",
    area_types: ["onsen_town", "rural"],
    lat: 42.9186,
    lon: 143.2525,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://www.daiichihotel.com/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E5%8D%81%E5%8B%9D%E5%B7%9D%E6%B8%A9%E6%B3%89",
    },
    tags: ["tokachigawa", "moor_onsen", "world_rare_spring", "since_1955", "hokkaido_heritage"],
    source: "manual",
  },
  {
    slug: "hokkaido-tokachigawa-kangetsuen",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "十勝川温泉 観月苑",
    title_ja: "十勝川温泉 観月苑",
    romaji: "Tokachigawa Kangetsuen",
    summary_zh:
      "十勝川温泉老舖、1961 年創業。モール温泉的另一代表館。3 樓露天「飛翔」は日本庭園に囲まれた 500 坪の広さ、十勝川と白鳥飛来を眺望。",
    content_md:
      "- 地址:河東郡音更町十勝川温泉南 14 丁目 1(JR 帯広駅→十勝バス 25 分)\n- 立地:十勝川沿い、白鳥観察地隣接\n- 溫泉:モール温泉(植物性腐植質泉)、pH 9.0 弱アルカリ、美人の湯\n- 規模:104 室、中大型\n- 開業:1961 年(昭和 36)創業\n- 料金:1 泊 2 食 平日 ¥15,000〜 / 旺季 ¥29,000〜\n- 名物:3F 露天「飛翔」500 坪日本庭園、夜間ライトアップ\n- 食事:会席或ビュッフェ選択、十勝牛ステーキ提供\n- 送迎:JR 帯広駅から無料シャトル(要予約)\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "河東郡",
    municipality_ja: "音更町",
    lg_code: "01631",
    area_types: ["onsen_town", "rural"],
    lat: 42.9173,
    lon: 143.2533,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://www.kangetsuen.com/",
    },
    tags: ["tokachigawa", "moor_onsen", "since_1961", "500tsubo_rotenburo", "swan_view"],
    source: "manual",
  },
  {
    slug: "hokkaido-yunokawa-takubokutei",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "湯の川温泉 啄木亭",
    title_ja: "湯の川温泉 啄木亭",
    romaji: "Yunokawa Takubokutei",
    summary_zh:
      "函館湯の川温泉の代表、歌人石川啄木に因んで命名。13 階屋上展望大浴場「雲海」は函館山夜景と津軽海峡一望で全国露天風呂ランキング上位常連。",
    content_md:
      "- 地址:函館市湯川町 1-18-15(市電「湯の川温泉」停留所徒歩 7 分)\n- 立地:津軽海峡沿い、函館山眺望\n- 溫泉:鈉氯化物-硫酸鹽泉、13F 屋上展望大浴場 + 庭園露天\n- 規模:101 室、中大型\n- 開業:1962 年、大和家系列\n- 料金:1 泊 2 食 平日 ¥18,000〜 / 旺季 ¥36,000〜\n- 名物:屋上大浴場「雲海」函館山 + 海峽眺望、夕焼時間帯絶景\n- 食事:旬彩会席(津軽海峡海鮮 + 函館朝市食材)\n- 命名:歌人 石川啄木(1907 函館滞在)詠んだ「潮の香の朝の湯」に因む\n- アクセス:函館空港から車 5 分・市電 5 分\n- 2026-04 人工查核(官網 + Wikipedia 湯の川温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["onsen_town", "urban", "coastal"],
    lat: 41.7806,
    lon: 140.7867,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://www.takubokutei.com/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E6%B9%AF%E3%81%AE%E5%B7%9D%E6%B8%A9%E6%B3%89_(%E5%8C%97%E6%B5%B7%E9%81%93)",
    },
    tags: ["yunokawa", "hakodate", "rooftop_rotenburo", "night_view", "takuboku"],
    source: "manual",
  },
  {
    slug: "hokkaido-yunokawa-heiseikan-shiosai",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "湯の川温泉 平成館しおさい亭",
    title_ja: "湯の川温泉 平成館 しおさい亭",
    romaji: "Heiseikan Shiosai-tei",
    summary_zh:
      "函館湯の川温泉,海沿いで津軽海峡直面の立地。全客室海景オーシャンビュー。平成元年(1989)開業で名称,海鮮中心料理と 8F 大浴場「しおさい」で人気。",
    content_md:
      "- 地址:函館市湯川町 1-2-25(市電「湯の川」停留所徒歩 3 分)\n- 立地:津軽海峡沿い、全室海景\n- 溫泉:鈉氯化物泉、8F 展望大浴場「しおさい」+ 露天\n- 規模:115 室\n- 開業:1989 年(平成元年)、啄木亭姉妹館(大和家系列)\n- 料金:1 泊 2 食 平日 ¥17,000〜 / 旺季 ¥32,000〜\n- 食事:海鮮中心「潮騒の膳」(アワビ・カニ・海峡烏賊)\n- 特色:津軽海峡を渡る漁火(夏)+ 冬は海鮮鍋\n- アクセス:函館空港から車 7 分・市電 5 分\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["onsen_town", "urban", "coastal"],
    lat: 41.7819,
    lon: 140.7881,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 45,
    closed_days: [],
    external_urls: {},
    tags: ["yunokawa", "hakodate", "ocean_view", "seafood_kaiseki", "since_1989"],
    source: "manual",
  },
  {
    slug: "hokkaido-niseko-grand-hotel",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "ニセコグランドホテル(ニセコ湯本温泉)",
    title_ja: "ニセコグランドホテル",
    romaji: "Niseko Grand Hotel",
    summary_zh:
      "ニセコ温泉郷の老舖、ニセコアンヌプリ山麓立地。日本では珍しく残る混浴大露天風呂「森の湯」(男女時間制あり)。鉄分豊富な赤茶色湯は「不死鳥の湯」と呼ばれる。",
    content_md:
      "- 地址:虻田郡ニセコ町ニセコ 412(JR ニセコ駅→車 20 分、無料送迎あり)\n- 立地:ニセコアンヌプリ山麓、チセヌプリ眺望\n- 溫泉:鈉炭酸水素鹽塩化物泉、鉄分豊富赤湯、混浴大露天 2 つ + 男女別露天\n- 規模:114 室\n- 開業:1971 年(昭和 46)、ニセコ温泉郷のパイオニア\n- 料金:1 泊 2 食 平日 ¥14,000〜 / 旺季 ¥28,000〜\n- 名物:混浴露天「森の湯」(男女時間制:19-21 時 女性専用)\n- 食事:和洋中 70 種ビュッフェ、カニ食べ放題プラン\n- 周辺:ニセコアンヌプリ国際スキー場(冬・車 15 分)、チセヌプリ登山口\n- 2026-04 人工查核(官網 + Wikipedia ニセコ温泉郷)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "ニセコ町",
    lg_code: "01395",
    area_types: ["onsen_town", "mountain"],
    lat: 42.8667,
    lon: 140.6833,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://niseko-grand.com/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E3%83%8B%E3%82%BB%E3%82%B3%E6%B8%A9%E6%B3%89%E9%83%B7",
    },
    tags: ["niseko", "since_1971", "mixed_bath", "iron_spring", "hokkaido_ski"],
    source: "manual",
  },
  {
    slug: "hokkaido-shikotsu-marukoma-onsen",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "支笏湖 丸駒温泉旅館",
    title_ja: "丸駒温泉旅館",
    romaji: "Marukoma Onsen Ryokan",
    summary_zh:
      "支笏湖畔に建つ秘湯系老舗、1915 年(大正 4)創業。湖畔天然露天「湖と同じ水位の自然湧出」は日本で 4 軒のみの珍しい形式。冬凍らない支笏湖 + 山を眺望。",
    content_md:
      "- 地址:千歳市幌美内 7(JR 千歳駅→無料送迎 or 車 50 分)\n- 立地:支笏湖北岸、秘湯感の強い陸の孤島\n- 溫泉:鈉氯化物泉 + 炭酸水素鹽泉、天然露天「湖面岩風呂」(湖水と同水位湧出)\n- 泉質特徴:4 種源泉(天然露天/内湯/展望大浴場/家族風呂 それぞれ別)\n- 規模:51 室\n- 開業:1915 年(大正 4)、創業者 佐々木初太郎\n- 料金:1 泊 2 食 平日 ¥16,000〜 / 旺季 ¥30,000〜\n- 名物:湖面岩風呂(男湯 24H / 女湯 時間制)、湖との境界なし\n- アクセス:新千歲空港から無料送迎 60 分(要予約)\n- 周辺:支笏湖遊覧船(夏)、氷濤まつり(1-2 月徒歩 10 分)\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "千歳市",
    lg_code: "01224",
    area_types: ["onsen_town", "mountain"],
    lat: 42.8069,
    lon: 141.3208,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      official: "https://www.marukoma.co.jp/",
    },
    tags: ["shikotsu", "since_1915", "lakeside_onsen", "hidden_spring", "4_sources"],
    source: "manual",
  },
  {
    slug: "hokkaido-tenninkyo-tenninkaku",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "天人峡温泉 天人閣",
    title_ja: "天人峡温泉 天人閣",
    romaji: "Tenninkyo Onsen Tenninkaku",
    summary_zh:
      "大雪山国立公園の峡谷温泉、1941 年(昭和 16)創業。忠別川の柱状節理渓谷に面する秘湯で、落差 270m「羽衣の滝」(日本の滝百選)徒歩 20 分圏。硫酸鹽泉の名湯。",
    content_md:
      "- 地址:上川郡東川町勇駒別天人峡温泉(JR 旭川駅→バス 90 分 or 車 70 分)\n- 立地:大雪山国立公園・忠別川源流渓谷・標高 700m\n- 溫泉:カルシウム・ナトリウム硫酸塩泉、源泉かけ流し、露天「羽衣の湯」\n- 規模:66 室\n- 開業:1941 年(昭和 16)、戦後の観光旅館化\n- 料金:1 泊 2 食 平日 ¥16,000〜 / 旺季 ¥32,000〜\n- 名物:羽衣の滝(落差 270m・日本の滝百選)徒歩 20 分、敷島の滝 徒歩 40 分\n- アクセス:旭川から道北バス「天人峡線」(夏期のみ運行)、冬期は車必須\n- 周辺:旭岳ロープウェイ(車 40 分・夏の高山植物・秋の紅葉・冬スキー)\n- 季節:5-10 月 渓谷散策、11-4 月 雪景色・露天\n- 2026-04 人工查核(官網 + Wikipedia 天人峡温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川郡",
    municipality_ja: "東川町",
    lg_code: "01458",
    area_types: ["onsen_town", "mountain"],
    lat: 43.6167,
    lon: 142.6167,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E5%A4%A9%E4%BA%BA%E5%B3%A1%E6%B8%A9%E6%B3%89",
    },
    tags: ["tenninkyo", "since_1941", "waterfall_view", "daisetsuzan", "sulfate_spring"],
    source: "manual",
  },
  {
    slug: "hokkaido-fukiage-hakuginso",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "吹上温泉保養センター 白銀荘",
    title_ja: "吹上温泉保養センター 白銀荘",
    romaji: "Fukiage Onsen Hakuginso",
    summary_zh:
      "上富良野町営の公共保養施設、十勝岳中腹標高 1010m。北海道最大級の混浴野天風呂「吹上露天の湯」(無料)は撮影公開されるほど知名度高い。1994 年 町営リニューアル。",
    content_md:
      "- 地址:空知郡上富良野町吹上温泉(JR 上富良野駅→車 30 分、冬期通行止めあり)\n- 立地:十勝岳中腹標高 1010m、原生林に囲まれた山の湯\n- 溫泉:単純酸性泉 pH 2.7(胃腸病・皮膚病)、男女別露天 + 内湯\n- 別途:徒歩 3 分「吹上露天の湯」は 24 時間無料の混浴野天(ガチ混浴、水着不可)\n- 規模:個室 4 + ライダーハウス 相部屋(低価格)\n- 運営:1994 年 上富良野町営リニューアル、元は大正期発見の湯治場\n- 料金:日帰り入浴 ¥700 / 宿泊素泊 ¥3,500〜(格安)、食事要持参 or 炊事場自炊\n- アクセス:夏期のみ町営バス「吹上温泉線」(1 日 3 便)\n- 周辺:十勝岳温泉(車 5 分)、望岳台(十勝岳展望・車 15 分)\n- 2026-04 人工查核(町営公式サイト)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "空知郡",
    municipality_ja: "上富良野町",
    lg_code: "01460",
    area_types: ["onsen_town", "mountain"],
    lat: 43.4547,
    lon: 142.6569,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 0,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      official: "https://kamifurano-hokkaido.com/fukiage-hakuginsou/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E5%90%B9%E4%B8%8A%E6%B8%A9%E6%B3%89_(%E5%8C%97%E6%B5%B7%E9%81%93)",
    },
    tags: ["fukiage", "town_operated", "mixed_bath", "budget", "tokachidake"],
    source: "manual",
  },
  {
    slug: "hokkaido-asahidake-yukomanso",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "旭岳温泉 湧駒荘",
    title_ja: "旭岳温泉 湧駒荘",
    romaji: "Asahidake Onsen Yukomanso",
    summary_zh:
      "北海道最高峰 旭岳(2291m)登山口、大雪山国立公園の秘湯。「日本秘湯を守る会」加盟、7 種源泉を異なる 6 つの浴場で楽しめる。1957 年創業の旭岳温泉老舗。",
    content_md:
      "- 地址:上川郡東川町勇駒別旭岳温泉(JR 旭川駅→バス 90 分 or 車 60 分)\n- 立地:大雪山国立公園旭岳山麓、旭岳ロープウェイ姉沼駅徒歩 3 分\n- 溫泉:7 種源泉(カルシウム硫酸塩泉中心)を 6 浴場で使い分け、源泉かけ流し\n- 規模:36 室\n- 開業:1957 年(昭和 32)\n- 料金:1 泊 2 食 平日 ¥18,000〜 / 旺季 ¥35,000〜\n- 認定:日本秘湯を守る会 加盟(全国 180 軒の秘湯網)\n- 食事:大雪山麓の山菜 + 旬魚 + 北海道和牛、料理評価高い\n- アクセス:旭川駅からいで湯号バス(通年 1 日 4 便)\n- 周辺:旭岳ロープウェイ(3-10 月 高山植物・紅葉、11-5 月 パウダースキー)、忠別湖\n- 2026-04 人工查核(官網 + 日本秘湯を守る会サイト + Wikipedia 旭岳温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川郡",
    municipality_ja: "東川町",
    lg_code: "01458",
    area_types: ["onsen_town", "mountain"],
    lat: 43.6797,
    lon: 142.8433,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      official: "https://www.yukoman.com/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E6%97%AD%E5%B2%B3%E6%B8%A9%E6%B3%89",
    },
    tags: ["asahidake", "since_1957", "hidden_spring_guild", "7_sources", "daisetsuzan"],
    source: "manual",
  },
  {
    slug: "hokkaido-tokachidake-ryounkaku",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "十勝岳温泉 凌雲閣",
    title_ja: "十勝岳温泉 凌雲閣",
    romaji: "Tokachidake Onsen Ryounkaku",
    summary_zh:
      "北海道最高標高 1280m の温泉宿、1963 年創業(昭和 38)。十勝岳山腹からの眺望と豊富な 3 種源泉が特徴。露天「雲海の湯」は夜間天体観測スポットとしても有名。",
    content_md:
      "- 地址:空知郡上富良野町十勝岳温泉(JR 上富良野駅→車 35 分、冬期道路除雪あり通年営業)\n- 立地:十勝岳中腹・標高 1280m(北海道で最も高所の温泉宿)\n- 溫泉:3 種源泉(含鉄・硫黄・カルシウム)、赤褐色湯、源泉かけ流し\n- 規模:32 室(全室禁煙 2021 改装)\n- 開業:1963 年(昭和 38)、十勝岳山岳観光のパイオニア\n- 料金:1 泊 2 食 平日 ¥14,000〜 / 旺季 ¥28,000〜\n- 名物:雲海の湯(男女別露天・標高 1280m から雲海眺望)、夜 星空観察\n- アクセス:上富良野駅より季節運行バス or タクシー 15 分\n- 周辺:十勝岳望岳台(車 10 分)、吹上露天の湯(車 5 分)、安政火口ハイキング\n- 特色:標高高く梅雨なし・湿度低い・通年登山&スキー拠点\n- 2026-04 人工查核(官網 + Wikipedia 十勝岳温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "空知郡",
    municipality_ja: "上富良野町",
    lg_code: "01460",
    area_types: ["onsen_town", "mountain"],
    lat: 43.4286,
    lon: 142.6694,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E5%8D%81%E5%8B%9D%E5%B2%B3%E6%B8%A9%E6%B3%89",
    },
    tags: ["tokachidake", "since_1963", "highest_altitude", "iron_spring", "stargazing"],
    source: "manual",
  },
  {
    slug: "hokkaido-nigorikawa-shineikan",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "濁川温泉 新栄館",
    title_ja: "濁川温泉 新栄館",
    romaji: "Nigorikawa Onsen Shineikan",
    summary_zh:
      "1868 年(明治元)創業、日本に数軒しか残らない茅葺屋根の湯治場。混浴内湯は板で仕切っただけの原初形式、地元民が自慢する「北海道遺産クラス」の秘湯。",
    content_md:
      "- 地址:茅部郡森町濁川(JR 森駅→車 30 分、新千歲空港から車 2 時間)\n- 立地:濁川カルデラ内、農村地帯の湯治場\n- 溫泉:ナトリウム・カルシウム塩化物泉(1868 発見)、源泉かけ流し 100%\n- 規模:8 室(湯治場型)、茅葺屋根の古民家旅館\n- 開業:1868 年(明治元)、150 年超の伝統\n- 料金:1 泊 2 食 ¥10,500〜(シンプル・安価)、素泊 ¥6,000〜\n- 名物:混浴内湯(木造湯屋・板仕切りのみ)、館内の古道具・古民具展示\n- 食事:地元食材の家庭料理中心、華美なし・本物志向\n- アクセス:JR 函館本線 森駅(特急停車)からタクシー 30 分\n- 周辺:駒ヶ岳(日本の山岳信仰地)、大沼国定公園(車 40 分)\n- 2026-04 人工查核(森町観光協会 + 個別旅館記事)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "茅部郡",
    municipality_ja: "森町",
    lg_code: "01345",
    area_types: ["onsen_town", "rural"],
    lat: 42.1353,
    lon: 140.5181,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["nigorikawa", "since_1868", "thatched_roof", "toji_retreat", "heritage_inn"],
    source: "manual",
  },
  {
    slug: "hokkaido-rausu-daiichi-hotel",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "羅臼温泉 第一ホテル",
    title_ja: "羅臼温泉 第一ホテル",
    romaji: "Rausu Onsen Daiichi Hotel",
    summary_zh:
      "世界自然遺産知床半島・太平洋側の羅臼温泉唯一の中規模旅館。1966 年開業、知床峠越え直前の拠点。名物は露天からの羅臼岳眺望 + 近海シャケ・キンキ・羅臼昆布の食卓。",
    content_md:
      "- 地址:目梨郡羅臼町湯ノ沢町(女満別空港から車 2 時間 30 分、中標津空港から 1 時間)\n- 立地:知床半島太平洋側・羅臼岳(1661m)東麓、知床峠入口\n- 溫泉:単純硫黄泉(源泉 70°C)、内湯 + 露天、羅臼岳展望\n- 規模:31 室\n- 開業:1966 年(昭和 41)、知床観光最初期から営業\n- 料金:1 泊 2 食 平日 ¥14,000〜 / 旺季 ¥25,000〜(冬は流氷船パックあり)\n- 名物:羅臼昆布しゃぶ・キンキ煮付・シャケ塩焼、羅臼産海産物の会席\n- 周辺:熊の湯(無料混浴露天・徒歩 10 分)、知床峠展望台(車 30 分)、羅臼ビジターセンター\n- アクティビティ:ホエールウォッチング(夏)、流氷クルーズ(1-3 月)、羅臼岳登山(7-9 月)\n- アクセス:中標津空港からウトピアバス 1 日 4 便、冬期は車・送迎推奨\n- 2026-04 人工查核(官網 + Wikipedia 羅臼温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "目梨郡",
    municipality_ja: "羅臼町",
    lg_code: "01694",
    area_types: ["onsen_town", "coastal"],
    lat: 44.0206,
    lon: 145.1842,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E7%BE%85%E8%87%BC%E6%B8%A9%E6%B3%89",
    },
    tags: ["rausu", "since_1966", "shiretoko", "whale_watching", "drift_ice"],
    source: "manual",
  },
  {
    slug: "hokkaido-shikabe-royal-hotel",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "鹿部ロイヤルホテル",
    title_ja: "鹿部ロイヤルホテル",
    romaji: "Shikabe Royal Hotel",
    summary_zh:
      "函館市 30 分圏の鹿部温泉、噴出する間歇泉(鹿部間歇泉公園・徒歩 5 分)で有名な町。1973 年開業の中規模リゾートホテル、温泉プール + 露天 + 大駒ヶ岳眺望。",
    content_md:
      "- 地址:茅部郡鹿部町本別 426(JR 鹿部駅→車 10 分、新函館北斗駅→車 40 分)\n- 立地:駒ヶ岳北麓・太平洋望・鹿部温泉地区\n- 溫泉:ナトリウム塩化物泉、源泉 96°C の高温泉、大浴場 + 露天\n- 施設:温泉プール(通年・全長 25m)、ゴルフ場(27 ホール・隣接)\n- 規模:142 室(ツイン中心・ファミリー向け広め)\n- 開業:1973 年(昭和 48)、函館リゾート拠点型の老舗\n- 料金:1 泊 2 食 平日 ¥13,000〜 / 旺季 ¥22,000〜\n- 名物:鹿部たらこ・駒ヶ岳黒毛和牛・噴出温泉むし料理\n- 周辺:鹿部間歇泉(徒歩 5 分・12 分毎 15m 噴出)、道の駅しかべ(徒歩 8 分)\n- アクセス:新函館北斗駅からリゾートシャトル(予約制)、大沼公園 車 30 分\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "茅部郡",
    municipality_ja: "鹿部町",
    lg_code: "01343",
    area_types: ["onsen_town", "coastal"],
    lat: 42.0358,
    lon: 140.7958,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["shikabe", "since_1973", "geyser", "hakodate_area", "onsen_pool"],
    source: "manual",
  },
  {
    slug: "hokkaido-toyotomi-kawashima-ryokan",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "豊富温泉 川島旅館",
    title_ja: "豊富温泉 川島旅館",
    romaji: "Toyotomi Onsen Kawashima Ryokan",
    summary_zh:
      "世界的にも珍しい「重油臭」の石油含有泉、アトピー性皮膚炎・乾癬の湯治場として全国から長期滞在者が集まる。1926 年創業の温泉街最古参、100 年近い湯治伝統。",
    content_md:
      "- 地址:天塩郡豊富町豊富温泉(JR 豊富駅→バス 10 分、稚内空港から車 50 分)\n- 立地:日本最北の温泉街、サロベツ原野の玄関\n- 溫泉:ナトリウム塩化物泉に石油・天然ガス成分(世界的に類を見ない特殊泉質)\n- 医療評価:アトピー性皮膚炎・乾癬・掌蹠膿疱症に有効性報告、皮膚科医の紹介で湯治来訪あり\n- 規模:19 室(湯治滞在型 + 短期観光両対応)\n- 開業:1926 年(大正 15)、豊富温泉で最古参、地元名家 川島家\n- 料金:1 泊 2 食 平日 ¥12,000〜、湯治連泊割引あり(7 泊で 10% 割)\n- 食事:地元産ホタテ・タコしゃぶ・じゃがいも会席\n- 周辺:サロベツ原野(日本最大湿原)、宗谷岬(日本最北端・車 1 時間 30 分)\n- 注意:浴槽に石油膜が浮く・独特の重油臭あり、これが効能の源\n- 2026-04 人工查核(官網 + Wikipedia 豊富温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "天塩郡",
    municipality_ja: "豊富町",
    lg_code: "01516",
    area_types: ["onsen_town", "rural"],
    lat: 45.1156,
    lon: 141.7608,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://www.toyotomi-onsen.com/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E8%B1%8A%E5%AF%8C%E6%B8%A9%E6%B3%89",
    },
    tags: ["toyotomi", "since_1926", "oil_spring", "atopy_retreat", "northernmost_onsen"],
    source: "manual",
  },
  {
    slug: "hokkaido-karurusu-suzuki-ryokan",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "カルルス温泉 鈴木旅館",
    title_ja: "カルルス温泉 鈴木旅館",
    romaji: "Karurusu Onsen Suzuki Ryokan",
    summary_zh:
      "登別温泉の奥座敷、カルルス温泉 1899 年(明治 32)創業の老舗。国民保養温泉地第 1 号指定(1957 年)、チェコのカルロヴィ・ヴァリに泉質が似ることから名付けられた。",
    content_md:
      "- 地址:登別市カルルス町(登別温泉街から車 10 分、登別駅から車 30 分)\n- 立地:登別温泉西 8km・標高 360m の山間・閑静な湯治場\n- 溫泉:単純温泉 pH 6.8(低刺激・万人向け)、源泉かけ流し\n- 泉名由来:チェコ カルロヴィ・ヴァリ温泉に泉質が似るため「カルルス」(カールスバッドの独読み)\n- 規模:14 室(湯治型・家族経営)\n- 開業:1899 年(明治 32)、鈴木鉄三郎が発見・開湯\n- 指定:1957 年 国民保養温泉地 第 1 号(日本で最初の指定温泉地の一つ)\n- 料金:1 泊 2 食 平日 ¥12,000〜 / 湯治連泊割引あり\n- 食事:地元山菜・川魚・北海道和牛、素朴な湯治料理\n- 周辺:登別温泉(車 10 分)、登別伊達時代村(車 15 分)、来馬岳登山口(徒歩 20 分)\n- 2026-04 人工查核(官網 + Wikipedia カルルス温泉)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "登別市",
    lg_code: "01230",
    area_types: ["onsen_town", "mountain"],
    lat: 42.4967,
    lon: 140.9942,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://suzukiryokan.com/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E3%82%AB%E3%83%AB%E3%83%AB%E3%82%B9%E6%B8%A9%E6%B3%89",
    },
    tags: ["karurusu", "since_1899", "national_spa_no1", "noboribetsu_area", "toji"],
    source: "manual",
  },

  // ── luxury_hotel (9 筆) ──────────────────────────────
  {
    slug: "hokkaido-hoshino-resort-tomamu",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "星野リゾート トマム(ザ・タワー + リゾナーレトマム)",
    title_ja: "星野リゾート トマム",
    romaji: "Hoshino Resort Tomamu",
    summary_zh:
      "北海道最大級のリゾート施設、占冠村に位置。1983 年アルファリゾートトマム開業 → 2004 年星野リゾート買收。2006 年開始の「雲海テラス」(5-10 月、標高 1,088m)が SNS で爆発的人気、夏冬二季営業。",
    content_md:
      "- 地址:勇払郡占冠村中トマム(JR「トマム」駅直結 or 新千歲空港から車 90 分)\n- 立地:占冠村、トマム山(標高 1,239m)山麓、175ha 超大敷地\n- 構成:ザ・タワー(535 室、1983 創業系)+ リゾナーレトマム(200 室全スイート、2007 リブランド)\n- 歷史:1983 年アルファリゾートトマム開業 → 2004 年星野リゾート買収 → 2006 年雲海テラス開業\n- 名物:雲海テラス(5 月中-10 月中、標高 1,088m ゴンドラ 13 分、朝 5-8 時)\n- 夏アクティビティ:ファームエリア・水の教会・ミナミナビーチ(室内人造ビーチ)\n- 冬:トマム スキー場 29 コース・アイスビレッジ\n- 料金:1 泊素泊まり 平日 ¥20,000〜 / 夏季雲海シーズン ¥45,000〜\n- 食事:ブッフェダイニング「hal」、星野系和食「紅藤」\n- 2026-04 人工查核(官網 + Wikipedia 星野リゾート)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "勇払郡",
    municipality_ja: "占冠村",
    lg_code: "01463",
    area_types: ["mountain", "rural"],
    lat: 43.0786,
    lon: 142.6664,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 120,
    closed_days: [],
    external_urls: {
      official: "https://www.snowtomamu.jp/summer/",
    },
    tags: ["hoshino_resort", "tomamu", "unkai_terrace", "since_1983", "ski_summer"],
    source: "manual",
  },
  {
    slug: "hokkaido-omo3-sapporo-susukino",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "OMO3 札幌すすきの by 星野リゾート",
    title_ja: "OMO3 札幌すすきの by 星野リゾート",
    romaji: "OMO3 Sapporo Susukino",
    summary_zh:
      "星野リゾート「OMO」ブランドの札幌版、2022 年 1 月開業。すすきの中心立地で 24H フロント、夜の街遊びと朝のラーメン横丁に直結。全 200 室で比較的手頃な都市観光型。",
    content_md:
      "- 地址:札幌市中央区南 5 条西 1 丁目 22-2(地下鉄南北線「すすきの」駅徒歩 1 分)\n- 立地:すすきの中心、狸小路・ラーメン横丁・二条市場徒歩圏\n- 規模:200 室、ダブル/ツイン中心、和モダン内装\n- 開業:2022 年 1 月 20 日、星野リゾート運営\n- 料金:1 泊素泊まり 平日 ¥10,000〜 / 週末・雪祭時 ¥25,000〜\n- OMO コンセプト:「ご近所アクティビティ」館内にすすきのネオンマップ、ご近所専門家と夜散歩ツアー\n- 食事:朝食ビュッフェ北海道食材 + 館内カフェ「OMO Cafe & Bar」\n- アクセス:新千歲から快速エアポート+地下鉄 50 分\n- 周辺:狸小路商店街(徒歩 3 分)・札幌ラーメン横丁(徒歩 3 分)\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0553,
    lon: 141.3542,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://hoshinoresorts.com/ja/hotels/omo3sapporosusukino/",
    },
    tags: ["hoshino_resort", "omo_brand", "susukino", "opened_2022", "city_stay"],
    source: "manual",
  },
  {
    slug: "hokkaido-hilton-niseko-village",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ヒルトンニセコビレッジ",
    title_ja: "ヒルトンニセコビレッジ",
    romaji: "Hilton Niseko Village",
    summary_zh:
      "ニセコビレッジスキーリゾートのセンターホテル、2008 年ヒルトンブランド化。ゲレンデ ski-in/ski-out 可能、羊蹄山(エゾ富士)正面眺望。冬は世界各国スキーヤー集結、夏は湖畔ゴルフと登山拠点。",
    content_md:
      "- 地址:虻田郡ニセコ町東山温泉(JR ニセコ駅から車 15 分 or シャトル)\n- 立地:ニセコビレッジスキー場ゲレンデ直結、羊蹄山眺望\n- 規模:506 室、ニセコエリア最大級\n- 開業:1983 年 ヒルトン系前身 → 2008 年ヒルトンブランド化\n- 料金:1 泊素泊まり 夏季 ¥18,000〜 / 冬ピーク ¥80,000〜(冬价格夏 3-5 倍)\n- ski-in/out:ニセコビレッジゴンドラ直接アクセス\n- 夏:ゴルフ(ニセコビレッジ GC 2 コース)、ラフティング、ホーストレック\n- 冬:ニセコユナイテッド 4 リゾート共通券対応\n- レストラン:和食「雪月花」、鉄板焼「弁慶」、ビュッフェ\n- 送迎:ニセコバス 新千歲空港直通便(約 3 時間)\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "ニセコ町",
    lg_code: "01395",
    area_types: ["mountain", "onsen_town"],
    lat: 42.8414,
    lon: 140.6892,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 5,
    booking_window_days: 120,
    closed_days: [],
    external_urls: {
      official: "https://www.hiltonnisekovillage.jp/",
    },
    tags: ["niseko", "hilton", "ski_in_out", "yotei_view", "international_ski"],
    source: "manual",
  },
  {
    slug: "hokkaido-park-hyatt-niseko-hanazono",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "パーク ハイアット ニセコ HANAZONO",
    title_ja: "パーク ハイアット ニセコ HANAZONO",
    romaji: "Park Hyatt Niseko HANAZONO",
    summary_zh:
      "ニセコ HANAZONO リゾート内の最高級ホテル,2020 年 1 月開業。ニセコユナイテッド 4 リゾートの 1 つ HANAZONO ゲレンデ直結。羊蹄山全景、日本のハイアット最上位クラス。",
    content_md:
      "- 地址:虻田郡倶知安町岩尾別 328-36(JR 倶知安駅から車 20 分 or シャトル)\n- 立地:ニセコ HANAZONO スキー場直結、羊蹄山眺望\n- 規模:100 室 + 15 棟ヴィラ、全室 70m² 以上、ブランドレジデンス併設\n- 開業:2020 年 1 月 20 日、ハイアット最高級ブランド\n- 料金:1 泊素泊まり 夏季 ¥40,000〜 / 冬ピーク ¥150,000〜\n- スキー:HANAZONO ski-in/out + ユナイテッド 4 リゾート共通リフト券\n- 夏:ゴルフ、ジップライン、ホーストレック、NAC ラフティング\n- レストラン:鉄板焼・懐石・洋食ダイニング 計 5 店舗\n- スパ:パークハイアット スパ(12 treatment room)\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "倶知安町",
    lg_code: "01400",
    area_types: ["mountain"],
    lat: 42.8708,
    lon: 140.7144,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 5,
    booking_window_days: 180,
    closed_days: [],
    external_urls: {
      official: "https://www.hyatt.com/ja-JP/hotel/japan/park-hyatt-niseko-hanazono/ckjph",
    },
    tags: ["niseko", "hanazono", "park_hyatt", "opened_2020", "top_luxury"],
    source: "manual",
  },
  {
    slug: "hokkaido-rusutsu-resort",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ルスツリゾート",
    title_ja: "ルスツリゾート",
    romaji: "Rusutsu Resort",
    summary_zh:
      "留寿都村の総合リゾート、1973 年開業。37 コース/18 リフトで北海道最大級のスキー場、夏は遊園地(ジェットコースター 60)併設で家族向け。ホテル・コンドミニアム 3 棟構成。",
    content_md:
      "- 地址:虻田郡留寿都村泉川 13 番地(JR 洞爺駅から車 45 分 or 新千歲空港シャトル 2 時間)\n- 立地:西山・東山・イゾラの 3 山、標高 994m\n- 規模:ホテル棟(ノースウィング/サウスウィング/タワー)計 1,030 室\n- 開業:1973 年、加森観光運営\n- 料金:1 泊素泊まり 夏季 ¥14,000〜 / 冬ピーク ¥60,000〜\n- スキー:37 コース(パウダースノー定評)・ナイター・2 ゴンドラ・18 リフト\n- 夏:ルスツ遊園地(日本最多級 60 アトラクション)、4 ゴルフ場\n- 食事:レストラン 20 店舗以上(バイキング・寿司・ステーキ)\n- 家族特色:遊園地無料入場券付プラン、キッズスクール完備\n- アクセス:新千歲空港直行バス 2 時間(冬期は増便)\n- 2026-04 人工查核(官網 + Wikipedia ルスツリゾート)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "留寿都村",
    lg_code: "01397",
    area_types: ["mountain", "rural"],
    lat: 42.7381,
    lon: 140.8736,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 120,
    closed_days: [],
    external_urls: {
      official: "https://rusutsu.com/",
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E3%83%AB%E3%82%B9%E3%83%84%E3%83%AA%E3%82%BE%E3%83%BC%E3%83%88",
    },
    tags: ["rusutsu", "since_1973", "largest_ski", "amusement_park", "family"],
    source: "manual",
  },
  {
    slug: "hokkaido-lavista-hakodate-bay",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ラビスタ函館ベイ",
    title_ja: "ラビスタ函館ベイ",
    romaji: "La Vista Hakodate Bay",
    summary_zh:
      "函館ベイエリアの代表、2009 年開業。共立メンテナンス運営。朝食部門じゃらんアワード「泊まってよかった宿」北海道部門 朝食 1 位 を連年受賞(海鮮勝手丼が名物)。屋上天然温泉展望大浴場で函館山夜景。",
    content_md:
      "- 地址:函館市豊川町 12-6(JR 函館駅徒歩 15 分 or 市電「魚市場通」停留所徒歩 3 分)\n- 立地:金森赤レンガ倉庫群徒歩 3 分、函館山眺望\n- 規模:335 室、大型シティホテル\n- 開業:2009 年 3 月、共立メンテナンス(ドーミーイン系列高級版)\n- 料金:1 泊朝食付 平日 ¥16,000〜 / 旺季 ¥35,000〜\n- 朝食:海鮮勝手丼ビュッフェ(いくら/ウニ/マグロ/イカ/蟹トッピング自由)、じゃらん朝食 1 位連年\n- 温泉:13F 屋上展望大浴場、函館山+夜景眺望、深夜まで OPEN\n- 夜鳴きそば:22:30-翌 0:30 無料(ドーミーイン系伝統)\n- 周辺:金森赤レンガ(徒歩 3 分)、函館ベイ(徒歩 5 分)、朝市(徒歩 10 分)\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["urban", "coastal"],
    lat: 41.7747,
    lon: 140.7144,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://www.hotespa.net/hotels/lahakodate/",
    },
    tags: ["hakodate", "lavista", "seafood_breakfast", "kanemori_nearby", "kyoritsu"],
    source: "manual",
  },
  {
    slug: "hokkaido-windsor-toya-resort",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ザ・ウィンザーホテル洞爺リゾート&スパ",
    title_ja: "ザ・ウィンザーホテル洞爺リゾート&スパ",
    romaji: "The Windsor Hotel Toya Resort & Spa",
    summary_zh:
      "2008 年 G8 洞爺湖サミット開催地、標高 625m ポロモイ山の山頂立地。洞爺湖と噴火湾を 360°眺望、ミシュラン星付き 2 軒のレストラン併設。国内屈指の山頂リゾート。",
    content_md:
      "- 地址:虻田郡洞爺湖町清水 336(JR 洞爺駅から無料送迎バス 30 分)\n- 立地:ポロモイ山山頂(標高 625m)、洞爺湖 + 噴火湾 + 有珠山 360°眺望\n- 規模:379 室、山頂リゾートホテル\n- 開業:1993 年エプソンミシガンホテル → 2002 年再開、2008 年 G8 洞爺湖サミット会場\n- 料金:1 泊素泊まり 平日 ¥30,000〜 / サミット記念期 ¥80,000〜\n- レストラン:ミシュランガイド北海道掲載「ミシェル・ブラス トーヤ ジャポン」「三國清三 Michel Bras」「和食 山里」\n- スパ:「ウィンザー スパ」タラソテラピー、サウナ、屋内プール\n- ゴルフ:ザ・ウィンザー GC 36H(ニクラス・ノーマン設計)\n- アクセス:新千歲空港から車 1.5 時間、無料送迎(要予約)\n- 2026-04 人工查核(官網 + Wikipedia G8 洞爺湖サミット)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "洞爺湖町",
    lg_code: "01584",
    area_types: ["mountain", "onsen_town"],
    lat: 42.6258,
    lon: 140.7722,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 5,
    booking_window_days: 120,
    closed_days: [],
    external_urls: {
      official: "https://www.windsor-hotels.co.jp/ja/",
    },
    tags: ["toya", "g8_summit_2008", "mountain_top", "michelin", "360_view"],
    source: "manual",
  },
  {
    slug: "hokkaido-omo5-otaru",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "星野リゾート OMO5 小樽 by 星野集團",
    title_ja: "OMO5 小樽 by 星野リゾート",
    romaji: "OMO5 Otaru by Hoshino Resorts",
    summary_zh:
      "2022 年 1 月開業の小樽唯一の星野ブランドホテル。小樽運河徒歩 10 分、旧三菱銀行支店(1922 築の歴史建築)を活用した全 125 室。地元「ご近所さん」を巻き込む OMO スタイル.",
    content_md:
      "- 地址:小樽市色内 1-6-31(JR 小樽駅徒歩 8 分 / 小樽運河徒歩 10 分)\n- 立地:小樽運河北岸・北のウォール街(旧金融街)・歴史建築地区\n- 建築:旧三菱銀行小樽支店(1922 年築・国の登録有形文化財)を一部保存転用した新築ホテル\n- 規模:125 室(ツイン中心 + ファミリー寝台ルーム)\n- 開業:2022 年 1 月 14 日(星野リゾートが北海道で 7 館目)\n- 料金:1 泊朝食 平日 ¥14,000〜 / 旺季 ¥28,000〜(部屋単位料金)\n- OMO 特徴:ご近所ガイド(OMO レンジャー)による街歩きツアー・寿司屋案内・夜の運河ツアー\n- 食事:1F レストランで北海道朝食ビュッフェ・夜は近隣寿司屋紹介\n- 周辺:小樽運河(徒歩 10 分)、北一硝子・オルゴール堂(徒歩 15 分)、鱗友朝市(車 10 分)\n- アクセス:新千歲空港→JR 快速エアポート 60 分+徒歩 8 分\n- 2026-04 人工查核(官網 + 星野リゾート公式)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "小樽市",
    lg_code: "01203",
    area_types: ["urban", "coastal"],
    lat: 43.1953,
    lon: 141.0058,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      official: "https://hoshinoresorts.com/ja/hotels/omo5otaru/",
    },
    tags: ["otaru", "hoshino", "omo", "opened_2022", "heritage_building"],
    source: "manual",
  },
  {
    slug: "hokkaido-shiretoko-kitakobushi",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "知床 第一ホテル 北こぶし",
    title_ja: "知床 第一ホテル 北こぶし",
    romaji: "Shiretoko Daiichi Hotel Kitakobushi",
    summary_zh:
      "世界自然遺産ウトロ温泉の最高級旅館、1960 年創業・2016 年全面改装。オホーツク海流氷(1-3 月)を一望できる客室 + 露天、知床観光船乗り場徒歩 3 分の絶好立地。",
    content_md:
      "- 地址:斜里郡斜里町ウトロ東 172(女満別空港から車 2 時間、釧路空港から 4 時間)\n- 立地:ウトロ温泉街・オホーツク海直接面する絶景ホテル\n- 溫泉:ナトリウム塩化物泉(源泉 50°C)、最上階 7F 展望露天(流氷眺望)\n- 規模:175 室(全室オーシャンビュー)\n- 開業:1960 年(昭和 35)、2016 年「KITAKOBUSHI」ブランドで全面改装\n- 料金:1 泊 2 食 平日 ¥22,000〜 / 旺季 ¥45,000〜(冬の流氷シーズン割増)\n- 名物:流氷眺望露天(1-3 月)、ウトロ港の夕陽展望、会席料理(羅臼昆布・時鮭・ウニ・ホタテ)\n- 施設:BOOK CAFÉ・サウナ・子ども向けキッズルーム\n- 周辺:道の駅うとろ・シリエトク(徒歩 5 分)、知床観光船おーろら乗り場(徒歩 3 分)、オシンコシンの滝(車 15 分)\n- シーズン:4-11 月 知床遊覧・ヒグマウォッチング、1-3 月 流氷クルーズ・知床五湖氷上散策\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "斜里郡",
    municipality_ja: "斜里町",
    lg_code: "01545",
    area_types: ["onsen_town", "coastal"],
    lat: 44.0725,
    lon: 144.9797,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 120,
    closed_days: [],
    external_urls: {
      official: "https://www.shiretoko.co.jp/",
    },
    tags: ["shiretoko", "since_1960", "utoro", "drift_ice_view", "renovated_2016"],
    source: "manual",
  },

  // ── budget_hotel_chain (8 筆) ──────────────────────────────
  {
    slug: "hokkaido-jr-tower-nikko-sapporo",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "JR タワーホテル日航札幌",
    title_ja: "JR タワーホテル日航札幌",
    romaji: "JR Tower Hotel Nikko Sapporo",
    summary_zh:
      "JR 札幌駅直結の最高層ホテル、22-34F(高さ 173m)。2003 年開業、ホテルニッコーブランド。駅直結で新千歲空港から快速 37 分到着後すぐ。35F 展望室 T38 は外部客でも利用可(有料)。",
    content_md:
      "- 地址:札幌市中央区北 5 条西 2 丁目 5 番地(JR 札幌駅南口直結)\n- 立地:JR 札幌駅南口徒歩 0 分、地下直結\n- 規模:350 室、22-34F\n- 開業:2003 年 5 月 JR 札幌駅ビル「ステラプレイス」と同時開業\n- 料金:1 泊素泊まり 平日 ¥20,000〜 / 旺季 ¥45,000〜\n- 22F スパ「スカイ」:宿泊客専用、札幌夜景眺望\n- 35F 展望室 T38(¥740):外部客利用可、360°眺望\n- アクセス:新千歲空港→JR 快速エアポート 37 分→直結徒歩 2 分\n- 周辺:大丸・エスタ・ステラプレイス・アピア すべて駅ビル内\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0686,
    lon: 141.3506,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 4,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "https://www.jrhotels.co.jp/tower/",
    },
    tags: ["sapporo_station", "station_connected", "nikko", "opened_2003", "high_floor"],
    source: "manual",
  },
  {
    slug: "hokkaido-jr-inn-sapporo",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "JR イン 札幌",
    title_ja: "JR イン札幌",
    romaji: "JR Inn Sapporo",
    summary_zh:
      "JR 札幌駅北口徒歩 2 分、JR 北海道 ホテル系列のビジネスホテル。日航より手頃だが駅徒歩圏の立地メリットはそのまま。展望大浴場(14F)は女性専用でセキュリティ重視。",
    content_md:
      "- 地址:札幌市北区北 8 条西 4 丁目 5 番地(JR 札幌駅北口徒歩 2 分)\n- 立地:JR 札幌駅北口徒歩 2 分、大学(北海道大学)近辺\n- 規模:265 室、14F シングル中心\n- 開業:2008 年、JR イン全国チェーン北海道展開第 1 号\n- 料金:1 泊素泊まり 平日 ¥8,500〜 / 旺季 ¥18,000〜\n- 14F 展望大浴場(女性専用):夜景眺望、男性用は別フロア大浴場\n- 朝食:北海道食材ビュッフェ ¥1,200(別料金)\n- アクセス:新千歲空港→JR 37 分→徒歩 2 分\n- 同系列:JR イン函館・旭川・帯広・網走・千歲 等道内展開\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0697,
    lon: 141.3489,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      official: "https://www.jr-inn.jp/sapporo/",
    },
    tags: ["sapporo_station", "jr_inn_chain", "women_only_onsen", "business_hotel"],
    source: "manual",
  },
  {
    slug: "hokkaido-dormy-inn-sapporo-annex",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "ドーミーイン PREMIUM 札幌 ANNEX",
    title_ja: "ドーミーイン PREMIUM 札幌 ANNEX",
    romaji: "Dormy Inn Premium Sapporo Annex",
    summary_zh:
      "共立メンテナンス運営ドーミーイン系、札幌市内に 3 館。ANNEX は 2017 年開業の新館。屋上展望大浴場 + 無料夜鳴きそば(22:30-翌 0:30)はドーミー系統の定番サービス。",
    content_md:
      "- 地址:札幌市中央区南 2 条西 6 丁目 6-2(地下鉄南北線「すすきの」駅徒歩 5 分)\n- 立地:狸小路 2 丁目交差点近辺、繁華街中心\n- 規模:204 室\n- 開業:2017 年(ドーミーイン PREMIUM 札幌 本館 2010 年の姉妹館)\n- 料金:1 泊素泊まり 平日 ¥9,500〜 / 旺季 ¥22,000〜\n- 温泉:最上階大浴場「火の神の湯」+ 露天(人工炭酸泉)\n- 夜鳴きそば:22:30-翌 0:30 無料提供(醤油半玉サイズ)\n- 朝食:北海道食材ビュッフェ ¥2,200(鮭親子丼・イクラ丼)\n- アクセス:新千歲空港→地下鉄「すすきの」→徒歩 5 分\n- 周辺:狸小路徒歩 1 分、ラーメン横丁徒歩 3 分\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0569,
    lon: 141.3533,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["susukino", "dormy_inn", "free_ramen_night", "rooftop_onsen", "kyoritsu"],
    source: "manual",
  },
  {
    slug: "hokkaido-monterey-sapporo",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "ホテルモントレ札幌",
    title_ja: "ホテルモントレ札幌",
    romaji: "Hotel Monterey Sapporo",
    summary_zh:
      "ヨーロッパ風(英国ビクトリア朝)のクラシック内装が特徴、1998 年開業。モントレ系列は各都市で欧州都市をテーマにし、札幌はロンドンをイメージ。JR 札幌駅徒歩 7 分、大通公園へもすぐ。",
    content_md:
      "- 地址:札幌市中央区北 4 条東 1 丁目 3 番地(JR 札幌駅南口徒歩 7 分 / 地下鉄「さっぽろ」駅徒歩 3 分)\n- 立地:JR 札幌駅・大通公園の中間、創成川近辺\n- 規模:250 室\n- 開業:1998 年、マルイト系列(本社大阪)\n- 料金:1 泊素泊まり 平日 ¥9,000〜 / 旺季 ¥20,000〜\n- 内装:英国ビクトリア調、ステンドグラス、アンティーク家具\n- 朝食:イギリス風朝食 ¥1,900 (スコーン・クランペット)\n- 2026-04 リニューアル予定:全館 Wi-Fi 無料、近年まだ目立った改修なし\n- アクセス:新千歲→JR 37 分→徒歩 7 分 / 地下鉄 3 分\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0658,
    lon: 141.3569,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 45,
    closed_days: [],
    external_urls: {
      official: "https://www.hotelmonterey.co.jp/sapporo/",
    },
    tags: ["sapporo", "european_style", "victorian", "monterey", "opened_1998"],
    source: "manual",
  },
  {
    slug: "hokkaido-richmond-sapporo-odori",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "リッチモンドホテル札幌大通",
    title_ja: "リッチモンドホテル札幌大通",
    romaji: "Richmond Hotel Sapporo Odori",
    summary_zh:
      "大通公園徒歩 2 分、狸小路徒歩 5 分の好立地。RNB ホテルズ運営、全国チェーンで「お客さまが選ぶ 人気のホテル 楽天トラベル 1 位」を多数回受賞。価格帯とサービスのバランスが良い定番。",
    content_md:
      "- 地址:札幌市中央区南 2 条西 4 丁目 2 番地(地下鉄「大通」駅徒歩 3 分)\n- 立地:大通公園徒歩 2 分、狸小路徒歩 5 分\n- 規模:232 室、シングル中心\n- 開業:2007 年、RNB ホテルズ(ロイヤルホテル系列)\n- 料金:1 泊素泊まり 平日 ¥8,000〜 / 旺季 ¥18,000〜\n- 受賞:楽天トラベル アワード上位常連(国内ホテル部門)\n- 朝食:道産食材ビュッフェ ¥1,600\n- 館内:コインランドリー・電子レンジ・製氷機\n- アクセス:新千歲→JR 札幌→地下鉄 1 駅→徒歩 3 分\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0589,
    lon: 141.3547,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["sapporo_odori", "richmond", "tanukikoji", "rakuten_top", "business_hotel"],
    source: "manual",
  },
  {
    slug: "hokkaido-jr-inn-asahikawa",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "JR イン 旭川",
    title_ja: "JR イン旭川",
    romaji: "JR Inn Asahikawa",
    summary_zh:
      "JR 旭川駅直結、2015 年新駅ビル「イオンモール旭川駅前」開業と同時オープン。旭川ラーメン村・旭山動物園バス乗降場所へも徒歩圏。道北拠点として立地最強。",
    content_md:
      "- 地址:旭川市宮下通 7 丁目 2 番 5 号(JR 旭川駅直結)\n- 立地:JR 旭川駅直結(イオンモール旭川駅前内)\n- 規模:198 室\n- 開業:2015 年 3 月、JR 北海道ホテル系列\n- 料金:1 泊素泊まり 平日 ¥7,500〜 / 旺季 ¥16,000〜\n- 最上階(13F)大浴場:女性専用階設計\n- 朝食:道産食材ビュッフェ ¥1,200\n- アクセス:新千歲空港→JR 特急 1.5 時間→駅直結\n- 周辺:旭川ラーメン村(車 10 分)、旭山動物園(バス 40 分)\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "旭川市",
    lg_code: "01204",
    area_types: ["urban"],
    lat: 43.7608,
    lon: 142.3650,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {
      official: "https://www.jr-inn.jp/asahikawa/",
    },
    tags: ["asahikawa_station", "jr_inn_chain", "station_connected", "opened_2015"],
    source: "manual",
  },
  {
    slug: "hokkaido-dormy-inn-hakodate-goryokaku",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "函館 ラビスタ五稜郭(共立メンテナンス系)",
    title_ja: "ラビスタ函館五稜郭",
    romaji: "La'gent Stay Hakodate Goryokaku",
    summary_zh:
      "五稜郭公園徒歩 7 分の中級ビジネス、2020 年開業。共立メンテナンスのドーミーイン派生ブランド「La'gent Stay」、最上階天然温泉大浴場 + 無料夜鳴きそばで人気上昇中.",
    content_md:
      "- 地址:函館市本町 25-8(市電「五稜郭公園前」徒歩 3 分 / JR 函館駅から市電 20 分)\n- 立地:五稜郭タワー・公園徒歩 7 分、市電中央バス沿線\n- 系列:共立メンテナンス La'gent Stay ブランド(ドーミーイン姉妹系)\n- 規模:261 室\n- 開業:2020 年 7 月\n- 料金:1 泊素泊 平日 ¥8,000〜 / 旺季 ¥16,000〜\n- 温泉:最上階 13F 天然温泉大浴場・露天 + サウナ(ドーミーインと同スペック)\n- 名物:無料夜鳴きそば(21:30-23:00)、無料コーヒー朝\n- 朝食ビュッフェ:函館いか刺し・海鮮丼セルフ・道南食材(¥2,200 別)\n- 周辺:五稜郭タワー(徒歩 7 分)、五稜郭公園(徒歩 5 分・桜の名所)、函館朝市(市電 15 分)\n- 2026-04 人工查核(官網 + 共立メンテナンス公式)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["urban"],
    lat: 41.7967,
    lon: 140.7567,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["hakodate", "goryokaku", "lagent_stay", "opened_2020", "top_floor_onsen"],
    source: "manual",
  },
  {
    slug: "hokkaido-comfort-hotel-chitose-airport",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "コンフォートホテル新千歲空港",
    title_ja: "コンフォートホテル新千歲空港",
    romaji: "Comfort Hotel New Chitose Airport",
    summary_zh:
      "新千歲空港連絡橋渡るだけの立地、2010 年開業。空港直結で早朝便/深夜着の拠点。Choice Hotels 系列、コンフォート標準の無料朝食(バナナ/パン/コーヒー/スープ)。",
    content_md:
      "- 地址:千歳市美々(新千歲空港直結 連絡橋徒歩 3 分)\n- 立地:新千歲空港ターミナルビル隣接、チェックイン前/後の荷物預かり便利\n- 系列:Choice Hotels International / グリーンズ(日本運営)\n- 規模:180 室(シングル中心・ツインも)\n- 開業:2010 年 3 月\n- 料金:1 泊素泊 平日 ¥8,500〜 / 旺季 ¥14,000〜\n- 無料朝食:バナナ・パン・スープ・コーヒー(¥0、セルフ式 6:30-9:30)\n- 設備:全室禁煙・PC ロビー・コインランドリー・空港シャトル不要(徒歩圏)\n- 用途:早朝 6 時便・深夜 22 時以降着・ターミナル混雑回避\n- 周辺:新千歲空港内(徒歩 3 分)、千歲アウトレットモール・レラ(車 10 分)\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "千歳市",
    lg_code: "01224",
    area_types: ["urban"],
    lat: 42.7797,
    lon: 141.6822,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["chitose", "airport_hotel", "comfort", "opened_2010", "airport_connected"],
    source: "manual",
  },

  // ── rural_minshuku (1 筆) ──────────────────────────────
  {
    slug: "hokkaido-iwaobetsu-chinohate",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "岩尾別温泉 ホテル地の涯",
    title_ja: "岩尾別温泉 ホテル地の涯",
    romaji: "Iwaobetsu Onsen Hotel Chi-no-Hate",
    summary_zh:
      "知床連山・羅臼岳登山口直近の山小屋型秘湯旅館、1964 年開業。冬季閉山のため営業 4 月下-10 月末の半年間のみ。ヒグマ生息圏内で電気柵囲い、知床の最奥で最も「地の果て」感のある宿。",
    content_md:
      "- 地址:斜里郡斜里町岩尾別(ウトロ温泉から車 15 分)\n- 立地:知床連山・羅臼岳登山口、世界自然遺産エリア内\n- 溫泉:単純硫黃温泉、大露天 + 内湯、源泉 100%掛け流し\n- 規模:35 室、山小屋型・簡樸\n- 開業:1964 年、知床・羅臼岳登山拠点として\n- 営業期間:4 月下旬-10 月下旬(11 月-4 月上旬 冬季閉鎖)\n- 料金:1 泊 2 食 平日 ¥13,000〜 / 紅葉ピーク ¥22,000〜\n- 食事:知床地元食材(ウニ・エビ・鹿肉・山菜)\n- アクセス:ウトロ温泉バスターミナルから斜里バス 20 分(夏季のみ運行)、JR 知床斜里駅から車 45 分\n- 周辺:羅臼岳登山口(徒歩 1 分)、知床五湖(車 15 分)、カムイワッカ湯の滝(車 20 分)\n- 注意:ヒグマ出没頻繁、夜間外出禁止\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "斜里郡",
    municipality_ja: "斜里町",
    lg_code: "01545",
    area_types: ["mountain", "rural", "depopulated"],
    lat: 44.0594,
    lon: 145.0989,
    season_start: "2000-04-25",
    season_end: "2000-10-25",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {
      official: "http://www.shiretoko.co.jp/",
    },
    tags: ["shiretoko", "iwaobetsu", "rausu_climb", "since_1964", "seasonal_only", "bear_zone"],
    source: "manual",
  },

  // ── capsule_hostel (4 筆) ──────────────────────────────
  {
    slug: "hokkaido-ninehours-sapporo-station",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "ナインアワーズ 札幌 ステーション",
    title_ja: "ナインアワーズ札幌ステーション",
    romaji: "Nine Hours Sapporo Station",
    summary_zh:
      "ナインアワーズ系列の札幌店、2018 年開業。JR 札幌駅北口徒歩 3 分。男女別フロア、デザイン性の高い無機質カプセルで夜行バス前後や終電後の単身泊に定番。¥4,000 前後から泊まれる。",
    content_md:
      "- 地址:札幌市北区北 8 条西 3 丁目 3(JR 札幌駅北口徒歩 3 分)\n- 立地:JR 札幌駅北口徒歩 3 分、地下街アクセス良好\n- 規模:カプセル 125 個(男 79/女 46)\n- 開業:2018 年 6 月、ナインアワーズグループ札幌進出\n- 料金:カプセル 1 泊 ¥4,200〜 / デイユース(9H)¥1,800〜\n- 設計:柴田文江氏(Ninja プロダクト デザイン)、完全無機質白カプセル\n- 設備:各カプセルにナイトライト・目覚時計・USB ポート、シャワー共用\n- 男女完全分フロア:エレベーター制限つき\n- 外国人チェックイン可、英語対応\n- アクセス:新千歲→JR 37 分→徒歩 3 分\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0694,
    lon: 141.3500,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["sapporo_station", "nine_hours", "capsule", "opened_2018", "design_hotel"],
    source: "manual",
  },
  {
    slug: "hokkaido-sapporo-international-youth-hostel",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "札幌国際ユースホステル",
    title_ja: "札幌国際ユースホステル",
    romaji: "Sapporo International Youth Hostel",
    summary_zh:
      "日本ユースホステル協会直営、1976 年創業の老舖。地下鉄「学園前」駅徒歩 1 分。個室/ドミトリー両対応、単身海外バックパッカー多数利用。会員非会員ともに宿泊可。",
    content_md:
      "- 地址:札幌市豊平区豊平 6 条 5 丁目 5-35(地下鉄東豊線「学園前」駅徒歩 1 分)\n- 立地:豊平区・学園前駅徒歩 1 分、中心部へ地下鉄 8 分\n- 規模:80 室 × 199 ベッド(個室 + ドミトリー)\n- 開業:1976 年、日本ユースホステル協会直営\n- 料金:ドミトリー 1 泊 ¥4,500〜 / 個室 ¥6,500〜(非会員 +¥500)\n- 設備:共用シャワー・ランドリー・キッチン・ラウンジ\n- 食事:朝食 ¥700・夕食 ¥1,100(要予約)\n- 長期割:週割・月割プランあり\n- バックパッカー率高、英語スタッフ常駐\n- アクセス:新千歲→JR→地下鉄乗換 50 分\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0433,
    lon: 141.3769,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["sapporo", "youth_hostel", "since_1976", "backpacker", "long_stay"],
    source: "manual",
  },
  {
    slug: "hokkaido-amanek-capsule-sapporo",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "AMANEK カプセルホテル札幌",
    title_ja: "AMANEK カプセルホテル札幌",
    romaji: "AMANEK Capsule Hotel Sapporo",
    summary_zh:
      "すすきの中心のモダンカプセルホテル、2021 年開業。テクニカル系インテリアで 24H フロント。大浴場 + サウナ完備、終電後の締め泊にラーメン横丁 + すすきのラーメン帰りに便利。",
    content_md:
      "- 地址:札幌市中央区南 6 条西 4 丁目 1-8(地下鉄南北線「すすきの」駅徒歩 3 分)\n- 立地:すすきの中心、ラーメン横丁徒歩 2 分\n- 規模:カプセル 180 個(男 120/女 60)、最上階ワイド個室タイプもあり\n- 開業:2021 年、AMANEK ホテル系列\n- 料金:カプセル 1 泊 ¥4,800〜 / ワイド個室 ¥7,500〜\n- 温泉:大浴場 + ドライサウナ + 水風呂 完備(男女別)\n- 設備:漫画ラウンジ(1,000 冊)、喫煙ブース、コインランドリー\n- 女性専用フロア セキュリティカード制\n- 男女混合のフリースペース ラウンジあり\n- アクセス:新千歲→地下鉄「すすきの」→徒歩 3 分\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban"],
    lat: 43.0522,
    lon: 141.3533,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["susukino", "amanek", "capsule", "sauna", "opened_2021"],
    source: "manual",
  },
  {
    slug: "hokkaido-ninehours-newchitose",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "ナインアワーズ新千歲空港",
    title_ja: "ナインアワーズ新千歲空港",
    romaji: "Nine Hours New Chitose Airport",
    summary_zh:
      "2018 年開業、新千歲空港 国内線ターミナル直結の空港内カプセルホテル。1 時間単位(¥1,500)利用可能な仮眠室として早朝便/トランジット旅客に人気。",
    content_md:
      "- 地址:千歲市美々(新千歲空港国内線ターミナル 3F 直結、保安区域外)\n- 立地:空港ビル内・飛行機眺望カプセルあり\n- 系列:ナインアワーズ(東京発カプセルチェーン、羽田・成田・京都などと同ブランド)\n- 規模:170 カプセル(男女別フロア、男性 120・女性 50)\n- 開業:2018 年 7 月(新千歲空港初のカプセル)\n- 料金:宿泊 1 泊 ¥4,000〜 / 1 時間仮眠 ¥1,500 / シャワー単体 ¥1,500\n- 設計:デザイナー柴田文江、Panasonic 熟睡カプセル・アロマ付き\n- 設備:シャワー(アメニティ完備)・ロッカー・無料 Wi-Fi\n- 用途:早朝 6 時便・深夜到着・国際線→国内線トランジット・搭乗口往復 5 分以内\n- 注意:保安検査外のため搭乗前に再手荷物検査必要、夜間 22 時以降の空港館内移動に制限\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "千歳市",
    lg_code: "01224",
    area_types: ["urban"],
    lat: 42.7742,
    lon: 141.6928,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["chitose", "airport_capsule", "ninehours", "opened_2018", "hourly_rate"],
    source: "manual",
  },

  // ── glamping_camp (3 筆) ──────────────────────────────
  {
    slug: "hokkaido-shikaribetsu-kotan",
    category: "lodging",
    sub_type: "glamping_camp",
    title_zh: "然別湖コタン(冬季限定氷上村)",
    title_ja: "然別湖コタン",
    romaji: "Shikaribetsu Kotan",
    summary_zh:
      "冬季全面結氷する然別湖の上に,毎年 1 月下-3 月中 に造られる氷と雪の村。アイスバー/アイスチャペル/氷上露天風呂など全て氷から作る。1980 年開始の冬の風物詩、北海道の魔法。",
    content_md:
      "- 地址:河東郡鹿追町然別湖畔(JR 帯広駅→バス 1 時間 30 分、冬季便限定)\n- 立地:然別湖(然別湖畔温泉周辺)、湖氷結季節のみ\n- 開催期間:毎年 1 月下旬-3 月中旬(約 50 日間)\n- 歷史:1980 年第 1 回開催以来、毎冬造成\n- 構造物:氷のバー(ICE BAR)/氷の教会(結婚式も可)/氷の露天風呂(水着可)\n- 宿泊:然別湖畔温泉ホテル風水・旅館福原(コタン隣接)に泊まる、コタン内では氷のホテル「イグルー」体験泊(限定企画)\n- 夜イベント:21 時-22 時 ライトアップ、冬花火 週末\n- 料金:入場無料(氷上露天風呂 ¥500)、宿泊(ホテル風水)1 泊 2 食 ¥22,000〜\n- アクセス:JR 帯広駅から十勝バス 1 時間 30 分、車では帯広から 1 時間\n- 2026-04 人工查核(鹿追町観光協会 + Wikipedia 然別湖)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "河東郡",
    municipality_ja: "鹿追町",
    lg_code: "01634",
    area_types: ["mountain", "rural"],
    lat: 43.2556,
    lon: 143.1111,
    season_start: "2000-01-25",
    season_end: "2001-03-15",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      wikipedia:
        "https://ja.wikipedia.org/wiki/%E7%84%B6%E5%88%A5%E6%B9%96",
    },
    tags: ["shikaribetsu", "winter_only", "ice_village", "since_1980", "kotan"],
    source: "manual",
  },
  {
    slug: "hokkaido-recamp-toya",
    category: "lodging",
    sub_type: "glamping_camp",
    title_zh: "RECAMP 洞爺",
    title_ja: "RECAMP 洞爺",
    romaji: "RECAMP Toya",
    summary_zh:
      "洞爺湖畔のグランピング&オートキャンプ場、2020 年リブランド開業。テント手ぶら OK のセットアッププラン + 車乗り入れサイトで初心者から本格派まで対応。洞爺湖花火 4-10 月 毎晚眺望可。",
    content_md:
      "- 地址:虻田郡洞爺湖町月浦 56(JR 洞爺駅から車 15 分)\n- 立地:洞爺湖畔南側、月浦ワイナリー隣接\n- 開業:1994 年 月浦フォレストパーク → 2020 年 RECAMP ブランドへリニューアル\n- 料金:オートキャンプ 1 泊 ¥4,500〜 / グランピング棟 1 泊 ¥15,000〜\n- 施設:オートサイト 80・グランピングコテージ 10 棟・常設テント 15\n- 設備:炊事場・温水シャワー・売店(薪/氷/BBQ セット)\n- 特色:洞爺湖花火(4/28-10/31 毎晚 20:45)から湖畔で眺望\n- アクティビティ:カヌー体験(夏)・星空観察(通年)・月浦ワイナリー見学(徒歩 5 分)\n- アクセス:新千歲から車 1 時間 40 分 / JR 洞爺駅からタクシー 15 分\n- 営業:通年(冬期は一部サイトのみ)\n- 2026-04 人工查核(官網)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "洞爺湖町",
    lg_code: "01584",
    area_types: ["coastal", "rural", "onsen_town"],
    lat: 42.5525,
    lon: 140.8217,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["toya", "glamping", "auto_camp", "renewed_2020", "fireworks_view"],
    source: "manual",
  },
  {
    slug: "hokkaido-autoresort-tomakomai-arten",
    category: "lodging",
    sub_type: "glamping_camp",
    title_zh: "オートリゾート苫小牧アルテン",
    title_ja: "オートリゾート苫小牧アルテン",
    romaji: "Auto Resort Tomakomai Arten",
    summary_zh:
      "苫小牧市の大型オートキャンプ場、1991 年開業。全日本オートキャンプ協会 最高 5 つ星認定。200ha の敷地内にコテージ・グランピング・湯の華ゆのみ温泉併設、新千歲空港 30 分圏.",
    content_md:
      "- 地址:苫小牧市字樽前 421-4(JR 苫小牧駅から車 30 分 / 新千歲空港から車 40 分)\n- 立地:錦大沼公園内・樽前山南麓・200ha の広大な森と湖\n- 開業:1991 年(平成 3)、苫小牧市が第三セクター運営\n- 認定:日本オートキャンプ協会 5 つ星(国内最上位)\n- 施設:オートサイト 190・コテージ 30 棟(2-7 名)・グランピングテント 8・個別温泉付コテージ 5\n- 料金:オートサイト ¥3,800〜 / コテージ 4 名 ¥18,000〜 / グランピング 2 名 ¥22,000〜\n- 温泉:「ゆのみの湯」(敷地内、ナトリウム塩化物泉、日帰り ¥600)\n- アクティビティ:カヌー(錦大沼)、フィッシング、レンタサイクル、ノルディックウォーキング\n- 周辺:樽前山(百名山・車 30 分)、支笏湖(車 30 分)、新千歲空港(車 40 分)\n- 営業:通年(冬期もサイト一部・コテージは全期)\n- 2026-04 人工查核(官網 + 苫小牧市観光協会)",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "苫小牧市",
    lg_code: "01213",
    area_types: ["rural", "mountain"],
    lat: 42.6647,
    lon: 141.3908,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {
      official: "https://www.arten.jp/",
    },
    tags: ["tomakomai", "since_1991", "5_star_auto", "airport_area", "cottage"],
    source: "manual",
  },

  // ══════════════════════════════════════════════════════════════════
  // Sprint 16.3 R1 expansion(2026-04-28・50 → 80)
  // ══════════════════════════════════════════════════════════════════

  // ── onsen_ryokan 追加(5 筆・道東+道北温泉) ──────────────────
  {
    slug: "kawayu-onsen-mashu",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "川湯温泉(摩周湖+屈斜路湖の中間・酸性硫黄泉)",
    title_ja: "川湯温泉",
    romaji: "Kawayu Onsen",
    summary_zh:
      "弟子屈町の温泉,摩周湖と屈斜路湖の中間に位置する道東有数の温泉地。源泉は強酸性硫黄泉で温泉街中心部の自然湧出力が強い。横綱大鵬関(1940-2013)の出身地としても知られる。観光客は摩周湖 + 屈斜路湖 + 阿寒湖の道東巡回拠点として宿泊。",
    content_md:
      "- 立地:弟子屈町・摩周湖屈斜路湖中間\n- 泉質:強酸性硫黄泉(pH 1.8)\n- 主要旅館:川湯観光ホテル + 民宿数軒\n- 横綱大鵬関出身地\n- 道東巡回拠点(摩周 + 屈斜路 + 阿寒)\n- 価格:¥10,000-25,000\n- アクセス:JR 摩周駅 + バス 30 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "川上郡",
    municipality_ja: "弟子屈町",
    lg_code: "01665",
    area_types: ["mountain", "rural"],
    lat: 43.617,
    lon: 144.435,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["onsen", "kawayu", "mashu_lake", "kussharo_lake", "tarapou"],
    source: "manual",
  },
  {
    slug: "yorōushi-onsen",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "養老牛温泉(中標津・道東秘湯・1 軒宿)",
    title_ja: "養老牛温泉",
    romaji: "Yorōushi Onsen",
    summary_zh:
      "中標津町の山中の秘湯,川を挟む露天風呂で野生鹿 + シマフクロウ + 川湯けが見られる絶景温泉。湯宿だいいち(1964 創業)が唯一の宿,予約 3-6 ヶ月前。冬期(11-3 月)夜にシマフクロウが訪れる『フクロウの湯』として写真愛好家の聖地。",
    content_md:
      "- 立地:中標津町山中\n- 唯一の宿:湯宿だいいち(1964 創業・1 軒宿)\n- 露天風呂:川を挟む・野生動物観察可\n- シマフクロウ:冬期(11-3 月)夜訪問\n- 価格:¥25,000-40,000(2 食付)\n- 予約:3-6 ヶ月前必須\n- 写真愛好家の聖地\n- アクセス:中標津空港 + 車 40 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "標津郡",
    municipality_ja: "中標津町",
    lg_code: "01692",
    area_types: ["mountain", "rural"],
    lat: 43.564,
    lon: 144.881,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["onsen", "yoroushi", "secret", "shimafukurou", "single_inn"],
    source: "manual",
  },
  {
    slug: "kussharo-konsen-lakeside",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "屈斜路湖湖畔温泉(自然湧出+湖水露天)",
    title_ja: "屈斜路湖湖畔温泉",
    romaji: "Kussharo Lakeside Onsen",
    summary_zh:
      "屈斜路湖(日本最大カルデラ湖)湖畔の温泉地,湖水温泉 + 砂湯(湖砂を掘ると湯が出る)で名高い。和琴半島 + 砂湯 + 池の湯 等の野湯多数,料金無料。湖畔民宿 + ホテル 10 軒余,¥8,000-20,000。冬期は湖が凍結し白鳥が飛来する野鳥観察の名所。",
    content_md:
      "- 立地:屈斜路湖湖畔(弟子屈町)\n- 湖:日本最大カルデラ湖\n- 主要野湯:和琴温泉 + 砂湯 + 池の湯(全て無料)\n- 主要旅館:屈斜路プリンスホテル + 屈斜路湖荘 等 10 軒余\n- 価格:¥8,000-20,000\n- 冬期:凍結 + 白鳥飛来\n- アクセス:JR 川湯駅 + バス\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "川上郡",
    municipality_ja: "弟子屈町",
    lg_code: "01665",
    area_types: ["mountain", "rural", "coastal"],
    lat: 43.617,
    lon: 144.350,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["onsen", "kussharo_lake", "wakoto", "sunayu", "free_yu"],
    source: "manual",
  },
  {
    slug: "shiretoko-utoro-onsen",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "知床ウトロ温泉(世界遺産+流氷ベース)",
    title_ja: "知床ウトロ温泉",
    romaji: "Shiretoko Utoro Onsen",
    summary_zh:
      "斜里町ウトロの温泉郷,知床半島観光 + 流氷ウォーク(冬期)+ 知床五湖ハイキング(夏期)の前線基地。知床第一ホテル + 知床グランドホテル北こぶし + 民宿 20 軒余で構成,¥12,000-30,000。世界自然遺産に隣接する露天風呂が魅力。",
    content_md:
      "- 立地:斜里町ウトロ・知床半島入口\n- 主要旅館:知床第一ホテル + 知床グランドホテル北こぶし(既存 entry)+ 民宿 20 軒\n- 価格:¥12,000-30,000\n- 観光:知床五湖(夏)+ 流氷ウォーク(2-3 月)+ クルーズ\n- 世界自然遺産隣接\n- アクセス:女満別空港 + バス 2 時間\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "斜里郡",
    municipality_ja: "斜里町",
    lg_code: "01545",
    area_types: ["coastal", "rural"],
    lat: 44.080,
    lon: 144.967,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["onsen", "shiretoko", "utoro", "ryuhyo_base", "world_heritage"],
    source: "manual",
  },
  {
    slug: "biei-shirogane-onsen",
    category: "lodging",
    sub_type: "onsen_ryokan",
    title_zh: "白金温泉(美瑛・青い池の湯)",
    title_ja: "白金温泉",
    romaji: "Shirogane Onsen",
    summary_zh:
      "美瑛町の山中の温泉,『青い池』(SNS で世界的に有名)の上流に位置。白金温泉ホテル + 大雪山白金観光ホテル + 林道沿の民宿が中心,¥10,000-25,000。十勝岳ビューポイントの好立地で,夏は青い池 + 冬はライトアップ青い池の観光客が集まる。",
    content_md:
      "- 立地:美瑛町白金・十勝岳麓\n- 観光:青い池(下流・SNS 世界的有名)+ 美瑛丘陵\n- 主要旅館:白金温泉ホテル + 大雪山白金観光ホテル\n- 価格:¥10,000-25,000\n- 冬:青い池ライトアップ + 流星のような風景\n- アクセス:JR 美瑛駅 + バス 30 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川郡",
    municipality_ja: "美瑛町",
    lg_code: "01459",
    area_types: ["mountain", "rural"],
    lat: 43.567,
    lon: 142.652,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["onsen", "shirogane", "biei", "blue_pond", "tokachidake"],
    source: "manual",
  },

  // ── budget_hotel_chain ビジネス都市別(5 筆) ──────────────────
  {
    slug: "business-hakodate-area",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "函館商務酒店エリア(駅周辺ビジネス + 朝市起点)",
    title_ja: "函館ビジネスホテル",
    romaji: "Hakodate Business",
    summary_zh:
      "函館駅周辺のビジネスホテル集積地区,東横イン + コンフォート + アパ + ドーミーイン函館等 20 軒余。¥6,000-12,000/泊。朝市(150 m 徒歩)+ ベイエリア(15 分)+ 元町(20 分)の徒歩観光起点として最適。冬期は函館山ロープウェイ夜景観賞のベース。",
    content_md:
      "- 場所:函館駅周辺(徒歩 5 分圏内)\n- 主要 chain:東横イン + コンフォート + アパ + ドーミーイン\n- 価格:¥6,000-12,000/泊\n- 観光:朝市(150 m)+ ベイエリア + 元町 + 函館山ロープウェイ\n- 朝食:朝市での海鮮丼推奨\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["urban"],
    lat: 41.774,
    lon: 140.726,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["business_hotel", "hakodate_station", "asaichi", "concept", "area_guide"],
    source: "manual",
  },
  {
    slug: "business-asahikawa-area",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "旭川商務酒店エリア(駅前 + 旭山動物園)",
    title_ja: "旭川ビジネスホテル",
    romaji: "Asahikawa Business",
    summary_zh:
      "旭川駅前 + 買物公園周辺のビジネスホテル集積,東横イン + アパ + ANA クラウンプラザ旭川 等 30 軒余。¥7,000-15,000/泊。旭山動物園 + 大雪山 + 富良野アクセスの拠点として観光客 + ビジネス両用途。冬期は -10℃ 以下,室内温暖装備重視。",
    content_md:
      "- 場所:旭川駅前 + 買物公園周辺\n- 主要 chain:東横 + アパ + ANA クラウンプラザ + JR イン\n- 価格:¥7,000-15,000/泊\n- 観光:旭山動物園(バス 30 分)+ 大雪山(車 60 分)+ 富良野(車 60 分)\n- 冬期:-10℃ 以下・室内温暖装備\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "旭川市",
    lg_code: "01204",
    area_types: ["urban"],
    lat: 43.770,
    lon: 142.366,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["business_hotel", "asahikawa_station", "concept", "area_guide", "zoo_base"],
    source: "manual",
  },
  {
    slug: "business-obihiro-area",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "帯広商務酒店エリア(駅前 + 十勝観光)",
    title_ja: "帯広ビジネスホテル",
    romaji: "Obihiro Business",
    summary_zh:
      "帯広駅周辺のビジネスホテル,東横 + コンフォート + アパ + ドーミーイン 等 15 軒余。¥6,000-12,000/泊。十勝平野(豆 + 牛 + 馬)観光 + 帯広競馬(ばんえい)+ 然別湖アクセスの拠点。豚丼名店『ぱんちょう』+『はげ天』が徒歩圏。",
    content_md:
      "- 場所:帯広駅周辺(徒歩 5 分圏内)\n- 主要 chain:東横 + コンフォート + アパ + ドーミーイン\n- 価格:¥6,000-12,000/泊\n- 観光:十勝平野 + ばんえい競馬 + 然別湖(車 90 分)\n- 名物:豚丼ぱんちょう + はげ天(駅徒歩圏)\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "帯広市",
    lg_code: "01207",
    area_types: ["urban"],
    lat: 42.917,
    lon: 143.196,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["business_hotel", "obihiro", "tokachi", "ban-ei", "concept"],
    source: "manual",
  },
  {
    slug: "business-kushiro-area",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "釧路商務酒店エリア(駅前 + 湿原+漁港)",
    title_ja: "釧路ビジネスホテル",
    romaji: "Kushiro Business",
    summary_zh:
      "釧路駅 + フィッシャーマンズワーフ MOO 周辺のビジネスホテル,ANA クラウンプラザ釧路 + 東横 + アパ + コンフォート 等 12 軒余。¥7,000-13,000/泊。釧路湿原 + 阿寒湖 + 摩周湖 + 釧路漁港(炉端焼の本場)へのアクセス基地。",
    content_md:
      "- 場所:釧路駅 + フィッシャーマンズワーフ MOO 周辺\n- 主要 chain:ANA クラウンプラザ + 東横 + アパ + コンフォート\n- 価格:¥7,000-13,000/泊\n- 観光:釧路湿原 + 阿寒湖 + 摩周湖\n- 名物:釧路漁港炉端焼(炉ばた + 岸壁炉ばた 等)\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "釧路市",
    lg_code: "01206",
    area_types: ["urban", "coastal"],
    lat: 42.985,
    lon: 144.382,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["business_hotel", "kushiro", "shitsugen", "robatayaki", "concept"],
    source: "manual",
  },
  {
    slug: "business-tomakomai-area",
    category: "lodging",
    sub_type: "budget_hotel_chain",
    title_zh: "苫小牧商務酒店エリア(フェリー乗船+空港中継)",
    title_ja: "苫小牧ビジネスホテル",
    romaji: "Tomakomai Business",
    summary_zh:
      "苫小牧市内のビジネスホテル,フェリー乗船(大洗 / 仙台 / 名古屋)前後 + 新千歳空港中継 + 白老ウポポイ観光の拠点。東横 + アパ + コンフォート + ルートイン 等 15 軒余,¥6,000-11,000/泊。フェリーターミナル+港町文化 + 工業地帯混在の特殊エリア。",
    content_md:
      "- 場所:苫小牧駅 + フェリーターミナル周辺\n- 主要 chain:東横 + アパ + コンフォート + ルートイン\n- 価格:¥6,000-11,000/泊\n- 用途:\n  → フェリー乗船前後(大洗 / 仙台 / 名古屋)\n  → 新千歳空港中継(40 分)\n  → 白老ウポポイ + 登別観光(車 30-60 分)\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "苫小牧市",
    lg_code: "01213",
    area_types: ["urban", "coastal"],
    lat: 42.640,
    lon: 141.593,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["business_hotel", "tomakomai", "ferry_terminal", "airport_relay", "concept"],
    source: "manual",
  },

  // ── luxury_hotel リゾート追加(5 筆) ──────────────────
  {
    slug: "niseko-village-resort",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ニセコビレッジ(ヒルトン傘下・国際リゾート)",
    title_ja: "ニセコビレッジ",
    romaji: "Niseko Village",
    summary_zh:
      "倶知安町のニセコビレッジ,ヒルトン + グリーンリーフ + カサラニセコ等の高級リゾート集積。冬期(12-3 月)はパウダースキー + 夏期(6-9 月)はゴルフ + ハイキング + ジップライン。¥30,000-100,000/泊。Australia + 香港観光客の聖地。",
    content_md:
      "- 立地:倶知安町ニセコビレッジ\n- 主要ホテル:ヒルトン + ザ・グリーンリーフ + カサラニセコ\n- 季節:\n  → 冬(12-3 月)パウダースキー\n  → 夏(6-9 月)ゴルフ + ハイキング + ジップライン\n- 価格:¥30,000-100,000/泊\n- 国際客層:Australia + 香港 + シンガポール\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "倶知安町",
    lg_code: "01395",
    area_types: ["mountain"],
    lat: 42.879,
    lon: 140.701,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.niseko-village.com/" },
    tags: ["resort", "niseko", "hilton", "international", "ski"],
    source: "manual",
  },
  {
    slug: "rusutsu-the-tower",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ルスツ ザ・タワー(2009 開業・スキー直結 18F)",
    title_ja: "ルスツ ザ・タワー",
    romaji: "Rusutsu The Tower",
    summary_zh:
      "留寿都村ルスツリゾートの 18 階建ホテル(2009 開業),洞爺湖 + 羊蹄山が見える展望客室。冬期はスキー直結ゴンドラ徒歩 1 分,夏期はテーマパーク内ホテル。¥20,000-60,000/泊で家族向け。新千歳空港から バス 90 分。",
    content_md:
      "- 開業:2009\n- 規模:18 階建\n- 立地:ルスツリゾート内・スキー直結\n- 客室:洞爺湖 + 羊蹄山ビュー\n- 季節:\n  → 冬:スキー直結ゴンドラ徒歩 1 分\n  → 夏:遊園地内ホテル(家族向け)\n- 価格:¥20,000-60,000/泊\n- アクセス:新千歳 + バス 90 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "留寿都村",
    lg_code: "01396",
    area_types: ["mountain"],
    lat: 42.731,
    lon: 140.840,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://rusutsu.com/" },
    tags: ["resort", "rusutsu", "since_2009", "ski_in_out", "family"],
    source: "manual",
  },
  {
    slug: "akan-tsuruga-hougou",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "鶴雅 鳳凰(阿寒湖最高級・露天展望)",
    title_ja: "鶴雅リゾート 鳳凰",
    romaji: "Tsuruga Hōōgou",
    summary_zh:
      "阿寒湖温泉の最高級ホテル,鶴雅リゾートグループ(阿寒湖 5 ホテル運営)の旗艦。展望露天風呂 + 阿寒湖湖畔 + アイヌコタン徒歩 5 分。¥30,000-80,000/泊で 2 食付,シェフによる海鮮 + 北海道食材コース。冬は氷上イベント+夏はカヌー+秋は紅葉。",
    content_md:
      "- 開業:1997(鶴雅グループ)\n- 立地:阿寒湖温泉\n- 客室:展望露天風呂付プレミアム\n- 価格:¥30,000-80,000/泊(2 食付)\n- 食事:シェフによる海鮮 + 北海道コース\n- 季節:\n  → 冬:氷上イベント\n  → 夏:カヌー\n  → 秋:紅葉\n- 隣接:アイヌコタン徒歩 5 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "釧路市",
    lg_code: "01206",
    area_types: ["mountain", "rural"],
    lat: 43.444,
    lon: 144.090,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://www.tsuruga.com/" },
    tags: ["luxury", "akan", "tsuruga", "lake_view", "ainu_kotan"],
    source: "manual",
  },
  {
    slug: "tomamu-club-med",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "クラブメッド・トマム(オールインクルーシブ・冬限定)",
    title_ja: "クラブメッド・トマム",
    romaji: "Club Med Tomamu",
    summary_zh:
      "占冠村ホシノリゾート トマム内のフランス系オールインクルーシブリゾート。スキー + 食事 + ドリンク + 子供キャンプ全部込みの料金体系で家族 + 国際客向け。¥40,000-150,000/泊・人,12-3 月の冬期限定運営。アジア + 欧米客層が集まる。",
    content_md:
      "- 立地:占冠村ホシノリゾート トマム\n- 系列:Club Med(フランス本部)\n- システム:オールインクルーシブ(スキー + 食 + ドリンク + 子供キャンプ込)\n- 期間:12-3 月限定\n- 価格:¥40,000-150,000/泊・人\n- 客層:アジア + 欧米国際客\n- アクセス:JR トマム駅 + シャトル\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "勇払郡",
    municipality_ja: "占冠村",
    lg_code: "01581",
    area_types: ["mountain"],
    lat: 42.985,
    lon: 142.524,
    season_start: "2000-12-01",
    season_end: "2000-03-31",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: { official: "https://www.clubmed.co.jp/" },
    tags: ["luxury", "club_med", "tomamu", "all_inclusive", "winter_only"],
    source: "manual",
  },
  {
    slug: "shiretoko-utoro-grand",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "知床ウトロ第一ホテル(世界遺産+流氷ベース)",
    title_ja: "知床ウトロ第一ホテル",
    romaji: "Shiretoko Utoro Daiichi",
    summary_zh:
      "斜里町ウトロの最大級ホテル,知床第一ホテル(1962 創業)。世界自然遺産知床半島観光 + 流氷ウォーク(2-3 月)+ 知床五湖(夏期)の前線基地。展望露天風呂 + 海鮮ビュッフェ + 知床ガイドツアー併設。¥18,000-40,000/泊。",
    content_md:
      "- 立地:斜里町ウトロ・知床半島入口\n- 開業:1962(60 年の歴史)\n- 規模:200 室・ウトロ最大級\n- 設備:展望露天風呂 + 海鮮ビュッフェ + ガイド\n- 価格:¥18,000-40,000/泊(2 食付)\n- 季節 highlight:\n  → 冬(2-3 月)流氷ウォーク\n  → 夏知床五湖 + クルーズ\n- アクセス:女満別空港 + バス 2 時間\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "斜里郡",
    municipality_ja: "斜里町",
    lg_code: "01545",
    area_types: ["coastal", "rural"],
    lat: 44.080,
    lon: 144.967,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://shiretoko-1.com/" },
    tags: ["luxury", "shiretoko", "utoro", "since_1962", "ryuhyo"],
    source: "manual",
  },

  // ── capsule_hostel ホステル追加(3 筆) ──────────────────
  {
    slug: "sapporo-prime-hostel",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "プライムホステル札幌(2018 開業・大通公園至近)",
    title_ja: "プライムホステル札幌",
    romaji: "Prime Hostel Sapporo",
    summary_zh:
      "札幌大通公園至近の 2018 開業ホステル,カプセルベッド + 個室両対応で観光客 + 出張両用。雪まつり大通会場徒歩 5 分,深夜営業バー併設で sociable な雰囲気。¥3,500-6,000/泊。チェックイン 24 時間制で深夜便対応。",
    content_md:
      "- 開業:2018\n- 立地:大通公園徒歩 5 分(雪まつり会場)\n- ベッドタイプ:カプセル + 個室\n- 価格:¥3,500-6,000/泊\n- 24 時間チェックイン(深夜便対応)\n- 設備:バー併設 + 共同キッチン\n- 客層:国際客 + 若者\n- アクセス:地下鉄南北線大通駅徒歩 5 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban_central"],
    lat: 43.063,
    lon: 141.357,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["hostel", "sapporo", "since_2018", "odori_park", "yuki_festival"],
    source: "manual",
  },
  {
    slug: "hakodate-mt-hakodate-bnb",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "函館元町 B&B(明治洋館街・ハイカラ滞在)",
    title_ja: "函館元町 B&B",
    romaji: "Hakodate Motomachi BnB",
    summary_zh:
      "函館元町の明治期洋館を改装した B&B + ゲストハウス 5 軒余,ハイカラ和洋折衷インテリアで函館港町の雰囲気を体験。¥6,000-15,000/泊で朝食付。函館山ロープウェイ + 元町散策 + 教会群が徒歩圏で観光客に人気の独立系宿。",
    content_md:
      "- 場所:函館元町(明治洋館街)\n- 主要宿:旧 hostel 系 + 古民家改装 B&B\n- 価格:¥6,000-15,000/泊(朝食付)\n- 観光:函館山 + 元町教会群 + ハリストス正教会\n- 客層:女性 + 国際客\n- アクセス:函館市電十字街駅徒歩 5 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "函館市",
    lg_code: "01202",
    area_types: ["urban"],
    lat: 41.762,
    lon: 140.713,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["bnb", "hakodate", "motomachi", "concept", "haikara"],
    source: "manual",
  },
  {
    slug: "niseko-backpacker-hostel",
    category: "lodging",
    sub_type: "capsule_hostel",
    title_zh: "ニセコバックパッカーホステル(冬 SB+夏ハイキング)",
    title_ja: "ニセコバックパッカー",
    romaji: "Niseko Backpacker",
    summary_zh:
      "ニセコ + 倶知安エリアのバックパッカーホステル 5 軒余,Australia + 香港 + 韓国の若い SB スキー客向け。ドミトリー ¥3,000-6,000/泊 + 個室 ¥8,000-12,000。共同キッチン + 乾燥室 + スキーロッカーが標準装備。SB スキー初心者対応のレッスン斡旋も。",
    content_md:
      "- 場所:ニセコ + 倶知安駅前\n- 主要宿:Niseko Yume + Mountain Side + 等 5 軒\n- 価格:ドミトリー ¥3,000-6,000・個室 ¥8,000-12,000\n- 設備:共同キッチン + 乾燥室 + スキーロッカー\n- 客層:Australia + 香港 + 韓国の若年 SB 客\n- 同期:冬(12-3 月)+ 夏(6-9 月)両対応\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "倶知安町",
    lg_code: "01395",
    area_types: ["mountain"],
    lat: 42.901,
    lon: 140.687,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 14,
    closed_days: [],
    external_urls: {},
    tags: ["backpacker", "niseko", "concept", "international", "ski_dorm"],
    source: "manual",
  },

  // ── rural_minshuku 民宿(3 筆) ──────────────────
  {
    slug: "shiretoko-utoro-minshuku",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "知床ウトロ民宿(漁師家系・¥8,000-)",
    title_ja: "知床ウトロ民宿",
    romaji: "Shiretoko Utoro Minshuku",
    summary_zh:
      "斜里町ウトロの漁師経営の小規模民宿 10 軒余,2 食付¥8,000-12,000/泊で大型ホテルより安価。漁師直送の海鮮(鮭 + ウニ + イクラ)が魅力,主人による知床ガイドサービスも提供。冬期は流氷観察用に防寒装備貸出。",
    content_md:
      "- 場所:斜里町ウトロ\n- 業態:漁師家経営の小規模民宿\n- 主要宿:ペンション系 10 軒余\n- 価格:¥8,000-12,000/泊(2 食付・大型ホテルより安価)\n- 食事:漁師直送海鮮(鮭 + ウニ + イクラ)\n- サービス:主人による知床ガイド\n- 冬期:防寒装備貸出\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "斜里郡",
    municipality_ja: "斜里町",
    lg_code: "01545",
    area_types: ["coastal", "rural"],
    lat: 44.080,
    lon: 144.967,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["minshuku", "shiretoko", "fisherman", "concept", "seafood"],
    source: "manual",
  },
  {
    slug: "daisetsuzan-tozan-lodge",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "大雪山登山ロッジ(山小屋系・1700 m)",
    title_ja: "大雪山登山ロッジ",
    romaji: "Daisetsuzan Tozan Lodge",
    summary_zh:
      "大雪山黒岳石室 + 白雲岳避難小屋 + 忠別岳避難小屋等の山小屋,夏期(6-10 月)登山者向け宿泊。素泊まり¥3,000-5,000 で寝具持参。大雪山縦走 1-3 泊の中間泊として利用。要予約 + 自炊 + 携帯ストーブ持参の本格登山者向け。",
    content_md:
      "- 主要小屋:黒岳石室 + 白雲岳避難小屋 + 忠別岳避難小屋\n- 立地:標高 1500-1900 m\n- 期間:6-10 月(冬期閉鎖)\n- 価格:素泊まり¥3,000-5,000\n- 寝具:持参(寝袋必須)\n- 食事:自炊(携帯ストーブ + 食料持参)\n- 用途:大雪山縦走 1-3 泊の中間泊\n- 予約:必須(電話 + 公式 web)\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["mountain"],
    lat: null,
    lon: null,
    season_start: "2000-06-01",
    season_end: "2000-10-31",
    event_start: null,
    event_end: null,
    price_tier: 1,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["lodge", "daisetsuzan", "mountain_hut", "advanced_hikers", "concept"],
    source: "manual",
  },
  {
    slug: "furano-pension",
    category: "lodging",
    sub_type: "rural_minshuku",
    title_zh: "富良野ペンション(花畑+ラベンダー観光ベース)",
    title_ja: "富良野ペンション",
    romaji: "Furano Pension",
    summary_zh:
      "富良野市内のペンション 30 軒余,ラベンダー観光ピーク期(7 月)+ 富良野チーズ + ジャガイモ + 美瑛丘陵観光のベース。¥8,000-15,000/泊で 2 食付,オーナー手作の家庭料理が魅力。冬はスキー客向けにも対応。",
    content_md:
      "- 場所:富良野市内 + 周辺\n- 規模:約 30 軒余ペンション\n- 価格:¥8,000-15,000/泊(2 食付)\n- 食事:オーナー手作家庭料理(地元食材)\n- 同期:夏ラベンダー(7 月)+ 冬スキー\n- 観光:富良野ラベンダー + 美瑛丘 + 富良野チーズ工房\n- アクセス:JR 富良野駅 + 車 5-15 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "富良野市",
    lg_code: "01229",
    area_types: ["rural"],
    lat: 43.342,
    lon: 142.382,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["pension", "furano", "lavender", "concept", "homestay"],
    source: "manual",
  },

  // ── glamping_camp 追加(2 筆) ──────────────────
  {
    slug: "kussharo-glamping",
    category: "lodging",
    sub_type: "glamping_camp",
    title_zh: "屈斜路湖グランピング(湖畔ドーム+焚火)",
    title_ja: "屈斜路湖グランピング",
    romaji: "Kussharo Glamping",
    summary_zh:
      "屈斜路湖湖畔のグランピング施設,ドームテント + 焚火 + 湖水露天で本格的アウトドア体験。¥18,000-30,000/泊・人(食事込)。夏期(5-10 月)運営,湖水アクティビティ(SUP + カヌー)併設。家族 + カップル向け非日常体験。",
    content_md:
      "- 場所:屈斜路湖湖畔\n- 形式:ドームテント + 焚火 + 湖水露天\n- 価格:¥18,000-30,000/泊・人(2 食付)\n- 期間:5-10 月\n- アクティビティ:SUP + カヌー併設\n- 客層:家族 + カップル\n- アクセス:JR 川湯駅 + 車 25 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "川上郡",
    municipality_ja: "弟子屈町",
    lg_code: "01665",
    area_types: ["mountain", "rural"],
    lat: 43.617,
    lon: 144.350,
    season_start: "2000-05-01",
    season_end: "2000-10-31",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["glamping", "kussharo", "lakeside", "summer", "family"],
    source: "manual",
  },
  {
    slug: "biei-glamping",
    category: "lodging",
    sub_type: "glamping_camp",
    title_zh: "美瑛丘陵グランピング(青い池+丘陵ビュー)",
    title_ja: "美瑛グランピング",
    romaji: "Biei Glamping",
    summary_zh:
      "美瑛町の丘陵地に開設されたグランピング施設,青い池 + パッチワーク丘陵 + 十勝岳の景観を満喫。ドームテント + バーベキュー + 焚火付,¥20,000-35,000/泊・人。夏期(5-10 月)+ 冬期一部運営(青い池ライトアップ視察)。SNS インスタ映えで人気急上昇。",
    content_md:
      "- 場所:美瑛町丘陵地\n- 形式:ドームテント + BBQ + 焚火\n- 価格:¥20,000-35,000/泊・人(食事込)\n- 期間:5-10 月 + 冬一部(青い池ライトアップ)\n- 景観:青い池 + パッチワーク丘陵 + 十勝岳\n- 客層:SNS 映え志向\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "上川郡",
    municipality_ja: "美瑛町",
    lg_code: "01459",
    area_types: ["rural"],
    lat: 43.567,
    lon: 142.652,
    season_start: "2000-05-01",
    season_end: "2000-10-31",
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: {},
    tags: ["glamping", "biei", "blue_pond", "instagram", "summer"],
    source: "manual",
  },

  // ── lodging_area_guide 都市別エリア(7 筆) ──────────────────
  {
    slug: "sapporo-station-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "札幌駅エリア住宿選擇(JR 直結+地下街+空港アクセス)",
    title_ja: "札幌駅エリア住宿",
    romaji: "Sapporo Station Lodging",
    summary_zh:
      "札幌駅徒歩 5 分圏内のホテル選択ガイド。JR タワー日航(高級)+ JR イン札幌(中級)+ ビジネス各 chain(東横/アパ/コンフォート/ドーミー)+ ナインアワーズ(カプセル)= 価格帯すべて揃う。新千歳空港まで JR 37 分・地下街連結で雪まつり時期も快適。",
    content_md:
      "- 立地:JR 札幌駅徒歩 5 分圏\n- 価格帯:\n  → 高級:JR タワー日航 ¥30,000-(既存 entry)\n  → 中級:JR イン ¥10,000-15,000\n  → ビジネス:東横 + アパ + コンフォート ¥7,000-12,000\n  → カプセル:ナインアワーズ ¥3,500-5,000\n- 空港アクセス:新千歳まで JR 37 分・¥1,150\n- 雪まつり時期:地下街連結で雨雪不要傘\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban_central"],
    lat: 43.068,
    lon: 141.350,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["area_guide", "sapporo_station", "concept", "all_price_range"],
    source: "manual",
  },
  {
    slug: "susukino-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "すすきのエリア住宿(歓楽街+夜遊び+夜食)",
    title_ja: "すすきのエリア住宿",
    romaji: "Susukino Lodging",
    summary_zh:
      "札幌すすきの(歓楽街)エリアのホテル選択ガイド。OMO3 すすきの(星野リゾート)+ 東横 + アパ + ANA クラウンプラザ等 30 軒余,深夜帰宅 + 夜遊び目的の宿泊客に最適。ラーメン横丁 + ジンギスカン + クラブが徒歩圏。¥7,000-25,000/泊。",
    content_md:
      "- 立地:札幌すすきの地区\n- 主要 hotel:OMO3(星野・既存 entry)+ 東横 + アパ + ANA クラウンプラザ\n- 価格:¥7,000-25,000/泊\n- 用途:夜遊び + 夜食 + 深夜帰宅対応\n- 周辺名物:ラーメン横丁 + ジンギスカン + クラブ\n- アクセス:地下鉄南北線すすきの駅\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "札幌市",
    lg_code: "01100",
    area_types: ["urban_central"],
    lat: 43.055,
    lon: 141.353,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: null,
    closed_days: [],
    external_urls: {},
    tags: ["area_guide", "susukino", "nightlife", "concept", "izakaya"],
    source: "manual",
  },
  {
    slug: "abashiri-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "網走エリア住宿(流氷+知床ベース)",
    title_ja: "網走エリア住宿",
    romaji: "Abashiri Lodging",
    summary_zh:
      "網走市のホテル選択ガイド,流氷観光船おーろら(2-3 月)+ 知床アクセス + 網走監獄博物館観光のベース。網走湖畔 + 駅前 + 海岸沿の 3 立地,ホテル網走湖荘 + 東横 + ホテルルートイン 等 15 軒余,¥8,000-20,000/泊。冬期は流氷観光客で予約困難。",
    content_md:
      "- 立地:網走湖畔 + 駅前 + 海岸沿\n- 主要 hotel:ホテル網走湖荘 + 東横 + ルートイン\n- 価格:¥8,000-20,000/泊\n- 用途:流氷観光船(2-3 月)+ 知床アクセス + 網走監獄博\n- 冬期予約困難:1 ヶ月前推奨\n- アクセス:女満別空港 + バス 30 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "網走市",
    lg_code: "01211",
    area_types: ["urban", "coastal"],
    lat: 44.018,
    lon: 144.275,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["area_guide", "abashiri", "ryuhyo_base", "concept"],
    source: "manual",
  },
  {
    slug: "wakkanai-area-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "稚内エリア住宿(最北+利尻礼文ベース)",
    title_ja: "稚内エリア住宿",
    romaji: "Wakkanai Lodging",
    summary_zh:
      "日本最北端稚内市のホテル選択ガイド。稚内駅前ホテル多数 + 副港横ホテル(夕日綺麗)+ 北海道最北端宗谷岬周辺民宿。ホテル ドーミーイン稚内 + 稚内サンホテル 等 12 軒余,¥9,000-18,000/泊。利尻島 + 礼文島フェリー乗船前後の宿泊地。",
    content_md:
      "- 立地:稚内駅前 + 副港 + 宗谷岬周辺\n- 主要 hotel:ドーミーイン稚内 + 稚内サンホテル + 12 軒余\n- 価格:¥9,000-18,000/泊\n- 用途:利尻 + 礼文島フェリー前後 + 宗谷岬最北端観光\n- 副港:夕日 + 港の風景\n- アクセス:JR 宗谷本線稚内駅\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: "稚内市",
    lg_code: "01214",
    area_types: ["urban", "coastal"],
    lat: 45.416,
    lon: 141.673,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 30,
    closed_days: [],
    external_urls: {},
    tags: ["area_guide", "wakkanai", "northernmost", "rishiri_rebun", "concept"],
    source: "manual",
  },
  {
    slug: "rishiri-rebun-lodging",
    category: "lodging",
    sub_type: "lodging_area_guide",
    title_zh: "利尻+礼文島住宿(夏期限定民宿+リゾート)",
    title_ja: "利尻礼文島住宿",
    romaji: "Rishiri Rebun Lodging",
    summary_zh:
      "利尻島(利尻富士)+ 礼文島(花の島)の住宿ガイド,5-9 月のシーズン中のみ運営の民宿 + リゾートホテル。利尻島は 30 軒余 + 礼文島は 25 軒余,¥10,000-25,000/泊で 2 食付。10 月以降は閉鎖宿が多く,夏期予約は 3 ヶ月前必須。",
    content_md:
      "- 利尻島:利尻富士 + ハイキング + ウニ漁\n- 礼文島:高山植物 + ハイキング + アザラシ\n- 主要宿:民宿 30 軒余(利尻)+ 25 軒余(礼文)\n- シーズン:5-9 月のみ運営\n- 価格:¥10,000-25,000/泊(2 食付)\n- 予約:3 ヶ月前必須\n- アクセス:稚内 + ハートランドフェリー(既存 entry)\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: null,
    municipality_ja: null,
    lg_code: null,
    area_types: ["coastal", "rural"],
    lat: 45.220,
    lon: 141.225,
    season_start: "2000-05-01",
    season_end: "2000-09-30",
    event_start: null,
    event_end: null,
    price_tier: 2,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["area_guide", "rishiri", "rebun", "summer_only", "concept"],
    source: "manual",
  },
  {
    slug: "yoichi-wine-resort",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "余市ワインリゾート(NIKI Hills + 醸造場併設)",
    title_ja: "余市ワインリゾート",
    romaji: "Yoichi Wine Resort",
    summary_zh:
      "余市町のワイナリー併設リゾート,NIKI Hills Winery + Hotel(2017 開業)等。ワイン醸造場見学 + 試飲 + 食事 + 宿泊オールインワン。¥30,000-80,000/泊で,余市の冷涼気候を活かしたピノノワール + シャルドネが主品目。NHK 朝ドラ『マッサン』ニッカ余市蒸溜所も近隣。",
    content_md:
      "- 立地:余市町(NIKI Hills 等)\n- 開業:2017(NIKI Hills)\n- 設備:ワイナリー + ホテル + レストラン併設\n- 価格:¥30,000-80,000/泊\n- 主品目:ピノノワール + シャルドネ\n- 周辺:ニッカ余市蒸溜所(NHK 朝ドラ『マッサン』)\n- アクセス:JR 余市駅 + 車 10 分\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "余市郡",
    municipality_ja: "余市町",
    lg_code: "01408",
    area_types: ["rural", "small_town"],
    lat: 43.190,
    lon: 140.792,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 60,
    closed_days: [],
    external_urls: { official: "https://nikihills.co.jp/" },
    tags: ["luxury", "yoichi", "winery", "since_2017", "nikka"],
    source: "manual",
  },
  {
    slug: "niseko-condominium-long-stay",
    category: "lodging",
    sub_type: "luxury_hotel",
    title_zh: "ニセココンドミニアム長期滞在(自炊+1 週間以上)",
    title_ja: "ニセココンドミニアム",
    romaji: "Niseko Condominium",
    summary_zh:
      "ニセコ + 倶知安エリアのコンドミニアム(自炊式長期滞在),1 LDK + 2 LDK + 4 LDK 等の各種サイズ。¥15,000-50,000/泊・1-2 週間滞在の Australian + 香港客が中心。スキー + ハイキング + ゴルフ等の長期滞在に最適。AirBnB / Booking + 専門エージェント経由。",
    content_md:
      "- 立地:ニセコ + 倶知安\n- 形式:1-4 LDK コンドミニアム(自炊式)\n- 価格:¥15,000-50,000/泊\n- 推奨期間:1-2 週間\n- 客層:Australian + 香港 + 韓国の長期滞在\n- 予約:AirBnB + Booking + 専門エージェント\n- 2026-04 人工查核",
    region: "hokkaido",
    prefecture_ja: "北海道",
    gun_ja: "虻田郡",
    municipality_ja: "倶知安町",
    lg_code: "01395",
    area_types: ["mountain"],
    lat: 42.901,
    lon: 140.687,
    season_start: null,
    season_end: null,
    event_start: null,
    event_end: null,
    price_tier: 3,
    booking_window_days: 90,
    closed_days: [],
    external_urls: {},
    tags: ["condominium", "niseko", "long_stay", "concept", "self_catering"],
    source: "manual",
  },
];

async function main() {
  const bySubType = rows.reduce<Record<string, number>>((acc, r) => {
    acc[r.sub_type] = (acc[r.sub_type] ?? 0) + 1;
    return acc;
  }, {});
  console.log(
    `📦 ${rows.length} rows prepared. Distribution:`,
    JSON.stringify(bySubType),
  );

  if (DRY) {
    console.log("\n— Dry-run preview —");
    for (const r of rows) {
      console.log(
        `  [${r.sub_type.padEnd(20)}] ${r.title_zh} (${r.municipality_ja ?? "-"}/${r.lg_code ?? "-"})`,
      );
    }
    return;
  }

  const sb = createAdminClient();
  const { data, error } = await sb
    .from("japan_entries")
    .upsert(rows, { onConflict: "slug" })
    .select("id,slug");
  if (error) {
    console.error("❌ upsert failed:", error.message);
    process.exit(1);
  }
  console.log(`✅ upsert ok: ${data?.length ?? 0} rows`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
