// Seed 千葉県 R2 補完(20 筆 / Sprint 2.x / 第十二卷)
// 食 5 / 住 4 / 衣 3 / 育 3 / 楽 3 / 行 2 = 20 累積 123 + 20 = 143
import { seedMain, type SeedRow } from "./seed-helpers/upsert-entries";

const rows: SeedRow[] = [
  // 食 5
  {
    slug: "futtsu-nori",
    category: "food", sub_type: "chiba_seafood",
    title_zh: "富津海苔(富津市+木更津・全国海苔生産量上位+ 江戸期 1700 年代から海苔養殖 300+ 年・東京湾湾奥の海苔発祥地候補・富津湾養殖場・10-3 月旬・1 帖 ¥1,500-4,500・道の駅+漁協販売)",
    title_ja: "富津海苔", romaji: "Futtsu Nori",
    summary_zh: "**富津海苔は全国海苔生産量上位・江戸期 1700 年代から海苔養殖 300+ 年・東京湾海苔発祥地候補**(富津+木更津・**10-3 月旬**)。¥1,500-4,500/帖、道の駅+漁協。",
    content_md: "- 立地:**富津市 + 木更津市**\n- 起源:**江戸期 1700 年代から海苔養殖 300+ 年**\n- 認定:**全国海苔生産量上位 + 東京湾海苔発祥地候補**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "富津市", lg_code: "12226",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 35.3194, lon: 139.7811,
    season_start: "2026-10-01", season_end: "2027-03-31", event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["futtsu_nori"], source: "manual",
  },
  {
    slug: "kujukuri-iwashi-himono",
    category: "food", sub_type: "chiba_seafood",
    title_zh: "九十九里イワシ干物+丸干し(山武郡九十九里町+大網白里・九十九里浜近海漁港 江戸期から鰯漁 400+ 年・1700 年代房総鰯油全国流通+ 丸干しイワシ+目刺し+ 季節 11-3 月+ 道の駅+魚屋直販+ 1 袋 ¥350-1,500)",
    title_ja: "九十九里イワシ干物", romaji: "Kujūkuri Iwashi",
    summary_zh: "**九十九里イワシ干物+丸干しは九十九里浜近海漁港 江戸期から鰯漁 400+ 年・1700 年代房総鰯油全国流通**(九十九里+大網・**11-3 月旬**)。¥350-1,500/袋。",
    content_md: "- 立地:**山武郡九十九里町 + 大網白里市**\n- 起源:**江戸期から鰯漁 400+ 年**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: "山武郡", municipality_ja: "九十九里町", lg_code: "12403",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 35.5306, lon: 140.4594,
    season_start: "2026-11-01", season_end: "2027-03-31", event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kujukuri_iwashi"], source: "manual",
  },
  {
    slug: "katsuura-asaichi-1591",
    category: "food", sub_type: "chiba_kyodo",
    title_zh: "勝浦朝市(勝浦市・1591 天正 19 年里見氏義康設立 434+ 年+ 全国 3 大朝市(輪島朝市・高山朝市と並ぶ)+ 毎水曜+第 1・3・5 日曜は休市・通常 6 時-11 時+ R1 食 勝浦カツオ+ R1 行 JR 外房線勝浦駅徒歩 5 分・無料散策)",
    title_ja: "勝浦朝市", romaji: "Katsuura Asaichi",
    summary_zh: "**勝浦朝市は 1591 天正 19 年里見氏義康設立 434+ 年・全国 3 大朝市(輪島+高山と並ぶ)**(勝浦・**6 時-11 時+毎水曜+第 1・3・5 日曜休**)。R1 食 勝浦カツオ連動、無料。",
    content_md: "- 立地:**勝浦市**\n- 起源:**1591 天正 19 年里見氏義康設立 434+ 年**\n- 認定:**全国 3 大朝市(輪島朝市 + 高山朝市と並ぶ)**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "勝浦市", lg_code: "12218",
    area_types: ["restaurant_traditional", "shopping_district", "history_site_castle"], lat: 35.1542, lon: 140.3155,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: ["wednesday"],
    external_urls: {}, tags: ["katsuura_asaichi", "1591", "434_years", "national_top3_asaichi"], source: "manual",
  },
  {
    slug: "ohara-asaichi-isumi",
    category: "food", sub_type: "chiba_kyodo",
    title_zh: "大原漁港朝市+いすみ朝市(いすみ市大原・1700 年代から大原漁港朝市 300+ 年+ 毎月第 1 日曜開催+ 大原港新鮮魚直売+ R1 衣 大原はだか祭観光連動・無料散策)",
    title_ja: "大原朝市", romaji: "Ōhara Asaichi",
    summary_zh: "**大原漁港朝市+いすみ朝市は 1700 年代から 300+ 年・毎月第 1 日曜・大原港新鮮魚直売**(いすみ大原)。R1 衣 大原はだか祭連動、無料。",
    content_md: "- 立地:**いすみ市大原**\n- 起源:**1700 年代から 300+ 年**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "いすみ市", lg_code: "12238",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 35.2519, lon: 140.3886,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["ohara_asaichi"], source: "manual",
  },
  {
    slug: "boso-peanut-miso",
    category: "food", sub_type: "chiba_meika",
    title_zh: "房総ピーナツ味噌+ピーナツ甘露煮(全県+八街+富里・R1 食 八街落花生派生・落花生味噌絡め煮+ 砂糖+ 醤油+ 味噌+ 水飴・房総ご飯のお供代表+ 道の駅+全国百貨店流通+ 1 瓶 ¥350-1,500)",
    title_ja: "房総ピーナツ味噌", romaji: "Bōsō Peanut Miso",
    summary_zh: "**房総ピーナツ味噌+ピーナツ甘露煮は R1 食 八街落花生派生・落花生味噌絡め煮+砂糖+醤油+味噌+水飴**(全県+八街+富里・**ご飯のお供代表**)。道の駅+百貨店、¥350-1,500/瓶。",
    content_md: "- 立地:**千葉県全域 + 八街市 + 富里市**\n- 関連:**R1 食 八街落花生派生**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "八街市", lg_code: "12230",
    area_types: ["restaurant_traditional", "shopping_district"], lat: 35.6614, lon: 140.3194,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["boso_peanut_miso"], source: "manual",
  },

  // 住 4
  {
    slug: "yoro-keikoku-onsen",
    category: "lodging", sub_type: "chiba_minami_boso",
    title_zh: "養老渓谷温泉郷(市原市朝生原+大多喜町・1934 県立公園内 91+ 年+ 房総中部里山温泉郷+ 11 月下旬-12 月上旬関東紅葉最終地+ 旅館 12+ 軒+ R1 育 養老渓谷+R1 行 小湊鉄道+いすみ鉄道沿線・¥9,500-22,000/泊)",
    title_ja: "養老渓谷温泉", romaji: "Yōrō Keikoku Onsen",
    summary_zh: "**養老渓谷温泉郷は 1934 県立公園内 91+ 年・房総中部里山温泉郷・11 月下旬-12 月上旬関東紅葉最終地・旅館 12+ 軒**(市原+大多喜)。R1 育 養老+R1 行 小湊鉄道連動、¥9,500-22,000/泊。",
    content_md: "- 立地:**市原市朝生原 + 大多喜町**\n- 起源:**1934 県立公園内 91+ 年**\n- 規模:**温泉旅館 12+ 軒**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "市原市", lg_code: "12219",
    area_types: ["onsen_natural", "accommodation_ryokan", "nature_park"], lat: 35.2853, lon: 140.1606,
    season_start: "2026-11-20", season_end: "2026-12-10", event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["yoro_onsen"], source: "manual",
  },
  {
    slug: "ichinomiya-surf-hotels",
    category: "lodging", sub_type: "chiba_minami_boso",
    title_zh: "一宮サーフィン町ホテル(長生郡一宮町・2020 五輪サーフィン会場 R1 衣 派生・サーファーズインホテル 8+ 軒+ 釣ヶ崎海岸ビーチ前+ R1 育 玉前神社上総一宮徒歩 5 分+ R1 食 太巻き祭り寿司連動・¥9,500-22,000/泊)",
    title_ja: "一宮サーフホテル", romaji: "Ichinomiya Surf Hotel",
    summary_zh: "**一宮サーフィン町ホテルは 2020 五輪サーフィン会場 R1 衣派生・サーファーズイン 8+ 軒・釣ヶ崎海岸ビーチ前**(一宮)。R1 育 玉前神社+R1 食 太巻き連動、¥9,500-22,000/泊。",
    content_md: "- 立地:**長生郡一宮町**\n- 関連:**R1 衣 房総サーフ + R1 育 玉前神社派生**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: "長生郡", municipality_ja: "一宮町", lg_code: "12421",
    area_types: ["accommodation_hotel", "beach_coast"], lat: 35.3739, lon: 140.3633,
    season_start: "2026-06-01", season_end: "2026-09-30", event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["ichinomiya_surf"], source: "manual",
  },
  {
    slug: "kameyama-lake-resort",
    category: "lodging", sub_type: "chiba_kisarazu_aqua",
    title_zh: "上総亀山ダム+ 亀山湖畔リゾート(君津市・1980 完成亀山ダム 45+ 年+ 県内最大級ダム湖+ 関東紅葉名所+ ボート遊覧+ JR 久留里線終点+ 湖畔リゾート 4+ 軒+ R1 育 久留里城観光連動・¥9,500-18,000/泊)",
    title_ja: "亀山湖畔リゾート", romaji: "Kameyama Lake",
    summary_zh: "**上総亀山ダム+亀山湖畔リゾートは 1980 完成 45+ 年・県内最大級ダム湖・関東紅葉名所+JR 久留里線終点**(君津・**湖畔リゾート 4+ 軒**)。R1 育 久留里城連動、¥9,500-18,000/泊。",
    content_md: "- 立地:**君津市**\n- 起源:**1980 完成亀山ダム 45+ 年**\n- 認定:**県内最大級ダム湖 + 関東紅葉名所**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "君津市", lg_code: "12225",
    area_types: ["accommodation_ryokan", "nature_park"], lat: 35.2492, lon: 140.0606,
    season_start: "2026-11-01", season_end: "2026-12-10", event_start: null, event_end: null,
    price_tier: 3, booking_window_days: 30, closed_days: [],
    external_urls: {}, tags: ["kameyama_lake", "1980"], source: "manual",
  },
  {
    slug: "sakura-business-hotels",
    category: "lodging", sub_type: "chiba_chiba_city",
    title_zh: "佐倉駅前ビジネスホテル群(佐倉市・JR 佐倉駅前+ 国立歴史民俗博物館徒歩 15 分+ 京成佐倉駅前+ アパ・東横イン・ヴィアイン等中堅チェーン 5+ 軒+ R1 育 佐倉城+R1 衣 佐倉武家屋敷連動・¥6,500-12,000/泊)",
    title_ja: "佐倉駅前ビジネス", romaji: "Sakura Business",
    summary_zh: "**佐倉駅前ビジネスホテル群は JR 佐倉駅前+国立歴史民俗博物館徒歩 15 分・中堅チェーン 5+ 軒**(佐倉)。R1 育 佐倉城+R1 衣 武家屋敷連動、¥6,500-12,000/泊。",
    content_md: "- 立地:**佐倉市駅前**\n- 規模:**中堅ビジネスチェーン 5+ 軒**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "佐倉市", lg_code: "12212",
    area_types: ["accommodation_hotel"], lat: 35.7236, lon: 140.2233,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: 14, closed_days: [],
    external_urls: {}, tags: ["sakura_business"], source: "manual",
  },

  // 衣 3
  {
    slug: "isumi-jimon-aloha",
    category: "fashion", sub_type: "chiba_resort",
    title_zh: "夷隅地紋アロハ+ 房総サマーアパレル(いすみ市+大多喜+勝浦・房総中部夷隅郡 古来織紋様+ 1990 年代以降サーフリゾート派生アロハシャツ+ パームツリー柄+ R1 衣 大原はだか祭+R1 楽 鴨川シーワールド連動・¥3,500-12,000)",
    title_ja: "夷隅地紋アロハ", romaji: "Isumi Aloha",
    summary_zh: "**夷隅地紋アロハ+房総サマーアパレルは古来織紋様+1990 年代以降サーフリゾート派生**(いすみ+大多喜+勝浦・**パームツリー柄**)。R1 衣 大原+R1 楽 シーワールド連動、¥3,500-12,000。",
    content_md: "- 立地:**いすみ市 + 大多喜町 + 勝浦市**\n- 関連:**R1 衣 房総サーフ派生**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "いすみ市", lg_code: "12238",
    area_types: ["shopping_district"], lat: 35.2519, lon: 140.3886,
    season_start: "2026-06-01", season_end: "2026-09-30", event_start: null, event_end: null,
    price_tier: 3, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["isumi_aloha"], source: "manual",
  },
  {
    slug: "otaki-castle-samurai",
    category: "fashion", sub_type: "chiba_samurai",
    title_zh: "大多喜城下武士装束+ 本多忠勝陣羽織(夷隅郡大多喜町・本多忠勝 1601 大多喜藩入封 424+ 年+ 大多喜城下武家屋敷町並み+ R1 育 大多喜城+本多忠勝記念館 1975+ 国登録有形文化財武家屋敷 2+ R1 行 いすみ鉄道大多喜駅徒歩 10 分・観覧 ¥200)",
    title_ja: "大多喜武士装束", romaji: "Ōtaki Samurai",
    summary_zh: "**大多喜城下武士装束+本多忠勝陣羽織は 1601 本多忠勝大多喜藩入封 424+ 年・武家屋敷町並み**(大多喜・**城+記念館 1975+国登録 2 棟**)。R1 行 いすみ鉄道徒歩 10 分、¥200。",
    content_md: "- 立地:**夷隅郡大多喜町**\n- 起源:**1601 本多忠勝大多喜藩入封 424+ 年**\n- 認定:**大多喜城 + 本多忠勝記念館 1975 + 国登録有形文化財武家屋敷 2 棟**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: "夷隅郡", municipality_ja: "大多喜町", lg_code: "12441",
    area_types: ["history_site_castle", "museum_art"], lat: 35.2958, lon: 140.2453,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["otaki_samurai", "honda_tadakatsu", "1601"], source: "manual",
  },
  {
    slug: "kamagaya-asaori",
    category: "fashion", sub_type: "chiba_asaori",
    title_zh: "鎌ケ谷+下総麻織+紅花染め(鎌ケ谷市+柏+我孫子+流山・古代下総国麻織伝統 1000+ 年+ 1990 年代以降復興運動・染色工房 5+ 軒+ R1 衣 流山みりん職人着+R1 食 千葉なし観光連動・¥12,000-45,000)",
    title_ja: "下総麻織", romaji: "Shimōsa Asaori",
    summary_zh: "**鎌ケ谷+下総麻織+紅花染めは古代下総国麻織伝統 1000+ 年・1990 年代以降復興運動・染色工房 5+ 軒**(鎌ケ谷+柏+我孫子+流山)。R1 衣 みりん+R1 食 千葉なし連動、¥12,000-45,000。",
    content_md: "- 立地:**鎌ケ谷市 + 柏市 + 我孫子市 + 流山市**\n- 起源:**古代下総国麻織伝統 1000+ 年 + 1990 年代以降復興運動**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "鎌ケ谷市", lg_code: "12224",
    area_types: ["industrial_heritage"], lat: 35.7733, lon: 139.9919,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 5, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shimōsa_asaori"], source: "manual",
  },

  // 育 3
  {
    slug: "chiba-pref-museum-art",
    category: "culture", sub_type: "chiba_museum",
    title_zh: "千葉県立美術館(千葉市中央区・1974 開館 51+ 年+ 千葉港隣接+ 千葉県唯一の県立美術館+ 浅井忠+石井林響+鴨居玲 千葉ゆかり画家+ 近代日本油彩+西洋洋画コレクション・観覧 ¥300・JR 千葉港駅徒歩 10 分)",
    title_ja: "千葉県立美術館", romaji: "Chiba Pref Art Museum",
    summary_zh: "**千葉県立美術館は 1974 開館 51+ 年・千葉港隣接・千葉県唯一の県立美術館・浅井忠+石井林響+鴨居玲 千葉ゆかり画家**(千葉中央)。観覧 ¥300。",
    content_md: "- 立地:**千葉市中央区**\n- 起源:**1974 開館 51+ 年**\n- 認定:**千葉県唯一の県立美術館**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["museum_art"], lat: 35.5994, lon: 140.1064,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["chiba_pref_art_1974"], source: "manual",
  },
  {
    slug: "chiba-city-museum-1995",
    category: "culture", sub_type: "chiba_museum",
    title_zh: "千葉市美術館(千葉市中央区中央・1995 開館 30+ 年+ 旧川崎銀行千葉支店(国登録有形文化財)再生美術館建築+ 浮世絵+ 江戸絵画 + 現代アートコレクション・観覧 ¥300・JR 千葉駅徒歩 15 分・京成千葉中央駅徒歩 5 分)",
    title_ja: "千葉市美術館", romaji: "Chiba City Art",
    summary_zh: "**千葉市美術館は 1995 開館 30+ 年・旧川崎銀行千葉支店(国登録有形文化財)再生美術館建築・浮世絵+江戸+現代アート**(千葉中央)。観覧 ¥300。",
    content_md: "- 立地:**千葉市中央区**\n- 起源:**1995 開館 30+ 年**\n- 認定:**旧川崎銀行千葉支店 国登録有形文化財再生**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "千葉市", lg_code: "12100",
    area_types: ["museum_art", "history_site_castle"], lat: 35.6131, lon: 140.1233,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["chiba_city_art_1995"], source: "manual",
  },
  {
    slug: "otaki-castle-1975",
    category: "culture", sub_type: "chiba_castle",
    title_zh: "大多喜城+本多忠勝記念館(夷隅郡大多喜町・1521 真里谷氏築城 504+ 年+ 1601 本多忠勝大多喜藩 10 万石入封・1975 復元天守 千葉県立中央博物館大多喜分館 50+ 年+ 観覧 ¥200・国登録有形文化財武家屋敷)",
    title_ja: "大多喜城", romaji: "Ōtaki Castle",
    summary_zh: "**大多喜城+本多忠勝記念館は 1521 真里谷氏築城 504+ 年・1601 本多忠勝大多喜藩 10 万石入封・1975 復元天守 50+ 年**(大多喜・**千葉県中央博物館大多喜分館**)。¥200。",
    content_md: "- 立地:**夷隅郡大多喜町**\n- 起源:**1521 真里谷氏築城 504+ 年 + 1601 本多忠勝入封**\n- 認定:**1975 復元天守 = 千葉県立中央博物館大多喜分館**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: "夷隅郡", municipality_ja: "大多喜町", lg_code: "12441",
    area_types: ["history_site_castle", "museum_art"], lat: 35.2958, lon: 140.2453,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: ["monday"],
    external_urls: {}, tags: ["otaki_castle_1975"], source: "manual",
  },

  // 楽 3
  {
    slug: "iioka-gyobu-misaki",
    category: "entertainment", sub_type: "chiba_beach",
    title_zh: "飯岡刑部岬展望台(旭市飯岡・関東屈指夕日名所「日本の夕日 100 選」候補+ 標高 60m 屛風ヶ浦展望+ 太平洋 240 度パノラマ+ 国指定名勝候補・上永井公園+ JR 飯岡駅徒歩 30 分・無料展望)",
    title_ja: "飯岡刑部岬", romaji: "Iioka Gyobu Misaki",
    summary_zh: "**飯岡刑部岬展望台は関東屈指夕日名所・標高 60m 屛風ヶ浦展望・太平洋 240 度パノラマ・国指定名勝候補**(旭飯岡)。JR 飯岡駅徒歩 30 分、無料。",
    content_md: "- 立地:**旭市飯岡**\n- 認定:**関東屈指夕日名所 + 国指定名勝候補(屏風ヶ浦)**\n- 規模:**標高 60m + 太平洋 240 度パノラマ**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "旭市", lg_code: "12215",
    area_types: ["nature_park", "beach_coast"], lat: 35.6889, lon: 140.7269,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["iioka_gyobu", "byōbu_ga_ura"], source: "manual",
  },
  {
    slug: "kameyama-lake-park",
    category: "entertainment", sub_type: "chiba_park",
    title_zh: "亀山湖+亀山ダム湖畔公園(君津市・1980 完成亀山ダム 45+ 年+ 県内最大級ダム湖+ 関東紅葉名所(11 月下旬-12 月上旬)+ ボート遊覧+ サイクリング+ JR 久留里線終点・無料散策・R1 楽 養老渓谷徒歩 30 分連動)",
    title_ja: "亀山湖", romaji: "Kameyama Lake",
    summary_zh: "**亀山湖+亀山ダム湖畔公園は 1980 完成 45+ 年・県内最大級ダム湖・関東紅葉名所(11 月下旬-12 月上旬)・ボート+サイクリング**(君津)。JR 久留里線終点、無料。",
    content_md: "- 立地:**君津市**\n- 起源:**1980 完成亀山ダム 45+ 年**\n- 認定:**県内最大級ダム湖 + 関東紅葉名所**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "君津市", lg_code: "12225",
    area_types: ["nature_park"], lat: 35.2492, lon: 140.0606,
    season_start: "2026-11-20", season_end: "2026-12-10", event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["kameyama_lake_park"], source: "manual",
  },
  {
    slug: "inba-tega-natural-park",
    category: "entertainment", sub_type: "chiba_park",
    title_zh: "千葉県立印旛手賀自然公園(印西市+佐倉+我孫子+柏・1969 県立公園指定 56+ 年+ 印旛沼+手賀沼の 2 大水郷+ サイクリング+ 釣り+ ボート+ R1 食 印旛沼水産+R1 育 佐倉城観光連動・無料)",
    title_ja: "印旛手賀自然公園", romaji: "Inba Tega Natural Park",
    summary_zh: "**千葉県立印旛手賀自然公園は 1969 県立公園指定 56+ 年・印旛沼+手賀沼の 2 大水郷・サイクリング+釣り+ボート**(印西+佐倉+我孫子+柏)。R1 食 印旛沼+R1 育 佐倉城連動、無料。",
    content_md: "- 立地:**印西市 + 佐倉市 + 我孫子市 + 柏市**\n- 起源:**1969 県立公園指定 56+ 年**\n- 規模:**印旛沼 + 手賀沼の 2 大水郷**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "印西市", lg_code: "12231",
    area_types: ["nature_park"], lat: 35.8311, lon: 140.1444,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 0, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["inba_tega"], source: "manual",
  },

  // 行 2
  {
    slug: "hokuso-railway-1979",
    category: "transport", sub_type: "chiba_skyaccess",
    title_zh: "北総鉄道(印西市+鎌ケ谷+船橋・1979 開業 46+ 年+ 京成高砂駅-印旛日本医大駅 32.3km+ 京成電鉄連携・R1 行 成田スカイアクセス線 2010 共同運営+ 京成本線+京成成田スカイアクセス線+ ¥710-1,250/片道・国際旅行者 R1 行 NEX 並ぶ成田アクセス選択肢)",
    title_ja: "北総鉄道", romaji: "Hokusō Tetsudō",
    summary_zh: "**北総鉄道は 1979 開業 46+ 年・京成高砂-印旛日本医大 32.3km・成田スカイアクセス 2010 共同運営**(印西+鎌ケ谷+船橋)。¥710-1,250/片道、国際旅行者代表。",
    content_md: "- 立地:**印西市 + 鎌ケ谷市 + 船橋市**\n- 起源:**1979 開業 46+ 年**\n- 規模:**京成高砂駅-印旛日本医大駅 32.3km**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "印西市", lg_code: "12231",
    area_types: ["transport_hub"], lat: 35.8311, lon: 140.1444,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 2, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["hokuso_tetsudō", "1979"], source: "manual",
  },
  {
    slug: "shin-keisei-1947",
    category: "transport", sub_type: "chiba_keisei",
    title_zh: "新京成電鉄(松戸市+船橋+鎌ケ谷+習志野・1947 京成電鉄子会社開業 78+ 年+ 京成津田沼駅-松戸駅 26.5km+ 京成本線連携・北部千葉県主要通勤線+ 1 日 30 万人乗降+ ¥210-330/片道)",
    title_ja: "新京成電鉄", romaji: "Shin-Keisei",
    summary_zh: "**新京成電鉄は 1947 京成子会社開業 78+ 年・京成津田沼-松戸 26.5km・北部千葉県主要通勤線・1 日 30 万人乗降**(松戸+船橋+鎌ケ谷+習志野)。¥210-330/片道。",
    content_md: "- 立地:**松戸市 + 船橋市 + 鎌ケ谷市 + 習志野市**\n- 起源:**1947 京成電鉄子会社開業 78+ 年**\n- 規模:**26.5km + 1 日 30 万人乗降**",
    region: "kanto", prefecture_ja: "千葉県", gun_ja: null, municipality_ja: "松戸市", lg_code: "12207",
    area_types: ["transport_hub"], lat: 35.7842, lon: 139.9019,
    season_start: null, season_end: null, event_start: null, event_end: null,
    price_tier: 1, booking_window_days: null, closed_days: [],
    external_urls: {}, tags: ["shin_keisei", "1947"], source: "manual",
  },
];

seedMain(rows, "chiba-r2");
